### ISSUE TITLE
期待

### ISSUE THREAD

**Issue by CK110** [NG-ZORRO/ng-zorro-antd#1]
期待很久了，虽然没有源码，看了一下tabs的示例，动态增加tab标签，也只是数据源的增加，有实现能够动态创建一个tab，tab内容是一个其他的组件页面？是不是这种比较难实现？

**Comment by cipchk** [comment]
在哪有示例URL？

**Comment by CK110** [comment]
@cipchk https://ng-zorro.github.io/#/docs/angular/introduce

**Comment by stbui** [comment]
.

**Comment by ShaofeiZi** [comment]
排队

**Comment by shiyu123** [comment]
排队等候~

**Comment by 543802360** [comment]
排队+1

**Comment by eminoda** [comment]
刘明
