### ISSUE TITLE
modal弹窗里再一嵌套弹一个弹窗

### ISSUE THREAD

**Issue by luohong123** [NG-ZORRO/ng-zorro-antd#1000]
## What problem does this feature solve?

弹窗里面是一个列表或者表单，点击列表或者表单的操作按钮，再次弹出一个弹窗
The modal open a list or form ,my modal's list or form has button,I wan't to click button to open another modal
## What does the proposed API look like?

有交互的代码示例
I hope example code

**Comment by vthinkxie** [comment]
the same method as the first modal

**Comment by yangpengfei369** [comment]
@luohong123 Encounter many Modal window, manually set nzZIndex parameters, the bottom nzZIndex Modal parameters less than the front nzZIndex parameters
