### ISSUE TITLE
datapick 等位bug

### ISSUE THREAD

**Issue by vickmeng** [NG-ZORRO/ng-zorro-antd#1006]
## Version

0.6.13

## Environment

0.6.3

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

## Steps to reproduce

https://ng.ant.design/#/components/date-picker 
nz-rangepicker 范围选择定位位置有问题chrome59.0.3071.115

## What is expected?

修复定位位置

## What is actually happening?

修复定位位置在浏览器左侧

**Comment by vickmeng** [comment]
![image](https://user-images.githubusercontent.com/19486247/35714525-242b1b78-0808-11e8-8c24-a20b480635d4.png)

**Comment by HsuanXyz** [comment]
@vickmeng 除了 `Chrome v59.0.3071.115` 还有什么其他的复现条件吗？我现在身边暂时没有其他设备用于复现此问题。可以的话请提供更详细的环境信息用于跟踪此问题，谢谢。

**Comment by vickmeng** [comment]
@HsuanXyz chrome58.0.3029.110的浏览器也出现了这个问题，目前没发现其他干扰条件。回退到0.612的zorro就没有这个问题

**Comment by fanshuai** [comment]
<img width="1418" alt="2018-02-06 16 10 27" src="https://user-images.githubusercontent.com/1005487/35848318-a6513792-0b58-11e8-8173-eef36ebaa3c6.png">

https://ng.ant.design/#/components/date-picker
nz-rangepicker 组件无法选择月份。

**Comment by yy7054wyq5** [comment]
In 0.6.12, i have same problem. I use custom dateTimeRanger demo.
