### ISSUE TITLE
[BUG] `nz-col` 当指定 `nzOffset` 时，响应式下会导致无法缩进

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#101]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

![123](https://user-images.githubusercontent.com/2987467/29494064-3608c3dc-85d5-11e7-871f-c2417489f59b.gif)

```html
<div nz-form-item nz-row>
    <div nz-form-control nz-col [nzSpan]="14" [nzXs]="24" [nzOffset]="6">
        <button nz-button [nzType]="'primary'" [nzSize]="'large'">Login</button>
        <button nz-button [nzSize]="'large'">Register</button>
    </div>
</div>
```

`nzXs` 即屏幕小于 768px 时，应该同 username & password 一样靠向最左边，但受了 `nzOffet` 影响了。

React 版本中，`[nzXs]` 支持一个复合对象，类似：`[nzXs]="{ span: 24, offset: 0 }"`。

**Comment by vthinkxie** [comment]
not supported yet. to be discuss next version.
