### ISSUE TITLE
The nzSelectedIndex attribute of the tabs component

### ISSUE THREAD

**Issue by micro-bean** [NG-ZORRO/ng-zorro-antd#1010]
## Version

0.6.13

## Environment

SystemVersion：windows7，Browser：Chrome

## Steps to reproduce

  tabs = [{name:'test1'}];
  tabsSelectedIndex: number=0;

  navItemClick(name){

    var index=this.tabs.findIndex((value,index,arr)=>{
      return value.name==name? true : false;
    });
    
    if(index<0){
      index=this.tabs.push({name:name, close:true, component:component});
      index--;
    }
    this.tabsSelectedIndex=index;
  }

  closeTab(tab) {
    this.tabs.splice(this.tabs.indexOf(tab), 1);
  }

## What is expected?

Turn off the open selected state and specify a tab

## What is actually happening?

First open a few and turn off the first one and open the first one, but the second is the last one.

**Comment by vthinkxie** [comment]
Hello @micro-bean , your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper]( http://ng.ant.design/issue-helper/#/new-issue ) to create an issue, thank you!
