### ISSUE TITLE
Can not use nzPopover inside a nzTable

### ISSUE THREAD

**Issue by liuyangc3** [NG-ZORRO/ng-zorro-antd#1012]
## Version

0.6.13

## Environment

stackblitz Chrome

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-test?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-test?file=app%2Fapp.component.html)

## Steps to reproduce

see link

## What is expected?

works

## What is actually happening?

```
ERROR Error: StaticInjectorError[NgZone]: 
  StaticInjectorError[NgZone]: 
    NullInjectorError: No provider for NgZone!
...
```

**Comment by vthinkxie** [comment]
@wilsoncook

**Comment by wilsoncook** [comment]
It seems a bug from @angular/cdk, upgrade to @angular/cdk@5.1.1 to resolve this problem.

Check out this: https://stackblitz.com/edit/ng-zorro-antd-test-xcsnrf

**Comment by wilsoncook** [comment]
@liuyangc3 the angular/cdk is a peer denpendence by ng-zorro-antd (currently matching version with `^5.0.0`), so just reinstall angular/cdk to the latest is fine.
