### ISSUE TITLE
add or delete Table data, but  not change by nzDataSource

### ISSUE THREAD

**Issue by lishaoh** [NG-ZORRO/ng-zorro-antd#1017]
## What problem does this feature solve?

<nz-table #table1 [nzDataSource]="data?.auditTask.auditItem || []" [nzPageSize]="10" nzShowSizeChanger nzPageSizeChange [nzIsPageIndexReset]="false">
              <thead nz-thead>
              <tr>
                <th nz-th><span>编号</span></th>
                <th nz-th><span>操作</span></th>
              </tr>
              </thead>
              <tbody nz-tbody>
              <tr nz-tbody-tr *ngFor="let data of table1.data;">
                <td nz-td>{{data.id}}</td>
                <td nz-td>
                  <button class="button-lightRed" (click)="delTasks(data.id)">删除</button>
                </td>
              </tr>
              </tbody>
            </nz-table>

--------------------
.ts

 delTasks(id) {
    const pos = this.data.auditTask.auditItem.findIndex(item => item.id == id);
    this.data.auditTask.auditItem.splice(pos, 1);
  }

this table no change

## What does the proposed API look like?

add or delete Array for nzDataSource, data must change

**Comment by vthinkxie** [comment]
duplicated #805

**Comment by lishaoh** [comment]
@vthinkxie thank you
