### ISSUE TITLE
useless scroll bar

### ISSUE THREAD

**Issue by vickmeng** [NG-ZORRO/ng-zorro-antd#1018]
## Version

0.6.14

## Environment

chrome 59

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

## Steps to reproduce

https://ng.ant.design/#/components/table fixedhead

## What is expected?

固定表头怎么多了个多余的滚动条呀 

## What is actually happening?

拿掉多余的滚动条

**Comment by vthinkxie** [comment]
read the doc and release note carefully

**Comment by vickmeng** [comment]
![image](https://user-images.githubusercontent.com/19486247/35795847-8afd13f8-0a95-11e8-8e90-360450b1c572.png)

**Comment by vthinkxie** [comment]
read the doc and config **CAREFULLY** please.
![2](https://user-images.githubusercontent.com/1506722/35796330-259b3c4a-0a97-11e8-84dc-2d60d356dab4.png)
![1](https://user-images.githubusercontent.com/1506722/35796331-25ca7d5c-0a97-11e8-908d-74218aa46552.png)
![default](https://user-images.githubusercontent.com/1506722/35796332-25fa2dfe-0a97-11e8-9218-6099965d0837.png)

**Comment by vickmeng** [comment]
不是我没读，我的截图是你们官网的示例呀。。。看我画的红圈
