### ISSUE TITLE
ngModel is not working in nz-rate

### ISSUE THREAD

**Issue by lishaoh** [NG-ZORRO/ng-zorro-antd#1022]
## What problem does this feature solve?

ngModel 绑定 nz-rate显示个数

## What does the proposed API look like?
```
 <div  *ngFor="let item of rate; let j = index;">
        <p class="m-b-xs">{{item.label}}</p>{{item.value}}
        <nz-rate [(ngModel)]="item.value"></nz-rate>
      </div>
```

---ts

this.rate = [{
        label: '服务质量',
        value: 4},{
        label: '服务时效',
        value: 2},{
        label: '服务态度',
        value:3},{
        label: '综合评价',
        value:1}
    ];

but show five stars, ngModel not update

**Comment by vthinkxie** [comment]
you want submit a bug or feature request?
