### ISSUE TITLE
how tow customize nz-collapse head？

### ISSUE THREAD

**Issue by zhangkang1521** [NG-ZORRO/ng-zorro-antd#1023]
## What problem does this feature solve?

[collapse-title] type is ng-content, can provide a demo?

## What does the proposed API look like?

customize nz-collapse head

**Comment by vthinkxie** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/9a5621efa111f333a74d2edfc953506de4363205/src/components/collapse/nz-collapse.component.ts#L27
