### ISSUE TITLE
Dropdown content spillover after fixed outside width

### ISSUE THREAD

**Issue by Elliottssu** [NG-ZORRO/ng-zorro-antd#1026]
## Version

0.6.8

## Environment

angular 5.1.1

## Reproduction link

[http://plnkr.co/edit/ry8khB2Q8qHxMpAydqYi?p=preview](http://plnkr.co/edit/ry8khB2Q8qHxMpAydqYi?p=preview)

## Steps to reproduce

I put zorro dropdown in my angular project, and it doesn't work when i try to fixed outside width. i mean that the content of the li is too long to fix the width of the ul, but I have added the attributes of the `word-break:break-all;` at li, the content is still the overflow.

angular: V5.1.1
code:
*style part*
```
.ant-dropdown-menu {
      width:300px!important
    }
    .ant-dropdown-menu-item {
      word-break:break-all;
    }
```

*ts part*
```
 <nz-dropdown [nzTrigger]="'click'">
      <a class="ant-dropdown-link" nz-dropdown>
        click me <i class="anticon anticon-down"></i>
      </a>
      <ul nz-menu>
        <li nz-menu-item>
          <a target="_blank" rel="noopener noreferrer" href="http://www.alipay.com/">1st menust menust menust menust menust menust menust menust menu item</a>
        </li>
        <li nz-menu-item>
          <a target="_blank" rel="noopener noreferrer" href="http://www.alipay.com/">2nd menu item</a>
        </li>
        <li nz-menu-item>
          <a target="_blank" rel="noopener noreferrer" href="http://www.alipay.com/">3rd menu item</a>
        </li>
      </ul>
    </nz-dropdown>
```

## What is expected?

The content is folding line

## What is actually happening?

![image.png](http://upload-images.jianshu.io/upload_images/3502567-f04379d58c7c8185.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by vthinkxie** [comment]
please do not ask basic css problem here.
and here is the answer.
https://stackblitz.com/edit/ng-zorro-antd-setup-p9xpdv?file=app%2Fapp.component.css
```css
.ant-dropdown-menu {
  width:300px !important
}
.ant-dropdown-menu-item {
  word-break: break-all;
  white-space: normal;
}
```
