### ISSUE TITLE
[BUG] `nz-input` width `nzDisabled`

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#103]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

`nz-input` is ignored `.ant-input-disabled` class when set `[nzDisabled]="true"`

## Expected behavior

`.ant-input-disabled` should not be ignored.

```html
<nz-input [nzDisabled]="true" [nzSize]="'large'"></nz-input>
```

this is i get in [0.5.0-rc.2] version:

![now](https://user-images.githubusercontent.com/2987467/29495686-b74d63b4-85f6-11e7-8a50-e6cb0afc2920.png)

the text should be in disabled color i belive, just like:

![aa](https://user-images.githubusercontent.com/2987467/29495698-e053fe26-85f6-11e7-8335-28b3c38a6b5d.png)

**Comment by vthinkxie** [comment]
style bug confirm, fix next version, thanks.
