### ISSUE TITLE
table repeat request

### ISSUE THREAD

**Issue by lyc152** [NG-ZORRO/ng-zorro-antd#1030]
## Version

0.6.14

## Environment

0.6.14

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/showcase/nz-demo-table/](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/showcase/nz-demo-table/)

## Steps to reproduce

当我把表格页面切换到非第一页时，我现在做表格筛选的操作，这时表格会回到第一页，但是向后台发了两次请求

## What is expected?

只向后台发一次请求

## What is actually happening?

向后台多发了一次请求

**Comment by vthinkxie** [comment]
please provide minimal reproduction online demo.
