### ISSUE TITLE
nz-select style incorrect inside a form

### ISSUE THREAD

**Issue by liuyangc3** [NG-ZORRO/ng-zorro-antd#1032]
## Version

0.6.13

## Environment

chrome

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-test-manegb?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-test-manegb?file=app%2Fapp.component.html)

## Steps to reproduce

https://stackblitz.com/edit/ng-zorro-antd-test-manegb?file=app%2Fapp.component.html

## What is expected?

nzCompact work

## What is actually happening?

nzCompact did not work

**Comment by vthinkxie** [comment]
why are you only use `nzCompact` in a single select component? 
`nzCompact` is not used like this.

**Comment by liuyangc3** [comment]
I took `nz-select` code  from website demo, add it in a form group which also from demo

BTW: nzId also can not be used inside form
```
<label for="test">test</label >
<nz-select formControlName="repoType" [nzId]="'test'">
...
```

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-test-ll7pgg?file=app/app.component.html
https://ng.ant.design/#/components/form ->注册新用户->Phone Number
