### ISSUE TITLE
Nz-popconfirm can add disabled properties？

### ISSUE THREAD

**Issue by Zhouuuuuuuuu** [NG-ZORRO/ng-zorro-antd#1036]
## What problem does this feature solve?

For example, the data in the table has a delete button (using nz-popconfirm), but some conditions need to be met to delete it.Another way is to hide the button, but the visual effects are somewhat unfriendly.

![qq 20180208115606](https://user-images.githubusercontent.com/29364579/35954878-19e0139e-0cc7-11e8-8dd1-8a886bd08389.png)

## What does the proposed API look like?

Add nzDisabled API

**Comment by vthinkxie** [comment]
pointer-events: none; will help you
https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
