### ISSUE TITLE
How to dynamic  disabled time? 

### ISSUE THREAD

**Issue by yy7054wyq5** [NG-ZORRO/ng-zorro-antd#1037]
## What problem does this feature solve?

Dynamic setting disabled time. Build a time ranger.

## What does the proposed API look like?

flow existing API

**Comment by vthinkxie** [comment]
please read the doc carefully, If you have read it carefully, you won't ask a question like this.
That is why the bot say “不要期待我们单方面地为你服务”
I think the demo in our doc site is clear enough to tell you how to dynamic set disabled time.
```typecript
import { Component } from '@angular/core';

@Component({
  selector: 'nz-demo-timepicker-disabled-options',
  template: `
    <nz-timepicker [(ngModel)]="_date" [nzDisabledHours]="disabledHours" [nzDisabledMinutes]="disabledMinutes"></nz-timepicker>`,
  styles  : []
})
export class NzDemoTimePickerDisabledOptionsComponent {
  _date = null;
  newArray = (start, end) => {
    const result = [];
    for (let i = start; i < end; i++) {
      result.push(i);
    }
    return result;
  };
  disabledHours = () => {
    const hours = this.newArray(0, 60);
    hours.splice(20, 4);
    return hours;
  };

  disabledMinutes = (h) => {
    if (h === 20) {
      return this.newArray(0, 31);
    } else if (h === 23) {
      return this.newArray(30, 60);
    }
    return [];
  };
}

```

**Comment by yy7054wyq5** [comment]
I have try. But it did't work.So i ask question in this place.
I use two time pickers. And put them in a component. I want to them can linkage.
```html
<nz-timepicker style="width: 140px;" [(ngModel)]="startTime" [nzPlaceHolder]="placeHolders[0] | translate" [nzDisabledHours]="disabeldStartHours"
  (ngModelChange)="startTime=$event;timeChange(startTime,endTime)"></nz-timepicker>

<nz-timepicker style="width: 140px;" [(ngModel)]="endTime" [nzPlaceHolder]="placeHolders[1] | translate" [nzDisabledHours]="disabeldEndHours"
  (ngModelChange)="endTime=$event;timeChange(startTime,endTime)"></nz-timepicker>
```

```javascript
  get _disabeldStartHours() {
    // console.log(this.endTime);
    const endHour = this._backHMS(this.endTime).hours;
    // console.log(endHour);
    return endHour ? newArray(endHour, 24) : [];
  }

  disabeldStartHours = (): Array<number> => {

    return this._disabeldStartHours;
  }
```
How it work?

**Comment by vthinkxie** [comment]
@yy7054wyq5 
If it does not work as intend, you can just submit a bug report with stackblitz.
Try to think the way of other, If someone come here and say I want a feature but I don't want to provide any description, or I want report a bug but I am lazy to provide any reproduction link.
What do you think about it?

**Comment by vthinkxie** [comment]
And here is how the others describe their feature request https://github.com/NG-ZORRO/ng-zorro-antd/issues/320

**Comment by vthinkxie** [comment]
Here is another article for you https://github.com/seajs/seajs/issues/545, hope it can help you to learn how to get help from open source project.

**Comment by yy7054wyq5** [comment]
ok. I will provide a link. 
其实后面我回复的重点是想说，机器人回复的英文和中文，意思差别很大。为什么中文就得说“不要期待我们单方面地为你服务”。而英文里面一个字都不这样提的？
这是什么道理？

**Comment by vthinkxie** [comment]
Whether you admit it or not, look at the closed and invalid issues, you will know why.

**Comment by yy7054wyq5** [comment]
well.The bot  answer is not friendly. Thanks your Patience.

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-n19dcx?file=app%2Fapp.component.ts
here is the demo for you, it works well when you reset the disabled hours function.
That is why I say we spend almost 30% of our time to figure out the fake bug report.

**Comment by yy7054wyq5** [comment]
Get it. I did't have a thought of 'reset function'. 3q.
But i am not a '伸手要的人'.
At last, thank u again.
