### ISSUE TITLE
0.6版.14日期选择框在Safari下出现问题.

### ISSUE THREAD

**Issue by wangshoukai** [NG-ZORRO/ng-zorro-antd#1041]
## Version

0.6.14

## Environment

mac safari  ; win 360 都会出现;

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/showcase/nz-demo-datepicker/nz-demo-datepicker-basic.component.ts](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/showcase/nz-demo-datepicker/nz-demo-datepicker-basic.component.ts)

## Steps to reproduce

使用Safari打开https://ng.ant.design/#/components/date-picker

## What is expected?

同Google Chrome 展示效果

## What is actually happening?

选框内日期偏移,且被超过隐藏,时间选择框左移至屏幕最左边

**Comment by wangshoukai** [comment]
时间选框兼容性问题.

**Comment by vthinkxie** [comment]
@HsuanXyz
