### ISSUE TITLE
upload组件在上传单个文件后会多次调用(nzChange)方法

### ISSUE THREAD

**Issue by pangtouyuyyf** [NG-ZORRO/ng-zorro-antd#1043]
## Version

0.6.12

## Environment

win10 chrome版本 62.0.3202.94（正式版本）

## Reproduction link

[https://github.com/pangtouyuyyf/ng-zorro-bug.git](https://github.com/pangtouyuyyf/ng-zorro-bug.git)

## Steps to reproduce

点击上传按钮后多次调用(nzChange)方法后图片会显示出来

## What is expected?

在上传一个文件后单次调用该方法

## What is actually happening?

多次调用

## Other?

这个可能是有意为之，也可能是我操作失误，希望能给出一个解释

**Comment by cipchk** [comment]
请认真阅读文档。

> # nzChange
> 开始、上传进度、完成、失败都会调用这个函数。

**Comment by karocksjoelee** [comment]
is there any variable that indicates difference between "開始" 、"上傳進度"、"完成" 

status 都是 done 
percent 都是 100

**Comment by cipchk** [comment]
基于 `beforeUpload` 返回的结果分两种情况（自动&手动上传）说明这些状态的情况：

## 自动上传

其 `status` 值如下：

| 事件 | 状态值 | 触发 | 其它
| ----- | ------- | ----- | -----
| 开始 | uploading | 选择文件后 | -
| 上传进度 | uploading | 上传过程中后端返回 `total`、`loaded` 等时触发 |  `nzChange` 的 `file` 会携带 `percent` 值表示百分比与 `event` 表示完整返回参数数据
| 成功 | done | 后端告知完成时 |  `nzChange` 的 `file` 会携带 `response` 值表示结果且无 `event` 参数
| 错误 | error | 后端告知错误或HTTP中断等 |  `nzChange` 的 `file` 会携带 `message` 值表示错误文本且无 `event` 参数

## 手动上传

无 `status` 值，一切交由用户自动决定；其文件对象本质是一个带有 `uid` （一个随机字符串） `File` 值。
