### ISSUE TITLE
表格UI操作接口支持排序和筛选吗

### ISSUE THREAD

**Issue by tossp** [NG-ZORRO/ng-zorro-antd#105]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

**Comment by vthinkxie** [comment]
you can sort and filter your data use javascript sort and filter function.

**Comment by tossp** [comment]
抱歉，
我的意思不是要用前端做排序或者筛选，
我的意思是，table组件，应该能收集用户的筛选或者排序意图，抓取到响应数据以后，根据具体业务逻辑客户端操作也好，服务器操作也好做相应的操作，如下图

![zz](https://user-images.githubusercontent.com/2138631/29752795-f76198e4-8b96-11e7-8eb7-45f478534aac.gif)

@vthinkxie 希望可以重开这个issues

**Comment by vthinkxie** [comment]
if you want to use server sort, the table support also support it, just read `nzAjaxData` and `nz-table-sort` in the doc, and filter component on the table has not been supported yet.

**Comment by tossp** [comment]
好的，谢谢你的建议
