### ISSUE TITLE
InputNumber字输入框

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1051]
## Version

0.6.12

## Environment

win10 、chrome63.0.3239.108、0.6.12

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-xmpppo?file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-xmpppo?file=app/app.component.html)

## Steps to reproduce

InputNumber最小的输入不支持0的显示，包括0.x的统一显示undefined，formatterPercent = value => value == undefined ? `0%` : `${value}%`;这段代码解决了0.x的问题，但是最小的数字依然不支持0的显示

## What is expected?

支持0的显示和0.x的问题

## What is actually happening?

支持0的显示和0.x的问题

**Comment by vthinkxie** [comment]
please upgrade to latest version
the bug has been solved already.
https://stackblitz.com/edit/ng-zorro-antd-setup-u2pbru?file=app/app.component.ts
