### ISSUE TITLE
input-number 点击上箭/下箭按钮表现不正常

### ISSUE THREAD

**Issue by xingzhuo1983** [NG-ZORRO/ng-zorro-antd#1055]
## Version

0.6.14

## Environment

win10/chrome65

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

## Steps to reproduce

1.打开官方文档input-number示例, 确认当前输入框的值是3
2.输入数字6
3.,保持焦点不离开, 点击上箭头, 输入框显示4
4.输入数字4.5,焦点离开,确认值已生效
5.点击上箭头,输入框显示6

## What is expected?

输入后,输入值即可生效,而不是需要焦点离开
值为小数时,点上下箭头,值直接 1 而不是取整后 1

## What is actually happening?

当前值在输入后并没有变为新值,点击上下箭头时按原值变化
小数 1时是取整 1

**Comment by vthinkxie** [comment]
ref #1057
