### ISSUE TITLE
nz-table 在显示页码的情况下, 数据源数组延时增加，不触发 UI 渲染

### ISSUE THREAD

**Issue by Xcorpio** [NG-ZORRO/ng-zorro-antd#1058]
## Version

0.6.14

## Environment

mac os, chrome latest 0.6.14

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-t2pfg3?file=app%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-t2pfg3?file=app%2Fapp.component.ts)

## Steps to reproduce

https://stackblitz.com/edit/ng-zorro-antd-setup-t2pfg3?file=app%2Fapp.component.ts

## What is expected?

需要触发UI渲染

## What is actually happening?

如果延时，push 数据, 不会 渲染.  

使用 `this._dataSet=[...this._dataSet]` 才能触发渲染.

**Comment by sail-sail** [comment]
我也遇到同样的问题, 我还以为是Angular的问题, 反复测试之后, 才确定
搞得我都想用material算了

**Comment by vthinkxie** [comment]
duplicated #805 
please read the doc of ngOnChanges of angular 

https://angular.io/guide/lifecycle-hooks#onchanges


The log entries appear as the string value of the power property changes. But the ngOnChanges does not catch changes to hero.name That's surprising at first.

Angular only calls the hook when the value of the input property changes. The value of the hero property is the reference to the hero object. Angular doesn't care that the hero's own name property changed. The hero object reference didn't change so, from Angular's perspective, there is no change to report!
