### ISSUE TITLE
ng-table 显示页码时, 同时添加数据 修改当前页码到最后一页, 页码条当前页渲染错误 

### ISSUE THREAD

**Issue by Xcorpio** [NG-ZORRO/ng-zorro-antd#1059]
## Version

0.6.14

## Environment

chrome latest 0.6.14

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-umkwhw?file=app%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-umkwhw?file=app%2Fapp.component.ts)

## Steps to reproduce

https://stackblitz.com/edit/ng-zorro-antd-setup-umkwhw?file=app%2Fapp.component.ts

同时往 dataset 中加数据
一直点最后一个按钮, pageIndex 改变, 但是 当前 页码 渲染错误

## What is expected?

页码 随 pageIndex 改变

## What is actually happening?

页码 随 pageIndex 不改变

**Comment by vthinkxie** [comment]
fixed in version 0.7.0 closed
