### ISSUE TITLE
表单模型再次赋值时的BUG(bug:When the form model was again assignment)

### ISSUE THREAD

**Issue by myepoch** [NG-ZORRO/ng-zorro-antd#106]
当表单模型再次被赋值的时候报错(When the form model was again assignment,error) ：
’ERROR Error: There is no FormControl instance attached to form control element with name: 'email'

`
  //CN: 初始化表单模型
 // EN: Initialization form model
  ngOnInit() {
    this.validateForm = this.fb.group({ 
      email            : [ '', [ Validators.email ] ],
    });
  }
  // CN:当页面文本框失去焦点时，表单模型再次赋值
  // EN:When the nz-input loses focus, again assignment form model
  public onIdCardChange (form: any): void { 
    this.validateForm = this.fb.group({
      email            : [ 'hello@nz-zorro.com', [ Validators.email ] ],
    });
  }
`
CN:以下是页面部分代码
EN:html code
`<nz-root>
  <form nz-form [formGroup]="validateForm" (ngSubmit)="_submitForm()">
    <div nz-form-item nz-row>
      <div nz-form-control>
        <nz-input [nzSize]="'large'" formControlName="email" [nzId]="'email'" (nzBlur)="onIdCardChange(validateForm.controls)"></nz-input>
      </div>
    </div>
  </form>
</nz-root>`

**Comment by vthinkxie** [comment]
It's an angular problem, please use setValue or patchvalue to manipulate form value.
https://angular.cn/guide/reactive-forms#使用setvalue和patchvalue来操纵表单模型
Please make sure you fully understand the usage of [Reactive forms](https://angular.cn/guide/reactive-forms).

**Comment by myepoch** [comment]
你好，但是原生的ANGULAR响应式表单的input是没问题的：
（hi,The original ANGULAR ， input is no problem）

      <div nz-form-control >

<input id="email" name="email" formControlName="email" (blur)="onIdCardChange(validateForm.controls)" class="form-control">

        
      </div>

**Comment by vthinkxie** [comment]
@myepoch 
please use follow code as a temp solution. thanks.
```typescript
    this.validateForm.controls['email'].setValue('hello@nz-zorro.com');
```

**Comment by vthinkxie** [comment]
related #114
