### ISSUE TITLE
switch should have onChange event

### ISSUE THREAD

**Issue by vellengs** [NG-ZORRO/ng-zorro-antd#1061]
## What problem does this feature solve?

虽然ngModel 可以使用 get set 插入事件注册点，但是对于 ngFor 以及特殊的场景下，要获得值变化的监测则很困难。

## What does the proposed API look like?

https://mobile.ant.design/components/switch-cn/
与 ant design 保持一致

**Comment by vthinkxie** [comment]
ngModelChange?

**Comment by vellengs** [comment]
Ok, 确实可以使用 ngModelChange。
