### ISSUE TITLE
NzModalService.warning wrapClassName may didn't work

### ISSUE THREAD

**Issue by Elliottssu** [NG-ZORRO/ng-zorro-antd#1066]
## Version

0.6.8

## Environment

angular 5.2

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-6wdvxr](https://stackblitz.com/edit/ng-zorro-antd-setup-6wdvxr)

## Steps to reproduce

I put zorro NzModalService in my angular project, and it doesn't work when i try to use `wrapClassName` create special classname.

angular: V5.2
code:
```
warning() {
    this.confirmServ.warning({
      title: '这是一条成功信息',
      content: '一些附加信息一些附加信息一些附加信息',
      wrapClassName: 'my-class'
    });
  }
```
css what i want
```
.my-class .ant-modal {
  width: 200px !important;
  height: 500px !important
}
```

## What is actually happening?

I can't find className `my-class`,that i defined it by `wrapClassName`

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-jpxhrc?file=app%2Fapp.component.ts

**Comment by Elliottssu** [comment]
@vthinkxie yes, thanks, it works well, you should update the documents

**Comment by vthinkxie** [comment]
@Elliottssu we are working on 0.7.0 version now, it will refactor almost every component rewrite the document totally.
