### ISSUE TITLE
inline mode menu init error

### ISSUE THREAD

**Issue by xunjianxiang** [NG-ZORRO/ng-zorro-antd#1068]
## Version

0.6.14

## Environment

ng-zorro-antd 0.6.14

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-vdyrtt?file=app%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-vdyrtt?file=app%2Fapp.component.ts)

## Steps to reproduce

After init.

## What is expected?

The normal display.

## What is actually happening?

The normal display.

## Other?

Style error.

**Comment by vthinkxie** [comment]
duplicated #364

**Comment by vthinkxie** [comment]
try to fixed in version 0.7.0 but failed
https://github.com/NG-ZORRO/ng-zorro-antd/blob/5c0716107e0955b034a2d9ce75463ff3b0e9fdb6/components/menu/style/index.less#L372
the design of ant design can not insert any self define component into menu, it will break the style define.
