### ISSUE TITLE
Can't change width of nz-rangePicker

### ISSUE THREAD

**Issue by WOOOFEI** [NG-ZORRO/ng-zorro-antd#1089]
## Version

0.6.12

## Environment

osx 10.13 chrome 64

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

## Steps to reproduce

![771b96148d51b01994477468efc3614c](https://user-images.githubusercontent.com/21849553/36837643-eb68eb78-1d77-11e8-9a3b-73c0836801eb.jpg)
![51d10b82a0267a0f1784b75f27845804](https://user-images.githubusercontent.com/21849553/36837644-ec9e32b4-1d77-11e8-9b6b-182f3ae980a5.jpg)

## What is expected?

change width.

## What is actually happening?

Can't change width of nz-rangepicker

**Comment by vthinkxie** [comment]
not a bug, please check your code

**Comment by WOOOFEI** [comment]
对不起，我这张图截得有歧义，我style里面的东西是后来测试加上去的，我使用demo中一样的写法也出现了这个问题。
