### ISSUE TITLE
阿里巴巴 2019届实习生应届生招聘

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#1090]
![2019](https://user-images.githubusercontent.com/1506722/36839070-e566eb86-1d7b-11e8-8450-fb9ade90c410.png)

**Comment by cdllqos** [comment]
Is there any chance for 2018 graduate?

**Comment by bobmayuze** [comment]
Do u accept English version of Resume?

**Comment by vthinkxie** [comment]
@cdllqos @bobmayuze yes.

**Comment by cdllqos** [comment]
@vthinkxie sorry for that, I'll will be internship for another team this Wednesday.

**Comment by bobmayuze** [comment]
@vthinkxie  Resume sent, but I don't think I'm a good match for frontend dev.
