### ISSUE TITLE
nz-rangepicker宽度设置问题

### ISSUE THREAD

**Issue by webliuxiang** [NG-ZORRO/ng-zorro-antd#1091]
## Version

0.6.15

## Environment

0.6.15

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

## Steps to reproduce

我尝试了使用栅格系统和行内样式，都不能正确显示宽度。我使用的代码和文档上的demo是一致的，但是当宽度设置的比较大的时候，内部的时间范围选择框不会撑满。
![image](https://user-images.githubusercontent.com/25944130/36842204-d4d7733a-1d85-11e8-8401-91d2533c6a38.png)
·
![image](https://user-images.githubusercontent.com/25944130/36842290-334944c0-1d86-11e8-8c3f-f2034ce2a11b.png)
↑↑↑
nz-rangepicker的宽度是没问题的，但是可以看到里面宽度没发生改变。

## What is expected?

设置宽度能正确显示。

## What is actually happening?

我在设置宽度的时候，nz-rangepicker元素宽度会改变，但是实际显示的宽度（日期范围选择框）不会改变。

**Comment by vthinkxie** [comment]
It has noting to do with ng-zorro, please read about how to change html element style with css define.

**Comment by vthinkxie** [comment]
please provide an reproduction link, a fake reproduction link won't help.

**Comment by WindAndDust** [comment]
:host ::ng-deep .ant-calendar-picker-input {
  width: 260px;
  padding-top: 4px;
}
在样式中将其原有class覆盖

**Comment by webliuxiang** [comment]
OK 已经修改了。谢谢
