### ISSUE TITLE
兼容性问题，布局实例（顶部-侧边布局）在ie9下会变形

### ISSUE THREAD

**Issue by liiyannjiee** [NG-ZORRO/ng-zorro-antd#110]
1 直接使用（顶部-侧边布局）实例代码，ng-zorro-antd使用0.5.0-rc.2。
在ie9下打开布局变为了：
![image](https://user-images.githubusercontent.com/11025703/29505924-a1cb19a2-867b-11e7-8623-c194a939e1c7.png)
chrome下：
![image](https://user-images.githubusercontent.com/11025703/29505974-e49bcc40-867b-11e7-81b7-5d4de790dfbf.png)

**Comment by vthinkxie** [comment]
Layout is based on **CSS Flexible Box Layout Module**. There is a tip to pay attention to the compatibility on [this page](https://ng.ant.design/#/components/layout).
You can check compatibility [here](http://caniuse.com/#search=flex)
