### ISSUE TITLE
Tree树形控件

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1102]
## What problem does this feature solve?

Tree树形控件有没有在6.x版本的计划或者7.x版本有没有

## What does the proposed API look like?

Tree树形控件有没有在6.x版本的计划或者7.x版本有没有

**Comment by vthinkxie** [comment]
will be provided in version 0.7.0

**Comment by Y2zz** [comment]
I have not seen the relevant code for the tree yet

**Comment by vthinkxie** [comment]
@Y2zz not submitted yet, any problem?

**Comment by Y2zz** [comment]
Urgent need tree. . .

**Comment by JCqiu** [comment]
https://github.com/cipchk/ng-tree-antd

**Comment by Y2zz** [comment]
@JCqiu Currently using this tree, but getting the check data is too complicated

**Comment by JCqiu** [comment]
This component can be operated like ant @Y2zz
