### ISSUE TITLE
ng-Affix trigger change detection too frequently

### ISSUE THREAD

**Issue by vickmeng** [NG-ZORRO/ng-zorro-antd#1103]
## Version

0.6.15

## Environment

zorro0.6.15 chrome66 window7

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

## Steps to reproduce

只要页面存在ng-Affix，就会不停地触发变化检测

## What is expected?

希望优化检测定位的部分

## What is actually happening?

触发频繁

**Comment by vthinkxie** [comment]
please provide reproduction link.
