### ISSUE TITLE
why nz-upload is not exist

### ISSUE THREAD

**Issue by lishaoh** [NG-ZORRO/ng-zorro-antd#1106]
## What problem does this feature solve?

VM34011:34 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'nzFileList' since it isn't a known property of 'nz-upload'.

## What does the proposed API look like?

```<nz-upload nzAction="https://jsonplaceholder.typicode.com/posts/"
    nzListType="picture"
    [(nzFileList)]="fileList1">
  </nz-upload>
```

**Comment by lishaoh** [comment]
版本"ng-zorro-antd": "^0.6.10",

**Comment by vthinkxie** [comment]
reproduction link?

**Comment by vthinkxie** [comment]
read the changelog please
https://ng.ant.design/#/changelog
