### ISSUE TITLE
the Notification and the Message and so on cannot set the property id

### ISSUE THREAD

**Issue by sunny2zhang** [NG-ZORRO/ng-zorro-antd#1109]
## What problem does this feature solve?

when I use the Notification.html create a  <a (click)="gotoarmpage()"> link to the arm route ,at the same time I want to close the Notification,but I can't find the prop "id" anywhere 

## What does the proposed API look like?

Notification(html: string, id:string, options?: Object)

**Comment by vthinkxie** [comment]
please read the doc carefully
