### ISSUE TITLE
[Popover] Can't set canvas width and height

### ISSUE THREAD

**Issue by lishaoh** [NG-ZORRO/ng-zorro-antd#1112]
## What problem does this feature solve?

const canvas = document.querySelector('.img-qrcode');
canvas.width = 230;
canvas.height = 230;
const ctx = canvas.getContext('2d');

I want to create qrcode ,but get the error:   Property 'width' does not exist on type 'Element'.

## What does the proposed API look like?

```
<nz-popover [nzTitle]="''" [nzPlacement]="'bottom'" (nzVisibleChange)="makeQrcode($event)">
        <button class="button-deepGreen" nz-button nz-popover>扫码上传</button>
        <ng-template #nzTemplate>
          <canvas class="img-qrcode" style="width: 230px;height: 230px;background:#ffffff"></canvas>
        </ng-template>
      </nz-popover>
```

**Comment by vthinkxie** [comment]
not related to ng-zorro, closed.
