### ISSUE TITLE
moment打包体积问题

### ISSUE THREAD

**Issue by jecyhw** [NG-ZORRO/ng-zorro-antd#1117]
angular-cli在打包时，会把moment的locale全部打包进去，整个体积占比相对很大，如下图，
![image](https://user-images.githubusercontent.com/10094084/37261933-e6c52bb6-25da-11e8-8ecc-3ee33b196d32.png)
建议使用[moment-mini-ts](https://www.npmjs.com/package/moment-mini-ts)，或者其他方式避免把moment的所有locale打包进去。

**Comment by vthinkxie** [comment]
moment will be removed in version 0.7.0
