### ISSUE TITLE
https://ng.ant.design/#/docs/angular/introduce 首页的搜索组件的 select 在 Mac Pro 屏幕下点开下拉树闪烁

### ISSUE THREAD

**Issue by MwumLi** [NG-ZORRO/ng-zorro-antd#1120]
ng-zorro站点首页的搜索组件 select, 点击弹出的 dropdown 会在 Mac Pro 屏幕下出现闪烁

环境: Mac Pro 屏幕(外接的屏幕是 ok的)

之所以没用你们 issue 链接, 是你们的 issue 连接写的太死了, 像我发现的这种情况下怎么去提

**Comment by MwumLi** [comment]
你在 Mac Pro 下直接就可以看到?为什么不试一下呢?

**Comment by vthinkxie** [comment]
@MwumLi everything works fine in my mac pro.

**Comment by MwumLi** [comment]
@vthinkxie 
如图
![nz-select](https://user-images.githubusercontent.com/6889433/37327255-795f6f0e-26d0-11e8-913e-ee1dbded322f.gif)

**Comment by MwumLi** [comment]
我们这边3台 Mac Pro都出现这个现象, 外界显示屏反而不会

**Comment by vthinkxie** [comment]
@MwumLi thanks for reporting

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/0.7.x/docs/introduce/zh is there the problem exist in version 0.7.0?

**Comment by MwumLi** [comment]
It seems to be fixed

**Comment by MwumLi** [comment]
how to fix it?

**Comment by vthinkxie** [comment]
select components in version 0.7.0 is totally rewrite.
