### ISSUE TITLE
数据表格中的列出现多次渲染（严重影响性能和列中自定义组件）

### ISSUE THREAD

**Issue by lanmingle** [NG-ZORRO/ng-zorro-antd#1124]
## Version

0.6.15

## Environment

any

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd/issues/1123](https://github.com/NG-ZORRO/ng-zorro-antd/issues/1123)

## Steps to reproduce

 自己写对着例子测试就知道

## What is expected?

一个列在非数据变化情况下不重新渲染（生命钩子）

## What is actually happening?

一个列居然调用4次以上（5.x 更多从），更多的列调用更多的次数。。。

**Comment by vthinkxie** [comment]
make sure you have learn angular, it has noting to do with zorro
