### ISSUE TITLE
cannt use a tree component？？？可以加一个树形结构的组件样式吗

### ISSUE THREAD

**Issue by qfy081** [NG-ZORRO/ng-zorro-antd#113]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by tossp** [comment]
我看React版是基于rc-tree制作的

angular 好像只找到 [angular-tree-component](https://github.com/500tech/angular-tree-component) 
但是他依赖了mobx ，不知道官方会不会觉得臃肿

**Comment by vthinkxie** [comment]
duplicated #132
