### ISSUE TITLE
英文文档需求

### ISSUE THREAD

**Issue by lokyoung** [NG-ZORRO/ng-zorro-antd#1134]
## What problem does this feature solve?

首先感谢推出这么优秀的基于ant design的UI库。发现你们的组件能解决我当前项目的大部分问题。但是这个项目还没有英文文档，我当前项目的客户是美国人，所以他们应该不会接受使用没有英文文档的项目。希望能尽快出英文文档。如果暂时没有人员去做这件事，我可以帮助翻译。

## What does the proposed API look like?

ant design作为一个优秀的设计语言帮助了大量的开发者和设计师去构建了user friendly的应用，而angular在欧美市场的占有率很高。我在当前项目的开发中引入了很多个angular supported的UI库，因为很多时候一个库并不满足我全部的需求。但是看了一遍你们的文档，发现竟然所有的需求都可以满足。所以如果可能的话，我非常乐意参与你们的翻译工作。让世界各地的angular开发者都能用上这个优秀的UI库。
我是一名写前端很多的Ruby程序员。

github: https://github.com/lokyoung

email: lokyoung76@gmail.com

非常高兴认识你们，希望能帮助你们维护英文文档。感谢。

**Comment by vthinkxie** [comment]
@lokyoung 非常感谢你的关注，事实上我们在最新版本已经完成了部分英文文档的翻译，你可以切换至0.7.0分支，https://github.com/NG-ZORRO/ng-zorro-antd/blob/0.7.0/PROGRESS.md 按照该步骤即可查看最新的版本和英文翻译内容，欢迎帮助我们校对，谢谢

**Comment by lokyoung** [comment]
@vthinkxie 非常感谢

**Comment by vthinkxie** [comment]
@lokyoung ，英文文档已经发布 https://ng.ant.design/version/0.7.x/docs/introduce/zh 有兴趣参与校对的话可以随时联系我

**Comment by lokyoung** [comment]
@vthinkxie 太赞了！谢谢！

**Comment by lokyoung** [comment]
Hello @vthinkxie . 有个问题想说下，https://yuque.com/ng/read/2017-01 。你在语雀整理的angular资料的title是2017-01，我看了下日期，应该是2018-01。我是在知乎上看到你发的链接的，但是不知道怎么联系上您（知乎上不能给你发私信），就在这里提一下。谢谢。
