### ISSUE TITLE
表单重置未生效？

### ISSUE THREAD

**Issue by Feng-JY** [NG-ZORRO/ng-zorro-antd#114]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

表单重置问题，form.reset()后表单dirty仍为true。使用input未出现该情况
![image](https://user-images.githubusercontent.com/13466494/29514794-5fde6cd0-869c-11e7-8426-b729ed2a6d02.png)

**Comment by vthinkxie** [comment]
works fine for me, please check your angular version.

**Comment by vthinkxie** [comment]
bug confirm, thanks.

**Comment by vthinkxie** [comment]
related https://github.com/angular/angular/issues/9700

**Comment by mushang11** [comment]
private resetForm(forms:NgForm[]) {
        forms.forEach((form: NgForm) => {
            if (form.dirty) {
                for (let l in form.controls) {
                    form.controls[l].markAsPristine();
                    form.controls[l].markAsUntouched();
                }
            }
        })
    }
u can use similar function to do your work

**Comment by htmlcss23** [comment]
Can't bind to 'formGroup' since it isn't a known property of 'form'. ("
        </div>
        <div class="login-right">
            <form nz-form [ERROR ->][formGroup]="validateForm" class="login-form" (ngSubmit)="_submitForm()">
                <div nz-for"): ng:///AuthModule/LoginPageComponent.html@20:26
No provider for ControlContainer ("
        </div>
        <div class="login-right">
            [ERROR ->]<form nz-form [formGroup]="validateForm" class="login-form" (ngSubmit)="_submitForm()">
             "): ng:///AuthModule/LoginPageComponent.html@20:12
No provider for NgControl ("  <div nz-form-control [nzValidateStatus]="validateForm.controls.userName">
                        [ERROR ->]<nz-input formControlName="userName" [nzPlaceHolder]="'Username'" [nzSize]="'large'">
               "): ng:///AuthModule/LoginPageComponent.html@23:24
No provider for NgControl ("  <div nz-form-control [nzValidateStatus]="validateForm.controls.password">
                        [ERROR ->]<nz-input formControlName="password" [nzType]="'password'" [nzPlaceHolder]="'Password'" [nzSize]="'la"): ng:///AuthModule/LoginPageComponent.html@33:24
No provider for NgControl ("               <div nz-form-item>
                    <div nz-form-control>
                        [ERROR ->]<label nz-checkbox formControlName="remember">
                          <span>Remember me</span>
   "): ng:///AuthModule/LoginPageComponent.html@43:24
    at syntaxError (http://localhost:4201/vendor.bundle.js:85450:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:4201/vendor.bundle.js:96574:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:4201/vendor.bundle.js:110726:39)
    at http://localhost:4201/vendor.bundle.js:110646:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:4201/vendor.bundle.js:110646:19)
    at http://localhost:4201/vendor.bundle.js:110533:19
    at Object.then (http://localhost:4201/vendor.bundle.js:85439:156)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4201/vendor.bundle.js:110532:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync 













涉及到交互就报这个错误，是我少引入了什么东西了么

**Comment by vthinkxie** [comment]
@htmlcss23 read the doc again.
https://ng.ant.design/#/components/form

**Comment by htmlcss23** [comment]
在子modle里面引用就报错，直接父modle引用是不报错的
