### ISSUE TITLE
[BUG] nz-table nzCustomNoResult display format

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#115]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

html code: 

```html
<nz-table [nzCustomNoResult]="true">
    <div #noResult>Please choose file to upload.</div>
    <thead nz-thead>
        <tr>
            <th nz-th><span>Name</span></th>
            <th nz-th><span>Size</span></th>
            <th nz-th><span>Progress</span></th>
            <th nz-th><span>Status</span></th>
            <th nz-th><span>Actions</span></th>
        </tr>
    </thead>
</nz-table>
```

but, rendering view: 

![tim 20170821190500](https://user-images.githubusercontent.com/2987467/29516636-b2adbdf6-86a3-11e7-8489-25e045961262.png)

![tim 20170821190519](https://user-images.githubusercontent.com/2987467/29516640-b4722c94-86a3-11e7-82a5-816d8e6ba720.png)

there's a couple of issues here:

+ my custom empty result text is not style.
+ has a empty placeholder: `.ant-table-placeholder`.

**Comment by vthinkxie** [comment]
use
```html
<div noResult>Please choose file to upload.</div>
```
