### ISSUE TITLE
The parent node of Tree Component should have the appropriate UI state

### ISSUE THREAD

**Issue by SangKa** [NG-ZORRO/ng-zorro-antd#1152]
When the Tree Component is initialized, the parent node should have the appropriate state, such as isHalfChecked or isAllChecked, show as below which comes from official document example.

![image](https://user-images.githubusercontent.com/6177271/37498950-11bfb9fc-28fc-11e8-9f81-01071807e479.png)

**Comment by simplejason** [comment]
nzDefaultxxxKeys will not associate child nodes when initialized, we will fix it soon.thanks
