### ISSUE TITLE
Use the select component in the reactiveForm,  change the value via patchValue in asynchronously execution environment but keep the old value

### ISSUE THREAD

**Issue by dknfeiov** [NG-ZORRO/ng-zorro-antd#1153]
## Version

0.5.1

## Environment

win7  chrome latest,  zorro0.5.1

## Reproduction link

[https://stackblitz.com/edit/zorro55-basic](https://stackblitz.com/edit/zorro55-basic)

## Steps to reproduce

see links

steps:
initial value: 1
new value :0 

## What is expected?

option  '0'  has been selected 

## What is actually happening?

option  '1'  has been selected 

## Other?

the initial positioning, the problem  is caused by function "addOption",  the condition  judgment of  fourth line has some problem, when the value is number zero , can't be passed

    addOption = (option) => {
     this._options.push(option);
     if (!this._isTags) {
       if (option.nzValue) {
         this.updateSelectedOption(this._value);
       } else {
         this.forceUpdateSelectedOption(this._value);
       }
     }
   }

**Comment by vthinkxie** [comment]
0.5.1 is not under maintain any longer, please update to the latest version, thanks.

**Comment by xzedx** [comment]
My project is at 0.6.3 now. Still have the same problem

**Comment by flyaway0624** [comment]
Excuse me, what is the cause of this problem, and I have the same problem?

**Comment by dknfeiov** [comment]
@flyaway0624 see the problem description . you can modify the source code to solve ,  or avoid the dropdown option value is zero
