### ISSUE TITLE
Documentation still defaults to version v0.6.x not v0.7.x

### ISSUE THREAD

**Issue by murraybauer** [NG-ZORRO/ng-zorro-antd#1157]
## Version

0.7.0-beta.1

## Environment

0.7.0-beta.1

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

## Steps to reproduce

Go to https://ng.ant.design in incognito browser window: v0.6.x in version drop down on top right selected by default

## What is expected?

v0.7.x (latest) should be selected

**Comment by vthinkxie** [comment]
0.7.x is not stable yet, will be change to default when stable.
