### ISSUE TITLE
[0.7.0-beta.1] table: 固定多个右列时产生多个阴影

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#1161]
## 重现

png:

![image](https://user-images.githubusercontent.com/2987467/37553205-5d4ea2a4-29fe-11e8-98c0-4caf7a8cc30b.png)

https://stackblitz.com/edit/angular-uzggds?file=app/app.component.ts

**以及当固定列后，若实际宽度不足以需要固定时依然会显示固定右列的效果，响应式布局很容易产生这种现象**

![tim 20180317161907](https://user-images.githubusercontent.com/2987467/37553228-03e10256-29ff-11e8-9741-cf14af648559.png)

**Comment by vthinkxie** [comment]
fixed in #1163
