### ISSUE TITLE
nz-modal 能否提供全局事件，如：closeAll

### ISSUE THREAD

**Issue by realmx** [NG-ZORRO/ng-zorro-antd#1162]
## What problem does this feature solve?

当页面打开一个或多个modal时，用户点其它菜单或点击浏览器后退按钮，这些已打开的modal需要一次性全关闭掉

## What does the proposed API look like?

希望提供一个closeAll事件，在根页面监听路由变化，可关闭所有modal，如下代码
```
    constructor(
        private router: Router,
        private modalService: NzModalService
    ) {
        router.events.subscribe(event => {
            if (event instanceof NavigationStart) {
                this.modalService.closeAll();
            }
        });
    }
```

**Comment by vthinkxie** [comment]
@wilsoncook please take this into consideration in 0.7.0 version.
