### ISSUE TITLE
[bug] 多选择框相互联动，联动变更时， 重设默认值无法生效

### ISSUE THREAD

**Issue by lopn** [NG-ZORRO/ng-zorro-antd#1169]
## Version

0.6.15

## Environment

window/mac chrome node6.11.1

## Reproduction link

[https://github.com/lopn/bug-img/blob/master/ng-zorro-antd/](https://github.com/lopn/bug-img/blob/master/ng-zorro-antd/)

## Steps to reproduce

    前提：两个下拉选择框相互联动，  第二个选择框的先项会随着第一个选择框的值 相互改变
    问题： 当新旧选择项列表 存在相同的选择项时，并且相同的选择项处于选中状态 
                当我切换了第一个选择框的时候，并且我手动修改了第二个选择框的默认选中值 后， 第二个选择框的选项已经改变，但是对应的选择项没有发生变化 
   对应代码： 
### component:
```
    changeSelectedDate(dateKey): void {
        this.compareDateLists = this.dateDefineService.getCompareDateList(dateKey);
        this.reportTableTimeSetting.summary_date_compare =  this.compareDateLists [0]['key']; // @todo 阿里组件bug
     }
```
### tpl:
```
<div class="lab-row mt30">
        <label>时间范围:</label>
        <nz-select class="w100 ml8" [nzSize]="'small'" [(ngModel)]="reportTableTimeSetting.summary_date" (ngModelChange)="changeSelectedDate($event)">
          <ng-container *ngFor="let item of dateLists">
            <nz-option [nzLabel]="item.name" [nzValue]="item.key"></nz-option>
          </ng-container>
        </nz-select>
        <nz-rangepicker  [(ngModel)]="reportTableTimeSetting.summary_date_range" [nzFormat]="'YYYY/MM/DD'" [nzAllowClear]="false" [nzDisabled]="reportTableTimeSetting.summary_date !== 'define'" [nzSize]="'small'" class="ml8"></nz-rangepicker>
      </div>

      <div class="lab-row mt10">
        <label>对比时间:</label>
        <nz-select class="w100 ml8" [nzSize]="'small'" [(ngModel)]="reportTableTimeSetting.summary_date_compare">
          <ng-container *ngFor="let item of compareDateLists">
            <nz-option [nzLabel]="item.name" [nzValue]="item.key"></nz-option>
          </ng-container>
        </nz-select>
        <nz-rangepicker  [(ngModel)]="reportTableTimeSetting.summary_date_compare_range" [nzFormat]="'YYYY/MM/DD'" [nzAllowClear]="false" [nzDisabled]="reportTableTimeSetting.summary_date_compare !== 'define'" [nzSize]="'small'" class="ml8"></nz-rangepicker>
      </div>
```

## What is expected?

 ![](https://github.com/lopn/bug-img/blob/master/ng-zorro-antd/bug-select-expect-ng.gif?raw=true)

## What is actually happening?

![](https://github.com/lopn/bug-img/blob/master/ng-zorro-antd/bug-select-ng-zorro.gif?raw=true)

## 框架代码原因：
https://github.com/NG-ZORRO/ng-zorro-antd/blob/51364d8432beab326c3b55be6e730e60976d270f/src/components/select/nz-select.component.ts#L351
 ···
 removeOption(option: NzOptionComponent): void {
    this._options.splice(this._options.indexOf(option), 1);
    if (!this._isTags) {
      this.forceUpdateSelectedOption(this._value);
    }
  }

  forceUpdateSelectedOption(value: string | string[]): void {
    /** trigger dirty check */
    setTimeout(_ => {
      this.updateSelectedOption(value);
    });
  }

····

removeOption时 所用的forceUpdateSelectedOption ，实际上有一个setTimeout , 但是，removeOption时的this._value是变化前的值 ， 这就会使 这个updateSelectedOption（value）在下一轮检测后执行，导致 选项在变化后又重新被改写 （如上图bug中的结果 ，debug 实际流程是  （原先自定义）->(变为我设的新值) ->( 又变化为原先的自定义 ) ）
 
## 修改方法：(结果为上图中期望的结果 )
···
    removeOption(option: NzOptionComponent): void {
    this._options.splice(this._options.indexOf(option), 1);
    if (!this._isTags) {
      this.updateSelectedOption(this._value);
    }
  }
···
   由于本人没有明白你们当初为什么要用forceUpdateSelectedOption, 所以在此提出问题，没有提交pull request

**Comment by vthinkxie** [comment]
please try the latest version, the select component is totally rewrite.

**Comment by lopn** [comment]
I see , but our is the product version . the last version Just released, I'm afraid of having other bug

so i want you fixed this bug of 0.6.x

**Comment by vthinkxie** [comment]
The stable version of 0.7.0 will be released at the end of this month, select component in version 0.6.x is complex, if remove setTimeout here, will cause bug when remove option at initial state.

**Comment by lopn** [comment]
i remove setTimeout  in my project, , I haven't met bug yet 。
Can you give an example of what bug brings?

**Comment by vthinkxie** [comment]
should be resolved in latest version, you can reopen it if the bug still exist.
