### ISSUE TITLE
nz-input组件中touched不能被正确设置

### ISSUE THREAD

**Issue by tossp** [NG-ZORRO/ng-zorro-antd#117]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## What is the motivation / use case for changing the behavior?

使用FormBuilder构建动态表单，dirty正常，touched一直为false
```ts
  ngOnInit() {
    this.LoginForm = this.fb.group({
      'UserName': [null, Validators.compose([Validators.required, Validators.minLength(2), Validators.maxLength(255)])],
      'PassWord': [null, Validators.compose([Validators.required, Validators.minLength(5), Validators.maxLength(255)])],
      'Remember': [true],
    });
  }
```

```html5
<div nz-form-item>
  <div nz-form-control [nzValidateStatus]="LoginForm.get('PassWord')" nzHasFeedback>
    <nz-input formControlName="PassWord" [nzType]="'password'" [nzPlaceHolder]="'密码'" [nzSize]="'large'">
      <ng-template #prefix>
        <i class="anticon anticon-lock"></i>
      </ng-template>
    </nz-input>
    <div nz-form-explain [innerHtml]="LoginForm.get('PassWord') | tsValidate"
         *ngIf="(LoginForm.get('PassWord').dirty||LoginForm.get('PassWord').touched)&&LoginForm.get('PassWord').errors">
    </div>
  </div>
</div>
```

## Environment

<pre><code>
Angular version: 4.3.5

ng-zorro-antd version: 0.5.0-rc.2

Browser:
- [x] Chrome (desktop) version 60.0.3112.101

Others:

</code></pre>

**Comment by vthinkxie** [comment]
bug confirm, thanks.
