### ISSUE TITLE
[0.7.0-beta.1] form: 触发markAsDirty缺少 has-error 样式

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#1170]
png:

![image](https://user-images.githubusercontent.com/2987467/37563131-18574496-2ab5-11e8-9cd9-6eaac2cc407a.png)

https://stackblitz.com/edit/angular-uszbzy?file=app/app.component.ts

**Comment by vthinkxie** [comment]
miss detect because of angular https://github.com/angular/angular/issues/10887

**Comment by vthinkxie** [comment]
duplicated #1485
