### ISSUE TITLE
select 多选模式点击删除tag会展开下拉框

### ISSUE THREAD

**Issue by 2070255** [NG-ZORRO/ng-zorro-antd#1172]
## Version

0.7.0-beta.1

## Environment

node 8.10.0 chrome

## Steps to reproduce

多选下拉框多选后点击某个tag删除后点击事件冒泡导致触发下拉框展开

## What is expected?

删除已选的tag不触发下拉框展开

## What is actually happening?

删除已选的tag会触发下拉框展开

**Comment by vthinkxie** [comment]
work as design.
