### ISSUE TITLE
tag API文档说明有误

### ISSUE THREAD

**Issue by 2070255** [NG-ZORRO/ng-zorro-antd#1173]
## Version

0.7.0-beta.1

## Environment

node 8.10.0

## Steps to reproduce

无

## What is expected?

nzMode的类型'closable'更正为‘closeable’

## What is actually happening?

nzMode的类型为'closable'

**Comment by vthinkxie** [comment]
@2070255 pr is well come

**Comment by 2070255** [comment]
okay, will pr in next time. :)
