### ISSUE TITLE
input 设置disabled为动态输入属性后可以修改值

### ISSUE THREAD

**Issue by 2070255** [NG-ZORRO/ng-zorro-antd#1175]
## Version

0.7.0-beta.1

## Environment

node 8.10.0

## Steps to reproduce

```
<input nz-input [disabled]="true">
```
在input上将disabled设置为@Input()

## What is expected?

动态设置为disabled为true后不能修改输入框的值

## What is actually happening?

动态设置为disabled为true后可以修改输入框的值

**Comment by vthinkxie** [comment]
work as design.

**Comment by vthinkxie** [comment]
all design was the same as react version, https://ant.design/docs/react/introduce-cn

**Comment by 2070255** [comment]
但是不合理啊，设置disabled为true应该禁止输入更改呀，在input标签上设置disabled="true"能禁用输入，但是设置[disabled]="true"却不能禁用输入

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-zw8g59?file=app/app.component.ts
please provide reproduction link before submit a bug, the input work as design here.

**Comment by 2070255** [comment]
```
<form>
    <input nz-input placeholder="Basic usage" [(ngModel)]="value" [disabled]="true">
    </form>
```
try these bro, not work as design when u use it in form

**Comment by vthinkxie** [comment]
reactive form is not the same as template-driven form, the bug has been fixed already.
duplicated #1166 
that is why you should provide the reproduction link or the reproduction code at least.
otherwise we will waste a lot of time to focus the environment.

**Comment by 2070255** [comment]
thx for your patience.

**Comment by sameer05k21a0440** [comment]
Not working for me
