### ISSUE TITLE
Click 'customize theme', it will be add 'p=/~and~q=' in url, and the page can not load

### ISSUE THREAD

**Issue by heyan12127** [NG-ZORRO/ng-zorro-antd#1184]
## Version

0.7.0-beta.1

## Environment

Chrome 65.0.3325.162

## Reproduction link

[https://ng-zorro-antd-setup-8nmmuc.stackblitz.io](https://ng-zorro-antd-setup-8nmmuc.stackblitz.io)

## Steps to reproduce

Click 'customize theme' in https://ng.ant.design/version/0.7.x/components/icon/en

## What is expected?

Open customize theme page

## What is actually happening?

Can not open customize theme page

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/0.7.x/docs/customize-theme/zh here is link
