### ISSUE TITLE
table: 设置nzShowTotal分页器不显示总条数

### ISSUE THREAD

**Issue by 2070255** [NG-ZORRO/ng-zorro-antd#1189]
## Version

0.7.0-beta.1

## Environment

node 8.10.0 chrome

## Steps to reproduce

在nz-table上设置nzShowTotal

## What is expected?

表格分页器显示数据总条数

## What is actually happening?

表格分页器不显示数据总条数

**Comment by vthinkxie** [comment]
please read the doc carefully before asking.
