### ISSUE TITLE
nz-rangepicker怎么没有月份

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1190]
![bug](https://user-images.githubusercontent.com/16211027/37699226-86ec95d2-2d21-11e8-92ad-0e39f5904c4d.png)
![bug1](https://user-images.githubusercontent.com/16211027/37699261-b3e09818-2d21-11e8-95b2-a260ed57108a.png)

## What problem does this feature solve?

ng-zorro版本0.6.15，nz-rangepicker怎么没有月份的选择只有年份，nz-datepicker就有月份的选择

## What does the proposed API look like?

ng-zorro版本0.6.15，nz-rangepicker能选月份

**Comment by ZuiSong** [comment]
nz-rangepicker can not select month

**Comment by vthinkxie** [comment]
not supported yet. will supported in version 1.0

**Comment by JCqiu** [comment]
@vthinkxie 是0.7.1？还是1.0.0？迫切需要选择月，或者有没有另外的代替的办法

**Comment by simplejason** [comment]
you can use [nz-datepicker](https://ng.ant.design/#/components/date-picker) (the last demo) instead of nz-rangepicker

**Comment by mianxiaoqian** [comment]
在日历弹框打开之后，可以手动在选中的日期那里写
![wechatimg71](https://user-images.githubusercontent.com/33279766/37806775-b5edc23c-2e7c-11e8-8b68-bb0b9fffd523.jpeg)

**Comment by mianxiaoqian** [comment]
@vthinkxie 不是说0.7版本就会放出日历控件吗
![wechatimg72](https://user-images.githubusercontent.com/33279766/37807566-200e7504-2e81-11e8-9e2d-c9fc94863441.jpeg)

**Comment by vthinkxie** [comment]
@mianxiaoqian delay.

**Comment by mianxiaoqian** [comment]
@vthinkxie when would you publish the version 1.0 ?

**Comment by vthinkxie** [comment]
@mianxiaoqian next month after angular 6.0 released.
