### ISSUE TITLE
Could you tell me how long I need to wait for DatePicker?

### ISSUE THREAD

**Issue by Mickxuanyuan** [NG-ZORRO/ng-zorro-antd#1200]
## What problem does this feature solve?

I will update 0.6 -> 0.7, but I need date picker, Could you tell me the estimation about this component?
thanks.

**Comment by vthinkxie** [comment]
next month I am afraid.

**Comment by Mickxuanyuan** [comment]
We can use this component in 0.7 or 1.0? If you tell me we can use in the angular6, I will cry......, I have start a new project and use the 0.7, and I have to finish it in the next month.

**Comment by vthinkxie** [comment]
you can choose other datepicker component instead.

**Comment by Mickxuanyuan** [comment]
So, After updating the angular6, I can use DatePick in ng-zorro?

**Comment by oridark** [comment]
@vthinkxie any advices for other datepicker component ?

**Comment by vthinkxie** [comment]
@oridark you can use https://material.angular.io/components/datepicker/overview as temp solution.
