### ISSUE TITLE
[0.7.0-beta.1] dropdown 宽度问题

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#1203]
### 现状

png: 
![image](https://user-images.githubusercontent.com/2987467/37816524-62768f94-2eae-11e8-90d6-7b20f7bc98ce.png)

### 期望

尽可能默认采用 `width: 100%`，绝大多数场景里会更合理，当需要固定宽度时再指定 `nzWidth` 值。

> 然，这里会涉及多个问题，`nz-dropdown` 大部分场景来自表单，表单默认的 `nz-form-item`、`nz-form-control` 由于 Angular 元素在DOM渲染过程是以 `inline` 形式，`width: 100%` 会受控于父元素的宽度。

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-qeudqa?file=app/app.component.ts there is no width, any reproduction link?

**Comment by cipchk** [comment]
https://stackblitz.com/edit/angular-nd6gxl?file=app/app.component.ts

不过也不全是 nz-select 的原因，暂时关闭。
