### ISSUE TITLE
measureScrollbar() 导致 css3 transition重绘

### ISSUE THREAD

**Issue by rel-wxx** [NG-ZORRO/ng-zorro-antd#1205]
## Version

0.7.0-beta.1

## Environment

mac chrome

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-jx9ywo](https://stackblitz.com/edit/ng-zorro-antd-setup-jx9ywo)

## Steps to reproduce

切换页面

## What is expected?

不触发transition

## What is actually happening?

触发transition

## Other?

https://github.com/NG-ZORRO/ng-zorro-antd/blob/9822bb8945188da15c1cbdfd86a58126c469c16d/components/core/util/mesure-scrollbar.ts#L16

scrollbarWidth == 0 == false

**Comment by rel-wxx** [comment]
。。。。

**Comment by rel-wxx** [comment]
Cascader 默认值通过数组的方式指定，但nzOptions没有赋值，通过nzLoadData函数延迟加载。
====
这个可以不让默认延迟加载吗 因为每个请求需要250ms 4个请求下来需要延迟1秒才能显示数据

**Comment by vthinkxie** [comment]
@rel-wxx thanks for your feedback, we will try to fix it in next version.
