### ISSUE TITLE
[0.7.0-beta] 关于响应式布局更友好的使用建议

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#1207]
### 现状

一般而言需要运用到响应式都会大量的运用 `nzXs`、`nzSm` 等之类，但目前的状况是以格子为单位，即：

```
xl: 6, lg: 8, md: 8, sm: 12, xs: 24
```

来表示 `xl` 屏时每 `6` 格为一个单位（因为 antd 是以 `24` 栅格系统），这不符合开发体验，应该反过来，即，当我们希望 `xl` 屏显示 `4` 个时应该**只需要**填写 `4` 即可，这样更直观。

反观上述一种更直观的写法：

```
xl: 4, lg: 3, md: 3, sm: 2, xs: 1
```

**Comment by vthinkxie** [comment]
这种设计适合栅格数相同并且重复的情况，复杂情况下反而很难理解，比如有(2+3+5+2)*2的情况
