### ISSUE TITLE
the value of DatePicker component is only just Date type?

### ISSUE THREAD

**Issue by YDJSZY** [NG-ZORRO/ng-zorro-antd#121]
when I set the value is like "2017-08-08" and it shows Invalid date

**Comment by vthinkxie** [comment]
only accept Date type.

**Comment by YDJSZY** [comment]
why not support String type ? Will it be change later ?

**Comment by vthinkxie** [comment]
won't change recently

**Comment by YDJSZY** [comment]
well..thanks

**Comment by vthinkxie** [comment]
welcome pr
