### ISSUE TITLE
[0.7.0-beta.1] Cascader init data bug

### ISSUE THREAD

**Issue by pengsoftdotcom** [NG-ZORRO/ng-zorro-antd#1210]
## Version

0.7.0-beta.1

## Environment

macos

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-xz9flq?embed=1&file=app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-xz9flq?embed=1&file=app/app.component.ts)

## Steps to reproduce

set init data for the cascader, then click.

## What is expected?

data in every level will be right

## What is actually happening?

data in first level is blank

**Comment by vthinkxie** [comment]
@fbchen

**Comment by fbchen** [comment]
The method `writeValue` causes 1st column options lost, for not calling the `nzLoadData`. We will fix it soon. Thanks @pengsoftdotcom
