### ISSUE TITLE
[0.7.0-beta.1] Layout or Menu bug

### ISSUE THREAD

**Issue by pengsoftdotcom** [NG-ZORRO/ng-zorro-antd#1216]
## Version

0.7.0-beta.1

## Environment

macos, chrome

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-2hvsej?file=app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-2hvsej?file=app/app.component.ts)

## Steps to reproduce

change static menus to dynamic menus, and **set a leaf menu at index 0, and set a non-leaf menu at index 1**.

## What is expected?

the menus will be rendered with no error.

## What is actually happening?

the menus are rendered with an error, detail as following:

**ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'padding-left: null'. Current value: 'padding-left: 24'**

**Comment by shhdgit** [comment]
Same situation.

**Comment by fuybooo** [comment]
same
