### ISSUE TITLE
Tree树形控件-定义循环模版

### ISSUE THREAD

**Issue by kainOnly** [NG-ZORRO/ng-zorro-antd#1222]
## What problem does this feature solve?

能够让树形控件显示更多自定义字段

## What does the proposed API look like?

希望能有个TemplateRef
如同：https://angular2-tree.readme.io/docs/templates

**Comment by kainOnly** [comment]
What problem does this feature solve?
--
Allows tree control to show more custom fields

What does the proposed API look like?
--

Hope to have a TemplateRef
E.g https://angular2-tree.readme.io/docs/templates

**Comment by simplejason** [comment]
#1221 will support, you can use NzTreeNode.origin to get your custom data

**Comment by kainOnly** [comment]
Okay thanks
