### ISSUE TITLE
Locale 国际化中部分链接无效

### ISSUE THREAD

**Issue by lulushui** [NG-ZORRO/ng-zorro-antd#1223]
## Version

0.7.0-beta.3

## Environment

浏览器版本

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd/issues](https://github.com/NG-ZORRO/ng-zorro-antd/issues)

## Steps to reproduce

1.我们目前提供了英语，中文，其他语言将在后续版本中添加，所有语言包可以在 “这里” 找到。“这里”链接无效 404错误
2.如果你找不到你需要的语言包，欢迎你在 “英文语言包 ”的基础上创建一个新的语言包，并给我们 Pull Request。 “英文语言包 ”链接无效 404错误

## What is expected?

链接到正确地址

## What is actually happening?

链接无效 404错误

**Comment by vthinkxie** [comment]
make sure you have read the correct version of doc.
https://ng.ant.design/version/0.7.x/
