### ISSUE TITLE
Missing locale data for the locale "zh-cn"

### ISSUE THREAD

**Issue by cbyniiaii** [NG-ZORRO/ng-zorro-antd#1227]
## Version

0.7.0-beta.3

## Environment

mac

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-81dwnv](https://stackblitz.com/edit/ng-zorro-antd-setup-81dwnv)

## Steps to reproduce

Getting Started

/src/app/app.component.html
<button nz-button nzType="primary">Button</button>
<nz-calendar [(ngModel)]="date" [(nzMode)]="mode"></nz-calendar>

/src/app/app.component.ts
date = new Date(2012, 11, 21);
  mode = 'month';

## What is expected?

show calendar correct

## What is actually happening?

ERROR Error: Missing locale data for the locale "zh-cn".

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-c6kt3g?file=main.ts
you have to import correct locale package if you want to use calendar
https://ng.ant.design/version/0.7.x/components/calendar/zh#api

**Comment by cbyniiaii** [comment]
```
ng serve
```
 it's work,but 
```
ng build --pord 
```
 it dones work.

**Comment by vthinkxie** [comment]
@cbyniiaii everything works fine in our project, please check your code.

**Comment by cbyniiaii** [comment]
```
providers   : [ { provide: NZ_I18N, useValue: zh_CN } ], 
```
add it will be ok. I think it default zh.

**Comment by vthinkxie** [comment]
@cbyniiaii you can update to 0.7.0-beta.4 to resolve this problem
