### ISSUE TITLE
[select]多选模式下无法选中value值为0的选项

### ISSUE THREAD

**Issue by ppjjzz** [NG-ZORRO/ng-zorro-antd#1229]
## Version

0.7.0-beta.3

## Environment

node 8.10.0 chrome

## Reproduction link

[https://stackblitz.com/edit/angular-uei4kw](https://stackblitz.com/edit/angular-uei4kw)

## Steps to reproduce

设置一个option的value为0

## What is expected?

可以选中value为0的选项

## What is actually happening?

不能选中value为0的选项

**Comment by vthinkxie** [comment]
bug confirm, will be fixed in next version, thanks for your feedback.
