### ISSUE TITLE
[feat] about `nzDate`

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#123]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

i'll depend on `nzDate` pipe operator date format.

but, a `moment` object allow is of various kinds. like:

+ `moment('2011-04-20 07:12:59')`
+ `moment(1503380505000)`
+ `moment(20110420)`
+ more...

the best design of `nzDate`, but just allow time stamp format, and this I regret!

**Comment by vthinkxie** [comment]
`nzDate` pipe is not provided for user actually, you can defined your own pipe by moment.
