### ISSUE TITLE
Submenu displays incorrectly when the parent menu.

### ISSUE THREAD

**Issue by inankai** [NG-ZORRO/ng-zorro-antd#1230]
## Version

0.6.15

## Environment

MacOS, Chrome, ng-zorro 0.6.15

## Reproduction link

[https://ng-zorro-antd-setup-wv72op.stackblitz.io/](https://ng-zorro-antd-setup-wv72op.stackblitz.io/)

## Steps to reproduce

1.Open the parent menu and the submenu.
2.Close the parent menu.
3.Open the parent menu again, we will find the submenu was closed.

## What is expected?

Submenu displays correctly.

## What is actually happening?

Submenu displays incorrectly.

**Comment by vthinkxie** [comment]
fixed in 0.7.0 already
