### ISSUE TITLE
table存在严重性能问题

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#1237]
## Version

0.7.0-beta.3

## Environment

windows 10/chrome 65/ng-zorro@0.7.0-beta.3

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-p5yt76?file=app%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-p5yt76?file=app%2Fapp.component.ts)

## Steps to reproduce

A、在顶部的input中输入123会导致get dataSet方法被大量调用直至页面卡死

B、点击show dialog按钮也会导致get dataSet方法被多次调用

我在console中有输出，具体调用频率可通过开发者工具栏查看
## What is expected?

提高table性能

## What is actually happening?

多种行为都会导致table性能降低

**Comment by vthinkxie** [comment]
@wanghaolu please make sure you have used angular in correct way before you blame us.
https://stackblitz.com/edit/angular-vnkavb?file=app%2Fapp.component.ts
