### ISSUE TITLE
我的项目是基于sass的，但是7.0.x版本要引入的是less文件，无法与我项目兼容，怎么处理

### ISSUE THREAD

**Issue by BluesPeter** [NG-ZORRO/ng-zorro-antd#1239]
## What problem does this feature solve?

解决项目是基于sass开发的问题

## What does the proposed API look like?

 "styles": [
        "../node_modules/ng-zorro-antd/src/ng-zorro-antd.sass"
      ],

**Comment by vthinkxie** [comment]
you can use both less and sass file in angular cli, please read angular cli doc.
