### ISSUE TITLE
NzTree checkedKeys Missing Option

### ISSUE THREAD

**Issue by kainonly** [NG-ZORRO/ng-zorro-antd#1241]
## What problem does this feature solve?

For example: When I only checked a subset,Does not contain the indeterminate parent NzTreeNode.

## What does the proposed API look like?

Hope to have a contain option

**Comment by kainOnly** [comment]
![12afa47b-860c-19b3-6b70-634fee79ea52](https://user-images.githubusercontent.com/9986159/38075135-e0958b00-3363-11e8-97d8-2b8676aa5085.jpg)
![e041fda4-fd01-5e37-6f4c-beb5be46a6ac](https://user-images.githubusercontent.com/9986159/38075142-e2f4cd16-3363-11e8-82f3-e3b6faec625f.jpg)

**Comment by simplejason** [comment]
@kainOnly  you can iterate over this node to get all the children, will support `flatCheckedKeys` (one dimensional array) to get all checked nodes.
**demo:** 
```
  // get node's children. splitCheckedNodeList = []
  deepCheckNode(node: NzTreeNode): void {
    this.splitCheckedNodeList.push(node);
    if (node.getChildren().length > 0) {
      node.getChildren().filter(cNode => cNode.isAllChecked === true).forEach(cNode => {
        return this.deepCheckNode(cNode);
      });
    }
  }
```
