### ISSUE TITLE
[select]多选模式下选中项后下拉框滚动条会跳动

### ISSUE THREAD

**Issue by ppjjzz** [NG-ZORRO/ng-zorro-antd#1245]
## Version

0.7.0-beta.3

## Environment

Windows

## Reproduction link

[https://stackblitz.com/edit/angular-uei4kw](https://stackblitz.com/edit/angular-uei4kw)

## Steps to reproduce

1.下拉框设置多选模式
2.下拉选项多到出滚动条
3.选择较靠后的项

## What is expected?

选中后下拉框的滚动条不跳动

## What is actually happening?

选中后下拉框的滚动条会跳动

**Comment by vthinkxie** [comment]
thanks for your feedback, will be fixed in next version.
