### ISSUE TITLE
NzMessageService配合angular/cdk portal使用报错

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#1246]
## Version

0.7.0-beta.3

## Environment

ng-zorro 0.7.0 beta3

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-2dgxmu?file=app%2Fapp.module.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-2dgxmu?file=app%2Fapp.module.ts)

## Steps to reproduce

1、打开开发者工具栏
2、点击重现链接中的button
3、开发者工具栏提示错误

![tim 20180330085646](https://user-images.githubusercontent.com/9586655/38119961-19286854-33f8-11e8-831a-053f79ebd28d.png)

## What is expected?

无报错，正常使用

## What is actually happening?

报错

**Comment by ppjjzz** [comment]
你需要先在App模块的providers里注册这个服务即可解决

**Comment by wanghaolu** [comment]
@ppjjzz app.component里面直接使用没有问题的，只是在动态加载的组件中使用才会出现这个问题

**Comment by vthinkxie** [comment]
@wanghaolu seems works fine now https://stackblitz.com/edit/ng-zorro-antd-setup-gaczvx?file=app/app.component.html
