### ISSUE TITLE
我想使用选项卡组件再次封装成项目中使用的选项卡组件

### ISSUE THREAD

**Issue by luohong123** [NG-ZORRO/ng-zorro-antd#1247]
## What problem does this feature solve?

angular有什么方法可以封装多个ng-content组件

## What does the proposed API look like?

<nz-tabset 
        nzAnimated="false"
        [nzType]="fcType" 
        [nzShowPagination]="fcShowPagination"
        [nzSize]="fcSize"
        [nzTabPosition]="fcPosition"
        [(nzSelectedIndex)]="fcSelectedIndex">
        <nz-tab [nzDisabled]="fcTabs[0]?.disabled" [hidden]="fcTabs.length<1">
            <ng-template #nzTabHeading>
               {{fcTabs[0]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent1]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[1]?.disabled" [hidden]="fcTabs.length<2">
            <ng-template #nzTabHeading>
            {{fcTabs[1]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent2]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[2]?.disabled" [hidden]="fcTabs.length<3">
            <ng-template #nzTabHeading>
            {{fcTabs[2]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent3]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[3]?.disabled" [hidden]="fcTabs.length<4">
            <ng-template #nzTabHeading>
            {{fcTabs[3]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent4]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[4]?.disabled" [hidden]="fcTabs.length<5">
            <ng-template #nzTabHeading>
            {{fcTabs[4]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent5]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[5]?.disabled" [hidden]="fcTabs.length<6"> 
            <ng-template #nzTabHeading>
            {{fcTabs[5]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent6]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[6]?.disabled" [hidden]="fcTabs.length<7">
            <ng-template #nzTabHeading>
            {{fcTabs[6]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent7]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[7]?.disabled" [hidden]="fcTabs.length<8">
            <ng-template #nzTabHeading>
            {{fcTabs[7]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent8]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[8]?.disabled" [hidden]="fcTabs.length>9">
            <ng-template #nzTabHeading>
            {{fcTabs[8]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent9]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[9]?.disabled" [hidden]="fcTabs.length<10">
            <ng-template #nzTabHeading>
            {{fcTabs[9]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent10]"></ng-content></div>
        </nz-tab>
    </nz-tabset>

**Comment by vthinkxie** [comment]
why not use *ngFor?
