### ISSUE TITLE
dropdowntreeComponent will be which version?

### ISSUE THREAD

**Issue by luohong123** [NG-ZORRO/ng-zorro-antd#1252]
## What problem does this feature solve?

Which version of the drop-down component is released?This function solves the requirement of the tree in the dropdown， I'm really looking forward to it.

## What does the proposed API look like?

I hope API has an online demo.

**Comment by HsuanXyz** [comment]
v1.x [TreeSelect](https://ng.ant.design/components/tree-select/en)
