### ISSUE TITLE
使用nz-rate的ngModel报错

### ISSUE THREAD

**Issue by LiuXiao617111** [NG-ZORRO/ng-zorro-antd#1258]
![image](https://user-images.githubusercontent.com/8858358/38170351-3b31494c-35b6-11e8-9306-79d4f6a3cda4.png)
![image](https://user-images.githubusercontent.com/8858358/38170358-4773764e-35b6-11e8-84c3-e37d82b6097b.png)

如果把ngModel去掉，可以显示nz-rate，就是星星是空的。

**Comment by vthinkxie** [comment]
FormModule?

**Comment by LiuXiao617111** [comment]
yes ，l forget import formmodule in my module

发自我的 iPhone
