### ISSUE TITLE
Can't bind to 'nzPageSizeOptions' since it isn't a known property of 'nz-table'

### ISSUE THREAD

**Issue by wunairuoshi** [NG-ZORRO/ng-zorro-antd#1259]
well,  i just create a table as <nz-table [nzShowSizeChanger]="true" [nzPageSizeOptions]="[20,100,200,1000]" >...</nz-table> ; but it errors with " Can't bind to 'nzPageSizeOptions' since it isn't a known property of 'nz-table' "
And, ng-zorro-antd's version is 0.6.15

**Comment by vthinkxie** [comment]
if you are using 0.6.15, please read the doc of 0.6.15
