### ISSUE TITLE
nz-menu组件在build的时候报错 Supplied parameters do not match any signature of call target.

### ISSUE THREAD

**Issue by canaanjin** [NG-ZORRO/ng-zorro-antd#126]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

我在项目中使用了
[Menu 导航菜单](https://ng.ant.design/#/components/menu) 组件
```
<ul nz-menu [nzMode]="'horizontal'" class="menu-tools">
    <li nz-submenu>
        <span title>File</span>
        <ul class="menu-item-child">
            <li (click)="newFile()">Select PDF</li>
            <li>Open File...</li>
            <li>Save</li>
        </ul>
    </li>
    <li nz-submenu>
        <span title>Edit</span>
        <ul>
        </ul>
    </li>
    <li nz-submenu>
        <span title>View</span>
        <ul>
        </ul>
    </li>
    <li nz-submenu>
        <span title>Go</span>
        <ul>
        </ul>
    </li>
    <li nz-submenu>
        <span title>Help</span>
        <ul>
        </ul>
    </li>
</ul>
```
在使用 _**ng build --prod --aot**_命令进行发布的时候报错
```
ERROR in ng:///D:/Desktop/pdf-tools/src/app/app.component.html (5,31): Supplied parameters do not match any signature of call target.
ERROR in ng:///D:/Desktop/pdf-tools/src/app/app.component.html (5,31): Supplied parameters do not match any signature of call target.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pdf-tools@0.0.0 build: `ng build --prod --aot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pdf-tools@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Canaan_Jin\AppData\Roaming\npm-cache\_logs\2017-08-22T08_24_44_268Z-debug.log
```
指向到了 _**[nzMode]="'horizontal'"**_
```
<ul nz-menu [nzMode]="'horizontal'" class="menu-tools">
```
## Environment

<pre><code>
Angular version:4.2.4

ng-zorro-antd version: 0.5.0-rc.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: 6.9.1  
- NPM version: 5.3.0
- @angular/cli version: 1.3.1
- Platform: Windows  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
please check your `newFile()` function, it should has a param to receive.

**Comment by canaanjin** [comment]
`newFile()`方法没有任何参数的接受
```
  newFile() {
    $(this.selectPDF.nativeElement).click()
  }
```

**Comment by vthinkxie** [comment]
`Supplied parameters do not match any signature of call target` means it is a function that you binding in your template does not match parameters its required, check it again.

**Comment by canaanjin** [comment]
好的 我再去详细看看
