### ISSUE TITLE
i  import module according to the office newsite ,  but 。。。

### ISSUE THREAD

**Issue by BYicon** [NG-ZORRO/ng-zorro-antd#1261]
Error: StaticInjectorError(AppModule)[NzRootModule -> InjectionToken DocumentToken]: 
  StaticInjectorError(Platform: core)[NzRootModule -> InjectionToken DocumentToken]: 
    NullInjectorError: No provider for InjectionToken DocumentToken!
    at _NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10854)
    at _createClass (core.js:10895)
    at _createProviderInstance$1 (core.js:10865)

client:147 [WDS] Warnings while compiling.
warnings @ client:147
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:421
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543
client:153 ./node_modules/_@angular_core@5.2.9@@angular/core/esm5/core.js
6558:15-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/_@angular_core@5.2.9@@angular/core/esm5/core.js
 @ ./node_modules/_ng-zorro-antd@0.6.15@ng-zorro-antd/esm5/antd.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./node_modules/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
warnings @ client:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:421
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543
client:153 ./node_modules/_@angular_core@5.2.9@@angular/core/esm5/core.js
6578:15-102 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/_@angular_core@5.2.9@@angular/core/esm5/core.js
 @ ./node_modules/_ng-zorro-antd@0.6.15@ng-zorro-antd/esm5/antd.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./node_modules/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
warnings @ client:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:421
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543

**Comment by ikecoolon** [comment]
I want to konw how u solve it???    I have same issue.

**Comment by candy4290** [comment]
i have the same issue. no such issue in 0.6.x, but it occured in 0.7.x

**Comment by candy4290** [comment]
@ikecoolon  have you solved it?
