### ISSUE TITLE
lazyload懒加载引入包，报错

### ISSUE THREAD

**Issue by Elliottssu** [NG-ZORRO/ng-zorro-antd#127]
我使用的是angular4 lazyload ,在子模块system.module.ts 引入包，失败
```
//system.module.ts
import { NgZorroAntdModule } from 'ng-zorro-antd';
·····
@NgModule({
    imports: [
         ···
        NgZorroAntdModule.forRoot()
    ]
})
```
![image.png](http://upload-images.jianshu.io/upload_images/3502567-4f68ab9293a29c1e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

报这个错误，官方教程上说在根模块和子模块都引入 但是貌似不起作用
![image.png](http://upload-images.jianshu.io/upload_images/3502567-61e718709181dee1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

不知道是否和环境有关

**Comment by vthinkxie** [comment]
please not use forRoot in your sub module.

**Comment by Elliottssu** [comment]
@vthinkxie root module( app.module.ts imports) is imports ` NgZorroAntdModule.forRoot()` and  sub module(system.module.ts) is  imports` NgZorroAntdModule`, but its still have error:`polyfills.js:7857 Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.`

**Comment by vthinkxie** [comment]
please provide your angular version and your cli version.

**Comment by Elliottssu** [comment]
@vthinkxie  angularV4.3.4 ,webpackV3.5.4,   I didn't use @angular/cli,  Is that the reason?

**Comment by vthinkxie** [comment]
We support both support webpack and angular cli, please check your webpack config.
I recommend you to use cli then use `eject` command to get the correct webpack configuration.
