### ISSUE TITLE
Upload组件怎么传递自定义的header

### ISSUE THREAD

**Issue by test0426775** [NG-ZORRO/ng-zorro-antd#1270]
## What problem does this feature solve?

我使用upLoad组件，但是在上传的时候需要传递自定义的header。如何办到？
另外如果自定义请求的时候怎么获取上传进度？

## What does the proposed API look like?

我使用upLoad组件，但是在上传的时候需要传递自定义的header。如何办到？
另外如果自定义请求的时候怎么获取上传进度？

**Comment by cipchk** [comment]
1、`nzHeaders` 允许以函数传递
2、自定义请求参数细节请参考API文档[nzCustomRequest](https://ng.ant.design/version/0.7.x/components/upload/zh)部分
