### ISSUE TITLE
docs: 所有站内链接点击后都进入无限循环中

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#1271]
GIF：

![asdf](https://user-images.githubusercontent.com/2987467/38308634-4f735fda-384a-11e8-813e-d03f5a4ac14e.gif)

好像是 `404.html` 的代码引起的。

**Comment by vthinkxie** [comment]
this will be ok when 0.7.x be the root folder

**Comment by qifanrui** [comment]
我这边电脑都不能访问了文档网站了，但是手机可以，好奇怪

**Comment by cipchk** [comment]
duplcated of #1184
