### ISSUE TITLE
关于使用table 浏览器报错：ERROR TypeError: Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by zhaopeiym** [NG-ZORRO/ng-zorro-antd#1273]
## Version

0.7.0-beta.3

## Environment

Angular CLI: 1.6.7   Node: 8.9.3   OS: win32 x64   Angular: 5.2.9   typescript: 2.4.2   webpack: 3.10.0   Chrome:64.0.3282.140

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-1qhvq3?file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-1qhvq3?file=app/app.component.html)

## Steps to reproduce

下载到本地，然后执行 ng serve --aot  

（简单一句话：就是使用0.7beta版本，在使用table组件 打包到生产浏览器会报错。）

## What is expected?

正常浏览，没有error

## What is actually happening?

浏览器F12报错：ERROR TypeError: Cannot read property 'locale' of undefined
![image](https://user-images.githubusercontent.com/5820324/38343314-c6944d7a-38b5-11e8-9164-9cbc2a085a91.png)

**Comment by vthinkxie** [comment]
you can set default i18n https://ng.ant.design/version/0.7.x/docs/i18n/zh to skip the error now.

**Comment by vthinkxie** [comment]
closed #1220
