### ISSUE TITLE
NzSelectComponent nz-select 搜索输入框在ios移动端浏览器中无法换出键盘

### ISSUE THREAD

**Issue by guuya-com** [NG-ZORRO/ng-zorro-antd#1274]
## Version

0.7.0-beta.1

## Environment

ios11.3 微信内置浏览器 Safari浏览器

## Reproduction link

[https://stackblitz.com/run](https://stackblitz.com/run)

## Steps to reproduce

在IOS手机移动端，微信浏览器和Safari浏览器中。
使用nz-select nzShowSearch 搜索input中无法输入内容，因为键盘无法换出。
Android手机无此问题

## What is expected?

在IOS手机移动端，微信浏览器和Safari浏览器中nz-select可以换出键盘进行输入

## What is actually happening?

在IOS手机移动端，微信浏览器和Safari浏览器中nz-select无法换出键盘进行输入

**Comment by yunjifen** [comment]
another qustion:
Could you please add `autocapitalize="off"` into nz-select search INPUT or add some ways else?
For IOS browser, default `autocapitalize="on"`, so the search content first letter must be an uppercase letter!
Could you please improve this problem?

**Comment by vthinkxie** [comment]
@yunjifen got it.

**Comment by smile2014** [comment]
select 是否可以提供一个设置聚焦的api ，在form表单上tab切换到select上就默认聚焦了
