### ISSUE TITLE
What's new name of 'NzModalSubject' in 0.7? 

### ISSUE THREAD

**Issue by Eve-1995** [NG-ZORRO/ng-zorro-antd#1279]
## What problem does this feature solve?

Chinese:
在0.6中的NzModalSubject现在叫什么名字?我找了好久也没找到,通过官方API,我只看到了父组件向子组件传递信息的代码
``const instance = modal.getContentComponent();``
但是没有找到子组件向父组件传递信息的代码,能给我个示例吗?
English:
NzModalSubject is version0.6's name,but I don't know it's new name.I spent much time to find it.From official API,I just find parent component transfer data to child component.
``const instance = modal.getContentComponent();``
But not find how child component transfer data to parent component,can u give me a demo?

## What does the proposed API look like?

Chinese:
我不知道是这个功能目前没有还是我没找到关键代码,如果是没有的话,我认为有必要新增一个,子组件向父组件传递消息是一个很常见的应用场景.
English:
I don't know either Ng-Zorro doesn't make it or I didn't find core code.If doesn't make it,Personally,It's a very useful application scene.

**Comment by Liangdi** [comment]
查看 NzModalRef

**Comment by Flcwl** [comment]
@Eve-1995 Hi, can u share with me how to solve it please? I have  the same problem.thx!

**Comment by Eve-1995** [comment]
@Flcwl Sorry,I can't help u.As matter of fact,I did't find the way.
