### ISSUE TITLE
sort header in table is hard to click

### ISSUE THREAD

**Issue by yyegithub** [NG-ZORRO/ng-zorro-antd#1281]
## What problem does this feature solve?

when i click to sort the data in table,I must slowly move my mouse to select asc or desc,it too hard to select,it can be more easy?

## What does the proposed API look like?

may be it can has only click region,in every click,it will be toggle in {null,'ascend','descend'}

**Comment by vthinkxie** [comment]
should be fixed after sync with antd 3.6.1
