### ISSUE TITLE
希望可以支持关闭Message

### ISSUE THREAD

**Issue by baiyunchen** [NG-ZORRO/ng-zorro-antd#1283]
## What problem does this feature solve?

全局提示Message组件，我希望错误消息由用户看清楚了之后，手动关闭。
目前的组件，要么是设置一个自动消失的时间（时间要设置的合理太难），要么就一直停在那里，用户无法操作，只能看。

The global prompt message component, I hope that the error message is manually close it after user understand the message content.
The current component either sets a time that automatically disappears (time is reasonably difficult to set), or it stays there, and the user cannot close it.

## What does the proposed API look like?

```
{
  nzDuration: 3000,
  nzMaxStack: 7,
  nzPauseOnHover: true,
  nzAnimate: true
}
```
这个配置项中增加一个配置项：`nzClosable:true`
Add a setting options in NzMessageDataOptions ：`nzClosable:true`

**Comment by simplejason** [comment]
@baiyunchen  hope this can help you! [loading demo](https://ng.ant.design/version/0.7.x/components/message/zh#components-message-demo-loading)

**Comment by baiyunchen** [comment]
我的意思是，可以由操作的用户点击某个按钮，将message关闭，而不是由开发人员使用代码关闭。

 I mean is that a button can be clicked by the operating user to close the message,not closed by the developer using the code.

**Comment by vthinkxie** [comment]
message does not support close, you can use notification instead.
