### ISSUE TITLE
autocomplete Nzlabel should not affect the submit of form data

### ISSUE THREAD

**Issue by smile2014** [NG-ZORRO/ng-zorro-antd#1298]
## Version

0.7.0-beta.3

## Environment

0.7.0-beta.3

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-ztvtap](https://stackblitz.com/edit/ng-zorro-antd-setup-ztvtap)

## Steps to reproduce

选中12345，保存表单，应该提交的数据是12345，而不是A

## What is expected?

选择的什么保存就是什么，显示不应该影响实际的值

## What is actually happening?

12345

**Comment by smile2014** [comment]
https://stackblitz.com/edit/angular-a6bntv?file=app%2Fautocomplete-display-example.html

**Comment by JCqiu** [comment]
你应该写nzValue="12345",而不是[nvValue]=“12345”

**Comment by smile2014** [comment]
@JCqiu 说白了，我想autocomplete，显示的值和提交的值可以分开。目前好像不支持，类似material2
https://stackblitz.com/edit/angular-a6bntv?file=app%2Fautocomplete-display-example.html

**Comment by JCqiu** [comment]
@smile2014 其实是可以的，我都用了的，是你写法不对而已，0.7.0版很多写法都改变了，多参考文档就可以了

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-sbuyix?file=app/app.component.html please make sure you have used ng-zorro-antd in correct way.

**Comment by smile2014** [comment]
@JCqiu  你能好好看看我贴的material2效果吗。

**Comment by smile2014** [comment]
@vthinkxie 你能看看我贴的 material2的效果吗，谢谢了
https://stackblitz.com/edit/angular-a6bntv?file=app%2Fautocomplete-display-example.html

**Comment by JCqiu** [comment]
@smile2014 你能好好看文档在使用行嘛，不然作者为什么会关掉你的问题

**Comment by smile2014** [comment]
我都去看过源码，压根就不支持，你试试nzvalue是对象你试试

**Comment by smile2014** [comment]
@JCqiu  例如我input里显示name，value 值是{code:'aaa',name:'bb'},作者压根就没细看，提供了一个链接根本就不是我想要的效果
