### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'nz-progress'

### ISSUE THREAD

**Issue by apphost** [NG-ZORRO/ng-zorro-antd#130]
## I'm submitting a issue of <nz-progress>

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

`Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'nz-progress'.
1. If 'nz-progress' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'nz-progress' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

  <nz-progress [ERROR ->][ngModel]="30"></nz-progress>

"):`

## Minimal reproduction of the problem with instructions

1.import NgZorroAntdModule in module ts.
2.add  `  <nz-progress [ngModel]="30"></nz-progress>
` to component html.

## Environment

<pre><code>
Angular version: 4.2.4

ng-zorro-antd version: 0.5.0-rc.2

Browser:
- [x] Chrome (desktop) version  60.0.3112.101 x64
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: v8.3.0  
- Platform: Windows 10 x64 

Others:

</code></pre>

**Comment by vthinkxie** [comment]
duplicated #33 close
