### ISSUE TITLE
表单正则验证错误

### ISSUE THREAD

**Issue by ppjjzz** [NG-ZORRO/ng-zorro-antd#1304]
## Version

0.7.0-beta.3

## Environment

angular 5.2.8

## Reproduction link

[https://stackblitz.com/edit/angular-3un788?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-3un788?file=app%2Fapp.component.ts)

## Steps to reproduce

1.随便输入一串不带数字的字符
2.逐个删除字符

## What is expected?

删除过程中表单验证结果正确

## What is actually happening?

删除过程中表单验证结果不正确，且验证结果经常变换

## Other?

我不确定这个否是angular本身的bug

**Comment by vthinkxie** [comment]
not related to ng-zorro
