### ISSUE TITLE
0.7.x 版本 AOT 编译 运行 报错！！

### ISSUE THREAD

**Issue by wuzhouyang** [NG-ZORRO/ng-zorro-antd#1305]
使用了 `0.7.x`  版本后，aot编译可以通过。但是运行时候会报错，报错信息如下
![image](https://user-images.githubusercontent.com/12148043/38593098-4811701a-3d72-11e8-920e-905d4ad6b9ca.png)
点击报错源大概定位到
![image](https://user-images.githubusercontent.com/12148043/38593143-74d2d99a-3d72-11e8-8458-43551df3b7b1.png)

如果是bug，希望尽快修复此问题

**Comment by vthinkxie** [comment]
https://travis-ci.org/NG-ZORRO/ng-zorro-antd/builds/364501848

**Comment by wuzhouyang** [comment]
@vthinkxie      ?

**Comment by vthinkxie** [comment]
@wuzhouyang please check your code, all ci passed and works fine in our product.

**Comment by wuzhouyang** [comment]
@vthinkxie  AOT build has no problem. The error was printed when I run the project after AOT build.

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/0.7.x/ was built with ng-zorro-antd, and all our project was built with ng-zorro-antd too.

**Comment by wuzhouyang** [comment]
Sorry , is my fault ! Its no a bug.
