### ISSUE TITLE
导航菜单根据路由自动展开子菜单

### ISSUE THREAD

**Issue by whoissj** [NG-ZORRO/ng-zorro-antd#131]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

路由导航到查询用户，刷新页面之后，用户管理就自动收起了，并不会根据当前路由展开

![image](https://user-images.githubusercontent.com/16336139/29598759-7fc9be7a-87fd-11e7-99a4-539555e8977c.png)
![image](https://user-images.githubusercontent.com/16336139/29598830-17c93886-87fe-11e7-90d4-f606cdefb350.png)

## Environment

<pre><code>
Angular version: 4.3.5

ng-zorro-antd version: 0.5.0-rc.2

Browser:
- [ ] Chrome (desktop) version 60
 
For Tooling issues:
- Node version: 6.9.2
- Platform:  Windows

Others:

</code></pre>

**Comment by giscafer** [comment]
use `[nzOpen]="ture"` to control menu expand

**Comment by whoissj** [comment]
@giscafer ok,收到，多谢~

**Comment by gosongs** [comment]
@giscafer true
