### ISSUE TITLE
Popconfirm nzOkType改变按钮类型无效

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1312]
## Version

0.7.0-beta.3

## Environment

win10,chrome65,0.7.0-beta-3

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-eefaxa?file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-eefaxa?file=app/app.component.html)

## Steps to reproduce

Popconfirm nzOkType改变按钮类型无效

## What is expected?

Popconfirm nzOkType有效,增加取消按钮的样式

## What is actually happening?

Popconfirm nzOkType改变按钮类型无效

## Other?

增加取消按钮的样式

**Comment by simplejason** [comment]
Error: `Can't bind to 'nzOkType' since it isn't a known property of 'nz-popconfirm'.` @wilsoncook
