### ISSUE TITLE
Carousel - swipe/draggable option

### ISSUE THREAD

**Issue by skix123** [NG-ZORRO/ng-zorro-antd#1314]
# I'm submitting a...
- [x] Feature request

# Expected behavior
Carousel can support swipe/draggable feature

I can see you're using [Slick](http://kenwheeler.github.io/slick/) elements - they use swipe and draggable options to achieve that.

**Comment by vthinkxie** [comment]
Hi @skix123 , we will not depend on other components expect angular itself, thanks for your suggestion.

**Comment by skix123** [comment]
I didn't mean you have to depend on 3rd party component, it would just be very nice to have a swipe feature. Cheers!

**Comment by vthinkxie** [comment]
@skix123 pr is welcome :)
