### ISSUE TITLE
nz-tree can not used in reactiveform

### ISSUE THREAD

**Issue by yyegithub** [NG-ZORRO/ng-zorro-antd#1323]
## Version

0.7.0-beta.4

## Environment

windows 10 x64, chrome 65.0.3325.181, ng-zorro 0.7.0-beta.4

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-evun5b](https://stackblitz.com/edit/ng-zorro-antd-setup-evun5b)

## Steps to reproduce

```
<form nz-form [formGroup]="form">
  <nz-form-item>
          <nz-tree [(ngModel)]="menus">
          </nz-tree>
  </nz-form-item>
</form>
```
just put nz-tree component in reactivefrom and use ngModel bind data ,it will be error:
```
ngModel cannot be used to register form controls with a parent formGroup directive.  Try using
      formGroup's partner directive "formControlName" instead. 
```
but is I use formControlName to instead ngModel,It will not be display anything!

## What is expected?

Can use formControlName to bind data to nz-tree or other method can use to bind data to nz-tree and can be put in reactiveform

## What is actually happening?

Now can not be used in reactiveform

**Comment by simplejason** [comment]
@yyegithub not nz-tree's error, `If ngModel is used within a form tag, either the name attribute must be set or the form control must be defined as 'standalone' in ngModelOptions. `, you should use  `[ngModelOptions]="{standalone: true}"`
