### ISSUE TITLE
nz-tree  bug

### ISSUE THREAD

**Issue by kisslove** [NG-ZORRO/ng-zorro-antd#1324]
## What problem does this feature solve?

ng-zorro-antd: 0.7.0-beta.4  
渲染树形结构时，控制台错误：ERROR TypeError: _co.nzTreeNode.getChildren is not a function

## What does the proposed API look like?

no error

**Comment by kisslove** [comment]
NzTreeNodeComponent.html:32 ERROR TypeError: _co.nzTreeNode.getChildren is not a function
    at Object.eval [as updateRenderer] (NzTreeNodeComponent.html:37)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:14693)
    at checkAndUpdateView (core.js:13807)
    at callViewAction (core.js:14153)
    at execEmbeddedViewsAction (core.js:14111)
    at checkAndUpdateView (core.js:13803)
    at callViewAction (core.js:14153)
    at execComponentViewsAction (core.js:14085)
    at checkAndUpdateView (core.js:13808)
    at callViewAction (core.js:14153)

**Comment by kisslove** [comment]
@simplejason 
调用堆栈：

View_NzTreeNodeComponent_3 | @ | NzTreeNodeComponent.html:32
-- | -- | --
  | DebugContext_.logError | @ | core.js:14996
  | ErrorHandler.handleError | @ | core.js:1514
  | (anonymous) | @ | core.js:5914
  | ZoneDelegate.invoke | @ | zone.js:388
  | Zone.run | @ | zone.js:138
  | NgZone.runOutsideAngular | @ | core.js:4697
  | ApplicationRef.tick | @ | core.js:5914
  | (anonymous) | @ | core.js:5740
  | ZoneDelegate.invoke | @ | zone.js:388
  | onInvoke | @ | core.js:4749
  | ZoneDelegate.invoke | @ | zone.js:387
  | Zone.run | @ | zone.js:138
  | NgZone.run | @ | core.js:4566
  | next | @ | core.js:5740
  | schedulerFn | @ | core.js:4331
  | SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:243
  | SafeSubscriber.next | @ | Subscriber.js:190
  | Subscriber._next | @ | Subscriber.js:131
  | Subscriber.next | @ | Subscriber.js:95
  | Subject.next | @ | Subject.js:56
  | EventEmitter.emit | @ | core.js:4311
  | checkStable | @ | core.js:4714
  | onHasTask | @ | core.js:4762
  | ZoneDelegate.hasTask | @ | zone.js:441
  | ZoneDelegate._updateTaskCount | @ | zone.js:461
  | Zone._updateTaskCount | @ | zone.js:285
  | Zone.runTask | @ | zone.js:205
  | drainMicroTaskQueue | @ | zone.js:595
  | Promise resolved (async) |   |  
  | scheduleMicroTask | @ | zone.js:578
  | ZoneDelegate.scheduleTask | @ | zone.js:410
  | onScheduleTask | @ | zone.js:297
  | ZoneDelegate.scheduleTask | @ | zone.js:401
  | Zone.scheduleTask | @ | zone.js:232
  | Zone.scheduleMicroTask | @ | zone.js:252
  | scheduleResolveOrReject | @ | zone.js:862
  | resolvePromise | @ | zone.js:808
  | (anonymous) | @ | zone.js:724
  | webpackJsonpCallback | @ | inline.bundle.js:22
  | (anonymous) | @ | document.module.chunk.js:1

**Comment by simplejason** [comment]
@kisslove  have you Initializd data with `new NzTreeNode`? like this [demo](https://ng-zorro.github.io/version/0.7.x/components/tree/zh#components-tree-demo-basic) . nz-tree accepts `NzTreeNodes[]`.

**Comment by kisslove** [comment]
@simplejason 
yes,
like html:
    <nz-tree  [ngModel]="nodes" >
    </nz-tree>
ts:
  nodes = [new NzTreeNode({
    title   : 'root1',
    key     : '1001',
    children: []
  }),
  new NzTreeNode({
    title   : 'root2',
    key     : '1002',
    children: []
  }),
  new NzTreeNode({
    title: 'root3',
    key  : '1003'
  })];

**Comment by kisslove** [comment]
@simplejason 
it's my problem,it must use new NzTreeNode,thanks.
