### ISSUE TITLE
级联选择器Cascader进行动态加载时Promise方法中的this指向错误

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#1327]
## Version

0.7.0-beta.4

## Environment

0.7.0 beta4

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-ry9e5k?file=app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-ry9e5k?file=app/app.component.ts)

## Steps to reproduce

我按照官网的示例，只是将province等数据放到了component中，导致无法显示出选项

## What is expected?

在promise中使用this应该指向cascader所在的父组件，而非cascader其本身

## What is actually happening?

this指向了cascader自己导致this无法获取父组件中的属性值

**Comment by vthinkxie** [comment]
basic javascript problem, what the this point to is not determined by ng-zorro, it is defined by your code
https://stackblitz.com/edit/ng-zorro-antd-setup-t9kvok?file=app/app.component.ts

**Comment by nieshiming** [comment]
loadData.bind(this)       this way can fix it
