### ISSUE TITLE
You cannot get DOM (document.getElementById ('test')) in the hook function of components created through Modal services.

### ISSUE THREAD

**Issue by shiyu123** [NG-ZORRO/ng-zorro-antd#1328]
## Version

0.7.0-beta.4

## Environment

Google Chrome 63.0.3239.132

## Reproduction link

[https://ng-zorro-antd-setup-bsgujw.stackblitz.io](https://ng-zorro-antd-setup-bsgujw.stackblitz.io)

## Steps to reproduce

1. Components created through Modal services
```
this.modalService.create({
    nzContent: TestComponent
});
```
2. In ngOnInit or other hook functions, Dom is obtained through document.getElementById ('test').
```
ngOnInit() {
    this.test = document.getElementById('test');
    console.log(this.test);
  }
```

## What is expected?

I can get my don right away in hook function, because some third party components are initialized by document.getElementById.

## What is actually happening?

No response because there was no access to Dom

## Other?

Initializing TinyMCE in modal components

**Comment by vthinkxie** [comment]
please read the doc carefully
获取对话框内容中nzContent的Component实例instance。注：当对话框还未初始化完毕（ngOnInit未执行）时，此函数将返回undefined
https://stackblitz.com/edit/ng-zorro-antd-setup-yngbtx?file=app/test/test.component.ts
