### ISSUE TITLE
hi, ng-zorro-antd documents has a problem

### ISSUE THREAD

**Issue by zhangyuyuan123** [NG-ZORRO/ng-zorro-antd#1331]
http://ng-zorro.gitee.io/docs/customize-theme/zh   

URL cannot be opened ,Please fix it in time ，thanks

**Comment by zhangyuyuan123** [comment]
@vthinkxie in the http://ng-zorro.gitee.io/version/0.7.x/components/icon/zh     customize theme
-

**Comment by vthinkxie** [comment]
it will be ok after 0.7.0 be the default version.
