### ISSUE TITLE
how to use NzTreeService

### ISSUE THREAD

**Issue by kisslove** [NG-ZORRO/ng-zorro-antd#1332]
## What problem does this feature solve?

更新日志中：
1.nzTreeData 变更为 ngModel, 初始化数据使用 new NzTreeNode({}),请参阅示例
2.新增 origin 属性存储用户原始数据
3.支持根据 NzTreeComponent 上下文获取 NzTreeService
第3条中表明支持获取NzTreeService， 怎样获取NzTreeService？有例子吗？

## What does the proposed API look like?

html:  <nz-tree  #tree  [ngModel]="nodes"
         </nz-tree>
 ts:   @ViewChild('tree') tree: NzTreeComponent;

**Comment by simplejason** [comment]
@kisslove  `this.tree.nzTreeService` , will provide the demo

**Comment by kisslove** [comment]
@simplejason  
在nz-tree.component.d.ts中：
export declare class NzTreeComponent implements OnInit {
    private nzTreeService;
    ....
}
这里是private，在外层使用this.tree.nzTreeService编译不过的

**Comment by simplejason** [comment]
@kisslove my mistake, will fix it and provide demos soon, thanks!
