### ISSUE TITLE
ng-zorro-antd 0.7.0 Is it possible to deploy the icon locally?

### ISSUE THREAD

**Issue by zhangyuyuan123** [NG-ZORRO/ng-zorro-antd#1336]
ng-zorro-antd 0.7.0 Is it possible to deploy the icon locally?

**Comment by vthinkxie** [comment]
read the doc carefully.
https://ng.ant.design/version/0.7.x/docs/customize-theme/zh

**Comment by zhangyuyuan123** [comment]
@vthinkxie Please provide examples
