### ISSUE TITLE
Modal对话框支持拖动功能

### ISSUE THREAD

**Issue by baiyunchen** [NG-ZORRO/ng-zorro-antd#1337]
## What problem does this feature solve?

使用Modal做数据新增或编辑的时候，有时候用户如果想参考现有的数据，但Modal可能会挡住数据，如果Modal可以拖动，那将是极好的~

## What does the proposed API look like?

nzAllowDrag="true"

**Comment by vthinkxie** [comment]
please track #1291

**Comment by baiyunchen** [comment]
@vthinkxie  thanks!
