### ISSUE TITLE
Select，radio and check component whether support readonly attributes？

### ISSUE THREAD

**Issue by luohong123** [NG-ZORRO/ng-zorro-antd#1338]
## What problem does this feature solve?

下拉框、单选框、多选框支持只读属性，和禁用属性有所区别

## What does the proposed API look like?

online

**Comment by vthinkxie** [comment]
just add the style below to the component you want to set to readonly
```css
pointer-events: none;
```
select, radio, check has no readonly attributes.

**Comment by luohong123** [comment]
Thank you. According to your method, this problem has been solved.
