### ISSUE TITLE
input support nzDisabled

### ISSUE THREAD

**Issue by cbyniiaii** [NG-ZORRO/ng-zorro-antd#1340]
## What problem does this feature solve?

解决了input只能查看，不能编辑的功能。

## What does the proposed API look like?

<input type="text" nz-input [nzDisabled]="true">

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/0.7.x/components/input/zh
nz-input 可以使用所有的W3C标准下的所有 使用方式 和 Angular对 input 的全部额外功能支持。
