### ISSUE TITLE
关于calendar获取数据的行为

### ISSUE THREAD

**Issue by selegiline** [NG-ZORRO/ng-zorro-antd#1343]
## Version

0.7.0-beta.4

## Environment

chrome 

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-jgt3nm](https://stackblitz.com/edit/ng-zorro-antd-setup-jgt3nm)

## Steps to reproduce

官方关于calendar示例的第二个 ， 在component中getListData方法的第一行加入console.log(date);  

## What is expected?

这个方法执行的次数应该跟当前月份显示的天数一致，

## What is actually happening?

 控制台每隔不到1秒就会打印当前月份的所有日期，stackblitz执行大概2000次以上就无响应了

## Other?

请问这是正常的行为吗？官方示例中dateCell渲染badge没有问题， 但渲染带有动态数据的tag浏览器会直接没有响应。

**Comment by vthinkxie** [comment]
直接在模板中绑定的function执行的次数取决于doCheck钩子函数执行的次数，angular进行过多少次脏值检查，这个function就会执行多少次
