### ISSUE TITLE
无法在calendar中使用tag

### ISSUE THREAD

**Issue by selegiline** [NG-ZORRO/ng-zorro-antd#1346]
## Version

0.7.0-beta.4

## Environment

chrome

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-goqfwk](https://stackblitz.com/edit/ng-zorro-antd-setup-goqfwk)

## Steps to reproduce

见stackblitz

## What is expected?

正常使用

## What is actually happening?

页面卡死

**Comment by vthinkxie** [comment]
ngFor在使用时永远不应该从一个函数中获取数据，每次doCheck的时候 ngFor都会被重新渲染一遍
https://stackblitz.com/edit/ng-zorro-antd-setup-xaenmz?file=app/app.component.html

官方指南假设你已了解关于 HTML、CSS 和 JavaScript 的中级知识，并且已经完全掌握了 Angular 及配套设施的正确开发方式。如果你刚开始学习前端或者 Angular ，将框架作为你的第一步可能不是最好的主意 —— 掌握好基础知识再来吧！

**Comment by selegiline** [comment]
既然ngFor在使用时永远不应该从一个函数中获取数据， 那为何官方文档还给出这样的用法呢？
https://ng.ant.design/version/0.7.x/components/calendar/zh

![image](https://user-images.githubusercontent.com/31548229/38912700-5aa3387a-4309-11e8-984f-4a5dad77a092.png)

**Comment by vthinkxie** [comment]
@selegiline 我们下次会修复
