### ISSUE TITLE
input error explain text cause elements blick in firefox

### ISSUE THREAD

**Issue by SunGuoQiang123** [NG-ZORRO/ng-zorro-antd#1349]
## Version

0.7.0-beta.4

## Environment

Linux ubuntu 15.04  firefox 59.04 

## Reproduction link

[https://angular-n7jlea.stackblitz.io](https://angular-n7jlea.stackblitz.io)

## Steps to reproduce

1 type something in any input item make it satisfy the verification
2 make this input item  switch from right to error
3 the elements behind this input blink 

## What is expected?

the elements behind the input do not blink

## What is actually happening?

when switch the input status between right and error , the elements behin the input blink

## Other?

when you click very fast in chrome this problem also occurs

**Comment by vthinkxie** [comment]
@SunGuoQiang123 could you please provide an gif, I can not reproduce it in firefox in my computer

**Comment by vthinkxie** [comment]
fixed in 1.0 version, you can reopen it if it still happened.
