### ISSUE TITLE
click a button ,how to clear the contents of the select component

### ISSUE THREAD

**Issue by luohong123** [NG-ZORRO/ng-zorro-antd#1350]
## What problem does this feature solve?

For example,click a button to add the new page to clear the contents of the select component. Which attribute should be use?(中文：点击新增按钮到新增页面，用的是[hidden]实现页面的显示隐藏，无法清除已选中的下拉内容，现在想清除下拉选中的内容，应该使用哪个属性呢？nzAllowClear是允许清除选中内容，我看了有clearSelect($event?: MouseEvent): void;)这个事件，不知道如何使用，能否实现这个功能）

## What does the proposed API look like?

online

**Comment by vthinkxie** [comment]
angular是数据驱动的框架
