### ISSUE TITLE
nz-checkbox-wrapper：外部设置 `width` 无效

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#1358]
## 重现

png:

![tim 20180422002311](https://user-images.githubusercontent.com/2987467/39086415-68c2f10e-45c3-11e8-8f10-24d13f3df91e.png)

## 原因

`ant-checkbox-group` 样式应该附加在组件上，而非再单独一层 `div`

**Comment by vthinkxie** [comment]
fixed in #1577
