### ISSUE TITLE
BUG：由于打包样式顺序导致部分样式无效

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#1360]
## 原因

样式文件 `.css` 的顺序会影响优先级，例如目前 zorro 生成的顺序 ：

```style

@media (max-width: 575px) {
    .ant-form-item-label { width: 100%; }
}

.ant-col-4 { width: 16.66666667%; }

```

若某个元素应用如下：

```html
<nz-form-label class="ant-col-4 ant-form-item-label"></nz-form-label>
```

则 `ant-col-4` 样式始终优先，倒置在 `575px` 以下屏幕无法应用 `ant-form-item-label` 值。

PNG：

![tim 20180422142852](https://user-images.githubusercontent.com/2987467/39092159-81b59b78-4639-11e8-965e-83755aadd59b.png)

## 解决办法

ant-design 由于将 `col` 做为独立的目录存在，在打包过程中获取的 less 文件按字母排序，因此 ant-design 会优先加载。

反之，zorro 的 col 是做为 grid 的问题，这导致 `form` 比 `grid` 来得优先。

**建议：** 保持完整的 `components` 目录结构。

**Comment by leemove** [comment]
遇到了同样的问题 日期选择器样式 会覆盖表单的部分样式.

**Comment by vthinkxie** [comment]
fixed
