### ISSUE TITLE
input框disabled不起作用

### ISSUE THREAD

**Issue by fashiontai** [NG-ZORRO/ng-zorro-antd#1362]
在看了源码之后，发现当在input里面动态添加[disabled]="disabled"时，样式会发生改变，但是不会禁掉input框。
修改方案：
@Input()
  @HostBinding(`class.ant-input-disabled`)
  set disabled(value: boolean) {
    this._disabled = toBoolean(value);
    if (toBoolean(value)) {
      this.renderer.setAttribute(this.el, 'disabled', 'disabled');
    }else {
      if (this.el.getAttribute('disabled')) {
        this.renderer.removeAttribute(this.el, 'disabled');
      }
    }
  }

  get disabled(): boolean {
    // if (this.ngControl && this.ngControl.disabled !== null) {
    //   return this.ngControl.disabled;
    // }
    return this._disabled;
  }

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-cbtqau?file=app/app.component.ts

**Comment by fashiontai** [comment]
我在您的0.7官网上，代码演示
当有表单验证时，点击编辑按钮，在input上添加[disabled]="true",不起作用。

**Comment by vthinkxie** [comment]
ReactiveForm != TempalateForm
