### ISSUE TITLE
Current less styles not compatible with angular-cli 6.X

### ISSUE THREAD

**Issue by csyszf** [NG-ZORRO/ng-zorro-antd#1363]
## What problem does this feature solve?

relate issue: https://github.com/ant-design/ant-design/issues/7927

Angular-cli 6.X uses higer versions of webpack/less which disable inline javascript by default,
and angular-cli projects couldn't config less-loader,
so [some .less](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/color/bezierEasing.less) could not be compiled.

## What does the proposed API look like?

angular-cli projects could be built successfully

**Comment by vthinkxie** [comment]
ref https://github.com/angular/angular-cli/issues/10430

**Comment by jakechan2012** [comment]
如果不使用 Angular 6.0，可以用一个临时方案保证项目的正确运行，`package.json`增加一个脚本

```bash
npm i -D less
```

```json
"scripts": {
  "prestart": "lessc src/styles.less src/styles.css --js"
}
```

`angular.json` 中响应的把 styles.less 改成 styles.css


=====

另外，希望 Zorro 可以尽快适配 rxjs 6.x，🙏🙏谢谢

**Comment by vthinkxie** [comment]
angular cli fixed
