### ISSUE TITLE
0.7.x不向下兼容0.6.x

### ISSUE THREAD

**Issue by oridark** [NG-ZORRO/ng-zorro-antd#1365]
## What problem does this feature solve?

迁移困难，公司项目刚用0.6.x写了一个模块，然后0.7.x发布了，升级后大规模报错，发现很多参数名以及方法都有变化，有49年入国·军的感觉。。。。

## What does the proposed API look like?

来一份迁移文档

**Comment by vthinkxie** [comment]
https://ng-alain.com/6to7

**Comment by sunscheung** [comment]
0.7.x不向下兼容0.5.x ，可否来一份迁移文档？
