### ISSUE TITLE
Error ENOENT: no file open 'ng-zorro-antd/index.js' when using with ionic 3

### ISSUE THREAD

**Issue by Jeffen** [NG-ZORRO/ng-zorro-antd#137]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

Display an error when trying to introduce the module into ionic root module(``app.module.ts``) and came 
up with following messages:
```
Module build failed: Error: ENOENT: no such file or directory, open 'C:\proj\ottApp\node_modules\ng-zorro-antd\index.js'
    at Error (native)
```
But test normal in ``ng new`` project.
## Expected behavior

ng-Zorro can be introduced into ionic

## Minimal reproduction of the problem with instructions

1. initiate ionic3 and install ng-zorro-antd as a dependency.
2. introduce ``NgZorroAntdModule`` in root module
3. ``ionic serve``
## Environment

<pre><code>
Ionic Framework: 3.6.0
Ionic App Scripts: 2.1.4
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.11.2
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

Others:

</code></pre>

**Comment by vthinkxie** [comment]
ionic and mobile is not supported yet.
