### ISSUE TITLE
nzAutosize性能差

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#1370]
## Version

0.7.0-beta.3

## Environment

Windows10专业版 、Google Chrome版本 66.0.3359.27（正式版本）dev （64 位）， 0.7.0-beta.3

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-tuaoti?file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-tuaoti?file=app/app.component.html)

## Steps to reproduce

接口请求30ms以内，页面加载却10000ms左右。

## What is expected?

支持[attr.row]="d.rows"。 或者[nzAutosize]="true"优化性能。

## What is actually happening?

1： row="4"无效；
2： [nzAutosize]="true"当textarea有一百个时，加载特别慢。

## Other?

`<div class="api-one" *ngFor="let d of data; index as di">
            <h3 *ngIf="di===0||d.service!==data[di-1].service" [id]="d.service"><nz-tag [nzColor]="'#87d068'">{{d.service}}</nz-tag></h3>
            <h2 [id]="d.hid">{{d.api}}</h2>
            <div class="api-return">返回值：{{d.return}}</div>
            <div class="api-doc">
                <textarea [attr.row]="d.rows" nz-input [ngModel]="d.doc" readonly></textarea>
            </div>
      </div>`

**Comment by liwei511** [comment]
item.rows = item.doc.split('\n').length * 23 + 'px';
我的解决方法是，算出高度，设置[style.height]="d.rows"。非常快

**Comment by HsuanXyz** [comment]
是 `textarea[rows]` 不是 `textarea[row]`，[textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea)
