### ISSUE TITLE
ng-zorro-antd/src does not contain less file

### ISSUE THREAD

**Issue by VladimirHumeniuk** [NG-ZORRO/ng-zorro-antd#1372]
After installing ng-zorro-antd, folder `node_modules/ng-zorro-antd/src/` does not contain` ng-zorro-antd.less` file, so i have error: 

> ERROR in multi ./node_modules/ng-zorro-antd/src/ng-zorro-antd.less
> Module not found

**Comment by vthinkxie** [comment]
@VladimirHumeniuk make sure you have installed correct version
npm install ng-zorro-antd@next
