### ISSUE TITLE
nztable新增数据视图不刷新

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1373]
## Version

0.7.0-beta.4

## Environment

win10，chrome65，0.7.0-beta.4

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-38huvb?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-38huvb?file=app%2Fapp.component.html)

## Steps to reproduce

新增一条数据的时候视图不刷新

## What is expected?

新增一条数据的时候视图刷新

## What is actually happening?

新增一条数据的时候视图不刷新

**Comment by hamdiwanis** [comment]
when you push to an array (i.e using the .push operator) the reference to the array does not change, so change detection does not kick in as for it nothing changed.

**Comment by JCqiu** [comment]
@hamdiwanis what can i do

**Comment by hamdiwanis** [comment]
instead of 
```
 this.dataSet.push({
      key: '666',
      name: 'Joe Black',
      age: 32,
      address: 'Sidney No. 1 Lake Park'
    })
```
use this 
```
this.dataSet = [...this.dataSet, {
      key: '666',
      name: 'Joe Black',
      age: 32,
      address: 'Sidney No. 1 Lake Park'
    }]
```

**Comment by JCqiu** [comment]
@hamdiwanis thanks
