### ISSUE TITLE
关于checkbox多选框的group

### ISSUE THREAD

**Issue by Charles953** [NG-ZORRO/ng-zorro-antd#138]
当使用nz-checkbox-group时，ngModel使用用户定义的数组进行存储checkbox中的value是否更适合，而不是把整个options传入ngModel中，这样提交表单只需要关注选中的checkbox，不需要关注整个options数组对象

**Comment by vthinkxie** [comment]
maybe it is a good idea, but it will bring break changes.
to be discussed later.

**Comment by cipchk** [comment]
一方面： `values.map(item => item.value)` 也算简单。

另一方面，也可以考虑增加一个额外的属性标识，例如：`[nzOnlyValue]="true"` 返回 `value` 属性值数组。

**Comment by bokire** [comment]
一方面：`values.map(item => item.value)`之前要先判断`item.checked`。
另一方面：建议options和ngModel应该是两个不同的值，options负责整个控件的逻辑，ngModel负责控件的结果。
另一方面：可以考虑对options设置一个索引属性，例如：`[nzOptionIndex]="value"` 返回`value`属性值数组，同时初始时根据`value`属性值来判断`option`是否被选择。默认不设置，则返回整个`option`对象。(ps:其实还有需求，只返回`option`中的若干个属性作为结果[捂脸]。这个最好开放`ngModelChange`方法，让用户自己实现。包括初始化方法。)

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/0.7.x/components/checkbox/zh#components-checkbox-demo-layout
