### ISSUE TITLE
希望表格能支持指定列的显示和隐藏

### ISSUE THREAD

**Issue by freeMan-qian** [NG-ZORRO/ng-zorro-antd#1383]
## What problem does this feature solve?

在查看数据时，只需要看到自己想看的列，而不是全部

## What does the proposed API look like?

定义一个属性集合如 [{key:"",IsShow:}]   使用的时候，在th或者td加个属性，传入key。然后决定是否显示列，如果传入的key不存在，则默认显示

**Comment by vthinkxie** [comment]
`*ngIf` or `hidden`

**Comment by freeMan-qian** [comment]
[hidden]="getShowHideByKey('name')"
  fieldSettting = [
    { key: "name", IsShow: false,lable:""},
    { key: "fullName", IsShow: false ,lable:""},
 
  ];
  getShowHideByKey(key) {
    
    var isShow=true;
    for (var i = 0; i < this.fieldSettting.length;) {
      if (this.fieldSettting[i].key == key) {
        isShow= false;
        break;
      }   
    }
    console.log(isShow);
    return isShow;
  }

I try to do this, but I keep calling the method and cannot hide it

**Comment by vthinkxie** [comment]
repro link?

**Comment by freeMan-qian** [comment]
Can't provide address temporarily. Is this correct?

**Comment by vthinkxie** [comment]
Any Angular html syntax ** must can work ** in `nz-table`. If not, please check your code.
We can not offer any help without repro link.

**Comment by freeMan-qian** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-mt8wuo?file=app/app.component.ts

If I unlock the code below, the page is stuck. Please help me see why.
code:
/* for (var i = 0; i < this.fieldSettting.length;) {
      if (this.fieldSettting[i].key == key) {
        isShow= false;
        break;
      }   
    } */

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-r9ajdr?file=app/app.component.ts `nz-table` work fine as intend.

**Comment by freeMan-qian** [comment]
for (var i = 0; i < this.fieldSettting.length;) {
if (this.fieldSettting[i].key == key) {
isShow= false;
break;
}
} 

My purpose is to show that the key exists. If it does not exist, it is not displayed.
[hidden]="getShowHideByKey('name')"

**Comment by freeMan-qian** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-z1j15i?file=app/app.component.ts
not  run
Do not annotate
  /* for (var i = 0; i < this.fieldSettting.length;) {
      if (this.fieldSettting[i].key == key) {
        isShow= false;
        break;
      }   
    } */
Please run 
 getShowHideByKey(key) {    
    var isShow=false;
    for (var i = 0; i < this.fieldSettting.length;) {
      if (this.fieldSettting[i].key == key) {
        isShow= false;
        break;
      }   
    } 
    return isShow;
  }

**Comment by freeMan-qian** [comment]
Please run
getShowHideByKey(key) {      //Each column is loaded  call
var isShow=true;   // Default does not display   
for (var i = 0; i < this.fieldSettting.length;) {
if (this.fieldSettting[i].key == key) {  //  if  Meet the conditions to show
isShow= false;
break;
}
}
return isShow;
}

**Comment by vthinkxie** [comment]
your code is totally wrong.
```
for (var i = 0; i < this.fieldSettting.length;) 
```
is a **dead lock**

https://stackblitz.com/edit/ng-zorro-antd-setup-r9ajdr?file=app%2Fapp.component.ts

please do not ask question like this any longer.

**Comment by freeMan-qian** [comment]
I'm terribly sorry, I didn't notice
I'm so careless, I'm sorry
Excuse me, thank you

**Comment by vthinkxie** [comment]
you can use https://ng-alain.com/components/simple-table

**Comment by freeMan-qian** [comment]
好的，谢谢，我先看看
