### ISSUE TITLE
In the upload component, I want to use the photo wall preview image and multi-file upload at the same time, what to do.

### ISSUE THREAD

**Issue by ohmygodoh** [NG-ZORRO/ng-zorro-antd#1392]
## Version

0.7.0-beta.4

## Environment

win10 google

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-qumg3y](https://stackblitz.com/edit/ng-zorro-antd-setup-qumg3y)

## Steps to reproduce

I combined the code of the two samples and found that the picture can be previewed, but multiple files are not received in the background

## What is expected?

 I want to use the photo wall preview image and multi-file upload at the same time.

## What is actually happening?

I combined the code of the two samples and found that the picture can be previewed, but multiple files are not received in the background

**Comment by cipchk** [comment]
The default upload is one by one, allows for advanced customization by overriding default behavior via `nzCustomRequest`.
