### ISSUE TITLE
升级material 6.0报错

### ISSUE THREAD

**Issue by ppjjzz** [NG-ZORRO/ng-zorro-antd#1395]
## Version

0.7.0-beta.5

## Environment

ng 6.0, angular-cli 6.0

## Steps to reproduce

ng update @angular/material

## What is expected?

能升级不报错

## What is actually happening?

D:\ad-platform-fe\yisike>ng update @angular/material
                  Package "ng-zorro-antd" has an incompatible peer dependency to "@angular/cdk" (requires "^5.0.0", would install "6.0.0").
Incompatible peer dependencies found. See above.

**Comment by vthinkxie** [comment]
not support 6.0 yet.

**Comment by ppjjzz** [comment]
and there are also lots of issues with update rxjs 6.0

**Comment by vthinkxie** [comment]
yes, rxjs 6.0 is not compatible with 5.0

**Comment by wanghaolu** [comment]
希望下个beta版支持ng6.0

**Comment by thanatos915** [comment]
i hope konw how long to support 6.0.

**Comment by vthinkxie** [comment]
please track #1406 now

**Comment by qiangyongjun918** [comment]
also
