### ISSUE TITLE
使用tree，打包时报错

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#1398]
只要导入了：import { NzTreeComponent, NzTreeNode } from 'ng-zorro-antd';
打包：ng build --prod --base-href --output-hashing=bundles ./ 
报错：Module not found: Error: Can't resolve 'ng-zorro-antd/src/tree/public-api' in 'C:\GitDevGroup\bms\bms-acct\src\app\routes\account-management'
测试运行时：ng serve --host 10.110.1.194 -port 4203 -o  没问题。

package: 
    "ng-zorro-antd": "^0.7.0-beta.5",
    "@angular/cli": "~1.7.3",
    "@angular/core": "^5.2.0",

**Comment by vthinkxie** [comment]
https://travis-ci.org/NG-ZORRO/ng-zorro-antd/builds/373527535 所有的build prod ci测试都是通过的，请检查一下自己的代码。

**Comment by liwei511** [comment]
多谢@vthinkxie 。可是创建新项目，引入tree， 仍然报错Module not found: Error: Can't resolve 'ng-zorro-antd/src/tree/public-api'。

**Comment by vthinkxie** [comment]
@simplejason

**Comment by simplejason** [comment]
@liwei511 can you share your codes(where u import tree)，I use `import { NzTreeComponent, NzTreeNode } from 'ng-zorro-antd';` and build successfully。

**Comment by liwei511** [comment]
thank you @simplejason 。
this is my project: 
link：https://pan.baidu.com/s/1_9UV8xskwxUBaGURLj3lcQ password：7afg

my account-management's Module file has imported NgZorroAntdModule
`import { NgZorroAntdModule } from 'ng-zorro-antd';
@NgModule({
  declarations: [
    AppComponent,
    AccountManagementComponent,
    RoleManagementComponent,
    AuthorityManagementComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    BrowserAnimationsModule,
    LayoutModule,
    PublicModule,
    NgZorroAntdModule.forRoot(),
    AppRoutingModule
  ],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  providers: [
    {provide: LocationStrategy, useClass: HashLocationStrategy},
    Service,
    ToolService,
  ]
})
`

**Comment by liwei511** [comment]
@vthinkxie  谢谢，已提交stackbliz的项目本地打包没问题。只有网盘中项目可以重现。抱歉。一定是我没有找对出错的地方。
