### ISSUE TITLE
Use angular commit message format

### ISSUE THREAD

**Issue by yokots** [NG-ZORRO/ng-zorro-antd#14]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

See [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines)

**Comment by wilsoncook** [comment]
As release candidate, we're about to improve the PR & Contributing specifications, thanks for your attention !
