### ISSUE TITLE
图标 i 标签的的伪类before样式没有引入进来

### ISSUE THREAD

**Issue by longjichun** [NG-ZORRO/ng-zorro-antd#140]
页面不存在 类似 .anticon-search:before {    content: "\E670";} 的样式。按照官网所示，不知是否缺了哪个步骤。iconfont已解压放置相应目录，指令属性已添加。

**Comment by vthinkxie** [comment]
https://zhuanlan.zhihu.com/p/25795393

**Comment by LinBoLen** [comment]
I 
feel 
i will get 
beat up from 
zorro 
team 
after reading 
"https://zhuanlan.zhihu.com/p/25795393"


remind me that i make so many mistakes in open source project's discussion.

also i need to jinshen di go home or office. maybe when i discuss on the road, someone will 

Stab me in the back
--

😂😂😂

**Comment by longjichun** [comment]
抱歉~~~
那我还是手动引入吧~~
