### ISSUE TITLE
List Component performance issue

### ISSUE THREAD

**Issue by musicq** [NG-ZORRO/ng-zorro-antd#1402]
## Version

0.7.0-beta.5

## Environment

mac 10.13.4 chrome 66.0.3359.139

## Reproduction link

[https://stackblitz.com/edit/angular-twqtq2](https://stackblitz.com/edit/angular-twqtq2)

## Steps to reproduce

Typing some numbers in the filter input to filter the list, and delete it to see the renderer speed of the list.

## What is expected?

The list could be rendered fast when using `nzRenderItem`.

## What is actually happening?

Actually it too much slowly than expected

## Other?

I don't know if I use this component in the wrong case?

**Comment by cipchk** [comment]
这个问题并非 `nz-list` 的原因，而是 `ngTemplateOutlet` 本质是动态构建组件，这个过程相比较模板被 aot 以后完全不在同一个层次；

当然示例也不存在涉及 `TrackBy` 问题。

请看另一个示例：https://stackblitz.com/edit/angular-twqtq2-zpx362?file=app/app.component.ts

以及二者过程中所调用方法的不同之处：

动态组件

![image](https://user-images.githubusercontent.com/2987467/39852537-a423c2a6-544f-11e8-9bbd-bb29c953b8da.png)

AOT

![image](https://user-images.githubusercontent.com/2987467/39852541-a807816e-544f-11e8-8312-97dcdd52315b.png)

**Comment by musicq** [comment]
@cipchk 对不起没把问题描述清楚，我看到你提供的例子中并没有使用 nzRenderItem 这个 input，我的使用场景是使用了这个属性，只不过例子比较简单。

我之前看了代码中是使用 ngTemplateOutlet 去动态创建的，所以我怀疑说是不是这个组件是不适合做我的那种场景使用？

我觉得如果说为这个组件加上虚拟列表的功能是不是就会 cover 到这种场景。

PS：我在本地对于我的例子即使 aot 也还是一样。

**Comment by cipchk** [comment]
@musicq 是的，并非不适合，`nzDataSource` 你可以看做是适用于小型数据的一个快捷操作，本质上 `nz-list`、`nz-list-item` 是允许独立使用，参考我Fork的示例。
