### ISSUE TITLE
Some ICONS in the Modal are not fully displayed.

### ISSUE THREAD

**Issue by angel0725** [NG-ZORRO/ng-zorro-antd#1403]
## Version

0.6.15

## Environment

Firefox 59.0.3 (32 位)

## Reproduction link

[https://ng-zorro-antd-setup-j99ceu.stackblitz.io](https://ng-zorro-antd-setup-j99ceu.stackblitz.io)

## Steps to reproduce

just click those button , and you can see this. the top of  ICON is losted

## What is expected?

those ICONS can display fully

## What is actually happening?

those ICONS can display fully

**Comment by vthinkxie** [comment]
<img width="492" alt="2018-05-08 5 37 33" src="https://user-images.githubusercontent.com/1506722/39749936-85f85536-52e6-11e8-967b-4752e70d9574.png">
works fine when I check it.

**Comment by angel0725** [comment]
![default](https://user-images.githubusercontent.com/15307458/39794406-bb1e114c-537c-11e8-84c9-83d5c61e518e.png)
ng-zorro-antd version is 0.6.15
and in https://ng.ant.design/#/components/modal ,click those buttons , the ICONS in the Modal  are also  not fully displayed.

**Comment by vthinkxie** [comment]
<img width="1083" alt="2018-05-09 11 39 12" src="https://user-images.githubusercontent.com/1506722/39794580-9fd0d216-537d-11e8-81f8-139ed1a59f40.png">
can not reproduce it in my compute, any one has the same issue?

**Comment by angel0725** [comment]
![default](https://user-images.githubusercontent.com/15307458/39794737-74e0f3e6-537e-11e8-8cee-80375b510c1c.png)
my Firefox is 32 bits
and in chrome 32 bits ,it have same problem

**Comment by dmytroyarmak** [comment]
I've tested it on OS X with Firefox 59.0.3 (64-bit) and Chrome 66.0.3359.117 (64-bit) and it works fine.

I think it can be specific to Windows but it will be great to have someone else to reproduce it as well.

**Comment by wenqi73** [comment]
![err](https://user-images.githubusercontent.com/23337087/39822241-ae49d086-53dc-11e8-9503-de5c4399e0a2.png)
I can reproduce it and My system is Windows 7 SP1.

**Comment by vthinkxie** [comment]
fixed in latest version.
