### ISSUE TITLE
ng-zorro-antd@0.7不支持angular6。rxjs版本问题如何解决。

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#1413]
node_modules/@angular/router/src/utils/collection.d.ts(9,28): error TS2307: Cannot find module 'rxjs'.
//
This project uses version 5.5.6 of RxJs, which is not supported by Angular v6.
The official RxJs version that is supported is 5.6.0-forward-compat.0 and greater.

Please visit the link below to find instructions on how to update RxJs.
https://docs.google.com/document/d/12nlLt71VLKb-z3YaSGzUfx6mJbc34nsMXtByPUN35cg/edit#
//
Module not found: Error: Can't resolve 'rxjs/operators/take' in 'C:\GitDevGroup\bms\a6-sys\node_modules\ng-zorro-antd\esm5'
//node_modules/ng-zorro-antd/src/slider/nz-slider.component.d.ts(3,10): error TS2305: Module
'"C:/GitDevGroup/bms/a6-sys/node_modules/rxjs/Observable"' has no exported member 'Observable'.

**Comment by vthinkxie** [comment]
rxjs5和6均处于不兼容状态，0.7版本不会支持angular 6.0

**Comment by liwei511** [comment]
多谢@vthinkxie 指明
