### ISSUE TITLE
弹出框中点击下拉框出现双重蒙层

### ISSUE THREAD

**Issue by ppjjzz** [NG-ZORRO/ng-zorro-antd#1414]
## Version

0.7.0-beta.5

## Environment

ng5

## Reproduction link

[https://github.com/ppjjzz/ngx-bg](https://github.com/ppjjzz/ngx-bg)

## Steps to reproduce

点击弹出框中的下拉框

## What is expected?

不出现双重蒙层

## What is actually happening?

出现双重蒙层
![image](https://user-images.githubusercontent.com/26438223/39797557-26b2ee34-538f-11e8-9949-bdd701b46eec.png)

**Comment by vthinkxie** [comment]
<img width="1423" alt="2018-05-09 2 35 44" src="https://user-images.githubusercontent.com/1506722/39799303-603f0884-5396-11e8-99fe-88638c433138.png">
