### ISSUE TITLE
use NzTreeNode，when build with "ng build --prod" , error: Module not found

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#1416]
## Version

0.7.0-beta.5

## Environment

window10 64专业版, chrome 68 dev, ng-zorro-antd@0.7.0-beta.5

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-wgpg5w?file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-wgpg5w?file=app/app.component.html)

## Steps to reproduce

ng build --prod --base-href --output-hashing=bundles ./ 

## What is expected?

可以使用prod方式打包

## What is actually happening?

ERROR in ./src/app/routes/account-management/account-management.component.ngfactory.js
Module not found: Error: Can't resolve 'ng-zorro-antd/src/tree/public-api' in 'C:\GitDevGroup\bms\bms-acct\src\app\routes\account-management'

## Other?

link：https://pan.baidu.com/s/1_9UV8xskwxUBaGURLj3lcQ password：7afg
报错项目

**Comment by liwei511** [comment]
抱歉，stackblitz无法重现，我再找找我自己的问题。抱歉浪费各位时间，抱歉。

**Comment by simplejason** [comment]
@liwei511 I will check it

**Comment by vthinkxie** [comment]
thanks your feedback @liwei511
