### ISSUE TITLE
打包出错

### ISSUE THREAD

**Issue by 306654214** [NG-ZORRO/ng-zorro-antd#1417]
## Version

0.7.0-beta.5

## Environment

0.7.x都会出现ng build --prod --aot之后发布访问不了

## Reproduction link

[https://ng-zorro-antd-setup.stackblitz.io](https://ng-zorro-antd-setup.stackblitz.io)

## Steps to reproduce

1、ng build --prod --aot
2、发布访问
3、报错Cannot read property 'resolveComponentFactory' of undefined
TypeError: Cannot read property 'resolveComponentFactory' of undefined
    at t.LM7e.e.createContainer 

## What is expected?

正常发布访问

## What is actually happening?

不能访问

**Comment by vthinkxie** [comment]
plz provide valid repro link.

**Comment by luckBegin** [comment]
我也遇见了,你解决了没有

**Comment by vthinkxie** [comment]
@luckBegin you have to use angular 5.x and rxjs 5.x

**Comment by vthinkxie** [comment]
please provide an repro link with stackbliz which can download and reproduce the build error.

**Comment by vthinkxie** [comment]
尝试升级 @angular/cdk 到5.2.5版本试试

**Comment by 306654214** [comment]
@luckBegin 我最后用的是6.X打包的
