### ISSUE TITLE
利用*ngFor 生成ng-step报错

### ISSUE THREAD

**Issue by yytian1017** [NG-ZORRO/ng-zorro-antd#1418]
## Version

0.7.0-beta.5

## Environment

mac

## Reproduction link

[https://ng-zorro-antd-setup-zyiyt6.stackblitz.io](https://ng-zorro-antd-setup-zyiyt6.stackblitz.io)

## Steps to reproduce

<nz-step nzIcon="anticon anticon-solution"  *ngFor="let step of orderHistorySteps"></nz-step>

## What is expected?

无错

## What is actually happening?

console中报错 

ERROR

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: true'. Current value: 'ngIf: false'.

**Comment by vthinkxie** [comment]
bug confirm, thanks for report.

**Comment by yytian1017** [comment]
when will the fix  release in 0.7.0-beta.5
