### ISSUE TITLE
[feature] 希望table组件固定表头改用sticky属性来实现

### ISSUE THREAD

**Issue by ppjjzz** [NG-ZORRO/ng-zorro-antd#1419]
## What problem does this feature solve?

解决了固定表头时会产生多余的元素
解决了固定表头时在windows下thead右侧会固定出现滚动条
解决了固定表头时列对不齐

## What does the proposed API look like?

能够解决上述问题

**Comment by vthinkxie** [comment]
目前就是sticky方式固定的，对不齐的问题和sticky没有关系，需要手动指定nzWidth
