### ISSUE TITLE
how to remove the right padding of body when show a modal

### ISSUE THREAD

**Issue by yzy1197988245** [NG-ZORRO/ng-zorro-antd#1422]
## What problem does this feature solve?

每次show modal 的时候右边多一个空白，body不会出现滚动条

## What does the proposed API look like?

加一个配置项

**Comment by hemiaoio** [comment]
同样关注ing...

**Comment by wendzhue** [comment]
It seems that it was fixed in recent commits. See https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/modal/nz-modal.component.ts.

```ts
private changeBodyOverflow(): void {
    const openModals = this.modalControl.openModals;

    if (openModals.length) {
      this.renderer.setStyle(this.document.body, 'padding-right', `${this.nzMeasureScrollbarService.scrollBarWidth}px`);
      this.renderer.setStyle(this.document.body, 'overflow', 'hidden');
    } else {
      this.renderer.removeStyle(this.document.body, 'padding-right');
      this.renderer.removeStyle(this.document.body, 'overflow');
    }
  }
```

But I think the padding should be added before the modal shows up, just like [antd](http://ant.design/components/modal-cn/).

**Comment by wilsoncook** [comment]
@yzy1197988245 @hemiaoio 
Now the modal shown strategy is the same with antd, let's make it more clear, do you want a option to avoid adding the `padding-right:Npx` to `body`?

**Comment by hemiaoio** [comment]
@wilsoncook YES. Now open the modal window, the back window will shake, visually feel uncomfortable

**Comment by lopn** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/6ae44678133a91467e568edc736e685aa8a565d8/components/modal/nz-modal.component.ts#L417

**Comment by lopn** [comment]
padding-right 不能每次都加， 我觉得最合理的是应该先判断页面是否有滚动条，如果有获取bar宽度，加padding-right, 否则不加

**Comment by lopn** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/6ae44678133a91467e568edc736e685aa8a565d8/components/core/services/nz-measure-scrollbar.service.ts#L18
