### ISSUE TITLE
Unexpected transition in form item etc.

### ISSUE THREAD

**Issue by shhdgit** [NG-ZORRO/ng-zorro-antd#1424]
## Version

0.7.0-beta.5

## Environment

ng-zorro-antd@0.7.x

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-8bvsty?file=app%2Fapp.module.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-8bvsty?file=app%2Fapp.module.ts)

## Steps to reproduce

https://ng.ant.design/version/0.7.x/components/form/zh#components-form-demo-layout

官方示例中，表单布局下，vertical和inline布局来回切换，input框会有不希望有的动画。input框单独使用时有时也有奇怪的动画。

## What is expected?

no transition when rerender

## What is actually happening?

have transition

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-8bvsty?file=app%2Fapp.module.ts
fixed in latest version, close now.
