### ISSUE TITLE
when using nz-select, there are some 'cdk-overlay-backdrop' class div emerge with a top z-index, so I can't click anything except it

### ISSUE THREAD

**Issue by shenchaoran** [NG-ZORRO/ng-zorro-antd#1426]
the div is in the 'cdk-overlay-container', and has a z-index of 1000.
```
<div class='cdk-overlay-container'>
       <div class="cdk-overlay-backdrop cdk-overlay-dark-backdrop cdk-overlay-backdrop-showing"></div>
</div>
```

当我使用nz-select时，总是会出现一层遮罩挡在最前面，宽和高都是100%，这时就点不了任何按钮了，请问是什么原因啊？

**Comment by ppjjzz** [comment]
cdk的overlay就是这样，你可以看下官方文档这方面的介绍，出现这个遮罩层是为了让点击这个遮罩层的时候下拉框可以收起来

**Comment by gin-lsl** [comment]
当没有任何弹出层出现的时候，依旧无法正常点击或滚动页面。

有没有可以监听overlay弹出的数量的服务，好让我动态改变cdk-overlay-container的height值？

**Comment by wendzhue** [comment]
由于 cdk 存在的一个 bug，出现两个 overlay 时需要点击两次才能移除全部的 overlay，目前还没遇到过完全不能点击的情况。请提供复现链接。
