### ISSUE TITLE
prod下表格无数据的时候提示文字的问题

### ISSUE THREAD

**Issue by 694551594** [NG-ZORRO/ng-zorro-antd#1428]
## Version

0.7.0-beta.5

## Environment

win7、Google Chrome66.0.3359.139、0.7.0-beta.5

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.html)

## Steps to reproduce

使用nz-table没指定无数据的时候的提示文本（默认），本地开发环境下是正常的（暂无数据），当prod打包后，却显示（Table.emptyText）。

## What is expected?

prod环境下也显示 暂无数据

## What is actually happening?

prod环境下显示 Table.emptyText

**Comment by vthinkxie** [comment]
provide valid repro link or issue will be closed.

**Comment by Renhj90520** [comment]
Is this solved? I have the same problem. When there's no data the Table component shows 暂无数据 in dev mode but it shows Table.emptyText in build --prod mode.

**Comment by Renhj90520** [comment]
It works. Many thanks for your quick response. @vthinkxie
