### ISSUE TITLE
Animation not triggered at the first time overlay's position change

### ISSUE THREAD

**Issue by wilsoncook** [NG-ZORRO/ng-zorro-antd#1429]
At the first time position change, the animation will not be triggered because the overlay's "positionChange" event is emitted after the content's full shown up.

![overlay-animation](https://user-images.githubusercontent.com/1631659/39964903-334ce7e6-56c1-11e8-81fb-770cb57f3258.gif)

And all other components like "nz-dropdown" "nz-date-picker" which depends on overlay also has the same issue.

**Comment by 100cm** [comment]
If  `FlexibleConnectedPositionStrategy.apply()` return `ConnectedOverlayPositionChange` may could resolve this problem.
