### ISSUE TITLE
nz-radio 的 nzValue 、ngModel 为什么不能是int类型，对于一个复杂的数据结构，转化很麻烦。

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#1431]
<nz-radio-group formControlName="tax_model" [(ngModel)]="cinemaInfo.base_info.tax_model">
    <label nz-radio nzValue="1">一般纳税人</label>
    <label nz-radio nzValue="2">小规模纳税人</label>
</nz-radio-group>
// 当cinemaInfo.base_info.tax_model = 1 时，“一般纳税人”未选中。
// 当cinemaInfo.base_info.tax_model = '1' 时，“一般纳税人”选中。
// 取cinemaInfo.base_info.tax_model时，也是字符类型。
// 有什么办法让 nzValue和ngModel 是整形吗？

**Comment by vthinkxie** [comment]
不带方括号默认就是string，这是angular的定义

**Comment by liwei511** [comment]
好的，谢谢，我明白了，是我写法不对，多谢@vthinkxie
`<nz-radio-group formControlName="tax_model" [(ngModel)]="cinemaInfo.base_info.tax_model">
   <label nz-radio [nzValue]="1">一般纳税人</label> // 对
   <label nz-radio [nzValue]="'2'">小规模纳税人</label>  // 错
</nz-radio-group>`

this.cinemaInfo.base_info.tax_model = 1; // 此时’一般纳税人‘是选中
