### ISSUE TITLE
nzLoadData

### ISSUE THREAD

**Issue by tatiana-r** [NG-ZORRO/ng-zorro-antd#1435]
How can i use nzLoadData in Cascader component to get data from service? I can't get my component's properties amd methods in function loadData.

i have in my component properties:
public rootData =  [{
    value: 'root',
    label: 'root'
 }]
public childData =  [{
    value: 'child 1',
    label: 'child 1'
  }, {
    value: 'child 2',
    label: 'child 2'
  }]

And handler for [nzLoadData]:

 loadData(node: any, index: number) {
    return new Promise((resolve) => {
    setTimeout(() => {
       if (index < 0) { // if index less than 0 it is root node
        node.children = this.rootData;
         } else {
          node.children = this.childDepartments;
         } 
        resolve();
      }, 1000);
    });
  }

I get undefined instead of data

**Comment by wlclass** [comment]
hi @tatiana-r,   please try following:

  loadData = (node: any, index: number) => {
    return new Promise((resolve) => {
      setTimeout(() => {
        if (index < 0) { // if index less than 0 it is root node
          node.children = this.rootData;
        } else {
          node.children = this.childDepartments;
        }
        resolve();
      }, 1000);
    });
  }
