### ISSUE TITLE
Angular Package Format compatible distribution

### ISSUE THREAD

**Issue by trotyl** [NG-ZORRO/ng-zorro-antd#144]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

Whatever opposite to expected behavior.

## Expected behavior

**Goals**

- [x] Clean distribution, no sources, tests or other meaningless files;
- [x] Main FESM15 distribution following [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit) for entire lib;
- [x] Main FESM5 distribution following [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit) for entire lib;
- [x] Main UMD distribution following [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit) for entire lib (with minified version);
- [x] Plunker template/starter;
- [x] Compatible with Angular CLI (add integration test);
- [x] Compatible with Webpack (add integration test);
- [x] Compatible with Rollup (add integration test);

**Non-Goals**

- Compatible with Closure Compiler ADVANCED mode (too hard);
- Compatible with server-side rendering (could be done later);
- Well-defined documentation for all possible usages (would be done in separate card);
- Correct sourcemap to original .ts files (having technical problems);
- Individual bundle for each component (secondary entries in Angular package are individual modules, not partial ones, would require new designs);
- Stackblitz template/starter (it's unable to customize package source, need to wait for release);

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
Will use the new format introduced by https://github.com/angular/angular/commit/fd701b07f0ead6cdb549b1ce7a4725cbb542e56c.

**Comment by trotyl** [comment]
Initial version of [plunker template here](http://plnkr.co/edit/qCEuu4LAbLUDWQDnyosz?p=preview).

**Comment by cipchk** [comment]
Don't dismiss a follower and expect them to keep items!

+++++++++++++1 for @trotyl

**Comment by yupengfei** [comment]
Will  Closure Compiler ADVANCED possible in future?

**Comment by trotyl** [comment]
@yupengfei Not even a feature request for that yet.
