### ISSUE TITLE
Can't bind to 'nzAjaxData' since it isn't a known property of 'nz-table'.

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#1440]
## Version

0.7.0-beta.5

## Environment

ng5

## Reproduction link

[https://ng-zorro.github.io/#/components/table](https://ng-zorro.github.io/#/components/table)

## Steps to reproduce

nz-table 输入属性nzAjaxData不能绑定

## What is expected?

nzAjaxData 可用

## What is actually happening?

nzAjaxData 不可用

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/0.7.x/
如果你用的是0.7.x的版本，请阅读0.7版本的文档

**Comment by liganggang** [comment]
文档更新
