### ISSUE TITLE
写在 0.7.0 正式版本发布时

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#1442]
#### 我应该升级到最新版本的 `ng-zorro-antd` 吗？

`0.7.0` 版本的 `ng-zorro-antd` 在以下几个方面做出了很大改进

* 更少的代码：简化了很多组件的使用方式，例如 `form` 表单同样功能下代码量会缩减1/3
* 更强的功能：完善了很多组件的功能，无论是 `input` 还是 `date-picker` 等大量组件都有了更强大的功能可用
* 更好的质量：增加了组件的单元测试，为了保证组件的质量我们目前为止增加了 1070 个测试用例，单测覆盖率达到了 `95%` 以上
* 更新的规范：升级到 Ant Design 3.0 规范，并且支持像 `react` 版本一样自定义主题

升级到 `0.7.0` 版本是最好的选择。

#### 为什么会有这么多 break change

就像上文所说的那样，为了能够提供更好的使用方式，我们对大量代码进行了简化，并对很多功能做了增强，在这个过程中不可避免的会引入破坏性更新，希望大家能够理解。

#### 应该如何升级到最新版本

为了帮助用户从低版本升级，我们保留了低版本的文档系统，你可以随时对比文档中的差别，另外 `ng-alain` 也提供了从 `0.6.x` 版本升级到 `0.7.0` 的[在线模板工具](https://ng-alain.com/6to7)，大家可以根据需要使用。

**请注意：** 由于 `@angular/cli` 的最新版本已经默认采用 `angular 6.0` 以上的版本，请使用 `@angular/cli` 1.7.4 及以下版本。

### 写给 `0.7.0` 试用用户

感谢在测试阶段升级到 `0.7.0 beta` 版本的所有用户，没有你们的协助就不会有 `0.7.0` 正式版本的诞生，推荐所有 `0.7.0 beta` 版本用户升级到该版本。

#### 如何从 `0.7.0` 测试版本迁移到正式版

从 `0.7.0` 测试版本到 `0.7.0` 正式版本基本没有破坏性更新，更多的工作是在开发新的组件上，因此可以放心迁移。

```bash
npm install ng-zorro-antd@0.7.0
```
命令即可升级至 `0.7.0` 正式版本

#### 什么时候官方会支持 `Angular 6.0` 版本

目前 `ng-zorro-antd` 已经全力在适配 `Angular 6.0` 版本，可以在[这里](https://github.com/NG-ZORRO/ng-zorro-antd/issues/1406) 追踪我们的进度。
我们会在 `1.0` 版本提供经过测试的 `Angular 6.0` 适配版本，届时我们还会同时支持 `@angular/cli` 最新版本的众多特性，`rxjs` 与 `cdk` 的依赖版本也会同步升级到 `6.0` 版本，提供更好更多的性能。

#### 如何在 0.7.0 版本下使用 `Angular 6.0`

如果你希望在当前版本(0.7.0) 使用 `Angular 6.0`，你需要至少完成以下两部分工作

* 安装 `rxjs-compat` 用于兼容 `rxjs 5.x`
* 降级到 `less 2.7` 版本，因为最新版本的 `@angular/cli` 依赖的 `less 3.0` 版本禁用了 `javascriptEnabled` 选项，相关工作可以在[这里](https://github.com/angular/angular-cli/issues/10430) 追踪

最后，由于目前官方未对 `Angular 6.0` 版本进行全面的测试和兼容工作，并不建议用户在生产环境使用 `Angular 6.0` 版本。

#### 从 `0.7.0` 到 `1.0.0` 还会有破坏性更新吗？

除了Angular 和 RxJS 升级带来的更新之外，`ng-zorro-antd` 不会再引入破坏性更新，可以安心使用当前版本。

**Comment by vthinkxie** [comment]
@JCqiu @oydr 再试下

**Comment by mahf** [comment]
太赞了~~！辛苦了

**Comment by jsjjl** [comment]
npm install -g @ angular / cli 安装后 ng new的时候一直报错提示安装.net framwork怎么处理啊 ，之前都没有遇到过

**Comment by jakechan2012** [comment]
这速度杠杠的，感谢开发人员和贡献者 🙏

**Comment by wlclass** [comment]
感谢开发人员和贡献者

**Comment by jsjjl** [comment]
Angular 6.0 环境下 处理了 rxjs-compat   和 less  还是报错，ERROR in node_modules/@angular/cdk/overlay/typings/overlay-ref.d.ts(11,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@angular/cdk/overlay/typings/overlay-ref.d.ts(12,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/@angular/cdk/overlay/typings/position/connected-position-strategy.d.ts(12,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@angular/cdk/scrolling/typings/scroll-dispatcher.d.ts(10,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/@angular/cdk/scrolling/typings/scroll-dispatcher.d.ts(11,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@angular/cdk/scrolling/typings/scrollable.d.ts(9,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@angular/cdk/scrolling/typings/viewport-ruler.d.ts(10,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-zorro-antd/src/dropdown/nz-dropdown.component.d.ts(3,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-zorro-antd/src/dropdown/nz-dropdown.component.d.ts(4,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ng-zorro-antd/src/dropdown/nz-dropdown.component.d.ts(5,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/ng-zorro-antd/src/menu/nz-submenu.component.d.ts(2,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ng-zorro-antd/src/modal/nz-modal-subject.service.d.ts(1,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ng-zorro-antd/src/slider/nz-slider.component.d.ts(3,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-zorro-antd/src/slider/nz-slider.component.d.ts(4,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/ng-zorro-antd/src/tabs/nz-tabs-nav.component.d.ts(4,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/ng-zorro-antd/src/tabs/nz-tabset.component.d.ts(3,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-zorro-antd/src/tooltip/nz-tooltip.component.d.ts(4,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/ng-zorro-antd/src/tooltip/nz-tooltip.component.d.ts(5,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-zorro-antd/src/transfer/nz-transfer.component.d.ts(2,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-zorro-antd/src/upload/interface.d.ts(1,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-zorro-antd/src/upload/interface.d.ts(2,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/ng-zorro-antd/src/upload/nz-upload.component.d.ts(2,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-zorro-antd/src/upload/nz-upload.component.d.ts(3,10): error TS2305: Module '"/Users/jiangjinlei/Documents/ng-app/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.
node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.

**Comment by vthinkxie** [comment]
@jsjjl rxjs的使用问题请不要在这里提问，谢谢，官方issue用来追踪和报告ng-zorro-antd相关问题

**Comment by oydr** [comment]
日期的选择框的样式怎么不对呀，我引用的有问题？如下图
![2018-05-15 10 27 46](https://user-images.githubusercontent.com/20137819/40063038-0969ce56-588f-11e8-8fc3-bfa1532eef64.png)

**Comment by guccihuiyuan** [comment]
我的日期的选择框的样式也不对
![image](https://user-images.githubusercontent.com/7911691/40091280-4b791162-58e9-11e8-862a-3410ab70b4d0.png)

**Comment by vthinkxie** [comment]
请先读完上手指南再使用，谢谢
