### ISSUE TITLE
公司的IP，会被你们屏蔽

### ISSUE THREAD

**Issue by tianxiaozi** [NG-ZORRO/ng-zorro-antd#1446]
## Version

0.7.0

## Environment

无

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.ts?](https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.ts?)

## Steps to reproduce

公司IP偶尔会访问不了你们网站，是不是被你们屏蔽了，需要重启路由才能正常访问。
公司路由重启必须申请比较麻烦，被屏蔽的时候要看文档都得用手机热点
就它---> https://ng.ant.design/docs/introduce/zh

## What is expected?

正常访问

## What is actually happening?

偶尔会连不上，必须重启路由器。

**Comment by vthinkxie** [comment]
网站的实际地址是github.io，不会屏蔽任何公司。部分ip访问不了是因为你懂得，我们会尽快迁移到其他地方
