### ISSUE TITLE
当鼠标点击数字输入框加减数字后，点其他地方失去焦点后，数字输入框还是有聚焦的样式

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1449]
![qq 20180516110138](https://user-images.githubusercontent.com/16211027/40094283-a030a9fe-58f8-11e8-912b-027bfe506f39.png)

## Version

0.7.0

## Environment

win10,chrome66,0.7.0

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-i4ybse?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-i4ybse?file=app%2Fapp.component.html)

## Steps to reproduce

当鼠标点击数字输入框加减数字后，点其他地方失去焦点后，数字输入框还是有聚焦的样式

## What is expected?

当鼠标点击数字输入框加减数字后，点其他地方失去焦点后，数字输入框还没有聚焦的样式

## What is actually happening?

当鼠标点击数字输入框加减数字后，点其他地方失去焦点后，数字输入框还是有聚焦的样式

**Comment by vthinkxie** [comment]
![kapture 2018-05-16 at 11 11 56](https://user-images.githubusercontent.com/1506722/40094498-fdd83102-58f9-11e8-80e4-a9469f9ae6fe.gif)
不能复现

**Comment by JCqiu** [comment]
![test](https://user-images.githubusercontent.com/16211027/40094960-49f58682-58fc-11e8-8804-2c84b81cc2ff.gif)

**Comment by jakechan2012** [comment]
@chichujn 我本地已经升级到 0.7.0正式版，问题依然存在

**Comment by vthinkxie** [comment]
@jakechan2012 got it.

**Comment by wendzhue** [comment]
Do you already have guys working on this issue? I think I am capable of fixing this. @vthinkxie

**Comment by vthinkxie** [comment]
@wendzhue I will assign the issue to you, thanks.
