### ISSUE TITLE
ng-zorro-antd跟react-antd有什么 优势呢？

### ISSUE THREAD

**Issue by HelloJasonZhang** [NG-ZORRO/ng-zorro-antd#145]
目前react-antd版本更稳定，组件更丰富，也有大量的实践经历累计。
所以不明白为什么要弄出来angular antd design. 问下ng-zorro-antd跟react-antd对比有什么优势？

**Comment by mushang11** [comment]
对使用 angular 的团队提供企业化的组件库。

**Comment by linguowei** [comment]
@HelloJasonZhang 一个是react的组件库一个是angular的，你这问题问的。。。

**Comment by HelloJasonZhang** [comment]
@linguowei 你说对，目前有一个新项目要做，想对比下ng-zorro-antd和react-antd。本人一直在学习react-antd。所以想不明白ng-zorro-antd优势在哪？

**Comment by vthinkxie** [comment]
There is no advantage at all, if you don't use angular.

**Comment by linguowei** [comment]
@HelloJasonZhang 这是两个框架基于 Ant Design 这个ui设计规范的组件实现，两个东西没有对比性，你用react就选 react-antd，用angular就选 ng-zorro

**Comment by LinBoLen** [comment]
还可以选择我正在开发的, ng-zorro fork版本😀
