### ISSUE TITLE
0.6.x 升级到 0.7.0 没有样式了 怎么回事？

### ISSUE THREAD

**Issue by lishengzhuang** [NG-ZORRO/ng-zorro-antd#1452]

**Comment by vthinkxie** [comment]
请先读完快速上手指南，再开始升级项目

**Comment by lishengzhuang** [comment]
我以前 0.6.15  是正常的 升级到0.7.0 就不行了

**Comment by lishengzhuang** [comment]
...
  "styles": [
    "../node_modules/ng-zorro-antd/src/ng-zorro-antd.less"
  ]
...

这个已经加了

**Comment by sunbay** [comment]
@lishengzhuang 问题解决了吗？ 我升级后也碰到这个问题，没有了样式。就是按照快速上手指南升级的。

**Comment by lishengzhuang** [comment]
没有、又换到0.6x  了

**Comment by vthinkxie** [comment]
@lishengzhuang @sunbay 确认一下 angular cli 和 angular 的版本号，angular cli 6.0以上的配置是需要手动调整的

**Comment by lishengzhuang** [comment]
- 
![qq 20180517115740](https://user-images.githubusercontent.com/16040980/40156024-87bd18a4-59c9-11e8-8b0f-f7a27025dfb1.png)


-

**Comment by vthinkxie** [comment]
<img width="937" alt="2018-05-17 12 11 19" src="https://user-images.githubusercontent.com/1506722/40156338-838fcefa-59cb-11e8-8187-31780aaaf73a.png">

**Comment by sunbay** [comment]
@vthinkxie cli的版本就是1.7.4，另外，过程中也没出现任何报错。
目前临时的解决办法是：
![image](https://user-images.githubusercontent.com/5295278/40186331-679b7dfa-5a27-11e8-8304-87ed46ecabf1.png)
![image](https://user-images.githubusercontent.com/5295278/40186409-96c0395e-5a27-11e8-80b4-56f3e0fa1ec5.png)
