### ISSUE TITLE
nzCustomNoResult取消后 nzNoResult没设置成功

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#1458]
## Version

0.7.0

## Environment

ng5

## Reproduction link

[https://ng-zorro.github.io/components/table/zh](https://ng-zorro.github.io/components/table/zh)

## Steps to reproduce

暂无

## What is expected?

nzNoResult可用

## What is actually happening?

nzNoResult不可用

## Other?

没有案列

**Comment by vthinkxie** [comment]
[nzNoResult]="暂无数据"

**Comment by liganggang** [comment]
[nzNoResult] failed to use
