### ISSUE TITLE
[nzNoResult]="没有数据" Error: Template parse errors ，TemplateRef<void> not working

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#1459]
## Version

0.7.0

## Environment

ng5

## Reproduction link

[https://ng-zorro.github.io/components/table/zh](https://ng-zorro.github.io/components/table/zh)

## Steps to reproduce

No steps

## What is expected?

nzNoResult  available

## What is actually happening?

nzNoResult unavailable

## Other?

the document is not clear

**Comment by vthinkxie** [comment]
please do not ask questions more than once after get response 
https://stackblitz.com/edit/ng-zorro-antd-setup-ynes5x?file=app/app.component.html

`[nzNoResult]="没有数据" ` -> `[nzNoResult]="'没有数据'" `
