### ISSUE TITLE
 npm install error 

### ISSUE THREAD

**Issue by Daniel201618** [NG-ZORRO/ng-zorro-antd#1466]
First I downdowned "ng-zorro-antd-master" Project From github. After Completely downloaded, fisrt executed install command  while found install error. the following is the error I found:
 Refusing to install package with name "ng-zorro-antd" under a package
 also called "ng-zorro-antd". Did you name your project the same
as the dependency you're installing?
![image](https://user-images.githubusercontent.com/24787150/40219402-c527b3dc-5aa7-11e8-9bda-92f6e1792b10.png)

**Comment by vthinkxie** [comment]
if you want to use ng-zorro-antd, you need to follow https://ng.ant.design/docs/getting-started/en this
there is no need to download this repo at all.
