### ISSUE TITLE
大家好，我在全局styles.css中引入自定义的样式，在某个子模块中引入了zorro，当加载该子模块时，自定义的全局样式被覆盖了，是哪里写的有问题吗？

### ISSUE THREAD

**Issue by zy-1995** [NG-ZORRO/ng-zorro-antd#147]
## styles.css
`@import "../node_modules/font-awesome/css/font-awesome.css";
@import "assets/css/site.css";/*全局CSS样式*/`
## angular-cli.json
`"styles": [
        "styles.css"
      ],`

假设现在有两个模块，在A模块中引入了zorro，而B模块中的<a>标签未设置颜色，那么当加载a模块时，b模块中的的<a>标签就会变为zorro中的<a>标签的颜色。因为angular使用了仿真 (Emulated)模式，全局样式可以影响组件，是否有办法避免zorro的样式影响

**Comment by LinBoLen** [comment]
no problem

**Comment by LinBoLen** [comment]
ref: https://angular.cn/guide/component-styles#组件样式

**Comment by zy-1995** [comment]
假设现在有两个模块，在A模块中引入了zorro，而B模块中的<a>标签未设置颜色，那么当加载a模块时，b模块中的的<a>标签就会变为zorro中的<a>标签的颜色

**Comment by trotyl** [comment]
That's true, you cannot apply ng-zorro partially, it's for global styling.

**Comment by trotyl** [comment]
You can make a feature request like: **separate global `.css` file against auto-import**. That way you can manually scope the styling.

**Comment by zy-1995** [comment]
那么我还是全局引入得了，也没有必要分模块引入了，实在是很好看，不想放弃……
