### ISSUE TITLE
use nz-date-picker ,ng build --prod 

### ISSUE THREAD

**Issue by freezyh** [NG-ZORRO/ng-zorro-antd#1473]
正常引入nz-date-picker组件，报错后，按照官网说明main.ts添加如下：
import { registerLocaleData } from '@angular/common';
import zh from '@angular/common/locales/zh';
registerLocaleData(zh);
cnpm start 正常运行
但是ng buil --prod的时候报错
错误提示：
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null......

如果去掉registerLocaleData(zh);又不会报错！当然日期组件也用不了

**Comment by vthinkxie** [comment]
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null......
这个报错明显是aot检测你的程序写的有问题，你去掉 registerLocaleData(zh) 之后 date-picker 整个组件都挂了，和ng-zorro-antd没有关系
