### ISSUE TITLE
使用日期组件ng buil -prod 报错，无法aot

### ISSUE THREAD

**Issue by freezyh** [NG-ZORRO/ng-zorro-antd#1474]
## Version

0.7.0

## Environment

系统win7 64位，Angular CLI: 1.6.5，Node: 8.11.2，Angular: 5.2.10， ng-zorro-antd：0.7.0

## Reproduction link

[https://ng-zorro-antd-setup.stackblitz.io](https://ng-zorro-antd-setup.stackblitz.io)

## Steps to reproduce

尊敬的ng-zorro-antd维护团队您好！
       感谢您们一直对ng-zorro-antd的维护，但这个问题实在找不到解决方法，求助您们，因为使用日期组件发生的相关问题，同时请原谅无效的【重现链接】，因为无法通过重现连接来表达，谢谢您们的谅解，希望得到您们的重视，我也希望ng-zorro-antd会越来越好，如果能帮助解决，方便的话邮件通知下，万分感谢
具体重新步骤如下:

1.正常安装ng-zorro-antd

2.main.ts文件中 引入相应的 Angular 语言包
import { registerLocaleData } from '@angular/common';
import zh from '@angular/common/locales/zh';
registerLocaleData(zh);

3.使用任意日期组件
例如：<nz-date-picker [(ngModel)]="date" (ngModelChange)="onChange($event)" nzShowTime></nz-date-picker>

4.运行ng serve命令，无报错，然后终止

5.运行ng buil --prod 报错
错误：
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at enterNode (F:\managerSystem\node_modules\webpack\lib\optimize\ConcatenatedModule.js:146:15)
    at getPathInAst (F:\managerSystem\node_modules\webpack\lib\optimize\ConcatenatedModule.js:125:24)
.....................................

6.把registerLocaleData(zh);注释掉，运行ng buil -prod 无报错

7.如果不注释掉registerLocaleData(zh); 运行ng build -prod -aot=false  命令，无报错

## What is expected?

正常使用日期组件，ng buil -prod 无报错

## What is actually happening?

运行ng buil --prod 报错

## Other?

正常情况下ng serve无任何错误，由于发布版本需要ng build -prod -aot会发生错误，ng buil -prod -aot=false，虽然无错误，但浏览器渲染时间长，基本项目无接口的情况下都超过4s，体验差

**Comment by vthinkxie** [comment]
@freezyh ，你代码的报错的意思是从一个null对象中获取了range的属性的报错
```typescript
const a = null;
console.log(a.range);
```
在ng-zorro-antd的代码是没有这样的代码的，只可能是你业务中某个对象未初始化，或者初始化为了null，在template代码中绑定了未初始化对象的range属性，这个和 ng-zorro-antd 没有任何关系，ng-zorro-antd 中的datepicker部分的组件代码中也没有任何使用 .range 的部分。
不是使用 ng-zorro-antd 后报错的内容都是由于 ng-zorro-antd 造成的，这点还请理解。

**Comment by freezyh** [comment]
您好，感谢您的回答，深感激动，ng-zorro-antd的代码是确实是没有这样的代码，我也不是想纠结这个代码上的问题,只是使用日期选择器组件的时候使用了Angular语言包，
import { registerLocaleData } from '@angular/common';
import zh from '@angular/common/locales/zh';
registerLocaleData(zh);

官网中日期选择器也提到“注意：nz-date-picker 的部分 locale 来自于 Angular 自身的国际化支持，需要在 main.ts文件中 引入相应的 Angular 语言包。”
我想说明的是日期选择器组件竟然使用了registerLocaleData(zh)；那么按道理是应该能通过ng build -prod的，然后报错了
如果不是ng-zorro-antd 造成的，那么我就想问，官方使用了ng-zorro-antd 的日期组件，都通过ng build -prod不报错吗？
发布一个angular项目 通过ng buil -prod是能很大提高性能的，还请希望得到重视！！！
再次感谢！！！

**Comment by vthinkxie** [comment]
@freezyh 所有ng-zorro-antd的项目都是经过严格的持续集成测试的，目前 angular cli webpack和 rollup的 代码都是经过 prod测试不报错才会发布出来给大家使用，并且 ng-zorro-antd 的官网也是使用 --prod编译出来的
持续集成地址可以参照：https://travis-ci.org/NG-ZORRO/ng-zorro-antd/builds/380012944
关于官网使用 --prod 编译的部分可以参照
<img width="1023" alt="2018-05-19 11 44 41" src="https://user-images.githubusercontent.com/1506722/40264595-278a101c-5b5a-11e8-9679-b6f009ca97ef.png">

https://travis-ci.org/NG-ZORRO/ng-zorro-antd/jobs/380012945
所有的这些质量测试都是公开并且可查的，请多了解一下开源项目的质量控制，我们的核心开发人员都是 Angular 的 Contributor，请相信我们连 --prod 这种最基本的问题上不会出问题

**Comment by vthinkxie** [comment]
@freezyh 刚好看到的了一个可能对你有用的issue
https://github.com/angular/angular-cli/issues/9537
应该是angular cli的低版本bug被你触发了

**Comment by zhiqianguan** [comment]
借题主的问题我想问一下，我无法使用任意一个日期组件如nz-date-picker，则可以通过编译但是会报错如下：

'nz-date-picker' is not a known element:
1. If 'nz-date-picker' is an Angular component, then verify that it is part of this module.
2. If 'nz-date-picker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this

**Comment by freezyh** [comment]
按照官网的正常引入是可以的，不知道你是不是用的1.0以上的版本？
