### ISSUE TITLE
Steps Component bug

### ISSUE THREAD

**Issue by xingkoo** [NG-ZORRO/ng-zorro-antd#1475]
![](https://user-images.githubusercontent.com/2936579/40247941-cec42836-5b00-11e8-94f6-8af90e2d068f.png)

![](https://user-images.githubusercontent.com/2936579/40247959-de0949fc-5b00-11e8-99af-c4ec7f8e9da0.png)

![image](https://user-images.githubusercontent.com/2936579/40264789-77827d08-5b5e-11e8-8517-fad2305e6040.png)

**Comment by vthinkxie** [comment]
注意你安装的ng zorro antd的版本

**Comment by xingkoo** [comment]
抱歉，发了截图信息后直接close掉了。用stackblitz复现时未出现问题。
应该是版本问题。
目前改用引用方式临时解决问题，就没有提交新的issue了。
