### ISSUE TITLE
升级到0.7.0后所有ng-zorro-antd样式无效。

### ISSUE THREAD

**Issue by llycc** [NG-ZORRO/ng-zorro-antd#1476]
升级到0.7.0后所有ng-zorro-antd样式无效。
我的项目使用的是scss，在0.6.15版本时没问题。升级后，所有ng-zorro-antd样式无效。

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.ts  点击export 下载到本地试试
