### ISSUE TITLE
nz-tree异步设置nodes，如果子节点没有全选，父节点是不会选中状态，而不是半选中状态

### ISSUE THREAD

**Issue by 694551594** [NG-ZORRO/ng-zorro-antd#1478]
## Version

0.7.0

## Environment

win7 谷歌 0.7.0

## Reproduction link

[https://ng-zorro-antd-setup.stackblitz.io](https://ng-zorro-antd-setup.stackblitz.io)

## Steps to reproduce

nodes = [];

  constructor() {
  }

  ngOnInit() {
    setTimeout(() => {
      this.nodes.push(new NzTreeNode({
        "title": "test",
        "key": "1",
        "children": [{
          "title": "test1",
          "key": "20",
          "children": [],
          "isLeaf": true,
          "checked": true,
        }, {
          "title": "test2",
          "key": "21",
          "children": [],
          "isLeaf": true,
          "checked": false,
        }],
        "isLeaf": false,
        "checked": false
      }));
    });
  }

这样设置后展现的结果，本来父节点应该是半选中状态，但是实际上是未选中状态。
如果没有加setTimeout，则是正常的。

## What is expected?

异步加载节点后父节点的状态可以正常展现。

## What is actually happening?

setTimeout 加载的节点父节点应该是半选中状态，但是实际上是未选中状态。

**Comment by simplejason** [comment]
@694551594  Angular ngModel会检测对象引用是否发生改变，push方式不会修改对象引用，动态修改可使用
`this.nodes = [...this.nodes, new NzTreeNode({...})]`
