### ISSUE TITLE
need to toggle switch state async

### ISSUE THREAD

**Issue by sxlwar** [NG-ZORRO/ng-zorro-antd#1481]
## What problem does this feature solve?

Sometimes， whether the switch state can be changed depends on some async actions like ajax , api resposne or other actions. Before we get the response ,  the switch state should not be changed, in other word , it should be hold on current state.

## What does the proposed API look like?

Add new input attr on this component and use like this:

```
@Component({
...
})
export class SwitchComponent {
    @Input() asyncToggle?: Observable<boolean>
}

@Component({
     selector: ....
     template: `
        <nz-switch  [asyncToggle]="canToggle"></nz-switch>
     `
})
export class UserComponent {
      canToggle: Observable<boolean>;
}
```
Toggle switch state when the input observable emit 'true' , else hold on current state.

**Comment by vthinkxie** [comment]
plz read the doc about async pipe of angular.

**Comment by sxlwar** [comment]
async pipe?  What is the matter with async toggle switch state?. The problem is state will be changed immediately when user click the switch.

**Comment by sxlwar** [comment]
Of coures, I have tried to use nzLoading, but it doesn't meet our needs. 
As the demo, when I click the switch, the state changed, then show loading for user,  then loading complete. But the correct order is click ,  show loading,  toggle switch state depends on  some async actions. 

[https://stackblitz.com/edit/ng-zorro-antd-setup-9urcsr?file=app%2Fapp.component.ts](url)

Sometimes the switch's state is open or close is determined by server,  if the server response fail or error, we must reset the switch state here , but for a good user experience we should keep the state of the switch until the serve response arrive.

**Comment by vthinkxie** [comment]
@sxlwar I get your point, I will discuss with our team later.

**Comment by sxlwar** [comment]
@vthinkxie Thanks very much!!
