### ISSUE TITLE
nz-table property nzShowTotal

### ISSUE THREAD

**Issue by 3qfang** [NG-ZORRO/ng-zorro-antd#1483]
## What problem does this feature solve?

Very awesome UI,thanks very much.
Version:0.7.
One puzzle with nz-table.

## What does the proposed API look like?

Can support one demo,how to use property nzShowTotal.Thanks again.

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/pagination/zh#components-pagination-demo-total same as pagination.
