### ISSUE TITLE
按快速上手操作报错

### ISSUE THREAD

**Issue by lizongwen** [NG-ZORRO/ng-zorro-antd#1486]
angular/cli  6.0.3
ng-zorro-antd:0.7.0
无法启动

**Comment by simplejason** [comment]
由于 0.7.0 版本的 ng-zorro-antd 目前尚未正式支持 angular 6.0 版本，@angular/cli 请选择 1.7.4 版本安装。

**Comment by lizongwen** [comment]
官网又提示
![image](https://user-images.githubusercontent.com/16129078/40340013-84c1cb2e-5daf-11e8-9dc8-4c799636ac54.png)
这不自相矛盾么

**Comment by simplejason** [comment]
@lizongwen 官网这段下面有注意
<img width="984" alt="20180522110256" src="https://user-images.githubusercontent.com/11643113/40340127-0d21bdbc-5db0-11e8-8ab3-14095b58fc57.png">
