### ISSUE TITLE
使用NzModalService 打开Component, 可以在component里设置with，高度和title

### ISSUE THREAD

**Issue by Cuiqs76** [NG-ZORRO/ng-zorro-antd#1489]
## What problem does this feature solve?

很多组件里的输入字段，需要从一个弹出的模式窗口的一个加载数据的表里选择， 每次调用NzModalService 都需要重复去设置title, width等，很麻烦。
在示例里，没有找到相关示例。

## What does the proposed API look like?

可以直接在component里设置相关属性

**Comment by vthinkxie** [comment]
请更详细的描述你的需求
在Component设置相关属性，哪个component，外层Component还是弹出的Component？
在NzModalService 重复设置 title,width，你是怎么重复设置的？你觉得怎么设置才是不麻烦的？

你希望的api是什么样子？

**Comment by Cuiqs76** [comment]
` const modal = this.modalSrv.create({
            nzContent: UserSelectComponent,
            nzTitle: '选择用户',
            nzWidth: 700,
            nzFooter: [
                {
                    label: '取消',
                    shape: 'default',
                    onClick: () => modal.destroy()
                }              
        });`

我现在需要在这里才能设置弹出的对话框的width和title. 
这个组件是我定义的一个组件:  UserSelectComponent.
`import { Component, OnInit, Input } from '@angular/core';
import { SimpleTableColumn } from '@delon/abc';
import { NzModalRef } from 'ng-zorro-antd';
import { FormBuilder,  FormControl,  FormGroup} from '@angular/forms';
import { User } from '../../models/user.model';
import { UserService } from '../../services/user.service';
import { tap } from 'rxjs/operators';

@Component({
  selector: 'user-select',
  templateUrl: './user-select.component.html',
  styleUrls: ['./user-select.component.css']
})
export class UserSelectComponent implements OnInit {

  users: any[];
  loading = false;

  form: FormGroup;
  controlArray = [];
  isCollapse = true;

  resetForm(): void {
    this.form.reset();
  }


  constructor(
    private modal: NzModalRef,
    private fb: FormBuilder,
    private userSrv: UserService,  
  ) { }

  ngOnInit() {
    this.form = this.fb.group({});   
    this.getData();
  }

  getData() {
    this.loading = true;
    this.userSrv.getUsers().pipe(
      tap(x => this.loading = false)
    )   
    .subscribe(
        data => this.users = data    
    );
}

  columns: SimpleTableColumn[] = [
    { title: '用户名', index: 'userName' },
    { title: '姓名', index: 'name' },
    { title: '邮箱地址', index: 'email' },   
];

}
`

希望能够在这个UserSelect组件里能够设置，modal的 title等 ，组件里能设置相关属性。

如果需要在很多其他组件里弹出这个选择有用户的窗口，目前需要每次都要输入第一段代码的内容。

**Comment by vthinkxie** [comment]
为什么不能 把  `this.modalSrv.create({ nzContent: UserSelectComponent, nzTitle: '选择用户', nzWidth: 700, nzFooter: [ { label: '取消', shape: 'default', onClick: () => modal.destroy() } })` 
二次封装成一个service，然后在你的组件复用

**Comment by wilsoncook** [comment]
You can try `NzModalRef.getInstance()` to get the modal component it self, then change its `nzWidth`/`nzTitle` directly then trigger the change detection.
