### ISSUE TITLE
我怎样修改message和modal的层级关系

### ISSUE THREAD

**Issue by cyhjojo** [NG-ZORRO/ng-zorro-antd#1493]
## What problem does this feature solve?

当modal打开的时候 我希望message置于它的上方

## What does the proposed API look like?

我希望有个属性 可以自由切换z-index

**Comment by wilsoncook** [comment]
The `message` can cover above the `modal` in the next `ng-zorro-antd` release version.

**Comment by vthinkxie** [comment]
close by #1461
