### ISSUE TITLE
How can I get datetime by format

### ISSUE THREAD

**Issue by cyhjojo** [NG-ZORRO/ng-zorro-antd#1497]
## What problem does this feature solve?

I want to get ngmodal data by format ,just like date pipe {{date | date}}, so that I can  transfer datum to the back end using the format I want. By the way, I found that there are some functions  that I can use to fullfill my requirements, such as getDay() . BUT , it's too complex to use.

## What does the proposed API look like?

I can  transfer datum to the back end using the format I want. For example, like "2018-5-23" , not like  "Sat May 26 2018 10:01:39 GMT 0800 (中国标准时间)"

**Comment by vthinkxie** [comment]
<img width="659" alt="2018-05-23 10 27 33" src="https://user-images.githubusercontent.com/1506722/40400289-1303f33e-5e74-11e8-98b8-e4ec9f88fab9.png">
