### ISSUE TITLE
does any plan to support 'interval'  or 'debounce' feature for nz-input component?

### ISSUE THREAD

**Issue by Coder7777** [NG-ZORRO/ng-zorro-antd#1504]
## What problem does this feature solve?

How long, in milliseconds, to wait to trigger the ionInput event after each keystroke.   

default: 2500ms.

suppose  :   "<input nz-input placeholder="Basic usage" [(ngModel)]="value" [debounce]=2500>"

## What does the proposed API look like?

<input nz-input placeholder="Basic usage" [(ngModel)]="value" [debounce]=2500>

**Comment by vthinkxie** [comment]
please track https://github.com/angular/angular/issues/19705
