### ISSUE TITLE
从0.6版升级到0.7版本时候，全局的样式都没啦？这什么情况？

### ISSUE THREAD

**Issue by hanzehua521** [NG-ZORRO/ng-zorro-antd#1505]

**Comment by hanzehua521** [comment]
![31184b8a19a013d70107492924b0ebb](https://user-images.githubusercontent.com/30396590/40462838-5a5e2968-5f44-11e8-9789-9d6624403919.png)
![4bc97818780e6dfa1e1f67d8f6410ab](https://user-images.githubusercontent.com/30396590/40462844-5fb6061a-5f44-11e8-9088-19ad6e22b5fb.png)
![4c805163b3caa646aeaf6f8879766ac](https://user-images.githubusercontent.com/30396590/40462846-63fd7a0a-5f44-11e8-9460-0b76fb77f2a6.png)

**Comment by vthinkxie** [comment]
@hanzehua521 please read https://ng.ant.design/ doc first before updating.
