### ISSUE TITLE
无法在loadChildren后的子路由中使用nz组件

### ISSUE THREAD

**Issue by HereWeR** [NG-ZORRO/ng-zorro-antd#151]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

在配置好路由RouterModule.forRoot(appRouters)后，通过{path: 'main', loadChildren: './main/main.module#MainModule'}懒加载之后的模块无法使用nz组件，
报错为：ERROR Error: Uncaught (in promise): Error: Template parse errors:
'nz-dropdown' is not a known element:
1. If 'nz-dropdown' is an Angular component, then verify that it is part of this module.
2. If 'nz-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
			</div>
			<div class="col-md-3">
				[ERROR ->]<nz-dropdown>
					<button nz-button nz-dropdown><span>more</span> <i class="anticon anticon-down"></"): ng:///ItemsModule/TodoComponent.html@29:4
Error: Template parse errors:
'nz-dropdown' is not a known element:
1. If 'nz-dropdown' is an Angular component, then verify that it is part of this module.
2. If 'nz-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

## Expected behavior

希望支持下级module引用

## Minimal reproduction of the problem with instructions

    {path: '', redirectTo: 'main', pathMatch: 'full'},
    {path: 'main', loadChildren: './main/main.module#MainModule'},
    {path: 'setting', loadChildren: './setting/setting.module#SettingModule'},

import：        BrowserAnimationsModule,
        NgZorroAntdModule.forRoot(),
        RouterModule.forRoot(appRouters)

## What is the motivation / use case for changing the behavior?

最后一个module需要再次import引用NgZorroAntdModule，无法实现“在根 module 中使用 NgZorroAntdModule.forRoot()，在子 module 中使用 NgZorroAntdModule 即可”，望提供解决方案

## Environment
angular-cli：“1.3.0”
ng-zorro-antd: "^0.5.0-rc.2"

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ x ] Chrome (desktop) version 59.0
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
You have to import `NgZorroAntdModule` in your sub module and it is the design of Angular, you may misunderstand the doc.

**Comment by cipchk** [comment]
推荐比较合理的做法是在 `SharedModule` 中导入 `NgZorroAntdModule` 并导出。
