### ISSUE TITLE
12-hour support on timepicker

### ISSUE THREAD

**Issue by patricknazar** [NG-ZORRO/ng-zorro-antd#1513]
## What problem does this feature solve?

The timepicker is 24 hour time, I'd like 12 hour with AM/PM

## What does the proposed API look like?

something like nzType="12"

**Comment by wenqi73** [comment]
Set the `[nzFormat]` like this:
```html
<nz-time-picker nzFormat="h:mm:ss a"></nz-time-picker>
```
![1](https://user-images.githubusercontent.com/23337087/40828564-9005b296-65b3-11e8-8412-7058959aa18a.png)

**Comment by wendzhue** [comment]
Closed by #3127.

**Comment by anna-ps** [comment]
and how to set 24 hours? it gives me 12 hours by default and I'm not able to change it, can't find it on the docs
