### ISSUE TITLE
[BUG] nzScroll 设置未正确应用nzWidth

### ISSUE THREAD

**Issue by simplejason** [NG-ZORRO/ng-zorro-antd#1518]
## Version

0.7.0

## Environment

Chrome

## Reproduction link

[https://stackblitz.com/edit/angular-h52cq9?file=app/app.component.ts](https://stackblitz.com/edit/angular-h52cq9?file=app/app.component.ts)

## Steps to reproduce

设置nzScroll和nzWidth，如果td内容过长会导致固定列功能失效

## What is expected?

正常应用nzWidth并显示

## What is actually happening?

不正常显示

**Comment by dmytroyarmak** [comment]
@simplejason you have a typo in your StackBlitz example. You use `th` instead of `td` for the third column in `tbody`.
Here is a fixed example that works fine for me:
https://stackblitz.com/edit/angular-h52cq9-rg4umc

**Comment by vthinkxie** [comment]
@dmytroyarmak yes, you are absolutely right!
