### ISSUE TITLE
如何像react版本一样定制主题or样式?

### ISSUE THREAD

**Issue by Crystal2Han** [NG-ZORRO/ng-zorro-antd#152]
## 如何像react版本一样定制主题or样式?

react的版本可以通过两种方式定制主题，angular版本什么时候可以支持定制化？

**Comment by cipchk** [comment]
方法一：当下可以Fork一份源代码，然后修改 `components/style/themes/default.less` 相应参数。

方法二：对组件各种 `!important` 不过成本太高。

期待有好的脚手架出现。

**Comment by vthinkxie** [comment]
not supported yet.
