### ISSUE TITLE
ng-table 使用报错， 提示找不到 NzMeasureScrollbarService

### ISSUE THREAD

**Issue by xiaodiao1212** [NG-ZORRO/ng-zorro-antd#1521]
本地用cli@1.7.4启动项目的，ng-zorro版本为"ng-zorro-antd": "^0.7.0"；

当我使用ng-table时，提示：
![image](https://user-images.githubusercontent.com/14543505/40482347-162662a4-5f87-11e8-93a7-678ad102ee51.png)

` No provider for NzMeasureScrollbarService!`

找不到这个模块，查看源码是有的，请问该导入什么模块呢？

**Comment by vthinkxie** [comment]
请按照快速上手的方式引入模块，不要单独引入nzTableModule模块使用，这不会带来任何好处或者收益
https://ng.ant.design/docs/faq/zh#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%8F%90%E4%BE%9B%E6%A8%A1%E5%9D%97%E5%8D%95%E7%8B%AC%E5%BC%95%E5%85%A5

**Comment by xiaodiao1212** [comment]
@vthinkxie 我没有单独引用

这是module代码
`import { ShareModule } from './../share/share.module';
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BasicComponent } from './basic/basic.component';
import { Routes, RouterModule } from '@angular/router';
import { TreeComponent } from './tree/tree.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';

const tableSetRoutes: Routes = [
  {
    path: 'basic',
    component: BasicComponent
  }
]

@NgModule({
  imports: [
    CommonModule,
    ShareModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    RouterModule.forChild(tableSetRoutes)
  ],
  exports: [
    CommonModule,
    ShareModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule
  ],
  declarations: [BasicComponent, TreeComponent]
})
export class DictionaryModule { }
`

这是component代码
`import { Component, OnInit, ViewChild } from '@angular/core';
import {TreeComponent} from "./../tree/tree.component";

@Component({
  selector: 'app-basic',
  templateUrl: './basic.component.html',
  styleUrls: ['./basic.component.less']
})
export class BasicComponent implements OnInit {

  constructor() { }

  dataSet = [
    {
      key    : '1',
      name   : 'John Brown',
      age    : 32,
      address: 'New York No. 1 Lake Park'
    },
    {
      key    : '2',
      name   : 'Jim Green',
      age    : 42,
      address: 'London No. 1 Lake Park'
    },
    {
      key    : '3',
      name   : 'Joe Black',
      age    : 32,
      address: 'Sidney No. 1 Lake Park'
    }
  ];

  ngOnInit() {

  }
}
`
这是html代码
`<nz-table
        #borderedTable
        nzBordered
        nzFooter="Footer"
        nzTitle="Header"
        [nzData]="dataSet">
        <thead>
          <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Address</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let data of borderedTable.data">
            <td>{{data.name}}</td>
            <td>{{data.age}}</td>
            <td>{{data.address}}</td>
          </tr>
        </tbody>
      </nz-table>
`
这是公共模块代码
`// 共享模块
import { NgModule } from '@angular/core';
import { NgZorroAntdModule } from "ng-zorro-antd";

@NgModule({
  imports: [
    NgZorroAntdModule
  ],
  exports: [
    NgZorroAntdModule
  ]
})
export class ShareModule { }`

我在ng-zorro-antd模块中引用 NzNotificationService,NzMessageService,NzDropdownService,NzMeasureScrollbarService，这四个服务，仅仅最后一个报错，提示找不到，但是我在下载的包中能找到这个服务，所以很诧异！
