### ISSUE TITLE
Module not found: Error: Can't resolve 'ng-zorro-antd/src/table/nz-table.component' 

### ISSUE THREAD

**Issue by spt110** [NG-ZORRO/ng-zorro-antd#1523]
## Version

0.7.1

## Environment

mac 

## Reproduction link

[https://stackblitz.com/edit/angular-n9nkkn?file=src%2Fapp%2Ftable-fit.directive.ts](https://stackblitz.com/edit/angular-n9nkkn?file=src%2Fapp%2Ftable-fit.directive.ts)

## Steps to reproduce

ng serve
报错
Module not found: Error: Can't resolve 'ng-zorro-antd/src/table/nz-table.component' 

## What is expected?

import { NzTableComponent } from 'ng-zorro-antd/src/table/nz-table.component';

正常解析到NzTableComponent类

## What is actually happening?

import { NzTableComponent } from 'ng-zorro-antd/src/table/nz-table.component';
ng serve报
Module not found: Error: Can't resolve 'ng-zorro-antd/src/table/nz-table.component' 

## Other?

mac 和windows都报这个错   无法导入NzTableComponent

**Comment by vthinkxie** [comment]
import 组件的位置不对，应该是
`import { NzTableComponent } from 'ng-zorro-antd'`

**Comment by spt110** [comment]
![image](https://user-images.githubusercontent.com/5217855/40557503-e8e383a6-6082-11e8-952b-9d6d08490582.png)
import { NzTableComponent } from 'ng-zorro-antd'   也试了，不行，不知道什么原因
