### ISSUE TITLE
make it modular to reduce bundle size

### ISSUE THREAD

**Issue by mapsgeek** [NG-ZORRO/ng-zorro-antd#1524]
## What problem does this feature solve?

currently you import a global module for the whole library, what about dividing into small individual modules to enable tree shaking while running build command to reduce final bundle size, mostly like angular material and ng-bootstrap.

## What does the proposed API look like?

import {select} from "antDesign/select"

**Comment by vthinkxie** [comment]
Hi~ @mapsgeek , it will bring no benefit to import small individual modules, because all dependencies of`ng-zorro-antd` can be tree-shaked, so all module can be tree-shaked even if you import all module of ng-zorro-antd now, you can use source-map-explorer to explore the size of each bundle.
here is an example if you only use button after import all module of ng-zorro-antd
![tb1d8mxdttybenjy1xdxxxxyvxa-2864-1592](https://user-images.githubusercontent.com/1506722/40522005-31e68d32-6001-11e8-9180-bbe1389bddc2.jpg)

**Comment by mapsgeek** [comment]
well for me it's not the same case, i use webpack bundle analyzer, and i will provide you with 3 shots with 3 different cases that seems to end up the same, everything is being imported !

here i'm just importing the **NgZorroAntdModule** in app.module for root

**first running ng build -aot**
the size of antd.js is 1.2 MB, and the less file is 530 KB.

![capture](https://user-images.githubusercontent.com/10188264/40560038-0bea418e-6059-11e8-9cb3-55bc6006bfc3.JPG)

**here i run ng build --prod**

![capture](https://user-images.githubusercontent.com/10188264/40560187-89661570-6059-11e8-87b1-c0b0601a48ab.JPG)

again i don't use in components in my app, i just import the **NgZorroAntdModule** in app.module
and you can compare the number of modules +59 against the next shot where i remove the import for  **NgZorroAntdModule** completely  with only +17 modules, so i think everything from NgZorro is being imported that way, isn't it ?!

![capture](https://user-images.githubusercontent.com/10188264/40560320-ef59e870-6059-11e8-90bb-7da1d703ce3e.JPG)

**Comment by vthinkxie** [comment]
@mapsgeek the module is only an empty shell, all the component in it are shaked
you can use export the below link and use webpack-bundle-analyzer after `ng build --prod --stats-json`

in the link below
https://stackblitz.com/edit/ng-zorro-antd-setup-mkmith?file=app/app.component.html
<img width="570" alt="2018-05-26 9 45 22" src="https://user-images.githubusercontent.com/1506722/40571330-8693d4a2-60c9-11e8-84c0-d7e867b254cd.png">

you will get
<img width="391" alt="2018-05-26 9 46 00" src="https://user-images.githubusercontent.com/1506722/40571334-9ddabce8-60c9-11e8-8d96-fa66a4125298.png">

after removing select component in the demo

https://stackblitz.com/edit/ng-zorro-antd-setup-cdtyrz?file=app/app.component.html
<img width="611" alt="2018-05-26 9 44 39" src="https://user-images.githubusercontent.com/1506722/40571326-70861bf2-60c9-11e8-8428-6c2b91c16d27.png">

you will get 
<img width="725" alt="2018-05-26 9 43 35" src="https://user-images.githubusercontent.com/1506722/40571320-4d7622a6-60c9-11e8-8661-403c48b4facd.png">

you can see there are about `381.05KB` -`298.46KB` size are shaked after remove the select component.

**Comment by mapsgeek** [comment]
yes you are absolutely right, thank you for your patience .
can't wait for v 1.0 and universal support <3
