### ISSUE TITLE
table 支持 分组显示

### ISSUE THREAD

**Issue by liweitao92** [NG-ZORRO/ng-zorro-antd#1525]
## What problem does this feature solve?

将数据根据某个字段进行分组，用于分类比对

## What does the proposed API look like?

https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/index.htm#demos/jqxgrid/grouping.htm
类是 jqwidgets 分组表格

**Comment by vthinkxie** [comment]
<img width="885" alt="2018-05-25 9 46 08" src="https://user-images.githubusercontent.com/1506722/40521894-775fa9d0-6000-11e8-970a-b29162528206.png">
