### ISSUE TITLE
在弹出气泡框时进行路由跳转，气泡框无法关闭

### ISSUE THREAD

**Issue by yjq8023** [NG-ZORRO/ng-zorro-antd#1527]
## Version

0.7.1

## Environment

win10, 谷歌浏览器

## Reproduction link

[https://github.com/](https://github.com/)

## Steps to reproduce

1.先弹出一个气泡框或提示框，并点击里面的元素进行跳转
   <nz-tooltip [nzTitle]="'作业明细'" [nzPlacement]="'top'">
            <i nz-tooltip routerLink="/detail"  class="icon-book-open"></i>
    </nz-tooltip>
2.可以看到跳转到新的页面后， '作业明细'几个提示文字依旧存在并无法关闭
3.不仅仅是提示文字无法关闭，尝试使用气泡弹框，跳转后依旧无法关闭

## What is expected?

路由跳转后弹出的提示框自动关闭

## What is actually happening?

路由跳转后弹出的提示框没有关闭

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-9bsiux?file=app%2Fapp.component.html
请不要提不可以在线重现的bug
