### ISSUE TITLE
0.7.x的文档中 nz-checkbox 的 属性 ngModel 使用无效， 查代码用 nzChecked 是可以有效的

### ISSUE THREAD

**Issue by shnuXjt** [NG-ZORRO/ng-zorro-antd#1531]
## Version

0.7.1

## Environment

windows、谷歌66.0.3359.181 (Official Build) (64-bit)、0.7.0

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup、](https://stackblitz.com/edit/ng-zorro-antd-setup、)

## Steps to reproduce

npm install ng-ant-zorro 进入项目，项目的页面中使用nz-checkbox ，属性使用 ngModel 但是不成功

## What is expected?

能够双向绑定选择和未选中状态

## What is actually happening?

并未成功绑定

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-6mxbuc?file=app/app.component.ts

**Comment by shnuXjt** [comment]
能顺便解释一下 nzChecked的用法吗

**Comment by vthinkxie** [comment]
不需要使用nzChecked，只是内部的实现而已
