### ISSUE TITLE
error TS2305: Module '"/app-project/node_modules/ng-zorro-antd/antd"' has no exported member 'NzTableComponent'.

### ISSUE THREAD

**Issue by spt110** [NG-ZORRO/ng-zorro-antd#1532]
## Version

0.7.1

## Environment

ng-zorro 0.7.1

## Reproduction link

[https://stackblitz.com/edit/angular-n9nkkn?file=src%2Fapp%2Ftable-fit.directive.ts](https://stackblitz.com/edit/angular-n9nkkn?file=src%2Fapp%2Ftable-fit.directive.ts)

## Steps to reproduce

1.ng build
2.报错如下
ERROR in src/app/core/directive/nz-table-fit.directive.ts(4,10): error TS2305: Module '"/Users/sunpeitao/mycodenew/zeus-app-project-static/node_modules/ng-zorro-antd/antd"' has no exported member 'NzTableComponent'.

## What is expected?

正常使用类 NzTableComponent

## What is actually happening?

ERROR in src/app/core/directive/nz-table-fit.directive.ts(4,10): error TS2305: Module '"/Users/sunpeitao/mycodenew/zeus-app-project-static/node_modules/ng-zorro-antd/antd"' has no exported member 'NzTableComponent'.

**Comment by spt110** [comment]
![image](https://user-images.githubusercontent.com/5217855/40558209-266ef6ea-6085-11e8-9213-38d86cd41c4c.png)
补充报错信息

**Comment by vthinkxie** [comment]
@spt110 是的，我们会在下个版本修复这个问题，感谢反馈
