### ISSUE TITLE
InputNumber not work when int length greater than 16 digit

### ISSUE THREAD

**Issue by SoaringTiger** [NG-ZORRO/ng-zorro-antd#1535]
## Version

0.7.1

## Environment

Angular version: 5.2.5  ng-zorro-antd version: 0.7.1  Browser: - [x] Chrome (desktop) version 66 - [ ] Firefox version XX - [ ] Safari (desktop) version XX - [ ] IE version XX   For Tooling issues: - Node version: v8.11.1   - Platform:  Mac 

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-d5fb6l?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-d5fb6l?file=app%2Fapp.component.html)

## Steps to reproduce

https://stackblitz.com/edit/ng-zorro-antd-setup-d5fb6l?file=app%2Fapp.component.html

## What is expected?

The number greater than 16 digit should work correctly.
大一些的数也应该能正确的显示，并且step按钮能正常工作。

## What is actually happening?

click step button not work.
17位及以上整数，点击step按钮没有反应。

**Comment by vthinkxie** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
