### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'nz-date-picker'

### ISSUE THREAD

**Issue by ultshift** [NG-ZORRO/ng-zorro-antd#1537]
## Version

0.7.1

## Environment

ng-zorro  0.7.1

## Reproduction link

[https://ng-zorro-antd-setup-ffqgpx.stackblitz.io](https://ng-zorro-antd-setup-ffqgpx.stackblitz.io)

## Steps to reproduce

Can't bind to 'ngModel' since it isn't a known property of 'nz-date-picker'

## What is expected?

绑定默认时间

## What is actually happening?

Can't bind to 'ngModel' since it isn't a known property of 'nz-date-picker'

**Comment by vthinkxie** [comment]
demo工作完全正常
<img width="516" alt="2018-05-28 1 14 47" src="https://user-images.githubusercontent.com/1506722/40598231-1eeb94d2-6279-11e8-9a64-f29f3937a5bb.png">
