### ISSUE TITLE
0.7.0打包时会报错误，提示为Property 'nzPlaceHolder' does not exist on type 'NzDatePickerComponent'

### ISSUE THREAD

**Issue by xingyibiao** [NG-ZORRO/ng-zorro-antd#1542]
## Version

0.7.1

## Environment

mac os10.13.3 angular-cli 1.7.4 angular5.2.10 node9.8.0 npm6.0.0

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.module.ts](https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.module.ts)

## Steps to reproduce

项目 ng build --prod 打包时就会报错， 我并没有用到日期组件

## What is expected?

直接编译通过，打包完成

## What is actually happening?

ERROR in node_modules/ng-zorro-antd/antd.d.ts.ɵgo.html(1,228): : Property 'nzPlaceHolder' does not exist on type 'NzDatePickerComponent'. Did you mean 'nzPlaceholder'?
node_modules/ng-zorro-antd/antd.d.ts.ɵgu.html(1,226): : Property 'nzPlaceHolder' does not exist on type 'NzMonthPickerComponent'. Did you mean 'nzPlaceholder'?
node_modules/ng-zorro-antd/antd.d.ts.ɵgv.html(1,228): : Property 'nzPlaceHolder' does not exist on type 'NzWeekPickerComponent'. Did you mean 'nzPlaceholder'?
node_modules/ng-zorro-antd/antd.d.ts.ɵgt.html(1,228): : Property 'nzPlaceHolder' does not exist on type 'NzRangePickerComponent'. Did you mean 'nzPlaceholder'?

**Comment by xingyibiao** [comment]
我切换到0.7.0版本时就会直接打包完成

**Comment by xingyibiao** [comment]
我在0.7.1打包会报错， 刚才我切回到0.7.0才打包完成了，版本应该不会有错误


![6294be7d-d5dc-41b8-a4e3-6035d0923350](https://user-images.githubusercontent.com/24382926/40635869-cbbbcece-632e-11e8-9954-18759741633c.png)

这是我刚才切到0.7.1复现了问题

**Comment by vthinkxie** [comment]
按照提示修改成 `nzPlaceholder` 就可以了，

**Comment by xingyibiao** [comment]
我没有找到这几个文件呀，本来我准备自己修改的。 但是没有找到所以提了个issue

**Comment by vthinkxie** [comment]
这个报错的意思是让你项目中的 `nzPlaceHolder` 替换为 `nzPlaceholder`，全局搜索一下看看

**Comment by xingyibiao** [comment]
开始我也以为是我项目中的， 我改了依旧报这个错。 

![beb798e1-c420-45c8-bfbe-2b8d536dce52](https://user-images.githubusercontent.com/24382926/40640079-0210b94a-6347-11e8-9ecf-89ee9e360344.png)

**Comment by vthinkxie** [comment]
@xingyibiao 官方的demo项目一切正常的，你可以按照刚才我的步骤重试一遍

https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.module.ts
点export下载到本地， npm install & ng build --prod 一切正常

**Comment by ppjjzz** [comment]
0.7.1 , 同样是这个报错

**Comment by vthinkxie** [comment]
@ppjjzz 
你的包绝对装错了，这个是0.7.1目前的打包代码
https://unpkg.com/ng-zorro-antd@0.7.1/src/date-picker/abstract-picker.component.d.ts

**Comment by vthinkxie** [comment]
@ppjjzz 学习一下package-lock.json的相关知识
