### ISSUE TITLE
nz-tree升级之后的nodes只能写死吗？

### ISSUE THREAD

**Issue by onecorner** [NG-ZORRO/ng-zorro-antd#1544]
升级到最新版本后，不能对查询出来的数据进行绑定了，也就是说node必须要写死，不能先查询出来再进行赋值，然后设置默认checked，由于框架里面使用的就是最新版本的zorro，所以不能回退，请问针对这个问题有什么解决方案？

**Comment by simplejason** [comment]
@onecorner 你可以修改ngModel值来实现重新渲染tree，初始值可定义你想要的值，参考 [demo](https://stackblitz.com/edit/angular-cbsukc-chirrv?file=app/app.component.ts)
