### ISSUE TITLE
modal and notification z-index bug

### ISSUE THREAD

**Issue by eevin** [NG-ZORRO/ng-zorro-antd#1546]
## Version

0.7.1

## Environment

linux服务器，google浏览器

## Reproduction link

[https://ng-zorro-antd-setup.stackblitz.io](https://ng-zorro-antd-setup.stackblitz.io)

## Steps to reproduce

The development environment

![image](https://user-images.githubusercontent.com/21354993/40646355-78aefc6a-635b-11e8-805f-1b54928794c8.png)

![image](https://user-images.githubusercontent.com/21354993/40646023-ac5d3adc-635a-11e8-9fdf-0384ef80c49e.png)

when I ng build 

The production environment

![image](https://user-images.githubusercontent.com/21354993/40646391-99429c7a-635b-11e8-9522-d81988e19264.png)
![image](https://user-images.githubusercontent.com/21354993/40646400-a10123c8-635b-11e8-9219-a1ad7cefaac2.png)

## What is expected?

生产环境能够正常显示

## What is actually happening?

生产环境modal遮住了notification

**Comment by wilsoncook** [comment]
@eevin Pls provide a correct production link to reproduce this issue

**Comment by eevin** [comment]
when i remove node_modules and npm i  then ok
thanks
