### ISSUE TITLE
nz-silder add a flag to restrict min <= max when it's showing range

### ISSUE THREAD

**Issue by yinjs** [NG-ZORRO/ng-zorro-antd#1547]
## What problem does this feature solve?

In most of the case user expect min <= max, or the range value auto sort from min -> max

## What does the proposed API look like?

<nz-slider someFlagNameToRestrictMin<=Max ></nz-slider>

**Comment by wendzhue** [comment]
@yinjs This is considered a bug now. So please track itin 2373.
