### ISSUE TITLE
Can not show icon correctly

### ISSUE THREAD

**Issue by tigercosmos** [NG-ZORRO/ng-zorro-antd#155]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

![](https://raw.githubusercontent.com/tigercosmos/webImg/master/ng-zorro-antd-1.JPG)

## Expected behavior

It should work as https://ng.ant.design/#/components/form example.

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: 6.11.2  
- Platform: Win10 

Others:

</code></pre>

**Comment by vthinkxie** [comment]
make sure you have used nz-root for this version and read this doc again
https://ng.ant.design/#/components/icon
