### ISSUE TITLE
表单验证错误

### ISSUE THREAD

**Issue by qq253498229** [NG-ZORRO/ng-zorro-antd#1551]
## Version

0.7.1

## Environment

macOS10.13.4/Google Chrome 版本 66.0.3359.181（正式版本） （64 位）/ng-zorro-antd@0.7.1

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-v6gakc?embed=1&file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-v6gakc?embed=1&file=app/app.component.html)

## Steps to reproduce

#name="ngModel"

## What is expected?

#name="ngModel" 希望支持这种写法

## What is actually happening?

#name="ngModel" 不支持这种写法

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-pef3w2?file=app/app.component.html
仔细看下官网关于ngModel的部分
https://angular.io/guide/forms#show-and-hide-validation-error-messages
你的ngModel都没用声明，怎么能在模板中间export出去呢？
