### ISSUE TITLE
nz-select tags - I want to use tags and limit the number of tags

### ISSUE THREAD

**Issue by sunscheung** [NG-ZORRO/ng-zorro-antd#1553]
## What problem does this feature solve?

nz-select  [nzMode]= "'tags'" select
Tags select, random input, enter key to add tag ，but not support limit Selection. I need add  a option like maxSelectionLength to limit tag number
(随意输入的内容，回车键新增tag,但不支持限制多选的个数,我希望增加一个配置限制多选个数)

## What does the proposed API look like?

add a option like :   maxSelectionLength: 1 

参数  | 说明 | 类型 | 默认值
---- | ---- | ---- | ----  
nzMode | 设置 Select 的模式 | 'multiple' | 'tags' | -
nzMaxSelectionLength | 当添加该属性时，设置限制多选个数仅对多选有效 | number | 0

```
import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'nz-demo-select-tag',
  template: `
    <nz-select 
      [nzMode]="'tags'" 
      [nzMaxSelectionLength]="1" 
      [nzPlaceHolder]="'请选择人员'"
      [(ngModel)]="selectedMultipleOption"
      [nzNotFoundContent]="'无法找到'"
      [nzShowSearch]="true">
      <nz-option
        *ngFor="let option of searchOptions"
        [nzLabel]="option.label"
        [nzValue]="option">
      </nz-option>
    </nz-select>
  `,
  styles  : []
})
export class NzDemoSelectTagComponent implements OnInit {
  searchOptions = [
    { value: 'jack', label: '杰克' },
    { value: 'lucy', label: '露西' },
    { value: 'tom', label: '汤姆' }
  ];
  selectedMultipleOption = [ this.searchOptions[ 0 ] ];
  constructor() {
  }
  ngOnInit() {
    setTimeout(_ => {
      this.selectedMultipleOption = [];
    }, 2000)
  }
}
```

**Comment by vthinkxie** [comment]
提问之前请仔细查看文档
`nzMaxMultipleCount `
https://stackblitz.com/edit/angular-ybvjad?file=app/app.component.ts

**Comment by sunscheung** [comment]
谢谢 vthinkxie @simplejason

**Comment by sunscheung** [comment]
0.5.x版本源码中有这个nzMaxMultiple参数，相当于nzMaxMultipleCount功能，
但是具体如何实现，竟然没找到。
有同样需求的人采纳，有知道如何实现的，留言。
谢谢！
@simplejason  ngModelChange处理起来还是比较麻烦的....
