### ISSUE TITLE
我们使用了树组件，在初始化树结构时，[nzDefaultCheckedKeys]="selectedKeys",selectedKeys 中有父节点的key ，但其子节点并未全部勾选，却因为父节点的把下面的子节点全部勾选了，这个问题能否解决一下，非常紧急，谢谢

### ISSUE THREAD

**Issue by kingna** [NG-ZORRO/ng-zorro-antd#1555]

**Comment by simplejason** [comment]
请具体描述应用场景,编辑这个[demo](https://stackblitz.com/edit/angular-arsjae?file=app/app.component.ts)，nzDefaultCheckedKeys会关联子节点

**Comment by yyicon** [comment]
I also encountered the same problem

**Comment by simplejason** [comment]
@yyicon please edit the demo link above to provide more information

**Comment by yyicon** [comment]
The selected node I got is returned from the server. The demo may not be demonstrated

**Comment by simplejason** [comment]
@yyicon maybe you can describe the problems you have met in detail and then we will help you, I don't understand how you use it.

**Comment by yyicon** [comment]
in html:
 <nz-tree
                    *ngIf="isOpen"
                    [ngModelOptions]="{standalone: true}"
                    [(ngModel)]="nodes"
                    [nzCheckable]="true"
                    [nzMultiple]="true"
                    [nzDefaultExpandAll]="expandDefault"
                    [nzDefaultExpandedKeys]="expandKeys"
                    [nzDefaultCheckedKeys]="checkedKeys"
                    (nzCheckBoxChange)="mouseAction('click',$event)"
                    (nzDblClick)="mouseAction('dblclick', $event)"
                  >`
No problem tree initialization，I posted the code to open Modal
in Component
 checkedKeys = [];
  expandKeys = [];
openPermsModal(event, item) {
    this.service.getData("/sys/role/info/" + item.roleId, res => {
      this.checkedKeys = res.role.menuIdList;
      this.expandKeys = res.role.menuIdList;
    });
  }

thank you for your help

**Comment by yyicon** [comment]
I have solved this problem. If I want to display normally, I can only add the leaf node to nzDefaultCheckedKeys. Before I wrote it wrong, thank you.

**Comment by simplejason** [comment]
@yyicon this [PR](https://github.com/NG-ZORRO/ng-zorro-antd/pull/1477/files#diff-8c93355fb4cf5035120d6ce9107977c2) has supported nzDefaultCheckedKeys asynchronously
