### ISSUE TITLE
It is very inconvenient to modify the Zorro component style through CSS files.

### ISSUE THREAD

**Issue by StarkL** [NG-ZORRO/ng-zorro-antd#1556]
## What problem does this feature solve?

In the angular-cli configuration, when webpack is compiled, the CSS selector I write is added an attribute selection (for example: _ngcontent-c1), and the Zorro component's label has not be added, which causes my CSS selector can not select the components in the Zorro, so that the style of the Zorro component can not be changed conveniently.

```html
  <div class="table-wrap">
  <!-- My code will be converted to the following format -->
  <div _ngcontent-c1="" class="table-wrap">
  
  <!-- But some Zorro tags will not be converted in this way, like this -->
  <thead class="ant-table-thead ng-star-inserted">
```

## What does the proposed API look like?

Zorro components,  like the HTML tags written by myeself, are added Angular attributes, so that my CSS can choose the tags correctly.

**Comment by StarkL** [comment]
I'm not good at English. Please forgive me.

**Comment by vthinkxie** [comment]
https://angular.cn/guide/component-styles#inspecting-generated-css

**Comment by StarkL** [comment]
I saw the official website explained, thank you!

But some component labels of Zorro will not be added to these attributes. Why?

**Comment by vthinkxie** [comment]
some components in ng-zorro-antd are compiled, transformed or removed after view init.
