### ISSUE TITLE
图片裁剪组件

### ISSUE THREAD

**Issue by freezyh** [NG-ZORRO/ng-zorro-antd#1557]
## What problem does this feature solve?

上传图片到服务器之前可以自由裁剪图片尺寸大小

## What does the proposed API look like?

裁剪成功后返回裁剪成功的方法

**Comment by vthinkxie** [comment]
<img width="867" alt="2018-05-30 6 17 32" src="https://user-images.githubusercontent.com/1506722/40714620-be178c06-6435-11e8-838c-932601652ac3.png">
