### ISSUE TITLE
有没有一套通用的CSS样式库的？类似于Bootstrap的

### ISSUE THREAD

**Issue by litttlefisher** [NG-ZORRO/ng-zorro-antd#156]
在使用`ng-zorro-antd`时，对于`css`样式有些无从下手。例如类似于`bootstrap`的`panel panel-default`等等这种通用型的`css`样式，不知在`ng-zorro-antd`中是否有提供

**Comment by LinBoLen** [comment]
ant design style is awesome. but the less file lack of  flexible reuse.

change or refactor less to be more Sleek, intuitive, and powerful is indeed.

**Comment by vthinkxie** [comment]
please do not request any css file change or feathers here.
if you want more css implements, please go to https://github.com/ant-design/ant-design
