### ISSUE TITLE
inline style margin style breaks grid overflow

### ISSUE THREAD

**Issue by mapsgeek** [NG-ZORRO/ng-zorro-antd#1564]
## Version

0.7.1

## Environment

angular 5.2. chrome

## Reproduction link

[https://angular-dcunhs.stackblitz.io/](https://angular-dcunhs.stackblitz.io/)

## Steps to reproduce

add gutter to the grid

## What is expected?

no margin rule override

## What is actually happening?

inline style override the margin-left/right:0; causing overflow

**Comment by vthinkxie** [comment]
Hi, ng-zorro-antd keep the same with antd react version, you can get more details in
https://github.com/ant-design/ant-design/issues/10144
