### ISSUE TITLE
穿梭框 nzChange事件增加一个回调函数功能，如果回调函数结果为真时，则允许执行穿梭项目改变，否则不允许执行。

### ISSUE THREAD

**Issue by feiyingkeba** [NG-ZORRO/ng-zorro-antd#1566]
## What problem does this feature solve?

这个要求不同与canMove功能。或者将canMove功能融合到nzChange中，有时候在进行穿梭时，左边的可以看做数据源，右边为目标区域，左边向右边穿梭时，是要检测重复，或者其他一些条件判断，在允许后才执行穿梭操作。现在是我自己进行判断了，但UI上已经执行了穿梭操作，尽管该项目是不被允许的。希望可以把这两个函数合并为一个，比较有效节省时间，和实现步骤。

## What does the proposed API look like?

onChange(moveChange:TransferChange,canMove:bool|fun)

**Comment by cipchk** [comment]
`canMove` 的结果将影响是否穿梭，且支持 `Observable` 基本上可以做复杂的操作。
