### ISSUE TITLE
why there are so many nz prefix

### ISSUE THREAD

**Issue by LinBoLen** [NG-ZORRO/ng-zorro-antd#157]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

every fork version will know it build from a ng-zorro project, because there are stupid nz prefix

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
avoid conflict with other ui components.

**Comment by LinBoLen** [comment]
the input output name ?

**Comment by vthinkxie** [comment]
if you used more than one directives on one html tag, you will understand why.

**Comment by LinBoLen** [comment]
so i need to use  [nzMin]="min" [min]="min" both? also [nzMax], [max]

**Comment by vthinkxie** [comment]
think again.

**Comment by LinBoLen** [comment]
any problem? i introduce in, no mean i will absolutely inquire them. component should be easy to customize and free to reuse. not with a lot of self define tag. 

such as namespace is designed to reduce of name collision. when no namespace, developer will write a lot of prefix, and it's hard to migrate and customize

**Comment by vthinkxie** [comment]
please think again before you comment or submit any issue.
