### ISSUE TITLE
nz-range-picker能同时支持nzPlaceholder和nzPlaceHolder

### ISSUE THREAD

**Issue by Guoyilin10** [NG-ZORRO/ng-zorro-antd#1571]
## What problem does this feature solve?

升级到0.7.1版本后，nz-range-picker不支持nzPlaceholder了，项目已经成型，需要每个页面去修改，非常非常的麻烦。希望同时支持这两种写法，

## What does the proposed API look like?

升级到0.7.1版本后，nz-range-picker不支持nzPlaceholder了，项目已经成型，需要每个页面去修改，非常非常的麻烦；希望能够同时支持这两种写法，下次对于类似的这种情况，希望能够在文档中说明已修改及修改原因，不然，真的很坑

**Comment by vthinkxie** [comment]
全局搜索替换一下？
