### ISSUE TITLE
cdn problem(Forgive me for not using the following link)

### ISSUE THREAD

**Issue by asself** [NG-ZORRO/ng-zorro-antd#1576]
The ng-zorro-antd version I use is 0.6.x, When I try to add @ icon-url in 'styles / custom-variables.less', I find that iconfont will be loaded twice, one from the local and the other from cdn. Is this a bug that has been fixed? How can I solve this problem if I still use this version for the time being?

**Comment by vthinkxie** [comment]
@asself plz upgrade to 0.7.x and 0.6.x is not under maintain any longer.
you can modify source code from the 0.6.15 tag from ng-zorro-antd and publish your own package if you want to use it .
