### ISSUE TITLE
Add Custom props to tree node

### ISSUE THREAD

**Issue by hsbalar** [NG-ZORRO/ng-zorro-antd#1580]
## What problem does this feature solve?

Can we have feature that node can contains more information other than title, key, isLeaf etc

## What does the proposed API look like?

have different icon based on json,
can display more information instead only title,
can have html template

**Comment by vthinkxie** [comment]
Hi @hsbalar 
please read the doc
https://ng.ant.design/components/tree/en#components-tree-demo-customized-icon
you can change all template if you want
https://stackblitz.com/edit/angular-d3ury1?file=app/app.component.ts

<img width="490" alt="2018-06-01 9 51 13" src="https://user-images.githubusercontent.com/1506722/40844228-f0a2b356-65e5-11e8-9225-63e41311b519.png">

**Comment by vthinkxie** [comment]
@hsbalar it is very easy to custom your own tree using template, it can transform any json to the template you want.

**Comment by hsbalar** [comment]
I'm not able to provide custom JSON, when Initialising tree. 
```
nodes = [
    new NzTreeNode({
      title   : 'root1',
      key     : '1001',
      type    : 'a',
      status  :''
  })
];
```

**Comment by vthinkxie** [comment]
@simplejason

**Comment by vthinkxie** [comment]
@hsbalar https://stackblitz.com/edit/angular-d3ury1?file=app/app.component.ts 
you can use this as temp solution, there are some typescript definition lost in our interface,
thanks for your feedback, we will fix it in next version.

**Comment by hsbalar** [comment]
Your welcome @vthinkxie.

**Comment by simplejason** [comment]
#1584
