### ISSUE TITLE
编译发布后分页的页码 会变成变量名

### ISSUE THREAD

**Issue by tianxiaozi** [NG-ZORRO/ng-zorro-antd#1586]
## Version

0.7.1

## Environment

mac 最新版chrome

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.ts1](https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.ts1)

## Steps to reproduce

执行命令：ng build -prod --env=test -d https://xxxx

部署到服务器后 分页会出现这些变量名

10Pagination.items_per_page
Pagination.jump_to 
Pagination.page

## What is expected?

解决它

## What is actually happening?

10Pagination.items_per_page
Pagination.jump_to 
Pagination.page

**Comment by kingna** [comment]
请问这个问题解决了吗

**Comment by vthinkxie** [comment]
@kingna 看下国际化注册部分
