### ISSUE TITLE
nz-tag how change style

### ISSUE THREAD

**Issue by windsOne** [NG-ZORRO/ng-zorro-antd#1593]
## What problem does this feature solve?

i thinke this tag is very small   i want change size
nz-tag

## What does the proposed API look like?

i think 'nz-tag' can change size

**Comment by windsOne** [comment]
![image](https://user-images.githubusercontent.com/14890297/40893723-2f0e8b6e-67d6-11e8-8a4b-190ab9e3f19d.png)

**Comment by simplejason** [comment]
you can change `.ant-tag` style like `.ant-tag { height: 30px}`
