### ISSUE TITLE
Support contextmenu component

### ISSUE THREAD

**Issue by shaodahong** [NG-ZORRO/ng-zorro-antd#16]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

Enterprise-class there are a lot of contextmenu, this can support ?

**Comment by shaodahong** [comment]
Contextmenu supports icons, shortcuts and subclasses

**Comment by wilsoncook** [comment]
The Contextmenu is currently for our internal use, the component may be coming later, thanks for your attention !

**Comment by shaodahong** [comment]
@wilsoncook OK, I am looking forward

**Comment by candy4290** [comment]
@vthinkxie where is the doc?i can't find it.

**Comment by vthinkxie** [comment]
@candy4290 https://ng.ant.design/version/0.7.x/components/dropdown/zh#components-dropdown-demo-context-menu

**Comment by courage007** [comment]
I visit @vthinkxie 's url ,but it redirects to  [index page](https://ng.ant.design/docs/introduce/zh). So it 
closed the source？

**Comment by vthinkxie** [comment]
@courage007 https://ng.ant.design/components/dropdown/zh
