### ISSUE TITLE
ng-zorro-antd 0.7.0 icon deploy locally error

### ISSUE THREAD

**Issue by 0o0o0o0o0o0o0** [NG-ZORRO/ng-zorro-antd#1600]
![image](https://user-images.githubusercontent.com/39577696/40915851-25a4af4a-6830-11e8-9b2c-03977748b622.png)

![image](https://user-images.githubusercontent.com/39577696/40915862-2edbef1a-6830-11e8-877a-db33e060b6a9.png)

![image](https://user-images.githubusercontent.com/39577696/40915867-362ad52e-6830-11e8-828d-e75083e05afc.png)

ERROR in ./src/styles.less (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/less-loader/dist/cjs.js??ref--15-3!./src/styles.less)
(Emitted value instead of an instance of Error)

   8 |   src:
   9 |   /* chrome、firefox */
> 10 |   url('@{icon-url}.woff') format('woff'),
     |      ^
  11 |   /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
  12 |   url('@{icon-url}.ttf') format('truetype'),

  10 |   url('@{icon-url}.woff') format('woff'),
  11 |   /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
> 12 |   url('@{icon-url}.ttf') format('truetype'),
     |      ^
  13 |   /* iOS 4.1- */
  14 |   url('@{icon-url}.svg#iconfont') format('svg');

  5 | @font-face {
  6 |   font-family: 'anticon';
> 7 |   src: url('@{icon-url}.eot'); /* IE9*/
    |           ^
  8 |   src:
  9 |   /* chrome、firefox */

**Comment by fanweimei** [comment]
+1
