### ISSUE TITLE
树组件使用自定义模版，无法实现高亮搜索结果。

### ISSUE THREAD

**Issue by vellengs** [NG-ZORRO/ng-zorro-antd#1601]
## What problem does this feature solve?

树组件使用自定义模版，能实现高亮搜索结果。

## What does the proposed API look like?

提供 matchValue 到模版上下文。

**Comment by simplejason** [comment]
你可以使用`nzOnSearchNode`事件获取匹配的节点，配合input组件自行实现自定义高亮(nzOnSearchNode emit事件做了简单修改，空字符输入也会emit回来，可以追踪这个PR #1602)

**Comment by vellengs** [comment]
可否在demo 演示示例增加这个示例效果，我想大多数人还是这个示例的，毕竟不想自定义了，马上丢失了这个功能效果。

**Comment by crane168** [comment]
我也遇到了这个问题，大家是怎么解决的呢，就是自定义树节点模板，搜索时候不能高亮

**Comment by crane168** [comment]
> 可否在demo 演示示例增加这个示例效果，我想大多数人还是这个示例的，毕竟不想自定义了，马上丢失了这个功能效果。

你这个问题解决了吗

**Comment by s641135196** [comment]
我用了自定义的， 不可以高亮显示了。

**Comment by s641135196** [comment]
> > 可否在demo 演示示例增加这个示例效果，我想大多数人还是这个示例的，毕竟不想自定义了，马上丢失了这个功能效果。
> 
> 你这个问题解决了吗
