### ISSUE TITLE
[0.7.1] Autocomplete 的键盘选择支持不会更改滚动条位置缺陷

### ISSUE THREAD

**Issue by canaanjin** [NG-ZORRO/ng-zorro-antd#1604]
## What problem does this feature solve?

希望和nz-select一样在键盘选择项超出时 对滚动条进行重新设定
![ddd](https://user-images.githubusercontent.com/12317236/40951818-535daea2-68ab-11e8-8a16-9e3e01598a09.gif)

**Comment by vthinkxie** [comment]
fixed in #1533 
will be released in next version.
