### ISSUE TITLE
ng-zorro-antd 0.7.0 icon deploy locally error

### ISSUE THREAD

**Issue by 0o0o0o0o0o0o0** [NG-ZORRO/ng-zorro-antd#1605]
## Version

0.7.1

## Environment

win10 64、chrome65

## Reproduction link

[https://ng-zorro-antd-setup.stackblitz.io/](https://ng-zorro-antd-setup.stackblitz.io/)

## Steps to reproduce

@icon-url    : "./assets/iconfont"; 

## What is expected?

icon deploy locally

## What is actually happening?

ERROR in ./src/styles.less (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/less-loader/dist/cjs.js??ref--15-3!./src/styles.less)
(Emitted value instead of an instance of Error)

8 | src:
9 | /* chrome、firefox */

10 | url('@{icon-url}.woff') format('woff'),
| ^
11 | /* chrome、firefox、opera、Safari, Android, iOS 4.2 */
12 | url('@{icon-url}.ttf') format('truetype'),

10 | url('@{icon-url}.woff') format('woff'),
11 | /* chrome、firefox、opera、Safari, Android, iOS 4.2 */

12 | url('@{icon-url}.ttf') format('truetype'),
| ^
13 | /* iOS 4.1- */
14 | url('@{icon-url}.svg#iconfont') format('svg');

5 | @font-face {
6 | font-family: 'anticon';

7 | src: url('@{icon-url}.eot'); /* IE9*/
| ^
8 | src:
9 | /* chrome、firefox */

## Other?
![123](https://user-images.githubusercontent.com/39577696/40954789-bbb930c2-68b8-11e8-8b7a-4386557c4f86.png)
![1](https://user-images.githubusercontent.com/39577696/40954816-d8c583aa-68b8-11e8-8e21-b7ffbf3e53a8.png)

**Comment by vthinkxie** [comment]
less环境问题，和ng-zorro-antd没有任何关系，请仔细检查本地配置和相对路径
