### ISSUE TITLE
1.0 版本文档校对

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#1615]
Hi，我们即将发布 1.0 正式版本，目前文档部分已经基本编写完成
为了能够给正式版用户一个更简单明了的上手文档
欢迎大家通过下面的链接（该链接会根据反馈逐步更新）协助我们进行文档校对

https://deploy-preview-1610--ng-zorro-master.netlify.com/docs/introduce/zh

**请注意：目前测试版本发布在 next tag上，ng add 时需要执行 `ng add ng-zorro-antd@next`**

如果发现：
* 语句不通顺
* 错别字
* 难以理解的部分
* 英文翻译错误
* 链接错误

等任何问题

欢迎在该ISSUE下留言
感谢大家的协助

**Comment by hstarorg** [comment]
可不可以发布一个 `ng-zorro-antd@next` 用来体验1.0呢？

**Comment by chichujn** [comment]
随便说一个。
nz-date-picker, nz-range-picker的共同参数nzPlaceHolder，虽然名称是一样的，但是对应类型是不同的。
文档里说明是string / string []，猜测nz-date-picker使用的是toString()，而nz-range-picker使用的是split().toString()，最好还是分开单列。

**Comment by vthinkxie** [comment]
@chichujn 已经修改，可以在上面的链接查看

**Comment by chichujn** [comment]
@vthinkxie 👍

**Comment by vthinkxie** [comment]
@hstarorg 今天晚些时候会发布一个next版本给大家试用

**Comment by hstarorg** [comment]
@vthinkxie 非常感谢，昨天根据 Changelog，0.7.1 + 6.x 也还ok。

**Comment by JCqiu** [comment]
TreeSelect会在0.7.2发布么

**Comment by vthinkxie** [comment]
@JCqiu 没有0.7.2版本了，可以直接升级到1.0，ng-zorro-antd 没有break change

**Comment by vthinkxie** [comment]
使用 ng add ng-zorro-antd@next 即可体验最新版本，有问题欢迎反馈

**Comment by spt110** [comment]
ng add ng-zorro-antd@next  跑起来了；   每个版本最好提供一个完整脚手架， 每次都折腾各种npm版本
