### ISSUE TITLE
表格固定列的兼容性问题

### ISSUE THREAD

**Issue by oridark** [NG-ZORRO/ng-zorro-antd#1617]
## What problem does this feature solve?

目前表格固定列用的是position:sticky属性来实现的，只支持最新几版的浏览器，比如chrome65之后的浏览器。兼容性极差（即使不考虑ie，现在的兼容性也不算好）。希望能使用类似ant design的方案，做到较强的兼容性。

## What does the proposed API look like?

至少兼容chrome49版本

**Comment by vthinkxie** [comment]
这部分工作我们已经进行过尝试，ant design方案的多表格兼容性在目前的nz-table设计下基本上不能实现，即不能既可以灵活自定义table的每一项又可以精确复制每一项的定义到多个表格上。
除非整个table改成和ant design一样的api调用方式，这样会引起整个table全部break change

**Comment by oridark** [comment]
如果是个人项目我觉得无所谓，但是 to B甚至 to C的项目里，这样做兼容性风险很大，心塞啊，感觉我们要自己对表格封装打补丁了，看看覆盖样式或者修改dom结构能不能兼容

**Comment by JCqiu** [comment]
可以不可以列表拖动宽度

**Comment by vthinkxie** [comment]
@JCqiu 表格的拖拽antd react就没有支持，我们没有对应的交互

**Comment by JCqiu** [comment]
那可不可指出哪些代码或者api可以进行修改，可以在生产环境下开发者自己来实现拖拽宽度 @vthinkxie

**Comment by vthinkxie** [comment]
@JCqiu 自己看下源码好了，其实nz-table的实现很简单，就是把用户的各种td tr的设置复制到了对应的位置上，然后增加了分页支持

**Comment by JCqiu** [comment]
@vthinkxie 谢谢

**Comment by BerQin** [comment]
@vthinkxie 
nz-range-picker 这个组件有一个属性 nzRanges 的使用上，默认的变化和内容都还算不错，但是如果我点选了自己预设的日期范围，有时候需要知道点选的属性是什么属性怎么怎么办？ nzRanges 直接给一个对象，Key是标题，对应的是一个简单的数组，还是不够用，需要给一个回调函数或者，给一个方法可以在点选后知道自己点选的是什么预设？

**Comment by vthinkxie** [comment]
@BerQin 提需求请新开issue

**Comment by oridark** [comment]
是不是在0.7.x中所有的组件基准大小都做了调整，感觉都相对之前放大了好多 @vthinkxie

**Comment by vthinkxie** [comment]
@oridark 0.7.x 按照 Ant Design 3.0 标准设计

**Comment by FaussYao** [comment]
@vthinkxie 这边想自己实现nz-table,  如何把用户的各种td tr的设置复制到了对应的位置上
这边已可以使用@contentChildren 获取投影中dom ，后续如何操作

**Comment by WeCantStop** [comment]
@vthinkxie 如果我想使用ant在IE11中实现列固定，这个通过修改代码可以实现吗？
