### ISSUE TITLE
nztree绑定数据时有问题

### ISSUE THREAD

**Issue by Zhouuuuuuuuu** [NG-ZORRO/ng-zorro-antd#1618]
## Version

0.7.1

## Environment

---

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-kqnlsp?file=app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-kqnlsp?file=app/app.component.ts)

## Steps to reproduce

当数据源中节点checked为false时，nzClick返回的event.node.isChecked为true（数据源中checked为true时正常），具体可见重现链接中console.log.

## What is expected?

正确返回event.node.isChecked

## What is actually happening?

错误的event.node.isChecked

**Comment by simplejason** [comment]
如果你希望同步checked和selected状态，可以手动设置isChecked/isAllChecked/isHalfChecked(如有需要)状态 [demo](https://stackblitz.com/edit/ng-zorro-antd-setup-bdo7zk?file=app/app.component.ts) ，event.node是组件返回的结果
