### ISSUE TITLE
layout-trigger cover nz-menu in nz-sider when overflow

### ISSUE THREAD

**Issue by chichujn** [NG-ZORRO/ng-zorro-antd#1621]
## Version

0.7.1

## Environment

Windows 10 64bit, Chrome 66, ng-zorro 0.7.1

## Reproduction link

[https://ng-zorro-antd-setup-zkxsjw.stackblitz.io](https://ng-zorro-antd-setup-zkxsjw.stackblitz.io)

## Steps to reproduce

Create nz-sider with style "overflow: auto;" and nzCollapsible.
layout-trigger will cover both scrollbar and elements at bottom side when overflow. 

## What is expected?

layout-trigger should sit under bottom of nz-sider.

## What is actually happening?

As described above.

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-jncwxw?file=app/app.component.html
just add margin-bottom

**Comment by chichujn** [comment]
ps: add z-index to nz-sider to make scrollbar  visible totally
