### ISSUE TITLE
table 加上 nzScroll 表头和表格宽度对不齐

### ISSUE THREAD

**Issue by tianxiaozi** [NG-ZORRO/ng-zorro-antd#1622]
## Version

0.7.1

## Environment

mac chrome 最新版

## Reproduction link

[https://stackblitz.com/edit/angular-anbgkn?file=app/app.component.ts](https://stackblitz.com/edit/angular-anbgkn?file=app/app.component.ts)

## Steps to reproduce

nzScroll 去掉这个属性就能对齐了

## What is expected?

对齐

## What is actually happening?

表头和表格没法对齐

**Comment by vthinkxie** [comment]
需要设定 `nzWidth`
https://stackblitz.com/edit/angular-anbgkn-yn2btz?file=app/app.component.ts

**Comment by kingna** [comment]
设定了nzWidth,为什么还是不对齐呢
