### ISSUE TITLE
When set [nzInlineCollapsed]="true" by default with nz-menu directive will get 'ExpressionChangedAfterItHasBeenCheckedError'.

### ISSUE THREAD

**Issue by Sioxas** [NG-ZORRO/ng-zorro-antd#1625]
## Version

0.7.1

## Environment

Windows 10, Chrome 66, ng-zorro:0.7.1

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-nr1t9m](https://stackblitz.com/edit/ng-zorro-antd-setup-nr1t9m)

## Steps to reproduce

When set [nzInlineCollapsed]="true" by default with nz-menu directive will get 'ExpressionChangedAfterItHasBeenCheckedError'.

Open demo page: https://ng-zorro-antd-setup-nr1t9m.stackblitz.io  
Open developer tools in Chrome, and we can meet an error in console.

## What is expected?

No error.

## What is actually happening?

Got the error in console:   
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ant-menu-vertical: false'. Current value: 'ant-menu-vertical: true'.

## Other?

Workaround:  
```js
this.isCollapsed = false  
ngOnInit() {  
    setTimeout(()=>{  
        this.isCollapsed = true  
    })  
}  
```

**Comment by vthinkxie** [comment]
will be fixed in next version, thanks for your feedback.
