### ISSUE TITLE
关于时间预设值的回调函数

### ISSUE THREAD

**Issue by BerQin** [NG-ZORRO/ng-zorro-antd#1628]
# What problem does this feature solve?
nz-range-picker 这个组件有一个属性 nzRanges 的使用上，默认的变化和内容都还算不错，但是如果我点选了自己预设的日期范围，有时候需要知道点选的属性是什么属性怎么怎么办？ nzRanges 直接给一个对象，Key是标题，对应的是一个简单的数组，还是不够用，需要给一个回调函数或者，给一个方法可以在点选后知道自己点选的是什么预设？

**Comment by SimpLe-Yu** [comment]
nz-range-picker　如何设置初期值啊？

**Comment by BerQin** [comment]
@SimpLe-Yu ngmodel绑定一个date类型的数组，2个  比如  [ngmodel]="date"
