### ISSUE TITLE
An example of the official website is inappropriate

### ISSUE THREAD

**Issue by thegatheringstorm** [NG-ZORRO/ng-zorro-antd#163]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

![6042576032](https://user-images.githubusercontent.com/20680370/29741738-f4ed6536-8aa4-11e7-8ed9-b2bd78b0d00d.gif)
I have 5 items (0,1,2,3,4).
Touch the delete button of the item named 0,so the first item has gone 
Next ,Touch the delete button of the item named 1,but * the item named 2* has gone
## Expected behavior

Touch the delete button of the item named 1,* the item named 1* has gone

## Minimal reproduction of the problem with instructions

The Index of the array has refreshed.But the item didn't.
## What is the motivation / use case for changing the behavior?

More precise

## Environment

<pre><code>
Angular version: 4.4.3

ng-zorro-antd version: 0.4.0

Browser:
- [x] Chrome (desktop) version 60.0.3112.78 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by vthinkxie** [comment]
thanks for your feedback.
