### ISSUE TITLE
I wanner a OK button for the datepiker even if  I don't use the 'nzShowTime'

### ISSUE THREAD

**Issue by cyhjojo** [NG-ZORRO/ng-zorro-antd#1635]
## What problem does this feature solve?
Just as the title,I found that I cannot make a ok button if  I don't use the 'nzShowTime'.However, I need no detail time for my project ,I only need date.
And I have another question, but I cannot reappear the code. I used the
disabledDate = (current: Date): boolean => {
    return differenceInDays(current, this.today) > 0 ;
  }
to limit the date range ,but  the fact is I got one more day.For example, today is 6/11.when I limit the day to today ，the result is 6/12.I don't know why...

## What does the proposed API look like?
I wanner a OK button for the datepiker even if  I don't use the 'nzShowTime'

**Comment by ppjjzz** [comment]
me too

**Comment by simplejason** [comment]
ng zorro's  design is consistent with ant design

**Comment by wilsoncook** [comment]
Marks: current feature is against to Ant Design, consider to provide a new option to support this demand.

**Comment by wilsoncook** [comment]
@cyhjojo Another, use `differenceInCalendarDays` instead to resolve your problem.
