### ISSUE TITLE
tree addChildren pass a NzTreeNode，display '---',not the real title

### ISSUE THREAD

**Issue by MagicWang** [NG-ZORRO/ng-zorro-antd#1636]
## Version
1.0.0
## Environment
win10
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-puxqhk](https://stackblitz.com/edit/ng-zorro-antd-start-puxqhk)
## Steps to reproduce
click the expand icon
## What is expected?
real title，eg:'南山区'
## What is actually happening?
---

**Comment by simplejason** [comment]
不要强行更改origin属性，这个属性是用户原始数据结构，NzTreeNode会重新初始化这个值以设置相关属性。删除 `cnode.origin = obj;`。

**Comment by MagicWang** [comment]
那怎么把原始数据挂到树节点下呢，我在0.7.1下这么用是正常的

**Comment by simplejason** [comment]
@MagicWang 你是指将原始数据的信息展示出来？可以参考官网 tree 的文件树demo

**Comment by MagicWang** [comment]
不只是展示出来，原始数据没有key和title属性，我需要把原始数据挂到树节点下，对树节点操作时容易取到原始数据。文件树demo那样做，我需要把后台传来的属性全部重新赋值给NzTreeNodeOptions，是不是太麻烦了

**Comment by MagicWang** [comment]
![jpub9 bg_ok0v0_1h piedu](https://user-images.githubusercontent.com/3860039/41266239-a662a198-6e28-11e8-9b97-2290e36a3d62.png)

**Comment by simplejason** [comment]
```
var cnode = new NzTreeNode({
     key: obj.id,
     title: obj.name,
      ...obj
});
```

**Comment by MagicWang** [comment]
ok
