### ISSUE TITLE
The count of nz-table columns can not be large than 11

### ISSUE THREAD

**Issue by Jayanzhou** [NG-ZORRO/ng-zorro-antd#1637]
## Version

0.7.1

## Environment

nz-zorro:0.7.1,  chrome:67.0.3396.79

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-hooexy?file=app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-hooexy?file=app/app.component.ts)

## Steps to reproduce

```
<nz-table #settingMatrixTable  [nzData]="selectedInputKeysList" [nzShowPagination]="false" [nzBordered]="true">
                <thead>
                <tr>
                    <th *ngFor="let input of settingMatrixTable.data">{{input.displayName}}</th>
                    <th>Output</th>
                </tr>
                </thead>
                <tbody>
              
                </tbody>
            </nz-table>
```
ps: selectedInputKeysList is a array, pls see the detail from https://stackblitz.com/edit/ng-zorro-antd-setup-hooexy?file=app/app.component.ts

## What is expected?

count of columns can large than 11

## What is actually happening?

count of columns can not be large than 11

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-yqplvu?file=app/app.component.html
please read the doc carefully.

**Comment by Jayanzhou** [comment]
@vthinkxie tks
