### ISSUE TITLE
[nz-range-picker] 预设时间范围快捷选择后不可选择的日期会被改变

### ISSUE THREAD

**Issue by ppjjzz** [NG-ZORRO/ng-zorro-antd#1640]
## Version
1.0.0
## Environment
ng 6， zorro 1.0
## Reproduction link
[https://stackblitz.com/edit/angular-i1tnt3](https://stackblitz.com/edit/angular-i1tnt3)
## Steps to reproduce
1. 选择这个月
2. 重新打开日期控件，不可选择日期会往后退一天
## What is expected?
重新打开日期控件，不可选择日期正常
## What is actually happening?
重新打开日期控件，不可选择日期会往后退一天
## Other?
![image](https://user-images.githubusercontent.com/26438223/41269260-d2272516-6e36-11e8-98de-36c33e6d92dc.png)
![image](https://user-images.githubusercontent.com/26438223/41269270-e2c9377e-6e36-11e8-9b1f-ea5596f8ee49.png)

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-7ozt2g?file=src%2Fapp%2Fapp.component.ts
@wilsoncook

**Comment by wilsoncook** [comment]
@ppjjzz The judgement of `differenceInDays` is accurate to the second, use `differenceInCalendarDays` instead!
