### ISSUE TITLE
Could you consider adding an example of theme.less to the Customize Theme in DOC ?  

### ISSUE THREAD

**Issue by NiLinli** [NG-ZORRO/ng-zorro-antd#1641]
## What problem does this feature solve?
decrease Compiled  style.xxxxx.css size
## What does the proposed API look like?
```
// -------- import official less file -----------
@import "../node_modules/ng-zorro-antd/src/ng-zorro-antd.less";

// -------- override less var -----------
@primary-color          : #f5222d;
```

OR
```
@import "../node_modules/ng-zorro-antd/src/style/index.less";  

//  -------- other component style that you require -----------  
@import "../node_modules/ng-zorro-antd/src/input-number/style/index.less";  
@import "../node_modules/ng-zorro-antd/src/xxxxxxxxxx/style/index.less";

// -------- override less var -----------
@primary-color          : #f5222d;
```

**Comment by vthinkxie** [comment]
https://ng.ant.design/docs/customize-theme/en
please read the latest doc.
<img width="956" alt="2018-06-12 12 48 09" src="https://user-images.githubusercontent.com/1506722/41270639-e58d9d58-6e3e-11e8-8c62-a65fb2b92b3e.png">

**Comment by NiLinli** [comment]
Maybe I haven't stated clearly

I mean you could provide other choice(example) to import patial less file that corresponds to component  you actually use.

such as：
```
@import "../node_modules/ng-zorro-antd/src/style/index.less";  
@import "../node_modules/ng-zorro-antd/src/input-number/style/index.less";  
@import "../node_modules/ng-zorro-antd/src/xxxxxxxxxx/style/index.less";
```
can decrease compiled css file size

**Comment by wendzhue** [comment]
> Maybe I haven't stated clearly
> 
> I mean you could provide other choice(example) to import patial less file that corresponds to component you actually use.
> 
> such as：
> 
> ```
> @import "../node_modules/ng-zorro-antd/src/style/index.less";  
> @import "../node_modules/ng-zorro-antd/src/input-number/style/index.less";  
> @import "../node_modules/ng-zorro-antd/src/xxxxxxxxxx/style/index.less";
> ```
> 
> can decrease compiled css file size

Try secondary entry point. https://ng.ant.design/docs/getting-started/en#import-a-component-individually
