### ISSUE TITLE
Select dropdown bug in popover

### ISSUE THREAD

**Issue by svdamani** [NG-ZORRO/ng-zorro-antd#1643]
## Version
1.0.0
## Environment
Stable release
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-popover-select-bug](https://stackblitz.com/edit/ng-zorro-antd-popover-select-bug)
## Steps to reproduce
 - Open https://ng-zorro-antd-popover-select-bug.stackblitz.io
 - Click on button to reveal popover
 - Click on select to reveal options
 - Notice options rendered below popover
## What is expected?
Select options should be rendered above popover
## What is actually happening?
Select options is getting rendered below popover
## Other?
This issue first appeared since 0.7.0 release and has percolated in all further releases. However, this was working fine till 0.7.0-beta.5

**Comment by super3s1988** [comment]
I meet same problem as you,I just use css to modify the z-index temporarily,but it works not very good

**Comment by vthinkxie** [comment]
will be fixed in next version, thanks for your feedback.

**Comment by super3s1988** [comment]
@vthinkxie 请问有没有什么办法可以临时解决以下呢

**Comment by vthinkxie** [comment]
@super3s1988 手动修改z index

**Comment by svdamani** [comment]
@vthinkxie how do you manually modify z-index on `.cdk-overlay-connected-position-bounding-box` for a select options menu?

**Comment by vthinkxie** [comment]
@svdamani 
```typescript
@ViewChild(NzSelectComponent) nzSelectComponent:NzSelectComponent;
```
you can get cdkConnectedOverlay like 
```typescript
this.cdkConnectedOverlay.nzSelectComponent
```

**Comment by lopn** [comment]
@ViewChild(NzSelectComponent) childComponent: NzSelectComponen 
在开发环境正常，不过当在线上 --prod 后， 则 this.nzSelectComponent 变成了undefined  (在ngAfterViewInit)

所以我不得不自定义了模板变量 （开发环境和正式环境就都正常了）
 @ViewChild('nzSelectOper') childComponent: NzSelectComponent;


不知道 是ng-zorro-antd 的问题，还是 --prod编译的问题

**Comment by tommas3210** [comment]
> @ViewChild(NzSelectComponent) childComponent: NzSelectComponen
> 在开发环境正常，不过当在线上 --prod 后， 则 this.nzSelectComponent 变成了undefined (在ngAfterViewInit)
> 
> 所以我不得不自定义了模板变量 （开发环境和正式环境就都正常了）
> @ViewChild('nzSelectOper') childComponent: NzSelectComponent;
> 
> 不知道 是ng-zorro-antd 的问题，还是 --prod编译的问题

我也遇上了。@ViewChild / @ViewChildren / @ContentChild / @ContentChildren 只要是ng-zorro-antd的控件都是undefined，而其它第三方控件卻沒問題。

**Comment by vthinkxie** [comment]
@lopn @tommas3210 plz track https://github.com/NG-ZORRO/ng-zorro-antd/issues/2696
