### ISSUE TITLE
angular5.2版本使用的是0.7.1，我使用npm uninstall 卸载掉后，重新安装1.0版本，但是报错提示出现图上的提示

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1645]
![qq 20180612142634](https://user-images.githubusercontent.com/16211027/41273709-228fc3b2-6e4d-11e8-8757-0562f01aebde.png)
![qq 20180612142717](https://user-images.githubusercontent.com/16211027/41273710-22c008b0-6e4d-11e8-8cac-c1acf5e3c591.png)
angular也必须升级到6.0么
## What problem does this feature solve?
angular5.2版本使用的是0.7.1，我使用npm uninstall 卸载掉后，重新安装1.0版本，但是报错提示出现图上的提示
## What does the proposed API look like?
angular5.2版本使用的是0.7.1，我使用npm uninstall 卸载掉后，重新安装1.0版本，但是报错提示出现图上的提示

**Comment by HsuanXyz** [comment]
`ng-zorro-antd@1.0.0` 需要 Angualr6 以及 RxJS6

```base
ng update @angular/cli
ng update @angular/core
npm install ng-zorro-antd@1.0.0
npm install -g rxjs-tslint
rxjs-5-to-6-migrate -p src/tsconfig.app.json
```
参考

- https://update.angular.io/
- https://zhuanlan.zhihu.com/p/37942535
