### ISSUE TITLE
[nz-cascader]: After clear up option, the custom-render-template is unusable

### ISSUE THREAD

**Issue by liuchunhuicanfly** [NG-ZORRO/ng-zorro-antd#1646]
## Version
1.0.0
## Environment
ng-zorro-antd 1.0.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ik7myb](https://stackblitz.com/edit/ng-zorro-antd-start-ik7myb)
## Steps to reproduce
开启自定义已选项功能，使用清除按钮清除选中值，再次选择某个选项，并没有展示自定义的内容
## What is expected?
 每次选中能够正确展示自定义的内容
## What is actually happening?
在清除操作后再次选择，没有展示自定义的内容

**Comment by simplejason** [comment]
will be fixed next version
