### ISSUE TITLE
ERROR TypeError: o.ngAfterContentInit is not a function

### ISSUE THREAD

**Issue by shhdgit** [NG-ZORRO/ng-zorro-antd#1647]
## Version
1.0.0
## Environment
MacOS10.13.3、Chrome67、Angular 6.x
## Reproduction link
[https://stackblitz.com/edit/angular-sk2qrg?file=src/main.ts](https://stackblitz.com/edit/angular-sk2qrg?file=src/main.ts)
## Steps to reproduce
重现链接无效。
重现步骤：在 env=prod 构建时，使用 ng-zorro-antd@1.0.0，在任何用menu的页面都会报 ERROR TypeError: o.ngAfterContentInit is not a function
使用 ng-zorro-antd@1.0.0-rc.0 则不会有该错误
## What is expected?
No Error
## What is actually happening?
ERROR TypeError: o.ngAfterContentInit is not a function

**Comment by simplejason** [comment]
可以贴一下你打包的脚本，我们自己的项目 `ng build --prod` 是正常的

**Comment by shhdgit** [comment]
找到了，貌似是 @angular-devkit/build-optimizer 的bug，不知道为什么把生命周期优化没了，暂时把 buildOptimizer 选项关掉来解决了
感谢

**Comment by shhdgit** [comment]
我去 angular-cli 那边咨询一下.....😂
