### ISSUE TITLE
iOS does not show keyboard on Select component click

### ISSUE THREAD

**Issue by danielszenasi** [NG-ZORRO/ng-zorro-antd#1653]
## Version
1.0.0
## Environment
IOS 11.3, Safari
## Reproduction link
[https://ng-zorro-antd-start-vcwbct.stackblitz.io](https://ng-zorro-antd-start-vcwbct.stackblitz.io)
## Steps to reproduce
Click the input, the keyboard doesn`t show up, so i cannot type to the input
## What is expected?
The keyboard show up
## What is actually happening?
The keyboard doesn`t show up

**Comment by vthinkxie** [comment]
ref #1274
