### ISSUE TITLE
nzSortChange bug in nz-table

### ISSUE THREAD

**Issue by 274860460** [NG-ZORRO/ng-zorro-antd#1658]
## Version
1.0.0
## Environment
Google Chrome 67.0.3396.79
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-xu97lp](https://stackblitz.com/edit/ng-zorro-antd-start-xu97lp)
## Steps to reproduce
Successive click column Name descend:
First: { "key": "name", "value": descend}
Second: { "key": "name", "value": null }
Third: { "key": "name", "value": descend}
## What is expected?
Ignore the null value. 
## What is actually happening?
 { "key": "name", "value": null }

**Comment by vthinkxie** [comment]
The null value should not be ignored, or you will never know when user reset the sort.
