### ISSUE TITLE
Multi select field's size should not grow.

### ISSUE THREAD

**Issue by manojp1988** [NG-ZORRO/ng-zorro-antd#1661]
## What problem does this feature solve?
I have to use multiselect field in my form.  If user selects more options, and if the field couldn't hold them, its height is growing. This will disturb my form layout. Instead, if user selects more number of items, I want to show for example "4 options selected".  If user wants to know what they are, he can anyway click the toggle icon, and see.
## What does the proposed API look like?
I would not show all the items in the field, instead based on the size of the field, I would display just how many items user selected.

**Comment by vthinkxie** [comment]
Got it, we will try to support it in latter version.
