### ISSUE TITLE
Modal & location back bug

### ISSUE THREAD

**Issue by shhdgit** [NG-ZORRO/ng-zorro-antd#1663]
## Version
1.0.0
## Environment
ng-zorro-antd
## Reproduction link
[https://stackblitz.com/edit/angular-ax7ofd?file=src/main.ts](https://stackblitz.com/edit/angular-ax7ofd?file=src/main.ts)
## Steps to reproduce
无需打开重现链接

1. 打开官网  https://ng.ant.design/docs/introduce/zh
2. 选择 Modal对话框 ，点开一个示例modal
3. 不要关闭 modal，点击浏览器左上角的返回键（或者mac滑动返回）
4. 此时任何页面都无法滚动了

## What is expected?
经过复现操作后可以滚动
## What is actually happening?
经过复现操作后无法滚动
## Other?
应该是某个蒙层没有销

**Comment by vthinkxie** [comment]
感谢反馈
