### ISSUE TITLE
Close button overlaps with alert's text

### ISSUE THREAD

**Issue by dmytroyarmak** [NG-ZORRO/ng-zorro-antd#1668]
## Version
1.0.0
## Environment
any
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-zte9ev](https://stackblitz.com/edit/ng-zorro-antd-start-zte9ev)
## Steps to reproduce
Open [demo app](https://stackblitz.com/edit/ng-zorro-antd-start-zte9ev)
## What is expected?
Close button doesn't overlap with alert's text
## What is actually happening?
Close button does overlap with alert's text

**Comment by vthinkxie** [comment]
@afc163 have a look at this.

**Comment by cohancarpentier** [comment]
PR: https://github.com/NG-ZORRO/ng-zorro-antd/pull/2491

**Comment by wendzhue** [comment]
@cohancarpentier styles of `ng-zorro-antd` are copied from [`antd`](https://github.com/ant-design/ant-design). Maybe you could make a pr there first?

**Comment by cohancarpentier** [comment]
@wendzhue OK! I made the PR on the Ant Design repository:
https://github.com/ant-design/ant-design/pull/13220

**Comment by vthinkxie** [comment]
this bug has been fixed by #2880 
plz try again when next version released
