### ISSUE TITLE
Layout中的Sidebar的position=fixed，不知什么时候能增加呢？React版本有这个属性

### ISSUE THREAD

**Issue by Salmon-Lee** [NG-ZORRO/ng-zorro-antd#167]
这个属性，觉得还是很有必要的，如果左边栏导航纵向太长的话，拖动菜单栏，不影响右边页内容的查阅，能提升很大的用户体验，望增加，谢谢。

**Comment by vthinkxie** [comment]
it is just a style, please apply it just as react version.
`{ overflow: 'auto', height: '100vh', position: 'fixed', left: 0 }`

**Comment by Salmon-Lee** [comment]
谢谢！

**Comment by CK110** [comment]
@vthinkxie  `{ overflow: 'auto' } ` 和 `[nzMode]="'vertical'"` 有冲突，设置了`auto`, 绝对定位的`ul`显示不出来了
