### ISSUE TITLE
如果表格中表头有排序则固定表头时会导致有滚动条

### ISSUE THREAD

**Issue by lightman0215** [NG-ZORRO/ng-zorro-antd#1671]
## Version
1.0.0

## Environment
Chrome：67，OS：Mac OS 10.13.5

## Steps to reproduce
1、设置表格表头排序；  
2、设置nzScroll中y的高度；  
3、表头会出现Y轴滚动条；

## What is expected?
不出现y轴滚动条

## What is actually happening?
出现了y轴滚动条

## Other?
0.7版本中也存在该问题

**Comment by vthinkxie** [comment]
repro link:https://stackblitz.com/edit/angular-ztnpt8?file=src%2Fapp%2Fapp.component.ts
