### ISSUE TITLE
nz-range-picker 时间上下限 存在问题，当使用moment时

### ISSUE THREAD

**Issue by billpeace** [NG-ZORRO/ng-zorro-antd#1675]
## Version
1.0.0
## Environment
angular 6.0
## Reproduction link
[https://stackblitz.com/edit/angular-nm7jvs?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-nm7jvs?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
     this.dateRange[0] = '2016-01-05T09:05:05.035Z';
     this.dateRange[1] = '2016-01-20T09:05:05.035Z';
     this.dateRange2[0] = moment().startOf('day');
     this.dateRange2[1] = moment().add(30, 'days').endOf('day');

<nz-range-picker [(ngModel)]="dateRange" name="dateRange" ></nz-range-picker>
<nz-range-picker [(ngModel)]="dateRange2" name="dateRange" ></nz-range-picker>
## What is expected?
nz-range-picker dateRange2 时间上下限  不同
## What is actually happening?
nz-range-picker dateRange2 时间上下限  一致，都等于  this.dateRange2[0]

**Comment by HsuanXyz** [comment]
@billpeace 你好，这里指的 "时间上下限" 是什么意思？

**Comment by billpeace** [comment]
时间上下限  是指时间范围
nz-range-picker   制定 

this.dateRange2[0] = moment().startOf('day');
this.dateRange2[1] = moment().add(30, 'days').endOf('day');

<nz-range-picker [(ngModel)]="dateRange2" name="dateRange" >

nz-range-picker 时间范围 未能正确反应

**Comment by HsuanXyz** [comment]
`nz-range-picke` 只支持 `string` 和 `Date` 类型。
你可以这样：

```ts
this.dateRange2[0] = moment().startOf('day').toDate();
this.dateRange2[1] = moment().add(30, 'days').endOf('day').toDate();
```
