### ISSUE TITLE
Display items inside cdk-overlay (popovers, tooltips, etc.)

### ISSUE THREAD

**Issue by roeir** [NG-ZORRO/ng-zorro-antd#1677]
## Version
1.0.0
## Environment
OS: Debian, Chrome: 65.0.3325.181
## Reproduction link
[https://ng-zorro-antd-start-kejuqy.stackblitz.io/](https://ng-zorro-antd-start-kejuqy.stackblitz.io/)
## Steps to reproduce
- Hover over the first button to show the popover
- Hover over another buttons to show the rest popovers
## What is expected?
- Slide the cursor away from button causes the popover to be hidden with related `cdk-overlay-connected-position-bounding-box`
## What is actually happening?
- Slide the cursor away from button causes the popover to be hidden but related `cdk-overlay-connected-position-bounding-box` remains inside `cdk-overlay-container`
## Other?
Is it correct that `cdk-overlay-connected-position-bounding-box` remains inside html, even the popover was hidden? For example, if I have a `*ngFor` that shows me 200 items with popovers,  then i trigger most of them, I mean that containers can be created a lot during my work

**Comment by vthinkxie** [comment]
The tooltip component is based on `@angular/cdk` overlay module.
You can see the same strategy here https://material.angular.io/components/tooltip/overview.

**Comment by roeir** [comment]
@vthinkxie is there way to override this behaviour? like, `destroy` or, maybe `dispose` from `Overlay` module. Sorry, Im not strong in `@angular/cdk`

**Comment by vthinkxie** [comment]
cdk-overlay-connected-position-bounding-box will not affect the running speed, I think there is no need to destroy it. you can check cdk doc for more detail.
