### ISSUE TITLE
[建议] date-picker ngModel 类型设计缺陷

### ISSUE THREAD

**Issue by hsuanxyz** [NG-ZORRO/ng-zorro-antd#1679]
## What problem does this feature solve?
- 当使用 `string` 类型时组件正常工作，但是返回是 `Date`；
- 使用其它类型时组件不会报错，但是无法正常工作。
## What does the proposed API look like?
- 如果支持多类型的话，请保持输入输出类型一致；
- 如果不支持多类型的话请报错。

**Comment by vthinkxie** [comment]
当为string的时候需要报warning，待完成

**Comment by zlhgo** [comment]
@vthinkxie 建议能接收字符串输入，返回字符串输出。就是看到什么得到就是什么。

**Comment by hsuanxyz** [comment]
@zlhgo 其他参数多类型可以，NgModel 多类型会很奇怪
