### ISSUE TITLE
树形选择器在modal里面下拉选择显示错误

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1681]
![qq 20180619151151](https://user-images.githubusercontent.com/16211027/41582070-273884cc-73d3-11e8-875b-f3cd4e8ff161.png)
## Version
1.0.0
## Environment
win10，chrome66，1.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-h6ngmn?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-h6ngmn?file=src/app/app.component.ts)
## Steps to reproduce
树形选择器在modal里面下拉选择显示错误
## What is expected?
树形选择器在modal里面下拉选择显示错误
## What is actually happening?
树形选择器在modal里面下拉选择显示错误

**Comment by kezhanshi** [comment]
我也刚碰到这个问题，猜测跟modal的动画有关，当浏览器的大小改变后，重新下拉就正常了
