### ISSUE TITLE
Directive ɵht, Property 'handleKeydown' is private and only accessible within class 'NzAutocompleteTriggerDirective'

### ISSUE THREAD

**Issue by canaanjin** [NG-ZORRO/ng-zorro-antd#1683]
## Version
1.0.0
## Environment

```
Angular CLI: 6.0.7
Node: 8.11.1
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.7
@angular-devkit/build-angular      0.6.7
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.7
@angular-devkit/core               0.6.7
@angular-devkit/schematics         0.6.7
@angular/cdk                       6.2.1
@angular/cli                       6.0.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.7
@schematics/angular                0.6.7
@schematics/update                 0.6.7
ng-packagr                         3.0.3
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
```

## Reproduction link
无法重现
该错误出现在build的时候
![image](https://user-images.githubusercontent.com/12317236/41584258-6fa9afdc-73d9-11e8-9008-94d89556b831.png)
![image](https://user-images.githubusercontent.com/12317236/41584267-73c25998-73d9-11e8-8c6e-3e6c76042e45.png)

## Steps to reproduce
正常使用 [Autocomplete](https://ng.ant.design/components/auto-complete/zh)组件的时候
## What is expected?
经过查看相关问题。有提示说将`handleKeydown` `handleInput` `handleBlur` `handleFocus` 改为`public`
[问题解决相关地址](https://blog.angularindepth.com/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5)
![image](https://user-images.githubusercontent.com/12317236/41584404-c283ab86-73d9-11e8-8f59-352bc69e5186.png)

**Comment by canaanjin** [comment]
由于是额外创建的project
单独发布project的话会有相关错误
我在默认项目中 引用 并且打包一切顺利

**Comment by HsuanXyz** [comment]
感谢反馈，我们会在下个版本修复。
现在可以尝试关闭 `tsconfig.json` 中的 `fullTemplateTypeCheck` 试试。

```json
{
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": false,
  }
}
```
