### ISSUE TITLE
No value accessor for form control with unspecified name attribute

### ISSUE THREAD

**Issue by lyw90** [NG-ZORRO/ng-zorro-antd#1684]
## Version
0.6.15
## Environment
window   node  v8.11.2   ng-zorro-antd  0.6.15
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-4zzcef](https://stackblitz.com/edit/ng-zorro-antd-start-4zzcef)
## Steps to reproduce
this is template howto use

<nz-input [(ngModel)]="tilte" ></nz-input>

No value accessor for form control with unspecified name attribute

**Comment by lightman0215** [comment]
在子模块中import NgZorroAntdModule

**Comment by lyw90** [comment]
Correct way  

shoud be  like this
 <input nz-input placeholder="Basic usage" [(ngModel)]="LzText">
