### ISSUE TITLE
give a way to show full title of transfer item( display a apostrophe for now )

### ISSUE THREAD

**Issue by locotor** [NG-ZORRO/ng-zorro-antd#1689]
## What problem does this feature solve?
to have a way to display the full title of transfer item, cause we have some items have a very long title.
## What does the proposed API look like?
a api property to config if show a pop card when hover on the item; or just wrap to the next line like table component; or a scroll bar on horizental direction when some title vary long.

**Comment by cipchk** [comment]
You can custom render item via `nzRender` property.
https://ng.ant.design/components/transfer/en#components-transfer-demo-advanced

**Comment by locotor** [comment]
@cipchk yes, thanks for response. I already used this property to display a pop card when user hover on it. just submit a component  suggest.
