### ISSUE TITLE
Angular4 AOT摇树优化报错

### ISSUE THREAD

**Issue by hythzx** [NG-ZORRO/ng-zorro-antd#169]
根据Angular官方文档的AOT配置（ https://angular.cn/guide/aot-compiler ），到 Rollup插件 这一块，运行 node_modules/.bin/rollup -c rollup-config.js  报下列错误：

[!] Error: Cannot call a namespace ('moment') 
node_modules/ng-zorro-antd/src/release/calendar/nz-calendar.component.js (14:26)
12:         this._yearUnit = '年';
13:         this._monthUnit = '月';
14:         this._showMonth = moment(new Date()).month();
                              ^
15:         this._showYear = moment(new Date()).year();
16:         this._value = new Date();

**Comment by trotyl** [comment]
Duplicate of https://github.com/NG-ZORRO/ng-zorro-antd/issues/85

**Comment by whoissj** [comment]
@hythzx 您好，您这个问题解决了吗？
