### ISSUE TITLE
layout and its modules from different modules components 

### ISSUE THREAD

**Issue by calebeaires** [NG-ZORRO/ng-zorro-antd#1692]
## What problem does this feature solve?
I have tried to create an layout putting sider and header in diferent componets, but it were not possible. Layout loose its correct beheavor.
## What does the proposed API look like?
Make possible put sider, header into diferente components when using nz-layout

```
// BASE COMPONENT
<nz-layout class="wrapper">
  <app-sider></app-sider>
   <nz-layout class="wrapper">
        <router-outlet></router-outlet>
  </nz-layout>
</nz-layout>
```

root component
```
<nz-layout class="wrapper">
  <app-sider></app-sider>
   <nz-layout class="wrapper">
        <router-outlet></router-outlet>
  </nz-layout>
</nz-layout>
```

app sider equal to all pages
```
 <nz-sider>
    <ul nz-menu [nzTheme]="'dark'" [nzMode]="'inline'" [nzInlineCollapsed]="isCollapsed">
.... ul contents
    </ul>
  </nz-sider>
```

child component -> header diferent on all pages

```
<nz-header style="position:fixed; z-index: 1; height: 40px; width:100%; background: #fff; padding:0;">
... differente header contents
</nz-header>
 .... content

```

But when doing so, header does work as expected

**Comment by roymilder** [comment]
Same problem here, solved it temporarily this way: 

```
  <nz-sider [nzWidth]="200" style="background:#fff">
    <app-side-nav></app-side-nav>
  </nz-sider>
```

So I put all the side nav shared code in the  component, without the nz-sider tag. This works as expected.

**Comment by vthinkxie** [comment]
Hi @calebeaires @roymilder 
here is the reason
https://github.com/NG-ZORRO/ng-zorro-antd/blob/dd0cec2c92bddcad4815648d9f906b53e4eecfed/components/layout/style/index.less#L21

`nz-content` must be follow `nz-layout`
