### ISSUE TITLE
Use transfer function without checkbox

### ISSUE THREAD

**Issue by cyhjojo** [NG-ZORRO/ng-zorro-antd#1694]
## What problem does this feature solve?
If use transfer function without checkbox,just click left item transfer to right place,it is maybe more pure.You can just click once every time .
## What does the proposed API look like?
Use transfer function without checkbox,just click left item transfer to right place,it is maybe more pure.You can just click once every time .

**Comment by vthinkxie** [comment]
有些特性为什么不会被支持#
ng-zorro-antd 是 Angular 版本 Ant Design 的实现，这意味着只有 Ant Design 支持的交互、功能 才会被 ng-zorro-antd 实现。
