### ISSUE TITLE
顯目打包后 Table 的 選擇按鈕 應該是 “確認”和“重置” ，但是由於沒有獲取到值變爲 “Table.filterConfirm   Table.filterReset” ，日曆應該選擇日期 重置過濾條件后 按鈕 應該變爲未選擇之前的暗色

### ISSUE THREAD

**Issue by lancelove** [NG-ZORRO/ng-zorro-antd#1700]
## What problem does this feature solve?
顯目打包后 Table 的 選擇按鈕 應該是 確認和重置 ，不是 Table.filterConfirm   Table.filterReset ，日曆應該選擇日期
重置過濾條件后 按鈕 應該變爲未選擇之前的暗色
## What does the proposed API look like?
None

**Comment by vthinkxie** [comment]
fixed in #1674
