### ISSUE TITLE
client-side pagination

### ISSUE THREAD

**Issue by mapsgeek** [NG-ZORRO/ng-zorro-antd#1702]
## What problem does this feature solve?
give the pagination component an array of items to distribute it across multiple pages, reducing the number of elements to be shown for better performance for apps with large data
## What does the proposed API look like?
not really sure but maybe something similar, or just the same idea
```
<p *ngFor="let item of items" #paginate>{{item.x}}</p>
<nz-pagination #paginate [nzSize]="'small'"></nz-pagination>
```

**Comment by vthinkxie** [comment]
can not support in current design.
