### ISSUE TITLE
nz-select  ngModel 绑定的数据渲染不出来

### ISSUE THREAD

**Issue by Paynecheng** [NG-ZORRO/ng-zorro-antd#1705]
## Version
1.0.0
## Environment
ng 6, 
## Reproduction link
[https://ng-zorro-antd-start-yhfqcl.stackblitz.io/](https://ng-zorro-antd-start-yhfqcl.stackblitz.io/)
## Steps to reproduce
```
      <nz-select style="width: 200px;" [(ngModel)]="yyy" [nzSize]="size">
        <nz-option *ngFor="let option of listOfOption" [nzLabel]="option.name" [nzValue]="option.category_id"></nz-option>
      </nz-select>
```
## What is expected?
默认选中 yyy对应的数据
## What is actually happening?
yyy对应的数据渲染不出来

**Comment by vthinkxie** [comment]
ngModel是和nzValue对应的，仔细看下你的写程序

**Comment by jasonvalue** [comment]
@Paynecheng  hi，这个问题你解决了吗？我遇到同样的问题，我确定我的ngModel是和nzValue对应的，但是ngModel仍然不起作用。并且当我使用ngModel时报了一个错。
ProductDetailComponent.html:27 ERROR Error: If ngModel is used within a form tag, either the name attribute must be set or the form
      control must be defined as 'standalone' in ngModelOptions.
