### ISSUE TITLE
[nzAutoFocus] can not work in <nz-input-number>

### ISSUE THREAD

**Issue by wenqi73** [NG-ZORRO/ng-zorro-antd#1706]
## Version
1.0.0
## Environment
mac OS 10.11 Chrome 67
## Reproduction link
[https://stackblitz.com/edit/nz-input-number?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/nz-input-number?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
Set [nzAutoFocus]="true"
## What is expected?
NzInputNumberComponent is focused
## What is actually happening?
NzInputNumberComponent is not focused

**Comment by HsuanXyz** [comment]
@wenqi73 Thanks feedback, you can use the following code:

```ts
import { Component, ViewChild, OnInit } from '@angular/core';
import { NzInputNumberComponent } from 'ng-zorro-antd';

@Component({
  selector: 'nz-demo-input-number-basic',
  template: `
    <nz-input-number [(ngModel)]="demoValue" [nzMin]="1" [nzMax]="10" [nzStep]="1"></nz-input-number>
  `
})
export class NzDemoInputNumberBasicComponent implements OnInit {
  demoValue = 3;

  @ViewChild(NzInputNumberComponent) numberInput;

  ngOnInit() {
    this.numberInput.focus();
  }
}
```

**Comment by wendzhue** [comment]
This method is actually invoked before `ngAfterViewInit` hook so the input element do not have `autofocus` attribute. Remove `if (this.isInit)` would make the input autofocus in Chrome.

https://github.com/NG-ZORRO/ng-zorro-antd/blob/4cbcd6f7a9410e97eed03a5b03aa6b08addcb633/components/input-number/nz-input-number.component.ts#L106-L114
