### ISSUE TITLE
更改nz-carousel自动切换（autoPlay）的间隔时间

### ISSUE THREAD

**Issue by edtim8** [NG-ZORRO/ng-zorro-antd#1711]
## What problem does this feature solve?
更改nz-carousel自动切换（autoPlay）的间隔时间
## What does the proposed API look like?
把时间间隔设置作为属性

**Comment by HsuanXyz** [comment]
@edtim8 你愿意提交一个 PR 吗？你可以为它添加一个 `nzAutoplaySpeed` 属性。
