### ISSUE TITLE
[bug] modal padding-right

### ISSUE THREAD

**Issue by lopn** [NG-ZORRO/ng-zorro-antd#1720]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/6ae44678133a91467e568edc736e685aa8a565d8/components/modal/nz-modal.component.ts#L417

**Comment by lopn** [comment]
padding-right 不能每次都加， 我觉得最合理的是应该先判断页面是否有滚动条，如果有获取bar宽度，加padding-right, 否则不加

**Comment by lopn** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/6ae44678133a91467e568edc736e685aa8a565d8/components/core/services/nz-measure-scrollbar.service.ts#L18

修改成
```
  get scrollBarWidth(): number {
    if(document.body.scrollHeight <= (window.innerHeight || document.documentElement.clientHeight)){
         return 0;
      }

    if (isNotNil(this._scrollbarWidth)) {
      return this._scrollbarWidth;
    }
    this.initScrollBarWidth();
    return this._scrollbarWidth;
  }
```

**Comment by AnhuiWdan** [comment]
同样的情况需要修复

**Comment by DouglasOGarrido** [comment]
Any news from that? I agree with the opinion of @lopn, before add a `padding-right`, verify if exists a scrollbar.
