### ISSUE TITLE
NzTree disableCheckbox but parent node is checked

### ISSUE THREAD

**Issue by MagicWang** [NG-ZORRO/ng-zorro-antd#1721]
## Version
1.1.0
## Environment
Win10 Chrome68
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-te9rad](https://stackblitz.com/edit/ng-zorro-antd-start-te9rad)
## Steps to reproduce
null
## What is expected?
parent node is unchecked
## What is actually happening?
parent node is checked

**Comment by simplejason** [comment]
Will fix soon, thanks for reporting!
