### ISSUE TITLE
Allow nz-submenu to expand when ant-menu-item-selected is true

### ISSUE THREAD

**Issue by KevinStirling** [NG-ZORRO/ng-zorro-antd#1729]
## What problem does this feature solve?
Using the routerLinkActive parameter on nz-menu-item is really useful when the router has navigated to a new route without clicking on the menu item that has a router link mapping. However, if the mapped menu item exists as a sub-menu item, the selected element will not be visible when the route is changed since the sub-menu is collapsed. 

If nz-submenu was allowed to expand when ant-menu-item-selected is true, it would be easier for the user to see where they are contextually in the application if the route was forcibly changed, or if they entered the url to a specific route manually. It would be nice to have this kind of visual feedback.
## What does the proposed API look like?
Maybe a property for nz-submenu called expandOnItemSelected that would trigger the expanding of the nz-submenu when the nz-menu-item inside of the the nz-submenu is selected.

**Comment by vthinkxie** [comment]
You can use `nzOpen` to control the expand state of submenu yourself.
It will bring conflict with `nzOpen` if auto expand the submenu when router active.

**Comment by KevinStirling** [comment]
Hmm I see. The tricky part about this that I'm having is getting the value of RouterLinkActive's .isActive  to the <nz-submenu> tag to define whether it should be open or not. Probably will have to do something clever with a template variable.

**Comment by KevinStirling** [comment]
@vthinkxie After playing with this a bit, im not sure if this is possible with the way the submenu handles `routerLinkActive`. It seems that `nz-menu-item` only sets `routerLinkActive.isActive` to `true` when `nz-submenu` is already open.

Not sure if it's possible to replicate this on stack blitz with a router but if not ill try to make a repo for this. Here is a rough example of what I'm trying to so with the template variables though. I'm setting the submenu title to display the value of .isActive so you can see how the value changes when the route remains the same while the menu opens and closes


```
      <ul nz-menu [nzMode]="'inline'" [nzInlineCollapsed]="isCollapsed">
        <li nz-submenu [(nzOpen)]="rla.isActive">
          <span title>
            <span>{{ rla.isActive}}</span>
          </span>
          <ul>
            <li nz-menu-item routerLinkActive="ant-menu-item-selected" #rla="routerLinkActive" routerLink="/route1">
              Route 1
            </li>
            <li nz-menu-item routerLinkActive="ant-menu-item-selected" #rla="routerLinkActive" routerLink="/route2">
              Route 2
            </li>
          </ul>
        </li>
      </ul>

**Comment by KevinStirling** [comment]
Since it seems i may have discovered a bug in that stackblitz example, I can open a bug issue rather than an enhancement if this thread seems to die. I feel like this is a fairly important feature.

**Comment by vthinkxie** [comment]
@KevinStirling you can subscribe the router events to set nzOpen rather than use routerLinkActive isActive now.

**Comment by KevinStirling** [comment]
thank you, ill try this

**Comment by jiashengLeong** [comment]
@KevinStirling Would you mind to share your code, since we are facing this issue too.

**Comment by KevinStirling** [comment]
@jiashengLeong  sure thing. In your ngOnInit(), create the subscription to the router events:
```
      this.router.events
      .filter(event => event instanceof NavigationStart)
      .subscribe((event: NavigationStart) => {
        if (RegExp('(\/route1?.+)').test(event.url)){
          this.openMap.sub1 = true;
          this.openHandler('sub1');
        } else if (RegExp('(\/route2?.+)').test(event.url)){
          this.openMap.sub2 = true;
          this.openHandler('sub2');
        } else if (RegExp('(\/route3?.+)').test(event.url)){
          this.openMap.sub3 = true;
          this.openHandler('sub3');
        } else if (RegExp('(\/route4?.+)').test(event.url)){
          this.openMap.sub4 = true;
          this.openHandler('sub4');
        }
      });
```
the openmap simply tracks which sub menus are open:

```  
openMap = {
    sub1: true,
    sub2: false,
    sub3: false,
    sub4: false,
  };
```

and openHandler() is what manages openMap's values: 

```
  openHandler(value: string): void {
    for (const key in this.openMap) {
      if (key !== value) {
        this.openMap[ key ] = false;
      }
    }
  }
```
