### ISSUE TITLE
ng-zorro-antd.min.css is not loaded

### ISSUE THREAD

**Issue by masalinas** [NG-ZORRO/ng-zorro-antd#1731]
## Version
1.1.0
## Environment
Angular 6.0.3   ng-zorro-antd 1.1.0
## Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)
## Steps to reproduce
Angular.json:
```
            "styles": [
              "node_modules/ng-zorro-antd/src/ng-zorro-antd.min.css",
              "src/styles.css"
            ],

```
The ng-zorro-antd.min.css is not loaded from my component. I must add this configuration in my component to run:

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['../../node_modules/ng-zorro-antd/src/ng-zorro-antd.min.css',
              './app.component.css']
})
```
## What is expected?
Load ng-zorro-antd.min.css
## What is actually happening?
No load ng-zorro-antd.min.css

**Comment by wendzhue** [comment]
@masalinas In the demo you provided, styles of nzButton is loaded. You should provide a reproduction link by clicking the FORK button on the stackblitz page and copying that URL (we can only see the demo not your code for now).

Did you `ng add ant-zorro-antd` after `ng serve`? In that case please restart the dev server.

**Comment by masalinas** [comment]
Yes I added the package using this command ng add ng-zorro-antd. The component configuration is correct, the ng-zorro-antd.min.css is added in the angular.json correct, I used the angular-cli for the project so everything is ok, but the css is not loaded, only if I added in the component style then is loaded, but this is not correct.

**Comment by vthinkxie** [comment]
@masalinas https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.ts
Just click export button in the top right, and `npm install` the exported folder, is everything ok now?

**Comment by HsuanXyz** [comment]
@masalinas Try clearing cache. `Chrome Dev-Tool > Application > Clear Storage`

**Comment by masalinas** [comment]
The problema was resolve!. I cleant he project and compile again and now the css is loaded. Really I don't know what happend :+1:
