### ISSUE TITLE
when nz-transfer in nz-form, it's title display style error

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd#1732]
## Version
1.1.0
## Environment
ng-zorro 1.1.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-transfer-in-form](https://stackblitz.com/edit/ng-zorro-transfer-in-form)
## Steps to reproduce
<form #f="ngForm" nz-form>
    <nz-form-item>
        <nz-form-label>请选择项目</nz-form-label>
        <nz-form-control>
          <nz-transfer
                [nzDataSource]="list"
                [nzTitles]="['Source', 'Target']"
                (nzSelectChange)="select($event)"
                (nzChange)="change($event)">
              </nz-transfer>
        </nz-form-control>
    </nz-form-item>
</form>
## What is expected?
标题可以正常显示
## What is actually happening?
标题被左对齐了
## Other?

![image](https://user-images.githubusercontent.com/3461709/41949292-6023dae0-79f3-11e8-856e-b0b4ff282c99.png)

**Comment by HsuanXyz** [comment]
@dusdong 临时方案:
```less
::ng-deep .ant-form-item .ant-transfer-list-header label {
  position: static;
}
```

@cipchk react 那边结构和咱们不一样。

**zorro**
```html
<div class="ant-transfer-list-header">
  <label nz-checkbox="" class="ant-checkbox-wrapper">
    <span class="ant-checkbox">
      <input class="ant-checkbox-input" type="checkbox">
      <span class="ant-checkbox-inner"></span>
    </span>
    <span>
      <span class="ant-transfer-list-header-selected">
        <span>18 项</span>
        <!--bindings={ "ng-reflect-ng-if": "Source" }-->
        <span class="ant-transfer-list-header-title">Source</span></span>
    </span>
  </label>
</div>
```

**react**

```html
<div class="ant-transfer-list-header">
  <label class="ant-checkbox-wrapper">
    <span class="ant-checkbox">
      <input type="checkbox" class="ant-checkbox-input" value="">
      <span class="ant-checkbox-inner"></span>
    </span>
  </label>
  <span class="ant-transfer-list-header-selected">
    <span>14 项</span>
    <span class="ant-transfer-list-header-title">Source</span></span>
</div>
```

**Comment by dusdong** [comment]
临时方案好使，谢谢！
