### ISSUE TITLE
datePicker  default highlight today bug

### ISSUE THREAD

**Issue by lyc152** [NG-ZORRO/ng-zorro-antd#1750]
## Version
0.7.0
## Environment
mac
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-cmyfmc?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-cmyfmc?file=src/app/app.component.ts)
## Steps to reproduce
Popup window to choose
## What is expected?
do not  default highlight today when I do not select today
## What is actually happening?
default highlight today
## Other?
在 1.0.x 版本也是这种情况

**Comment by vthinkxie** [comment]
work as design, you can check react version here https://ant.design/components/date-picker-cn/
