### ISSUE TITLE
tree have expandAll and collapseAll function

### ISSUE THREAD

**Issue by winds2016** [NG-ZORRO/ng-zorro-antd#1758]
## What problem does this feature solve?
I can expand or collapse all node sometimes
## What does the proposed API look like?
there are two function like expandAll and collapseAll

**Comment by simplejason** [comment]
you can traverse NzTreeNodes array to set `isExpanded` to `true` or `false`.

**Comment by winds2016** [comment]
ok
But i hope there is inner function we can call everywhere, so we do not need write many same code while expand or collapse all. or think of higher performance
This two function will be often called

**Comment by winds2016** [comment]
just like ng-tree-antd: tree.treeModel.expandAll();
