### ISSUE TITLE
NgZorroAntdModule.forRoot引入iconfont报错

### ISSUE THREAD

**Issue by HereWeR** [NG-ZORRO/ng-zorro-antd#176]
## I'm submitting a...

<pre><code>
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

按照文档(https://ng.ant.design/#/components/icon)引入iconfont，
NgZorroAntdModule.forRoot({ extraFontName: 'anticon', extraFontUrl: './assets/fonts/iconfont' }),
时报错： Supplied parameters do not match any signature of call target.

## Environment

<pre><code>
Angular version: 1.3.0

ng-zorro-antd version: ^0.5.0-rc.2

Browser:
- [ X ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
please check https://ng.ant.design/#/changelog
NgZorroAntdModule.forRoot is only for 0.5.0-rc.3
