### ISSUE TITLE
Adding support for RTL 

### ISSUE THREAD

**Issue by KhaledSMQ** [NG-ZORRO/ng-zorro-antd#1762]
## What problem does this feature solve?
Currently i tried to add RTL support for temporary solution till ant.design release official support for the components. please feel free to check my modified fork
https://github.com/KhaledSMQ/ng-zorro-antd

## What does the proposed API look like?
Add RTL Components

**Comment by mutasemAHmad** [comment]
Is there any update ?

**Comment by CoderBees245** [comment]
+

**Comment by saeedrahimi** [comment]
Currently we are working on a RTL fork of this repository in our company and we made some of components work with right-to-left direction.
I want to contribute and i don't know how to start.
I've already read the [Guide](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md).
We add rtl styles to components one by one and at the beginning i want to pull request button component.

**Comment by vthinkxie** [comment]
Hi @saeedrahimi 
I saw your pr https://github.com/NG-ZORRO/ng-zorro-antd/pull/3882/files great job, but all styles file are following [ant design repo](https://github.com/ant-design/ant-design)
there is a discuss [here](https://github.com/ant-design/ant-design/issues/4051) and [here](https://github.com/ant-design/ant-design-pro/issues/3969)
maybe you can submit a pr to ant-design repo first, so we can sync from them.
thanks a lot!

**Comment by wendellhu95** [comment]
@saeedrahimi I noticed that you finished the work of https://github.com/ant-design/ant-design/pull/19380. Greate job! Could you please bring RTL to zorro? Many thanks in advance!

**Comment by saeedrahimi** [comment]
RTL of Ant Design in react will be shipping out with v4 release. I there any plan to sync with new release? there are a lot of changes.
I think it needs to discuss after v4 release and syncing zorro with v4.

**Comment by wendellhu95** [comment]
@saeedrahimi We're working on ng-zorro-antd 9.0.0 and will sync antd 4.0.0 in this version. So feel free to submit PR.

**Comment by saeedrahimi** [comment]
#4704
