### ISSUE TITLE
Instead of February, another March is displayed

### ISSUE THREAD

**Issue by VladimirHumeniuk** [NG-ZORRO/ng-zorro-antd#1765]
![image](https://user-images.githubusercontent.com/20288162/42128185-40afe88a-7cae-11e8-857c-66e5f82bc452.png)

## Version
1.1.0
## Environment
Your site
## Reproduction link
[https://user-images.githubusercontent.com/20288162/42127863-ba5a0c84-7ca8-11e8-9d3e-a88435097a82.png](https://user-images.githubusercontent.com/20288162/42127863-ba5a0c84-7ca8-11e8-9d3e-a88435097a82.png)
## Steps to reproduce
Just check month picker in your documentation
## What is expected?
February
## What is actually happening?
March

**Comment by vthinkxie** [comment]
Hi @VladimirHumeniuk , I check our website and find everything works fine, can you provide a repro link?

**Comment by VladimirHumeniuk** [comment]
@vthinkxie  looks like now it's work fine, but it was like on my screen. Sorry then, i close issue.
