### ISSUE TITLE
nztree work with openlayers is slow

### ISSUE THREAD

**Issue by MagicWang** [NG-ZORRO/ng-zorro-antd#1771]
## Version
1.1.0
## Environment
win10 chrome68
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-m1gmr6](https://stackblitz.com/edit/ng-zorro-antd-start-m1gmr6)
## Steps to reproduce
pan and zoom the map
## What is expected?
map can pan and zoom fluency
## What is actually happening?
map is very slow,very high cpu
## Other?
nztree node number the less the better ,when more than 100 ,can not pan and zoom

**Comment by simplejason** [comment]
nz-tree won't affect your cpu usage, and your demo is working fine. you can describe your problem with more detail, chinese is ok! (tips: do not use `addChildren` every loop)

**Comment by MagicWang** [comment]
![image](https://user-images.githubusercontent.com/3860039/42149611-7946fb82-7e09-11e8-9348-866764dcf84d.png)
你试一下，5个节点跟5000个有什么区别，5个时地图拖动很流畅，5000个卡爆了，地图都拖动不了，我的项目上目前有1000多个节点，拖一下地图cpu就50%以上，把树去掉，就很流畅

**Comment by simplejason** [comment]
@MagicWang 这是Angular渲染机制，即使你使用简单的tr遍历5000条数据渲染，拖拽仍然会卡顿 ([issue](https://github.com/angular/angular/issues/23813))，不建议一次性全部展示数千条数据，可以采用滚动加载方式，只加载可见区域暂时规避。

**Comment by vthinkxie** [comment]
@MagicWang 
https://blog.thoughtram.io/angular/2017/02/02/making-your-angular-app-fast.html

**Comment by MagicWang** [comment]
![image](https://user-images.githubusercontent.com/3860039/42161904-6293cd72-7e2f-11e8-837d-596f7c6f01ac.png)
试过了__Zone_disable_requestAnimationFrame，onpush跟detach，效果都不大，看来只能改数据加载了

**Comment by mapsgeek** [comment]
same with mapboxGL js
