### ISSUE TITLE
nz-list cannot use an ellipsis instead of an overflow by  css style

### ISSUE THREAD

**Issue by cyhjojo** [NG-ZORRO/ng-zorro-antd#1778]
## Version
1.0.0
## Environment
angular/cli: 6.0.8
## Reproduction link
[https://ng-zorro-antd-start-udv4tt.stackblitz.io/](https://ng-zorro-antd-start-udv4tt.stackblitz.io/)
## Steps to reproduce
:host ::ng-deep .ant-list-item-content{
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
## What is expected?
show an ellipsis 
## What is actually happening?
the excess content is hidden , but the ellipsis is not show

**Comment by smile2014** [comment]
放在弹框上动态渲染数据的时候闪屏非常严重

**Comment by vthinkxie** [comment]
`text-overflow: ellipsis;` won't work in `display: flex; `
basic css problem closed.

**Comment by vthinkxie** [comment]
@smile2014 出现闪屏仔细看 angular 关于 ngFor 的文档
