### ISSUE TITLE
modal的onok和oncancel在返回promise报错时任然关闭

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#1779]
## What problem does this feature solve?
很多时候我们需要在onok或oncancel中处理复杂逻辑，遇到报错的时候并不想让modal关闭。现在的modal在promise无论成功还是失败都是关闭，这个逻辑在实际使用中并不是太实用
## What does the proposed API look like?
返回promise时出现错误不关闭modal。

能否考虑允许返回Obserable对象呢，本来深度集成rxjs了能返回Obserable具有promise同样的效果我们就可以少写个toPromise()了。
还可以增加个Obserable返回false时也不关闭。不是所有操作都是抛出异常的。

**Comment by simplejason** [comment]
使用 `NzModalRef ` 结合 自定义 footer，自己决定什么时候触发关闭或回调事件，官方demo有很多例子可参考。
