### ISSUE TITLE
nz-mention shall have custom filter function

### ISSUE THREAD

**Issue by humblepride** [NG-ZORRO/ng-zorro-antd#1784]
## What problem does this feature solve?
nz-mention can have custom template, and suggestion can filter by custom object field by providing custom nzValueWith. But the problem is, when I select the suggestion, all nzValueWith content is selected, not only the 'key' or 'name'.
## What does the proposed API look like?
nzValueWith: the object key or name to input when select some suggesion.
nzFilterWith: a custom fucntion to return a boolean, or string, to indicate whether this suggestion should be shown.

**Comment by HsuanXyz** [comment]
@humblepride You can use `(onSearchChange)`

 https://stackblitz.com/edit/nz-mention-filter

```ts
import { Component } from '@angular/core';
import { MentionOnSearchTypes } from 'ng-zorro-antd';

@Component({
  selector     : 'nz-mention-filter',
  template     : `
  <nz-mention
    [nzSuggestions]="suggestions"
    [nzValueWith]="valueWith"
    (nzOnSearchChange)="onSearchChange($event)">
    <input nzMentionTrigger nz-input placeholder="input @" [(ngModel)]="inputValue">
  </nz-mention>
`
})
export class NzMentionFilterComponent {
  inputValue: string;
  suggestions = [];
  webFrameworks = [
    { name: 'React', type: 'JavaScript', icon: 'https://zos.alipayobjects.com/rmsportal/LFIeMPzdLcLnEUe.svg' },
    { name: 'Angular', type: 'JavaScript', icon: 'https://zos.alipayobjects.com/rmsportal/PJTbxSvzYWjDZnJ.png' },
    { name: 'Dva', type: 'JavaScript', icon: 'https://zos.alipayobjects.com/rmsportal/EYPwSeEJKxDtVxI.png' },
    { name: 'Flask', type: 'Python', icon: 'https://zos.alipayobjects.com/rmsportal/xaypBUijfnpAlXE.png' },
  ];

   valueWith = data => data.name;

  onSearchChange({value}: MentionOnSearchTypes): void {
    this.suggestions = this.webFrameworks.filter(e => e.type === 'JavaScript')
  }

}
```

**Comment by humblepride** [comment]
Well. Look like I'm not clear enough.
Just like stackbliz you provided, what I'm expecting is: when I input "@Java", every webFramework with the word "Java"(in it's 'type' field) would appear as suggestion so I can select. For now, nothing appears.

**Comment by humblepride** [comment]
@HsuanXyz hello?

**Comment by humblepride** [comment]
@vthinkxie Hello, my problem is not solved.

**Comment by humblepride** [comment]
我自己移植了一个

`mention.component.ts`:
添加:`@Input() nzValueWithShow: (value: any) => string = value => value; // tslint:disable-line:no-any`
修改: 函数`selectSuggestion()`的第1行为: `const value = this.nzValueWithShow(suggestion);`

使用:
`my.component.html`:
```
<cbr-mention
  [nzValueWith]="tagFilterBy"
  [nzValueWithShow]="tagShowBy"
  ...></cbr-mention>
```
`my.compotent.ts`:
```
tagFilterBy = (tag) => `${tag.tag_key} - ${tag.tag_desc} - ${tag.tag_key_alias_list}`;
tagShowBy = (tag) => tag.tag_key;
```
