### ISSUE TITLE
nz-range-picker throw an error in aot

### ISSUE THREAD

**Issue by lyon-liao** [NG-ZORRO/ng-zorro-antd#1788]
## Version
0.7.1
## Environment
Angular CLI: 6.0.1
Node: 8.11.1
OS: darwin x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/cdk                      5.2.5
@angular/cli                      6.0.1
@angular/flex-layout              6.0.0-beta.16
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ewkyz2?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-ewkyz2?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
npm run build:prod
## What is expected?
datetime picker work well
## What is actually happening?
```
ERROR TypeError: Cannot read property '0' of undefined
    at t.getPlaceholder (main.94ded981dd7a28ce4841.js:1)
    at Object.updateRenderer (main.94ded981dd7a28ce4841.js:1)
    at Object.updateRenderer (main.94ded981dd7a28ce4841.js:1)
    at to (main.94ded981dd7a28ce4841.js:1)
    at uo (main.94ded981dd7a28ce4841.js:1)
    at lo (main.94ded981dd7a28ce4841.js:1)
    at to (main.94ded981dd7a28ce4841.js:1)
    at uo (main.94ded981dd7a28ce4841.js:1)
    at lo (main.94ded981dd7a28ce4841.js:1)
    at to (main.94ded981dd7a28ce4841.js:1)
```

**Comment by vthinkxie** [comment]
everything works fine in your repro link after build in aot mode.
you can export and try yourself.
