### ISSUE TITLE
nz-avatar报错

### ISSUE THREAD

**Issue by sunbay** [NG-ZORRO/ng-zorro-antd#179]
1. 使用文档中的示例代码：
  `<nz-avatar nzIcon="user" nzSrc="''"></nz-avatar>`

就会报错，`Can't bind to 'nzSrc' since it isn't a known property of 'nz-avatar'`

而其他directive都能正常使用，NgZorroAntdModule已正确引入。

2. 如果使用`<nz-avatar nzIcon="user"></nz-avatar>`

则依然会报错：

'nz-avatar' is not a known element:

请问这是什么原因？谢谢

**Comment by vthinkxie** [comment]
`nz-avatar` is only provided in `0.5.0-rc.3` version.
