### ISSUE TITLE
why can not use treeSelect

### ISSUE THREAD

**Issue by songjinb** [NG-ZORRO/ng-zorro-antd#1790]
Can't bind to 'nzDefaultExpandedKeys' since it isn't a known property of 'nz-tree-select'.
1. If 'nz-tree-select' is an Angular component and it has 'nzDefaultExpandedKeys' input, then verify that it is part of this module.
2. If 'nz-tree-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<nz-tree-select

**Comment by simplejason** [comment]
make sure you have import NgZorroAntdModule in module and ng-zorro's version is 1.0+
