### ISSUE TITLE
nzTreeComponent nzCheckBoxChange event is not called when the data nodes "checked" is set true

### ISSUE THREAD

**Issue by super3s1988** [NG-ZORRO/ng-zorro-antd#1791]
## Version
1.1.1
## Environment
Angular 6
## Reproduction link
[https://ng-zorro-antd-start-jsaemj.stackblitz.io/](https://ng-zorro-antd-start-jsaemj.stackblitz.io/)
## Steps to reproduce
No actions required
## What is expected?
checkEvent() is called when the tree is init complete
## What is actually happening?
checkEvent() is not called

**Comment by simplejason** [comment]
`nzCheckBoxChange ` will be called if the node's checkbox is clicked, not value changed!

**Comment by super3s1988** [comment]
有没有什么办法知道值改变或者知道数据加载完成后的回调函数

**Comment by simplejason** [comment]
@super3s1988 如果用户点击你可以触发nzCheckBoxChange，如果是你自己更改值你可以直接执行相关方法啊，数据加载完成依赖的是你ngModel什么时候赋值，tree组件只是渲染你的数据

**Comment by super3s1988** [comment]
明白了，谢谢
