### ISSUE TITLE
nz-range-picker can Limit the selected date ?

### ISSUE THREAD

**Issue by pgh147** [NG-ZORRO/ng-zorro-antd#1792]
## What problem does this feature solve?
I chose one time and wanted to limit the other time interval.我选择一个时间，希望根据这个选择的时间去限制另一个时间的范围
## What does the proposed API look like?
Provides time to select events

**Comment by simplejason** [comment]
`nzDisabledDate` & `nzDisabledTime` may help you, more details you can read official document's demo

**Comment by wilsoncook** [comment]
As @simplejason mentioned above, pls use `nzDisabledDate` and `nzDisabledTime` to archive your goals, demo refer to: http://ng.ant.design/components/date-picker/zh#components-date-picker-demo-start-end

**Comment by renyuns** [comment]
Can this function be used now? I want to limit the end  date of <nz-range-picker> to just today and before today.  现在这个功能可以用吗,我想限制 <nz-range-picker> 的结束之间只能是今天之前
