### ISSUE TITLE
nz-select 不能实现自定义输入值

### ISSUE THREAD

**Issue by jimsonyang** [NG-ZORRO/ng-zorro-antd#1794]
## What problem does this feature solve?
下拉单选时，实现用户自定义输入值
## What does the proposed API look like?
当单选nz-select时， 应该具备allowCustom属性 ，使其可以实现自定义用户输入值

**Comment by jimsonyang** [comment]
请帮忙实现 该功能 ！

**Comment by JCqiu** [comment]
![test](https://user-images.githubusercontent.com/16211027/42358841-512b157e-8111-11e8-923e-629161380d10.gif)

**Comment by jimsonyang** [comment]
谢谢，试过了，下拉是可以输入但当下拉列表没有值的时候，自己输入的值是不能被选中的。
也就是说，当自动下拉列表没有联想到值的时候，由我输入的值取代。。。
