### ISSUE TITLE
(nzSelect): unable to trigger nzScrollToBottom when using display scaling

### ISSUE THREAD

**Issue by itryan** [NG-ZORRO/ng-zorro-antd#1796]
## Version
1.1.1
## Environment
Windows 10 (Display Scaling 175%), Chrome 67
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-qcihna](https://stackblitz.com/edit/ng-zorro-antd-start-qcihna)
## Steps to reproduce
open the select and scroll to the bottom
## What is expected?
trigger nzScrollToBottom event and call the loadMore() function
## What is actually happening?
nzScrollToBottom is not triggered

**Comment by itryan** [comment]
in `\components\select\nz-option-container.component.ts`

```typescript
  dropDownScroll(e: MouseEvent, ul: HTMLUListElement): void {
    e.preventDefault();
    e.stopPropagation();    
    if (ul && (ul.scrollHeight - ul.scrollTop === ul.clientHeight)) {   // scrollTop could be decimal
      this.nzScrollToBottom.emit();
    }
  }
```

**Comment by itryan** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/61dc87be8a4fd4687d83c5e9e0d5d3d19dd11575/components/select/nz-option-container.component.ts#L268-L274

```typescript
    if (ul && (ul.scrollHeight - ul.scrollTop === ul.clientHeight)) {   // scrollTop could be decimal
      ...
```

**Comment by vthinkxie** [comment]
fixed in latest version.
