### ISSUE TITLE
Can't change the locale to Korean

### ISSUE THREAD

**Issue by SimyungYang** [NG-ZORRO/ng-zorro-antd#1797]
## Version
1.1.1
## Environment
.
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-a53njp](https://stackblitz.com/edit/ng-zorro-antd-start-a53njp)
## Steps to reproduce
Please see the reproduce link
## What is expected?
Run without error.

the data format in ko_KR.d.ts file is not compatible with NzI18nInterface.
## What is actually happening?
Encountered the following error.
================================================================
ERROR in src/app/datepicker/datepicker.component.ts(30,25): error TS2345: Argument of type '{ locale: string; Pagination: { items_per_page: string; jump_to: string; jump_to_confirm: string;...' is not assignable to parameter of type 'NzI18nInterface'.
  Types of property 'Table' are incompatible.
    Type '{ filterTitle: string; filterConfirm: string; filterReset: string; emptyText: string; }' is not assignable to type '{ filterTitle: string; filterConfirm: string; filterReset: string; emptyText: string; selectAll: ...'.
      Property 'selectAll' is missing in type '{ filterTitle: string; filterConfirm: string; filterReset: string; emptyText: string; }'.

**Comment by simplejason** [comment]
you should register `@angular/common/locales/ko` in your module.([offical demo](http://ng.ant.design/docs/i18n/en#providers)).

**Comment by SimyungYang** [comment]
Even though i added ko locale, the error message is showing.

Look again reproduction link.

Thank you,

**Comment by SimyungYang** [comment]
If you see the file, https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/i18n/languages/ko_KR.ts,

You can see the selectAll, selectInvert field is missing in table.
I added that field in ko_KR.d.ts in node_module, and the error message is gone.

I hope that would be applied in the regular release.

Thank you

**Comment by SimyungYang** [comment]
@HsuanXyz Sure, I'll create a PR to fix it.
