### ISSUE TITLE
ng-select can not inputs a custom text

### ISSUE THREAD

**Issue by jimsonyang** [NG-ZORRO/ng-zorro-antd#1799]
## What problem does this feature solve?
Can not input a custom value .. it is look like adding an attribute 'allowCustom' in this component
## What does the proposed API look like?
Can not input a custom value .. it is look like adding an attribute 'allowCustom' in this component

**Comment by HsuanXyz** [comment]
Not yet support, ZORRO will always sync with [ant design](https://ant.design/).
