### ISSUE TITLE
about datetime picker two way binding

### ISSUE THREAD

**Issue by icepoint0** [NG-ZORRO/ng-zorro-antd#180]
![123xxx](https://user-images.githubusercontent.com/12691638/29800803-9226e494-8c9e-11e7-9201-2a53b27ca0ca.png)

## 双向绑定绑定的值成为了一个moment对象

1.我要如何通过这个对象找到时间。getTime or other function ?
2.我在数据库存储的时间 要以什么样的格式 才能展现在 input默认时间里？现在都是invalid date。

**Comment by vthinkxie** [comment]
have a look at http://momentjs.cn/
