### ISSUE TITLE
menu可不可以增加一个靠右侧的item功能？

### ISSUE THREAD

**Issue by qq253498229** [NG-ZORRO/ng-zorro-antd#1803]
## What problem does this feature solve?
菜单右上角经常需要一个注销按钮，现在的api里面没有找到，需要自己实现，但是样式会出现问题
![image](https://user-images.githubusercontent.com/31200516/42438999-3b63d548-8394-11e8-98a2-990e44630568.png)

## What does the proposed API look like?
nz-menu-item-right类似这样的，或者增加一个属性[nzRight]

**Comment by JCqiu** [comment]
用Dropdown这个控件

**Comment by qq253498229** [comment]
@JCqiu 多谢多谢
