### ISSUE TITLE
Use Observable instead of Subject

### ISSUE THREAD

**Issue by Brooooooklyn** [NG-ZORRO/ng-zorro-antd#181]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

in some components, ng-zorro use subject to emit values when event callback triggered.
But this is not a good practice when writing Angular component.

## Expected behavior

Use Observable.fromEvent / Observable.create to wrap eventListener， and dispose the eventListener in teardown logic when unsubscribe in ngOnDestroy.

## Minimal reproduction of the problem with instructions

see https://github.com/NG-ZORRO/ng-zorro-antd/pull/148

## What is the motivation / use case for changing the behavior?

performance imporve

**Comment by Brooooooklyn** [comment]
@vthinkxie @trotyl  what do you think about this issue. if you are approving my suggestion, I will help you to change all Subject to Observable.

**Comment by vthinkxie** [comment]
@trotyl what do you think about it

**Comment by trotyl** [comment]
Dropdown is a special case which has dynamic event trigger, I don't think it would apply to all components, is there any specific reason for that?
