### ISSUE TITLE
nz-carousel's width doesn't changed after the window resized

### ISSUE THREAD

**Issue by wuiancocos2d** [NG-ZORRO/ng-zorro-antd#1811]
## Version
1.1.1
## Environment
windows 7 / chrome 65.0.3325.181 
## Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)
## Steps to reproduce
```javascript
<nz-carousel>
	<div nz-carousel-content>
		<div nz-col nzXs="24" nzSm="24" nzMd="12" nzLg="12" nzXl="12">
			<h3>Title of image</h3>
		</div>
		<div nz-col nzXs="24" nzSm="24" nzMd="12" nzLg="12" nzXl="12">
			<img src="https://i2.wp.com/www.cartwheelart.com/site/wp-content/uploads/2018/01/49-Romero.jpg?w=600" alt="" style="width:100%">
		</div>
	</div>
</nz-carousel>
```
## What is expected?
nz-carousel's width will be changed after the window resized
## What is actually happening?
nz-carousel's width doesn't changed after the window resized
## Other?
use nz-carousel-content with ng grid

**Comment by wuiancocos2d** [comment]
here is editor's url
https://stackblitz.com/edit/ng-zorro-antd-start
would you kindly give some suggestions ?

**Comment by HsuanXyz** [comment]
@wuiancocos2d You need to click `FORK` button the get a unique URL with [stackblitz](https://stackblitz.com/edit/ng-zorro-antd-start).

**Comment by wuiancocos2d** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-bg1lwd?file=src/index.html
@HsuanXyz thx for you advice !!

**Comment by wuiancocos2d** [comment]
@HsuanXyz thx very much!!
