### ISSUE TITLE
modal弹出后表格右侧显示空白边距

### ISSUE THREAD

**Issue by WangHone** [NG-ZORRO/ng-zorro-antd#1814]
## Version
1.1.1
## Environment
win10,chrome67
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-qpbax7?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-qpbax7?file=src/app/app.component.html)
## Steps to reproduce
点击delete按钮,弹出对话框后,页面右侧显示空白边距
## What is expected?
页面右侧不显示空白边距
## What is actually happening?
页面右侧显示空白边距

**Comment by HsuanXyz** [comment]
Duplicate #1422 #1720
