### ISSUE TITLE
Add gesture support to Carousel

### ISSUE THREAD

**Issue by wuiancocos2d** [NG-ZORRO/ng-zorro-antd#1816]
## What problem does this feature solve?
Add gesture animate to Carousel component , to improve the experience of phone user. Including , swap distance  animate before next()/pre()
## What does the proposed API look like?
[swapDistance], [ifGesture]

**Comment by wendzhue** [comment]
Ant Design React supports swipe gesture. We should keep up.

**Comment by vthinkxie** [comment]
add support for hammerjs
