### ISSUE TITLE
关于 nz-table 的搜索功能的支持

### ISSUE THREAD

**Issue by myepoch** [NG-ZORRO/ng-zorro-antd#182]
1.nz-table 看文档上说是支持 对数据进行搜索，但是在文档并没有看到如何用，并且查看源码也没看到哪里支持这个搜索功能。是下一版本支持吗？
2.另外，该组件是否支持行编辑，是不是当前不支持，之后再做考虑呢？

**Comment by vthinkxie** [comment]
Table data is on the control by yourself, you can just filter the data in javascript or in server side.
If you want to edit table row, just show nz-input in `tr` under the condition defined by yourself.
