### ISSUE TITLE
Popover placement

### ISSUE THREAD

**Issue by zhuxm0217** [NG-ZORRO/ng-zorro-antd#1825]
## Version
1.1.1
## Environment
win7 chrome 最新版本zorro
## Reproduction link
[https://stackblitz.com/edit/tabs-bug-add-to-start-2nie1w?file=src/index.html](https://stackblitz.com/edit/tabs-bug-add-to-start-2nie1w?file=src/index.html)
## Steps to reproduce
鼠标移到表格任何一行的文字上
## What is expected?
期望解决
## What is actually happening?
Popover不能显示在合适的位置上

**Comment by zhuxm0217** [comment]
![default](https://user-images.githubusercontent.com/25685199/42683569-3ded6de0-86c0-11e8-92cf-6e8e044c7bd1.png)
![1](https://user-images.githubusercontent.com/25685199/42683573-400bebb0-86c0-11e8-9892-f5a5d2b32f1c.png)

**Comment by zhuxm0217** [comment]
什么时候解决？

**Comment by zhuxm0217** [comment]
@vthinkxie

**Comment by zhuxm0217** [comment]
@vthinkxie @wendzhue 麻烦告知下什么时候解决？谢谢

**Comment by vthinkxie** [comment]
@zhuxm0217 定位目前完全依赖于 `@angular/cdk`的算法，我们没有自己添加任何内容
