### ISSUE TITLE
Anchor Bug 

### ISSUE THREAD

**Issue by AnhuiWdan** [NG-ZORRO/ng-zorro-antd#1827]
## Version
1.1.1
## Environment
angular 6 
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-zkmuml](https://stackblitz.com/edit/ng-zorro-antd-start-zkmuml)
## Steps to reproduce
文档中的代码，点击API、nz-anchor、nz-link的锚点都不生效
## What is expected?
跳转
## What is actually happening?
不能跳转

**Comment by vthinkxie** [comment]
锚点都没有设定，当然点击不会生效了
http://www.w3school.com.cn/html/html_links.asp
https://stackblitz.com/edit/ng-zorro-antd-start-zkmuml?file=src%2Fapp%2Fapp.component.html
