### ISSUE TITLE
[nz-tree] 通过checkedKeys 属性取消选中节点时，不会反映到页面上

### ISSUE THREAD

**Issue by gassyou** [NG-ZORRO/ng-zorro-antd#1836]
## Version
1.1.1
## Environment
window 10，chrome 67
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-cweh9l](https://stackblitz.com/edit/ng-zorro-antd-start-cweh9l)
## Steps to reproduce
将 checkedKeys 数组中的数据 移除时，页面上没有反映。
但是，向checkedKeys 数组中添加数据时，页面上相关的节点会变成选中状态。
## What is expected?
将 checkedKeys 数组中的数据 移除时，页面上的选择状态也应该被取消。
## What is actually happening?
将 checkedKeys 数组中的数据 移除时，页面上的选择状态没有被取消。

**Comment by simplejason** [comment]
追踪这个PR #1809

**Comment by gassyou** [comment]
[这个问题。好像还没有解决彻底。比如，说原来选中了2个节点。通过手动赋值，变成一个被选中。但是页面上还是2个节点被选中的状态。

https://stackblitz.com/edit/ng-zorro-antd-start-cweh9l

https://stackblitz.com/edit/angular-u1zoon-yeygt3

**Comment by wangwanttt** [comment]
我用最新 1.5 版也遇到了这个问题，怎么改都不行
// this.changeRef.markForCheck();
        // this.changeRef.detectChanges();
        // this.zone.run(() => {
        //     console.log('enabled time travel');
        // });
