### ISSUE TITLE
The selector wants to select all option

### ISSUE THREAD

**Issue by liuwu1211** [NG-ZORRO/ng-zorro-antd#1837]
## What problem does this feature solve?
Too many options, one choice is too much trouble
用户查询统计数据时，要自定义查看什么分类的数据，之前在使用primeNG框架时，我做了4级多选联动，满足客户要求，现在需要换框架，发现并没有select全选。
功能说明（以我做出来的效果为例）：
一个四级select，
页面初始化时，四个select加载所有选项，可以从任意一个选项开始选择，并联动父级和子级
选择样式就好比是所有的option都是CheckBox，联动效果是，CheckBox变为已选状态，select输入框显示选择了几项或者具体到选择名称，每个select可以支持全选，搜索关键字
此功能可以解决：
用户从一级菜单一直选到3级菜单时，4级菜单的选项还是很多，用户如果不能全选的话不太友好
另外：
tree-select这个功能不太适合普通用户
## What does the proposed API look like?
不需要API，只要select可以支持全选功能，搜索功能，选项显示优化就可以了

**Comment by HsuanXyz** [comment]
NG-ZORRO 仅支持 [Ant Design](https://ant.design/components/select-cn/) 已有的组件和功能，如果目前的组件不能满足你的需求建议前往 [ant-design/issues](https://github.com/ant-design/ant-design/issues) 提需求。

目前建议你使用 dropdown + checkbox 实现。
