### ISSUE TITLE
AutoComplete: at the bottom of the page, the drop-down is blocked

### ISSUE THREAD

**Issue by zhuxm0217** [NG-ZORRO/ng-zorro-antd#1840]
![111](https://user-images.githubusercontent.com/25685199/42919586-3ef7fe7e-8b45-11e8-8fd1-d7e8e2ea5075.jpg)
![222](https://user-images.githubusercontent.com/25685199/42919587-3f396094-8b45-11e8-8a6f-2aeee6c1dd61.jpg)

## Version
1.1.1
## Environment
win7; chrome; zorro 1.1.1
## Reproduction link
[https://stackblitz.com/edit/angular-e13ftq?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-e13ftq?file=src/app/app.component.ts)
## Steps to reproduce
页面底部的AutoComplete下拉框被挡住
## What is expected?
期望解决
## What is actually happening?
页面底部的AutoComplete下拉框被挡住

**Comment by HsuanXyz** [comment]
@zhuxm0217 感谢反馈，这里存在2个问题。

1. 初始化定位（因为打开动画还没完成，将在本次修复）
2. 在固定高度表格中无法跟随滚动（CDK 目前还不支持设置滚动容器，所以会在未来修复）
