### ISSUE TITLE
nz-overlay-container添加的pointer-events：none在ie10 不兼容

### ISSUE THREAD

**Issue by htmlcss23** [NG-ZORRO/ng-zorro-antd#1842]
在ie10下所有的元素都被nz-overlay-container遮盖住

**Comment by screamsyk** [comment]
由于.nz-overlay-container样式中高宽为100%，遮挡了整个页面，而IE10对pointer-events：none的支持性不好，所以会导致一些鼠标操作上的问题。
通过将.nz-overlay-container样式中的高宽都设为0，可以暂时解决IE10下的问题，但不是很清楚这样改会不会有其他的影响 @vthinkxie

**Comment by screamsyk** [comment]
test @screamsyk

**Comment by screamsyk** [comment]
好吧，这是个错误的解决办法，会对nz-dropdown、popover这类组件有影响

**Comment by vthinkxie** [comment]
@screamsyk   @angular/cdk 已经放弃对 ie10 版本的兼容
