### ISSUE TITLE
upload组件未传递要移除的file对象给Observable<boolean>类型的[nzRemove]回调

### ISSUE THREAD

**Issue by wlclass** [NG-ZORRO/ng-zorro-antd#1850]
## Version
1.1.1
## Environment
windows10 , chorme
## Reproduction link
[https://stackblitz.com/edit/antd-upload-nzremove?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/antd-upload-nzremove?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
打开[重现链接](https://stackblitz.com/edit/antd-upload-nzremove?file=src%2Fapp%2Fapp.component.ts),点击upload组件中任一图片的移除按钮
## What is expected?
期望在handleRemove方法中能获取到将要移除的file对象，以便发送http请求进行后台数据删除处理，在http返回成功后，才允许将图片从upload的ui上移除。
## What is actually happening?
handleRemove无法获取到将要移除的file对象

**Comment by GeorgeHuang13** [comment]
啥时候能修正呢。。。。

**Comment by louisljw** [comment]
传值的时候还是传 file 对象，把返回结果设置成 observable 对象就可以了。
`handleRemove = (file: NzUploadFile) => {
    return new Observable<boolean>((obs) => {
        // do something
        obs.next(false);
    });
}`
