### ISSUE TITLE
nz-modal trigger (nzAfterClose) when component init

### ISSUE THREAD

**Issue by chenxxzhe** [NG-ZORRO/ng-zorro-antd#1852]
## Version
1.1.1
## Environment
angular 6
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-m1gh88](https://stackblitz.com/edit/ng-zorro-antd-start-m1gh88)
## Steps to reproduce
check the console
## What is expected?
don't trigger afterClose when component init
## What is actually happening?
trigger afterClose when component init

**Comment by vthinkxie** [comment]
you use `nzVisible = false` to close the modal, the afterClose will be called as designed.
