### ISSUE TITLE
Basic table sorting only work once.

### ISSUE THREAD

**Issue by penleychan** [NG-ZORRO/ng-zorro-antd#1853]
## Version
1.1.1
## Environment
Angular 6
## Reproduction link
[https://stackblitz.com/edit/angular-xcs429](https://stackblitz.com/edit/angular-xcs429)
## Steps to reproduce
Click on the sort button (ex. ascending), then click the (descending) or any other sort button
## What is expected?
It should sort the table
## What is actually happening?
It only sort once, then sort no longer works/stop functioning.

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-m3zjpa?file=src/app/app.component.ts
please read the doc of nz-table in the bottom.
