### ISSUE TITLE
keydown事件无效

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1854]
## Version
1.1.1
## Environment
win10,chrome66,1.1.1
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-juvmdk?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-juvmdk?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
keydown事件无效
## What is expected?
keydown事件有效
## What is actually happening?
keydown事件无效

**Comment by vthinkxie** [comment]
mousedown？
you can only add keydown event to the element which can be focused.
please read the document of keydown carefully.
