### ISSUE TITLE
Responsive header

### ISSUE THREAD

**Issue by cdskill** [NG-ZORRO/ng-zorro-antd#1869]
## What problem does this feature solve?
Having a header with the same behaviour of sider with some size breakpoint like the sider...
## What does the proposed API look like?
Not responsive !

**Comment by vthinkxie** [comment]
https://ng.ant.design/docs/faq/zh
#有些特性为什么不会被支持
ng-zorro-antd 是 Angular 版本 Ant Design 的实现，这意味着只有 Ant Design 支持的交互、功能 才会被 ng-zorro-antd 实现。

**Comment by cdskill** [comment]
No english ?

**Comment by vthinkxie** [comment]
we only support the features designed by `ant design`
