### ISSUE TITLE
IE11打开demo站点，cpu占用率高，页面卡顿

### ISSUE THREAD

**Issue by linkaiyi** [NG-ZORRO/ng-zorro-antd#187]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

IE11打开demo站点( https://ng.ant.design/#/components/form )，cpu占用率高，页面卡顿，试了2台机子都是这样，chrome没问题。
![p](https://user-images.githubusercontent.com/1537278/29824077-194429e6-8d03-11e7-9dbc-fb94a72c7b8a.png)

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x] IE version 11
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jianqiao0313** [comment]
+1

**Comment by myepoch** [comment]
+1

**Comment by vthinkxie** [comment]
anyone can help us figure the problem, we can not reproduce it.

**Comment by linkaiyi** [comment]
特别是在拖动滚动条的时候很卡
![p1](https://user-images.githubusercontent.com/1537278/30149878-e60ca078-93db-11e7-9cea-1bed259973c7.png)
![p2](https://user-images.githubusercontent.com/1537278/30149884-eb5499a0-93db-11e7-9698-4bd7be9b65c6.png)
以下是IE11的性能会话分析文件，可在IE11中导入查看。

[ng_ant_design.zip](https://github.com/NG-ZORRO/ng-zorro-antd/files/1283659/ng_ant_design.zip)

**Comment by vthinkxie** [comment]
@linkaiyi thanks a lot

**Comment by linkaiyi** [comment]
另外React版本虽然在滚动页面的时候cpu占用率也是在30%左右(cpu i5-7200U@2.5G)，但是很平滑，没有卡顿现象。
