### ISSUE TITLE
Set initial filter to nz-table component

### ISSUE THREAD

**Issue by oluevano** [NG-ZORRO/ng-zorro-antd#1872]
## What problem does this feature solve?
Currently in my "nz-table" component in the header column can i set filterList in the nzFilters (input component parameter) but i can't set initial filter.

Can you help me with this wish?

Thank you
## What does the proposed API look like?
I propose when set filterList input parameter on the header column, add one flag to set initial filters based on the filterList inputParameter and after this tirrger event "nzFilterChange", with this initial filter.

For example

To the [nzFilters] input parameter -> [{text: 'anyText' , value: 'anyValueId' }]

change To

[nzFilters] -> [{text: 'anyText' , value: 'anyValueId', selected : <true/false> }]

**Comment by vthinkxie** [comment]
we will try to support in in next version.

**Comment by wendzhue** [comment]
@oluevano You can check the deploy preview. Is that what you need?

**Comment by oluevano** [comment]
@wendzhue.  thank you so much, i will try this feature! and send you comments!

**Comment by oluevano** [comment]
I tried the feature and it's ok!.

Thank you so much!.
