### ISSUE TITLE
在嵌套路由中【非站点根路径下】使用nz-anchor

### ISSUE THREAD

**Issue by kisslove** [NG-ZORRO/ng-zorro-antd#1875]
## What problem does this feature solve?
使用ng-zorro@1.2.0。假设我的站点是：http://test.com。我在子级路由【http://test.com/page1】页面中使用nz-anchor，由于 nzHref="#test1"，指向的是http://test.com/#test1,导致找不到对应锚点，所以无法导航
## What does the proposed API look like?
nzHref="page1#test1"，这样指向的是http://test.com/page1#test1

**Comment by kisslove** [comment]
我想使用   nzHref="#page/page2#test" ,
在源码中，使用 this.doc.querySelector(linkComp.nzHref)，去获取锚点元素，假如我的nzHref=“page/page2#test”，这样就会报错，
`handleScrollTo(linkComp: NzAnchorLinkComponent): void {
    const el = this.doc.querySelector(linkComp.nzHref);
    if (!el) {
      return;
    }

    this.animating = true;
    const containerScrollTop = this.scrollSrv.getScroll(this.getTarget());
    const elOffsetTop = this.scrollSrv.getOffset(el).top;
    const targetScrollTop = containerScrollTop + elOffsetTop - (this.nzOffsetTop || 0);
    this.scrollSrv.scrollTo(this.getTarget(), targetScrollTop, null, () => {
      this.animating = false;
      this.handleActive(linkComp);
    });
    this.nzClick.emit(linkComp.nzHref);
  }
`

**Comment by kisslove** [comment]
源码中使用this.doc.querySelector(linkComp.nzHref)去获取锚点对应元素，我的nzHref中包含“/”,这样就会出错，比如nzHref=“page/test#test1”.
`  handleScrollTo(linkComp: NzAnchorLinkComponent): void {
    const el = this.doc.querySelector(linkComp.nzHref);
    if (!el) {
      return;
    }

    this.animating = true;
    const containerScrollTop = this.scrollSrv.getScroll(this.getTarget());
    const elOffsetTop = this.scrollSrv.getOffset(el).top;
    const targetScrollTop = containerScrollTop + elOffsetTop - (this.nzOffsetTop || 0);
    this.scrollSrv.scrollTo(this.getTarget(), targetScrollTop, null, () => {
      this.animating = false;
      this.handleActive(linkComp);
    });
    this.nzClick.emit(linkComp.nzHref);
  }`

**Comment by HsuanXyz** [comment]
> 这是一个必需属性为锚定义一个超文本链接来源。这表示链接目标的URL或URL片段。URL片段是由一个hash符号（＃），它指定一个内部目标在**当前文档中的位置**（ID）开头的名字。 
—— https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/a

**Comment by ZCatherine** [comment]
Hello, I have encountered the same problem.I can not jump when using abchor in sub-routes of nested routes, how do you solve it?
