### ISSUE TITLE
nzInput 中的nzPlaceHolder

### ISSUE THREAD

**Issue by guaicaiboshi** [NG-ZORRO/ng-zorro-antd#1878]
经过测试发现，在IE11浏览器中，只要nzInput 中的nzPlaceHolder描述为中文就会出现脏验证，把错误显示出来，英文情况下没有问题，使用的版本是0.6.14，本来想在你们指定的地方提交BUG，但是没法找到0.6.14的版本使用

**Comment by vthinkxie** [comment]
0.6.x 已经不再维护，请尽快升级
