### ISSUE TITLE
nzInput 配置nzPlaceholder中文触发脏检查

### ISSUE THREAD

**Issue by guaicaiboshi** [NG-ZORRO/ng-zorro-antd#1879]
## Version
0.6.14
## Environment
系统win7专业版，浏览器IE11，an-zorro版本0.6.14
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-akcxhc?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-akcxhc?file=src/app/app.component.html)
## Steps to reproduce
直接打开重现连接即可触发第一个input框的脏检查，因为nzPlaceholder使用了中文，如果是英文和数字不会有问题。
## What is expected?
期望打开时候不会进行脏检查。nzPlaceholder为中文的时候
## What is actually happening?
nzPlaceholder为中文，在第一次打开页面触发了脏检查
## Other?
我开发环境用的是0.6.14版本，由于stackblitz的里面不知道怎么指定版本，所以用了你们1.2的 from 登录框 的代码，只是把placeholder部分改成中文，在IE11下任然有有问题，希望我的0.6.14版本能有解决方案，谢谢

**Comment by HsuanXyz** [comment]
0.6.x 已经不再提供维护；关于 Form 你可以在 [这里](https://angular.io/api/forms/FormControl) 了解更多。

**Comment by guaicaiboshi** [comment]
但是1.2的版本也有同样的问题？这个也不维护吗？

**Comment by vthinkxie** [comment]
@guaicaiboshi 1.2 版本没有对 placeholder 做任何特殊处理，不使用 ng-zorro-antd 你看到的情况应该是一模一样的，另外你表述的脏检查是什么意思，整个angular 的运行基础就是脏值检查，打开页面的时候必然会进行第一次脏值检查
