### ISSUE TITLE
modal 框内容过多时，modal框的内容区域不会出现滚动条

### ISSUE THREAD

**Issue by Guoyilin10** [NG-ZORRO/ng-zorro-antd#1882]
## What problem does this feature solve?
弹出层内容多的时候，modal框的内容区域出现滚动条，方便查阅
## What does the proposed API look like?
弹出层内容多的时候，modal框的内容区域出现滚动条

![image](https://user-images.githubusercontent.com/24948321/43248239-d1ea1948-90e9-11e8-8876-5a33ba410f9a.png)

**Comment by wendzhue** [comment]
请提供一个最小复现
不过，要达成你想要的效果，似乎仅需在内容外套一个 div，设置 max-height 和 overflow: scroll

**Comment by ishowman** [comment]
@Guoyilin10 建议使用Component模式去实现，官方文档已经有示例代码
