### ISSUE TITLE
Tooltip, large text 

### ISSUE THREAD

**Issue by andersonchica** [NG-ZORRO/ng-zorro-antd#1885]
## Version
0.7.0
## Environment
Angular 4.0
## Reproduction link
[https://stackblitz.com/edit/angular-hdpihx?file=app/app.component.ts](https://stackblitz.com/edit/angular-hdpihx?file=app/app.component.ts)
## Steps to reproduce
when the tooltip appear, the text does not appear completally
## What is expected?
show all text from span
## What is actually happening?
show in the first line untextodemasiadolargo/store/comodis, and the next row show comodisimos-camas_electricas, the text of span is untextodemasiadolargo/store/comodisimos2/categoria-comodisimos-camas_electricas, the is cutting imos2/categoria-

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-hdpihx-1xpaez?file=app/app.component.ts
you can add your own classname to make large text wrap.
