### ISSUE TITLE
Ability to disable vertical menu when sider is collapsed

### ISSUE THREAD

**Issue by KevinStirling** [NG-ZORRO/ng-zorro-antd#1886]
## What problem does this feature solve?
> I am using angular's `BreakPointObserver` to switch between an inline menu layout expanded for large screens, an inline layout collapsed with a collapsed width of `80px` for medium sized screens, and an inline layout collapsed with a collapse width of `0px` for mobile devices. 

> I have a basic working example of this here: https://stackblitz.com/edit/angular-enh6va

>When in mobile view, where the menu is collapsed, the vertical menu will suddenly appear if you are redirected to one of the submenu items's router links, and that sub menu item has `routerLinkActive="ant-menu-item-selected"`. I do not have enough time to build a stack blitz with the router at the moment, but it looks like this when that happens (the menu is collapsed to a width of `0px` on the left):
![screen shot 2018-07-26 at 5 20 43 pm](https://user-images.githubusercontent.com/3855493/43289625-87a568f0-90f9-11e8-8f5c-69c93fcf85f2.png)

> If there was a way to manually disable the switch to vertical menu when the inline menu is collapse, I believe it would solve the issue.
## What does the proposed API look like?
Maybe a directive called `disableVerticalMenu`, or a separate `nzMode` specifically when the menu is collapsed, such as `nzCollapsedMode` .  This is also being done in version 0.7, but I have tested in the latest stable version and seems to act the same.

**Comment by KevinStirling** [comment]
So I guess this functionality is desired then? Or is there a possibility of this working differently?

**Comment by KevinStirling** [comment]
Is there any plan for this functionality or should i continue trying to fix this myself?

**Comment by KevinStirling** [comment]
is this a bug

**Comment by vthinkxie** [comment]
@KevinStirling sorry for the late response, can you provide an valid repro link? 
it is hard to get the point without repro link, thanks for reporting.

**Comment by KevinStirling** [comment]
Here's the repro link : https://stackblitz.com/edit/angular-enh6va

In order to reproduce, shrink screen horizontally, or use the browsers developer tools to test out a mobile phone small enough to make the sidenav minimize completely. (in this case there is a maximized mode, a half sized mode, and a completely minimized mode).

Use the nav button in the top left to open the drawer, and click on the nav2 drop down. Then click the nav2 button so the router resolves the `nav2` component.

Then, close the sidenav, and click on the button in the header that says "overview" to trigger the redirect to the overview component. The floating menu will appear like in the screenshot above.


This is a result of subscribing to the router events to control which drawer in the nav is open. Even though I forced the mode of the sidenav to be vertical, it automatically switches to the horizontal mode when minimized.

The need for this use case arose from the app I'm working on, where the nav automatically expands on mouseover anyway, so theres no need for me to have a horizontal menu mode. I left this out of my repro for simplicity's sake. Apologies for the weird project structure, this was kind of thrown together quickly.

**Comment by KevinStirling** [comment]
Thanks @vthinkxie !
