### ISSUE TITLE
nz-table表格控件性能比较差

### ISSUE THREAD

**Issue by defolly** [NG-ZORRO/ng-zorro-antd#1887]
## What problem does this feature solve?
nz-table 显示大数据时（300条记录 ，10列），性能比较差，全选/取消全选 页面卡顿严重
## What does the proposed API look like?
react 版本的 table 不存在此问题，全选 ，取消都比较流畅。 希望 zorro 能解决此问题

**Comment by vthinkxie** [comment]
请提供复现链接，否则issue将被直接关闭
