### ISSUE TITLE
nz-month-picker has error view  1,3,3,5,5,7,8,10,10,12,12

### ISSUE THREAD

**Issue by Picktarget** [NG-ZORRO/ng-zorro-antd#1899]
## Version
1.2.0
## Environment
angular 6.0 /windows10/ lastest chrome
## Reproduction link
[https://stackblitz.com/edit/angular-jqp6s2?file=src/main.ts](https://stackblitz.com/edit/angular-jqp6s2?file=src/main.ts)
## Steps to reproduce
just click the component
## What is expected?
correct view 1,2,3,4,5,6,7,8,9,10,11,12
## What is actually happening?
wrong view 1,3,3,5,5,7,8,10,10,12,12
## Other?
I just need a range picker that shows month only,In addition ,https://stackblitz.com/edit/angular-jqp6s2?file=src/main.ts is not my project,I can't open the  stackblitz for some reasons. just build a  simple nz-month-picker u will get it.

**Comment by wilsoncook** [comment]
![image](https://user-images.githubusercontent.com/1631659/43434051-abebdd1e-94ac-11e8-853e-b2b7fc7f83e4.png)
Mark with reproduction view (at every 31st)

**Comment by Picktarget** [comment]
well,can u provide a component likes nz-year-picker to make a year view?

**Comment by Picktarget** [comment]
excuse me,when could this patch merge into the main branch？

**Comment by wilsoncook** [comment]
@Picktarget Hi, the year-picker and this bugfix are about to release at later releases

**Comment by Picktarget** [comment]
@wilsoncook Thanks for what u & u'r team have done
