### ISSUE TITLE
set target to es6 in tsconfig.json lead to an error using nz-range-picker

### ISSUE THREAD

**Issue by 85204** [NG-ZORRO/ng-zorro-antd#1901]
## Version
1.2.0
## Environment
windows 10
## Steps to reproduce
set target to es6 in tsconfig.json and then use nz-range-picker in html
## What is expected?
work fine
## What is actually happening?
Cannot read property 'localeChange' of undefined
    at NzRangePickerComponent.ngOnInit (antd.js:13053)
## Other?
I test that it has the same error in target es6+ , does antd support babel to es6+ ?

**Comment by wenqi73** [comment]
@85204 It's not reproducible works fine on my machine, this issue will be closed.
