### ISSUE TITLE
"ng-zorro-antd": "^1.2.0" bug

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#1902]
when use ng-zorro-antd@1.2.0
———分割线———————————————————————————————————————
html: 
`<nz-input-group style="width: 300px;margin: 0.5px 0 0 16px;" nzSuffixIcon="anticon anticon-search">
    <input type="text" nz-input placeholder="输入名字搜索" [(ngModel)]="searchName" (keydown.enter)="getAccountData()">
  </nz-input-group>`
———分割线———————————————————————————————————————
bug： 
ng serve 正常 
ng build --prod --base-href --output-hashing=bundles  样式有问题。
———分割线———————————————————————————————————————
use ng-zorro-antd@1.1.1 一切正常

**Comment by vthinkxie** [comment]
不会存在serve 正常build之后出错的情况，node_modules重装一下
