### ISSUE TITLE
Modal can support drag and drop？(弹窗是否支持拖拽)

### ISSUE THREAD

**Issue by luohong123** [NG-ZORRO/ng-zorro-antd#1904]
## What problem does this feature solve?
Modal support drag and drop，When you fill in the contents of the pop-up window, you want to see the contents of the window cover, hoping to drag the window to see the contents below the window.（弹窗能支持拖拽，在弹窗内填写内容时，想看弹窗遮住的内容，希望能拖拽弹窗看到弹窗下面遮住的内容）
## What does the proposed API look like?
online（有在线的例子）

**Comment by vthinkxie** [comment]
有些特性为什么不会被支持#
ng-zorro-antd 是 Angular 版本 Ant Design 的实现，这意味着只有 Ant Design 支持的交互、功能 才会被 ng-zorro-antd 实现。

**Comment by wendzhue** [comment]
Ref https://github.com/ant-design/ant-design/issues/3012#issuecomment-410632148
