### ISSUE TITLE
DatePicker 组件在edge浏览器中选择好日期之后需要点击两次ok按钮才会把弹出的日期选择组件关闭

### ISSUE THREAD

**Issue by fanzhengshao** [NG-ZORRO/ng-zorro-antd#1908]
## Version
1.2.0
## Environment
windows10
## Reproduction link
[http://ng.ant.design/components/date-picker/zh](http://ng.ant.design/components/date-picker/zh)
## Steps to reproduce
使用edge浏览器打开官方文档 http://ng.ant.design/components/date-picker/zh 里面的第一个例子。选择好时间之后需要点击两次确定按钮才会关闭弹出的日期选择组件
## What is expected?
在edge浏览器中选择好时间之后只需要点击一次确定按钮就能关闭弹出的日期选择组件
## What is actually happening?
在edge浏览器中选择好时间之后需要点击两次次确定按钮才能关闭弹出的日期选择组件

**Comment by smile2014** [comment]
与ag-grid集成，点击下一个月或下一年，直接就关闭了当前日期面板

import { Component, ViewChild } from '@angular/core';
import {ICellEditorAngularComp} from "ag-grid-angular";
import { dateFormat } from '../../../utils/utils';
import { NzDatePickerComponent  } from 'ng-zorro-antd';

//[(ngModel)]="inputValue"
@Component({
    selector: 'apes-cell-date',
    template: `
      <nz-date-picker #picker [(ngModel)]="inputValue" (keydown)="onKeyDown($event)"   (ngModelChange) = "onChange($event)"></nz-date-picker>
     `,
    styles: []
})
export class EditorDateComponent implements ICellEditorAngularComp {
    inputValue: any;
    params: any;
    ctx: any;
    formatType: string = 'yyyy-MM-dd';

    @ViewChild('picker', {read: NzDatePickerComponent}) picker: NzDatePickerComponent;

    constructor() {
    }

    agInit(params: any): void {
        this.params = params;
        // this.api = params.api;
        // this.downFormatter = params.downFormatter;
        // this.valueFormatter = params.valueFormatter;
        console.log(params);
        this.inputValue = params.value;
        this.ctx = params.context;

    }

    ngAfterViewInit() {
      //this.picker.apesOpen = true;
    }
    isPopup(): boolean {
        return true;
    }
  onClick(param){
    this.inputValue = dateFormat(this.formatType, new Date(param));
    this.params.value = this.inputValue;
  }

    getValue(): any {
        let result;
        if (!this.inputValue) {
            result = '';
            this.params.value = '';
        } else {
            result = this.inputValue;
            this.params.value = this.inputValue;
        }
        return result;
    }

  onKeyDown(event): void {
    let key = event.which || event.keyCode;
    if (key === 38 || key === 40) {
      this.preventDefaultAndPropagation(event);
    }else if (key == 13 || key == 9) { // enter
      // perform some validation on enter - in this example we assume all inputs are mandatory
      // in a proper application you'd probably want to inform the user that an input is blank'
      /**/
      this.inputValue = event.target.value
      this.params.value = event.target.value;
    }
  }

  onChange(param){
    this.inputValue = dateFormat(this.formatType, new Date(param));
    this.params.value = this.inputValue;
  }
  private preventDefaultAndPropagation(event) {
    event.preventDefault();
    event.stopPropagation();
  }
}

**Comment by smile2014** [comment]
https://stackblitz.com/edit/angular-grid-zorro

**Comment by wilsoncook** [comment]
@smile2014 Pls open a new issue to start a discussion, thanks.

**Comment by smile2014** [comment]
换个变通方式规避了这个问题

**Comment by wenqi73** [comment]
9.3.0 已不存在该问题
