### ISSUE TITLE
[nz-select] Allow nz-select open with spacebar when focused, like the default HTML select

### ISSUE THREAD

**Issue by DouglasOGarrido** [NG-ZORRO/ng-zorro-antd#1909]
## What problem does this feature solve?
The select component doesn't open when press spacebar key.
## What does the proposed API look like?
Allow nz-select open with spacebar when focused, like the default HTML select. 

Example: [W3Schools Select Tag](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select)

**Comment by Devvarat** [comment]
This creates a new issue with the nz-select with search. Now you can not type space while writing search text in select. 
nz-zorro behaiviour: https://ng.ant.design/components/select/en#components-select-demo-select-users
ant-design(react): https://ant.design/components/select/#components-select-demo-select-users

**Comment by wendzhue** [comment]
Duplicates #2201.
