### ISSUE TITLE
@angular/cdk新版本发布导致升级版本 "ng-zorro-antd": "^0.5.0-rc.3",报错

### ISSUE THREAD

**Issue by htmlcss23** [NG-ZORRO/ng-zorro-antd#191]
ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-ref.d.ts (9,10): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'PortalHost'.

ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-ref.d.ts (9,22): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'Portal'.

ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-state.d.ts (9,10): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'Direction'.

ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/overlay/scroll/scroll-dispatcher.d.ts (9,10): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'Platform'.

ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-directives.d.ts (12,10): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'Directionality'.

ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-directives.d.ts (12,26): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'Direction'.

ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/floater/floater-props.d.ts (3,10): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'ComponentType'.

ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/floater/floater-props.d.ts (3,25): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'Directionality'.

ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/floater/floater.d.ts (3,10): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'Direction'.

ERROR in D:/spark/learner-web/node_modules/ng-zorro-antd/src/release/core/floater/floater.service.d.ts (2,10): Module '"D:/spark/learner-web/node_modules/@angular/cdk/cdk"' has no exported member 'ComponentType'.

**Comment by vthinkxie** [comment]
it seems that you have not installed @angular/cdk, try to rm node_modules and install again.

**Comment by vthinkxie** [comment]
@htmlcss23 @angualr/cdk just release a new version  `2.0.0-beta.10`, but it is not compatible `2.0.0-beta.8` please install `@angular/cdk@2.0.0-beta.8` manually.

**Comment by htmlcss23** [comment]
如何手动安装呢。

**Comment by vthinkxie** [comment]
just run `npm install @angular/cdk@2.0.0-beta.8`

**Comment by Liangdi** [comment]
@htmlcss23  你需要  cd node_modules/ng-zorro-antd    然后再执行 cnpm install @angular/cdk@2.0.0-beta.8

**Comment by viggoChen** [comment]
我执行了`cd node_modules/ng-zorro-antd` 再执行`cnpm install @angular/cdk@2.0.0-beta.8`
出现了这样的错误:
`ERROR in Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supp
orted. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NZ_ROOT_CONFIG in
 D:/project/node_modules/ng-zorro-antd/src/release/root/nz-root-config.d.ts, resolving symbol NgZorroAntdModule.forRoo
t in D:/project/node_modules/ng-zorro-antd/src/release/ng-zorro-antd.module.d.ts, resolving symbol AppModule in D:/project/src/app/app.module.ts, resolving symbol AppModule in D:/project/src/app/app.module.ts`

**Comment by vthinkxie** [comment]
@viggoChen 
Just run `npm install @angular/cdk@2.0.0-beta.8` in your directory and everything will be ok, there is no need to go to `node_modules`.

**Comment by litttlefisher** [comment]
PS D:\Workspaces\LittleFisherBlog> npm install @angular/cdk@2.0.0-beta.8
npm WARN update-linked node_modules\@angular\cdk needs updating to 2.0.0-beta.8 from 2.0.0-beta.10 but we can't, as it
's a symlink
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_animati
ons@4.3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_cdk@2.0
.0-beta.10@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular-devkit_
build-optimizer@0.0.13@@angular-devkit\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_cli@1.3
.0@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_common@
4.3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_compile
r-cli@4.3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_compile
r@4.3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_http@4.
3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_forms@4
.3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_languag
e-service@4.3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_core@4.
3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_platfor
m-browser@4.3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_router@
4.3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_tsc-wra
pped@4.3.6@@angular\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@ngtools_webpack
@1.6.0@@ngtools\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@types_jasmine@2
.5.54@@types\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@ngtools_json-sc
hema@1.1.0@@ngtools\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@types_jasminewd
2@2.0.3@@types\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@types_q@0.0.32@
@types\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@types_node@6.0.
88@@types\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@types_selenium-
webdriver@2.53.42@@types\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\Workspaces\LittleFisherBlog\node_modules\_@angular_platfor
m-browser-dynamic@4.3.6@@angular\package.json'


I do not know how to fix it.

**Comment by vthinkxie** [comment]
@litttlefisher 
npm install @angular/cdk@2.0.0-beta.8 not npm install @2.0.0-beta.8

**Comment by litttlefisher** [comment]
@vthinkxie sorry,it is beacause of markdown style. The bug can not be fixed.

**Comment by vthinkxie** [comment]
@litttlefisher try to remove all node_modules and reinstall

**Comment by litttlefisher** [comment]
@vthinkxie Tryed, but useless. And I try to change the package.json to input `"@angular/cdk": "2.0.0-beta.8"`, but useless either.

**Comment by vthinkxie** [comment]
@litttlefisher please paste your error message in correct format

**Comment by twocucao** [comment]
```json
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/cdk": "2.0.0-beta.8",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular-in-memory-web-api": "^0.3.2",
    "core-js": "^2.4.1",
    "ng-zorro-antd": "^0.5.0-rc.3",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
```

删除node_module 后 执行 yarn 完成之后 ng serve 报错如下:

```bash
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-ref.d.ts (9,10): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'PortalHost'.
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-ref.d.ts (9,22): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'Portal'.
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-state.d.ts (9,10): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'Direction'.
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/overlay/scroll/scroll-dispatcher.d.ts (9,10): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'Platform'.
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-directives.d.ts (12,10): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'Directionality'.
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/overlay/overlay-directives.d.ts (12,26): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'Direction'.
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/floater/floater-props.d.ts (3,10): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'ComponentType'.
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/floater/floater-props.d.ts (3,25): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'Directionality'.
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/floater/floater.d.ts (3,10): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'Direction'.
ERROR in mypath/node_modules/ng-zorro-antd/src/release/core/floater/floater.service.d.ts (2,10): Module '"mypath/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' has no exported member 'ComponentType'.
```

**Comment by vthinkxie** [comment]
@twocucao  try remove the directory `node_modules/ng-zorro-antd/node_modules`

**Comment by twocucao** [comment]
```bash
rm -rf node_modules/ng-zorro-antd/node_modules
```

It Works , Thx

**Comment by vthinkxie** [comment]
@litttlefisher  try remove this directory node_modules/ng-zorro-antd/node_modules

**Comment by litttlefisher** [comment]
@vthinkxie It works , Thx.
