### ISSUE TITLE
cannot load ng zorro components in unit test?

### ISSUE THREAD

**Issue by Leeway213** [NG-ZORRO/ng-zorro-antd#1915]
## Version
0.7.1
## Environment
windows & node.js v8.11.3
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-pkxcbg](https://stackblitz.com/edit/ng-zorro-antd-start-pkxcbg)
## Steps to reproduce
execute `ng test` to run unit test.
## What is expected?
test passed without error
## What is actually happening?
`expect(sortOptions.length).toBe(component.sorts.length);`
expect '0' to be 3.
## Other?
I tried to trigger click event of 'sortBtn', then queried 'li' elements with debugElement. They didn't exist as expected.
Even the style of button is original but not antd style. I think the NgZorroAntdModule loaded with some errors?

**Comment by vthinkxie** [comment]
plz check your test configuration and code, there is nothing special in test environment for any angular package or components.
