### ISSUE TITLE
Table Secondary Development

### ISSUE THREAD

**Issue by Charles953** [NG-ZORRO/ng-zorro-antd#1917]
### Version
1.2.0
###  #Environment
Window && node.js 8.11.2
### What is expected?
希望table模块中的组件不以selector为element-name的形式来绑定标签
### What is actually happening?
虽然现有的table组件不用像0.7.x版本之前使用指令的方式来绑定table中的子元素，但开发者想进行功能扩展（比如表头进行拖动改变列宽），因为**侵略性**太强，二次开发的table无法与ng-zorro的table共存（项目依赖ng-zorro）

**Comment by Charles953** [comment]
I hope u can answer my doubts.tks

**Comment by vthinkxie** [comment]
只需要给 th 增加 .nz-disable-th className就可以了，具体的操作可以参照 源代码
