### ISSUE TITLE
服务端渲染时报ReferenceError: document is not defined

### ISSUE THREAD

**Issue by iwe7** [NG-ZORRO/ng-zorro-antd#1918]
## Version
1.2.0
## Environment
mac
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ymjfnr?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-ymjfnr?file=src/app/app.component.ts)
## Steps to reproduce
```

```
## What is expected?
我想应该支持服务端渲染
## What is actually happening?
但是现实并不支持，希望可以更新下!

**Comment by vthinkxie** [comment]
duplicated #43
