### ISSUE TITLE
firefox 45 document issue

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#1919]
https://github.com/angular/angular-cli/issues/9340#event-1744781942

Here is my cli@6.0.0 workaround: (Adapted from @FDIM's solution)

add these two lines to package.json:
```
"uglify-es": "3.2.2",
"uglifyjs-webpack-plugin": "1.1.5"
```

run npm install on your project
manualy delete the following two folders from your project:
```
.\node_modules\@angular-devkit\build-angular\node_modules\uglify-es
.\node_modules\@angular-devkit\build-angular\node_modules\uglifyjs-webpack-plugin
```
ng build --prod now produces output that works on firefox 50 and older.

**Comment by solael** [comment]
another solution is add yarn resolutions to package.json.
"resolutions": {
    "uglify-es": "3.2.2",
    "uglifyjs-webpack-plugin": "1.1.5"
  }

**Comment by vthinkxie** [comment]
fixed in https://github.com/angular/angular-cli/issues/9340
