### ISSUE TITLE
nzShowQuickJumper,  the pagination changed but table is not change when input a page index number in quick jumper

### ISSUE THREAD

**Issue by sunnyleo2015** [NG-ZORRO/ng-zorro-antd#192]
## I'm submitting a...
<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

![qcyt 2znpe7f0_clkge7spo](https://user-images.githubusercontent.com/12390696/29854326-c3be1d18-8d77-11e7-89f2-1f0414568244.png)

## Expected behavior

when input a page index number, table should change to this page

## Minimal reproduction of the problem with instructions

use [nzShowQuickJumper] in nz-table
input number at quick jumper

**Comment by vthinkxie** [comment]
duplicated #171
