### ISSUE TITLE
nz-popover stype

### ISSUE THREAD

**Issue by leaughing** [NG-ZORRO/ng-zorro-antd#1929]
i user “nz-popover ” in my component ，but popover style  I have some problem，my code in  
`
<span class="action noticeButton"  nz-popover [(nzVisible)]="visible" nzTrigger="click" [nzContent]="contentTemplate" nzPlacement="bottomRight" nzOverlayClassName="popover>
    <nz-badge   [nzCount]="12"><i  class="icon anticon anticon-bell"></i></nz-badge>
</span>

`
`import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-antd-notice-icon',
  templateUrl: './antd-notice-icon.component.html',
  styleUrls: ['./antd-notice-icon.component.less']
})
export class AntdNoticeIconComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
`

css '.popover{ ..}' in './antd-notice-icon.component.less'

but “.popover ”  not work   ，  because  “.popover” render “.popover[_ngcontent-c10] {}”  but   "ant-popover html"  render  [_ngcontent-c14]

why?  and  how can i get a  alone css file for my this popover

**Comment by vthinkxie** [comment]
https://angular.io/guide/component-styles please read angular doc first.

**Comment by leaughing** [comment]
= @vthinkxie thank you
