### ISSUE TITLE
表头分组中使用 nzScroll  会出现表头和表格对不齐现象

### ISSUE THREAD

**Issue by git8534** [NG-ZORRO/ng-zorro-antd#1933]
## Version
1.3.0
## Environment
windows7
## Reproduction link
[https://angular-nfrnr6.stackblitz.io](https://angular-nfrnr6.stackblitz.io)
## Steps to reproduce
不使用 nzScroll  不会有该问题
案例中的 Company Name 列 可以看到 对不齐现象
## What is expected?
可以对齐
## What is actually happening?
无法对齐
案例中的 Company Name 列 可以看到 对不齐现象

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-nfrnr6-w24uzu?file=src/app/app.component.ts
nzScroll x 的值要大于所有的width之和

**Comment by git8534** [comment]
这样 nzWidthConfig 中 不能使用 null，需要使用固定宽度

**Comment by git8534** [comment]
或者 nzScroll x 的值 不能是百分比
