### ISSUE TITLE
Avatar Zoom/Magnifier Image

### ISSUE THREAD

**Issue by oluevano** [NG-ZORRO/ng-zorro-antd#1935]
## What problem does this feature solve?
Currently in the nz-avatar component i can show a image of profile people or products in a nz-table I would like to can zoom o magnify this image when mouse over or click on the nz-avatar component.

I think this feature is interesant when the table component is used to show product catalogs.

Can you help me to build this feature!

Thank you so much!

## What does the proposed API look like?
I propose add new input parameter in the nz-avatar component to use this feature.

 <nz-avatar  nzSrc="[uriImage]" [magnify]="true" [magnify-event]="'hover/click'"></nz-avatar>.

**Comment by vthinkxie** [comment]
we will only support the feature which designed by ant design
you can create feature request to https://github.com/ant-design/ant-design first
