### ISSUE TITLE
Plans for Server side support

### ISSUE THREAD

**Issue by mapsgeek** [NG-ZORRO/ng-zorro-antd#1936]
## What problem does this feature solve?
there was a tracking issue for adding server side and it was supposed to be in v 1.0 , then you said that it will come in later version , now it's v1.3 and you removed the milestone all together, do you have an exact plan for this so we can decide whether to wait or move on with other solutions ?

**Comment by vthinkxie** [comment]
ref https://github.com/NG-ZORRO/ng-zorro-antd/issues/2025
