### ISSUE TITLE
"export 'ɵhz' (imported as 'i1') was not found in 'ng-zorro-antd'

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#1938]
WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
110:55-61 "export 'ɵhz' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
110:684-690 "export 'ɵhz' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
110:692-698 "export 'ɵhz' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
112:657-663 "export 'ɵij' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
112:665-671 "export 'ɵij' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
128:1311-1317 "export 'ɵjm' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
128:1319-1325 "export 'ɵjm' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
128:55-61 "export 'ɵjm' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
20:1241-1247 "export 'ɵij' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
20:1249-1255 "export 'ɵij' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
20:3952-3958 "export 'ɵhz' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
20:3960-3966 "export 'ɵhz' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
20:4321-4327 "export 'ɵjm' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
20:4329-4335 "export 'ɵjm' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_trust/cinema_trust.module.ngfactory.js
27:1367-1373 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_trust/cinema_trust.module.ngfactory.js
27:1375-1381 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_trust/cinema_trust.module.ngfactory.js
27:4159-4165 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_trust/cinema_trust.module.ngfactory.js
27:4167-4173 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_trust/cinema_trust.module.ngfactory.js
27:4528-4534 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_trust/cinema_trust.module.ngfactory.js
27:4536-4542 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/chain_mng/chain_mng.module.ngfactory.js
28:1361-1367 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_mng/cinema_mng.module.ngfactory.js
28:1363-1369 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_trust/special_trust.module.ngfactory.js
28:1369-1375 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/chain_mng/chain_mng.module.ngfactory.js
28:1369-1375 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_chain/special_chain.module.ngfactory.js
28:1369-1375 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_mng/cinema_mng.module.ngfactory.js
28:1371-1377 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_cinema/special_cinema.module.ngfactory.js
28:1371-1377 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_chain/special_chain.module.ngfactory.js
28:1377-1383 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_trust/special_trust.module.ngfactory.js
28:1377-1383 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_cinema/special_cinema.module.ngfactory.js
28:1379-1385 "export 'ɵij' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/chain_mng/chain_mng.module.ngfactory.js
28:4153-4159 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_mng/cinema_mng.module.ngfactory.js
28:4155-4161 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/chain_mng/chain_mng.module.ngfactory.js
28:4161-4167 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_chain/special_chain.module.ngfactory.js
28:4161-4167 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_trust/special_trust.module.ngfactory.js
28:4161-4167 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_mng/cinema_mng.module.ngfactory.js
28:4163-4169 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_cinema/special_cinema.module.ngfactory.js
28:4163-4169 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_trust/special_trust.module.ngfactory.js
28:4169-4175 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_chain/special_chain.module.ngfactory.js
28:4169-4175 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_cinema/special_cinema.module.ngfactory.js
28:4171-4177 "export 'ɵhz' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/chain_mng/chain_mng.module.ngfactory.js
28:4522-4528 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_mng/cinema_mng.module.ngfactory.js
28:4524-4530 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/chain_mng/chain_mng.module.ngfactory.js
28:4530-4536 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_chain/special_chain.module.ngfactory.js
28:4530-4536 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_trust/special_trust.module.ngfactory.js
28:4530-4536 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_cinema/special_cinema.module.ngfactory.js
28:4532-4538 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/cinema_mng/cinema_mng.module.ngfactory.js
28:4532-4538 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_chain/special_chain.module.ngfactory.js
28:4538-4544 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_trust/special_trust.module.ngfactory.js
28:4538-4544 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./src/app/routes/special_cinema/special_cinema.module.ngfactory.js
28:4540-4546 "export 'ɵjm' (imported as 'i8') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
4762:120-126 "export 'ɵjn' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
4762:159-165 "export 'ɵjn' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
4764:73-79 "export 'ɵjn' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./src/app/app.module.ngfactory.js
52:11905-11912 "export 'ɵhz' (imported as 'i22') was not found in 'ng-zorro-antd'

WARNING in ./src/app/app.module.ngfactory.js
52:11914-11921 "export 'ɵhz' (imported as 'i22') was not found in 'ng-zorro-antd'

WARNING in ./src/app/app.module.ngfactory.js
52:12292-12299 "export 'ɵjm' (imported as 'i22') was not found in 'ng-zorro-antd'

WARNING in ./src/app/app.module.ngfactory.js
52:12301-12308 "export 'ɵjm' (imported as 'i22') was not found in 'ng-zorro-antd'

WARNING in ./src/app/app.module.ngfactory.js
52:4618-4625 "export 'ɵij' (imported as 'i22') was not found in 'ng-zorro-antd'

WARNING in ./src/app/app.module.ngfactory.js
52:4627-4634 "export 'ɵij' (imported as 'i22') was not found in 'ng-zorro-antd'

**Comment by wendzhue** [comment]
@ruipeng-wang This is usually bacause node_modules is messed up. Have you tried `rm -rf node_modules` and reinstall all dependencies?

**Comment by lanzhihui** [comment]
I resolve the problem with  rm -rf node_modules and reinstall all dependencies
