### ISSUE TITLE
update version 1.2.0 to version1.3.0

### ISSUE THREAD

**Issue by Picktarget** [NG-ZORRO/ng-zorro-antd#1939]
## Version
1.3.0
## Environment
chrome latest
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-m1gmr6](https://stackblitz.com/edit/ng-zorro-antd-start-m1gmr6)
## Steps to reproduce
run ng build --prod 
## What is expected?
package correctly
## What is actually happening?
there're many warnings in console
## Other?
there is no review scene。。。。in  stackblitz 

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
110:55-61 "export 'ɵhz' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
110:684-690 "export 'ɵhz' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
110:692-698 "export 'ɵhz' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
112:657-663 "export 'ɵij' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
112:665-671 "export 'ɵij' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js
128:1311-1317 "export 'ɵjm' (imported as 'i1') was not found in 'ng-zorro-antd'

WARNING in ./node_modules/ng-zorro-antd/antd.ngfactory.js

**Comment by vthinkxie** [comment]
reinstall your node_modules.

**Comment by Picktarget** [comment]
after excuting  npm update ，I excuted npm i for installing node_modules,it still told me these

**Comment by vthinkxie** [comment]
please remove all your node_modules, and reinstall, it is obvious that your package is wrong.
