### ISSUE TITLE
Carousel on desktop can't slide images

### ISSUE THREAD

**Issue by ohnow** [NG-ZORRO/ng-zorro-antd#1947]
## Version
1.3.0
## Environment
ref to link
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-eyz816](https://stackblitz.com/edit/ng-zorro-antd-start-eyz816)
## Steps to reproduce
ref to link
## What is expected?
slide ok
## What is actually happening?
there have an issue already found by wendzhue. it's cause by <img> default action, workaround is add (mousedown)="$event.preventDefault()"

**Comment by wendzhue** [comment]
@ohnow Are you interested in fixing this issue?

**Comment by wendzhue** [comment]
A hint for fixing this issue:

When user is dragging a `<img>` element, it would trigger browsers' default behavior to create a handler, which should be prevented.
