### ISSUE TITLE
nz-tooltip doesn't work in Chrome when the button is disabled

### ISSUE THREAD

**Issue by AhmedBoustani** [NG-ZORRO/ng-zorro-antd#1953]
## Version
1.2.0
## Environment
Chrome Version 68.0.3440.84 (Official Build) (64-bit) on Ubuntu 18.04
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-2dvuvq?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-2dvuvq?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
Create a simple nz-tooltip on a disabled button. when the button is enabled, the tooltip works, but when it's disabled, it doesn't. It works fine on Firefox Quantum 61.0.1 (64-bit), but not in Chrome.
## What is expected?
The tooltip to show even if the button is disabled
## What is actually happening?
when the button is enabled, the tooltip works, but when it's disabled

**Comment by vthinkxie** [comment]
work as design, the disabled button will not emit any hover or mouse over event.
