### ISSUE TITLE
select doesn't work when reopen on multiple select search mode 

### ISSUE THREAD

**Issue by oluevano** [NG-ZORRO/ng-zorro-antd#1954]
## Version
1.3.0
## Environment
angular 6 and 1.3.0 ng-zorro API
## Reproduction link
[https://stackblitz.com/edit/ant-dropdown-select-angular?file=app%2Fapp.component.ts](https://stackblitz.com/edit/ant-dropdown-select-angular?file=app%2Fapp.component.ts)
## Steps to reproduce
Create a nz-select on multiple select mode into a nz-doprwon as a custom filter table, then select one option and close then the options selected doesn't show.

## What is expected?
When reopen the select in the nz-dropdown as a custom filter table, the options selected shown in the select box
## What is actually happening?
When re-open select, the selected options in the fist time doesn't show in the select box.

**Comment by vthinkxie** [comment]
it is the animation bug of angular, we have submit it to angular.
https://github.com/angular/angular/issues/24041

**Comment by vthinkxie** [comment]
plz track #1455 
close now

**Comment by vthinkxie** [comment]
ref https://github.com/angular/angular/issues/24041
