### ISSUE TITLE
table filter size

### ISSUE THREAD

**Issue by oluevano** [NG-ZORRO/ng-zorro-antd#1955]
## Version
1.3.0
## Environment
angular 6 and 1.3.0 ng-zorro API
## Reproduction link
[https://stackblitz.com/edit/ant-dropdown-select-angular-3vmhxz](https://stackblitz.com/edit/ant-dropdown-select-angular-3vmhxz)
## Steps to reproduce
Create a table with filters on the header and set a array filter with many records, then click in the filter header and when show the filter box, the box is very large and not is visible the button filters to accept or cancel
## What is expected?
apply css rule to limit the height of the filter box on table header

my propouse:

 .ng-tns-c9-133 ant-table-filter-dropdown >
.ant-dropdown-menu .ant-menu-dropdown-vertical .ant-dropdown-menu-root .ant-dropdown-menu-light
{
    max-height:300px!important;
    overflow-y:auto!important;
}
## What is actually happening?
the list of filter header is very large

**Comment by wendzhue** [comment]
@oluevano Thanks for your feedback. FYI, our css files are synced from [Ant Design](https://github.com/ant-design/ant-design), so probably you should open an issue there at the first place. And certainly it's a bad idea to use `!important` in a UI framework. So we won't fix this for now.
