### ISSUE TITLE
[nz-timeline-item] Custom color on circle's

### ISSUE THREAD

**Issue by DouglasOGarrido** [NG-ZORRO/ng-zorro-antd#1956]
## What problem does this feature solve?
In the DOC's [nz-timeline-item](https://ng.ant.design/components/timeline/en#nz-timeline-item), the description says: "Set the circle's color to blue, red, green or other custom colors", but what "custom colors"? I tried hex color, named color and none of this worked.
## What does the proposed API look like?
That property "nzColor" should accept any type of color, e.g.: '#ced12e', 'rgb(255, 255, 255)', 'rgba(255, 255, 255, .65)', 'gray'.. etc. And, instead of using "blue, red or green" to default value, use "primary or default, error, success and warning".

**Comment by wendzhue** [comment]
@DouglasOGarrido Thank you for your feedback. We will fix that soon. As for using 'primary' instead of 'blue', could you please open an issue on ant design first? See:  https://ant.design/components/timeline-cn/#components-timeline-demo-color

**Comment by DouglasOGarrido** [comment]
Hi @wendzhue. Tks for your feedback too and tks for the fix. I will open an issue on ant design.
