### ISSUE TITLE
Dynamic theme capability

### ISSUE THREAD

**Issue by Supamiu** [NG-ZORRO/ng-zorro-antd#1957]
## What problem does this feature solve?
Following https://github.com/ant-design/ant-design/issues/9366 (which has a solution on react aparently).

It would be nice to have such flexibility on angular implementation too, as I'm not a less expert I didn't find a way to do that without ejecting webpack (which is impossible with current angular-cli version).
## What does the proposed API look like?
It would simply provide a way to call less to modify variables and have it loaded properly on runtime.

**Comment by vthinkxie** [comment]
we already support it, you can check the bottom right of our site.
you can use less.js to change theme if you want.

**Comment by Supamiu** [comment]
@vthinkxie I see the implementation for the docs site and if feels quite hard to maintain, especially because you seem to import the whole ant style in this file because it needs to be regenerated in the browser, but then I can't make sure I'm up to date in this file with the latest ant design changes.

**Comment by vthinkxie** [comment]
As you see, it is the only way to dynamic change style in runtime without eject angular-cli to webpack.

**Comment by Supamiu** [comment]
Yeah that was my initial guess, but I thought maybe I was missing something, thanks for the details.

N.B: do you have a script or something to generate color.less based on current version of the theme? it seems like I don't have the same theme with the same colors if I'm using this file instead of the classic theme system.

**Comment by vthinkxie** [comment]
@Supamiu you can check `antd-theme-generator` package in npm
