### ISSUE TITLE
Default Sort on Table

### ISSUE THREAD

**Issue by oluevano** [NG-ZORRO/ng-zorro-antd#1958]
## What problem does this feature solve?
Set deafult sorts on table and show values
## What does the proposed API look like?
Add on table header

    <th nzShowSort nzSortKey="Inventory" nzSortDirection="[asc/desc]" >ColumnaName</th>

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/table/en#components-table-demo-custom-filter-panel 
we already support it, you can check it here.

**Comment by MassimilianoOreto** [comment]
In the example provided ther's no reference to SORTING

**Comment by adaczo** [comment]
You can do
`<th nzShowSort nzSortKey="your_sort_key" nzSort="ascend">
           ...
          </th>`

the available values are `'ascend' | 'descend' | null;`
