### ISSUE TITLE
nz-input 在 form 里时 [disabled] 不生效

### ISSUE THREAD

**Issue by zlhgo** [NG-ZORRO/ng-zorro-antd#1960]
## Version
1.3.0
## Environment
linux chrome
## Reproduction link
[https://stackblitz.com/edit/angular-myik5g](https://stackblitz.com/edit/angular-myik5g)
## Steps to reproduce
请看示例
## What is expected?
能正确添加 .ant-input-disabled 
## What is actually happening?
没有添加 .ant-input-disabled

**Comment by vthinkxie** [comment]
请打开console仔细看报错
