### ISSUE TITLE
在响应式表单中使用自定义验证无法正确显示错误样式

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#197]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

当自定义验证错误时，不能正确显示错误样式
![tim 20170831102907](https://user-images.githubusercontent.com/9586655/29903620-6485766e-8e37-11e7-952a-5a7b75671d00.png)

因为nz-form-control只支持angular内置验证错误时显示
![tim 20170831103217](https://user-images.githubusercontent.com/9586655/29903714-d1ff7564-8e37-11e7-97f1-964c4a4a1fef.png)

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
please ensure your validator follow the correct format
```typescript
  emailValidator = (control: FormControl): { [s: string]: boolean } => {
    const EMAIL_REGEXP = /^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i;
    if (!control.value) {
      return { required: true }
    } else if (!EMAIL_REGEXP.test(control.value)) {
      return { error: true, email: true };
    }
  };
```

**Comment by wanghaolu** [comment]
这是我的验证代码

```javascript
import { ValidatorFn, AbstractControl } from "@angular/forms";

export function identityNoValidator(): ValidatorFn {
  return (control: AbstractControl): { [key: string]: any } => {
    let reg = /^\d{17}[0-9xX]{1}$/;
    if (!reg.test(control.value)) {
      return { 'identityNo': '身份证号格式不合法' };
    }
    let divisor = [7, 9, 10, 5, 8, 4, 2, 1, 6, 3, 7, 9, 10, 5, 8, 4, 2];
    let sum = 0;
    for (let i = 0; i < 17; i++) {
      sum += Number.parseInt(control.value[i]) * divisor[i];
    }

    let validCode = ['1', '0', 'X', '9', '8', '7', '6', '5', '4', '3', '2'];
    return validCode[sum % 11].toUpperCase() !== control.value[17] ? { 'identityNo': '身份证号错误' } : null;
  }
}
```

**Comment by vthinkxie** [comment]
@wanghaolu please `return { error: true}`

**Comment by wanghaolu** [comment]
@vthinkxie 加了error后可以了，谢谢 
```javascript
return { 'error': true, 'identityNo': '身份证号格式不合法' };

**Comment by vthinkxie** [comment]
@wanghaolu thanks for your feedback.
