### ISSUE TITLE
NzProgressComponent - Add an input for displayed text (separate percent input from label input)

### ISSUE THREAD

**Issue by Simon-Bru** [NG-ZORRO/ng-zorro-antd#1971]
## What problem does this feature solve?
Using "dashboard" progress, I would need to display a computed percentage from a temperature and the original input as label.
The problem: I have a very low temperature and want to display it using the dashboard progress, but the value is so low the progress is always almost empty. To fix that issue, I calculate a percentage from that temperature using a simple algorithm and the progress displays perfectly. However, the displayed text below is the computed percentage but it should be the temperature.

As a dashboard component, we should be able to display any data in all units. But it only allows to display a percentage.
## What does the proposed API look like?
You could achieve this by adding a "label" input in the component. Actually, the best would be to change nzFormat type from a lambda to a string. It adds control over the label in the calling component. It would break things for actual users, but they would just need to change the nzFormat input in the template and add the parameter. 
An additional input wouldn't break things for actual users, it would complexify the component's API BUT I think it would simplify the component's logic.

### Additional input usage: 
```
    <nz-progress [nzPercent]="getTemperaturePercent(state.temperature)"
        [nzFormat]="tempFormat"
        [label]="state.temperature  | number:'0.0-2'"
        nzType="dashboard"
        nzWidth="65">
```

### NzFormat change usage
```
    <nz-progress [nzPercent]="getTemperaturePercent(state.temperature)"
        [nzFormat]="tempFormat(state.temperature)"
        nzType="dashboard"
        nzWidth="65">
```

**Comment by wendzhue** [comment]
@Simon-Bru Have you tried `[nzFormat]`? Is this what you need? https://stackblitz.com/edit/angular-thdovz?file=src%2Fapp%2Fapp.component.ts

**Comment by wendzhue** [comment]
I don't know what you mean. Are you trying to do this? https://stackblitz.com/edit/angular-thdovz?file=src%2Fapp%2Fapp.component.ts

Certainly we won't introduce breaking changes in 1.* versions.

**Comment by Simon-Bru** [comment]
Yeah kind of, but it didn't work in my case for 2 reasons:
First: It doesn't work on the "dashboard" progress element
Secondly, I understand the use case of that input, but I think it should adapt the jauge so it is filled when that successPercent is reached. 

I think this can be used but it doesn't fit my requirements. Here's my exact use case: I have a temperature between -10 and 10 and I have a range of 0 to 5 so I calculate a percentage out of the temperature according to the minimum and maximum of my range. That percentage makes the progress fills perfectly as I want but the wrong temperature is displayed then. I would just like to change that displayed text so I can represent my measures with the scale I wish.

Moreover, I think the nzFormat input isn't that convenient and could easily be replaced so it is executed in the caller's component at least. (eg: as a string and not a lambda). I understand about breaking changes, so I would suggest a new input as in my first solution.

Thank you for reading me. Let me know if it makes sense or not

Simon

**Comment by wendzhue** [comment]
Reopen for more discussions from others.

**Comment by wendzhue** [comment]
@Simon-Bru Thanks for your detailed explanation. I have just updated the demo. As I can tell, if you can calculate the percentage according to the temperature, of course you can do it backwards. Is this your case? If not, a reproduce link would be preferred.

**Comment by Simon-Bru** [comment]
Hi again !
Thank you very much your solution actually works for me, I tried to use a similar approach with nzFormat but i actually passed a component's function and not a lambda..... I just noticed it works with the syntax 
`formatter = (val) => '${this.temprature} *C'`
But not with this one:
`formatter(val) { return '${this.temprature} *C'} `

I'm sorry I should have tried harder I guess..
Anyway thanks a lot for the help !!

**Comment by wendzhue** [comment]
@Simon-Bru Yeah, this binding works differently in arrow functions.

**Comment by Simon-Bru** [comment]
It was a good opportunity to learn about the difference between closure and non closure functions ;)
