### ISSUE TITLE
自定义Tree组件实现文件树，点击图标展开文件夹，鼠标拖拽例子。在火狐不可用拖拽并且样式也有错误。

### ISSUE THREAD

**Issue by simplew11** [NG-ZORRO/ng-zorro-antd#1973]
## Version
1.3.0
## Environment
火狐浏览器
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-v3typu?embed=1&file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-v3typu?embed=1&file=src/app/app.component.ts)
## Steps to reproduce
1.用火狐浏览器查看http://ng.ant.design/components/tree/zh，中的最后一个例子。
自定义Tree组件实现文件树，点击图标展开文件夹，鼠标拖拽。右键自定义菜单。
2.火狐浏览器点击右键时候会发现css存在问题。
3.火狐浏览器点击结点无法进行结点的拖拽。

## What is expected?
Tree组件最后一个例子在火狐浏览器中没有兼容性问题，可以进行拖拽，并且css是正常的。
## What is actually happening?
在火狐浏览器中存在兼容性问题。

**Comment by wendzhue** [comment]
@simplew11 Thx for you feedback. This duplicates #1928, so would be closed.
