### ISSUE TITLE
Can you add a property  enableAnimation which  type is boolean  for tag component?

### ISSUE THREAD

**Issue by asself** [NG-ZORRO/ng-zorro-antd#1975]
## What problem does this feature solve?
The tag component will flash when its data is fetched by timer call api。I found this problem is caused by the use of Angular animation in the tag component.
## What does the proposed API look like?
like this:
<nz-tag *ngFor="let tag of Tags" nzEnableAnimation ="false">
      {{ tag }}
</nz-tag>

**Comment by vthinkxie** [comment]
please add trackByFn if the component flash.

**Comment by patricknazar** [comment]
@asself I've found a way to do this - `[@.disabled]="true"` on the element. `<nz-tag [@.disabled]="true">Tag</nz-tag>`
