### ISSUE TITLE
nz-table cannot align after setting nzScroll

### ISSUE THREAD

**Issue by Rockergmail** [NG-ZORRO/ng-zorro-antd#1976]
## Version
1.3.0
## Environment
chrome
## Reproduction link
[https://stackblitz.com/edit/angular-y75ijp](https://stackblitz.com/edit/angular-y75ijp)
## Steps to reproduce
1、do not set nzScroll.  Can align.
2、set nzScroll. Can NOT align.
## What is expected?
After setting nzScroll. Can align.
## What is actually happening?
After setting nzScroll. Can NOT align.

**Comment by vthinkxie** [comment]
you have to set nzScroll x property, which should larger than the sum of nzWidth.
