### ISSUE TITLE
树形table 删除children项 不会更新界面

### ISSUE THREAD

**Issue by tianxiaozi** [NG-ZORRO/ng-zorro-antd#1978]
## Version
1.3.0
## Environment
mac chrome
## Reproduction link
[https://stackblitz.com/edit/angular-bume4p-whnd2s?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-bume4p-whnd2s?file=src/app/app.component.ts)
## Steps to reproduce
删除子节点不会更新界面, 删除根节点才会更新界面
## What is expected?
解决它
## What is actually happening?
无法更新界面

**Comment by TeamMicLee** [comment]
删除子节点你需要做的也是更新 `this.data ` 的值。

**Comment by vthinkxie** [comment]
依据angular的设计，mutate一个对象angular是不会检测到变更的，无论如何都需要imutate data 而不是 mutate data
https://www.angular.cn/guide/lifecycle-hooks#onchanges
