### ISSUE TITLE
NzMessageService 打包发布后访问提示Cannot read property 'resolveComponentFactory' of undefined

### ISSUE THREAD

**Issue by Cyclone77** [NG-ZORRO/ng-zorro-antd#1980]
## Version
1.3.0
## Environment
angular 6 NG-ZORRO1.3
## Reproduction link
[https://ng-zorro-antd-start-vthgyr.stackblitz.io](https://ng-zorro-antd-start-vthgyr.stackblitz.io)
## Steps to reproduce
import { NzMessageService, NZ_MESSAGE_CONFIG } from 'ng-zorro-antd';
providers: [NzMessageService, { provide: NZ_MESSAGE_CONFIG, useValue: { nzDuration: 3000 }}]
constructor(
    private message: NzMessageService
  ) {}
this.message.create('success', `文章内容保存成功。`);
## What is expected?
提示弹框
## What is actually happening?
组件保存页面加载错误
## Other?
Cannot read property 'resolveComponentFactory' of undefined
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'resolveComponentFactory' of undefined
TypeError: Cannot read property 'resolveComponentFactory' of undefined

**Comment by vthinkxie** [comment]
node_modules全部删掉，重新安装，出现这种错误一般都是你本地package冲突

**Comment by Cyclone77** [comment]
试了一下还是一样的，angular cli 6 打包命令加ng build --prod 就是这个错误不加 --prod 没有问题 。
