### ISSUE TITLE
table在nzSize=small的时候bordered=false 时仍然有外边框

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#1982]
## Version
1.3.0
## Environment
angular 6.1.0
## Reproduction link
[https://stackblitz.com/edit/angular-limymn?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-limymn?file=src/app/app.component.ts)
## Steps to reproduce
设置nzSize=small，并且bordered=false
## What is expected?
table没有外边框
## What is actually happening?
table任然有外边框
## Other?
示例是官方demo的
https://ng.ant.design/components/table/zh#components-table-demo-dynamic-settings

**Comment by wendzhue** [comment]
@wanghaolu https://ant.design/components/table-cn/#components-table-demo-dynamic-settings Checkout Ang Design. This is a ByDesign.

**Comment by wendzhue** [comment]
Thanks anyway. 😄
