### ISSUE TITLE
nz-tree can not drag in firefox

### ISSUE THREAD

**Issue by Rockergmail** [NG-ZORRO/ng-zorro-antd#1984]
## Version
1.3.0
## Environment
firefox
## Reproduction link
[https://stackblitz.com/edit/ng-antd-nztree-drag-bug-firefox](https://stackblitz.com/edit/ng-antd-nztree-drag-bug-firefox)
## Steps to reproduce
drag the node
## What is expected?
can drap & drop
## What is actually happening?
can not drap

**Comment by wendzhue** [comment]
@Rockergmail Thx for opening this issue. It duplicates #1928.
