### ISSUE TITLE
tree 组件搜索时隐藏不相干的node

### ISSUE THREAD

**Issue by zlhgo** [NG-ZORRO/ng-zorro-antd#1986]
## What problem does this feature solve?
如果tree太大，搜索时只是高亮显示不方便查找想要搜索的node,直接隐藏不相干的node更好。望官方考虑，谢谢。
## What does the proposed API look like?
-

**Comment by wendzhue** [comment]
@zlhgo 有关于组件行为而非 API 设计的功能请求，请先[到 Ant Design 那边提 issue](https://new-issue.ant.design/)

**Comment by wendzhue** [comment]
@zlhgo 现在的搜索不会改变 tree 的数据结构，仅仅会把不含有搜索匹配的父节点收起
