### ISSUE TITLE
nz-select  nz-tree-select 输入框获取焦点时按回车键不能弹出下拉列表

### ISSUE THREAD

**Issue by zlhgo** [NG-ZORRO/ng-zorro-antd#1989]
## What problem does this feature solve?
之前 0.6.x版本  nz-select 输入框获取焦点时按回车键能弹出下拉列表
## What does the proposed API look like?
nz-select  nz-tree-select 输入框获取焦点时按回车键弹出下拉列表

**Comment by wendzhue** [comment]
Duplicates #1909.
