### ISSUE TITLE
Select seems only  support string 's `ngModel`, and will support the `enum` and `number` type?

### ISSUE THREAD

**Issue by startewho** [NG-ZORRO/ng-zorro-antd#1990]
## Version
1.3.0
## Environment
Win10 X64 Node LTS
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-enum-select](https://stackblitz.com/edit/ng-zorro-antd-enum-select)
## Steps to reproduce
Sometime we use the the `enum` type to regard the select.and in the ts language default ,the `enum` value is a number in fact.And i want to use the enum value to binding with the `ngModel` like 
```
[(ngModel)]="menu.menuType"
```
And in my example.it can not show the correct value in the first `Select`.And when I use a string value,it seems correct in the second `Select`
## What is expected?
The select can support the number value ,and also i found the select in multi select mode,it  also only support string .It would be nice if both single and multi mode can support the number value.
## What is actually happening?
Can binding the `ngModel` with the `number` and `enum` type.

**Comment by wendzhue** [comment]
This is not the way how HTML `<select></select>` tag works. Your proposal is unnatural for other developers to understand. You should write code to find the index of the `value` if you really need it.

**Comment by startewho** [comment]
by view the source code and i  binding a `compareWith` function like this:
```
 static compareOjects(o1:any,o2:any):boolean
    {
        let result=false;
        if (o1===o2) {
            result=true;
        }
        if (o1.toString()===o2.toString()) {
            result=true;
        }
        return result;
    }
```
and i use it like this:
```
 <nz-select [nzDisabled]="editOrNew" [compareWith]="compareObject" name="status"  formControlName="status" placeholder="状态"  [(ngModel)]="record.status">
                      <nz-option nzValue="0" nzLabel="正常"></nz-option>
                      <nz-option nzValue="1" nzLabel="删除"></nz-option>
                      <nz-option nzValue="2" nzLabel="禁用"></nz-option>
                   
                    </nz-select>
```
it works as i expect.the only this is two many step to do this .
It 's usually we get the `dic` from the server.and also there some option we usually do not change in the soft life.and use the `enum` is suitable.
