### ISSUE TITLE
NzMessageService 打包(ng build --prod)发布后访问提示Cannot read property 'resolveComponentFactory' of undefined

### ISSUE THREAD

**Issue by Cyclone77** [NG-ZORRO/ng-zorro-antd#1995]
## Version
1.3.0
## Environment
"@angular/core": "^6.0.3", "@angular/cli": "~6.0.8", "ng-zorro-antd": "^1.3.0",
## Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)
## Steps to reproduce
ng build --prod打包后NzMessageService发布后访问提示Cannot read property 'resolveComponentFactory' of undefined
## What is expected?
打包测试
## What is actually happening?
把node_modules删除重新安装（npm），都试了一下，ng build 是没有问题，加上--prod打包后发布就提示：

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'resolveComponentFactory' of undefined
TypeError: Cannot read property 'resolveComponentFactory' of undefined

**Comment by hannahGu** [comment]
同问，从昨天折磨到今天，rm node_modules 后没有用，npm install 或者npm install 淘宝镜像问题都在😔

**Comment by vthinkxie** [comment]
@Cyclone77 @hannahGu 请确保你的cli版本与angular core 的版本对齐，resolveComponentFactory 是 angular 函数，报错只可能是包之间的版本没对齐

**Comment by Cyclone77** [comment]
@vthinkxie 可否发一个cli版本与angular core的版本（6.0+）可以不报错的版本？

**Comment by vthinkxie** [comment]
@Cyclone77 ng-zorro-antd 的版本是没有任何问题的，打包报错和 ng-zorro-antd 也没有关系，请检查你本地的 angular 版本和 cli 版本

**Comment by Cyclone77** [comment]
@vthinkxie 没搞懂 “请确保你的cli版本与angular core 的版本对齐”啥意思，我今天又试了一下，把angular core和cli都升级到最新：`"@angular/core": "^6.1.3",` ` "@angular/cli": "~6.1.4",`还是不行，难道这个版本没对齐？我整个项目就只用了ng-zorro-antd。

**Comment by vthinkxie** [comment]
@Cyclone77 https://ng.ant.design/docs/getting-started/zh 按照快速上手重新建一个新项目，然后用NzMessageService打包后也会有问题么？

**Comment by Cyclone77** [comment]
@vthinkxie 我并没有这么做，我直接用 cli  ng new <name>建立的项目， 然后安装的ng-zorro-antd。

**Comment by vthinkxie** [comment]
@Cyclone77 严格按照快速上手新建完项目，如果还是报错，你可以把你的项目上传到github上，然后给我地址

**Comment by Cyclone77** [comment]
@vthinkxie 好的我来试试。

**Comment by Cyclone77** [comment]
@vthinkxie 我试了快速上手并没有问题，我找到错误地方了。因为我在组件里这样做的：
``` js
@Component({
  selector: 'app-add',
  templateUrl: './add.component.html',
  styleUrls: ['./add.component.css'],
  providers: [NzMessageService]
})
```
取消`providers: [NzMessageService]`后打包就没有问题了。

**Comment by vthinkxie** [comment]
@Cyclone77 碰到问题提供可靠的重现链接是解决问题的最快速的方式，绝大部分的这种issue通过写重现链接都可以发现实际的问题。

**Comment by Cyclone77** [comment]
@vthinkxie 感谢，没做重现链接是因为，我这边打开过慢……

**Comment by vthinkxie** [comment]
@Cyclone77 自己动手重写一下也可以发现大部分问题的

**Comment by Cyclone77** [comment]
@vthinkxie 并非调试问题，而且打包加了参数才错误，就没去想其它问题；耽误你时间了，再次感到抱歉。

**Comment by Yestory** [comment]
@Cyclone77 @vthinkxie 两位好，我也遇到这个问题，当NzMessageService注册到module或component后使用aot打包会出现。也就是说NzMessageService不需要且不能注册到module或component是么？

**Comment by Cyclone77** [comment]
@Yestory 就我测试是这样的。

**Comment by hannahGu** [comment]
我也正常跑起来了，按照前面同学说的去掉app.module下providers里面的NzMessageService就好了，全局angular/cli卸载了也可以。

**Comment by dineshtomarevontech** [comment]
> @vthinkxie 我试了快速上手并没有问题，我找到错误地方了。因为我在组件里这样做的：
> 
> ```js
> @Component({
>   selector: 'app-add',
>   templateUrl: './add.component.html',
>   styleUrls: ['./add.component.css'],
>   providers: [NzMessageService]
> })
> ```
> 
> 取消`providers: [NzMessageService]`后打包（--prod）就没有问题了。

Works for me. Thanks.
