### ISSUE TITLE
nz-tree search support case ignore

### ISSUE THREAD

**Issue by Rockergmail** [NG-ZORRO/ng-zorro-antd#1996]
## What problem does this feature solve?
support case ignore when search the nz-tree
## What does the proposed API look like?
[caseIgnore]="true"

**Comment by Rockergmail** [comment]
@wendzhue yep, adding custom filter is better. The ```[caseIgnore]``` was my poor idea.

**Comment by wendzhue** [comment]
Hint for fixing this issue:

Custom filter feature is already supported in cascader component, which would be a reference.

**Comment by krokofant** [comment]
As of now I don't see a upstream issue and the upstream TreeSelect supports things like `value` for the TreeNode and `onSearch` method to customize the search. In fact this issue doesn't seem to exist in upstream anymore.

https://ant.design/components/tree-select/
https://ng.ant.design/components/tree-select/en

**Comment by krokofant** [comment]
@Rockergmail This issue isn't fixed. Don't close it.

**Comment by krokofant** [comment]
Related lines of code https://github.com/NG-ZORRO/ng-zorro-antd/blob/db1f43137ecd693aed6a5685f4386e602f653a41/components/core/tree/nz-tree-base.service.ts#L368
Ping @oestrogen
