### ISSUE TITLE
上传按钮能不能加入按钮组

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#1997]
## Version
1.3.0
## Environment
win10,chrome66,1.3.0
## Reproduction link
[https://stackblitz.com/edit/angular-vhv4po?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-vhv4po?file=src/app/app.component.ts)
## Steps to reproduce
上传按钮能不能加入按钮组
## What is expected?
上传按钮能加入按钮组
## What is actually happening?
上传按钮能不能加入按钮组

**Comment by TeamMicLee** [comment]
you can do it like this https://stackblitz.com/edit/angular-vhv4po-ddxqin?embed=1&file=src/app/app.component.ts

**Comment by vthinkxie** [comment]
@TeamMicLee is right! close now.
