### ISSUE TITLE
About Schedule or Plan

### ISSUE THREAD

**Issue by zhangwei8387** [NG-ZORRO/ng-zorro-antd#20]
I hope your team can formulate a plan about NG - ZORRO.
The plan can let us know when there will be a new component release or what is the break change.
  Thanks.
Best Regard,

**Comment by vthinkxie** [comment]
Hi @zhangwei8387 please check it here

https://ng.ant.design/#/changelog

* 每周末会进行日常 bugfix 更新。（如果有紧急的 bugfix，则任何时候都可发布）。
* 每月发布一个带有新特性的向下兼容的版本。
* 含有破坏性升级的版本更新不在发布周期内。
