### ISSUE TITLE
datePicker 如何支持yyyy-MM-dd hh:mm:ss类型

### ISSUE THREAD

**Issue by xingcun** [NG-ZORRO/ng-zorro-antd#2003]
## Version
1.3.0
## Environment
mac safari
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-fbpc91](https://stackblitz.com/edit/ng-zorro-antd-start-fbpc91)
## Steps to reproduce
当日期为yyyy-MM-dd hh:mm:ss格式时的字符串，即报错
## What is expected?
可以支持yyyy-MM-dd hh:mm:ss格式
## What is actually happening?
"Invalid Date"
## Other?
由于后台数据很多时间都是格式化的，可能是yyyy-MM-dd,同时也可能存在yyyy-MM-dd HH:mmss，希望可以自动适配

**Comment by vthinkxie** [comment]
ngModel只接收Date类型的数据，请使用第三方库，例如date-fns或者 moment 自行格式化成 Date之后再传入，组件不会自动适配
