### ISSUE TITLE
I used ant and ngxbootstrap, ant cover ngxbootstrap style, how to set ant first load, or custom ant style attributes, such as font size ....

### ISSUE THREAD

**Issue by Itherma** [NG-ZORRO/ng-zorro-antd#202]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
related https://github.com/ant-design/ant-design/issues/4331

**Comment by Bonelol** [comment]
This is blocking from using ng-zorro in my website.

**Comment by Bonelol** [comment]
Just for a temp solution, I had to remove the normalise css from NzRootStyleComponent and put it in a seperate file, so it can be loaded first and override by our global settings

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/0.7.x/docs/customize-theme/zh
