### ISSUE TITLE
NG-ZORRO Roadmap

### ISSUE THREAD

**Issue by wendellhu95** [NG-ZORRO/ng-zorro-antd#2025]
<p align="center">
⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️
</p>

<div align="center">
<h3>Road Map</h3>
</div>

<p align="center">
⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️
</p>

## Milestones

Please check these milestones for details

- [ ] MILESTONE: LATE 2019 #3667
- [x] MILESTONE: EARLY 2019 #2474
- [x] MILESTONE: LATE 2018 #2381 

We would like to hear any suggestions from the community. Welcome to join in this discussion. ☕️ Just comment in these issues above.

---

Team ng-zorro-antd with ❤️

---

> Note: suggestions accepted and implemented would be folded.

**Comment by cipchk** [comment]
建议把**配置优化**也当成核心，大部分情况下使用 ng-zorro-antd 的时候会统一一种风格，例如统一的 `nzSize`，但需要对所有组件都手动增加该属性。

倘若能对每一个模块有一个配置项，允许对组件默认值进行预设，这对于开发体验有很大帮助。

## 示例

假设整个应用都希望以大号字号呈现，以现有的形式需要对每个按钮编写：

```html
<button nz-button nzSize="large"></button>
```

然而，若我们遵守一种**配置优化**的风格，例如：

```ts
export function NzButtonConfig(): NzButtonConfig {
  return Object.assign(new NzButtonConfig (), <NzButtonConfig >{
    nzSize: 'large'
  });
}

providers: [
  { provide: NzButtonConfig, useFactory: fnNzButtonConfig() }
]
```

整个应用将保持一个最干净、最简洁的HTML模板。

**Comment by ram16g** [comment]
个人觉得和 Angular 版本对齐意义不大，官方那两个库也只能做到大版本对齐。

**Comment by yy7054wyq5** [comment]
* scm-submenu和scm-lastmenu的存在只是为了减少一个组件内的ngFor使用

```html
<!-- 一级菜单 -->
<nav *ngFor="let lv1Menu of menu">
  <div class="lv1 menu-item" [class.actived]="lv1Menu.expand" (click)="common.expandMenu($event,lv1Menu)">
    <i class="icon {{lv1Menu.icon}}"></i>
    <span>{{lv1Menu.label}}</span>
    <i class="fas arrow" [class.fa-angle-up]="lv1Menu.expand" [class.fa-angle-down]="!lv1Menu.expand"></i>
  </div>
  <div *ngIf="lv1Menu.expand">
    <!-- 二级菜单 -->
    <scm-submenu [data]="lv1Menu.children"></scm-submenu>
  </div>
</nav>
<!-- 二级菜单内部 -->
<ng-container *ngFor="let lv2Menu of data">
  <div class="menu-item lv2" [class.actived]="lv2Menu.expand" (click)="common.expandMenu($event,lv2Menu)">
    <i class="icon"></i>
    <span>{{lv2Menu.label}}</span>
    <i class="fas arrow" [class.fa-angle-up]="lv2Menu.expand" [class.fa-angle-down]="!lv2Menu.expand"></i>
  </div>
  <div *ngIf="lv2Menu.expand">
    <!-- 三级菜单 -->
    <scm-lastmenu [data]="lv2Menu.children"></scm-lastmenu>
  </div>
</ng-container>
<!-- 三级菜单内部 -->
<ng-container *ngFor="let lv3Menu of data">
  <div class="lv3 menu-item {{common.lv3ClassName(lv3Menu.url)}}" [class.actived]="lv3Menu.actived" (click)="jump(lv3Menu.url)">
    <i class="icon"></i>
    <span>{{lv3Menu.label}}</span>
  </div>
</ng-container>
```

**Comment by jeffrey-igaw** [comment]
Would you have a plan for applying [virtual scroll of cdk](https://material.angular.io/cdk/scrolling/overview) to select-box, auto-complete, fixed size table with support angular 7.0?

**Comment by wendzhue** [comment]
@jeffrey-igaw Yes we have a plan for that.

**Comment by krokofant** [comment]
Is Angular 7 support targeted for the 1.8 release? (Or 7.0 release of you align with their versioning)

**Comment by fabioemoutinho** [comment]
Please, angular support and update less

**Comment by Svetomechc** [comment]
Currently, I have the following behavior: **1.7.1** & **1.8.0** do not work with **Angular 7** (page just loads infinitely), whereas **1.6.0** works just fine. What should I do in order to fix this?

**Comment by vthinkxie** [comment]
@Svetomechc Angular 7.0 has not been fully tested, you can checkout to the `next` version and release your own package if you can't wait any longer.

**Comment by baiyunchen** [comment]
对于性能这块，个人建议，对于`select`这类下拉型的控件，对于他选项的部分，使用*ngIf来控制，而不是样式的隐藏与显示，这对于一个有大量下拉型控件的页面中来说，性能的提升是非常显著的。
如图，目前看起来cdk的实现是通过style来控制的
![image](https://user-images.githubusercontent.com/10071911/48075515-62d7b480-e21e-11e8-8064-571a94d09102.png)

**Comment by JadeTao** [comment]
will roadmap be update?

**Comment by aldhamdy** [comment]
why there is a support for RTL language ?
