### ISSUE TITLE
nz-pagination  component can still perform the next page when nzTotal=0

### ISSUE THREAD

**Issue by weboey** [NG-ZORRO/ng-zorro-antd#2026]
## Version
1.4.0
## Environment
Chrome  68.0.3440.106;  ng-zerro 1.0.0 
## Reproduction link
[https://stackblitz.com/edit/angular-nhcs49](https://stackblitz.com/edit/angular-nhcs49)
## Steps to reproduce
使用nz-pagination 设置[nzTotal]="0"
## What is expected?
The next page should be forbidden.
## What is actually happening?
When total hits 0, clicking the next page can trigger nzPageIndexChange  events

**Comment by vthinkxie** [comment]
感谢反馈，组件不会处理数据异常的情况
pagination中 nzTotal = 0 是异常情况，和 nzPageIndex = 1 在数值上就冲突了，
react版本中 直接就消失了 https://codepen.io/vthinkxie/pen/bxxXEq?&editors=001
