### ISSUE TITLE
bug(input-number) 当按 `tab` 切换时无法校验，以及

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#203]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

```html
<nz-input-number [(ngModel)]="demoValue" name="demoValue" [nzMin]="1" [nzMax]="10" [nzStep]="1"></nz-input-number>
```

会有两个问题：

+ 若初始值 `demoValue=1` 时 ![1](https://user-images.githubusercontent.com/2987467/29939126-70a4c428-8ebd-11e7-9bd9-4f99c153c46c.png) “减” 的状态不正确。
+ 文本框录入 `1000` 按下 `Tab` 键时依然是 `1000` ![2](https://user-images.githubusercontent.com/2987467/29939234-c0fa12f2-8ebd-11e7-8241-6b0b5d2bf825.png)

晚安！

**Comment by thegatheringstorm** [comment]
＋1 
------------------ Original ------------------

**Comment by thegatheringstorm** [comment]
＋1

**Comment by deart1mer** [comment]
I think `_checkDisabled` call the wrong location.

https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/input-number/nz-input-number.component.ts#L168

```js
export class NzInputNumberComponent implements ControlValueAccessor {
  // ...
  set nzValue(value: number) {
    if (this._value === value) {
      return;
    }
    if (value > this.nzMax) {
      this._value = this.nzMax;
      this.onChange(this.nzMax);
    } else if (value < this.nzMin) {
      this._value = this.nzMin;
      this.onChange(this.nzMin);
    } else {
      this._value = value;
      this._checkDisabled(); // disabled should be called after the setter function instead of here
    }
  }
}
```

**Comment by vthinkxie** [comment]
confirm, thanks for feedback.
