### ISSUE TITLE
富文本编辑器组件

### ISSUE THREAD

**Issue by HuiHenry** [NG-ZORRO/ng-zorro-antd#2042]
## What problem does this feature solve?
编辑格式化的文章时需要使用，应该说是很常用的一个功能
## What does the proposed API look like?
双向绑定，可附加图片

**Comment by vthinkxie** [comment]
有些特性为什么不会被支持
ng-zorro-antd 是 Angular 版本 Ant Design 的实现，这意味着只有 Ant Design 支持的交互、功能 才会被 ng-zorro-antd 实现。
