### ISSUE TITLE
select在选择项目发生变化后所选内容没有置空

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#2044]
## Version
1.4.0
## Environment
cli:6.1.2, node:10.6
## Reproduction link
[https://stackblitz.com/edit/angular-x53muf?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-x53muf?file=src/app/app.component.ts)
## Steps to reproduce
1、在select中选择一项
2、点change button改变绑定列表
## What is expected?
由于新的列表中没有之前所选的项目，select应该置空
## What is actually happening?
select任然保持之前选项
## Other?
不知道这个设计就是这样，或者是个bug

**Comment by wendzhue** [comment]
@wanghaolu select 值基于双向绑定, 你应该手动更新 `selectedValue`.

**Comment by vthinkxie** [comment]
设计如此，在option发生改变的时候 select的ngModel不会发生改变，假想一下异步加载的情况就可以理解这么设计的原因
