### ISSUE TITLE
tags: support preset colors for checkable mode 

### ISSUE THREAD

**Issue by wendzhue** [NG-ZORRO/ng-zorro-antd#2045]
## What problem does this feature solve?
We can't use checkable mode with colors. But sometimes, tags with colors could be checkable. Say we try to tag a job as emergent.

## What does the proposed API look like?
No need to add an API.

**Comment by rstrange1992** [comment]
Hi, any progress on this feature?

**Comment by wendzhue** [comment]
@rstrange1992 Hi. Actually I am going to implement this after `antd` gives response to this https://github.com/ant-design/ant-design/issues/11889.
