### ISSUE TITLE
How do I customize data in tree? I don't want to use fixed title, key and so on.

### ISSUE THREAD

**Issue by zhaoshaokun** [NG-ZORRO/ng-zorro-antd#2049]
## Version
1.4.0
## Environment
ng6 ngzorro1.1.1
## Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
I just started writing code with ng-zorro, without understanding the specific [key:string]: any.
## What is expected?
Give me an example or some inspiration

**Comment by wendzhue** [comment]
@zhaoshaokun You cannot use a library without following its API. You should write code to parse your data. And your reproduction link is invalid.

**Comment by simplejason** [comment]
@zhaoshaokun NzTreeNodeOptions accpet any data u provided, then u can use them with NzTreenode.origin. [official demo](http://ng.ant.design/components/tree/zh#components-tree-demo-dir-tree)
