### ISSUE TITLE
ng-zorro 什么时候可以实现《缩起内嵌菜单》-When can ng-zorro implement the < < embedded Menu > >?

### ISSUE THREAD

**Issue by cyongk** [NG-ZORRO/ng-zorro-antd#206]
When can ng-zorro implement the < < embedded Menu > >?

**Comment by vthinkxie** [comment]
please provide more detail.

**Comment by cyongk** [comment]
比如https://ant.design/docs/react/introduce-cn 中的，缩起内嵌菜单（For example, the shrink up inline menu in https://ant.design/docs/react/introduce-cn
）.
![default](https://user-images.githubusercontent.com/16489791/29958421-54ebbaee-8f25-11e7-8128-270f6750628e.PNG)
![1](https://user-images.githubusercontent.com/16489791/29958439-6ec6510e-8f25-11e7-9601-1353a2979f0a.PNG)
