### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by preraksola** [NG-ZORRO/ng-zorro-antd#2060]
I am trying to setup a custom theme in my project, but I am unable to see the different primary color.
As per the docs, I have the following in my `theme.less` file in `src` folder:
```
// -------- import official less file -----------
@import "../node_modules/ng-zorro-antd/src/ng-zorro-antd.less";
@icon-url: "/assets/fonts/iconfont";
@primary-color: #f5f36d;
```

And in my `angular.json` file I have:
```
"projects"       : {
    "abc-web-v2"     : {
      "root"        : "",
      "sourceRoot"  : "src",
      "projectType" : "application",
      "prefix"      : "app",
      "schematics"  : {},
      "architect"   : {
        "build"        : {
          "builder"        : "@angular-devkit/build-angular:browser",
          "options"        : {
            "outputPath" : "dist/abc-web-v2",
            "index"      : "src/index.html",
            "main"       : "src/main.ts",
            "polyfills"  : "src/polyfills.ts",
            "tsConfig"   : "src/tsconfig.app.json",
            "assets"     : [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles"     : [
              "src/theme.css",
              "src/styles.css"
            ],
            "scripts"    : []
          }
        }
      }
    }
  }
```

In my HTML I have a button, like:
```
<button nz-button nzType="primary" nzSize="large" [disabled]="!validateForm.valid">
        <span> Log in </span>
        <i class="anticon anticon-login"></i>
</button>
```

But still I see the default blue color button.
Is there anything else that I am missing over here?

**Comment by preraksola** [comment]
It says on [Issue Helper](http://ng.ant.design/issue-helper/#/en) to use it for **bug/feature request**.
But I have a question related to the usage. Also, it states that:

> For usage questions, please use the following resources:
>     - Read the docs
>     - Look for / ask questions on StackOverflow or Github

This is what exactly I did. So either open the issue again for an answer or update the issue helper to submit a usage question!

**Comment by wendzhue** [comment]
@preraksola If you want to override the default theme, you should create a less file instead of a css file and import default theme file into it.

```
"src/theme.css",
"src/styles.css"
```

**Comment by preraksola** [comment]
Hi @wendzhue that was a typing mistake. 
It's `theme.less` in `angular.json` file.

Also, it would be helpful if you can add a stackblitz example in the docs for custom theme.
