### ISSUE TITLE
Table - Not Responsive

### ISSUE THREAD

**Issue by ravindralande** [NG-ZORRO/ng-zorro-antd#2065]
## What problem does this feature solve?
Hay can you do the table responsive as of [datatable](https://datatables.net/). 

## What does the proposed API look like?
Mobile friendly table

**Comment by wendzhue** [comment]
@ravindralande ng-zorro-antd implements Ant Design. Maybe you could open an issue there first. 

BTW, responsive table seems weird to me because you cannot see some columns in some resolutions... Why would visitors want that? And how do we know which columns should be hidden?
