### ISSUE TITLE
nz-menu-item activated before router guard

### ISSUE THREAD

**Issue by sxlwar** [NG-ZORRO/ng-zorro-antd#2067]
## Version
1.4.0
## Environment
mac OS 10.13  angular 6.0 ng-zorro-antd 1.4.0
## Reproduction link
[https://stackblitz.com/edit/angular-mvc7vx?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular-mvc7vx?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
Navigate to the component which has CanDeactivated router guard. Then navigate to another component, select cancel button  in the confirm panel. Now, the router state never changed, but the activated menu changed already. In this demo, you will find that the activated menu changed,but url path still  two and activated component is TwoComponent.
## What is expected?
Menu activated after router guard.
## What is actually happening?
Menu activated before router guard.
## Other?
I haved tried to set nzSelected on the nz-menu-item element to solve this issue, but the effect still the same as above.

**Comment by vthinkxie** [comment]
Hi, @sxlwar thanks for your feedback, nz-menu won't watch the change of router, you can use `[nzSelected]` to set the selected state of menu item.
