### ISSUE TITLE
Date range picker not working on iOS 11

### ISSUE THREAD

**Issue by svdamani** [NG-ZORRO/ng-zorro-antd#2069]
## Version
1.4.0
## Environment
Mozilla/5.0 (iPad; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
## Reproduction link
[https://ng-zorro-antd-start-ggfn1i.stackblitz.io](https://ng-zorro-antd-start-ggfn1i.stackblitz.io)
## Steps to reproduce
1. Click on date range picker
2. Select any values for start date and end date
3. Notice ok button not clickable, ngModel not updated and ngModelChange not triggered

## What is expected?
Ok button should be clickable, ngModel should be updated automatically, ngModelChange should also be triggered
## What is actually happening?
Notice ok button not clickable, ngModel not updated and ngModelChange not triggered

**Comment by smile2014** [comment]
https://stackblitz.com/edit/angular-grid-zorro

**Comment by sridharan21994** [comment]
@wilsoncook  @vthinkxie  Please look into this issue.

**Comment by maoguiyou** [comment]
在最新的7.32版本中这个问题依旧存在

**Comment by maoguiyou** [comment]
@wilsoncook @vthinkxie 请看看这个问题。

**Comment by wenqi73** [comment]
It works fine on 10.0.2
