### ISSUE TITLE
asp.net core for angular 引用 ng-zorro-ant 报错

### ISSUE THREAD

**Issue by zerobaselove** [NG-ZORRO/ng-zorro-antd#207]
使用 asp.net core for angular，一个 Spa 项目 引用 ng-zorro-ant 报错
异常：document is not defined at NzGlobalMonitorService._observeGlobalEvents
按照剧情来讲应该是可以的，Microsoft.AspNetCore.SpaServices，服务端渲染

**Comment by vthinkxie** [comment]
duplicated #43

**Comment by vthinkxie** [comment]
@zerobaselove server rendering is not supported yet.
