### ISSUE TITLE
firstDayOfWeek in DatePicker doesn't respect i18n

### ISSUE THREAD

**Issue by outofrange** [NG-ZORRO/ng-zorro-antd#2073]
## Version
1.4.0
## Environment
Windows 10, Chrome
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-3higab](https://stackblitz.com/edit/ng-zorro-antd-start-3higab)
## Steps to reproduce
Open any date picker showing days
## What is expected?
Since the locale (i.e. "de") has effect on nearly all elements in a date picker component, I would expect it to handle the start of the week correctly, which should be 'Monday' ('Montag')
## What is actually happening?
The week is starting at Sunday
## Other?
The problem is in the following line:
https://github.com/NG-ZORRO/ng-zorro-antd/blob/69e1f5f37da174fc1fa997a3bbc4455ddf3a2f47/components/date-picker/lib/candy-date/util.ts#L7

This should be refactored to handle more locales than 'zh-cn' and 'zh-tw'

**Comment by vthinkxie** [comment]
Hi, @outofrange it will be great if you can create a pr for this issue.

**Comment by cosmodesantnik** [comment]
Temporary solution:

import { CandyDate } from 'ng-zorro-antd';
CandyDate.prototype.firstDayOfWeek = () => 1;

**Comment by wilsoncook** [comment]
Likely reference to https://github.com/date-fns/date-fns/blob/a5420d69a3f1e8f4533d02c09b6ce91cd1db78c6/src/locale/de/index.js#L26 as the default solution for all locales.
Additional, provide a option to support customize "firstDayOfWeek".

**Comment by Zacknero** [comment]
Hi i don't understand how set {
  /** Specify which day is the beginning of the week (null for default, 0 for Sunday, 1 for Monday, and so on) */
  firstDayOfWeek: null
}

To be set on app module?? or into component?? Thanks!!

**Comment by nclandrei** [comment]
@Zacknero - inside _app.module.ts_, you add the following:

```typescript
@NgModule({
  imports: [
    ...
  ],
  declarations: [
    ...
  ],
  providers: [
    ...,
    {
      provide: NZ_DATE_CONFIG,
      useValue: {
        firstDayOfWeek: 1, // week starts on Monday (Sunday is 0)
      },
    },
  ],
  ...
})
```

**Comment by RoroTiti** [comment]
Thanks so much @nclandrei !! This should be documented in Ng-Zorro docs
