### ISSUE TITLE
ng-timeline nzcolor 自定义颜色无效

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#2076]
## Version
0.7.0
## Environment
ng5
## Reproduction link
[https://ng-zorro.github.io/version/0.7.x/components/timeline/zh](https://ng-zorro.github.io/version/0.7.x/components/timeline/zh)
## Steps to reproduce
无
## What is expected?
可以自定义颜色
## What is actually happening?
不可以自定义颜色

**Comment by vthinkxie** [comment]
请升级至最新版本
