### ISSUE TITLE
Usage of Modal's service,  [nz-input] Input box  [disabled] Does not work properly

### ISSUE THREAD

**Issue by fanzhengshao** [NG-ZORRO/ng-zorro-antd#2079]
## Version
1.4.0
## Environment
windows10
## Reproduction link
[https://stackblitz.com/edit/angular-t1bmbd](https://stackblitz.com/edit/angular-t1bmbd)
## Steps to reproduce
https://stackblitz.com/edit/angular-t1bmbd
## What is expected?
Usage of Modal's service,  [nz-input] Input box  [disabled] Normal work
## What is actually happening?
Usage of Modal's service,  [nz-input] Input box  [disabled] Does not work properly
## Other?
Usage of Modal's service,  [nz-input] Input box  [disabled] Does not work properly
Now it's done in another way, there is EDIT2 in the code.
But I hope [disabled] will work properly.

**Comment by fanzhengshao** [comment]
https://stackblitz.com/edit/angular-t1bmbd
There is only style in ‘NO FormGroup‘’, but it can't work normally, you can still enter text.

**Comment by fanzhengshao** [comment]
Click the 'edit' button，The modal box pops up. The input box is set to disable, but can be entered.

**Comment by vthinkxie** [comment]
@fanzhengshao the repro link is invalid, could you plz give a valid repro link
this issue will be opened then.

**Comment by fanzhengshao** [comment]
@vthinkxie  https://stackblitz.com/edit/angular-mvcvgc-b2cnjh

**Comment by vthinkxie** [comment]
@fanzhengshao you cannot use [disabled] in reactive form
<img width="486" alt="2019-02-14 10 16 32" src="https://user-images.githubusercontent.com/1506722/52758001-9efe8a80-3041-11e9-8e73-a1e0a9770f51.png">

**Comment by fanzhengshao** [comment]
What about dynamic activation？How to do？

**Comment by vthinkxie** [comment]
@fanzhengshao https://angular.io/api/forms/AbstractControl#disable
read the doc plz

**Comment by fanzhengshao** [comment]
Thanks a million
