### ISSUE TITLE
nz-input's nzSize not work when nz-input not set nzDisabled property

### ISSUE THREAD

**Issue by gsbybb** [NG-ZORRO/ng-zorro-antd#208]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

if I do not set 'nzDisabled' property on nz-input ,'nzSize' will not work fine.
<img width="423" alt="default" src="https://user-images.githubusercontent.com/13886444/29965896-25fcc864-8f42-11e7-980e-5b69b8ae26bf.png">

## Expected behavior

if I only set 'nzSize'="'large'", nz-input can work fine.

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
works fine when I test it, please provide the code to reproduce it.

**Comment by vthinkxie** [comment]
@gsbybb 
bug confirm, thanks a lot.
