### ISSUE TITLE
NzModalService.confirm nzMaskClosable配置无效

### ISSUE THREAD

**Issue by cquptpei** [NG-ZORRO/ng-zorro-antd#2088]
## Version
1.4.1
## Environment
1.4.1
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-sb68iu](https://stackblitz.com/edit/ng-zorro-antd-start-sb68iu)
## Steps to reproduce
在设置nzMaskClosable: true的情况下,出现confirm对话框之后,点击蒙层,对话框不会关闭
## What is expected?
通过配置nzMaskClosable: true,confirm对话框点击蒙层可以关闭
## What is actually happening?
无反应，对话框不会关闭
## Other?
``` javascript
NzModalService.prototype.confirm = /**
     * @template T
     * @param {?=} options
     * @param {?=} confirmType
     * @return {?}
     */
    function (options, confirmType) {
        if (options === void 0) { options = {}; }
        if (confirmType === void 0) { confirmType = 'confirm'; }
        if ('nzFooter' in options) {
            this.logger.warn("The Confirm-Modal doesn't support \"nzFooter\", this property will be ignored.");
        }
        if (!('nzWidth' in options)) {
            options.nzWidth = 416;
        }
        if (typeof options.nzOnOk !== 'function') {
            // NOTE: only support function currently by calling confirm()
            options.nzOnOk = function () {
            }; // Leave a empty function to close this modal by default
        }
        options.nzModalType = 'confirm';
        options.nzClassName = "ant-confirm ant-confirm-"   confirmType   " "   (options.nzClassName || '');
        options.nzMaskClosable = false;
        return this.create(options);
    };
```
以上是confirm函数的源码,可以看到nzMaskClosable是被写死的,开发者传入的配置并不会覆盖默认配置

**Comment by vthinkxie** [comment]
确认模式下`nzMaskClosable` 不会生效，work as design
<img width="914" alt="2018-09-03 7 03 43" src="https://user-images.githubusercontent.com/1506722/44983525-1a94df80-afac-11e8-8297-619f9f206222.png">

**Comment by cquptpei** [comment]
@vthinkxie 我想问的是蒙层的配置无效,并不是右上角关闭按钮,是`nzMaskClosable`的配置,并不是`nzClosable`的配置,你们默认隐藏的配置是`nzMaskClosable`,并不是`nzClosable`,官方文档截图如下:
<img width="950" alt="wx20180904-083348 2x" src="https://user-images.githubusercontent.com/11143986/45004255-b874c280-b01d-11e8-9a01-b4ddae336777.png">

**Comment by wendzhue** [comment]
@cquptpei 

并不是无效, 设计就是这样, 你在用 confirm 的时候 closable 是不能配置的, 你可以看 Ant Design 的设计: https://codepen.io/wendzhue/pen/wEdxRq?&editors=001

用 confirm, 就应该让用户明确的返回一个结果.  浏览器自带的 confirm() 也是不能通过点击外部关闭的.

**Comment by cquptpei** [comment]
@wendzhue 非常感谢,刚刚和同事讨论了下,才理解到这样设计的用意,只是文档上写的并不是很清晰,误以为nzMaskClosable是可配置的

**Comment by cquptpei** [comment]
@wendzhue 希望能够在文档上像`nzClosable`配置一样,备注说明`nzMaskClosable `在确认框模式下该值无效
