### ISSUE TITLE
Calendar only showing year from 2008

### ISSUE THREAD

**Issue by piyush-ampersand** [NG-ZORRO/ng-zorro-antd#2091]
## Version
0.7.1
## Environment
The calendar only gives option to select the year greater than 2008 and upto 2027
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ukyito](https://stackblitz.com/edit/ng-zorro-antd-start-ukyito)
## Steps to reproduce
No reproduction needed as with basic calendar the issue persist. Ideally user should be able to select any year.
## What is expected?
User should be able to select dates before 2008 and 2027 also
## What is actually happening?
User is only able to choose dates between 2008 and 2027

**Comment by piyush-ampersand** [comment]
@vthinkxie Hey don't you think this is a requirement since by default a calendar should not be bounded and should give user the freedom of selecting any date just like datepicker

**Comment by vthinkxie** [comment]
@piyush-ampersand will be supported in next version.

**Comment by piyush-ampersand** [comment]
@vthinkxie Ok I understand, can you tell me how to restrict the years/months in calendar as I only want to show upcoming three months calendar but all previous months?

**Comment by vthinkxie** [comment]
@piyush-ampersand 
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/calendar/nz-calendar-header.component.ts
https://blog.angularindepth.com/changing-the-behavior-of-a-3rd-party-angular-component-91f84fb9af28?source=---------6---------------------

**Comment by piyush-ampersand** [comment]
@vthinkxie Thank you for your support. So should I update my npm package now , will it available??

**Comment by vthinkxie** [comment]
@piyush-ampersand please wait until the next version released
