### ISSUE TITLE
cascader can not filter correctly when a node has no children

### ISSUE THREAD

**Issue by zd5043039119** [NG-ZORRO/ng-zorro-antd#2104]
## Version
1.4.1
## Environment
Angular 6.1.3,Chrome  67.0.3396.87
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-mshvaz](https://stackblitz.com/edit/ng-zorro-antd-start-mshvaz)
## Steps to reproduce
1. 触发Cascader，并使焦点聚集在输入框<br/>
2. 输入Test这个单词的任意结果
## What is expected?
能出现高亮的Test选项
## What is actually happening?
Not Found

**Comment by wendzhue** [comment]
@zd5043039119 Please provide the edit link, not just the demo.

**Comment by wendzhue** [comment]
@zd5043039119 Thanks for reporting this. You don't need to provide that link now.

**Comment by zd5043039119** [comment]
@wendzhue Updated

**Comment by wendzhue** [comment]
@zd5043039119 You didn't mark the node as `isLeaf` so it would treated as a non-leaf node, which means it shouldn't be able to dispatch a value at all.

**Comment by wendzhue** [comment]
But it do have a problem. I would fix it for another issue.

**Comment by zd5043039119** [comment]
@wendzhue i config the `isLeaf`, and will get the same result, and i read the source code,

```java
const loopParent = (node: CascaderOption, forceDisabled = false) => {
      const disabled = forceDisabled || node.disabled;
      path.push(node);
      node.children.forEach((sNode) => {
        if (!sNode.parent) { sNode.parent = node; } /** 搜索的同时建立 parent 连接，因为用户直接搜索的话是没有建立连接的，会提升从叶子节点回溯的难度 */
        if (!sNode.isLeaf) { loopParent(sNode, disabled); }
        if (sNode.isLeaf || !sNode.children) { loopChild(sNode, disabled); }
      });
      path.pop();
    };
```

node.children is empty and will never be execute loopChild, so will never execute filter

**Comment by wendzhue** [comment]
@zd5043039119 Yes that's a reason.

Since you have found the reason, are you interested in firing a pull request to fix this?

**Comment by zd5043039119** [comment]
sure, i'll try
