### ISSUE TITLE
Message Component position

### ISSUE THREAD

**Issue by MykhayloBondacrhuk** [NG-ZORRO/ng-zorro-antd#2106]
## What problem does this feature solve?
When it is necessary to display a Message Component not only on the top of the screen but also in the bottom, on the left or right side. 
## Example
`
{
  ...NZ_MESSAGE_CONFIG,
  nzPlacement: 'top' | 'bottom' | 'left' | 'right' 
}
`

**Comment by wendzhue** [comment]
@MykhayloBondacrhuk Hi. `ng-zorro-antd` implements Ant Design. Could you please open a similar feature request there, explaining why it should be supported?

**Comment by wendzhue** [comment]
Closed because no implementation or plan seen on Ant Design.
