### ISSUE TITLE
button更多颜色/自定义配色,我希望zorro能有更多颜色色调的按钮可以使用

### ISSUE THREAD

**Issue by Diry2017** [NG-ZORRO/ng-zorro-antd#2107]
## What problem does this feature solve?
1. 我希望按钮能够有更多的主题颜色默认配色可以提供更多的选择.
2. 比如说在后台管理系统中,可以一个表需要用按钮来承放增删改查,不同颜色可以区别这种按钮.
3. 然后提供一个可以设置颜色的less变量色,这里的颜色设置可以从 按钮的选中 到点击波纹 都提供一个规定格式的设置
4. 如果已经提供了该功能哪可能是我疏忽了,或者没有理解文档内容,麻烦告诉我一下对应的文档链接,我去研究.
5. 感激不尽~
## What does the proposed API look like?
1. button nz-button nzColor="red"
2. less{
   1. @color-red-0: #fff;
   2. @color-red-1: #fff
   3. @color-red-2: #fff
3. }

**Comment by Diry2017** [comment]
https://beta.ionicframework.com/docs/theming/color-generator
类似于ionic这样定义色调

**Comment by wenqi73** [comment]
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/color/colors.less](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/color/colors.less)
Copy this to your project, you can change the primary color and it will replace old [colors](https://ant.design/docs/spec/colors-cn).

**Comment by Diry2017** [comment]
谢谢你,这个能新增配色并且使用吗？

**Comment by wenqi73** [comment]
Try this: `<button nz-button nzType="{{your_class}}">xxx</button>`

```less
.ant-btn-{{your_class}} {
  // ...
}
```
