### ISSUE TITLE
在firefox浏览器上有些table一直处于loading状态，鼠标点击或滚动时loading消失，显示数据。

### ISSUE THREAD

**Issue by zlhgo** [NG-ZORRO/ng-zorro-antd#2109]
## Version
1.4.1
## Environment
firefox
## Reproduction link
[http://stackblitz.com/](http://stackblitz.com/)
## Steps to reproduce
最新版的nz和ng。firefox浏览器，不管是windows、mac、linux的firefox都有这个问题，但是不一定能重现。在我的项目中也只是某些table会出现这个问题，对比后没发现这些table有什么问题。
## What is expected?
当数据加载完成后loading消息，显示数据。
## What is actually happening?
数据加载完成后loading一直存在，鼠标点击和滚动时loading才消失后显示数据。
google chrome正常。
## Other?
使用的是ajax data， 这个问题有点像是升级ng后出现的，不过具体哪个版本忘了，本以为等多升级nz 和 ng几个版本后会消失，大概有差不多一个月了吧。

**Comment by vthinkxie** [comment]
请提供正确的重现链接

**Comment by zlhgo** [comment]
@vthinkxie 我尽量提供，不一定能重现。在我的项目中是有这个问题。

**Comment by vthinkxie** [comment]
close for lacking of repro link
