### ISSUE TITLE
import NgZorroAntdModule  question

### ISSUE THREAD

**Issue by huangyangyang-yangyang** [NG-ZORRO/ng-zorro-antd#211]
<!
import NgZorroAntdModule
-->

compiler.es5.js:1689 Uncaught Error: Can't resolve all parameters for FLOATER_SERVICE_PROVIDER_FACTORY: ([object Object], ?, [object Object]).
    at syntaxError (compiler.es5.js:1689)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getDependenciesMetadata (compiler.es5.js:15756)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getFactoryMetadata (compiler.es5.js:15636)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getProviderMetadata (compiler.es5.js:15909)
    at compiler.es5.js:15830
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getProvidersMetadata (compiler.es5.js:15790)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js:15445)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleSummary (compiler.es5.js:15298)
    at compiler.es5.js:15371
syntaxError @ compiler.es5.js:1689
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getDependenciesMetadata @ compiler.es5.js:15756
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getFactoryMetadata @ compiler.es5.js:15636
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getProviderMetadata @ compiler.es5.js:15909
(anonymous) @ compiler.es5.js:15830
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getProvidersMetadata @ compiler.es5.js:15790
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js:15445
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleSummary @ compiler.es5.js:15298
(anonymous) @ compiler.es5.js:15371
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js:15356
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleSummary @ compiler.es5.js:15298
(anonymous) @ compiler.es5.js:15390
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js:15385
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleSummary @ compiler.es5.js:15298
(anonymous) @ compiler.es5.js:15371
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js:15356
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleSummary @ compiler.es5.js:15298
(anonymous) @ compiler.es5.js:15371
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js:15356
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleSummary @ compiler.es5.js:15298
(anonymous) @ compiler.es5.js:15371
webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js:15356
webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules @ compiler.es5.js:26679
webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents @ compiler.es5.js:26652
webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync @ compiler.es5.js:26581
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4595
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4581
../../../../../src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap 1609ad10f1ec84641970:54
3 @ main.bundle.js:3496
__webpack_require__ @ bootstrap 1609ad10f1ec84641970:54
webpackJsonpCallback @ bootstrap 1609ad10f1ec84641970:25
(anonymous) @ main.bundle.js:1
client?ffdb:41 [WDS] Warnings while compiling.
client?ffdb:106 ./~/ng-zorro-antd/src/release/root/nz-root.module.js
25:105-113 "export 'DOCUMENT' was not found in '@angular/common'
warnings @ client?ffdb:106
sock.onmessage @ socket.js:37
webpackJsonp.../../../../sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
webpackJsonp.../../../../sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
webpackJsonp.../../../../sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
wrapFn @ zone.js:1056
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:191
ZoneTask.invoke @ zone.js:486
client?ffdb:106 ./~/ng-zorro-antd/src/release/root/nz-root.module.js
31:58-66 "export 'DOCUMENT' was not found in '@angular/common'
warnings @ client?ffdb:106
sock.onmessage @ socket.js:37
webpackJsonp.../../../../sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
webpackJsonp.../../../../sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
webpackJsonp.../../../../sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
wrapFn @ zone.js:1056
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:191
ZoneTask.invoke @ zone.js:486
client?ffdb:106 ./~/ng-zorro-antd/src/release/root/nz-root.component.js
30:58-66 "export 'DOCUMENT' was not found in '@angular/common'
warnings @ client?ffdb:106
sock.onmessage @ socket.js:37
webpackJsonp.../../../../sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
webpackJsonp.../../../../sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
webpackJsonp.../../../../sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
wrapFn @ zone.js:1056
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:191
ZoneTask.invoke @ zone.js:486
client?ffdb:106 ./~/ng-zorro-antd/src/release/core/floater/floater.service.js
47:58-66 "export 'DOCUMENT' was not found in '@angular/common'
warnings @ client?ffdb:106
sock.onmessage @ socket.js:37
webpackJsonp.../../../../sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
webpackJsonp.../../../../sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
webpackJsonp.../../../../sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
wrapFn @ zone.js:1056
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:191
ZoneTask.invoke @ zone.js:486
client?ffdb:106 ./~/ng-zorro-antd/src/release/core/floater/floater.service.js
55:20-28 "export 'DOCUMENT' was not found in '@angular/common'

show warning and error,page can't show

**Comment by vthinkxie** [comment]
please remove node_modules directory and update to 0.5.0-rc.4

**Comment by vthinkxie** [comment]
and if you are using webpack, make sure you have correct config file.
We recommend you to use @angular/cli with eject command to get correct webpack config.
