### ISSUE TITLE
Ability to disable card footer actions

### ISSUE THREAD

**Issue by Supamiu** [NG-ZORRO/ng-zorro-antd#2113]
## What problem does this feature solve?
When you have a card with actions, some actions might not be available but you still want them to be shown, just not the same color and without hover behavior.
## What does the proposed API look like?
a simple way to disable a given action, could'nt find one at the moment because there's no way to access the span around the icon, making this behavior implementation quite hard.

**Comment by vthinkxie** [comment]
it is easy to add your own class to `<i>` tag to disable any behavior you want.
https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
