### ISSUE TITLE
table 组件 能够disable hover 显示效果

### ISSUE THREAD

**Issue by symphony2014** [NG-ZORRO/ng-zorro-antd#2123]
## What problem does this feature solve?
有时候并不想使用hover的效果，只想单纯的展示数据。
## What does the proposed API look like?
nzTableHoverDisable

**Comment by fanzhengshao** [comment]
自己写样式覆盖不就行了吗

**Comment by symphony2014** [comment]
@fanzhengshao ,这样不好。这应该算产品BUG。应该提到issues里面。

**Comment by vitadolce** [comment]
样式覆盖不了
