### ISSUE TITLE
通过服务创建的对话框，如果未关闭，每按一次空格都会弹出一个新的对话框。

### ISSUE THREAD

**Issue by The-Lost** [NG-ZORRO/ng-zorro-antd#2124]
## Version
1.5.0
## Environment
Chrome 版本 69.0.3497.81（正式版本） （64 位）
## Reproduction link
[https://ng-zorro-antd-start-7wftxv.stackblitz.io](https://ng-zorro-antd-start-7wftxv.stackblitz.io)
## Steps to reproduce
点击按钮创建一个对话框，在未进行任何操作的情况下，按空格键。
## What is expected?
无任何事情发生。
## What is actually happening?
创建了一个新的对话框。
## Other?
null

**Comment by wendzhue** [comment]
@The-Lost 你可以先临时加一个变量保留 modal 对象的引用, 调用打开 modal 方法的时候检查这个变量是否为 falsy.
