### ISSUE TITLE
How load large data in ng-zorro table?

### ISSUE THREAD

**Issue by v1ar31** [NG-ZORRO/ng-zorro-antd#2127]
## Version
0.7.1
## Environment
"@angular/core": "5.2.9"
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-bg28mg](https://stackblitz.com/edit/ng-zorro-antd-start-bg28mg)
## Steps to reproduce
load large data in ng-zorro table (more then 150 rows)
## What is expected?
fine work
## What is actually happening?
chrome freeze and the table very long renders unlike pure angular 5 or ngx-datatable

**Comment by wendzhue** [comment]
@v1ar31 You should use front end pagination for now. Maybe we would support lazy load in the future.

**Comment by vthinkxie** [comment]
closed as #2157 merge now.
