### ISSUE TITLE
[DOC's] Update methods from Notification documentation page

### ISSUE THREAD

**Issue by DouglasOGarrido** [NG-ZORRO/ng-zorro-antd#2128]
## Version
1.5.0
## Environment
Windows 10. Chrome 69.
## Reproduction link
[https://stackblitz.com/edit/angular-zhww75?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-zhww75?file=src/app/app.component.ts)
## Steps to reproduce
Click on the button "Loading Create" or "Loading" on the link provided. The documentation page: [Notification DOC](https://ng.ant.design/components/notification/en#nznotificationservice)
## What is expected?
Expected the method ```NzNotificationService.loading()``` or ```NzNotificationService.create('loading')``` exists.
## What is actually happening?
The method ```NzNotificationService.loading()``` or ```NzNotificationService.create('loading')``` doesn't exist.

**Comment by vthinkxie** [comment]
sorry for the mistake doc, there is no loading method in notification service, welcome to create a pr to fix the doc, thanks for reporting.
