### ISSUE TITLE
NzNotificationService render error when content contains special character

### ISSUE THREAD

**Issue by schsiung** [NG-ZORRO/ng-zorro-antd#2129]
## Version
1.5.0
## Environment
ALL
## Reproduction link
[https://stackblitz.com/edit/angular-1pcuag?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-1pcuag?file=src/app/app.component.ts)
## Steps to reproduce
当通知内容包含某些特殊字符时，notification渲染内容出错
```
    let a = `9d935<X046`;
    console.log(a);
    this.notification.create(type, 'Notification Title',
      `This is the content of the notification. This is the content of the notification. This is the content of the notification. ${a}`);
  }
```
## What is expected?
内容展示正确，与控制台输出相同
## What is actually happening?
内容展示时截掉了9d935后面的内容

**Comment by wendzhue** [comment]
@schsiung 当你要把字符串插入 HTML 中的时候, 当然要进行转义:

```ts
  createNotification(type: string): void {
    let a = `9d935<X046`;
    console.log(a);
    this.notification.create(type, 'Notification Title',
      `This is the content of the notification. This is the content of the notification. This is the content of the notification. ${a.replace('<', '&lt;')}`);
  }
```

**Comment by wendzhue** [comment]
我修改了你的 demo: https://stackblitz.com/edit/angular-1pcuag-tjkmvf?file=src/app/app.component.ts.

**Comment by schsiung** [comment]
多谢解答！
Angular在进行数据绑定时，默认是进行了转义处理的，建议可以在文档里补充说明一下，避免更多人采坑！
