### ISSUE TITLE
升级1.5 打包发布异常

### ISSUE THREAD

**Issue by tianxiaozi** [NG-ZORRO/ng-zorro-antd#2132]
## Version
1.5.0
## Environment
mac os x  chrome最新版
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.tsxx](https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.tsxx)
## Steps to reproduce
打包发布的时候加此配置 "buildOptimizer": true, 会报异常，跑不了

Angular CLI: 6.2.1
Node: 8.11.2
OS: darwin x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.8.1
@angular/cdk                      6.4.7
@angular/cli                      6.2.1
@angular/flex-layout              6.0.0-beta.16
@ngtools/webpack                  6.0.8
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

编译报的异常----------->>>>
116:1141-1147 "export 'ɵin' (imported as 'i1') was not found in 'ng-zorro-antd'
42:5583-5589 "export 'ɵjr' (imported as 'i9') was not found in 'ng-zorro-antd'
4517:70-76 "export 'ɵjq' (imported as 'i1') was not found in 'ng-zorro-antd'
4601:70-76 "export 'ɵjq' (imported as 'i1') was not found in 'ng-zorro-antd'
4622:192-198 "export 'ɵjq' (imported as 'i1') was not found in 'ng-zorro-antd'
4623:71-77 "export 'ɵjq' (imported as 'i1') was not found in 'ng-zorro-antd'
4737:120-126 "export 'ɵjs' (imported as 'i1') was not found in 'ng-zorro-antd'
4737:159-165 "export 'ɵjs' (imported as 'i1') was not found in 'ng-zorro-antd'
4739:73-79 "export 'ɵjs' (imported as 'i1') was not found in 'ng-zorro-antd'
52:10206-10213 "export 'ɵin' (imported as 'i17') was not found in 'ng-zorro-antd'
52:10215-10222 "export 'ɵin' (imported as 'i17') was not found in 'ng-zorro-antd'
52:10507-10514 "export 'ɵjr' (imported as 'i17') was not found in 'ng-zorro-antd'
52:10516-10523 "export 'ɵjr' (imported as 'i17') was not found in 'ng-zorro-antd'
54:5709-5716 "export 'ɵin' (imported as 'i15') was not found in 'ng-zorro-antd'
54:5718-5725 "export 'ɵin' (imported as 'i15') was not found in 'ng-zorro-antd'
54:6010-6017 "export 'ɵjr' (imported as 'i15') was not found in 'ng-zorro-antd'
54:6019-6026 "export 'ɵjr' (imported as 'i15') was not found in 'ng-zorro-antd'
77:527-533 "export 'ɵjs' (imported as 'i4') was not found in 'ng-zorro-antd'
77:76-82 "export 'ɵjs' (imported as 'i4') was not found in 'ng-zorro-antd'
## What is expected?
0
## What is actually happening?
0

**Comment by vthinkxie** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/angular.json#L47
https://travis-ci.org/NG-ZORRO/ng-zorro-antd/jobs/427078888 
works fine in ci

**Comment by wzengguang** [comment]
@tianxiaozi  
请教你是如果解决的。我也报的和你一样的警告。部署后访问首页加载不出来。
在main.js有个 cant read property 'nativeElement' of undefined 。也是出在ng-zorro部分。

**Comment by tianxiaozi** [comment]
解决了，  升级你的依赖包 跟官方版本一样 然后删掉node_module 重新下载依赖

**Comment by tianxiaozi** [comment]
查看 releases  找到1.5版本 下载源码，打开package.json 看依赖版本

**Comment by tianxiaozi** [comment]
@wmhh1129 @wzengguang
