### ISSUE TITLE
Page freezes when rendering large data use nz-card and nz-card-grid with nz-table nested in 

### ISSUE THREAD

**Issue by wunaidage** [NG-ZORRO/ng-zorro-antd#2139]
## Version
1.5.0
## Environment
Angular 6, MacPro 2017, Chrome 68
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ucjqcd](https://stackblitz.com/edit/ng-zorro-antd-start-ucjqcd)
## Steps to reproduce
1. Get large data with like 1500 records
2. use nz-card-grid to render each record and use nz-table in the nz-card-grid, see stackblitz example
## What is expected?
Page rendered quickly and scrolled smoothly
## What is actually happening?
Page freezes, table in each grid will rendered after several seconds. when scrolling, page is almost broken.
when change to native html table, the page became much smoother and quicker.

**Comment by wendzhue** [comment]
Of course it would freeze. You are putting 1500 nz-card components and 1500 nz-table components and thousands of thousands of DOM elements into a single page. 

We would do lazy-load for nz-table component in the future, of course. But we cannot handle everything for users. You should do pagination yourself.
