### ISSUE TITLE
nz-input-number 组件如果手动输入则需要鼠标点一下空白页面才会触发表单验证，选择上下箭头增减数值则可以立即触发

### ISSUE THREAD

**Issue by fanzhengshao** [NG-ZORRO/ng-zorro-antd#2151]
## Version
1.5.0
## Environment
win10，chrome65  ，1.5.0
## Reproduction link
[https://stackblitz.com/edit/nz-input-number-1?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/nz-input-number-1?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
在表单中有nz-input-number组件，并且有做表单校验的，手动输入则需要鼠标点一下空白页面才会触发表单验证，选择上下箭头增减数值则可以立即触发验证
## What is expected?
手动输入的时候也能即时触发验证
## What is actually happening?
必须点一下其他地方使输入框失去光标才能触发验证

**Comment by vthinkxie** [comment]
手动输入的时候是不能立即触发验证的，想象一下你的验证条件是>9，实际输入的时候先后输入 1 和 0 的情况你就能理解为什么这样设计。
