### ISSUE TITLE
sider nzBreakpoint 设置没有效果

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#2153]
## Version
1.5.0
## Environment
ng 6
## Reproduction link
[https://ng-zorro.github.io/components/layout/zh](https://ng-zorro.github.io/components/layout/zh)
## Steps to reproduce
无重新步骤
## What is expected?
不出现....
## What is actually happening?
折叠始终出现...

**Comment by vthinkxie** [comment]
<img width="769" alt="2018-09-18 4 12 46" src="https://user-images.githubusercontent.com/1506722/45673594-b6524e00-bb5d-11e8-8cac-736833b82f57.png">
