### ISSUE TITLE
pagination nzShowQuickJumper bug

### ISSUE THREAD

**Issue by yy7054wyq5** [NG-ZORRO/ng-zorro-antd#2156]
## Version
1.5.0
## Environment
macOS 10.13.6, Chrome 69.0.3497.92, Angular 6.1.7
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-buapt6](https://stackblitz.com/edit/ng-zorro-antd-start-buapt6)
## Steps to reproduce

* Put 'button' and 'pagination' in one form.
* Set [nzShowQuickJumper]="true".
* Input number and click 'enter'
* Fire the button click event.

```html
<form>
   <button nz-button nzType="primary" (click)="a(1)">Button</button>
   <nz-pagination [nzPageIndex]="2" [nzTotal]="500" nzShowQuickJumper></nz-pagination>
</form>
```

## What is expected?
Don't fire button click event. Use blur or other instead.
```html
<input #quickJumperInput (blur)="handleKeyDown($event,quickJumperInput,true)">
```

## What is actually happening?
nzShowQuickJumper, Fire the button click event.

**Comment by yy7054wyq5** [comment]
@vthinkxie update.If link stil can't work.Please use this code instead.
```html
<form>
   <button nz-button nzType="primary" (click)="a(1)">Button</button>
   <nz-pagination [nzPageIndex]="2" [nzTotal]="500" nzShowQuickJumper></nz-pagination>
</form>
```
```javascript
a(){
 alert(1);
}
```

**Comment by vthinkxie** [comment]
there is nothing todo with ng-zorro-antd at all.
please read the document of button type
https://www.w3schools.com/tags/att_button_type.asp

here is the link which can work 
https://stackblitz.com/edit/ng-zorro-antd-start-9m9ax7?file=src/app/app.component.html

**Comment by yy7054wyq5** [comment]
👌
