### ISSUE TITLE
Tabs标签页 附加内容 nzTabBarExtraContent height 和  TabBar中的nav-container height值不一致

### ISSUE THREAD

**Issue by xcorpio** [NG-ZORRO/ng-zorro-antd#2160]
## Version
1.5.0
## Environment
macos,chrome latest
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-fdcipw?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-fdcipw?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
1. 查看链接, 会有以下`表象`
2. 对比 `tabbar` 中 `.ant-tabs-nav-container` 和 `.ant-tabs-extra-content` 高度不一直

## What is expected?
高度一直，或`.ant-tabs-extra-content` 应小于 `.ant-tabs-nav-container`
## What is actually happening?
在`nzTabBarStyle` 设置 `margin:0px` 后， 多占了下面 TAB 的位置( 由于`.ant-tabs-nav-container`多出来的像素高度)

**Comment by vthinkxie** [comment]
按照 ant design 设计规范与 react 版本保持一致，以下是react版本的效果
https://codepen.io/vthinkxie/pen/MqZjKp?editors=0010

**Comment by xcorpio** [comment]
但是感觉有点儿奇怪🤔

![ant-design](https://user-images.githubusercontent.com/4575409/45768358-40d6a280-bc6f-11e8-97c8-8f502c1ace2d.gif)

=======  如过颜色不一样，会这样。虽然设置 padding-bottom 也行，但是 tab 选中的那个下划线标志就不在最底部了

![ant-design](https://user-images.githubusercontent.com/4575409/45768858-9495bb80-bc70-11e8-9272-da848a33801b.gif)

**Comment by vthinkxie** [comment]
@xcorpio 如果觉得是规范设计错误，可以到 antd 仓库 https://github.com/ant-design/ant-design 发起issue
ng-zorro-antd 的样式文件会定期从 ant-design 同步
