### ISSUE TITLE
TREE数据获取

### ISSUE THREAD

**Issue by liubinduo** [NG-ZORRO/ng-zorro-antd#2168]
## What problem does this feature solve?
很多时候我们都会对树的数据进行在前端编辑，这样获取整个树的数据就成了刚需。
## What does the proposed API look like?
初始化树时传入NzTreeNodeOption或者origin，编辑完树后，可以获取到整个树的NzTreeNodeOption获取origin

**Comment by simplejason** [comment]
当前tree操作的是NzTreeNode，origin不一定准确匹配，新版将支持直接传递NzTreeNodeOption数组，支持直接获取Tree全部节点。[追踪这个PR](https://github.com/NG-ZORRO/ng-zorro-antd/pull/2121)

**Comment by liubinduo** [comment]
那么目前我有什么方法可以获取NzTreeNodeOption吗？

**Comment by liubinduo** [comment]
> 当前tree操作的是NzTreeNode，origin不一定准确匹配，新版将支持直接传递NzTreeNodeOption数组，支持直接获取Tree全部节点。[追踪这个PR](https://github.com/NG-ZORRO/ng-zorro-antd/pull/2121)

那么目前我有什么方法可以获取NzTreeNodeOption吗？

**Comment by simplejason** [comment]
@liubinduo 目前的NzTreeNodeOption是原始输入值，并不一定是你需要的，你可以描述一下需要哪些属性
