### ISSUE TITLE
ability to globally set default buttons text (ok, cancel) in modal and popconfirm components

### ISSUE THREAD

**Issue by mortifactor** [NG-ZORRO/ng-zorro-antd#2169]
## What problem does this feature solve?
there will be no need to redefine "OK" and "Cancel" text of buttons in these components
## What does the proposed API look like?
may be we could set this text inside i18n files

**Comment by vthinkxie** [comment]
plz read the doc carefully.
<img width="572" alt="2018-09-20 11 57 32" src="https://user-images.githubusercontent.com/1506722/45795087-6219ac00-bccc-11e8-8db5-76136c5916b3.png">
<img width="576" alt="2018-09-20 11 57 27" src="https://user-images.githubusercontent.com/1506722/45795088-62b24280-bccc-11e8-827d-694c1a1095d0.png">
