### ISSUE TITLE
select, popover 下拉列表弹出层 某些情况不显示

### ISSUE THREAD

**Issue by xcorpio** [NG-ZORRO/ng-zorro-antd#2172]
## Version
1.5.0
## Environment
macos, chrome latest
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ihjrxi?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-ihjrxi?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
1. 打开 https://ng-zorro-antd-start-ihjrxi.stackblitz.io/
2. 点击 `FullScreen` 按钮
3. `select` `popover` 不能弹出
## What is expected?
表现的像普通的 select
## What is actually happening?
*

**Comment by xcorpio** [comment]
这应该是 和 `screenfull` 这个库有地方有些冲突， 有什么 办法可以解吗？ 🤔

**Comment by wendzhue** [comment]
@xcorpio 按了 FullScreen 时候什么都没有发生... Select 也能正常弹出.

**Comment by xcorpio** [comment]
@wendzhue  在编辑器里面好像是有错误提示，需要单独打开个窗口，https://ng-zorro-antd-start-ihjrxi.stackblitz.io/  这里， 全屏之后，select 和popover 就不能弹出了，退出全屏还在显示

**Comment by vthinkxie** [comment]
原因很简单 你request full screen 的 div内部 并不包含 select 的下拉部分
https://developer.mozilla.org/zh-CN/docs/Web/API/Element/requestFullScreen
这种API方式实现的全屏问题非常多，不建议这么使用

**Comment by xcorpio** [comment]
切换 className 能全屏？ 先要请求 整个 document 全屏, 然后再让 div 占用 整个 document 这样吗, 我试试

**Comment by xcorpio** [comment]
https://ng-zorro-antd-start-ihjrxi.stackblitz.io/
@vthinkxie  可以了，多谢， 学到了新东西
