### ISSUE TITLE
nz-tree 控件，当在 [nzDefaultCheckedKeys] 属性中指定根节点为选中节点时，下级节点会自动全部选中。而 [nzDefaultSelectedKeys] 表现正常。

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd#2174]
## Version
1.5.0
## Environment
angular6
## Reproduction link
[https://stackblitz.com/edit/angular-89qiyv?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-89qiyv?file=src/app/app.component.ts)
## Steps to reproduce
```
@Component({
  selector: 'nz-demo-tree-basic',
  template: `
    <nz-tree
      [(ngModel)]="nodes"
      [nzCheckable]="true"
      [nzDefaultCheckedKeys]="checkedKeys"
      [nzDefaultSelectedKeys]="selectedKeys"
    >
    </nz-tree>
})
export class NzDemoTreeBasicComponent implements OnInit {
  checkedKeys = [ '1001', '10001', '100011' ];
  selectedKeys = [ '1001', '10001', '100011' ];
}
```
## What is expected?
应该只选中指定的节点，而不要自动选中下属子节点。 与  [nzDefaultSelectedKeys] 属性的表现一致。
![image](https://user-images.githubusercontent.com/3461709/45857420-2265c980-bd8b-11e8-81c6-4df1f490efd5.png)

## What is actually happening?
只选中根节点，nz-tree 会自动选中下属子节点

**Comment by dusdong** [comment]
我又重新测试了下，当属性  [nzCheckStrictly]="true" 时， [nzDefaultCheckedKeys] 与   [nzDefaultSelectedKeys] 表现一致。

**Comment by zzmmbb** [comment]
楼主 解决了吗  我也希望选中父节点的时候不要初始化子节点
