### ISSUE TITLE
pagination nzShowQuickJumper bug

### ISSUE THREAD

**Issue by baronQin** [NG-ZORRO/ng-zorro-antd#2178]
## Version
1.5.0
## Environment
windows 7, 68.0.3440.106, Angular 6.1.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-vpijpc](https://stackblitz.com/edit/ng-zorro-antd-start-vpijpc)
## Steps to reproduce
1 set [nzShowQuickJumper]="true".
2 on that  form input value.

## What is expected?
the pageindex can jump auto
but i tied it in version 0.6.x, it is valid
## What is actually happening?
the pageindex dosen't jump auto

**Comment by vthinkxie** [comment]
press enter key after input plz.

**Comment by baronQin** [comment]
thanks
