### ISSUE TITLE
Menu: Should be processing overflowed when is horizontal mode

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#2183]
## Reproduce

A react [online demo](https://codepen.io/cipchk/pen/wEZPKd), png:

![1](https://user-images.githubusercontent.com/2987467/45924628-87f6b900-bf37-11e8-8832-0b6c2af9f9cb.png)

A angular [online demo](https://stackblitz.com/edit/angular-s1qbdn?file=src/app/app.component.ts), png:

![2](https://user-images.githubusercontent.com/2987467/45924634-aa88d200-bf37-11e8-968b-ad537a9d42b1.png)

**Comment by vthinkxie** [comment]
duplicated #2531
