### ISSUE TITLE
Modal content 为 form 时，自定义的 footer 或`nzOnCancel` 无法 reset form

### ISSUE THREAD

**Issue by mattshma** [NG-ZORRO/ng-zorro-antd#2184]
## Version
1.5.0
## Environment
chrome version:  69.0.3497.100
## Reproduction link
[https://stackblitz.com/edit/angular-otrup2](https://stackblitz.com/edit/angular-otrup2)
## Steps to reproduce
1. modal 的 content 为 template form，footer 的`Cancel`按钮有 `myForm.reset()`
2. 点击footer中的取消按钮时，报错：`Cannot read property 'reset' of undefined`
3. 同理，若`nzOnCancel`需执行 `myForm.reset()`时，点击 modal 的关闭按钮时，`nzOnCancel`报错：`Cannot read property 'reset' of undefined`
## What is expected?
点击 model 关闭按钮或“取消” 时，form 清空。
## What is actually happening?
点击 model 关闭按钮或“取消” 时，报错：Cannot read property 'reset' of undefined

**Comment by vthinkxie** [comment]
template vairable跨 ng-template是不会生效的，请注意这一点
