### ISSUE TITLE
nz-tree nzDefaultCheckedKeys bug

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#2186]
![tree bug](https://user-images.githubusercontent.com/18389869/45995460-bc4eae80-c0ca-11e8-9f65-3d7d0a28cbad.png)

1.6.0版 设置nzDefaultCheckedKeys时报错。1.5.0版无此问题。由于项目较复杂，不方便复现。抱歉在此简言之。

**Comment by simplejason** [comment]
看一下nzDefaultCheckedKeys传递的值是不是string数组

**Comment by liwei511** [comment]
检查了，是string数组
