### ISSUE TITLE
Table: Support default config

### ISSUE THREAD

**Issue by zMADCATz** [NG-ZORRO/ng-zorro-antd#2200]
## What problem does this feature solve?
I have multiple table in my application and I need config default value for nzNoResult text, nzSimple Pagination and etc
## What does the proposed API look like?
set default on providers like:
```
...,
{
      provide: NZ_TABLE_CONFIG,
      useValue: {
            nzNoResult: 'No Data',
            nzSimple: true
      }
}
```

**Comment by wendzhue** [comment]
In version 8.3.0 and later you can use global config feature to achieve this. I am closing this now. Please open another issue if you have more feature requests.
