### ISSUE TITLE
树组件增加删除节点功能

### ISSUE THREAD

**Issue by feiyingkeba** [NG-ZORRO/ng-zorro-antd#2202]
## What problem does this feature solve?
现在的树组件，在删除树节点时，只提供删除子节点功能，即node.ClearChildren().现在，删除节点的操作是，先获取该节点的父节点，然后通过调用父节点的ClearChildren()方法来达到删除功能。但是，此方法是删除所有的子节点。如果只想删除一个子节点，则调用此方法，与此子节点同级的其他节点也给一并删除了。这并不能达到要求。希望增加可以删除指定节点的功能。
## What does the proposed API look like?
Node.Remove()或者Node.Clear().

**Comment by simplejason** [comment]
可以自行使用splice方法实现，因为根节点无父节点，所以绑定在nzTreeNode上对于根节点删除会导致很多问题，可通过子节点 getParentNode().getChildren() 方法获得全部子节点，然后执行相关操作

**Comment by feiyingkeba** [comment]
我想获得的功能是删除指定的节点，而不是删除所有的子节点。 getParentNode().getChildren()仍然会删除了与该节点同级的所有子节点。

**Comment by feiyingkeba** [comment]
splice方法要指定节点的索引值，有时候是动态添加，删除节点的。删除之后，树组件并会动态的显示刷新的。

**Comment by feiyingkeba** [comment]
addChildren | 添加子节点,接收NzTreeNode或NzTreeNodeOptions数组,第二个参数为插入的索引位置 | (children: array, index?: number )=>{}
-- | -- | --

或者向addChildren一样，clearChildren在删除子节点的同时,可以指定删除节点的索引位置，来删除指定节点。
