### ISSUE TITLE
上传头像手动上传 无法显示缩略图

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#2203]
## Version
1.6.0
## Environment
antdesign v1.6  angular v6
## Reproduction link
[https://ng-zorro.github.io/components/upload/zh](https://ng-zorro.github.io/components/upload/zh)
## Steps to reproduce
无
## What is expected?
手动上传 时 可显示图片缩略图
## What is actually happening?
手动上传 时 可显示图片缩略图不能正常显示

**Comment by vthinkxie** [comment]
https://ng-zorro.gitee.io/docs/faq/zh
有些特性为什么不会被支持
ng-zorro-antd 是 Angular 版本 Ant Design 的实现，这意味着只有 Ant Design 支持的交互、功能 才会被 ng-zorro-antd 实现。

**Comment by liganggang** [comment]
自我矛盾啊 哥 ，为什么自动上传就支持

**Comment by liganggang** [comment]
这块 问题挺多的

**Comment by liganggang** [comment]
nzFileList

**Comment by vthinkxie** [comment]
@liganggang 参照react版本的交互实现，手动上传的时候整个file都在用户的掌控之下，你不可能要求控制一部分，不控制另外一部分

**Comment by liganggang** [comment]
原生的写 当你选择一个图片 也可以展示缩略图，手动上传即post数据 难道不是这样吗 按说ng-zorro也可以做到这点吧 还是我太菜了...

**Comment by vthinkxie** [comment]
@liganggang 你都用了手动上传了，file对象也获得了，和原生的写有什么区别么？

**Comment by liganggang** [comment]
确实可以获得  但是nzFileList不能正常显示选择后的图片呀 现在是这个问题呢

**Comment by liganggang** [comment]
beforeUpload = (file: UploadFile): boolean => {
      console.log(file)
    this.fileList.push(file)
    return false;
  }     push后  nzListType="picture" 不可以显示缩略图

**Comment by vthinkxie** [comment]
@cipchk plz check this.

**Comment by cipchk** [comment]
@liganggang  抱歉，我无法理解你的问题，麻烦提供一个完整重现示例。

**Comment by liganggang** [comment]
或许是你demo写的 不够详细 我已解决这个问题  明天再说  下班了

**Comment by liganggang** [comment]
不过还是有些问题

**Comment by liganggang** [comment]
手动上传图片，当我选择了图片后 nzfilelist未能显示选择后的缩略图 ，当我修改了下面代码后 选择了图片 鼠标点击缩略图才可以显示  不知道你看懂了没...
beforeUpload = (file): boolean => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = (arg) => {
        file.url = arg.target.result;
      }
    this.fileList.push(file);
    console.log(this.fileList)
    return false;
  }

**Comment by liganggang** [comment]
我可以 自己 用img来显示选择后的缩略图  这样就不能用你样式了

**Comment by liganggang** [comment]
兄弟 上班了没
