### ISSUE TITLE
The backdrop on select and select-like components should be transparent not dark

### ISSUE THREAD

**Issue by Synkretik** [NG-ZORRO/ng-zorro-antd#2204]
## Version
1.6.0
## Environment
Angular 6 
## Reproduction link
[https://angular-5jzpk9.stackblitz.io](https://angular-5jzpk9.stackblitz.io)
## Steps to reproduce
open a select or another component based on it.  The overlay has a class `.cdk-overlay-dark-backdrop`
## What is expected?
The overlay should be transparent  by using the   `.cdk-overlay-transparent-backdrop` class rather than setting the opacity to 0 
## What is actually happening?
some templates like http://angular-material.fusetheme.com will actually use the semantically correct  `.cdk-overlay-dark-backdrop`  and actually make it dark.  It would be semantically appropriate to ensure that the `.cdk-overlay-transparent-backdrop`  is applied in the case of input components.

**Comment by vthinkxie** [comment]
we will check it later, thanks for reporting.

**Comment by vthinkxie** [comment]
fixed in #2917
