### ISSUE TITLE
[Tree]getHalfCheckedNodeList can not get the nodes

### ISSUE THREAD

**Issue by DoesntWong** [NG-ZORRO/ng-zorro-antd#2205]
## Version
1.6.0
## Environment
Angular6
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-1tpsiy](https://stackblitz.com/edit/ng-zorro-antd-start-1tpsiy)
## Steps to reproduce
Initialize  nzCheckStrictly is true，then change to false.
Uncheck 0-0-0-0，click on the button to get halfCheckedNodeList，console print halfCheckedNodeList is []
## What is expected?
I want to get 0-0 and 0-0-0  node
## What is actually happening?
halfCheckedNodeList is []

**Comment by DoesntWong** [comment]
有没有一种方法，获取所有勾选，半选？

**Comment by simplejason** [comment]
@DoesntWong 你可以在nzCheckStrictly=false时，将返回的nzTreeNode数组遍历，取出全部节点和子节点ID
