### ISSUE TITLE
Conflict  when use  jhipster and zorro,the <td> selector range is too big 

### ISSUE THREAD

**Issue by wangkeshan9538** [NG-ZORRO/ng-zorro-antd#2207]
the log:
![image](https://user-images.githubusercontent.com/19386096/46239777-f15f4780-c3cf-11e8-8015-b0c242e5888a.png)
the reason is  :
Zorro:
![image](https://user-images.githubusercontent.com/19386096/46239857-8a429280-c3d1-11e8-8cb0-f09aa072b88f.png)
jhipster:
![image](https://user-images.githubusercontent.com/19386096/46239867-9cbccc00-c3d1-11e8-8e31-36d2af5e27ce.png).
i think  ":not(sub_selector)" is not good in it  ,the range is too big

**Comment by vthinkxie** [comment]
plz add `nz-disable-td` className to `td` element you do not want `ng-zorro-antd` to render
