### ISSUE TITLE
一个form表单下，patchValue给两个TreeSelect赋值，只有一个会有值，另一个有值不会显示选中的TreeSelect项

### ISSUE THREAD

**Issue by JCqiu** [NG-ZORRO/ng-zorro-antd#2209]
## Version
1.6.0
## Environment
win10,chrome69,1.6.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-tpdxye?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-tpdxye?file=src/app/app.component.ts)
## Steps to reproduce
一个form表单下，patchValue给两个TreeSelect赋值，只有一个会有值，另一个有值不会显示选中的TreeSelect项
## What is expected?
解决需求
## What is actually happening?
没有解决

**Comment by JCqiu** [comment]
@HsuanXyz 我把ngModelChange删除了就都会显示， 但是我需要ngModelChange的事件怎么处理呢

**Comment by HsuanXyz** [comment]
@JCqiu 用 form 应该用 `valueChanges`  https://angular.io/api/forms/AbstractControl
