### ISSUE TITLE
[BUG] Upload component and large file (800 mb )

### ISSUE THREAD

**Issue by Grinion** [NG-ZORRO/ng-zorro-antd#2216]
## Version
1.6.0
## Environment
Chrome 69.0.3497.100
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-hozp9w](https://stackblitz.com/edit/ng-zorro-antd-start-hozp9w)
## Steps to reproduce
Select lager file (which is bigger than 2 Gb  ) - result: immediately crash tab
OR 
Select lager file (which is bigger than 800 Mb  ) result: When progress bar value was about 40 % and next crash tab
## What is expected?
The tab should not crash
## What is actually happening?
The tab is crash

**Comment by vthinkxie** [comment]
plz try https://ng.ant.design/components/upload/zh#components-upload-demo-custom-request

**Comment by Grinion** [comment]
The result is the same

(Also, I try to do it on https://ant.design/components/upload/, there I don't get a crash tab)

**Comment by vthinkxie** [comment]
@cipchk plz check this.

**Comment by Grinion** [comment]
![](https://media.giphy.com/media/1Ajkj5AOLhQPFCGCka/giphy.gif)

**Comment by abdelrahmannasr** [comment]
Is there any way to use manual upload as file selector then preview the selected file if it an image

**Comment by cipchk** [comment]
@abdelrahmannasr You can use [nzPreviewFile](https://ng.ant.design/components/upload/zh#nz-upload) property.
