### ISSUE TITLE
input-group using 'nzAddOnBefore' and 'nzSuffix' not present as expect

### ISSUE THREAD

**Issue by code1986** [NG-ZORRO/ng-zorro-antd#2222]
## Version
1.6.0
## Environment
chrome
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-cj9p1b](https://stackblitz.com/edit/ng-zorro-antd-start-cj9p1b)
## Steps to reproduce
<div nz-row style="margin-top: 20px">
<div nz-col nzSpan="6" nzOffset="6">
  
    <nz-input-group nzAddOnBefore="http://www." nzSearch [nzSuffix]="suffixIconButton">
      <input type="text" nz-input name="dockerURL" [(ngModel)]="dockerURL" placeholder="something.com">
    </nz-input-group>
    <ng-template #suffixIconButton>
      <button nz-button (click)="onSearchWar()" nzType="primary" nzSearch><i class="anticon anticon-search"></i></button>
    </ng-template>

</div>
</div>
## What is expected?
search box in right place
## What is actually happening?
search box in the middle of input box

**Comment by vthinkxie** [comment]
ref https://github.com/ant-design/ant-design/issues/15048

**Comment by vthinkxie** [comment]
ref https://github.com/ant-design/ant-design/issues/15049

**Comment by vthinkxie** [comment]
this should work in latest verison now, try the code below
```html
<nz-input-group nzAddOnBefore="http://www." nzSearch [nzAddOnAfter]="suffixIconButton">
  <input type="text" nz-input name="dockerURL" placeholder="something.com">
</nz-input-group>
<ng-template #suffixIconButton>
  <button nz-button (click)="onSearchWar()" nzType="primary" nzSearch><i class="anticon anticon-search"></i></button>
</ng-template>
```
