### ISSUE TITLE
NzTreeNodeOptions增加一个控制项使父级的checked状态不影响子级

### ISSUE THREAD

**Issue by x-wk** [NG-ZORRO/ng-zorro-antd#2224]
## What problem does this feature solve?
NzTreeNodeOptions增加一个控制项使父级的checked状态不影响子级
## What does the proposed API look like?
无

**Comment by vthinkxie** [comment]
什么情况下会有这种需求，能详细描述下么？

**Comment by x-wk** [comment]
与[nzCheckStrictly]="true"时的行为保持一致 , 实际使用时发现选择时是完全受控的 , 但是回显时父子相互影响

**Comment by wendzhue** [comment]
Similar issue #2244. We need to clarify this problem.

**Comment by herohql521** [comment]
> 什么情况下有这种需求，能详细描述下么？

当某个child和parent没有关联关系的时候，没法单独设置nzCheckStrictly，目前个人解决办法整体设置成非受控，然后自己自定义受控关系，可是实现我想要的，但是我想在父子存在受控关系的时候，自定义父级半选，好像没有相应的api
