### ISSUE TITLE
[Bugs] carousel inside card

### ISSUE THREAD

**Issue by LiadIdan** [NG-ZORRO/ng-zorro-antd#2226]
## Version
1.6.0
## Environment
Chrome
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-bug](https://stackblitz.com/edit/ng-zorro-bug)
## Steps to reproduce
Check out the StackBlitz.
## What is expected?
The carousel contents shouldn't collapse and the carousel should recalculate the transform on rezise. Also, the menu item shouldn't remain selected when `nzSelected` return false.
## What is actually happening?
You can notice the first bug when the app loaded (the carousel contents collapses). The second bug occurs when you slide to different index and resize the page (the carousel isn't recalculating the transform). The last issue is in `nz-menu-item`, as you can see the first item remains selected even when `nzSelected` return false

**Comment by LiadIdan** [comment]
@wendzhue I've managed to fix the bugs related to the carousel, check out this [StackBlitz](https://stackblitz.com/edit/ng-zorro-carousel) and let me know what do you think.

**Comment by vthinkxie** [comment]
Hi @LiadIdan , just feel free to submit pr, we will review it.
thanks for your report!
