### ISSUE TITLE
body overflow and padding with drawer component

### ISSUE THREAD

**Issue by mortifactor** [NG-ZORRO/ng-zorro-antd#2227]
## Version
1.6.0
## Environment
Chrome
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-vqeu99](https://stackblitz.com/edit/ng-zorro-antd-start-vqeu99)
## Steps to reproduce
open devtools, go to body element, open drawer, see that padding style applies even if scrollbar does not exist
## What is expected?
do not apply padding style to body if scrollbar does not exist
## What is actually happening?
padding style applied to body, so all content moving to left
## Other?

![1](https://user-images.githubusercontent.com/1426349/46270147-2aceb900-c570-11e8-9906-b092ff73cdbb.gif)

**Comment by cipchk** [comment]
This is not `ng-drawer` problem. In fact, because of `ng-alain` beautified scroll bar width, resulting in `ng-drawer` inaccurate calculation width.

you can closed beautifiy scroll bar in `ng-alain`

```
@scrollbar-enabled: false;
```

**Comment by mortifactor** [comment]
Hello. Sorry for this issue is not of this project. I've tried `@scrollbar-enabled: false;` as you said, but it not works.
Could you please suggest more solutions?
I also made a stackblitz with ng-alain: [https://stackblitz.com/edit/ng-alain-3gacbk](url)
Anyway thank you.

**Comment by cipchk** [comment]
pls refer to https://ng-alain.com/theme/getting-started/en#How-to-override-parameters

**Comment by LiadIdan** [comment]
@cipchk I'm having the same issue and I'm not using `ng-alain`.
@mortifactor a quick workaround is to add ```padding: 0 !important;``` to the `body` tag.

**Comment by cipchk** [comment]
@vthinkxie , i guess need check the `NzMeasureScrollbarService` calculation value.

**Comment by vthinkxie** [comment]
will check it later

**Comment by repertory** [comment]
I have the same issue http://ng-antd-admin.demo.wangdong.io
