### ISSUE TITLE
Adjusting Tab Width (Module : Tabs)

### ISSUE THREAD

**Issue by sgokulnath** [NG-ZORRO/ng-zorro-antd#2242]
## What problem does this feature solve?
The Tabs module have certain set of useful features. I would like to have a fullWidth Tab set, where even if there are only 3 tabs, it covers the entire page. In the current set of options, there are lot of empty spaces, when the number of tabs are less.

## What does the proposed API look like?
<nz-tabset fullWidth>
     <nz-tab nzTitle = "Tab1"></nz-tab>
     <nz-tab nzTitle = "Tab2"></nz-tab>
     <nz-tab nzTitle = "Tab3"></nz-tab>
</nz-tabset>

**Comment by wendzhue** [comment]
You can achieve that by overriding CSS of `.ant-tabs-nav` and `.ant-tabs-tab` using flex. 

![stackblitz com_run_file src 2fapp 2fapp component ts](https://user-images.githubusercontent.com/12122021/46508703-4dfbb000-c871-11e8-8dda-43f513c79e0f.png)

If you consider it a design problem, please refer it to [Ant Design React](https://github.com/ant-design/ant-design).

**Comment by sgokulnath** [comment]
> You can achieve that by overriding CSS of `.ant-tabs-nav` and `.ant-tabs-tab` using flex.
> 
> You can clean up the CSS yourself. I guess `!important` is not necessary. You can also override it in `less` files. Whatever you like.
> 
> ![stackblitz com_run_file src 2fapp 2fapp component ts](https://user-images.githubusercontent.com/12122021/46508703-4dfbb000-c871-11e8-8dda-43f513c79e0f.png)
> 
> If you consider it a design problem, please refer it to [Ant Design React](https://github.com/ant-design/ant-design).

Thank you very much for your help. Works fine 👍

**Comment by wessamyaacob** [comment]
![image](https://user-images.githubusercontent.com/21978069/91646713-789d1600-ea52-11ea-8dcb-014ea697fa23.png)
I've tried the same css style but It didn't work ! is there any changes in the new versions affect the style ? there is a div before the first tab without any style when I tried to give it   `display: flex !important; width: 100% !important;` it works but still I can't catch it using simple css , any advice ?

**Comment by wessamyaacob** [comment]
I managed a good solution for that by access the first div after ant-tabs-tab 
```

::ng-deep .ant-tabs-nav {
  width: 100% !important;
}

::ng-deep .ant-tabs-tab {
  flex: 1;
  text-align: center;
}

::ng-deep .ant-tabs-nav > div:nth-of-type(1) {
  display: flex !important;
  width: 100% !important;
}

```

**Comment by hugobarragon** [comment]
Anyone with same issue on react above css does not work, here is the solucion  

[![Edit Basic - antd@4.16.3 tabs centered full width](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd4163-tabs-centered-full-width-oqi4n?fontsize=14&hidenavigation=1&theme=dark)  
  
  ```
.ant-tabs-nav {
  width: 100% !important;
}

.ant-tabs-tab {
  display: block; // centers text inside tabs
  flex: 1;
  text-align: center;
}

.ant-tabs-nav > div:nth-of-type(1) {
  display: unset !important;
  width: 100% !important;
}

  ```

**Comment by hullis** [comment]
> 为什么关闭，官方是否提供这个支持啊

目前官方设计库中没有对应的样式，可以通过覆写 CSS 自行实现。

**Comment by smile2014** [comment]
@hullis  已经解决了，谢谢回复
