### ISSUE TITLE
tree组件Checkbox 勾选问题，当nzData元数据从后台获取时，nzCheckedKeys与nzDefaultCheckedKeys无效，只要父节点checked为true时，子节点一定会被勾选，即使nzCheckStrictly为true

### ISSUE THREAD

**Issue by zzmmbb** [NG-ZORRO/ng-zorro-antd#2244]
html：
<nz-tree
    [(ngModel)]="nodes"
    [nzCheckable]="true"
    [nzCheckStrictly]='true'
    [nzDefaultExpandedKeys]="expandKeys"
    [nzDefaultCheckedKeys]="checkedKeys"
    [nzDefaultSelectedKeys]="selectedKeys"
    [nzDefaultExpandAll]="expandDefault"
    (nzClick)="mouseAction('click',$event)"
    (nzDblClick)="mouseAction('dblclick', $event)"
  >
  </nz-tree>

/**
** 代码只有部分 nodes数据无论是从后台获取还是后台响应后重新赋值 子节点都会被勾选上
**/
ts:
  expandKeys = [ '1001', '10001' ];
  checkedKeys = [ '1001', '10001', '100011' ];
  selectedKeys = [ '1001', '10001', '100011' ];
  expandDefault = false;
  checkedArrry: any;
  loginObj: any;
  nodes = [
  ];

this.http.post(url, this.toHttpParams(obj))
      .subscribe((val: any) => {
          this.nodes = [
            new NzTreeNode({
              title   : 'root1',
              key     : '1001',
              checked: false,
              children: [
                {
                  title   : 'child1',
                  key     : '10001',
                  checked: true,
                  children: [
                    {
                      title : 'child1.1',
                      key   : '100011',
                      isLeaf: true,
                      checked: false,
                    },
                    {
                      title : 'child1.2',
                      key   : '100012',
                      isLeaf: true
                    }
                  ]
                },
                {
                  title   : 'child2',
                  key     : '10002',
                  children: [
                    {
                      title   : 'grandchild1.2.1',
                      key     : '1000121',
                      isLeaf  : true,
                      disabled: true
                    },
                    {
                      title : 'grandchild1.2.2',
                      key   : '1000122',
                      isLeaf: true
                    }
                  ]
                }
              ]
            })
          ];
        },
        response => {
          console.log( response.currentTarget.response);
        },
        () => {
          console.log('The POST observable is now completed.');
        });
  }

**Comment by wendzhue** [comment]
@zzmmbb 感谢你的反馈, 请在上面的 issue 追踪这个问题.
