### ISSUE TITLE
嵌套List列表组件，[nzItemLayout] 总会应用外部的List组件，内部的值无效

### ISSUE THREAD

**Issue by xcorpio** [NG-ZORRO/ng-zorro-antd#2245]
## Version
1.6.0
## Environment
macos, chrome latest
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-jvgr9f](https://stackblitz.com/edit/ng-zorro-antd-start-jvgr9f)
## Steps to reproduce
1. https://stackblitz.com/edit/ng-zorro-antd-start-jvgr9f

2. 外部的`List` 设置 `nzItemLayout="vertical"`, 嵌套的设置 `horizontal`

## What is expected?
顶部的`nzItemLayout`属性，不该覆盖内部的`nzItemLayout`
## What is actually happening?
内部的`List` 的 `nzItemLayout` 设置无效

**Comment by cipchk** [comment]
antd 竖排的定义是指 item 内容部分，可以明确外层并不会覆盖内层的情况。

> 建议进一步描述所要实现的效果细节

**Comment by xcorpio** [comment]
![311539092807_ pic_hd](https://user-images.githubusercontent.com/4575409/46673963-99191880-cc0d-11e8-8ba4-4f92d8a4780d.jpg)
![321539092867_ pic_hd](https://user-images.githubusercontent.com/4575409/46673990-a59d7100-cc0d-11e8-96f3-e80c222f13ec.jpg)
![331539093136_ pic_hd](https://user-images.githubusercontent.com/4575409/46673998-a8986180-cc0d-11e8-8744-4ad74b6856c0.jpg)

**Comment by xcorpio** [comment]
就是 外面的是 `vertical` 里面的是 `horizontal ` 这种情况下,  `nzActions`显示的好像不对，里外都按垂直显示的

**Comment by cipchk** [comment]
请认真参考 http://ng.ant.design/components/list/zh#components-list-demo-vertical  写法，以及 API 的正确使用，特别是示例中 `nzContent` 的写法并不正确。

**Comment by xcorpio** [comment]
`nzContent ` 这样吧, 还是不行，没看出其他什么地方用法不对🤔
```html
<ng-template #nzContent>
```
