### ISSUE TITLE
Cascader still have fixed size, no matter of menu height

### ISSUE THREAD

**Issue by poomponk** [NG-ZORRO/ng-zorro-antd#2252]
## Version
1.6.0
## Environment
stackblitz and my
## Reproduction link
[https://ng-zorro-antd-start-3egf4x.stackblitz.io](https://ng-zorro-antd-start-3egf4x.stackblitz.io)
## Steps to reproduce
nzMenuStyle = { height: '500px' }; 
 
<nz-cascader [nzMenuStyle]="nzMenuStyle"></nz-cascader>
## What is expected?
Cascader shows more elements without scroll
## What is actually happening?
Casceder dropdown menu size is stlll fixed, dropdown menu is huge
## Other?
Also looks bad if height < default

**Comment by wendzhue** [comment]
@poomponk 

If you take a look at the DOM structure, and you would find all that options are wrapped in a `ul` element whose class name contains `ant-cascader-menu` that determines the `ul`'s height. You can achieve what you want by overriding this CSS class.

Our `.less` files are derived from [`antd`](https://github.com/ant-design/ant-design) which means we are not going to change them. If you consider it a bug (actually what can be resolved by CSS wouldn't be considerer as), you can report this issue to them. Thanks for your reporting.
