### ISSUE TITLE
Good news! Working Server-Side rendering

### ISSUE THREAD

**Issue by vlados** [NG-ZORRO/ng-zorro-antd#2253]
You can use https://github.com/Angular-RU/angular-universal-starter or use [their solution](https://github.com/Angular-RU/angular-universal-starter/blob/master/defined.md) for Angular Universal. 
**I've tested it with few components and everything was working**

**Comment by vlados** [comment]
#983 #43 #1826 #1936

**Comment by vthinkxie** [comment]
duplicated #43
