### ISSUE TITLE
ng-zorro nz-select 使用服务器搜索、多选模式时，在IE环境下，搜索框不能显示全部字符

### ISSUE THREAD

**Issue by bairitan** [NG-ZORRO/ng-zorro-antd#2257]
## Version
1.6.0
## Environment
windows ie11
## Reproduction link
[https://stackblitz.com/edit/angular-uqnua8](https://stackblitz.com/edit/angular-uqnua8)
## Steps to reproduce
nz-select 设置nzMode="multiple" nzAllowClear nzShowSearch [nzServerSearch]="true"。
官网示例也有该问题：
https://ng.ant.design/components/select/zh 下的“搜索用户一个带有远程搜索，节流控制，请求时序控制，加载状态的多选示例。”
## What is expected?
选择器输入框能显示全部字符
## What is actually happening?
选择器输入框能未能显示全部字符，只显示了输入的最后一个字符，前面的字符被隐藏

**Comment by Credo-Zhao** [comment]
IE should be die

**Comment by vthinkxie** [comment]
plz track #2427
and this comment may help
https://github.com/NG-ZORRO/ng-zorro-antd/issues/2427#issuecomment-481211182
