### ISSUE TITLE
inputNumber输入框输入数字不会触发ngModelChange事件

### ISSUE THREAD

**Issue by zhuxm0217** [NG-ZORRO/ng-zorro-antd#2258]
## Version
1.6.0
## Environment
win7 chrome ng-zorro最新版本
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-fpnqr2?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-fpnqr2?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
输入数字不会触发ngModelChange
## What is expected?
输入数字触发ngModelChange
## What is actually happening?
输入数字不会触发ngModelChange

**Comment by vthinkxie** [comment]
duplicated https://github.com/NG-ZORRO/ng-zorro-antd/issues/2151
