### ISSUE TITLE
nz-tree 动态设置disabled属性无效？

### ISSUE THREAD

**Issue by lishaoh** [NG-ZORRO/ng-zorro-antd#2264]
## What problem does this feature solve?
通过按钮点击控制nz-tree的可选状态，但是现在可选状态只是默认的状态，无法动态更新
## What does the proposed API look like?
```ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { NzFormatEmitEvent, NzTreeNode, NzTreeNodeOptions } from 'ng-zorro-antd';

@Component({
  selector: 'nz-demo-tree-basic',
  template: `
    <nz-tree
      #treeCom
      [nzData]="nodes"
      nzCheckable="true"
      nzMultiple="true"
      [nzCheckedKeys]="defaultCheckedKeys"
      [nzExpandedKeys]="defaultExpandedKeys"
      [nzSelectedKeys]="defaultSelectedKeys"
      (nzClick)="nzClick($event)"
      (nzCheckBoxChange)="nzCheck($event)">
    </nz-tree>
    <button (click)="test()">disabled</button>
  `
})
export class NzDemoTreeBasicComponent implements OnInit {
  @ViewChild('treeCom') treeCom;
  defaultCheckedKeys = [ '1001', '1002' ];
  defaultSelectedKeys = [ '10011' ];
  defaultExpandedKeys = [ '100', '1001' ];

  nodes: NzTreeNodeOptions[] = [ {
    title   : 'parent 1',
    key     : '100',
    children: [ {
      title   : 'parent 1-0',
      key     : '1001',
      disabled: true,
      children: [
        { title: 'leaf 1-0-0', key: '10010', disableCheckbox: true, isLeaf: true },
        { title: 'leaf 1-0-1', key: '10011', isLeaf: true, checked: true }
      ]
    }, {
      title   : 'parent 1-1',
      key     : '1002',
      children: [
        { title: 'leaf 1-1-0', key: '10020', isLeaf: true }
      ]
    } ]
  } ];

## 点击切换可选状态
  test() {
    this.nodes[0].children[0].disabled = false;
    this.nodes[0].children[0].children[0].disableCheckbox = false;
  }

  ngOnInit(): void {
    setTimeout(() => {
      console.log(this.treeCom.getTreeNodes(), this.treeCom.getCheckedNodeList());
    }, 500);

  }
}
```

**Comment by Fyniny** [comment]
> ## What problem does this feature solve?
> 通过按钮点击控制nz-tree的可选状态，但是现在可选状态只是默认的状态，无法动态更新
> 
> ## What does the proposed API look like?
> ```ts
> import { Component, OnInit, ViewChild } from '@angular/core';
> import { NzFormatEmitEvent, NzTreeNode, NzTreeNodeOptions } from 'ng-zorro-antd';
> 
> @Component({
>   selector: 'nz-demo-tree-basic',
>   template: `
>     <nz-tree
>       #treeCom
>       [nzData]="nodes"
>       nzCheckable="true"
>       nzMultiple="true"
>       [nzCheckedKeys]="defaultCheckedKeys"
>       [nzExpandedKeys]="defaultExpandedKeys"
>       [nzSelectedKeys]="defaultSelectedKeys"
>       (nzClick)="nzClick($event)"
>       (nzCheckBoxChange)="nzCheck($event)">
>     </nz-tree>
>     <button (click)="test()">disabled</button>
>   `
> })
> export class NzDemoTreeBasicComponent implements OnInit {
>   @ViewChild('treeCom') treeCom;
>   defaultCheckedKeys = [ '1001', '1002' ];
>   defaultSelectedKeys = [ '10011' ];
>   defaultExpandedKeys = [ '100', '1001' ];
> 
>   nodes: NzTreeNodeOptions[] = [ {
>     title   : 'parent 1',
>     key     : '100',
>     children: [ {
>       title   : 'parent 1-0',
>       key     : '1001',
>       disabled: true,
>       children: [
>         { title: 'leaf 1-0-0', key: '10010', disableCheckbox: true, isLeaf: true },
>         { title: 'leaf 1-0-1', key: '10011', isLeaf: true, checked: true }
>       ]
>     }, {
>       title   : 'parent 1-1',
>       key     : '1002',
>       children: [
>         { title: 'leaf 1-1-0', key: '10020', isLeaf: true }
>       ]
>     } ]
>   } ];
> 
> ## 点击切换可选状态
>   test() {
>     this.nodes[0].children[0].disabled = false;
>     this.nodes[0].children[0].children[0].disableCheckbox = false;
>   }
> 
>   ngOnInit(): void {
>     setTimeout(() => {
>       console.log(this.treeCom.getTreeNodes(), this.treeCom.getCheckedNodeList());
>     }, 500);
> 
>   }
> }
> ```

我nzData属性 angular提示不存在，请问您知道怎么做吗

**Comment by simplejason** [comment]
angular不会检测对象值变化，你可以通过getTreeNodes方法获取NzTreeNode数组，然后修改isDisabled属性来实现禁用，nzData属性只在ng-zorro 1.6.0及以后版本支持

**Comment by lishaoh** [comment]
@simplejason 修改了isDisabled后有set方法来实现树节点更新吗？
