### ISSUE TITLE
[Bug] Drawer mask transition in production

### ISSUE THREAD

**Issue by LiadIdan** [NG-ZORRO/ng-zorro-antd#2265]
## Version
1.6.0
## Environment
chrome/firefox/edge
## Reproduction link
[https://drawer-mask-bug.stackblitz.io](https://drawer-mask-bug.stackblitz.io)
## Steps to reproduce
build an app with a drawer in production mode.
## What is expected?
the drawer mask transition should only fade out on drawer close
## What is actually happening?
the drawer mask fade out up on drawer close

**Comment by cipchk** [comment]
Another reproduce [example](https://ng-alain.com/components/table/en#components-table-buttons) in ng-alain. @HsuanXyz

**Comment by HsuanXyz** [comment]
@cipchk @LiadIdan Downgrade clean-css  `"clean-css": "~4.1.11"`.

This is angular-cli bug https://github.com/angular/angular-cli/issues/12408

**Comment by vthinkxie** [comment]
@HsuanXyz try to fix it with this comment
https://github.com/angular/angular-cli/issues/12408#issuecomment-427879892

**Comment by HsuanXyz** [comment]
@vthinkxie https://github.com/angular/angular-cli/pull/12565

**Comment by HsuanXyz** [comment]
Close via [CLI for Angular v7.0](https://github.com/angular/angular-cli/releases/tag/v7.0.1)

**Comment by HsuanXyz** [comment]
Close via [CLI for Angular v7.0](https://github.com/angular/angular-cli/releases/tag/v7.0.1)
