### ISSUE TITLE
NzModalService组建弹出层里的nz-input如何才能获取到聚焦

### ISSUE THREAD

**Issue by Hangoro-Yang** [NG-ZORRO/ng-zorro-antd#2269]
## What problem does this feature solve?
弹出层默认聚焦在第一个input组件里，回车后可以自动聚焦到下一个input组件
## What does the proposed API look like?
弹出层默认聚焦在第一个input组件里，回车后可以自动聚焦到下一个input组件

**Comment by Hangoro-Yang** [comment]
父级component部分代码
showDetail(a) {
    const subscription = this.modalService.open({
      title          : `xxxxx`,
      content        : ChildComponent,
      onOk() {},
      onCancel() {},
      footer         : false,
      maskClosable: false,
      componentParams: { a: a}
    });
}
子级ChildComponent.html部分代码如下
<div nz-form-control nz-col [nzSm]="14" [nzXs]="24">
        <nz-input #inputThroneCd [nzSize]="'large'" formControlName="throneCd" [nzId]="'throneCd'" (keyup.enter)="scanThroneCd()"></nz-input>
      </div>
子级ChildComponent.ts部分代码如下
@ViewChild('inputThroneCd') inputThroneCd;
  @ViewChild('inputBarcode') inputBarcode;

  constructor(
    private fb: FormBuilder,
    public msg: NzMessageService,
    private subject: NzModalSubject
  ) {
    setTimeout(() => {
      console.log("无法聚焦的nz-input")
      this.inputThroneCd._el.querySelector('input').focus;
    }, 500)
}

**Comment by HsuanXyz** [comment]
@Hangoro-Yang 你再看看文档 https://angular.cn/api/core/ViewChild

**Comment by Hangoro-Yang** [comment]
@HsuanXyz 不知道下面加粗的那句写的不对，我做了简单的测试，还是聚焦不到
`@Component({
  selector: 'app-lens-scan-code',
  template: `<nz-input #inputThroneCd [nzSize]="'large'" [nzId]="'throneCd'"></nz-input>`,
  styles: []
})
export class LensScanCodeComponent implements OnInit {
  @ViewChild('inputThroneCd') inputThroneCd;
  constructor(
  ) {
    setTimeout(() => {
      console.log("无法聚焦")
      **this.inputThroneCd._el.querySelector('input').focus;**
    }, 500)
  }
  ngOnInit(): void {

  }
}`

**Comment by Hangoro-Yang** [comment]
这样就可以了 @HsuanXyz 谢谢
`@Component({
  selector: 'app-lens-scan-code',
  template: `<nz-input #inputThroneCd ></nz-input>`,
  styles: []
})
export class LensScanCodeComponent implements AfterViewInit,OnInit {
  @ViewChild('inputThroneCd') inputThroneCd;
  constructor(
  ) {
    // console.log("无法聚焦")
    // console.log(this.inputThroneCd)
    // this.inputThroneCd._el.querySelector('input').autofocus = true;
    // // this.inputThroneCd.nativeElement.autofocus = true;
  }

  ngAfterViewInit() {
    console.log("聚焦")
    this.inputThroneCd._el.querySelector('input').autofocus = true;
    // this.inputThroneCd.nativeElement.autofocus = true;
  }

  ngOnInit(): void {

  }
}`
