### ISSUE TITLE
Select component dont support custom option

### ISSUE THREAD

**Issue by deart1mer** [NG-ZORRO/ng-zorro-antd#227]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

In the current implementation, the nz-option component does not render, so the content projection can not be added to the nz-option.

## Expected behavior

Support custom option like this:

```html
<nz-select [(ngModel)]="selectedOption" nzAllowClear>
  <nz-option *ngFor="let option of options" [nzValue]="option" [nzDisabled]="option.disabled">
    <!-- custom option here -->
    <icon class="an-icon"><icon>{{option.label}}
  </nz-option>
</nz-select>
```

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by wilsoncook** [comment]
An easy implementation would be, let the `nzLabel` attribute to support `html` strings, of cause, if the html option being chosen, here needs to strip all html tags to be shown as selected.

**Comment by deart1mer** [comment]
@wilsoncook Hi. I think that immediately using `nz-option`(use the node projection for `nz-option` in `nz-select`) instead of now using a pipe to transform it as a object is a better way. After that users could customize their template that would be projected to the `ng-content` of `nz-option` component.

Such like follow fake code: 
```html
<!-- template of nzSelectComponent -->
<select>
  <ng-content></ng-content>
</select>
```

```html
<!-- template of nzOptionComponent -->
<option>
  <ng-content></ng-content>
</option>
```

Template of user's component: 

```html
<nz-select>
  <nz-option *ngFor="..."> freestyle here </nz-option>
</nz-select>
```

**Comment by wilsoncook** [comment]
@deart1mer Yes the way using content projection is standard and easy to use like this issue illustrated above. Since the code of `nz-select` that formerly archived business goals in a short time, it's complicated and quite a bit redundant with potential issues, the code maybe refactored in the near future, so, i'm thinking about an easy implementation as said.
(It is pleasure to have a PR in your spare time, if any)   :-)

**Comment by deart1mer** [comment]
@wilsoncook Got it. It is my pleasure if I could do any help. This project is really great.

**Comment by wilsoncook** [comment]
@deart1mer Thank you sincerely for supporting!
