### ISSUE TITLE
nz-upload 设置 [nzSize] 限制文件大小后，当超出指定大小后，可否增加提示框，提醒用户已超出限定大小？

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd#2270]
## Version
1.6.0
## Environment
ng-zorro 1.6
## Reproduction link
[https://stackblitz.com/edit/angular-guayg2?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-guayg2?file=src/app/app.component.ts)
## Steps to reproduce
```<nz-upload [nzSize]='1000'></nz-upload>```
## What is expected?
当超出指定大小后，可否增加提示框，提醒用户已超出限定大小。 或者可以触发 (nzChange) 事件。
## What is actually happening?
没有任何提醒，直接返回。

**Comment by wendzhue** [comment]
https://ng-zorro.gitee.io/components/upload/zh#components-upload-demo-avatar 这个 Demo 里面的交互能否满足你的需求? 

@cipchk 复现里面提示 tooltip 显示 Unknown Error, 这个是可配置的吗?

**Comment by cipchk** [comment]
@dusdong  也可以通过自定义 `nzFilter` 重新定义名称（`name`）为 `limit` 或 `size` 来覆盖内置的检查机制，实现更多交互。
