### ISSUE TITLE
nz-tree children node setChecked(true) can not change they parent node 's isHalfChecked status

### ISSUE THREAD

**Issue by lovedemo** [NG-ZORRO/ng-zorro-antd#2273]
## Version
1.6.0
## Environment
win10,ng-zorro-antd 1.6.0 ,angular 6.1.0 
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-rspuw7](https://stackblitz.com/edit/ng-zorro-antd-start-rspuw7)
## Steps to reproduce
点击链接 ，点击叶子节点，
## What is expected?
点击叶子节点时，父节点的状态应该改变
## What is actually happening?
点击叶子节点，父节点的状态不对
## Other?
实现点击title选中叶子节点

**Comment by wendzhue** [comment]
To specify the case: click 0-0-2 in title and 0-0 is not half-selected. @simplejason
