### ISSUE TITLE
code-expand CSS problem on IE

### ISSUE THREAD

**Issue by wenqi73** [NG-ZORRO/ng-zorro-antd#2274]
## Version
1.6.0
## Environment
Win 7 IE Edge
## Reproduction link
[http://ng.ant.design/components/button/zh](http://ng.ant.design/components/button/zh)
## Steps to reproduce
Open official site
## What is actually happening?
CSS has problem
![57xr l_o1 e3p pa3 sq 9](https://user-images.githubusercontent.com/23337087/46912441-121ac600-cfa8-11e8-9d57-1315426bd4a1.png)

## Other?

https://github.com/ant-design/ant-design/blob/b04fefe0479d20b36645011fa4e49f9b1f6ec80d/site/theme/static/demo.less#L127

Can ng-zorro-bot also synchronize site less ?

**Comment by wendzhue** [comment]
It seems OK on Windows 10 Edge. Is it specific to Windows 7 or IE? Which version of IE do you use? @wenqi73

**Comment by wenqi73** [comment]
Windows 7 IE 11

![8dn cc 04l e a1dybf2 36](https://user-images.githubusercontent.com/23337087/46913901-a39a3000-cfc8-11e8-88bf-6295a22a1a47.png)

**Comment by wendzhue** [comment]
@wenqi73 OK... We actually didn't have a Windows 7 devices at hands now. But we would try to fix it by sync the styles.

**Comment by wenqi73** [comment]
@wendzhue Fixing this manually ?  Can ng-zorro-bot sync the styles ?

**Comment by wendzhue** [comment]
@wenqi73 Try this: https://deploy-preview-2284--ng-zorro-master.netlify.com/. Is the problem still there.

Bot cannot help in this situation because some styles are not the same.

**Comment by wenqi73** [comment]
:ok_hand:  It's normal now
![57k 3 f_ jvu7v7z6z02k_o](https://user-images.githubusercontent.com/23337087/47022125-62a04800-d18f-11e8-8e0f-5b3f196c1468.png)
