### ISSUE TITLE
While using customize directory tree together with searchable Tree, color of the filter node will not change to red

### ISSUE THREAD

**Issue by joyshen0829** [NG-ZORRO/ng-zorro-antd#2275]
## Version
1.6.0
## Environment
Angular
## Reproduction link
[https://ng-zorro-antd-start.stackblitz.io/](https://ng-zorro-antd-start.stackblitz.io/)
## Steps to reproduce
While using customize directory tree together with searchable Tree, color of the filter node will not change to red
## What is expected?
While using customize directory tree and searchable Tree, color of the filter node will change to red
## What is actually happening?
While using customize directory tree and searchable Tree, color of the filter node will not change to red
## Other?
![image](https://user-images.githubusercontent.com/42802741/46925057-71d2a900-d05c-11e8-88d9-ea8cba389445.png)

**Comment by simplejason** [comment]
if u use NzTemplate to render nodes,you must render it yourself.(with NzTreeNode.isMatched)

**Comment by joyshen0829** [comment]
Thanks for your answer.

**Comment by cnnicknick** [comment]
Thanks for your answer.
