### ISSUE TITLE
nz-table scroll can follow data scrolling

### ISSUE THREAD

**Issue by BecksWang** [NG-ZORRO/ng-zorro-antd#2279]
## What problem does this feature solve?
When the data of the table is added one by one, the scroll bar needs to be scrolled synchronously with the data, or the scroll bar can be kept at the bottom.
## What does the proposed API look like?
Give an attribute whether the scroll bar scrolls to the bottom or can scroll to a location

**Comment by BecksWang** [comment]
Or how do I control the scrollbar inside the table?

**Comment by vthinkxie** [comment]
you can control scrollbar yourself
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop

**Comment by BecksWang** [comment]
Thank you for your answer;But how should I get the scroll, I have tried several methods and I have not obtained it.

**Comment by BecksWang** [comment]
![menu saveimg savepath20181015175850](https://user-images.githubusercontent.com/33107864/46944212-17f5d180-d0a4-11e8-85d9-3374f6a108b9.jpg)

**Comment by BecksWang** [comment]
I have seen the html code it produces, but it is confusing to get the scrollbar through both document and window.

**Comment by BecksWang** [comment]
Or can you give this div a unique identifier for easy access?
