### ISSUE TITLE
Some custom form controls touched state would not be changed

### ISSUE THREAD

**Issue by deart1mer** [NG-ZORRO/ng-zorro-antd#228]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

Some custom form controls (nz-input-number, nz-radio, select, datepicker, timepicker, etc) will not change touched state after touch(blur).

## Expected behavior

Change touched state when user touch it.

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
Yes, registerOnTouched is not called when touch event trigger.
