### ISSUE TITLE
当NzSelect因为Tab键进入时候，搜索下拉框没有打开

### ISSUE THREAD

**Issue by vincywindy** [NG-ZORRO/ng-zorro-antd#2281]
## What problem does this feature solve?
当一个表单有很多元素的时候，使用Tab进行表单元素间切换是很正常的，而目前当Tab进入NzSelect的时候，搜索文本框并没有获取到焦点，必须再按一次Tab键然后按下方向键才能是的文本框获取焦点 打开下拉框
## What does the proposed API look like?
按下Tab进入Select的时候，搜索框自动获取焦点并且弹出下拉框，这样能提升表单录入的连贯性

**Comment by wendzhue** [comment]
@vincywindy 没有必须 再按 一次方向键才可以打开下拉框, 只要 select 本身获取了焦点就可以通过空格键或者方向键展开下拉框.

HTML 本身的 select 元素也不是 focus 的时候就会自动展开的, 你可以自行尝试, ant design 当然要遵守默认元素的行为.

不过我们会让支持搜索的 select 自动聚焦输入框, 这 issue 会被关闭.

**Comment by zlhgo** [comment]
@wendzhue 希望能加入按回车键也能弹出下拉列表，0.6.x版本支持回车键弹出下拉列表。
