### ISSUE TITLE
Notification and Message does't created on global error catch

### ISSUE THREAD

**Issue by tinybaby** [NG-ZORRO/ng-zorro-antd#2282]
## Version
1.6.0
## Environment
ng6
## Reproduction link
[https://stackblitz.com/edit/angular-9m1eyi](https://stackblitz.com/edit/angular-9m1eyi)
## Steps to reproduce
look at demo 
## What is expected?
正确的弹出提示
## What is actually happening?
需要再点一次按钮才弹出

**Comment by wendzhue** [comment]
@tinybaby 即使是 button 的样式也不能正确的应用上, 请使用我们提供的 startup 来创建复现链接. https://stackblitz.com/edit/ng-zorro-antd-start

请保持最小复现. 我们在自己的项目中也用到了 errorHandler, 没有这种问题. 提供最小复现有助于你发现代码中的问题.

**Comment by liwei511** [comment]
因为请求超过Notification默认时长，你把Notification时间设长或者请求结束后create Notification 试一下。

**Comment by tinybaby** [comment]
@wendzhue https://stackblitz.com/edit/angular-9m1eyi 已经修正样式问题， 第一次请求返回 403 ，是不会弹出通知框的，但再点击一次就会弹出来 了。

**Comment by tinybaby** [comment]
`const appRef = this.injector.get(ApplicationRef);
      appRef.tick();`
fix.

**Comment by Bonelol** [comment]
引入zone：NgZone， 然后this.zone.run(...display notification)，感觉更好。
