### ISSUE TITLE
BUG appears when dynamically adding a List item.

### ISSUE THREAD

**Issue by ismezy** [NG-ZORRO/ng-zorro-antd#2287]
## Version
1.6.0
## Environment
chrome 69.0.3497.100 , windows 10
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-x1escz](https://stackblitz.com/edit/ng-zorro-antd-start-x1escz)
## Steps to reproduce
app.component.html
```html
<button nz-button nzType="primary" (click)="add()">Button</button>

<nz-list [nzDataSource]="list" [nzRenderItem]="item">
  <ng-template #item let-item>
    <nz-list-item [nzContent]="item"></nz-list-item>
  </ng-template>
</nz-list>
```

app.component.ts
```javascript
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  list = [];
  i = 0;
  constructor(private view:ViewContainerRef){

  }
  add(){
    this.list = [...this.list,   this.i];
  }
}
```
When the list is initially empty, the list is clicked the second time when the button is added....
## What is expected?
The list item is displayed on the first click.
## What is actually happening?
But it is displayed on the second click.

**Comment by vthinkxie** [comment]
fixed in 1.7.1 closed https://stackblitz.com/edit/ng-zorro-antd-start-gjp5mc?file=src/app/app.component.ts
