### ISSUE TITLE
nz-upload beforeUpload gets triggered when dropping multiple items when it shouldn't

### ISSUE THREAD

**Issue by DennisJaamann** [NG-ZORRO/ng-zorro-antd#2288]
## What problem does this feature solve?
The component should show an error state when we try to drag and drop multiple files even when multiple is false and / or limit 1

## What does the proposed API look like?
I would expect that if we set either:
- Limit to 1 
- Multiple to false

That beforeupload would not be triggered when dropping for example 5 images on the component. Furthermore the component should show the error state when dropping more files than allowed.

**Comment by cipchk** [comment]
You can using @Input property `[nzFilter]` override default size & type rules.
