### ISSUE TITLE
NzTree 使用icon属性的时候，getTreeNodes()里获取的NzTreeNode里没有icon属性，需要在NzTreeNode中增加该属性

### ISSUE THREAD

**Issue by karvint** [NG-ZORRO/ng-zorro-antd#2289]
## What problem does this feature solve?
动态修改树的时候能够简单的获取icon属性
## What does the proposed API look like?
在NzTreeNode中增加icon属性

**Comment by jys2013** [comment]
遇到同样的问题，无法解决

**Comment by Canyouhearme** [comment]
同求同求

**Comment by karvint** [comment]
> 可以直接使用NzTreeNode.origin获取元素，可以描述一下需求[demo](https://stackblitz.com/edit/angular-gycqg3?embed=1&file=src/app/app.component.ts)

origin获取的只是元数据，但是如果动态的添加叶子节点，origin中是没有这个新增加的叶子节点的。
目前我保存的方式是使用getTreeNodes()方法获取整棵树，但没有icon属性，希望能在构造的时候顺便加上icon的属性

**Comment by karvint** [comment]
@simplejason 谢谢大佬，解决了
