### ISSUE TITLE
多表头表格，宽度列设置偏差

### ISSUE THREAD

**Issue by hstarorg** [NG-ZORRO/ng-zorro-antd#2294]
## Version
1.6.0
## Environment
Windows
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-g6qb8x](https://stackblitz.com/edit/ng-zorro-antd-start-g6qb8x)
## Steps to reproduce
双重表格，设置最后一个th宽度
## What is expected?
设置成功
## What is actually happening?
宽度设置有误

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-h1oz9q?file=src/app/app.component.html

**Comment by hstarorg** [comment]
@vthinkxie The last column width is not my except. 
![gh1](https://user-images.githubusercontent.com/4043284/47579588-069fa580-d97f-11e8-9668-1e3c10b0e4f3.png)
You are not calc the `colspan` for build colgroup with width.
![gh2](https://user-images.githubusercontent.com/4043284/47579674-3d75bb80-d97f-11e8-95c9-8889bc7f789b.png)
