### ISSUE TITLE
升级angular7.0.0报错

### ISSUE THREAD

**Issue by TxOne** [NG-ZORRO/ng-zorro-antd#2297]
## Version
1.6.0
## Environment
angular cli 7.0.1
## Reproduction link
[https://github.com/angular/angular](https://github.com/angular/angular)
## Steps to reproduce
d:\workspace\Media\web>ng update @angular/core
                  Package "ng-zorro-antd" has an incompatible peer dependency to "typescript" (requires "~2.9.2", would install "3.1.3").
Incompatible peer dependencies found. See above.
## What is expected?
success
## What is actually happening?
d:\workspace\Media\web>ng update @angular/core
                  Package "ng-zorro-antd" has an incompatible peer dependency to "typescript" (requires "~2.9.2", would install "3.1.3").
Incompatible peer dependencies found. See above.

**Comment by vthinkxie** [comment]
<img width="482" alt="2018-10-19 11 51 36" src="https://user-images.githubusercontent.com/1506722/47196893-8e8d1a80-d395-11e8-853e-4a2c4010f891.png">

**Comment by zhaoqian** [comment]
we have any plans to support angular new version?

**Comment by vthinkxie** [comment]
will support in the next version.

**Comment by zhaoqian** [comment]
> will support in the next version.

thanks.

> Ref #2025

sorry,I should see roadmap.
thanks for u
