### ISSUE TITLE
按照官方的快速开始，编译出错

### ISSUE THREAD

**Issue by yiranlee** [NG-ZORRO/ng-zorro-antd#23]
在执行ng serve --port 0 --open，报错
<img width="748" alt="b5a6098b-6291-4dc5-93fb-33ae0c79547c" src="https://user-images.githubusercontent.com/27332318/29345827-e72e101e-8273-11e7-83c0-cc71f4b0dc80.png">

**Comment by vthinkxie** [comment]
try to update cli to the latest version, rm -rf node_modules, and retry again

**Comment by yiranlee** [comment]
the angular/cli and the ng-zorro-antd were the latest version

**Comment by trotyl** [comment]
![image](https://user-images.githubusercontent.com/6059170/29345985-efb0177c-8274-11e7-89da-d9b5b6d406c6.png)

Agree this is a bug, `@angular/***`s shouldn't be made into `dependencies`, it would cause sub dependencies being installed when version not being the same.

**Comment by wilsoncook** [comment]
Agree with @trotyl , may it's time to remove dependencies that not privately needs

**Comment by wilsoncook** [comment]
@yiranlee 
1. Could you please provide more information about your local dev environment ?
2. Did you encounter with any errors or warnings while npm install ng-zorro-antd ?

**Comment by taozhiw** [comment]
![ng-zero](https://user-images.githubusercontent.com/8348553/29346558-a1f92d58-8278-11e7-8632-fc63b076093c.png)

类似的问题，反馈一下。在 angular 4.2.3 和 cli 版本 1.2.7 编译出错，之后 cli 升级到 1.3.0 还是同样的问题。最后升级 angular 至最新版本 4.3.4 编译成功。

**Comment by vthinkxie** [comment]
@yiranlee 
rm -rf node_modules and reinstall may be a temporary solution, have a try please, thanks for feedback.

**Comment by yiranlee** [comment]
@wilsoncook 
1.my local dev environment in below pic 
<img width="483" alt="2017-08-16 11 52 58" src="https://user-images.githubusercontent.com/27332318/29346775-3922f7bc-827a-11e7-80c7-ed559557dca6.png">
<img width="576" alt="2017-08-16 11 54 08" src="https://user-images.githubusercontent.com/27332318/29346791-576a4450-827a-11e7-8f67-35bdd22d77dc.png">
2.  no errors when i install angular/cli and the ng-zorro-antd

**Comment by LinBoLen** [comment]
it sames that our project angular dependeces version does't suit with  ng-zorro-antd

**Comment by wilsoncook** [comment]
@yiranlee Could you please take a snapshot of under the `node_modules/ng-zorro-antd/node_modules` folder ?

**Comment by yiranlee** [comment]
@wilsoncook  
<img width="327" alt="2017-08-16 1 35 09" src="https://user-images.githubusercontent.com/27332318/29348668-f4a46f36-8287-11e7-82b1-044474870d05.png">

**Comment by wilsoncook** [comment]
It could be confirmed as version conflict of angular and related, i am about to fix the specs of dependencies. @vthinkxie

**Comment by liuliangjia** [comment]
我也是这个错误，怎么解决的？

**Comment by wilsoncook** [comment]
@liuliangjia Please remove `node_modules` (`rm -rf node_modules`), then re-install all node modules (`npm install`) if emergency

**Comment by olivewind** [comment]
I have a similar problem, upgrade angualr to 4.3.4 can resolve this problem

**Comment by liuliangjia** [comment]
这个问题，升级到4.3.4，如果是用cnpm安装的，还是会出错，只有通过npm安装，才正常，给同样问题的朋友参考下哈。也不知道cnpm漏了啥。

**Comment by huhaoGitHub** [comment]
先把NgZorroAntdModule.forRoot()从app.module移除，把项目正常跑起来以后，再引入它，热更新就可以跑起来。很神奇的赶脚。

**Comment by litttlefisher** [comment]
@wilsoncook 出错的问题，什么时候会发布新版本进行修复呢

**Comment by vthinkxie** [comment]
@litttlefisher `rm -rf node_modules` and reinstall will solve this problem.

**Comment by litttlefisher** [comment]
@vthinkxie 不知道为什么，删除了node_modules目录后重新cnpm install还是会报错，而且报错内容没有变化。难道跟window平台有关吗？全局环境中没有ng-zorro-antd

**Comment by wilsoncook** [comment]
@litttlefisher It's about to be fixed in next version

**Comment by litttlefisher** [comment]
@wilsoncook 所以我想了解下，下个版本什么时候上，每天来github检查一下毕竟比较麻烦

**Comment by vthinkxie** [comment]
@litttlefisher we will release next version tomorrow, thanks

**Comment by litttlefisher** [comment]
@vthinkxie @wilsoncook 谢谢两位大神，坐等明天修复后，开始玩ng-zorro-antd
