### ISSUE TITLE
file upload photo camera not work

### ISSUE THREAD

**Issue by Elliottssu** [NG-ZORRO/ng-zorro-antd#2305]
## Version

1.6.0

## Environment

angular 6.0

## Reproduction link

none

## Steps to reproduce

```html
 <nz-upload class="avatar-uploader"
    nzAction="https://jsonplaceholder.typicode.com/posts/"
    nzName="avatar"
    nzListType="picture-card"
    [nzShowUploadList]="false"
    [nzBeforeUpload]="beforeUpload"
    (nzChange)="handleChange($event)">
    <ng-container *ngIf="!avatarUrl">
      <i class="anticon anticon-plus"></i>
      <div class="ant-upload-text">Upload</div>
    </ng-container>
    <img *ngIf="avatarUrl" [src]="avatarUrl" class="avatar">
  </nz-upload>
```

## What is expected?

Camera uploads will be uploaded, but not uploaded.

## What is actually happening?

![WechatIMG459.jpeg](https://upload-images.jianshu.io/upload_images/3502567-eaa67b1107dc7e34.jpeg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by vthinkxie** [comment]
plz use https://github.com/NG-ZORRO/ng-zorro-antd-mobile in mobile client.

**Comment by Elliottssu** [comment]
ng-zorro-antd-mobile not comes long ago, but we've had plunge in ng-zorro for a long time ago and it's not suitable to reintroduce it now.

Is there any other way?

**Comment by vthinkxie** [comment]
@cipchk plz check it

**Comment by cipchk** [comment]
@Elliottssu  I can upload it on my phone (env: android 8 and iphone x) via [DEMO](http://ng.ant.design/components/upload/zh#components-upload-demo-picture-card).

png:

![de](https://user-images.githubusercontent.com/2987467/47251978-1135d880-d46f-11e8-8402-7f80e8b4367a.png)

Can you provide reproduce demo and env?

**Comment by cipchk** [comment]
@Elliottssu About the error visual becase of backend URL is a mock post request (https://jsonplaceholder.typicode.com/posts/) in all demos, so request result status is limited to the mock request status.
