### ISSUE TITLE
nz-input-number support onUp and onDown callback

### ISSUE THREAD

**Issue by mnikn** [NG-ZORRO/ng-zorro-antd#2307]
## What problem does this feature solve?
In some case we need to listen nz-input-number up and down event, thus we need those callbacks in nz-input-number.
## What does the proposed API look like?
```javascript
class NzInputNumberComponent {
@Output() onUp: EventEmitter<{oldValue: number, newValue: number}>; 
@Output() onDown: EventEmitter<{oldValue: number, newValue: number}>; 
}
```

```html
<nz-input-number
(onUp)="doSomething($event)"
(onDown)="doSomething($event)">
</nz-input-number>
```

**Comment by vthinkxie** [comment]
plz use ngModelChange.

**Comment by mnikn** [comment]
@vthinkxie it seems like we can only get the newValue from ngModelChange event thus we can't know which event is triggered.

**Comment by vthinkxie** [comment]
https://www.learnrxjs.io/operators/combination/pairwise.html

**Comment by kevindaizj** [comment]
@vthinkxie In most cases, `(ngModelChange )` is adequate. But what if we need to distinguish if it is :
1. an **user input**  or 
2. a change triggered programmatically (`setValue` or `patchValue`).

Something like `(onUserInput)` would be helpful.
