### ISSUE TITLE
ie10兼容问题

### ISSUE THREAD

**Issue by Joyhua** [NG-ZORRO/ng-zorro-antd#2335]
## Version
1.7.0
## Environment
ie10浏览器
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
1、新建1到2个日期控件
2、控件获取焦点，控件弹出
3、点击控件外的空白处，ie10无法隐藏控件
4、另一个控件获取焦点，此时有两个正在显示的日期
5、需要点击某一天，才可使相应日期控件消失
## What is expected?
点击控件外空白处，控件消失
## What is actually happening?
点击控件外空白处，控件不消失

**Comment by HsuanXyz** [comment]
## 🖥 Environment Support

* Angular `^6.0.0`
* Modern browsers and Internet Explorer 11+ (with [polyfills](https://angular.io/guide/browser-support))
* [Electron](http://electron.atom.io/)

| [<img src="https://raw.githubusercontent.com/alrra/browser-logos/master/src/edge/edge_48x48.png" alt="IE / Edge" width="24px" height="24px" />](http://godban.github.io/browsers-support-badges/)</br>IE / Edge | [<img src="https://raw.githubusercontent.com/alrra/browser-logos/master/src/firefox/firefox_48x48.png" alt="Firefox" width="24px" height="24px" />](http://godban.github.io/browsers-support-badges/)</br>Firefox | [<img src="https://raw.githubusercontent.com/alrra/browser-logos/master/src/chrome/chrome_48x48.png" alt="Chrome" width="24px" height="24px" />](http://godban.github.io/browsers-support-badges/)</br>Chrome | [<img src="https://raw.githubusercontent.com/alrra/browser-logos/master/src/safari/safari_48x48.png" alt="Safari" width="24px" height="24px" />](http://godban.github.io/browsers-support-badges/)</br>Safari | [<img src="https://raw.githubusercontent.com/alrra/browser-logos/master/src/opera/opera_48x48.png" alt="Opera" width="24px" height="24px" />](http://godban.github.io/browsers-support-badges/)</br>Opera | [<img src="https://raw.githubusercontent.com/alrra/browser-logos/master/src/electron/electron_48x48.png" alt="Electron" width="24px" height="24px" />](http://godban.github.io/browsers-support-badges/)</br>Electron |
| --------- | --------- | --------- | --------- | --------- | --------- |
| IE11, Edge | last 2 versions | last 2 versions | last 2 versions | last 2 versions | last 2 versions

> Listing `@angular/cdk` as its dependency, `ng-zorro-antd` supports the most recent two versions of all major browsers.
