### ISSUE TITLE
Drop-down menu

### ISSUE THREAD

**Issue by mjn1154477982** [NG-ZORRO/ng-zorro-antd#234]
![image](https://user-images.githubusercontent.com/20697182/30097050-4170e664-930e-11e7-9dcb-9dcc2a79e7de.png)
When I leave that button, the drop-down menu also disappears, which makes it impossible for me to select the contents of the menu

**Comment by vthinkxie** [comment]
@Brooooooklyn 
it seems that the issue is related to #148 ,any idea to fix it?

**Comment by Brooooooklyn** [comment]
I'll take a look at it soon

**Comment by vthinkxie** [comment]
@Brooooooklyn thanks :)
