### ISSUE TITLE
collapse icon in nz-sider disappear

### ISSUE THREAD

**Issue by chichujn** [NG-ZORRO/ng-zorro-antd#2341]
## Version
1.7.1
## Environment
Windows10 64bit Chrome69
## Reproduction link
[https://ng-zorro-layout-sider.stackblitz.io](https://ng-zorro-layout-sider.stackblitz.io)
## Steps to reproduce
Trigger icon on collapsible nz-sider disappear.
The icon is still of ver1.6 style: <i class='anticon'></i> which should be mistake.
## What is expected?
Trigger icon on collapsible nz-sider should use nz-icon.
## What is actually happening?
As above.

**Comment by wendzhue** [comment]
@chichujn Check the link again? I think we fixed it in 1.7.1.

**Comment by chichujn** [comment]
Sorry, this was an issue under 1.7.0, has been fixed at 1.7.1
