### ISSUE TITLE
nz-menu 鼠标点击激活 和ts控制激活选中 不能共存

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#2342]
## Version
1.6.0
## Environment
ng@6  nz-zorro@1.6
## Reproduction link
[https://ng-zorro-antd-start-eifz48.stackblitz.io](https://ng-zorro-antd-start-eifz48.stackblitz.io)
## Steps to reproduce
1, 点击分享链接下面button 可以控制切换menu的选中状态，
2，鼠标点击menu的选中状态，在点击按钮切换选中状态即错乱
## What is expected?
鼠标点击 选中 有输出方法 和ts控制选中可共存
## What is actually happening?
鼠标点击 选中 有输出方法 和ts控制选中不可共存

**Comment by vthinkxie** [comment]
很明显你应该维护一个selectedMap负责激活不同的菜单，和组件库没有关系

**Comment by liganggang** [comment]
维护也不行啊 你的鼠标点击选中后 会打呀破平衡的呀

**Comment by liganggang** [comment]
应该是有鼠标输出事件  让程序员来控制选中状态， 你觉得呢

**Comment by vthinkxie** [comment]
<img width="1152" alt="2018-10-24 10 05 43" src="https://user-images.githubusercontent.com/1506722/47402839-bdcacf80-d779-11e8-8288-f15d05e01b96.png">

**Comment by liganggang** [comment]
https://ng-zorro-antd-start.stackblitz.io/    兄弟 你再看一下吧  步骤 1，点击人员管理，2 点击button, 3,点击人员管理， 4，单击button  看看吧，   你应该是没看到代码所以没理解问题，

**Comment by liganggang** [comment]
button控制日志管理激活的

**Comment by liganggang** [comment]
我把  我没看到这个属性 我从新撸一次...
