### ISSUE TITLE
自定义上传内容时 可以设置thumbUrl 、URL不同的URL

### ISSUE THREAD

**Issue by lishengzhuang** [NG-ZORRO/ng-zorro-antd#2344]
## What problem does this feature solve?
可以设置缩略图与名字的不同的URL
## What does the proposed API look like?
设置 thumbUrl 、URL

**Comment by cipchk** [comment]
@lishengzhuang 抱歉，我不明白你的意思，麻烦详细描述，或提供相应的重现示例。

**Comment by vthinkxie** [comment]
closed since no response in a long time.
