### ISSUE TITLE
form表单内的input number怎样取消滑动改变数据

### ISSUE THREAD

**Issue by liangyuqi** [NG-ZORRO/ng-zorro-antd#2345]
## What problem does this feature solve?
form表单较长，用户需要下滑，但是经常误操作导致input number内值上下变动，Event Listeners内也没有找到scroll事件，怎么样取消滑动改变值
## What does the proposed API look like?
form表单内的input number取消滑动改变值

**Comment by vthinkxie** [comment]
监听全局滚轮事件，修改focus位置就可以了
