### ISSUE TITLE
how do we clear nz-date-picker from ngModelChange method?

### ISSUE THREAD

**Issue by rahulmistry25425** [NG-ZORRO/ng-zorro-antd#2348]
**Version**
1.6.0

**Environment**
Chrome

**Steps to reproduce**
Having 2 date picker "Start" and "End", if end is smaller than start than it should not allow to fill date picker. 

**What is expected?**
end date picker should not be filled until and unless end date is not grater than start date.

**What is actually happening?**
Used ngModelChange and nzOnOk default events but not sure how can i clear date picker input by code.

**Comment by vthinkxie** [comment]
just try to set ngModel to null
