### ISSUE TITLE
angular 6.0.0 and zorro 1.7  not allowed to use [formGroup]

### ISSUE THREAD

**Issue by liuwu1211** [NG-ZORRO/ng-zorro-antd#2358]
## Version
1.7.1
## Environment
angular6.0.0
## Reproduction link
[https://github.com/liuwu1211/angular6-zorro-demo.git](https://github.com/liuwu1211/angular6-zorro-demo.git)
## Steps to reproduce
Can't bind to 'formGroup' since it isn't a known property of 'form'. ("
    <form nz-form [ERROR ->][formGroup]="validateForm" class="login-form" (ngSubmit)="submitForm()">
## What is expected?
repair bug 
## What is actually happening?
When I use cli in demo of official website, the page cannot be displayed properly.
"ng g ng-zorro-antd:form-normal-login -p app --styleext=less --name=login"

**Comment by vthinkxie** [comment]
reactiveFormModule, plz make sure you have read angular doc before using ng-zorro
