### ISSUE TITLE
menu: missing bg color when using dropdown

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#2359]
## Reproduce

https://stackblitz.com/edit/angular-xryjuo?file=src/app/app.component.ts

png:

![wechat screenshot_20181026123224](https://user-images.githubusercontent.com/2987467/47544762-374df380-d91b-11e8-8eb7-6fbfcee5c799.png)

**Comment by vthinkxie** [comment]
fixed in latest version.
