### ISSUE TITLE
upload a 2.7M jpg,the thumbnail upside-down

### ISSUE THREAD

**Issue by tanxiaolongsky** [NG-ZORRO/ng-zorro-antd#2360]
## Version
1.7.1
## Environment
chrome 62.0.3202.89 
## Reproduction link
[https://stackblitz.com/xxx](https://stackblitz.com/xxx)
## Steps to reproduce
upload a small jpg is show normal, but when i upload a jpg which is 2.7M,the  thumbnail is upside-down.
[sample jpg](https://pan.baidu.com/s/1g8A_uI87cArMlr76yUBMnQ)
## What is expected?
i upload person jpg,don't want the jpg is upside-down.
## What is actually happening?
upside-down

**Comment by wendzhue** [comment]
@tanxiaolongsky The reproduction is invalid.

**Comment by tanxiaolongsky** [comment]
> @tanxiaolongsky The reproduction is invalid.

diden't  need the reproduction

![tg](https://user-images.githubusercontent.com/36794109/47548372-6ff5c900-d92b-11e8-9be0-91d538d7c3d1.gif)

**Comment by wendzhue** [comment]
@tanxiaolongsky OK. We will look into this. Please protect your privacy.

@cipchk Please take a look.

**Comment by cipchk** [comment]
> The photos are likely being presenting in their natural orientation. When taking a photograph, a bunch of meta data about the camera is stored in something called **EXIF data**, things such as time, location, shutter, and orientation.
> 
> Most photo viewing software, including the ones on the device itself, take the orientation into account and display it accordingly. As a result, your logic will need to do the same.

pls refer to https://stackoverflow.com/questions/26133817/image-with-src-from-url-appearing-upside-down-or-sideways-sometimes

**Comment by tanxiaolongsky** [comment]
> > The photos are likely being presenting in their natural orientation. When taking a photograph, a bunch of meta data about the camera is stored in something called **EXIF data**, things such as time, location, shutter, and orientation.
> > Most photo viewing software, including the ones on the device itself, take the orientation into account and display it accordingly. As a result, your logic will need to do the same.
> 
> pls refer to https://stackoverflow.com/questions/26133817/image-with-src-from-url-appearing-upside-down-or-sideways-sometimes

thank you for help.

Exif.js read the image meta data
[link](http://code.ciaoca.com/javascript/exif-js/)

use exif.js  Solve IOS mobile phone upload vertical photo rotation 90 degrees.
[link](https://blog.csdn.net/linlzk/article/details/48652635)
