### ISSUE TITLE
希望 NzDrawerRef 能增加 onClose 事件

### ISSUE THREAD

**Issue by 1-2-3** [NG-ZORRO/ng-zorro-antd#2361]
## What problem does this feature solve?
使用Component方式用drawerService.create() 方法创建抽屉非常方便。但由于不再在html文件中声明nz-drawer标签，无法使用它的onClose事件了。我想实现当点击背景层关闭抽屉前判断抽屉里面的表单是否已被修改，如有修改则提示用户的功能就无法实现了。
## What does the proposed API look like?
当用户点击背景层时，不自动关闭抽屉，而是触发 onClose事件，由程序调用 drawerRef.close(); 关闭抽屉。
this.drawerRef.onClose.subscribe(() => {
    this.drawerRef.close();
});

**Comment by vthinkxie** [comment]
supported in latest version, closed now.

**Comment by 1-2-3** [comment]
感谢开源团队卓越的工作！
