### ISSUE TITLE
fileUpload 上传图片， 使用beforeUpload() 修改fileList，异步情况下页面预览没效果

### ISSUE THREAD

**Issue by tanxiaolongsky** [NG-ZORRO/ng-zorro-antd#2371]
## Version
1.8.0
## Environment
chrome 62.0.3202.89
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-7l4jwj?embed=1&file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-7l4jwj?embed=1&file=src/app/app.component.ts)
## Steps to reproduce
beforeUpload 调用方法 push file 到 fileList, fileList 数据变化后，因该页面显示也跟着变化，但是fileList变了，页面没变。
## What is expected?
动态修改fileList后，页面立即显示，如文档说的fileList 是双向绑定，应该是同时变化的。
## What is actually happening?
数据变了，页面显示没变

**Comment by cipchk** [comment]
虽然不清楚你的问题，但是 Angular 并不会因为 `push` 而重新渲染，可以更改为：

```ts
this.fileList = this.fileList.concat([newFile]);
```

另一个问题是 `onloadend` 若想访问到组件 `this`，则应该：

```ts
reader.onloadend = (e) => {}
```

**Comment by tanxiaolongsky** [comment]
☆⌒(*＾-゜)v THX!!   
大神请收下我的膝盖！
大神请收下我的膝盖！
大神请收下我的膝盖！
