### ISSUE TITLE
slider: minimum value should always of zero position in range mode

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#2373]
## 重现

**Angular**

https://stackblitz.com/edit/angular-n2vcdt?file=src/app/app.component.ts

gif:

![ng](https://user-images.githubusercontent.com/2987467/47631976-2bfd0100-db83-11e8-85b2-7565b3d171c9.gif)

**React**

https://codepen.io/cipchk/pen/wYZazP?editors=0010

gif:

![react](https://user-images.githubusercontent.com/2987467/47631988-33240f00-db83-11e8-8ebb-72dd2c035c38.gif)

**Comment by wendzhue** [comment]
@wilsoncook I noticed that you would refactor this component so I would reassign this issue to you.

**Comment by wendzhue** [comment]
Ref #1547.
