### ISSUE TITLE
Position of Sorter and Filter from table header looks odd.

### ISSUE THREAD

**Issue by Leon-Black** [NG-ZORRO/ng-zorro-antd#2374]
## Version
1.8.0
## Environment
macOS, Safari
## Reproduction link
[https://stackblitz.com/edit/angular-4dfruj](https://stackblitz.com/edit/angular-4dfruj)
## Steps to reproduce
https://ng.ant.design/components/table/en
## What is expected?
The icon sits closely to the left label.
## What is actually happening?
The icon sits far from the label and close to next label, looks like it belongs to the label on its right side.  It is even more confusing especially when the table is wide.

**Comment by wendzhue** [comment]
Ant Design specifies this. See https://ant.design/components/table/#components-table-demo-head.
