### ISSUE TITLE
tree-select: Can't bind default value after nodes changed

### ISSUE THREAD

**Issue by invader41** [NG-ZORRO/ng-zorro-antd#2375]
## Version
1.8.0
## Environment
Chrome
## Reproduction link
[https://stackblitz.com/edit/angular-nn3qyb-nzskro](https://stackblitz.com/edit/angular-nn3qyb-nzskro)
## Steps to reproduce
Click Set nodes button
## What is expected?
Default value should be bound
## What is actually happening?
Default value has not be bound

**Comment by vthinkxie** [comment]
closed by #2976
