### ISSUE TITLE
pagination position in table 

### ISSUE THREAD

**Issue by mortifactor** [NG-ZORRO/ng-zorro-antd#2376]
## What problem does this feature solve?
I think it would be grate to have ability to set pagination position in table (top, bottom (default) and both)
## What does the proposed API look like?
"paginationPosition" property with "top, bottom (default), both" possible values
i.e.:
```
<nz-table ... paginationPosition="both"></nz-table>
```
![image](https://user-images.githubusercontent.com/1426349/47639432-d54bf300-db93-11e8-8758-7fcdbdaffefd.png)

**Comment by huynv86** [comment]
since 2018, not yet implement

**Comment by Vishalsagar01** [comment]
dsd
