### ISSUE TITLE
[Feature] Timeline support node layout mode

### ISSUE THREAD

**Issue by HsuanXyz** [NG-ZORRO/ng-zorro-antd#2379]
## What problem does this feature solve?

https://github.com/ant-design/ant-design/pull/11490

## What does the proposed API look like?

```diff
<nz-timeline
+  nzMode="alternate">
   ...
</nz-timeline>
```

### API

| Property | Description | Type | Default |
| -------- | ----------- | ---- | ------- |
| [nzMode] | By sending `alternate` the timeline will distribute the nodes to the left and right. | `left` \| `alternate` \| `right` | `left` |

**Comment by wendzhue** [comment]
Implemented in #2515.
