### ISSUE TITLE
upgrade to @angular/cdk 2.0.0-beta.11

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#238]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Expected behavior

upgrade @angular/cdk 2.0.0-beta.8 to @angular/cdk 2.0.0-beta.10

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by encool** [comment]
ASAP plz

**Comment by encool** [comment]
快一点咯，下个版本会升级好吗？什么时候？

**Comment by vthinkxie** [comment]
@encool any block to you?

**Comment by encool** [comment]
项目同时使用了angular material 2.0.0-beta.10和nz 0.5.0。aot build会失败。是这里的原因吗？

**Comment by wilsoncook** [comment]
@encool Could you pls commit an issue to describe the problems u have met, any details to help resolving your problem.

**Comment by encool** [comment]
@wilsoncook  [290](https://github.com/NG-ZORRO/ng-zorro-antd/issues/290)

**Comment by wanghaolu** [comment]
升级到@angular/cdk beta.12 项目编译报错，希望尽快升级下
