### ISSUE TITLE
list 里的分页完全没反应，是不是有bug， 

### ISSUE THREAD

**Issue by ye-ma** [NG-ZORRO/ng-zorro-antd#2385]
## Version
1.8.0
## Environment
1.8.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-dq9plo?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-dq9plo?file=src/app/app.component.html)
## Steps to reproduce
完全复制官网代码，把每页显示个数改成5个，把array改成100
## What is expected?
是bug吗
## What is actually happening?
是bug吗

**Comment by vthinkxie** [comment]
需要自己处理每页显示的数据，应该是demo没写全 @cipchk

**Comment by ye-ma** [comment]
求思路啊，想不出

**Comment by ye-ma** [comment]
> 需要自己处理每页显示的数据，应该是demo没写全 @cipchk
求思路啊，想不出

**Comment by vthinkxie** [comment]
看下nz-pagination的用法，根据当前分页切分data数据
