### ISSUE TITLE
use carousel in Modal ,the carousel-content no display

### ISSUE THREAD

**Issue by yanganglove** [NG-ZORRO/ng-zorro-antd#2387]
## Version
1.8.0
## Environment
angular6
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-g21fmh](https://stackblitz.com/edit/ng-zorro-antd-start-g21fmh)
## Steps to reproduce
just use carousel in Modal

## What is expected?
the carousel-content  display
## What is actually happening?
the carousel-content no display

**Comment by wendzhue** [comment]
The carousel would appear when window resizes. I guess something is wrong this its life cycle. Thanks for reporting this.

**Comment by NOPROD** [comment]
Hi, just for say i got the same issue today on angular 7, i solve it by force changeDetection

 `  ngAfterViewInit() {
    setTimeout(() => {
      this.carousel.carouselContents.setDirty();
    }, 200);
  }`

That also force resize of carousel and fix a bug with carousel's width.

My carousel's width was blocked by modal's width :/
