### ISSUE TITLE
IE 11 中在A标签上打开modal 窗口出错

### ISSUE THREAD

**Issue by kkalpha** [NG-ZORRO/ng-zorro-antd#2388]
## Version
1.8.0
## Environment
IE 11
## Reproduction link
https://stackblitz.com/edit/ng-zorro-antd-start-y5nxnf
## Steps to reproduce
1. 在A标签上的click事件打开modal，代码如  <a class="action-button" (click)="addEmployee()"><i class="anticon anticon-plus-circle"></i></a>
2. addEmployee的代码如： const modal = this.modalService.create({
		nzTitle: '',
		nzContent: EmployeeListComponent,
		nzComponentParams: {
			selectedEmployees: '1'
		},
		nzWidth: '700px',
		nzClosable: false,
		nzFooter: null
	});
## What is expected?
正常打开
## What is actually happening?
IE浏览器报错: Object doesn't support property or method 'blur'
## Other?
1.6版本是正确的，是不是1.7升级这个功能的时候造成的: modal: 当 modal 打开关闭时自动切换焦点 (#2188) (7c0ced4), closes #2124

**Comment by wendzhue** [comment]
@kkalpha 请提供重现链接

**Comment by kkalpha** [comment]
> @kkalpha 请提供重现链接
请参照更新： https://stackblitz.com/edit/ng-zorro-antd-start-y5nxnf
在IE中出错，chrome浏览器可以正常打开

**Comment by kkalpha** [comment]
从IE浏览器报错看: Object doesn't support property or method 'blur'
是不是IE的A标签不支持blur?

**Comment by wendzhue** [comment]
@kkalpha It works for me. I start a new project because stackblitz is too huge for IE11 🤣 

![image](https://user-images.githubusercontent.com/12122021/48038562-279c9d80-e1ac-11e8-9b43-4bd3b9b0b945.png)

**Comment by kkalpha** [comment]
@wendzhue 
can you test to use the a link to open a 'modal':
when click the a tag: use the modalService to present a component.
 const modal = this.modalService.create({
nzTitle: '',
nzContent: XXXComponent,
nzComponentParams: {
selectedEmployees: '1'
},
nzWidth: '700px',
nzClosable: false,
nzFooter: null
});

**Comment by kkalpha** [comment]
@wendzhue 
The exact code for the "a link' part is as bellow, I had a i tag in between the a tag:
```
 <a  title="open modal"  (click)="openModal()">
  <i class="anticon anticon-user-add"></i>
</a> 
```

sorry for the misleading by just saying a link.
below is the screen shot:
![modal](https://user-images.githubusercontent.com/6467057/48199421-eddbba80-e396-11e8-84ed-488840a210f6.png)

**Comment by kkalpha** [comment]
@wendzhue 
the same code was working in 1.6

**Comment by ferqx** [comment]
我也是同样问题

**Comment by ferqx** [comment]
![image](https://user-images.githubusercontent.com/23183225/48693412-5ab34800-ec14-11e8-9b70-4433b59358d7.png)

**Comment by ferqx** [comment]
用button按钮点击打开模态框不会出现这种错误，因为它们有focus和blur方法，<i>和<a>标签点击打开模态框会出现此类问题

**Comment by ferqx** [comment]
用button按钮点击打开模态框不会出现这种错误，因为它们有focus和blur方法，i和a标签点击打开模态框会出现此类问题

**Comment by ferqx** [comment]
看日志`7.0.0-rc.1`版本已经修复，
当前项目`ng-zorro-antd `版本：7.0.0-rc.3，
在IE11中并没有解决该问题，还是同样的报错，提交代码后请先测试通过再关闭。
![image](https://user-images.githubusercontent.com/23183225/51019363-8f5cd380-15b5-11e9-9ed0-27db4df3d209.png)
