### ISSUE TITLE
How to check image dimension in nzBeforeUpload

### ISSUE THREAD

**Issue by kherP** [NG-ZORRO/ng-zorro-antd#2389]
## Version
1.4.1
## Environment
Angular 6
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-6bvdsj](https://stackblitz.com/edit/ng-zorro-antd-start-6bvdsj)
## Steps to reproduce
I was finding a way to check image's dimension before uploading. However, I am not able to find a way to get the dimension checked. Is there any way to check the dimension before uploading?
## What is expected?
Have the image's dimension checked before uploading.
## What is actually happening?
Based on my knowledge, in order to get the actual width and height of the image chosen, I need to use the image onload function. However, there is no way for me to add an async/await function or even a pipe to check the chosen file.

**Comment by RamboWan** [comment]
同样遇到这个问题 ....不知道怎么限制图片的宽高

**Comment by cipchk** [comment]
@kherP @RamboWan , you can return a Observable value in `beforeUpload`, I hava update [demo](https://github.com/NG-ZORRO/ng-zorro-antd/blob/e3b37526826c27cc89432e414f49b2643d7805dd/components/upload/demo/avatar.ts#L46) code.
