### ISSUE TITLE
Table排序的$event怎么取到列头的值。

### ISSUE THREAD

**Issue by Acumes** [NG-ZORRO/ng-zorro-antd#239]
<p-column field="amount" header="余额" [sortable]="true" styleClass='text-right'>
像Pringmg一样去到field的值

**Comment by Acumes** [comment]
如果这样排序的话只是单页面的排序，是要把排序的field值传到后端，后端排好序返回数据显示

**Comment by Acumes** [comment]
解决了

**Comment by LinBoLen** [comment]
maybe ng-zorro should uniform datasource format
