### ISSUE TITLE
表格table能否自适应屏幕

### ISSUE THREAD

**Issue by ye-ma** [NG-ZORRO/ng-zorro-antd#2390]
## Version
1.8.0
## Environment
1.8.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-2jfesp?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-2jfesp?file=src/app/app.component.ts)
## Steps to reproduce
表格table能否自适应屏幕
## What is expected?
表格table能否自适应屏幕
## What is actually happening?
表格table能否自适应屏幕
## Other?
表格table能否自适应屏幕

**Comment by vthinkxie** [comment]
请清晰的描述你的需求，如果需要汇报bug请提供正确的重现链接
