### ISSUE TITLE
Cascader can't Search when change value and label

### ISSUE THREAD

**Issue by lkhuoch** [NG-ZORRO/ng-zorro-antd#2395]
## Version
1.8.0
## Environment
Calendar can't Search when change value and label
## Reproduction link
[https://kmpzfu.run.stackblitz.io](https://kmpzfu.run.stackblitz.io)
## Steps to reproduce
The Cascader will fine with search when it is set [nzValueProperty] and [nzLabelProperty] is default, but when change [nzValueProperty]="'id'" [nzLabelProperty]="'name'", it seems work fine, but we cannot search, how to fix it?
## What is expected?
Can change nzValueProperty and znLabelProperty to other, like id or name, ...
## What is actually happening?
The Cascader will fine with search when it is set [nzValueProperty] and [nzLabelProperty] is default, but when change [nzValueProperty]="'id'" [nzLabelProperty]="'name'", it seems work fine, but we cannot search, how to fix it?
## Other?
The Cascader will fine with search when it is set [nzValueProperty] and [nzLabelProperty] is default, but when change [nzValueProperty]="'id'" [nzLabelProperty]="'name'", it seems work fine, but we cannot search, how to fix it?

**Comment by wendzhue** [comment]
Closed in #2516.
