### ISSUE TITLE
has conflict with material-table-component

### ISSUE THREAD

**Issue by shenchaoran** [NG-ZORRO/ng-zorro-antd#2398]
## Version
1.8.0
## Environment
angular: 7.0.2, material: 7.0.2, ng-zorro-antd: 1.8.0
## Reproduction link
[https://stackblitz.com/edit/ng-material-starter](https://stackblitz.com/edit/ng-material-starter)
## Steps to reproduce
Import `NgZorroAntdModule`, use material-table  with the directive like  `<tr mat-header-row></tr>`  got error: `Missing definitions for header, footer, and row; cannot determine which columns should be rendered.` 

It means don't know the directive of `mat-header-row`.

## What is expected?
don't conflict with material
## What is actually happening?
can't use material and zorro simultaneously.

**Comment by vthinkxie** [comment]
ng-zorro-antd now depends on material: 6.x
we will release new version the end of this month.

**Comment by shenchaoran** [comment]
@vthinkxie still conflict, please find [here](https://stackblitz.com/edit/mat-table-conflict-with-zorro). 
versions:
```
angular: 7.0.2
material: 7.0.2
ng-zorro-antd: 7.0.0-rc.1
```

`NzTableModule` of ng-zorro-antd has conflict with `MatTableModule` of material

**Comment by chitayta** [comment]
Hi, any update for this ticket?

If I import the whole library, I will get the same issue.
Versions: Angular 7.2.9, Material 7.3.4, ng-zorro-antd: 7.0.3

![image](https://user-images.githubusercontent.com/20698545/54576929-798fe280-4a2c-11e9-9918-8844ca13a35b.png)

Thanks

**Comment by wendzhue** [comment]
@chitayta Can you make a reproduce?

@shenchaoran I can't see errors in your reproduction. Care for a look?

**Comment by wendzhue** [comment]
Will be closed by #3234.

**Comment by vthinkxie** [comment]
ng-zorro-antd support individual module import now, you can skip the NzTableModule now
