### ISSUE TITLE
关于生产库使用和版本计划

### ISSUE THREAD

**Issue by cnicy** [NG-ZORRO/ng-zorro-antd#24]
请问，目前可以在生产环境使用了吗？后续有没有发布计划，版本升级改怎么处理？谢谢。

**Comment by vthinkxie** [comment]
please check it here
https://ng.ant.design/#/changelog

* 每周末会进行日常 bugfix 更新。（如果有紧急的 bugfix，则任何时候都可发布）。
* 每月发布一个带有新特性的向下兼容的版本。
* 含有破坏性升级的版本更新不在发布周期内。
