### ISSUE TITLE
Modal对话框新增出现方式（自上而下）

### ISSUE THREAD

**Issue by leaughing** [NG-ZORRO/ng-zorro-antd#2401]
## What problem does this feature solve?
我们服务的客户大多属于医院，由于客户年龄偏大，目前从按钮出现慢慢变大的出现方式（对话框），可能由于电脑网络或硬件配置或其他 有时会出现 显示过程卡顿 导致弹出过程像是一跳一跳的 ，老人家受不了，所以能新增一种出现方式，保持对话框宽度不变，自上而下慢慢出现 类似于抽屉出现。
## What does the proposed API look like?
我期望出现方式可以定制，新增类似于bootstrap3 模态框的弹出方式。

**Comment by ishowman** [comment]
同感，感觉原来模态框动画出现的动画（从点击位置，宽高展开到最大）有点突兀。看多几次动画眼睛很难受。
期望组件能暴露自定义模态框动画的能力，或者提供多种动画特效供选择。

**Comment by vthinkxie** [comment]
ref #2922

**Comment by heramerom** [comment]
所以过了好几年，还是不支持react那边的transationName属性呗，这效率真是可以啊。
