### ISSUE TITLE
divider建议加一个 / 分隔线

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#2402]
## What problem does this feature solve?
丰富库
## What does the proposed API look like?
[nzType] 加一个 / 的分割线字段

**Comment by wendzhue** [comment]
你可以先反馈给 Ant Design.

另外似乎没有必要在组件库中添加这么一个支持, 万一用户想要用 ⭐️ 作为分隔符呢? 自行用 CSS 实现就可以了, 很简单.

**Comment by tanxiaolongsky** [comment]
分割先的颜色 能自己设定吗？ 有些背景色 会隐藏分割线导致看不清
