### ISSUE TITLE
divider组件放入table可展开td里面出现样式错误

### ISSUE THREAD

**Issue by shilim-developer** [NG-ZORRO/ng-zorro-antd#2407]
## Version
1.8.0
## Environment
angular 6.18
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-eqjcnj](https://stackblitz.com/edit/ng-zorro-antd-start-eqjcnj)
## Steps to reproduce
divider组件放入table可展开的td里面
## What is expected?
线与文字垂直居中对齐
## What is actually happening?
线偏上

**Comment by vthinkxie** [comment]
nz-divider 不保证在任何组件内都是垂直居中对齐，可以通过css样式调整达到你想要的效果
