### ISSUE TITLE
popover does not work with cdk 7

### ISSUE THREAD

**Issue by hamdiwanis** [NG-ZORRO/ng-zorro-antd#2410]
## Version
1.8.0
## Environment
angular 7, cdk 7
## Reproduction link
[https://stackblitz.com/edit/angular-bum5vh](https://stackblitz.com/edit/angular-bum5vh)
## Steps to reproduce
open lick and click on the test button
## What is expected?
popup should appear
## What is actually happening?
does not appear error on prod build
## Other?
it works on regular serve

**Comment by wendzhue** [comment]
Please read `README.md` and search issues. We've been working on this. You can track #2025 and #2381.
