### ISSUE TITLE
menu-group, when hover the title, the menu will hidden

### ISSUE THREAD

**Issue by zmzimpl** [NG-ZORRO/ng-zorro-antd#2412]
## Version
1.8.0
## Environment
angular6
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
hover this code
```
            <span title>Item 1</span>
```
## What is expected?
the menu is hiding
## What is actually happening?
the menu still show

**Comment by zmzimpl** [comment]
sorry~
the reproduction link is : https://ng-zorro-antd-start.stackblitz.io/

**Comment by zmzimpl** [comment]
sorry~
the reproduction link is : https://stackblitz.com/edit/ng-zorro-antd-start-w6iku8?embed=1&file=src/app/app.component.ts

**Comment by ffey** [comment]
I think this problem is same as #2449 , it was be solved at #2454

**Comment by ffey** [comment]
I think this issue can be close. @vthinkxie

**Comment by ffey** [comment]
I think this issue could be closed. @vthinkxie @wendzhue

**Comment by vthinkxie** [comment]
@ffey is right, close now.
