### ISSUE TITLE
Multiple select - Select All and Display number of selected instead of all values

### ISSUE THREAD

**Issue by powermax01** [NG-ZORRO/ng-zorro-antd#2421]
## What problem does this feature solve?
Situations:
I have a multiple select with about 100 values. I just add an Option [Select All] for user to select all options.
But when use want to select 97 (all then remove 3 options) the list displays label of 97 items.... hmmm, so long text.

## What does the proposed API look like?
Suggestion:

- Officially have Select All option for component.
- Can I have option to display "(97 items selected)" instead of "option1, option2, option3 ...... option 97"?
- The number of Items can be configured.

Ex: if number of options is greater than X, component will display: (X items selected) instead of "option1... optionX"

Thanks

**Comment by chanchaw** [comment]
have not response ? I have the same question

**Comment by powermax01** [comment]
Any updates on this?
What does "Ant Design" mean? will it be implemented?

**Comment by chanchaw** [comment]
ant design create ng-zorro-antd,it's a company's name
i use PrimeNg's multiple select   instead of ng-zorro-antd's

**Comment by wendzhue** [comment]
Sorry for the late reply guys! We will implement this in our recent milestone I.

**Comment by powermax01** [comment]
I see this ticket in the roadmap but not see when it is planned to be resolved. 

It's nice to have an estimation since we are using another 3rd party component to do this function of the Select control.
Please tell us about the plan.

Thanks

**Comment by MatGhp** [comment]
Am Do., 17. Jan. 2019, 03:48 hat vthinkxie <notifications@github.com>
geschrieben:
