### ISSUE TITLE
Tag select input field does not grow correctly in IE

### ISSUE THREAD

**Issue by klaascuvelier** [NG-ZORRO/ng-zorro-antd#2427]
## Version
1.8.0
## Environment
all
## Reproduction link
[https://ng-zorro-antd-start-vsrhwy.stackblitz.io](https://ng-zorro-antd-start-vsrhwy.stackblitz.io)
## Steps to reproduce
In IE start typing in the input field of the select component (in tag mode)
## What is expected?
The input field has the correct width
## What is actually happening?
Input field does not grow correctly
## Other?
I assume this is the related code: https://github.com/NG-ZORRO/ng-zorro-antd/blob/4fa93673803d0279589f0448cc17158276beb9d9/components/select/nz-select-top-control.component.ts#L170
Seems not to work correctly in IE, In Safari on MacOS it's also not perfect, but it's not as bad

**Comment by brampeirs** [comment]
scrollwidth stays the same in IE11, it is not correctly calculated.
This could be fixed with this polyfill: https://github.com/gregwhitworth/scrollWidthPolyfill
