### ISSUE TITLE
nz-sider support switch theme

### ISSUE THREAD

**Issue by xixiliguo** [NG-ZORRO/ng-zorro-antd#2435]
## What problem does this feature solve?
default theme of nz-sider is dark,   
i see code already have light css info  
need  provide convenient way to switch from dark theme to light one  
## What does the proposed API look like?
like nz-menu API

```
<nz-sider nzCollapsible [(nzCollapsed)]="isCollapsed" [nzWidth]="width" [nzReverseArrow]="isReverseArrow" [nzTheme]="theme">
```

**Comment by vthinkxie** [comment]
supported
