### ISSUE TITLE
nz-table can't use nzWidth="50px"

### ISSUE THREAD

**Issue by zomixi** [NG-ZORRO/ng-zorro-antd#2439]
## Version
1.8.0
## Environment
chrome , win10
## Reproduction link
[https://ng-zorro-antd-start-1fi38w.stackblitz.io/](https://ng-zorro-antd-start-1fi38w.stackblitz.io/)
## Steps to reproduce
use nzWidth="50px"
## What is expected?
width:50px;
## What is actually happening?
width:49.6px;
## Other?
There is a gap between the two fixed columns

**Comment by vthinkxie** [comment]
<img width="558" alt="2018-11-24 7 49 51" src="https://user-images.githubusercontent.com/1506722/48967878-21b71100-f022-11e8-93bd-dd8c423fb698.png">
it seems everything work fine here
