### ISSUE TITLE
rate星级平分不好使

### ISSUE THREAD

**Issue by htmlcss23** [NG-ZORRO/ng-zorro-antd#244]
<nz-rate [ngModel]="2" [nzDisabled]="true"></nz-rate>
默认的星级不显示。ngModel不好使
ng-zorro 是最新版本

**Comment by vthinkxie** [comment]
works fine when I test it. make sure you have import `FormsModule`.
please provide the gif or detail.

报告 BUG 时请务必按照下列格式书写，并尽可能提供源代码、复现步骤、复现演示、GIF 演示等。我们和你一样都希望尽快解决问题，请不要浪费时间在互相追问上。
