### ISSUE TITLE
Missing horizontal alignment in table

### ISSUE THREAD

**Issue by michaelkrog** [NG-ZORRO/ng-zorro-antd#2444]
## What problem does this feature solve?
In ant.design's table the **Column** has an align property that specifies how content is aligned. This property is *not* available in ngzorro and there seems no way to easily align the columns to the center or to the right.
## What does the proposed API look like?
I expect it to be possible to align a column to the center or to the right.

**Comment by michaelkrog** [comment]
Reference to documentation in ant.design's table:
https://ant.design/components/table/#Column

**Comment by vthinkxie** [comment]
Thanks @michaelkrog , we will add it later.
