### ISSUE TITLE
建议增加 NzIconTestingModule

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#2446]
## 理由

整个测试用例会收到太多的警告或错误信息，可以考虑增加相应的 `testing` 专门用于测试。

**Comment by vthinkxie** [comment]
@wendzhue 可以考虑在测试环境隐藏warning提示

**Comment by wendzhue** [comment]
报错是 (也应该) 在底包中实现, 而且最新的版本报错从 console 改成了抛出错误.

**Comment by wendzhue** [comment]
Closed by #2641.
