### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'nz-switch'

### ISSUE THREAD

**Issue by RogerHuangZB** [NG-ZORRO/ng-zorro-antd#245]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
<pre><code>
Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'nz-switch'.
1. If 'nz-switch' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'nz-switch' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<div class="menu-bar">
  <nz-switch [ERROR ->][(ngModel)]="theme">
    <span checked>Dark</span>
    <span unchecked>Light</span>
"): ng:///PagesModule/BaMenuBarComponent.html@15:13
</code></pre>

pages.module.ts
<pre><code>
@NgModule({
  imports: [
    CommonModule,
    routing,
    NgZorroAntdModule
  ],...
</code></pre>

ba-menu-bar.component.html
just copy from api document : [https://ng.ant.design/#/components/menu](url)
`  <nz-switch [(ngModel)]="theme">`
`    <span checked>Dark</span>`
`    <span unchecked>Light</span>`
`  </nz-switch>`
`  <br>`
`  <br>`

<pre><code>
export class BaMenuBarComponent implements OnInit {
  theme = true;
</code></pre>
## Environment

<pre><code>
Angular version: 4.2.4

ng-zorro-antd version: 0.5.0-rc.4

Browser:
- [x] Chrome (desktop) version 59.0.3071.86
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: v8.1.0  
- Platform: Windows 10  

Others:

</code></pre>

**Comment by SangKa** [comment]
need to import `FormsModule`
