### ISSUE TITLE
tree组件能否提供根据节点的key获取到节点的对象实例

### ISSUE THREAD

**Issue by yhz1992** [NG-ZORRO/ng-zorro-antd#2455]
## What problem does this feature solve?
这样我在tree组件外部就能给组件传节点key值拿到节点对象直接操作节点的增删改以及状态改变
## What does the proposed API look like?
提供一个TreeService服务里面提供一些工具类方法，里面就有getNodeBykey(key:string)的方法

**Comment by simplejason** [comment]
此需求不属于组件需求，可以自行获取 NzTreeNode 数组去实现
