### ISSUE TITLE
Notification 组件需要有“关闭时的回调函数”这种操作

### ISSUE THREAD

**Issue by victor-fa** [NG-ZORRO/ng-zorro-antd#2458]
通知提醒框，十分需要一个关闭时的回调函数
手动关闭之后能告诉开发者提醒框目前最新状态，是否已关闭~
方便开发者进行下一步操作

如图所示：

![image](https://user-images.githubusercontent.com/17930138/48529053-63caaf00-e8cc-11e8-935d-312edaea3a56.png)

可以模仿 [element-angular](https://github.com/ElemeFE/element-angular) 的组件 [Notification](https://element-angular.faas.ele.me/notice/notification) 有个回调

如图所示：

![image](https://user-images.githubusercontent.com/17930138/48529168-e7849b80-e8cc-11e8-841c-231c2220b403.png)

**Comment by victor-fa** [comment]
@ng-zorro-bot 这是个意见或建议~
我认为这种弹框十分需要有个回调，场景不仅是用于提醒，还可用于展示数据等……
所以这也是个很重要的问题了，望重视……

感谢您的反馈

**Comment by smile2014** [comment]
能否提供一个clearAll 关闭所有notify

**Comment by wendzhue** [comment]
> 能否提供一个clearAll 关闭所有notify
> 类似https://akserg.github.io/ng2-webpack-demo/#/toasty

你可以直接调用 `NotificationService.remove()`, 不带参数.

**Comment by smile2014** [comment]
@wendzhue  谢谢了，

**Comment by wendzhue** [comment]
I've started working on this...
