### ISSUE TITLE
ng serve --prod --aot  show error

### ISSUE THREAD

**Issue by dyh333** [NG-ZORRO/ng-zorro-antd#246]
## I'm submitting a...

<pre><code>
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
cli version is 1.3.2
zorro version is 0.5.0-rc.4
angular version is 4.2.4
cdk version is 2.0.0-beta.10

when run "ng serve --prod --aot", show error like this:
![image](https://user-images.githubusercontent.com/1221313/30155359-2b426dea-93ef-11e7-96f6-376060c2ee8f.png)

**Comment by dyh333** [comment]
@vthinkxie

**Comment by vthinkxie** [comment]
@dyh333 cdk version is 2.0.0-beta.10 is not supported yet. please use 2.0.0-beta.8
