### ISSUE TITLE
 The upload component adds an api for user-defined thumbnails.

### ISSUE THREAD

**Issue by yxxuweb** [NG-ZORRO/ng-zorro-antd#2461]
## What problem does this feature solve?
After uploading the image, you need to add a description to the image.
## What does the proposed API look like?
```
<nz-upload
    nzAction="https://jsonplaceholder.typicode.com/posts/"
    [nzCustomRequest]="customReq">
    <button nz-button>
      <i nz-icon type="upload"></i><span>Click to Upload</span>
    </button>
  </nz-upload>

```

**Comment by cipchk** [comment]
You can closed `nzShowUploadList: false`, then custom rendering file list via `nzFileList` data souce.
