### ISSUE TITLE
 the prefix of mention 

### ISSUE THREAD

**Issue by tianjy** [NG-ZORRO/ng-zorro-antd#2462]
## What problem does this feature solve?
 <nz-mention
    [nzSuggestions]="suggestions"
    (nzOnSelect)="onSelect($event)">
    <input
      placeholder="input here"
      nzMentionTrigger
      nz-input
      [prefix]="['from','where','group by']"
      [(ngModel)]="inputValue"
      (ngModelChange)="onChange($event)"
    >
  </nz-mention>

[prefix]="['from','where','group by']"

如果写 sql语句时，一个字符提及 实现不了，获得表名，字符名
## What does the proposed API look like?
[prefix]="['from','where','group by']"

**Comment by HsuanXyz** [comment]
Not support, you can use [ace](https://github.com/ajaxorg/ace/) or [monaco-editor](https://github.com/Microsoft/monaco-editor)
