### ISSUE TITLE
Please consider removing cdkConnectedOverlay element when `nz-select`s are not open, like what `nz-dropdown` does

### ISSUE THREAD

**Issue by CarterLi** [NG-ZORRO/ng-zorro-antd#2465]
## What problem does this feature solve?
We are facing serious performance issues in a page which contains many `nz-select` and `nz-autocomplete`. After some investigation, I found that when nz-select is not open, `nz-option-li`s are still in the DOM tree. It will result in performance issues when there are lots of nz-select in one page. For example there are 100 `nz-select`s in a page; each `nz-select` has 100 `nz-option`s. There will be 100*100 `nz-option-li` elements in the DOM tree, though user doesn't open any select dropdown. 

我们有一个页面有很多的 `nz-select` 和 `nz-autocomplete`，在这个页面遇到了比较严重的页面卡顿。我简单调研了一下，发现尽管下拉框没有打开，下拉框的选项元素 `nz-option-li` 仍然存在在页面上。我认为如果一个页面有很多的 `nz-select` 组件会导致性能问题。例如如果一个页面有 100 个下拉框，每个下拉框有 100 个备选项，这样 DOM 树里就会同时存在 100*100 个 `nz-option-li` 节点，虽然用户一个下拉框都没有打开。

Another problem comes from cdkConnectedOverlay. I found that the style attribute is modified when scrolling page. Scrolling events do affect scroll performance. The performance drawback can be huge when when lots of scroll events are bound in document.

还有一个问题来自于cdkConnectedOverlay。我发现我滚动页面的时候 `cdk-overlay-pane` 元素会更新 style 属性（我理解这是为了让下拉框随着页面滚动改变位置），但是滚动事件真的对页面滚动性能有很大的影响，特别是每个 `nz-select` 都有自己的 cdkConnectedOverlay，所有 overlay-pane 都会随着页面滚动更新 style 属性，这样对滚动性能影响真的很大。

I found other dropdown components like `nz-dropdown` `nz-popover` do remove cdkConnectedOverlay when they are closed. I wonder why `nz-select` is not implemented like `nz-dropdown`, but I'm suggesting that we should make `nz-select` behaves like `nz-dropdown`, to reduce possible performance issues.

我发现其他的下拉组件例如 `nz-dropdown` `nz-popover` 在关闭的时候确实会删除 cdkConnectedOverlay 元素。不知道为什么 `nz-select` 没有像 `nz-dropdown` 那样实现，但是我建议 `nz-select` 也应该像 `nz-dropdown` 那样在关闭下拉选项时移除 cdkConnectedOverlay 元素以减少可能的性能问题。

I know we are applying OnPush ChangeDetectionStrategy to improve performance. Removing invisible elements can be another effective, easy, and even more straight-forward option. Because of no elements, no components, thus no dirty-checks.

我知道我们正在给组件应用 OnPush 的变更检查策略以提升性能。删除不可见元素DOM可以是另一个有效、简单，且更为直接的方式。没有元素就没有组件，没有组件的话组件内的脏检查更无从谈起。

The official [Angular Doc](https://angular.cn/guide/structural-directives#why-emremoveem-rather-than-emhideem) do suggest removing elements when they are not visible to users to recover the unused resources. Please think twice. Thanks

[Angular的官方文档](https://angular.cn/guide/structural-directives) 建议移除用户看不见的那些 DOM 元素以回收未使用的资源。请三思。

![image](https://user-images.githubusercontent.com/6134068/48549699-787a6780-e90b-11e8-8fab-e24822b78e2b.png)

## What does the proposed API look like?

Remove cdkConnectedOverlay elements when closing `nz-select` dropdown

**Comment by vthinkxie** [comment]
ref https://github.com/angular/material2/issues/10337

**Comment by CarterLi** [comment]
> 举一个简单的异步例子，当ngModel的值为valueA，这个时候的nz-option为ngFor的空数组 listA = []，select的选中状态是空，随后listA从远程获得数据 ['valueA'] ，顶部的显示框需要更新显示的值为 'valueA'，如果这个时刻cdkConnectedOverlay已经被销毁，顶部的数据将永远不会被更新。

What about add a new property binding `nzData` ( like the one in `nz-table` )? You can subscribe its change to resolve async-data problem

像 `nz-table` 那样添加一个叫 `nzData` 的属性如何？这样的话，排序、筛选、限制最大长度都更好做，当然也可以解决异步数据的问题。

Another option is keep a virtual component tree. Instead of rendering them directly in DOM, put them into `ng-template`.

另一个想法是像虚拟DOM那样，不要直接把备选项放到DOM里，而是先放到 ng-template 里，然后再渲染。只是一个设想，从来没这样做过。

**Comment by CarterLi** [comment]
@vthinkxie Suddenly found that [ng-drawer](https://ng.ant.design/components/drawer/zh)s have the same problem, and I don't see any communication requirements for a drawer. Please remove cdkConnectedOverlay when a drawer is closed

**Comment by vthinkxie** [comment]
closed by #2741

**Comment by CarterLi** [comment]
Cool! Looking forward a new release
