### ISSUE TITLE
iconfont图标颜色bug

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#2466]
## Version
1.8.0
## Environment
windows 10 , angular 6.1.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-setup-7bbus1?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-7bbus1?file=app%2Fapp.component.html)
## Steps to reproduce
1、随便找一个iconfont上的图标
2、以下代码第二个li里
<ul nz-menu [nzMode]="'inline'" style="height:100%;" nzTheme="dark" [nzInlineCollapsed]="isCollapsed">
  <li  nz-menu-item>
     <span title><i nz-icon type="mail"></i><span>icon颜色正常</span></span>
  </li>
  <li nz-menu-item>
     <span title><i nz-icon [iconfont]="'test_icon'"></i><span>icon颜色异常</span></span>
  </li>
  <li nz-menu-item>
     <span title><i nz-icon [iconfont]="'test_icon'"></i><span>icon颜色异常</span></span>
  </li>
</ul>
3、第二个li标签颜色是黑的，并且改不了颜色
## What is expected?
<i nz-icon [iconfont]="'test_icon'"></i>颜色同ant icon
## What is actually happening?
<i nz-icon [iconfont]="'test_icon'"></i>和ant icon， 颜色一黑一白，改不过来
## Other?
关于ant-issue: 这里为什么不能上传图片，可以的话，我就能做个动图演示了。

**Comment by wendzhue** [comment]
@liwei511 The link you provided is not valid. Did you use this https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.ts as a boilerplate to create a reproduction?

I made a reproduction. It workds: https://stackblitz.com/edit/ng-zorro-antd-start-rgfghu?file=src%2Fapp%2Fapp.component.ts

**Comment by liwei511** [comment]
谢谢 @wendzhue,  找到问题了。
示例如下：https://stackblitz.com/edit/ng-zorro-antd-start-6kgvca?file=src%2Fapp%2Fapp.component.html
目前发现的原因是：我们ui做的图标 'https://www2.huayingjuhe.com/static/font/iconfont.js' 出问题。我们的图标文件中，除了icon-zhengshu（iconfont上找的)，都显示颜色异常。
