### ISSUE TITLE
carousel warnings about hammer.js

### ISSUE THREAD

**Issue by CarinaCLH** [NG-ZORRO/ng-zorro-antd#2468]
## Version
1.8.0
## Environment
windows10, angular 6.2.4
## Reproduction link
[https://ng-zorro-antd-start-lc5lqb.stackblitz.io/](https://ng-zorro-antd-start-lc5lqb.stackblitz.io/)
## Steps to reproduce
1. copy the code about carousel to my website;
2. get warings, like " The 'pan' event cannot be bound because Hammer.JS is not loaded and no custom loader has been specified."
3. I just set [nzEnableSwipe]="false";
4. I still get warnings
![image](https://user-images.githubusercontent.com/32316875/48602592-99e05f80-e9ae-11e8-988d-cf52696c4a2e.png)
5. I think for pc users, we don't need to import Hammer.JS to support gesture, so how can i get out of those warnings?
## What is expected?
without any warnings about Hammer.JS
## What is actually happening?
have warnings

**Comment by CarinaCLH** [comment]
Thank you for your reply and your great job.

**Comment by vahidvdn** [comment]
I have the same issue and swipe is not working in the carousel. Should I install hammerjs (at least before the fix)?
Why it's not a part of the project's dependencies?

**Comment by wendzhue** [comment]
@vahidvdn Recently, we refactored the component and `hammer.js` will be required no longer soon.
