### ISSUE TITLE
[nzClickHide] of nz-dropdown not work for ng-content

### ISSUE THREAD

**Issue by SoaringTiger** [NG-ZORRO/ng-zorro-antd#2473]
## Version
1.8.0
## Environment
nz 1.8, Angular CLI: 6.2.6, Node: 8.11.2, OS: darwin x64, Angular: 6.1.10
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-9zg4ta?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-9zg4ta?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
从component外部通过ng-container向drop-down添加menu item，见  stackblitz
## What is expected?
[nzClickHide]在通过ng-container添加 menu item 时也能正常的工作
## What is actually happening?
[nzClickHide] 不工作。

**Comment by vthinkxie** [comment]
受限于 https://github.com/angular/angular/issues/14842 ，通过 ng-content 透传之后的menu item的DI不会跟随投影传入，暂时无法解决。
