### ISSUE TITLE
按iconfont制作的图标，颜色异常

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#2476]
## Version
1.8.0
## Environment
windows 10, angular 6.1.8
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-6kgvca?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-6kgvca?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
直观的，我们UI做的图标文件中，除了icon-zhengshu（iconfont上找的)，都显示颜色异常。
## What is expected?
颜色正常
## What is actually happening?
颜色不正常
## Other?
首先谢谢阿里的各位大神，抱歉 之前误认为是NG-ZORRO的bug

**Comment by liwei511** [comment]
补充：icon颜色无法修改，UI也没找到具体问题，希望大神指导一下方向

**Comment by liwei511** [comment]
补充：使用老方式 <i class="iconfont icon-xxx"></i>，图标不显示。

**Comment by wendzhue** [comment]
@liwei511 

图标不能修改颜色, 是因为 UI 在绘制图标的时候已经指定了颜色 `fill="#333333"`:

![image](https://user-images.githubusercontent.com/12122021/48687940-b70b6d00-ebfe-11e8-817b-f31a2d6db084.png)

尝试将这个属性设置为 `currentColor` 或者直接删除, 我看到 `zhengshu` 这个 icon 就没有这个属性.

用老方式图标不显示:

![image](https://user-images.githubusercontent.com/12122021/48688131-c939db00-ebff-11e8-988b-7b47b1cb3829.png)

**Comment by liwei511** [comment]
谢谢 @wendzhue  , 执行 ng g ng-zorro-antd:fix-icon后，使用老方式图标可以正常显示。

**Comment by liwei511** [comment]
我批量删掉了 ' fill="#333333"', 暂时解决了问题，谢谢 @wendzhue
