### ISSUE TITLE
In nz-table, nzSortChange cannot be triggered after table headers changed

### ISSUE THREAD

**Issue by Fanoid** [NG-ZORRO/ng-zorro-antd#2484]
## Version
1.8.0
## Environment
MacOS, Chrome 70
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-4yafks](https://stackblitz.com/edit/ng-zorro-antd-start-4yafks)
## Steps to reproduce
See the stackblitz link:
1. At the beginning, click column headers will trigger nzSortChange callback;
2. 3 seconds later, colNames are changed;
3. Clicks on column headers do not trigger nzSortChange callback any longer.
## What is expected?
nzSortChange callback should be triggered.
## What is actually happening?
nzSortChange callback is not triggered.

**Comment by vthinkxie** [comment]
@Fanoid thanks for reporting, you can use [hidden] instead of *ngIf to skip this bug.

**Comment by vthinkxie** [comment]
@Fanoid 
you repeat all td and add [hidden] attribute to the one you don't want to display.

**Comment by Fanoid** [comment]
But all of the possible headers are not known in advance. Hope you guys can fix the bug soon! ^_^

**Comment by vthinkxie** [comment]
@Fanoid or you can just rerender the whole table after colNames changes
