### ISSUE TITLE
Add Danish Locale

### ISSUE THREAD

**Issue by michaelkrog** [NG-ZORRO/ng-zorro-antd#2485]
## What problem does this feature solve?
The lack of danish locale
## What does the proposed API look like?
Same as other locales.

**Comment by vthinkxie** [comment]
Hi, @michaelkrog 
Thanks for your advice, It will be great if you can create PR for this

**Comment by michaelkrog** [comment]
I am on it.. :)

**Comment by vthinkxie** [comment]
Thanks a lot! You can also create pr to https://github.com/ant-design/ant-design

**Comment by michaelkrog** [comment]
Already did 👍 
https://github.com/ant-design/ant-design/pull/12730

**Comment by vthinkxie** [comment]
Good job, thanks a lot!
