### ISSUE TITLE
TreeSelect树选择， 使用勾选框实现多选功能  显示的问题

### ISSUE THREAD

**Issue by lyj1008** [NG-ZORRO/ng-zorro-antd#2488]
## Version
1.8.0
## Environment
windows
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-wovjye?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-wovjye?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
链接中，过多选中节点 的时候， treeSelect 框内 节点值 一一排列 放不下
## What is expected?
选中的节点过多时，框内的显示 能够支持以  ‘已选择了几项 ’ 代替 n 个 一一排列 的选中的value值
## What is actually happening?
目前的显示 ： 选中的节点值 一一排列
## Other?
![image](https://user-images.githubusercontent.com/43951176/48764158-daf7ad00-ece9-11e8-9004-6ecc60fa633a.png)

**Comment by wendzhue** [comment]
I guess it's same with #2421, design problems.

**Comment by wendzhue** [comment]
Closed by #2741
