### ISSUE TITLE
nz-upload 组件中[nzFileType]="'image/png,image/jpeg'"没起作用

### ISSUE THREAD

**Issue by lishaoh** [NG-ZORRO/ng-zorro-antd#2489]
版本1.8.0
## What problem does this feature solve?
上传图片时选择相应图片格式
## What does the proposed API look like?
<nz-upload [nzFileType]="'image/png,image/jpeg'" class="img-uploader"></nz-upload>

**Comment by vthinkxie** [comment]
if you want to report bug, plz use bug reporter template, thanks.
