### ISSUE TITLE
nz-input component NgControlStatus not rendered correctly when given the ngModel binding variable a initializationvalue 

### ISSUE THREAD

**Issue by schsiung** [NG-ZORRO/ng-zorro-antd#249]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

For the given nz-demo-input-basic example, if given the ngModel binding variable a initialization value like
<code>
inputValue: string='';
</code>
The class status of nz-input becomes  _ant-input-wrapper ng-untouched ng-valid ng-dirty_

## Expected behavior
while the ng-pristine status is expected!

**Comment by schsiung** [comment]
![nzinput](https://user-images.githubusercontent.com/10345922/30193007-6b386b96-947d-11e7-8924-760c6f62f68c.png)

**Comment by vthinkxie** [comment]
It is custom ngModel component bug in angular
related https://github.com/angular/angular/issues/17294
