### ISSUE TITLE
IE11下打开模态窗口Modal，键盘按下“Backspace”，Url会退回上一步，Chrome下正常

### ISSUE THREAD

**Issue by MagicWang** [NG-ZORRO/ng-zorro-antd#2490]
## Version
1.8.0
## Environment
Win10 ie11
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-m1gmr6](https://stackblitz.com/edit/ng-zorro-antd-start-m1gmr6)
## Steps to reproduce
IE11下打开模态窗口Modal，键盘按下“Backspace”，Url会退回上一步，Chrome下正常
## What is expected?
Url不退回上一步
## What is actually happening?
Url退回上一步

**Comment by HsuanXyz** [comment]
IE 的问题

**Comment by wendzhue** [comment]
IE 在任何时候按下 backspace 都是返回, 和 Modal 没有关系.
