### ISSUE TITLE
能否在nz-input 中增加nzDisabled指令

### ISSUE THREAD

**Issue by yutao331763646** [NG-ZORRO/ng-zorro-antd#2497]
## What problem does this feature solve?
input禁止输入
## What does the proposed API look like?
nzDisabled

**Comment by vthinkxie** [comment]
nz-input 是 directive
不需要使用 nzDisabled
按照 angular 官方文档正常使用即可
https://www.angular.cn/guide/template-syntax#html-attribute-vs-dom-property
