### ISSUE TITLE
体验问题，Menu组件导致整个布局抖动

### ISSUE THREAD

**Issue by DemonCloud** [NG-ZORRO/ng-zorro-antd#25]
https://ng.ant.design/#/components/menu

只展开当前父级菜单
控制菜单开合，点击菜单，收起其他展开的所有菜单，保持菜单聚焦简洁。

Menu的 toggle会抖动.

**Comment by Maroon1** [comment]
PR #330 通过为子菜单的开合添加高度过渡效果，已经可以在子菜单间平滑过渡了
