### ISSUE TITLE
使用nzTreeTemplate实现自定义目录树时，拖拽功能不可用

### ISSUE THREAD

**Issue by lichangfeng** [NG-ZORRO/ng-zorro-antd#2501]
## Version
1.7.1
## Environment
angular6
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-2tmqz1?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-2tmqz1?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
1.创建一颗使用nzTreeTemplate实现自定义目录树
2.添加可拖拽属性
3.节点不可拖拽
## What is expected?
节点可拖拽
## What is actually happening?
节点不可拖拽

**Comment by simplejason** [comment]
需要手动添加 draggable 属性在自定义的span上

**Comment by lichangfeng** [comment]
好的  感谢 @simplejason

**Comment by iotzy** [comment]
感谢 @simplejason
