### ISSUE TITLE
Enable custom Icon when using [nzShowLine]="true"

### ISSUE THREAD

**Issue by WOOOFEI** [NG-ZORRO/ng-zorro-antd#2503]
## What problem does this feature solve?
Enable custom Icon when using [nzShowLine]="true"
## What does the proposed API look like?
希望设置[nzShowLine]="true"后叶子节点默认不显示file图标只显示连接线，如果在[nzData]绑定的数据中定义了自定义的icon则在连接线上显示自定义的icon

**Comment by whwz163** [comment]
对呀，感觉加个文件图标好怪
