### ISSUE TITLE
[BUG] carousel use with layout

### ISSUE THREAD

**Issue by tanxiaolongsky** [NG-ZORRO/ng-zorro-antd#2504]
## Version
1.8.0
## Environment
chrome 62.0.3202.89
## Reproduction link
[https://stackblitz.com/edit/angular-sjo7ja?embed=1&file=src/app/app.component.ts](https://stackblitz.com/edit/angular-sjo7ja?embed=1&file=src/app/app.component.ts)
## Steps to reproduce
default :
```
[nz-carousel-content]
height: 160px;
line-height: 160px;
```
change to :
```
[nz-carousel-content]
height: 360px;
line-height: 360px;
```
## What is expected?
when i change the carousel height , the view is don't my want need.
## What is actually happening?
The pictures overlap.

**Comment by tanxiaolongsky** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-fr1qs7?embed=1&file=src/app/app.component.ts

**Comment by tanxiaolongsky** [comment]
https://stackblitz.com/edit/angular-sjo7ja?embed=1&file=src/app/app.component.ts

**Comment by tanxiaolongsky** [comment]
![image](https://user-images.githubusercontent.com/36794109/48952350-d72f8900-ef7c-11e8-853f-ca18f4b45900.png)

**Comment by tanxiaolongsky** [comment]
```

import { Component } from '@angular/core';

@Component({
  selector: 'nz-demo-carousel-vertical',
  template: `
      <nz-layout>
      <nz-content>
        <nz-carousel nzAutoPlay>
           <div nz-carousel-content *ngFor="let index of array"><h3>{{index}}</h3></div>
        </nz-carousel>
      </nz-content>
    </nz-layout>
    `,
  styles: [
    `[nz-carousel-content] {
      text-align: center;
      height: 360px;
      line-height: 360px;
      background: #364d79;
      color: #fff;
      overflow: hidden;
    }

    h3 {
      color: #fff;
    }
    :host {
      text-align: center;
    }

    :host ::ng-deep .ant-layout-content {
      background: rgba(16, 142, 233, 1);
      color: #fff;
    }


    `
  ]
})
export class NzDemoCarouselVerticalComponent {
  array = [1, 2, 3, 4];
}

```

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-sjo7ja-tmhtsp?file=src/app/app.component.ts
