### ISSUE TITLE
form下使用input框的状态为disabled时不起作用

### ISSUE THREAD

**Issue by majinqin** [NG-ZORRO/ng-zorro-antd#2507]
## Version
1.8.0
## Environment
angular
## Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)
## Steps to reproduce
在form中加入一个input,然后input的状态置为disabled
## What is expected?
input变成不可用状态
## What is actually happening?
input的状态依然可用

**Comment by tanxiaolongsky** [comment]
``` 
<input formControlName="userName" disabled nz-input placeholder="Username">
```

**Comment by vthinkxie** [comment]
提问前务必看清楚报错
https://github.com/NG-ZORRO/ng-zorro-antd/issues/1849

**Comment by majinqin** [comment]
` <nz-form-item>
                <nz-form-label [nzSm]="4" [nzXs]="24" nzFor="email">医嘱名称</nz-form-label>
                <nz-form-control [nzSm]="20" [nzXs]="24">
                  <input
                    #input
                    nz-input
                    [disabled]="status === 'detail'"
                    formControlName="specs"
                    [(ngModel)]="formValues.specs"
                    class="input-1"
                    (input)="handleShowTable($event)"
                    (click)="handleInitTablePos($event)"
                    (keydown)="handleEnterDown($event, 0, 1)"
                  >
                  <nz-form-explain *ngIf="drugForm.get('specs').dirty && drugForm.get('specs').errors">该字段是必输的
                  </nz-form-explain>
                  <i nz-icon type="retweet" theme="outline" class="form-change-icon" (click)="changeFormType()"></i>
                </nz-form-control>
              </nz-form-item>`
这样写是不会报错的，并且diabled的效果也没有出来

**Comment by majinqin** [comment]
那我想在form下的input变成disabled应该怎么写啊

**Comment by vthinkxie** [comment]
https://netbasal.com/disabling-form-controls-when-working-with-reactive-forms-in-angular-549dd7b42110
https://stackoverflow.com/questions/42840136/disable-input-fields-in-reactive-form

**Comment by majinqin** [comment]
已经可以了，感谢
