### ISSUE TITLE
nz select 的使用体验好差，nz select 打开情况下 点击页面操作按钮

### ISSUE THREAD

**Issue by leaughing** [NG-ZORRO/ng-zorro-antd#2508]
## What problem does this feature solve?
目前打开会弹出一个层覆盖整个页面，导致用户无法点击操作页面上的可见按钮，用户操作 总是需要点击2次，这种体验简直反人类啊
## What does the proposed API look like?
希望不要覆盖任何东西，打开状态不影响我进行其他操作，失去焦点 关闭就好，

**Comment by vthinkxie** [comment]
https://material.angular.io/cdk/overlay/overview
受制于 angular cdk 的目前实现方式，可以给 https://github.com/angular/material2 提issue

**Comment by lait233** [comment]
请问楼主这个问题解决了吗。有没有变通的方法？现在体验效果确实太差了。。。
