### ISSUE TITLE
nz  layout 能否加入拖拽功能，手动调整左侧右侧，上下高度或宽度

### ISSUE THREAD

**Issue by leaughing** [NG-ZORRO/ng-zorro-antd#2509]
## What problem does this feature solve?
适用不同的宽度的屏幕，用户可自己调整
## What does the proposed API look like?
手动通过拖拉的方式调整宽度和高度，类似easyui layout 的拉动

**Comment by vthinkxie** [comment]
ng-zorro-antd 不会提供 ant design 未设计的交互功能，谢谢建议
