### ISSUE TITLE
ant-table-placeholder clips the bottom rounded corners of small tables

### ISSUE THREAD

**Issue by oestrogen** [NG-ZORRO/ng-zorro-antd#2518]
## Version
1.8.0
## Environment
any
## Reproduction link
[https://ng-zorro-antd-start-j4tdbh.stackblitz.io](https://ng-zorro-antd-start-j4tdbh.stackblitz.io)
## Steps to reproduce
- Create a small table with no data
- Look at the bottom corners of the table

## What is expected?
The rounded bottom corners of table are not clipped
## What is actually happening?
The bottom corners of the ant-table-placeholder are not rounded and therefore clip parts of the rounded corners of the table, making it look broken.

**Comment by krokofant** [comment]
It also happens on the top corners when the table has no headers.

**Comment by vthinkxie** [comment]
fixed in https://github.com/ant-design/ant-design/commit/5a1119f37d183efa0eb1a09506f64a79aff5d9f5
