### ISSUE TITLE
icon svg动态请求路径修改

### ISSUE THREAD

**Issue by xuqinggang** [NG-ZORRO/ng-zorro-antd#2526]
icon svg动态请求路径，如何修改?
svg图标动态加载，上线后默认路径为 http://xxx.com/assets/outline/user.svg
如何更改加载路径，添加/valkyrie/static前缀更改为http://xxx.com/valkyrie/static/assets/outline/user.svg？

**Comment by wendzhue** [comment]
@xuqinggang https://ng-zorro.gitee.io/components/icon/zh#nziconservice `changeAssetsSource()`.

Please read the doc before asking usage questions.
