### ISSUE TITLE
Hash模式breadcrumb问题

### ISSUE THREAD

**Issue by sustand** [NG-ZORRO/ng-zorro-antd#2538]
## Version
1.8.0
## Environment
win10,chrome66, node8.11.1
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-breadcrumb-auto-fjsa2y?file=src/app/app-routing.module.ts](https://stackblitz.com/edit/ng-zorro-breadcrumb-auto-fjsa2y?file=src/app/app-routing.module.ts)
## Steps to reproduce
1. 点击菜单，进入某个页面，生成面包屑
2. 刷新页面，发现面包屑消失
3. 点击面包屑链接，发现此链接为h5模式，跳转失败
## What is expected?
1.  刷新页面，发现面包屑存在
2.  点击面包屑链接，跳转成功
3. 某些路由中不配置`data: {
                    breadcrumb: ''
                },`，期望可过滤
## What is actually happening?
问题解决

**Comment by tanxiaolongsky** [comment]
这不单单是Hash模式breadcrumb问题吧，如下写不用Hash模式依然存在此问题：
```
export const AppRoutes: any = RouterModule.forRoot(routes);
```
https://stackblitz.com/edit/angular-ufb7vz?embed=1&file=src/app/app.module.ts

**Comment by thinkdj** [comment]
Is there a workaround / solution to this, which we can implement till a fix comes out ?

**Comment by luopeihai** [comment]
找了半天,硬是没说怎么处理,只好用猥琐路线重定义 面包屑:
1. 封装 Breadcrumb 
import { Link } from 'umi';

export const renderBreadcrumb = (routers) => {
  return (
    <div className="ant-pro-grid-content">
      <div className="ant-page-header has-breadcrumb ant-page-header-ghost">
        <div className="ant-breadcrumb">
          {routers.map((item) => {
            return (
              <span>
                <span class="ant-breadcrumb-link">
                  {item.path ? (
                    <Link to={item.path}>{item.breadcrumbName}</Link>
                  ) : (
                    <span>{item.breadcrumbName}</span>
                  )}
                </span>
                <span class="ant-breadcrumb-separator">/</span>
              </span>
            );
          })}
        </div>
      </div>
    </div>
  );
};

2. 引用 breadcrumb
import { renderBreadcrumb } from '@/components/Breadcrumb';

const CommentView: React.FC<> = (props) => {
  useEffect(() => {}, []);

  const pageHeaderRender = (routersInfo) => {
    let {
      breadcrumb: { routes },
    } = routersInfo;

    routes = [
      ...routes,
      { path: '/post/comment', breadcrumbName: '评论列表' },
      { breadcrumbName: '评论详情' },
    ];
    return renderBreadcrumb(routes);
  };

  return (
    <PageHeaderWrapper pageHeaderRender={pageHeaderRender} title={false}>
      评论详情
    </PageHeaderWrapper>
  );
};

export default CommentView;

**Comment by wendellhu95** [comment]
> 
> 
> 找了半天,硬是没说怎么处理,只好用猥琐路线重定义 面包屑:
> 
>     1. 封装 Breadcrumb
> 
> 
> ```
> import { Link } from 'umi';
> 
> export const renderBreadcrumb = (routers) => {
>   return (
>     <div className="ant-pro-grid-content">
>       <div className="ant-page-header has-breadcrumb ant-page-header-ghost">
>         <div className="ant-breadcrumb">
>           {routers.map((item) => {
>             return (
>               <span>
>                 <span class="ant-breadcrumb-link">
>                   {item.path ? (
>                     <Link to={item.path}>{item.breadcrumbName}</Link>
>                   ) : (
>                     <span>{item.breadcrumbName}</span>
>                   )}
>                 </span>
>                 <span class="ant-breadcrumb-separator">/</span>
>               </span>
>             );
>           })}
>         </div>
>       </div>
>     </div>
>   );
> };
> ```
> 
>     1. 引用 breadcrumb
> 
> 
> ```
> import { renderBreadcrumb } from '@/components/Breadcrumb';
> 
> const CommentView: React.FC<> = (props) => {
>   useEffect(() => {}, []);
> 
>   const pageHeaderRender = (routersInfo) => {
>     let {
>       breadcrumb: { routes },
>     } = routersInfo;
> 
>     routes = [
>       ...routes,
>       { path: '/post/comment', breadcrumbName: '评论列表' },
>       { breadcrumbName: '评论详情' },
>     ];
>     return renderBreadcrumb(routes);
>   };
> 
>   return (
>     <PageHeaderWrapper pageHeaderRender={pageHeaderRender} title={false}>
>       评论详情
>     </PageHeaderWrapper>
>   );
> };
> 
> export default CommentView;
> ```

哥你是不是发错地方了，这边是 Angular

**Comment by luopeihai** [comment]
> > 找了半天,硬是没说怎么处理,只好用猥琐路线重定义 面包屑:
> > ```
> > 1. 封装 Breadcrumb
> > ```
> > 
> > 
> > ```
> > import { Link } from 'umi';
> > 
> > export const renderBreadcrumb = (routers) => {
> >   return (
> >     <div className="ant-pro-grid-content">
> >       <div className="ant-page-header has-breadcrumb ant-page-header-ghost">
> >         <div className="ant-breadcrumb">
> >           {routers.map((item) => {
> >             return (
> >               <span>
> >                 <span class="ant-breadcrumb-link">
> >                   {item.path ? (
> >                     <Link to={item.path}>{item.breadcrumbName}</Link>
> >                   ) : (
> >                     <span>{item.breadcrumbName}</span>
> >                   )}
> >                 </span>
> >                 <span class="ant-breadcrumb-separator">/</span>
> >               </span>
> >             );
> >           })}
> >         </div>
> >       </div>
> >     </div>
> >   );
> > };
> > ```
> > 
> > 
> > ```
> > 1. 引用 breadcrumb
> > ```
> > 
> > 
> > ```
> > import { renderBreadcrumb } from '@/components/Breadcrumb';
> > 
> > const CommentView: React.FC<> = (props) => {
> >   useEffect(() => {}, []);
> > 
> >   const pageHeaderRender = (routersInfo) => {
> >     let {
> >       breadcrumb: { routes },
> >     } = routersInfo;
> > 
> >     routes = [
> >       ...routes,
> >       { path: '/post/comment', breadcrumbName: '评论列表' },
> >       { breadcrumbName: '评论详情' },
> >     ];
> >     return renderBreadcrumb(routes);
> >   };
> > 
> >   return (
> >     <PageHeaderWrapper pageHeaderRender={pageHeaderRender} title={false}>
> >       评论详情
> >     </PageHeaderWrapper>
> >   );
> > };
> > 
> > export default CommentView;
> > ```
> 
> 哥你是不是发错地方了，这边是 Angular

不好意思 已经删除了
