### ISSUE TITLE
No support currently for Slovene language (sl_SI)

### ISSUE THREAD

**Issue by aleksander351** [NG-ZORRO/ng-zorro-antd#2545]
## What problem does this feature solve?
Proper translations for Slovene language.
## What does the proposed API look like?
Use sl_SI as language provider.

**Comment by aleksander351** [comment]
The React version of Ant already has the translations:
https://github.com/ant-design/ant-design/blob/master/components/locale-provider/sl_SI.tsx

How can I make a pull request?

**Comment by vthinkxie** [comment]
@aleksander351  feel free to create pr, thanks a lot!

**Comment by aleksander351** [comment]
Commit 302d90a.

**Comment by aleksander351** [comment]
Adding language pack to project not working:
`ng add ng-zorro-antd --i18n=sl_SI`

**Comment by aleksander351** [comment]
The **sl_SI** language is working now. But there is **one** typo. :(
Do I have to make a new PR?
Tagged as bug fix?
Thank you.
