### ISSUE TITLE
Use other components in modal , change other components's style ,it doesn't work

### ISSUE THREAD

**Issue by angel0725** [NG-ZORRO/ng-zorro-antd#2549]
## Version
1.8.1
## Environment
Chrome 70.0.3538.110  ; Firefox
## Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)
## Steps to reproduce
click button show modal
## What is expected?
those components in modal ,their custom style doesn't work
## What is actually happening?
the components in modal ,can change their style

**Comment by vthinkxie** [comment]
plz provide correct repro link, or this issue will be closed.

**Comment by angel0725** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html

**Comment by angel0725** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-jreb65?file=src%2Fapp%2Fapp.component.html

**Comment by HsuanXyz** [comment]
`:host` not working, because modal open in outside, you can use `[nzWrapClassName]` and `::ng-deep`.

```html
<nz-modal nzWrapClassName="my-class">...</nz-modal>
```

```css
::ng-deep .my-class .ant-tabs-ink-bar{
  background-color: red;
}
```
