### ISSUE TITLE
nz-datepicker ngmodel value

### ISSUE THREAD

**Issue by cdllqos** [NG-ZORRO/ng-zorro-antd#255]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

when I use 'nz-datepicker' component, I use '[nzFormat]="'YYYY/MM/DD'"' for formatting date, yes it worked.the data dispaly as "YYYY/MM/DD" format

## Expected behavior

I want to change the ngmodel value not display value

## Environment

<pre><code>
Angular version:4.3.6

ng-zorro-antd version: 0.5.0-rc.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Windows 

Others:

</code></pre>

**Comment by vthinkxie** [comment]
support momentjs format http://momentjs.cn/docs/#/parsing/string-formats/

**Comment by cdllqos** [comment]
yes, I know it. I just have to handle format date again. I think there should have a api which can help us format the date which sends to background. In this version, the format api just changed how date looks but 
not its value.
