### ISSUE TITLE
希望给Tree组件的 getCheckedNodeList 方法增加一个参数 isLeafNode

### ISSUE THREAD

**Issue by xixiliguo** [NG-ZORRO/ng-zorro-antd#2551]
## What problem does this feature solve?
当父节点选中时,   getCheckedNodeList  只会返回该父节点, 不会返回下面所有的子节点  
有需求只获取当前已选中的叶子节点  
当参数isLeafNode为true时, 返回已选中的所有叶子节点  

比如tree如下显示, 右边table组件显示已选中员工的个人信息, 这时并不关心选中哪个部门  
```
部门A
      员工A
      员工B
部分B
      员工C
      员工D
```
## What does the proposed API look like?
getCheckedNodeList (isLeafNode: boolean)

**Comment by 100cm** [comment]
我觉得你可以通过递归方式遍历出所有叶子节点。。通过nzTreeNode 的children去遍历。

I think the way you can through the recursive traversal of all nodes by `nzTreeNode.children`

**Comment by hydeCaesar** [comment]
我觉得你使用的组件不对，作为一个树而言，上面的每个节点都应该是相同的实例，你这个请使用cascader来实现而不是tree。

**Comment by simplejason** [comment]
如果想只取叶子节点，可以自行递归遍历获取 isLeaf=true 的节点
