### ISSUE TITLE
Is there any possible to make tab nav bar sticky

### ISSUE THREAD

**Issue by zhonghua-wang** [NG-ZORRO/ng-zorro-antd#2557]
## What problem does this feature solve?
Make it possible that the tab bar of a tab set component  could stick on top (bottom or somewhere else).
## What does the proposed API look like?
make tab bar template support `nz-affix`, or add property like `[nzFixTop]='true'` to `nz-tabset`

**Comment by vthinkxie** [comment]
Will not support for some time to come,  close now
