### ISSUE TITLE
icon change from class="anticon" to nz-icon

### ISSUE THREAD

**Issue by sridharan21994** [NG-ZORRO/ng-zorro-antd#2558]
We have more than 250 icons in our application which uses class="anticon" format. Since it will be deprecated in the future, It has to be changed to nz-icon. But changing in all the 250 places is a time consuming process. Is there any way to do it in a simple and faster way?

**Comment by wendzhue** [comment]
@sridharan21994 

You can use regular expression to find and replace these `class="anticon"`. I actually did this in our official website when I was writing the new icon component.

The deprecation wouldn't happen even in the next major version, so take your time to do this.

**Comment by sridharan21994** [comment]
@wendzhue  Thank you so much for the response.
