### ISSUE TITLE
Ability to have badges appear on menu icons

### ISSUE THREAD

**Issue by KevinStirling** [NG-ZORRO/ng-zorro-antd#2560]
## What problem does this feature solve?
Currently the menu does allow you to add a badge to an icon, but it breaks the formatting of the collapsed and expanded view of the menu. It would be nice to be able to show badges in the side menu of an application. An example of the problem :

https://stackblitz.com/edit/badge-in-menu-demo

## Screenshots
**collapsed view**

<img width="886" alt="screen shot 2018-11-29 at 11 43 27 am" src="https://user-images.githubusercontent.com/3855493/49237706-cb085900-f3cc-11e8-8cdf-c384ffcd65c7.png">

**expanded view**

<img width="1391" alt="screen shot 2018-11-29 at 11 43 16 am" src="https://user-images.githubusercontent.com/3855493/49237723-d196d080-f3cc-11e8-9278-e2223a69f2a9.png">

## What does the proposed API look like?
Being able to wrap the anticon object in the `<nz-badge [nzCount]="5">` tag like so: 

```
<li nz-submenu [(nzOpen)]="openMap.sub1" (nzOpenChange)="openHandler('sub1')">
    <span title>
             <nz-badge [nzCount]="5">
                     <i class="anticon anticon-upload"></i>
              </nz-badge>
              <span>My Data</span>
     </span>
</li>
```

**Comment by churanov** [comment]
```javascript
<li nz-submenu *ngIf="isAnyItem$ | async">
  <span title>
    <i nz-icon nzType="plus" nzTheme="outline"></i>
    <span>New</span>
    <nz-badge [nzCount]="totalEditedItems$ | async"  [nzStyle]="{transform: 'translate(15%, -25%)'}"
            ></nz-badge>
  </span>
</li>
```

![image](https://user-images.githubusercontent.com/7630061/59027726-77d2ff80-8862-11e9-8df6-ba29ef893214.png)

![image](https://user-images.githubusercontent.com/7630061/59027750-87eadf00-8862-11e9-9c16-33694ce3a58b.png)
