### ISSUE TITLE
layout中的sider布局, 页面有大量空白

### ISSUE THREAD

**Issue by xixiliguo** [NG-ZORRO/ng-zorro-antd#2573]
## Version
1.8.1
## Environment
1.8.1
## Reproduction link
[https://stackblitz.com/edit/angular-wbtizz](https://stackblitz.com/edit/angular-wbtizz)
## Steps to reproduce
见链接

## What is expected?
sider的高度应该占满整个页面
## What is actually happening?
没有

**Comment by vthinkxie** [comment]
ng-zorro-antd 不会帮你写完所有的css，请根据自己的业务需求编写
高度占满整个页面，只需要一句css `nz-layout{height:100vh;}`
具体链接见下面
https://stackblitz.com/edit/angular-wbtizz-zqtsrc?file=src/app/app.component.ts
