### ISSUE TITLE
Bug I encountered using drop-down menu components

### ISSUE THREAD

**Issue by LaamGinghong** [NG-ZORRO/ng-zorro-antd#2577]
## Version
1.8.1
## Environment
Angular 7.1.0,  Windows 10 , Google Chrome 70.0.3538.77
## Reproduction link
[https://laamginghong.github.io/bang-cli/dist/bang-cli/#/pages/content/home](https://laamginghong.github.io/bang-cli/dist/bang-cli/#/pages/content/home)
## Steps to reproduce
Enter the page, click the button in the upper right corner,  and open the menu. Select the first menu item, and click it.
## What is expected?
Click the item, It will go to another routing page, and close the menu.
## What is actually happening?
However, it does jump to another page. But the menu is not closed.
## Other?
Actually, I want to use this component to jump to different routing pages such as login page.

**Comment by LaamGinghong** [comment]
However, somtimes it doesn't happen, refresh the page and try again

**Comment by vthinkxie** [comment]
duplicated with https://github.com/NG-ZORRO/ng-zorro-antd/issues/1530
ref https://github.com/angular/material2/issues/11478

**Comment by vthinkxie** [comment]
在跳转之前增加 setTimeout应该可以解决这个问题

**Comment by Tinet-zhangmd** [comment]
select框也遇到了这个问题，请问解决了吗？试过了setTimeout并不能解决
