### ISSUE TITLE
Tree组件在上万节点时会导致页面卡顿, 是否可以通过virtual scroll 解决

### ISSUE THREAD

**Issue by xixiliguo** [NG-ZORRO/ng-zorro-antd#2578]
## What problem does this feature solve?
提供大数据量下tree组件的性能问题
## What does the proposed API look like?
angular 7.0 新增 virtual scroll功能,  是否能用该特性提高tree组件的性能

**Comment by wendzhue** [comment]
Have plan for that.

**Comment by MagicWang** [comment]
7.0已经发布，但是tree没有虚拟滚动，请问这个问题还有追踪吗
