### ISSUE TITLE
使用 NzModalService 弹出的窗口， 迅雷会自动下载视频

### ISSUE THREAD

**Issue by anarckk** [NG-ZORRO/ng-zorro-antd#2579]
## Version
1.8.1
## Environment
angular ^6.0.0
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-x31efp](https://stackblitz.com/edit/ng-zorro-antd-start-x31efp)
## Steps to reproduce
前提: 电脑上安装了迅雷
点击打开弹窗
## What is expected?
打开之后不弹出迅雷
## What is actually happening?
打开之后弹出了迅雷，并出现下载框

**Comment by vthinkxie** [comment]
弹窗就是插入了一个html在body的里面，和任何框架、任何组件库的实现都是一模一样的。
