### ISSUE TITLE
1.8及以上的版本table组件在火狐浏览器上有border样式兼容问题

### ISSUE THREAD

**Issue by Itherma** [NG-ZORRO/ng-zorro-antd#2581]
![image](https://user-images.githubusercontent.com/24877853/49444400-090cdf00-f80a-11e8-8a3c-5e389e958ae2.png)

![image](https://user-images.githubusercontent.com/24877853/49444423-1cb84580-f80a-11e8-85ed-81d3edcd0731.png)
鼠标指针hover过会显示border  指针移出border又消失了

**Comment by cipchk** [comment]
duplcated of https://github.com/NG-ZORRO/ng-zorro-antd/issues/2582#issuecomment-445429878
