### ISSUE TITLE
Table row dividers in firefox not working

### ISSUE THREAD

**Issue by beckedorf** [NG-ZORRO/ng-zorro-antd#2582]
## Version
7.0.0-rc.0
## Environment
Firefox 63.0.3
## Reproduction link
https://ng.ant.design/components/table/en#components-table-demo-basic
## Steps to reproduce
Open page dividers are not shown. When hover from top to bottom dividers appear. Hovering in the other direction the dividers disappear.
## What is expected?
Dividers always shown.
## What is actually happening?
Open page dividers are not shown. When hover from top to bottom dividers appear. Hovering in the other direction the dividers disappear.

**Comment by cipchk** [comment]
A temporary solution by https://stackoverflow.com/questions/24103392/bottom-border-doesnt-show-up-in-firefox, added in `style.less`:

```less
.ant-table table {
  border-collapse: separate;
  border-spacing: 0;
}
```
