### ISSUE TITLE
ng.ant.degin can not open by https://ng.ant.degin

### ISSUE THREAD

**Issue by lovedemo** [NG-ZORRO/ng-zorro-antd#2583]
## Version
7.0.0-rc.0
## Environment
上海电信 阿里云dns
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-kkf83u](https://stackblitz.com/edit/ng-zorro-antd-start-kkf83u)
## Steps to reproduce
can not open https://ng.ant.degin.
Then I ping the ng.ant.degin,get the ip:47.52.234.18.
replace the domain,I can open the web;
## What is expected?
open the https://ng.ant.degin
## What is actually happening?
only can open use ip
## Other?
I don't know where to tell ,if disturbing, I am sorry

**Comment by vthinkxie** [comment]
GFW certificated
you can try https://ng-zorro.gitee.io/
