### ISSUE TITLE
`.cdk-overlay-container`的`z-index`值应该也由@zindex-modal-mask变量决定

### ISSUE THREAD

**Issue by ishowman** [NG-ZORRO/ng-zorro-antd#2584]
## What problem does this feature solve?
在1.8.0版本中，`@zindex-modal-mask`less变量和`NzModalServiceSERVICE `的`nzZIndex`api，均未能更改`.cdk-overlay-container`的z-index值，
这会引起Modal未能在预期的层次中展示。
造成这个问题的原因之一是`.cdk-overlay-container`被设置为`z-index: 1000`，而不是通过`@zindex-modal-mask`和`nzZIndex`去设置。
## What does the proposed API look like?
建议：
```
.cdk-overlay-container{
  z-index: @zindex-modal-mask;
}
```

**Comment by JLHwung** [comment]
I think this issue should be raised at https://github.com/ant-design/ant-design as we merely sync stylesheets from that.

**Comment by hsuanxyz** [comment]
`.cdk-overlay-container` 是 CDK 创建的唯一容器层，目前没有合理的解决修改它的 `z-index`，目前比较勉强方案是使用 `nzGetContainer` 将元素挂载在你能控制的地方(比如 body)。
