### ISSUE TITLE
I am using antd for our angular6 application but getting error in node_modules folder

### ISSUE THREAD

**Issue by KSANTHOSHKUMA** [NG-ZORRO/ng-zorro-antd#2585]
I am using antd for our application.

I am unable to provide stackblitz link which you asked . so i am placing this issue in github plesae see the issue.

thanks for you help

issue: node_modules/ng-zorro-antd/core/wave/nz-wave-renderer.d.ts(6,39): error TS1039: Initializers are not allowed in ambient contexts.

dependency in package.json: "ng-zorro-antd": "^7.0.0-rc.0",
Angular version: 6

how to resolve error. please help me.

**Comment by wendzhue** [comment]
@KSANTHOSHKUMA 7.0.0-rc.0 is for Angular 7.0.0. Please use 1.8.1 instead,
