### ISSUE TITLE
ERROR in node_modules/ng-zorro-antd/core/wave/nz-wave-renderer.d.ts(6,39): error  TS1039: Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by KSANTHOSHKUMA** [NG-ZORRO/ng-zorro-antd#2588]
## Version
7.0.0-rc.0
## Environment
error in node modules while i am using the ng zorro antd in our angular 6 application
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?embed=1&view=preview](https://stackblitz.com/edit/ng-zorro-antd-start?embed=1&view=preview)
## Steps to reproduce
https://stackblitz.com/edit/ng-zorro-antd-start
## What is expected?
error should solve to run appplication
## What is actually happening?
ERROR in node_modules/ng-zorro-antd/core/wave/nz-wave-renderer.d.ts(6,39): error
 TS1039: Initializers are not allowed in ambient contexts.
i am getting this error in command prompt

**Comment by julin69** [comment]
I have the same problem,and we are very worried.

**Comment by HsuanXyz** [comment]
@KSANTHOSHKUMA Invalid reproduce link.
@julin69 Can you provide a recurrence, or more info?

**Comment by julin69** [comment]
I dont have a reproduction link,but i can give you the steps:
ng new PROJECT_NAME
cd PROJECT_NAME
ng add ng-zorro-antd
then the command: ng serve --port 0 --open
finally you will get the same problem.You can try it.

**Comment by KSANTHOSHKUMA** [comment]
Hi @HsuanXyz Thanks for your reply, here i am unable to produce link. actually i am thinking that no need to produce any link as it is a node-modules error.
please find above screen(@julin69 ) shot of command prompt.

**Comment by HsuanXyz** [comment]
Normal work, please run `ng --version` check your environment.

```base
ng-zorro-antd: 7.0.0-rc.0

###

Angular CLI: 7.0.3
Node: 10.9.0
OS: darwin x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.3
@angular-devkit/build-angular      0.10.3
@angular-devkit/build-ng-packagr   0.10.3
@angular-devkit/build-optimizer    0.10.3
@angular-devkit/build-webpack      0.10.3
@angular-devkit/core               7.0.3
@angular-devkit/schematics         7.0.3
@angular/cdk                       7.0.2
@angular/cli                       7.0.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.3
@schematics/angular                7.0.3
@schematics/update                 0.10.3
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.3
webpack                            4.19.1
```

**Comment by KSANTHOSHKUMA** [comment]
Please find below dependencies which we are using
![image](https://user-images.githubusercontent.com/19944264/49508817-b256e200-f8a9-11e8-9f9b-23053916ef2e.png)

![image](https://user-images.githubusercontent.com/19944264/49508856-d0244700-f8a9-11e8-8304-ae9e50d6dfb7.png)

**Comment by HsuanXyz** [comment]
Try `ng add ng-zorro-antd@1.8`

**Comment by KSANTHOSHKUMA** [comment]
ok i will try and let you know
thanks for your help
@HsuanXyz

**Comment by KSANTHOSHKUMA** [comment]
great working properly. @julin69 you can try it once

**Comment by julin69** [comment]
Use this way really works:ng add ng-zorro-antd@1.8
but now my ng-zorro-antd version is ^1.8.1, not 7.0.0-rc.0, very expect your team very solve this problem in  7.0.0-rc.0 version .Thanks!
