### ISSUE TITLE
我在一个页面中使用多个<nz-select> 导致页面一直打印'setInterval' handler took 56ms导致页面卡死

### ISSUE THREAD

**Issue by zhazihong** [NG-ZORRO/ng-zorro-antd#2592]
<nz-select [nzAllowClear]="true"
                         name="assistant2"
                         style="width: 100%;"
                         [nzPlaceHolder]="'搜索助手'"
                         [(ngModel)]="assistant2.docId"
                         [nzServerSearch]="true"
                         (nzOnSearch)="searchOperDoctor($event)"
                         nzShowSearch>
                <nz-option
                  *ngFor="let option of operDocArrQueryResult"
                  [nzLabel]="option.docName"
                  [nzValue]="option.id">
                </nz-option>
 </nz-select>

searchOperDoctor是搜索数据方法, 返回数据量在100个以内, 
console中一直打印'setInterval' handler took 56ms  
最后导致页面卡死, 是否是因为我的使用不当造成的?

**Comment by liyf0520** [comment]
我也遇到相同的问题。,目前我页面有40个以上的select。当我将select注释之后页面回复正常
