### ISSUE TITLE
tree compent reset data bug

### ISSUE THREAD

**Issue by xingkoo** [NG-ZORRO/ng-zorro-antd#2596]
## Version
7.0.0-rc.0
## Environment
mac,chrome
## Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-sm7pq5](https://stackblitz.com/edit/ng-alain-setup-sm7pq5)
## Steps to reproduce
点击重现示例中的更新数据.可以看到,当数据被更新时,选中的数据被丢失.
## What is expected?
变更数据后不影响当前选中
## What is actually happening?
变更数据后,选择项丢失.

**Comment by HsuanXyz** [comment]
@xingkoo 你因该更改 `nzData` 的数据，而不是 `nzCheckedKeys`。

**Comment by xingkoo** [comment]
抱歉,demo贴错代码了.已修正.麻烦帮重新看一下.

**Comment by simplejason** [comment]
重置nzData后，数据指向的是不同对象，所以选中的key不会自动关联，需要手动重设一下checkedKeys (https://stackblitz.com/edit/ng-alain-setup-mnhhzx?file=src/app/app.component.ts)
