### ISSUE TITLE
Danish locale is not exported

### ISSUE THREAD

**Issue by michaelkrog** [NG-ZORRO/ng-zorro-antd#2598]
## Version
7.0.0-rc.0
## Environment
All
## Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/issues/2485](https://github.com/NG-ZORRO/ng-zorro-antd/issues/2485)
## Steps to reproduce
Use Danish locale
## What is expected?
The danish locale is expected to be usable.
## What is actually happening?
The danish locale is not usable because it is not exported.
## Other?
I added the danish locale but failed to actually export the locale. I will try to fix it.

**Comment by vthinkxie** [comment]
fixed in #2599
