### ISSUE TITLE
nz-avatar图标或文字没居中

### ISSUE THREAD

**Issue by liujiusheng** [NG-ZORRO/ng-zorro-antd#2600]
## Version
1.8.1
## Environment
chrome
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-wqxpyg?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-wqxpyg?file=src%2Fapp%2Fapp.component.html)
## Steps to reproduce
<nz-avatar [nzText]="2234" nzSize="large" [ngStyle]="{'background-color':'red'}" style="vertical-align: middle;"></nz-avatar>
## What is expected?
图标或文字居中显示
## What is actually happening?
偏右显示了
## Other?
测试发现由于1.8.1版本中avatar/style/index.lessk中添加了position:absolute;这一行，导致显示效果默认没居中

**Comment by HsuanXyz** [comment]
Fix via #2536
