### ISSUE TITLE
when I use nz-tabs with nz-table using fixed columns，the style doesn't work  properly

### ISSUE THREAD

**Issue by HaoxiangShen** [NG-ZORRO/ng-zorro-antd#2604]
## Version
7.0.0-rc.0
## Environment
window x64 chrome
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-z94g2w?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-z94g2w?file=src/app/app.component.html)
## Steps to reproduce
it always appear
## What is expected?
border  work  properly
## What is actually happening?
the fixed column doesn't have border

**Comment by HaoxiangShen** [comment]
![image](https://user-images.githubusercontent.com/26294584/49683579-62bf2300-fb02-11e8-851c-b9d36fa26f6f.png)

**Comment by skyoLion** [comment]
we also have this problem, before update to 1.8, it's working with no style problem.

**Comment by lishaoh** [comment]
+1
