### ISSUE TITLE
nz-tree，加载大量结点时会变得很卡，让整个页面都变得卡顿了起来，直接影响整个页面的操作。

### ISSUE THREAD

**Issue by hijjl** [NG-ZORRO/ng-zorro-antd#2608]
## Version
7.0.0-rc.0
## Environment
Win10
## Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/issues/2607](https://github.com/NG-ZORRO/ng-zorro-antd/issues/2607)
## Steps to reproduce
无
## What is expected?
可以加载大量数据吗？
## What is actually happening?
没有结果
## Other?
无

**Comment by hellojiangjialin** [comment]
Nz-tree, when loading a large number of nodes will become very card, so that the entire page becomes stuck, directly affecting the operation of the entire page.

**Comment by anarckk** [comment]
same question.  但是我用 onpush 模式解决卡的问题，改了一天多

**Comment by hellojiangjialin** [comment]
> same question. 但是我用 onpush 模式解决卡的问题，改了一天多

我这边改用了一个插件，angular-tree-component.
我试了一下，一次性加载大量节点会变得很卡。

**Comment by hellojiangjialin** [comment]
> same question. 但是我用 onpush 模式解决卡的问题，改了一天多

比较好奇大佬你的**### onpush**模式解决方式

**Comment by anarckk** [comment]
> > same question. 但是我用 onpush 模式解决卡的问题，改了一天多
> 
> 比较好奇大佬你的**### onpush**模式解决方式

就是用 changeDetection: ChangeDetectionStrategy.OnPush, 搜一搜就有了

**Comment by simplejason** [comment]
This issue has been closed due to inactivity. If you still have the problem, you can use the v9 version or asynchronous data.
