### ISSUE TITLE
Add auto width for header to fixed header table component

### ISSUE THREAD

**Issue by TylerYang** [NG-ZORRO/ng-zorro-antd#261]
- [ ] Feature request

## Current behavior

Component: table
Currently while using table component fixed header functionality. We need to set static width for each column. e.g.

```
  <nz-table #nzTable [nzDataSource]="data" [nzPageSize]="50" [nzScroll]="{ y: 240 }">
      <ng-template #nzFixedHeader>
        <thead nz-thead>
          <tr>
            <th nz-th [nzWidth]="'150px'"><span>Name</span></th>
            <th nz-th [nzWidth]="'150px'"><span>Age</span></th>
            <th nz-th><span>Address</span></th>
          </tr>
        </thead>
      </ng-template>
      <tbody nz-tbody>
        <tr nz-tbody-tr *ngFor="let data of nzTable.data">
          <td nz-td>{{data.name}}</td>
          <td nz-td>{{data.age}}</td>
          <td nz-td>{{data.address}}</td>
        </tr>
      </tbody>
    </nz-table>
```
In this example, the width of `name` column and `age` column is being set to `150px`. 

## Expected behavior
We don't need to set static width to these headers. 

## What is the motivation / use case for changing the behavior?
Data are loaded dynamically, we could not define the width before loading.

## Environment

```
Angular version: 4.2.4
ng-zorro-antd version: 0.5.0
Browser:
- [ ] Chrome (desktop) version 
- [ ] Firefox version 
- [ ] Safari (desktop) version 
- [ ] IE version 
 ```

**Comment by LinBoLen** [comment]
#### proposal
- [ ] should create an `auto width directive`. 
- [ ] when enable auto width. the directive calculate width
- [ ] detect dom change out of angular detectchange
- [ ] apply width change, just set fixed width or height implicitly

**Comment by xawill** [comment]
Any progress on this ?

**Comment by amomesso** [comment]
nzScroll is still setting nzTableLayout to fixed, but the pull request has been resolved, what am i doing wrong?

Example: https://stackblitz.com/edit/angular-mptb8j?file=src/app/app.component.ts

@vthinkxie @TylerYang
