### ISSUE TITLE
关于美化滚动条所带来Modal细节问题

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#2612]
## 现状

Modal 打开以后会根据 `NzMeasureScrollbarService` 来计算，但是这只是针对不同浏览器的结果，事实上若美化滚动以后这种方法也会失效，这会导致美化以后的结果不正确。

## 方案

针对 `NzMeasureScrollbarService` 增加一个额外的类名，例如：`class="nz-NzMeasureScrollbarService"`，用户可以针对 `nz-NzMeasureScrollbarService` 增加美化样式，从而确保美化后滚动条宽度。

**autoBodyPadding**

`autoBodyPadding` 是否自动给body加上padding及overflow来隐藏滚动条，但过于直接，对于关闭 `autoBodyPadding` 情况，可以考虑给 `body` 增加一个类名，例如：`<body class="nz-modal-open">`，这给已打开 Modal 以后有更多的想象空间。

**Comment by kzzc** [comment]
顺带提个问提,
页面上存在多个modal或drawer时,关闭其中一个,会将美化滚动条的状态样式"overflow: hidden; padding-right: 17px;"清除掉.
应该在存在多个drawer或modal的情况下,仅在关闭最后一个的时候清除body上的附加style

**Comment by nzbin** [comment]
@cipchk 个人建议能否去除 ng-alain 的滚动条美化，在 Mac 上体验不好

**Comment by cipchk** [comment]
@nzbin 这无关乎 ng-alain （有对应的开关可以关掉美化滚动条），作为UI组件库理应有更多的弹性。

**Comment by nzbin** [comment]
@cipchk 请问如何关闭滚动条美化，望赐教。另外个人觉得美化问题可以由用户在 CSS 中自行设置。
