### ISSUE TITLE
存在于多个抽屉，打开第二个抽屉，然后关闭，第一个抽屉的身体会溢出，可以drawer的示例中重现

### ISSUE THREAD

**Issue by chenxiangjun2010** [NG-ZORRO/ng-zorro-antd#2615]
## Version
7.0.0-rc.0
## Environment
最新版
## Reproduction link
[https://ng-zorro-antd-start.stackblitz.io/](https://ng-zorro-antd-start.stackblitz.io/)
## Steps to reproduce
存在于多个抽屉，打开第二个抽屉，然后关闭，第一个抽屉的身体会溢出，可以drawer的New Cookbook示例中重现，同样的代码放在stackblitz中并没有出现问题，
## What is expected?
希望打开第二层抽屉的时候，不会让第一层抽屉的body溢出
## What is actually happening?
第二层抽屉打开之后，关闭，会让第一层抽屉的body溢出

**Comment by kzzc** [comment]
是在关闭第二个抽屉时, 将美化滚动条的状态样式"overflow: hidden; padding-right: 17px;"给清除掉了.

应该在存在多个drawer或modal的情况下,仅在关闭最后一个的时候清除body上的附加style

**Comment by chenxiangjun2010** [comment]
这个是需要我自己手动去改，还是说下个版本修复呢




------------------ 原始邮件 ------------------
发件人: "kzzc"<notifications@github.com>;
发送时间: 2018年12月12日(星期三) 下午2:52
收件人: "NG-ZORRO/ng-zorro-antd"<ng-zorro-antd@noreply.github.com>;
抄送: "陈相军"<291493133@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NG-ZORRO/ng-zorro-antd] 存在于多个抽屉，打开第二个抽屉，然后关闭，第一个抽屉的身体会溢出，可以drawer的示例中重现 (#2615)




是在关闭第二个抽屉时, 将美化滚动条的状态样式"overflow: hidden; padding-right: 17px;"给清除掉了.
 
应该在存在多个drawer或modal的情况下,仅在关闭最后一个的时候清除body上的附加style

**Comment by kzzc** [comment]
我也是遇到了这个问题,等待答复

**Comment by kzzc** [comment]
> 这个是需要我自己手动去改，还是说下个版本修复呢
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "kzzc"<notifications@github.com>; 发送时间: 2018年12月12日(星期三) 下午2:52 收件人: "NG-ZORRO/ng-zorro-antd"<ng-zorro-antd@noreply.github.com>; 抄送: "陈相军"<291493133@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [NG-ZORRO/ng-zorro-antd] 存在于多个抽屉，打开第二个抽屉，然后关闭，第一个抽屉的身体会溢出，可以drawer的示例中重现 (#2615) 是在关闭第二个抽屉时, 将美化滚动条的状态样式"overflow: hidden; padding-right: 17px;"给清除掉了. 应该在存在多个drawer或modal的情况下,仅在关闭最后一个的时候清除body上的附加style — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

我也是遇到了这个问题,等待答复
