### ISSUE TITLE
官方文档打不开了都没人发现吗？还是只有我打不开？？

### ISSUE THREAD

**Issue by harrylyh** [NG-ZORRO/ng-zorro-antd#2640]

**Comment by vthinkxie** [comment]
可以尝试 ng-zorro.gitee.io 国内镜像

**Comment by hihuhu** [comment]
感谢 @vthinkxie  提供的国内镜像地址，晚上加班竟然进不去官方文档真的 有意思

**Comment by wendzhue** [comment]
For anyone who finds out our official website is down, please try https://downforeveryoneorjustme.com/ first.
