### ISSUE TITLE
路由跳转出现css transition执行出现nz-card nz-input nz-menu等闪烁

### ISSUE THREAD

**Issue by blackraindrop** [NG-ZORRO/ng-zorro-antd#2642]
## Version
7.0.0-rc.1
## Environment
angular 7.1.3
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-si4gvx](https://stackblitz.com/edit/ng-zorro-antd-start-si4gvx)
## Steps to reproduce
来回点击导航进行路由跳转出现闪烁
## What is expected?
不出现闪烁
## What is actually happening?
出现闪烁

**Comment by blackraindrop** [comment]
调试下来是主要由于ChangeDetectorRef.detectChanges导致，例如使用nz-breadcrumb自动生成面包屑、nz-back-top自动显示隐藏等等都会出新类似情况。建议在使用OnPush策略时使用ChangeDetectorRef.markForCheck进行变更检查。

**Comment by vthinkxie** [comment]
ref https://github.com/angular/angular/issues/34718
