### ISSUE TITLE
promise return false in Modal component can't stop [button ok] loading

### ISSUE THREAD

**Issue by xiehongyang** [NG-ZORRO/ng-zorro-antd#2644]
## Version
7.0.0-rc.1
## Environment
any
## Reproduction link
[https://stackblitz.com/edit/angular-efvfiu?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-efvfiu?file=src/app/app.component.ts)
## Steps to reproduce
```
 this.confirmModal = this.modal.confirm({
      nzTitle: 'Do you Want to delete these items?',
      nzContent: 'When clicked the OK button, this dialog will be closed after 1 second',
      nzOnOk: () => new Promise((resolve, reject) => {
        // setTimeout(Math.random() > 0.5 ? resolve : reject, 1000);
         setTimeout(() => {
           return false;
         }, 1000);
      }).catch(() => console.log('Oops errors!'))
    });
```
## What is expected?
when I return false, the [loading status] in OK button should be removed and back to normal status
## What is actually happening?
always loading

**Comment by cipchk** [comment]
@xiehongyang Must be call `resolve()` in `setTimeout` if you hope closed.

**Comment by xiehongyang** [comment]
> @xiehongyang Must be call `resolve()` in `setTimeout` if you hope closed.

yes, I know that, both `resolve()` and `reject()` can close the modal, but now If I want keep the Modal open, I pass `return false` to stop the Modal close, the **loading** in button OK can't be removed, how  could I remove the **loading** in that button

**Comment by cipchk** [comment]
`resolve(false)`

**Comment by St-Yukio** [comment]
> `resolve(false)`
这个好像没用,modal框还是会消失

**Comment by xiehongyang** [comment]
@St-Yukio 你方法里是promise吗，我试过了，是可以阻止 modal框关闭的

**Comment by St-Yukio** [comment]
> @St-Yukio 你方法里是promise吗，我试过了，是可以阻止 modal框关闭的

@xiehongyang 刚刚试了下 resolve(false)不行 还要在then里return false才可以,类似这样
nzOnOk: studentInfoComponent => {
        return studentInfoComponent.submitStudentInfo().then((res) => {
          if (res) {
            this.getTableData();
          }
          return res;
        });
      }
res 是resolve的true或者false

**Comment by St-Yukio** [comment]
> @St-Yukio 你方法里是promise吗，我试过了，是可以阻止 modal框关闭的

@xiehongyang 我知道原因了 谢谢...

**Comment by HiiragiMatu** [comment]
用一個state控制visible 用promise控制按鈕狀態
visible: isVisible,
onOk() { 
  return new Promise((resolve, reject) => { 
      resolve(false);
