### ISSUE TITLE
table的滚动区域width设置最大值

### ISSUE THREAD

**Issue by cuicuicuinice** [NG-ZORRO/ng-zorro-antd#2647]
## What problem does this feature solve?
自适应单元格内容长度，当 当前宽度已经无法装下当前列和列的内容时候，表格宽度会自动变宽
## What does the proposed API look like?
可以设置自适应宽度最大值和最小值，如果不设置，可以无限增长宽度根据内容

**Comment by cuicuicuinice** [comment]
目前有这种宽度自适应的解决方案吗？
因为表格body宽度就算可以自动适应内容宽度，但是head表头不会，最终会导致内容和表头位置错位

**Comment by vthinkxie** [comment]
目前还暂时没有方案支持这种实现

**Comment by vthinkxie** [comment]
duplicated #261
