### ISSUE TITLE
nz-tree 如果设置某个节点的checked为true时，刚好这个节点拥有子节点，那么这个节点的所以子节点都会被选中，强制设置其子节点checked为false都不管用

### ISSUE THREAD

**Issue by isfong** [NG-ZORRO/ng-zorro-antd#2655]
## Version
7.0.0-rc.1
## Environment
linux
## Reproduction link
[https://stackblitz.com/edit/angular-igexfk-qbb24v]
(https://stackblitz.com/edit/angular-igexfk-qbb24v)
## Steps to reproduce
重现链接查看
## What is expected?
希望只是按照nodes 的真实属性进行设置是否checked，如果需要在需要数据回显的需求下 根本没法办到回显那些被勾选了哪些没有勾选
## What is actually happening?
重现链接查看

**Comment by cnfanhua** [comment]
我也遇到过这个问题。
现在使用以下组合的方式来选中节点，不知道还有没有其它解决方案。
`[nzCheckStrictly]="true" `
` [nzCheckedKeys] = "defaultSelectedKeys"`

**Comment by isfong** [comment]
> 我也遇到过这个问题。
> 现在使用以下组合的方式来选中节点，不知道还有没有其它解决方案。
> `[nzCheckStrictly]="true" `
> ` [nzCheckedKeys] = "defaultSelectedKeys"`
我已经放弃了checked属性，使用selected属性来代替，暂时能满足需求，等于是舍弃了checkebox
