### ISSUE TITLE
Click event for  nz-card - nzActions

### ISSUE THREAD

**Issue by merihs** [NG-ZORRO/ng-zorro-antd#2670]
## What problem does this feature solve?
I created a nz-card with nzActions using ng-template. In the example in ngzorro's web site we are only able to set click event to icon or nz-avatar. Some icons or avatars are a little bit small and user are not able to click properly. Is it possible to set click event to whole nzActions area. 
(ng-template creates 'li' automatically so it would be great to set a function to ng-template so to li indirectly.)

## What does the proposed API look like?
<nz-card [nzActions]="[actionEdit,actionDelete]">
   <p>Card Content</p>
</nz-card>
<ng-template #actionEdit (click)="editStep(step)">
   <i nz-icon type="edit"></i>
</ng-template>
<ng-template #actionDelete (click)="deleteStep(step)">
    <i nz-icon type="delete"></i>
</ng-template>

**Comment by NearZXH** [comment]
I have a template solution, you can modified the style of the nz-card-action，make the tag `li` is contained the width and height， [here is a demo.](https://stackblitz.com/edit/ng-zorro-card)

**Comment by merihs** [comment]
@NearZXH Thanks for the demo, this is exactly what I'm looking for. ;) Thanks

**Comment by RyanEntrostat** [comment]
@NearZXH How can I pass variables (context) into the templates so that it can be passed into the on click function?

Typically with ngTemplate you would define the let-context and then set the context when you call the template, with the nzActions (and other card template attributes) I am unable to work out how to pass the content to the template through the card.

**Comment by MAGICSCIENTIST** [comment]
@RyanEntrostat Have you solve the problem that how to pass the content? I'm facing the same problem..

**Comment by siweipancc** [comment]
> @RyanEntrostat Have you solve the problem that how to pass the content? I'm facing the same problem..

a bad but useful idea  is to look up  its parent , as its source code looks like this 
![image](https://user-images.githubusercontent.com/51185888/59344094-f2f35480-8d3f-11e9-87a1-e50249ac5612.png)
i seems i can use tag-name **nz-card**
i need to find parent's id so i go up with a loop, and here the ways i try:  
-  a loop in html

```
<div *ngFor="let article of articles;index as index" nz-col [nzSpan]="8">
            <nz-card [nzTitle]="article.lastModifiedDate|date" [id]="article.id"
                     [nzActions]="[actionEdit,actionDelete]">
              <a style="text-decoration: none;color: black" [routerLink]="['/note',article.id,'view']">
                <p>{{article.content.substr(0, 60)}}</p>
              </a>
            </nz-card>
          </div>
```

- and a template in html

```<ng-template #actionEdit >
  <i nz-icon nzType="edit" nzTheme="outline"  (click)="gotoEdit($event)"></i>
</ng-template>
````

- and a function in *.ts.file
```
  gotoEdit(e: MouseEvent) {
    let element = e.srcElement;
    while ('nz-card'.toUpperCase() !== element.tagName) {
      element = element.parentElement;
      console.log(element.tagName);
    }
    console.log(`element.getAttribute('id') = ${element.getAttribute('id')}`);
  }
```
- it works well and prints
![image](https://user-images.githubusercontent.com/51185888/59344894-88dbaf00-8d41-11e9-8680-282e7f6b621c.png)

hope it helps
@RyanEntrostat @MAGICSCIENTIST

**Comment by NearZXH** [comment]
@RyanEntrostat @MAGICSCIENTIST @siweipancc 
Because Ng-zorro not provide the [ngTemplateOutletContext] in its code. so there is no good way to realize it.
But i'm comfused that why do you need to do this, you can pass the variables in the function easily, i guess you have a multiple nz-card so you want to different things to each one. Here is a [stackblitz](https://stackblitz.com/edit/ng-zorro-card) demo.

**Comment by siweipancc** [comment]
> @RyanEntrostat @MAGICSCIENTIST @siweipancc
> Because Ng-zorro doesn't provide the `[ngTemplateOutletContext]` in its code. so there is no good way to realize it.
> But i'm confused that why do you need to do this, you can pass the variables in the function easily, i guess you have multiple `nz-card`s so you want to do different things to each one. Here is a [stackblitz](https://stackblitz.com/edit/ng-zorro-card) demo.

thanks for good solution. 

btw: Maybe I have attentioned too much on #referrence that forget so much perspective,  sad
