### ISSUE TITLE
Calendar Day View

### ISSUE THREAD

**Issue by merihs** [NG-ZORRO/ng-zorro-antd#2671]
## What problem does this feature solve?
It would be a great benefit if a calendar component had a Day View.
## What does the proposed API look like?
Day | Month | Year

**Comment by wilsoncook** [comment]
@merihs Do you mean a day view contains only Hour/Minute/Second selections? Or what you want is like below:
![image](https://user-images.githubusercontent.com/1631659/51674559-ecbc4000-200b-11e9-927b-3b715371d8b9.png)

**Comment by merihs** [comment]
@wilsoncook

Hourly view is exactly what I want. I add a few example.

---- Google Calendar ----
![google-calendar](https://user-images.githubusercontent.com/6755868/51678859-6e04da00-1fee-11e9-8ff7-866fa612cec9.PNG)

---- Outlook Calendar ----
![outlook-calendar](https://user-images.githubusercontent.com/6755868/51678864-70ffca80-1fee-11e9-8bcb-f3547953be97.PNG)

---- angular-calendar from mattlewis92 ----
![sample](https://user-images.githubusercontent.com/6755868/51679022-d94eac00-1fee-11e9-9198-4d788b347872.PNG)

Thanks

**Comment by wendzhue** [comment]
React does not provide such an option. https://ant.design/components/calendar/

Actually it's a different component (you can see that its layout is totally different) and needs design ing. Maybe you could open an issue in Ant Design first? Thank you!
