### ISSUE TITLE
下拉框组件虚构时会崩

### ISSUE THREAD

**Issue by 18469645** [NG-ZORRO/ng-zorro-antd#269]
NzDropDownComponent.prototype.ngOnDestroy = function () {
        this._subscription && this._subscription.unsubscribe();
    };

当页面跳转，调用页面组件里下拉组件的虚构函数时，会崩在这里this._subscription.unsubscribe();。改成这样 this._subscription && this._subscription.unsubscribe();才正常。应该是虚构时this._subscription这个对像已不存在

**Comment by wilsoncook** [comment]
Perhaps you call `ngOnDestroy` (in)directly before `nz-dropdown`'s `ngAfterViewInit`, the `_subscription` is initialized at `ngAfterViewInit`? Would u pls provider more information about your dev scene or code to determine whether needs judging conditions here.

**Comment by osbertngok** [comment]
Confirm can reproduce this. May need some time to do a minimal reproduceable case.

**Comment by ryancui-** [comment]
+1
