### ISSUE TITLE
table pagination pagesize for custom

### ISSUE THREAD

**Issue by dax369888** [NG-ZORRO/ng-zorro-antd#2690]
## What problem does this feature solve?
I think it would be grate to have ability to custom the pagesize by the user,because each one may have different requirement about pagesize in the same table. 
## What does the proposed API look like?
Let the users input a number for setting their pagesize,then it can be recorded in the pagesize option array.

**Comment by vthinkxie** [comment]
plz read the doc

https://ng.ant.design/components/table/en

[nzPageSizeOptions] | 页数选择器可选值 | number[] | [ 10, 20, 30, 40, 50 ]
-- | -- | -- | --
