### ISSUE TITLE
@ViewChild(NzTableComponent)  return null when using --prod build option

### ISSUE THREAD

**Issue by kikong** [NG-ZORRO/ng-zorro-antd#2696]
## Version
1.8.1
## Environment
ng-zorro-antd=>1.8.1 chrome=> 71.0.3578.98
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-viewchild](https://stackblitz.com/edit/ng-zorro-antd-start-viewchild)
## Steps to reproduce
"NzTableComponent is found by @ViewChild" will be showed in dev mod. 
but display "NzTableComponent can't be found by @ViewChild"  message when building app with below cmd
```
ng build --prod --aot --build-optimizer
```
## What is expected?
the same result with dev mod
## What is actually happening?
 "NzTableComponent can't be found by @ViewChild" in production mod

**Comment by kevin100702** [comment]
NzTreeComponent也有相同问题

**Comment by tommas3210** [comment]
+1 same problem

**Comment by vthinkxie** [comment]
ref https://github.com/madoar/angular-archwizard/issues/131#issuecomment-455797868

**Comment by wxpxzdj** [comment]
这是 Angular 的 bug吗，持续关注中~

**Comment by hsuanxyz** [comment]
Could not be reproduced in the latest version(10.x), welcome to open a new issue if have any similar problems.
