### ISSUE TITLE
Bootstrap's global Margin Padding style is overwritten

### ISSUE THREAD

**Issue by baiyunchen** [NG-ZORRO/ng-zorro-antd#270]
## Before use Zorro
![image](https://user-images.githubusercontent.com/10071911/30269672-3cc6f740-971c-11e7-8f4f-324ae6cc634e.png)

## After Use Zorro
![image](https://user-images.githubusercontent.com/10071911/30269627-0ecd6194-971c-11e7-9509-cf13f6bbbf8b.png)

## I use chrome dev tools see styles found,zerror use `<style>` tag define some styles that contain the following code:
![image](https://user-images.githubusercontent.com/10071911/30269813-d9ad2b10-971c-11e7-9ade-eb7644cae8ae.png)

**Comment by vthinkxie** [comment]
duplicated #147  
related https://github.com/ant-design/ant-design/issues/4331

**Comment by baiyunchen** [comment]
@vthinkxie I think Zorro is best to be compatible with bootstrap, because the bootstrap ecosystem is perfect ,so it can help to use Zorro team to save a lot of cost.

**Comment by thegatheringstorm** [comment]
@baiyunchen Sir, [ANT DESIGN](https://ant.design/)  A UI Design Language

**Comment by baiyunchen** [comment]
@thegatheringstorm  sorry,I went to the wrong field, and I was referring to some ant-based controls.eg. Ant Design of React,NG-ZORRO

**Comment by thegatheringstorm** [comment]
:smile:
The behavior of the two will be consistent.
However,the use of some components may vary as a result of some of the Angular's distinctive features.
:smile:

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/0.7.x/docs/customize-theme/zh
