### ISSUE TITLE
对component API 可传null的地方 添加 null类型支持

### ISSUE THREAD

**Issue by Sevenonclick** [NG-ZORRO/ng-zorro-antd#2700]
## What problem does this feature solve?
解决强制类型检查编译不过的问题（公司要求严格类型检查，文档告诉我要用null，但是接口定义并不支持接收null参数）
## What does the proposed API look like?
```nzFooter: string | TemplateRef<{}> | Array<ModalButtonOptions<T> | null>;```

**Comment by vthinkxie** [comment]
plz track #2884
