### ISSUE TITLE
When i foreach nz-steps  ,then i dont know how to set  [nzDescription] as TemplateRef for every one

### ISSUE THREAD

**Issue by julin69** [NG-ZORRO/ng-zorro-antd#2702]
## Version
1.8.1
## Environment
local test environemnt
## Reproduction link
[https://ng-zorro-antd-start-7nuxhm.stackblitz.io](https://ng-zorro-antd-start-7nuxhm.stackblitz.io)
## Steps to reproduce
When i foreach nz-steps  ,then i dont know how to set  [nzDescription] as TemplateRef for every one
## What is expected?
[nzDescription] can set params as symbol,and <ng-template>can set #xxxx params
## What is actually happening?
I cant set params to [nzDescription] and <ng-template>

**Comment by julin69** [comment]
I want to achieve this effect,my code like this:
![image](https://user-images.githubusercontent.com/34527159/50476535-7378ff80-0a03-11e9-8069-2d03bd6e3b2b.png)

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-yugkak?file=src/app/app.component.html

**Comment by julin69** [comment]
Thank you very much.
