### ISSUE TITLE
对话框nz-modal中增加drag-drop

### ISSUE THREAD

**Issue by liuxiqian** [NG-ZORRO/ng-zorro-antd#2705]
## What problem does this feature solve?
对话框nz-modal中增加drag-drop
## What does the proposed API look like?
https://material.angular.io/cdk/drag-drop/overview

**Comment by vthinkxie** [comment]
dragDrap是一个directive，完全可以自己引入实现，框架不会复写 material 已经提供的 directive 功能

**Comment by plusGo** [comment]
> dragDrap是一个directive，完全可以自己引入实现，框架不会复写 material 已经提供的 directive 功能

全局modal components都需要支持drag时，目前不支持全局配置。全局modal配置项是否可以添加title

**Comment by wendellhu95** [comment]
应该提供一种方式或者在文档增加一个 FAQ 介绍如何在通过 API 调用打卡 modal 时支持 drag
