### ISSUE TITLE
table表格固定底部行

### ISSUE THREAD

**Issue by jinxiangqiang** [NG-ZORRO/ng-zorro-antd#2706]
## What problem does this feature solve?
多种合计等场景需要合计金额固定在底部
## What does the proposed API look like?
<tr  bottom='0'></tr>

**Comment by vthinkxie** [comment]
ng-zorro-antd 是 Angular 版本 Ant Design 的实现，这意味着只有 Ant Design 支持的交互、功能 才会被 ng-zorro-antd 实现。


可以给 https://github.com/ant-design/ant-design 提 issue，我们会同步 feature
