### ISSUE TITLE
[BUG] type mismatch in NzInputComponent

### ISSUE THREAD

**Issue by thegatheringstorm** [NG-ZORRO/ng-zorro-antd#271]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

* ERROR in /ng-zorro-antd/src/components/input/nz-input.component.ts (149,7): Type 'string | boolean | AutoSizeType' is not assignable to type 'boolean | AutoSizeType'.
  Type 'string' is not assignable to type 'boolean | AutoSizeType'.

* ERROR in /ng-zorro-antd/src/components/input/nz-input.directive.component.ts (72,7): Type 'string | boolean | AutoSizeType' is not assignable to type 'boolean | AutoSizeType'.
  Type 'string' is not assignable to type 'boolean | AutoSizeType'.

## Environment

<pre><code>
Angular version: 4.0.0

ng-zorro-antd version: 0.5.0
</code></pre>

**Comment by vthinkxie** [comment]
it is not a mismatch, it is just a hack, with this code `nzAutosize` could work like an attribute.
```typescript
    <nz-input [(ngModel)]="inputValueOne" nzType="textarea" nzAutosize nzPlaceHolder="Autosize height based on content lines"></nz-input>

```

**Comment by thegatheringstorm** [comment]
@vthinkxie Got it,thanks!
