### ISSUE TITLE
Missing DomSanitizer arguments

### ISSUE THREAD

**Issue by KhaledSMQ** [NG-ZORRO/ng-zorro-antd#2721]
## Version
7.0.0-rc.3
## Environment
Windows
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-uax5bc](https://stackblitz.com/edit/ng-zorro-antd-start-uax5bc)
## Steps to reproduce
in 
https://github.com/NG-ZORRO/ng-zorro-antd/blob/6554cf51ccbce08c755b0a3b8a9e968771c3113d/components/icon/nz-icon.service.ts#L143
you have to pass DomSanitizer 
## What is expected?
passing DomSanitizer to super icon service
## What is actually happening?
arguments missed
## Other?
check https://github.com/ant-design/ant-design-icons/blob/39d709f11e47f8a9c32ba2449f8f7df09f77f959/packages/icons-angular/lib/component/icon.service.ts#L64

**Comment by wendzhue** [comment]
@KhaledSMQ 

Currently, `ng-zorro-antd` is depending on `@ant-design/icons-angular` 2.0.0-beta.1. And in that version, the constructor on `IconService` is:

```ts
constructor(
    protected _rendererFactory: RendererFactory2,
    @Optional() protected _handler: HttpBackend,
    @Optional() @Inject(DOCUMENT) protected _document: any
  ) {
    this._renderer = this._rendererFactory.createRenderer(null, null);
    if (this._handler) {
      this._http = new HttpClient(this._handler);
    }
  }
```

And I've opened a pr #2641 to update this dependency.

Thanks for you care.
