### ISSUE TITLE
In the case of browser scaling, the lazy loading of the select component is invalid.(在浏览器缩放情况下，select组件的懒加载失效)

### ISSUE THREAD

**Issue by Zeppelinsaikou** [NG-ZORRO/ng-zorro-antd#2725]
## Version
7.0.0-rc.3
## Environment
win10 Chrome Version 71
## Reproduction link
[https://stackblitz.com/edit/angular-qkex4r?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-qkex4r?file=src/app/app.component.ts)
## Steps to reproduce
Adjust browser zoom to 80% , then lazy loading will fail 
调整浏览器缩放至80%，select组件的下拉加载就会失去作用
## What is expected?
Load data on scroll.
## What is actually happening?
It doesn't work

**Comment by DouglasOGarrido** [comment]
Hi guys, any update on this? Thks.

**Comment by vthinkxie** [comment]
fixed in next version
