### ISSUE TITLE
nz-sider添加自定义的mouseenter事件，二级菜单未消失

### ISSUE THREAD

**Issue by nightwaking** [NG-ZORRO/ng-zorro-antd#2727]
现在我想做一个类似阿里云后台的菜单效果。鼠标mouseenter时菜单打开，但是submenu本身有一个mouseenter事件，中间有一个动画时间。导致了菜单展开后，二级菜单还没有消失。这种有什么好的解决方法吗

**Comment by vthinkxie** [comment]
menu 增加 time option.

**Comment by nightwaking** [comment]
你好，我对time option不太理解，是setTimeout吗。

**Comment by vthinkxie** [comment]
@nightwaking 这个是备注，我们后面会提供类似的配置项

**Comment by nightwaking** [comment]
好的，谢谢

**Comment by vthinkxie** [comment]
经过讨论后该组件不应使用submenu实现，暂时关闭，如果有其他需求欢迎重新提issue
