### ISSUE TITLE
Static position datepicker 

### ISSUE THREAD

**Issue by Halomaple** [NG-ZORRO/ng-zorro-antd#2728]
## What problem does this feature solve?
Current the popup datepicker works very well but user some time needs a already open datepicker to quickly select a date. It can be achieved by using `nzOpen=true` but the position of opened datepicker is absolute and it is placed under the 'cdk-overlay-connected-position-bounding-box' which cover the whole view portal. 

So the tricky thing is: when the layout or offset of the 'fake' container where the orginal <nz-date-picker></nz-date-picker> is placed in is changed, the datepicker will overflow cause the `left` or `top` of its absolute position is not changed.

If ng-zorro-antd can provide static opened datepicker, that would be much nicer. Static and opened datepicker is helpful for date selection.

Thanks. 

## What does the proposed API look like?
Add a new nzStatic of type boolean default to false. When it is true, use position: static for the datepicker and place it under the original container (where the &lt;nz-date-picker&gt;&lt;/nz-date-picker&gt; is locating at).

**Comment by wilsoncook** [comment]
@Halomaple Would <nz-calendar> match your requirements?

**Comment by krokofant** [comment]
@wilsoncook What do you mean?

**Comment by Halomaple** [comment]
@wilsoncook  I think the datepicker should offer a option to use `position:static` so that it will stay inside the container.

**Comment by theadley** [comment]
This could also lead to another useful API entry for `nzInline` which could hide the input field and instead show an inline, open date/month/range/week picker.

**Comment by wendellhu95** [comment]
I belive that this feature is already implemented in a previous PR#6436.
