### ISSUE TITLE
响应式表达校验放在  框架自定义的 maxlength 之后可以达到自定义的效果，

### ISSUE THREAD

**Issue by yjph83** [NG-ZORRO/ng-zorro-antd#2733]
## What problem does this feature solve?
响应式表达校验放在  框架自定义的 maxlength 之后可以达到自定义的效果，
## What does the proposed API look like?
期望的官网能够详细说使用规则；

**Comment by yjph83** [comment]
方式1：
confirmationValidator = (control: FormControl): { [ s: string ]: boolean } => {
......
  };
 方式2：
 userNameAsyncValidator = (control: FormControl) => Observable.create((observer: Observer<ValidationErrors>) => {
   ......
  });

感觉在应用方式2的时候，不能放在 Validators.maxLength 之后，请问这个是怎么回事啊？我方法中有正则表达式校验和调用后台接口api异步校验

**Comment by vthinkxie** [comment]
issue不接收纯angular问题，见谅
