### ISSUE TITLE
collapse: support custom icon

### ISSUE THREAD

**Issue by HsuanXyz** [NG-ZORRO/ng-zorro-antd#2736]
## What problem does this feature solve?

Support custom expand icon

## What does the proposed API look like?

https://github.com/ant-design/ant-design/pull/12212
https://github.com/ant-design/ant-design/pull/14060

**Comment by danranVm** [comment]
I am trying to solve this issue, but I have some difficulties.

I don't know how to get the element inside the `ng-template` and add a class to it.

I hope to get your help, this is sample code: [stackblitz](https://stackblitz.com/edit/ng-template-element)

**Comment by wendzhue** [comment]
@danranVm Try this: https://stackblitz.com/edit/ng-template-element-vzbamn?file=src/app/app.component.ts.

I guess the template's element if 'extracted' or somehow.

**Comment by danranVm** [comment]
thx,  i know what to do .

**Comment by danranVm** [comment]
thx, i know what to do .

**Comment by wendzhue** [comment]
@danranVm Feel free to file a PR!

**Comment by vthinkxie** [comment]
closed in #2783
