### ISSUE TITLE
Sync i18n files from antd

### ISSUE THREAD

**Issue by wendzhue** [NG-ZORRO/ng-zorro-antd#2738]
I found that some languages are currently not supported in `ng-zorro-antd` but supported in `ant-design/ant-design`. Since `ng-zorro-antd` is an Angyular implementation of Ant Design, it would be convenient to sync i18n files from there.

**Comment by dingjules** [comment]
If `ant-design/ant-design` can split the i18n part out as an independent module would be better.

**Comment by krokofant** [comment]
This is mentioned in Milestone II https://github.com/NG-ZORRO/ng-zorro-antd/issues/2474

**Comment by wendzhue** [comment]
@krokofant Yes, I added that. 🤣
