### ISSUE TITLE
表格支持单选某行

### ISSUE THREAD

**Issue by xixiliguo** [NG-ZORRO/ng-zorro-antd#2747]
## What problem does this feature solve?
业务需求从表格中只选中一行, 类似阿里云上创建虚拟机时选择哪一个具体实例规格  

select选择器信息太少  
## What does the proposed API look like?
```
<th nzShowRadio [nzValue]=data.name></th>
```

**Comment by xiaoyiaishide** [comment]
可以自己为表头添加 radiobutton，使用radioGroup包裹，绑定change事件将当前data传入进去，就能实现单选效果。

**Comment by s97712** [comment]
可以用样式吗，比如点击哪行哪行高亮

**Comment by s97712** [comment]
@xiaoyiaishide
