### ISSUE TITLE
Modal afterClose observable never completes

### ISSUE THREAD

**Issue by dnbo** [NG-ZORRO/ng-zorro-antd#2749]
## Version
7.0.0-rc.3
## Environment
Mac OS
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-hfcdxp](https://stackblitz.com/edit/ng-zorro-antd-start-hfcdxp)
## Steps to reproduce
Pipe an observable array of objects into a `concatMap` to open a modal for each object in sequence. Return the `Observable<any>` from the `modalRef.afterClose` function to the outer observable. The inner observable `afterClose` never completes.
## What is expected?
The inner observable to complete.
## What is actually happening?
The inner observable never completes.
### Work around
Piping the `afterClose` to `take(1)` to force `source.complete` to be called.

**Comment by atxkm** [comment]
Not yet, 8.0

**Comment by atxkm** [comment]
已经8.0了，没有解决，没法用 await afterClose
