### ISSUE TITLE
0.5.0 在代码中使用@ViewChild引用组件实例，目前的导出名感觉不太好

### ISSUE THREAD

**Issue by yiji** [NG-ZORRO/ng-zorro-antd#275]
例如引用分页组件
import { ɵcw } from 'ng-zorro-antd';
@ViewChild('pagination') pagination: ɵcw;

如果有别的写法请告诉我

**Comment by LinBoLen** [comment]
应该要把 Pagination 导出

**Comment by vthinkxie** [comment]
@yiji thanks for your feedback, we will take it into consideration.
