### ISSUE TITLE
How to get the index of nz-list loop

### ISSUE THREAD

**Issue by yang-small-fan** [NG-ZORRO/ng-zorro-antd#2750]
## What problem does this feature solve?
It's very useful to me.
## What does the proposed API look like?
Thank you！

**Comment by wendzhue** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/3f07279302cdcae0c6baa1befae52319d1bf322f/components/list/nz-list.component.html#L15

We have passed the index to the template, so all you have to do is to `let` another variable in your template passed to `nzRenderItem`.

@cipchk Is this explained or necessary to explain in docs?

**Comment by yang-small-fan** [comment]
Thank you @wendzhue  
 Do you mean to use let-index in templates like item let-item?I do this with the same object as item。
![image](https://user-images.githubusercontent.com/33932653/50804877-f155d880-132a-11e9-8443-bf2ab929fc10.png)

**Comment by wendzhue** [comment]
@yang-small-fan It should be `<ng-template #item let-item let-index="index">`.

This is Angular's DSL. Read Angular's doc if you have doubts about it.

**Comment by yang-small-fan** [comment]
wow！This grammar is something I don't know. Maybe I neglected it carelessly. Thank you @wendzhue .
