### ISSUE TITLE
Timeline nzMode 

### ISSUE THREAD

**Issue by hzyyy** [NG-ZORRO/ng-zorro-antd#2752]
## Version
7.0.0-rc.3
## Environment
windows 10, chrome71
## Reproduction link
[https://ng-zorro-antd-start-mbbahx.stackblitz.io/](https://ng-zorro-antd-start-mbbahx.stackblitz.io/)
## Steps to reproduce
copy and paste
## What is expected?
Can display the effect normally
## What is actually happening?
Timeline nzMode Failure m；Unable to center and to the right；
## Other?
无法居中和靠右边，重现无问题；

**Comment by wendzhue** [comment]
Check your version. Only supported after 7.0.0-rc.1.

With information provided above, we can do nothing to help.

**Comment by hzyyy** [comment]
> 检查你的版本。仅在7.0.0-rc.1之后受支持。
> 
> 根据上面提供的信息，我们无能为力。

How should I check the version?
