### ISSUE TITLE
ng build -  --prod flag produces error

### ISSUE THREAD

**Issue by Selion05** [NG-ZORRO/ng-zorro-antd#2753]
## Version
7.0.0-rc.3
## Environment
ubuntu 1604, node v11.6.0
## Reproduction link
[https://github.com/Selion05/build-bug](https://github.com/Selion05/build-bug)
## Steps to reproduce
ng build --prod
## What is expected?
no error
## What is actually happening?
ERROR in : Unexpected value 'NzLayoutModule in (...)/ng-zorro-antd/ng-zorro-antd.d.ts' imported by the module 'AppModule in (...)/app.module.ts'. Please add a @NgModule annotation.

**Comment by wendzhue** [comment]
You can't just throw us a project and hope us to find out where went wrong. Please provide a minimum reproduction of your problem. Use stackblitz please.

**Comment by Selion05** [comment]
this is an empty project (ng new ...) just imported NzLayoutModule in AppModule  and then `ng build --prod` i don't think more minimal is possible... 

I just did a quick search and couldn't find a way to run cli commands there?
```
git clone https://github.com/Selion05/build-bug  build-bug && cd build-bug && npm install && ng build --prod
```

**Comment by wendzhue** [comment]
https://github.com/Selion05/build-bug/blob/b6ceb25f2884f6eca19c2b1e5987315acf08ea86/src/app/app.module.ts#L16

Do not import a submodule directly. Import `NgZorroAntdModule` instead. See: https://ng.ant.design/docs/faq/zh#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%8F%90%E4%BE%9B%E6%A8%A1%E5%9D%97%E5%8D%95%E7%8B%AC%E5%BC%95%E5%85%A5.

**Comment by krokofant** [comment]
The wording in the getting started is maybe a bit wrong:
> /** import ng-zorro-antd root module，you should import NgZorroAntdModule instead in sub module **/
    NgZorroAntdModule

Should it say "instead of"?

**Comment by krokofant** [comment]
Ref #2826
