### ISSUE TITLE
new component: countdown/statistics

### ISSUE THREAD

**Issue by wendzhue** [NG-ZORRO/ng-zorro-antd#2754]
Ref: https://github.com/ant-design/ant-design/pull/14154.

So many new components recently! 😆

**Comment by wendzhue** [comment]
This component seems not complicated to implement. Consider it to be `Good First Issue`?

**Comment by wendzhue** [comment]
Closed by #2760.

**Comment by thinkdj** [comment]
Proposing an enhancement: Instead of keeping this as a 'nz-countdown' (which is restricted to countdown, and of time alone), can we have a **countup+countdown that works for both numbers and time** ?
