### ISSUE TITLE
notification description cant add css styles, and cant add click function, they are not work

### ISSUE THREAD

**Issue by julin69** [NG-ZORRO/ng-zorro-antd#2755]
## Version
1.8.1
## Environment
local environment
## Reproduction link
[https://ng-zorro-antd-start-5pgvxy.stackblitz.io](https://ng-zorro-antd-start-5pgvxy.stackblitz.io)
## Steps to reproduce
When i add notification description css styles and click functions, they are not work
## What is expected?
 notification description can set css styles and can add click functions
## What is actually happening?
 notification description  set css styles and add click functions, they are not work

**Comment by wendzhue** [comment]
Why style won't work:

* Angular has restrictions on inline HTML. For example, inline style.
* You can use class name and global style to make it work: https://stackblitz.com/edit/ng-zorro-antd-start-hxfdak?file=src/app/notify/notify.component.ts

Why callback won't work:

* It's not a template. Angular wouldn't know you wrote a callback here.

Please be sure that you have a sound understanding of Angular before using a component kit.

**Comment by julin69** [comment]
But i still dont know how to add click function,and let it work,help,help!

**Comment by vthinkxie** [comment]
notification.template should support pass $implicit @wendzhue

**Comment by wendzhue** [comment]
@julin69 Try this: https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html
