### ISSUE TITLE
nz-form validateForm IE11 shows dont same as Chrome  

### ISSUE THREAD

**Issue by julin69** [NG-ZORRO/ng-zorro-antd#2756]
## Version
1.8.1
## Environment
local environment
## Reproduction link
[https://ng-zorro-antd-start-zsgdbw.stackblitz.io](https://ng-zorro-antd-start-zsgdbw.stackblitz.io)
## Steps to reproduce
When i open this page in Chrome, it is correct, and then i enter account, then it shows the error message,it is correct ,then when i enter account complete the error message missing, it is correct.
But when i open this page in IE11,and not enter anything,it shows all the error message directly,and when i enter account complete,the account error message missing,the process in IE11 is not correct.
## What is expected?
When i open this page in Chrome, it is correct, and then i enter account, then it shows the error message,it is correct ,then when i enter account complete the error message missing, it is correct.
And in IE11 the same as Chrome.
## What is actually happening?
When i open this page in IE11,and not enter anything,it shows all the error message directly,and when i enter account complete,the account error message missing,the process in IE11 is not correct.

**Comment by vthinkxie** [comment]
ref https://github.com/angular/angular/issues/15299

**Comment by julin69** [comment]
In Chrome the page is below:
![image](https://user-images.githubusercontent.com/34527159/50808111-0d13ab80-1338-11e9-9d77-198742b59edf.png)


But in IE11,it shows below:
![image](https://user-images.githubusercontent.com/34527159/50808339-046fa500-1339-11e9-930f-50f0d1400d20.png)

**Comment by julin69** [comment]
But i still dont know how to solve this problem.

**Comment by vthinkxie** [comment]
plz check the angular issue link, there are many temp solutions.

**Comment by vthinkxie** [comment]
duplicated #2111
