### ISSUE TITLE
Support internationalization and localization

### ISSUE THREAD

**Issue by zverbeta** [NG-ZORRO/ng-zorro-antd#276]
## I'm submitting a...
<pre><code>
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
At the moment, all components support only Chinese language

## Expected behavior
Components should support at least Chinese and English language

## What is the motivation / use case for changing the behavior?
A more people can use the library then now. I suggest looking towards `ngx-translate` https://github.com/ngx-translate/core 

P/S For React components there is a `LocaleProvider` https://ant.design/components/locale-provider/

**Comment by vthinkxie** [comment]
@zverbeta 
thanks for your feedback, supporting other language is on our plan. we are working on it.
