### ISSUE TITLE
Notification component surpport close callback function

### ISSUE THREAD

**Issue by tirelyl** [NG-ZORRO/ng-zorro-antd#2761]
## What problem does this feature solve?
I have a NPS score notification, i want send some info to backend when user close the notification.
## What does the proposed API look like?
options interface add a property
{
  nzOnCancel: () => void
}

**Comment by wendzhue** [comment]
Duplicate of #2458

**Comment by wendzhue** [comment]
Closing this now. @tirelyl You can track this problem in that issue.
