### ISSUE TITLE
menu Nzselected

### ISSUE THREAD

**Issue by zqzy** [NG-ZORRO/ng-zorro-antd#2762]
## Version
7.0.0-rc.3
## Environment
chrome7
## Reproduction link
[https://stackblitz.com/edit/angular-gwppyd?file=src/app/app.module.ts](https://stackblitz.com/edit/angular-gwppyd?file=src/app/app.module.ts)
## Steps to reproduce
https://stackblitz.com/edit/angular-gwppyd?file=src/app/app.module.ts
## What is expected?
修复
## What is actually happening?
menu  selected 发生改变时出现问题

**Comment by vthinkxie** [comment]
nz-menu works fine after checked, you can check it in 
https://stackblitz.com/edit/angular-gwppyd-eqeafb?file=src/app/app.component.ts
