### ISSUE TITLE
在0.5.0-rc.4 版本中  nzReadonly 不起作用 并且渲染错误

### ISSUE THREAD

**Issue by qq12020306** [NG-ZORRO/ng-zorro-antd#277]
## 版本
angualr :4.2.4
ng-zorro-antd: ^0.5.0-rc.4
windos :10

## 问题
 <nz-input formControlName="name" [nzType]="'text'" [nzReadonly]="isEdit"></nz-input>
nzReadonly 不起作用 且 渲染页面出现错误，但是nzDisabled 是好的 代码如下
<nz-input formControlName="username" [nzType]="'text'" [(ngModel)]="ariesImage.username"  [nzDisabled]="isEdit" [nzSize]="'large'"></nz-input> 正确显示

  <nz-input formControlName="name" [nzType]="'text'" [(ngModel)]="ariesImage.name" [nzReadonly]="isEdit"  [nzSize]="'large'"></nz-input> 渲染错误

![image](https://user-images.githubusercontent.com/14108070/30317875-0a979640-97de-11e7-8b09-f51c05458520.png)

**Comment by vthinkxie** [comment]
https://ng.ant.design/#/changelog
nzReadOnly is only supported in 0.5.0, please upgrade your ng-zorro-antd
