### ISSUE TITLE
Angular 某个npm包的自动导入提示 ，在打npm包的时候是如何实现的 ？

### ISSUE THREAD

**Issue by 87223178** [NG-ZORRO/ng-zorro-antd#2771]
![69b438c4-cedc-46f1-af35-861eec5b3c8d](https://user-images.githubusercontent.com/35592760/51073509-eee9da80-16ac-11e9-8e27-2bcd7c479354.png)
## What problem does this feature solve?
我想做 NG-ZORRO 项目层扩展 npm 包，扩展一些项目内用的 组件。
## What does the proposed API look like?
参考了 ng-zorro-antd 源码的 项目结构 。
现在问题是 引用 ExtendModule 的时候没有自动提示，只能手动 import { ExtendModule } from 'extend';
当手动 引用之后，使用 ExtendModule  内部组件的时候会有自动提示。
那么 ExtendModule  的根级引用 在打npm 包的时候是如何做到的？

**Comment by vthinkxie** [comment]
issue仅用于追踪bug和feature，不用于教学或任何其他功能，请见谅
