### ISSUE TITLE
trigger expanded event when call setExpanded method from treeNode

### ISSUE THREAD

**Issue by MrHuangJser** [NG-ZORRO/ng-zorro-antd#2785]
## What problem does this feature solve?
I initial a treeNodeOptions whitch like [{title: 'title', key: 'key', expanded: true}] in the async data nz-tree 。 In my expectation, this node should be initially expanded and request asynchronous data, but it is not. It does not make logical sense for this node to expand without requesting asynchronous data

## What does the proposed API look like?
当调用节点的setExpanded方法时希望能触发expandChange事件（emit the expand event when call setExpanded method）

**Comment by MrHuangJser** [comment]
> @MrHuangJser 为什么不在调用 setExpanded 的时候执行你写的 expandChange 的处理逻辑呢?

请注意看例子 我实在初始化的时候给了一个NzTreeOptions[], options数组里面可能不止一个是expand:true，也可能是多层级的，难道我要再去手动遍历整个树去判断那个的expand为true然后手动请求再赋值children？既然可以初始化expand字段为什么不直接触发expand的事件呢

**Comment by HsuanXyz** [comment]
`expanded` 初始化为 `true` 时， `children` 就不应该再通过异步的方式加载了。
否则作为一个 `@Input`, 每次 change 的时候都会触发你的异步加载方法。

**Comment by simplejason** [comment]
@MrHuangJser  当前想触发可以在手动setExpand时执行自定义方法，或者通过清除children后点击展开图标触发expandChange事件，可以进一步讨论设计模式（当前setXXX方法是独立于组件的补充方法）
