### ISSUE TITLE
Dropdown下拉菜单 在 nzDisabled 状态下  click事件依然生效

### ISSUE THREAD

**Issue by 87223178** [NG-ZORRO/ng-zorro-antd#2791]
## Version
7.0.0-rc.3
## Environment
prod
## Reproduction link
[https://ng-zorro-antd-start-mycaoz.stackblitz.io/](https://ng-zorro-antd-start-mycaoz.stackblitz.io/)
## Steps to reproduce
在 nzDisabled 状态下  click事件依然生效
## What is expected?
在 nzDisabled 状态下  click事件不生效
## What is actually happening?
在 nzDisabled 状态下  click事件依然生效

**Comment by vthinkxie** [comment]
ng-zorro-antd 的状态不会去阻塞任何 dom 的原生事件，比如drag dblclick mouseover mouseenter等等，也包括 click 事件，需要自己在click中进行判断。

**Comment by 87223178** [comment]
那 nzDisabled 的意义是啥，就是一个样式吗？

**Comment by 87223178** [comment]
或者暴露一个 nzclick 好不好

**Comment by vthinkxie** [comment]
提供 nzClick 没有任何意义，每个函数是否应该执行本来就不应该由html或者template来决定，应该由函数自身的输入确定

https://stackblitz.com/edit/ng-zorro-antd-start-tgnbwe?file=src%2Fapp%2Fapp.component.ts
