### ISSUE TITLE
Is it possible? to custom spin indicator in all view with one templateRef

### ISSUE THREAD

**Issue by moonrinnn** [NG-ZORRO/ng-zorro-antd#2792]
## What problem does this feature solve?
How to custom spin indicator in all view with one templateRef
now nz-spin can custom via attribute "nzIndicator" with TemplateRef value's type, so that template should provide templateRef for all view that nzSpin is used.
## What does the proposed API look like?
could it custom by provider in ngModule? like useValue

**Comment by wendzhue** [comment]
Like `Empty` component, some components used by our own components should provide a unified way for users to set default content.
