### ISSUE TITLE
option can still be chosen to the input when triggering ENTER in autocomplete

### ISSUE THREAD

**Issue by CC2013** [NG-ZORRO/ng-zorro-antd#2795]
## Version
1.8.1
## Environment
angular v6.1.10; node v10.15.0; win7 64bit
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-lg72sr?file=src%2Fpolyfills.ts](https://stackblitz.com/edit/ng-zorro-antd-start-lg72sr?file=src%2Fpolyfills.ts)
## Steps to reproduce
1. text "f" to the input，use enter or click some option to choose one option like "f1", and now you got "f1" in the input;
2. then change "f1" to "g";
3. just use the enter on your keybord to trigger the event;
4. then you will get "f1" not "g" in the input .
## What is expected?
maybe it can not remain the last option "f1" to input
## What is actually happening?
but I got the last option "f1"
## Other?
maybe style is a little problem in stackblitz example, but being not affected.

**Comment by HsuanXyz** [comment]
Try the latest version.
https://stackblitz.com/edit/angular-gntfwl?file=src/app/app.component.ts
