### ISSUE TITLE
modal窗口可以用于展示Form吗？

### ISSUE THREAD

**Issue by Alucardxy** [NG-ZORRO/ng-zorro-antd#28]
我用文字可以，用了form布局就会乱，看起来像是height不够导致控件换行了

**Comment by cipchk** [comment]
其实我比较建议在 `NzModalService` 增加允许modal打开一个已有组件。

**Comment by vthinkxie** [comment]
@cipchk supported already , take a look at https://ng.ant.design/#/components/modal

**Comment by giscafer** [comment]
please use a custom component

![20170816140146](https://user-images.githubusercontent.com/8676711/29349305-9ce2a2dc-828b-11e7-89c6-57f3e870deda.png)

``` html
template: `
   <form>
      <h3>use a form</h3>
       <div>
      <h4>{{_name}}</h4>
      <br/>
      <p>可以通过Subject传递数据</p>
      <div class="customize-footer">
        <button nz-button [nzType]="'primary'" [nzSize]="'large'" (click)="emitDataOutside()">
          传递数据到上层
        </button>
        <button nz-button [nzType]="'default'" [nzSize]="'large'" (click)="handleCancel()">
          返 回
        </button>
      </div>
    </div>
   <form>
  `,
```

**Comment by vthinkxie** [comment]
@Alucardxy 
It is ok to use form in modal, please check your code

<img width="552" alt="2017-08-16 2 28 34" src="https://user-images.githubusercontent.com/1506722/29350085-9fa34c34-828f-11e7-91a2-c1c14742a9fa.png">

**Comment by WOOOFEI** [comment]
@vthinkxie 您好，我在开发中也遇到了类似的疑惑。我现在正在使用文档中异步关闭的modal，modal中的表单（即多个输入框）内容绑定了当前组件中的一些变量，然后在(nzOnOk)中发请求，能实现我的需求，但是这样做很乱，于是考虑能不能将表单分离出去。您上面的解决方案是直接在子组件中去发送请求的，我还是想使用(nzOnOk)去发送请求，请问一下有没有什么比较好的解决方案、可不可以采用@output的方式去解决这个问题？
