### ISSUE TITLE
nz-range-picker 手动修改日期不点确认绑定值与显示值不一致的问题

### ISSUE THREAD

**Issue by lidong081824** [NG-ZORRO/ng-zorro-antd#2804]
## Version
1.6.0
## Environment
test
## Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)
## Steps to reproduce
选择一个日期，然后手动更改日期最上面日期，点击空白关闭弹窗，发现绑定值与显示值不一致
## What is expected?
不点击ok，手动改的值无效，或者时刻保持双向绑定值与组件显示值一致
## What is actually happening?
手动更改的日期和双向绑定的值不一致

**Comment by HsuanXyz** [comment]
@lidong081824 
你提供的复现链接无效，我猜测是低版本的问题，请尽快升级到最新版本，以下是一个简单的 DEMO：

https://stackblitz.com/edit/angular-fn9wp4?file=src/app/app.component.ts
