### ISSUE TITLE
Multiple Tree Node Drag and drop

### ISSUE THREAD

**Issue by ramaHruday** [NG-ZORRO/ng-zorro-antd#2808]
## What problem does this feature solve?
Our Tree involves Drag and drop of multiple tree nodes, not only selection of multiple nodes.
## What does the proposed API look like?
-

**Comment by simplejason** [comment]
Not support yet, you can use template to implement it now.

**Comment by ramaHruday** [comment]
hi NG-ZORRO/ng-zorro-antd
Thank You.
We tried using template for implementing multi select and drag-drop feature.
but we are only able to have a multi-select.
drag-drop was not Implementing.
Could u give us an example or demo to do that if its possible?

**Comment by simplejason** [comment]
you can read this page (https://www.sitepoint.com/accessible-drag-drop), hope to help you.

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue if you are encountering a similar or related problem.
