### ISSUE TITLE
nz-cascader使用nzLoadData延迟加载数据时，如果nz-cascader组件靠屏幕下方，但是加载的数据过长时，pop弹框不会重新定位，导致部分数据被遮挡

### ISSUE THREAD

**Issue by supersongpiao** [NG-ZORRO/ng-zorro-antd#2809]
## Version
7.0.0-rc.3
## Environment
mac os
## Reproduction link
[https://stackblitz.com/edit/angular-songlong?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-songlong?file=src/app/app.component.ts)
## Steps to reproduce
点击nz-cascader然后点击Zhejiang
## What is expected?
pop弹框可以重新定位
## What is actually happening?
pop弹框不能重新定位，部分数据被遮挡。需要重新打开nz-cascader，pop弹框才能重新定位

**Comment by wendzhue** [comment]
Ref #2181.
