### ISSUE TITLE
nzTable nzWidth 失效

### ISSUE THREAD

**Issue by weirui** [NG-ZORRO/ng-zorro-antd#2812]
## Version
7.0.0-rc.3
## Environment
angular "~7.2.0" chrome  71.0.3578.98（正式版本） （64 位）
## Reproduction link
[https://ng-zorro-antd-start-l5qnjj.stackblitz.io/](https://ng-zorro-antd-start-l5qnjj.stackblitz.io/)
## Steps to reproduce
审查该例子中一个单元格即可

## What is expected?
单元格按照设定宽度展示,比如我设置的80px
## What is actually happening?
平分展示的
## Other?
大量的列需要滚动展示

**Comment by simplejason** [comment]
确保你已使用 nzScroll 设置了x属性，如仍无法达到预期，请提供代码复现链接

**Comment by weirui** [comment]
@simplejason  复现链接 https://ng-zorro-antd-start-l5qnjj.stackblitz.io/ ,使用了 nzScroll 设置了x属性为1300px 了

**Comment by vthinkxie** [comment]
一共可scroll的width只有 1300px，你的宽度设置了50*80+80 =  4080px

**Comment by zhangxinyong12** [comment]
![image](https://user-images.githubusercontent.com/29941627/59481110-9bff9380-8e95-11e9-9228-bd3251d9785c.png)
![image](https://user-images.githubusercontent.com/29941627/59481124-aa4daf80-8e95-11e9-926a-56644b11148f.png)

**Comment by zhangxinyong12** [comment]
![image](https://user-images.githubusercontent.com/29941627/59481517-21377800-8e97-11e9-9170-0383fde36fc7.png)
![image](https://user-images.githubusercontent.com/29941627/59481532-2c8aa380-8e97-11e9-9844-6343f194ce4b.png)

**Comment by PoPOvO** [comment]
同样的问题发现了，设置nzWidth，firefox正常，chrome没有达到预期
