### ISSUE TITLE
数字输入框的ngModalChange与预期不符合

### ISSUE THREAD

**Issue by NoDocCat** [NG-ZORRO/ng-zorro-antd#2814]
## Version
7.0.0-rc.3
## Environment
Angular 7.2.1
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-723qjr](https://stackblitz.com/edit/ng-zorro-antd-start-723qjr)
## Steps to reproduce
见重现链接
## What is expected?
当值改变时触发ngModelChange
## What is actually happening?
输入框失去焦点后才会触发ngModelChange

**Comment by vthinkxie** [comment]
duplicated https://github.com/NG-ZORRO/ng-zorro-antd/issues/2708
