### ISSUE TITLE
"Select with search field" shows clear button on hover when empty

### ISSUE THREAD

**Issue by oestrogen** [NG-ZORRO/ng-zorro-antd#2823]
## Version
7.0.0-rc.3
## Environment
Any
## Reproduction link
[https://6jrkl2.run.stackblitz.io/](https://6jrkl2.run.stackblitz.io/)
## Steps to reproduce
- Hover a "Select with search field" (without anything selected and with nzAlllowClear set)
- Try to click dropdown arrow icon
## What is expected?
- Dropdown arrow icon should still be visible
- Clicking dropdown arrow icon should open the select menu
## What is actually happening?
- Dropdown arrow icon is replaced with Ⓧ icon
- Clicking Ⓧ icon does nothing
## Other?
The same component upstream in Ant behaves as expected.

**Comment by vthinkxie** [comment]
fixed by https://github.com/NG-ZORRO/ng-zorro-antd/pull/2741
plz try again when next version released
