### ISSUE TITLE
nz-table nzScroll overfolow-y set percentage value not working

### ISSUE THREAD

**Issue by TonyBaiSAP** [NG-ZORRO/ng-zorro-antd#2827]
Hello guys,
when i try to use nz-table and set the nzScroll property like this  [nzScroll]="{ x:'130%',y: '130%' }", it's not working for me. Does there any workaround to fix this? What I need is overflow-y can also use percentage value and the table can responsive change height when the browser resizing. Just like writing in CSS set the max-height value and overflow-y to auto.
The below URL can reproduce my question
[](https://ng-zorro-antd-start.stackblitz.io)

Thanks and Regards
Tony

**Comment by 1-2-3** [comment]
may be helpful:
https://1-2-3.github.io/zorro-sharper/directives/auto-height-table-demo
