### ISSUE TITLE
View update issue

### ISSUE THREAD

**Issue by mjn1154477982** [NG-ZORRO/ng-zorro-antd#2829]
## Version
7.0.0-rc.3
## Environment
angular6
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-v1vxnt?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-v1vxnt?file=src/app/app.component.html)
## Steps to reproduce
When I call the method above app.component.ts, the data changes, but the view is not updated, how can I update the view without using two-way binding
## What is expected?
The radio button view is not selected
## What is actually happening?
The radio button view is still in the previous state
## Other?
How to trigger a view update without using two-way binding

**Comment by vthinkxie** [comment]
plz use ViewChild to get the template, not the `#template`
