### ISSUE TITLE
nz-table nzScroll overfolow-y set percentage value not working

### ISSUE THREAD

**Issue by TonyBaiSAP** [NG-ZORRO/ng-zorro-antd#2830]
## What problem does this feature solve?
when i try to use nz-table and set the nzScroll property like this [nzScroll]="{ x:'130%',y: '130%' }", it's not working for me. Does there any workaround to fix this? What I need is overflow-y can also use percentage value and the table can responsive change height when the browser resizing. Just like writing in CSS set the max-height value and overflow-y to auto.
## What does the proposed API look like?
overflow-y for the table also can set percentage value

**Comment by vthinkxie** [comment]
you have to set all parent div of the overflow-y one to `height:100%` with css selector.

**Comment by MagicWang** [comment]
most of the time,table occupy the remaining space.nzScroll set fixed value is useless for me.

**Comment by 1-2-3** [comment]
may be helpful:
https://1-2-3.github.io/zorro-sharper/directives/auto-height-table-demo

**Comment by Coada** [comment]
@vthinkxie please consider opening this issue again, I am also interested in this feature.

**Comment by strybol-nicolas** [comment]
@vthinkxie I second @Coada 's suggestion, would save a lot of time and headaches.

**Comment by Jbz797** [comment]
My solution :

### xxx.component.html
```html
<div #tableContainer class="table_container">
  <nz-table [nzData]="xxx" nzPageSize="Infinity" [nzScroll]="{ y: tableHeight + 'px' }" nzShowPagination="false">
     ...
  </nz-table>
</div>
```

### xxx.component.ts
```typescript
@ViewChild('tableContainer') public tableContainer!: ElementRef;
public tableHeight!: number;

constructor(){}

public ngAfterViewInit(): void {
  this.tableHeight = (this.tableContainer.nativeElement as HTMLImageElement).clientHeight - X; // X depend of your page display
}
```

### xxx.component.scss
```scss
.table_container {
  height: 100%;
}
```

**Comment by saifxx** [comment]
My Solution.
Directive to make nz-table height to 100%
(not tested in production)

`import {
  ChangeDetectorRef,
  Directive,
  ElementRef,
  Input,
  OnDestroy,
  OnInit,
  Renderer2,
} from '@angular/core';
import { NzTableComponent } from 'ng-zorro-antd/table';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

@Directive({
  selector: '[nzTableFullHeight]',
})
export class NsTableFullHeightDirective implements OnInit, OnDestroy {

  @Input()
  baseNsTableFullHeight = 95;

  private observer: ResizeObserver;
  private resize = new Subject<void>();

  constructor(
    private element: ElementRef,
    private table: NzTableComponent<unknown>,
    private cd: ChangeDetectorRef,
    private render2: Renderer2
  ) {
    this.observer = new ResizeObserver(() => this.resize.next());
    this.resize.pipe(debounceTime(200)).subscribe(() => this.resizeTable());
  }

  ngOnInit(): void {
    this.render2.setStyle(this.element.nativeElement, 'height', '100%');
    this.observer.observe(this.element.nativeElement);
  }

  ngOnDestroy(): void {
    this.observer.disconnect();
    this.resize.complete();
  }

  private resizeTable() {
    const nzTable: HTMLElement = this.element.nativeElement;
    this.table.scrollY = `${nzTable.clientHeight - this.baseNsTableFullHeight}px`;
    this.cd.detectChanges();
  }
}
`

**Comment by JSPRH** [comment]
Thanks @saifurrehmanx, works great! Just one typo:
```diff
  private resizeTable() {
    const nzTable: HTMLElement = this.element.nativeElement;
-    this.table.scrollY = `${nzTable.clientHeight - this.baseNsTableFullHeight}px`;
+    this.table.scrollY = `${nzTable.clientHeight - this. nzTableFullHeight}px`;
    this.cd.detectChanges();
  }
```

Full fixed version:
```ts

import {
  ChangeDetectorRef,
  Directive,
  ElementRef,
  Input,
  OnDestroy,
  OnInit,
  Renderer2,
} from '@angular/core';
import { NzTableComponent } from 'ng-zorro-antd/table';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

@Directive({
  selector: '[nzTableFullHeight]',
})
export class NzTableFullHeightDirective implements OnInit, OnDestroy {

  @Input()
  nzTableFullHeight = 95;

  private observer: ResizeObserver;
  private resize = new Subject<void>();

  constructor(
    private element: ElementRef,
    private table: NzTableComponent<unknown>,
    private cd: ChangeDetectorRef,
    private render2: Renderer2
  ) {
    this.observer = new ResizeObserver(() => this.resize.next());
    this.resize.pipe(debounceTime(200)).subscribe(() => this.resizeTable());
  }

  ngOnInit(): void {
    this.render2.setStyle(this.element.nativeElement, 'height', '100%');
    this.observer.observe(this.element.nativeElement);
  }

  ngOnDestroy(): void {
    this.observer.disconnect();
    this.resize.complete();
  }

  private resizeTable() {
    const nzTable: HTMLElement = this.element.nativeElement;
    this.table.scrollY = `${nzTable.clientHeight - this.nzTableFullHeight}px`;
    this.cd.detectChanges();
  }
}
```

**Comment by vuboi** [comment]
> Thanks [@saifurrehmanx](https://github.com/saifurrehmanx), works great! Just one typo:
> 
>   private resizeTable() {
>     const nzTable: HTMLElement = this.element.nativeElement;
> -    this.table.scrollY = `${nzTable.clientHeight - this.baseNsTableFullHeight}px`;
> +    this.table.scrollY = `${nzTable.clientHeight - this.nzTableFullHeight}px`;
>     this.cd.detectChanges();
>   }
> Full fixed version:
> 
> import {
>   ChangeDetectorRef,
>   Directive,
>   ElementRef,
>   Input,
>   OnDestroy,
>   OnInit,
>   Renderer2,
> } from '@angular/core';
> import { NzTableComponent } from 'ng-zorro-antd/table';
> import { Subject } from 'rxjs';
> import { debounceTime } from 'rxjs/operators';
> 
> @Directive({
>   selector: '[nzTableFullHeight]',
> })
> export class NzTableFullHeightDirective implements OnInit, OnDestroy {
> 
>   @Input()
>   nzTableFullHeight = 95;
> 
>   private observer: ResizeObserver;
>   private resize = new Subject<void>();
> 
>   constructor(
>     private element: ElementRef,
>     private table: NzTableComponent<unknown>,
>     private cd: ChangeDetectorRef,
>     private render2: Renderer2
>   ) {
>     this.observer = new ResizeObserver(() => this.resize.next());
>     this.resize.pipe(debounceTime(200)).subscribe(() => this.resizeTable());
>   }
> 
>   ngOnInit(): void {
>     this.render2.setStyle(this.element.nativeElement, 'height', '100%');
>     this.observer.observe(this.element.nativeElement);
>   }
> 
>   ngOnDestroy(): void {
>     this.observer.disconnect();
>     this.resize.complete();
>   }
> 
>   private resizeTable() {
>     const nzTable: HTMLElement = this.element.nativeElement;
>     this.table.scrollY = `${nzTable.clientHeight - this.nzTableFullHeight}px`;
>     this.cd.detectChanges();
>   }
> }

thank you, finally i found a solution for it.
