### ISSUE TITLE
nz-tree控件如果加了nzShowLine（连接线）属性，叶子节点就会多一个图标（类似新建文件图标）

### ISSUE THREAD

**Issue by sxjlinux** [NG-ZORRO/ng-zorro-antd#2833]
## Version
7.0.0-rc.3
## Environment
window node 11.3.0 angular ^7.0.0 ng-zorro-antd ^7.0.0-rc.3
## Reproduction link
[https://ng-zorro-antd-start-yeygrj.stackblitz.io/](https://ng-zorro-antd-start-yeygrj.stackblitz.io/)
## Steps to reproduce
nz-tree控件如果加了nzShowLine（连接线）属性，叶子节点就会多一个图标（类似新建文件图标），此时如果nz-tree在加上自定义的图标时，看上去就会有两个图标似的，有点多余，如果不加连接线则看上去是正常的
## What is expected?
如果加上连接线，将那个类似新建文件的图标去掉
## What is actually happening?
加了nzShowLine（连接线）属性就会多了一个类似新建文件的图标

**Comment by simplejason** [comment]
这是因为你传递了不存在的icon，请确保你传递的icon值存在于ng zorro icon中

**Comment by whwz163** [comment]
怎样不要这个文件的图标，当他是子页点时， 是否加个props会好点

**Comment by peacejj** [comment]
@whwz163  @sxjlinux 请问去除文件这个图标，你们是怎么解决的？
