### ISSUE TITLE
Documentation over the sync process between ng zorro and ant design

### ISSUE THREAD

**Issue by krokofant** [NG-ZORRO/ng-zorro-antd#2838]
## What problem does this feature solve?
If a feature or fix is provided to ant design in what time frame would that reach ng zorro? How does this process work? I think this can be mentioned in the readme so that fixes can be provided in the right repository while a timeframe can be estimated.
## What does the proposed API look like?
Not applicable

**Comment by vthinkxie** [comment]
you can check
https://github.com/NG-ZORRO/ng-zorro-antd/pulls/ng-zorro-bot
https://nz-styles-syncer.now.sh/
