### ISSUE TITLE
cannot reset select

### ISSUE THREAD

**Issue by Akiq2016** [NG-ZORRO/ng-zorro-antd#284]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

Like #128 but i'm not using in form, just make a simple filter function by using several inputs and selects. my `resetFilter` function reset `data` as `{}`, but the value of select component do not being reset.

## Expected behavior

As what two-way binding should do, when my value is changed, it should affect my View.

## Minimal reproduction of the problem with instructions

```html
<nz-select [(ngModel)]="data.a" style="width: 100px;" nzAllowClear>
  <nz-option *ngFor="let item of list" [nzLabel]="item.viewValue" [nzValue]="item.value">
  </nz-option>
</nz-select>

<nz-input [(ngModel)]="data.b" style="width: 100px;"></nz-input>

<button type="reset" (click)="resetFilter()">reset</button>
```
```javascript
resetFilter() {
  this.data = {}
}
```

**Comment by vthinkxie** [comment]
try this.data={a:null,b:null};

**Comment by Akiq2016** [comment]
yeah it works

**Comment by vthinkxie** [comment]
@Akiq2016 we will support the undefined reset next verison. thanks for your feedback.
