### ISSUE TITLE
nz-date-picker

### ISSUE THREAD

**Issue by jiashiyan** [NG-ZORRO/ng-zorro-antd#2840]
## What problem does this feature solve?
nz-date-picker 设置初始化面板的默认时间
## What does the proposed API look like?
nz-date-picker 设置初始化面板的默认时间

**Comment by vthinkxie** [comment]
[ngModel]

**Comment by jiashiyan** [comment]
[ngModel] 会填充上input框 需求是不填充input 但是打开面板时面板默认选中当前时间点
