### ISSUE TITLE
ng-zorro 有颜色选择器(color-picker)组件吗？

### ISSUE THREAD

**Issue by FunBooWen** [NG-ZORRO/ng-zorro-antd#2843]
## What problem does this feature solve?
ng-zorro 有颜色选择器(color-picker)组件吗？我在文档里找不到有，但是在文档页脚看到你们有使用到选择主题色的。有时候希望用户自己去选择一些提醒标志的颜色，而不是程序预早去固定某个颜色，这种情况下要用到颜色选择器。
## What does the proposed API look like?
希望可以通过调用颜色选择器组件让用户在颜色选择器上选择颜色然后返回颜色代码

**Comment by vthinkxie** [comment]
ngx-color
