### ISSUE TITLE
new component: descriptions

### ISSUE THREAD

**Issue by wendzhue** [NG-ZORRO/ng-zorro-antd#2847]
~Ref https://github.com/ant-design/ant-design/pull/14529.~
Ref https://github.com/ant-design/ant-design/pull/14645.

**Comment by krokofant** [comment]
What happened to the upstream PR? Was it cherry picked or rejected?

**Comment by wendzhue** [comment]
@krokofant They file a new PR. I have updated the link.

**Comment by chenshuai2144** [comment]
对不住你 我们改名字了
