### ISSUE TITLE
使用NzModalService模块build后报错'create' of undefined

### ISSUE THREAD

**Issue by yyhuaisha** [NG-ZORRO/ng-zorro-antd#2849]
## Version
1.8.1
## Environment
windows7
## Reproduction link
[https://stackblitz.com/edit/angular-zbaqmj](https://stackblitz.com/edit/angular-zbaqmj)
## Steps to reproduce
ng build  --prod
## What is expected?
解决'create' of undefined 报错
## What is actually happening?
错误 'create' of undefined
## Other?
dev环境能够正常执行，build以后就会报错'create' of undefined。
看到有说删除了app.module.js  里面的 platformBrowserDynamic().bootstrapModule(AppModule) 解决问题的，
但是我的platformBrowserDynamic().bootstrapModule(AppModule) 只写在main.ts。以上方式无效

**Comment by vthinkxie** [comment]
直接按照官网上手指南新建一个最小项目，把你提供的代码拷贝进去，ng build --prod之后 会发现不会出现这个错误
请检查你项目的本地环境

**Comment by humblepride** [comment]
@yyhuaisha 我也遇到了相同的问题, 后来发现误把 NzModalService 放到了模块的 providers 列表里. 删掉就好了.

**Comment by ivanwonder** [comment]
@vthinkxie 我也发现这个问题了，好像是在build aot过程中把NzModalService当成了私有变量，https://github.com/NG-ZORRO/ng-zorro-antd/blob/51c0d5363a3110cc8ed89d9fb58e2c3432534ccd/components/ng-zorro-antd.module.ts#L119
这里换成`export * from './modal/index'`;貌似就可以了，这里应该是`ngc`的一个bug。可以把 NzModalService 放到新建项目的模块的 providers 列表里去验证
