### ISSUE TITLE
modal怎么阻止使用esc关掉，还不能在取消事件里return true

### ISSUE THREAD

**Issue by cuiwang137** [NG-ZORRO/ng-zorro-antd#285]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cuiwang137** [comment]
怎么解决

**Comment by cuiwang137** [comment]
如题所说，上面那些都系统填的

**Comment by vthinkxie** [comment]
not supported yet.

**Comment by cuiwang137** [comment]
找到办法了 在设置一个window.onkeydown  监测键盘事件  按键盘在开个弹窗 不过在开之前要清除之前的  这样就好了 。就关不掉了

**Comment by vthinkxie** [comment]
@cuiwang137 we will provide an option next version. thanks for your feedback.

**Comment by cuiwang137** [comment]
have nothing to do

**Comment by cuiwang137** [comment]
没事

**Comment by gsbybb** [comment]
@vthinkxie  我可以添加一个 nzEscClosable 属性给 Modal 组件和添加一个escClosable选项给NzModalService 去实现这个功能嘛？

**Comment by vthinkxie** [comment]
@gsbybb of course

**Comment by LinBoLen** [comment]
可以独立出去, 单独写个nzEscClosable显得太累赘. 可以专门写个directive来处理
