### ISSUE TITLE
timepicker can't change nzDisabledHours attribute dynamically 

### ISSUE THREAD

**Issue by mraiguo** [NG-ZORRO/ng-zorro-antd#286]
## I'm submitting a...

<pre><code>
[ ] Bug report  
## Current code

《nz-timepicker 
      [nzDisabledHours]="disableHours"
      formControlName="start_time" 
       [nzFormat]="'HH:mm'"></nz-timepicker>
《button (click)="changeDisableHours()">确定</button>
<br>
// 开始时默认的不能点击的小时时间
  disableHours = () => {
    return this.newArray(1,10);
  };
// 点击按钮后，改变的小时时间
  changeDisableHours() {
    this.disableHours = () => {
      return this.newArray(1,20);
    }
  }
## Expected behavior

当我点击button的时候，通过changeDisableHours方法我改变了disableHours输出的array，
这时我希望time-picker里面的disableHours也随之改变

## Environment

<pre><code>
Angular version: 4.3.2

ng-zorro-antd version: ^0.5.0-rc.4

Browser:
- [ ] Chrome (desktop) version XX

For Tooling issues:
- Node version: v8.4.0 
- Platform:  mac

**Comment by wilsoncook** [comment]
AFAIK, the disabled status only initialized at `nz-timepicker`'s `ngOnInit` life cycle, that's to say, the ui will not re-rendered while settled once.
