### ISSUE TITLE
Submenu lost context with ng-template

### ISSUE THREAD

**Issue by mediatec** [NG-ZORRO/ng-zorro-antd#2868]
## Version
7.0.0-rc.3
## Environment
Windows 10
## Reproduction link
[https://stackblitz.com/edit/angular-ufwakd](https://stackblitz.com/edit/angular-ufwakd)
## Steps to reproduce
Try to open submenus
## What is expected?
Submenus should renders arrows and open next level submenu on the right. It can be reproduced with horizontal menu and inline with vertical mode.
## What is actually happening?
Submenus works just as dropdowns, I think this items lost context when it was used with the ng-template

**Comment by mediatec** [comment]
Hi there!

Any updates with recursive demo that works fine in horizontal menu?

This demo is works correclty only in inline mode - https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/menu/demo/recursive.ts

Reproducing of the problem - https://stackblitz.com/edit/angular-ufwakd

Thank you!

**Comment by vthinkxie** [comment]
Hi @mediatec 
yes, the recursive demo can only work in inline menu, because there is no way to access contentchildren in ng-template outlet in current angular version.
https://github.com/angular/angular/issues/14842

**Comment by mediatec** [comment]
Thank you for fast response. I found there horizontal menu and it works as well (this is nz-menu component with horizontal mode) https://e.ng-alain.com/preview?type=theme&url=pro

Source Screenshot: https://gyazo.com/1e6b8b158c3c50583691fee85cd7d3d0
Gif: https://gyazo.com/7eb674534ccc159fb834b17732828cda 

Any mention how can this work? This really important thing to make horizontal menu working...

Thank you in advance

**Comment by vthinkxie** [comment]
@mediatec 
@cipchk may answer this question.

**Comment by cipchk** [comment]
@mediatec Sorry, i don't have a special solution, the horizontal menu usage of the pro theme is more like the WORKING part of  your https://stackblitz.com/edit/angular-ufwakd

**Comment by vthinkxie** [comment]
another solution is to convert the recursive to array and use *ngFor to the max level

**Comment by mediatec** [comment]
Thank you guys for you work!

**Comment by londomloto** [comment]
maybe this working solution

```<ul nz-menu [nzMode]="'horizontal'">
  <ng-container *ngFor="let item of menus">
    <li nz-menu-item>
      <span>{{ item.title }}</span>
    </li>
    <li nz-submenu *ngIf="item.children">
      <span title>{{item.title}}</span>
      <ul>
        <ng-container *ngTemplateOutlet="menutpl; context: { $implicit: item.children }"></ng-container>
        <ng-template #menutpl let-menus>
          <ng-container *ngFor="let item of menus">
            <li nz-menu-item>
              <span>{{ item.title }}</span>
            </li>
            <li nz-submenu *ngIf="item.children">
              <span title>{{item.title}}</span>
              <ul>
                <ng-container *ngTemplateOutlet="menutpl; context: { $implicit: item.children }"></ng-container>
              </ul>
            </li>
          </ng-container>
        </ng-template>
      </ul>
    </li>
  </ng-container>
</ul>```

**Comment by manztihagi** [comment]
Hi @londomloto,

The code is working well, unfortunately, the menu level is until 2, when having the menu 3rd level, the 2nd level will disappear.

Tx
