### ISSUE TITLE
Allow user to sort / reorder items in Transfer (maybe with the help of external library, such as cdx)

### ISSUE THREAD

**Issue by avifatal** [NG-ZORRO/ng-zorro-antd#2870]
## What problem does this feature solve?
Nothing much to explain, its a necessary feature for lists.. and  better value control
## What does the proposed API look like?
[allowValueSorting]="true"

**Comment by cipchk** [comment]
@avifatal The rendering order is determined by the `nzDataSource` values.

I don't understand what you mean. Can you give an example of why some scenes require `allowValueSorting`?

**Comment by avifatal** [comment]
Manual reorder, so when I save the data to the database I'm letting the user determine in what order.

![image](https://user-images.githubusercontent.com/12430740/53501547-0c380400-3ab5-11e9-83b7-22294cc5b3fb.png)

**Comment by xingkoo** [comment]
what is the progress of this feature?

**Comment by s641135196** [comment]
希望能支持这个可以托拽排序的， 例如： 我要导出选中的某些字段。 而这些字段一般是需要排序的。 （最好还能更改显示名称）
