### ISSUE TITLE
Customizable slider values

### ISSUE THREAD

**Issue by NikolajNielsen** [NG-ZORRO/ng-zorro-antd#2872]
## What problem does this feature solve?
My current issue is that I've several sliders going from e.g 1 to 10.000, but 80% of our users will choose numbers around 500-2.000, which leads to my request - I'd love that 50 or 70% of my slider would have values from 1-2.000 and rest of the slider would have values from 2.000 to 10.000. 

## What does the proposed API look like?
nz-slider

**Comment by wendzhue** [comment]
@NikolajNielsen This can be implemented by existing API. https://stackblitz.com/edit/angular-v8hyor-gzdce9?file=src/app/app.component.ts

In my opinion this scenario is not that common and it is not necessary to add a new API.

**Comment by wendzhue** [comment]
Please open another issue if you have other requests cannot be fulfilled by the demo provided above.
