### ISSUE TITLE
The dropdown menu for 'Select' component does not function properly when 'Select' bar is at the bottom of the screen

### ISSUE THREAD

**Issue by zdong11** [NG-ZORRO/ng-zorro-antd#2876]
## Version
7.0.0-rc.3
## Environment
Browser: Chrome: Version 71
## Reproduction link
[https://ng-zorro-antd-start-efzzwu.stackblitz.io/](https://ng-zorro-antd-start-efzzwu.stackblitz.io/)
## Steps to reproduce
Any 'Select' drop-down menu with long list and at the bottom of the screen will reproduce this issue
## What is expected?
When the 'Select' component is at the bottom of the screen, the pop-up direction of its drop-down menu should be 'Top'.
## What is actually happening?
The drop-down menu will pop-up to 'Bottom' position then move back to 'Top' position

**Comment by vthinkxie** [comment]
duplicated of #1429
