### ISSUE TITLE
Potential memory leak in components using QueryList

### ISSUE THREAD

**Issue by dominicglenn** [NG-ZORRO/ng-zorro-antd#2882]
## Version
7.0.0-rc.3
## Environment
Browser: Chrome: Version 71
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-vk1nes?file=package.json](https://stackblitz.com/edit/ng-zorro-antd-start-vk1nes?file=package.json)
## Steps to reproduce
When using a component from ngzorro that uses QueryList, the components do not seem to be freed upon ngdestroy.

In the example linked, if you check out the memory heap in chrome at the application start you can see that no nztabset is on the heap, if you click the toggle button a couple of times you will see that the number of nztabset in memory keeps on increasing even though they should be freed.

Even if you force the Garbage Collector in chrome to clear the memory, it still remains, which must mean something somewhere is referencing it.
## What is expected?
The used components should be freed from memory once they are no longer used.
## What is actually happening?
The used components keep persisting in memory after they are no longer in use.
## Other?
If you use components that don't use the querylist, e.g. nzTab by itself, this issue does not happen.

**Comment by vthinkxie** [comment]
ref https://github.com/angular/angular/issues/25459

**Comment by dominicglenn** [comment]
In the sample I have provided above I used an ngIf, but in my own code this was being used as a routed component, and going back/forth between different routes was causing the same issue to occur FYI.

**Comment by hsuanxyz** [comment]
This issue should have been fixed in ivy.
Please file a new issue if you are encountering a similar or related problem.
