### ISSUE TITLE
more strict tsconfig options

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#2884]
Should add 

```json
{
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "skipLibCheck": true,
}
```

- [x] noUnusedParameters #2960
- [x] noUnusedLocals #2959
- [x] strictNullChecks #2977
- [x] strictFunctionTypes #3019
- [x] noImplicitAny #3019
- [x] noImplicitThis #3019
- [x] skipLibCheck #2959 

in tsconfig.json -> compilerOptions .

**Comment by wendzhue** [comment]
@vthinkxie I guess add these to `tsconfig.lib.json`? Should specs have strict restrictions?

**Comment by keenondrums** [comment]
Just FYI, with "strict" set to `true` currently `ng build --prod` fails with:
```
ERROR in node_modules/ng-zorro-antd/ng-zorro-antd.d.ts.ɵjd.html(3,3): : Object is possibly 'undefined'.
node_modules/ng-zorro-antd/ng-zorro-antd.d.ts.ɵjd.html(2,3): : Object is possibly 'undefined'.
```
If I set "strictNullChecks" to `false` it passes.

**Comment by wendzhue** [comment]
@keenondrums Yeah that's a known problem. We would try to fix tslint related problems in pull requests regarding this issue.

**Comment by wendzhue** [comment]
🎉 Finally!
