### ISSUE TITLE
Support tags mode in autocomplete 

### ISSUE THREAD

**Issue by HDaghash** [NG-ZORRO/ng-zorro-antd#2887]
## What problem does this feature solve?
ability to fille the autocomplete field with multi-values. 
## What does the proposed API look like?
same like nzMode="tags" with select but instead of a dropdown list it will be a normal field with autocomplete , also if we will have the ability to customize these tags like adding icons to it it will be great

**Comment by HsuanXyz** [comment]
Ant Design does not provide this feat, you can submit a issues to [ant-design/ant-design](https://github.com/ant-design/ant-design), it will be sync if ant-design provide this feat.
