### ISSUE TITLE
nz-select 初始化问题，必须使用引用对象初始化么？

### ISSUE THREAD

**Issue by yangyi358252535** [NG-ZORRO/ng-zorro-antd#289]
可以用formControlName进行数据初始化么？ 用ngModel很不方便, 而且使用对象初始化的时候，不是引用的集合中的对象, 是初始化不上的.

**Comment by vthinkxie** [comment]
look at the doc https://ng.ant.design/#/components/form

**Comment by yangyi358252535** [comment]
thx for your explain.
