### ISSUE TITLE
Tree component optimization

### ISSUE THREAD

**Issue by supersongpiao** [NG-ZORRO/ng-zorro-antd#2890]
## What problem does this feature solve?
Hope to customize the expansion icon
## What does the proposed API look like?
https://bpta3s.run.stackblitz.io

**Comment by supersongpiao** [comment]
@vthinkxie Hope to customize tree node icon

**Comment by supersongpiao** [comment]
![e049b876-f24b-40ca-8cc4-2e2647ecfc77](https://user-images.githubusercontent.com/31645741/52776861-7c8a6280-307d-11e9-9d56-1e239132e716.png)
@vthinkxie

**Comment by fanzhengshao** [comment]
@vthinkxie Also hope to increase this feature extension. thank you very much.
