### ISSUE TITLE
menu nzMode='inline' should not work as vertical

### ISSUE THREAD

**Issue by fbchen** [NG-ZORRO/ng-zorro-antd#2899]
## Version
7.0.0-rc.3
## Environment
Mac OS 10.14.2
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-3kvofj](https://stackblitz.com/edit/ng-zorro-antd-start-3kvofj)
## Steps to reproduce
1、build nz-menu with ng-template to create sub-menus;
2、set nz-menu [nzMode]='inline'
## What is expected?
`nzMode`  should work as expand/collapse when setting as `'inline'` , or should work as popup sub-menus  when setting as `'vertical'`
## What is actually happening?
`nzMode` set to `'inline'`, but work as `'vertical'`

**Comment by vthinkxie** [comment]
do not support mixed 'inline' and 'vertical' mode under one `nz-menu`

**Comment by stvnwrgs** [comment]
Running into the same issue. @vthinkxie What do you mean with mixed inline and vertical mode? There is only one mode definition in place.

**Comment by sergioorlov** [comment]
@stvnwrgs do you find some solution ? How to make the nz-menu in nz-dropdown-menu work in inline mode ?

**Comment by stvnwrgs** [comment]
@sergioorlov no, we are using bootstrap now.
