### ISSUE TITLE
NZ_MESSAGE_CONFIG doesn't set global config for notifications

### ISSUE THREAD

**Issue by keenondrums** [NG-ZORRO/ng-zorro-antd#2900]
## Version
7.0.0-rc.3
## Environment
Angular 7.1.4
## Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-qh5r56](https://stackblitz.com/edit/ng-zorro-antd-start-qh5r56)
## Steps to reproduce
- Create a simple app
- Add `NZ_MESSAGE_CONFIG` to the list of providers to your root module ({ provide: NZ_MESSAGE_CONFIG, useValue: { nzPlacement: 'bottomRight' }}).
- Show a notification using `NzNotificationService.blank`
## What is expected?
It should appear at bottom right
## What is actually happening?
It appears at top right, which is default.
## Other?
During debug I found out that third parameter here (https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/notification/nz-notification-container.component.ts#L20) is always null. It should be our config provided with NZ_MESSAGE_CONFIG. 
`NzNotificationService.config` works as expected and currently can be considered a workaround.

**Comment by wendzhue** [comment]
@keenondrums

Why not provide `NZ_NOTIFICATION_CONFIG` instead?

 https://stackblitz.com/edit/ng-zorro-antd-start-7jysux?file=src/app/app.module.ts

**Comment by keenondrums** [comment]
@wendzhue I misread documentation and confused NZ_NOTIFICATION_CONFIG with NZ_MESSAGE_CONFIG. Sorry!
