### ISSUE TITLE
nz-select tags - Two options are selected

### ISSUE THREAD

**Issue by Lontten** [NG-ZORRO/ng-zorro-antd#2920]
## Version
7.0.0-rc.3
## Environment
ng-zorro Official website   https://ng.ant.design/components/select/en
## Reproduction link
[https://stackblitz.com/edit/angular-l7kt2u?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-l7kt2u?file=src/app/app.component.ts)
## Steps to reproduce
https://ng.ant.design/components/select/zh

Data Entry  ->  Select  ->  tags select 

Enter the letter a，There should be only one Option selected，
The two options  ( a  a10)   are all selected

0.7x   1.8x   7.0.0-rc.3
They all have such problems.
Is this a bug? I am not very sure,
This is the official website demo
But this seems strange.

## What is expected?
There should be only one Option selected
## What is actually happening?
The  two  Option are all selected.
## Other?
Please forgive me for my bad English (from Google Translate)

**Comment by vthinkxie** [comment]
this bug has been fixed by #2741
plz try again when next version released
