### ISSUE TITLE
support disable animation in every component

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#2922]
`[@.disabled] = nzNoAnimation`

- [x] alert
- [x] autocomplete
- [x] cascader
- [x] collapse
- [x] drawer
- [x] dropdown
- [x] form
- [x] message
- [x] notification
- [x] popconfirm
- [x] popover
- [x] select
- [x] menu
- [x] modal
- [x] tag
- [x] timepicker
- [x] tooltip
- [x] tree
- [x] tabs
- [x] tree-select
- [x] date-picker

**Comment by leaughing** [comment]
which version  support ? why i  use  [@.disabled] = "true"    not work .
`<nz-modal #tplmodal  [@.disabled] = "true"`
