### ISSUE TITLE
生成的生产环境的文件太多了，在assets文件下有非常多的svg文件，请问怎么配置？

### ISSUE THREAD

**Issue by moonbreezee** [NG-ZORRO/ng-zorro-antd#2927]
注意：不是用 https://ng.ant.design/issue-helper/#/zh 创建的 issue 会被立即关闭。

运行的命令如下：ng build --prod --base-href ./

生成的svg文件太多了，能否合并到一个文件内进行管理，每次上传的文件太多了

**Comment by wendzhue** [comment]
@moonbreezee 这是 icon 动态加载所必需的. 如果不想要这些文件, 你需要静态引入你所用到的图标, 然后在 angular.json 里去掉对资源文件的引入. 具体请看文档.
