### ISSUE TITLE
Bug in "NzDemoLayoutSideComponent" 

### ISSUE THREAD

**Issue by yangxin9527** [NG-ZORRO/ng-zorro-antd#293]
when my left navigation beyond screen height,the bug appears in the component named "NzDemoLayoutSideComponent "。
![u0z97o q6ac96ds5tttu wi](https://user-images.githubusercontent.com/18702092/30420525-5ea7be38-996c-11e7-8ba5-8deca13252e2.png)

当我的导航超出屏幕高度，错误出现在组件命名为“nzdemolayoutsidecomponent”

**Comment by vthinkxie** [comment]
related #167 
please add overflow:auto to the style.

**Comment by yangxin9527** [comment]
![d9ce e9 ej u4 b tl](https://user-images.githubusercontent.com/18702092/30432004-e898f050-9992-11e7-9cbb-8767e298741a.png)
I'm sorry,It may have wasted your time， I'm a newbie，I don't konw this is my fault or your bug.Look the picture！I have added “overflow:auto” on it.

**Comment by vthinkxie** [comment]
just add style to ul element with 
```css
    max-height: 200px; // defined your own height;
    overflow: auto;
```

**Comment by yangxin9527** [comment]
ok,thinks

**Comment by yangxin9527** [comment]
ok,thanks
