### ISSUE TITLE
使用nz-option-group时，对分组数据重新赋值，input框无法显示已选中数据，控制台可打印选中的数据。

### ISSUE THREAD

**Issue by Eric-chengYuan** [NG-ZORRO/ng-zorro-antd#2937]
## Version
7.0.0-rc.3
## Environment
win 7 chrome  zorro 7.0.0-rc.3
## Reproduction link
[https://ng-zorro-antd-start-hsy84z.stackblitz.io](https://ng-zorro-antd-start-hsy84z.stackblitz.io)
## Steps to reproduce
1.点击‘initData’，加载第一组 分组数据  
2.点击‘firstClick’，加载第二组 分组数据
3.点击‘secondClick’,控制台可以打印 选中的数据   input框中没有显示
4.点击 ‘backToFirstData’按钮  把数据重置成第一组 分组数据  input便可显示选中的数据

1.【choose 'initData', load the first groupdata】
2.【choose  'firstClick', load the second groupdata [replace the first groupdata]】
3.【choose 'secondClick', console can print the selectedValue, but the input can not show it on the webPage】
4.【click the 'backToFirstData' reset the groupData to the first groupdata, the input can show selectedValue on the webPage again】

## What is expected?
整体替换分组数据时，input框可以显示选中数据。
## What is actually happening?
替换数据时,input框未能显示选中数据

**Comment by vthinkxie** [comment]
替换分组数据时你的 `selectedValue` 从头到尾都没有改过
https://stackblitz.com/edit/ng-zorro-antd-start-sdihdo?file=src/app/app.component.html
