### ISSUE TITLE
How to change fontsize?

### ISSUE THREAD

**Issue by AlcheXie** [NG-ZORRO/ng-zorro-antd#294]
## I'm submitting a...
<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

Now default fontsize of body is 12px.
Is it able to change to 14px or else by setting an option, not by writing css to overwrite it as it's too small?

**Comment by vthinkxie** [comment]
not supported yet, will be take into consideration next version.
duplicated #147
