### ISSUE TITLE
执行ng g ng-zorro-antd:fix-icon报错

### ISSUE THREAD

**Issue by yuying1230** [NG-ZORRO/ng-zorro-antd#2942]
"ng-zorro-antd": "^1.4.0"版本，angular的项目中执行ng g ng-zorro-antd:fix-icon 命令会报Schematic "fix-icon" not found in collection "ng-zorro-antd". 请问应该如何解决？

**Comment by wendzhue** [comment]
该命令要到 1.7.0 之后才能使用。
