### ISSUE TITLE
Component Password Strength

### ISSUE THREAD

**Issue by GabrielRodriguesS** [NG-ZORRO/ng-zorro-antd#2943]
## What problem does this feature solve?
Most web systems have a user registry with a password type entry, this is a fact.
A password strength bar is a component commonly used in these applications, so that the user meets the system password requirements.
It is important for the user and for application the feedback during the registration and updating of the password.

That way I suggest creating a strong password component, I do not have recommendations regarding design, just functionality that is coupled to the antd form or antd input and that defines a minimum level of force for the form to be considered valid.

## What does the proposed API look like?

I suggest pass by Input this four levels to strength:
- weak -  Lowercase letters, for example: a, u, r
- normal - Numbers, for example: 2, 6, 7
- strong - Capital letters, for example: A, U, R
- great - Symbols and special characters, for example:  ! @ & *

If the user passes only one level a string the component should require the levels before the last level.
Example: 
Input string: 'normal', the password should contain the 'normal' requirements and the 'weak' requirements.

If it passes an array, you should only consider past levels.
Example:
Array: ['weak', 'normal', 'great'] the password must contain lowercase letters, numbers and special characters.

Code example: 
> @ Input() nzPasswordLevel: string[] | 'weak' | 'normal' | 'strong' | 'great';

I also suggest passing a boolean parameter if the form should be valid regardless of the force strength of the password, leaving it as default false

Code example:
> @ Input() nzIgnoreStrength = false;

Reference password strength: https://support.google.com/accounts/answer/32040

**Comment by HsuanXyz** [comment]
Hello @GabrielRodriguesS 

Ant Design does not provide this feat, you can submit a issues to [ant-design/ant-design](https://github.com/ant-design/ant-design), it will be sync if ant-design provide this feat.

**Comment by GabrielRodriguesS** [comment]
I will make this component in my project...and I will submit issue with more core example.
