### ISSUE TITLE
nzCustomContent support for nz-select too

### ISSUE THREAD

**Issue by thinkdj** [NG-ZORRO/ng-zorro-antd#2946]
## What problem does this feature solve?
It's great that we can customize the content of nz-option. However, that same custom-content functionality is missing for the selected item in nz-select
## What does the proposed API look like?
> < nz-select nzCustomContent="selectedValueTemplate" >
> .... [options]
> < /nz-select >

**Comment by ddvkid** [comment]
It looks a very reasonable one, our team is struggling with the same requirement atm, happy to make a pr for it.

**Comment by caoyuanqi** [comment]
Yes, this feature is very useful.

**Comment by vthinkxie** [comment]
Hi @ddvkid 
Just feel free to submit pr :)
thanks for your contribution!

**Comment by ishowman** [comment]
@thinkdj thanks.This is a useful feature

**Comment by ishowman** [comment]
@vthinkxie will it release in next version?

**Comment by thinkdj** [comment]
This was done by ~March 11 by ddvkid. When can we expect a merge ?
