### ISSUE TITLE
nz-tabset 设置 positon left，设置高度，tabs 没有显示 prev,next

### ISSUE THREAD

**Issue by kunl** [NG-ZORRO/ng-zorro-antd#2947]
## Version
7.0.0-rc.3
## Environment
chrome 74.0.3712.0（正式版本）canary （64 位）;firefox 66.0b8 (64 位)
## Reproduction link
[https://stackblitz.com/edit/angular-l4dbpf?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-l4dbpf?file=src/app/app.component.ts)
## Steps to reproduce
如 stackblitz 代码，设置 竖向 tab 和高度后，没有显示 ‘上一个，下一个’ 切换按钮;
## What is expected?
老版本的就可以,老版本还有一个问题，默认的 next 是hover的时候是 disable 状态，但是是可以点击的
https://stackblitz.com/edit/ng-zorro-antd-setup-extjzg
## What is actually happening?
没有显示 ‘上一个，下一个’ 切换按钮;

**Comment by vthinkxie** [comment]
fixed in https://github.com/NG-ZORRO/ng-zorro-antd/commit/b79753f9192b43b99f91bcffa3fa7ea2b4ac1deb
