### ISSUE TITLE
1.8.x版本无法兼容IE9，是否可以做兼容性处理

### ISSUE THREAD

**Issue by wayne950921** [NG-ZORRO/ng-zorro-antd#2954]
## Version
1.8.1
## Environment
IE9
## Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)
## Steps to reproduce
1.用IE浏览器打开https://ng.ant.design
2.选择版本1.8.x
3.设置IE浏览器版本为9
## What is expected?
页面可以正常访问
## What is actually happening?
页面无法正常访问

**Comment by wendzhue** [comment]
![image](https://user-images.githubusercontent.com/12122021/53227511-58e89d00-36b9-11e9-864e-565baa0bdb60.png)

**Comment by wayne950921** [comment]
Why IE10 can be accessed normally？

**Comment by wayne950921** [comment]
@wendzhue

**Comment by wendzhue** [comment]
@wayne950921 You can try it. We do not ensure that.

**Comment by wayne950921** [comment]
@wendzhue I tried it, IE10 is OK.
