### ISSUE TITLE
Native scroll is ugly 

### ISSUE THREAD

**Issue by popingblink** [NG-ZORRO/ng-zorro-antd#296]
native scroll  is not suitable for me ,maybe we can change it such as [perfect-scrollbar ](https://github.com/noraesae/perfect-scrollbar)

**Comment by vthinkxie** [comment]
@popingblink thanks for your advice, the package will not be included in the ng-zorro-antd dependency, you can implement it in your own project.

**Comment by LinBoLen** [comment]
maybe [SlimScroll](https://github.com/jkuri/ngx-slimscroll) can help you.
