### ISSUE TITLE
下拉框响应式表单无法获取到nzlabel的值

### ISSUE THREAD

**Issue by runningxiao** [NG-ZORRO/ng-zorro-antd#2962]
## What problem does this feature solve?
例如修改，我增加完成后不需要请求后台刷新列表，直接将值加入到列表中，但是我无法获取到nzlabel，那么我表格的显示的值将会是id。
## What does the proposed API look like?
validateform.get('xx').label

**Comment by vthinkxie** [comment]
nzValue可以是任何值，包括object，请仔细看文档
