### ISSUE TITLE
nz-tooltip cannot work with nz-options in the nz-select 

### ISSUE THREAD

**Issue by Fanoid** [NG-ZORRO/ng-zorro-antd#2966]
## Version
7.0.0-rc.3
## Environment
MacOS
## Reproduction link
[https://stackblitz.com/edit/angular-sznujt](https://stackblitz.com/edit/angular-sznujt)
## Steps to reproduce
1. Use the nz-select component, and set the labels of nz-options to a very long string.
2. Add nz-tooltip to every nz-option.
## What is expected?
Tooltips work when hovering mouse on the options.
## What is actually happening?
No tooltips.

**Comment by vthinkxie** [comment]
@Fanoid  `nzCustomContent`
https://stackblitz.com/edit/angular-sznujt-upxc4v?file=src/app/app.component.ts
