### ISSUE TITLE
‘addOnAfter’ affects typography.How can i avoid this error?

### ISSUE THREAD

**Issue by zy-1995** [NG-ZORRO/ng-zorro-antd#298]
![1505387964203](https://user-images.githubusercontent.com/27221548/30462249-15e0802c-998a-11e7-9d34-80a564bce0d5.jpg)
<img width="754" alt="wx20170914" src="https://user-images.githubusercontent.com/27221548/30462252-1c44b172-998a-11e7-9571-5c4122797467.png">

**Comment by vthinkxie** [comment]
add wrapper with nz-col and nz-row
