### ISSUE TITLE
nz-sider trigger disappeared after build.

### ISSUE THREAD

**Issue by Sioxas** [NG-ZORRO/ng-zorro-antd#2980]
## Version
7.0.0-rc.3
## Environment
OS:macOS 10.14.3  node:v10.9.0  npm:6.2.0  browser:Chrome 72.0.3626.109
## Reproduction link
[https://github.com/Sioxas/antd-ui-bug](https://github.com/Sioxas/antd-ui-bug)
## Steps to reproduce
# `nz-sider` trigger disappeared after build
Bug to reproduce
```
git clone https://github.com/Sioxas/antd-ui-bug
cd antd-ui-bug
npm install
ng serve
```
The trigger shows as normal.
![image](https://user-images.githubusercontent.com/9740581/53484193-33470380-3abe-11e9-9391-c2057b1dcb35.png)
In the production mode the trigger disappeared.
```
ng build --prod
```
or
```
ng serve --prod
```
![image](https://user-images.githubusercontent.com/9740581/53484390-b5372c80-3abe-11e9-8874-d9f51cbf8a4b.png)

## What is expected?
Trigger shows after build.
## What is actually happening?
Trigger disappeared after build.

**Comment by vthinkxie** [comment]
this is resolved in the latest version, closed
