### ISSUE TITLE
row: 响应式nzGutter属性文档宽度配置值丢失

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#2990]
## 重现

https://angular-fgnjbk.stackblitz.io/ （[Editor Mode](https://stackblitz.com/edit/angular-fgnjbk?file=src/app/app.component.ts))

`nzGutter` 值为响应式时，例如：

```html
<div nz-row [nzGutter]="{ md: 8, lg: 24, xl: 48 }">
```

当窗体大小满足 `≥1200px`（即 `xxl`） 以上配置会导致 `nzGutter` 为空；依响应式规则应该是使用 `xl` 的值，即上述示例在窗体大小满足 `≥1200px` 以上时 `nzGutter` 应为 `48`。

反之，当窗体大小 `<768px`（即 `sm`、`xs`）的情况下依响应式规则 `nzGutter` 应为 `8`。

**Comment by vthinkxie** [comment]
https://codesandbox.io/s/vmpw2k4k4l
与 ant design 设计规范保持一致，可以到 antd 提issue
