### ISSUE TITLE
1.8.1版本下，很多图标都不能正常显示

### ISSUE THREAD

**Issue by StarkL** [NG-ZORRO/ng-zorro-antd#2991]
## Version
1.8.1
## Environment
angular 6.x
## Reproduction link
[https://stackblitz.com/edit/angular-nua94d](https://stackblitz.com/edit/angular-nua94d)
## Steps to reproduce
1.正确引入zorro <br>
2.运用 <i nz-icon type="bar-chart" theme="outline"></i> 标签 <br>
3.不显示对应的图标
## What is expected?
能正常展示图标
## What is actually happening?
console里报错： <br>
[@ant-design/icons-angular]: the icon bar-chart-o does not exist in your assets folder. <br>
[@ant-design/icons-angular]: the icon bar-chart-o does not exist or is not registered.

**Comment by wendzhue** [comment]
仔细阅读文档. https://ng.ant.design/components/icon/zh.

遇到这样格式化的报错显然是用法不对.
