### ISSUE TITLE
Ng Table Cannot read property length of undefined v7.0

### ISSUE THREAD

**Issue by venuduggireddy** [NG-ZORRO/ng-zorro-antd#2999]
This issue started to happen after I updated ng-zorro-antd "7.0.0-rc.3" to "7.0.0",

![ng-table](https://user-images.githubusercontent.com/243075/53602217-14a74200-3b7c-11e9-8a2c-59ef58a1f26f.PNG)

**Comment by vthinkxie** [comment]
nzData has to be array type

**Comment by venuduggireddy** [comment]
nzData is an array type. Here is the link to reproduce

https://stackblitz.com/edit/ng-zorro-antd-start-wchpdf

**Comment by vthinkxie** [comment]
@venuduggireddy plz note that your `recentProjects` init value is undefined.
