### ISSUE TITLE
后面会不会增加侧边栏弹层的组件?

### ISSUE THREAD

**Issue by yb19890724** [NG-ZORRO/ng-zorro-antd#30]
左右滑动的方式

**Comment by giscafer** [comment]
using the angular animation is easy to implement，need components?

**Comment by LinBoLen** [comment]
use animation +1

**Comment by vthinkxie** [comment]
@yb19890724 

You can build your animation component follow this https://angular.cn/guide/animations.

Components in ng-zorro-antd will synchronize with the [react antd](https://ant.design/docs/react/introduce-cn) on a regular basis, component which is not designed by antd will not be supported in ng-zorro-antd.
Thanks.

**Comment by yb19890724** [comment]
@giscafer thx

**Comment by yb19890724** [comment]
@vthinkxie

**Comment by yb19890724** [comment]
@vthinkxie thx
