### ISSUE TITLE
InvalidPipeArgument: 'Missing locale data for the locale "ar".' for pipe 'DatePipe'

### ISSUE THREAD

**Issue by HDaghash** [NG-ZORRO/ng-zorro-antd#3010]
### Reproduction link
https://stackblitz.com/edit/ng-zorro-antd-start-yrjyey?file=src%2Fapp%2Fapp.component.html
### Steps to reproduce
1-Set local provider for arabic
2-add date picker component
3-try to select date

### What is expected?
date picker popup should show up

### What is actually happening?
console error message showing : InvalidPipeArgument: 'Missing locale data for the locale "ar".' for pipe 'DatePipe'

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.0-rc.3 |
| Browser | chrome latest |

**Comment by wenqi73** [comment]
NG-ZORRO date format is based on angular i18n by default, you should register `ar`:
```ts
import ar from '@angular/common/locales/ar';
registerLocaleData(ar);
```
