### ISSUE TITLE
NzColDirective 在 Prod 下无法通过 @ContentChildren 在父组件获得

### ISSUE THREAD

**Issue by wxpxzdj** [NG-ZORRO/ng-zorro-antd#3011]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-fez9i7](https://stackblitz.com/edit/ng-zorro-antd-start-fez9i7)

### Steps to reproduce
在 Dev 模式下能正常获取，通过 ng build --prod 构建后无法获取
![avatar](http://www.zeroerror.io/upload/20190302/png/1551497626-257140.png)

### What is expected?
获取到 NzColDirective List 并根据需求统一动态设置 nzXs、nzMd 等属性

### What is actually happening?
在 Prod 下无法正常获取

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.0 |
| Browser | Chrome 72.0.3626.119 |

---
由于有些表单是可以统一格式的，如果可以在父组件中获取每一个 nz-col，就不需要在模板里面把 nzXs、nzMd 等属性都设置一遍，而且也方便通过代码/后端配置控制。

**Comment by vthinkxie** [comment]
duplicated #2696
