### ISSUE TITLE
nz-select not clear after we clear form reset

### ISSUE THREAD

**Issue by lkhuoch** [NG-ZORRO/ng-zorro-antd#3014]
### Reproduction link
[https://stackblitz.com/edit/nz700?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/nz700?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
1. select "Item 1" from list
2. let check the "Result", it shows "1"
3. click "Reset" button
4. select same previous one "Item 1" again from list
5. let check the "Result", it show nothing
6. But if we choose other beside "Item 1", the "Result" shows correctly

### What is expected?
I expect like the previous version (7.0.0-RC3), it works fine

### What is actually happening?
It comes from latest version 7.0.0

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.0 |
| Browser | Latest Chrome |

**Comment by lkhuoch** [comment]
Hello admin,
Did you fix it already?
Thanks

**Comment by vthinkxie** [comment]
@lkhuoch will be fixed in 7.0.1, the code has been submitted.
