### ISSUE TITLE
`nzWidth` invalid in `nz-th`

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#302]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

the html:

```html
<th nz-th [nzWidth]="45"></th>
```

screenshot:

![tim 20170915171445](https://user-images.githubusercontent.com/2987467/30475427-67367bca-9a39-11e7-82b6-a623eaf8e9ef.png)

**Comment by vthinkxie** [comment]
please read the doc again. 45px not 45

**Comment by cipchk** [comment]
all the same, when `45px`

the html:

```html
<th nz-th [nzWidth]="'45px'"></th>
```

screenshot:

![2](https://user-images.githubusercontent.com/2987467/30477643-76daa478-9a40-11e7-9f3e-ea4eaddba97d.png)

**Comment by cipchk** [comment]
the [source](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/table/nz-th.directive.ts#L14) no process in any binding action!

**Comment by vthinkxie** [comment]
@cipchk https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/table/nz-table.component.ts#L48

**Comment by cipchk** [comment]
I found the reason!!

the html:

```html
<th nz-th><span>标题</span></th>
<th nz-th *ngIf="s.need_sku"><span>SKU编号</span></th>
<th nz-th><span>状态</span></th>
<th nz-th [nzWidth]="'120px'"><span>修改时间</span></th>
<th nz-th [nzWidth]="'60px'"></th>
```

but, what generate wrong position `style` when `need_sku=true`, that influenced by the `ngIf`.

![111](https://user-images.githubusercontent.com/2987467/30479025-ec579558-9a45-11e7-9059-728f2056a5f4.png)
