### ISSUE TITLE
Clear item after selected, In Version 7.0.0-RC3, it works fine

### ISSUE THREAD

**Issue by lkhuoch** [NG-ZORRO/ng-zorro-antd#3021]
### Reproduction link
[https://stackblitz.com/edit/nz700?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/nz700?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Note: I want clear the select option after selected item, in version 7.0.0-RC3 it worked fine
1. select item from selected list, it does not clear after select it
2. If we click on "Reset Product", it clears perfectly
3. I use the same code with "Reset Product" to clear specific form, but it does not work
4. In Version 7.0.0-RC3, I used this code to clear it after selected "this.form.setControl('product', new FormControl());"
5. Please, help me! I put code in app.component.ts

### What is expected?
I want it works like previous version.

### What is actually happening?
It does not clear after selected from select list with same code in previous version 7.0.0-RC3 and version 7.0.0

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.0 |
| Browser | Latest Chrome |

**Comment by vthinkxie** [comment]
fixed in 7.0.1, plz don't submit duplicated issue #3014, thanks.

**Comment by vthinkxie** [comment]
Hi @lkhuoch , are you sure that the codes work fine in 7.0.0-rc.3?
https://stackblitz.com/edit/nz700-xn38t6?file=src%2Fapp%2Fapp.component.ts
here is the reprolink of 7.0.0-rc.3

**Comment by lkhuoch** [comment]
Yes, it works in version 7.0.0-RC3.
I used it everyday with version 7.0.0-RC3.
When I update to version 7.0.0, it has problem with clearing the nz-select
when select same item after cleaning. You just solve it in version 7.0.1.

I can confirm that it is worked it in version 7.0.0-RC3.

Thanks,

**Comment by lkhuoch** [comment]
Is it fixed yet?

Thanks,

**Comment by vthinkxie** [comment]
hi @lkhuoch 
I checked from 0.7.1 version to 7.0.0-rc.3 version, all versions before can not work
```ts
this.form.setControl('product', new FormControl())
```
plz check the link above

**Comment by lkhuoch** [comment]
Ok, tomorrow I send the link to you via this email directly.

Thank for your time.

**Comment by lkhuoch** [comment]
Good morning,
I created link for you to test it.

https://stackblitz.com/edit/nz700-rc3?file=src%2Fapp%2Fapp.component.ts

The product is reset automatically after i selected product from product
list, please check.
Thank for your support

**Comment by vthinkxie** [comment]
@lkhuoch 
plz check it again, reset form with the code below
```typescript
this.form.setControl('product', new FormControl());
```
would not work in 7.0.0-rc.3 in your repro link

**Comment by lkhuoch** [comment]
Hello,
I mean it does not reset whole "this.form", but it is reset only "product"
select list in the form.
when you select "product 1" from the "product" select list still show
"select product" and I get the result value "Product: 1".
Please, check again.

Thank you

**Comment by vthinkxie** [comment]
yes, `this.form.setControl('product', new FormControl());`
is and was not worked in any before version.
not only in latest version.

**Comment by lkhuoch** [comment]
Now, let compare with these two version of 7.0.0-RC3 and 7.0.0.
Version 7.0.0-RC3:
https://stackblitz.com/edit/nz700-rc3

Version 7.0.0:
https://stackblitz.com/edit/nz700

In version 7.0.0-RC3, it is clear or reset "product" select list to "Select
Product" placeholder.
In version 7.0.0, it is NOT clear or reset "product" select list, if you
select "product 1", it shows "product 1" in select list.

Please, check again

**Comment by vthinkxie** [comment]
![kapture 2019-03-05 at 11 44 40](https://user-images.githubusercontent.com/1506722/53779694-1b4b0600-3f3c-11e9-98fa-388b179b76f1.gif)

Version 7.0.0-RC3:
https://stackblitz.com/edit/nz700-rc3

can not work as what you say.

**Comment by lkhuoch** [comment]
I am so sorry to confuse you.

Verison 7.0.0-RC3:
https://stackblitz.com/edit/nz700-rc3?file=src%2Fapp%2Fapp.component.html

Version 7.0.0:
https://stackblitz.com/edit/nz700?file=src%2Fapp%2Fapp.component.ts

Please take a look at "Product" select list after you select any product
from the list.
Version 7.0.0-RC3, it is clear or reset automatically.
Version 7.0.0, it is NOT clear or reset, it still shows the selected
product.
All codes are the same.

Please, check again.
I am so sorry to confuse you.

**Comment by lkhuoch** [comment]
Ok, thank for your help.

**Comment by vthinkxie** [comment]
Hi @lkhuoch 
the clicked option has the highest priority in the latest version, so when you click an option, it is impossible to reset it to null again in the same detect change.
but you can do a little trick to hack this with `Promise.resolve().then()`
here is the demo, I hope this could help you.
https://stackblitz.com/edit/nz700-2vokoh?file=src/app/app.component.ts
