### ISSUE TITLE
新建Module中的component中nz-submenu使用ng-if后，在<span title>中使用变量，控制台报错

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#3023]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-egtnt1](https://stackblitz.com/edit/ng-zorro-antd-start-egtnt1)

### Steps to reproduce
打开控制台（console）查看报错信息。Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'width: 14'. Current value: 'width: 56'.

### What is expected?
解决：ExpressionChangedAfterItHasBeenCheckedError

### What is actually happening?
报错：ExpressionChangedAfterItHasBeenCheckedError

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.1 |
| Browser | Google Chrome 已是最新版本 版本 74.0.3717.0（正式版本）dev （64 位） |

---
页面加载正常，控制台有报错信息。备注：Current value: 'width: 56'. 是变量文字都宽度

**Comment by tony-yyj** [comment]
same question.
