### ISSUE TITLE
nz-tree backward compatibility

### ISSUE THREAD

**Issue by wenqi73** [NG-ZORRO/ng-zorro-antd#3025]
### Reproduction link
[https://stackblitz.com/edit/nz-tree-7](https://stackblitz.com/edit/nz-tree-7)

### Steps to reproduce
run demo

### What is expected?
treeService is defined

### What is actually happening?
treeService is undefined

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.1 |
| Browser | chrome |

### Other 
When I use old API to create tree, then change `isSelected` which is NzTreeNode's property, it will throw an error.

---

用之前的老方法来创建 tree，再改变某个 NzTreeNode 的 `isSelected` 属性，treeService 提示 `undefined`，请问这个会做兼容处理吗？

**Comment by simplejason** [comment]
考虑在ngAfterViewInit 里执行操作（ViewChild会在此时可获取）[例子](https://stackblitz.com/edit/nz-tree-7-ws92uk?file=src/app/app.component.ts)
