### ISSUE TITLE
选中的nz-option异步修改nzLabel后nz-select的显示不自动更新

### ISSUE THREAD

**Issue by wunaidage** [NG-ZORRO/ng-zorro-antd#3029]
### Reproduction link
[https://ng-zorro-antd-start-ghdqtr.stackblitz.io](https://ng-zorro-antd-start-ghdqtr.stackblitz.io)

### Steps to reproduce
点击选择器，选中一项

### What is expected?
异步操作后选择器显示为新的label值

### What is actually happening?
异步操作后选择器显示仍为旧值，需要点击选择器后才会更新

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.1 |
| Browser | chrome |

---
不知道这是个bug还是个feature

**Comment by wunaidage** [comment]
I think the translated title should be
# nz-select displaying does not get updated after selected nz-option's nzLabel is asynchronously modified

**Comment by EeeEui** [comment]
第一次修改nzLabel更新了，但是第二次修改nzLabel不会更新。

Environment | version
-- | --
ng-zorro-antd | ^8.5.0
Browser
