### ISSUE TITLE
trigger onSearchChange after resetting the search value

### ISSUE THREAD

**Issue by Akiq2016** [NG-ZORRO/ng-zorro-antd#304]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

```javascript
private aSub$: Subject<string>
```
```html
<nz-select
  nzAllowClear
  formControlName="fieldA"
  [nzShowSearch]="true"
  (nzSearchChange)="aSub$.next($event)">
  <nz-option
    *ngFor="let item of list"
    [nzLabel]="item.name"
    [nzValue]="item.val">
  </nz-option>
</nz-select>
```
What my Subject do is to retrieve data from server to update my `list`.

So after I input some words, get a new `list`, and select a new option. Yeah I love this.
Once again, now the `list` do not reset to the pure one, because even though the search value is reset, you don't emit this reset value to me, so I also do not make a request too.

## Expected behavior

Like the behavior of searching from local data, the select component will reset list after selecting too. So I think you should also trigger `onSearchChange` after `clearSearchText ` in this scene. Or is there any other approaches to doing this?

**Comment by cp1001** [comment]
maybe [(ngModel)]  and (ngModelChange) will help you.try it

**Comment by vthinkxie** [comment]
Hi @Akiq2016 , I have checked the demo and source code, nzSearchChange will be emit after search value change, ref code https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/select/nz-select.component.ts#L101

**Comment by Akiq2016** [comment]
@vthinkxie yeah, I know `nzSearchChange will be emit after search value change`, but what I say is about If I input a key word then fire blur event, or I input a key word then select an option, these two scenes, the select component will clear the search text, but do not emit this to me.

**Comment by vthinkxie** [comment]
@Akiq2016 you can listen to  (blur) and (ngModelChange) event instead.

**Comment by Akiq2016** [comment]
@vthinkxie Well, it's not a good idea for me to add (blur) on `nz-select` as this is not a standard form element or link, so I have to add `tabindex=0` on it, but it is more complex cause `nz-select` still need to compile and the tab-able order is not that controllable, only if I `tab` to the next element can I fire the previous element's blur event. And, at least I can not just add `tabindex=0` on `nz-select` to solve my `blur` problem, cause it actually fired a focus event for me in my `blur` callback, hah. So the current situation for me is to add `tabindex=0` and listen `focus`.
Whatever, thanks a bunch.

**Comment by vthinkxie** [comment]
@Akiq2016 thanks for your feedback, we will take it into consideration later.
