### ISSUE TITLE
常见问题页面中-打包出来的文件太大这个问题有一处错误

### ISSUE THREAD

**Issue by W-Abel-jia** [NG-ZORRO/ng-zorro-antd#3043]
### Reproduction link
[https://ng-zorro-antd-start-n9xssx.stackblitz.io/](https://ng-zorro-antd-start-n9xssx.stackblitz.io/)

### Steps to reproduce
打开ng-zorro-antd文档页面，点击左侧“常见问题”，然后看到右侧的“打包出来的文件太大”问题中，关于命令：“ng build --prod --sourcemaps” 写法错误，正确的是：“ng build --prod --sourcemap”，多了一个s。

### What is expected?
ng build --prod --sourcemap

### What is actually happening?
ng build --prod --sourcemaps

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.1 |
| Browser | Chrome72.0.3626.119 |

**Comment by wendzhue** [comment]
@W-Abel-jia 似乎是 `ng build --source-map`?

**Comment by W-Abel-jia** [comment]
您好，这里是 ng build --prod --source-map，在页面上标注为ng build --prod --source-maps。谢谢
