### ISSUE TITLE
Pagination 向后5页向前5页页码不跟随变化

### ISSUE THREAD

**Issue by liurw1025** [NG-ZORRO/ng-zorro-antd#3049]
### Reproduction link
[https://stackblitz.com/run?embed=1&file=src/app/app.component.ts](https://stackblitz.com/run?embed=1&file=src/app/app.component.ts)

### Steps to reproduce
点击向后5页

### What is expected?
2,3,4,5应该变成下一页的数字

### What is actually happening?
2,3,4,5没有变化

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.1 |
| Browser | Google Chrome版本 71.0.3578.98 |

**Comment by HsuanXyz** [comment]
@liurw1025 请提供正确的复现连接
