### ISSUE TITLE
7.0.0 upgrade to 7.0.1 is unsuccessful

### ISSUE THREAD

**Issue by HelloValue** [NG-ZORRO/ng-zorro-antd#3057]
### Steps to reproduce
I use the following command to upgrade.
ng update
 Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       7.3.4 -> 7.3.5           ng update @angular/cli
      @angular/core                      7.2.7 -> 7.2.8           ng update @angular/core
      ng-zorro-antd                      7.0.0 -> 7.0.1           ng update ng-zorro-antd
ng update ng-zorro-antd
Package "ng-zorro-antd" has a missing peer dependency of "@angular/cdk" @ "^7.3.0".
Incompatible peer dependencies found. See above.

### What is expected?
upgrade to 7.0.1

### What is actually happening?
Error:
Package "ng-zorro-antd" has a missing peer dependency of "@angular/cdk" @ "^7.3.0".
Incompatible peer dependencies found. See above.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.1 |
| Browser | Chrome 71.0 |

---
this is my angular version
----------------------------------------------------------
Angular CLI: 7.3.4
Node: 8.11.3
OS: win32 x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.4
@angular/cdk                      7.3.3
@angular/cli                      7.3.4
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.8.3

**Comment by wendzhue** [comment]
Follow the instruction to install cdk@7.3.0 and try again.

**Comment by HelloValue** [comment]
> Follow the instruction to install cdk@7.3.0 and try again.
must be @cdk 7.3.0 ? @cdk 7.3.3 not？

**Comment by wendzhue** [comment]
@HelloValue 7.3.3 is OK. See https://michaelsoolee.com/npm-package-tilde-caret/ .

**Comment by HelloValue** [comment]
> @HelloValue 7.3.3 is OK. See https://michaelsoolee.com/npm-package-tilde-caret/ .

I'm so sorry. I ignored a "^" symbol in the prompt.
So,i use "ng version" command can see my @angular/cdk version is 7.3.3.but i can‘t upgrade.
Where is my problem?
Thanks.

**Comment by HsuanXyz** [comment]
Ref: https://github.com/angular/angular-cli/issues/12261

**Comment by HsuanXyz** [comment]
@HelloValue `7.0.0` upgrade  to `7.0.1` only need do `npm i ng-zorro-antd@latest`.

**Comment by HelloValue** [comment]
> @HelloValue `7.0.0` upgrade to `7.0.1` only need do `npm i ng-zorro-antd@latest`.

thank you. although have some errors. but it's upgrade successful.

**Comment by HelloValue** [comment]
@HsuanXyz  , thank you. `npm i ng-zorro-antd@latest`  it works. 
although have some errors. but it's upgrade successful.
