### ISSUE TITLE
Anchor: invalid in a modal dialog

### ISSUE THREAD

**Issue by Xcorpio** [NG-ZORRO/ng-zorro-antd#307]
## I'm submitting Feature Request

<pre><code>
[ ] Bug report  
[ *] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

``` typescript
// model is the `NzModalService` service
edit(item: BizMod) {
    let dlg = this.modal.open({
      title: `编辑模块 ${item.NameCn}`,
      content: ModEditDlgComponent,
      onOk: () => {
        this.load(1)
      },
      componentParams: {
        item: item
      },
      footer: false,
    })
  }
```
> ModEditDlgComponent
```html
<div nz-row style="height: 375px;overflow:auto;">
  <div nz-col [nzSpan]="5">
    <nz-affix>
      <nz-anchor>
        <nz-link nzHref="#GIT" nzTitle="GIT">
          <nz-link nzHref="#GIT-GROUP" nzTitle="Group"></nz-link>
          <nz-link nzHref="#GIT-PROJECT" nzTitle="Project"></nz-link>
        </nz-link>
      </nz-anchor>
    </nz-affix>
  </div>
  <div nz-col [nzSpan]="19">
   <nz-select id="GIT-GROUP" (ngModelChange)="groupChange($event)" >
     ...
    </nz-select>
     ......
    <nz-select id="GIT-PROJECT" (ngModelChange)="projectChange($event)" 
       ...
    </nz-select>
  </div>
</div>
```

click the `anchor` , the `document body` scrolls
## Expected behavior

I hope it  can scroll in the parent component which has scrollbar

## Environment

<pre><code>
Angular version: 4.3.0

ng-zorro-antd version: ^0.5.0-rc.4

 
For Tooling issues:
- Node version: v8.4.0  
- Platform:  Mac

Others:

</code></pre>

**Comment by vthinkxie** [comment]
@cipchk any idea about this?

**Comment by cipchk** [comment]
@Xcorpio Try specifing a `nzTarget` parameter in `nz-affix` component. please read the doc & showcase code.

**Comment by vthinkxie** [comment]
@Xcorpio 
close this issue now, if any question please submit another issue.
