### ISSUE TITLE
nz-dropdown overlay dackdrop background color is not transparent.

### ISSUE THREAD

**Issue by luke-emmental** [NG-ZORRO/ng-zorro-antd#3075]
I think (nz-dropdown)  is missed in (#2917) issue.

https://stackblitz.com/edit/ng-zorro-antd-start-pwxuhd

**Comment by luke-emmental** [comment]
add stackblitz URL : https://ng-zorro-antd-start.stackblitz.io

**Comment by vthinkxie** [comment]
Hi @luke-emmental 
I think you forgot to fork the link

**Comment by luke-emmental** [comment]
ok fork link: https://stackblitz.com/edit/ng-zorro-antd-start-pwxuhd
