### ISSUE TITLE
Tree component can not  get nodes sync , treeService undefined

### ISSUE THREAD

**Issue by simplejason** [NG-ZORRO/ng-zorro-antd#3076]
### Reproduction link
[https://stackblitz.com/edit/angular-qwlewn?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-qwlewn?file=src/app/app.component.ts)

### Steps to reproduce
above

### What is expected?
getTreeNodes() in ngOnInit

### What is actually happening?
empty

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.2 |
| Browser | chrome |

**Comment by zdong11** [comment]
This issue should not be labelled as Bug.

Based on the life-cycle hooks, the <nz-tree> component is not setup when implement ngOnInit on its  parent component. The correct hook could be used is AfterViewInit (Respond after Angular initializes the component's views and child views / the view that a directive is in.)

Please have a test on above stackblitz link and it works to use AfterViewInit.

**Comment by zdong11** [comment]
https://stackblitz.com/edit/angular-qwlewn-rlqbtu?file=src/app/app.component.ts
