### ISSUE TITLE
nz-tag in nz-dropdown will disapear

### ISSUE THREAD

**Issue by SoaringTiger** [NG-ZORRO/ng-zorro-antd#3077]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-5kmyml?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-5kmyml?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
1、nz-tag in nz-dropdown will show at first time.       第一次打开 dropdown，nz-tag正常显示
2、click nz-dropdown item and close nz-dropdown.   收起 dropdown
3、reopen nz-dropdown, nz-tag will disapear.           再次打开 dropdown, nz-tag消失了

### What is expected?
nz-tag will be keeped   正常显示

### What is actually happening?
nz-tag will disapear   

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.2 |
| Browser | Chrome 72.0.3626.121 |

**Comment by vthinkxie** [comment]
the bug of angular, plz track https://github.com/angular/angular/issues/24041

you can disable tag animation to avoid this bug.
