### ISSUE TITLE
Order of DOM nodes in a button is not respected

### ISSUE THREAD

**Issue by chabb** [NG-ZORRO/ng-zorro-antd#3079]
### Reproduction link
[https://ng-zorro-antd-start-vjhban.stackblitz.io](https://ng-zorro-antd-start-vjhban.stackblitz.io)

### Steps to reproduce
Make a component with an input. Use a button with an icon. Use interpolation in the view to display some text before the icon. It does not work.
It works when theres is no binding/interpolation in the HTML

### What is expected?
The order of the HTML should be respected

### What is actually happening?
The order is not respected. The icon comes before the text

It might because of the  `moveIcon` method in `nz-button-component.ts`. I am taking a look 

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.2 |
| Browser | Chrome latest  |

**Comment by wendzhue** [comment]
@chabb Please check out this demo https://ng.ant.design/components/button/en#components-button-demo-size. Button could be placed after text.
