### ISSUE TITLE
Message module `content` property should support  type `TemplateRef` param

### ISSUE THREAD

**Issue by kekehaoz** [NG-ZORRO/ng-zorro-antd#3081]
## What problem does this feature solve?
we can put navigate link on the message tip with TemplateRef param
## What does the proposed API look like?
content: string | TemplateRef<any>

**Comment by wendzhue** [comment]
@kekehaoz Got it. Would be released in the next version.

**Comment by ishowman** [comment]
@wendzhue could you add the usage of the feature demo in docs?
