### ISSUE TITLE
Select Dropdown list is not attached to dropdown while scrolling the drawer

### ISSUE THREAD

**Issue by jaganpari** [NG-ZORRO/ng-zorro-antd#3092]
### Reproduction link
[https://stackblitz.com/edit/angular-wbm8sd?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-wbm8sd?file=src/app/app.component.ts)

### Steps to reproduce
Click "Create" and Open the "Drawer".
Click on any dropdown
Try to scroll the Drawer

### What is expected?
It should attach to corresponding dropdown.

### What is actually happening?
Select Dropdown list is not attached to dropdown while scrolling the drawer

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | Firefox |

---
But its working properly in Chrome

**Comment by vthinkxie** [comment]
it is a bug from `@angular/cdk`
ref https://github.com/angular/material2/issues/8986

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue if you are encountering a similar or related problem.
