### ISSUE TITLE
弹出菜单显示不完全

### ISSUE THREAD

**Issue by liuren78** [NG-ZORRO/ng-zorro-antd#3094]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-f5fu2x](https://stackblitz.com/edit/ng-zorro-antd-start-f5fu2x)

### Steps to reproduce
左侧菜单收缩以后，鼠标停留在user3上面

### What is expected?
子菜单能完全显示

### What is actually happening?
有部分菜单没有显示出来

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | chrome 72.0.3626.119 |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-rave2m?file=src/app/app.component.html
css overflow的部分需要自行处理
