### ISSUE TITLE
Need to trigger the clear directive manually in nz-select

### ISSUE THREAD

**Issue by sridharan21994** [NG-ZORRO/ng-zorro-antd#3097]
## What problem does this feature solve?
If I want to clear the dropdown to go back to the original null state showing only the placeholder value after selecting any values from the dropdown, It can be done only by clicking 'x' symbol, But I need to do that programatically. Please help me with the same.
## What does the proposed API look like?
By exposing any input property to bind with the nz-select to take the clear as the variable(input)

**Comment by vthinkxie** [comment]
[ngModel] = "null"

**Comment by omirobarcelo** [comment]
@vthinkxie I tried it, both with `null` and `undefined`, and in the `(ngModelChange)` callback and directly in the template.

https://stackblitz.com/edit/angular-zsq6ev

With `null` it doesn't work. With `undefined` it works only the first time.

Am I doing something wrong, or maybe is something that has changed in most recent versions?

**Comment by vthinkxie** [comment]
you should never change the ngModel value at the ngModelChange
it anti the design of angular, has nothing to do with ng-zorro-antd

**Comment by omirobarcelo** [comment]
@vthinkxie Thanks for the clarification. Then how would you clear the select when something is selected? Or is another component more appropriate for this case?

**Comment by vthinkxie** [comment]
nz-select support nzDropdownRender, have a try

**Comment by RaulDr** [comment]
You can try to use `[nzCustomTemplate]="emptyTemplate"` with an empty template:  `<ng-template #emptyTemplate></ng-template>`

**Comment by vv619-perf** [comment]
First time the value gets cleared when we set the ngModel to null but the second time it's not getting cleared, is there any events we can trigger to clear.

**Comment by winexist** [comment]
> First time the value gets cleared when we set the ngModel to null but the second time it's not getting cleared, is there any events we can trigger to clear.

having the same issue.

**Comment by Greegko** [comment]
I solved it by 

```
// HTML
<nz-select ... [(ngModelChange)]="onNewValue($event)"></nz-select>

// Component
@ViewChild(NzSelectComponent, { static: true }) selectNode: NzSelectComponent;

onNewValue() {
  this.selectNode.writeValue(undefined);
   ...
}
```

https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/select/select.component.ts#L521

Playing around a bit, and it seems the culprit around listOfValue and change detection.
