### ISSUE TITLE
nz-collapse doesn't open panel at Safari

### ISSUE THREAD

**Issue by dk-seo** [NG-ZORRO/ng-zorro-antd#3098]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-roeg51](https://stackblitz.com/edit/ng-zorro-antd-start-roeg51)

### Steps to reproduce
Open inactive [nz-collapse-panel](https://github.com/angular/angular-cli) on Safari browser.

### What is expected?
nz-collapse-panel is expected to open its contents when it turns out active.

### What is actually happening?
An arrow icon on nz-collapse-panel keeps rotating whenever it is clicked but the contents never showed up  once after they hided

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | Safari Version 12.0.3 (14606.4.5) |

---
Chrome works well as expected.
Every example in Collapse (https://ng.ant.design/components/collapse/en) has same problem on Safari.

**Comment by littleinsz** [comment]
Collapse also doesn't open panel at IE11

**Comment by wendzhue** [comment]
`display: none` style is not removed on IE11. @vthinkxie

**Comment by Credo-Zhao** [comment]
> `display: none` style is not removed on IE11. @vthinkxie
> 
> Don't have Safari at hand. Maybe the same reason.
> 
> ![iexplore_stsa0XG8Cq](https://user-images.githubusercontent.com/12122021/54578167-a5fe2b80-4a39-11e9-8d17-33bc7bab29f4.png)

刚看了下,确实是这样的.

**Comment by wendzhue** [comment]
Angular to blame (maybe?) https://github.com/angular/angular/issues/29371

**Comment by vthinkxie** [comment]
this would help
https://github.com/NG-ZORRO/ng-zorro-antd/pull/3216#issuecomment-483057694
