### ISSUE TITLE
[nzAutoGenerate] not work when use lazy load

### ISSUE THREAD

**Issue by Sokiy** [NG-ZORRO/ng-zorro-antd#3104]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io/home/list](https://ng-zorro-antd-start.stackblitz.io/home/list)

### Steps to reproduce
模块使用  **lazy loading**去加载,
然后 **<nz-breadcrumb [nzAutoGenerate]="true"></nz-breadcrumb>** 不会生效, 
我在路由里面都有配置 **breadcrumb** 的值

### What is expected?
期望 **nz-breadcrumb** 的自动渲染生成面包屑在 **lazy loading** 模式下可以生效

### What is actually happening?
没有渲染出来

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | Chrome  72.0.3626.121（正式版本） （64 位） |

**Comment by wendzhue** [comment]
Duplicate of #2538.

**Comment by smilemuffie** [comment]
Was this fixed? I can not auto generate breadcrumb in lazy loading,  with ng-zorro@7.3.3

**Comment by wenqi73** [comment]
@smilemuffie plz update ng-zorro version.
