### ISSUE TITLE
tabset在modal里的,无法显示左右移动的按钮

### ISSUE THREAD

**Issue by shetz163** [NG-ZORRO/ng-zorro-antd#3105]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-yr89dn](https://stackblitz.com/edit/ng-zorro-antd-start-yr89dn)

### Steps to reproduce
点击modal按钮,弹出的modal里的tab有十几个,但左右移动的按钮没有显示.

### What is expected?
在modal里能正常显示tab.

### What is actually happening?
左右移动的按钮没有正常显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | chrome  73.0.3683.75 |

**Comment by vthinkxie** [comment]
fixed in the latest version, closed now

**Comment by xujuan7090** [comment]
I am using the latest version and the problem persists
