### ISSUE TITLE
treeselect控件选中所有子节点后如何让模型中继续使用子节点的key

### ISSUE THREAD

**Issue by xiaohuilam** [NG-ZORRO/ng-zorro-antd#3106]
### Reproduction link
![image.png](https://user-images.githubusercontent.com/6964962/54425889-6f7e9300-4751-11e9-9982-cc9c74a0f1fd.png)

### Steps to reproduce
- 打开https://ng.ant.design/components/tree-select/zh
- 依次选中 node2 下的child node2/child node3/ child node4
- 可以看到控制台输出为
```bash
>[]
>["0-1-0"]
>["0-1-0", "0-1-1"]
>["0-1"]
```

### What is expected?
得到
>["0-1-0", "0-1-1", "0-1-2"]

### What is actually happening?
> ["0-1"]

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | chrome |

**Comment by werts** [comment]
这个设计还有点蛋疼，应该提供选项的，内部都保存了值，就是不提供出来

**Comment by simplejason** [comment]
> 内部

nzCheckStrictly，暂时使用这个属性可以取消自动关联

**Comment by werts** [comment]
1.8.X好像没有这个属性，看来不升级做起来就麻烦了

**Comment by W1821** [comment]
我为了达到这种效果，把父级设置成禁选 [disableCheckbox]=true

**Comment by werts** [comment]
@W1821 子节点要选很多就麻烦了，我已经弃用treeselect了，用tree了，手动取数据
