### ISSUE TITLE
请问何时能够提供combotree 、tree、fileupload

### ISSUE THREAD

**Issue by DBcooper28** [NG-ZORRO/ng-zorro-antd#311]
谢谢各位大佬反馈一下 我公司目前重构系统正在使用zorro，感觉体验非常不错，只是和react版本相比差了些许功能

**Comment by Itherma** [comment]
是啊 我们公司重构也用的Zorro , 非常好用 ,唯一的遗憾是少了 tree和upload 这些常用的控件

**Comment by SoaringTiger** [comment]
挺好用的，支持增加tree类型的控件

**Comment by thegatheringstorm** [comment]
@Itherma Upload 正在紧张有序的编写中 :smile:

**Comment by tigercosmos** [comment]
Nice to see this to be more and more complete.

**Comment by vthinkxie** [comment]
Hi all, please give us more patient.

**Comment by cipchk** [comment]
关于 `tree` & `fileupload` 在官方未提供之前可以考虑参考 [ng-alain](https://cipchk.github.io/ng-alain/)。

## 依赖

+ [ng-tree-antd](https://github.com/cipchk/ng-tree-antd), [demo](https://cipchk.github.io/ng-alain/#/elements/tree-antd)
+ [File Upload Demo](https://cipchk.github.io/ng-alain/#/forms/upload)

**Comment by vthinkxie** [comment]
duplicated #132 closed

**Comment by wuhao930406** [comment]
+1

**Comment by panzhu** [comment]
同问 fileupload 什么时候能提供？或有无这个计划？
