### ISSUE TITLE
table-拖曳排序无法实现

### ISSUE THREAD

**Issue by Rolling-ball** [NG-ZORRO/ng-zorro-antd#3113]
### Reproduction link
[https://7p12ka.run.stackblitz.io](https://7p12ka.run.stackblitz.io)

### Steps to reproduce
选中表格中某一项进行拖曳

### What is expected?
实现拖曳排序

### What is actually happening?
表格中项无法拖动

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | Google Chrome |

**Comment by Rolling-ball** [comment]
> Hello @Rolling-ball. Please provide a online reproduction by forking this link https://stackblitz.com/edit/ng-zorro-antd-start or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @Rolling-ball, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://stackblitz.com/edit/ng-zorro-antd-start) 创建一个 stackblitz 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

url: https://4aeshh.run.stackblitz.io
是ngzorro里拖曳排序的模板源码，运行时无法实现拖曳功能

**Comment by vthinkxie** [comment]
https://material.angular.io/cdk/drag-drop/overview
仔细看下用法
