### ISSUE TITLE
无法在表单中使用走马灯

### ISSUE THREAD

**Issue by ismezy** [NG-ZORRO/ng-zorro-antd#3118]
### Reproduction link
[https://stackblitz.com/edit/angular-3nx4h2](https://stackblitz.com/edit/angular-3nx4h2)

### Steps to reproduce
在表单中添加走马灯样式不正确，并且点击切换小圆点会提交表单。

### What is expected?
能在表单中正常使用，并且点击切换小圆点不会提交表单。

### What is actually happening?
无法在表单中正常显示组件，点击小圆点会提交表单。

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | chrome |

**Comment by wendzhue** [comment]
@ismezy 

dot 的实现里面有个 button, 没有指定 button 的 type 的时候就是 submit.

渲染异常是 form 没有指定的宽度.

为什么要这样使用呢?

**Comment by ismezy** [comment]
用于自定义拍照表单控件，显示预览图片。

**Comment by wendzhue** [comment]
@ismezy 你可以通过一个父元素包裹跑马灯来解决宽度的问题, 用自定义 dot 渲染解决点击的问题. 

或许根本就不应该把跑马灯嵌套在 form 中, 毕竟没有对应的 model.
