### ISSUE TITLE
nz-icon cannot work correctly with nzSpin if embedded in svg

### ISSUE THREAD

**Issue by Fanoid** [NG-ZORRO/ng-zorro-antd#3120]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-wq8fxg](https://stackblitz.com/edit/ng-zorro-antd-start-wq8fxg)

### Steps to reproduce
1. Embed xhtml:div in svg using foreignObject;
2. Use nz-icon with nzSpin in the xhtml:div;
3. Add transform="translate(xx,xx)" in the g which wraps the foreignObject.

### What is expected?
nz-icon should be visible with spinning.

### What is actually happening?
nz-icon is not visible.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | Chrome |

---
In this case, transform in the g and nzSpin of nz-icon are in conflict. Remove either one will make the icon visible. So I think the problem may be caused by the animation code of nz-icon.

**Comment by wendzhue** [comment]
Try another way to implement the effect you want, then. This problem is inevitable.

**Comment by Fanoid** [comment]
> Try another way to implement the effect you want, then. This problem is inevitable. You can't set transform to child elements of `<g>`.
> 
> https://stackblitz.com/edit/ng-zorro-antd-start-ep7k6j?file=src/app/app.component.html

I'm not setting transform to **child elements** of `<g>`. I'm setting to the `<g>` itself.

**Comment by wendzhue** [comment]
@Fanoid If you set `nzSpin` to true, it would attach a class which includes an animation property to the svg element inside of the icon.

**Comment by Fanoid** [comment]
> Try another way to implement the effect you want, then. This problem is inevitable. You can't set transform to child elements of `<g>`.
> 
> https://stackblitz.com/edit/ng-zorro-antd-start-ep7k6j?file=src/app/app.component.html

The link you provided can't work either.

**Comment by wendzhue** [comment]
@Fanoid Of course, it won't work. What I mean is that you just can't do that for SVG. It has nothing to do with the icon component. If you set transform to the text it would disappear too. See it yourself.

**Comment by Fanoid** [comment]
> @Fanoid Of course, it won't work. What I mean is that you just can't do that for SVG. It has nothing to do with the icon component. If you set transform to the text it would disappear too. Try it yourself.

I've tried. Here is the link: https://stackblitz.com/edit/ng-zorro-antd-start-qjgjkj 
Only `transform` doesn't make they disappear.  It is the `translate3d` in your code.
