### ISSUE TITLE
`nz-form-label`强制通过::after伪类加上`:`，并不是很合理

### ISSUE THREAD

**Issue by ishowman** [NG-ZORRO/ng-zorro-antd#3122]
## What problem does this feature solve?
在左侧表单字段描述，右侧输入框的这种设计中，并不是所有设计师都喜欢在表单描述中使用`:`符号，希望能慎重考虑这个问题。个人认为强制通过::after伪类加上`:`并不合理

## What does the proposed API look like?
去除该伪类，如果开发者需要加上`:`，由开发者自行加上即可

**Comment by wendzhue** [comment]
@ishowman Hi. 这是 Ant Design 设计规范, 可以去 https://github.com/ant-design/ant-design/ 发起 issue 讨论.
