### ISSUE TITLE
nz-table expand all in header

### ISSUE THREAD

**Issue by julian-ott-emnify** [NG-ZORRO/ng-zorro-antd#3126]
## What problem does this feature solve?
**FOR** a table with expandable rows
**I WANT TO** have an expand all button
**SO THAT** i don't have to click every row on it's own

the expand all button should run through these states:
* some or no rows expanded -> all rows expanded
* all rows expanded -> no rows expanded

at the moment i implemented this in a small helper function:

```typescript
  /**
   * calculate the expand state and go from
   * some or none expanded -> all expanded
   * all expanded -> none expanded
   * @param data
   */
  handleToggleAll(data: { expand: boolean }[]) {
    const items = data || [];
    const state = !items.every(item => item.expand);
    items.forEach(item => item.expand = state);
  }
```
## What does the proposed API look like?
```html
<nz-table>
  <thead>
    <th nzShowExpand nzShowExpandAll></th>
  </thead>
</nz-table>
```

**Comment by vthinkxie** [comment]
As you see, `nz-table` does not and can not change your data at all time, all data are managed by developers.
there is no way to add such a function.
