### ISSUE TITLE
Upload组件无法显示Tooltip文本

### ISSUE THREAD

**Issue by ismezy** [NG-ZORRO/ng-zorro-antd#3130]
### Reproduction link
[https://stackblitz.com/edit/angular-cwmfsv-ieebn1](https://stackblitz.com/edit/angular-cwmfsv-ieebn1)

### Steps to reproduce
在Upload上添加nzText属性，或者在Upload内的button上添加nzText

### What is expected?
鼠标移动到upload组件上显示Tooltip提示

### What is actually happening?
无法显示Tooltip提示

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.3 |
| Browser | chrome |

**Comment by HsuanXyz** [comment]
`<button nz-button nz-tooltip nzTitle="上传">`
