### ISSUE TITLE
InputNumber blur methods can't get correct current value from validation info

### ISSUE THREAD

**Issue by ishowman** [NG-ZORRO/ng-zorro-antd#3134]
### Reproduction link
[https://stackblitz.com/edit/zorro-input-number?file=src/app/app.component.ts](https://stackblitz.com/edit/zorro-input-number?file=src/app/app.component.ts)

### Steps to reproduce
- focus & input some content
- blur
- see log info from devtool console 

### What is expected?
Expect developer can get correct current value from InputNumber when blur triggers, just as the html tag `<input type="number">` performs.

### What is actually happening?
Actually, InputNumber get previous value when blur methods trigger, while the html tag `<input type="number">`get the correct current value

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.1.0 |
| Browser | chrome 73 |

**Comment by ishowman** [comment]
@vthinkxie Is it a bug to be fixed?

**Comment by vthinkxie** [comment]
Hi @ishowman the repro link is not valid now, could you plz give another one?

**Comment by ishowman** [comment]
@vthinkxie link updated
