### ISSUE TITLE
ng-zorro 7版本关于对话框moadl的bug

### ISSUE THREAD

**Issue by lixiangyue** [NG-ZORRO/ng-zorro-antd#3137]
ng-zorro 7版本关于对话框moadl的bug
组件：
信息提示框
各种类型的信息提示，只提供一个按钮用于关闭。

1.8的版本是只有一个按钮
7版本变成了2个按钮
麻烦请关注下，给与解决

**Comment by HsuanXyz** [comment]
@lixiangyue 升级到 `7.1.0`
