### ISSUE TITLE
Add Landing Page Templates 

### ISSUE THREAD

**Issue by yehia2amer** [NG-ZORRO/ng-zorro-antd#3140]
## What problem does this feature solve?
Creating Landing Page Templates Including Navs, Banners, Content Components, and Footers
To give users a fast way to Create enterprise web apps in few mins

React users do have this in: https://landing.ant.design/ . But this templates don't support Angular.
## What does the proposed API look like?
https://github.com/ant-design/ant-design-landing

**Comment by DreamPWJ** [comment]
Yes, it's necessary, otherwise I have to use react for my official website

**Comment by DreamPWJ** [comment]
Landing Page Templates工作量可能有点大   可以先考虑开源文档系统 让更多的开源项目可以使用 高质量的文档系统

**Comment by wendzhue** [comment]
You should open a feature request on https://github.com/ant-design/ant-design-landing, to request exporting to Angular. See https://github.com/ant-design/ant-design-landing/issues/50.
