### ISSUE TITLE
Disable nzTooltip conditionally

### ISSUE THREAD

**Issue by Supamiu** [NG-ZORRO/ng-zorro-antd#3142]
## What problem does this feature solve?
We sometimes want to disable tooltip conditionally, an example would be inside a collapsible sidebar, you might want to show route names on hover using tooltips when the sidebar is collapsed, but not when it's expanded
## What does the proposed API look like?
Adding an input to nz-tooltip, named `nzDisabled` that just stops the tooltip from opening if it's true.

**Comment by HsuanXyz** [comment]
```html 
        <li nz-menu-item nz-tooltip nzPlacement="right" [nzTitle]="isCollapsed ? 'Navigation One' : null>
          <span title>
            <i nz-icon type="mail"></i>
            <span>Navigation One</span>
          </span>
        </li>
```

**Comment by IonelLupu** [comment]
@hsuanxyz it doesn't work : https://stackblitz.com/edit/ng-zorro-antd-start-doyvx3

**Comment by jan-nick** [comment]
`[nzPopoverTrigger]="condition ? null : 'hover'"` worked for me, but might lead to type errors (depending on how strict you configured typing in your tsconfig)
