### ISSUE TITLE
标签页右键关闭功能

### ISSUE THREAD

**Issue by runFP** [NG-ZORRO/ng-zorro-antd#3150]
## What problem does this feature solve?
目前标签页右键，关闭标签，是关闭当前标签，关闭其他标签是关闭除选中外的所有标签

## What does the proposed API look like?
能否提供参数，让关闭其它标签和关闭标签是基于鼠标选中，来排除其他标签

**Comment by HsuanXyz** [comment]
@runFP NG-ZORRO 目前(**7.1.x**) 并未提供右键关闭功能，请检测一下是否使用的是其他第三方库，比如 NG-Alain，并在正确的 Github 仓库提交此 Issue。
