### ISSUE TITLE
关于表格table的nzData问题

### ISSUE THREAD

**Issue by lixiangyue** [NG-ZORRO/ng-zorro-antd#3151]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
如果nzData绑定的变量是一个对象的话，table会直接生成一条数据

### What is expected?
不会自动生成一条数据

### What is actually happening?
自动生成了一条数据

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.1.0 |
| Browser | 所有 |

**Comment by vthinkxie** [comment]
nzData 只支持绑定数组，传入非法数据不会正确渲染
