### ISSUE TITLE
Checkbox   ngModel support 0 and 1

### ISSUE THREAD

**Issue by DreamPWJ** [NG-ZORRO/ng-zorro-antd#3152]
## What problem does this feature solve?
The Boolean types stored in most back-end databases may be 0 and 1 values, while the ngmodel retrieves true and false. Although the conversion is simple, it is still a little tedious to convert each time. We hope that the ngmodel can directly retrieve 0 and 1 values

## What does the proposed API look like?
[ngModel] number|boolean  ,  add  nzValueNumber="true" api

**Comment by vthinkxie** [comment]
won't support

**Comment by DreamPWJ** [comment]
@vthinkxie  对不住  说错了  是Switch组件  这个功能还是很实用的  考虑一下
