### ISSUE TITLE
nz-time-picker的nzFormat属性设置为“mm:ss”时，返回的时间不对

### ISSUE THREAD

**Issue by iotzy** [NG-ZORRO/ng-zorro-antd#3156]
## What problem does this feature solve?
在nzFormat属性设置为“mm:ss”时，手动填写四位时间【分分：秒秒】[mm：ss]会当做【时时：分分】[hh:mm]来处理，希望这里针对nzFormat的设定值处理一下，谢谢。

parseTime(text: string): Date | undefined { if (!text) { return; } return fnsParse(1970-01-01 ${text}); }

## What does the proposed API look like?
在nzFormat属性设置为“mm:ss”时，返回的时间格式能正确处理

**Comment by simplejason** [comment]
time-picker返回的格式为Date类型，如需提取相应格式，请自行处理，更多定义类型请参考官方文档

**Comment by iotzy** [comment]
希望 nzformat = "mm:ss"时  在time-picker中输入4位的数字 能

> return fnsParse(`1970-01-01 00:${text}`);
这样处理,而不是

> return fnsParse(`1970-01-01 ${text});

下面的这种会将我输入的4位数【mm:ss】 的分钟数当 【hh:mm】 处理，从而返回的是我不想要的结果。

**Comment by hsuanxyz** [comment]
fixed via #5770
