### ISSUE TITLE
tree-select 子节点使用selectable:false禁止选中后，希望能点击此节点时能展开此节点

### ISSUE THREAD

**Issue by huangxiuqi** [NG-ZORRO/ng-zorro-antd#3157]
## What problem does this feature solve?
现在tree-select组件点击禁止选中的节点时会直接关闭下拉弹出，体验挺不好的，希望能改成如果点击selectable:false的节点，展开此节点，

## What does the proposed API look like?
https://stackblitz.com/edit/ng-zorro-antd-start-utfmho?embed=1&file=src/app/app.component.ts
例如上面的例子，点击parent 1节点，会直接关闭下拉框，希望能做成点击parent 1节点时展开parent 1节点

**Comment by hsuanxyz** [comment]
fixed via ##3843
