### ISSUE TITLE
栅格布局中间隔nzGutter的正确的使用方式？

### ISSUE THREAD

**Issue by guodidi** [NG-ZORRO/ng-zorro-antd#316]
在栅格布局中，常常需要和间隔进行配合，你可以使用 nz-row 的 nzGutter 属性，我们推荐使用 (16+8n)px 作为栅格间隔。请问这里的16 ， 8 ， n 三个参数/数字，分别代表什么意思呢？谢谢

**Comment by cipchk** [comment]
所以我一直非常建议好好细读[整个antd的指引文章](https://ant.design/docs/spec/introduce)。

`nzGutter` 间距是整个布局中最常用的，默认分为：

+ 小 `8px`
+ 中 `16px`
+ 大 `24px`

这三种间距规格主要用来划分信息层次，一张ANTD官网的图解释一切：

![blbcqhsujhkxxau](https://user-images.githubusercontent.com/2987467/30521494-f82712d8-9bf2-11e7-8897-c2f26a0c1237.png)

我曾经也写过一篇文章[我所认知的 ANT DESIGN](https://zhuanlan.zhihu.com/p/28767882)，希望能帮到你。
