### ISSUE TITLE
Select component should not display dropdown menu correctly when using NzSelectComponent.focus API 

### ISSUE THREAD

**Issue by YuchenWell** [NG-ZORRO/ng-zorro-antd#3168]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-d88fxe](https://stackblitz.com/edit/ng-zorro-antd-start-d88fxe)

### Steps to reproduce
- Add a new select component into DOM.
- Use NzSelectComponent.focus( ).
- Input text in search box (please do not click the search box before input text).

### What is expected?
I hope select component do the same thing as normal situation.

### What is actually happening?
Dropdown menu should not display as normal.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.1.0 |
| Browser | Chrome  72.0.3626.121 |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-rfw2m5?file=src/app/app.component.ts
this may help
`nzOpen` and `focus()` are two different api, the `focus()` api won't open the dropdown
