### ISSUE TITLE
[bug] 关于 nz-modal 的 zIndex 问题

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#317]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

若在 `nz-modal` 中再次使用 `NzModalService` 打开另一个 `nz-modal` 的时候，需要手动维护 `nzZIndex` 属性，否则会像这样：

GIF动画：

![bug](https://user-images.githubusercontent.com/2987467/30521574-485d5496-9bf4-11e7-938a-7547c9778912.gif)

若指定：

```typescript
zIndex: 1001
```

`nz-modal` 正常，但变成影响到 **nz-popconfirm**、**Notification** 的显示。

另一个GIF：

![1](https://user-images.githubusercontent.com/2987467/30531806-2208d81c-9c83-11e7-862d-e3cca51bf144.gif)

建议在 `NzModalService` 维护好 `zIndex` 合理值，否则在三层（虽然很少）很难把持。

**Comment by vellengs** [comment]
Any processing for this issue?

**Comment by LinBoLen** [comment]
modal is used for focus on some of detail. there are no need to display two modal in same page.

when new modal open. the previous modal should be hidden, and when new modal closed then the previous should be visible

**Comment by vellengs** [comment]
Can not agree that, disappointed.

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed
