### ISSUE TITLE
It seems that Select [nzMenuItemSelectedIcon]doesn't work

### ISSUE THREAD

**Issue by ishowman** [NG-ZORRO/ng-zorro-antd#3172]
### Reproduction link
[https://stackblitz.com/edit/zorro-select](https://stackblitz.com/edit/zorro-select)

### Steps to reproduce
Click select to choose Windows option

### What is expected?
Expect to show File icon with Windows text in the select input

### What is actually happening?
Only show Windows text in the select input, no File icon.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.1.0 |
| Browser | chrome 73 on Mac air |

---
I want a Select, and options inside it with custom icons.
When I select one option, I wish the content shows in Select is the same as option I selected (text with icon).

I notice that there is  `nzMenuItemSelectedIcon` in docs which seems can deal with it,  but I tried and nothing different happens.
If I misunderstood it, please tell me whether Select support this feature or not( It would be better if you could offer a solution).

**Comment by vthinkxie** [comment]
nzMenuItemSelectedIcon only work with nzMode="multiple"

**Comment by ishowman** [comment]
> I want a Select, and options inside it with custom icons.
When I select one option, I wish the content shows in Select is the same as option I selected (text with icon).

@vthinkxie Is it not supported yet?

**Comment by ishowman** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/2946
