### ISSUE TITLE
virtual-scroll 希望支持 autosize

### ISSUE THREAD

**Issue by billpeace** [NG-ZORRO/ng-zorro-antd#3173]
### Reproduction link
[https://stackblitz.com/edit/angular-tydcq3?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-tydcq3?file=src/app/app.component.ts)

### Steps to reproduce
现在 不支持 autosize

期待 support items of unknown size

### What is expected?
期望 支持   autosize

### What is actually happening?
可以根据实际 row height 大小来自动改变 ItemSize

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.1.0 |
| Browser | chrome |

---
https://github.com/angular/material2/issues/10113

<cdk-virtual-scroll-viewport [style.height.px]="height" autosize>
  <div *cdkVirtualFor="let item of list">{{ item }}</div>
</cdk-virtual-scroll-viewport>

import { ScrollingModule } from '@angular/cdk-experimental/scrolling';
import { ScrollDispatchModule } from '@angular/cdk/scrolling';
imports: [ScrollDispatchModule, ScrollingModule],

**Comment by vthinkxie** [comment]
Hi @billpeace 
we will not `@angular/cdk-experimental` you can submit this issue after it supports`autosize` in `@angular/cdk`
