### ISSUE TITLE
NzDropdownService doesn't support create with click event

### ISSUE THREAD

**Issue by wheeljs** [NG-ZORRO/ng-zorro-antd#3175]
### Reproduction link
[https://stackblitz.com/edit/angular-snzcmj-q1nxjh](https://stackblitz.com/edit/angular-snzcmj-q1nxjh)

### Steps to reproduce
Remove `$event.stopPropagation()` in contextMenu method at line 41, it seems nothing happened when clicking. But after putting breakpoint in `NzDropdownService#create` and step into, we can see the dropdown be created and close immediately.

### What is expected?
Create and show dropdown correctly, like ng-zorro-antd@7.0.0-rc.3.

stackblitz with ng-zorro-antd@7.0.0-rc.3: https://stackblitz.com/edit/angular-snzcmj-hzlura

### What is actually happening?
Dropdown was created and closed immediately.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.1.0 |
| Browser | 版本 73.0.3683.86（正式版本） （64 位） |

---
Sorry for my English.

**Comment by vthinkxie** [comment]
NzDropdownService is designed for contextmenu event, all click event outside the menu will close it immediately.
it works as design, you can add `$event.stopPropagation()` just like what you have done in the repro link.
