### ISSUE TITLE
使用表单组件时,编辑器提示 Angular: Identifier 'userName' is not defined. '__type does not contain such a member

### ISSUE THREAD

**Issue by leeziiAtCn** [NG-ZORRO/ng-zorro-antd#318]
直接copy的官网例子
webstorm vscode下报错一样

**Comment by HsuanXyz** [comment]
Form 表单有很多例子，请问你说的是那个？

**Comment by vthinkxie** [comment]
Hi @leeziiAtCn , it is an unanswerable question https://zhuanlan.zhihu.com/p/25795393.

**Comment by leeziiAtCn** [comment]
![image 1](https://user-images.githubusercontent.com/22995117/30527283-70028d26-9c59-11e7-98f4-803c19509ab2.png)

**Comment by vthinkxie** [comment]
@leeziiAtCn your userName is not defined, please make sure you already understand angular reactive form before you copy code from the website.

**Comment by leeziiAtCn** [comment]
@vthinkxie 
ok bro, What's the point of your document if I have the error of copying the code according to the document?

**Comment by vthinkxie** [comment]
@leeziiAtCn you can not boot angular only with single component, the demo code assumed that you have corrected angular base environment.

**Comment by leeziiAtCn** [comment]
@vthinkxie  emmm,I still think it's inappropriate for zorro to do it, Because I  think is not the user's responsibility.
I try copy your code on step form 'get started'--->'form',I still get a error.
Of course if you think  user in not too smart , so we are is not too smart,haha

**Comment by leeziiAtCn** [comment]
and my Ng-app is can running , no error in my page and console,
only get a error in my IDE,
so I think that error is not easy to catch

**Comment by vthinkxie** [comment]
If there is only error in your ide, you may not config your `tslint.json o`r other config properly, there is nothing todo with the code itself.

**Comment by leeziiAtCn** [comment]
![image 1](https://user-images.githubusercontent.com/22995117/30539405-cf0ef6ec-9ca4-11e7-92b3-9f2fede0bbd1.png)
![2](https://user-images.githubusercontent.com/22995117/30539406-cf0f4746-9ca4-11e7-96ef-d4f21022d00a.png)
![image 4](https://user-images.githubusercontent.com/22995117/30539407-cf0fc842-9ca4-11e7-8c5c-ac1e92c44eec.png)
