### ISSUE TITLE
the [nzStrokeColor] input doesn't work in nz-progress, because path.ant-progress-circle-path stroke has overwritten it.

### ISSUE THREAD

**Issue by Crystal2Han** [NG-ZORRO/ng-zorro-antd#3184]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
<nz-progress id="red-progress" [nzWidth]="40" [nzPercent]="75" nzType="circle" nzStrokeColor="#f31d28">
</nz-progress>

### What is expected?
should be reset store color correctly

### What is actually happening?
it is overwritten by default strock color

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Chrome |

**Comment by wendzhue** [comment]
@Crystal2Han The reproduce link is invalid.

**Comment by xguan2014** [comment]
@chunghha 请问这个 bug ，你那边怎么解决的？ 设置 nzStrokeColor="#f31d28" 无效

**Comment by wendzhue** [comment]
@xguan2014 可以开一个新 issue 并提供复现链接以帮我们排查这个问题。

**Comment by ssolida** [comment]
any news on that ? still having the same issue

**Comment by wenqi73** [comment]
Ref #3441
