### ISSUE TITLE
breadcrumb doesn't work @v7.2.0 when nzAutoGenerate is true

### ISSUE THREAD

**Issue by cp1001** [NG-ZORRO/ng-zorro-antd#3186]
### Reproduction link
[https://stackblitz.com](https://stackblitz.com)

### Steps to reproduce
我使用了自动生成面包屑的模式：
```
      <nz-breadcrumb [nzAutoGenerate]="true" style="margin:16px 0;">
      </nz-breadcrumb>
```
在v7.0.3版本，刷新页面后，面包屑消失。为了解决这个问题，我升级到v7.2.0，但是切换页面后面包屑没有跟随改变

### What is expected?
切换页面后面包屑跟随改变

### What is actually happening?
切换页面后面包屑没有跟随改变

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome |

**Comment by wendzhue** [comment]
@cp1001 重现链接无效

**Comment by jiangzhenxiang** [comment]
> Hello @cp1001. Please provide a online reproduction by forking this link https://stackblitz.com/edit/ng-zorro-antd-start or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @cp1001, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://stackblitz.com/edit/ng-zorro-antd-start) 创建一个 stackblitz 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

https://github.com/jiangzhenxiang/ng-breadcrumb
我使用最新的@angular/cli新建了一个项目， 使用NG-ZORRO 的layout和Breadcrumb， 切换页面面包屑没有更新。

**Comment by jiangzhenxiang** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-kkvhda?file=src%2Fapp%2Fapp.module.ts

**Comment by jiangzhenxiang** [comment]
stackblitz例子
https://stackblitz.com/edit/ng-zorro-antd-start-kkvhda?file=src%2Fapp%2Fapp.module.ts

**Comment by jiangzhenxiang** [comment]
> @cp1001 重现链接无效

stackblitz例子
https://stackblitz.com/edit/ng-zorro-antd-start-kkvhda?file=src%2Fapp%2Fapp.module.ts

**Comment by Gyyyang** [comment]
我也出现了同样的问题，刷新后固定在当前页面路由，不会跟随变化

**Comment by howardlau1999** [comment]
我出现的问题是breadcrumb根本无法获取当前页面的路由，一直为空

**Comment by Lin-Zhy** [comment]
same problem，在非lazy load 情况下， @v7.3.2 breadcrumb根本无法获取当前页面的路由，一直为空，退回@v7.0.1 breadcrumb 就神奇的出现了。面白y

**Comment by duoduoObama** [comment]
我也出现了，出现的问题是[nzAutoGenerate]="true"根本无法获取当前页面的路由，面包屑一直为空
和这个例子一样https://stackblitz.com/edit/ng-zorro-antd-start-kkvhda?file=src%2Fapp%2Fapp.module.ts
