### ISSUE TITLE
PageHeader with a button in `extra` and title is not aligned

### ISSUE THREAD

**Issue by TheAifam5** [NG-ZORRO/ng-zorro-antd#3187]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-rcgr6u](https://stackblitz.com/edit/ng-zorro-antd-start-rcgr6u)

### Steps to reproduce
* Add `nz-page-header`
* Add `nz-page-header-title`
* Add `nz-page-header-extra` with a button only (normal size tested)

### What is expected?
The button in `extra` should be aligned to the text horizontally.

### What is actually happening?
The button in `extra` is not aligned and looks ugly. With `small` button looks ok.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Firefox 67.0b5 |

**Comment by TheAifam5** [comment]
Using `absolute` everywhere is so ugly ....

**Comment by TheAifam5** [comment]
My fix:
```
&-page-header {
    &-title-view {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;

      &-extra {
        position: unset;
        top: unset;
        right: unset;
      }
    }
  }
```

**Comment by HsuanXyz** [comment]
https://github.com/ant-design/ant-design/issues/15680

**Comment by hsuanxyz** [comment]
fixed via antd v4

https://stackblitz.com/edit/angular-3mxtsv?file=src%2Fapp%2Fapp.component.ts
