### ISSUE TITLE
Add row grouping to NzTableComponent

### ISSUE THREAD

**Issue by martani** [NG-ZORRO/ng-zorro-antd#3188]
## What problem does this feature solve?
Allow the NzTableComponent to have row groupings where groups of rows can be expanded/collapsed. 
## What does the proposed API look like?
The user can define a grouping key in the model where rows with the same grouping key are shown in the same collapsible group in the table. Users should be able to define a template of what's shown in the group heading.

**Comment by vthinkxie** [comment]
Hi @martani 
all` td` and `tr` are controlled by the users in ng-zorro-antd table component, the nz-table is a template driven component, we won't provide render api like `columns group` because they are conficted.
