### ISSUE TITLE
Navbar RWD

### ISSUE THREAD

**Issue by tigercosmos** [NG-ZORRO/ng-zorro-antd#319]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

We can use [`menu`](https://ng.ant.design/#/components/menu) to do the navbar as in [`layout`](https://ng.ant.design/#/components/layout) demo.
Navbar no RWD yet.

## Expected behavior

![image](https://user-images.githubusercontent.com/18013815/30526597-cf71e8c4-9c4f-11e7-939c-925f51d53fe0.png)
![image](https://user-images.githubusercontent.com/18013815/30526598-d4903536-9c4f-11e7-84d2-fc8c6fac8965.png)

## What is the motivation / use case for changing the behavior?

If this function have not been started yet. Maybe I can do it.

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
RWD is not provided by ant design itself yet, it will be sync if antd react provide this feat.

**Comment by boubouhkarim** [comment]
Hi @tigercosmos , 
I'm looking for the same thing, did you found any handy solution for this ?
Thank you.

**Comment by tigercosmos** [comment]
@boubouhkarim I build my own wheels by pure CSS

**Comment by vthinkxie** [comment]
duplicated #2531
