### ISSUE TITLE
[ input  textarea ] Component recommends the allowClear attribute be added

### ISSUE THREAD

**Issue by DreamPWJ** [NG-ZORRO/ng-zorro-antd#3191]
## What problem does this feature solve?
You can click on the clear icon to delete content, which is very useful

## What does the proposed API look like?
[allowClear]="true"

**Comment by wendzhue** [comment]
@DreamPWJ Could you open a similar issue on https://github.com/ant-design/ant-design? We would implement it after them.

**Comment by DreamPWJ** [comment]
@wendzhue  ant-design react This functionality has been implemented

**Comment by vthinkxie** [comment]
@DreamPWJ 
https://ng.ant.design/components/input/zh#components-input-demo-presuffix

**Comment by DreamPWJ** [comment]
@vthinkxie API设计太复杂了，react和vue版都很简单，如果有10几个input框，仅仅清除icon的代码就满屏了
