### ISSUE TITLE
[Popconfirm] Whether a service can be created in a way that provides it

### ISSUE THREAD

**Issue by DreamPWJ** [NG-ZORRO/ng-zorro-antd#3199]
## What problem does this feature solve?
Many deleted API requests require the service to invoke， unrelated pages ui， in a way that requires confirmation whenever the delete API is invoked。This is really useful to avoid multiple calls to the UI code

## What does the proposed API look like?
a service create

**Comment by wendzhue** [comment]
Please describe your use case in detail.

A question of not using service is hard to determine the overlay ref element. User has to manually query that reference.

**Comment by DreamPWJ** [comment]
As I thought before, it is really difficult to determine the display position. Can I get the position of the last mouse click as the display position?The common scenario is the delete operation, which may exist in several places at the same time. However, for the same HTTP API request that is called, the confirmation box is required, so we want to create it in the way of service, or there will be multiple confirmation boxes and text descriptions that are not easy to maintain

**Comment by wendzhue** [comment]
I guess some (fake) code would be helpful. I still have no idea why supporting popconfirm created by service would benefit you.

**Comment by DreamPWJ** [comment]
This is component-independent and involves the convenience of multiple calls to the same API for validation

**Comment by DreamPWJ** [comment]
这个和组件无关了，涉及到同一个api多次调用确认框的方便，如果用组件方式生成会写多个地方(涉及到多处维护修改要修改多处，同时防止减少工作量防止遗忘确认框)，如果用服务方式就只写调用http  api一个地方

**Comment by wendzhue** [comment]
如果你要在很多处地方都要写这种代码，那就应该考虑用 template 或者是创建一个组件来封装。如果按照鼠标位置弹出，popconfirm 就没有东西可以作为锚点来跟随页面滚动了。
