### ISSUE TITLE
不知道是字体太小，细还是颜色太浅，好像挺难看清的。

### ISSUE THREAD

**Issue by liuliangjia** [NG-ZORRO/ng-zorro-antd#32]
不知道是字体太小，细还是颜色太浅，好像挺难看清的。

**Comment by tarepanda1024** [comment]
觉得Source Code Pro字体挺好的

**Comment by liuliangjia** [comment]
不知道在哪儿可以配置整体的字的大小，对字体我没什么要求。就是primary颜色啥的。

**Comment by vthinkxie** [comment]
You can overwrite font family with css, custom colors and themes are not supported yet.
