### ISSUE TITLE
nz-drawer  [nzVisible]="true" 报错。

### ISSUE THREAD

**Issue by zaureus** [NG-ZORRO/ng-zorro-antd#3200]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-x8ifyn](https://stackblitz.com/edit/ng-zorro-antd-start-x8ifyn)

### Steps to reproduce
加载即报错。

### What is expected?
修正

### What is actually happening?
Error: Cannot read property 'overlayElement' of undefined

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome 版本 73.0.3683.86（正式版本） （64 位） |

**Comment by PineappleBeer** [comment]
这个[nzVisible]默认值不能为ture，否则初始渲染的时候就会报这个错了，只能设置初始值为false，后面再设置为ture，这样就不会报错了。
