### ISSUE TITLE
table [noResult] suggestion

### ISSUE THREAD

**Issue by tigercosmos** [NG-ZORRO/ng-zorro-antd#321]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

Currently the table component implement [`noResult`](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/table/nz-table.component.ts#L53) as
```html
<div class="ant-table-placeholder" *ngIf="data.length==0 && !nzCustomNoResult">
    <span>没有数据</span>
</div>
<div class="ant-table-placeholder" *ngIf="data.length==0 && nzCustomNoResult">
    <ng-content select="[noResult]"></ng-content>
</div>
```

So, if table has data in `.html`, but not in `data` in `.ts`, the no result will still exist, due to data.length is still 0.

**Comment by vthinkxie** [comment]
@tigercosmos you can pass any data into data in ts to hide the noResult tips, it will be hard to understand if not show noData when data is empty.
