### ISSUE TITLE
[Grid] default  [nzType]='flex', [nz-col] add [nzAlignSelf] property

### ISSUE THREAD

**Issue by DreamPWJ** [NG-ZORRO/ng-zorro-antd#3212]
## What problem does this feature solve?
Now that most users are using the current browser, can you just default to flex mode, which reduces the amount of wasted code you need to specify a type each time.
The align-self property is also very common in flex, and you want to add an API to it

## What does the proposed API look like?
default  [nzType]='flex'   ,It doesn't have to be specified,
[nz-col] add [nzAlignSelf] property , Better col layout control

**Comment by wendzhue** [comment]
This would introduce break changes.

**Comment by DreamPWJ** [comment]
@wendzhue  兼容确实是个问题 ，现在浏览器毕竟使用的是多数，可以考虑后面默认flex
