### ISSUE TITLE
use `nz-select` in `nz-modal` would cases a problem

### ISSUE THREAD

**Issue by haoyinag** [NG-ZORRO/ng-zorro-antd#3213]
### Reproduction link
[https://ng-zorro-antd-start-a6ja5q.stackblitz.io/](https://ng-zorro-antd-start-a6ja5q.stackblitz.io/)

### Steps to reproduce
use nz-select in nz-modal

### What is expected?
fix that btns not shown again

### What is actually happening?
fix it

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome |

**Comment by renyuns** [comment]
i have the same problem,have you solve it?

**Comment by renyuns** [comment]
@hsuanxyz 我的也是,自定义了 footer,然后关闭的时候还是出现取消确定按钮,我自定义 footer 为 提交了,不知道啥问题, 7.2.0 版本

**Comment by vthinkxie** [comment]
@renyuns 修复的问题只会在最新版本（目前是7.3.1）上体现，旧版本是不会自动修改代码的

**Comment by renyuns** [comment]
@vthinkxie 好的,谢谢了,我更新到 7.3.1 了,这个问题解决了
