### ISSUE TITLE
设置空状态只能全局设置，希望可以设置特定的表格设置特定空状态

### ISSUE THREAD

**Issue by runningxiao** [NG-ZORRO/ng-zorro-antd#3215]
## What problem does this feature solve?
特定的表格可以设置特定的空状态。

## What does the proposed API look like?
可以设置特定组件的空状态样式

**Comment by wendzhue** [comment]
@runningxiao 能设置空状态的组件都有 `nzNotFound` 或者类似的 input

**Comment by runningxiao** [comment]
我用的全局setDefaultEmptyContent设置空组建，全都都改变了，毫无疑问。我现在的问题的是只想在一个单独的表格设置自定义的空状态样式，求解，谢谢

**Comment by wendzhue** [comment]
@runningxiao 

这个 API OK 吗？

![image](https://user-images.githubusercontent.com/12122021/55469793-d0a2d380-5638-11e9-89d1-41c48b3a3772.png)

**Comment by runningxiao** [comment]
api是这只全局的呢
