### ISSUE TITLE
时间分页乱码

### ISSUE THREAD

**Issue by doudou2020** [NG-ZORRO/ng-zorro-antd#3217]
注意：不是用 https://ng.ant.design/issue-helper/#/zh 创建的 issue 会被立即关闭。

**Comment by zhaopeiym** [comment]
... 偶尔也会出现这种清空，每次都是需要刷新浏览器。

**Comment by zhaopeiym** [comment]
@doudou2020  有解决吗？

**Comment by vthinkxie** [comment]
最新版本已经替换了左右箭头的实现方式

**Comment by zhaopeiym** [comment]
在不更新版本的情况下  能有什么临时解决办法没有。

**Comment by zhaopeiym** [comment]
@vthinkxie  大佬
