### ISSUE TITLE
表格国际化切换语言，需要手动点击一下才会change

### ISSUE THREAD

**Issue by JoyZhou007** [NG-ZORRO/ng-zorro-antd#3218]
### Reproduction link
[https://stackblitz.com/edit/angular-5jxjdy](https://stackblitz.com/edit/angular-5jxjdy)

### Steps to reproduce
点击按钮切换语言

### What is expected?
页脚的分页会改变语言

### What is actually happening?
分页没有改变语言，需要点击一下才会改变

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome：Version 73.0.3683.86 (Official Build) (64-bit) |

**Comment by haoyinag** [comment]
@JoyZhou007 @wendzhue 其它组件也会有类似情况
比如我通过弹窗请求了一个接口，返回了一个信息，
此时弹窗并没有一齐消失，然后调用
this.modalService.success({
        nzTitle: '保存成功'
      });
也是需要点一下才会显示弹窗，
然后重启又不会，等一下又会重复出现需要点一下这个二级弹窗才会出现

**Comment by JoyZhou007** [comment]
> @JoyZhou007 @wendzhue 其它组件也会有类似情况
> 比如我通过弹窗请求了一个接口，返回了一个信息，
> 此时弹窗并没有一齐消失，然后调用
> this.modalService.success({
> nzTitle: '保存成功'
> });
> 也是需要点一下才会显示弹窗，
> 然后重启又不会，等一下又会重复出现需要点一下这个二级弹窗才会出现
