### ISSUE TITLE
Could not override css classes 

### ISSUE THREAD

**Issue by johnico** [NG-ZORRO/ng-zorro-antd#3219]
### Reproduction link
[https://stackblitz.com/edit/angular-md42sr?file=src/app/app.component.ts](url)
### Steps to reproduce
1- trying to add label float to left in component css based on simple form

### What is expected?
label will be floated to left 

### What is actually happening?
css and other css rules are not  reflected in the code

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome |

---
it happens with all CSS ruled I trying to override, for example, ant-alerts-warning ... and a lot of class that are not be overridden and I don't see them in the console

How do I affect generaly on child component  of ant

my angular json 

```
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets",
              "src/favicon.ico",
              "src/favicon.png",
              "src/favicon.icns",
              "src/favicon.256x256.png",
              "src/favicon.512x512.png",
              {
                "glob": "**/*",
                "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
                "output": "/assets/"
              }
            ],
            "styles": [
              "src/theme.less",
              "src/styles.scss"
            ],
            "scripts": []
          },

```

**Comment by johnico** [comment]
fixed
reproduce link:
https://stackblitz.com/edit/angular-md42sr?file=src/app/app.component.ts

**Comment by wendzhue** [comment]
You want to make labels left-aligned by this?

```css
label {
  float:left;
}
```

**Comment by johnico** [comment]
no its not working with text-aling . and i asked globally about override classes
please open the item

**Comment by ltotsas** [comment]
I confirm that overriding default css classes is not working, either in component scope or globally!

**Comment by electro75** [comment]
Is there any solution for this?

**Comment by creadicted** [comment]
I stumble over similar cases where I use a component and can not overwrite a value. It only works if i place overwrites in to the main application folder. But not when I use modules. 

src/theme.less or src/style.scss (both imported in the angular.json file) works. But not in the 
my-new.component.scss that I import

**Comment by wendzhue** [comment]
IMHO, I guess that’s because of scoped CSS. See https://angular.io/guide/component-styles#style-scope <https://angular.io/guide/component-styles#style-scope>.

Can you make a reproduction if it’s not the case?

**Comment by DepickereSven** [comment]
You can override CSS class by using the deep selector
example: 
```
::ng-deep .ant-table.ant-table-default 

    { 
          padding: 16px; 16px

    }
```

Source: https://stackoverflow.com/questions/58181488/how-to-change-styles-of-nz-table-in-ng-zorro

**Comment by dilipsinhrathod** [comment]
Thank you so much Bro DepickereSven +1:
