### ISSUE TITLE
表单提交

### ISSUE THREAD

**Issue by TxOne** [NG-ZORRO/ng-zorro-antd#3220]
## What problem does this feature solve?
提交的方法返回如果是promise，能否给提交按钮显示加载状态

## What does the proposed API look like?
<form nz-form (ngSubmit)="submitForm()">
  <nz-form-item>
    <nz-form-label [nzSpan]="6" nzFor="email">E-mail</nz-form-label>
    <nz-form-control [nzSpan]="14">
      <input nz-input name="email" type="email" id="email">
    </nz-form-control>
  </nz-form-item >
<nz-form-item nz-row style="margin-bottom:8px;">
        <nz-form-control [nzSpan]="14" [nzOffset]="6">
          <button nz-button nzType="primary">Register</button>
        </nz-form-control>
      </nz-form-item>
</form>

submitForm():Promise<any>{
  return new Promise((reolsve)=>{
   settimeout(()=>resolve(),3000)
})
}

**Comment by wendzhue** [comment]
```ts
submitForm(): void {
  this.isLoading = true;
  setTimeout(() => this.isLoading = false, 3000);
}
```
