### ISSUE TITLE
nz-table组件nzData不能赋值null（ng-alain的st组件报错）

### ISSUE THREAD

**Issue by qy8502** [NG-ZORRO/ng-zorro-antd#3225]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-godvkh](https://stackblitz.com/edit/ng-zorro-antd-start-godvkh)

### Steps to reproduce
对nz-table组件nzData赋值null，会得到Error: Cannot read property 'length' of null错误。
一定有人说，不要赋值null就解决了，但是使用ng-alain的st组件时，当一个http请求被取消，事实上相当于对封装的nz-table赋值null，从而报错。
错误来自nz-table.component.js:244行

        this.data = tslib_1.__spread(data);
        this.nzCurrentPageDataChange.next(this.data);

在此我只用ng-zorro-antd-start说明这个情况。

### What is expected?
期望赋值null当空数组来处理。

### What is actually happening?
控制台提示ERROR
Error: Cannot read property 'length' of null

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome |

---
使用ng-alain的st组件时报错

**Comment by vthinkxie** [comment]
ng-alain 组件的问题建议去 ng-alain 的仓库提issue

**Comment by cipchk** [comment]
@qy8502 我关闭这个 issues，若需要更多 NG-ALAIN 的帮助请至 https://github.com/ng-alain/ng-alain
