### ISSUE TITLE
NzCascarderComponent mutate the source data structure

### ISSUE THREAD

**Issue by sxlwar** [NG-ZORRO/ng-zorro-antd#3226]
### Reproduction link
[https://stackblitz.com/edit/angular-hm8boi?file=angular.json](https://stackblitz.com/edit/angular-hm8boi?file=angular.json)

### Steps to reproduce
Select a value as normal usage.

### What is expected?
NzCasecarderComponent should not mutate nzOptions's value.

### What is actually happening?
As soon as the value selected, the structure of  nzOptions would be modified. As you can see in the console, the item of children field now had been  mounted a field which named 'parent', and this filed is circular reference to its parent node.

![WX20190406-145207](https://user-images.githubusercontent.com/20088392/55666542-fcb19500-5882-11e9-8fef-dc552b97589c.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chorme 73.0.3683.86 |

---
I think this is a bad implementation.The component modifies the user's source data, and even worse, adds a circular reference.
Source data may be used by other libraries in addition to ng-zorro-antd. As my current work, I hope to combine ng-zorro-antd with ngx-formly, but this issue caused an error in my implementation process.

ngx-formly: src/core/src/lib/components/formly.form.ts

```ts
changeModel(event: { key: string, value: any }) {
    assignModelValue(this.model, event.key, event.value);
    this.modelChange.emit(clone(this.model));  
}
```

When the model changed, formly clone the model and emit it, you can find the clone mehtod at 'src/core/src/lib/utils.ts'.

```ts
export function clone(value: any): any {
  if (!isObject(value) || value instanceof RegExp || value instanceof Observable || /* instanceof SafeHtmlImpl */ value.changingThisBreaksApplicationSecurity) {
    return value;
  }

  if (value instanceof AbstractControl) {
    return null;
  }

  if (Object.prototype.toString.call(value) === '[object Date]') {
    return new Date(value.getTime());
  }

  if (Array.isArray(value)) {
    return value.slice(0).map(v => clone(v));
  }

  value = Object.assign({}, value);
  Object.keys(value).forEach(k => value[k] = clone(value[k]));

  return value;
}
```

Obviously, it's used to deep clone the target object.

Now, if ng-zorro-antd mutated nzOptions contains a circular reference(at the time user select a value), error occurs:  ERROR RangeError: Maximum call stack size exceeded.

![WX20190406-154642](https://user-images.githubusercontent.com/20088392/55666554-3f736d00-5883-11e9-8494-98356aeff9ec.png)

You can find the code at this [repo](https://github.com/sxlwar/ngx-formly)

**Comment by wendzhue** [comment]
@sxlwar Are you interested in creating a pull request?

**Comment by sxlwar** [comment]
@wendzhue  Okay, I’ll try.

**Comment by wendzhue** [comment]
A neat fix to this problem would introduce breaking changes to ng-zorro-antd. We would evaluate this issue in the future. Thanks for opening this issue.
