### ISSUE TITLE
upload组件图标还在使用class的写法。

### ISSUE THREAD

**Issue by zaureus** [NG-ZORRO/ng-zorro-antd#3228]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/upload/nz-upload-list.component.html](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/upload/nz-upload-list.component.html)

### Steps to reproduce
      <i *ngIf="icons.showRemoveIcon" (click)="handleRemove(file, $event)" class="anticon anticon-delete" title="{{ locale.removeFile }}"></i>

### What is expected?
修正

### What is actually happening?
      <i *ngIf="icons.showRemoveIcon" (click)="handleRemove(file, $event)" type="delete" title="{{ locale.removeFile }}"></i>

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Chrome 73 |

**Comment by wendzhue** [comment]
@zaureus Feel free to make a pull request! 😆
