### ISSUE TITLE
sanitizing HTML stripped some content

### ISSUE THREAD

**Issue by dasoncheng** [NG-ZORRO/ng-zorro-antd#3232]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-vd9r3y](https://stackblitz.com/edit/ng-zorro-antd-start-vd9r3y)

### Steps to reproduce
创建nzModalService时，nzContent参数为字符串html时，xss报错。

### What is expected?
自动DomSanitizer

### What is actually happening?
WARNING: sanitizing HTML stripped some content, see http://g.co/ng/security#xss

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome 73.0.3683.103 |

**Comment by wendzhue** [comment]
@HsuanXyz 

![image](https://user-images.githubusercontent.com/12122021/55696256-b8430800-59ee-11e9-85f9-3b71fd617251.png)

It seems that `ModalOptions` provided by users should be assigned to a default option.

**Comment by wendzhue** [comment]
@dasoncheng Thanks for your issue. You can use `templateRef` instead for now.

**Comment by dasoncheng** [comment]
I know, but it's too adjective to use `TemplateRef` with  some message, such as `<b>some message</b>`. so can you support the type of `bypassSecurityTrustHtml` with `nzContent` prop

**Comment by HsuanXyz** [comment]
@wendzhue 错误与此问题无关，但是我认为可以为 `nzContent ` 字段添加 `SafeHtml ` 类型支持。

**Comment by HsuanXyz** [comment]
@dasoncheng warning 是 angular 预期的行为，只会存在开发模式。手动 sanitizing 不安全的 HTML 字符串依然会出现此 warning，更多信息可以前往 [angular issues](https://github.com/angular/angular/issues?utf8=%E2%9C%93&q=sanitizing) 了解。
