### ISSUE TITLE
nz-tooltip 悬浮提示在可以双击跳转页面的表格内使用时，跳转页面后悬浮提示不消失

### ISSUE THREAD

**Issue by liangchunyanhaha** [NG-ZORRO/ng-zorro-antd#3233]
![image](https://user-images.githubusercontent.com/48541748/55696158-49fe4580-59ee-11e9-9740-2085ab213bef.png)
![image](https://user-images.githubusercontent.com/48541748/55696169-571b3480-59ee-11e9-83f2-6934fd312b9f.png)

**Comment by wendzhue** [comment]
duplicate of https://github.com/NG-ZORRO/ng-zorro-antd/issues/1530
