### ISSUE TITLE
Can't bind to 'nzIcon' since it isn't a known property of 'a'.  nz-popconfirm

### ISSUE THREAD

**Issue by abhishek-mittal** [NG-ZORRO/ng-zorro-antd#3235]
The issue which is not created via https://ng.ant.design/issue-helper/#/en will be closed immediately.

Can't bind to 'nzIcon' since it isn't a known property of 'a'. ("lReport(i)"></i></span>
              </a>
              <a nz-popconfirm nzTitle="Are you sure?" [ERROR ->][nzIcon]="iconTpl">Delete</a>
              <ng-template #iconTpl>
                <i nz-icon nzTyp"): ng:///SharedModule/GeneratedReportsManagerComponent.html@55:55

**Comment by dineshadhikari** [comment]
**Same issue** 

'nz-dropdown-menu' is not a known element:
1. If 'nz-dropdown-menu' is an Angular component, then verify that it is part of this module.
2. If 'nz-dropdown-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      Click me
    </a>
    [ERROR ->]<nz-dropdown-menu #menu="nzDropdownMenu">
      <ul nz-menu>
        <li>1st menu item</li>

**Comment by vthinkxie** [comment]
@dineshadhikari make sure you use the correct version of ng-zorro-antd

**Comment by dineshadhikari** [comment]
> @dineshadhikari make sure you use the correct version of ng-zorro-antd that match the doc you read.

My version is up-to-date.
My issue has been resolved.  @abhishek-mittal
