### ISSUE TITLE
[drawer,modal]等使用服务方式 传参的属性不一致 希望统一

### ISSUE THREAD

**Issue by DreamPWJ** [NG-ZORRO/ng-zorro-antd#3237]
## What problem does this feature solve?
drawer，modal传参分辨使用nzContentParams，nzComponentParams 不知这样设计的原因 系统统一命名  。
同时希望增加这两个组件的点击设置全屏显示按钮和属性
## What does the proposed API look like?
使用[nzParams]=''  ,  [nzFullScreen]='true'

**Comment by wendzhue** [comment]
会带来 break change

**Comment by DreamPWJ** [comment]
保持现有的api  新增api  [nzParams]=''  下一个大版本废弃掉旧的api
