### ISSUE TITLE
关于模态框关闭的时候出现奇怪的组件

### ISSUE THREAD

**Issue by Vanforu** [NG-ZORRO/ng-zorro-antd#3238]
### Reproduction link
[https://ng-zorro-antd-start-pvwucc.stackblitz.io](https://ng-zorro-antd-start-pvwucc.stackblitz.io)

### Steps to reproduce
在模态框里面放一个select

### What is expected?
不会在模态框关闭以及init的时候出现奇怪的东西

### What is actually happening?
在模态框关闭以及init的时候出现奇怪的东西

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | 版本 69.0.3497.100（正式版本） （64 位） |

**Comment by HsuanXyz** [comment]
#3213
