### ISSUE TITLE
nzSelect， when nzOpenChange then click remove item no call back

### ISSUE THREAD

**Issue by amily4555** [NG-ZORRO/ng-zorro-antd#324]
在使用 nzSelect 时，使用nzOpenChange 监听 ngModel 变化，但点击删除已选项时，没有返回监听信息

**Comment by vthinkxie** [comment]
use ngModelChange instead.

**Comment by amily4555** [comment]
OK, 3Q, FIXED

but, u can update document

**Comment by vthinkxie** [comment]
@amily4555 https://angular.cn/guide/template-syntax#ngmodel内幕 please read the doc, it should be an common sense for angular developers.
