### ISSUE TITLE
table表单的分页选择器回调可能因为网络不稳定导致数据出错。

### ISSUE THREAD

**Issue by 929853209** [NG-ZORRO/ng-zorro-antd#3240]
### Reproduction link
[https://ng-zorro-antd-start-nb4abe.stackblitz.io](https://ng-zorro-antd-start-nb4abe.stackblitz.io)

### Steps to reproduce
table首先选择pagesize=5,最后一页（第二页），之后切换为pagesize=10，可以看到network有连续的两个console，因为最大页数把当前页数挤掉了，导致当前页数变更（从第二页变为第一页）出发indexchange事件,两个请求按顺序indexchange=>pagesizechange。并且第一个indexchange时pagesize为5.连续发送的两个网络请求，并且无法获取有用的数据进行区别和屏蔽，如果第一个请求返回的比较晚会导致显示错误。手动rxjs控制发送请求频率显得因为组件被bug并且导致代码不够规范美观。  
nz-pagination.component.ts:  
```   
 const pageIndexOverflow = this.checkLastIndexOverflow();
    if (pageIndexOverflow) {
      this.nzPageIndex = this.lastIndex;
      this.nzPageIndexChange.emit(this.lastIndex);
    }  
```

### What is expected?
提供参数配置,跳过这次多余的indexchange事件。

### What is actually happening?
先进行了不应该出现的indexchange，然后pagesizechange。

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | 谷歌浏览器最新。 |

---
如果目前有解决方案因为我才疏学浅没看到，还请指教。

**Comment by 929853209** [comment]
在在线编辑器上虽然出现了两次请求，但pageSize的值是正确的。但在本地项目的console中pageIndexChange中的pageSize是旧的pageSize。是因为我的ant版本教低？还是因为本地项目数据较大产生的rxjs事件延时不同导致的？  
补充：    "ng-zorro-antd": "^1.7.0",

**Comment by vthinkxie** [comment]
@929853209 请升级至最新版本，并确定可以在在线版本重现成功

**Comment by 929853209** [comment]
> @929853209 请升级至最新版本，并确定可以在在线版本重现成功

在线版本版本可以发现确实因为总页数的减少，导致了当前页变化，并且出发了pageIndexChange事件。虽然在线版本的页数没问题，但同时触发两个请求（pageIndexChange,pageSizeChange）依然可能因为网络不稳定导致数据展示出错。

**Comment by vthinkxie** [comment]
nzPageIndexChange是当前页码变化的事件，根据nzPageIndexChange如何触发后端请求是业务逻辑，可以自行在rxjs中处理，nzTable不替用户发送任何请求，自然也无法保证网络先后顺序，可以参照rxjs switchMap一章

**Comment by zhhhc** [comment]
@vthinkxie 关于paging，有一个问题不太理解。
以这个为例
https://ng-zorro-antd-start-nb4abe.stackblitz.io

第一种操作：
1. 选择**第2页**
2. 切换pagesize为10/page
此时，只触发了nzPageSizeChange。
![image](https://user-images.githubusercontent.com/20251916/56849899-5f9bc680-692d-11e9-8549-2240e85c3e0e.png)

第二种操作：
1.选择**第3页**
2.切换pagesize为10/page
此时，同时触发了nzPageSizeChange和nzPageIndexChange事件。
![image](https://user-images.githubusercontent.com/20251916/56849915-9d98ea80-692d-11e9-9ab0-78463feb77df.png)

为什么上面两种操作触发的事件会不一样。麻烦帮忙解惑一下。

**Comment by 929853209** [comment]
> @vthinkxie 关于paging，有一个问题不太理解。
> 以这个为例
> https://ng-zorro-antd-start-nb4abe.stackblitz.io
> 
> 第一种操作：
> 
> 1. 选择**第2页**
> 2. 切换pagesize为10/page
>    此时，只触发了nzPageSizeChange。
>    ![image](https://user-images.githubusercontent.com/20251916/56849899-5f9bc680-692d-11e9-8549-2240e85c3e0e.png)
> 
> 第二种操作：
> 1.选择**第3页**
> 2.切换pagesize为10/page
> 此时，同时触发了nzPageSizeChange和nzPageIndexChange事件。
> ![image](https://user-images.githubusercontent.com/20251916/56849915-9d98ea80-692d-11e9-9ab0-78463feb77df.png)
> 
> 为什么上面两种操作触发的事件会不一样。麻烦帮忙解惑一下。

我就是来握个手
