### ISSUE TITLE
表格filter对话框中可以选择默认值但重置以后默认值失效

### ISSUE THREAD

**Issue by zwjsexcalibur** [NG-ZORRO/ng-zorro-antd#3243]
nz-table控件可以通过[nzFilters]的数组对象设置默认值，但是点击了重置过后，控件只是简单的清空了全选状态，这里既然是重置并且设置了默认值是不是最好可以重置为默认值比较符合习惯和设置默认值的意义呢？同时建议此处能够留下属性，使得程序中能够动态的决定这里的选中状态，目前好像是只可以是用户手动选择。最后感谢工程师们的辛勤付出！

**Comment by vthinkxie** [comment]
经过讨论，不会支持这个需求，原因是在 radio 选择时，唯一全部清除选项的功能依赖 重置 按钮，如果重置为 默认值，会失去全部清除选项的功能
