### ISSUE TITLE
Notifcation使用模板语法时，无法保存消息的状态

### ISSUE THREAD

**Issue by twt898xu** [NG-ZORRO/ng-zorro-antd#3249]
## What problem does this feature solve?
Notifcation的状态保存

## What does the proposed API look like?
提供状态保存的方法

我有个使用Notifcation实现消息通知的功能，在使用template语法时无法对消息的状态进行保存，请问该怎么解决。

![image](https://user-images.githubusercontent.com/28769187/55881556-732cfa80-5bd5-11e9-839f-6294f67d8498.png)

![image](https://user-images.githubusercontent.com/28769187/55881574-7cb66280-5bd5-11e9-91a6-b9a9ee6e08c8.png)

ps:深度拷贝template对象可实现状态保存，但性能上不行

**Comment by wendzhue** [comment]
@twt898xu 不知道你说的状态指的是什么的状态

**Comment by twt898xu** [comment]
@wendzhue 就是模板绑定了title和content，当title和content改变时，之前的通知里面的内容也会发生改变，有什么办法能规避这种情况

**Comment by wendzhue** [comment]
和组件库并无关联，建议先了解 Angular template 的工作原理。
