### ISSUE TITLE
Add a click event to nz-rate

### ISSUE THREAD

**Issue by martani** [NG-ZORRO/ng-zorro-antd#3252]
## What problem does this feature solve?
It would be useful to expose a click event on nz-rate. In my case, I want to show the user a popover to enter feedback.
## What does the proposed API look like?
[nzClick]="ClickHandler($event)"

**Comment by wendzhue** [comment]
`click` is a native DOM event.

**Comment by martani** [comment]
The native click event does not get triggered when you click on the stars themselves. It's only triggered when you clean on the empty space between the stars. Here is a repro: https://stackblitz.com/edit/angular-c22cjy

**Comment by wendzhue** [comment]
@martani
