### ISSUE TITLE
Modal包含表单时，反馈图标存在bug

### ISSUE THREAD

**Issue by michaelzx** [NG-ZORRO/ng-zorro-antd#3255]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-djhlth](https://stackblitz.com/edit/ng-zorro-antd-start-djhlth)

### Steps to reproduce
1.点击按钮：打开窗口
2.不输入任何信息，点击：OK
3.点击：Cancel

### What is expected?
隐藏Modal的时候，反馈图标应该一起消失

### What is actually happening?
隐藏Modal的时候，反馈图标没有消失

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Chrome |

**Comment by michaelzx** [comment]
7.0.0-rc.3中Modal的隐藏方式是display:none，7.2.0中是visibility:hidden

但表单中的.has-error.has-feedback样式的visibility:visible，这样应该是会有冲突的

**Comment by hsuanxyz** [comment]
更新你的反馈，与 #3245 所修复的是同一个问题
