### ISSUE TITLE
在代码中更新 nz-select 组件的 ngModel 下拉框内容没有变化 

### ISSUE THREAD

**Issue by liutian** [NG-ZORRO/ng-zorro-antd#3257]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-eqaqjp?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-eqaqjp?file=src/app/app.component.html)

### Steps to reproduce
选择下拉框中的一个选项，然后点击清空值

### What is expected?
下拉框内容为空

### What is actually happening?
下拉框没有任何变化，还是原来的内容

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | win10  chrome 73.0.3683.103 |

**Comment by vthinkxie** [comment]
'' 和 null 是完全不同的意义
https://stackblitz.com/edit/ng-zorro-antd-start-4qss3t?file=src/app/app.component.html

**Comment by zhangxu123123** [comment]
> ''和null是完全不同的意义
> https://stackblitz.com/edit/ng-zorro-antd-start-4qss3t?file=src/app/app.component.html
不管我设置null，还是 ''，都不会改变
