### ISSUE TITLE
How to capture key up event in inputNumber

### ISSUE THREAD

**Issue by sridharan21994** [NG-ZORRO/ng-zorro-antd#3259]
## What problem does this feature solve?
NgModelChange will be emitted only if the focus is changed but it is required to capture the events on key press.
## What does the proposed API look like?
Please expose a method for key press for inputNumber

**Comment by wendzhue** [comment]
@sridharan21994 

Note that `keydown` is a DOM native event that can propagate. See this demo: 

https://stackblitz.com/edit/ng-zorro-antd-start-aknfa4?file=src/app/app.component.ts
