### ISSUE TITLE
nz-select component can't render the multiple selected status correctly with a given initialized value

### ISSUE THREAD

**Issue by schsiung** [NG-ZORRO/ng-zorro-antd#326]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
With the given example of NzDemoSelectMultipleComponent, if I initialize the selectedMultipleOption and searchOptions both in a synchronized way, not the asynchronized way in the given example, then the initialized  selectedMultipleOption can not be rendered correctly.
<pre><code>
    this.selectedMultipleOption = [ 'tom', 'jack' ];
    this.searchOptions = [
      { value: 'jack', label: '杰克' },
      { value: 'lucy', label: '露西' },
      { value: 'tom', label: '汤姆' }
    ];
</code></pre>

**Comment by vthinkxie** [comment]
bug confirm, thanks for your feedback.
