### ISSUE TITLE
nz-carousel next方法示例？

### ISSUE THREAD

**Issue by shaww0930** [NG-ZORRO/ng-zorro-antd#3260]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
不知道如何调用nz-carousel的next方法，望提供，谢谢！

### What is expected?
希望能提供nz-carousel的next监听方法，谢谢

### What is actually happening?
希望能提供nz-carousel的next监听方法，谢谢

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome  |

**Comment by wendzhue** [comment]
https://angular.io/api/core/ViewChild
