### ISSUE TITLE
Module '"../../../../node_modules/ng-zorro-antd/ng-zorro-antd"' has no exported member 'NzInputDirective'.

### ISSUE THREAD

**Issue by wakakaLynn** [NG-ZORRO/ng-zorro-antd#3263]
报错信息如下
![image](https://user-images.githubusercontent.com/39177907/56011808-efc9f100-5d1b-11e9-95e1-a80d5bae93ce.png)

**Comment by javierfelix** [comment]
> 报错信息如下
> ![image](https://user-images.githubusercontent.com/39177907/56011808-efc9f100-5d1b-11e9-95e1-a80d5bae93ce.png)



> 报错信息如下
> ![image](https://user-images.githubusercontent.com/39177907/56011808-efc9f100-5d1b-11e9-95e1-a80d5bae93ce.png)

how did you resolve it?
