### ISSUE TITLE
How to delete or add root nodes in the nz-tree component?

### ISSUE THREAD

**Issue by hllinc** [NG-ZORRO/ng-zorro-antd#3264]
Version **0.6** I can delete or add root nodes like this:
Delete:
`if (this.activedNode.level === 0) {
            this.treeCom.nzTreeService.rootNodes.forEach((node, index, array) => {
              if (node === this.activedNode) {
                // 删除节点
                this.treeCom.nzTreeService.rootNodes.splice(index, 1);
                return;
              }
            });
          }`
Add:
`this.treeCom.nzTreeService.rootNodes.push(newNode);`

When I upgrade to **7.2.0** it doesn't work any more, it  seems the tree data is not refresh. Because when I click the tree's other node, the new node or the deleted node will suddenly appear or disappear.

**Comment by hllinc** [comment]
can not commit issue through this way.

发自我的 iPhone

**Comment by simplejason** [comment]
> can not commit issue through this way. 发自我的 iPhone
> […](#)
> 在 2019年4月12日，15:02，ng-zorro-bot ***@***.***> 写道： Hello @hllinc, your issue has been closed because it does not conform to our issue requirements. Please use the Issue Helper to create an issue, thank you! 你好 @hllinc，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 issue 助手 来创建 issue 以方便我们定位错误。谢谢配合！ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

If you want to change array data, you should use `...` operator because we support OnPush

**Comment by hllinc** [comment]
> > can not commit issue through this way. 发自我的 iPhone
> > […](#)
> > 在 2019年4月12日，15:02，ng-zorro-bot _**@**_.***> 写道： Hello @hllinc, your issue has been closed because it does not conform to our issue requirements. Please use the Issue Helper to create an issue, thank you! 你好 @hllinc，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 issue 助手 来创建 issue 以方便我们定位错误。谢谢配合！ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> If you want to change array data, you should use `...` operator because we support OnPush

Thank you.

**Comment by lucaslimafons** [comment]
Did you find any solution to that problem?

**Comment by ImportFence** [comment]
(#tree).getTreeNodes.push(NEWNode);
(#tree).renderTree()
