### ISSUE TITLE
表格横向滚动标题没有跟着变.The horizontal scrolling title of the form has not changed.

### ISSUE THREAD

**Issue by lait233** [NG-ZORRO/ng-zorro-antd#3269]
### Reproduction link
[https://stackblitz.com/edit/angular-ayyoqd?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ayyoqd?file=src/app/app.component.ts)

### Steps to reproduce
横向滚动即可看到bug.
Scroll horizontally to see the bug

### What is expected?
横向滚动表头可以跟着滚动
Horizontal scrolling header can be scrolled

### What is actually happening?
Horizontal scrolling header is not scrolling

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome73 |

**Comment by wendzhue** [comment]
@vthinkxie Check when `nzVirtualScroll` is false.

**Comment by vthinkxie** [comment]
@lait233 nzVirtualScroll 打开和关闭时tr的写法都是不同的，有什么需求需要动态切换 nzVirtualScroll ?
