### ISSUE TITLE
建议完善菜单组件 <Menu> 特性：希望添加菜单项点击事件

### ISSUE THREAD

**Issue by dkvirus** [NG-ZORRO/ng-zorro-antd#327]
菜单组件 <Menu> 希望添加菜单项点击事件。

**Comment by dkvirus** [comment]
该功能应用场景，点击子菜单时获取菜单相关信息，比如菜单名称（如果能获取到父级菜单名称那就更好了），在右侧可以制作面包屑。

![image](https://user-images.githubusercontent.com/29170168/30574481-becf834a-9d2c-11e7-9cf1-b6634b665cb4.png)

**Comment by vthinkxie** [comment]
@dkvirus you can handle it by pass any param you need into (click) event.
