### ISSUE TITLE
Carousel nzAutoPlay 改变浏览器大小后面板指示点不再自动切换

### ISSUE THREAD

**Issue by TianXinX** [NG-ZORRO/ng-zorro-antd#3272]
### Reproduction link
[https://ng-zorro-antd-start-ex2j9n.stackblitz.io/](https://ng-zorro-antd-start-ex2j9n.stackblitz.io/)

### Steps to reproduce
改变浏览器大小

### What is expected?
改变浏览器大小不影响面板指示点的切换

### What is actually happening?
改变浏览器大小后面板指示点不再自动切换

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Google Chrome 73.0.3683.103（32 位） |

**Comment by wendzhue** [comment]
Should be fixed by #3026.
