### ISSUE TITLE
Not able to search data in all pages of pagination from ng-table when using custom pipe

### ISSUE THREAD

**Issue by Ainnop** [NG-ZORRO/ng-zorro-antd#3273]
### Reproduction link
[https://stackblitz.com/edit/angular-beqgmt](https://stackblitz.com/edit/angular-beqgmt)

### Steps to reproduce
Search content in a page other than the current one

### What is expected?
Should be able to search all items in all pages not only in the current page from the pagination

### What is actually happening?
Only able to search items in the current page in the pagination, and not able to search items in other pages

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Chrome and FireFox |

**Comment by vthinkxie** [comment]
@Ainnop 
you should change the `[nzData]="alldata"` alldata when the input change, other than add filter to the template.

**Comment by Ainnop** [comment]
Many Thanks, you saved me.
