### ISSUE TITLE
[Drawer] In the case of scroll bars, the top of the Title is not fixed and should be fixed by default

### ISSUE THREAD

**Issue by DreamPWJ** [NG-ZORRO/ng-zorro-antd#3274]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-lijtrs](https://stackblitz.com/edit/ng-zorro-antd-start-lijtrs)

### Steps to reproduce
1. NgFor array loop 2. Scroll down 3. View Title position

### What is expected?
The top of the Title should be fixed by default

### What is actually happening?
The top of the Title is not fixed to follow the page scroll

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Chrome72 |

**Comment by vthinkxie** [comment]
@DreamPWJ plz submit issue to ant-design repo, we will sync with ant-design

**Comment by DreamPWJ** [comment]
@vthinkxie  ok

**Comment by hsuanxyz** [comment]
ant-design not support .
