### ISSUE TITLE
[bug] nz-select text truncation when nz-option has more text

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#328]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

the html: 

```html
<nz-select [(ngModel)]="s.s" name="s" [nzAllowClear]="false">
    <nz-option nzValue="" nzLabel="状态不限"></nz-option>
    <nz-option nzValue="1" nzLabel="正常"></nz-option>
    <nz-option nzValue="2" nzLabel="已取消合作"></nz-option>
    <nz-option nzValue="3" nzLabel="已删除但未被上传"></nz-option>
    <nz-option nzValue="10" nzLabel="待提交"></nz-option>
    <nz-option nzValue="11" nzLabel="待审核"></nz-option>
</nz-select>
```

screenshot:

![tim 20170919132401](https://user-images.githubusercontent.com/2987467/30576953-d4d36c40-9d3d-11e7-9cd0-01254c72d895.png)

**Comment by vthinkxie** [comment]
what is your expect behavior?

**Comment by cipchk** [comment]
Please see `已删除但未被上传` part.

![tim 20170919171513](https://user-images.githubusercontent.com/2987467/30585030-1f2599ba-9d5e-11e7-93f9-8da5a6d2c6b7.png)

**Comment by vthinkxie** [comment]
yes, but it is the same as antd react, you can view it here 
https://codepen.io/vthinkxie/pen/BwjvVm

**Comment by cipchk** [comment]
got it!
