### ISSUE TITLE
请问下如何点击按钮触发一个日期选择框DatePicker？

### ISSUE THREAD

**Issue by Cyclone77** [NG-ZORRO/ng-zorro-antd#3282]
### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
并非所有的时间选择都是input，也许是其他元素触发等等。
这里有个需求是这样，点击图标触发时间选择，选择时间后对其他地方赋值。

### What is expected?
实现时间选择特有组件

### What is actually happening?
实现时间选择特有组件

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser |  google |

**Comment by wendzhue** [comment]
Tried `nzOpen`?

**Comment by Cyclone77** [comment]
> Tried `nzOpen`?

nzOpen可以但是不要input直接按钮触发，值会显示在其他地方的span里，看来只能通过css来隐藏input了，不知道有其他好的方法没？
