### ISSUE TITLE
Implement Perfect Scroll Bar on scrollable tables and any other ng-zorro-ant controls where scrolling occurs FOR WINDOWS BROWSERS

### ISSUE THREAD

**Issue by Ainnop** [NG-ZORRO/ng-zorro-antd#3291]
## What problem does this feature solve?
All browsers used on windows show ugly large scroll bar while using ng-zorro-ant controls like tables, as opposed to browsers used on Mac, so the problem will solve ugly scroll bars in windows browsers. Using perfect scroll bar in ng-zorro-ant controls for scrolling or any other scrolling like on Mac would make sense. 
## What does the proposed API look like?
Perfect Scroll Bar: https://www.npmjs.com/package/ngx-perfect-scrollbar

**Comment by Ainnop** [comment]
I think you are answering a wrong question, my question is not related to width of tables, its the scroll bar appearance, please look at the images in the question for both Mac and Windows

**Comment by simplejason** [comment]
@Ainnop you can add css to overwrite scroll bar styles, ng-zorro-antd uses the same styles with ant-design, so we won't add extra styles to change the design experience unless necessary.

**Comment by Ainnop** [comment]
So how do i overwrite the css for scrolling is there section i have to change and what css selectors are affected.

**Comment by simplejason** [comment]
> So how do i overwrite the css for scrolling is there section i have to change and what css selectors are affected.

you can write css in styles.less to overwrite it. [w3c demo](https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp)

**Comment by Lukameladz3** [comment]
how did you make action field fixed? can you help me?
