### ISSUE TITLE
Pass select options by TemplateRef

### ISSUE THREAD

**Issue by maxtorchel** [NG-ZORRO/ng-zorro-antd#3293]
## What problem does this feature solve?
i.e. i want to render options in parent component, and pass them to child with nz-select component.
```
<nz-select nzSize="small" nzMode="multiple" style="width: 200px;"
           nzShowSearch
           nzAllowClear
>
<ng-container [ngTemplateOutlet]="opts"></ng-container>
</nz-select>

<ng-template #opts>
  <nz-option nzLabel="Jack" nzValue="jack"></nz-option>
  <nz-option nzLabel="Jack1" nzValue="jack1"></nz-option>
</ng-template>
```
## What does the proposed API look like?
maybe this just should works

**Comment by vthinkxie** [comment]
there is no method to get contentchild created by ngTemplateOutlet now
https://github.com/angular/angular/issues/14842
