### ISSUE TITLE
nz-table无法实现内容溢出省略

### ISSUE THREAD

**Issue by TianXinX** [NG-ZORRO/ng-zorro-antd#3300]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-pehxmq](https://stackblitz.com/edit/ng-zorro-antd-start-pehxmq)

### Steps to reproduce
出现问题的列为Description列

### What is expected?
超出宽度的内容能够隐藏并显示省略号。

### What is actually happening?
Description列的宽度不受控制，nzWidth或style="width:"都没有效果

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Google Chrome 73.0.3683.103（32位） |

---
我需要表格的内容能够保持一行并且在内容超出时显示省略号，但是当我在td上添加了相应的样式后，td的宽度就变成了内容的最大宽度，任何宽度设置都不生效。

**Comment by vthinkxie** [comment]
基础css问题，与组件库没有关系
https://stackblitz.com/edit/ng-zorro-antd-start-vfvymg?file=src/app/app.component.css
