### ISSUE TITLE
when close modal, button will flash on IE 11

### ISSUE THREAD

**Issue by Liiiiimo** [NG-ZORRO/ng-zorro-antd#3302]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-wvjvrn](https://stackblitz.com/edit/ng-zorro-antd-start-wvjvrn)

### Steps to reproduce
open modal,  and close it 

### What is expected?
nothing happen after close the modal

### What is actually happening?
modal button will flash on window

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | IE 11 |

---
you  can reproduce in the official website

**Comment by hsuanxyz** [comment]
close via #3245

**Comment by renyuns** [comment]
i have the same problem, have you solve it?
