### ISSUE TITLE
Datepicker highlighting date that isn't set on form

### ISSUE THREAD

**Issue by patricknazar** [NG-ZORRO/ng-zorro-antd#3303]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-datepicker-issue?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-datepicker-issue?file=src/app/app.component.html)

### Steps to reproduce
1. Open the DatePicker. The date has been set to new Date().
2. Click the "go-back-one-month" arrow < and navigate different pages.
3. Notice how there is a date highlighted? This deceives my users into thinking they have selected a date. They end up clicking out thinking that date was selected.
![step1png](https://user-images.githubusercontent.com/5165547/56355897-d0026380-621a-11e9-9e4c-f8c87e098eed.png)
![step2](https://user-images.githubusercontent.com/5165547/56355914-db558f00-621a-11e9-92bd-7214748fcafc.png)

### What is expected?
 * Option 1: Automatically set the date to the highlighted date as pages are navigated around.
 * Option 2: Disable this functionality and only highlight dates that are actually selected.

Both options could be configurable DatePicker modes.

### What is actually happening?
When navigating month pages a date is highlighted and looks like it has been selected. It has not.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Chrome |

---
I'm not sure if this is a spec issue or not but it really is deceptive. The same issue exists on the react version.

**Comment by wenqi73** [comment]
solved in latest AntD.

**Comment by wenqi73** [comment]
Closed via #4699.
