### ISSUE TITLE
when [nzValue] use Object at nzSelect 

### ISSUE THREAD

**Issue by web900621** [NG-ZORRO/ng-zorro-antd#3309]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-sezsm6](https://stackblitz.com/edit/ng-zorro-antd-start-sezsm6)

### Steps to reproduce
when [nzValue] use Object at nzSelect ; The first time you cancel the option, flash will appear.

### What is expected?
no flash

### What is actually happening?
has flash

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
@web900621 I didn't quite get your point, I could not find any flash when canceling the option, could you give a screenshot or gif?

**Comment by web900621** [comment]
@vthinkxie 
I am very sorry that there is no description.
To be precise, it should be when the select has a width.
Blinks when the option is cancelled for the first time.
I updated the connection: [link](https://stackblitz.com/edit/ng-zorro-antd-start-sezsm6)
It should be more obvious now

**Comment by web900621** [comment]
@vthinkxie 
![](https://raw.githubusercontent.com/web900621/giftest/master/excutee.gif)

**Comment by vthinkxie** [comment]
@web900621 you can disable animation to skip this question
https://stackblitz.com/edit/ng-zorro-antd-start-rzxwbg?file=src/app/app.component.html
we will try to resolve it later, thanks for your reporting.

**Comment by web900621** [comment]
@vthinkxie 
ok！ Thank you very much for your answer.

**Comment by vthinkxie** [comment]
the animation works as design after checked, the flash including one option display and an option destroy
It looks strange but that is how angular animation works.
