### ISSUE TITLE
为什么Table的冻结表头无法完成列宽自动同步，在下方未出现滚动条时，表头为什么右侧会有难看的滚动条。

### ISSUE THREAD

**Issue by git102347501** [NG-ZORRO/ng-zorro-antd#3312]
## What problem does this feature solve?
1.按照正常显示规则，当冻结表头时，表内数据如果未达到页面高度，此时表头和表行都不应该出现滚动条，而我发现无论如何现在表头右侧都会显示一个很不和谐的灰色滚动条出来，这不是一个规避表头对齐的最好方法。
2.而在数据超出表格高度后，表格内应该出现滚动条，同时表头冻结在最上方，此时才需要同步调整因为滚动条出现导致的表头td和内容th的对齐问题，而当数据列随着删除小于表格高度时，滚动条消失，间距应该重新调整到原始的状态。
3.当数据列宽自适应数据长度撑开或者缩小列宽的时候，表头需要跟随改变。
4.当表格数据宽度超出出现横向滚动条时，在横向滚动条左右滚动时，表头要同步对齐滚动。
以上是我个人认为冻结表头的基础功能，现在组件实现的功能一定程度上并没有解决这些问题，而是通过制定规则直接规避了这些问题。

## What does the proposed API look like?
希望后续提供表头列th="auto"的属性，设定后，该列可以自动同步列宽到对应表行td的列宽，并同时针对以上问题进行改善。

**Comment by vthinkxie** [comment]
@git102347501 样式问题可以追踪 https://github.com/ant-design/ant-design/issues/14211
我们会定期从 antd 设计文件进行同步

**Comment by git102347501** [comment]
> @ git102347501样式问题可以追踪[ant-design / ant-design＃14211](https://github.com/ant-design/ant-design/issues/14211)
> 我们会定期从antd设计文件进行同步

亲，这个提交只提到了上述第一个问题，其他几个问题也有吗？

**Comment by vthinkxie** [comment]
> > @ git102347501样式问题可以追踪[ant-design / ant-design＃14211](https://github.com/ant-design/ant-design/issues/14211)
> > 我们会定期从antd设计文件进行同步
> 
> 亲，这个提交只提到了上述第一个问题，其他几个问题也有吗？

所有的样式均需要设计文件进行支持，我们会追踪这些设计规范
