### ISSUE TITLE
Table with encapsulated customer filter component and sort

### ISSUE THREAD

**Issue by kiyonlin** [NG-ZORRO/ng-zorro-antd#3314]
### Reproduction link
[https://stackblitz.com/edit/angular-3huaun](https://stackblitz.com/edit/angular-3huaun)

### Steps to reproduce
run the stackblitz

### What is expected?
customer filter icon is after sort icon

### What is actually happening?
customer filter icon is not in the order

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Version 73.0.3683.103 (Official Build) (64-bit) |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-3huaun-erxaqg?file=src/app/customer-filter.component.ts
you have to add some style in `app-custom-filter`
```css
    :host{
      position: static !important;
    }
```

**Comment by kiyonlin** [comment]
with version `ng-zorro-antd 7.3.2`, problem happens again.

# Reproduction link
[stackblitz](https://stackblitz.com/edit/angular-3huaun-rtcmot)
