### ISSUE TITLE
Dropdown which would expand outside of the bounds of the page is stuck at the bottom left corner

### ISSUE THREAD

**Issue by SvenSchoene** [NG-ZORRO/ng-zorro-antd#3319]
### Reproduction link
[https://stackblitz.com/edit/angular-qctcpc](https://stackblitz.com/edit/angular-qctcpc)

### Steps to reproduce
1. Open the Stackblitz example.
2. Expand the dropdown in the top right corner.

### What is expected?
Dropdown menu is visible below the clicked menu item.

### What is actually happening?
Dropdown menu is visible at the bottom left of the screen.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.0 |
| Browser | Chrome 73 |

---
Related: https://github.com/NG-ZORRO/ng-zorro-antd/issues/3288
This issue was introduced with the fix for #3288.
I was really happy that the fix came so quickly, good job to you guys!
If this could be fixed additionally, that would be great.

I have a full-width menu bar and the last menu item expanded outside of the bounds of the page with ng-zorro-antd@7.2.0, and now it opens on the bottom left of the screen in @7.3.0.

**Comment by vthinkxie** [comment]
it seems that you forgot to import ng-zorro-antd.min.css
https://stackblitz.com/edit/angular-ervcpg?file=src/app/app.component.html

**Comment by SvenSchoene** [comment]
Indeed.

Also, I misread the example in #3288 and glossed over the fact that it uses `nz-dropdown` -- and therefore copy&pasted it lazily.

You're right: the issue with `nz-dropdown` is fixed now.
However, there's still an issue when using `nz-submenu`, see this example: https://stackblitz.com/edit/angular-cgqrfw?file=src%2Fapp%2Fapp.component.css

I will use `nz-dropdown` in my app for now, since that is fixed and was easy enough to switch out. However, it would be nice if submenus which pop out would also be aware of the bounds of the page.

If you want I can create a new issue for this.

**Comment by kalimulhaq** [comment]
@SvenSchoene yes right, the issue has been fixed for `nz-dropdown` but it still exist for `nz-submenu`
![submenu](https://user-images.githubusercontent.com/6983682/67856566-44a14d80-fb2e-11e9-907e-a7693b059959.png)

**Comment by wenqi73** [comment]
Submenu issue sees #3412.
