### ISSUE TITLE
走马灯放到气泡卡片和Modal对话框里面无法正常显示

### ISSUE THREAD

**Issue by 252539329** [NG-ZORRO/ng-zorro-antd#3329]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
气泡卡片鼠标经过共2张第一屏显示了第二屏的图片宽度无效，Modal对话框鼠标点击共2张图片不显示改变下浏览器宽度就显示出来了

### What is expected?
气泡卡片里面的走马灯能正常显示为每一屏的希望有个自定宽高设置，
Modal对话框能正常显示出走马灯的内容

### What is actually happening?
  

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.0 |
| Browser | Google Chrome 版本 71.0.3578.98（正式版本） （64 位） |

**Comment by wendzhue** [comment]
@252539329 重现链接无效

**Comment by 252539329** [comment]
import { Component } from '@angular/core';

@Component({
  selector: 'nz-demo-modal-basic',
  template: `
    <button nz-button [nzType]="'primary'" (click)="showModal()"><span>Show Modal</span></button>
    <nz-modal [(nzVisible)]="isVisible" nzTitle="The first Modal" (nzOnCancel)="handleCancel()" (nzOnOk)="handleOk()">
      <nz-carousel [nzEffect]="effect">
      <div nz-carousel-content *ngFor="let index of array">
        <h3>{{ index }}</h3>
      </div>
    </nz-carousel>
    </nz-modal>
  `,
  styles: [
    `
      [nz-carousel-content] {
        text-align: center;
        height: 160px;
        line-height: 160px;
        background: #364d79;
        color: #fff;
        overflow: hidden;
      }

      h3 {
        color: #fff;
      }
    `
  ]
})
export class NzDemoModalBasicComponent {
  isVisible = false;
array = [1, 2, 3, 4];
  effect = 'scrollx';
  constructor() {}

  showModal(): void {
    this.isVisible = true;
  }

  handleOk(): void {
    console.log('Button ok clicked!');
    this.isVisible = false;
  }

  handleCancel(): void {
    console.log('Button cancel clicked!');
    this.isVisible = false;
  }
}

**Comment by 252539329** [comment]
走马灯放到气泡卡里面
import { Component } from '@angular/core';

@Component({
  selector: 'nz-demo-popover-placement',
  template: `

      <button nz-button nz-popover nzTitle="Title" [nzContent]="contentTemplate" nzPlacement="top">Top</button>
    
    <ng-template #contentTemplate>
      <div>
        <nz-carousel [nzEffect]="effect">
          <div nz-carousel-content *ngFor="let index of array">
            <h3>{{ index }}</h3>
          </div>
        </nz-carousel>
      </div>
    </ng-template>
  `,
  styles: [
    `
      [nz-carousel-content] {
        text-align: center;
        height: 160px;
        line-height: 160px;
        background: #364d79;
        color: #fff;
        overflow: hidden;
      }

      h3 {
        color: #fff;
      }
    `
  ]
})
export class NzDemoPopoverPlacementComponent {
   array = [1, 2, 3, 4];
  effect = 'scrollx';
}

**Comment by wendzhue** [comment]
https://ng.ant.design/docs/contributing/zh#bugs

**Comment by 252539329** [comment]
走马灯放到Modal对话框里面
https://ng-zorro-antd-start.stackblitz.io

走马灯放到气泡卡片里面
https://4qkybr.run.stackblitz.io

**Comment by ngstyle** [comment]
https://ng-zorro-antd-start-ss5b1a.stackblitz.io

**Comment by ngstyle** [comment]
走马灯放到Modal对话框里面https://ng-zorro-antd-start-ss5b1a.stackblitz.io

**Comment by ngstyle** [comment]
https://ng-zorro-antd-start-ss5b1a.stackblitz.io

**Comment by ngstyle** [comment]
走马灯放到Modal对话框里面  https://ng-zorro-antd-start-ss5b1a.stackblitz.io

**Comment by ngstyle** [comment]
走马灯放到Modal对话框里面   https://stackblitz.com/edit/ng-zorro-antd-start-ss5b1a

**Comment by 799929573** [comment]
@ngstyle 你解决了吗？我也遇到同样问题了

**Comment by ngstyle** [comment]
> @ngstyle 你解决了吗？我也遇到同样问题了
忘记参考的哪里了，你试试
  ngAfterViewInit() {
    setTimeout(() => {
      if (this.carousel) {
        this.carousel.carouselContents.setDirty();
      }
    }, 400);
  }

**Comment by ngstyle** [comment]
@799929573 
忘记参考哪里的了，你试试
`  ngAfterViewInit() {
    setTimeout(() => {
      if (this.carousel) {
        this.carousel.carouselContents.setDirty();
      }
    }, 400);
  }`

**Comment by ngstyle** [comment]
@799929573 刚刚看了一下， 9.1.2 已经修复这个问题了

**Comment by 799929573** [comment]
@ngstyle thankyou
