### ISSUE TITLE
走马灯放到Modal对话框和Popover气泡卡片里面显示问题

### ISSUE THREAD

**Issue by 252539329** [NG-ZORRO/ng-zorro-antd#3337]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io ， https://4qkybr.run.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io ， https://4qkybr.run.stackblitz.io)

### Steps to reproduce
1、走马灯在Modal对话框里面无法正常显示，需要改变一下浏览器分辨率才能显示出来。
2、走马灯在Popover气泡卡片里面显示问题，插入的图片会显示出第二屏的图片，有时候左右滑动不灵活，像被黏在鼠标上了。

### What is expected?
走马灯在Modal对话框里里面和Popover气泡卡片能正常显示。

### What is actually happening?
无法正常显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.0.0-rc.3 |
| Browser | Google Chrome版本 71.0.3578.98（正式版本） （64 位） |

**Comment by wendzhue** [comment]
@252539329 哥你的复现链接打不开啊……

要不你先升到 7.3.2 版本试试，应该已经 fix 掉了

**Comment by 252539329** [comment]
走马灯在Modal对话框里
https://stackblitz.com/edit/ng-zorro-antd-start-yqcjqt

走马灯在Popover气泡卡片里
https://stackblitz.com/edit/ng-zorro-antd-start-xuexeq

你看看这个能打卡不？

**Comment by 252539329** [comment]
可能之前两次被保存好，现在这个应该能打开了。
走马灯在Modal对话框里的时候显示不出来，需要改变一下浏览器宽度才可以显示走马灯；
在Popover气泡卡片里走马灯里面的图片显示了第二屏的图片，内容不能占满。而且鼠标左右滑动有点问题，有时候就像黏住鼠标

**Comment by wendzhue** [comment]
A regression bug.

**Comment by wendzhue** [comment]
@252539329 

第二个问题中你的 img 没有按比例缩放，和 carousel 没有关系。

这个 PR #3367  merge 之后你还需要修改一下第一个例子中你的代码，用动态创建的方式来创建 modal，不然 carousel 首次渲染的时候 carousel 拿不到父元素正确的宽高，因为 modal 是 invisible 的。

PS 不要在复现中暴露敏感信息
