### ISSUE TITLE
【bug: nz-select】: nzSearchChange method not callback

### ISSUE THREAD

**Issue by dkvirus** [NG-ZORRO/ng-zorro-antd#334]
![image](https://user-images.githubusercontent.com/29170168/30623457-492a99ae-9dea-11e7-838e-7f7ef7bc6674.png)

- 现在状况：

只有在下拉文本框中输入值时，nzSearchChange  才能监听到事件变化

- 预期状况：

点击下拉选项改变下拉文本框的值，希望 nzSearchChange   也能监听到事件变化，并提供当前点击下拉项的 value 和 label 属性作为参数。

或者给下拉选项提供新事件，专门监听下拉选项被点击的事件。

**Comment by vthinkxie** [comment]
use ngModelChange, please

**Comment by vthinkxie** [comment]
https://angular.cn/guide/template-syntax#ngmodel内幕

**Comment by dkvirus** [comment]
thanks your time.It is my problem.I will read official document again.
