### ISSUE TITLE
upload 在chrome60版本 点击选择文件加载超级慢

### ISSUE THREAD

**Issue by lidong081824** [NG-ZORRO/ng-zorro-antd#3343]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
点击选择文件 加载框反应时间超长

### What is expected?
迅速显示选择文件筐

### What is actually happening?
反应5s左右才能显示出选择文件筐

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.2 |
| Browser | 60.0.3112.113 |

---
https://ng.ant.design/components/upload/zh 上亦是如此

**Comment by vthinkxie** [comment]
fork链接之后再写代码

**Comment by lidong081824** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-lhycfx?file=src/app/app.component.html

**Comment by cipchk** [comment]
@lidong081824 我没有相应的环境去重现，我只能找到一个相关的 [chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=638874)，我不觉得是否因为这个引起的，主要是 当 file 元素包含 `accept`、`multiple` 属性时选择文件会变慢，这个BUG已经修复。你可以确认一下。

**Comment by lidong081824** [comment]
我删除了accept 属性 仍然如此。因为 https://ng.ant.design/components/upload/zh 上也是这样 所以 我想是否需要寻找一下60版本浏览器测试一下。

**Comment by cipchk** [comment]
@lidong081824 我建议你反过来，升级你的环境看问题是否解决，相比较会更容易一点。

**Comment by lidong081824** [comment]
升级浏览器环境是ok的。chrome60有这个问题。还能提供其他的解决方案吗？

**Comment by cipchk** [comment]
@lidong081824 我也没办法，毕竟是 chrome bug。

**Comment by lidong081824** [comment]
好的 谢谢耐心解答。
