### ISSUE TITLE
Selected sub menu isn't highlighted when collapsed

### ISSUE THREAD

**Issue by ddvkid** [NG-ZORRO/ng-zorro-antd#3345]
### Reproduction link
[https://stackblitz.com/edit/angular-anbpkt?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-anbpkt?file=src/app/app.component.ts)

### Steps to reproduce
Collapse the menu and set submenu to open

### What is expected?
The selected sub menu should be highlighted by the class `ant-menu-submenu-selected`.

### What is actually happening?
The selected sub menu is not highlighted when first loaded.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.2 |
| Browser | Latest Chrome |

---
It might be because of this line https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/menu/nz-submenu.component.ts#L197

**Comment by vthinkxie** [comment]
fixed, will release in 8.0.0 version
