### ISSUE TITLE
incorrect position of custom filter icon with nzshowsort enabled

### ISSUE THREAD

**Issue by maxtorchel** [NG-ZORRO/ng-zorro-antd#3348]
### Reproduction link
[https://stackblitz.com/edit/angular-v8yetu?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-v8yetu?file=src/app/app.component.ts)

### Steps to reproduce
nzShowSort=true nzCustomFilter=true

### What is expected?
align right

### What is actually happening?
wrong align

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.2 |
| Browser | all |

**Comment by TheAifam5** [comment]
Last working version: 7.2.0

**Comment by cipchk** [comment]
@vthinkxie 能发布一个补丁吗？因为这个问题涉及 `st` 导致不敢发布新版本。

**Comment by vthinkxie** [comment]
@vthinkxie 我们今天会发布hotfix
