### ISSUE TITLE
Add anchor link to API section of each page in documentation website

### ISSUE THREAD

**Issue by avin-kavish** [NG-ZORRO/ng-zorro-antd#3349]
## What problem does this feature solve?
The documentation site generator is only generating TOC for demos. It would be good to generate TOC for site header and API section of page. I think API  link is most important as it's at the bottom of the page and need it quickly when developing.
### Method 1 (hack)
Add static code block `<nz-link nzHref="#api" nzTitle="API">` to `generateToc` method in `generate-demo.js` assuming (safely?) all pages have #api link to them.

### Method 2 (proper way)
* Capture headings in `parse-doc-md.js` to two properties, `whenToUseHeadings` and `apiHeadings`.
* Pass values to `generateToc` in `generate-demo.js`

(I'd like to contribute if approved)

**Comment by vthinkxie** [comment]
Hi @avin-kavish 
it will be great if you like to contribute, thanks a lot!

**Comment by wendzhue** [comment]
Already implemented. I am closing this now.
