### ISSUE TITLE
Cascader  component not rendered the selected label correctly with nzChangeOnSelect option

### ISSUE THREAD

**Issue by schsiung** [NG-ZORRO/ng-zorro-antd#336]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
With the given demo of nz-demo-cascader-change-on-select,  I add one middle level leaf node Ningbo,
The options is set as follow:
<pre><code>
const options = [{
  value: 'zhejiang',
  label: 'Zhejiang',
  children: [{
    value: 'hangzhou',
    label: 'Hangzhou',
    children: [{
      value: 'xihu',
      label: 'West Lake',
      isLeaf: true
    }],
  },
  {
    value: 'ningbo',
    label: 'Ningbo',
    isLeaf: true
  },
],
}, {
  value: 'jiangsu',
  label: 'Jiangsu',
  children: [{
    value: 'nanjing',
    label: 'Nanjing',
    children: [{
      value: 'zhonghuamen',
      label: 'Zhong Hua Men',
      isLeaf: true
    }],
  }],
}];
</code></pre>

1. First step: I click 'Zhejiang->Hangzhou' in order, then the 'West Lake' option comes in.

2. Then: I click 'Ningbo'  in the middle, the selected label is rendered as "Zhejiang / Ningbo"  correctly.

3. When I open the select menu again, the 'West Lake' option still exist, and if I click the 'West Lake' option directly, the the selected lable is rendered as 'Zhejiang / Ningbo / West Lake', which is not correct

## Expected behavior
In the third step, 'West Lake' option disappears or If I click the West Lake option directly,
The selected label becomes 'Zhejiang / Hangzhou / West Lake'

**Comment by vthinkxie** [comment]
@fbchen
