### ISSUE TITLE
日历插件和分页器出现如下bug，我也不知道怎么描述了，看图。

### ISSUE THREAD

**Issue by yyhuaisha** [NG-ZORRO/ng-zorro-antd#3362]
日历插件和分页器出现如下bug，我也不知道怎么描述了，按照dome正常使用，但是在测试的电脑上出现了这样的问题，我电脑上没发现过。
windows7  64位。
![image](https://user-images.githubusercontent.com/13938131/56707410-4509f780-674b-11e9-9d75-077347d86590.png)
![image](https://user-images.githubusercontent.com/13938131/56707426-55ba6d80-674b-11e9-828e-e6e85b05070d.png)
![image](https://user-images.githubusercontent.com/13938131/56707429-5a7f2180-674b-11e9-8de4-73bafb9674f5.png)

**Comment by vthinkxie** [comment]
默认打开了网页翻译软件/插件？
