### ISSUE TITLE
nz-select inside nz-dropdown: selected options disappear after reopen dropdown

### ISSUE THREAD

**Issue by maxtorchel** [NG-ZORRO/ng-zorro-antd#3368]
### Reproduction link
[https://stackblitz.com/edit/angular-iscsbq?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-iscsbq?file=src/app/app.component.ts)

### Steps to reproduce
open custom filter in first column with multiselect, select option, close and open filter dropdown again

### What is expected?
selected options are still displayed

### What is actually happening?
selected options disappear

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.2 |
| Browser | all |

**Comment by vthinkxie** [comment]
duplicated https://github.com/NG-ZORRO/ng-zorro-antd/issues/1455

**Comment by vthinkxie** [comment]
ref https://github.com/angular/angular/issues/24041
