### ISSUE TITLE
nz-table nzWidth error

### ISSUE THREAD

**Issue by ZeyZhang** [NG-ZORRO/ng-zorro-antd#337]
照着官方的例子，出现这个错误，请问如何解决？
![image](https://user-images.githubusercontent.com/20785848/30629256-791e43cc-9e0d-11e7-9922-7c7e9a3e2573.png)

**Comment by vthinkxie** [comment]
nzWdith->nzWidth

**Comment by ZeyZhang** [comment]
我用的就是nzWidth
![image](https://user-images.githubusercontent.com/20785848/30630827-c25ab2b2-9e14-11e7-9a5b-3ed8e2a6a753.png)

**Comment by ZeyZhang** [comment]
我用的就是nzWidth
![image](https://user-images.githubusercontent.com/20785848/30630932-1e8fc694-9e15-11e7-9f33-5c49256b5913.png)

**Comment by vthinkxie** [comment]
please upgrade your version to 0.5.0 higher, nzWidth is only provide after 0.5.0, you can get more info here https://ng.ant.design/#/changelog

**Comment by ZeyZhang** [comment]
ok，thanks
