### ISSUE TITLE
nz-modal  when nzOnOk is typeof OnClickCallback<any>, click ok button trigger nzAfterClose twice

### ISSUE THREAD

**Issue by tky753** [NG-ZORRO/ng-zorro-antd#3371]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-modal-bug-report000?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-modal-bug-report000?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. open console
2. click show modal button
3. click 确定 button.
```ts
handleOk(): boolean {
  return true;
}

handleCancel(): boolean {
  return undefined;
}
afterClose($event: any){
  console.log('closed for: '   $event);
}
```

### What is expected?
console one line:  
closed for: true

### What is actually happening?
console two lines:  
closed for: true  
closed for: undefined

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | Chrome 72.0.3626.121（正式版本） （64 位 |

---
BTW, when opening the page,  afterClose is triggered once immediately.
![EmEKZF.png](https://s2.ax1x.com/2019/04/26/EmEKZF.png)
![EmE1i9.png](https://s2.ax1x.com/2019/04/26/EmE1i9.png)

**Comment by hsuanxyz** [comment]
fixed via #4702
