### ISSUE TITLE
nz-select nzAllowClear数据时缺少回调函数

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#3381]
### Reproduction link
[https://ng-zorro-antd-start-imzd9o.stackblitz.io](https://ng-zorro-antd-start-imzd9o.stackblitz.io)

### Steps to reproduce
select  nzAllowClear数据时 没有回调方法

### What is expected?
select  nzAllowClear数据时 有回调方法

### What is actually happening?
暂时无法获取 nzAllowClear 清除数据的方法

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | 任意浏览器 |

---
无

**Comment by wendzhue** [comment]
`(ngModalChange)`
