### ISSUE TITLE
nz-input-group 同时使用nzPrefix和nzAddOnAfter时样式出错

### ISSUE THREAD

**Issue by ismezy** [NG-ZORRO/ng-zorro-antd#3384]
### Reproduction link
[https://stackblitz.com/edit/angular-q5eg7r](https://stackblitz.com/edit/angular-q5eg7r)

### Steps to reproduce
在nz-input-group 同时使用nzPrefix和nzAddOnAfter

### What is expected?
之前版本这样使用时是正常的

### What is actually happening?
现在这样使用后input框后的按钮样式不正确

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
样式同步原因不再支持 nzPrefix 和 nzAddOn 混写
https://stackblitz.com/edit/angular-q5eg7r-tnte4u?file=src/app/app.component.ts
