### ISSUE TITLE
ERROR Error: [@ant-design/icons-angular]: the icon arrow-left-o does not exist or is not registered.

### ISSUE THREAD

**Issue by devpei** [NG-ZORRO/ng-zorro-antd#3389]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?embed=1&file=package.json](https://stackblitz.com/edit/ng-zorro-antd-start?embed=1&file=package.json)

### Steps to reproduce
根据官网快速上手一步步创建，在使用图标的时候错误。

### What is expected?
能够显示图标

### What is actually happening?
ERROR Error: [@ant-design/icons-angular]: the icon arrow-left-o does not exist or is not registered.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.2 |
| Browser | Chrome |

---
原因：
{
                "glob": "**/*",
                "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
                "output": "/assets/"
}
版本7.3.2install后node_moudle没有/@ant-design/icons-angular/src/inline-svg/目录

**Comment by wendzhue** [comment]
重新安装即可解决。

**Comment by wendzhue** [comment]
@BruneXX Please read the doc https://ng.ant.design/components/icon/en#static-loading-and-dynamic-loading. You need to register icons (import icon resources in another word). The error is quite explicit IMHO.

**Comment by wendzhue** [comment]
PR is welcome! @BruneXX

**Comment by olegdeezus** [comment]
Hi! I received this error when running tests. Icons is dynamically linked under "ant" namespace. Can you help me?

**Comment by wendzhue** [comment]
@olegdeezus In test environments, I strongly recommend you to write a IconTestingModule and provide all icons in the module. And import that module when you are configuraing tests.

You can use this as a reference. https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/icon/testing/nz-icon-test.module.ts

Hope this helps.

**Comment by olegdeezus** [comment]
@wendzhue Thank you!

**Comment by babarinde** [comment]
Hi,
Thanks for the answers above,
I am Using Angular Universal and I should mention that for my case it seems the error was displayed but the svgs were displayed as  HTTP remote calls was loading them. It seems the error showing on the console is therefore a false alarm, since its not aware that they are dynamically loaded.
Now its quite strange to wire my mind to ignore the error messages displayed

**Comment by madumal7** [comment]
> Hi,
> Thanks for the answers above,
> I am Using Angular Universal and I should mention that for my case it seems the error was displayed but the svgs were displayed as HTTP remote calls was loading them. It seems the error showing on the console is therefore a false alarm, since its not aware that they are dynamically loaded.
> Now its quite strange to wire my mind to ignore the error messages displayed

I'm facing the same issue. Is there any solution to get rid of those ugly error messages on the console?

**Comment by kamran-mushtaq** [comment]
> Hi,
> Thanks for the answers above,
> I am Using Angular Universal and I should mention that for my case it seems the error was displayed but the svgs were displayed as HTTP remote calls was loading them. It seems the error showing on the console is therefore a false alarm, since its not aware that they are dynamically loaded.
> Now its quite strange to wire my mind to ignore the error messages displayed

I am facing the same in Angular Universal.

**Comment by s2t4nv0k** [comment]
> 重新安装即可解决。

Hope you are here to help me?

File : package.json
`  "dependencies": {

    "@angular/animations": "~10.0.2",

    "@angular/common": @ #"~10.0.2",

    "@angular/compiler": "~10.0.2",

    "@angular/core": "~10.0.2",

    "@angular/forms": "~10.0.2",

    "@angular/platform-browser": "~10.0.2",

    "@angular/platform-browser-dynamic": "~10.0.2",

    "@angular/router": "~10.0.2",

    "@ant-design/icons": "^4.2.2",

    "@ant-design/icons-angular": "^10.0.1",

    "ng-zorro-antd": "^10.0.2",

    "rxjs": "~6.5.5",

    "tslib": "^2.0.0",

    "zone.js": "~0.10.3"`


When I want to add an icon :
`<i nz-icon nzType="star" nzTheme="fill"></i>`
It runs but 
`        <i nz-icon nzType="menu-fold" nzTheme="outline"></i>
`
Error:
http://localhost:4200/assets/outline/menu-fold.svg 404 (Not Found)
ERROR Error: [@ant-design/icons-angular]:the icon menu-fold-o does not exist or is not registered.

Thanks you

**Comment by id1945** [comment]
Fix this here!
[https://giai-ma.blogspot.com/2021/05/ant-designicons-angular-icon-reload-o.html](url)

**Comment by mobinakhalilzade** [comment]
This issue solved with installing @ant-design/icons-angular and add " {
                "glob": "**/*",
                "input": "node_modules/@ant-design/icons-angular/src/inline-svg/",
                "output": "/assets/"
              }"
in angualr.json.
Thank you

**Comment by wsambian** [comment]
> In my particular case if I use: `<i [nzType].... />` the following error arise:
> 
> `Can't bind to 'nzType' since it isn't a known property of 'i'`
> 
> but when I'm using `<i nz-icon [nzType].... />` the specific error displayed here appears:
> 
> `ERROR Error: [@ant-design/icons-angular]: the icon menu-fold-o does not exist or is not registered.`
> 
> I've extracted that from the documentation page and nothing of above tried seems to work.

Please add import { NzButtonModule } from 'ng-zorro-antd/button'; to app.module and then add NzButtonModule to the list of imports. 

That should do the trick.

**Comment by cs24k1993** [comment]
> In my particular case if I use: `<i [nzType].... />` the following error arise:
> 
> `Can't bind to 'nzType' since it isn't a known property of 'i'`
> 
> but when I'm using `<i nz-icon [nzType].... />` the specific error displayed here appears:
> 
> `ERROR Error: [@ant-design/icons-angular]: the icon menu-fold-o does not exist or is not registered.`
> 
> I've extracted that from the documentation page and nothing of above tried seems to work.


I have come across the same problem as you. I did as the documention says, but it didn't work. 

Can you help me ? thank you

**Comment by HCenggel** [comment]
我也遇到过同样的问题，删除node_modules之后重新下载依赖之后就好了，仅供参考

**Comment by aniketthumar** [comment]
@wendzhue Thank you

**Comment by dimitriadisat** [comment]
Hi all,

I m facing the same issue when I try to run **ng test**.

I've tried all the solutions above but I still cannot run ng test without getting many errors saying the following message:
[ERROR Error: [@ant-design/icons-angular]: the icon arrow-left-o does not exist or is not registered.](https://github.com/NG-ZORRO/ng-zorro-antd/issues/3389#top)

My version of ng-zorro-antd is 13.0.0

**Comment by dimitriadisat** [comment]
> As wzhudev says above
> 
> 1：Create a new file . eg: import { NzIconTestModule } from '@shared/nz-icon-test.module';
> 
> You can use this as a reference. https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/icon/testing/nz-icon-test.module.ts
> 
> 2: Introduce it in your test file eg: beforeEach(async () => { await TestBed.configureTestingModule({ imports: [ NzIconTestModule //here
> 
> now , is OK！

Thanks chenweihan.

I already implemented that but nothing has changed.

**Comment by chenweihan** [comment]
@dimitriadisat
please check it again, because this file is the file in the official test case.
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/icon/testing/nz-icon-test.module.ts.

**Comment by venkateshatfrudev** [comment]
> This issue solved with installing @ant-design/icons-angular and add " { "glob": "**/*", "input": "node_modules/@ant-design/icons-angular/src/inline-svg/", "output": "/assets/" }" in angualr.json. Thank you

thank you this is working

**Comment by 1stcoderXiaoLin** [comment]
Create a new icons-provider in the directory at the same level as app, and type the icons you need, and then introduce app.config.ts

```ts
import {EnvironmentProviders, importProvidersFrom} from '@angular/core';
import {
  BookOutline,
  EnterOutline,
  LockOutline,
  LoginOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PlusOutline,
  RollbackOutline,
  SearchOutline,
  UserOutline
} from '@ant-design/icons-angular/icons';
import {NzIconModule} from 'ng-zorro-antd/icon';

const icons = [PlusOutline, UserOutline, BookOutline, LoginOutline, MenuFoldOutline, MenuUnfoldOutline,
  EnterOutline, LockOutline, SearchOutline, RollbackOutline];

export function provideNzIcons(): EnvironmentProviders {
  return importProvidersFrom(NzIconModule.forRoot(icons));
}

```
![image](https://github.com/user-attachments/assets/012fd7ca-3853-465e-9e1e-9ffc1d3ace52)

**Comment by ahmad-ben** [comment]
I had that problem in test file, and i simply solve it by:

```
import { NzIconModule, provideNzIcons } from 'ng-zorro-antd/icon';
import { StopOutline } from '@ant-design/icons-angular/icons';

fdescribe('EmptyStateComponent', () => {

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        ...
        NzIconModule
      ],
      providers: [provideNzIcons([StopOutline])]
    })
    .compileComponents();
    ....
  });
});
```
