### ISSUE TITLE
Bug nz-input can't bind ngModel

### ISSUE THREAD

**Issue by Tuanz1** [NG-ZORRO/ng-zorro-antd#339]
# When I use nz-input, there is a bug.
Here is my code 
```
<nz-input [(ngModel)]="siteName">
  <ng-template #addOnBefore>http://</ng-template>
  <ng-template #addOnAfter>.com</ng-template>
</nz-input>
```
But the console report that:
> Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'nz-input'.

Then I delete the bind words. There is no error. But this means I can't input any data.

How can I solve this issue?

**Comment by vthinkxie** [comment]
if you want to use ngModel, you have to import form modules, please read the doc https://angular.cn/guide/forms#修改-appmodulets

**Comment by Tuanz1** [comment]
I really forget it！ @vthinkxie Thanks
