### ISSUE TITLE
nz-carousel的nzDotRender如何使用

### ISSUE THREAD

**Issue by michael2043** [NG-ZORRO/ng-zorro-antd#3390]
## What problem does this feature solve?
如题，我想自定义样式，应该怎么实现，最好有demo，初学者请见谅

## What does the proposed API look like?
提供相关demo

**Comment by wendzhue** [comment]
![image](https://user-images.githubusercontent.com/12122021/56943116-97cf1f00-6b50-11e9-8042-75581d194b06.png)
