### ISSUE TITLE
textarea will not autoresize on load if inside a collapse-panel

### ISSUE THREAD

**Issue by azvolinl** [NG-ZORRO/ng-zorro-antd#3396]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-txmsmw?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-txmsmw?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
Put textarea inside a collapse panel with nzAutosize and extra long string assigned to ngModel. Will not resize itself to multi rows on load. Works fine if the textarea positioned outside of collapse panel

### What is expected?
Will resize to accommodate the string

### What is actually happening?
Stays as one row textarea with scroll bar

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
has been fixed after upgrade to ivy in angular 9
closing now
