### ISSUE TITLE
nz-table sorts descending by default

### ISSUE THREAD

**Issue by tmccurdy** [NG-ZORRO/ng-zorro-antd#3398]
### Reproduction link
[https://angular-s4nyi3.stackblitz.io](https://angular-s4nyi3.stackblitz.io)

### Steps to reproduce
* Add nztable and make it sortable
* Sort an "unsorted" column

### What is expected?
Column should sort "ascending" by default when it does not have a sort order already set.
Or (optionally), provide a setting to control the default sort-order direction of the table.

### What is actually happening?
Column sorts "descending" by default.  No other site or behavior in the world sorts descending first.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | all |

**Comment by vthinkxie** [comment]
could this demo meet your expect?
https://ng.ant.design/components/table/en#components-table-demo-reset-filter

**Comment by Doc999tor** [comment]
@vthinkxie How can I set default sorting direction on the first click on non-sorted column? 
For now it starts to sort from ascending like you changed but can I revert it back and to sort descending by default?
