### ISSUE TITLE
Make <nz-root> component optional

### ISSUE THREAD

**Issue by trotyl** [NG-ZORRO/ng-zorro-antd#34]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

As suggested in doc, `<nz-root>` component must be listed at outermost layer of the app, which seems inconvenient for user.

#### High-level goal:

Do not require `<nz-root>` in component template.

#### Detailed design:

- [x] Add optional configuration param in `forRoot()` method.
- [x] Introduce a separate `InjectionToken` for that configuration param.
- [x] Use a dynamic component to apply global styles.
- [x] Use a `APP_INITIALIZER` to apply font styles.

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by nikhilbangre** [comment]
when **nzDrawerService** Release.
