### ISSUE TITLE
Hope that Autocomplete component could support append mode

### ISSUE THREAD

**Issue by tangjwt** [NG-ZORRO/ng-zorro-antd#3401]
## What problem does this feature solve?
The current autocomplete will overwrite all current content every time it is selected,  when use autocomplete on textarea, We usually want content to be appended instead of overwriting. 
Or you can add an event where the autcomptele option is selected so that we can customize the behavior.

## What does the proposed API look like?
<nz-autocomplete [mode]="'append'" #auto>
      <nz-auto-option *ngFor="let option of fields" [nzValue]="option.value">{{ option.label }}<\/nz-auto-option>
  <\/nz-autocomplete>

or

<nz-autocomplete (nzSelect)="updateValue($event)" #auto>
      <nz-auto-option *ngFor="let option of fields" [nzValue]="option.value">{{ option.label }}<\/nz-auto-option>
  <\/nz-autocomplete>

$event content is nz-auto-option

**Comment by hsuanxyz** [comment]
@tangjwt  You can do this like

```ts
options = [... options, ...appendOptions]
/** or */
options = options.concat(appendOptions)
```

**Comment by tangjwt** [comment]
> @tangjwt You can do this like
> 
> ```ts
> options = [... options, ...appendOptions]
> /** or */
> options = options.concat(appendOptions)
> ``` 

I don't want append options,  I want append selected content. 
For example: 
I have options=[1,2,3,4,5],  first time, I select 1, second time I select 2,  I want the textarea show 1\n2 instead of 2.
