### ISSUE TITLE
nz-upload doesn't refresh when 'nzFileList' is updated

### ISSUE THREAD

**Issue by tky753** [NG-ZORRO/ng-zorro-antd#3409]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-jmxqmj?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-jmxqmj?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
1. open console
2. click add button
3. you can see 'fileList' is updated, but the nz-upload control doesn't refresh.

### What is expected?
 nz-upload component automatically refresh after clicking the add button.

### What is actually happening?
nothing happen

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | 版本 73.0.3683.103（正式版本） （64 位） |

**Comment by cipchk** [comment]
I think you need this: https://ng.ant.design/components/table/en#note

**Comment by tky753** [comment]
THX, that works for me.
