### ISSUE TITLE
引入ng-zorro-antd后，全局样式冲突。

### ISSUE THREAD

**Issue by wjtGitHub** [NG-ZORRO/ng-zorro-antd#341]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[*] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

引入ng-zorro-antd后全局样式冲突
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { NgZorroAntdModule } from 'ng-zorro-antd';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    NgZorroAntdModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
## Expected behavior

样式全部加载到style标签里面。无法提取到css里面，无法重写覆盖样式

## Environment

<pre><code>
Angular version: 4.2.4

ng-zorro-antd version: 0.5.1

Browser:
- [ *] Chrome (desktop) version new
- [ *] Firefox version new
- [ *] Safari (desktop) version new
- [ *] IE version new
 
For Tooling issues:
- Node version:6.10.2  
- Platform:  

Others:

</code></pre>

**Comment by zy-dreamer** [comment]
<img width="346" alt="wx20170920-180109 2x" src="https://user-images.githubusercontent.com/25117663/30638355-be81d8e6-9e2d-11e7-820e-528270dd111f.png">
This is my desperation solution.If you have a better solution,please tell me🤦🏻‍♂️

**Comment by vthinkxie** [comment]
duplicated #202 , you can just overwrite all style over your css file.

**Comment by wjtGitHub** [comment]
@zy-dreamer @vthinkxie 请注意，zorro的样式再webpack下会放到页面的style标签下，我重写的样式再css下面。优先级导致我覆盖不到。有什么方法可以将zorro的样式提取出来嘛？

**Comment by vthinkxie** [comment]
@wjtGitHub 
All ant style are css in js, the style will only work when you import zorro module, and css file can not import separated with current design.

**Comment by wjtGitHub** [comment]
在生产环境下，必须把css抽离于js，但是，antd的样式始终在style标签下，导致我重写的样式无法覆盖antd的样式。何解？@vthinkxie

**Comment by vthinkxie** [comment]
@wjtGitHub you can overwrite all style like @zy-dreamer .

**Comment by wjtGitHub** [comment]
像下图的样式，我无论如何也重写不掉
![image](https://user-images.githubusercontent.com/17404628/30676745-3429d1c0-9eba-11e7-9da5-e793d42e6492.png)
因为我重写得样式再css里面，而antd的在style里面

**Comment by vthinkxie** [comment]
@wjtGitHub use important

**Comment by wjtGitHub** [comment]
@vthinkxie 我不认为这是一个好的办法，我觉得zorro应该改进这部分。非常感谢你的解答，我心里已经有谱了。

**Comment by zy-dreamer** [comment]
https://github.com/ant-design/ant-design/issues/4331
@wjtGitHub

**Comment by vthinkxie** [comment]
@wjtGitHub it is a trade-off, it is impossible to support both style lazy load and style customization.

**Comment by wjtGitHub** [comment]
@zy-dreamer 谢谢

**Comment by wjtGitHub** [comment]
不支持样式定制就无法满足产品的UI需求 @vthinkxie
