### ISSUE TITLE
7.3.2 Table with encapsulated customer filter component and sort

### ISSUE THREAD

**Issue by kiyonlin** [NG-ZORRO/ng-zorro-antd#3418]
### Reproduction link
[stackblitz](https://stackblitz.com/edit/angular-3huaun-rtcmot)

### Steps to reproduce
run the stackblitz

### What is expected?
customer filter icon is after sort icon

### What is actually happening?
customer filter icon is not in the order

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.2 |
| Browser | Version 73.0.3683.103 (Official Build) (64-bit) |

**Comment by wenqi73** [comment]
This bug has been fixed by [7.3.3](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CHANGELOG.md#733-2019-04-25)
