### ISSUE TITLE
virtual scroll table no data display error

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#3419]

**Comment by shuizhongxiong** [comment]
您好，我也遇到这个问题了，在 loading 或者 empty 状态时，virtual 的高度会把他们挤下去。请问这个会随着下次发版修复么？

**Comment by lppedd** [comment]
@vthinkxie @shuizhongxiong I think I have a similar problem. Could you describe the issue a little bit better?

**Comment by shuizhongxiong** [comment]
看了一下 cdk scrolling，发现他们也是不支持动态高度的，想到了一个方案，就是在视图渲染完后将 cdk view 定位到页面外面，等有数据的时候再去掉定位。

写了一个 [demo](https://stackblitz.com/edit/angular-r7snrw)，实现了虚拟滚动+分页加载。

但这只是一个暂时的解决办法，期待能有更好的方案。
