### ISSUE TITLE
nz-table不能设置nzData?

### ISSUE THREAD

**Issue by ANGULAR-X** [NG-ZORRO/ng-zorro-antd#3427]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-xkvisa](https://stackblitz.com/edit/ng-zorro-antd-start-xkvisa)

### Steps to reproduce
在ngOnit中手动通过引用设置nzData无效。

### What is expected?
能动态设置nzData及其他属性

### What is actually happening?
现在没找到方法设置

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | google |

**Comment by vthinkxie** [comment]
请参考官网使用规范

**Comment by ANGULAR-X** [comment]
你看了我发的代码链接吗？我要这样使用的原因是因为要批量设置nz-table属性。而不是一个个nz-table去设置。
