### ISSUE TITLE
二次封装nz-table组件，通过引用不能批量设置属性nzData。

### ISSUE THREAD

**Issue by ANGULAR-X** [NG-ZORRO/ng-zorro-antd#3428]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-xkvisa](https://stackblitz.com/edit/ng-zorro-antd-start-xkvisa)

### Steps to reproduce
见代码链接

### What is expected?
能通过引用批量设置nzData属性。

### What is actually happening?
暂时不能

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | google |

**Comment by ANGULAR-X** [comment]
1.8版本是可以这样使用的，升级到v7版本就不能使用了。希望能兼容。

**Comment by ANGULAR-X** [comment]
这样批量设置nzData，在项目中可以封装起来使用，而不是挨个nz-table去写nzData属性。在1.8版本是可以这样设置（代码链接），好奇升级到v7版本就不行了

**Comment by vthinkxie** [comment]
参考 angular 官网的 OnPush 部分
