### ISSUE TITLE
nz-modal去掉遮罩后扔无法操作下层

### ISSUE THREAD

**Issue by tian38304** [NG-ZORRO/ng-zorro-antd#3433]
## What problem does this feature solve?
![nz-modal遮罩问题](https://user-images.githubusercontent.com/50472404/57499423-33f7e380-7312-11e9-9f00-92f95148cd71.png)
红色框就是框架自带的一层背景，遮罩层是另一个标签，我已经取消掉了。现在是这层dialog挡着，我不能在modal打开的状态下操作下面地图。怎么解决

## What does the proposed API look like?
希望nz-modal是一个像windows窗口一样可移动并且不影响其它操作的窗口

**Comment by hsuanxyz** [comment]
@tian38304 组件模式(`<nz-modal>`)下 modal 是通过样式隐藏，无法保证其样式不与其他库冲突，如果你希望彻底关闭 modal 请该用服务(`NzModalService`)的方式。

**Comment by tian38304** [comment]
@hsuanxyz 我希望的是，在窗口打开的状态下，仍能操作地图。但现在的情况是有一层div挡住了，这个div时框架里自带的吧，我不知道怎么处理，才能在modal开着的情况下还能操作地图

**Comment by tian38304** [comment]
@hsuanxyz 截图中，黄色框是modal标签，其下的红框是描述的div，它占了全屏。蓝色的是实际的弹窗。现在的情况是红色这层挡住了全屏，导致无法操作下面的地图，而红色这层是属于modal的

**Comment by hsuanxyz** [comment]
@tian38304 Modal 不支持这样的设置，建议你使用 CDK overlay 定制你的需求 https://material.angular.io/cdk/overlay/overview

**Comment by tian38304** [comment]
@hsuanxyz 好的谢谢，我暂时用notification代替了，这个组件不会有遮罩情况，你的建议我会学习一哈的
