### ISSUE TITLE
TreeSelect performance is poor when there's a lot of data，feel the distinct caton

### ISSUE THREAD

**Issue by zomixi** [NG-ZORRO/ng-zorro-antd#3436]
### Reproduction link
[https://stackblitz.com/edit/angular-hqejv4](https://stackblitz.com/edit/angular-hqejv4)

### Steps to reproduce
open the treeSelect or close the  treeSelect 

### What is expected?
good performance

### What is actually happening?
poor performance

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | Google Chrome  74.0.3729.131（正式版本） （64 位） |

**Comment by avin-kavish** [comment]
What do you mean by 

> caton

?

**Comment by zomixi** [comment]
> What do you mean by
> 
> > caton
> 
> ?

not smooth，frame rate is too low
