### ISSUE TITLE
nz-menu多次选择后，样式问题。（垂直菜单和菜单收起状态都存在此问题）

### ISSUE THREAD

**Issue by zhhhc** [NG-ZORRO/ng-zorro-antd#3438]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
官网例子中的垂直菜单为例（请忽略重现链接）
https://ng.ant.design/components/menu/zh#components-menu-demo-vertical
1. 选择Navigation One的Option
2. 选择Navigation Two的Option
3. 选择Navigation Three的Option
...
 多次选择后，样式显示不正确。多个菜单显示被选中的状态。

### What is expected?
选择一个菜单后，之前菜单的显示为未选中样式。

### What is actually happening?
之前选中的菜单依然显示选中的样式。

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | Chrome |

**Comment by wenqi73** [comment]
Duplicate of #3434

**Comment by wenqi73** [comment]
Fixed by #3455
