### ISSUE TITLE
Implement a new module for Modal.

### ISSUE THREAD

**Issue by wilsoncook** [NG-ZORRO/ng-zorro-antd#344]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

The code of nz-modal is far more redundant with inconveniences and bugs.

## Expected behavior

I'm about to implement a new modal that is easy-using and refreshing, may name "nzx-modal"

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
close duplicated #644
