### ISSUE TITLE
nz-select 组件支持可选择、可搜索、可输入，下拉值提供单例选择

### ISSUE THREAD

**Issue by lihuabest** [NG-ZORRO/ng-zorro-antd#3447]
## What problem does this feature solve?
第一个目前组件的可选择、可搜索、可输入可以完成需求，但就是比较绕。我这边是放开了多选，但是选择数最大为1，可以输入并且选择确定输入项。
第二个是下拉值都是独立的，但是有些列表选择下拉业务里，下拉值可能来自同一个对象置，并且彼此之间选的值是互斥的，也就是下拉值是单例的，我们自己定义的组件就是新增了一个[single]="true"来表示单例，组件内部对下拉值不进行深度拷贝，而是直接引用。怎么实现都可以，只要可以实现互斥选择。
## What does the proposed API look like?
自定义吧

**Comment by vthinkxie** [comment]
autocomplete?
