### ISSUE TITLE
nz-select隐藏已选择选项, 无法回显默认选中

### ISSUE THREAD

**Issue by app2smile** [NG-ZORRO/ng-zorro-antd#3449]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ra5h6i](https://stackblitz.com/edit/ng-zorro-antd-start-ra5h6i)

### Steps to reproduce
1.粘贴组件nz-select中的 隐藏已选择选项 示例代码
2.更改其中的listOfSelectedValue选中值

### What is expected?
组件加载的时候 select框能够展示默认选中项

### What is actually happening?
select框没有展示默认选中项

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | chrome74.0.3729.131 |

**Comment by wenqi73** [comment]
因为你用了 `*ngIf`, `listOfSelectedValue` 找不到对应的 option。

**Comment by vthinkxie** [comment]
设计就是这样，初始值不在 nz-option 中的数据，是无法被选中的，组件需要根据 nz-option 中的 label 值进行显示，你现在的组件初始只有value，而option又没有与之匹配的value，所以不会有任何label能够显示出来
