### ISSUE TITLE
在 ng-zorro-antd 中 TreeSelect树选择 的 树结点中数据中的 表示结点是否为 叶子结点的 isLeaf 字段 如果是 java 来做后台 则 违背了 《阿里巴巴Java开发手册（详尽版）.pdf》第一章第一节第八点 关于 JavaBean 中 对 boolean 值的规定

### ISSUE THREAD

**Issue by chenq-cc** [NG-ZORRO/ng-zorro-antd#3454]
### Reproduction link
[https://stackblitz.com/edit/angular-tfvr23](https://stackblitz.com/edit/angular-tfvr23)

### Steps to reproduce
在 ng-zorro-antd 中 TreeSelect树选择 中
当JAVA 做为后台 并且 后台返回树结构时，对于 isLeaf(标识结点是否为叶子结点的字段名) 是和 《阿里巴巴Java开发手册（详尽版）.pdf》相冲突的

### What is expected?
booean 字段无 is前缀

### What is actually happening?
booean 字段有 is前缀

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.3.3 |
| Browser | all |

**Comment by chenq-cc** [comment]
![image](https://user-images.githubusercontent.com/23652100/57845402-85b5d780-7804-11e9-8783-41a6c52918ec.png)

**Comment by zombieJ** [comment]
手册中不推荐使用 isXxx 是因为部分 Java 框架会将 isXxx 对应成属性 `xxx`，从而导致属性匹配失败的问题。

JavaScript 作为弱类型语言，可以直接设置属性而不用关心类型：
```js
entity[propName] = whateverTypeValue;
```

对于 getter / setter 也与 java 不同，可以做到无感知：
```js
Object.defineProperty(entity, 'propName', {
  get() { ... },
  set(val) { ... }
});

entity[propName] = whateverTypeValue;
```

JS 中不会遇到 java 的序列化问题，因而也不会严格要求是否使用 `is` 作为前缀。

反过来，JS 中有一些规范，在 Java 中也同样不适用。例如判断是否相等需要用 `===` 而不是 `==`、`null` `undefined` `delete` 不推荐作为属性名等等。根据语言选择适合的规范就行了。

**Comment by vthinkxie** [comment]
转换只需要一句javascript代码
```js
const listOfSampleData = [{leaf:true,data:1000},{leaf:false,data:100}];
const listOfConvertData = listOfSampleData.map(item=>{return{...item,isLeaf:item.leaf}});
```

**Comment by chenq-cc** [comment]
> 如果后端返回的数据不符合你的需求，转换只需要一句的JavaScript代码
> 
> ```js
> const  listOfSampleData  = [{leaf ：true，data ：1000 }，{leaf ：false，data ：100 }];
> const  listOfConvertData  =  listOfSampleData。地图（项=> { 返回 { ...项，isLeaf ：项目。叶 }}）;
> ```



> 如果后端返回的数据不符合你的需求，转换只需要一句javascript代码
> 
> ```js
> const listOfSampleData = [{leaf:true,data:1000},{leaf:false,data:100}];
> const listOfConvertData = listOfSampleData.map(item=>{return{...item,isLeaf:item.leaf}});
> ```

我知道这种可以，但是 这种操作是需要map一次，也就是遍历一次数据的，对于设计来说这些都是可以避免的。

**Comment by chenq-cc** [comment]
> 手册中不推荐使用 isXxx 是因为部分 Java 框架会将 isXxx 对应成属性 `xxx`，从而导致属性匹配失败的问题。
> 
> JavaScript 作为弱类型语言，可以直接设置属性而不用关心类型：
> 
> ```js
> entity[propName] = whateverTypeValue;
> ```
> 
> 对于 getter / setter 也与 java 不同，可以做到无感知：
> 
> ```js
> Object.defineProperty(entity, 'propName', {
>   get() { ... },
>   set(val) { ... }
> });
> 
> entity[propName] = whateverTypeValue;
> ```
> 
> JS 中不会遇到 java 的序列化问题，因而也不会严格要求是否使用 `is` 作为前缀。
> 
> 反过来，JS 中有一些规范，在 Java 中也同样不适用。例如判断是否相等需要用 `===` 而不是 `==`、`null` `undefined` `delete` 不推荐作为属性名等等。根据语言选择适合的规范就行了。

确实JS 是没必要强制要求这个，但是个人觉得，为了适配不同的规则应该可以自定义传入的数据的属性名，比如可以指定另外一个名字来作为isLeaf的替代品
