### ISSUE TITLE
Rename nzTitle based on the directive

### ISSUE THREAD

**Issue by Supamiu** [NG-ZORRO/ng-zorro-antd#3456]
## What problem does this feature solve?
Having nz-tooltip, nz-popconfirm and nz-popover on the same component makes some behaviors impossible because both of them use the same input for the title: `nzTitle`.

This means that if you want to create a button that has a tooltip and a popover on click, you won't be able to show a tooltip at all.
## What does the proposed API look like?
Use `nzPopoverTitle`, `nzPopConfirmTitle` and `nzTooltipTitle` as optional second input, with an implicit setter in order to map these to the effective input value and minimize the impact of this change while providing a way to solve this issue.

I'm not sure these are the only directives that should be modified, but they are the ones I spotted so far.

**Comment by wenqi73** [comment]
Ref #3448

**Comment by Supamiu** [comment]
@wenqi73 I edited the issue to add popconfirm to it, might be worth one more label :)

**Comment by avin-kavish** [comment]
This behaviour can already by achieved. I think renaming directives is a breaking change and should not be done especially when it is already working. Check this [StackBlitz](https://stackblitz.com/edit/ng-zorro-antd-start-xnubbi?file=src%2Fapp%2Fapp.component.html) for a working example
```
<span nz-popover nzTitle="Popover" nzContent="Content">
    <span nz-tooltip nzTitle="This is a button" >
       <button nz-button nz-popconfirm nzTitle="Are you sure to press this button?" >
          Button
       </button>
    </span>
</span>

**Comment by wendzhue** [comment]
@Supamiu you can use @avin-kavish 's code as a temporary solution. We are trying to make the the directive's name as an input to make the code more readable.

**Comment by hsuanxyz** [comment]
https://github.com/angular/components/blob/master/src/material/tooltip/tooltip.ts#L171

```ts
@Input('nzPopconfirmTitle') nzTitle;
@Input('nzPopoverTitle') nzTitle;
@Input('nzTooltipTitle') nzTitle;
```

**Comment by HalfLegend** [comment]
Further more, the property of `nzTitle` is not needed at all. 
We can use `nzTooltip = XXX` directly and this would be more concise.
Please **remove** the property `nzTitle` or mark `nzTiltle` as not preferred

**Comment by HalfLegend** [comment]
What am I really concerned about is the property of nzContent, nzPlacement, etc.
They all come from a directive instead of the element itself. 
The name of the properties should indicate the source of the property even if there is no conflict.
This would make the code using "ng-zorro-antd"  more readable.

**Comment by wendzhue** [comment]
![image](https://user-images.githubusercontent.com/12122021/62610597-9161f780-b936-11e9-9ea6-a7c32f54a1be.png)

:tada:
