### ISSUE TITLE
Select component, a function that needs a hover display name

### ISSUE THREAD

**Issue by gb853940223** [NG-ZORRO/ng-zorro-antd#3464]
## What problem does this feature solve?
1, if select, the name of each option is very long, and the ellipsis is displayed, you can not see the full name, add the mouse hover function, you can solve this problem
2, sometimes, the select component, each option shows a name, when the mouse hover, you need to display another name

## What does the proposed API look like?
Added a nzTip attribute to debug the copy of the mouse hover. In fact, in my local development, I have made this change.

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-wd5zm8?file=src/app/app.component.ts
nz
you can use `nzCustomContent` to define the option template 
https://ng.ant.design/components/select/zh#components-select-demo-custom-content
