### ISSUE TITLE
Table组件能否支持直接树形数据？ 

### ISSUE THREAD

**Issue by lyuan520** [NG-ZORRO/ng-zorro-antd#3468]
## What problem does this feature solve?
不需要再做额外的数据处理。现在的示例里面会数据再做一遍处理： convertTreeToList(root: object): TreeNodeInterface[] 

## What does the proposed API look like?
像Vue/React for antd 的Table树形数据展示一样， 直接赋值就可以显示。

**Comment by zhang8043** [comment]
按照示例里面的使用convertTreeToList 处理数据会造成页面卡顿，效率太低。

**Comment by vthinkxie** [comment]
Table组件的实现是弱封装，所有的td和tr由用户控制，如果不想要每次都convert，完全可以自己在nz-table上封装一个组件使用。
