### ISSUE TITLE
TreeSelect在form表单中设置异步取数，如何设置默认值，包括显示文本（麻烦看看急需）

### ISSUE THREAD

**Issue by Cyclone77** [NG-ZORRO/ng-zorro-antd#3471]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-tree-select?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-tree-select?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
tree-select 组件异步加载数据还没执行如何设置默认值，设置显示文本？

### What is expected?
添加属性或者方法实现设置文本和值

### What is actually happening?
通过 expandKeys = ['0-0'];并不能设置文本

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.0 |
| Browser | google最新 |

---
https://github.com/NG-ZORRO/ng-zorro-antd/issues/1934  
以上并没有解决这个问题
另外如何添加异步加载自定义搜索框在下拉树的顶部。

**Comment by wenqi73** [comment]
```ts
this.personalForm = new FormGroup({
  type: new FormControl('')
});
```
请仔细阅读 angular 文档

**Comment by Cyclone77** [comment]
@wenqi73 设置值没有用呢，这个tree-select节点是异步加载的，设置了值树选择框的文本还是空的。

**Comment by wenqi73** [comment]
[https://stackblitz.com/edit/ng-zorro-antd-tree-select-dnrssn](https://stackblitz.com/edit/ng-zorro-antd-tree-select-dnrssn) 你应该是想要这种效果？

**Comment by Cyclone77** [comment]
@wenqi73 Demo和实际需求差太多了，比如我这里加载的是中国所有地区（点击的时候是分层加载的），而且我页面上有很多个tree-select，并不能进去就全部初始化完。所以我才使用了nzOpenChange

**Comment by simplejason** [comment]
是否可以把确定选中的节点加到显示列表中，异步加载时过滤掉（避免重复）

> @wenqi73 Demo和实际需求差太多了，比如我这里加载的是中国所有地区（点击的时候是分层加载的），而且我页面上有很多个tree-select，并不能进去就全部初始化完。所以我才使用了nzOpenChange，避免页面卡死，实际需求的字段有100+个

**Comment by Cyclone77** [comment]
> 是否可以把确定选中的节点加到显示列表中，异步加载时过滤掉（避免重复）
> 
> > @wenqi73 Demo和实际需求差太多了，比如我这里加载的是中国所有地区（点击的时候是分层加载的），而且我页面上有很多个tree-select，并不能进去就全部初始化完。所以我才使用了nzOpenChange，避免页面卡死，实际需求的字段有100+个

这样也可以，多一步构造临时节点，其实我只想要一个setText()的方法或者标签来设置文本这样最好。

**Comment by simplejason** [comment]
建议可以将待选中的节点追加到默认的数组里去，这样可以保证初始化时能匹配到数据，在异步加载新数据时过滤掉这条（自行判断包含关系），先按这种方式解决应该能完成你当前需求，具体是否支持默认值和文本还得讨论一下

**Comment by Cyclone77** [comment]
通过构造默认值的节点实现了，问题就在于，这个默认值节点也许是某个节点的子节点，这样在点击的时候还要清理后重新构选项树的层。

**Comment by simplejason** [comment]
这种多级模式（尤其是地区）我觉得级联组件更适合展示上下级关系，tree组件更多的是节点状态，而不存在上下级关联关系

**Comment by Cyclone77** [comment]
当然我只是举例，这个用的还是很广泛，多数情况级联组件并不能胜任tree-select的优势，比如选择并非最后一层，节点展开可以比较后选择。

**Comment by Cyclone77** [comment]
@wenqi73 @simplejason  请问一下我提前设置了[nzNodes]为什么点击下拉tree的选择框加载的还是很慢，就是地区树大概4000个节点？

**Comment by Cyclone77** [comment]
@wenqi73 麻烦重新开启一下issues，谢谢

**Comment by Cyclone77** [comment]
我通过调试源码发现：
![20190522101458](https://user-images.githubusercontent.com/10395760/58142713-c1c0c080-7c7a-11e9-8741-02d0b8870d7a.png)
更新位置耗时较为严重。

**Comment by wenqi73** [comment]
TreeSelect 性能问题请参考 #3436

**Comment by Cyclone77** [comment]
@wenqi73 并没有解决如何参考？
