### ISSUE TITLE
按钮在加载状态仍然可以点击

### ISSUE THREAD

**Issue by runningxiao** [NG-ZORRO/ng-zorro-antd#3479]
### Reproduction link
[https://ng-zorro-antd-start-5ujzdw.stackblitz.io](https://ng-zorro-antd-start-5ujzdw.stackblitz.io)

### Steps to reproduce
两个按钮，一个button的文本为空只有i标签，loading状态下可以继续点击，一个button有文本信息，在loading状态下无法继续点击

### What is expected?
按钮在loading状态下无法点击

### What is actually happening?
button在文本为空的时候，loading状态下仍然可以继续点击

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.1.0 |
| Browser | 谷歌 |

**Comment by hsuanxyz** [comment]
@runningxiao 会在下次合并样式时修复

https://github.com/NG-ZORRO/ng-zorro-antd/pull/3465/files#diff-68de505498c369b48fe255de576fa18eR114
