### ISSUE TITLE
nz-table: cannot remain previous pageindex when dataSource changes

### ISSUE THREAD

**Issue by AlcheXie** [NG-ZORRO/ng-zorro-antd#348]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
PageIndex will be 1 because forceRefresh is true when dataSource changes.

## Expected behavior

I can decide if pageIndex is 1 or value before dataSource changes (like **_buildIndexes()** in nz-pagination.component.ts).

**Comment by vthinkxie** [comment]
Yes, pr is welcome, just add `nzPageSizeReset=true` option, and replace `this._generateData(true)` to `this._generateData(this.nzPageSizeReset)` will be ok.
