### ISSUE TITLE
Responsive nz-header

### ISSUE THREAD

**Issue by mavortius** [NG-ZORRO/ng-zorro-antd#3486]
## What problem does this feature solve?
nz-header is not responsive.
## What does the proposed API look like?
Add options like nzBreakpoint and nzCollapsed as nz-sider has.

**Comment by wendzhue** [comment]
@mavortius Can you describe how you want `nz-header` to be responsive? Actually, it's just a `div` with proper margin.

**Comment by mavortius** [comment]
Actually, I mean the nz-menu component inside the nz-header. It would be nice if, when on mobile screen, the component was hidden and a button appeared to show it, with its possible items, similar to [Bootstrap navbar](https://getbootstrap.com/docs/4.2/components/navbar/).

**Comment by wendzhue** [comment]
@vthinkxie An event could be provided by the grid component so users could know when a breakpoint is hit.

**Comment by vthinkxie** [comment]
Hi @mavortius 
you can use https://material.angular.io/cdk/layout/api#BreakpointObserver to observe break point now
ant design does not support responsive header yet.
