### ISSUE TITLE
nz-modal button和a 的打开动画不一致

### ISSUE THREAD

**Issue by smartsoul** [NG-ZORRO/ng-zorro-antd#3489]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-9i4ypj](https://stackblitz.com/edit/ng-zorro-antd-start-9i4ypj)

### Steps to reproduce
nz-modal button和a 的打开动画不一致

### What is expected?
button和a 的打开动画一致，提供是否启用动画选项。一些重的modal会掉帧。

### What is actually happening?
button 的modal  是从按钮处缩放打开，a标签是从浏览器中间缩放打开

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.1 |
| Browser | Chrome 74.0.3729.169 |

**Comment by hsuanxyz** [comment]
@smartsoul https://ng.ant.design/docs/animations/zh#%E5%9C%A8%E6%9C%8D%E5%8A%A1%E4%B8%AD%E5%85%B3%E9%97%AD

**Comment by smartsoul** [comment]
@hsuanxyz 谢谢，看到关闭动画的选项了，但是有些场景是需要动画的，在7.2.0的时候，两者的动画是一致的。

**Comment by hsuanxyz** [comment]
@smartsoul 
缺少 `href` 属性的 `a` 标签无法聚焦，你可以指定 `tabindex` 属性 (`<a tabindex="-1">...</a>`)， 或者等待 #3503 合并后使用 `<button nz-button nzType="link">...</button>` 代替。

感谢反馈，如果还有什么问题欢迎重新发起 issue。
