### ISSUE TITLE
Can't use scope variables inside a popover/tooltip TemplateReference

### ISSUE THREAD

**Issue by javcode** [NG-ZORRO/ng-zorro-antd#3490]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-scmfqv](https://stackblitz.com/edit/ng-zorro-antd-start-scmfqv)

### Steps to reproduce
Create a tooltip inside an *ngFor and try to access the declared variable from inside the ng-template

### What is expected?
The scope variable should be accessible and rendered inside the ng-template used by the popover/tooltip

### What is actually happening?
The variable is undefined

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.1 |
| Browser | Chrome |

**Comment by wenqi73** [comment]
It is not a problem of ng-zorro, angular does not support this:
```html
<!-- Can not be rendered too -->
<div *ngFor="let item of items">
  <ng-container [ngTemplateOutlet]="popoverVarsContent"></ng-container>
</div>

<ng-template #popoverVarsContent>
  <p>Item: {{item | json}}</p>  
</ng-template>
```
You should create a new component and use `@Input`.

**Comment by hsuanxyz** [comment]
@javcode You can move `ng-template` to the loop body.

```html
<div *ngFor="let item of items">
  <ng-container [ngTemplateOutlet]="popoverVarsContent"></ng-container>
  <ng-template #popoverVarsContent>
    <p>Item: {{item | json}}</p>  
  </ng-template>
</div>
```

**Comment by javcode** [comment]
I've ended up creating a new Component taking the 'item' as an input as I wanted to be able to re-use this code as it's used in several places.

```javascript
export class ImportPopoverComponent implements OnInit {

  @Input()
  item:{}

  @Input()
  type:string

}
```

Now the new component html looks like:
```html
<a href="javascript:void(0)" nz-popover [nzContent]="popover">Add Item</a>

<ng-template #popover>
  <div>{{item}}</div>
</ng-template>
```

and I call it from the parent using:
```html
<app-import-popover [item]="item"></app-import-popover>
```

Thanks wenqi73 for the work-around

**Comment by wenqi73** [comment]
@hsuanxyz Yeah, Angular can use like this, another way is `context: {$implicit: item}`. I explained incorrectly before.

**Comment by wenqi73** [comment]
@javcode , @hsuanxyz 's work-around is more convenient.

**Comment by areeb-raza** [comment]
> @javcode You can move `ng-template` to the loop body.
> 
> ```
> <div *ngFor="let item of items">
>   <ng-container [ngTemplateOutlet]="popoverVarsContent"></ng-container>
>   <ng-template #popoverVarsContent>
>     <p>Item: {{item | json}}</p>  
>   </ng-template>
> </div>
> ```

Works like a charm.
