### ISSUE TITLE
日期组件 年份减小到负值

### ISSUE THREAD

**Issue by lihuabest** [NG-ZORRO/ng-zorro-antd#3495]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start ](https://stackblitz.com/edit/ng-zorro-antd-start )

### Steps to reproduce
日期组件，点击年份减小，可以一直点击到负值的年份，可能期望年份减小到1970年就ok啦

### What is expected?
年份减小到1970年

### What is actually happening?
一直可以点击减小到负值

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.1 |
| Browser | 任意 |

**Comment by wendzhue** [comment]
@lihuabest 重现链接无效
