### ISSUE TITLE
Request friendlier nz-table-sort and nz-table-filter

### ISSUE THREAD

**Issue by AlcheXie** [NG-ZORRO/ng-zorro-antd#350]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

Now **nz-table-sort** output only a string value of sort way, and **nz-table-filter** is provided as a content container. Maybe these two could be more convenient used.

## Expected behavior
1. **nz-table-sort:** input **fieldname** (string), sort data by executing method in **NzTableSortComponent** when **nzValueChange** is not defined.
2. **nz-table-filter:**: similar to nz-table-sort.

Maybe it's helpful when data is requested from remote server and network is not good.

**Comment by vthinkxie** [comment]
Thanks for your advice, but sort and filter function in table is indeed complex, it have to support both server and local sort and filter, I think it is better to make it simple, that all users can define their own strategy.

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed
