### ISSUE TITLE
select don't work when use chrome's translate

### ISSUE THREAD

**Issue by chriswangvv** [NG-ZORRO/ng-zorro-antd#3504]
### Steps to reproduce
just open https://ng.ant.design/components/select/zh this page and use translation of chrome, and u will find u can't 'select' your select component
简而言之就是当我们在网页中使用select组件时，如果用谷歌浏览器自带的翻译功能来进行翻译，那么这个select组件 可以下拉，但不能选择。

### What is expected?
we can use 'select' any condition

### What is actually happening?
we can't do 'select' action, unless we don't translate it again.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.1 |
| Browser | chrome 74.0.3729.169 |

**Comment by vthinkxie** [comment]
在谷歌翻译下绝大部分的组件库都是不能正常工作的，暂时不在我们的支持范围内
