### ISSUE TITLE
nzDatePicker: Second datepicker do not openafter selection if nzOpenChange 

### ISSUE THREAD

**Issue by chenxiangjun2010** [NG-ZORRO/ng-zorro-antd#3506]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io/](https://ng-zorro-antd-start.stackblitz.io/)
https://stackblitz.com/edit/ng-zorro-antd-start-s12lcp

### Steps to reproduce
点击开始时间选择器，选择时间后，结束时间选择器弹起，直接点ok按钮，弹窗关闭，在点击结束选择器，打不开选择弹窗，同理清除结束时间，也是打不开时间选择器的

### What is expected?
结束时间选择器，不管有没有值，都可以被打开

### What is actually happening?
结束时间选择器，没值，不可以被打开

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.1 |
| Browser | chrome |

**Comment by wenqi73** [comment]
使用了 `[nzOpen]="endOpen"` 后弹窗状态由 `endOpen` 来控制。

**Comment by chenxiangjun2010** [comment]
问题表面上是这样，可以通过endOpen控制，但是估计这么做的原因是，强制用户先选择开始时间再选择结束时间，因为假如先选择结束时间之后，那么开始时间的不可选日期就不对了，比如结束选择2019-6-18，那么开始时间只能选择2019-6-17之前，不能选择2019-6-18,

**Comment by wenqi73** [comment]
@chenxiangjun2010 已支持= `open()` `close()` 方法。#5777
