### ISSUE TITLE
table: 虚拟滚动闪烁回弹

### ISSUE THREAD

**Issue by margintopt** [NG-ZORRO/ng-zorro-antd#3509]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ouyjnz?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-ouyjnz?file=src/app/app.component.ts)

### Steps to reproduce
table中使用虚拟滚动 且有ngIf等判断 

### What is expected?
正常滚动

### What is actually happening?
table中ngIf越多 滚动闪烁情况越严重 甚至会出现无法向下滚动回弹的效果

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.1 |
| Browser | Google Chrome 74.0.3729.169（正式版本） （64 位） |

**Comment by vthinkxie** [comment]
你设定的       [nzVirtualItemSize]="65" ，但是明显每行高度不是65px，请仔细阅读文档
