### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by Svetomechc** [NG-ZORRO/ng-zorro-antd#3514]
## What problem does this feature solve?
Align the library with latest Angular release
## What does the proposed API look like?
[Not applicable]

**Comment by vthinkxie** [comment]
we will support angular 8 in next month

**Comment by ElderJames** [comment]
我升级了版本号，ng-zorro还是能跑起来。
不知道哪些地方会出兼容性问题？

**Comment by kunl** [comment]
@ElderJames  ivy 打包失败

**Comment by ElderJames** [comment]
发现ssr方式打包异常

**Comment by LitIce** [comment]
升级了ng8，普通打包能正常通过；
启用ivy时，打包失败

**Comment by hwangzhiming** [comment]
experimental support for Ivy, not yet ready for production

**Comment by krokofant** [comment]
So besides the *experimental* Ivy support Angular 8 works well with NgZorro?

**Comment by ningjn** [comment]
升级后，打包正常，运行会报错，null值操作，没找到原因，感觉应该是这个组件的原因，退回去了

**Comment by vthinkxie** [comment]
Hi, all
we will support angular 8 in late June, but ng-zorro-antd 8.0 may not support ivy because there are still some ivy issues blocked now
you can track it below
https://github.com/angular/angular-cli/issues/14594
https://github.com/angular/angular/issues/30080
https://github.com/angular/angular/issues/29361

**Comment by Svetomechc** [comment]
@vthinkxie this is quite okay with me since Ivy is still experimental ~~and breaks my app anyway~~

**Comment by vthinkxie** [comment]
We have released the `8.0.0-rc.0` version, anyone who has interest could test it now
This version not recommended to use in production env.

**Comment by krokofant** [comment]
@vthinkxie It seems that the rc releases are out on npm but not tagged or released on GitHub 😕

**Comment by vthinkxie** [comment]
@krokofant we will release stable version this week, and 8.0.0-rc.2 released yesterday
Some APIs will be deprecated in 8.0.0, but the old ones will still be supported before version 9.0.0.
It means that you may get some warning under dev environment, but it is compatible between 7.x and 8.x version.

**Comment by vthinkxie** [comment]
angular 8 supported
check the changelog for more information
https://ng.ant.design/docs/changelog/en

**Comment by Svetomechc** [comment]
@vthinkxie what is the ETA on 8.1.0?

**Comment by vthinkxie** [comment]
@Svetomechc will release 8.0.2 today

**Comment by Svetomechc** [comment]
@vthinkxie will it be targeting Angular 8.1.0?

**Comment by Svetomechc** [comment]
About Ivy:

@vthinkxie @hsuanxyz
https://github.com/angular/angular-cli/issues/14594 seems to be fixed now
https://github.com/angular/angular/issues/29361 can be worked around https://github.com/angular/angular/issues/29361#issuecomment-511094039
https://github.com/angular/angular/issues/30080 is the only real showstopper now I guess

**Comment by Svetomechc** [comment]
@vthinkxie, is 8.2.0 supported? Lots and lots of minor glitches on production build (debug is fine though, guess TypeScript there is less strict).

**Comment by wendzhue** [comment]
@Svetomechc We just upgrade to TypeScript 3.5.3 yesterday (UTC+8).
