### ISSUE TITLE
Tabs标签页 删除标签页后设置 nzSelectedIndex 失效

### ISSUE THREAD

**Issue by tomatoKnightJ** [NG-ZORRO/ng-zorro-antd#3519]
### Reproduction link
[https://stackblitz.com/edit/angular-fjn1aj](https://stackblitz.com/edit/angular-fjn1aj)

### Steps to reproduce
点击 Tab5 然后删除 Tab4

### What is expected?
tabs切换至最后一个

### What is actually happening?
未改变

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.1 |
| Browser | chrome 74.0.3729.131 |

**Comment by ZhiDanLuo** [comment]
看了你的 demo ，在 closeTab 方法中，你有对 index 重新赋值，造成了tabs切换至最后一个。@tomatoKnightJ

**Comment by tomatoKnightJ** [comment]
> 看了你的 demo ，在 closeTab 方法中，你有对 index 重新赋值，造成了 tabs 切换至最后一个。@tomatoKnightJ

需求就是关闭当前tab切换至最后一个tab，这个没问题，问题点在于不能每次正确指向最后一个tab；

**Comment by wendzhue** [comment]
@tomatoKnightJ Tabs 组件的下标是从 1 开始的

**Comment by ZhiDanLuo** [comment]
> > 看了你的 demo ，在 closeTab 方法中，你有对 index 重新赋值，造成了 tabs 切换至最后一个。@tomatoKnightJ
> 
> 需求就是关闭当前tab切换至最后一个tab，这个没问题，问题点在于不能每次正确指向最后一个tab；


ok 
tableClick 方法中不要对 index 重新赋值，在点击 tab 面板，会自动set nzSelectedIndex。
https://stackblitz.com/edit/angular-fjn1aj-r8v6vz

**Comment by hsuanxyz** [comment]
Any other questions are welcome to open a new issue.
