### ISSUE TITLE
Set type of NzTableComponent

### ISSUE THREAD

**Issue by MassimilianoOreto** [NG-ZORRO/ng-zorro-antd#3528]
## What problem does this feature solve?
If i can set the type of  NzTableComponent , when i change a field on interface of a table , the IDE give me the error that this field doesn't exist. At moment on PhpStorm underline the field (Unresolved variable)
## What does the proposed API look like?
Maybe like [nzType]="InterfaceName"

**Comment by vthinkxie** [comment]
this is not possible under the strict mode in typescript, plz read typescript doc to get more information
