### ISSUE TITLE
表格什么时候可以支持锁列呢

### ISSUE THREAD

**Issue by hdhxby** [NG-ZORRO/ng-zorro-antd#353]
麻烦问下,表格什么时候可以支持锁列呢,大量使用表格的业务系统对这块很看重.

**Comment by vthinkxie** [comment]
I have to say it is really hard to support locked column without bringing break changes, it is under discussing now.

**Comment by LinBoLen** [comment]
is that freeze column?

**Comment by hdhxby** [comment]
@vthinkxie Tanks.
@LinBoLen  Yes.

**Comment by Turkyden** [comment]
How can I fix the first column?In my project, there are so many tables and grids, which is too wide to rander scollBar in my Browser.So, I wanna fix the first column when I slide the scorllbar.Thank you!

**Comment by LinBoLen** [comment]
NG-ZORRO is an influence project made with angular. and I want to make it better so others can benefit from it.

My concern is lots about table component. which is so important in ria. tables/sheet/grids implemented with jquery or others framework is various. later I will bring all out

Create an advance table is not easy. freeze column is part of features. but is not the core feature of the advance table.

- first, talk about table cell calculate. if use table as the basic structure of the advance table. the most position of a cell will be calculated by chrome's c++. but it hard to handle table, is it?
table in table in table ..., nope, I hate it.
- second, use flex and grid class to arrange it. I have not investigated it.
- third, all of the table cells be calculated by js. we can control everything. so I can implement freeze column

The advance table feature is still in discussion in w3c standard.

btw. there is a narrow gap between advance table and sheet.

I will show a few of famous table implements later.

**Comment by LinBoLen** [comment]
# ADVANCE DATATABLE

## Simple Structure 

I will not reduce the attribute of the html. because this  attribute is the real use case.

### data-table

```html
<table id="example" 
       class="display nowrap dataTable dtr-inline" 
       cellspacing="0" 
       width="100%" 
       role="grid" 
       aria-describedby="example_info" 
       style="width: 100%;">
    <thead>
    <tr role="row">
        <th class="sorting_asc"
            tabindex="0"
            aria-controls="example"
            rowspan="1"
            colspan="1"
            aria-label="Name: activate to sort column descending"
            style="width: 137px;"
            aria-sort="ascending">Name</th>
        <th class="sorting"
            tabindex="0"
            aria-controls="example"
            rowspan="1"
            colspan="1"
            aria-label="Position: activate to sort column ascending"
            style="width: 214px;">Position</th>
        <th class="sorting"
            tabindex="0"
            aria-controls="example"
            rowspan="1"
            colspan="1"
            aria-label="Office: activate to sort column ascending"
            style="width: 103px;">Office</th>
        <th class="dt-body-right sorting"
            tabindex="0"
            aria-controls="example"
            rowspan="1"
            colspan="1"
            aria-label="Age: activate to sort column ascending"
            style="width: 41px;">Age</th>
        <th class="sorting"
            tabindex="0"
            aria-controls="example"
            rowspan="1"
            colspan="1"
            aria-label="Start date: activate to sort column ascending"
            style="width: 92px;">Start date</th>
        <th class="dt-body-right sorting"
            tabindex="0"
            aria-controls="example"
            rowspan="1"
            colspan="1"
            aria-label="Salary: activate to sort column ascending"
            style="width: 80px;">Salary</th>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <th rowspan="1" colspan="1">Name</th>
        <th rowspan="1" colspan="1">Position</th>
        <th rowspan="1" colspan="1">Office</th>
        <th class="dt-body-right" rowspan="1" colspan="1">Age</th>
        <th rowspan="1" colspan="1">Start date</th>
        <th class="dt-body-right" rowspan="1" colspan="1">Salary</th>
    </tr>
    </tfoot>
    <tbody>
    <tr role="row" class="odd">
        <td class="sorting_1">Airi Satou</td>
        <td class="">Accountant</td>
        <td class="">Tokyo</td>
        <td class="dt-body-right">33</td>
        <td class="">2008/11/28</td>
        <td class="dt-body-right">$162,700</td>
    </tr>
    <tr role="row" class="even">
        <td class="sorting_1">Angelica Ramos</td>
        <td class="">Chief Executive Officer (CEO)</td>
        <td class="">London</td>
        <td class="dt-body-right">47</td>
        <td class="">2009/10/09</td>
        <td class="dt-body-right">$1,200,000</td>
    </tr>
    </tbody>
</table>
```

[CODE PEN](https://codepen.io/anon/pen/Yrdxjm)

### Kendo

[Plunkr](http://plnkr.co/edit/3Pgwkrqm2KWdHeTNCqUw?p=preview)

### devexpress

[CODE PEN](https://codepen.io/anon/pen/yzGzRw)

### wijmo

simplify

```
<div id="gridDefault" class="wj-control wj-flexgrid wj-content">
    <div style="position:relative;width:100%;height:100%;overflow:hidden;max-width:inherit;max-height:inherit">
    	 <div wj-part="root">
    	 	<div cells>
    	 		<div row>
    	 			<div cell />
    	 		</div>
            </div>
    	 </div>
    	 <div wj-part="top-left">
    	 	<div cells>
    	 		<div row>
    	 			<div cell />
    	 		</div>
            </div>
    	 </div>
    	 <div wj-part="column-header">
    	 	<div cells>
    	 		<div row>
    	 			<div cell />
    	 		</div>
            </div>
    	 </div>
    	 <div wj-part="row-header">
    	 	<div cells>
    	 		<div row>
    	 			<div cell />
    	 		</div>
            </div>
    	 </div>
    </div>
</div>
```

[Jsfiddle](http://jsfiddle.net/Wijmo5/bwdea8y3)



## Row grouping

in table structure, use a `<tr>`  take whole row with setting colspan equal max span

### data-table

```html
<tbody>
  <tr class="group"><td colspan="5">Edinburgh</td></tr>
  <tr role="row" class="odd">
        <td class="sorting_1">Airi Satou</td>
        <td class="">Accountant</td>
        <td class="">Tokyo</td>
        <td class="dt-body-right">33</td>
        <td class="">2008/11/28</td>
        <td class="dt-body-right">$162,700</td>
    </tr>
    <tr role="row" class="even">
        <td class="sorting_1">Angelica Ramos</td>
        <td class="">Chief Executive Officer (CEO)</td>
        <td class="">London</td>
        <td class="dt-body-right">47</td>
        <td class="">2009/10/09</td>
        <td class="dt-body-right">$1,200,000</td>
    </tr>
</tbody>
```

### Kendo

[Plunkr](http://plnkr.co/edit/UbGiIQg0xHH2fnHV0Hke?p=preview)

### devexpress

[CODE PEN](https://codepen.io/anon/pen/JrwrmG)

### wijmo

[JSFiddle](http://jsfiddle.net/Wijmo5/st9jw19v)

## Tree Table

### data-table

### kendo

### devexpress

### wijmo

## Freeze Column
### data-table

### kendo

### devexpress

### wijmo

**Comment by vthinkxie** [comment]
fixed in version 0.7.0

**Comment by navisoftware** [comment]
You can refer to it
Has achieved the column and header locking, the effect also is pretty good
http://element.eleme.io/#/en-US/component/table

**Comment by vthinkxie** [comment]
@navisoftware https://ng.ant.design/version/0.7.x/components/table/zh we support it already.
