### ISSUE TITLE
nz-table underlying checkbox clickable on fixed column

### ISSUE THREAD

**Issue by kevinvaningen** [NG-ZORRO/ng-zorro-antd#3531]
The issue which is not created via https://ng.ant.design/issue-helper/#/en will be closed immediately.

Checkboxes which are scrolled behind a fixed column (so they are not visible) can be clicked.

In nz-table (version 7.3.2) I have build a table with the following properties:
- horizontal scroll
- fixed first three column (using nzLeft)
- Each row has a checkbox in the first column (which is fixed), and checkboxes in the horizontal scrollable content part of the table. 

So what happened is that whenever a user scrolls the table cells horizontally, the cells of the center of the table scroll behind the first fixed column. This is what you would expect. Now the users selects the first checkbox, which now looks unresponsive, but what actually happened is that the checkbox below (like in z-index below) is now checked. So a checkbox which is not visible to the user gets checked. 

I have made the background color of the first cell (left bottom) transparent, so its visible what happens.  The orange checkbox has scrolled behind the one which is still empty and holds the arrow, and just now the orange got checked. 

<img width="390" alt="Screenshot 2019-06-04 at 20 54 04" src="https://user-images.githubusercontent.com/2325408/58905965-3aa82980-870b-11e9-991d-b2d85610c22a.png">

**Comment by kevinvaningen** [comment]
> where the arrow is

igh

**Comment by vthinkxie** [comment]
Hi @kevinvaningen 
I check it in the below stackblitz, and found everything works fine
https://stackblitz.com/edit/angular-8dbptv?file=src/app/app.component.ts
plz submit another issue with valid stackbliz link if you still have questions
