### ISSUE TITLE
nz-select 数据源在数据量过大时可设置加载数据量的条数

### ISSUE THREAD

**Issue by HelloValue** [NG-ZORRO/ng-zorro-antd#3537]
## What problem does this feature solve?
数据量过大时需要配合搜索的情况。目前数据量过大会导致初始化组件时，页面无反应。搜索也比较迟钝。

## What does the proposed API look like?
<nz-select 
          nzShowSearch 
          nzAllowClear 
          nzPlaceHolder="选择..." 
          [(ngModel)]="selected" 
          [nzDataSource]="data"	
          >
          <ng-container *ngFor="let b of data">
            <nz-option   [nzValue]="b.Id" [nzLabel]="b.Name"></nz-option>
          </ng-container> 
        </nz-select>

**Comment by vthinkxie** [comment]
可设置加载数据量的条数 可以自己限制，数组一个slice操作

**Comment by HelloValue** [comment]
`<nz-option *ngFor="let b of brCollectionList.slice(0,300)" [nzValue]="b.brandCollectionId" [nzLabel]="b.brandCollectionName"></nz-option>`
这样的话，搜索也搜索不到 300条以后的数据了。

**Comment by HelloValue** [comment]
> 可设置加载数据量的条数 可以自己限制，数组一个slice操作

<nz-option *ngFor="let b of brCollectionList.slice(0,300)" [nzValue]="b.brandCollectionId" [nzLabel]="b.brandCollectionName"></nz-option>
这样的话，搜索也搜索不到 300条以后的数据了。

**Comment by vthinkxie** [comment]
搜索和数据展示本来就是一体的，数据量过大时不建议使用前端搜索

**Comment by HelloValue** [comment]
> 搜索和数据展示本来就是一体的，数据量过大时不建议使用前端搜索

不考虑增加一个选项单独把搜索数据源和展示数据源分开么？

**Comment by vthinkxie** [comment]
你可以很方便的通过 nzOnSearch  自行修改数据源数据
