### ISSUE TITLE
The dropdown component lack of  some events function，such as change listening events

### ISSUE THREAD

**Issue by yxmanyxman** [NG-ZORRO/ng-zorro-antd#354]
## Current behavior
When I use the Dropdown component，I need to use the change drop-down option to listen for events，base on now，just provide nzVisibleChange to recall when the nzVisible status changed。

## Expected behavior

I hope that the Dropdown component can provide the others listening events when option is changed

## What is the motivation / use case for changing the behavior?

There is a need in business needs，and such like Primeng,Material their dropdown component provide change listening events also.

## Environment

<pre><code>
Angular version: 4.4.3

ng-zorro-antd version: 0.5.1

 
For Tooling issues:
- Node version: 6.11.1  
- Platform:  Windows

**Comment by vthinkxie** [comment]
what listening events do you want?

**Comment by yxmanyxman** [comment]
For example, when the drop-down option changes, the event can monitor the state of the option change. Through this event, I can always monitor whether the drop-down option has changed, if the drop-down option has changed, I can through this event monitoring option has been changed to facilitate further implementation; if the option has not changed, does not trigger monitoring event.
If I do not express a clear need, you can refer to https://www.primefaces.org/primeng/#/dropdown ,primeng's dropdown component provides more events, like onChange, onFocus.

**Comment by yxmanyxman** [comment]
@vthinkxie

**Comment by yxmanyxman** [comment]
For example, when the drop-down option changes, the event can monitor the state of the option change. Through this event, I can always monitor whether the drop-down option has changed, if the drop-down option has changed, I can through this event monitoring option has been changed to facilitate further implementation; if the option has not changed, does not trigger monitoring event.
If I do not express a clear need, you can refer to https://www.primefaces.org/primeng/#/dropdown ,primeng's dropdown component provides more events, like onChange, onFocus.
