### ISSUE TITLE
Support for nested column headers，是否支持组合嵌套的表头？

### ISSUE THREAD

**Issue by RogerHuangZB** [NG-ZORRO/ng-zorro-antd#355]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

Are any plans to support multiple tier headers/headers spanning multiple rows or columns similar to these?:
https://www.w3.org/WAI/tutorials/tables/irregular/

Maybe there already is a way of doing that using the templates, but I've been trying around and have had no luck.

Thanks.

请问有没有方法实现组合嵌套表头？

## Expected behavior

https://www.w3.org/WAI/tutorials/tables/irregular/

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
supported
all the content in `nz-table` will be filled inside the `table` tag.
you can try the following code, replace the data with `*ngFor` and `*ngIf`
```typescript
    <nz-table #nzTable [nzDataSource]="data" [nzPageSize]="10">
      <colgroup span="3">
        <col>
        <col>
      </colgroup>
      <thead nz-thead>
        <tr>
          <th scope="col" nz-th>Poster name</th>
          <th scope="col" nz-th>Color</th>
          <th colspan="3" nz-th scope="colgroup">Sizes available</th>
        </tr>
      </thead>
      <tbody nz-tbody>
        <tr nz-tbody-tr>
          <th rowspan="3" scope="rowgroup">Zodiac</th>
          <th scope="row">Full color</th>
          <td>A2</td>
          <td>A3</td>
          <td>A4</td>
        </tr>
        <tr nz-tbody-tr>
          <th scope="row">Black and white</th>
          <td>A1</td>
          <td>A2</td>
          <td>A3</td>
        </tr>
        <tr nz-tbody-tr>
          <th scope="row">Sepia</th>
          <td>A3</td>
          <td>A4</td>
          <td>A5</td>
        </tr>
      </tbody>
      <tbody nz-tbody>
        <tr nz-tbody-tr>
          <th rowspan="2" scope="rowgroup">Angels</th>
          <th scope="row">Black and white</th>
          <td>A1</td>
          <td>A3</td>
          <td>A4</td>
        </tr>
        <tr nz-tbody-tr>
          <th scope="row">Sepia</th>
          <td>A2</td>
          <td>A3</td>
          <td>A5</td>
        </tr>
      </tbody>
    </nz-table>
```

**Comment by RogerHuangZB** [comment]
after add property [nzWidth] on each <th>, there is sth wrong.
these [nzWidth] property  does not match each <th>.
多表头加了 [nzWidth] 后，我发现 [nzWidth] 属性并没有和<th>一一对应，而是错位的，比如说‘姓名’那列宽度104px，这个属性其实应用到了 ‘描述1’ 那一列上面。

<pre><code>
          <thead nz-thead *ngIf="_header">
        <tr>
          <th rowspan="2" nz-th [nzCheckbox]="true" [nzWidth]="'100px'">
            <label nz-checkbox [(ngModel)]="_allChecked" [nzIndeterminate]="_indeterminate" (ngModelChange)="_checkAll($event)"></label>
          </th>
          <th colspan="3" nz-th [nzWidth]="'101px'"><span>用户信息</span></th>
          <th colspan="9" nz-th [nzWidth]="'102px'"><span>描述group</span></th>
          <th rowspan="2" nz-th [nzWidth]="'103px'"><span>操作</span></th>
        </tr>
        <tr>
          <th nz-th [nzWidth]="'104px'"><span>姓名</span></th>
          <th nz-th [nzWidth]="'105px'"><span>年龄</span></th>
          <th nz-th [nzWidth]="'106px'"><span>地址</span></th>

          <th nz-th [nzWidth]="'107px'"><span>描述1</span></th>
          <th nz-th [nzWidth]="'108px'"><span>描述2</span></th>
          <th nz-th [nzWidth]="'109px'"><span>描述3</span></th>
          <th nz-th [nzWidth]="'110px'"><span>描述4</span></th>
          <th nz-th [nzWidth]="'112px'"><span>描述5</span></th>
          <th nz-th [nzWidth]="'113px'"><span>描述6</span></th>
          <th nz-th [nzWidth]="'114px'"><span>描述7</span></th>
          <th nz-th [nzWidth]="'115px'"><span>描述8</span></th>
          <th nz-th [nzWidth]="'116px'"><span>描述9</span></th>
        </tr>
      </thead>
</code></pre>

##these are in devtools Element
<code><pre>
    <table>
                    <colgroup>

<col style="width: 100px; min-width: 100px;">
<col style="width: 101px; min-width: 101px;">
<col style="width: 102px; min-width: 102px;">
<col style="width: 103px; min-width: 103px;">
<col style="width: 104px; min-width: 104px;">
<col style="width: 105px; min-width: 105px;">
<col style="width: 106px; min-width: 106px;">
<col style="width: 107px; min-width: 107px;">
<col style="width: 108px; min-width: 108px;">
<col style="width: 109px; min-width: 109px;">
<col style="width: 110px; min-width: 110px;">
<col style="width: 112px; min-width: 112px;">
<col style="width: 113px; min-width: 113px;">
<col style="width: 114px; min-width: 114px;">
<col style="width: 115px; min-width: 115px;">
<col style="width: 116px; min-width: 116px;">
                    </colgroup>
                    
      <thead _ngcontent-c9="" nz-thead="" class="ant-table-thead">
        <tr _ngcontent-c9="">
          <th _ngcontent-c9="" nz-th="" rowspan="2" class="ant-table-selection-column">
            <label _ngcontent-c9="" nz-checkbox="" class="ant-checkbox-wrapper ng-untouched ng-pristine ng-valid">
    <span class="ant-checkbox">
      <span class="ant-checkbox-inner"></span>
      <input type="checkbox" class="ant-checkbox-input ng-untouched ng-pristine ng-valid">
    </span>
    
  </label>
          </th>
          <th _ngcontent-c9="" colspan="3" nz-th=""><span _ngcontent-c9="">用户信息</span></th>
          <th _ngcontent-c9="" colspan="9" nz-th=""><span _ngcontent-c9="">描述group</span></th>
          <th _ngcontent-c9="" nz-th="" rowspan="2"><span _ngcontent-c9="">操作</span></th>
        </tr>
        <tr _ngcontent-c9="">
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">姓名</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">年龄</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">地址</span></th>

          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">描述1</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">描述2</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">描述3</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">描述4</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">描述5</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">描述6</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">描述7</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">描述8</span></th>
          <th _ngcontent-c9="" nz-th=""><span _ngcontent-c9="">描述9</span></th>
        </tr>
      </thead>
      
                  </table>
<code></pre>


另外有一个问题，如果我有很多列，table好像不支持横向滚动？（这个我另起一个issue吧）

**Comment by vthinkxie** [comment]
@RogerHuangZB nzWidth is not supported with nested column headers yet, you can just write your own col to make it work, scroll horizontally is not supported yet.

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed
