### ISSUE TITLE
穿梭框点击checkbox无法纪录

### ISSUE THREAD

**Issue by AdaVih** [NG-ZORRO/ng-zorro-antd#3550]
<img width="886" alt="图片" src="https://user-images.githubusercontent.com/35645884/59175695-09a37b00-8b89-11e9-9527-2e67220f425b.png">
如图，只点击checkbox没有效果，其他功能正常。
代码如下：
<img width="408" alt="图片" src="https://user-images.githubusercontent.com/35645884/59175892-c8f83180-8b89-11e9-9742-cbee5904831c.png">
<img width="390" alt="图片" src="https://user-images.githubusercontent.com/35645884/59176015-44f27980-8b8a-11e9-9b45-2f15d1186eb8.png">
将文档的文档拷贝进去使用也出现这种问题。

**Comment by AdaVih** [comment]
@wendzhue 有什么需要提供给您的嘛？

**Comment by AdaVih** [comment]
#3026 你们将这个修改了嘛？

**Comment by AdaVih** [comment]
更新版本之后可以运行。
可否自定义穿梭框的排序，初始化direction设置为right的时候会自动排序，我需要根据自己的顺序来排。

**Comment by s641135196** [comment]
我也想用排序这功能。 好像还没这功能
