### ISSUE TITLE
响应式表单使用[formControl]时没有错误样式

### ISSUE THREAD

**Issue by ismezy** [NG-ZORRO/ng-zorro-antd#3551]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ehvwjt](https://stackblitz.com/edit/ng-zorro-antd-start-ehvwjt)

### Steps to reproduce
响应式表单在不使用formControlName而使用[formControl]时，错误提示和input框没有变成红色。

### What is expected?
应该添加has-error样式，显示红色错误提示。

### What is actually happening?
错误提示和input框没有变成红色。

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.0 |
| Browser | chrome |

**Comment by HDNRAY** [comment]
@ismezy 你使用formControlName就有吗，我用这个也没有

**Comment by ismezy** [comment]
@HDNRAY 输入1个字符，再删除就会出现错误提示。

**Comment by HDNRAY** [comment]
@ismezy 看了你的demo，又研究了一下。因为我是把control和input放在2个不同的component里，所以发现手动设置nzValidateStatus，可以暂时修复这个问题，文档说是7.3.0开始提供的

**Comment by ismezy** [comment]
@HDNRAY 好的，谢谢。:clap:

**Comment by vthinkxie** [comment]
已经修复，在 8.0.0 版本中会发布，感谢反馈

**Comment by liangGeek** [comment]
> 反馈

在11版本 错误提示没有了
