### ISSUE TITLE
select: 点击项时会额外触发一次 nzOnSearch

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#3554]
## 重现

https://stackblitz.com/edit/angular-mxd3xv?file=src/app/app.component.ts

**步骤**

- 输入 `a`，触发 `nzOnSearch` 正常现象
- 选择第一项会再一次触发一次 `nzOnSearch`，这个行为会导致额外增加一次网络请求（若不做校验时）

**Comment by vthinkxie** [comment]
@cipchk 点击之后会清除当前搜索内容，所以会触发一次nzOnSearch
