### ISSUE TITLE
Transfer希望支持内部字段排序（右边框）

### ISSUE THREAD

**Issue by s641135196** [NG-ZORRO/ng-zorro-antd#3556]
## What problem does this feature solve?
在Excel导出的表列应该与自定义的列的顺序相同。

## What does the proposed API look like?
无要求。 能实现功能即可。 能实现上下拖动或者有按钮能让字段上下移动都可以。

**Comment by wenqi73** [comment]
Duplicate of #2870

**Comment by hukaixuan2017** [comment]
这个建议是修改还是不修改？穿梭框左侧和右侧排序还是很实用的功能
