### ISSUE TITLE
使用ng build --prod报错

### ISSUE THREAD

**Issue by zyn926** [NG-ZORRO/ng-zorro-antd#3562]
注意：不是用 https://ng.ant.design/issue-helper/#/zh 创建的 issue 会被立即关闭。

Illegal state: Could not load the summary for directive CdkObserveContent in G:/JD-Admin111/node_modules/ng-zorro-antd/node_modules/@angular/cdk/observers/typings/index.d.ts.

**Comment by zyn926** [comment]
> Hello @zyn926. Please provide a online reproduction by forking this link https://stackblitz.com/edit/ng-zorro-antd-start or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @zyn926, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://stackblitz.com/edit/ng-zorro-antd-start) 创建一个 stackblitz 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

版本的问题，已经解决了

**Comment by wgf4242** [comment]
> > Hello @zyn926. Please provide a online reproduction by forking this link https://stackblitz.com/edit/ng-zorro-antd-start or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> > 你好 @zyn926, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://stackblitz.com/edit/ng-zorro-antd-start) 创建一个 stackblitz 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> 版本的问题，已经解决了，谢谢

怎么解决的。我也报这个错了。。
