### ISSUE TITLE
select: 标签模式下会产生重复已录入的项

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#3565]
## 重现

https://stackblitz.com/edit/angular-q4wbkr?file=src/app/app.component.ts

_png_

![image](https://user-images.githubusercontent.com/2987467/59427466-4da6b200-8e0d-11e9-8c1e-e981d88aced6.png)

**步骤**

1. 分别输入 `1` 和 `2` 两个项
2. 当输入 `3` 时下拉选项重复出现 `1` 与 `2`

**Comment by wenqi73** [comment]
Ref #3559, has PR already.
