### ISSUE TITLE
templateRef support for nzNotFoundContent in documentation

### ISSUE THREAD

**Issue by meowhunter** [NG-ZORRO/ng-zorro-antd#3566]
## What problem does this feature solve?
Right now if there is no search result found, icon with text shown, but if i want to change that icon, i cant do that, because i can pass just string to [nzNotFoundContent]
## What does the proposed API look like?
< nz-select nzShowSearch [nzNotFoundContent]t="notFound" >
.... [options]
< /nz-select >
<ng-template #notFound></ng-template>

**Comment by meowhunter** [comment]
Actually [nzNotFoundContent] does support templateRef but it says string in documentation and its a bit confusing

**Comment by darshanrampatel** [comment]
See PR #3577
