### ISSUE TITLE
Strip whitespaces in around checkbox label

### ISSUE THREAD

**Issue by beckedorf** [NG-ZORRO/ng-zorro-antd#3593]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-z3fqhd](https://stackblitz.com/edit/ng-zorro-antd-start-z3fqhd)

### Steps to reproduce
Create a nz-checkbox. The label inside should start with a whitespace. E.g. you want the content of the label in the indented next line.

```
<label nz-checkbox>
    Label
</label>
```

### What is expected?
Whitespaces around content are ignored.

### What is actually happening?
Whitespaces around content are displayed.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Chrome |

---
Can be fixed by changing css ```display``` property of the second ```span``` in ```nz-checkbox``` to ```inline-block``` (currently ```inline```).

**Comment by vthinkxie** [comment]
Hi @beckedorf 
angular will treat the wrap line as a `space` in the template, you can see it here
https://stackblitz.com/edit/ng-zorro-antd-start-tmqgtt?file=src%2Fapp%2Fapp.component.css

and it will break the default style if add inline-block to the `span`

**Comment by dingjules** [comment]
Set `preserveWhitespaces: true,` for `nz-checbox` may be a workaround.
[related reading](https://github.com/angular/angular/issues/31058#issuecomment-501506084)
