### ISSUE TITLE
Context menu of customized directory tree is not working on Firefox

### ISSUE THREAD

**Issue by its404** [NG-ZORRO/ng-zorro-antd#3601]
### Reproduction link
[https://stackblitz.com/edit/angular-38s5vc?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-38s5vc?file=src/app/app.component.ts)

### Steps to reproduce
1. Right click any node on the tree to trigger context menu popup
2. The context menu disappears after the right mouse button is released(mouse key up)

### What is expected?
Context menu should be fixed(not disappeared) after the right mouse button released

### What is actually happening?
 The context menu disappears

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Firefox 67.0.2 (64-bit) |

**Comment by vthinkxie** [comment]
fixed, will release in 8.0.0 version
