### ISSUE TITLE
nzTable 通过 *ngFor 动态生成列导致 nzSortChange 反复触发

### ISSUE THREAD

**Issue by AngusFu** [NG-ZORRO/ng-zorro-antd#3603]
### Reproduction link
[https://stackblitz.com/edit/angular-qq6zi1?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-qq6zi1?file=src/app/app.component.ts)

### Steps to reproduce
1. 指定 `columns: Array<{ key: 'string', title: string }>` 用于动态设置 table 所展示的列
2. 设置 `<thead [nzSingleSort]="true" (nzSortChange)="onSortChange($event)">`
3. 通过 `*ngFor` 生成一系列的 `<th nzShowSort [nzSortKey]="col.key">{{ col.title }}</th>`
4. 点击任意 `th` 进行排序操作，发现只触发一次 `onSortChange`
5. 更改 `columns` 数组，如删除一项
6. 点击任意 `th` 进行排序操作，发现 `onSortChange` 会触发两次
7. 重复 5、6 操作，发现 `onSortChange` 会触发三次
8. 如此等等

[视频](https://s3.ssl.qhres.com/static/18b135736269b69b.mp4)

### What is expected?
`nzSortChange` 不应当反复触发

### What is actually happening?
`nzSortChange` 反复触发

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Chrome/74.0.3729.169 |

**Comment by AngusFu** [comment]
@vthinkxie 大概定位了 bug 的原因。主要在这里：
[components/table/nz-thead.component.ts#L66](https://github.com/NG-ZORRO/ng-zorro-antd/blob/c10a7a90f792449310ad9eed8aea29dbcefd8844/components/table/nz-thead.component.ts#L66)

`merge(...this.listOfNzThComponent)` 

写了段原理类似的代码  ——

```
import { merge, Subject } from "rxjs";
import { startWith, flatMap } from "rxjs/operators";

const subject = new Subject();
const array = [new Subject(), new Subject(), new Subject()];

subject
  .pipe(
    startWith(true),
    flatMap(() => {
      console.log(array.length);
      return merge(...array);
    })
  )
  .subscribe(console.log);

array[0].next("hello");
array[1].next("world");
array.pop().next("!");

subject.next(123);
array[0].next("hello");
array[1].next("world");
array.pop().next("!");
```

执行效果如下：

![image](https://user-images.githubusercontent.com/8180186/59759230-3579db80-92c2-11e9-8db0-bf25d84219c5.png)

**Comment by AngusFu** [comment]
上面的例子 `flatMap` 换成 `switchMap` 就好了。我提个 PR ?

```ts
import { merge, Subject } from "rxjs";
import { startWith, switchMap } from "rxjs/operators";

const subject = new Subject();
const array = [new Subject(), new Subject(), new Subject()];

subject
  .pipe(
    startWith(true),
    switchMap(() => {
      console.log(array.length);
      return merge(...array);
    })
  )
  .subscribe(console.log);

array[0].next("hello");
array[1].next("world");
array.pop().next("!");

subject.next(123);
array[0].next("hello");
array[1].next("world");
```

![image](https://user-images.githubusercontent.com/8180186/59759826-7f16f600-92c3-11e9-83bb-6aad1c6c8923.png)

**Comment by vthinkxie** [comment]
@AngusFu 感谢，麻烦补上对应的测试

**Comment by AngusFu** [comment]
@vthinkxie 🙂 刚刚搜了下，貌似整个 repo 中还有另外三个地方使用了 `flatMap`，其出现的场景大体和本 issue 类似，table 中有一个，submenu 和 select 中也各有一个。建议可以确认排查下。

https://github.com/NG-ZORRO/ng-zorro-antd/search?q=flatMap&unscoped_q=flatMap
