### ISSUE TITLE
nz-table在flex布局里，超出边界

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#3604]
### Reproduction link
[https://stackblitz.com/edit/angular-yo2k28](https://stackblitz.com/edit/angular-yo2k28)

### Steps to reproduce
重现链接里直接可看到

### What is expected?
nz-table符合flex预期，宽度不够出现滚动条。

### What is actually happening?
没有滚动条，超出了边界，撑大了flex

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Chrome 72 |

**Comment by vthinkxie** [comment]
碰到样式问题，麻烦先去搜css的标准写法，谢谢
https://stackblitz.com/edit/angular-yo2k28-fothhg?file=src/app/app.component.ts

**Comment by liwei511** [comment]
@vthinkxie https://stackblitz.com/edit/angular-yo2k28 麻烦看清楚

**Comment by vthinkxie** [comment]
@liwei511 不知道你想表达的具体意思，所有的web-compoonent的tag都是默认display:inline的，如果你想要100%宽度的话，至少父级需要100%宽度，在父级是一个inline元素下，你使用多少个display:flex也不可能获得你想要的效果

**Comment by liwei511** [comment]
@vthinkxie 是我错了，不是width的问题，谢谢

**Comment by liwei511** [comment]
@vthinkxie 不好意思，打扰了，stackblitz已更新

**Comment by vthinkxie** [comment]
@liwei511 
https://stackblitz.com/edit/angular-yo2k28-y3zsal?file=src/app/app.component.ts

**Comment by liwei511** [comment]
谢谢，我该好好学习css了，多谢
