### ISSUE TITLE
怎样设置 table 里 th 的 padding

### ISSUE THREAD

**Issue by wgf4242** [NG-ZORRO/ng-zorro-antd#3606]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-w1jx1v](https://stackblitz.com/edit/ng-zorro-antd-start-w1jx1v)

### Steps to reproduce
在styles里直接设置 th 没有效果。
直接加 class 是可以有效果的。但是太丑陋了。
TD也要设置 padding。不方便用 class 的方式。太多了，

### What is expected?
padding: 0 0 0 0

### What is actually happening?
16px

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-f7mtv7?file=src/app/app.component.ts
确保先读完 angular文档
https://www.angular.cn/guide/component-styles#deprecated-deep--and-ng-deep
