### ISSUE TITLE
nzValidateStatus & nzHasFeedback overlap with nzSuffix

### ISSUE THREAD

**Issue by Svetomechc** [NG-ZORRO/ng-zorro-antd#3607]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-zahkan](https://stackblitz.com/edit/ng-zorro-antd-start-zahkan)

### Steps to reproduce
```html
<form nz-form>
	<nz-form-item>
		<nz-form-label [nzSpan]="5">Password</nz-form-label>
		<nz-form-control [nzSpan]="12" nzValidateStatus="success" nzHasFeedback>
			<nz-input-group [nzSuffix]="suffixTemplate">
				<input
        [type]="passwordVisible ? 'text' : 'password'"
        nz-input
        placeholder="input password"
        [(ngModel)]="password"
      />
    </nz-input-group>
        </nz-form-control>
      </nz-form-item>
</form>

<ng-template #suffixTemplate>
      <i nz-icon [nzType]="passwordVisible ? 'eye-invisible' : 'eye'" (click)="passwordVisible = !passwordVisible"></i>
</ng-template>
```

### What is expected?
Icons are displayed next to each other

### What is actually happening?
Icons overlap

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | 77.0.3824.6 |

---

P.S. Issue Helper can't handle "&" sign:

1. Issue title
![image](https://user-images.githubusercontent.com/36156020/59783616-2ea29700-92c9-11e9-86ac-dd4042be4773.png)

2. Issue title after pressing "Create"
![image](https://user-images.githubusercontent.com/36156020/59783629-382bff00-92c9-11e9-8f82-b0a032a66266.png)

**Comment by vthinkxie** [comment]
Hi @Svetomechc 
you can add the style below as temp solution, we will release the fix version in 8.0.0
```css
form .has-feedback .ant-input-suffix i {
    margin-right: 18px;
}
```

**Comment by Svetomechc** [comment]
Thank you. I will wait for 8.0.0 (I already worked around this issue for now).

**Comment by Svetomechc** [comment]
Tried release candidate. I am really sorry to say that your fix is quite subpar because it adds a constant margin, no matter if there are two icons or one.

See demonstration:

1. This is OK
![image](https://user-images.githubusercontent.com/36156020/59979973-f2887280-95f7-11e9-86d0-0a4d7b7ffcca.png)


2. This is NOT
![image](https://user-images.githubusercontent.com/36156020/59979978-ff0ccb00-95f7-11e9-81ff-193b22dee8aa.png)

Previously icons would always stick to the right. But now second image looks like a regression from **ng-zorro-antd 7.x.x**.

Please reopen.

**Comment by Svetomechc** [comment]
@vthinkxie, please reopen.

**Comment by Svetomechc** [comment]
Still the same.

**Comment by vthinkxie** [comment]
@Svetomechc 
the fix version has not released yet

**Comment by Svetomechc** [comment]
@vthinkxie oh sorry, my bad.

**Comment by Svetomechc** [comment]
@vthinkxie By the way, thank you for all your hard work and patience. Much appreciated (:

**Comment by vthinkxie** [comment]
try this
```css
form .has-feedback.has-success .ant-input-suffix i,
form .has-feedback.has-error .ant-input-suffix i,
form .has-feedback.is-validating .ant-input-suffix i{
    margin-right: 18px;
}
```

**Comment by Svetomechc** [comment]
@vthinkxie this still makes **[nzSuffix]** position a bit off.

1. With fix above
![image](https://user-images.githubusercontent.com/36156020/60093575-70f92780-9752-11e9-9bad-000b39d02867.png)

2. Should be
![image](https://user-images.githubusercontent.com/36156020/60093621-938b4080-9752-11e9-943e-6ad252bdf143.png)

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-dgfg2j?file=src%2Fstyles.css
@Svetomechc

**Comment by Svetomechc** [comment]
Hmm, looks OK to me. Have to investigate why it doesn't work in my case. I will

As a side note, I think **[nzSuffix]** should be displayed to the right of **[nzHasFeedback]** icon, not to the left.
