### ISSUE TITLE
tree组件是否提供可以修改树节点名称的方法？

### ISSUE THREAD

**Issue by 007GitHu** [NG-ZORRO/ng-zorro-antd#3609]
## What problem does this feature solve?
用户新增节点时，节点名称录入错误或者临时改名时，需要修改指定树节点的名字

## What does the proposed API look like?
类似addChildren方法，获取需要修改的节点title和key，将需要修改的title重新赋值即可

**Comment by simplejason** [comment]
直接修改NzTreeNode的title即可

**Comment by 007GitHu** [comment]
直接修改后，界面上还是显示原来的数据，是否要重新加载还是做特殊处理
