### ISSUE TITLE
nz-mention need a '@' with blank as prefix, but ant of react just need '@' as prefix

### ISSUE THREAD

**Issue by Eve-Sama** [NG-ZORRO/ng-zorro-antd#3611]
### Reproduction link
[https://stackblitz.com/edit/nz-mention](https://stackblitz.com/edit/nz-mention)

### Steps to reproduce
en: Just input @, you will find nothing's going to happen. But if the text you input is ' @'(with blank), the select panel will appear.

cn: 直接输入@, 没有什么反应, 但是输入空格再输入艾特才会出现选择框.

### What is expected?
en: The select panel appears whenever I input @

cn: 每次输入@的时候下拉框都会出现

### What is actually happening?
en: The prefix is ' @'(with blank)

cn: 前缀是' @'(带有空格)

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Firefox 67.0.3 (64-bit) |

---
en: Ant of React does as I expect

cn: Ant of React是直接输入艾特的.

**Comment by hsuanxyz** [comment]
@Eve-1995 感觉是 react 的 bug，因为没办法输入邮箱了， 上一个版本的 mention 不会出现这个问题 https://ant.design/components/mention-cn/。

**Comment by hsuanxyz** [comment]
@Eve-1995 https://github.com/ant-design/ant-design/issues/15694, 看来是新行为。

**Comment by yxrgds** [comment]
Still unsolved?

**Comment by Mr-Eve** [comment]
> 
> 
> Still unsolved?

Yes, it's not a big deal. But it still exist.

**Comment by valeriolucantonio** [comment]
@Eve-Sama is there any update on this issue? Is there any workaround we can use? I tried to use viewChild to open the dropdown manually but haven't managed so far. It would be cool if you could either deliver a fix or offer a workaround for it.
Thanks
Valerio
