### ISSUE TITLE
Menu导航菜单的递归生成菜单，hover时背景增加颜色

### ISSUE THREAD

**Issue by 007GitHu** [NG-ZORRO/ng-zorro-antd#3612]
## What problem does this feature solve?
hover时的效果类似于树组件的hover效果，更能够突出用户鼠标当前位置，仅仅只是字体颜色变化，用户体验不是很友好

## What does the proposed API look like?
类似于树组件中树节点title的hover效果，不提供API，内部实现

**Comment by vthinkxie** [comment]
ng-zorro-antd 同步 ant design 设计规范，请去 https://github.com/ant-design/ant-design 发起issue，谢谢

**Comment by CK110** [comment]
> ng-zorro-antd 同步 ant design 设计规范，请去 https://github.com/ant-design/ant-design 发起issue，谢谢

Menu组件属性和ant design不一样啊，很多属性没有，是不需要，还是以后回同步antdesign？

**Comment by vthinkxie** [comment]
@CK110 哪些属性没有？

**Comment by 007GitHu** [comment]
鼠标hover效果：背景颜色



------------------ 原始邮件 ------------------
发件人: "vthinkxie"<notifications@github.com>; 
发送时间: 2019年6月26日(星期三) 下午2:27
收件人: "NG-ZORRO/ng-zorro-antd"<ng-zorro-antd@noreply.github.com>; 
抄送: "卿玲玲"<1971722214@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NG-ZORRO/ng-zorro-antd] Menu导航菜单的递归生成菜单，hover时背景增加颜色 (#3612)




@CK110 哪些属性没有？

**Comment by vthinkxie** [comment]
> 鼠标hover效果：背景颜色
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "vthinkxie"<notifications@github.com>; 发送时间: 2019年6月26日(星期三) 下午2:27 收件人: "NG-ZORRO/ng-zorro-antd"<ng-zorro-antd@noreply.github.com>; 抄送: "卿玲玲"<1971722214@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [NG-ZORRO/ng-zorro-antd] Menu导航菜单的递归生成菜单，hover时背景增加颜色 (#3612) @CK110 哪些属性没有？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

hover 背景颜色一句css就可以搞定，为什么需要API提供？写在template里面也会导致和全主题无法统一配置

**Comment by 007GitHu** [comment]
不需要提供API，只是在内部实现而已，因为如果站着使用者的角度来讲，我增加了css，担心会对以后升级组件有影响




------------------ 原始邮件 ------------------
发件人: "vthinkxie"<notifications@github.com>; 
发送时间: 2019年6月26日(星期三) 下午2:32
收件人: "NG-ZORRO/ng-zorro-antd"<ng-zorro-antd@noreply.github.com>; 
抄送: "卿玲玲"<1971722214@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NG-ZORRO/ng-zorro-antd] Menu导航菜单的递归生成菜单，hover时背景增加颜色 (#3612)



 
鼠标hover效果：背景颜色
 …
 ------------------ 原始邮件 ------------------ 发件人: "vthinkxie"notifications@github.com; 发送时间: 2019年6月26日(星期三) 下午2:27 收件人: "NG-ZORRO/ng-zorro-antd"ng-zorro-antd@noreply.github.com; 抄送: "卿玲玲"1971722214@qq.com; "Author"author@noreply.github.com; 主题: Re: [NG-ZORRO/ng-zorro-antd] Menu导航菜单的递归生成菜单，hover时背景增加颜色 (#3612) @CK110 哪些属性没有？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
hover 背景颜色一句css就可以搞定，为什么需要API提供？写在template里面也会导致和全主题无法统一配置

**Comment by CK110** [comment]
> @CK110 哪些属性没有？

antd
![image](https://user-images.githubusercontent.com/9956098/60225496-bab05200-98b9-11e9-9d48-e429e25e9583.png)

zorro
![image](https://user-images.githubusercontent.com/9956098/60225533-ce5bb880-98b9-11e9-9bfe-00983940c290.png)

**Comment by vthinkxie** [comment]
@CK110 angular 本身是不需要keys进行选中操作的，在你想要选中的menu上直接加nzSelectable就可以了，其他的所有api在angular设计中都是冗余的

**Comment by CK110** [comment]
> @CK110 angular 本身是不需要keys进行选中操作的，在你想要选中的menu上直接加nzSelectable就可以了，其他的所有api在angular设计中都是冗余的

确实menu上直接加nzSelectable可以达到defaultselectkeys的操作，你说的不同点是angular和react本身机制的不同，还是就是react ant design中的属性设计就是冗余的？？
