### ISSUE TITLE
Select all option

### ISSUE THREAD

**Issue by fbcarpinato** [NG-ZORRO/ng-zorro-antd#3615]
## What problem does this feature solve?
I want to be able to have a select all option for the multi select component
## What does the proposed API look like?
<nz-select [selectAll]="true"></nz-select>

**Comment by wendzhue** [comment]
Use `[ngModel]`. This proposed API would result in confusion and inconsistent with existing API.

**Comment by fbcarpinato** [comment]
Okay, but every time I want to have an option for selecting/deselecting all items I have to do it by myself

**Comment by wendzhue** [comment]
@fbcarpinato Yes. Selecting all is just a special case of *selecting something*.
