### ISSUE TITLE
(bug): ng-upload filelist binding

### ISSUE THREAD

**Issue by dylanvdmerwe** [NG-ZORRO/ng-zorro-antd#3617]
### Reproduction link
[https://angular-y1cpfq.stackblitz.io](https://angular-y1cpfq.stackblitz.io)

### Steps to reproduce
Setup an `nz-upload` component. 
Binding it to a `fileList` as per the docs. 
Once the page has loaded, perhaps there are some files that need to be displayed that are loaded asynchronously.
Add these images into the `fileList` by pushing or recreating the 

### What is expected?
A picture-card nz-upload component should display images that have been added into the `fileList`.

### What is actually happening?
Binding issue. Items added manually into `fileList` do not appear on the images for the component.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Chrome 75 |

**Comment by cipchk** [comment]
According to [Angular documentation](https://angular.io/guide/lifecycle-hooks#onchanges)，developers should not use `push` or `splice` to change the data passed to `nzFileList`


```typescript
  ngOnInit() {
    setTimeout(() => {
      console.log("adding new image");
      this.fileList = this.fileList.concat(
        {
          uid: -2,
          name: 'xxx.png',
          status: 'done',
          url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png'
        }
      )
    }, 4000);
  }

```

**Comment by dylanvdmerwe** [comment]
Yes I can confirm the binding does work when using `concat`. Thank you for the information.
