### ISSUE TITLE
tooltip的属性容易造成冲突

### ISSUE THREAD

**Issue by HalfLegend** [NG-ZORRO/ng-zorro-antd#3620]
## What problem does this feature solve?
tooltip组件的属性，如nzTitle  nzPlacement看不出来源，且容易造成冲突
像某个元素上有  nzTitle  nzPlacement nzContent 等属性，看上去好像是元素自己的属性或者某种全局属性，但实际上是由于 nz-tooltip的存在才引入的，非常不友好，可读性不强
像 nzTitle nzContent 这种属性，其它组件很容易也存在此名字的属性，很容易冲突

## What does the proposed API look like?
1. nzTitle属性没有意义，应该去掉：  可以直接使用 nz-tooltip="XXX"。没必要再额外设置nzTitle
2. 其它属性，如 nzPlacement  nzContent 命名应当加入其来源，如 nzTooltipPlacement   nzTooltipContent  
(请参考其它框架：如 https://material.angular.io/components/tooltip/examples 
https://akveo.github.io/nebular/docs/components/tooltip/overview#nbtooltipdirective)

**Comment by darshanrampatel** [comment]
Duplicate of #3456

**Comment by wendzhue** [comment]
Closed because of duplication.
