### ISSUE TITLE
Disable Paging

### ISSUE THREAD

**Issue by yang-small-fan** [NG-ZORRO/ng-zorro-antd#3621]
## What problem does this feature solve?
Paging can be disabled.

## What does the proposed API look like?
Can't Paging Plug-ins Provide a Disabled Function?

**Comment by vthinkxie** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/commit/141bef8e935e46a4ad666ff2ad2b52fddac8525a
will support in 8.0.0

**Comment by yang-small-fan** [comment]
@vthinkxie Oh, thanks!
