### ISSUE TITLE
Tree : drag and drop with custom templates

### ISSUE THREAD

**Issue by Maryannah** [NG-ZORRO/ng-zorro-antd#3640]
### Reproduction link
[https://stackblitz.com/edit/angular-mtme3w?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-mtme3w?file=src/app/app.component.ts)

### Steps to reproduce
Try drag and drop after opening the link : it works. Remove the comments at the lines 17 and 30 to add custom templates : drag and drop stopped working.

### What is expected?
The drag and drop with custom templates should work.

### What is actually happening?
The elements of the tree are considered text and are highlighted by the cursor when trying to drag and drop

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | any |

**Comment by madhankumar05** [comment]
super thank you so much

**Comment by xiaotoya** [comment]
It doesn't work in version 1.8.x, can you help me. I just use the code above.

**Comment by whiteblueblack** [comment]
thank you ~
