### ISSUE TITLE
Collapse does not open after folding in Edge browser

### ISSUE THREAD

**Issue by xguan2014** [NG-ZORRO/ng-zorro-antd#3647]
### Reproduction link
[https://a4qfv1.run.stackblitz.io](https://a4qfv1.run.stackblitz.io)

### Steps to reproduce
在Edge中打开Collapse，折叠上面板，再打开会发现无法展开面板了

### What is expected?
可以展开

### What is actually happening?
无法展开

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Edge 44.17763.1.0 |

**Comment by vthinkxie** [comment]
duplicated #3098

**Comment by 772658652** [comment]
遇到同样的问题，请问怎么解决

**Comment by tinybull** [comment]
@vthinkxie I am using angularV7, so please help fix this issue to support us, we hope our application can be run in IE11, many thanks.
