### ISSUE TITLE
nz-menu,水平的顶部导航菜单模式下，没有自适应宽度，与antdesign有差别

### ISSUE THREAD

**Issue by CK110** [NG-ZORRO/ng-zorro-antd#3657]
### Reproduction link
[https://bkhzyw.run.stackblitz.io](https://bkhzyw.run.stackblitz.io)

### Steps to reproduce
[nzMode]="'horizontal'" style="width: 240px;"

### What is expected?
匹配react版的antd，自适应宽度，通过···占位，悬浮显示menu

### What is actually happening?
menu超出规定的宽度

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
Duplicate #2531
