### ISSUE TITLE
Card Header Styling

### ISSUE THREAD

**Issue by sunilksamanta** [NG-ZORRO/ng-zorro-antd#3659]
## What problem does this feature solve?
Cards of Ant Design is fantastic. But it would be very helpful If it was possible to add custom styling to the Card Header. 
## What does the proposed API look like?
[nzHeadStyle]

**Comment by vthinkxie** [comment]
you can add
:host ::ng-deep
to customize the style

**Comment by sunilksamanta** [comment]
> you can add
> :host ::ng-deep
> to customize the style

Working like a charm. Thanks 
![Screenshot from 2019-06-27 14-34-36](https://user-images.githubusercontent.com/3468128/60252936-cbc48780-98e8-11e9-8b28-7f3267c9e97d.png)

**Comment by vthinkxie** [comment]
@sunilksamanta 
do you have the interest t leave replies about your product and organization [here](https://github.com/NG-ZORRO/ng-zorro-antd/issues/1142)?

**Comment by sunilksamanta** [comment]
> @sunilksamanta
> do you have the interest to leave replies about your product and organization [here](https://github.com/NG-ZORRO/ng-zorro-antd/issues/1142)?

Yes sure. It is under development. Let me complete that. I'll surely. You people have done a really great design. Well documented and clean UI

**Comment by SongXuchun** [comment]
> 您可以添加 ：host ：：ng-deep 来自定义样式

But it seems to fail in nz-modal
