### ISSUE TITLE
InputNumber对科学计数法的输入不够友好，输入框宽度能否动态适应数字的长度

### ISSUE THREAD

**Issue by SoaringTiger** [NG-ZORRO/ng-zorro-antd#366]
## I'm submitting a...

<pre><code>
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

1、InputNumber对科学计数法的输入不够友好，比如输入1.2e20的时候，输到1.2e2的时候，数字就自动转成了120，似乎是每敲入一个数字就进行了自动转换，所以没法真正的逐个敲入1.2e20这样的格式。
2、InputNumber的输入框宽度好像无法修改?

## Expected behavior

1、能否把对数字的转换放到失去焦点后？
2、能否有选项保持科学计数法的显示？
3、输入框宽度能否动态适应数字的长度？

## Environment

<pre><code>
Angular version: 4.2.4

ng-zorro-antd version: 0.5.1

Browser:
- [x] Chrome (desktop) version 61
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: v8.2.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by vthinkxie** [comment]
Scientific notation is not supported yet, and all number will not be translated from scientific notation yet. We will discuss about it later. Thanks for your feedback.

You can just implements autoresize yourself, here is a demo.

```typescript
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'nz-demo-input-number-basic',
  template: `
    <nz-input-number [(ngModel)]="demoValue" [nzMin]="1" [nzStep]="1" [style.width.px]="(demoValue+'').length*10+50"></nz-input-number>
  `,

  styles: []
})
export class NzDemoInputNumberBasicComponent implements OnInit {
  demoValue = 3;

  constructor() {
  }

  ngOnInit() {
  }
}


```
