### ISSUE TITLE
怎么在ngFor指令中使用tree组件

### ISSUE THREAD

**Issue by xuwenqing2014** [NG-ZORRO/ng-zorro-antd#3662]
## What problem does this feature solve?
tree组件是ngFor循环出来的，所以ts中的@ViewChild('nzTree') nzTree: NzTreeComponent;以及html中的#nzTree不能这么写，如何在ts中通过循环的下标index获取对应的nzTree，最终实现this.nzTree.getCheckedNodeList()

## What does the proposed API look like?
看下是否有解决方案，如果没有，建议提供html中使用id的方式(因为id可以与循环的下标index关联)，而在ts中使用ElementRef的方式获取nzTree

**Comment by vthinkxie** [comment]
@ViewChildren?
