### ISSUE TITLE
Tabs中嵌入iframe每当切换会刷新

### ISSUE THREAD

**Issue by cnlt** [NG-ZORRO/ng-zorro-antd#3666]
### Reproduction link
[https://stackblitz.com/edit/angular-wf1ghw](https://stackblitz.com/edit/angular-wf1ghw)

### Steps to reproduce
切换tab页

### What is expected?
iframe不刷新

### What is actually happening?
iframe刷新了

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | google |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-wf1ghw-k8ddt7?file=src/app/app.component.ts
