### ISSUE TITLE
upload组件点击上传按钮触发表单校验和ngSubmit

### ISSUE THREAD

**Issue by zhuxiyu** [NG-ZORRO/ng-zorro-antd#3668]
### Reproduction link
[https://stackblitz.com/edit/angular-djbesr](https://stackblitz.com/edit/angular-djbesr)

### Steps to reproduce
点击upload按钮

### What is expected?
只做上传操作，不触发事件

### What is actually happening?
触发表单校验、触发ngSubmit绑定的save函数

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Google Chrome Version 75.0.3770.100 (Official Build) (64-bit) |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-djbesr-rsuxek?file=src/app/app.component.ts
https://stackoverflow.com/questions/3543615/difference-between-input-type-submit-and-button-type-submittext-butto
