### ISSUE TITLE
联级选择的每条信息前面应该可以加图标

### ISSUE THREAD

**Issue by gaodingpeng** [NG-ZORRO/ng-zorro-antd#3669]
## What problem does this feature solve?
有某些时候，无法判断当前的信息是否是属于哪个类型的。比如说，公司，部门，岗位，员工之间的4层联动，当这个岗位下没有员工的时候，当我选到这个岗位的时候，无法直观的知道这个是岗位还是员工！

## What does the proposed API look like?
[nzShowIcon]="true"

**Comment by wendzhue** [comment]
麻烦仔细描述下需求，最好带上复现。

职位和员工是如何混淆的，职位名和人的姓名相差的似乎挺大。

**Comment by gaodingpeng** [comment]
![image](https://user-images.githubusercontent.com/52306237/60323529-ee23d700-99b4-11e9-8162-c57c80665d74.png)

**Comment by gaodingpeng** [comment]
这个测试员就没法确定到底是岗位还是员工

**Comment by wendzhue** [comment]
TODO: 增加一个 `nzItemRender` 变量

**Comment by gaodingpeng** [comment]
ng-zorro里面没有这个API呀

**Comment by wendzhue** [comment]
@gaodingpeng **TODO**

**Comment by wendzhue** [comment]
close by #4127
