### ISSUE TITLE
[next] form: FormArray 下无法显示错误信息

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#3675]
## 重现

https://stackblitz.com/edit/angular-lqqqgd?file=src%2Fapp%2Fapp.component.ts 

其中在不输入任何文本时：
- 文本框视觉反馈：`ng-invalid`
- `invalid` 值为 `true`

表现正常，但无法触发 `nzErrorTip` 错误文本。

**Comment by vthinkxie** [comment]
nz-form-control 是一个 component，不能作为 directive 使用
