### ISSUE TITLE
Enable/Disable property for NzAffix

### ISSUE THREAD

**Issue by thinkdj** [NG-ZORRO/ng-zorro-antd#3676]
## What problem does this feature solve?
Sometimes there is a need to have the contents of nz-affix as default "static" and change to "absolute" only on special cases.
Proposing an enabled/disabled property

## What does the proposed API look like?
```
<nz-affix [nzEnabled]="dataHasCanged">
.....
</nz-affix>
```

**Comment by cipchk** [comment]
@thinkdj You can wrap a `nz-affix` of `div` element, like this:

```html
<div [ngStyle]="posStyle">
	<nz-affix></nz-affix>
</div>
```

```ts
get posStyle(): {} {
	return this.status ? { position: 'absolute' } : {};
}
```
