### ISSUE TITLE
在NzModal的confirm实例中，modal.nzCancelDisabled失效

### ISSUE THREAD

**Issue by tazyong** [NG-ZORRO/ng-zorro-antd#3679]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-qkfwqq](https://stackblitz.com/edit/ng-zorro-antd-start-qkfwqq)

### Steps to reproduce
在confirm类型下必然重现，其它类型匀正常

### What is expected?
当点击模态框“删除按钮”以后，“取消按钮”不可用

### What is actually happening?
点击模态框“删除按钮”以后，“取消按钮”仍然可以正常使用

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Google Chrome 72.0.3626.81 |

**Comment by cp1001** [comment]
nzCancelLoading可以禁用cancel按钮，不过会有loading态。nzCancelDisabled确实是个bug，没能禁用按钮
