### ISSUE TITLE
[ BUG ] ivy compiler error message "ERROR in Cannot combine @Input decorators with query decorators"

### ISSUE THREAD

**Issue by Aitthi** [NG-ZORRO/ng-zorro-antd#3682]
The issue which is not created via https://ng.ant.design/issue-helper/#/en will be closed immediately.

![Screen Shot 2019-06-29 at 8 50 57 PM](https://user-images.githubusercontent.com/26670680/60385081-aafa5e80-9aaf-11e9-872c-45bfce7c64e7.png)

**Comment by vthinkxie** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/3514#issuecomment-499101370

**Comment by liwei511** [comment]
遇到了同样的问题，请问您怎么解决？

**Comment by wendzhue** [comment]
不要启用 Ivy 即可解决，现在暂不支持 Ivy
