### ISSUE TITLE
nz-carousel 在 nz-carousel-content 没有显式设置高度时,元素的高度被固定为 height:1px

### ISSUE THREAD

**Issue by wxpxzdj** [NG-ZORRO/ng-zorro-antd#3688]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-jf5w5t](https://stackblitz.com/edit/ng-zorro-antd-start-jf5w5t)

### Steps to reproduce
当没有显式设置 nz-carousel-content 的高度时，在 8.0 版本会被固定为 height: 1px;
这是7.X.X 中的正常结果：https://stackblitz.com/edit/ng-zorro-antd-start-cfvpcv

### What is expected?
如 7.X.X 一样可以自适应图片高度

### What is actually happening?
高度被定死，无法自适应。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.0 |
| Browser | Chrome 5.0.3770.100 |

---
官网首页，我们这边的走马灯一般宽度是满屏，然后高度是自适应的

**Comment by wxpxzdj** [comment]
![image](https://user-images.githubusercontent.com/7706151/60395365-af348380-9b64-11e9-83fc-22926e7c06ca.png)
Reproduction link 里面有时候被固定为 1px, 有时候又不是 1px, 本地调试的时候一直都是 1px;

**Comment by wendzhue** [comment]
@wxpxzdj 

因为这里有两个异步事件：图片的加载和 carousel 对内容高度的计算，当图片没有下载下来时，carousel 如果去计算内容的高度当然就是 1px 了。

组件不应该也不可能知道它里面的内容什么时候下载完成，手动指定高度是必须的。

**Comment by wxpxzdj** [comment]
@wendzhue 这种情况下不需要固定高度吧，看旧版本也没有显式地设置高度：
![image](https://user-images.githubusercontent.com/7706151/60397426-c765cc00-9b7f-11e9-8476-5aa723bd3d83.png)

**Comment by wxpxzdj** [comment]
![image](https://user-images.githubusercontent.com/7706151/60397805-5b856280-9b83-11e9-8b74-d8d20d859c9c.png)
目前暂时通过这种方式实现想要的效果
