### ISSUE TITLE
IE11 Input's placeholder misaligned in IE11

### ISSUE THREAD

**Issue by mbrainiac** [NG-ZORRO/ng-zorro-antd#3700]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-lnrd1t?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-lnrd1t?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Create a nz-input with placeholder

### What is expected?
The placeholder is aligned correctly 

### What is actually happening?
The placeholder is misaligned vertically.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.0 |
| Browser | IE11 |

---
![screenshot](https://i.imgur.com/L7t2Kj0.png)

**Comment by vthinkxie** [comment]
will fix in https://github.com/NG-ZORRO/ng-zorro-antd/pull/3863/files#diff-9
