### ISSUE TITLE
LESS styling Operation on an invalid type

### ISSUE THREAD

**Issue by TheAifam5** [NG-ZORRO/ng-zorro-antd#3703]
### Reproduction link
stackblitz does not want to change to less :/ 

### Steps to reproduce
Install Antd-Zorro using `ng add ng-zorro-antd`

### What is expected?
No error while compiling less styles (needed for custom themes).

### What is actually happening?
```
[start:hmr:web] Module build failed (from node_modules/@angular-devkit/build-angular/node_modules/less-loader/dist/cjs.js):
[start:hmr:web] 
[start:hmr:web] 
[start:hmr:web]   &-round {
[start:hmr:web]     .btn-round(@btn-prefix-cls);
[start:hmr:web]   ^
[start:hmr:web] Operation on an invalid type
[start:hmr:web]       in node_modules/ng-zorro-antd/button/style/index.less (line 77, column 4)
```

After commenting the first thing out:
```
[start:hmr:web] Module build failed (from node_modules/@angular-devkit/build-angular/node_modules/less-loader/dist/cjs.js):
[start:hmr:web] 
[start:hmr:web] 
[start:hmr:web]   &-circle-outline {
[start:hmr:web]     .btn-circle(@btn-prefix-cls);
[start:hmr:web]   ^
[start:hmr:web] Operation on an invalid type
[start:hmr:web]       in node_modules/ng-zorro-antd/button/style/index.less (line 82, column 4)
[start:hmr:web] ℹ ｢wdm｣: Failed to compile.
```

After commenting both cases out, compiles successfuly.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.1 |
| Browser | Not related |

**Comment by vthinkxie** [comment]
our doc site is built with 8.0.1 and custom theme, I am afraid you have to provide an repro repo

**Comment by TheAifam5** [comment]
That's really weird, because while following the tutorial, after including the file: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/scripts/site/_site/doc/theme.less
I'm getting an error.

Here is an example:
[bug.zip](https://github.com/NG-ZORRO/ng-zorro-antd/files/3355685/bug.zip)

The stacklitz... no words ... just crashes after when I want to import that LESS file directly.

**Comment by vthinkxie** [comment]
@TheAifam5 
I have check your zip file, your styles.less file is not the same as https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/scripts/site/_site/doc/theme.less plz check it again.

**Comment by JesseHeisenberg** [comment]
VS code extension `Beautify` will cause this problem,suggest to use `Prettier` for format.
