### ISSUE TITLE
The table checkbox renders slowly with large amounts of data

### ISSUE THREAD

**Issue by zomixi** [NG-ZORRO/ng-zorro-antd#3705]
### Reproduction link
[https://stackblitz.com/edit/angular-dljafx](https://stackblitz.com/edit/angular-dljafx)

### Steps to reproduce
Click on the allCheck checkbox

### What is expected?
Quick selection

### What is actually happening?
slowly selection

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.1 |
| Browser | Google Chrome  75.0.3770.100（正式版本） （64 位） |

---
Problems with animation

**Comment by vthinkxie** [comment]
Hi @zomixi 
you can use nzVirtualScroll to get better performance
https://stackblitz.com/edit/ng-zorro-antd-ivy-kdf18c
