### ISSUE TITLE
still lack of tree component

### ISSUE THREAD

**Issue by dyh333** [NG-ZORRO/ng-zorro-antd#371]
still lack of tree component like [ant-react](https://ant.design/components/tree-cn/)

looking for it.

**Comment by vthinkxie** [comment]
duplicated #132

**Comment by vthinkxie** [comment]
you can use https://github.com/cipchk/ng-tree-antd as a temp solution.

**Comment by dyh333** [comment]
@vthinkxie  thanks, if the tree component would consider checkAll/uncheckAll like checkbox , and support add an icon before tree node text ,  it would be better.

![image](https://user-images.githubusercontent.com/1221313/30838553-b8ad421e-a29e-11e7-8252-8bc5413bd1d2.png)


by the way, does the checkbox component support add icon for every item including child item. now the 
nz-checkbox-group banding an array, seems hard to customize style.
`
<nz-checkbox-group [(ngModel)]="checkOptionsOne" (ngModelChange)="updateSingleChecked()"></nz-checkbox-group>
`
