### ISSUE TITLE
Ivy: Cannot combine @Input decorators with query decorators

### ISSUE THREAD

**Issue by limuxy** [NG-ZORRO/ng-zorro-antd#3712]
### Steps to reproduce

* using NzTable and/or NzPagination
* turn on ivy
* build

### What is expected?
Should build successfully

### What is actually happening?
Building process throws `ERROR in Cannot combine @Input decorators with query decorators`

 `@Input` & `@ViewChild` are used together in NzTable and NzPagination, which is not allowed in Ivy.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.1 |
| Browser | not concerned |

**Comment by wendzhue** [comment]
We do not support Ivy yet. Please open this kind of issue after there is an official announcement.

**Comment by techaks** [comment]
is there any updates on Ivy ?

**Comment by sgentile** [comment]
it's now January 2020 - same error

**Comment by vthinkxie** [comment]
ivy will be supported at 9.0 version

**Comment by dapothedeveloper** [comment]
> it's now January 2020 - same error

If you're still experiencing this error follow the official documentation for migrating to angular 9 here [https://update.angular.io/](url)
