### ISSUE TITLE
Anchor锚点展示问题

### ISSUE THREAD

**Issue by xingguixin** [NG-ZORRO/ng-zorro-antd#3714]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
1、页面滚动到最底部
2、切换浏览器页签
3、页面锚点界面显示就会有问题

### What is expected?
期待anchor锚点可以正常显示

### What is actually happening?
锚点样式错乱，显示为一个点

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.1 |
| Browser | chrome、360极速 |

**Comment by xingguixin** [comment]
![image](https://user-images.githubusercontent.com/45035944/60557563-98ff1100-9d78-11e9-8cac-558282659dcb.png)

**Comment by wendzhue** [comment]
Will track in #3938.
