### ISSUE TITLE
OnPush component dynamic disable input , the input component style is not updated

### ISSUE THREAD

**Issue by danranVm** [NG-ZORRO/ng-zorro-antd#3732]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-taeerc?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-taeerc?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
click button

### What is expected?
style is updated

### What is actually happening?
style is not updated

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.2 |
| Browser | chrome  |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-77vojp?file=src/app/app.component.html

**Comment by danranVm** [comment]
@vthinkxie 虽然解决了，但是还是请教下原因：
