### ISSUE TITLE
How to change primary-color while application running?

### ISSUE THREAD

**Issue by yutingding** [NG-ZORRO/ng-zorro-antd#3733]
如何动态切换主题颜色（类似于暗/亮色主题的切换，且颜色自定义）？
how to change @primary-color in theme.less dynamically?

**Comment by wendzhue** [comment]
@yutingding Please check this post on our blog: https://ng.ant.design/blog/custom-theme/.

**Comment by yutingding** [comment]
@wendzhue Thanks.
