### ISSUE TITLE
IE11 Select Mode is "tags" input display is incomplete

### ISSUE THREAD

**Issue by latelater** [NG-ZORRO/ng-zorro-antd#3734]
### Reproduction link
[https://ng-zorro-antd-start-fd8rkf.stackblitz.io](https://ng-zorro-antd-start-fd8rkf.stackblitz.io)

### Steps to reproduce
please open this URL in IE11, and then，enter some information in the input box.The input box can only display the first character, and the rest of the characters are covered.
https://ng.ant.design/components/select/en#components-select-demo-tags

### What is expected?
When using IE11, select can display the input content normally.

### What is actually happening?
The input result cannot be displayed normally using IE11 browser

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.4.1 |
| Browser | IE11 |

---
You can reproduce this question in your official document

https://ng.ant.design/components/select/en#components-select-demo-tags

**Comment by vthinkxie** [comment]
could you try the latest version?

**Comment by latelater** [comment]
First of all, the [official website demo](https://ng.ant.design/components/select/en#components-select-demo-tags) can reproduce the problem, and then our team does not use the requirements of angular8 for the time being.And the latest version of Antd Design just released on June 29th,we didn't upgrade so fast.
Whether to confirm that the latest version has resolved this issue?

**Comment by wenqi73** [comment]
It works fine in the latest version.
