### ISSUE TITLE
docs: Modules not listed any more

### ISSUE THREAD

**Issue by dylanvdmerwe** [NG-ZORRO/ng-zorro-antd#3735]
There used to be a section on the documents which detailed the module that needs to be installed for each component. 

This is no longer present and needs to be added back. 

For example, on [button](https://ng.ant.design/components/button/en):
![image](https://user-images.githubusercontent.com/2852839/60673450-05146e80-9e78-11e9-9bd5-e429184c0ddc.png)

**Comment by dylanvdmerwe** [comment]
Please reopen, documentation issue.

**Comment by vthinkxie** [comment]
in the top of the doc
