### ISSUE TITLE
Improve nzMatchRouter behaviour

### ISSUE THREAD

**Issue by Svetomechc** [NG-ZORRO/ng-zorro-antd#3736]
## What problem does this feature solve?
I expected **nzMatchRouter** directive to be the same as writing **routerLinkActive #rla="routerLinkActive" [nzSelected]="rla.isActive"**. It is not.
## What does the proposed API look like?
Please, make **nzMatchRouter** behave exactly like **routerLinkActive #rla="routerLinkActive" [nzSelected]="rla.isActive"** does.

**Comment by vthinkxie** [comment]
they are working the same way
if you found any problem plz provide valid repro link

**Comment by Svetomechc** [comment]
It is hard for me to reproduce outside my project as it uses custom dynamic menu building from routes meta info.

**Comment by Svetomechc** [comment]
@vthinkxie okay, I did it: https://stackblitz.com/edit/ng-zorro-antd-start-ipf8qe

**Comment by Svetomechc** [comment]
@vthinkxie is this reproduction ok?

**Comment by vthinkxie** [comment]
@Svetomechc yes, fixed in #3785
thanks to your report!

**Comment by Svetomechc** [comment]
My pleasure (:
What version will the fix land in?

**Comment by wendzhue** [comment]
8.0.3 @Svetomechc

**Comment by Svetomechc** [comment]
Cool.
