### ISSUE TITLE
InputNumber能否增加小数位数的限定配置

### ISSUE THREAD

**Issue by howing** [NG-ZORRO/ng-zorro-antd#374]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

目前InputNumber组件不支持用户进行小数位数的限定配置，也没有提供onChange事件。

## Expected behavior

提供小数位数的配置，如增加precision属性，设置为2的时候，用户输入“1.235”，会自动处理为“1.24”。或者至少也应该提供onChange事件，开发者可以自己实现小数限定逻辑。

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
use ngModelChange please

**Comment by howing** [comment]
@vthinkxie thanks.
