### ISSUE TITLE
alert description innerhtml

### ISSUE THREAD

**Issue by egalley** [NG-ZORRO/ng-zorro-antd#3742]
## What problem does this feature solve?
Hi all,

Alert description can be bind to a Template but no context is provided to render it.
[nzDescription]="alertTemplate"...

<ng-template #alertTemplate let-alert>
  {{alertl?.message}}
</ng-template>

Or maybe there is an other way to display all the pending alerts...

Thank you
## What does the proposed API look like?
Is there a way to transmit a context like
context:{$implicit:alert}

**Comment by vthinkxie** [comment]
what is the `{{alertl?.message}}`? 
you can put the ng-template inside nz-alert if you are using *ngFor

**Comment by egalley** [comment]
Thank you vthinkxie,
I just want to display innerhtml from an observable collection.

export class Alert {
  type : AlertType; // Error, Warning,...
  title : string;
  message : string;
  submessage : string;
}

export class AlertComponent implements OnInit, OnDestroy {
  alerts: Alert[] = [];
...
var alert {type:Error, title:"Error", message:"<strong>Very Important</strong> message"};
 this.alerts.push(alert);
...}

<nz-alert *ngFor="let alert of alerts" nzCloseable nzShowIcon
      nzType="{{ cssClass(alert) }}"
      nzMessage="{{alert.title}}"
      nzDescription="{{alert.message}}"
      (nzOnClose)="removeAlert(alert)"
    >
</nz-alert>

nzDescription will not interpret <strong>Very Important</strong>
And if I use a ng-template, I don't know how to access to alert object properties

Thank you

**Comment by vthinkxie** [comment]
```html
<nz-alert [nzDescription]="descriptionTpl">
<ng-template #descriptionTpl>anything here</ng-template>
</nz-alert>
```

**Comment by egalley** [comment]
Hi,

Sorry but it does not work.
I want to display innerhtml `<strong>Message</strong>`.
If I use your solution
`<nz-alert [nzDescription]="descriptionTpl">
<ng-template #descriptionTpl><strong>Very Important</strong></ng-template>
</nz-alert>`

 it will display
`<strong>Very Important</strong>`
instead of
<strong>Very Important</strong>

**Comment by vthinkxie** [comment]
@egalley it is very easy to check if it is working in stackblitz, why won't you have a try?
https://stackblitz.com/edit/angular-n3apwy?file=src/app/app.component.ts

**Comment by egalley** [comment]
Thank you, sorry to lose your time.
You can close the ticket.
I found how to display it.

import { Component } from '@angular/core';

@Component({
  selector: 'nz-demo-alert-basic',
  template: `
  <nz-alert nzType="success" nzMessage="Success Text" [nzDescription]="descriptionTpl"> 
  <ng-template #descriptionTpl><span innerHTML={{alertTxt}}></span></ng-template> </nz-alert>
  `
})
export class NzDemoAlertBasicComponent {
  alertTxt : string = 'Description <strong>Very Important</strong>.'  
}
