### ISSUE TITLE
Component deprecation warning should not log as error

### ISSUE THREAD

**Issue by krokofant** [NG-ZORRO/ng-zorro-antd#3749]
Currently the nz-dropdown creates an error due to it being deprecated:
```
[NG-ZORRO]: deprecated: 'nz-dropdown' Component is going to be removed in 9.0.0. Please use 'nz-dropdown-menu' instead. Read https://ng.ant.design/components/dropdown/en
```

I suggest that this should not output an error but a warning with `console.warn()` instead of `console.error()`.

Related code:
1. [warnDeprecation()](https://github.com/NG-ZORRO/ng-zorro-antd/blob/b89352046162456c7de46ca43f78640bc0330cf0/components/core/logger/logger.ts#L38)
2. [usage in nz-dropdown](https://github.com/NG-ZORRO/ng-zorro-antd/blob/fb4965b5fd782ce85a6d4d90dde5c38c7b953c9d/components/dropdown/nz-dropdown.component.ts#L141)

**Comment by vthinkxie** [comment]
@kekehaoz this warning would not show in prod mode

**Comment by krokofant** [comment]
@vthinkxie I understand, that sounds good. I think you tagged the wrong person.
