### ISSUE TITLE
nz-tab support each tab has a router

### ISSUE THREAD

**Issue by getmonyinfo** [NG-ZORRO/ng-zorro-antd#375]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ x ] Feature request
[ x ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

Does `nz-tab` support each tab has a  router similar like 

I checked material docoment found this:

> While <md-tab-group> is used to switch between views within a single route, <nav md-tab-nav-bar> provides a tab-like UI for navigating between routes.The tab-nav-bar is not tied to any particular router; it works with normal <a> elements and uses the active property to determine which tab is currently active. The corresponding <router-outlet> can be placed anywhere in the view.
```javascript
<nav md-tab-nav-bar>
  <a md-tab-link
     *ngFor="let link of navLinks"
     [routerLink]="link"
     routerLinkActive #rla="routerLinkActive"
     [active]="rla.isActive">
    {{tabLink.label}}
  </a>
</nav>

<router-outlet></router-outlet>
```

## Expected behavior
Each tab has  a individual router

```javascript
    <nz-tabset>
        <nz-tab>
            <ng-template #nzTabHeading>
                <a routerLink="/login">登录</a>
            </ng-template>
            <router-outlet></router-outlet>
            
        </nz-tab>
        
        <nz-tab>
            <ng-template #nzTabHeading>
                <a routerLink="/register">注册</a>
            </ng-template>
            <router-outlet ></router-outlet>
        </nz-tab>
        
    </nz-tabset>
```

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
```html
    <nz-tabset>
        <nz-tab>
            <ng-template #nzTabHeading>
                <a routerLink="/login">登录</a>
            </ng-template>            
        </nz-tab>
        <nz-tab>
            <ng-template #nzTabHeading>
                <a routerLink="/register">注册</a>
            </ng-template>
        </nz-tab>
    </nz-tabset>
    <router-outlet ></router-outlet>

```

**Comment by robichaud** [comment]
@vthinkxie Unfortunately, your solution does not work well because the user can change the tab without clicking the routerLink. Is there a workaround for that?
