### ISSUE TITLE
nz-date-picker 无法自适用铺满

### ISSUE THREAD

**Issue by luoshun83** [NG-ZORRO/ng-zorro-antd#3754]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-nxgzkn?embed=1&file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-nxgzkn?embed=1&file=src/app/app.component.html)

### Steps to reproduce
<nz-row nzGutter="16">
        <nz-col nzLg="6" nzMd="12" nzSm="24">
            <nz-form-item>
                <nz-form-label [nzSm]="8" nzFor="createdbytime" nzRequired>创建时间</nz-form-label>
                <nz-form-control [nzSm]="16">
                    <nz-date-picker [nzStyle]="{'width': '100%'}" formControlName="createdbytime"></nz-date-picker>
                </nz-form-control>
            </nz-form-item>
        </nz-col>
    </nz-row>

### What is expected?
期望是根据父容器的宽度自动适应铺满

### What is actually happening?
实际结果是宽度是固定的

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.1 |
| Browser | 谷歌 75.0.3770.100 64bit |

**Comment by wendzhue** [comment]
@luoshun83 

Ant Design 设计如此，参看 https://ant.design/components/date-picker-cn/。

如果有设计方面的问题请先给 Ant Design 提交 issue，这个 issue 现在会被关闭。

其实一个简单的 width: 100% 样式就可以了。

https://stackblitz.com/edit/ng-zorro-antd-start-8c2ced?file=src/app/app.component.css
