### ISSUE TITLE
nz-select (nzFocus) (nzBlur)这两个事件回调无效，我看了下issue，nz-input-number好像这两个功能也还未实现。

### ISSUE THREAD

**Issue by duoduoObama** [NG-ZORRO/ng-zorro-antd#3757]
### Reproduction link
[https://stackblitz.com/edit/angular-juphrm?embed=1&file=src/app/app.component.ts](https://stackblitz.com/edit/angular-juphrm?embed=1&file=src/app/app.component.ts)

### Steps to reproduce
用nz-select写一个测试用例，调用api (nzBlur)的回调监听log事件

### What is expected?
有回调值打印

### What is actually happening?
没有反应

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.2 |
| Browser | chrome |

**Comment by duoduoObama** [comment]
Although no one bird I, but I have already solved it, I saw the source code implementation to replace the blur method with another method callback. (nzOpenChange)

**Comment by mjn1154477982** [comment]
在nzShowSearch模式下，focus才有效
