### ISSUE TITLE
菜单加滚动条后，缩起时子菜单不能弹出显示(When the menu is added to the scroll bar, the submenu cannot pop up when it shrinks)

### ISSUE THREAD

**Issue by ZhangZheng-GIS** [NG-ZORRO/ng-zorro-antd#376]
在nz-layout中的nz-sider内添加菜单nz-menu，当菜单内容过长时需要在nz-sider中添加滚动条，但是当菜单缩起时无法弹出子菜单，删除滚动条则可以弹出子菜单。恳请开发者解答，谢谢！
![default](https://user-images.githubusercontent.com/14178404/30794748-9ea3cd90-a1fc-11e7-88eb-017960d41661.png)
![default](https://user-images.githubusercontent.com/14178404/30794739-870be000-a1fc-11e7-8a7b-cf523eb75243.png)
![default](https://user-images.githubusercontent.com/14178404/30794770-b255d374-a1fc-11e7-8b4b-2f4ad6c03c18.png)

相关代码见下面连接：
https://plnkr.co/edit/CuerW1?p=preview

@vthinkxie ， @trotyl , @cipchk , @dyh333

**Comment by vthinkxie** [comment]
Hi, @ZhangZheng-GIS 
it is a bit complex but you can use it as an temp solution.
https://plnkr.co/edit/ViWiHz?p=preview

**Comment by vthinkxie** [comment]
ref https://github.com/ant-design/ant-design/issues/6589

**Comment by vthinkxie** [comment]
fixed in version 0.7.0
