### ISSUE TITLE
如果Table header在模板中设置nzWidth属性无效

### ISSUE THREAD

**Issue by ismezy** [NG-ZORRO/ng-zorro-antd#3761]
### Reproduction link
[https://stackblitz.com/edit/angular-mue5n9](https://stackblitz.com/edit/angular-mue5n9)

### Steps to reproduce
将table的thead部分放在模板里，在th上设备nzWidth生效，如下：   

```html
<thead>
      <ng-container *ngTemplateOutlet="headerTmpl"></ng-container>
</thead>
<ng-template #headerTmpl>
      <tr>
          <th [nzWidth]="'20rem'">Name</th>
          <th>Age</th>
          <th>Address</th>
          <th>Action</th>
        </tr>
</ng-template>
```

### What is expected?
nzWidth能生效。

### What is actually happening?
nzWidth未生效。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.2 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
ContentChildren 穿透不了 ng-template，这个是 angular 的设计
