### ISSUE TITLE
Option to show week numbers on all datepickers

### ISSUE THREAD

**Issue by jerry1970** [NG-ZORRO/ng-zorro-antd#3764]
## What problem does this feature solve?
The week picker shows week numbers automatically. I would love to be able to show week numbers on all datepickers as well. Some users (especially in Sweden) are used to use calendars by week numbers. Don't show the week numbers by default, but a setting to toggle this would be great.

## What does the proposed API look like?
Add `[nzShowWeekNumber]` (`bool`) option to all date pickers.

**Comment by PWTony** [comment]
Hi there,

Any update about this feature please ?
Did you have an idea for the release date please ?

**Comment by klipnot** [comment]
Hello everyone ,

Is there any chance to add this features soon ?

Or even explain how to achieve this with à workaround ? 🤔

**Comment by bngo42** [comment]
Hi,

We use it on our project, and this fix would be greatly appreciated, any news on the progress ?

**Comment by Teeflam** [comment]
你好,
我也想知道什么时候有新的更新.
😥

**Comment by UncleDave** [comment]
I've implemented this in #7621 and I'd appreciate feedback from those of you who have requested this feature.
