### ISSUE TITLE
Cascader级联选择样式优化

### ISSUE THREAD

**Issue by tazyong** [NG-ZORRO/ng-zorro-antd#3767]
## What problem does this feature solve?
新增以下样式，可以使Cascader级联选择器输入或者选中值超过本身宽度时，显示优雅一些

nz-cascader {
&nbsp;&nbsp;input {
&nbsp;&nbsp;&nbsp;&nbsp;padding-right: 24px;
&nbsp;&nbsp;}
&nbsp;&nbsp;.ant-cascader-picker-label {
&nbsp;&nbsp;&nbsp;&nbsp;padding-right: 24px;
&nbsp;&nbsp;}
}

## What does the proposed API look like?
无API更新，仅优化样式建议

**Comment by wendzhue** [comment]
@tazyong 请提交至 Ant Design
