### ISSUE TITLE
Modal 对话框的nzWidth使用数据绑定时在component里面改变无法立即生效，必须关掉重新打开才能生效

### ISSUE THREAD

**Issue by dalin178** [NG-ZORRO/ng-zorro-antd#377]
Modal 对话框的nzWidth使用数据绑定时在component里面改变无法立即生效，必须关掉重新打开才能生效

**Comment by vthinkxie** [comment]
please provide your ng-zorro-antd version.

**Comment by dalin178** [comment]
0.5.0

**Comment by dalin178** [comment]
@vthinkxie  0.5.0

**Comment by dalin178** [comment]
@vthinkxie 0.5.2 also has this problem

**Comment by vthinkxie** [comment]
@dalin178 thanks we will check it later.

**Comment by dalin178** [comment]
@vthinkxie  这个问题怎么没解决呢

**Comment by vthinkxie** [comment]
works fine when tested, please provide online demo here http://plnkr.co/edit/tpl:sKWy62 or provide the code that can reproduce your problem with git.

**Comment by dalin178** [comment]
@vthinkxie 
import { Component } from '@angular/core';
@Component({
  selector: 'nz-demo-modal-basic',
  template: `
    <button nz-button [nzType]="'primary'" (click)="showModal()">
      <span>显示对话框</span>
    </button>

<nz-modal [nzVisible]="isVisible" [nzTitle]="'第一个 Modal'" [nzContent]="modalContent" (nzOnCancel)="handleCancel($event)" (nzOnOk)="handleOk($event)" [nzWidth]="nzWidth">
      <ng-template #modalContent>
        <p>对话框的内容</p>
        <p>对话框的内容</p>
        <p>对话框的内容</p>

	<button nz-button [nzType]="'primary'" (click)="changeWidth()">
      		<span>改变nzwidth</span>
   	 </button>
      </ng-template>
    </nz-modal>
  `,
  styles: []
})
export class NzDemoModalBasicComponent {
  isVisible = false;
  nzWidth=520;

changeWidth()
{
if(this.nzWidth==520)
{
this.nzWidth=1000;
}
else
{
this.nzWidth=520;
}
  
}
  showModal = () => {
    this.isVisible = true;
  }
  handleOk = (e) => {
    console.log('点击了确定');
    this.isVisible = false;
  }
  handleCancel = (e) => {
    console.log(e);
    this.isVisible = false;
  }
  constructor() {}
}

**Comment by vthinkxie** [comment]
there is no watch function to nzWidth when it change, you can check it after 0.7.0 released.

**Comment by vthinkxie** [comment]
fixed in version 0.7.0
