### ISSUE TITLE
nz-select | nz-option-group allow a parameter to make the grouped label sticky when scrolled

### ISSUE THREAD

**Issue by bthieblot** [NG-ZORRO/ng-zorro-antd#3772]
### What is the problem ? ###

When you have a large list inside your nz-select with multiple nz-option-group, when you scroll or when you opened a select with a selected value, you don't know in which option group you are.

If you add a sticky option group, you will clearly see where you are.
### How ? ###

Add a default input parameter on nz-option-group **nzSticky** set to *true* and *onInit* of the component just add a css class with these style (at least) depending on the value of ***nzSticky***: 
```css
  position: sticky;
  top: 0;
  background-color: white;
  z-index: 1;
  border-bottom: 1px solid rgba(0,0,0,0.1); // optionnal
```

**Comment by vthinkxie** [comment]
won't support after discussion.
