### ISSUE TITLE
NzInputNumberComponent European number insert

### ISSUE THREAD

**Issue by feirer** [NG-ZORRO/ng-zorro-antd#3773]
## What problem does this feature solve?
In most European countries, a comma is used to separate the integral part of a number from the decimal part. This means, for example, that three hundred euros and ten cents is written as 300,10 - with a comma as a decimal marker.

It's not possible to insert a number like 10,5 - the value in this case is 105 because the comma is not allowed 

## What does the proposed API look like?
```

export class NzInputNumberComponent implements ControlValueAccessor, AfterViewInit, OnChanges, OnInit, OnDestroy {

 onModelChange(value: string): void {
    this.actualValue = this.nzParser(
      value
        .trim()
        .replace(/。/g, '.')
        .replace(/,/g, '.')  <--------------[add this replace]
        .replace(/[^\w\.-] /g, '')
    );
    this.inputElement.nativeElement.value = `${this.actualValue}`;
  }

}


```

**Comment by vthinkxie** [comment]
@feirer but what is 3,000 means in European countries, should it translate to 3000 or 3.000

**Comment by lppedd** [comment]
@vthinkxie 3,000 means 3 basically.

**Comment by 4val0v** [comment]
**_See_**

- [i18n-number](https://www.npmjs.com/package/i18n-number) - [demo](https://t2ym.github.io/i18n-number/components/i18n-number/demo/)
- [formatjs](https://formatjs.io)
- [Mozilla NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat)

**Comment by wendzhue** [comment]
Numbers are even stringer in India.

**Comment by vthinkxie** [comment]
Hi all, you can override the default nzParser after v9 released
