### ISSUE TITLE
menu component not change selected item after click

### ISSUE THREAD

**Issue by dyh333** [NG-ZORRO/ng-zorro-antd#3774]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-rue8ku](https://stackblitz.com/edit/ng-zorro-antd-start-rue8ku)

### Steps to reproduce
第一次直接点击button：可正确将selected item切换至group3;
但当随便点击某个菜单项，如Team Group后，再去点击button，此时无法 将selected item切换至group3；

### What is expected?
点击任意菜单项后，也能通过设置selected=true，切换选中状态

### What is actually happening?
当随便点击某个菜单项，如Team Group后，再去点击button，此时无法 将selected item切换至group3；

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | chrome |

---
8.x版本同样存在此问题

**Comment by vthinkxie** [comment]
@dyh333 你第一次点击button之后，将selected 设置为true，第二次点击的时候，selected 已经是true，将已经是true的数据再次设置为true，组件肯定是不会进行任何响应的
如果你想要手动管理所有菜单的激活状态，需要将 nzSelected 设置为 false，并且根据 nzClick 事件将你的 数组 中的selected手动修改为对应状态 https://stackblitz.com/edit/ng-zorro-antd-start-rgfi7w?file=src/app/app.component.ts

**Comment by dyh333** [comment]
@vthinkxie 如你提供的方法，请问如何将NzMenuItemDirective设为selected状态。尝试直接修改nzSelected不起作用
https://stackblitz.com/edit/ng-zorro-antd-start-kl1adn

**Comment by vthinkxie** [comment]
你需要设定的是你给出的数组的selected状态，直接修改event里面的内容有问题

**Comment by dyh333** [comment]
但是通过nzClick 获取到的NzMenuItemDirective似乎不太好获取到当前选中的menu-item项

**Comment by vthinkxie** [comment]
可以手动给每个menu item加上id，通过element就可以获取
