### ISSUE TITLE
breadcrumb  自动生成面包屑，将`NZ_ROUTE_DATA_BREADCRUMB`设置为可配置化

### ISSUE THREAD

**Issue by CK110** [NG-ZORRO/ng-zorro-antd#3775]
## What problem does this feature solve?
router data里面的信息可能用于设置为title，和面包屑很大概率上是同一个值

## What does the proposed API look like?
通过inject token实现可配置

**Comment by wendzhue** [comment]
Would fix this after the global config service is online.

**Comment by CK110** [comment]
> Now global config is in the air, welcome to contribute~

看了 `global config`, 它是主要设置的组件属性默认值，但是 `NZ_ROUTE_DATA_BREADCRUMB`还并 不是属性。我觉得可以改为属性 ` @Input()  nzRouteDataBreadcrumbLabel: string = 'breadcrumb';` 。因为系统中不会有很多地方需要 `Breadcrumb`吧，没必要还可以全局设置默认值吧？
