### ISSUE TITLE
nz-dropdown-menu组件无法识别

### ISSUE THREAD

**Issue by hxtech-bj-wangbingxin** [NG-ZORRO/ng-zorro-antd#3791]
### Reproduction link
[https://ng-zorro-antd-start-kduwz5.stackblitz.io](https://ng-zorro-antd-start-kduwz5.stackblitz.io)

### Steps to reproduce
    <nz-dropdown-menu #menu="nzDropdownMenu">
        <ul nz-menu>
            <li nz-menu-item>1st menu item</li>
            <li nz-menu-item>2nd menu item</li>
            <li nz-menu-divider></li>
            <li nz-menu-item nzDisabled>disabled menu item</li>
            <li nz-submenu nzTitle="sub menu">
                <ul>
                    <li nz-menu-item>3rd menu item</li>
                    <li nz-menu-item>4th menu item</li>
                </ul>
            </li>
            <li nz-submenu nzDisabled nzTitle="disabled sub menu">
                <ul>
                    <li nz-menu-item>3rd menu item</li>
                    <li nz-menu-item>4th menu item</li>
                </ul>
            </li>
        </ul>
    </nz-dropdown-menu>

### What is expected?
解释或解决

### What is actually happening?
compiler.js:2196 Uncaught Error: Template parse errors:
Can't bind to 'nzDropdownMenu' since it isn't a known property of 'a'. ("
    </div>

    <a nz-dropdown nzTrigger="click" [ERROR ->][nzDropdownMenu]="menu">
        Click me
        <i nz-icon nzType="down"></i>
"): ng:///AppModule/CaseComponent.html@84:37
There is no directive with "exportAs" set to "nzDropdownMenu" ("
        <i nz-icon nzType="down"></i>
      </a>
    <nz-dropdown-menu [ERROR ->]#menu="nzDropdownMenu">
        <ul nz-menu>
            <li nz-menu-item>1st menu item</li>
"): ng:///AppModule/CaseComponent.html@88:22
'nz-dropdown-menu' is not a known element:
1. If 'nz-dropdown-menu' is an Angular component, then verify that it is part of this module.
2. If 'nz-dropdown-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        <i nz-icon nzType="down"></i>
      </a>
    [ERROR ->]<nz-dropdown-menu #menu="nzDropdownMenu">
        <ul nz-menu>
            <li nz-menu-item>1st menu "): ng:///AppModule/CaseComponent.html@88:4
    at syntaxError (compiler.js:2196)
    at TemplateParser.parse (compiler.js:19472)
    at JitCompiler._parseTemplate (compiler.js:24671)
    at JitCompiler._compileTemplate (compiler.js:24659)
    at compiler.js:24603
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:24603)
    at compiler.js:24516
    at Object.then (compiler.js:2187)
    at JitCompiler._compileModuleAndComponents (compiler.js:24515)

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.3 |
| Browser | Chrome |

---
none

**Comment by vthinkxie** [comment]
请阅读你使用版本的官方文档

**Comment by s33h0w** [comment]
@hxtech-bj-wangbingxin  你可能用的是7.5.x或者更早版本的，这个版本`nz-dropdown`是组件而非指令，也没有`nz-dropdown-menu`这个组件。

**Comment by vugardadalov** [comment]
[Look at that example ](https://github.com/ant-design/ant-design/issues/17388)
