### ISSUE TITLE
timeline组件在7.x版本中无法动态变换nzDot

### ISSUE THREAD

**Issue by dyh333** [NG-ZORRO/ng-zorro-antd#3792]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-nuctbw](https://stackblitz.com/edit/ng-zorro-antd-start-nuctbw)

### Steps to reproduce
点击按钮

### What is expected?
图标切换为dotTemplate2对应图标

### What is actually happening?
图标无变化

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | chrome |

---
v8.x可以正常切换

**Comment by vthinkxie** [comment]
8.x 版本中已经修复，请尽快升级至最新版本
