### ISSUE TITLE
Table: Grouping table head not respecting nzWidthConfig

### ISSUE THREAD

**Issue by Endran** [NG-ZORRO/ng-zorro-antd#3796]
### Reproduction link
[https://2nl1sk.run.stackblitz.io](https://2nl1sk.run.stackblitz.io)

### Steps to reproduce
Open stackblitz, or just go to the official docs https://ng.ant.design/components/table/en#components-table-demo-grouping-columns.
As you can see the Grouped table head is misaligned with the content, and there is some whitespace to the right and bottom of the component.

### What is expected?
A perfectly aligned table head

### What is actually happening?
Not aligned table head, instead some whitespace is present right and bottom

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.3 |
| Browser | Chrome 75, Safari 12.1.1 |

---
It works fine in Firefox 68

**Comment by Endran** [comment]
Let me also add a screenshot, straight from the docs.

<img width="1133" alt="Screen Shot 2019-07-15 at 14 22 55" src="https://user-images.githubusercontent.com/8580144/61216379-7d4b2180-a70d-11e9-8ab4-80f3c4dd2ea4.png">

**Comment by vthinkxie** [comment]
this bug will happen when set `automatically based on input device` in macos

**Comment by Endran** [comment]
I do not understand what you mean with `automatically based on input device`. Is there something we need to do? I guess it needs fixing, since it is an regression compared to the Angular7 version.

**Comment by vthinkxie** [comment]
@Endran I mean this http://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/
it is a bug, and we will fix it in next version.
