### ISSUE TITLE
nz-tree-select 选中节点时树结构会突然一下全展开

### ISSUE THREAD

**Issue by ygwoo** [NG-ZORRO/ng-zorro-antd#3805]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-tree-select-bug-report-demo](https://stackblitz.com/edit/ng-zorro-tree-select-bug-report-demo)

### Steps to reproduce
1、将下拉列表选择数据绑定至[nzNodes]属性；
2、从下拉列表中选择数据，或点击其它空白地方关闭下拉列表；
3、选中或关闭瞬间树结构突然完全展开，会“闪”一下。

### What is expected?
正常选择，选中或关闭树结构时树结构显示状态不会发生改变。

### What is actually happening?
选中或关闭树结构显示状态改变

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.3 |
| Browser | Chrome 75.0.3770.142 |

**Comment by hsuanxyz** [comment]
fix via #3947
