### ISSUE TITLE
ng-ztree rendering performance

### ISSUE THREAD

**Issue by OffieCao** [NG-ZORRO/ng-zorro-antd#3808]
## What problem does this feature solve?
render ng-ztree more fast with big data;
When we use more than 1500 one-time nodes in  ng-zree. Its rendering is very worse. At least 10s from my observation.
## What does the proposed API look like?
[online demo]  https://stackblitz.com/edit/antd-multi-nodes?file=src/app/app.component.ts

**Comment by TxOne** [comment]
组件套组件，无限迭代产生的。
