### ISSUE TITLE
table设置固定表头后样式出现问题

### ISSUE THREAD

**Issue by TxOne** [NG-ZORRO/ng-zorro-antd#3809]
### Reproduction link
[https://stackblitz.com/edit/angular-wfyxbr](https://stackblitz.com/edit/angular-wfyxbr)

### Steps to reproduce
点击Fixed Header选项，开启和关闭表头固定，会发现表头高度样式不一致。

### What is expected?
表头高度在表头固定的情况下不应该改变

### What is actually happening?
表头高度在表头固定的情况下变小

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.3 |
| Browser | Google Chrome  版本 75.0.3770.142（正式版本） （64 位） |

**Comment by vthinkxie** [comment]
fixed in #3806
