### ISSUE TITLE
nztable 全选的问题

### ISSUE THREAD

**Issue by JaouShingan** [NG-ZORRO/ng-zorro-antd#381]
nz-table 用的参数 是nzAjaxData 这个，有分页。

当在第一页的时候，勾上全选，然后点击分页进入下一页，第二页的全选checkbox始终默认被选中。然后再返回第一页，第一页的全选checkbox也默认被选中。进行了以上操作后，有时候甚至会出现table中tbody里的checkbox全部不选中，全选checkbox会变成选中状态的情况。

**Comment by vthinkxie** [comment]
nz-table will not help you to manage data and checkbox status, all status should be maintain by your code.

**Comment by JaouShingan** [comment]
@vthinkxie  
切换的时候把_allChecked 和_indeterminate 强制设定为false， 全选checkbox 依旧是勾选状态，怕不是checkbox组件问题哦

**Comment by vthinkxie** [comment]
@JaouShingan please provide the code or online demo here http://plnkr.co/edit/tpl:sKWy62, it is hard to reproduce your situation only with your description.
https://zhuanlan.zhihu.com/p/25795393

**Comment by JaouShingan** [comment]
@vthinkxie 
 http://plnkr.co/edit/tpl:sKWy62, 这网站点不开。
我还是和你说一点今天发现的情况吧。
就是最简单的带checkbox的表格，nz-table上使用nzAjaxData 这个参数。ts代码基本就是照着官网上的抄下来的。
当表格里有不能选择的checkbox的时候，就会出现进入下一页后全选checkbox 依旧是选中状态的情况。

然后我把 ts里的_refreshStatus()这个方法改成了下面这样就好了。
`
_refreshStatus() {
    const allChecked = this._displayData.every(value => {
		if(value.isChecked === true){
		// 当checkbox可选时
			return value.checked === true;
		} else {
		// 当checkbox不可选时
			return true;
		}
	});
    const allUnChecked = this._displayData.every(value => {
		if(value.isChecked === true){
		// 当checkbox可选时
			return !value.checked
		} else {
		// 当checkbox不可选时
			return true;
		}
	});
    this._allChecked = allChecked;
    this._indeterminate = (!allChecked) && (!allUnChecked);
  };
`

**Comment by vthinkxie** [comment]
@JaouShingan the demo on the ng.ant.design only write code to handle sync data.
If you want to use ajax data with check component in the table, you have to write your own strategy.
