### ISSUE TITLE
Component - rate

### ISSUE THREAD

**Issue by 4val0v** [NG-ZORRO/ng-zorro-antd#3810]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-mgn5yd](https://stackblitz.com/edit/ng-zorro-antd-start-mgn5yd)

### Steps to reproduce
Rating does not work correctly with fractional numbers.
Look in the console - https://ng-zorro-antd-start-mgn5yd.stackblitz.io

### What is expected?
value 3.0 = 3 star

value 4.8 = 5 star

### What is actually happening?
Rating value "3.0" != 3 star :(
![3.0 half star != 3 star](https://i.imgur.com/XwkFe7s.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.3 |
| Browser | Chrome 75.0.3770.100 |

---
```JS
value <= 0.5		// 🌗
value >= 4.5		// 🌕🌕🌕🌕🌕
```<!-- generated by ng-zorro-issue-helper. DO NOT REMOVE -->

**Comment by 4val0v** [comment]
Also remove the `margin` for the last element.
![last star margin](https://user-images.githubusercontent.com/11297476/61415416-37eb4780-a8f9-11e9-84a4-8d76af7801c0.png)
**_Solution:_**
```CSS
li:not(:last-child) {
    margin-right: 8px;
}
```

**Comment by vthinkxie** [comment]
it is quite clear that the rate only accept `number`, but you pass a string to the `ngModel`
https://stackblitz.com/edit/ng-zorro-antd-start-ab1fc3?file=src/app/app.component.ts

**Comment by 4val0v** [comment]
> The string is obviously not equal to a number

Oh yes, indeed, my carelessness😔, thanks🤝

And about the margin, [my message is higher](https://github.com/NG-ZORRO/ng-zorro-antd/issues/3810#issuecomment-512589989)
Create a new issues about this ?

_Now I use:_
```CSS
::ng-deep .ant-rate {
  li {
    margin: 0 4px 0 4px
  }
}
```
You can do it in the source code approximately as I said [above](https://github.com/NG-ZORRO/ng-zorro-antd/issues/3810#issuecomment-512589989).

**Comment by wendzhue** [comment]
For style problems, maybe you should send a pull request to ant design first because style files are synced from there.

**Comment by quangminh-archisketch** [comment]
I want show value 4.7, the Antd support show 3* and 2/3 for the 4th start yet ???
