### ISSUE TITLE
New Statistic component UpTime (CountUp)

### ISSUE THREAD

**Issue by 4val0v** [NG-ZORRO/ng-zorro-antd#3811]
## What problem does this feature solve?
Monitoring server uptime etc...

Specifically, I need a functional that will show how long the server is Offline
## What does the proposed API look like?
Same as Countdown, but also add functionality:
```JS
updateInterval // period for obtaining the date for counting (Appeal to the service that returns `Date()`)
stop // boolean type
```

**Comment by wendzhue** [comment]
You can wrap a component on `nz-statistic `.
