### ISSUE TITLE
upload 组件上传文件bug

### ISSUE THREAD

**Issue by SmallShrimp** [NG-ZORRO/ng-zorro-antd#3813]
#### 文件上传报错：
![image](https://user-images.githubusercontent.com/8120385/61446104-3c5b4300-a981-11e9-90fe-7419c23fa8c4.png)
#### 描述：
![image](https://user-images.githubusercontent.com/8120385/61446239-775d7680-a981-11e9-8236-de9f00b8a8d6.png)
不管怎么配置，结果都一样，示例代码也一样的！

**Comment by SmallShrimp** [comment]
补充：在change事件之前就出错

**Comment by ttwm** [comment]
请问解决了吗？我也遇到这个问题
