### ISSUE TITLE
TimePicker - remove padding !

### ISSUE THREAD

**Issue by 4val0v** [NG-ZORRO/ng-zorro-antd#3816]
### Reproduction link
[https://fqlmnr.run.stackblitz.io](https://fqlmnr.run.stackblitz.io)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/11297476/61474935-56e9e800-a992-11e9-9d4b-75c10c84f76c.png)

### What is expected?
Remove `padding: 0 0 160px;`

### Comment
In the calendar, when choosing a date there are no padding, follow a uniform format

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.3 |
| Browser | Chrome 73 |

**Comment by lppedd** [comment]
It does make sense to have the padding. Helps with top alignment.  
When selecting the time I want to pick it from the top, to have an "aligned overview" of the time.

![image](https://user-images.githubusercontent.com/19871649/61497202-089f0e00-a9bf-11e9-86d0-b493e0fcca66.png)

When there is no padding, it's pretty bad

![image](https://user-images.githubusercontent.com/19871649/61497163-f02ef380-a9be-11e9-9791-4f3a9b0efdb3.png)

**Comment by 4val0v** [comment]
Understood
thanks
