### ISSUE TITLE
1.8.1版本的tag组件页面说明有错误

### ISSUE THREAD

**Issue by W-Abel-jia** [NG-ZORRO/ng-zorro-antd#3819]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-aav3pz](https://stackblitz.com/edit/ng-zorro-antd-start-aav3pz)

### Steps to reproduce
1.  打开页面[NG-ZORRO](https://ng.ant.design)
2.  切换1.8.1版本
3. 切换到tag组件页面

### What is expected?
nzMode="closeable"

### What is actually happening?
nzMode="closable"

| Environment | Info |
|---|---|
| ng-zorro-antd | 1.8.1 |
| Browser | chrome75.0.3770.142（正式版本） |

**Comment by vthinkxie** [comment]
低版本已经全部归档，不再维护，请尽快升级至最新版本
