### ISSUE TITLE
form 表单异步验证，手动验证未通过

### ISSUE THREAD

**Issue by ant-robert** [NG-ZORRO/ng-zorro-antd#3829]
### Reproduction link
[https://zdtpyb.run.stackblitz.io/](https://zdtpyb.run.stackblitz.io/)

### Steps to reproduce
console.log(this.validateForm.valid)  //true
    for (const i in this.validateForm.controls) {
      this.validateForm.controls[i].markAsDirty();
      this.validateForm.controls[i].updateValueAndValidity();
    }
console.log(this.validateForm.valid)  //false

### What is expected?
手动验证通过

### What is actually happening?
手动验证未通过

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
@ant-robert 你的issue中所有的代码都是 angular reactiveform的部分，与 ng-zorro-antd 无关
