### ISSUE TITLE
TreeSelect如何设置只能选中叶子节点，当点击非叶子节点时，只是展开其子节点

### ISSUE THREAD

**Issue by lichangfeng** [NG-ZORRO/ng-zorro-antd#3833]
### Reproduction link
[https://stackblitz.com/edit/angular-3uuec8?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-3uuec8?file=src/app/app.component.ts)

### Steps to reproduce
点击非叶子节点，目前是直接选中，并关闭树

### What is expected?
1.点击非叶子节点，展开其子节点
2.点击叶子节点，选中

### What is actually happening?
点击非叶子节点，目前是直接选中，并关闭树

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | 360浏览器和chrome浏览器 |

**Comment by wendzhue** [comment]
@hsuanxyz 对于这种 case，bot 需要优化一下
