### ISSUE TITLE
Disabling dropdown backdrop works only for the first time and not letting close the dropdown but by selecting an item

### ISSUE THREAD

**Issue by amiram** [NG-ZORRO/ng-zorro-antd#3835]
### Reproduction link
[https://stackblitz.com/edit/angular-q8zww2](https://stackblitz.com/edit/angular-q8zww2)

### Steps to reproduce
Add a dropdown with trigger=click and nzBackdrop=false
Add a button beside that will do something on hover.
Open the dropdown menu and hover on the button - hover effect works. Click on the dropdown button - menu not closed.
Close the menu by selecting an item from it.
Open the dropdown menu and hover on the button - hover effect doesn't work. Click on the dropdown button - menu is closed.

### What is expected?
Hover effect of elements beside always should work. Menu should always be closed when clicking on the dropdown button.

### What is actually happening?
Hover effect works only in the first open.
Menu is not closed when clicking on the dropdown in the first open, only in the next opens.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | Chrome 75 |

**Comment by lppedd** [comment]
Hi @amiram, this is totally my fault, coming from PR https://github.com/NG-ZORRO/ng-zorro-antd/pull/3769.
I have fixed this on https://github.com/NG-ZORRO/ng-zorro-antd/pull/3831

Again, sorry!

**Comment by amiram** [comment]
Thanks a lot for the fix. We all do mistakes all the time.

**Comment by lppedd** [comment]
@amiram It's nothing. Lets wait for them to merge it.
