### ISSUE TITLE
collapse内使用函数会被反复多次调用

### ISSUE THREAD

**Issue by SoaringTiger** [NG-ZORRO/ng-zorro-antd#384]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

以折叠面板 代码演示的第一个例子为例子
```
<nz-collapseset>
      <nz-collapse *ngFor="let panel of panels" [nzTitle]="changeText(panel.name)" [nzActive]="panel.active"
                   [nzDisabled]="panel.disabled">
        <p>{{panel.name}}内容</p>
      </nz-collapse>
</nz-collapseset>
```

添加一个函数，并在模版中调用，会发现changeText**被反复调用了16次**（Chrome 61/ Safari 11）！

```
changeText(t: string): string {
    console.log('changetext');
    return t + ' @abc';
  }
```

## Expected behavior

按说 panels 有几个元素 changeText 就该被调用几次啊？

## Environment

<pre><code>
Angular version: 4.2.4

ng-zorro-antd version: 0.5.2

Browser:
- [x] Chrome (desktop) version 61
- [ ] Firefox version XX
- [x] Safari (desktop) version 11
- [ ] IE version XX
 
For Tooling issues:
- Node version: v8.2.1  
- Platform: Mac 

Others:

</code></pre>

**Comment by SoaringTiger** [comment]
复查了一下，不是 collapse 的问题，写在 collapse 外面也一样会被调用16次之多，想问下问题出在哪里？
`<li *ngFor="let panel of panels">
    {{changeText(panel.name)}}
</li>`

**Comment by SoaringTiger** [comment]
查了一下 原来是 change detection 造成的

**Comment by LinBoLen** [comment]
the problem underneath may still exist. can you provide a minimal reproduction plunkr or other online demo
