### ISSUE TITLE
nzInputGroup同时使用nzAddOnAfter和nzSuffix会出现样式问题

### ISSUE THREAD

**Issue by TxOne** [NG-ZORRO/ng-zorro-antd#3841]
### Reproduction link
[https://stackblitz.com/edit/angular-oy2kja](https://stackblitz.com/edit/angular-oy2kja)

### Steps to reproduce
在<nz-input-group>标签上使用nzSuffix给输入框加上前缀标签，再使用nzAddOnAfter给输入框加上后缀按钮，按钮位置出现问题。

### What is expected?
按钮位置在输入框内的右边无边距。

### What is actually happening?
按钮位置在输入框的右侧，且有边距，按钮边线与输入框边线没对齐。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | Google Chrome 版本 75.0.3770.142（正式版本） （64 位） |

---
使用场景：手机验证码输入框。
因为所有输入框的图标都是用nzSuffix加到nzInputGroup上的，验证码输入框在右侧会有个‘发送验证码’按钮。

**Comment by vthinkxie** [comment]
nzAddOnAfter 只能和 nzAddOnBefore 混用，文档上已经标明

**Comment by TxOne** [comment]
Solution：

### **style.less**
.ant-input-group-addon:last-child {
  padding: 0;
  border: 0;
  & > .ant-btn{
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
  }
}

### **style.css**
.ant-input-group-addon:last-child {
  padding: 0;
  border: 0;
}
.ant-input-group-addon:last-child > .ant-btn{
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
 }
