### ISSUE TITLE
Message: 在 HMR 开发模式下，会导致 Attempt to use a destroyed 异常

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#3845]
## 重现

https://stackblitz.com/edit/angular-uif43a?file=src%2Fapp%2Fapp.component.ts

**步骤：**

- 打开 Stackblitz 后，在 `template: ''` 录入任意字符，触发一次 HMR 的加载
- 点击按钮抛出 `Attempt to use a destroyed`

虽然在生产环境下无影响，但对于 HMR 开发环境下，会非常麻烦，特别是在需要触发 Message 时该错误会导致后续的动作无法继续，非要刷新 `Command + R` 后才会生效。

Version:

- ng-zorro-antd latest

**Comment by wendzhue** [comment]
🤔

**Comment by wendzhue** [comment]
@cipchk I cannot reproduce the problem in a local project. Any idea?

**Comment by cipchk** [comment]
@wendzhue A minimal reproduction link: https://github.com/cipchk/zorro-issues-3845

Setps: 

1. running `npm run hmr`
2. can be click button
3. modified `app.component.html`
4. can't be click button
