### ISSUE TITLE
DatePicker: Option to automatically switch to TimePicker on selecting a date

### ISSUE THREAD

**Issue by Cairon** [NG-ZORRO/ng-zorro-antd#3846]
## What problem does this feature solve?
Users feedback about date/time selection:

After selecting a date, the user have to click on "select time" in order to change the time, change time, and then click ok. Some users even dont see "select time" directly.

It will be smoother for the user to avoid manually switch between views, by doing it automatically after choosing a date.

This could be done by adding options to customize the behavior on selecting date and/or time.

Or expose open/close methods to do it in our component as #3352 with providing event emitter to detect the date selection.
## What does the proposed API look like?
```
<nz-date-picker
      nzShowTime
  ==> nzAutoSwitchTime
      nzFormat="yyyy-MM-dd HH:mm:ss"
      nzPlaceHolder="Select Time"
      (ngModelChange)="onChange($event)"
      (nzOnOk)="onOk($event)"
    ></nz-date-picker>
```

**Comment by wenqi73** [comment]
Please track #3148.
