### ISSUE TITLE
当[nzTotal]="0"时、代码解析少了ul标签、导致分页没显示 /When [nzTotal]="0", the ul tag is missing in code parsing, resulting in no pagination display

### ISSUE THREAD

**Issue by 18334113146** [NG-ZORRO/ng-zorro-antd#3851]
### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
[nzTotal]="0"

### What is expected?
展示默认的分页 / Show the default pagination

### What is actually happening?
分页没显示 / Pagination is not displayed

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | Google Chrome 已是最新版本 版本 75.0.3770.142（正式版本） （64 位） |

**Comment by vthinkxie** [comment]
设计就是这样，nzTotal等于0的时候你期望分页怎么展示？

**Comment by 18334113146** [comment]
zorro没升级之前是不存在这个问题的，当nzTotal等于0就显示“总 0 条数据 分页是默认第一页”

**Comment by vthinkxie** [comment]
这是之前版本的bug，新版本修复掉了，总数据0条分页第一页是不对的

**Comment by 18334113146** [comment]
额   原来是这样。
