### ISSUE TITLE
Timepicker has a default value(08:00:00) when use 'date-fns'

### ISSUE THREAD

**Issue by yy7054wyq5** [NG-ZORRO/ng-zorro-antd#3854]
### Reproduction link
[https://stackblitz.com/edit/angular-zorro-timepicker-bug](https://stackblitz.com/edit/angular-zorro-timepicker-bug)

### Steps to reproduce
* In AppModule
```javascript
@NgModule({
    // ...
    providers   : [
       { provide: NZ_I18N, useValue: en_US },
       { provide: NZ_ICONS, useValue: icons }, 
       { provide: NZ_DATE_LOCALE, useValue: enDateLocale } ]
 })
export class AppModule { }
```
* In html
```html
<nz-time-picker 
    [(ngModel)]="time" 
    [nzDefaultOpenValue]="defaultOpenValue">
</nz-time-picker>
```
* In ts
```javascript
export class NzDemoTimePickerBasicComponent {
    time: Date | null = null;
    defaultOpenValue = new Date(0, 0, 0, 0, 0, 0);
}
```

### What is expected?
No default value in input.

### What is actually happening?
Has a default value(08:00:00).Actually the ngModule value is right.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | google chrome 版本 75.0.3770.142（正式版本） （64 位） |

**Comment by yy7054wyq5** [comment]
Is anybody here?

**Comment by wenqi73** [comment]
@yy7054wyq5 Thank you for report.

**Comment by wushuxuan** [comment]
@wenqi73  请问目前有解决办法么？
