### ISSUE TITLE
select选择器多选的情况下，下拉列表和select输入框距离没有贴在一起

### ISSUE THREAD

**Issue by lait233** [NG-ZORRO/ng-zorro-antd#3855]
### Reproduction link
[https://stackblitz.com/edit/angular-jwy6t4-xhin52](https://stackblitz.com/edit/angular-jwy6t4-xhin52)

### Steps to reproduce
鼠标依次选择 a10 b11  c12 d13。然后用鼠标或者回车键在下拉选项列表里取消选择a10。 select框就会和下拉框出现一段空白距离,

### What is expected?
下拉列表应该和select输入框紧贴在一起

### What is actually happening?
下拉列表和select输入框出现了分开距离

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | chrome74 |

**Comment by vnobo** [comment]
点击X的时候吧。。。这是响应事件的样式问题
