### ISSUE TITLE
Pagination: Can I move the Tooltip  when hover on the page number?

### ISSUE THREAD

**Issue by Mickxuanyuan** [NG-ZORRO/ng-zorro-antd#386]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

When I hover on the number, I will get some info like: "最后一页：3"

## Expected behavior

I need to use i18n to change the word, like: "last page: 3" or can I move the tooltip?

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by tigercosmos** [comment]
The code is [here](
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/pagination/nz-pagination.component.ts#L72), which is:
```html
 <li
        [attr.title]="'最后一页: '+_lastIndex"
        class="ant-pagination-item"
        (click)="_jumpPage(_lastIndex)"
        *ngIf="(_lastIndex>0)&&(_lastIndex!==_firstIndex)"
        [class.ant-pagination-item-active]="_isLastIndex">
        <a>{{_lastIndex}}</a>
      </li>
```

The code make the result as:
```html
<li class="ant-pagination-item ant-pagination-item-active" title="最后一页: 50">
        <a>50</a>
</li>
```

**Comment by vthinkxie** [comment]
@Mickxuanyuan you can follow @tigercosmos 's suggestion as an temp solution.

**Comment by tigercosmos** [comment]
Will it support i18n in the future?

Or maybe we can remove the note "最后一页", because ant design react does not have the note. ( See [this](https://ant.design/components/pagination/))

**Comment by Mickxuanyuan** [comment]
@tigercosmos  I have tried this way to solve this question, but failed. Could you give me detail code about this, or do you have other way to solve it, then I will try it. 
thanks.

**Comment by tigercosmos** [comment]
@Mickxuanyuan Another way is fork this project and delete all Chinese.

**Comment by LinBoLen** [comment]
just fork it

**Comment by tigercosmos** [comment]
seems 0.6.0 becomes support i18n

**Comment by LinBoLen** [comment]
I don't know about it exactly.
it needs ticking time to show

**Comment by tigercosmos** [comment]
Since we support i18n, this should not be a issue anymore?

**Comment by vthinkxie** [comment]
close for supporting i18n now
