### ISSUE TITLE
Nz-table with [nzSize]=" small ,the fixed column backgroundColor is transparent

### ISSUE THREAD

**Issue by Credo-Zhao** [NG-ZORRO/ng-zorro-antd#3864]
### Reproduction link
[https://stackblitz.com/edit/angular-gxzmvb](https://stackblitz.com/edit/angular-gxzmvb)

### Steps to reproduce
nz-table used
1. [nzSize]="'small'" 
2. Fixed Columns and Header (nzScroll.x),
Fixed column background css is : background-color: transparent;

[nzSize] for middle and default no problem.only small

css:
.ant-table-small>.ant-table-content>.ant-table-body>table>.ant-table-tbody>tr>td, .ant-table-small>.ant-table-content>.ant-table-body>table>.ant-table-thead>tr>th, .ant-table-small>.ant-table-content>.ant-table-fixed-left>.ant-table-body-outer>.ant-table-body-inner>table>.ant-table-tbody>tr>td, .ant-table-small>.ant-table-content>.ant-table-fixed-left>.ant-table-body-outer>.ant-table-body-inner>table>.ant-table-thead>tr>th, .ant-table-small>.ant-table-content>.ant-table-fixed-left>.ant-table-header>table>.ant-table-tbody>tr>td, .ant-table-small>.ant-table-content>.ant-table-fixed-left>.ant-table-header>table>.ant-table-thead>tr>th, .ant-table-small>.ant-table-content>.ant-table-fixed-right>.ant-table-body-outer>.ant-table-body-inner>table>.ant-table-tbody>tr>td, .ant-table-small>.ant-table-content>.ant-table-fixed-right>.ant-table-body-outer>.ant-table-body-inner>table>.ant-table-thead>tr>th, .ant-table-small>.ant-table-content>.ant-table-fixed-right>.ant-table-header>table>.ant-table-tbody>tr>td, .ant-table-small>.ant-table-content>.ant-table-fixed-right>.ant-table-header>table>.ant-table-thead>tr>th, .ant-table-small>.ant-table-content>.ant-table-header>table>.ant-table-tbody>tr>td, .ant-table-small>.ant-table-content>.ant-table-header>table>.ant-table-thead>tr>th, .ant-table-small>.ant-table-content>.ant-table-scroll>.ant-table-body>table>.ant-table-tbody>tr>td, .ant-table-small>.ant-table-content>.ant-table-scroll>.ant-table-body>table>.ant-table-thead>tr>th, .ant-table-small>.ant-table-content>.ant-table-scroll>.ant-table-header>table>.ant-table-tbody>tr>td, .ant-table-small>.ant-table-content>.ant-table-scroll>.ant-table-header>table>.ant-table-thead>tr>th {
    padding: 8px;
    background-color: transparent;
}

### What is expected?
Fixed column background css is not background-color: transparent;

### What is actually happening?
Fixed column background-color css is transparent;

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | chrome and firefox |

---
only 8.1.0

**Comment by vthinkxie** [comment]
fixed in https://github.com/NG-ZORRO/ng-zorro-antd/pull/3849
