### ISSUE TITLE
If I don't define nz-list and nz-list-item in the same component, I will get a NullInjectorError

### ISSUE THREAD

**Issue by lanmolsz** [NG-ZORRO/ng-zorro-antd#3867]
### Reproduction link
[https://stackblitz.com/edit/angular-wq3yya](https://stackblitz.com/edit/angular-wq3yya)

### Steps to reproduce
打开重现链接，等待服务启动完成即可看到一个错误：NullInjectorError: No provider for NzListComponent!

Open the replay link and wait for the server to start up to see an error: NullInjectorError: No provider for NzListComponent!

### What is expected?
允许外部传入nz-list-item组件
Allow externally passed in the nz-list-item component

### What is actually happening?
外部传入nz-list-item组件报错
Externally passed in the nz-list-item component  failed

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | chrome版本 75.0.3770.142（正式版本） （64 位） |

**Comment by cipchk** [comment]
`nz-list-item` 需要依赖 `nz-list`，无法单独使用；示例中可以换另一个思路来实现，例如：https://stackblitz.com/edit/angular-wq3yya-msmcfd?file=src/app/my-list.component.ts

**Comment by lanmolsz** [comment]
> `nz-list-item` 需要依赖 `nz-list`，无法单独使用；示例中可以换另一个思路来实现，例如：https://stackblitz.com/edit/angular-wq3yya-msmcfd?file=src/app/my-list.component.ts

感谢及时回复，您的替代实现方式我了解了~我先这样实现。
