### ISSUE TITLE
Input Mask support for nz-inputs

### ISSUE THREAD

**Issue by thinkdj** [NG-ZORRO/ng-zorro-antd#3870]
## What problem does this feature solve?
In enterprise level apps, there is sometimes a need for entering sensitive data fields. Such inputs need to be masked/unmasked. Eg. DOB `19/09/1992` becomes `**/**/****`
## What does the proposed API look like?
`<input nz-input [nzMask]="myPattern" />`

**Comment by lppedd** [comment]
@thinkdj so this is more about obscuring characters right?
I ask because input masking is a pretty complex subject and it's not something I would ask to be re-implemented, see for example https://github.com/RobinHerbots/Inputmask

**Comment by thinkdj** [comment]
@lppedd Zorro is a super-amazing flexible library and I'd LOVE to see actual masks implemented in it too, as that would make it apt for more enterprise applications. 
I do agree with your suggestion too, and would be great if we start with obscuring characters as a start!

**Comment by davidhenley** [comment]
+1

**Comment by wendzhue** [comment]
For now you can use these with `nz-input`:

https://github.com/JsDaddy/ngx-mask#readme

https://github.com/uNmAnNeR/imaskjs/tree/master/packages/angular-imask

**Comment by hsuanxyz** [comment]
https://github.com/text-mask/text-mask/tree/master/angular2/#readme
https://stackblitz.com/edit/angular-42tfkp?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/22736418/62749354-a782cb80-ba8e-11e9-9c72-63cf3618ae34.png)

**Comment by thinkdj** [comment]
@wendzhue @hsuanxyz Thank you for the wonderful suggestions!

**Comment by mattarau** [comment]
I'd like to add that using 3rd party plugins would be fine if the `DatePicker` and `TimePicker` were directives to be used with the `<input> ` tag (like `nz-input`), but since they are components that create an input internally it's not possible to masks their value without a "hack".

**Comment by jonasschumacher** [comment]
@mattarau can you share how did you manage to get masks working with datepicker?

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
