### ISSUE TITLE
表格静态内容不能去除暂无数据提示

### ISSUE THREAD

**Issue by tedeum** [NG-ZORRO/ng-zorro-antd#3871]
注意：不是用 https://ng.ant.design/issue-helper/#/zh 创建的 issue 会被立即关闭。
# 重现
静态数据，就是直接写的tr td 标签，仍然会显示暂无数据
 nzNoResult="" 还是会有
如果是空格  nzNoResult=" "，还有一空白行
# 期望
能去除 暂无数据 提示
# 版本
8.1

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/table/zh#components-table-demo-template
