### ISSUE TITLE
Document for Typography doesn't contain information of imports

### ISSUE THREAD

**Issue by hamzaabamboo** [NG-ZORRO/ng-zorro-antd#3872]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-xy3xki?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-xy3xki?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
Open the web

### What is expected?
Expected that there should be information about importing NzTypographyModule

### What is actually happening?
There is none of that

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | - |

---
-

**Comment by wendzhue** [comment]
@hamzaabamboo Thanks for reporting this. Interested in a PR?

**Comment by wendellhu95** [comment]
From ver 9.0.0 importing `NgZorroAntd` would be deprecated. Which means importing `NzTyppgraphyComponent` would be the default approach. So it is unnecessary to add these lines anymore. I am closing this now. Thanks for your attention.
