### ISSUE TITLE
Tabs - no tab should be active if actual route does not match

### ISSUE THREAD

**Issue by ajeiie120120** [NG-ZORRO/ng-zorro-antd#3873]
### Reproduction link
[https://stackblitz.com/edit/angular-2twhgl](https://stackblitz.com/edit/angular-2twhgl)

### Steps to reproduce
Just append "/5" in the url, the page will be correctly reloaded but the tab "1" will be active even if the "/5" does not match any of the actual tabs links.

### What is expected?
Expected no tab active if the actual route does not match any of the tabs defined links through [routerLink] directive

### What is actually happening?
The first tab is active by default even if its routerLink is not matching with the actual route

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | all |

**Comment by wendzhue** [comment]
@ajeiie120120 Tabs component do not support `nzSelectedIndex === -1`. Check this demo. https://stackblitz.com/edit/angular-nrowfx?file=src/app/app.component.ts

**Comment by ajeiie120120** [comment]
Any news about the fix?

**Comment by vthinkxie** [comment]
@wendzhue try nzHideAll

**Comment by ajeiie120120** [comment]
**[PARTIALLY SOLVED]**
@vthinkxie @wendzhue 

Hi,
now the tabset does not highlight any tab if the relative link is not active.

But it seems that the first tab is not "smart" as the others and cant detect if current route has changed, so it does not react correctly.

You can try this example [https://stackblitz.com/edit/angular-mtudaw](url):

1. At application start no tab is active (great!)
2. Select the "1" tab on the left tabset
3. Select the "6" tab on the right
4. The "1" tab is still highlighted even if the route has actually changed

Same with the "5" tab:
1. Select the "5" tab on the right tabset
2. Select the "2" tab on the left
3. The "5" tab is still highlighted even if the route has actually changed

But with other tabs this will not happen:
1. Select the "2" tab on the left tabset
2. Select the "5" tab on the right
3. Tab "2" will be deactivated correctly

or

1. Select the "6" tab on the right tabset
2. Select the "3" tab on the left
3. Tab "6" will be deactivated correctly


Thanks a lot quick support, 
you're doing a great job.

**Comment by wendzhue** [comment]
@ajeiie120120 Hi. Thank you for these issues. We have fixed them problem. Please verify it in the next version.

**Comment by ajeiie120120** [comment]
@wendzhue thanks for the update, it works fine now.

The issue can be closed, great work!
