### ISSUE TITLE
[bug] plnkr template need import `BrowserAnimationsModule`

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#388]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

**Comment by trotyl** [comment]
Updated, could you confirm if it's working now?

**Comment by cipchk** [comment]
it works!
