### ISSUE TITLE
IE11下Input样式问题

### ISSUE THREAD

**Issue by xLong1029** [NG-ZORRO/ng-zorro-antd#3881]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-18xg5e?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-18xg5e?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
ng-alain version: 8.1.0
Angular version: 8.1.2
在以上版本，IE11下Input样式问题：使用带图标的Input组件时，占位符位置没与图标对称，偏下，影响外观

### What is expected?
占位符位置与图标对称

### What is actually happening?
占位符位置没与图标对称，偏下，影响外观

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.0 |
| Browser | IE11 |

![62027199-a9879780-b20f-11e9-826c-d9a0fd0256c2](https://user-images.githubusercontent.com/18066675/62031596-55ce7b80-b21a-11e9-8ca4-94fcf8897cc8.jpg)

**Comment by vthinkxie** [comment]
will fix in https://github.com/NG-ZORRO/ng-zorro-antd/pull/3863/files#diff-9

**Comment by vthinkxie** [comment]
duplicated #3700
