### ISSUE TITLE
[bot] 增加 delete-merged-branch

### ISSUE THREAD

**Issue by orzyyyy** [NG-ZORRO/ng-zorro-antd#3887]
## What problem does this feature solve?
Merge PR 后自动删除创建的分支。

## What does the proposed API look like?
https://github.com/apps/delete-merged-branch/

**Comment by wendzhue** [comment]
现在是从 fork 的仓库发起的 PR，而非这个主仓库，这个 bot 还能删除别人仓库的分支吗？

**Comment by orzyyyy** [comment]
不能。看了下，主仓库似乎不需要这个
