### ISSUE TITLE
nz-table使用build --prod报错

### ISSUE THREAD

**Issue by buzzers** [NG-ZORRO/ng-zorro-antd#3892]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-t2vqek](https://stackblitz.com/edit/ng-zorro-antd-start-t2vqek)

### Steps to reproduce
```
ng new NgVirtualTable
cd NgVirtualTable
ng add ng-zorro-antd
```
之后将重现链接中的app文件夹整体复制并覆盖新建的工程中的原app文件夹。

编译。
 ```
ng build --prod
``` 

### What is expected?
正常编译。

### What is actually happening?
```
ERROR in Illegal State: referring to a type without a variable {"filePath":"******/ClientApp/node_modules/ng-zorro-antd/table/ng-zorro-antd-table.d.ts","name":"NzTrDirective","members":[]}
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Chrome75 |

**Comment by vthinkxie** [comment]
welcome module 里面没有引入 ng zorro 的任何模块，再看一下 angular 文档关于模块引入的一章
