### ISSUE TITLE
如何更改颜色主题?

### ISSUE THREAD

**Issue by Feng-JY** [NG-ZORRO/ng-zorro-antd#39]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Expected behavior

如何更改颜色主题?

**Comment by vthinkxie** [comment]
Not supported yet.

**Comment by sishenwuda** [comment]
是不是可以考虑把组件内部引入的样式文件，导入到style下的index里面。类似material2一样，在style.css里面导入这个文件。

**Comment by shaodahong** [comment]
@vthinkxie This can be supported,  If you don't want the default blue

**Comment by lyc152** [comment]
现在还是不可以更改颜色主题吗

**Comment by crowncoder** [comment]
什么时候能更改颜色主题啊

**Comment by lizhuangs** [comment]
好像现在只有一套主题？默认这套太简洁了。主要是看起来太白了，组组又显得比较小巧。

**Comment by LinBoLen** [comment]
theme implement is on schedule in my project. but its use scss. write less and scss is really a huge budget work. waiting to see the feedback from ng zorro team


I almost have implemented a scss style. seems like that it's impossible to switch to scss by antd team currently. so right now ng zorro is also unlikely use scss.

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed

**Comment by wunaidage** [comment]
非常好奇官网的那个改变主题色的功能是是怎么实现的...

**Comment by andersonmadeira** [comment]
Excuse me for not speaking chinese, but I found a workaround with this:
```html

<nz-spin nzSimple [nzIndicator]="indicatorTemplate"> </nz-spin>

<ng-template #indicatorTemplate>
    <i nz-icon nzType="loading" style="font-size: 75px;"></i>
    <span class="loading-text" style="font-size: 25px; display: block; margin-top: 5px;">Loading...</span>
</ng-template>
```
