### ISSUE TITLE
加入ng-zorro-antd开发热更新速度很慢

### ISSUE THREAD

**Issue by zhouhuiquan** [NG-ZORRO/ng-zorro-antd#3900]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?embed=1&file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start?embed=1&file=src/app/app.component.ts)

### Steps to reproduce
ng new demo
ng add ng-zorro-antd

### What is expected?
开发预览速度快点
chrome开发工具performance 脚本执行时间长达3秒

### What is actually happening?
开发预览速度很慢
chrome开发工具performance 脚本执行时间在1秒以内

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | chrome@latest |

---
链接没用, 第一次提交这么标准的问题, 不会用

**Comment by vthinkxie** [comment]
https://ng.ant.design/docs/getting-started/zh#%E5%8D%95%E7%8B%AC%E5%BC%95%E5%85%A5%E6%9F%90%E4%B8%AA%E7%BB%84%E4%BB%B6

**Comment by unnhao** [comment]
> 如果只想使用单个组件，请参考，一次引入60多个组件模块肯定会降低热更新速度
> https://ng.ant.design/docs/getting-started/zh#%E5%8D%95%E7%8B%AC%E5%BC%95%E5%85%A5%E6%9F%90%E4%B8%AA%E7%BB%84%E4%BB%B6

如果使用Shared Module的方式整在一包，是否會很慢？是不是還是應該每個Module各自引入。
