### ISSUE TITLE
nz-sider 布局出现滚动条时底部出现空白

### ISSUE THREAD

**Issue by consunmida** [NG-ZORRO/ng-zorro-antd#3908]
### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
nzsider 自定义触发器，当菜单栏数目多，出现纵向滚动条时，底部会出现空白

### What is expected?
没有空白

### What is actually happening?
有空白

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Chrome |

**Comment by consunmida** [comment]
![image](https://user-images.githubusercontent.com/20217537/62282959-1a82b580-b483-11e9-9e02-1917ab845c3c.png)
[https://ng-zorro-antd-start-z13kqm.stackblitz.io](url)

**Comment by wendzhue** [comment]
给 `nz-sider` 加上 `overflow-y: scroll` 即可。
