### ISSUE TITLE
Notification error

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#391]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

当我引入NzNotificationService时页面运行报错
![tim 20170928154500](https://user-images.githubusercontent.com/9586655/30954788-11b80102-a464-11e7-9826-de4fdf465de4.png)

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
please provide the code to reproduce the error here 
http://plnkr.co/edit/tpl:sKWy62

**Comment by wanghaolu** [comment]
@vthinkxie  you can try this.
http://plnkr.co/edit/IRYjRRf0vYhVaLhEsaz0?p=preview

**Comment by vthinkxie** [comment]
@wanghaolu thanks for your feedback, @wilsoncook please check this question.

**Comment by wilsoncook** [comment]
May usage error or bug refer to angular/angular#20515
