### ISSUE TITLE
NzDatePicker  : How do I force the time is 0:00 instead of current time ?

### ISSUE THREAD

**Issue by John0King** [NG-ZORRO/ng-zorro-antd#3912]
## What problem does this feature solve?
When I only want user pick the Date,  that really mean it  `date` +  "00:00:00  +8:00",
I  see https://ng.ant.design/components/date-picker/zh  , it is indeed 00:00 for local time !! how do I do the same ? (I'm using version 7.2)

## What does the proposed API look like?
Is there a attribute to set this behavier ?

**Comment by wendzhue** [comment]
For old versions, please set the time by yourself. Use `Date.prototype.setHours`.
