### ISSUE TITLE
nz-table implement defaut automatic sort and filter 

### ISSUE THREAD

**Issue by John0King** [NG-ZORRO/ng-zorro-antd#3917]
## What problem does this feature solve?
most sort and filter function are almost the same , 

## What does the proposed API look like?
`<th nzShowSort nzSortKey="name"  />`  will use the default sort function
the defaut sort implement will be something like this
```ts
sort(e: { key: string, value: "ascend" | "descend" | null }) {
        if (e.value != null) {
            this.dataOriginal= this.data.filter(x => true); // copy the data
            this.data= this.dataOriginal.filter(x => true).sort((a, b) => e.value === "ascend" ? a[e.key] > b[e.key] ? 1 : -1  : a[e.key] < b[e.key]? 1:-1)
            
        }
        else {
            this.data= this.dataOriginal;
        }
    }
```
the same logic can be applied to the filter : `[nzFilters]` can be extract from the `data` property, compare function using js operator `==`

**Comment by wendzhue** [comment]
看不懂，你可以用中文。

**Comment by John0King** [comment]
我本来以为排序功能是自动的，结果发现还得自己写。我的建议是让 nzTable 实现默认的排序和筛选功能，毕竟大部分排序功能（本地排序）是相同的，就是比较大小而已， 对于筛选就是 比较相等， 再 nzTable  的 `thead` 上实现一个默认的排序和筛选程序理论上是可能的，我上面的是 排序的代码。

**Comment by vthinkxie** [comment]
table组件所有数据逻辑都由用户控制，不会引入一部分由组件控制，一部分由用户控制的行为（100%会导致数据冲突）

**Comment by John0King** [comment]
@wendzhue  
> table组件所有数据逻辑都由用户控制，不会引入一部分由组件控制，一部分由用户控制的行为（100%会导致数据冲突）

我不认同这一点
首先， 用户给的数据已经被Table组件控制（分页），用户操作自己的array， table利用模板循环控制的是 `tableInstance.data`
再者，不是组件控制的和用户控制的混合， 而是 单个行为的默认，  `<thead  (nzSortChange)="" (nzFilterChange)="">`  , 只是当用户未绑定时 有一个默认行为，当用户绑定自己的处理函数后， 这个行为就交给用户了

**Comment by vthinkxie** [comment]
所有的数据是由你传入的`[nzData]` 来控制的，你可以在任何时刻修改你的 `[nzData]` 来实现你想要的任何效果（包括排序、筛选、反转、删除），组件提供给你的永远都是事件（包括sortChange，filterChange），你也可以在任何时机去修改，包括增加一个button按钮去筛选，或者排序。
组件并没有操作你传入 `[nzData]`的数据，模板控制循环的是 view 的一部分，并不是数据的一部分

**Comment by John0King** [comment]
@vthinkxie   但是  `tableInstance.data` 相较于 [nzData] 已经是复制的数据，并且被截取了一部分处理。
我的意思是:
```
@Output()
nzSortChange = new EventEmiter<any>()

OnInit(){
  nzSortChange.subscribe((e)=>{
    if(this.nzSortChange.observers.length <= 1){ // when no other subscripbe
        this.currentSort = e;
       //handled in 
       // get data(){  return this.nzData.filter(x=>true).sort((a, b) => e.value === "ascend" ? a[e.key] > b[e.key] ? 1 : -1  : a[e.key] < b[e.key]? 1:-1) }
   }
})
}
```

或者添加一个属性，明确 是否让table组件自己去处理

这样，当用户自己订阅事件的时候， 可以跟自己的 `[nzData]` 去交互， table组件不再替用户去处理， 当用户自己不去处理的时候， sort 和 filter 交给table组件去处理， 而模板上还是跟以前一样，用 `tableInstance.data` 就好了

**Comment by vthinkxie** [comment]
@John0King 用户自己排序只需要一行代码，增加API需要给每个事件都区分是前端处理还是后端处理，何况排序和筛选不同的用户有完全不同的需求，组件根本不会知道排序和筛选的key是什么，还需要增加筛选函数的输入。除了增加复杂度没有带来任何好处。

**Comment by John0King** [comment]
> 增加API需要给每个事件都区分是前端处理还是后端处理，何况排序和筛选不同的用户有完全不同的需求，组件根本不会知道排序和筛选的key是什么，还需要增加筛选函数的输入

 - 组件处理，只处理本地传入的 `[nzData]`, 后台排序需要自己监听 `nzSortChange` 和 `nzFilterChange`， 不要用Input 输入自己函数， 要么让组件自动处理， 要么自己处理
-  只要手工订阅（如果增加 `nzAutosort:boolean`, 和 `nzAutoFilter:boolean` 就是当明确用户接管）则组件不再处理，用户需要自己操作 传入 [nzData] 的值。

> 组件根本不会知道排序和筛选的key是什么

目前组件可以知道排序的键， 毕竟 `nzSortKey`  , 筛选需要增加一个 `nzFilterKey`， 组件利用它进行筛选项的提取（就是去重），和执行比较

> 没有带来任何好处。

- 目前排序和筛选（本地），如果自己处理， 必须自己复制一份数据，取消排序和筛选又需要还原， 组件处理可以解决本次 排序和筛选的这个蛋疼问题， 而且排序代码几乎再任何地方都是相同的， 却需要再多个调用nzTable 的地方重复去写
- 对于筛选而言，在无特殊需要的情况下，对于筛选面板处理以及筛选这个的功能， 对于用户而言可以节省很大一部分代码
-  （这个纯属个人感觉）nzTable 提供了分页数据处理的自动化（本地），同时引出了一个  tableInstance.data 来，给我的感觉， 只要我用 data, 分页筛选排序都应该起作用才对，毕竟他是已经加工过的数据， 比如 Excel, 只要你贴入表格数据，就可以对列进行筛选和排序
