### ISSUE TITLE
datepicker怎样设置组件值，想用LocaleDateString: 'yyyy-mm-dd', 不想用ISOString()

### ISSUE THREAD

**Issue by wgf4242** [NG-ZORRO/ng-zorro-antd#3928]
### Reproduction link
[https://stackblitz.com/edit/angular-zorro-datepicker](https://stackblitz.com/edit/angular-zorro-datepicker)

### Steps to reproduce
随便选值，显示的都是"2019-08-06T16:00:00.000Z" ISO格式。
中间有很多道步骤，不方便在提交时处理。需要在组件中给出期望日期。

### What is expected?
2019-08-06

### What is actually happening?
2019-08-06T16:00:00.000Z

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Chrome |

**Comment by wendzhue** [comment]
大哥这是 JavaScript Date 对象
