### ISSUE TITLE
nzDataChange error

### ISSUE THREAD

**Issue by robinv8** [NG-ZORRO/ng-zorro-antd#394]
when nztable's property is nzAjaxData,then ngDataChange fails

**Comment by vthinkxie** [comment]
nzAjaxData is the same as current page data, there is no need to use this callback function.

**Comment by robinv8** [comment]
when the property is nzAjaxData,then checkbox function fails

**Comment by vthinkxie** [comment]
nz-table will not maintain checkbox status, you have to maintain the status with your code
duplicated #381

**Comment by robinv8** [comment]
l see ,thank you
