### ISSUE TITLE
nzMaskClosable="true" not working

### ISSUE THREAD

**Issue by aleksander351** [NG-ZORRO/ng-zorro-antd#3946]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-dii2lb](https://stackblitz.com/edit/ng-zorro-antd-start-dii2lb)

### Steps to reproduce
building a basic nz-modal, setting nzMaskClosable="true", opening modal, does not close the modal on clicking outside modal.

### What is expected?
when setting nzMaskClosable="true", it is expected to close the modal dialog when the mask (area outside the modal) is clicked

### What is actually happening?
It is not closing.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | Chrome |

**Comment by NearZXH** [comment]
I think it's maybe a bug for `ng-zorro`. You can fix it by add `(nzOnCancel)="handleCancel()"`, here is a [demo](https://stackblitz.com/edit/ng-zorro-antd-start-cmhz2h)

**Comment by wenqi73** [comment]
`nzOnCancel` is required, and now it's also written in the document (https://ng.ant.design/components/modal/en)
> Specify a function that will be called when a user clicks mask, close button on top right or Cancel button
