### ISSUE TITLE
nz-tree component when set nzShowLine to true then icon will be always displayed in the leaf node even set nzShowIcon to false

### ISSUE THREAD

**Issue by YuchenWell** [NG-ZORRO/ng-zorro-antd#3959]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-jckxsj](https://stackblitz.com/edit/ng-zorro-antd-start-jckxsj)

### Steps to reproduce
NZ-Tree Component 
- nzShowLine === true && nzShowIcon === false

### What is expected?
icon not display in this situation

### What is actually happening?
icon displayed at this situation

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Chrome 76.0 |

**Comment by simplejason** [comment]
`nzShowIcon` is only used with `NzTreeNode.icon`, it will hide user's icon, like this https://stackblitz.com/edit/angular-qbcvyc?file=src/app/app.component.ts
