### ISSUE TITLE
nz-table hover style missing when nzSize is small

### ISSUE THREAD

**Issue by YuchenWell** [NG-ZORRO/ng-zorro-antd#3961]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-tty7mw](https://stackblitz.com/edit/ng-zorro-antd-start-tty7mw)

### Steps to reproduce
nz-table hover style error when nzSize is small

### What is expected?
hover on table item have normal style like default or middle size!

### What is actually happening?
no style

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Chrome 76.0 |

**Comment by vthinkxie** [comment]
fixed, will release in next version.
