### ISSUE TITLE
setup extra [nzExtra] for collapse header, collapse panel will close or open when clicking icon button of extra content

### ISSUE THREAD

**Issue by xueqingxiao** [NG-ZORRO/ng-zorro-antd#3964]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-iwyevu](https://stackblitz.com/edit/ng-zorro-antd-start-iwyevu)

### Steps to reproduce
Click settings icon

### What is expected?
fire click event of settings icon and do not close or opening collapse panel.

### What is actually happening?
close or opening collapse panel.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Chrome Latest |

**Comment by wendzhue** [comment]
![Screen Shot 2019-08-12 at 4 08 29 PM](https://user-images.githubusercontent.com/12122021/62852257-7c60dc00-bd1b-11e9-953a-2c23921bfee6.png)

You can stop the event yourself. See the demo of the React version. https://ant.design/components/collapse-cn/#components-collapse-demo-extra

**Comment by xueqingxiao** [comment]
@wendzhue we'd better reorganize dom structure. it does not solve this issue through the root cause. if you guys are busy. I'm glad to help. (:

**Comment by vthinkxie** [comment]
@xueqingxiao we keep the same DOM with react version, you can submit pr to antd react if necessary

**Comment by wendzhue** [comment]
If you really wanna do that you don't have to change the dom. You can check if the click event's target is contained by the extra element. Use `contains()` method.

**Comment by wendzhue** [comment]
This issue is closed for now because of this is a by-design of Ant Design. Welcome to open an issue or pull request in the React version first.

**Comment by xueqingxiao** [comment]
@vthinkxie @wendzhue but antd react version is working what we expected. you can check the last demo of antd react and angular.

**Comment by wendzhue** [comment]
Have you read my reply? https://github.com/NG-ZORRO/ng-zorro-antd/issues/3964#issuecomment-520333174

**Comment by xueqingxiao** [comment]
> Have you read my reply? [#3964 (comment)](https://github.com/NG-ZORRO/ng-zorro-antd/issues/3964#issuecomment-520333174)

my bad. I will try to send a pr for antd react first.
