### ISSUE TITLE
将按钮宽度调整为其父宽度的选项失效

### ISSUE THREAD

**Issue by LZHD** [NG-ZORRO/ng-zorro-antd#3968]
### Reproduction link
[https://lzhd.github.io/button-bug/welcome](https://lzhd.github.io/button-bug/welcome)

### Steps to reproduce
ng new test
ng add ng-zorro-antd
添加如下代码

`<button nz-button nzType="primary" nzBlock>Primary</button>`

### What is expected?
按钮充满父宽度

### What is actually happening?
开发环境下按钮可以充满父宽度，生产环境样式丢失

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | chrome 76.0.3809.100 |

**Comment by wendzhue** [comment]
重现链接无效，请检查。

我们的官网是有效的 https://ng.ant.design/components/button/zh#components-button-demo-block

**Comment by LZHD** [comment]
@wendzhue 
代码: https://github.com/LZHD/button-bug
重现链接: https://lzhd.github.io/button-bug/welcome
只是在生产环境下有问题

**Comment by vthinkxie** [comment]
看上去是 @InputBoolean 方法在 prod 模式下失效了

**Comment by vthinkxie** [comment]
@LZHD 
只在 target 为 es2015 下会有这个问题，可以暂时使用 [nzBlock]="true" 的方式，我们在想办法解决了

**Comment by vthinkxie** [comment]
ref https://blog.angularindepth.com/converting-typescript-decorators-into-static-code-using-tsquery-tstemplate-and-transforms-8c65d606a517

**Comment by vthinkxie** [comment]
ref https://github.com/angular/angular-cli/issues/15301

**Comment by LZHD** [comment]
好的，万分感谢。

**Comment by LZHD** [comment]
fix [angular/angular-cli#15314](https://github.com/angular/angular-cli/pull/15314)
