### ISSUE TITLE
nzTree的nzHideUnMatched无效

### ISSUE THREAD

**Issue by wuzhiji37** [NG-ZORRO/ng-zorro-antd#3970]
### Reproduction link
[https://stackblitz.com/edit/angular-xcwhng](https://stackblitz.com/edit/angular-xcwhng)

### Steps to reproduce
搜索框输入A

### What is expected?
未匹配数据隐藏

### What is actually happening?
未匹配数据未隐藏

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Google Chrome 76.0.3809.100 |

**Comment by wuzhiji37** [comment]
Hello? Any one fix it?

**Comment by simplejason** [comment]
> still a bug in v8.3.1

not yet, maybe it will be fixed in next version if we have finished
