### ISSUE TITLE
Got double ghost menu when use 'NzContextMenuService' to create two different context menu.

### ISSUE THREAD

**Issue by tonyeen** [NG-ZORRO/ng-zorro-antd#3971]
### Reproduction link
[https://stackblitz.com/edit/angular-hqkzfz?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-hqkzfz?file=src/app/app.component.ts)

### Steps to reproduce
1. Right click  "Context Menu 1" area. (Don't close the opened context menu)
2. Right click "Context Menu 2"

### What is expected?
Get clear context menu of "Context Menu 2" area when right click on it.

### What is actually happening?
Got double ghost menu when use 'NzContextMenuService' to create two different context menu.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Chrome 75  |

**Comment by alfadb** [comment]
大佬，这个问题什么时候可以解决啊？现在生成环境客户意见好大

**Comment by tonyeen** [comment]
> 大佬，这个问题什么时候可以解决啊？现在生成环境客户意见好大

未修复之前可以禁用 `nzDropdownMenu` 的动画效果， 添加属性 ` [nzNoAnimation]="true"` 即可。

[参考示例](https://stackblitz.com/edit/ng-zorro-antd-start-zxbae9?file=src%2Fapp%2Fapp.component.html)
