### ISSUE TITLE
when "enableIvy": true  => 'date-fns' entry-point Error 

### ISSUE THREAD

**Issue by luke-emmental** [NG-ZORRO/ng-zorro-antd#3975]
### Steps to reproduce
package.json
{  
  "dependencies": {
    "@angular/animations": "^8.2.1",
    "@angular/common": "^8.2.1",
    "@angular/compiler": "^8.2.1",
    "@angular/core": "^8.2.1",
    "@angular/forms": "^8.2.1",
    "@angular/platform-browser": "^8.2.1",
    "@angular/platform-browser-dynamic": "^8.2.1",
    "@angular/router": "^8.2.1",
    "@nrwl/schematics": "^8.4.8",
    "core-js": "^2.5.4",
    "ng-zorro-antd": "^8.1.2",
    "rxjs": "~6.5.2",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.802.1",
    "@angular/cli": "8.2.1",
    "@angular/compiler-cli": "^8.2.1",
    "@angular/language-service": "^8.2.1",
    "@nrwl/cypress": "8.4.8",
    "@nrwl/jest": "8.4.8",
    "@nrwl/workspace": "8.4.8",
    "@types/jest": "24.0.9",
    "@types/node": "~8.9.4",
    "codelyzer": "~5.0.1",
    "cypress": "^3.4.1",
    "dotenv": "6.2.0",
    "jest": "24.1.0",
    "jest-preset-angular": "^7.1.1",
    "prettier": "1.16.4",
    "ts-jest": "24.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.5.3"
  }
}
//tsconfig.app.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": []
  },
  "include": ["**/*.ts"],
  "exclude": ["src/test-setup.ts", "**/*.spec.ts"],
  "angularCompilerOptions": {
    "enableIvy": true
  }
}

### What is expected?
app serve successful 

### What is actually happening?
ERROR in There is no appropriate source code format in '/{project path}/node_modules/date-fns' entry-point.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | chrome |

**Comment by wendzhue** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/3712
