### ISSUE TITLE
DatePicker doesn't recognize manual date input when using nzFormat

### ISSUE THREAD

**Issue by AmeBitto** [NG-ZORRO/ng-zorro-antd#3976]
### Reproduction link
[https://stackblitz.com/edit/angular-a8d35n](https://stackblitz.com/edit/angular-a8d35n)

### Steps to reproduce
Add DatePicker component and set nzFormat="dd.MM.yyyy".
```javascript
<nz-date-picker [(ngModel)]="date" nzFormat="dd.MM.yyyy"></nz-date-picker>
```
Manual input works only if date and month are same. For example, if we type 04.04.1995 it works, but 04.05.1995 is not working.

### What is expected?
After writing string date, DatePicker changes date in the model.

### What is actually happening?
Nothing happens

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Chrome 76 |

---
Default format working fine

**Comment by wenqi73** [comment]
Thanks for your report, we will support it until `dateFns` release 2.0.0. (#2492 also reported it)

**Comment by darshanrampatel** [comment]
@wenqi73 date-fns has now [released 2.0.0](https://github.com/date-fns/date-fns/releases/tag/v2.0.0?fbclid=IwAR3rrkytHDkVBxKk6FJOocMHp3qtLn4HZyYnqrD28JfC3QSfYUnXI4_67k4) so can this be looked at again please?

**Comment by wenqi73** [comment]
@darshanrampatel Sure, we will work it out soon.

**Comment by soulasvalentin** [comment]
Hello! Are there any updates on this? Thanks!

**Comment by valerio-lucantonio** [comment]
Guys any update?

**Comment by binle** [comment]
I think problem is here:
components/date-picker/lib/calendar/calendar-input.component.ts

```
 onInputKeyup(event: KeyboardEvent, isEnter: boolean = false): void {
    const date = this.checkValidInputDate(event);

    if (!date || (this.disabledDate && this.disabledDate(date.nativeDate))) {
      return;
    }

    this.value = date;
    this.valueChange.emit({ date, isEnter });
  }
```
```
  private checkValidInputDate(event: Event): CandyDate | null {
    const input = (event.target as HTMLInputElement).value;
    const date = new CandyDate(input);

    this.invalidInputClass = '';
    if (!date.isValid() || input !== this.toReadableInput(date)) {
      // Should also match the input format exactly
      this.invalidInputClass = `${this.prefixCls}-input-invalid`;
      return null;
    }

    return date;
  }
```
Problem is **const date = new CandyDate(input);** You should support new CandyDate with dev's format.

**Comment by xdrago1** [comment]
is it working now?

**Comment by wenqi73** [comment]
@xdrago1 You should import date-fns by providing `NZ_DATE_LOCALE`. 
https://ng.ant.design/docs/i18n/en#how-to-format-a-date-using-date-fns

**Comment by codersgyan** [comment]
I managed to solve this issue using date-fns Locale. 
I was looking for the Russian date format (dd.mm.yyyy). By changing prop `nzFormat="dd.mm.yyyy"`, it didn't work. 
So what I did is, In` app.module.ts`. 

```
import { ru as RU} from 'date-fns/locale';

providers: [
    { provide: NZ_DATE_LOCALE, useValue: RU },
  ],

```
By doing this, all my date pickers worked fine.
