### ISSUE TITLE
Problems of nz-cascader

### ISSUE THREAD

**Issue by AlcheXie** [NG-ZORRO/ng-zorro-antd#399]
## I'm submitting a...

<pre><code>
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

**Bugs**

1. If I set **nzOptions** in a asynchronous way, simultaneously give **ngModel** a default value, **ngMode** will change to an empty array because of **ngOnChanges**. (demo-cascader-basic)
2. If I give **ngModel** a default value of which length is greater than 1, pressing **'↑'** or **'↓'** does not work as **_nzColumns[n] (n >= 1)**  is not defined, pressing **‘→’** also does not work as a result.
3. When **ngModel**'s value is undefined or an empty array (include after clearing value), pressing **‘→’** cannot active the second column.
4. Press **'←'** when activeOptions's length is 1, placeholder shows and is covered by the display label.

**Features**

5. It selects option and closes menu when selected option's **isLeaf** is true by pressing arrows.
6. **chidren** and **isLeaf** properties' name may conflict with an option object's.

## Expected behavior

5. I can select option by pressing ENTER, only active options by pressing arrows.
6. Add inputs for property name, like **nzValueProperty**.

**Comment by vthinkxie** [comment]
Hi, @AlcheXie  please check the version 0.7.0, the bug should be fixed in the version.

**Comment by AlcheXie** [comment]
Hi, @vthinkxie @fbchen sorry I'm late.

To **1**, problem described above has been solved.
However, a new bug has been given while in the same condition (setting **nzOptions** in a asynchronous way and giving **ngModel** a default value).
The performance is:
-a. Related options are not selected.
-b. If initial value of **ngModel** is an array of string that only contains values (not labels) of options, initial showing text will show a combining string of these values. But text should show labels of selected options.

To **6**, I consider that **nzChildrenProperty** and **nzLeafProperty** are also necessary.

**Comment by vthinkxie** [comment]
@fbchen
