### ISSUE TITLE
select nzAutoFocus设置后并没有获得默认焦点

### ISSUE THREAD

**Issue by Cyclone77** [NG-ZORRO/ng-zorro-antd#3991]
### Reproduction link
[https://stackblitz.com/edit/angular-rq9df5](https://stackblitz.com/edit/angular-rq9df5)

### Steps to reproduce
<nz-select nzAutoFocus
      nzShowSearch
      nzServerSearch>
</nz-select>

### What is expected?
nzAutoFocus 设置后默认焦点生效

### What is actually happening?
nzAutoFocus 设置后没有效果

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | google76 |

**Comment by xawill** [comment]
Any update on this ?

**Comment by CreatingBUG521** [comment]
When will this problem be solved?
