### ISSUE TITLE
VSCODE代码片断已出发，坐等ng-zorro发布！

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#4]
ng-zorro 的 vscode 代码片断：[ng-zorro snippets](https://marketplace.visualstudio.com/items?itemName=cipchk.ng-zorro-vscode)

![help](https://user-images.githubusercontent.com/2987467/29163045-d3f0332c-7ded-11e7-8a48-a763ea641a9b.gif)

## 安装扩展

按 `F1` 输入 `ext install ng-zorro-vscode` 后回车。

## 如何使用?

你可以任意 `.html`、`.ts` 文件，输入 `nz-` 开头会自动出现在智能提醒列表当中；仅此而已！

**Comment by stbui** [comment]
.
