### ISSUE TITLE
Please Don't Use Field `_prefixCls`.

### ISSUE THREAD

**Issue by LinBoLen** [NG-ZORRO/ng-zorro-antd#40]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

```
@Component({
  selector     : 'nz-button-group',
  encapsulation: ViewEncapsulation.None,
  template     : `
    <div [ngClass]="_classMap" #groupWrapper>
      <ng-content></ng-content>
    </div>
  `,
  styleUrls    : []
})
export class NzButtonGroupComponent implements AfterContentInit {
  _size: NzButtonGroupSize;
  _prefixCls = 'ant-btn-group';
  _sizeMap = { large: 'lg', small: 'sm' };
  @ViewChild('groupWrapper') _groupWrapper: ElementRef;
```

## Expected behavior

please don't use  ` _prefixCls = 'ant-btn-group';`

## What is the motivation / use case for changing the behavior?

- class filed will consume memory when instance, simplify field will benefit performance.

- UI framework/component, should be welcome to developer just using COPY/PASTE command, simplify field will lead developer just focus on data associate field whitch commonly related to binding data.

- ui `class name`, `html tag` should simple behave as literal exactly. please use string function or string operator as less as possible. (developer can just find or replace what he need globally)
- i see some `_prefixCls`with string combine style. like `[ant-tag-${this.nzColor}]  : isPresetColor,`this sames like less/scss problem. the real effect style should be `ant-tag someofngcolor`

fininally, i insist on simplify field. and `_prefixCls` field should be removed.

## Environment

<pre><code>

Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:

- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by LinBoLen** [comment]
I'm trying to make pull request this weekend.

**Comment by vthinkxie** [comment]
@LinBoLen 
to be discussed, please not pr yet.
thanks.

**Comment by LinBoLen** [comment]
thanks, i can get an right voice from your team. i have to deep custom `ng-zorro` with some featured component.  preview of style break change will adjust weight of my work feature.


closed

**Comment by vthinkxie** [comment]
_prefixCls class is sync with ant design it self.
I don't think it will often change, don't worry about it too much.
