### ISSUE TITLE
栅格中，<p class="height-500">设置高度不起作用

### ISSUE THREAD

**Issue by okuc** [NG-ZORRO/ng-zorro-antd#400]
示意代码如下：
`<nz-card style="width:500px;height:690px;">
  <ng-template #body>
    <div class="gutter-example">
     
      <div nz-row [nzGutter]="0" [nzType]="'flex'" [nzJustify]="'space-around'"  [nzAlign]="'middle'">
          <div nz-col [nzSpan]="4">
              <p class="height-400">col-4</p>
            </div>
      </div>
    </div>

  </ng-template>
</nz-card>
`

如上设置后，高度不起作用。

**Comment by vthinkxie** [comment]
height-400 should be a class name define in your css code, it is not provided by the component.

**Comment by okuc** [comment]
原来如此，谢谢。
