### ISSUE TITLE
Select field is empty if there are some pre-selected Items in the component

### ISSUE THREAD

**Issue by shohrukh92** [NG-ZORRO/ng-zorro-antd#4000]
### Reproduction link
[https://stackblitz.com/edit/angular-fxhfwu?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-fxhfwu?file=src/app/app.component.ts)

### Steps to reproduce
1. Run the demo app from docs: "Hide already selected options in the dropdown"
2. Initialize selected items array with some values: listOfSelectedValue: string[] = ['Apples', 'Bananas'];

### What is expected?
Pre-selected Items should be displayed as tags in the Select field (i.e. 'Apples', 'Bananas').

### What is actually happening?
The Select field is empty if there is pre-selected Items in the component.
This might be the case if we are using "nz-select" as a form field and we want to patch form with some previously saved data during Form initialization.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.0 |
| Browser | Any browser |

**Comment by littleinsz** [comment]
Same question.
I have a nz-select in a nz-dropdownMenu.When close dropdown and reopen it.Pre-selected Items are missing.

**Comment by vthinkxie** [comment]
> Same question.
> I have a nz-select in a nz-dropdownMenu.When close dropdown and reopen it.Pre-selected Items are missing.

plz check https://github.com/NG-ZORRO/ng-zorro-antd/issues/1455
it is the bug of angular

**Comment by vthinkxie** [comment]
@shohrukh92 plz check this https://github.com/NG-ZORRO/ng-zorro-antd/issues/4000#issue-480195237

**Comment by shohrukh92** [comment]
@vthinkxie I've checked but it seems like #4000 is related to something different. From what I understand the tags in the `Select field` is generated based on items in the dropdown list itself. So when we want to hide selected items in the list, this issue is happen.

**Comment by vthinkxie** [comment]
@shohrukh92 it should be https://github.com/NG-ZORRO/ng-zorro-antd/issues/1455

**Comment by vthinkxie** [comment]
Hi @shohrukh92 
we will provide `nzHide` in next version, use it instead of `*ngIf`, everything will work fine
