### ISSUE TITLE
isMatched not set when rebuilding tree by setting nzData with nzTreeTemplate

### ISSUE THREAD

**Issue by wollerman** [NG-ZORRO/ng-zorro-antd#4001]
### Reproduction link
[https://stackblitz.com/edit/angular-w9iuev?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-w9iuev?file=src/app/app.component.ts)

### Steps to reproduce
Click the "Reload" button in the stackblitz.
Or create a tree component with a custom template, reference it with ViewChild and try to use `this.tree.nzSearchValue`.

### What is expected?
The component should update with highlighting. The nz-tree-node component should get the `isMatched` values and calculate matches. You can comment out the custom template to see how it should happen.

### What is actually happening?
The tree node just doesn't get updates and highlighting fails.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | chrome |

**Comment by simplejason** [comment]
- check this: https://stackblitz.com/edit/angular-w9iuev-waryg5?file=src/app/app.component.ts
- and your code has errors:
```html
<ng-template #nzTreeTemplate let-node>
  {{node.isMatched}}  
  <ng-container *ngIf="node?.isMatched">
    *** you don't define highlightKeys and nzSearchValue
    {{highlightKeys[0]}}<span class="font-highlight">{{nzSearchValue}}</span>{{highlightKeys[1]}}
  </ng-container>
  <ng-container *ngIf="!node?.isMatched">
    {{node.title}}
  </ng-container>
</ng-template>
```
you can use `nzHighlight` pipe of `ng-zorro-antd`:
```html
<ng-template #nzTreeTemplate let-node>
  {{node.isMatched}} -  
    <span class="ant-tree-title" [innerHTML]="node.title | nzHighlight: searchValue: '' : 'font-highlight'">
    </span>
</ng-template>
```

**Comment by wollerman** [comment]
Thanks @simplejason. Is `nzHighlight` a documented pipe? I don't see it when searching documentation.

**Comment by wenqi73** [comment]
Maybe we should add it to the document too. 🤔

**Comment by simplejason** [comment]
This issue has been closed due to inactivity.
