### ISSUE TITLE
feat progress: should support gradient color and success percent for circle and dashboard

### ISSUE THREAD

**Issue by wendzhue** [NG-ZORRO/ng-zorro-antd#4005]
Need refactoring.

**Comment by genhaodegenhao** [comment]
目前type为circle和dashboard时不能实现渐变吧？
nzType=circle/dashboard，Not currently available to gradient？

**Comment by wendzhue** [comment]
> 目前type为circle和dashboard时不能实现渐变吧？
> nzType=circle/dashboard，Not currently available to gradient？

已经在 #3933 中支持，预计 8.3.0 上线。
