### ISSUE TITLE
固定表头，nzWidth设置小一点其它列就对不齐

### ISSUE THREAD

**Issue by liuliangjia** [NG-ZORRO/ng-zorro-antd#4012]
### Reproduction link
[https://stackblitz.com/edit/angular-je18zt](https://stackblitz.com/edit/angular-je18zt)

### Steps to reproduce
https://stackblitz.com/edit/angular-je18zt

### What is expected?
表中列多的时候，如何快速调整每一列的合适宽度？

### What is actually happening?
表中列多的时候，如何快速调整每一列的合适宽度？

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.0 |
| Browser | Chrome 版本 76.0.3809.100（正式版本） （64 位） |

**Comment by liuliangjia** [comment]
目前我把所有的tbody td 加上  style="word-break:break-all"  这样来解决。
当然thead tr th 也还得加nzWidth

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-je18zt-camy8s?file=src/styles.css
