### ISSUE TITLE
Descriptions 组件 nzSpan 在有边框水平方向的情况下和其他情况效果不一致

### ISSUE THREAD

**Issue by zpdf** [NG-ZORRO/ng-zorro-antd#4013]
### Reproduction link
[https://stackblitz.com/edit/angular-gdkgur](https://stackblitz.com/edit/angular-gdkgur)

### What is expected?
  有边框水平方向和其他情况下一致

### What is actually happening?
  有边框水平方向和其他情况下一致

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.0 |
| Browser | chrome 76.0.3809.100 |

**Comment by wendzhue** [comment]
设计如此，水平有边框的情况下，title 要占用单独的一格。
