### ISSUE TITLE
nz-table hover style error when nzSize is small and column is fixed

### ISSUE THREAD

**Issue by YuchenWell** [NG-ZORRO/ng-zorro-antd#4018]
### Reproduction link
[https://stackblitz.com/edit/angular-eacq8q-csyzao](https://stackblitz.com/edit/angular-eacq8q-csyzao)

### Steps to reproduce
nz-table   small size   fixed column 
hover on table row

### What is expected?
fixed column has hover style in this situation like default or middle size 

### What is actually happening?
style missing

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.0 |
| Browser | Chrome 76.0 |

**Comment by vthinkxie** [comment]
fixed in latest version, closed
