### ISSUE TITLE
我在使用官网的布局组件例子中，发现有个别元素没有 '_ngcontent-c1'属性，导致的问题是，自定义的css样式对此元素失效。我在浏览器中审查元素中，手动给此元素加上'_ngcontent-c1'属性，自定义的css样式就生效了。请问这是什么问题？

### ISSUE THREAD

**Issue by DearSW** [NG-ZORRO/ng-zorro-antd#402]

**Comment by vthinkxie** [comment]
_ngcontent-c1 is just a className generated by Angular ViewEncapsulation.Emulated
please read 
https://angular.io/api/core/ViewEncapsulation
https://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html
