### ISSUE TITLE
Possibility to choose the type of the link in a rich-text tool (make it external)

### ISSUE THREAD

**Issue by SKaistrenko** [NG-ZORRO/ng-zorro-antd#4022]
## What problem does this feature solve?
When content editors use the tool, it might be too complex for them to type in raw HTML that has target="_blank"
## What does the proposed API look like?
Provide additional input when a user chooses to add a link, allowing to set the link to be external.

**Comment by wendzhue** [comment]
What does `the tool` means?

**Comment by SKaistrenko** [comment]
Rich text editor

**Comment by wendzhue** [comment]
We don't have this component.

**Comment by SKaistrenko** [comment]
I'm sorry, I guess I misunderstood
