### ISSUE TITLE
nz-tree 组件，当[nzData] 使用setTimeout获取时，[nzSelectedKeys] 失效

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd#4026]
### Reproduction link
[https://stackblitz.com/edit/angular-yqrn3n?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-yqrn3n?file=src/app/app.component.ts)

### Steps to reproduce
[nzData] 使用setTimeout赋值，[nzSelectedKeys] 直接赋值

### What is expected?
nz-tree 可以正确选中 [nzSelectedKeys] 指定节点

### What is actually happening?
nz-tree 没有选中 [nzSelectedKeys] 指定节点

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.0 |
| Browser | chorme 76 |

**Comment by Cyclone77** [comment]
首先你的结构赋值有问题defaultSelectedKeys = [...'0-0-0'];这样是数组["0", "-", "0", "-", "0"]

**Comment by dusdong** [comment]
@Cyclone77 我的结构赋值是有问题。但 defaultSelectedKeys 参数在 [nzData] 异步获取后失效的问题也确实存在。感谢你提供的方法，我也暂时先这么处理下。
