### ISSUE TITLE
Cascader可设置默认显示值

### ISSUE THREAD

**Issue by s641135196** [NG-ZORRO/ng-zorro-antd#4029]
## What problem does this feature solve?
例如，工单页面关联了公司组织结构信息， 如某个公司组织结构被软删除,  这样会导致显示不了值。（当然可以用disable属性，但它会显示到界面。）

## What does the proposed API look like?
例如:  defaultLabel='公司-事业部'

**Comment by wendzhue** [comment]
不是很明白你的需求。能用 disable 属性做一个复现看看吗？

**Comment by s641135196** [comment]
@wendzhue  谢谢了， 我又试了下， 发现有2种设置值的方法，第二种满足需求的
