### ISSUE TITLE
nz-descriptions component is not entirely themeable

### ISSUE THREAD

**Issue by krokofant** [NG-ZORRO/ng-zorro-antd#4031]
## Version
8.2.0

## Environment
all

## Description
Descriptions is missing a theme variable for the item label backgrounds https://github.com/NG-ZORRO/ng-zorro-antd/blob/8.2.0/components/descriptions/style/index.less#L100

**Comment by krokofant** [comment]
I see this is an upstream issue. Created a new issue there https://github.com/ant-design/ant-design/issues/18372

**Comment by wendzhue** [comment]
@krokofant Thanks you for opening these pull requests (we are enjoying a free ride 😎

**Comment by krokofant** [comment]
@wendzhue @vthinkxie If an issue like this was fixed upstream should it still be mentioned in the ng-zorro release notes after the upstream is synced to ng-zorro?

Like now I'm keeping track of when [this PR from the bot is merged](https://github.com/NG-ZORRO/ng-zorro-antd/pull/4075) but ideally I'd want to keep track of the ng-zorro release notes. Thanks for your insights.
