### ISSUE TITLE
ng-zorro-antd update from 7.2.0 to 8.2.0, aot error: <nullinjectorerror: no provider for overlay!>

### ISSUE THREAD

**Issue by pokemonfan7** [NG-ZORRO/ng-zorro-antd#4032]
### Reproduction link
[https://stackblitz.com/edit/i-did-not-write](https://stackblitz.com/edit/i-did-not-write)

### Steps to reproduce
it is not necessary, just AOT occur error

### What is expected?
no error

### What is actually happening?
nullinjectorerror: staticinjectorerror(appmodule)[overlay]: staticinjectorerror(platform: core)[overlay]: nullinjectorerror: no provider for overlay!

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.0 |
| Browser | google chrome 76.0.3809.100 |

**Comment by wendzhue** [comment]
Have you tried to remove node_modules, package-lock.json and reinstall?

**Comment by pokemonfan7** [comment]
yes, i only update ng-zorro-antd, 7.2.0 is no problem, but 8.2.0 has error

**Comment by vthinkxie** [comment]
@pokemonfan7 ng-zorro-antd depends on @angular/cdk, plz make sure you have install the correct version.
if you install 8.2.0 ng-zorro-antd with @angular/cdk 7.x, it must have an error

**Comment by pokemonfan7** [comment]
i update @angular/cdk and then the problem is resolved, but i have tried this and it did not work before.  i think the problem is npm package cache.
