### ISSUE TITLE
select控件初始值就算不在下拉列表也应要能正常显示

### ISSUE THREAD

**Issue by s641135196** [NG-ZORRO/ng-zorro-antd#4033]
## What problem does this feature solve?
如公司部门， 这部门名称可能会变动或删除， 这会导致引用这部门名称就显示不了。 

## What does the proposed API look like?
:defaultValue={value:'开发部',label: '开发部' } , 如果列表中的不存在就显示这个DefaultValue的值。

**Comment by hungtcs** [comment]
我感觉这个不属于基础Select组件的问题，你可以对`nz-select`组件进行再次封装实现这种自定义的需求

**Comment by vthinkxie** [comment]
duplicated #3672
