### ISSUE TITLE
there's no guide I can follow when execute ng add ng-zorro-antd 

### ISSUE THREAD

**Issue by cyhjojo** [NG-ZORRO/ng-zorro-antd#4046]
### Reproduction link
[https://ng-zorro-antd-start-p7c1xh.stackblitz.io/](https://ng-zorro-antd-start-p7c1xh.stackblitz.io/)

### Steps to reproduce
When I first carried out this order today, the guide showed up.However then, I deleted the project for some reason. After that, I tried to do the same steps several times with the same name of the project, but there's no guide anymore.

### What is expected?
How can I fix it?

### What is actually happening?
No guide shows up.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.0 |
| Browser | chrome |

**Comment by wendzhue** [comment]
What do you mean 'the guide'? Can you provide screenshots?
