### ISSUE TITLE
Not able to reset search value of a nz-transfer component

### ISSUE THREAD

**Issue by ah787264643** [NG-ZORRO/ng-zorro-antd#4048]
## What problem does this feature solve?
For now, there is no api to reset serach value of a nz-transfer component when nzShowSearch is set true.

## What does the proposed API look like?
add ngModel for nz-transfer or something alike.

**Comment by cipchk** [comment]
You can reset data via `nzSearchChange` event.

**Comment by ah787264643** [comment]
> You can reset data via `nzSearchChange` event.

Tried, will not work. I checked the source code, this value seems not setable .

**Comment by cipchk** [comment]
@ah787264643 Can u provide a reproduct link?

**Comment by sasyesp03** [comment]
I know the issue has been closed but there is still no way to reset the search value of the transfer component. Should i make a new issue?
