### ISSUE TITLE
dropdown-menu overflow hidden

### ISSUE THREAD

**Issue by dasoncheng** [NG-ZORRO/ng-zorro-antd#4054]
### Reproduction link
[stackblitz.io](https://stackblitz.com/edit/angular-paf61b)
![image](https://user-images.githubusercontent.com/16243342/68564983-1fe19a00-048d-11ea-9087-d754fdcc0693.png)

### Steps to reproduce
select submenu, but the display of menu-item is not complete

### What is expected?
display complete

### What is actually happening?
display not complete

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | Chrome 76.0.3809.100 |

**Comment by dasoncheng** [comment]
@vthinkxie 
![image](https://user-images.githubusercontent.com/16243342/68097266-ffe03280-fef0-11e9-9056-36a35613f3f1.png)

**Comment by dasoncheng** [comment]
anyone can fix that? @afc163

**Comment by wenqi73** [comment]
You can use `nzMenuClassName` to control the submenu's style.
