### ISSUE TITLE
Calender能否更灵活一点

### ISSUE THREAD

**Issue by FuQunYing** [NG-ZORRO/ng-zorro-antd#4059]
## What problem does this feature solve?
在项目中，有需要在日历中加入对应日期数据的需求，虽然可以自定义日期格子内的内容，但是使用时不如像使用table那样方便，比如我们不需要年月的切换和时间的切换，但是没有对应的API隐藏掉，只能通过找到它的的class，对这个class进行css的隐藏。

## What does the proposed API look like?
比如这样：
<nz-calender [nzShowHeader]="false"></nz-calender>

**Comment by wenqi73** [comment]
目前还没计划加 input，就先用 CSS。🤔
