### ISSUE TITLE
Problems of nz-menu with deactivate guard

### ISSUE THREAD

**Issue by fuybooo** [NG-ZORRO/ng-zorro-antd#407]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

When I want to change a route, but the deactivate guard of the current route return a <code>false</code>,so I should not leave the current  menu item, but the class 'ant-menu-item-selected' has been added to the menu item that I clicked one.

## Expected behavior

It should have a property to control this situation.

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
Hi @fuybooo 
can you reproduce the situation at http://plnkr.co/edit/tpl:sKWy62 ?
