### ISSUE TITLE
virtualTable多次改变nzData的条数，数据排序会错乱

### ISSUE THREAD

**Issue by 007GitHu** [NG-ZORRO/ng-zorro-antd#4071]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
初始化时数据[nzData]="listOfData"是十条数据：for (let i = 0; i < 10; i  )，i从1开始
步骤一：单击按钮1时，将listOfData数据改变为7条，并且for循环中，(let i = 5; i <12; i  ),i从5开始；
步骤二：在单击按钮2，，将listOfData数据改变为5条，并且for循环中，(let i = 9; i < 14; i  ),i从9开始；
步骤三：重复步骤1会发现数据项的顺序已经被打乱了，

### What is expected?
多次改变数据项时，let-index="index"，index排序正常、并且数据的顺序不会变

### What is actually happening?
多次改变数据项时，let-index="index"，index排序不正常、数据的顺序也会变

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | 谷歌 |

---
版本8.2.0也会有这种问题

**Comment by 007GitHu** [comment]
如何提供呢，有列子么

**Comment by 007GitHu** [comment]
https://ng-zorro-antd-start.stackblitz.io/

**Comment by vthinkxie** [comment]
<img width="1068" alt="屏幕快照 2019-08-27 下午3 17 37" src="https://user-images.githubusercontent.com/1506722/63749356-d4800c80-c8dd-11e9-8324-932c1bd842ae.png">

**Comment by 007GitHu** [comment]
写好代码，如何编译生成可以访问的链接呢

**Comment by 007GitHu** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-dxqft1?file=src/app/app.component.ts

**Comment by qinzheng2019** [comment]
加了trackBy之后，nzData动态变化，数据排序依然会乱，求教。
Angular 8.0.0
nz-zorro-antd 8.0.0
