### ISSUE TITLE
NZ Table , sorting th only ASC and DESC

### ISSUE THREAD

**Issue by alexberro** [NG-ZORRO/ng-zorro-antd#4081]
### Reproduction link
[https://angular-s4nyi3.stackblitz.io](https://angular-s4nyi3.stackblitz.io)

### Steps to reproduce
Just click on a th.

You will have desc sorting , asc sorting and "default" sorting

### What is expected?
I would like to set only asc and desc sorting

### What is actually happening?
I'm ordering by desc and sorting but remain the possibility to see two icon grey ( like default)

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | All browser |

**Comment by wenqi73** [comment]
Maybe need a `sortDirections` input.

**Comment by vthinkxie** [comment]
supported in v9 now 
https://next.ng.ant.design/components/table/en#components-table-demo-sort-filter
