### ISSUE TITLE
The danger button's display style is inconsistent with the example of official documents.

### ISSUE THREAD

**Issue by xixixixixiao** [NG-ZORRO/ng-zorro-antd#4087]
#### Step to reproduce

- new `Angular` app
- add `NG-ZORRO`
- edit the `app.component.html`, add a `danger` button

```html
<button nz-button nzType="danger">Danger</button>
```

The danger button's display style is inconsistent with the example of official documents.

In the example of official documents,  the `danger` button's style is the **red** background,  **white** foreground (white text).
![Snipaste_2019-08-30_12-11-39](https://user-images.githubusercontent.com/13077617/63992641-5c088e00-cb1f-11e9-9d37-896588aff943.png)

However, in my test example, the `danger` button's style is the **white** background, **red** foreground (red text).
![Snipaste_2019-08-30_12-11-11](https://user-images.githubusercontent.com/13077617/63992640-5b6ff780-cb1f-11e9-85a6-bbaaa2c5d64b.png)

### What is expected?
Consistent with the example of official documents, that is, the danger button's style is the **red** background,  **white** foreground (white text).

### What is actually happening?
the `danger` button's style is the **white** background, **red** foreground (red text).

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Google Chrome Version 74.0.3724.8 / Firefow 68.0.2 (64-bit) |

**Comment by vthinkxie** [comment]
plz mind the version of your local ng-zorro-antd
our doc is built with the published versoin of ng-zorro-antd, exactly the same as the one you download.
