### ISSUE TITLE
nz-table Gets all the data currently displayed

### ISSUE THREAD

**Issue by master-mazihao** [NG-ZORRO/ng-zorro-antd#4089]
## What problem does this feature solve?
Due to the demand, too frequent updating of the data in the table will cause the problem of stagnation. This function solves the problem of CPU overload.

## What does the proposed API look like?
Get each row of data currently displayed, and then act on the relevant data (e.g., bulk subscription).

**Comment by vthinkxie** [comment]
(nzCurrentPageDataChange)

**Comment by master-mazihao** [comment]
My table is not paginated. Where do I scroll to get every row of data displayed on the screen

**Comment by vthinkxie** [comment]
virtualScroll also have api to get in view data
