### ISSUE TITLE
NzModalService's method 'onOk' cannot find 'this'

### ISSUE THREAD

**Issue by tigercosmos** [NG-ZORRO/ng-zorro-antd#409]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

`app.component.ts`
```
import { Component } from '@angular/core';
import { NzModalService } from 'ng-zorro-antd';

@Component({
  selector: 'my-app',
  template: `
    <button nz-button [nzType]="'info'" (click)="showConfirm()">
      <span>确认对话框</span>
    </button>
  `,
  styles  : []
})
export class AppComponent {
  showConfirm = () => {
    console.log('outside: ', this);
    this.confirmServ.confirm({
      title: '您是否确认要删除这项内容',
      content: '<b>一些解释</b>',
      onOk() {
        console.log('inside: ', this);
      },
      onCancel() {
      }
    });
  }

  constructor(private confirmServ: NzModalService) {
  }
}
```

and the console get
```
outside:  Object { confirmServ: Object, showConfirm: AppComponent/this.showConfirm() }  app.component.ts:29:25   app.component.ts:34:33

inside:  undefined
```

as the result, `onOk` method cannot find `this`, which is `AppComponent`  itself. This issue will cause the methods in `AppComponent` inside `onOk` do not work.

## Environment

<pre><code>
Angular version: 4.3.6

ng-zorro-antd version: 0.5.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by tigercosmos** [comment]
`let that = this;` can solve the issue, but I am not sure if it is a bug or caused by the native JS mechanism.

```
showConfirm = () => {
    let that = this;
    console.log('outside: ', that);
    this.confirmServ.confirm({
      title: '您是否确认要删除这项内容',
      content: '<b>一些解释</b>',
      onOk() {
        console.log('inside: ', that);
      },
      onCancel() {
      }
    });
  }
```

**Comment by HsuanXyz** [comment]
Uses arrow functions instead of shorthand syntax.

```typescript
showConfirm = () => {
    console.log('outside: ', this);
    this.confirmServ.confirm({
      title: '您是否确认要删除这项内容',
      content: '<b>一些解释</b>',
      onOk: () => {
        console.log('inside: ', this)
      },
      onCancel() {
      }
    });
  }
```

**Comment by tigercosmos** [comment]
@HsuanXyz  Your solution did not work.
```
Uncaught (in promise) DOMException: Quota exceeded.     angular-ng-zorro-antd.stackblitz.io/_sw_.js:1
```

**Comment by vthinkxie** [comment]
@tigercosmos please reproduce the error here http://plnkr.co/edit/tpl:sKWy62

**Comment by tigercosmos** [comment]
https://stackblitz.com/edit/angular-ng-zorro-antd-8yeyy4 
F12  and click the button to see console

**Comment by vthinkxie** [comment]
@tigercosmos https://stackblitz.com/edit/angular-ng-zorro-antd-l9lkp6?file=app/app.component.ts
works fine here

**Comment by tigercosmos** [comment]
Yes, it looks good. Seems I did wrong at somewhere.
Thanks!
