### ISSUE TITLE
TimePicker组件在ngModelChange中控制nzOpen会导致组件无法绑定ngModal

### ISSUE THREAD

**Issue by YAN7** [NG-ZORRO/ng-zorro-antd#4090]
### Reproduction link
[https://stackblitz.com/edit/angular-77okeu?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-77okeu?file=src/app/app.component.ts)

### Steps to reproduce
点开重现demo可以看到，TimePicker组件在ngModelChange中控制nzOpen会导致组件无法绑定ngModal，demo代码如下：
import { Component } from '@angular/core';

@Component({
  selector: 'nz-demo-time-picker-value',
  template: `
    <nz-time-picker 
    nzFormat="HH:00"
    [(ngModel)]="time" 
    (ngModelChange)="log($event)"
    [(nzOpen)]="open"
    ></nz-time-picker>
  `
})
export class NzDemoTimePickerValueComponent {
  time: Date | null = null;
  open;

  log(time: Date): void {
    console.log(time && time.toTimeString());
    this.open = false;
  }
}

### What is expected?
可以正常绑定ngModel

### What is actually happening?
ngModelChange中控制nzOpen会导致组件无法绑定ngModal

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | chrome 76.0.3809.100 |

---
产品需要选完时间后自动关闭选择框，如果不控制nzOpen,timePicker组件选完组件是不会自动关闭的

**Comment by wenqi73** [comment]
先加个 `setTimeout` 吧 🤨
