### ISSUE TITLE
Timepicker options not available in DateTimePicker

### ISSUE THREAD

**Issue by shoobham** [NG-ZORRO/ng-zorro-antd#4098]
## What problem does this feature solve?
There are some properties which are present in the TimePicker component but missing in DatePicker. For example, nzMinuteStep is present in TimePicker and allows the developer to show a selective options but the same functionality is not present in the Time selection options of the DatePicker. We need to use the date picker time and show the time slots similar to that provided already in the TimePicker component
## What does the proposed API look like?
<nz-date-picker
      [nzMinuteStep]="15"
      nzFormat="HH:mm"
      [nzMode]="dateMode"
      nzShowTime
      (nzOnOpenChange)="handleDateOpenChange($event)"
      (nzOnPanelChange)="handleDatePanelChange($evennt)" >
    </nz-date-picker>

**Comment by dhiraj007** [comment]
Could you please expedite this. Thanks in advance.

**Comment by stygian-desolator** [comment]
Seems to have been fixed
https://stackblitz.com/edit/angular-kvrxqk?file=src/app/app.component.ts
