### ISSUE TITLE
tootlip文字提示多次点击，页面左上角会多出来一个黑块

### ISSUE THREAD

**Issue by renzhuoyan0** [NG-ZORRO/ng-zorro-antd#4103]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
tootlip文字提示多次点击，页面左上角会多出来一个黑块

### What is expected?
不会出现多余的黑块

### What is actually happening?
会出现黑块

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser |  76.0.3809.132 |

**Comment by michael2043** [comment]
同样的问题，而且多出的黑块会叠加

**Comment by wendzhue** [comment]
@michael2043 能够写一个复现吗，帮助我们排查这个问题。

**Comment by michael2043** [comment]
StackBlitz上再现不出来，只能在我的工程里的某个操作下才能出现。我把控制台截给你们看看吧

![1](https://user-images.githubusercontent.com/4134458/65827083-2e029f00-e2c1-11e9-8f49-5d24e11375d7.jpg)
![2](https://user-images.githubusercontent.com/4134458/65827085-31962600-e2c1-11e9-9615-abcbdf6e77c5.jpg)

**Comment by vthinkxie** [comment]
bug repro https://stackblitz.com/edit/angular-r36j27?file=src/app/app.component.ts

**Comment by wendzhue** [comment]
@michael2043 I will take a deeper investigation into this. Thank you for your comment.

**Comment by michael2043** [comment]
还是有同样的问题，同样还原至7.5.1不再现

**Comment by vthinkxie** [comment]
closed by #4387
