### ISSUE TITLE
Wrong item rendered in <nz-select>'s input box when clicking on <nz-option> with trackBy and changed nzData

### ISSUE THREAD

**Issue by Mensu** [NG-ZORRO/ng-zorro-antd#4107]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-select-wrong-item-bug?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-select-wrong-item-bug?file=src/app/app.component.html)

### Steps to reproduce
1. Open https://stackblitz.com/edit/ng-zorro-antd-select-wrong-item-bug?file=src/app/app.component.html
2. Input a '2' in the input box
3. Select option '2'

### What is expected?
It is '2' that is in the input box.

### What is actually happening?
'11' is in the input box instead.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Chrome 76.0.3809.132 (UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36) |

---
1. I am using `trackBy: trackByValue` on `<nz-option>`, which simply returns self value, i.e `(value) => value`. The bug disappears after removing `trackBy: trackByValue`.
2. I am using `searchKey` emitted by `nzOnSearch` to reduce the amount of `nzData` myself by `.filter()` and `.slice()` because the dropdown of `<nz-select>` is slow to open, which may also be the cause of the bug.

If these two usages are wrong, please let me know the right ones. Thanks in advance!

**Comment by vthinkxie** [comment]
your function trackByValue is actual trackByIndex, the first param in the function is index
https://stackblitz.com/edit/ng-zorro-antd-select-wrong-item-bug-6r8z2s?file=src/app/app.component.ts
plz read the angular doc
https://angular.io/api/core/TrackByFunction

**Comment by Mensu** [comment]
@vthinkxie Thanks for your correction❤️

According to https://angular.io/api/common/NgForOf#ngForTrackBy, the default `trackBy` is already `trackByIdentity` i.e. `<T>(index: number, item: T) => item`, so I don't need to write it myself.  I thought the default `trackBy` was `trackByIndex`. I should have read the doc carefully😓
