### ISSUE TITLE
IE9 is not supported by the official website

### ISSUE THREAD

**Issue by PollionChang** [NG-ZORRO/ng-zorro-antd#411]
在官方api的描述中对于浏览器支持

支持环境

现代浏览器和 IE9 以上（需要 polyfills）。

但是当我用IE9打开  [官方API](https://ng.ant.design/#/docs/angular/introduce) 的时候发现有 报错。

具体错误原因是由于没有对web animation进行兼容性处理 （requestAnimationFrame is  undefined）

那么是否所有组件都对ie9友好？有没有不太建议在ie9下使用的组件

**Comment by gin-lsl** [comment]
我也遇到了这个问题，似乎组件都用到了 WebAnimation，希望可以有避过的方法。

**Comment by PollionChang** [comment]
@gin-lsl   可以手动添加方法解决这个问题，但是本身官网不支持ie9。。选型的时候有点难受。。

**Comment by vthinkxie** [comment]
@gin-lsl @PollionChang need to add requestAnimationFrame polyfill.

**Comment by PollionChang** [comment]
@vthinkxie  Thanks for your reply
I have worked it out and suggest that The official website is support with IE9,although it's not very urgent,it's going to be a good experience after improvement ~

**Comment by vthinkxie** [comment]
@PollionChang thanks for your feedback.
