### ISSUE TITLE
nz-select nzOnSearch request need debounce

### ISSUE THREAD

**Issue by qingfengyijiu** [NG-ZORRO/ng-zorro-antd#4114]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-pj288q](https://stackblitz.com/edit/ng-zorro-antd-start-pj288q)

### Steps to reproduce
when you input characters, the component will request data. But the first request need wait 2000ms, while the later request can return immediately. So, the old data but return later will cover the new data but return earlier.

### What is expected?
The list shows new data.

### What is actually happening?
The list shows old data.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
(nzOnSearch)="nextEvent($event)"
you can add your debounce in nextEvent function

**Comment by ReinerRunge** [comment]
This is not how debounce works?
If you add a debounce in the nextEvent function it will just wait and then do the search anyway...
Please provide an example if I am not understanding correctly...

**Comment by ReinerRunge** [comment]
> (nzOnSearch)="nextEvent($event)"
> you can add your debounce in nextEvent function

This is not how debounce works?
If you add a debounce in the nextEvent function it will just wait and then do the search anyway...
Please provide an example if I am not understanding correctly...
