### ISSUE TITLE
After the production build project, the Table checkbox and expand display are missing, and the Search Box display is not normal.

### ISSUE THREAD

**Issue by kainonly** [NG-ZORRO/ng-zorro-antd#4117]
### Reproduction link
[https://stackblitz.com/edit/angular-3vkifu](https://stackblitz.com/edit/angular-3vkifu)

### Steps to reproduce
It is normal in stackblitz and cannot be reproduced, when I build a real project, the Table checkbox and expand display are missing, and the Search Box display is not normal.

```shell
ng build --prod
```

### What is expected?
I hope to display normal after build

### What is actually happening?
display is not normal
![TIM截图20190904183207](https://user-images.githubusercontent.com/9986159/64247937-75a43e00-cf42-11e9-82c1-b58e6ea5170e.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Google Chrome  75.0.3770.90 |

---
When I set angular.json's buildOptimizer to false, it will display normally.

**Comment by vthinkxie** [comment]
if you are using old version of angular cli, plz upgrade to the latest

it is a bug of angular cli and fixed in the latest version
https://github.com/NG-ZORRO/ng-zorro-antd/issues/3968
https://github.com/angular/angular-cli/issues/15301
