### ISSUE TITLE
Badge did not show the nzCount when i use ngIf

### ISSUE THREAD

**Issue by zomixi** [NG-ZORRO/ng-zorro-antd#4121]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ji4osj](https://stackblitz.com/edit/ng-zorro-antd-start-ji4osj)

### Steps to reproduce
There is no

### What is expected?
Show nzCount

### What is actually happening?
Did not  show nzCount

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Google Chrome 版本 76.0.3809.132（正式版本） （64 位） |

**Comment by wendzhue** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-x5nzzm?file=src%2Fapp%2Fapp.component.css

You just need to set number instead of `*ngIf`.

**Comment by zomixi** [comment]
> https://stackblitz.com/edit/ng-zorro-antd-start-x5nzzm?file=src%2Fapp%2Fapp.component.css
> 
> You just need to set number instead of `*ngIf`.

get it！

**Comment by andhadj** [comment]
The same problem exists when `ngIf` is applied on a parent element instead of the badge component directly. 

https://stackblitz.com/edit/ng-zorro-antd-start-rm2n9a

**Comment by hsuanxyz** [comment]
This problem didn't happen in the latest(9.1.2) version, and any more questions are welcome to submit issues!
