### ISSUE TITLE
希望增强skeleton的头像大小调整能力

### ISSUE THREAD

**Issue by ymind** [NG-ZORRO/ng-zorro-antd#4123]
## What problem does this feature solve?
当前skeleton的avatar尺寸被设定为固定的几个class值，然而即使是最大的尺寸在某些场合也不够大。
相关代码：https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/skeleton/nz-skeleton.component.html#L6

## What does the proposed API look like?
希望对avatar.size的传参方式进行扩展，使其在原来的基础上扩展支持数字和object参数。其中：
* 如果以数字128为参数，可以理解为要展现一个宽高均为128的头像；
* 如果以obj传参的话，这可以自定义宽高，例如：`{ width: 200, height: 64 }`；

我现在的解决方案是通过`::ng-deep`重写`.ant-skeleton-header .ant-skeleton-avatar-lg`样式。

如果能通过配置来调整avatar是居左还是居右那就更好了！

**Comment by wendzhue** [comment]
一般能够通过 CSS 解决的问题我们都不是很愿意增加 API，特别是对于 skeleton 这样的展示型组件，如果每个子元素都要添加控制样式的 API 的话，那 API 可太多了……

**Comment by wenqi73** [comment]
We will add the feature in 9.0.0, please track #4619.
