### ISSUE TITLE
the table component nzBordered attribute is not useable

### ISSUE THREAD

**Issue by FeiyuTo1** [NG-ZORRO/ng-zorro-antd#4125]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
Open this url.You can see the table doesn't have border,but I add the attribute nzBordered.

### What is expected?
The table have a border with its fit color.

### What is actually happening?
The table doesn't have border when I add nzBordered to it.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Google Chrome  76.0.3809.100 |

**Comment by vthinkxie** [comment]
don't forget to click the fork button when you create a repro link
