### ISSUE TITLE
There are different interactive behavior with the react version of the date picker

### ISSUE THREAD

**Issue by tirelyl** [NG-ZORRO/ng-zorro-antd#4130]
### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
For instance, i try to copy a string like '2019/12/12' into date-picker's input, i need press enter then the string can show in the input. 

### What is expected?
The interactive behavior synchronise withe the react version

### What is actually happening?
For instance, i try to copy a string like '2019/12/12' into date-picker's input, i need press enter then the string can show in the input. 

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Chrome 版本 76.0.3809.132（正式版本） （64 位） |

**Comment by tirelyl** [comment]
@wenqi73 Hello~我想问下这个问题复杂吗，大概什么时候能修复呢

**Comment by wenqi73** [comment]
@tirelyl 会尽快修复。

**Comment by vthinkxie** [comment]
@tirelyl 我们会尽快修复这个问题

**Comment by wenqi73** [comment]
9.0.0 同步 Antd，点击遮罩层也触发 onChange.

**Comment by wenqi73** [comment]
Fixed in #4699.
