### ISSUE TITLE
Build error: Missing 'global' property of ja_JP in ng-zorro-antd/i18n

### ISSUE THREAD

**Issue by keyman169** [NG-ZORRO/ng-zorro-antd#4131]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-vwdx81](https://stackblitz.com/edit/ng-zorro-antd-start-vwdx81)

### Steps to reproduce
Argument of type '{ locale: string; Pagination: { items_per_page: string; jump_to: string; jump_to_confirm: string; page: string; prev_page: string; next_page: string; prev_5: string; next_5: string; prev_3: string; next_3: string; }; ... 8 more ...; Empty: { ...; }; }' is not assignable to parameter of type 'NzI18nInterface'.
  Property 'global' is missing in type '{ locale: string; Pagination: { items_per_page: string; jump_to: string; jump_to_confirm: string; page: string; prev_page: string; next_page: string; prev_5: string; next_5: string; prev_3: string; next_3: string; }; ... 8 more ...; Empty: { ...; }; }' but required in type 'NzI18nInterface'.ts(2345)
nz-i18n.interface.d.ts(69, 5): 'global' is declared here.

### What is expected?
Fulfill ja_JP to build successfully

### What is actually happening?
Build error,
 Property 'global' is missing in type '{ locale: string; Pagination: { items_per_page: string; jump_to: string; jump_to_confirm: string; page: string; prev_page: string; next_page: string; prev_5: string; next_5: string; prev_3: string; next_3: string; }; ... 8 more ...; Empty: { ...; }; }' but required in type 'NzI18nInterface'.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Chrome, VS code |

**Comment by wendzhue** [comment]
Hi. This is already fixed in https://github.com/NG-ZORRO/ng-zorro-antd/pull/4102.

Are you interested in making a PR to add translations for Japanese?

**Comment by wendzhue** [comment]
I am closing this now. If you feel interested you can just submit a PR. Thank you!
