### ISSUE TITLE
form表单下select显示异常

### ISSUE THREAD

**Issue by CK110** [NG-ZORRO/ng-zorro-antd#4135]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-vn3zgt](https://stackblitz.com/edit/ng-zorro-antd-start-vn3zgt)

### Steps to reproduce
见链接

### What is expected?
正常显示

### What is actually happening?
显示不正常
![image](https://user-images.githubusercontent.com/9956098/64581705-c510c100-d3bd-11e9-8aef-315940bb998d.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1,8.3.0 |
| Browser | chrome 76.0.3809.132 |

**Comment by vthinkxie** [comment]
写复现不要忘记点fork

**Comment by CK110** [comment]
> 写复现不要忘记点fork

复现例子只是将文档中 form-高级搜索,中的`input`改为了`select`

**Comment by vthinkxie** [comment]
@CK110 ant design 中已经取消了 flex 的设计，请不要再使用，官方文档也会尽快更新

**Comment by CK110** [comment]
> @CK110 ant design 中已经取消了 flex 的设计，请不要再使用，官方文档也会尽快更新

去除`nzFlex`, 使用 `<form nz-form [nzLayout]="'inline'" ..` 已经是这样。

https://stackblitz.com/edit/ng-zorro-antd-start-nwwete

**Comment by danranVm** [comment]
看起来好像是 select 组件的bug ,不知道重构后的版本还存不存在，我待会尝试复现一下。

**Comment by danranVm** [comment]
9.x 中已经没有这个问题了

https://stackblitz.com/edit/ng-zorro-antd-ivy-jp8jp4?file=src%2Fapp%2Fapp.component.ts
