### ISSUE TITLE
tabset的nzDeselect希望增加用户手动继续切换或选择取消切换的操作，类似于next或者cancel

### ISSUE THREAD

**Issue by consunmida** [NG-ZORRO/ng-zorro-antd#4137]
## What problem does this feature solve?
用户可以手动继续切换或选择取消切换的操作

## What does the proposed API look like?
类似于next或者cancel

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
