### ISSUE TITLE
Can't Webpack App in Zorro 0.5.3 + Vs2017+Net Core2.0 

### ISSUE THREAD

**Issue by aptbird** [NG-ZORRO/ng-zorro-antd#414]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
 when run “node node_modules/webpack/bin/webpack.js --env.prod”

    ERROR in ng:///D:/Git/WeiXinCore/WeiXinCore/node_modules/ng-zorro-antd/index.d.ts.NzTabSetComponent.html (28,9): Object is possibly 'null'.
    
    ERROR in ./$$_gendir/~/ng-zorro-antd/index.ngfactory.ts
    Module parse failed: D:\Git\WeiXinCore\WeiXinCore\$$_gendir\node_modules\ng-zorro-antd\index.ngfactory.ts Unexpected token (15:39)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts 10:0-84
     @ ./ClientApp/boot.browser.ts

## Expected behavior
Can run in debug mode, but Can't Webpack. 

## Environment

<pre><code>
Angular version: 4.2.5

ng-zorro-antd version: 0.5.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [X] IE version XX
 
For Tooling issues:
- Node version: 8.2.1  
- Platform:  Windows Server 2012 R2

Others:
Webpack 2.5.1 

</code></pre>

**Comment by vthinkxie** [comment]
please check your webpack config, the integration test has been passed.
https://github.com/NG-ZORRO/ng-zorro-antd/tree/master/integration/webpack

**Comment by vthinkxie** [comment]
@noob9527 we will try to support fullTemplateType check in version 0.7.0
