### ISSUE TITLE
Production build throwing error after migratin UI to NG-ZORRO-ANTD

### ISSUE THREAD

**Issue by BrsJsk** [NG-ZORRO/ng-zorro-antd#4143]
Production build is succesfull but the application just does not work.

`RROR NullInjectorError: StaticInjectorError(c)[$ -> V]: 
  StaticInjectorError(Platform: core)[$ -> V]: 
    NullInjectorError: No provider for V!
    at j.get (http://localhost:4200/main.205a39b164af2df4f46e.js:1:257106)
    at http://localhost:4200/main.205a39b164af2df4f46e.js:1:259276
    at t (http://localhost:4200/main.205a39b164af2df4f46e.js:1:259646)
    at W.get (http://localhost:4200/main.205a39b164af2df4f46e.js:1:259769)
    at http://localhost:4200/main.205a39b164af2df4f46e.js:1:259276
    at t (http://localhost:4200/main.205a39b164af2df4f46e.js:1:259646)
    at W.get (http://localhost:4200/main.205a39b164af2df4f46e.js:1:259769)
    at ar (http://localhost:4200/main.205a39b164af2df4f46e.js:1:306022)
    at zr.get (http://localhost:4200/main.205a39b164af2df4f46e.js:1:314741)
    at ar (http://localhost:4200/main.205a39b164af2df4f46e.js:1:306022)`

The same error is thrown when running locally ng serve--prod or when we build the application ng serve --prod and then run it on a server.
Running in development mode, everything is great and work fine.

Error is thrown inside core.js.pre-build-optimizer.js:7187  file.

DEPENDENCIES
_"dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^7.3.1",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/material": "^7.3.1",
    "@angular/material-moment-adapter": "^7.3.1",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@netbasal/ngx-content-loader": "^2.1.0",
    "@ngrx/store": "^7.4.0",
    "@types/file-saver": "^2.0.1",
    "@types/googlemaps": "^3.30.16",
    "acorn": "^6.1.1",
    "core-js": "^2.5.4",
    "dayjs": "^1.8.15",
    "file-saver": "^2.0.2",
    "hammerjs": "^2.0.8",
    "luxon": "^1.12.0",
    "moment": "^2.24.0",
    "ng-zorro-antd": "^8.2.1",
    "ngx-cookie-service": "^2.1.0",
    "ngx-material-timepicker": "^3.0.2",
    "ramda": "^0.26.1",
    "rxjs": "~6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.0",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "~8.0.0",
    "@babel/core": "^7.4.5",
    "@compodoc/compodoc": "^1.1.9",
    "@storybook/addon-actions": "^5.0.11",
    "@storybook/addon-links": "^5.0.11",
    "@storybook/addon-notes": "^5.0.11",
    "@storybook/addons": "^5.0.11",
    "@storybook/angular": "^5.0.11",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "babel-loader": "^8.0.6",
    "browser-sync": "^2.26.5",
    "codelyzer": "^5.0.1",
    "husky": "^3.0.5",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "prettier": "1.18.2",
    "pretty-quick": "^1.11.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.4.5"
  }_

**Comment by Vbboi24** [comment]
Hi @BrsJsk , You were able to have storybook as part of Ng zorro. That's actually great. Can you help me with how you did that?

**Comment by sharathsrinivas** [comment]
Did anyone able to add storybook to NG-ZORRO? If please help me. The storybook won't load the and style.

**Comment by sharathsrinivas** [comment]
> Hi @BrsJsk , You were able to have storybook as part of Ng zorro. That's actually great. Can you help me with how you did that?

Did you succeed?

**Comment by jurito** [comment]
> Did anyone able to add storybook to NG-ZORRO? If please help me. The storybook won't load the and style.

+1, Same here :(
