### ISSUE TITLE
\t not working as token separator on nz-select

### ISSUE THREAD

**Issue by haykgh** [NG-ZORRO/ng-zorro-antd#4145]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-mz6ttj](https://stackblitz.com/edit/ng-zorro-antd-start-mz6ttj)

### Steps to reproduce
Write something and press Tab.

### What is expected?
Add token, and pass focus.

### What is actually happening?
Passing focus without adding token.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | All |

**Comment by vthinkxie** [comment]
work as design
