### ISSUE TITLE
nz-table nzVirtualScroll table header not aligned

### ISSUE THREAD

**Issue by laitedliang** [NG-ZORRO/ng-zorro-antd#4154]
### Reproduction link
[https://stackblitz.com/edit/angular-ewptrz?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ewptrz?file=src/app/app.component.ts)

### Steps to reproduce
scroll left/right and the header does not align with its corresponding column

Scroll up/down and the alignment is off even more if the column content is long

### What is expected?
table header aligns with its column

### What is actually happening?
table header not aligned

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | Chrome Version 76.0.3809.132 |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-ewptrz-yxoqzr?file=src/app/app.component.ts
you have to add 
    td{
      word-break:break-all;
    }
to break all words
