### ISSUE TITLE
设置NzTreeNode.isExpanded未能触发nzExpandChange事件

### ISSUE THREAD

**Issue by x-wk** [NG-ZORRO/ng-zorro-antd#4155]
### Reproduction link
[https://stackblitz.com/edit/angular-xceb3z](https://stackblitz.com/edit/angular-xceb3z)

### Steps to reproduce
双击node展开或折叠当前节点(node.isExpanded = !node.isExpanded)

### What is expected?
nzExpandChange发射事件, 控制台打印事件名称

### What is actually happening?
展开或折叠已实现, 但是未触发nzExpandChange

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | Google Chrome 版本 76.0.3809.132（正式版本） （64 位） |

**Comment by wenqi73** [comment]
这是符合预期的，文档有说明
> 点击展开树节点图标触发
