### ISSUE TITLE
Slider throws "ERROR TypeError: Cannot read property 'toFixed' of undefined"

### ISSUE THREAD

**Issue by dmattsson** [NG-ZORRO/ng-zorro-antd#4157]
### Reproduction link
[https://angular-ewptrz-upcjkt.stackblitz.io](https://angular-ewptrz-upcjkt.stackblitz.io)

### Steps to reproduce
Add a Nz-Slider with [nzDots]=true

### What is expected?
Value to be changed

### What is actually happening?
Get error
ERROR TypeError: Cannot read property 'toFixed' of undefined

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | Chrome |

**Comment by wendzhue** [comment]
It looks good to me. Any detailed steps to reproduce this error?

![屏幕快照 2019-09-16 15 53 24](https://user-images.githubusercontent.com/12122021/64941822-2e9b3e80-d89a-11e9-8f27-a31ba26dc5c1.png)
