### ISSUE TITLE
_co.locale is undefined

### ISSUE THREAD

**Issue by Abdullah700** [NG-ZORRO/ng-zorro-antd#4159]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-5yifk5?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-5yifk5?file=src/app/app.component.html)

### Steps to reproduce
change the localization to ar_EG and load nz-cascader component

### What is expected?
should working normally

### What is actually happening?
getting error _co.locale is undefined

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | firefox 69.0 |

**Comment by wendzhue** [comment]
Hi @Abdullah700 . Some properites are missing in the [ar_EG](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/i18n/languages/ar_EG.ts) i18n file (compared with [en_US](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/i18n/languages/en_US.ts)).

Are you interested in submitting a PR to fix this?

BTW, for now you can use `[nzPlaceHolder]` as a quick fix.

**Comment by Abdullah700** [comment]
hi @wendzhue . yeah i noticed some other missing properties ill be fixing all of the messing onse and ill PR the fix
