### ISSUE TITLE
建议日期选择框nzMode添加year支持，只选择年份

### ISSUE THREAD

**Issue by zhouwf108** [NG-ZORRO/ng-zorro-antd#416]
建议日期选择框nzMode添加year支持，只选择年份

**Comment by edgexie** [comment]
i hope this so.

**Comment by baiyunchen** [comment]
单纯的选个年份，难道不是一个下拉框就可以搞定的事情么？或者放个数字框，我不认为单纯的年份选择器有什么实际业务价值，而且我觉得选年份没有直接填一个数字来的简单方便。
