### ISSUE TITLE
modal 无法使用组件自定义底部按钮，即使是官方的demo也是无法实现

### ISSUE THREAD

**Issue by zzmmbb** [NG-ZORRO/ng-zorro-antd#4160]
### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
直接查看文档modal里面的stackblitz自定义页脚2代码

### What is expected?
modal自定义页脚能够使用组件化定义按钮

### What is actually happening?
modal自定义页脚无法使用组件化定义按钮

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | Chrome |

---
直接查看文档modal里面的stackblitz自定义页脚2demo演示

**Comment by hsuanxyz** [comment]
@zzmmbb 看上去文档中的自定义页脚正常工作，请提供有效的复现链接
