### ISSUE TITLE
Styling button group with upload

### ISSUE THREAD

**Issue by Coada** [NG-ZORRO/ng-zorro-antd#4168]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-utirek](https://stackblitz.com/edit/ng-zorro-antd-start-utirek)

### Steps to reproduce
I would like to have an upload functionality attached to one of the buttons in a button group. Currently, the only way to do this is to wrap it around a `<nz-upload>`, however this breaks the styling of the button groups.

### What is expected?
The button group should be styled as expected.

### What is actually happening?
The buttons are not grouped properly, including the rounding effect and the separator between them.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
@Coada 
you can add a file reader directive to button in button group
here is a demo 
https://github.com/apache/flink/blob/master/flink-runtime-web/web-dashboard/src/app/share/common/file-read/file-read.directive.ts

**Comment by marct83** [comment]
I agree this would be nice to see.
