### ISSUE TITLE
width is inconsistent in nz-modal of nz-dropdown-menu when first hover and later hover

### ISSUE THREAD

**Issue by CC2013** [NG-ZORRO/ng-zorro-antd#4169]
### Reproduction link
[https://stackblitz.com/edit/angular-nzdropdown-issue](https://stackblitz.com/edit/angular-nzdropdown-issue)

### Steps to reproduce
1.click the "click modal" button；
2.first hover "add config", the menu shows;
3.again hover "add config"， the menu shows again；

### What is expected?
no matter hover any times, the drop menu's width would be inconsistent;

### What is actually happening?
hover twice, but the drop menu's width is inconsistent;

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Chrome 76 |

---
just the first time hover, the width has some problem. And I think it still a problem in the version 8.3.0

**Comment by hsuanxyz** [comment]
Work on v10, https://stackblitz.com/edit/angular-7qcaal?file=src%2Fapp%2Fapp.component.ts.

Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
