### ISSUE TITLE
nz-tabset dynamic change nzType cause animation not working

### ISSUE THREAD

**Issue by wheeljs** [NG-ZORRO/ng-zorro-antd#4171]
### Reproduction link
[https://stackblitz.com/edit/angular-4a8g39?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-4a8g39?file=src/app/app.component.ts)

### Steps to reproduce
Change `nzType` from 'line' to 'card', then to 'line' again, click tab-bar the ink-bar not be animated.

### What is expected?
Animations for ink-bar should only be affected by `nzType` and `nzAnimated`.

### What is actually happening?
ink-bar not be animated when `nzType` changed to 'card', then to 'line'.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | 版本 76.0.3809.132（正式版本） （64 位） |

---
Sorry for my English.

**Comment by hsuanxyz** [comment]
close via #5590
