### ISSUE TITLE
Datepicker with tab navigation is not working properly 

### ISSUE THREAD

**Issue by Clamparion** [NG-ZORRO/ng-zorro-antd#4172]
### Reproduction link
[https://stackblitz.com/edit/angular-gnwz7d](https://stackblitz.com/edit/angular-gnwz7d)

### Steps to reproduce
Navigate through a formular with keyboard only - using the tab-key. 

Try to open the datepicker with tab and type the date manually (without using the mouse)

### What is expected?
Navigation from one form control to the other using only keyboard and the tab-key. Without interruption and using the mouse to select a date in the datepicker component

### What is actually happening?
If you navigate with the tab-key through your form, the datepicker control does not open if it is focused. You can't type the date manually (except if you press Enter). 

If you have opened the datepicker control and you are typing in the input field there you can't navigate to the next form control with the tab key.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | Google Chrome v. 77 |

**Comment by wenqi73** [comment]
`TAB` key cannot open/close panel and switch to next element at the same time.
