### ISSUE TITLE
支持 InputNumber 组件 nzPrecision 精度的处理方式为四舍五入或截断

### ISSUE THREAD

**Issue by renxia** [NG-ZORRO/ng-zorro-antd#4173]
## What problem does this feature solve?
如题，当前对 nzPrecision 精度的处理方式默认为四舍五入，但在一些需求中是希望做截断处理。
当前只能通过 ngModelChange 监听然后用“万能的”setTimeout 去实现。
组件既然存在配置项 nzPrecision，那么希望其能提供更为细致的配置性支持

## What does the proposed API look like?
增加配置项，支持 `nzPrecision` 精度的处理方式为四舍五入或截断

**Comment by wendzhue** [comment]
欢迎提交 PR～
