### ISSUE TITLE
树形控件tree 和树形选择控件dom渲染采用ngIf 而不是class="hidden"来隐藏

### ISSUE THREAD

**Issue by lihuabest** [NG-ZORRO/ng-zorro-antd#4182]
## What problem does this feature solve?
树形数据量特别大的时候（项目测试超过1000条），dom显示/隐藏采用hidden的形式加载渲染特别慢，其实下拉动画完全可以采用ngif来实现

## What does the proposed API look like?
修改动画形式

**Comment by wenqi73** [comment]
Already has PR #3947.
