### ISSUE TITLE
tree select use event  nzTreeCheckBoxChange error

### ISSUE THREAD

**Issue by xiaojian95** [NG-ZORRO/ng-zorro-antd#4187]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-jfcu8g?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-jfcu8g?file=src/app/app.component.ts)

### Steps to reproduce
<nz-tree-select

style="width: 250px"

[nzNodes]="Ogranizitionnodes"

nzShowSearch

nzCheckable

nzPlaceHolder="Please select"

[(ngModel)]="Orgvalue"

(nzTreeCheckBoxChange)="nzTreeCheckBoxChange($event)"

></nz-tree-select>

nzTreeCheckBoxChange(event){

console.log(event)

}

当nzTreeCheckBoxChange被触发时，我能拿到event值，同时会引发一个错误
Object too large to inspect. Open your browser console to view.
请问是什么原因？

### What is expected?
期待告知Object too large to inspect. Open your browser console to view.为什么会出这个错

### What is actually happening?
期待告知Object too large to inspect. Open your browser console to view.为什么会出这个错

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | Google Chrome |

**Comment by wendzhue** [comment]
![image](https://user-images.githubusercontent.com/12122021/65233400-56420f00-db05-11e9-91fb-8cf90eb8ab80.png)

<kbd>F12</kbd>
