### ISSUE TITLE
 https://ng.ant.design/issue-helper/#/zh 今天使用了nz-countdownd倒计时组件，这个组件有一个(nzCountdownFinish)事件，这个事件没有效果

### ISSUE THREAD

**Issue by coculate** [NG-ZORRO/ng-zorro-antd#4190]
注意：不是用 https://ng.ant.design/issue-helper/#/zh 创建的 issue 会被立即关闭。

今天使用了nz-countdownd倒计时组件，这个组件有一个(nzCountdownFinish)事件，这个事件没有效果，我准备用这个事件来关闭一个弹框，就是倒计时等于0的时候把弹框关闭，但是一点用都没有，调试和打日志都没用，不进方法

**Comment by wendzhue** [comment]
我们有测试确保 API 按照期望的方式工作。如果疑似找到了 bug，请提供复现。

**Comment by coculate** [comment]
不好意思，这么晚才回复您，我这边准备用这个事件倒计时结束就关闭弹框的，但是一直没效果，不知道是不是我这边对这个事件理解的有误还是我操作的问题，这个倒计时组件我放在模态框里面



发自我的iPad


------------------ 原始邮件 ------------------
发件人: Wendell <notifications@github.com&gt;
发送时间: 2019年9月23日 09:59
收件人: NG-ZORRO/ng-zorro-antd <ng-zorro-antd@noreply.github.com&gt;
抄送: coculate <2293878715@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[NG-ZORRO/ng-zorro-antd]  https://ng.ant.design/issue-helper/#/zh 今天使用了nz-countdownd倒计时组件，这个组件有一个(nzCountdownFinish)事件，这个事件没有效果 (#4190)




我们有测试确保 API 按照期望的方式工作。如果疑似找到了 bug，请提供复现。
