### ISSUE TITLE
版本8.3.0 Affix固钉不兼容IE11，导致锚点无法固定

### ISSUE THREAD

**Issue by Smilewangjing** [NG-ZORRO/ng-zorro-antd#4191]
版本8.3.0 Affix固钉不兼容IE11，导致锚点无法固定
版本7.5.1是没有问题的，可以固定
测试地址：官网：https://ng.ant.design/components/anchor/zh

**Comment by wendzhue** [comment]
Duplicates https://github.com/NG-ZORRO/ng-zorro-antd/issues/4070.
