### ISSUE TITLE
版本8.3.0 guAffix固钉不兼容IE11，导致锚点无法固定

### ISSUE THREAD

**Issue by Smilewangjing** [NG-ZORRO/ng-zorro-antd#4192]
### Reproduction link
[https://ng-zorro-antd-start-cj9an4.stackblitz.io](https://ng-zorro-antd-start-cj9an4.stackblitz.io)

### Steps to reproduce
ie11下样式错误，无法固定

### What is expected?
在ie11下也能固定

### What is actually happening?
ie11下样式错误，无法固定

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | IE11 |

---
https://ng.ant.design/components/affix/zh 官网可以重现，guAffix固钉以及锚点

**Comment by wendzhue** [comment]
和 #4070 重复，如果问题没有在 #4161 中被解决欢迎重新提交一个 issue
