### ISSUE TITLE
InputNumber 可以只限制输入数字吗？

### ISSUE THREAD

**Issue by mushang11** [NG-ZORRO/ng-zorro-antd#42]
https://ng.ant.design/#/components/input-number
名义是 input  number 但是没有限制。

**Comment by mushang11** [comment]
动态配置，例如可以配置整数，小数位数。

**Comment by giscafer** [comment]
还没扩展`formatter `属性。

**Comment by aruis** [comment]
手动在nz-input-number 输入数字， 直接从form 里取到的值是 字符串类型。 是我使用姿势不对，还是bug？

**Comment by giscafer** [comment]
@aruis 目前输入框取得的值都是string类型

**Comment by LinBoLen** [comment]
formatter +1
