### ISSUE TITLE
Could NzProgress be able to fan out like version 8.1.0 do? 

### ISSUE THREAD

**Issue by Adalake** [NG-ZORRO/ng-zorro-antd#4201]
- Reproduction link:

https://stackblitz.com/edit/angular-3u1pns  [ "ng-zorro-antd": "8.3.0" ]
https://stackblitz.com/edit/angular-hvts7k   [ "ng-zorro-antd": "8.1.0" ]

- What is expected?

be able to fan out
能够成扇形展开

- What is actually happening?

We want gradient function which version 8.3.0 provide, but fail to fan out the circle like  version 8.1.0 used to do.
我们需要使用 8.3.0 种的渐变色功能，但是切换成版本 8.3.0，圆环无法成扇形展开。

- version 8.1.0
![old](https://user-images.githubusercontent.com/39910904/65405043-9529da80-de0d-11e9-9688-f2441eacae2c.PNG)

Environment | Info
ng-zorro-antd: 8.1.0
Browser: Chrome

- version 8.3.0
![new](https://user-images.githubusercontent.com/39910904/65405053-a4a92380-de0d-11e9-8c10-bff0d2b65164.PNG)

Environment | Info
ng-zorro-antd: 8.3.0
Browser: Chrome

**Comment by Adalake** [comment]
- Reproduction link:

https://stackblitz.com/edit/angular-3u1pns [ "ng-zorro-antd": "8.3.0" ]
https://stackblitz.com/edit/angular-hvts7k [ "ng-zorro-antd": "8.1.0" ]

- What is expected?

be able to fan out
能够成扇形展开

- What is actually happening?

We want gradient function which version 8.3.0 provide, but fail to fan out the circle like version 8.1.0 used to do.
我们需要使用 8.3.0 种的渐变色功能，但是切换成版本 8.3.0，圆环无法成扇形展开。

- version 8.1.0

![old](https://user-images.githubusercontent.com/39910904/65405352-521c3700-de0e-11e9-85bf-42fe410206a4.PNG)

Environment | Info
ng-zorro-antd: 8.1.0
Browser: Chrome

- version 8.3.0

![new](https://user-images.githubusercontent.com/39910904/65405353-547e9100-de0e-11e9-88df-59ef549d75cf.PNG)

Environment | Info
ng-zorro-antd: 8.3.0
Browser: Chrome

**Comment by wendzhue** [comment]
设计如此，参考 React 版本 https://codesandbox.io/s/goofy-glitter-04ur5

非标准行为不会保证它的兼容性

**Comment by Adalake** [comment]
> 设计如此，参考 React 版本 https://codesandbox.io/s/goofy-glitter-04ur5
> 
> 非标准行为不会保证它的兼容性，很可能是由于潜在的 bug 导致的异常用法

你好，[nzStrokeLinecap] = 'square' 时，不是 square ，依旧为默认样式 round。
![bug](https://user-images.githubusercontent.com/39910904/65599120-b1757500-dfcf-11e9-885c-8c118c16d930.PNG)

**Comment by wendzhue** [comment]
@Adalake 这里的 square 是个变量不是字符串。
