### ISSUE TITLE
徽标在多级下拉菜单中不显示

### ISSUE THREAD

**Issue by GoodEvent** [NG-ZORRO/ng-zorro-antd#4203]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-pdikiz?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-pdikiz?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
重复展开下拉菜单

### What is expected?
徽标能显示

### What is actually happening?
第二次展开下拉菜单徽标不显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | chrome76     (win10) |

**Comment by wenqi73** [comment]
```html
 <nz-dropdown-menu #menu4="nzDropdownMenu" nzNoAnimation>
```
Related to #4489, angular/angular#24041
