### ISSUE TITLE
nz-transfer nzTargetKeys usage method

### ISSUE THREAD

**Issue by alasili** [NG-ZORRO/ng-zorro-antd#4210]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-nxxssu?embed=1&file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-nxxssu?embed=1&file=src/app/app.component.html)

### Steps to reproduce
<nz-transfer
      [nzDataSource]="list"
      [nzTitles]="['Source', 'Target']"
      [nzTargetKeys]="selectValue"
    >
    </nz-transfer>

### What is expected?
nzTargetKeys 

### What is actually happening?
nzTargetKeys error

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | Google Chrome 版本 77.0.3865.90（正式版本） （64 位） |

**Comment by alasili** [comment]
Can I write an example?

**Comment by Wu-Yao** [comment]
> 我可以写一个例 请问解决了吗，我也遇到了同样的问题
