### ISSUE TITLE
TreeSelect can custom the content of select template

### ISSUE THREAD

**Issue by tirelyl** [NG-ZORRO/ng-zorro-antd#4212]
## What problem does this feature solve?
I want the template in TreeSelect can be customed. because the value in tree structure may have some icon or avatar, there only pure string character in select content after user click the value item. 
## What does the proposed API look like?
It similar to Select component, provider a `nzCustomTemplate` property for user to custom the template

**Comment by wendzhue** [comment]
@tirelyl PR welcome~

**Comment by hsuanxyz** [comment]
@tirelyl Sorry, we missed its docs, you can use the `nzTreeTemplate` API to set the nodes template. https://ng.ant.design/components/tree-select/zh#components-tree-select-demo-customized-icon

**Comment by tirelyl** [comment]
@hsuanxyz ok，3q
