### ISSUE TITLE
Node Express server listening on http://localhost:4000 Error: No NgModule metadata found for '[object Object]'

### ISSUE THREAD

**Issue by golapdk** [NG-ZORRO/ng-zorro-antd#4219]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
after use server-side rendering 

### What is expected?
run smoothly.

### What is actually happening?
break

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.1 |
| Browser | Google Chrome Version 77.0.3865.90 (Official Build) (64-bit) |

**Comment by wendzhue** [comment]
Our official website use SSR. Please provide a reproduction.
