### ISSUE TITLE
Font Awesome Icons (SVG)

### ISSUE THREAD

**Issue by whittssg** [NG-ZORRO/ng-zorro-antd#4232]
## What problem does this feature solve?
Ability to use FA Icons with this library (nzIcon="").
## What does the proposed API look like?
I tried to add the following to angular.json:
"assets": [
              {
                "glob": "**/*",
                "input": "./node_modules/@fortawesome/pro-regular-svg-icons/",
                "output": "/assets/"
              }
            ],

and then

  constructor(private _iconService: NzIconService) {
    this._iconService.changeAssetsSource('./node_modules/@ant-design/icons-angular/src/inline-svg/');
  }

to the app.module but i wasnt able to use the icons.

Is there something i am missing? I would like to be able to use the icons in place that support nzIcon=""

Thanks,

**Comment by whittssg** [comment]
Maybe we can already do this but after reading the docs several times i cannt figure it out. Thanks

**Comment by wendzhue** [comment]
Sorry. This component is not (designed) for loading all icons.

```ts
this._iconService.changeAssetsSource('./node_modules/@ant-design/icons-angular/src/inline-svg/');
```

And `changeAssetsSource` is for changing the source for *dynamic loading*. 

If you want to use the component with font awesome, you should probably use the namespace feature.

**Comment by whittssg** [comment]
Thank you for replying, i did try that (based on the docs) as well but failed :( I cant find any examples online anywhere on how to do this as well.. Do you happen to know of any stackblitz examples out there that include a third party icon libary? Thanks again

**Comment by wendzhue** [comment]
There's a demo of *namespace*. Have you checked it?

**Comment by whittssg** [comment]
Ah man, i saw that it mentioned it but didnt see a demo for it so i assumed it was missing.. Just clicekd the the code view below and saw the code. I was able to make it work on my end with you demo svg variable but not with font awsome.. guess its the way they are formatting each ts file:
![image](https://user-images.githubusercontent.com/6453857/65841226-38875d80-e2ee-11e9-82a1-2edbbbe182d2.png)

what is addIconLiteral actually looking for in the second part ? i tried passing in the literal path and like this '<svg>' + far.faAbacus.icon[4]) + '</svg>' and nothing showed also tried with path '<path d="' + far.faAbacus.icon[4]) + '"</path>'</svg>'

**Comment by wendzhue** [comment]
You check use this feature:

https://ng.ant.design/components/icon/en#components-icon-demo-namespace
