### ISSUE TITLE
It doesn't support angular ivy mode

### ISSUE THREAD

**Issue by justwalk** [NG-ZORRO/ng-zorro-antd#4236]
## What problem does this feature solve?
it can use angular ivy mode to improve application performance.

## What does the proposed API look like?
Ng-zorro cannot compile through ivy mode because date-fns does not support Angular Package Format。

**Comment by wendzhue** [comment]
@wenqi73 Would you please take a look at this?

**Comment by lppedd** [comment]
@wendzhue this is the same problem I had seen weeks ago when the beta started.
The date-fns problem is resolved since (if I recall correctly) beta-5.  
However it would still be impossible to compile with Ivy, givien you have extending components (lets call them "mixins").

**Comment by Svetomechc** [comment]
@justwalk https://github.com/NG-ZORRO/ng-zorro-antd/issues/3514#issuecomment-499101370 blocking issues in Angular sadly for Ivy support to happen now

**Comment by Svetomechc** [comment]
@lppedd you can try compiling with Ivy enabled now with Angular version **9.0.0-rc.1**. Haven't tested it myself yet, but all the blocking issues seem to be closed now.

**Comment by lppedd** [comment]
@Svetomechc oh ok. Thanks! Even the base classes decorators has been solved?

**Comment by Svetomechc** [comment]
@lppedd I hope.

**Comment by lppedd** [comment]
@Svetomechc I haven't seen commits about that here, but I'll try anyway.

**Comment by Svetomechc** [comment]
@lppedd have you had any success?

**Comment by vthinkxie** [comment]
https://github.com/angular/angular/issues/33393 there is still some issue related to ivy
we will start our work to migrate to ivy after 8.5.1 version

**Comment by Svetomechc** [comment]
@vthinkxie added thumbs up to the issue, hope it gets resolved ASAP.

**Comment by lppedd** [comment]
@Svetomechc that issue is now on `v9-blockers`, so it will get solved pretty fast I hope!

**Comment by marcus-sa** [comment]
Excited for when Ivy support arrives!

**Comment by wendzhue** [comment]
Closed by #4453. We would release a beta version that supports Ivy shortly after. Thanks for your patience and waiting. :heart:

**Comment by marcus-sa** [comment]
Awesome! I just finished integrating view engine.. guess I'm gonna go back to Ivy again then, cheers!

**Comment by marcus-sa** [comment]
Seems like it's still failing
```
Error: Error on worker #8: Error: Unable to write a reference to NzStringTemplateOutletDirective in /home/marcus-sa/Git/siteattention/dashboard/node_modules/ng-zorro-antd/esm2015/core/addon/string_template_outlet.js from /home/marcus-sa/Git/siteattention/dashboard/node_modules/ng-zorro-antd/esm2015/core/addon/addon.module.js
```

**Comment by marcus-sa** [comment]
Seems like that didn't resolve the issue :sweat_smile: 
```
Error: Error on worker #8: Error: Unable to write a reference to NzStringTemplateOutletDirective node_modules/ng-zorro-antd/esm2015/core/addon/string_template_outlet.js from node_modules/ng-zorro-antd/esm2015/core/addon/addon.module.js
```

**Comment by wendzhue** [comment]
@marcus-sa Have you try to remove node_modules and reinstall? Usually this problem comes from an outdated version of @angular/cdk.

**Comment by Svetomechc** [comment]
@marcus-sa I succesfully enabled Ivy with ng-zorro-antd, ping me if you need any help.

**Comment by marcus-sa** [comment]
@Svetomechc cheers!
What does your `package.json` look like?
Now the error disappeared, but instead I get (with `@angular/cdk@9.0.0-rc.2`):
```
Error: Error on worker #3: Error: Unable to write a reference to CdkAccordion in /home/marcus-sa/Git/siteattention/dashboard/node_modules/@angular/cdk/esm2015/accordion/accordion.js from /home/marcus-sa/Git/siteattention/dashboard/node_modules/@angular/cdk/esm2015/accordion/accordion-module.js
```

**Comment by Svetomechc** [comment]
@marcus-sa make sure you updated **angular**, **zone.js**, **typescript**, etc.:

![image](https://user-images.githubusercontent.com/36156020/69716065-60424880-111a-11ea-8b9c-dcba8d5dae2b.png)

![image](https://user-images.githubusercontent.com/36156020/69716100-6f28fb00-111a-11ea-95d5-dbd7555b20b6.png)

make sure you have this line in **angular.json**:

![image](https://user-images.githubusercontent.com/36156020/69716177-95e73180-111a-11ea-8b35-4d43b7815913.png)

not sure if this is still needed, but here's my **tsconfig.app.json**:

![image](https://user-images.githubusercontent.com/36156020/69716287-ca5aed80-111a-11ea-941c-7379ffe91cdc.png)

delete your **package-lock.json** / **yarn.lock** files, remove **node_modules** directory, run **npm install** / **yarn** commands

**Comment by marcus-sa** [comment]
@Svetomechc thanks, but it's weird because I have the exact same versions of the packages installed and it still doesn't work.
The last two steps aren't needed for me since I use Bazel :smile:

**Comment by dapothedeveloper** [comment]
> @marcus-sa make sure you updated **angular**, **zone.js**, **typescript**, etc.:
> 
> ![image](https://user-images.githubusercontent.com/36156020/69716065-60424880-111a-11ea-8b9c-dcba8d5dae2b.png)
> 
> ![image](https://user-images.githubusercontent.com/36156020/69716100-6f28fb00-111a-11ea-95d5-dbd7555b20b6.png)
> 
> make sure you have this line in **angular.json**:
> 
> ![image](https://user-images.githubusercontent.com/36156020/69716177-95e73180-111a-11ea-8b35-4d43b7815913.png)
> 
> not sure if this is still needed, but here's my **tsconfig.app.json**:
> 
> ![image](https://user-images.githubusercontent.com/36156020/69716287-ca5aed80-111a-11ea-941c-7379ffe91cdc.png)
> 
> delete your **package-lock.json** / **yarn.lock** files, remove **node_modules** directory, run **npm i** / **yarn** commands
> 
> then your app should run smoothly (first run will take longer to compile. as it will compile your **node_modules** packages to new format)

Worked like charm all I did was to follow the official documentation of upgrading to angular 9 [here](https://update.angular.io/#8.2:9.0)

**Comment by marcus-sa** [comment]
It no longer works with the latest Angular 9 release candidate.
When running `ngcc --properties es2015 main` it seems to only compile the following entry points:
```
Compiling ng-zorro-antd/core/addon : main as umd
Compiling ng-zorro-antd/core/addon : es2015 as esm2015
Compiling ng-zorro-antd/version : main as umd
Compiling ng-zorro-antd/version : es2015 as esm2015
```

**Comment by vthinkxie** [comment]
Hi all, we are working on the ng-zorro-antd v9 now
I believe it would release soon after the angular v9 final version.

**Comment by zmzimpl** [comment]
The problem still exis when ngcc, it will thrown an error like this:
```
Tried to overwrite E:/Project/MstDashboard/node_modules/ng-zorro-antd/esm5/core/addon/classlist_add.js.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
```
but it could be solved by delete node_modules and then reinstall

**Comment by BrsJsk** [comment]
It's not still safe to use ng zorro with angular 9 ?

**Comment by hsuanxyz** [comment]
> It's not still safe to use ng zorro with angular 9 ?

We will release stable version(9.0.0) today

**Comment by Svitra** [comment]
> > It's not still safe to use ng zorro with angular 9 ?
> 
> We will release stable version(9.0.0) today

Hi, with the version 9 and Angular 9 (ivy enabled) I am now getting the following error:
Error: Tried to write .../node_modules/ng-zorro-antd/core/no-animation/nz-no-animation.directive.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, .../node_modules/ng-zorro-antd/core/no-animation/nz-no-animation.directive.d.ts.
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.

I tried removing node_modules folder and running a clean install but when i run ngcc i get the same result. That is a really big blocker for me. Can you please advise?

**Comment by BrsJsk** [comment]
> > > It's not still safe to use ng zorro with angular 9 ?
> > 
> > 
> > We will release stable version(9.0.0) today
> 
> Hi, with the version 9 and Angular 9 (ivy enabled) I am now getting the following error:
> Error: Tried to write .../node_modules/ng-zorro-antd/core/no-animation/nz-no-animation.directive.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, .../node_modules/ng-zorro-antd/core/no-animation/nz-no-animation.directive.d.ts.
> This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
> You should check other entry-points in this package and set up a config to ignore any that you are not using.
> 
> And then I get a bunch of other errors all related to nz-no-animation.directive.js
> 
> I tried removing node_modules folder and running a clean install but when i run ngcc i get the same result. That is a really big blocker for me. Can you please advise?

Is ngcc required to run? I think its more of a good thing to do for faster build time ?

**Comment by Svitra** [comment]
Unfortunately I get the same errors also during build and running unit tests while the dependencies are compiled so despite the unit tests passing the pipelines are failing due to these errors.

**Comment by hsuanxyz** [comment]
@Svitra @BrsJsk  #5045, we will fix it soon

**Comment by zmzimpl** [comment]
> @Svitra @BrsJsk #5045, we will fix it soon


Has the problem been solved? This error is still thrown when I run ngcc after upgrading to 9：
`Error on worker #5: Error: Tried to overwrite E:/Project/MstDashboard/node_modules/ng-zorro-antd/core/no-animation/nz-no-animation.directive.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.`

**Comment by hsuanxyz** [comment]
@zmzimpl It will be fixed in the next version(9.0.2), you can subscribe to the release notifications

**Comment by zmzimpl** [comment]
> @zmzimpl It will be fixed in the next version(9.0.2), you can subscribe to the release notifications

OK，thanks，It also seems to throw this error：
`Error: Error on worker #2: Error: Tried to overwrite E:/Project/MstDashboard/node_modules/ng-zorro-antd/fesm2015/ng-zorro-antd-icon.js.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.`

**Comment by hsuanxyz** [comment]
@zmzimpl Looks like a common error on ivy,  could you delete the `node_modules` and retry?

**Comment by zmzimpl** [comment]
> @zmzimpl Looks like a common error on ivy, could you delete the `node_modules` and retry?


I tried deleting `node_modules`, but it still throw this error. At this time, my `angular / cli` version is` 9.1.1`. When I roll back the antd version to `8.5.2`, it will throw There was an error related to `addon`, but in` angular cli 9.0.4`, after deleting `node_modules` and reinstalling it, ivy works fine again.
