### ISSUE TITLE
The fixed column of nz-table is not valid on IE

### ISSUE THREAD

**Issue by zmzimpl** [NG-ZORRO/ng-zorro-antd#4237]
### Reproduction link
[https://sks7eu.run.stackblitz.io](https://sks7eu.run.stackblitz.io)

### Steps to reproduce
use IE11 open this link:https://sks7eu.run.stackblitz.io

### What is expected?
 fixed column of nz-table is valid on IE

### What is actually happening?
 fixed column of nz-table is not valid on IE

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.1 |
| Browser | IE11 |

**Comment by vthinkxie** [comment]
<img width="982" alt="屏幕快照 2019-09-27 下午5 45 16" src="https://user-images.githubusercontent.com/1506722/65759919-9715d580-e14e-11e9-9075-74f7a97eca8f.png">
https://caniuse.com/#feat=css-sticky
