### ISSUE TITLE
Table function requirement

### ISSUE THREAD

**Issue by 3qfang** [NG-ZORRO/ng-zorro-antd#424]
## I'm submitting one need of Table

First,thanks for your job.Very awesome components lib.

For Table componet,I think that it should support selction mode,single or multiple.When single,may be add one event,like onRowSelect.I should be better.

PrimeNg DataTable can be example.

Thanks.

**Comment by vthinkxie** [comment]
you can just make it work with nz-checkbox.

**Comment by 3qfang** [comment]
if batch operate,nz-checkbox is better.I just want to select one item when mouse click one of them.now,no event for this.

**Comment by Cuiqs76** [comment]
@3qfang would you show the other methods here?  I want to double click the row to complete the selection and close the page. in my scene, only allow single select .
