### ISSUE TITLE
nz-table设置scroll后表格不对齐

### ISSUE THREAD

**Issue by s641135196** [NG-ZORRO/ng-zorro-antd#4243]
### Reproduction link
[https://stackblitz.com/edit/angular-m2tet2?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-m2tet2?file=src/app/app.component.ts)

### Steps to reproduce
直接预览

### What is expected?
表格对齐

### What is actually happening?
表格不对齐

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.1 |
| Browser | chrome 77 |

---
如果去掉代码中 [nzScroll]="{ y: '240px' }" 就会正常对齐，但我需要限制表格的高度。

**Comment by vthinkxie** [comment]
1.你表格里面的内容已经远远超过100px的宽度了
2.没有设定scrollX的宽度
3.如果需要折行显示需要添加css

**Comment by s641135196** [comment]
@vthinkxie  谢谢， 请问这个折行css怎么写了

**Comment by s641135196** [comment]
@vthinkxie  谢谢， 这个折行css怎么写的了。

**Comment by vthinkxie** [comment]
任意搜索引擎搜索 css 折行显示
