### ISSUE TITLE
Using ng-zorro-antd with mgechev/angular-seed possible?

### ISSUE THREAD

**Issue by kubica** [NG-ZORRO/ng-zorro-antd#425]
## Explanation

Since my chinese is very limited i didn't understand if ng-zorro-antd is limited to angular-cli or works with other popular seed-projects, too?!

## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Support request
</code></pre>

## Current behavior

I tried to add [ng-zorro-antd][1] to my [angular-seed](https://github.com/mgechev/angular-seed) project. I extended `project.config.ts` with

    let additionalPackages: ExtendPackages[] = [{
        name: 'ng-zorro-antd',
        path: 'node_modules/ng-zorro-antd/bundles/ng-zorro-antd.umd.min.js'
    }];
        
    this.addPackagesBundles(additionalPackages);

and added

    import { NgZorroAntdModule } from 'ng-zorro-antd';

as well as

    NgZorroAntdModule.forRoot()

to my `app.module.ts` but it crashes when running `npm start`

[![enter image description here][2]][2]

  [1]: https://github.com/NG-ZORRO/ng-zorro-antd
  [2]: https://i.stack.imgur.com/N8ibt.png

## Environment

<pre><code>
Angular version: 4.4.4

ng-zorro-antd version: 0.5.3

Browser:
- [X] Chrome (desktop) version 61.0.3163.100
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: v6.9.4  
- Platform:  Mac

**Comment by vthinkxie** [comment]
please use angular-cli or other config that passed our integration test.
https://github.com/NG-ZORRO/ng-zorro-antd/tree/master/integration
