### ISSUE TITLE
nz-tooltip >nzVisible = true ERROR

### ISSUE THREAD

**Issue by luke-emmental** [NG-ZORRO/ng-zorro-antd#4250]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-nzvisible-error?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-nzvisible-error?file=src/app/app.component.html)

### Steps to reproduce
nz-tooltop [nzVisible] = true  occur ERROR message 

### What is expected?
no error

### What is actually happening?
Error: Cannot read property 'elementRef' of undefined

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.1 |
| Browser | chrome |

**Comment by wendzhue** [comment]
It should have been fixed by #4229. Please check after we release a new version. Thank you.

**Comment by luke-emmental** [comment]
Okay 👌
