### ISSUE TITLE
nz-select can not paste clipboard text to the search box

### ISSUE THREAD

**Issue by aaaahoang123** [NG-ZORRO/ng-zorro-antd#4259]
### Reproduction link
[https://stackblitz.com/edit/angular-qplgiw](https://stackblitz.com/edit/angular-qplgiw)

### Steps to reproduce
1. Copy this text to clipboard: One
2. Try to paste the clipboard text to the search box by:
     Tap and hold the search box on Mobile.
     Right click the mouse on PC.

### What is expected?
Can paste the clipboard text to the search box as a normal input, and trigger the (nzOnSearch) event, indeed.

### What is actually happening?
The search box is lost focus when we try to paste (except use ctrl   v). Then we can not paste the clipboard text to it as normal.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.1 |
| Browser | chrome Version 77.0.3865.90 |

**Comment by vthinkxie** [comment]
Hi @aaaahoang123 
this bug is caused by the backdrop div in angular/cdk
there is no other ways to detect click outside the nz-select in current @angular/cdk version, we will keep track with angular/cdk issues

**Comment by aaaahoang123** [comment]
Hi there! It's me again.

It's may be too late for this, but now I've found a workaround to solve this problem. But I am not sure if it is a bad idea.

I have found that the backdrop that yout said have class "cdk-overlay-connected-position-bounding-box", it is a absolute layer with z-index: 1000;

Then I just add some style like this to styles.less:

```
.ant-select-selection-search-input {
  position: absolute;
  z-index: 1001;
}
```

It make the search box inside my <nz-select> is on a higher layer than the backdrop, and then I can trigger that input as normal.

I'm not sure this will help or a breaking change with another features, then I hope you can consider this.
