### ISSUE TITLE
树组件使用自定义模板后节点无法拖拽

### ISSUE THREAD

**Issue by hwangzhiming** [NG-ZORRO/ng-zorro-antd#4269]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-tree-drag](https://stackblitz.com/edit/ng-zorro-antd-tree-drag)

### Steps to reproduce
代码所示

### What is expected?
自定义模板也应支持拖放

### What is actually happening?
不支持

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | Chrome |

**Comment by hwangzhiming** [comment]
看了下源码，自定义模板的节点加上下面的属性即可
`                    [attr.draggable]="true"
                    [class.draggable]="true"
`

**Comment by TureeZhang** [comment]
> 看了下源码，自定义模板的节点加上下面的属性即可
> ` [attr.draggable]="true" [class.draggable]="true"`

谢谢，帮大忙了 ：-）

**Comment by ZaL0-0** [comment]
亲测可以，灰常感谢，v587
