### ISSUE TITLE
[nz-select] select option is not active after dynamically changing select source on (nzOnSearch)

### ISSUE THREAD

**Issue by tky753** [NG-ZORRO/ng-zorro-antd#4279]
### Reproduction link
[https://stackblitz.com/edit/nz-table-dynamic-active?file=src/app/app.component.ts](https://stackblitz.com/edit/nz-table-dynamic-active?file=src/app/app.component.ts)

### Steps to reproduce
1. copy "shen" to static nz-select
2. copy "shen" to dynamic nz-select
![image](https://user-images.githubusercontent.com/18205977/66651871-b6405700-ec66-11e9-8ab7-9b9ad91cbc2e.png)

### What is expected?
select option "shenzhen" is active for both compoments.

### What is actually happening?
select option "shenzhen" is active for static nz-select, 
but select option "shenzhen" is not active for dynamic nz-select.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.1 |
| Browser | Chrome 76.0.3809.132（正式版本） （64 位） |

---
After copying value to nz-select compoment, I have to tap **down arrow** to active the select option even if there is only one option.

**Comment by wenqi73** [comment]
```ts
  constructor(private cdr: ChangeDetectorRef) {}
  onSearch(val: string){
    // ...
    this.cdr.detectChanges();
  }
```
