### ISSUE TITLE
横向滚动条的位置

### ISSUE THREAD

**Issue by wucaibin** [NG-ZORRO/ng-zorro-antd#4294]
## What problem does this feature solve?
既有纵向滚动条又有横向滚动条的情况，需要把纵向滚动条拖到底部，才能使用横向滚动条。这是一个灾难性的设计。

## What does the proposed API look like?
横向滚动条能悬浮在界面底部。

**Comment by vthinkxie** [comment]
具体哪个组件，什么情况下碰到的这个情况
横向和纵向滚动条是由css控制的，不是你用了组件就会全部帮你处理

**Comment by wucaibin** [comment]
table 表格。&nbsp;[nzScroll]="{ x: '1100px' }"&nbsp; &nbsp;[nzScroll]="{ y: '240px' }"&nbsp; &nbsp; 横向和纵向滚动条都有。如果有100行数据，需要将纵向滚动条拉到最底部，才能使用横向滚动条。论坛里好像也有不少人提这个问题。有没有什么设置能让横向滚动条悬浮在底部，不管纵向滚动条在什么位置都能使用横向滚动条？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yadong Xie"<notifications@github.com&gt;; 
发送时间: 2019年10月15日(星期二) 中午11:36
收件人: "NG-ZORRO/ng-zorro-antd"<ng-zorro-antd@noreply.github.com&gt;; 
抄送: "吴才彬"<65581451@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [NG-ZORRO/ng-zorro-antd] 横向滚动条的位置 (#4294)




具体哪个组件，什么情况下碰到的这个情况
 横向和纵向滚动条是由css控制的，不是你用了组件就会全部帮你处理

**Comment by vthinkxie** [comment]
<img width="1163" alt="截屏2019-10-15上午11 44 16" src="https://user-images.githubusercontent.com/1506722/66798602-25f16300-ef41-11e9-9ca3-5be287f1db5b.png">
本来就是悬浮在底部的，官网的demo你看着也有问题？

**Comment by wucaibin** [comment]
框架里的表格高度，是否是开发者根据用户屏幕高度去计算？比如图例里的，表格高度高于屏幕了，就出现横向滚动条看不见，需要先滚动纵向滚动条，才能看见横向滚动条。根据用户屏幕大小去计算表格高度明显不可取。所以想咨询一下，有没有办法将横向滚动条悬浮在屏幕底部。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yadong Xie"<notifications@github.com&gt;; 
发送时间: 2019年10月15日(星期二) 中午11:45
收件人: "NG-ZORRO/ng-zorro-antd"<ng-zorro-antd@noreply.github.com&gt;; 
抄送: "吴才彬"<65581451@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [NG-ZORRO/ng-zorro-antd] 横向滚动条的位置 (#4294)





 本来就是悬浮在底部的，官网的demo你看着也有问题？

**Comment by vthinkxie** [comment]
根据屏幕高度计算为什么不可取，css 里面也就是 calc(100vh - 100px) 这样的表达式，建议了解一下 css 相关内容，组件 api 不会二次包装 css 语法
