### ISSUE TITLE
nzShowSearch on nz-select does not work in IOS 13

### ISSUE THREAD

**Issue by WeslleyDeSouza** [NG-ZORRO/ng-zorro-antd#4296]
### Reproduction link
[https://ng-zorro-antd-start-bbhuis.stackblitz.io](https://ng-zorro-antd-start-bbhuis.stackblitz.io)

### Steps to reproduce
Implemented Attribute:
nzShowSearch

### What is expected?
Input should be focused and keyboard should appear

### What is actually happening?
Keyboard does not appear

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.0 |
| Browser | IOS 13 | IPhone 6< |

---
similar to : https://github.com/NG-ZORRO/ng-zorro-antd/issues/1653

**Comment by WeslleyDeSouza** [comment]
the examples on the official website are also not working...
any solution to this?

**Comment by aaaahoang123** [comment]
@WeslleyDeSouza The same problem here with ios 12. I also face the [#4259](https://github.com/NG-ZORRO/ng-zorro-antd/issues/4259) when use nz-select as a search box.

And then, i make a custom search box by nz-autocomplete like this https://stackblitz.com/edit/angular-pyvfwe to resolve those issues

It is working fine for now, at least it is useful when we wait for an official support for this.

**Comment by WeslleyDeSouza** [comment]
@aaaahoang123 Thanks for ur reply..

note:
If I remove the css class of the parent input element, the keyboard trigger starts to work again..

<li class="ant-select-search ant-select-search--inline">
 <input ...>
</li>

any update on this?

**Comment by junekpavel** [comment]
Hello,
any updates on this? It's serious problem for us.
Is there any chance this issue will be resolved in next version?
Thanks for any reply.

**Comment by WeslleyDeSouza** [comment]
yes in the mean while im using select2, 
till this is fixed..

**Comment by junekpavel** [comment]
Thanks for your advice!
I've already known about select2 ... but because it needs jQuery, it's implementation would be our really really worst case scenario...
And based on their documentation, select2 doesn't cover all features we are currently using with nz-select :(

**Comment by WeslleyDeSouza** [comment]
which feautures do you need that select2 doesn't have?

**Comment by WeslleyDeSouza** [comment]
there is also an npm version of select2 but its also an jQuery wrapper

**Comment by junekpavel** [comment]
Actually, there's a lot, eg. custom `compareWith` function, simple ability to clear selected option, ability to pass custom template when no remote data found, etc. ... 

And I assume there's no output callbacks like `nzOpenChange`, `nzScrollToBottom`, `nzOnSearch` available in it's Angular wrapper.

And at least there's design... it looks different (worse) than nz-select and it feels like it would't be zero-time job to make it look similar to nz-select (and rest of ng-zorro components, we're using)...

**Comment by junekpavel** [comment]
So if is there any way to speed up this bug fixation, I'm all ears.

**Comment by WeslleyDeSouza** [comment]
Is there any chance this issue will be resolved in next version?

**Comment by junekpavel** [comment]
@vthinkxie could you please provide us any information/updates about this?

**Comment by WeslleyDeSouza** [comment]
@junekpavel 
could you create a new ticked?

**Comment by ajhernandez95** [comment]
> @aaaahoang123 Thanks for ur reply..
> 
> note:
> If I remove the css class of the parent input element, the keyboard trigger starts to work again..
> 
> * 
> any update on this?

@WeslleyDeSouza is there any way you can list the exact class you removed to get the keyboard working again on IOS?

**Comment by theadley** [comment]
Managed to **fix** it with a workaround!

I drew inspiration for fixing this issue from [here](https://github.com/wenqi73/ng-zorro-antd/commit/2af8188d1e1ad9da3c73a1e92b523aba98aa6d10) and did the following:

In the `component.less`:
```
::ng-deep nz-select div.ant-select-search.ant-select-search--inline {
  display: block !important;
}
```

Alternatively, you could add it site-wide in `styles.less` after the styles for antd:
```
nz-select div.ant-select-search.ant-select-search--inline {
  display: block !important;
}
```

Unfortunately the `!important` must remain because the display style is dynamically applied (`[style.display]="searchDisplay"`) and therefore applies after CSS applies.

Until an official fix, I hope this workaround can help someone else who's stuck pulling their hair out over this.

**Comment by zbin** [comment]
I found that long press will pop up the keyboard.

**Comment by ReinerRunge** [comment]
> Managed to **fix** it with a workaround!
> 
> I drew inspiration for fixing this issue from [here](https://github.com/wenqi73/ng-zorro-antd/commit/2af8188d1e1ad9da3c73a1e92b523aba98aa6d10) and did the following:
> 
> In the `component.less`:
> 
> ```
> ::ng-deep nz-select div.ant-select-search.ant-select-search--inline {
>   display: block !important;
> }
> ```
> 
> Alternatively, you could add it site-wide in `styles.less` after the styles for antd:
> 
> ```
> nz-select div.ant-select-search.ant-select-search--inline {
>   display: block !important;
> }
> ```
> 
> Unfortunately the `!important` must remain because the display style is dynamically applied (`[style.display]="searchDisplay"`) and therefore applies after CSS applies.
> 
> Until an official fix, I hope this workaround can help someone else who's stuck pulling their hair out over this.

Can confirm this workaround works

**Comment by dylanvdmerwe** [comment]
Any update on an official fix for this issue on iOS as we are experiencing this as well?

**Comment by joaomvfsantos** [comment]
This is also a major blocker for me. Hopefully it gets fixed soon.

**Comment by WeslleyDeSouza** [comment]
Workaround dont work in 9.0.0

**Comment by KwFung7** [comment]
I figure out a workaround, I simply remove "readonly" attribute in nz-select input element to fix this issue. 

`const inputEle = this.renderer.selectRootElement('nz-select nz-select-search input');`
`this.renderer.removeAttribute(inputEle , 'readonly');`

**Comment by Drunkenpilot** [comment]
> I figure out a workaround, I simply remove "readonly" attribute in nz-select input element to fix this issue.
> 
> `const inputEle = this.renderer.selectRootElement('nz-select nz-select-search input');`
> `this.renderer.removeAttribute(inputEle , 'readonly');`

This workaround works



```
 ngAfterViewInit(): void {
    setTimeout(() => {
      const allEles: any = document.querySelectorAll('nz-select nz-select-top-control nz-select-search input');
      for (const ele of allEles) {
        this.renderer.removeAttribute(ele, 'readonly');
      }
    }, 1500);

  }

  onBlur() {
    console.log('blur triggered');
    setTimeout(() => {
      const allEles: any = document.querySelectorAll('nz-select nz-select-top-control nz-select-search input');
      for (const ele of allEles) {
        this.renderer.removeAttribute(ele, 'readonly');
      }
    }, 500);
  }
```

```
<form>
.....
<nz-form-item>
<nz-form-control>
        <nz-select
          nzShowSearch
          formControlName="test1"
          (nzBlur)="onBlur()"
        >
....
</nz-select>
<nz-form-control>
</nz-form-item>

<nz-form-item>
<nz-form-control>
        <nz-select
          nzShowSearch
          formControlName="test2"
          (nzBlur)="onBlur()"
        >
....
</nz-select>
<nz-form-control>
</nz-form-item>
......
</form>
```

**Comment by Folo4ka** [comment]
fix this, please. It happening on all mobile devices, on android too.

**Comment by wenqi73** [comment]
Maybe the same problem with #5645.
