### ISSUE TITLE
Tooltip always visible

### ISSUE THREAD

**Issue by dylanvdmerwe** [NG-ZORRO/ng-zorro-antd#4297]
### Reproduction link
[https://stackblitz.com/edit/angular-yfkrry?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-yfkrry?file=src/app/app.component.ts)

### Steps to reproduce
Set `[nzVisible]='false'` always shows the tooltip. 

### What is expected?
There needs to be a bindable way to deactivate a tooltip. Either by setting visible to false or have a new disabled property. 

### What is actually happening?
The tooltip is always visible and cannot be disabled.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.0 |
| Browser | Chrome |

**Comment by wendzhue** [comment]
Try to set `[nzTrigger]="null"`. Refer to https://github.com/NG-ZORRO/ng-zorro-antd/blob/02ff1e92eb5114e7e960b73b358b185276832ec1/components/slider/nz-slider-handle.component.html#L6.

**Comment by dylanvdmerwe** [comment]
`[nzTrigger]="null"` works thank you. I feel this needs to potentially be better documented.

**Comment by wendzhue** [comment]
Yes please check #4298.
