### ISSUE TITLE
Global prompt

### ISSUE THREAD

**Issue by mjn1154477982** [NG-ZORRO/ng-zorro-antd#430]
If you click twice to show the load, then the prompt will not disappear, how should this be handled?
![_15078605111302](https://user-images.githubusercontent.com/20697182/31527336-06a20190-afff-11e7-8b8b-429549f3ca63.png)
![default](https://user-images.githubusercontent.com/20697182/31527347-1fe1c2e4-afff-11e7-8022-0c63f66dd096.png)

**Comment by vthinkxie** [comment]
just read the demo code, you need to manage a list of _id instead of _id.
