### ISSUE TITLE
Timeline时间轴，左右同时显示文字

### ISSUE THREAD

**Issue by zyuelei** [NG-ZORRO/ng-zorro-antd#4305]
## What problem does this feature solve?
可以将时间单独放在左面，右面为自定义文字，页面整洁规整

## What does the proposed API look like?
```
<nz-timeline nzMode="right">
      <nz-timeline-item nzLeftText="2019年10月17日" nzIndentSize="30px">某某调动</nz-timeline-item>
</nz-timeline>
```

**Comment by hsuanxyz** [comment]
@zyuelei Ant Design 还不支持次功能，请将你的需求提交给 [ant-design](https://github.com/ant-design/ant-design)。我们会与其保持同步。
