### ISSUE TITLE
nz-table的第一列不设置nzWidth，后面列乱了

### ISSUE THREAD

**Issue by MagicWang** [NG-ZORRO/ng-zorro-antd#4312]
### Reproduction link
[https://stackblitz.com/edit/angular-o3qap2](https://stackblitz.com/edit/angular-o3qap2)

### Steps to reproduce
第一列不设置nzWidth时后面列的宽度乱了
第一列设置为auto就正常

### What is expected?
第二列150px
第三列350px

### What is actually happening?
第一列150px
第二列350px

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.0 |
| Browser | chrome |

**Comment by lppedd** [comment]
This is caused by commit a9900edd
which introduced an `*ngIf="th.nzWidth"` to render the `col` element.

```
<ng-container *ngFor="let th of listOfNzThComponent">
  <col [style.width]="th.nzWidth" [style.minWidth]="th.nzWidth" *ngIf="th.nzWidth">
</ng-container>
```

@vthinkxie I think I get the behavior intention, the logic could be refactored a bit?

**Comment by vthinkxie** [comment]
> This is caused by commit [a9900ed](https://github.com/NG-ZORRO/ng-zorro-antd/commit/a9900edd6e11aa51b3f54fe50a73fcb679f0bca9)
> which introduced an `*ngIf="th.nzWidth"` to render the `col` element.
> 
> ```
> <ng-container *ngFor="let th of listOfNzThComponent">
>   <col [style.width]="th.nzWidth" [style.minWidth]="th.nzWidth" *ngIf="th.nzWidth">
> </ng-container>
> ```
> 
> @vthinkxie I think I get the behavior intention, the logic could be refactored a bit?

yes, it is a bug, we will fix it soon
