### ISSUE TITLE
nz-button 找不到多語系翻譯的 Key 時，瀏覽器當機並導致 CPU 飆高

### ISSUE THREAD

**Issue by lawrence8358** [NG-ZORRO/ng-zorro-antd#4314]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-translate-issue](https://stackblitz.com/edit/ng-zorro-translate-issue)

### Steps to reproduce
在 nz-button 內，放上一個 Html 的標籤(ex. span、div...)，該標籤使用 property 的方式設定 translate pipe，例如底下的程式碼

```html
<button nz-button>
  <span [translate]="'i18n.key.notfound'"></span>
</button>

<button nz-button>
  <span translate="i18n.key.notfound"></span>
</button>

<!-- 底下這些寫法都是正常的 --> 
<button>
  <span [translate]="'i18n.key.notfound'"></span>
</button>

<button nz-button>
  {{ 'i18n.key.notfound' | translate }}
</button> 
```

### What is expected?
當找不到 translate 的Key 時，應該直接顯示該 Key

### What is actually happening?
瀏覽器當掉，並且 CPU 飆高，僅能強制關閉該瀏覽器。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.0 |
| Browser | Chrome 77.0.3865.120  |

---
該使用情境下，找不到多語系，會一直無窮迴圈的一直嘗試尋找多語系欄位，才導致 CPU 飆升。

經過交叉測試，在 ng-zorro-antd@7.5.1 之前的版本該用法是可正確執行的，但升級到 ng-zorro-antd@8.x 版後，該問題就發生了，一直到目前最新的版本此問題仍然持續存在。

**Comment by wendzhue** [comment]
似乎和 zorro 的 button 组件的生命周期，与 ngx-translate 的生命周期冲突有关：https://github.com/ngx-translate/core/blob/f761cea2ec15880462277c2a3df1aae1c5c4d217/projects/ngx-translate/core/src/lib/translate.directive.ts#L60-L96

ngx-translate 的 translate 指令会去修改 DOM 结构，对结构的修改又会被 zorro 所监听 https://github.com/NG-ZORRO/ng-zorro-antd/blob/f203afd53c4e35e5be800765d8cc01cee40087de/components/button/nz-button.component.ts#L111-L130

降级到 7.5.1 的时候 ngx-translate 的版本和你在用 Angular 8 及以上的时候所使用的版本是一致的吗？

**Comment by lawrence8358** [comment]
是的，都一樣使用 ngx-translate@11.0.1 。

問題可能如您描述的那樣，但如果是這樣的話，可有解決辦法?

**Comment by lawrence8358** [comment]
> 似乎和 zorro 的 button 组件的生命周期，与 ngx-translate 的生命周期冲突有关：https://github.com/ngx-translate/core/blob/f761cea2ec15880462277c2a3df1aae1c5c4d217/projects/ngx-translate/core/src/lib/translate.directive.ts#L60-L96
> 
> ngx-translate 的 translate 指令会去修改 DOM 结构，对结构的修改又会被 zorro 所监听
> 
> https://github.com/NG-ZORRO/ng-zorro-antd/blob/f203afd53c4e35e5be800765d8cc01cee40087de/components/button/nz-button.component.ts#L111-L130
> 
> 降级到 7.5.1 的时候 ngx-translate 的版本和你在用 Angular 8 及以上的时候所使用的版本是一致的吗？

是的，都一樣使用 ngx-translate@11.0.1 。

問題可能如您描述的那樣，但如果是這樣的話，可有解決辦法?

**Comment by vthinkxie** [comment]
在下个版本会被修复
