### ISSUE TITLE
通知提醒框全局配置在生产环境中不生效

### ISSUE THREAD

**Issue by tazyong** [NG-ZORRO/ng-zorro-antd#4319]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-19p5nt](https://stackblitz.com/edit/ng-zorro-antd-start-19p5nt)

### Steps to reproduce
任何时候必现

### What is expected?
在生产环境里，根据自定义配置正确显示通知提醒框。

### What is actually happening?
全局配置了通知提醒框在右下角显示，在开发环境正常，但在生产环境依然显示在左上角。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.0 |
| Browser | 77.0.3865.120 |

**Comment by wendzhue** [comment]
请查看 https://github.com/NG-ZORRO/ng-zorro-antd/issues/4323#issuecomment-544208799

**Comment by wendzhue** [comment]
@tazyong Thanks for reporting this. It looks that after compiling our code breaks:

Dev:

![Snipaste_2019-10-20_10-04-34](https://user-images.githubusercontent.com/12122021/67153738-2b73f200-f321-11e9-86cf-13874a76e73a.png)

Prod:

![Snipaste_2019-10-20_10-01-42](https://user-images.githubusercontent.com/12122021/67153739-2fa00f80-f321-11e9-8f61-e248535713f2.png)

We will fix this soon.

**Comment by wendzhue** [comment]
@tazyong Have you tried other config?
