### ISSUE TITLE
分组table怎么写？

### ISSUE THREAD

**Issue by wangying11** [NG-ZORRO/ng-zorro-antd#432]
可不可以出一个分组table，子table和父table可以用不同的表栏

**Comment by tigercosmos** [comment]
不太懂你意思 可以附圖上來？

**Comment by wilsoncook** [comment]
Actually, the `nz-table` act as normal `<table>` tag, and the usage is the same, so you can try as below fake codes:
```html
<nz-table>
...
  <tr><td>
    <nz-table>...</nz-table>
  </td></tr>
...
</nz-table>
```
