### ISSUE TITLE
NzTable的tree型数据展示

### ISSUE THREAD

**Issue by jacobearl** [NG-ZORRO/ng-zorro-antd#4322]
## What problem does this feature solve?
现在在处理一些拥有父子关系的数据,比如说资源,常常一个资源下又有很多资源，此时想要使用NzTable里的tree型数据展示，但发现ng-zorro-antd的nzTable在这方面的处理比较复杂,并且例子也不太好理解

## What does the proposed API look like?
能否像elementui给表格加的 tree-props属性一样, 也给NzTable添加一个类似的属性，用来支持表格数据中children数据的渲染
 ```
<nz-table #nzTable [nzData]="dataList"  [tree-props]="{children: 'children', hasChildren: 'hasChildren'}">
</nz-table>
```<!-- generated by ng-zorro-issue-helper. DO NOT REMOVE -->

**Comment by vthinkxie** [comment]
nz-table 所有的dom结构都是用户可以自由控制的，组件的设计已经是所有结构由用户控制，添加这种api 和目前组件设计是直接冲突的，你可以自行封装 nz-table 使用，事实上绝大部分用户也是这样使用的
