### ISSUE TITLE
slider: focusable and keyboard control

### ISSUE THREAD

**Issue by hsuanxyz** [NG-ZORRO/ng-zorro-antd#4328]
![slider](https://user-images.githubusercontent.com/22736418/67175404-875d7a00-f3f8-11e9-9594-73c21c62a941.gif)

**Comment by wendzhue** [comment]
And reverse: https://ant.design/components/slider-cn/#components-slider-demo-reverse.

**Comment by wendellhu95** [comment]
This feature is already implemented. Closing now.
