### ISSUE TITLE
pagination pageIndex changes events 怎么写？

### ISSUE THREAD

**Issue by ZjVirus** [NG-ZORRO/ng-zorro-antd#433]
分页的pageIndex改变的方法怎么写？

**Comment by vthinkxie** [comment]
(nzPageIndexChange)

**Comment by ryancui-** [comment]
I found no documentation about pagination change events at 

https://ng.ant.design/#/components/pagination

so we have to dive into the source. Hope an update for the pagination showcase.

**Comment by vthinkxie** [comment]
all double binding property like [(property)] has two method [property] and (propertyChange) it should be an common sense for angular developers.

**Comment by ryancui-** [comment]
oh got it, thx.
