### ISSUE TITLE
The first column of the `Table` component' is not center aligned when set the `nzScroll` property.

### ISSUE THREAD

**Issue by xixixixixiao** [NG-ZORRO/ng-zorro-antd#4334]
### Reproduction link
[https://stackblitz.com/edit/angular-wrfp23](https://stackblitz.com/edit/angular-wrfp23)

### Steps to reproduce
1. Add the `nz-table` component.
2. Set the `<th>`'s *nzShowCheckbox* property of the component's `thead`.
3. Set the `<td>`'s *nzShowCheckbox* property of the component's `tbody`.
4. Set the `nz-table`'s *nzScroll* to equal "{ y: '500px' }".
5. It will be reproduced.

### What is expected?
The first column of the `Table` component' is center aligned when set the `nzScroll` property.

### What is actually happening?
The first column of the `Table` component' is not center aligned when I both set the `nzScroll` and `nzShowCheckbox` properties.
The code like below:

```html
<nz-table [nzScroll]="{ y: '500px' }">
    <thead>
        <tr>
                <th nzShowCheckbox></th>
        </tr>
    </thead>
    <tbody>
        <tr>
                <td nzShowCheckbox></td>
        </tr>
    </tbody>
</nz-table>
```

Like the figure below:
![Snipaste_2019-10-22_17-02-25](https://user-images.githubusercontent.com/13077617/67271759-c8838600-f4ed-11e9-8cff-a039ce82ca3c.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.0 |
| Browser | Firefox 69.0.3 / Google Chrome 77.0.3865.120 |

**Comment by vthinkxie** [comment]
you have to give nzWidth if you set nzScroll
> Specify the width of each th if header and cell do not align properly.

https://ng.ant.design/components/table/en#components-table-demo-fixed-header

**Comment by xixixixixiao** [comment]
> 
> 
> you have to give nzWidth if you set nzScroll
> 
> > Specify the width of each th if header and cell do not align properly.
> 
> https://ng.ant.design/components/table/en#components-table-demo-fixed-header

Thank you for responding. I've worked out this problem.
