### ISSUE TITLE
Allow TemplateRef for nz-select nzPlaceHolder value

### ISSUE THREAD

**Issue by darshanrampatel** [NG-ZORRO/ng-zorro-antd#4337]
## What problem does this feature solve?
At the moment, `nzPlaceHolder` can only be a string: https://github.com/NG-ZORRO/ng-zorro-antd/blob/13b861ca5959998942e9246b4de9f356a2a88b85/components/select/nz-select-top-control.component.html#L16

Since we can use a template for the selected value via `nzCustomTemplate` it makes sense to allow this for the `nzPlaceHolder` value.
## What does the proposed API look like?
`@Input() nzPlaceHolder: string | TemplateRef<void>;`

**Comment by wenqi73** [comment]
`string` is enough for most scenarios, we have no plan to support this.
