### ISSUE TITLE
feat request: support nzPlacement & nzTop in NzMessageDataOptions

### ISSUE THREAD

**Issue by wendellhu95** [NG-ZORRO/ng-zorro-antd#4338]
`NzMessageDataOptions` should support more properties like the React version. Ref https://ant.design/components/notification/#header. Ref #4323. cc @lppedd

**Comment by lppedd** [comment]
@wendzhue thanks! I can do it.

**Comment by wendzhue** [comment]
@lppedd Really appreciate it!

**Comment by lppedd** [comment]
@wendzhue I had a couple minutes to reflect on the implementation, and I think we get an easier time compared on the React approach.

For example, we can keep track of the requested placements via the submitted messages, like
```html
<div
  *ngFor="let placement of placementsSet | async"  (aid change detection)
  class="ant-notification ant-notification-{{ placement }}"
  [style... (omitted)"
>
  <nz-notification
    *ngFor="let message of messages[placement]; let i = index"
    [nzMessage]="message"
    [nzIndex]="i">
  </nz-notification>
</div>
```
This would meam not even having empty placeholder `div`s in DOM.
What do you think?

**Comment by wendzhue** [comment]
@`lppedd` Looks good!

**Comment by lppedd** [comment]
@wendzhue regarding the `top` and `bottom` properties, how should I go with those?
Currently it's the container who's setting the distance, not the individual notifications. The React version seems to let setting the distance only for the first notification.  
Are there guidelines for this?

**Comment by lppedd** [comment]
@wendzhue Ok. I have a working concept.
To maintan the distances I use a `Map<string, string>` currently.

![image](https://user-images.githubusercontent.com/19871649/67621162-f3334e80-f80d-11e9-9e6a-51139c2375d3.png)

Example:
![notifications](https://user-images.githubusercontent.com/19871649/67621193-52915e80-f80e-11e9-865b-495e0ec1fa97.gif)

I don't like how I currently use the `Map` in template. I think I can transform it via `Pipe`, or I have to choose another structure. Although a map is good for this.

```html
<div
  *ngFor="let placement of placements.entries(); trackBy: trackByName"
  class="ant-notification ant-notification-{{ placement[0] }}"
  [style.top]="placement[0] === 'topLeft' || placement[0] === 'topRight' ? placement[1] : null"
  ...
```

**Comment by wendzhue** [comment]
Hi @lppedd . Sorry for the late reply. Your proposal looks good. Maybe we can have furthur discussions after you submit your PR requests. 😄

**Comment by lppedd** [comment]
@wendzhue sure! I'm not at home today so expect it for tomorrow :smile:

**Comment by wendzhue** [comment]
@lppedd Ping~ Are you still working on this? If you have no time for this I could take it over.
