### ISSUE TITLE
nz-upload - Override HTTP method with component options

### ISSUE THREAD

**Issue by amityagov** [NG-ZORRO/ng-zorro-antd#4339]
## What problem does this feature solve?
Hi,

Component [nz-upload-btn.component.ts](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/upload/nz-upload-btn.component.ts#L257) has big private method **xhr()** with complicated logic and hadrcoded http method POST. And it also call some private instance methods.

I use minio which implements Amazon S3 api to upload files and only accepts PUT http method. 

'X-HTTP-Method-Override': 'PUT' via [nzHeaders] does not work.

## What does the proposed API look like?
Add [nzMethod] input to component with default value POST

**Comment by cipchk** [comment]
@amityagov You can use `nzCustomRequest` to change the default network request.

**Comment by amityagov** [comment]
@cipchk `nzCustomRequest` it is not about change request. This is replacement for default xhr(),
according to this [line](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/upload/nz-upload-btn.component.ts#L249):
```
const req$ = (opt.customRequest || this.xhr).call(this, args);
```

This is strange to replace whole function only to replace one word.

**Comment by cipchk** [comment]
fixed by `9.x`
