### ISSUE TITLE
Allow setting nzModalTitle via a directive (similar to nzModalFooter)

### ISSUE THREAD

**Issue by darshanrampatel** [NG-ZORRO/ng-zorro-antd#4343]
## What problem does this feature solve?
It would be useful to be able to set a modal's title via a directive, similar to nzModalFooter: https://github.com/NG-ZORRO/ng-zorro-antd/pull/3036

## What does the proposed API look like?
Similar to nzModalFooter directive:
```
<div *nzModalTitle>
  Modal Title
</div>
```

**Comment by jongomes** [comment]
Need this
