### ISSUE TITLE
NzModalService options (nzClosable, nzMaskClosable) not working as expected

### ISSUE THREAD

**Issue by sivaecekrr** [NG-ZORRO/ng-zorro-antd#4344]
### Reproduction link
[https://stackblitz.com/edit/angular-asqech](https://stackblitz.com/edit/angular-asqech)

### Steps to reproduce
Configure NzModalService in a component and enable nzClosable, nzMaskClosable. Even the example present in the document site is not working.

### What is expected?
Close icon on top right corner should be visible and when click area outside the modal, then the modal should close.

### What is actually happening?
The options nzClosable, nzMaskClosable are not working

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | Chrome 77 |

**Comment by hsuanxyz** [comment]
@sivaecekrr Thanks for the feedback. `nzClosable` unavailable in the confirm box mode is by design, but the `nzMaskClosable` not working is a bug. We will fix it in the next version.

**Comment by sivaecekrr** [comment]
@hsuanxyz I agree for nzModalService.confirm nzClosable is not available. But the same applicable for nzModalService.info also. Because info mode doesn't need any confirmation. Let me know your thoughts. Thanks.
