### ISSUE TITLE
穿梭框二次校验无法获取到数据源(Transfer Check Before Move can't get source data)

### ISSUE THREAD

**Issue by VenomChen** [NG-ZORRO/ng-zorro-antd#4353]
### Reproduction link
[https://stackblitz.com/edit/angular-irwbwh](https://stackblitz.com/edit/angular-irwbwh)

### Steps to reproduce
在穿梭框二次校验的方法中我需要获取数据源（list）与待穿梭的数据进行比较，从而判断是否允许穿梭，但我在二次校验的方法里始终获取不到数据源！望指教~谢谢！
In the method of check before move, I need to get a data source (list) to compare with the data to be shuttled to determine whether the shuttle is allowed, but I can never get the data source in the check before move method! Hope to teach ~ Thank you!

### What is expected?
二次校验方法里将待穿梭数据与穿梭框中的数据源进行比较判断

### What is actually happening?
无法获取到数据源（list undefined）

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | Chrome |

---
我穿梭框里放的是菜单信息，有一级菜单二级菜单。。。只有一级菜单在右边，二级菜单才允许到右边

**Comment by wenqi73** [comment]
`canMove` 使用箭头函数。
