### ISSUE TITLE
日期时间DatePicker，选择日期和时间不太方便。我简单写了一个。觉得这样更好用。

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#4356]
### Reproduction link
[https://stackblitz.com/edit/angular-jsvvne?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-jsvvne?file=src/app/app.component.ts)

### Steps to reproduce
1、选日期， 2、选时间

### What is expected?
官方组件：datePicker，增加一种选择方式，日期和时间分开

### What is actually happening?
datePicker不太好用

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | Chrome 72 |

---
抱歉，这是一个功能需求， 我写了个样例。 不是错误报告

**Comment by hsuanxyz** [comment]
@liwei511 你好，非常感谢你的建议。 

NG-ZORRO 是 Angular 版本的 Ant Design 实现，你有任何对组件设计的建议和想法都可以向 [ant-design ](https://github.com/ant-design/ant-design )提交。之后我们会同步实现。
