### ISSUE TITLE
Can't bind to 'nzTargetKeys' since it isn't a known property of 'nz-transfer'

### ISSUE THREAD

**Issue by ChaoQunPeng** [NG-ZORRO/ng-zorro-antd#4360]
### Reproduction link
[https://stackblitz.com/edit/angular-o7shy6?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-o7shy6?file=src/app/app.component.ts)

### What is actually happening?
 

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | Chrome  78.0.3904.70 |

**Comment by wenqi73** [comment]
Thank you for report, there is no `nzTargetKeys`, the document did not update.
