### ISSUE TITLE
nz-select多选，当ngmodel初始值为空字符串而不是数组时，报错

### ISSUE THREAD

**Issue by MagicWang** [NG-ZORRO/ng-zorro-antd#4370]
### Reproduction link
[https://stackblitz.com/edit/angular-ya1xwa](https://stackblitz.com/edit/angular-ya1xwa)

### Steps to reproduce
1、打开重现链接，可以在console时看到报错信息，ERROR TypeError: this.listOfSelectedValue.forEach is not a function
我知道初始值应该为一个数组，但是以前有很多代码都是赋的空字符串，希望能兼容一下

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | chrome 78 |

**Comment by vthinkxie** [comment]
代码不会兼容错误的使用方式，空字符串和null和undefined都是有独立意义的
