### ISSUE TITLE
nz-transfer renderList call always

### ISSUE THREAD

**Issue by tumblingG** [NG-ZORRO/ng-zorro-antd#4373]
# Reproduction link
https://ng.ant.design/components/transfer/zh#components-transfer-demo-table-transfer

# Steps to reproduce
when I use the nz-transfer with a renderList table, like the demo in the ant-design, `<nz-table #t [nzData]="convertItems(items)" nzSize="small">`, convertItems(items) function is always call which make the page die。

# What is expected?
only when the data change  that can call the convertItems(items)

**Comment by vthinkxie** [comment]
@tumblingG 在template上绑定方法是100%错误的写法，请仔细阅读 angular 文档
