### ISSUE TITLE
对某一列数据进行筛选，指定 th 的 nzShowFilter 属性来展示筛选菜单，筛选菜单按钮：确定和重置是否可有属性更改

### ISSUE THREAD

**Issue by 007GitHu** [NG-ZORRO/ng-zorro-antd#4378]
## What problem does this feature solve?
增强其灵活度，开发属性由业务自定义

## What does the proposed API look like?
filterOk:string：默认值确定
filterReset:string：默认值重置

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/table/zh#components-table-demo-custom-filter-panel
可以通过自定义筛选菜单完成你的需求
