### ISSUE TITLE
全局设置date picker时区

### ISSUE THREAD

**Issue by cran208** [NG-ZORRO/ng-zorro-antd#4379]
## What problem does this feature solve?
由于业务需要，我们后台系统中的时间都要求按北京时间设置并保存，但当用户切换了系统时区以后，date picker中显示的时间会根据系统时区变化，而用户仍然以为这是北京时间，导致误解。如果可以在config中全局设置date picker中显示时间的时区，则能解决这个问题

## What does the proposed API look like?
在component/i18n/date-config中增加设置
```
 export const NZ_DATE_CONFIG_DEFAULT: NzDateConfig = {
  firstDayOfWeek: undefined,
  dateTimezone:undefined
 };
 ....
 export interface NzDateConfig {
  /** Customize the first day of a week */
  firstDayOfWeek?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  dateTimezone?:string
 }
```

并在component/i18n/date-helper.service中应用设置
```
export class DateHelperByDatePipe extends DateHelperService {
 ....
 format(date: Date | null, formatStr: string): string {
    return date ? formatDate(date, formatStr, this.i18n.getLocaleId(), this.config.dateTimezone)! : '';
 }
 ....
}
```

使用方法同firstDayOfWeek

**Comment by vthinkxie** [comment]
组件不会统一处理用户传入的时间，如果想要根据特定时区设置，可以使用 date-fns 或者 https://angular.io/api/common/DatePipe 的 timezone属性，自行 format 或者 offset 传入时间

**Comment by cran208** [comment]
不是统一处理传入时间，并不会改变字段值，只是显示的时候按预设的时区显示，不设置时区就是按系统时间，本质上和datePipe的timezone是一个意思，只是date picker的timezone我们没法从外部设置。

而且date picker没有给可以设置timezone的属性啊？

**Comment by vthinkxie** [comment]
@cran208 你可以通过增加一个 timezonePipe 来直接解决这个问题。
组件的时间框架是 date-fns 和 angular 的 data-pipe 提供的，在这两者没有提供全局统一配置的时候，单独date-picker提供配置是肯定有问题的，全局页面需要保持所有的format一致，如果只是根据设定format了date-picker的内容，那用户自己 | date 的内容必然和datepicker展示的不不一致。

**Comment by cran208** [comment]
> @cran208 你可以通过增加一个 timezonePipe 来直接解决这个问题。
> 组件的时间框架是 date-fns 和 angular 的 data-pipe 提供的，在这两者没有提供全局统一配置的时候，单独date-picker提供配置是肯定有问题的，全局页面需要保持所有的format一致，如果只是根据设定format了date-picker的内容，那用户自己 | date 的内容必然和datepicker展示的不不一致。
> 
> 全局配置和全局生效是一个概念，组件库不会提供一个只在 部分范围内 生效的 全局配置。
> 
> 如果你希望这部分能够工作，应该要给 angular 提一个 issue，希望 datepipe 的 timezone 和 local 一样是可以全局配置的

我明白你的意思，但现在的问题是我可以通过 | date来使binding类型的时间按我想要的timezone显示，却没有办法设置date-picker组件中显示时间的timezone，这同样会导致date-picker和 | date的显示不一致。

那么我想问的是，我能在date-picker组件里设置timezone吗？按我目前的理解，nzFormat是无法设置timezone的

**Comment by vthinkxie** [comment]
是不可以的，所以我建议你把所有的date都统一处理掉，比如自定义一个 CustomDate 的类型，所有的 Date 统一转换成 CustomDate，再交给组件处理，最后回传后台的时候在 interceptor 做二次处理

**Comment by cran208** [comment]
> 是不可以的，所以我建议你把所有的date都统一处理掉，比如自定义一个 CustomDate 的类型，所有的 Date 统一转换成 CustomDate，再交给组件处理，最后回传后台的时候在 interceptor 做二次处理

好吧，我写的全局配置确实不太合理，是个偷懒的做法，其实如果能给date-picker组件添加timezone属性的话也能满足这个需求。

那请问会有计划给date-picker添加timezone属性吗？既然date-picker使用了datePipe或date-fns来做日期格式化，那么如果可以支持完整参数应该更好吧。

或者我可以再提个issue+PR来实现这个功能？

**Comment by vthinkxie** [comment]
欢迎提issue+PR，不过需要注意的是现在的datepicker的底层依赖是可选的，如果你要实现的话，需要注意datepipe和date-fns的差别
