### ISSUE TITLE
ng-zorro Tree树控件是否可以彼此拖动节点？如何设置呢

### ISSUE THREAD

**Issue by lengmoukong** [NG-ZORRO/ng-zorro-antd#4384]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-tree-drag](https://stackblitz.com/edit/ng-zorro-antd-tree-drag)

### Steps to reproduce
1、nz-tree组件
2、自定义模板
3、在模板中设置了draggable
4、各个节点互相拖动，子节点可以拖动到父节点外层

### What is expected?
1、各个节点内部子节点不影响
2、同级节点进行拖动

### What is actually happening?
各个节点互相拖动，子节点可以拖动到父节点外层

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | 谷歌 |

**Comment by lengmoukong** [comment]
已解决 
通过判断目标层级就可以了

**Comment by ZaL0-0** [comment]
@lengmoukong 麻烦问下你的自定义模板一共几级菜单，我看demo只有两级，那如果是很多层菜单要怎么生成？
