### ISSUE TITLE
table中，[nzDisabled]="0" 时判断错误， 0是false。checkbox却是disable的状态

### ISSUE THREAD

**Issue by liwei511** [NG-ZORRO/ng-zorro-antd#4385]
### Reproduction link
[https://stackblitz.com/edit/angular-zsj4bt](https://stackblitz.com/edit/angular-zsj4bt)

### Steps to reproduce
[nzDisabled]="0" 和 [nzDisabled]="1" 效果是一样的。只有设置成 ‘!!data.status’ 或 ‘data.status>0’ ， 才能正确识别。

### What is expected?
正确处理[nzDisabled]。 [nzDisabled] 是怎么实现的，对于数字‘0’怎么判断的？

### What is actually happening?
[nzDisabled]判断有误

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | chrome 72 |

**Comment by vthinkxie** [comment]
nzDisabled 本来只接收 bool 值，为什么会觉得传 0 进去组件应该能正常工作？

**Comment by liwei511** [comment]
为啥人家*ngIf可以，你不可以？

**Comment by liwei511** [comment]
@vthinkxie 我还是觉得，js认为是true， nzDisabled就应该认为是true。false同。

**Comment by vthinkxie** [comment]
ngIf接收的类型是any，nzDisabled接受的类型是boolean，使用Typescript就按照文档传入数据，不传boolean 在 fullTemplateTypeCheck 打开的时候编译都会报错，不愿意按类型传入数据，为什么要使用Typescript
