### ISSUE TITLE
date-picker: output Date value from ngModel contains unexpected segments

### ISSUE THREAD

**Issue by bossqone** [NG-ZORRO/ng-zorro-antd#4391]
### Reproduction link
[https://stackblitz.com/edit/angular-kegg7j](https://stackblitz.com/edit/angular-kegg7j)

### Steps to reproduce
- define date picker with `nzFormat="yyyy-MM-dd HH:mm"` and `[nzShowTime]="{ nzFormat: 'HH:mm' }"`
- open date picker 
- change date or time
- check console output

### What is expected?
Output Date from ngModel should not contain seconds and milliseconds (these parts should be set to 0) because they are not specified in `nzFormat`.

### What is actually happening?
Output Date from ngModel contains segments which are not specified in `nzFormat`.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | any |

**Comment by wenqi73** [comment]
The type of model change value is always `Date`, you can format after you get it.
