### ISSUE TITLE
结果页面嵌入步骤条，步骤条样式会错乱

### ISSUE THREAD

**Issue by wuaries** [NG-ZORRO/ng-zorro-antd#4394]
### Reproduction link
[https://stackblitz.com/edit/angular-mef8ey?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-mef8ey?file=src/app/app.component.ts)

### Steps to reproduce
  <nz-result
      nzStatus="success"
      nzTitle="Successfully Purchased Cloud Server ECS!"
      nzSubTitle="Order number: 2017182818828182881 Cloud server configuration takes 1-5 minutes, please wait."
    >
      <div nz-result-extra>
       <nz-steps [nzCurrent]="1" [nzProgressDot]="progressTemplate">
      <nz-step nzTitle="Finished" nzDescription="You can hover on the dot."></nz-step>
      <nz-step nzTitle="In Progress" nzDescription="You can hover on the dot."></nz-step>
      <nz-step nzTitle="Waiting" nzDescription="You can hover on the dot."></nz-step>
      <nz-step nzTitle="Waiting" nzDescription="You can hover on the dot."></nz-step>
    </nz-steps>
    <ng-template #progressTemplate let-dot let-status="status" let-index="index">
      <span nz-popover nzContent="steps {{ index }} status: {{ status }}" style="margin-left: -100%;">
        <ng-template [ngTemplateOutlet]="dot"></ng-template>
      </span>
    </ng-template>
        <button nz-button nzType="primary">Go Console</button>
        <button nz-button>Buy Again</button>
      </div>
    </nz-result>

### What is expected?
步骤条样式正常显示

### What is actually happening?
步骤条样式会向左偏移

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | 谷歌浏览器 |

**Comment by hsuanxyz** [comment]
@wuaries 你把 content 内容放进了 extra。

https://stackblitz.com/edit/angular-mef8ey-jegqxp?file=src/app/app.component.ts
