### ISSUE TITLE
nz-tree-select 在form表单中使用 formControlName 报错

### ISSUE THREAD

**Issue by WuZhenXing** [NG-ZORRO/ng-zorro-antd#4401]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ww73mv?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-ww73mv?file=src/app/app.component.html)

### Steps to reproduce
<form nz-form [formGroup]="resourceForm">
  <nz-form-item>
    <nz-form-label >父节点</nz-form-label>
    <nz-form-control [nzSpan]="12" nzHasFeedback>
            <nz-tree-select
        style="width: 250px"
        [nzNodes]="resourceTree"
        nzShowSearch
        nzPlaceHolder="选择父节点"
        formControlName="parentId"
      >
      </nz-tree-select>
    </nz-form-control>
  </nz-form-item>
</form>

### What is expected?
显示正常回填表单

### What is actually happening?
报错找不到属性

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | chrome 版本 78.0.3904.70（正式版本） （64 位） |

**Comment by hsuanxyz** [comment]
@WuZhenXing 复现链接不可用。

1. 没有定义有效的 `[nzNodes]` 作为数据源
2. 也没有引入 `ReactiveFormsModule`

请提供可以正确复现链接
