### ISSUE TITLE
nz-menu-item doesn't work with CanDeactivate and current route 

### ISSUE THREAD

**Issue by nitrexx** [NG-ZORRO/ng-zorro-antd#4407]
### Reproduction link
[https://stackblitz.com/github/nitrexx/ng-zorro-menu-bug](https://stackblitz.com/github/nitrexx/ng-zorro-menu-bug)

### Steps to reproduce
1. Create 2 components with router
2. Create component with nz-menu with nzMatchRouter
3. Create Interface wiht CanDeactivate method
4. Implements Interface with CanDeactivateMethod in components and return false
5. Create guard for canDeactivate router paramater
6. Click on first item in menu, it will change a route to the component 
7. Click on second item (canDeactivate returns false and route is same like in previous step), ng-menu-item change active item to the second item

### What is expected?
It shouldn't change selected item in menu on click but on the route if I use nzMatchRouter

### What is actually happening?
It changes selected menu item on click event and not depends on route

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.4.1 |
| Browser | google chrome Version 77.0.3865.120 (Official Build) (64-bit) |

**Comment by keyman169** [comment]
I have the same problem.
Is there any thing can me on this issue?

**Comment by wenqi73** [comment]
Maybe we should also listen `NavigationCancel` router event.

**Comment by vthinkxie** [comment]
Hi @keyman169 
you can add nzSelectable="false" in current design, https://stackblitz.com/edit/github-5lxjne?file=src/app/common/pending-changes-guard.ts 
we will make it default with nzMatchRouter in next version
