### ISSUE TITLE
nz-carousel style height bug

### ISSUE THREAD

**Issue by devKid88** [NG-ZORRO/ng-zorro-antd#4414]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-vjz4bp](https://stackblitz.com/edit/ng-zorro-antd-start-vjz4bp)

### Steps to reproduce
If it is not happening initial try to reload several times.

### What is expected?
Expected to have the exact height of the carousel all the time.

### What is actually happening?
The height of the carrousel is changing dynamically after loading/reloading the app. Breaks height added in CSS.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.0 |
| Browser | Chrome  78.0.3904.97  |

---
This is not happening all the time, but quite often. When the bug occurs I think the height of the carousel is set to height of the current window. 
To reproduce try to reload several times a basic example and you will get that issue.

Few images of the reproduced issue
![image](https://user-images.githubusercontent.com/20492089/68544642-91eeac00-03c5-11ea-9ef3-915d577aa810.png)
![image](https://user-images.githubusercontent.com/20492089/68544709-720bb800-03c6-11ea-9699-6e0d23dcdf93.png)

**Comment by wendzhue** [comment]
It looks like that you want to control the height of the carousel component? Have you tried to set style of <nz-carousel> it self like this:

```html
<nz-carousel nzAutoPlay style="height: 160px;">
```

**Comment by devKid88** [comment]
Thanks for the quick response,

I just want to have the same height every time 😄 not that height of 2500px for example ( in my real-time case 😄  ). The above example is just a basic code semple from ng zorro website. 
I am not a fan of inline styles, but I will try your suggestion.

Not sure will you agree, but still, I believe this is a bug, because if we set height in CSS class or like in the example from ng zorro website, it works 6,7 times of 10, so I believe something is overriding our height with that dynamic height.

**Comment by wendzhue** [comment]
You don't have to use inline style. It's just a demo. You can use any CSS selector you want. The key is to set the height of the outter element `<nz-carousel>`, not the inner carousel contents.

**Comment by devKid88** [comment]
Oh, ok, tnx, I will do that, and test it for a while, if it works i will close this issue.
