### ISSUE TITLE
Make table updating when array push or splice

### ISSUE THREAD

**Issue by shengzheng1981** [NG-ZORRO/ng-zorro-antd#4416]
## What problem does this feature solve?
According to Angular documentation, developers should not use push or splice to change the data passed to nzData.
But it will be confused, when array's address can not be rewrited. So the default behavior can handle most situations,but not all.

## What does the proposed API look like?
I do some work for nz-table's source code, and i write some similar codes for implement this purpose, check the following code:
```component
export class TestTableComponent implements OnInit, OnChanges, DoCheck {

  @Input() nzData: any = [];    //

  data: any = [];

  constructor() { }

  ngOnInit() {
  }

  ngOnChanges(changes){
      if (changes.nzData) {
          this.update();
          console.log("changed");
      }
  }

  ngDoCheck() {
      if(this.data.length !== this.nzData.length) {
          this.update();
      }
  }

  update() {
      this.data = [...this.nzData];
  }
}
```
Now you can bind the array, and push item to array, the nz-table whill update, and every thing works fine!
Just a idea for situations when array' address can not be redefined, and also this code just for reference, you guys know what i mean and will make it better!

**Comment by wendzhue** [comment]
Check OnPush on this page: https://angular.io/api/core/ChangeDetectionStrategy.

**Comment by shengzheng1981** [comment]
i see. have nothing to say in reply!

**Comment by shengzheng1981** [comment]
this is nothing to do with OnPush mode. cause you split data(bind for table component) away from nzData(input) for pagination. check source code:
```
updateFrontPaginationDataIfNeeded(isPageSizeOrDataChange: boolean = false): void {
    let data = this.nzData || [];
    if (this.nzFrontPagination) {
      this.nzTotal = data.length;
      if (isPageSizeOrDataChange) {
        const maxPageIndex = Math.ceil(data.length / this.nzPageSize) || 1;
        const pageIndex = this.nzPageIndex > maxPageIndex ? maxPageIndex : this.nzPageIndex;
        if (pageIndex !== this.nzPageIndex) {
          this.nzPageIndex = pageIndex;
          Promise.resolve().then(() => this.nzPageIndexChange.emit(pageIndex));
        }
      }
      data = data.slice((this.nzPageIndex - 1) * this.nzPageSize, this.nzPageIndex * this.nzPageSize);
    }
    this.data = [...data];
    this.nzCurrentPageDataChange.emit(this.data);
  }
```
if you bind nzData directly, you remove onpush mode, it works fine!
but now even if  remove onpush mode, also no effect for push and splice, you can try!

**Comment by vthinkxie** [comment]
> this is nothing to do with OnPush mode. cause you split data(bind for table component) away from nzData(input) for pagination. check source code:
> 
> ```
> updateFrontPaginationDataIfNeeded(isPageSizeOrDataChange: boolean = false): void {
>     let data = this.nzData || [];
>     if (this.nzFrontPagination) {
>       this.nzTotal = data.length;
>       if (isPageSizeOrDataChange) {
>         const maxPageIndex = Math.ceil(data.length / this.nzPageSize) || 1;
>         const pageIndex = this.nzPageIndex > maxPageIndex ? maxPageIndex : this.nzPageIndex;
>         if (pageIndex !== this.nzPageIndex) {
>           this.nzPageIndex = pageIndex;
>           Promise.resolve().then(() => this.nzPageIndexChange.emit(pageIndex));
>         }
>       }
>       data = data.slice((this.nzPageIndex - 1) * this.nzPageSize, this.nzPageIndex * this.nzPageSize);
>     }
>     this.data = [...data];
>     this.nzCurrentPageDataChange.emit(this.data);
>   }
> ```
> 
> if you bind nzData directly, you remove onpush mode, it works fine!
> but now even if remove onpush mode, also no effect for push and splice, you can try!

the component won't and shouldn't modify[mutate] user data, the computation inside the table component is not the reference to your input data.

**Comment by shengzheng1981** [comment]
ok. just for display. no offense! this will never change user data by inside the component! and just update display.

**Comment by shengzheng1981** [comment]
no one changes user data. it takes time.
