### ISSUE TITLE
Select使用[nzDropdownStyle]设置max-height、min-height、height，样式会出现问题。使用[nzDropdownClassName]设置max-height、min-height、height无效

### ISSUE THREAD

**Issue by W1821** [NG-ZORRO/ng-zorro-antd#4421]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-vongpj?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-vongpj?file=src/app/app.component.html)

### Steps to reproduce
依次点击下拉选就可以看到

### What is expected?
通过设置，样式正确有效

### What is actually happening?
通过设置，样式不正确无效

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.0 |
| Browser | Google Chrome 78.0.3904.97 |

**Comment by vthinkxie** [comment]
nzDropdownStyle 和 ngStyle 的作用是一样的，只会应用到弹出层的div上，与直接写css是没有区别的，如果没有按照你的想法生效，可以打开chrome调试工具查看css的样式
