### ISSUE TITLE
sample code error

### ISSUE THREAD

**Issue by KiKiKi1258** [NG-ZORRO/ng-zorro-antd#4428]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
https://ng.ant.design/components/switch/zh

 <nz-switch [(ngModel)]="switchValue"></nz-switch>

The correct way of data binding is only [ngModel].However this page is [(ngModel)] and only this one is wrong.
this error is in the first sample code

### What is expected?
(- v -)

### What is actually happening?
(- v -)

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.0 |
| Browser | google |

**Comment by wendzhue** [comment]
If I didn't get you wrong, it's two-way binding syntax. Check [this](https://angular.io/api/forms/NgModel).
