### ISSUE TITLE
ng.ant.design/issue-helper 全局配置nzMaxStack在aot模式下无效

### ISSUE THREAD

**Issue by msyesyan** [NG-ZORRO/ng-zorro-antd#4429]
ng-zorror-antd: 8.1.1
angular: 8.2.8

按照文档中描述的那样，在app.module中通过如下方式注入NZ_CONFIG
```
const ngZorroConfig = {
  message: {
    nzMaxStack: 1,
  },
};

{ provide: NZ_CONFIG, useValue: ngZorroConfig },

```
发现在生产环境的aot编译模式下无法生效。我也尝试了在app.component.ts的constructor中，通过NzConfigService.set('message', { nzMaxStack: 1 })的方式，依然无法生效，并且在每次调用NzMessageService.create之前，console.log出了NzConfigService,发现这个值已经set进去了，所以请帮忙查看一下该怎么解决

**Comment by vthinkxie** [comment]
请升级到最新版本

**Comment by 2693252993** [comment]
我现在用 8.5.2 还是有这个现象
