### ISSUE TITLE
GlobalConfig nzMaxStack 在生产环境的aot编译模式下，无法生效

### ISSUE THREAD

**Issue by msyesyan** [NG-ZORRO/ng-zorro-antd#4430]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-pnjhdq](https://stackblitz.com/edit/ng-zorro-antd-start-pnjhdq)

### Steps to reproduce
这个代码需要通过 ng serve --production 的参数去启动，然后快速点击按钮

### What is expected?
期望页面上只能弹出一条消息

### What is actually happening?
在 --production模式下，可以显示达到7条消息

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.1 |
| Browser | Chrome |

---
但是如果同样的代码，使用 NZ_MESSAGE_CONFIG来设置，就是可以用的。但是这个NZ_MESSAGE_CONFIG貌似已经被deprecated了

**Comment by wendzhue** [comment]
最新版本应该已经修复这个问题，请升级到 8.4.x 试试。

**Comment by msyesyan** [comment]
是的已修复，谢谢
