### ISSUE TITLE
DatePicker 修改文本框日期需要响应更新输入的日期

### ISSUE THREAD

**Issue by xinhaoxx** [NG-ZORRO/ng-zorro-antd#4433]
## What problem does this feature solve?
 Ant Design 的 DatePicker (https://ant.design/components/time-picker-cn/) ，展开日期选择时，通过在 DatePicker 修改文本框中的日期文本使用鼠标点击其他区域关闭弹出层，可以更新当前日期值。
NG-ZORRO 的 DatePicker 展开日期选择时，在修改文本框中的日期文本后鼠标点击其他区域关闭弹出层不会更新日期的值。

## What does the proposed API look like?
希望可以加上在弹出日期选择时，修改文本框内容后点击其他区域关闭弹出层时可以更新为手动输入的日期值的功能

**Comment by wenqi73** [comment]
Hi @xinhaoxx ，目前可以用 `Enter` 键来更新。（#4130）

**Comment by xinhaoxx** [comment]
@wenqi73 好的，感谢！

**Comment by wenqi73** [comment]
duplicate of #4130
