### ISSUE TITLE
nzTooltip ViewDestroyedError regression in 8.5.0

### ISSUE THREAD

**Issue by snebjorn** [NG-ZORRO/ng-zorro-antd#4435]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-q78kmv](https://stackblitz.com/edit/ng-zorro-antd-start-q78kmv)

### Steps to reproduce
- open the stackblitz provided
- open the console
- click the button
- observe that an error is throw in the console and it didn't route

### What is expected?
Same as above but with v8.4.1 and it works as expected
https://stackblitz.com/edit/ng-zorro-antd-start-zy6nrq

### What is actually happening?
When a router link element (or just something that routes) have a tooltip it'll throw the below error

> Error: Uncaught (in promise): Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges

#### Example
```html
<button
  nz-button
  nzType="primary"
  nz-tooltip
  nzTooltipTitle="TOOLTIP!"
  routerLink="extra"
>
  Click me
</button>
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.0 |
| Browser | Chrome Version 78.0.3904.87 (Official Build) (64-bit) |

**Comment by DouglasOGarrido** [comment]
Yes, i 'm having the same issue.

**Comment by wendzhue** [comment]
Will be closed in #4418.

**Comment by wendzhue** [comment]
Please help us to revalidate when 8.5.1 is released. Thank you!

**Comment by snebjorn** [comment]
@wendzhue I can confirm it works. Thanks for the quick fix!
