### ISSUE TITLE
按钮在加载状态仍然可以通过获取焦点后按回车键触发click事件

### ISSUE THREAD

**Issue by zomixi** [NG-ZORRO/ng-zorro-antd#4437]
### Reproduction link
[https://stackblitz.com/edit/angular-5riet8](https://stackblitz.com/edit/angular-5riet8)

### Steps to reproduce
Tab键选中按钮后回车即可

### What is expected?
回车后不会触发click事件

### What is actually happening?
回车后会触发click事件

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.0 |
| Browser | Google Chrome 版本 78.0.3904.97（正式版本） （64 位） |

---
这个Bug会导致用户使用键盘操作时多次回车会多次提交表单数据

**Comment by wendzhue** [comment]
nz-button 以指令的方式使用，**这意味着对于原生 HTML 元素的行为它并没有做干预**。

**Comment by zomixi** [comment]
> nz-button 以指令的方式使用，**这意味着对于原生 HTML 元素的行为它并没有做干预**。

![image](https://user-images.githubusercontent.com/33776415/69605832-2d397f80-105c-11ea-8d06-9b0a65f70896.png)
那是否考虑对NzModal的确认按钮做干预？

**Comment by zomixi** [comment]
> > nz-button 以指令的方式使用，**这意味着对于原生 HTML 元素的行为它并没有做干预**。
> 
> ![image](https://user-images.githubusercontent.com/33776415/69605832-2d397f80-105c-11ea-8d06-9b0a65f70896.png)
> 那是否考虑对NzModal的确认按钮做干预？

@wendellhu95

**Comment by vthinkxie** [comment]
@zomixi @wendellhu95 nz-button 是一个按照directive使用的原生button，我们没有方法阻止 click 事件的输出
