### ISSUE TITLE
nz-table 中 [nzBordered]="true" 时 .ant-table-placeholder 左右border未生效

### ISSUE THREAD

**Issue by conyxun** [NG-ZORRO/ng-zorro-antd#4439]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-9afwzd](https://stackblitz.com/edit/ng-zorro-antd-start-9afwzd)

### Steps to reproduce
[nzBordered]="true" ,
[nzData] = []

### What is expected?
 .ant-table-placeholder 拥有左右边框

### What is actually happening?
 .ant-table-placeholder 左右边框未生效

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.0 |
| Browser | google chrome |

---
查看源码发现原因是.ant-table-empty添加在了错误位置。

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/next 
该问题在最新版本已经被修复，如果仍然有问题可以提出新issue
