### ISSUE TITLE
TreeSelect设置多选的时候，点击2个节点之间可以选中上级节点

### ISSUE THREAD

**Issue by W1821** [NG-ZORRO/ng-zorro-antd#4442]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-76fmlo?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-76fmlo?file=src/app/app.component.ts)

### Steps to reproduce

打开下拉弹窗，鼠标移入2个节点中间，鼠标的标识会变成箭头，点击一下，会选中上级节点

### What is expected?
点击无效果

### What is actually happening?
点击选中上级节点

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.1 |
| Browser | Google Chrome 78.0.3904.97（64 位） |

**Comment by hsuanxyz** [comment]
fixed via #4869
