### ISSUE TITLE
Feature request: add custom template to Skeleton

### ISSUE THREAD

**Issue by tempura-shrimp** [NG-ZORRO/ng-zorro-antd#4444]
## What problem does this feature solve?

Feature request: add custom template / or using ng-content to Skeleton. Current Skeleton is great, but adding custom Skeleton can provide greater flexibility.

Meanwhile, custom template or content only need to be injected ant-skeleton-title class

## What does the proposed API look like?

```
<ng-content></ng-content>
```

**Comment by wenqi73** [comment]
`<ng-content>` is used when `nzLoading` is false. Skeleton itself is just a simple display component that is flexible, you can control it almost only use CSS, we will not add a custom template. At 9.0.0 we will add some inputs, you can track #4619.
