### ISSUE TITLE
nz-select 在 tags mode下 nzBlur触发的时机不正确

### ISSUE THREAD

**Issue by msyesyan** [NG-ZORRO/ng-zorro-antd#4452]
### Reproduction link
[https://ng-zorro-antd-start-jkfcwi.stackblitz.io](https://ng-zorro-antd-start-jkfcwi.stackblitz.io)

### Steps to reproduce
直接focus 到 <nz-select>组件上，你会发现handleBlur() 函数在focus的状态下被触发。这个问题在 8.2版本下貌似是没有的

### What is expected?
在blur的时候触发handleBlur

### What is actually happening?
在focus的时候触发了handleBlur

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.1 |
| Browser | Chrome |

**Comment by msyesyan** [comment]
@vthinkxie 请问可以知道啥原因么

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.

close #4458
