### ISSUE TITLE
nzUpload无法显示本地图片，且解决路径安全问题时会出错问题

### ISSUE THREAD

**Issue by CodeFronts** [NG-ZORRO/ng-zorro-antd#4456]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-f1sxx7](https://stackblitz.com/edit/ng-zorro-antd-start-f1sxx7)

### Steps to reproduce
我在上传前把选中的图片存到数组中，显示的时候需要显示本地图片地址

### What is expected?
能显示本地图片

### What is actually happening?
无法显示本地图片，只能显示远程服务上的图片

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.1 |
| Browser | chrome 版本 78.0.3904.97 |

**Comment by cipchk** [comment]
这一问题已经在 #4410 统一修复。
