### ISSUE TITLE
nz-table nz-thead set sorting programmatically

### ISSUE THREAD

**Issue by snebjorn** [NG-ZORRO/ng-zorro-antd#4460]
## What problem does this feature solve?
Making it easier to set sorting programmatically.

`<th>` supports programmatically setting sorting like so

```html
<th
            nzShowSort
            [(nzSort)]="mapOfSort.name"
            (nzSortChange)="sort('name', $event)"
>
```

There doesn't appear to be a way to do the same for `<thead>`.
It's way easier to work with the `thead.nzSortChange`, `td.nzSortKey` combo, so that's the reason for this request.
## What does the proposed API look like?
Support nzSort on `<thead>` taking advantage of the nzSortKey "style".

```html
<thead [nzSort]="mapOfSort" (nzSortChange)="sortChange($event)">
    <tr>
      <th nzShowSort nzSortKey="mykey">
```
I'm not sure what's best here. The thead.nzSort isn't directly related to the output of thead.nzSortChange so `[(nzSort)]` will cause problems.

So either the output of thead.nzSortChange need to change or thead.nzSort should be called something else like `nzSortMap`.

```html
<thead [nzSortMap]="mapOfSort" (nzSortChange)="sortChange($event)">
    <tr>
      <th nzShowSort nzSortKey="mykey">
```

**Comment by vthinkxie** [comment]
Hi @snebjorn  we have nzSortChange for thead
https://ng.ant.design/components/table/en#components-table-demo-head

**Comment by snebjorn** [comment]
@vthinkxie this feature request is about programmatically setting the sorting via `thead.nzSort` just as `th.nzSort`

```html
<thead (nzSort)="...">
```

**Comment by vthinkxie** [comment]
Hi @snebjorn 
in ng-zorro-antd 9.0.0
## server-side
we will provide `(nzQueryParams)` for the server-side pagination, sort, and filter.
## browser side
there is no need to transform the data manually, all pagination, sort and filter will be processed inside the component.

**Comment by snebjorn** [comment]
Looking forward to trying it out. I'll report back whether it solves it :)

**Comment by vthinkxie** [comment]
close via 9.0, feel free to open another issue if 9.0 not fixed your issue.
