### ISSUE TITLE
flex布局在nzAlign="center"时nzJustify="start"无效

### ISSUE THREAD

**Issue by selegiline** [NG-ZORRO/ng-zorro-antd#4463]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-l2xaw7](https://stackblitz.com/edit/ng-zorro-antd-start-l2xaw7)

### Steps to reproduce
打开链接即可见

### What is expected?
nzJustify="start"生效

### What is actually happening?
nzAlign="center"时nzJustify="start"无效。同时
nzAlign="center"时nzJustify="end"生效。或者
nzAlign="bottom"时nzJustify="start"生效。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.1 |
| Browser | chrome |

**Comment by wenqi73** [comment]
`nzAlign` 的取值是 `'top' | 'middle' | 'bottom' `。
