### ISSUE TITLE
It cannot close modal when I change a router

### ISSUE THREAD

**Issue by fuybooo** [NG-ZORRO/ng-zorro-antd#447]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

step 1: open https://ng.ant.design/#/components/pagination
step 2: open https://ng.ant.design/#/components/modal
step 3: click button '使用component'
step 4: click browser's back button
step 5: check the page, the modal is still visible

## Expected behavior

It likes bug #412

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by HsuanXyz** [comment]
Hi @fuybooo:
This is not a BUG, if you used  Modal's service, need to control it in the lifecycle hook. like this:

```typescript
import { Component } from '@angular/core';
import { NzModalService } from '../../../index.showcase';

@Component({
  selector: 'app-your-component',
  template: `
    <button nz-button [nzType]="'primary'" (click)="showModalForComponent()">
      <span>使用Component</span>
    </button>
  `
})
export class YourComponent implements OnDestroy {
  _modal: any;

  constructor(private modalService: NzModalService) {
  }

  showModalForComponent() {
    this._modal = this.modalService.open({ ... });
  }

  ngOnDestroy() {
    this._modal.destroy('onCancel')
  }
}


```
```diff
  ngOnDestroy() {
+  this._modal.destroy('onCancel')
  }
```

**Comment by fuybooo** [comment]
Ok, thank you very much!
