### ISSUE TITLE
nz-table 在 循环 table.data时， 无法获得data的正确类型

### ISSUE THREAD

**Issue by doosee** [NG-ZORRO/ng-zorro-antd#4474]
### Reproduction link
[https://stackblitz.com/edit/angular-mzt3y3](https://stackblitz.com/edit/angular-mzt3y3)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/20335603/69530752-90b8a400-0fad-11ea-969e-4ea83bb1fe15.png)

### What is expected?
nz-talbe 在 循环 #table.data时，获得 data 的正确类型

### What is actually happening?
无法获得 data 的正确类型

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.1 |
| Browser | chrome 50 |

**Comment by hsuanxyz** [comment]
#4593
