### ISSUE TITLE
能否在DateRangePickerComponent  中提供 DateRangePopupComponent组件的引用

### ISSUE THREAD

**Issue by xnxnxnxn** [NG-ZORRO/ng-zorro-antd#4475]
## What problem does this feature solve?
能解决只选一个值得情况下，使用额外的页脚增加别的个性化功能。

## What does the proposed API look like?
在date-range-picker.component.ts 文件中增加 @ViewChild(DateRangePopupComponent) dateRangePopup: DateRangePopupComponent;

**Comment by wenqi73** [comment]
Hi @xnxnxnxn，没听懂你的需求，能给个 demo 说明下吗？

**Comment by xnxnxnxn** [comment]
就是现在有个需求，是需要在时间范围选择框内（nz-range-picker 组件），我先选一个开始日期，然后点我自定义的页脚上的长期(按钮)，我希望可以在我点下去的时候获取到这个开始日期。现在的版本是，只选一个开始日期去触发事件ngModel的值是空的，只有选了开始日期和结束日期才会有值。

**Comment by wenqi73** [comment]
Related to #4330.
