### ISSUE TITLE
Tabs with router, possibility to set a default tab

### ISSUE THREAD

**Issue by DRYmag** [NG-ZORRO/ng-zorro-antd#4484]
## What problem does this feature solve?
Use case : https://stackblitz.com/edit/ng-zorro-antd-start-kmia5h?file=src%2Fapp%2Fapp.component.ts 

I have a page which list quotations. Quotations are filtered visually with tabs (draft/accepted/sended). 
Tabs are linked with the router because I need to to go to this page on a specific tab. 

But from the main navigation I don't want specify a tab, I want to show the default tab (the first one). Status of quotations (draft/accepted/sended) are dynamic so I can't create a link to a specific tab from the main navigation.
## What does the proposed API look like?
May be change the default behavior : If no tab corresponds to the route, the first one is shown. Or the possibility to set a default tab based on a tab index ?

**Comment by mini-peanut** [comment]
same question

**Comment by hsuanxyz** [comment]
components don't silently modify your routing, You can manually navigate in `ngOnInit`, or set the default route redirection in your `router.module`
