### ISSUE TITLE
Badge disappears in dropdown menu

### ISSUE THREAD

**Issue by ragnar-pals** [NG-ZORRO/ng-zorro-antd#4489]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-rnjeen](https://stackblitz.com/edit/ng-zorro-antd-start-rnjeen)

### Steps to reproduce
Create an avatar with badge and dropdown menu in the html file.
Have the avatar dropdown menu trigger on click.
Then create an item in the dropdown menu with icon that has a dotted badge. 
Add attribute to the badge element on both the avatar and the icon, nzDot

Now click the avatar and you will see the icon both above the avatar and the icon. 
Click somewhere to make the dropdown menu disappear.
Click the avatar again and the badge on the icon is gone.

### What is expected?
After clicking the avatar again and let the dropdown menu appear again it should show the badge.

### What is actually happening?
After clicking the avatar again and let the dropdown menu appear again the badge disappears.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Google Chrome 78.0.3904.108 |

---
I wanted to make the user available to see if he has some kind of notification close to his avatar and when he clicks the avatar he will see where the notification is coming from.

**Comment by vthinkxie** [comment]
related to https://github.com/angular/angular/issues/24041
