### ISSUE TITLE
表格分页page小于或等于0时，nzPageIndexChange会触发两次

### ISSUE THREAD

**Issue by zjcboy** [NG-ZORRO/ng-zorro-antd#45]
## I'm submitting a...
<pre><code>
[ x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
使用表格分页远程加载数据

## Expected behavior
根据服务端分页要求传递页码

## Minimal reproduction of the problem with instructions
当使用远程加载数据时，_current小于或等于0时，nzPageIndexChange事件会触发两次
![wx20170816-224242](https://user-images.githubusercontent.com/8294751/29369122-478f53fe-82d4-11e7-9f84-2d1b912b33d9.png)

## What is the motivation / use case for changing the behavior?
后台分页规则不一，有的是从0开始的，虽然已经解决了该问题，但还是提一下！
补充下问题，页码从0开始时切换pageIndex或者pageSize都会触发两次请求数据的事件！

**Comment by vthinkxie** [comment]
components do not help developers to check their inputs format yet, to be discuss later.
