### ISSUE TITLE
Select、Tree、TreeSelect、TreeTable、Table、Cascader等组件是否可以在节点渲染前添加一个钩子函数，用于处理节点数据

### ISSUE THREAD

**Issue by 52805893** [NG-ZORRO/ng-zorro-antd#4503]
## What problem does this feature solve?
例如从第三方获取的数据属性和节点属性不一致，可以利用钩子函数重新构造节点对象。
目前从第三方获取的数据除了循环构造数据没有找到其他好的解决方法

## What does the proposed API look like?
<nz-cascader
      [(ngModel)]="selectedValue"
      [nzNodeRenderingBefore]="nzNodeRenderingBefore">
</nz-cascader>

nzNodeRenderingBefore(node: {},index?: number){
	//节点对象处理逻辑
	return node;
}

**Comment by vthinkxie** [comment]
直接rxjs service里面处理就可以了，组件只负责输入输出数据，不负责处理数据
