### ISSUE TITLE
Style problem with menu group in dropdown

### ISSUE THREAD

**Issue by DRYmag** [NG-ZORRO/ng-zorro-antd#4505]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-yvnnay?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-yvnnay?file=src/app/app.component.ts)

### Steps to reproduce
Hover the "Show" button to open the drop-down menu.

### What is expected?
Displays a drop-down with a menu group and its menu items.

### What is actually happening?
The style is broken, the items of the menu group are visually prefixed by the `li` point. The menu is normally well formatted and works outside a drop-down menu.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome Version 78.0.3904.108 (Build officiel) (64 bits) |

**Comment by wenqi73** [comment]
Maybe #3687 is the reason?
