### ISSUE TITLE
nz-cascader 在loadData中不能获取this对象，无法从service获取数据

### ISSUE THREAD

**Issue by chengaobin** [NG-ZORRO/ng-zorro-antd#4506]
### Reproduction link
[https://stackblitz.com/edit/angular-songlong?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-songlong?file=src/app/app.component.ts)

### Steps to reproduce
在components中定义对象，在loaddata中无法获取，点击下拉无法展示级联菜单

### What is expected?
点击下拉展示级联菜单

### What is actually happening?
点击下拉无法展示级联菜单

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome |

**Comment by wendzhue** [comment]
你的复现没有体现出什么地方有问题。

不过我猜你应该是没有使用箭头函数。

**Comment by chengaobin** [comment]
> 你的复现没有体现出什么地方有问题。
> 
> 不过我猜你应该是没有使用箭头函数。
我的代码链接里面给了测试代码，使用的就是箭头函数
，麻烦看下

**Comment by chengaobin** [comment]
> 你的复现没有体现出什么地方有问题。
> 
> 不过我猜你应该是没有使用箭头函数。

![image](https://user-images.githubusercontent.com/14012804/70108550-90db3280-1684-11ea-8480-ffd8ce49786e.png)
这是代码片段

**Comment by chengaobin** [comment]
![image](https://user-images.githubusercontent.com/14012804/70108690-da2b8200-1684-11ea-8bc6-5d2aae63322c.png)

**Comment by chengaobin** [comment]
![1575428205(1)](https://user-images.githubusercontent.com/14012804/70108720-eb748e80-1684-11ea-9a37-5a5871e3d425.jpg)

**Comment by chengaobin** [comment]
如此获取testprovince会报this是undefined

**Comment by chengaobin** [comment]
感谢解答，已解决 @wendzhue

**Comment by sameenzm** [comment]
> 感谢解答，已解决 @wendzhue

请问怎么解决的？

**Comment by sameenzm** [comment]
噢噢，知道了，解决方式：
[nzLoadData]="loadData.bind(this)"
