### ISSUE TITLE
Layout documentation incorrect

### ISSUE THREAD

**Issue by darshanrampatel** [NG-ZORRO/ng-zorro-antd#4510]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-tq8s1a?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-tq8s1a?file=src/app/app.component.ts)

### Steps to reproduce
The breakpoint widths on the documentation page are incorrect:

```js
{
  xs: '480px',
  sm: '768px',
  md: '992px',
  lg: '1200px',
  xl: '1600px',
  xxl: '1600px'
}
```

https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/layout/doc/index.en-US.md

### What is expected?
Should match the values in https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/core/responsive/nz-breakpoint.ts

```js
export const responsiveMap: BreakpointMap = {
  xs: '(max-width: 575px)',
  sm: '(min-width: 576px)',
  md: '(min-width: 768px)',
  lg: '(min-width: 992px)',
  xl: '(min-width: 1200px)',
  xxl: '(min-width: 1600px)'
};
```

### What is actually happening?
Incorrect values shown

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by wendzhue** [comment]
PR is welcome!
