### ISSUE TITLE
tree组件，在设置默认初始选中后，添加新的节点并把nzSelectedKeys属性设置为新的节点的值，会显示两个节点被选中

### ISSUE THREAD

**Issue by JoyZhou007** [NG-ZORRO/ng-zorro-antd#4513]
### Reproduction link
[https://stackblitz.com/edit/angular-rnfute-kr5zkw](https://stackblitz.com/edit/angular-rnfute-kr5zkw)

### Steps to reproduce
点击add按钮

### What is expected?
添加的新的节点被选中，其他节点不被选中

### What is actually happening?
同时选中了两个节点

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Version 78.0.3904.108 (Official Build) (64-bit) |

**Comment by xusysh** [comment]
因为你每次给新节点添加的key都一样，所以导致选中的节点出问题，每个节点的key都是独一无二的才可以被正常选中，例如https://stackblitz.com/edit/angular-rnfute-u5rxqb?file=src/app/app.component.ts

**Comment by JoyZhou007** [comment]
> 因为你每次给新节点添加的key都一样，所以导致选中的节点出问题，每个节点的key都是独一无二的才可以被正常选中，例如https://stackblitz.com/edit/angular-rnfute-u5rxqb?file=src/app/app.component.ts

我的demo第一次添加是新的key,关键在于你加了setTimeOut把值放到下一轮变更检测里了才起作用，我把你更改key值移出TimeOut后还是会有问题的，https://stackblitz.com/edit/angular-rnfute-gpucah

**Comment by wenqi73** [comment]
好像和 #4566 是一个问题？@hsuanxyz @simplejason
