### ISSUE TITLE
Input使用 Search模式时，button切换loading状态时导致样式异常。

### ISSUE THREAD

**Issue by zjxcv7** [NG-ZORRO/ng-zorro-antd#4515]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-9bfn2v](https://stackblitz.com/edit/ng-zorro-antd-start-9bfn2v)

### Steps to reproduce
点击按钮，切换loading状态时；按钮loading过渡时异常。

### What is expected?
过渡时按钮的宽度不会改变

### What is actually happening?
按钮的宽度在切换loading状态时异常

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | 所有 |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-c2wnuy?file=src/app/app.component.css
可以通过css修改transition动画

**Comment by vthinkxie** [comment]
本质原因是 loading 的 icon 是通过另外一个 ngIf 来控制显示而不是直接修改原 icon 的 type，目前 angular 版本支持通过 projection 的方式传入 icon，导致替换 icon type比较困难

**Comment by vthinkxie** [comment]
最新版本该问题已经解决
