### ISSUE TITLE
Cannot find module '@angular-devkit/schematics/tasks' while creating 

### ISSUE THREAD

**Issue by gs-mrpatil** [NG-ZORRO/ng-zorro-antd#4520]
### Steps to reproduce
ng new projectName
cd projectName
ng add ng-zorro-antd

### What is expected?
i am unable to create ant design angular project. should be able to create the project.

### What is actually happening?
unable to add ng-zorro-antd. getting "schematics/tasks" error.
```

An unhandled exception occurred: Cannot find module '@angular-devkit/schematics/tasks'
See "/private/var/folders/fq/jmzr010j1rb6r3nz1_y19j9c0000gp/T/ng-bP8zSE/angular-errors.log" for further details.

```
I have installed angular/cli@latest

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome Version 78.0.3904.108 |

---

**Comment by gs-mrpatil** [comment]
for now i did a workaround
`npm i ng-zorro-antd --save `to setup antd

**Comment by wenqi73** [comment]
@gs-mrpatil Can you provide information of `ng version` ?

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
