### ISSUE TITLE
tree组件在使用nzExpandAll的时候会出现问题

### ISSUE THREAD

**Issue by xnxnxnxn** [NG-ZORRO/ng-zorro-antd#4528]
### Reproduction link
[https://ng-zorro-antd-start-t4usja.stackblitz.io](https://ng-zorro-antd-start-t4usja.stackblitz.io)

### Steps to reproduce
1.检索0-2
2.再点击向下的箭头图标，导致节点消失

### What is expected?
节点依然存在

### What is actually happening?
节点消失

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Google Chrome 78.0.3904.87 |

**Comment by wenqi73** [comment]
@xnxnxnxn 没有复现该问题，能提供下带代码的链接吗？

**Comment by xnxnxnxn** [comment]
> @xnxnxnxn 没有复现该问题，能提供下带代码的链接吗？

https://ng-zorro-antd-start-t4usja.stackblitz.io
