### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by mjn1154477982** [NG-ZORRO/ng-zorro-antd#453]
I am using lazy loading error；
this is my app.module.ts:
![appmoduleroute](https://user-images.githubusercontent.com/20697182/31750271-870ba474-b4b1-11e7-962f-129209568cd3.png)
lazy loading module:
![indexmodule](https://user-images.githubusercontent.com/20697182/31750330-e8eae434-b4b1-11e7-9154-32e0cd07cf88.png)
lazy loading html:
![indexhtml](https://user-images.githubusercontent.com/20697182/31750337-f9a2959c-b4b1-11e7-9329-bd8f70ae2b0e.png)
error:
![span](https://user-images.githubusercontent.com/20697182/31750346-06ba8960-b4b2-11e7-9de5-ef2df49a7c4b.png)
Whether each lazy loaded module needs to introduce the NgZorroAntdModule once. I see you in the source code also used lazy to load, I seemingly did not find you in the lazy load module introduced NgZorroAntdModule?？

**Comment by vthinkxie** [comment]
just import NgZorroAntdModule in your lazy load module please.
