### ISSUE TITLE
nz-range-picker readonly won't prevent opening keyboard 

### ISSUE THREAD

**Issue by returnvoid** [NG-ZORRO/ng-zorro-antd#4534]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-zgz8vh](https://stackblitz.com/edit/ng-zorro-antd-start-zgz8vh)

### Steps to reproduce
On mobile when click on input fields it will open the keyboard

### What is expected?
On mobile keyboard shouldn't open

### What is actually happening?
Keyboard is open

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.1 |
| Browser | all |

**Comment by wenqi73** [comment]
Datepicker component does not support `readonly` currently.

**Comment by returnvoid** [comment]
Will this feature be any time in the future? Also if no plan to add this, is there a workaround you recommend to avoid this behaviour?
thanks

**Comment by jobinjoymec** [comment]
Timepicker component also not support readonly currently

**Comment by wenqi73** [comment]
Need a `[nzInputReadOnly]` input and PR welcome.
