### ISSUE TITLE
Date-Picker allow template for calendar icon

### ISSUE THREAD

**Issue by haakon-io** [NG-ZORRO/ng-zorro-antd#4535]
## What problem does this feature solve?
We have a specific set of icons that we use on our site. We want to be able to user our calendar icon instead of the default icon that is specified in the fesm5/ng-zorro-antd-date-picker.js - <span class=\"{{ prefixCls }}-picker-icon\">\n    <i nz-icon nzType=\"calendar\"></i>\n  </span>

It would be ideal if the calendar icon would accept a template like some of the other controls do. If it doesn't find a template then just use the default calendar icon.
## What does the proposed API look like?
<nz-date-picker [(ngModel)]="date" (ngModelChange)="onChange($event)" [nzSuffixIcon]="customIconTemplate"></nz-date-picker>
<ng-template #customIconTemplate>
  <i class="far fa-calendar-alt"></i>
</ng-template>

**Comment by wenqi73** [comment]
The `suffixIcon` property in AntD.

**Comment by wenqi73** [comment]
Close via #5072
