### ISSUE TITLE
cascader级联选择器，用loadData获取数据，新增了远程数据之后，无法实时更新

### ISSUE THREAD

**Issue by chengaobin** [NG-ZORRO/ng-zorro-antd#4536]
## What problem does this feature solve?
cascader级联选择器，用loadData获取数据，新增了远程数据之后，无法实时更新

## What does the proposed API look like?
能实时刷新下拉框数据

**Comment by wendellhu95** [comment]
请先确保你给 nzLoadData 传递的是一个箭头函数。

**Comment by chengaobin** [comment]
传递的是一个箭头函数， loadData = (node: NzCascaderOption, index: number) => {}

**Comment by wendellhu95** [comment]
提供一个复现，不然无法排查问题。

**Comment by chengaobin** [comment]
https://ng-zorro-antd-start.stackblitz.io这个是用本地模拟的，实际中是操作接口数据@wendelhu95

**Comment by wendellhu95** [comment]
你好像分享之前没有点击 fork

**Comment by chengaobin** [comment]
https://ng-zorro-antd-start-gnid91.stackblitz.io

**Comment by chengaobin** [comment]
@wendelhu95

**Comment by chengaobin** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-gnid91

**Comment by chengaobin** [comment]
这个已经fork了

**Comment by wendellhu95** [comment]
你想要修改的是 NzCascaderComponent 的 options 属性，但是你实际上修改的是 `scenicspots`。

**Comment by chengaobin** [comment]
我是通过laodData取的数据，跟nzoption没关系啊

**Comment by qiurenbo** [comment]
> 请先确保你给 nzLoadData 传递的是一个箭头函数。

这边改成箭头函数成功解决···这是什么原因呢···

**Comment by wendellhu95** [comment]
> > 请先确保你给 nzLoadData 传递的是一个箭头函数。
> 
> 这边改成箭头函数成功解决···这是什么原因呢···

简单的 this 绑定问题

**Comment by NxqF** [comment]
使用了loadData后，只有第一次点击节点的时候会获取数据
