### ISSUE TITLE
关于Menu 导航菜单的使用BUG

### ISSUE THREAD

**Issue by eevin** [NG-ZORRO/ng-zorro-antd#454]
1、使用收缩展开时候，操作过快，选中样式未消失。
2、菜单收起状态，点击菜单会造成子菜单出现，立刻消失。一般用户不一定知道是hover，都会点一下，体验不好。
3、菜单定位：选择子菜单，刷新页面，子菜单父级未展开。

**Comment by vthinkxie** [comment]
1. not a bug
2. need enhancement
3. just set nzOpen according to  ActivatedRoute state.
