### ISSUE TITLE
nz-select默认模式下，开启搜索功能，不能在已选文本基础上编辑搜索内容

### ISSUE THREAD

**Issue by flash12328** [NG-ZORRO/ng-zorro-antd#4544]
## What problem does this feature solve?
nz-select默认模式下，开启搜索功能，选中的文本会在下拉框打开之后置灰文本，并且输入文本时不是在之前所选的文本上编辑输入，而是重新输入，可能你们的交互稿是要求这么做的；
我个人认为可以做成开关，因为好多这种前端搜索过滤的下拉框都是在已选中的文本只是做编辑，然后再搜索的；我尝试在不修改你们源码的基础上去改成在已选文本上编辑的效果，我可能技术不到家，改不了。希望你们能给出可自定义的方案，非常感谢

## What does the proposed API look like?
希望可以给个开关以灵活切换搜索效果

**Comment by wenqi73** [comment]
This behavior is by design. https://github.com/ant-design/ant-design/issues/18683
