### ISSUE TITLE
datepicker with time show error,and modal return data question

### ISSUE THREAD

**Issue by winds2016** [NG-ZORRO/ng-zorro-antd#455]
## I'm submitting a...

<pre><code>
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

datepicker:
when show time such as "2017-10-10 13:30:56" ,the second part('56')  cover with icon

modal:
subscribe event can return unneed data,such as:onOk onhidden,onDestroy

## Expected behavior

datepicker:
show time all away from icon
modal:
subscribe event return custom data only

## Environment

<pre><code>
Angular version: 4.0.1

ng-zorro-antd version: 0.5.4

Browser:
- [ ] Chrome (desktop) version XX
- [*] Firefox version 56
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: 7.7  
- Platform:  win7

**Comment by vthinkxie** [comment]
datepicker: just add style width with it
modal: you can wrap your custom data in your data structure.

**Comment by winds2016** [comment]
thanks
modal: need to judge if is my data structure, will waste performance
