### ISSUE TITLE
List数据分页，限定每页能够显示指定多少条数据

### ISSUE THREAD

**Issue by Junior0909** [NG-ZORRO/ng-zorro-antd#4557]
## What problem does this feature solve?
List列表能够进行分页处理，解决列表太长问题。

## What does the proposed API look like?
期望有像Table的nzPageSize等API

**Comment by cipchk** [comment]
请参考 [竖排列表样式](https://ng.ant.design/components/list/zh#components-list-demo-vertical) 示例。

**Comment by Junior0909** [comment]
当我从后端获取到json数据，怎么放到data去呢？示例的data是new Array。

**Comment by cipchk** [comment]
@Junior0909 其中 `nzDataSource` 为数据源，并配合 `nzRenderItem` 完成自定义渲染。

**Comment by Junior0909** [comment]
这个能看懂，只是不知道DataSource是怎么跟分页联系起来的。我看demo是新建固定长度的数组进行数据填充，当我从后端拿到返回的数据，该如何处理，希望能提供个http请求数据的示例。万分感谢！
