### ISSUE TITLE
2nd button in nz-button group not aligned when size is set to default or not set at all

### ISSUE THREAD

**Issue by whittssg** [NG-ZORRO/ng-zorro-antd#4558]
### Reproduction link
[https://stackblitz.com/edit/nz-z-button-group?file=src/app/app.component.ts](https://stackblitz.com/edit/nz-z-button-group?file=src/app/app.component.ts)

### Steps to reproduce
add two buttons into a nz-button-group and set size to default or dont set a size, the second button isnt aligned. Setting size to small or large works as expected.

### What is expected?
both buttons to align

### What is actually happening?
buttons are not aligning.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Latest Chrome 64bit |

**Comment by wenqi73** [comment]
Fixed in AntD https://github.com/ant-design/ant-design/issues/19392
