### ISSUE TITLE
[Doc] copy icon CSS rules

### ISSUE THREAD

**Issue by AlcheXie** [NG-ZORRO/ng-zorro-antd#456]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

Copy text of HTML tag by clicking icon.

## Expected behavior

I can copy CSS rule content if I need to write pseudo-class with content of icon.

**Comment by AlcheXie** [comment]
Another, setTimeout in nz-icon-copy.directive works but doesn't work on view.

**Comment by vthinkxie** [comment]
This part of doc would not change for the most recent period, thanks for your suggestion.
