### ISSUE TITLE
resizable模块在以Ivy 模式运行时没有为预览div添加动态属性

### ISSUE THREAD

**Issue by Etran-H** [NG-ZORRO/ng-zorro-antd#4571]
### Reproduction link
[https://stackblitz.com/edit/angular-8vvhe8](https://stackblitz.com/edit/angular-8vvhe8)

### Steps to reproduce
angular 版本9 

开启Ivy
```
  "angularCompilerOptions": {
    "enableIvy": true
  }
```

### What is expected?
有 _ngcontent-#
```
<div _ngcontent-pet-c10="" class="nz-resizable-preview" style="width: 176px; height: 54px;"></div>
```

### What is actually happening?
没有动态属性
```
<div class="nz-resizable-preview" style="width: 193px; height: 54px;"></div>
```
样式没有应用

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0-beta.0 |
| Browser | Chrome 79 |

**Comment by hsuanxyz** [comment]
@Etran-H 你的复现链接无效，另外 `_ngcontent ` 这样的属性本来就是 ng 生成的不应该与你的样式发生任何关系。

**Comment by Etran-H** [comment]
抱歉我不太清楚如何在在线IDE设置编译选项。
是的这个属性应该由ng自动生成，但是没有生成。而ng也会为我的样式自动加上对应属性的限定。因为该标签没有生成相应的属性，所以我的样式无法应用。

**Comment by hsuanxyz** [comment]
@Etran-H 在文档最下面你可以看见组建组成的 class，你的样式应该是根据这些 class 设置，而不是 ng 自动生成的标签。

**Comment by Etran-H** [comment]
我并没有为我的样式加上ng 的标签。
这是我的样式：
```
.nz-resizable-preview {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 8;
  border: 1px dashed #d1d1d1;
  border-width: 0;
  border-right-width: 1px;
}
```
这是ng最终生成的样式：
```
.nz-resizable-preview[_ngcontent-??????] {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 8;
  border: 1px dashed #d1d1d1;
}
```
- 这在不使用ivy时可以正确应用。
- 我其他的样式也可以正确应用。
- 在使用ivy时不能被正确应用。
- ng 无论是否在ivy 模式下，都会**自动为我的样式**添加和**同一模块内**的html标签**相同**的`_ngcontent-#`随机属性。
- ng 在非Ivy 编译时，都会**自动为模块内的html标签**添加和**同一模块内的样式 相同**的`_ngcontent-#`随机属性。
- ng 在Ivy 编译时，都会**自动为模块内的html标签**(除了[class="nz-resizable-preview"] 所在的div)添加和**同一模块内的样式 相同**的`_ngcontent-#`随机属性。
- ng 在Ivy 编译时，**没有**为[class="nz-resizable-preview"] 所在的div 添加和**同一模块内的样式 相同**的`_ngcontent-#`随机属性。

因此

在没有开启Ivy 编译选项时，
ng 自动添加了属性选择器的样式`.nz-resizable-preview[_ngcontent-??????] { …… }`
可以被应用到
ng 自动添加了属性的标签`<div _ngcontent-??????="" class="nz-resizable-preview" …… />`
上。

在开启Ivy 编译选项时，
ng 自动添加了属性选择器的样式`.nz-resizable-preview[_ngcontent-??????] { …… }`
无法被应用到
ng 没有自动添加属性的标签`<div class="nz-resizable-preview" …… />`
上。

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
