### ISSUE TITLE
tree和tree-select是否可支持正则搜索？或是否可以简单提供忽略大小写搜索模式？

### ISSUE THREAD

**Issue by alfadb** [NG-ZORRO/ng-zorro-antd#4572]
## What problem does this feature solve?
在很多情况下，用户搜索时不会严格区分大小写，导致用户体验不佳。

## What does the proposed API look like?
`[nzSearchCaseInsensitive]="true"`

**Comment by hsuanxyz** [comment]
duplicate #4497
