### ISSUE TITLE
table能支持列宽度拖动和列拖拽排序吗

### ISSUE THREAD

**Issue by doubleji** [NG-ZORRO/ng-zorro-antd#4574]
## What problem does this feature solve?
table能支持列宽度拖动和列拖拽排序吗，这样用户可以自己用table调整样式

## What does the proposed API look like?
table能支持列宽度拖动和列拖拽排序吗

**Comment by vthinkxie** [comment]
可以直接使用ngFor th 配合 cdk 的 dragdrop 实现
