### ISSUE TITLE
nz-dropdown-menu中放置nz-tag标签时, 第一次会显示, 后续显示空白

### ISSUE THREAD

**Issue by x-wk** [NG-ZORRO/ng-zorro-antd#4576]
### Reproduction link
[https://stackblitz.com/edit/angular-1tyhct](https://stackblitz.com/edit/angular-1tyhct)

### Steps to reproduce
点击两次

### What is expected?
显示标签

### What is actually happening?
空白

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome 79.0.3945.79 |

**Comment by vthinkxie** [comment]
it is a bug of angular, plz add `nzNoAnimation` to the dropdown
related https://github.com/angular/angular/issues/24041

**Comment by x-wk** [comment]
@vthinkxie thank you
