### ISSUE TITLE
tooltip and dropdown integration problem

### ISSUE THREAD

**Issue by hsuanxyz** [NG-ZORRO/ng-zorro-antd#4577]
### Reproduction link
[https://stackblitz.com/edit/angular-agev4j?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-agev4j?file=src/app/app.component.ts)

### Steps to reproduce
click link

### What is expected?
The tooltip does not close properly

### What is actually happening?
Open and close properly

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | * |

**Comment by wendellhu95** [comment]
issue 太多居然没看到这个……

**Comment by wendellhu95** [comment]
这个问题貌似没法解，在目前我们使用 backdrop 检测 click outside 的前提下，这个原理和同时打开两个 modal 或者 drawer 是一样的。
