### ISSUE TITLE
NzUploadListComponent previewFile bug

### ISSUE THREAD

**Issue by huiyuanai709** [NG-ZORRO/ng-zorro-antd#4578]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-2gmnya](https://stackblitz.com/edit/ng-zorro-antd-start-2gmnya)

### Steps to reproduce
NzUploadListComponent:
```
private previewFile(file: File | Blob, callback: (dataUrl: string) => void): void {
    if (file.type && this.imageTypes.indexOf(file.type) === -1 /* Always true */) {
      callback('');
      // Need return here
    }
    // only image go on
    // SVG need use sanitizer.bypassSecurityTrustResourceUrl
    const reader = new FileReader();
    // https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL
    reader.onloadend = () => callback(reader.result as string);
    reader.readAsDataURL(file);
}
```

### What is expected?
Use file extension to determine if it is an image
The file extension may be empty
The only image executes FileReader.
SVG file should bypassSecurityTrustResourceUrl

### What is actually happening?
FileReader executed with each file

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 79.0.3945.79 |

**Comment by cipchk** [comment]
We use `canvas` to get the preview image, I think these problems no longer exist.
