### ISSUE TITLE
progress进度条缓冲区颜色无法设置

### ISSUE THREAD

**Issue by 1174971877** [NG-ZORRO/ng-zorro-antd#4579]
## What problem does this feature solve?
自能设置进度条颜色，如果能设置缓冲区颜色会有更大的自由度

## What does the proposed API look like?
[nzBufferColor]=""

**Comment by wendellhu95** [comment]
可以使用 CSS 属性或者我们提供的 less 变量，来修改 .ant-progress-inner 的 background-color 属性。

我们不太会为能够被 CSS 层叠所解决的问题引入一个 API，因为这会提高使用成本，而且不利于用户借助已有的 web 技术。

如果你遇到了不能由 CSS 覆盖解决的 case，欢迎提交另外一个 issue。
