### ISSUE TITLE
Simply boolean attribute usage

### ISSUE THREAD

**Issue by trotyl** [NG-ZORRO/ng-zorro-antd#458]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

For using a positive boolean attribute (whose falsy value does nothing), use must use data-binding with the `boolean` value:

```html
<button nz-button [nzGhost]="true">Ghost</button>
```

## Expected behavior

User able to use attribute without value to indicate truthy value：

```html
<button nz-button nzGhost>Ghost</button>
```

Equals to:

```html
<button nz-button [nzGhost]="true">Ghost</button>
```

While

```html
<button nz-button>Ghost</button>
```

means:

```html
<button nz-button [nzGhost]="false">Ghost</button>
```

## Detailed design

When applying empty attribute, an empty string will be passed to the input or attribute.

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by LinBoLen** [comment]
how about use
<button nz-button nzGhost="true">Ghost</button>

**Comment by trotyl** [comment]
@LinBoLen That's meaningless, if you're not using dynamic binding, then empty attribute is enough.

**Comment by trotyl** [comment]
Some of the components already support this usage.

**Comment by trotyl** [comment]
Blocked by #460.
