### ISSUE TITLE
Icon: Unused module being included

### ISSUE THREAD

**Issue by dylanvdmerwe** [NG-ZORRO/ng-zorro-antd#4586]
### Steps to reproduce
In my app, I have gone through every module import. There is absolutely no reference to NgZorroAntdModule or NzIconModule. However, when using webpack-bundle-analyzer to investigate what is bundled, I see the icon module always included in the main module. 

### What is expected?
Only the modules absolutely required, or manually specified, should be pulled. 

### What is actually happening?
Icon module is being included when there is no reference to NzIconModule anywhere in the project. 

![image](https://user-images.githubusercontent.com/2852839/71320549-6aefc380-24b5-11ea-9996-927c096ae391.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by wendellhu95** [comment]
If you use other components of ng-zorro-antd that uses icon, then the icon module would be imported. So what components are you using?
