### ISSUE TITLE
Popover triggered by focus not effect in InputNumber 

### ISSUE THREAD

**Issue by zebulon988** [NG-ZORRO/ng-zorro-antd#4590]
### Reproduction link
[https://stackblitz.com/edit/nz-issue-popover-inputnumber](https://stackblitz.com/edit/nz-issue-popover-inputnumber)

### path one:
1. Number input components is placed in the end of each row.  Click anyone of them.

### path two:
1. Click nz-input compoent which is before number-input.
2. Click **Tab** so number-input has the focus.

### What is expected?
The number-input who has focus will open the popover.

### What is actually happening?
Popover is not open whe number-input has focus.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome 版本 79.0.3945.88（正式版本） （64 位） |

---
1. Change the value of **nzPopoverTrigger** in **nz-input-number** to **click** will ok.
2. **focus** of   **nzPopoverTrigger** in **nz-input** is ok.

**Comment by wenqi73** [comment]
`nz-input-number` does not support native `focus`.

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/popover/zh#%E6%B3%A8%E6%84%8F

**Comment by miteshkapasia** [comment]
Can anyone let me know, how this issue of focus has been resolved ? Currently I am using antd inputnumber and popover is not working on focus trigger.

**Comment by Webs95** [comment]
Did you manage to solve this problem?
