### ISSUE TITLE
how to hide a tab?

### ISSUE THREAD

**Issue by aokaywe** [NG-ZORRO/ng-zorro-antd#4592]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-heqqus?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-heqqus?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
set tab1 hidden attribute to true

### What is expected?
tab1 was hidden

### What is actually happening?
tab1 was not hidden

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome 79.0.3945.79 |

**Comment by aokaywe** [comment]
i don't want use ngIf

**Comment by vthinkxie** [comment]
any special reason you don't want to use ngIf?

**Comment by aokaywe** [comment]
ngIf will remove elements from dom, the element in tab1 is too big to reload

**Comment by aokaywe** [comment]
@vthinkxie [style.visibility] solved my problem, thks

**Comment by aokaywe** [comment]
@vthinkxie [style.visibility] has the same problem, any other idea? thank you~
https://stackblitz.com/edit/ng-zorro-antd-start-heqqus?file=src%2Fapp%2Fapp.component.html

**Comment by vthinkxie** [comment]
plz use css to modify the visibility

**Comment by aokaywe** [comment]
can u give me a example with stackblitz, i can't find a way to modify nz-tab-label css. @vthinkxie

**Comment by vthinkxie** [comment]
have you tried `nzForceRender`?

**Comment by aokaywe** [comment]
yes, i tried, only ngIf can hide tab in this demo:
https://stackblitz.com/edit/ng-zorro-antd-start-heqqus?file=src%2Fapp%2Fapp.component.html

**Comment by vthinkxie** [comment]
you can skip the content part of nz-tab and render yourself outside it, here is a demo https://stackblitz.com/edit/ng-zorro-antd-start-6xbxxs?file=src/app/app.component.html

**Comment by aokaywe** [comment]
@vthinkxie 
good idea, thank you~
