### ISSUE TITLE
Dropdowns or tags are animating when change page or sorting starting from second row

### ISSUE THREAD

**Issue by IonelLupu** [NG-ZORRO/ng-zorro-antd#4594]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-y5ggqo?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-y5ggqo?file=src/app/app.component.ts)

### Steps to reproduce
Use a Dropdown in NzTable with pagination like in the example above.

### What is expected?
I expect the Dropdowns (and also the Tags in the example above) not to animate. This happens starting from row two. The first row works as expected and has the correct behaviour.

### What is actually happening?
Dropdowns and Tags(other elements might be also affected) starting from row two are animating by changing the background color and size.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome, Firefox, Opera, Edge |

**Comment by IonelLupu** [comment]
I've played a bit more with this and it seems that the Dropdown is the problem. If I remove it the Tags are showing correctly.

This is a Dropdown issue, not a Tag issue, so we can change the label of this issue into 'Dropdown'

**Comment by wendellhu95** [comment]
Ref #4576. If you want this to be resolved faster, please +1 in this issue of Angular: https://github.com/angular/angular/issues/24041.

**Comment by wendellhu95** [comment]
@vthinkxie @hsuanxyz This bug is raising a lot of questions recently. Consider pinning it for some time.

**Comment by IonelLupu** [comment]
@wendellhu95 Are you sure this is related to #4576?  My problem is with the animation that starts from the second row not with the disappearance of the <nz-tag>.
