### ISSUE TITLE
下拉框里面的 nzTag ，会在下一次展开时消失。

### ISSUE THREAD

**Issue by doosee** [NG-ZORRO/ng-zorro-antd#4597]
### Reproduction link
[https://stackblitz.com/edit/angular-t6lzah](https://stackblitz.com/edit/angular-t6lzah)

### Steps to reproduce
下拉框里面的 nzTag ，会在下一次展开时消失。

### What is expected?
下拉框里面的 nzTag ，会在下一次展开时还在。

### What is actually happening?
下拉框里面的 nzTag ，会在下一次展开时消失。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Windows/Chrome 79.0.3945.88（正式版本） （64 位） |

---
看了一下 DOM 里面标签都还在，试着改了样式，没luan用， 我怀疑是浏览器给吞掉了。

**Comment by wendellhu95** [comment]
Duplicate of #4576.
