### ISSUE TITLE
pagination切换每页显示数量，当切换的每页显示的数据量过大，并且当前页码超出了范围时，会默认选择到最后一页

### ISSUE THREAD

**Issue by chengaobin** [NG-ZORRO/ng-zorro-antd#4599]
### Reproduction link
[https://angular-yejdsl.stackblitz.io](https://angular-yejdsl.stackblitz.io)

### Steps to reproduce
1.点击页码5，切换到第五页
2.点击每页切换数量，切换到每页300个数据
3.会看到页码显示到第四页，自己设置到显示第一页也不起作用

### What is expected?
1.点击页码5，切换到第五页
2.点击每页切换数量，切换到每页300个数据
3.会看到页码显示到第一页

### What is actually happening?
1.点击页码5，切换到第五页
2.点击每页切换数量，切换到每页300个数据
3.会看到页码显示到第四页，自己设置到显示第一页也不起作用

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
超出页码时切换到最后一页是预期行为
