### ISSUE TITLE
[RFC] Make all boolean attribute `false` by default

### ISSUE THREAD

**Issue by trotyl** [NG-ZORRO/ng-zorro-antd#460]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Content

It's much easier and instinctive to specify an attribute for applying it (rather than strip it). 

Consider:

```html
<!-- truthy -->
<nz-cascader></nz-cascader>
<!-- falsy -->
<nz-cascader [nzShowInput]="false" [nzShowArrow]="false"></nz-cascader>
```

Versus:

```html
<!-- truthy -->
<nz-cascader></nz-cascader>
<!-- falsy -->
<nz-cascader [nzNoInput]="true" [nzNoArrow]="true"></nz-cascader>
```

The latter can then be simplified to:

```html
<!-- truthy -->
<nz-cascader></nz-cascader>
<!-- falsy -->
<nz-cascader nzNoInput nzNoArrow></nz-cascader>
```

This way we could keep consistency with [HTML boolean attributes](https://html.spec.whatwg.org/#boolean-attributes), and the value part could always be omitted while remain effective.

It can make non-binding usage much simpler. For binding usage, just need to add or remove an `!` operator.

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Maroonl** [comment]
这种用法会混淆 Directive 和 Input，感觉用起来怪怪的。

**Comment by trotyl** [comment]
@ghost Haven't you add `disabled` on `<input>`?

**Comment by vthinkxie** [comment]
@trotyl what if user want to dynamic change the attribute

**Comment by trotyl** [comment]
@vthinkxie Will keep the same behavior as `input[disabled]`, namely:

```html
<input disabled>
<nz-cascader nzNoInput nzNoArrow></nz-cascader>
```

Are used for static mockup, while:

```html
<input [disabled]="condition">
<nz-cascader [nzNoInput]="condition" [nzNoArrow]="condition"></nz-cascader>
```

Applies to dynamic binding.

The only change is that if user writes `condition` before, they need to use `!condition` now, and vice versa.

**Comment by vthinkxie** [comment]
@trotyl 
Some components are designed as your description already, but change all boolean attribute `false` by default will bring some break changes, would you please figure out these changes?

**Comment by trotyl** [comment]
@vthinkxie I'll have a thorough check.

**Comment by trotyl** [comment]
Boolean inputs with `true` by default (so must have a value):

+ `NzCalendarComponent#nzClearTime`
+ `NzCalendarComponent#nzFullScreen`
+ `NzCalendarComponent#nzShowHeader`
+ `NzCardComponent#nzBordered`
+ `NzCarouselComponent#nzDots`
+ `NzCascaderComponent#nzShowInput`
+ `NzCascaderComponent#nzAllowClear`
+ `NzCascaderComponent#nzShowArrow`
+ `NzCascaderComponent#nzEnableCache`
+ `NzConfirmComponent#nzMaskClosable`
+ `NzDatePickerComponent#nzAllowClear`
+ `NzDropDownComponent#nzClickHide`
+ `NzDropDownButtonComponent#nzClickHide`
+ `NzMenuComponent#nzClickActive`
+ `NzModalComponent#nzClosable`
+ `NzModalComponent#nzMaskClosable`
+ `NzProgressComponent#nzShowInfo`
+ `NzSelectComponent#nzFilter`
+ `NzSliderComponent#nzIncluded`
+ `NzSpinComponent#nzSpinning`
+ `NzTabsNavComponent#nzAnimated`
+ `NzTabsNavComponent#nzShowPagination`
+ `NzTabSetComponent#nzAnimated`
+ `NzTabSetComponent#nzShowPagination`

Boolean inputs with `false` by default (but not support no value):

+ `NzAlertComponent#nzBanner`
+ `NzAlertComponent#nzCloseable`
+ `NzAlertComponent#nzShowIcon`
+ `NzBadgeComponent#nzDot`
+ `NzButtonComponent#nzGhost`
+ `NzButtonComponent#nzLoading`
+ `NzCalendarComponent#nzDatePicker`
+ `NzCardComponent#nzLoading`
+ `NzCardComponent#nzNoHovering`
+ `NzCarouselComponent#nzAutoPlay`
+ `NzCarouselComponent#nzVertical`
+ `NzCascaderComponent#nzDisabled`
+ `NzCascaderComponent#nzShowSearch`
+ `NzCascaderComponent#nzChangeOnSelect`
+ `NzCheckboxGroupComponent#nzDisabled`
+ `NzCheckboxGroupComponent#nzIndeterminate`
+ `NzCollapseComponent#nzDisabled`
+ `NzCollapseComponent#nzActive`
+ `NzConfirmComponent#nzVisible`
+ `NzConfirmComponent#nzConfirmLoading`
+ `NzDropDownButtonComponent#nzDisable`
+ `NzDropDownButtonComponent#nzVisible`
+ `NzDropDownComponent#nzVisible`
+ `NzModalComponent#nzVisible`
+ `NzModalComponent#nzConfirmLoading`
+ `NzMenuItemComponent#nzDisable`
+ `NzMenuItemComponent#nzSelected`
+ `NzMenuComponent#nzInlineCollapsed`
+ `NzOptionComponent#nzDisabled`
+ `NzPopconfirmComponent#nzCondition`
+ `NzRadioButtonComponent#nzDisabled`
+ `NzRadioComponent#nzChecked`
+ `NzRadioComponent#nzDisabled`
+ `NzRateComponent#nzDisabled`
+ `NzRowExpandIconComponent#nzExpand`
+ `NzRowExpandIconComponent#nzShowExpand`
+ `NzSelectComponent#nzShowSearch`
+ `NzSelectComponent#nzDisabled`
+ `NzSelectComponent#nzOpen`
+ `NzSiderComponent#nzCollapsed`
+ `NzSliderMarksComponent#nzVertical`
+ `NzSliderMarksComponent#nzIncluded`
+ `NzSliderStepComponent#nzVertical`
+ `NzSliderStepComponent#nzIncluded`
+ `NzSliderTrackComponent#nzVertical`
+ `NzSliderTrackComponent#nzIncluded`
+ `NzSliderComponent#nzDisabled`
+ `NzSliderComponent#nzDots`
+ `NzStepsComponent#nzProgressDot`
+ `NzSubMenuComponent#nzOpen`
+ `NzSwitchComponent#nzDisabled`
+ `NzTableComponent#nzBordered`
+ `NzTableComponent#nzCustomNoResult`
+ `NzTableComponent#nzLoading`
+ `NzTableComponent#nzShowSizeChanger`
+ `NzTableComponent#nzShowQuickJumper`
+ `NzTableComponent#nzShowTotal`
+ `NzTableComponent#nzShowFooter`
+ `NzTableComponent#nzShowTitle`
+ `NzTdDirective#nzCheckbox`
+ `NzTdDirective#nzExpand`
+ `NzThDirective#nzCheckbox`
+ `NzThDirective#nzExpand`
+ `NzTabLabelDirective#disabled`
+ `NzTabsInkBarDirective#nzAnimated`
+ `NzTabsNavComponent#nzHideBar`
+ `NzTabSetComponent#nzHide`
+ `NzCheckableTagComponent#nzChecked`
+ `NzCheckableTagComponent#nzClosable`
+ `NzTagComponent#nzClosable`
+ `NzTimePickerInnerComponent#nzDisabled`
+ `NzTimePickerComponent#nzDisabled`

Boolean inputs already supports no value truthy:

+ `NzBadgeComponent#nzShowZero`
+ `NzFormControlComponent#nzHasFeedback`
+ `NzSiderComponent#nzCollapsible`
+ `NzPaginationComponent#nzShowSizeChanger`
+ `NzPaginationComponent#nzShowQuickJumper`
+ `NzPaginationComponent#nzShowTotal`
+ `NzPaginationComponent#nzSimple`
+ `NzRateComponent#nzAllowHalf`
+ `NzSelectComponent#nzAllowClear`
+ `NzSelectComponent#nzKeepUnListOptions`
+ `NzSliderComponent#nzVertical`
+ `NzTableComponent#nzIsPagination`
+ `NzTableComponent#nzIsPageIndexReset`
+ `NzTimePickerInnerComponent#nzHideDisabledOptions`

**Comment by vthinkxie** [comment]
@trotyl 
it seems that many break changes will happened if make all boolean attribute `false` by default
what about make all `boolean inputs with false by default` support `no value truthy` first
and the bring the break change in the further version such as 0.6.x or 0.7.x

**Comment by trotyl** [comment]
Actually we don't need to remove the old ones (in near future), it's easy to provide different getter/setter with the same internal.

**Comment by vthinkxie** [comment]
@trotyl 
that is ok, we can give a warning or something before we remove the old ones.

**Comment by trotyl** [comment]
Wait for https://github.com/angular/angular/issues/19929.

**Comment by cipchk** [comment]
```ts
import { toBoolean } from '../util/convert';
```

Maybe much better in this way:

```ts
import {coerceBooleanProperty, coerceNumberProperty} from '@angular/cdk/coercion';
```

**Comment by trotyl** [comment]
@cipchk Agree with that.

**Comment by vthinkxie** [comment]
done in the latest version.
