### ISSUE TITLE
访问官网的临时方案 Temporary solution to access the website

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#462]
Hi all
If you can not access to our website, please visit ng-zorro.github.io as a temporary solution.
如果您所在的地区不能稳定的访问目前的官网，请暂时访问ng-zorro.github.io作为临时解决方案

**Comment by Turkyden** [comment]
为什么不能访问呢？是被墙了吗？

**Comment by tigercosmos** [comment]
I am also curious about why?

**Comment by gin-lsl** [comment]
猜一下我的内心。。。

**Comment by kentTanL** [comment]
这就很尴尬了，在家用电脑不能访问，但是用手机上的UC浏览器居然能访问。VPN 也被禁了！

**Comment by liepeng328** [comment]
为什么一会可以一会不可以，开发真是够累了，你就别折磨我了。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by vthinkxie** [comment]
http://ng-zorro.gitee.io/
