### ISSUE TITLE
[Input] support allowClear property for textarea

### ISSUE THREAD

**Issue by hsuanxyz** [NG-ZORRO/ng-zorro-antd#4623]
Ref https://github.com/ant-design/ant-design/pull/19310

**Comment by DreamPWJ** [comment]
请简化API  和react 一致

**Comment by DreamPWJ** [comment]
API太多复杂 ，多个清除input就导致大量的代码

**Comment by vthinkxie** [comment]
@DreamPWJ 自己封装一个组件一共7行代码，目前提供给所有用户的就是原子操作，你需要的不是简化API，是封装API
```html
    <nz-input-group [nzSuffix]="suffixTemplate">
      <input type="text" nz-input [(ngModel)]="inputValue" placeholder="input with clear icon" />
    </nz-input-group>
    <ng-template #suffixTemplate
      ><i nz-icon class="ant-input-clear-icon" nzTheme="fill" nzType="close-circle" *ngIf="inputValue" (click)="inputValue = null"></i
    ></ng-template>
```

**Comment by daniell0gda** [comment]
I think this issue should be reopened because of this situation:
![image](https://user-images.githubusercontent.com/8320732/89388989-1710b280-d705-11ea-9d29-b964b6ed966e.png)

Icon is now not visible.
