### ISSUE TITLE
树形控件叶子节点图标不显示

### ISSUE THREAD

**Issue by zhh007** [NG-ZORRO/ng-zorro-antd#4624]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-3cyrhe](https://stackblitz.com/edit/ng-zorro-antd-start-3cyrhe)

### Steps to reproduce
bug内容：树形控件叶子节点图标不显示。
这是官方文档中的例子。
地址：https://ng.ant.design/components/tree/zh。

### What is expected?
根据节点定义，叶子节点应显示文件图标。

### What is actually happening?
叶子节点文件图标未显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome 70 |

**Comment by hsuanxyz** [comment]
@zhh007 你提供的复现链接正常显示

**Comment by zhh007** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-3cyrhe
代码已修改。

**Comment by wenqi73** [comment]
@zhh007 叶子节点图标用 `icon` 属性展示；`nzExpandedIcon`替换的是展开的图标。
