### ISSUE TITLE
nz-table not supported horizontal scrolling

### ISSUE THREAD

**Issue by bambooj** [NG-ZORRO/ng-zorro-antd#463]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
yes, not support this feat yet

**Comment by zynzszyn521** [comment]
這個功能很重要，請幫忙盡快更新上吧，謝謝了

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed
