### ISSUE TITLE
Tag disappears when used inside dropdown that opened a second time

### ISSUE THREAD

**Issue by IonelLupu** [NG-ZORRO/ng-zorro-antd#4631]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-bknmpp?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-bknmpp?file=src/app/app.component.html)

### Steps to reproduce
Just use a nz-tag inside a dropdown menu. Open the dropdown once and you'll see that everything works ok. Open the dropdown a second time and you will notice the nz-tag disappear.

### What is expected?
I expect the tag to be rendered every time I open the dropdown

### What is actually happening?
The tag disappears the second time I open the dropdown

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 79.0, Firefox 71.0 , Opera 65.0 |

---
Works on Edge 42.17134.1.0

**Comment by wendellhu95** [comment]
Closed. Same reason with the one you submitted earlier.

**Comment by IonelLupu** [comment]
This is the issue #4594 in case someone is looking for it. Thank you!
