### ISSUE TITLE
对整体 UI 设计的一些不满

### ISSUE THREAD

**Issue by myfor** [NG-ZORRO/ng-zorro-antd#4632]
### NG.Ant 给人的整体感觉是浅色调+细字体+大间距（色调浅+字体细显得间距大）。
这样的话，初看很现代，但其实看起来很累。尤其是整体细字体的辨识度不高，再配合浅色调，看起来眼睛很累。
拿按钮举个例子：
![%`53D F@$ 1 )6MK3KU$}{1](https://user-images.githubusercontent.com/50647468/71789237-c482f100-3064-11ea-984c-e960c5659073.png)
默认的按钮是浅蓝色底色，这种颜色只在白色背景下会很搭，但看着就会很累，而且按钮的设计是十分扁平的，边框不明显，也没有阴影来修饰，使得按钮不像按钮，按钮和标签，卡片，甚至是列表的重合度高。你说它是标签我也不会怀疑。

### 大间距使得页面上的信息量有限
ant 的大间距是在细字体的效果上得以体现出来的。这样造成两个后果：
* 看着真的累
* 为了使页面来配合这种间距，页面整体的间距都要适当拉大，这就导致了窗口上能放下的信息量变小，会增加不需要的窗口拖动。

### 浅色调的字体看起来很累
浅色调 + 细字体 = 要用力看。
要用力看 + 字体偏小 = 要费力看。
这两点在 a 标签上是最明显的，所以 a 标签也是看起来最费力的。

### UI 效果太过突出
这是让我最不满意的一个地方，ant 的 UI 不是为了业务服务的，看起来就像是为了炫技。
整体的浅色调 + 细字体 + 大间距，虽然看起来现代化，但眼睛真的很累。浅色调使得组件和组件之间的区别不明显，例如：按钮是最应该和其他组件区分开的，但是为了扁平化的设计，把按钮也扁平化了，就让按钮看起来不像按钮。
到处都有的动画效果，真的会抢走用户的注意力，让他们不能马上注意到我要让他们注意到的内容。UI 是要为业务服务的，

以上是我认为的一些不足之处，来自于我自己多次使用的结果。就使用方式而言是非常方便的，奈何我眼睛真的太累了。

**Comment by vthinkxie** [comment]
ng zorro 9.0 会根据 antd 4.0 的设计规范进行调整，在此之前你可以通过自定义主题方式来控制界面的样式，包括主题色、间距等400多个变量
