### ISSUE TITLE
nzTable在虚拟滚动的情况下嵌套子表格滚动的问题

### ISSUE THREAD

**Issue by xiaoreign** [NG-ZORRO/ng-zorro-antd#4647]
### Reproduction link
[https://stackblitz.com/edit/angular-qbg79u](https://stackblitz.com/edit/angular-qbg79u)

### Steps to reproduce
点开前2行,展示子表格以后,往下滚动并不会滚到附表格的第三行,直接回滚到第五甚至第六行,

### What is expected?
外部的滚动条根据父表格正确的滚动

### What is actually happening?
因为子表格高度的原因,回直接跳过正确滚动的位置

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
虚拟滚动要求每行的行高一致才可以进行，非行高一致的情况下不支持虚拟滚动，具体参考https://material.angular.io/cdk/scrolling/overview
