### ISSUE TITLE
Inner scrollable UI elements of <body> are not scrollable while having a select as a child in opened state

### ISSUE THREAD

**Issue by waleedghous** [NG-ZORRO/ng-zorro-antd#4649]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-1j79jw](https://stackblitz.com/edit/ng-zorro-antd-start-1j79jw)

### Steps to reproduce
Scroll inner scrollable div - div.inner-scrollable-view is scrolling smoothly . 

- Step1: open any select.
- Step 2: attempt scroll.

Scroll inner scrollable div - div.inner-scrollable-view is not scrolling . 

### What is expected?
Scroll inner scrollable div - div.inner-scrollable-view is scrolling smoothly . 

- Step1: open any select.
- Step 2: attempt scroll.

Scroll inner scrollable div - div.inner-scrollable-view should be scrolling smoothly with any select control in opened state. 

### What is actually happening?
Scroll inner scrollable div - div.inner-scrollable-view is not scrolling while any select control in opened state. 

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | All browsers (IE11 , Edge, Chrome, Safari, Firefox) |

---
This isn't occurring in your REACT library because you guys have provided getpopupcontainer property there

**Comment by vthinkxie** [comment]
Hi @waleedghous 
we use the cdk backdrop to detect the click outside the component, there is an overlay with the backdrop in the DOM when the select open, users can not scroll before closing the select

**Comment by wenqi73** [comment]
closed via #5925.
