### ISSUE TITLE
TimePicker in ReactiveForms crashes when the input is a string representation of a Date.

### ISSUE THREAD

**Issue by TheAifam5** [NG-ZORRO/ng-zorro-antd#4654]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-6psoqi](https://stackblitz.com/edit/ng-zorro-antd-start-6psoqi)

### Steps to reproduce
1. Create Reactive Form
2. Add TimePicker with formControlName
3. Set FormGroup data with patchValue, where the input for TimePicker is a string representation of a Date (new Date().toJSON())
4. Click on TimePicker and pick something else.

### What is expected?
Should convert the string to the Date

### What is actually happening?
Tries to call Date related functions on a string, like getHour, getMinutes which leads to crash.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Firefox Developer Edition, Chrome |

**Comment by wenqi73** [comment]
Fixed it by #4949.
