### ISSUE TITLE
Resizable Table demo not working as expected

### ISSUE THREAD

**Issue by hrbernardic** [NG-ZORRO/ng-zorro-antd#4656]
### Reproduction link
[https://stackblitz.com/edit/angular-qoxgq4](https://stackblitz.com/edit/angular-qoxgq4)

### Steps to reproduce
Start the link i provided for stackblitz

### What is expected?
Table should render as shown in the demo on Ng Zorro website

### What is actually happening?
Initially the demo isn't working cause import for NzResizableModule is missing.
After adding the import resize handle renders below the header title not on the side.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Latest Chrome |

**Comment by hsuanxyz** [comment]
@hrbernardic Missing the basic style, need add `node_modules/ng-zorro-antd/resizable/style/index.min.css` in the angular.json.

 https://stackblitz.com/edit/angular-qoxgq4-uzwz2y

Thanks for feedback, we will fix the stackblitz.
