### ISSUE TITLE
Select does not show loading state when nzShowArrow is set to false

### ISSUE THREAD

**Issue by ReinerRunge** [NG-ZORRO/ng-zorro-antd#4659]
### Reproduction link
[https://angular-keaixs.stackblitz.io](https://angular-keaixs.stackblitz.io)

### Steps to reproduce
N/A

### What is expected?
The dropdown arrow must not show and the loading indicator should show

### What is actually happening?
Both the dropdown arrow and the loading state are not shown

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by ReinerRunge** [comment]
![image](https://user-images.githubusercontent.com/19598064/72065351-9b868880-3310-11ea-9d77-4ed2b2ba495f.png)

**Comment by ReinerRunge** [comment]
![image](https://user-images.githubusercontent.com/19598064/72065471-e0122400-3310-11ea-9487-f8a5dc3b0281.png)

**Comment by vthinkxie** [comment]
Hi @ReinerRunge 
the loading belows to the arrow part
keep the same behavior as react version
check it here
https://stackblitz.com/edit/react-xbly73?file=index.js
