### ISSUE TITLE
Can't disable an input from nz-input-group

### ISSUE THREAD

**Issue by dchirutac** [NG-ZORRO/ng-zorro-antd#4665]
Disabling an **input** from **nz-input-group** not works as expected. The style is applied but the input continue enabled.

```
<nz-input-group nzPrefixIcon="user">
      <input type="text" nz-input placeholder="Enter your username" [disabled]="true" />
 </nz-input-group>
```

[DEMO](https://stackblitz.com/edit/angular-p4edmk?file=src/app/app.component.ts)

**Comment by vthinkxie** [comment]
you need to add ngModel to nz-input in current version, we wil fix it in next version
