### ISSUE TITLE
Can't disable an input from nz-input-group

### ISSUE THREAD

**Issue by dchirutac** [NG-ZORRO/ng-zorro-antd#4666]
### Reproduction link
[https://stackblitz.com/edit/angular-p4edmk?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-p4edmk?file=src/app/app.component.ts)

### Steps to reproduce
```
<nz-input-group nzPrefixIcon="user">
     <input type="text" nz-input placeholder="Enter your username" [disabled]="disableInput" />
</nz-input-group>

```

### What is expected?
input should be disabled using **[disabled]="true"** attribute.

### What is actually happening?
input continue enabled using **[disabled]="true"** attribute.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by dchirutac** [comment]
Removing [] from disabled attribute resolve the issue

**Comment by vthinkxie** [comment]
duplicated #4655

**Comment by dchirutac** [comment]
In my case I'm using **FormBuilder** and no need of **ngModel**.

**Comment by vthinkxie** [comment]
@dchirutac 
if you are using **FormBuilder**, you must could find a warning in your web console
<img width="441" alt="截屏2020-01-10下午8 30 19" src="https://user-images.githubusercontent.com/1506722/72153155-0f479480-33e8-11ea-867e-888a542b22ea.png">

**Comment by dchirutac** [comment]
@vthinkxie my bad.  Thanks

**Comment by andressalhenriques** [comment]
It's is not working for me as well, I'm using nz-form-control, I try to find an example on documentation but I couldn't. Could someone help me?
