### ISSUE TITLE
nz-footer

### ISSUE THREAD

**Issue by chriseizus** [NG-ZORRO/ng-zorro-antd#4676]
### Reproduction link
[https://ng-zorro-antd-start-zsmt1x.stackblitz.io](https://ng-zorro-antd-start-zsmt1x.stackblitz.io)

### Steps to reproduce
resize the window's height to less than the inner container's height to make scroll appear, then the footer will behave incorrectly.

### What is expected?
The footer should be at the bottom under the inner container.

### What is actually happening?
in the example the footer is over on the inner container when the container's height is greater than the window's height.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
Hi @chriseizus 
just remove the 100vh in the css, it would work https://stackblitz.com/edit/ng-zorro-antd-start-k1qxfa?file=src/app/app.component.css
