### ISSUE TITLE
Can't bind to 'nzPopoverContent' since it isn't a known property of 'button'.

### ISSUE THREAD

**Issue by shahid-bitmascot** [NG-ZORRO/ng-zorro-antd#4677]
Hi,

When I use a popover with the directive `nzPopoverContent` it throws following error:

![Screenshot_40](https://user-images.githubusercontent.com/22909520/72216538-8138ee80-354c-11ea-8ecb-77c7c7bc0f5d.png)

In my template I was wrote:

```
<button nz-button [(nzVisible)]="visible" nz-popover nzPopoverTitle="Title" nzPopoverTrigger="click" [nzPopoverContent]="contentTemplate">Click me</button>
<ng-template #contentTemplate>
    <a (click)="clickMe()">Close</a>
</ng-template>
```

Can anyone please help me to figure out what was the wrong?

**Comment by vthinkxie** [comment]
plz make sure the version matches the doc you look

**Comment by shahid-bitmascot** [comment]
Issue resolved. I was using the `^8.1.2` version of `ng-zorro-antd`. Now using `^8.5.2`.

Thanks!
