### ISSUE TITLE
About Nz Carousel when the array is too large,it will show a lot and influence performance

### ISSUE THREAD

**Issue by Junior0909** [NG-ZORRO/ng-zorro-antd#4682]
## What problem does this feature solve?
When the array is large, we want to be able to display part of it in groups to solve the problem of too much display data and performance impact

## What does the proposed API look like?
I hope there is an API for data and an API for grouping data

**Comment by Junior0909** [comment]
https://github.com/Junior0909/nz-carousel.git

**Comment by wendellhu95** [comment]
It seems not usual (nor user-friendly) to have lots of carousel items is a single Carousel component. Maybe you can try [this](https://codepen.io/Raddy/full/NojQmd). If you could submit a PR implementing the feature you proposed we would be thrilled to review it.
