### ISSUE TITLE
树组件右键弹出操作面板，nz-dropdown-menu被树组件的ng-template包裹，右键的时会先后弹出两个框

### ISSUE THREAD

**Issue by 007GitHu** [NG-ZORRO/ng-zorro-antd#4684]
### Reproduction link
[https://stackblitz.com/edit/angular-az8atm?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-az8atm?file=src/app/app.component.ts)

### Steps to reproduce
<ng-template #nzTreeTemplate let-node>
    <nz-dropdown-menu #menu="nzDropdownMenu">
         <li nz-menu-item (click)="selectDropdown(node)">node值</li>
        <li nz-menu-item (click)="selectDropdown(node)">node值</li>
    </nz-dropdown-menu>
</ng-template>
   

### What is expected?
树组件的支持右键弹出操作面板，nz-dropdown-menu被树组件的ng-template包裹起来，右键弹框正常

### What is actually happening?
实际效果是会先后弹出两个框

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | 谷歌 |

---
包裹起来的目的是想在右键弹出的操作面板里面获取node节点的值

**Comment by vthinkxie** [comment]
ref #3971
