### ISSUE TITLE
nz-upload 不刷新的问题，这个问题距离我上次反馈已经有一年了

### ISSUE THREAD

**Issue by victory-wu** [NG-ZORRO/ng-zorro-antd#4687]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-kwbcz7?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-kwbcz7?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
add 添加图片后，使用refresh刷新才会显示

### What is expected?
添加后数据双向绑定，自动刷新

### What is actually happening?
需要手动刷新

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 版本 79.0.3945.88（正式版本） （64 位） |

**Comment by vthinkxie** [comment]
https://ng.ant.design/docs/faq/zh#%E6%95%B0%E6%8D%AE%E4%BF%AE%E6%94%B9%E5%90%8E%E9%A1%B5%E9%9D%A2%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%9B%B4%E6%96%B0

NG ZORRO 组件默认在 OnPush 模式下工作，mutate 对象或者数组不会触发 Angular 的变更检测，请使用 immutable 方式。

https://stackblitz.com/edit/ng-zorro-antd-start-bndrhp?file=src/app/app.component.ts
