### ISSUE TITLE
nz-switch 的选中与未先中的值可不可以自定义

### ISSUE THREAD

**Issue by MzoroHaHa** [NG-ZORRO/ng-zorro-antd#4692]
## What problem does this feature solve?
formGroup中需要的值是两个固定的值 （1/2 ）而非 true/false这样的boolean值，可不自定义 nz-swich的选中与不选中的值呢？

## What does the proposed API look like?
nz-switch 的选中与未先中的值可不可以自定义

**Comment by wendellhu95** [comment]
请自行转换。
