### ISSUE TITLE
tree 组件加上nzShowLine属性，不能开启异步加载

### ISSUE THREAD

**Issue by TheBeard30** [NG-ZORRO/ng-zorro-antd#4693]
I am opening an issue for：ng-zorro-antd
this is a bug report
Version:   8.5.2
Browser:  Google Chrome
Step to reproduce：
tree 组件加上nzShowLine属性，再加上nzAsyncData，不能出现loading状态,不能开启异步加载
Link to minimal reproduction:
https://stackblitz.com/edit/angular-dlsdqu

**Comment by TheBeard30** [comment]
https://stackblitz.com/edit/angular-dlsdqu

**Comment by kisslove** [comment]
在1.8.x版本中也发现一样的问题：tree 组件加上nzShowLine属性，再加上nzAsyncData，不能出现loading状态,能异步加载。
