### ISSUE TITLE
nz-select in nz-modal

### ISSUE THREAD

**Issue by egalley** [NG-ZORRO/ng-zorro-antd#4695]
Hello,

I have an issue with the size of nz-select inside an nz-modal.

You can reproduce it with the nz-modal example and adding an nz-select component inside.

Thank you
![nz-select](https://user-images.githubusercontent.com/10241465/72526164-11857500-3866-11ea-9cc5-810f0e2f3d51.png)

**Comment by wendellhu95** [comment]
Just fork the demo and paste the link here.

**Comment by egalley** [comment]
https://dlzdqv.run.stackblitz.io

**Comment by luohong123** [comment]
I have encountered the same problem. Have you solved it?

**Comment by egalley** [comment]
Yes I add this style="width:-webkit-fill-available;"

<nz-select style="width:-webkit-fill-available;">

and it works for me.

**Comment by hsuanxyz** [comment]
Should be fixed in the newer version
