### ISSUE TITLE
Table Tree data drag sorting does not work

### ISSUE THREAD

**Issue by jeyathilak** [NG-ZORRO/ng-zorro-antd#4697]
### Reproduction link
[https://stackblitz.com/edit/angular-eg7skx](https://stackblitz.com/edit/angular-eg7skx)

### Steps to reproduce
Drag a row from the parent or child tree and drop it to a different index. The row goes back to it's original index.

### What is expected?
Expected: The row that is dropped to a different index should stay and not go back to it's original index

### What is actually happening?
The row goes back to it's original index.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by rmonnier9** [comment]
Hi,
I'm trying to do the same thing, did you get a solution ?
Thanks !

**Comment by jeyathilak** [comment]
I ended up using my own custom drag and drop

**Comment by rmonnier9** [comment]
Could you share some advice about how to implement it ?
I will start doing it as well tomorrow, we could mutualize out work so we both get an external point of view

**Comment by vthinkxie** [comment]
this issue should be fixed in the latest version, feel free to open another one if you still meet the problem

**Comment by viniciusi** [comment]
@jeyathilak Could you share some advice about how to implement it?

@rmonnier9 Did you get the solution?

Thanks!

**Comment by rmonnier9** [comment]
Hi,

I decided to use an other component designed for hierarchical data : tree
data.
