### ISSUE TITLE
把nz-tag放在nz-dropdown中，首次显示再次展开后占位但不显示

### ISSUE THREAD

**Issue by waldo-wy** [NG-ZORRO/ng-zorro-antd#4698]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-hvs5yh](https://stackblitz.com/edit/ng-zorro-antd-start-hvs5yh)

### Steps to reproduce
Hover Show Issue 中两次可复现问题

### What is expected?
正常展示

### What is actually happening?
首次显示再次展开后占位但不显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by wendellhu95** [comment]
Could you please use issue seaching?

https://github.com/NG-ZORRO/ng-zorro-antd/issues?q=is%3Aissue+sort%3Aupdated-desc+dropdown+tag+is%3Aclosed
