### ISSUE TITLE
Need to set z-index manually on nz-menu.

### ISSUE THREAD

**Issue by chunghha** [NG-ZORRO/ng-zorro-antd#470]
## I'm submitting a...

<pre><code>
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

The sub menu in the Navigation Three is displayed under nz-content. Please see the stackblitz example below.

## Expected behavior

No need to set z-index manually on nz-menu.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-2zdzv3?embed=1&file=app/app.component.html
`<ul nz-menu [nzMode]="'horizontal'" style="position: relative; z-index: 999;">`
Try with/without the style above.

## What is the motivation / use case for changing the behavior?

Asking users to set z-index manually might be too much.

## Environment

<pre><code>
Angular version: 5.0.0-rc.3

ng-zorro-antd version: 0.5.5

Browser:
- [ ] Chrome (desktop) version XX
- [ x ] Firefox version 56
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: 8.7.0  
- Platform:  Linux 

Others:

</code></pre>

**Comment by tigercosmos** [comment]
Without style:
![image](https://user-images.githubusercontent.com/18013815/31858997-7bc219bc-b737-11e7-82ea-4f129e34a64b.png)

With style:
![image](https://user-images.githubusercontent.com/18013815/31859011-b8bde18e-b737-11e7-9094-ed27b2b1d7de.png)

**Comment by tigercosmos** [comment]
It's wired.
case in showcase is fine
![image](https://user-images.githubusercontent.com/18013815/31859286-2da1b4f4-b73c-11e7-901d-5bccf86ed7e9.png)

**Comment by tigercosmos** [comment]
Related code is [`src/components/menu/style/index.less`](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/menu/style/index.less)

**Comment by vthinkxie** [comment]
there is noting todo with z-index here
try this https://angular-dhfdxp.stackblitz.io

**Comment by tigercosmos** [comment]
what's the difference in your code?

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-dhfdxp?embed=1&file=app/app.component.html

**Comment by tigercosmos** [comment]
@vthinkxie only `div` is different?

before:
```html
<nz-layout>
    <nz-header style="background: #fff; padding:0;">
      <i class="anticon trigger" [class.anticon-menu-fold]="!isCollapsed" [class.anticon-menu-unfold]="isCollapsed" (click)="isCollapsed=!isCollapsed"></i>
    </nz-header>
    <ul nz-menu [nzMode]="'horizontal'">
      <li nz-menu-item><i class="anticon anticon-mail"></i> Navigation One</li>
      <li nz-menu-item [nzDisable]="true"><i class="anticon anticon-appstore"></i> Navigation Two</li>
      <li nz-submenu>
        <span title><i class="anticon anticon-setting"></i> Navigation Three - Submenu</span>
        <ul>
          <li nz-menu-group>
            <span title>Item 1</span>
            <ul>
              <li nz-menu-item>Option 1</li>
              <li nz-menu-item>Option 2</li>
            </ul>
          </li>
```

after:
```html
 <nz-layout>
    <nz-header style="background: #fff; padding:0;">
      <i class="anticon trigger" [class.anticon-menu-fold]="!isCollapsed" [class.anticon-menu-unfold]="isCollapsed" (click)="isCollapsed=!isCollapsed"></i>
    </nz-header>
    <div>  <!-- ================================== -->
    <ul nz-menu [nzMode]="'horizontal'">
      <li nz-menu-item><i class="anticon anticon-mail"></i> Navigation One</li>
      <li nz-menu-item [nzDisable]="true"><i class="anticon anticon-appstore"></i> Navigation Two</li>
      <li nz-submenu>
        <span title><i class="anticon anticon-setting"></i> Navigation Three - Submenu</span>
        <ul>
          <li nz-menu-group>
            <span title>Item 1</span>
            <ul>
              <li nz-menu-item>Option 1</li>
              <li nz-menu-item>Option 2</li>
            </ul>
          </li>
```

**Comment by vthinkxie** [comment]
@tigercosmos yes

**Comment by tigercosmos** [comment]
@vthinkxie  I don't know why we have to add a `div`? I thought it should be work without a `div` container. 
Or if this is necessary, maybe we should add a note in document.

**Comment by tigercosmos** [comment]
p.s. I thought using `nz-content` than `div` in this case may be more clear in logic.

**Comment by chunghha** [comment]
@tigercosmos @vthinkxie thanks for the checking.
