### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by saeedrahimi** [NG-ZORRO/ng-zorro-antd#4704]
## What problem does this feature solve?
Currently Ant-Design in v4 supports rtl in all components and demos, in this issue i want to add progress of making all components of ng-zorro-antd support rtl.
## What does the proposed API look like?
``` ts
dir: Direction = 'ltr';
constructor(
  private cdr: ChangeDetectorRef,
  @Optional() private directionality: Directionality
) {}

ngOnInit(): void {
  this.directionality.change?.pipe(takeUntil(this.destroy$)).subscribe((direction: Direction) => {
    this.dir = direction;
    this.cdr.detectChanges();
  });

  this.dir = this.directionality.value;
}
```

``` html
  <div
    #tableMainElement
    class="ant-table"
    [class.ant-table-rtl]="dir === 'rtl'"
  >
</div>
```

## RTL Progress #4703

- [x] Button
- [x] Icon
- [x] Typography
- [x] Grid
- [x] Layout
- [x] Affix
- [x] Breadcrumb
- [x] Dropdown
- [x] Menu
- [x] Pagination
- [x] PageHeader
- [x] Steps
- [x] AutoComplete
- [x] CheckBox
- [x] Cascader
- [x] DatePicker
- [x] Form: hdm91
- [x] InputNumber: hdm91
- [x] Input: hdm91
- [x] Mention
- [x] Rate
- [x] Radio
- [x] Switch
- [x] Slider: hdm91
- [x] Select
- [x] TreeSelect
- [x] Transfer: hdm91
- [x] TimePicker
- [x] Upload: hdm91
- [x] Avatar
- [x] Badge
- [x] Comment
- [x] Collapse: hdm91
- [x] Carousel
- [x] Card
- [ ] Calendar
- [x] Description List
- [x] Empty
- [x] List: hdm91
- [x] Popover
- [x] Statistic
- [x] Tree: hdm91
- [x] Tooltip
- [x] Timeline
- [x] Tag
- [x] Tabs: hdm91
- [x] Table
- [x] Alert: hdm91
- [x] Drawer
- [x] Modal: hdm91
- [x] Message
- [ ] Notification
- [x] Progress
- [x] Popconfirm
- [x] Result
- [x] Spin: hdm91
- [x] Skeleton
- [x] Anchor (No need to RTL)
- [x] BackTop
- [ ] ConfigProvider
- [x] Divider (No need to RTL)
- [ ] Front page

**Comment by wendellhu95** [comment]
Looking forward to it! Thank you very much.

**Comment by saeedrahimi** [comment]
> Looking forward to it! Thank you very much.

Should i open pull-request for every component or do them all in one pull-request?

**Comment by wendellhu95** [comment]
@saeedrahimi You can do them all in a single pull-request. I guess that would save you some trouble?

**Comment by vthinkxie** [comment]
Hi @saeedrahimi 

thanks for your pr a lot

we are refactoring some components these days, you may need to rebase on these components after that.

**Comment by saeedrahimi** [comment]
> Hi @saeedrahimi
> 
> thanks for your pr a lot
> 
> we are refactoring some components these days, you may need to rebase on these components after that.

Thanks @vthinkxie 
Is there any reference or issue that i can track refactored components and add rtl to them?
If i apply rtl before refactoring because of files renamed in refactoring and other changes, the process of rebase would be hard.

**Comment by vthinkxie** [comment]
Hi @saeedrahimi 
there is a list here
https://github.com/NG-ZORRO/ng-zorro-antd/issues/4634

**Comment by mkzaker** [comment]
@saeedrahimi 
آقا دمت گرم
چطوری می تونم بهت کمک کنم؟

**Comment by saeedrahimi** [comment]
@mkzaker 
ممنونم.
فعلا که منتظرم کامپوننت ها توسط تیم توسعه دهنده بازنویسی بشن و کار کمی کند پیش میره

**Comment by hdm91** [comment]
Hi @saeedrahimi thanks for your participation in ng zorro RTL support , i will be happy to help you.

**Comment by behroozbc** [comment]
@saeedrahimi 
اقا تو این تعطیلات چطور میتونیم کمکت کنیم بهمون بگو !!

**Comment by mkzaker** [comment]
@saeedrahimi 
منم پایه ام و البته منتظر این نسخه

**Comment by saeedrahimi** [comment]
> @saeedrahimi
> اقا تو این تعطیلات چطور میتونیم کمکت کنیم بهمون بگو !!

> @saeedrahimi
> منم پایه ام و البته منتظر این نسخه


ممنون از لطف شما
اگر مایلید توی نوشتن تست‌ها کمک کنید
چون برخی کدها اضافه شده و 
code coverage 
پایین اومده

-
اینو می‌دونم کسی که کد میزنه خودش باید تست هم بنویسه، اما فعلا بخاطر کانفیگ سیستمم در اجرای تست با مشکل مواجه هستم و تمام این تایمی که برای 
ng-zorro
دارم رو سعی میکنم فقط 
rtl
انجام بدم.

**Comment by HDaghash** [comment]
Thank you @saeedrahimi for supporting this any clue when this will be completed & released ?

Thanks again.

**Comment by Sina7312** [comment]
This is awesome, we really need it in our company. Is there any ETA on when this going to finish?
I'm also able to help if you need any help 👍

**Comment by renilbabu03** [comment]
@vthinkxie : Any idea when RTL will be available. It would be really helpful.

**Comment by abdelrahmannasr** [comment]
Any update about support RTL

**Comment by saeedrahimi** [comment]
I just need help on updating tests.

**Comment by HDaghash** [comment]
> I just need help on updating tests.

could you please point me to the modules that have a missing test so I can contribute with you?

**Comment by HDaghash** [comment]
@vthinkxie thank you guys for all the effort of releasing version 10 , but I believe this is was a part of the milestone of version 10 to support RTL, is it postponed now or something?

**Comment by saeedrahimi** [comment]
Hi there, 
Sorry for my long absence, i have been really busy.
.
recent changes:
rebased to last changes from master branch.
@hdm91 thanks for your efforts on adding RTL to some of remaining components, actually i cherry-picked your changes from your fork to mine in #4703.

**Comment by saeedrahimi** [comment]
> 
> 
> > I just need help on updating tests.
> 
> could you please point me to the modules that have a missing test so I can contribute with you?

Actually i'm struggling with tests and couldn't find any way to change direction (LTR | RTL) in test cases.

I've tried these methods and they  didn't worked.
```ts
document.body.setAttribue("dir","rtl")
// OR
TestBed.overrideProvider(Directionality, {value:'rtl'})
```
I want is to increase coverage to pass codecov pipeline.
- Merging #4703 into master will decrease coverage by 1.00%.
https://codecov.io/gh/NG-ZORRO/ng-zorro-antd/pull/4703?src=pr&el=tree

**Comment by saeedrahimi** [comment]
> 
> 
> > > I just need help on updating tests.
> > 
> > 
> > could you please point me to the modules that have a missing test so I can contribute with you?
> 
> Actually i'm struggling with tests and couldn't find any way to change direction (LTR | RTL) in test cases.
> 
> I've tried these methods and they didn't worked.
> 
> ```ts
> document.body.setAttribue("dir","rtl")
> // OR
> TestBed.overrideProvider(Directionality, {value:'rtl'})
> ```
> 
> I want is to increase coverage to pass codecov pipeline.
> 
>     * Merging #4703 into master will decrease coverage by 1.00%.
>       https://codecov.io/gh/NG-ZORRO/ng-zorro-antd/pull/4703?src=pr&el=tree

Just found a way for changing direction ;-)  https://github.com/NG-ZORRO/ng-zorro-antd/pull/4703/commits/478725d29dd6f82be3484c5dad97170eb0fedd17#

**Comment by vthinkxie** [comment]
Hi @saeedrahimi 
good job
thanks a lot to your efforts!
we will start reviewing it once you finish the job

**Comment by HDaghash** [comment]
Hi @saeedrahimi 
I'll try to contribute with the little remaining part :
here's a suggested way to RTL message : 

https://github.com/HDaghash/ng-zorro-antd/pull/1/files

**Comment by hsuanxyz** [comment]
👋 Hi all,

I think it is too difficult to do this in one PR. So I suggest that we submit a PR for each completed component, and add a label to the `components/**/doc/index.*.md` file.

```diff
---
category: Components
type: General
title: Button
cover: https://gw.alipayobjects.com/zos/alicdn/fNUKzY1sk/Button.svg
+ rtl: true
---
```

This allows us to better track progress and prevent other PRs to make breaking changes.

@saeedrahimi @HDaghash  what do you think about it?

**Comment by hsuanxyz** [comment]
By the way, we can merge these PRs in any version without having to wait for all components to finish.

**Comment by HDaghash** [comment]
> By the way, we can merge these PRs in any version without having to wait for all components to finish.

I agree with that , specially @saeedrahimi almost done with most of the components so much better to merge the done part instead of keep waiting for the little remaining components.
