### ISSUE TITLE
Select choice item style

### ISSUE THREAD

**Issue by LucaGabi** [NG-ZORRO/ng-zorro-antd#4717]
## What problem does this feature solve?
Allow to have visual differentiation on choice selected items 
## What does the proposed API look like?
Use 
``` 
       <nz-option nzCustomContent *ngIf="!isLoading" [nzValue]="o">
          <span style="background-color: red;">test</span >
        </nz-option>
```

![image](https://user-images.githubusercontent.com/37976898/72984502-83246c80-3dec-11ea-9501-fa6c5c691301.png)

NO nzLabel
Thanks!

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/select/en#components-select-demo-custom-template

**Comment by LucaGabi** [comment]
Thank you!

**Comment by LucaGabi** [comment]
I hava a question: in the demo example how do I use *ngFor and how do I pass item to the ng-template outside ngFor ?

Please help.

**Comment by xjuanc** [comment]
Did you manage to set a custom color to the custom template as in your image? Having a hard time to figure out how to do so when it's tag mode
