### ISSUE TITLE
checkbox text show bold default and margin can't custom

### ISSUE THREAD

**Issue by winds2016** [NG-ZORRO/ng-zorro-antd#472]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[*] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

checkbox text show bold default;
checkbox text margin have 1em,so whole checkbox(with icon) margin-left not equal margin-right

## Expected behavior
checkbox text show normal default;
how set checkbox text margin(left and right)?or whole checkbox(with icon) margin-left equal margin-right

## Environment

<pre><code>
Angular version: 4.0.1

ng-zorro-antd version: 0.5.4

Browser:
- [ ] Chrome (desktop) version XX
- [*] Firefox version 56
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: 7.6  
- Platform: win 

Others:

</code></pre>

**Comment by vthinkxie** [comment]
You can custom any style with your css file, if you can't please make sure you have read the angular doc .

**Comment by winds2016** [comment]
i just want checkbox text show normal default,not bold,so we not need to custom everywhere:)
thanks
and question 2 is not exists afternoon,strange and sorry

**Comment by winds2016** [comment]
i custom style in css file myself,thanks
