### ISSUE TITLE
Simplify component use

### ISSUE THREAD

**Issue by LucaGabi** [NG-ZORRO/ng-zorro-antd#4727]
## What problem does this feature solve?
I hava a question: in the demo example how do I use *ngFor and how do I pass item to the ng-template outside ngFor ?

https://ng.ant.design/components/select/en#components-select-demo-custom-template

Please help.
## What does the proposed API look like?
?

**Comment by vthinkxie** [comment]
I think it should be basic angular knowledge
`html
<div *ngFor="..." [templatePassIn]="templateVar"><ng-template #templateVar></ng-template> </div>
`

**Comment by LucaGabi** [comment]
The use case is this:

![image](https://user-images.githubusercontent.com/37976898/73118011-a10de080-3f56-11ea-9663-7cf46419aea4.png)

How to pass 'panel' foreach item in '#logHeader' ?

Thanks!

**Comment by vthinkxie** [comment]
why not put your template inside the *ngFor?
