### ISSUE TITLE
请问生成tgz推包文件是使用npm run integration 这个指令吗?但是找不到integration-test.sh文件

### ISSUE THREAD

**Issue by guggit** [NG-ZORRO/ng-zorro-antd#4729]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
无

### What is expected?
请问生成tgz推包文件是使用npm run integration 这个指令吗?但是找不到integration-test.sh文件

### What is actually happening?
生成失败

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome |

**Comment by wendellhu95** [comment]
`npm run pack`.

**Comment by guggit** [comment]
> `npm run pack`.

感谢你的回答，可是没有npm run pack 的脚本
![image](https://user-images.githubusercontent.com/34000909/73129527-1d6cf600-4021-11ea-9dd8-b2a2f6c0b1de.png)

**Comment by wendellhu95** [comment]
![图片](https://user-images.githubusercontent.com/12122021/73129560-0c70b480-4022-11ea-8f61-cb49c8ddad39.png)

请先学好 npm 基础知识，不要浪费彼此的时间。
