### ISSUE TITLE
nz-cascader does not support case insensitive search..

### ISSUE THREAD

**Issue by ngantcoder** [NG-ZORRO/ng-zorro-antd#4732]
## What problem does this feature solve?
nz-cascader having property nzShowSearch when it set to true i can search in data but its case sensitive search also containing NzShowSearchOptions but can't understand how to use this property.
can't find a solution, please help
## What does the proposed API look like?
[nzShowSearch]="{case-sensitive:true}"

**Comment by wendellhu95** [comment]
```html
[nzShowSearch]="searchOption"
```

```typescript
searchOption = {
  filter(inputValue: string): boolean {
     return inputValue.toLowerCase() === someInput.toLowerCase()
  }
}
```

Please do not use GitHub issue for usage questions.

**Comment by vatsake** [comment]
How do you use this? What's 'someInput'?

**Comment by wendellhu95** [comment]
> Why not? The documentation is ambiguous and makes no sense.
> I can't understand this at all:
> 
> ![image](https://user-images.githubusercontent.com/15611519/121025534-89c74000-c7a5-11eb-8c28-2e5456fa05ac.png)
> 
> And I thought that this sort of configuration should be based on a predicate reference, yet your "someInput" in your comment above comes from somewhere I don't understand.
> 
> Does this mean that the Cascader component is unable to resolve option label values against the internal search input value?

I modified that demo above. Hopefully it would make more sense to you.

The reason why we wouldn't support the API is that  `[nzShowSearch]="{ 'case-sensitive': true }"` is not a generic solution to all kinds of customized searching. What if users wants to use fuzzy searching here? Shall we add a configure like `{ fuzzy: true }`? IMHO, we could not cover all scenario by just adding configuration. Instead, a callback API like `filter` helps users to do customized searching in any way they want.

Hope this helps. :p

**Comment by chriso86** [comment]
> > Why not? The documentation is ambiguous and makes no sense.
> > I can't understand this at all:
> > ![image](https://user-images.githubusercontent.com/15611519/121025534-89c74000-c7a5-11eb-8c28-2e5456fa05ac.png)
> > And I thought that this sort of configuration should be based on a predicate reference, yet your "someInput" in your comment above comes from somewhere I don't understand.
> > Does this mean that the Cascader component is unable to resolve option label values against the internal search input value?
> 
> I modified that demo above. Hopefully it would make more sense to you.
> 
> The reason why we wouldn't support the API is that `[nzShowSearch]="{ 'case-sensitive': true }"` is not a generic solution to all kinds of customized searching. What if users wants to use fuzzy searching here? Shall we add a configure like `{ fuzzy: true }`? IMHO, we could not cover all scenario by just adding configuration. Instead, a callback API like `filter` helps users to do customized searching in any way they want.
> 
> Hope this helps. :p
> 
> BTW, no core team member of ng-zorro-antd is native English speaker. So we will appreciate it very much if you could please optimize our doc.

I understand, and I don't mind helping with the documentation.
I work with this library in my everyday, so I should be able to contribute in terms of documentation and language improvement for English speakers.

Thanks for updating the example above, it makes a lot more sense now.

It also helped to look at the implementation here of the [default filter](https://github.com/NG-ZORRO/ng-zorro-antd/blob/36c529d379da7f849b5fbab0b2643a2c5642ef13/components/cascader/cascader.service.ts#L238).
