### ISSUE TITLE
feat request: support nzPlacement in nz-menu / nz-submenu

### ISSUE THREAD

**Issue by ccppprogrammer** [NG-ZORRO/ng-zorro-antd#4743]
## What problem does this feature solve?
Currently you cannot create a menu with different placement options, similar to nz-dropdown.

Thus, if you put nz-submenu with nzMode="horizontal", which is located in nz-header, on the right side of the header, nz-submenu goes beyond the visible area.

Example screenshot of the current behavior:

<img src="https://i.imgur.com/eIv91w0.png"/>

## What does the proposed API look like?
nz-submenu of nz-menu in nzMode="horizontal" should support nzPlacement directive with at least bottomLeft and bottomRight values or correctly place sumenu on the screen automatically depending on the current position.

|Property|Description|Type|Default|
|---|---|---|---|
|[nzPlacement] | placement of pop menu | 'bottomLeft' \| 'bottomCenter' \| 'bottomRight' \| 'topLeft' \| 'topCenter' \| 'topRight' | 'bottomLeft' |

**Comment by timothyBrake** [comment]
This doesn't seem to be implemented yet or is it? Any workaround?

**Comment by klerick** [comment]
+1
