### ISSUE TITLE
Dragging over nzMax of nz-slider

### ISSUE THREAD

**Issue by clarkttfu** [NG-ZORRO/ng-zorro-antd#4749]
### Reproduction link
[https://stackblitz.com/edit/angular-bsrcq9](https://stackblitz.com/edit/angular-bsrcq9)

### Steps to reproduce
Drag the slider dot over the maximum point. The slider will automatically scale 10 times, making it 10 times longer

### What is expected?
The nzMax attribute should work

### What is actually happening?
The nzMax scales 10 times in this case

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 79 |

---
This is also reproducible in older versions like 8.0.2 
I guess this is something related to the grid layout..

**Comment by clarkttfu** [comment]
Note the template I used:

```
<nz-slider nzMin="0" nzMax="9" [(ngModel)]="retry"></nz-slider>
```

So the "0" is used as string instead of evaluated integer 0.

nz-slider.component.ts:353
```
const val = (this.nzMax - this.nzMin) * (this.nzVertical ? 1 - ratio : ratio) + this.nzMin;
```
The `+` above works as concatenation..

Work round:

```
<nz-slider [nzMin]="0" nzMax="9" [(ngModel)]="retry"></nz-slider>
```

Possible fix:
```
const val = (this.nzMax - this.nzMin) * (this.nzVertical ? 1 - ratio : ratio) + Number(this.nzMin);
```

**Comment by wendellhu95** [comment]
You can use `InputBoolean` decorator properties of the Slider component to fix this. PR welcome!

**Comment by wendellhu95** [comment]
Since we are refactoring this component, you can send a PR to the PR. https://github.com/NG-ZORRO/ng-zorro-antd/pull/4730/files#diff-10

**Comment by clarkttfu** [comment]
ok but may be later
