### ISSUE TITLE
<nz-breadcrumb nzAutoGenerate> not work when has multiple <router-outlet>s

### ISSUE THREAD

**Issue by wheeljs** [NG-ZORRO/ng-zorro-antd#4751]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-palk3f](https://stackblitz.com/edit/ng-zorro-antd-start-palk3f)

### Steps to reproduce
0. `<nz-breadcrumb nzAutoGenerate></nz-breadcrumb>` with two `<router-outlet>`s.
1. Click "Open" button, popover open and url appended with '(op: sub)', breadcrumb will be hidden.
2. Click "Close", then url back to '/app/home' and breadcrumb displayed correct.

### What is expected?
When popover is showing(url with '(op:sub)'), breadcrumb still showing with primary router outlet breadcrumb data.

### What is actually happening?
When popover showing(url with '(op:sub)'), breadcrumb be hidden.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 版本 79.0.3945.130（正式版本） （64 位） |

---
Sorry for my English.

**Comment by franknwankwo** [comment]
I'm experiencing the same issue
