### ISSUE TITLE
popover blocks webpage scrolling in some layout

### ISSUE THREAD

**Issue by rppig42** [NG-ZORRO/ng-zorro-antd#4763]
You can reproduce this issue by visiting this link https://stackblitz.com/edit/angular-hxlgre

**Comment by wendellhu95** [comment]
When we're using 'click' as the trigger, we would use a backdrop to detect "clicking outside" event. Unfortunately, this backdrop element would also make scroll events not dispatched to the `body` element. For now, you can use other triggers.
