### ISSUE TITLE
the "show password icon" is overlapped by the entered text

### ISSUE THREAD

**Issue by ccppprogrammer** [NG-ZORRO/ng-zorro-antd#4767]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-overlap-icon-bwhejb](https://stackblitz.com/edit/ng-zorro-antd-overlap-icon-bwhejb)

### Steps to reproduce
Add nzHasFeedback for the nz-form-control to display the "validation status icon" and nzSuffix template for the nz-input-group to display the "show password icon", and enter the text that should be larger than the input area.

### What is expected?
The text in nz-input shouldn't overlap the "show password" icon.

### What is actually happening?
When using the "validation status icon" and "show password icon" on the nz-input, text overlap the "show password icon".
Check the image below and the stackblitz demo.

<img src="https://i.imgur.com/ZCeHFtG.png">

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Google Chrome Version 79.0.3945.130 (Official Build) (64-bit) |

**Comment by vthinkxie** [comment]
fixed in 9.0.0-beta.3 now
https://stackblitz.com/edit/ng-zorro-antd-overlap-icon-bwhejb-zawmbd?file=angular.json
