### ISSUE TITLE
NzNotificationService doesn't update template via nzKey

### ISSUE THREAD

**Issue by levitatejay** [NG-ZORRO/ng-zorro-antd#4787]
### Reproduction link
[https://stackblitz.com/edit/angular-rghrwj](https://stackblitz.com/edit/angular-rghrwj)

### Steps to reproduce
Open notification, it should change from Apple to Banana.

### What is expected?
Notification should change to Banana with yellow tag

### What is actually happening?
Notification doesn't change

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by patricknazar** [comment]
Here is a [working fork](https://stackblitz.com/edit/angular-rghrwj-szxnmj?file=src/app/app.component.ts) of your stackblitz

**Comment by fengpeng** [comment]
Same problem in 9.1.0
在9.1.0里遇到了相同的问题.

**Comment by levitatejay** [comment]
> Here is a [working fork](https://stackblitz.com/edit/angular-rghrwj-szxnmj?file=src/app/app.component.ts) of your stackblitz

This is a good solution to that specific example but it requires that the service that creates the notification also holds a reference to the original input object so that it can mutate the values

Also I don't think there is a way to change the NzDuration on an existing NzNotification?

For example to update Notification from infinite duration (0ms) to fixed duration 2000ms

**Comment by fengpeng** [comment]
@levitatejay  thanks,  let me try ^O^

**Comment by artavdalyan** [comment]
please add this commit to 8.5.2 version
