### ISSUE TITLE
some style error when i use both Virtual scrolling and Ajax in table

### ISSUE THREAD

**Issue by mrlionline** [NG-ZORRO/ng-zorro-antd#4794]
### Reproduction link
[https://stackblitz.com/edit/angular-vy9sxx](https://stackblitz.com/edit/angular-vy9sxx)

### Steps to reproduce
title

### What is expected?
a normal table

### What is actually happening?
a bad table

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 80.0.3987.106 |

---
无

**Comment by vthinkxie** [comment]
Hi this issue has been fixed in 9.x version, you can try this https://stackblitz.com/edit/ng-zorro-antd-ivy-1denhy
feel free to open a new issue if I miss something
