### ISSUE TITLE
怎么统一改变整体字体大小？

### ISSUE THREAD

**Issue by steelmanmanm** [NG-ZORRO/ng-zorro-antd#48]
![ngzt](https://user-images.githubusercontent.com/30724252/29370850-3496a1c6-82d9-11e7-82cf-76c358dfb22a.png)
如上所示，默认按官方网站的“快速上手”建立了一个工程，但是字体很小，请问怎么统一放大一下整体字体大小呢？谢谢！

**Comment by liuliangjia** [comment]
windows底下特别小，mac底下还行。

**Comment by vthinkxie** [comment]
define font-size in your css file to overwrite it.

**Comment by liuliangjia** [comment]
在style.css里，通过定义body { font-size:14px }，覆盖不了，是通过其它的什么方式？

**Comment by zhangkang1521** [comment]
style.css at the top of the page, it override by ng-zorro's style!
![image](https://user-images.githubusercontent.com/18444827/34427987-f2a4ef7a-ec82-11e7-927a-e297ebf4827c.png)

**Comment by lomo1** [comment]
@liuliangjia  兄弟，我也遇到了，用的是Zorro 最新版0.6.x的。无论是在`style.css`还是在组件对应的样式文件里修改，都不起作用。。请问你是怎么解决的呢

**Comment by dknfeiov** [comment]
@lomo1  在组件对应的样式文件中用 
:host ::ng-deep {
  font-size:18px;
}
这种方式试试

**Comment by lomo1** [comment]
@dknfeiov thx, 我试了下，在单个组件的css里是可以的，但是我想调整整个body上的。我试了在`style.css`里加或者在`index.html`内敛都不行。又不想在每个组件的样式文件里加一遍，感觉挺繁琐的。

**Comment by dknfeiov** [comment]
@lomo1  
在style.scss 中定义mixin
在其他组件样式文件import ，稍微没那么繁琐
zorro 的样式，有时候是比较让人头疼的
