### ISSUE TITLE
nz-radio初始化是无法默认选中

### ISSUE THREAD

**Issue by ZeyZhang** [NG-ZORRO/ng-zorro-antd#480]
如图，选中之后确认，再次打开，currentGroupId是有值，但是所有radio是未选中的状态，请问是我的方式不对?

![image](https://user-images.githubusercontent.com/20785848/31992472-04eb07c2-b9ad-11e7-8be1-f35418dcfff5.png)

**Comment by vthinkxie** [comment]
can you provide an online demo here http://plnkr.co/edit/tpl:sKWy62

**Comment by ZeyZhang** [comment]
ok，please check demo。

**Comment by HsuanXyz** [comment]
Hi, @ZeyZhang you need to save [it](http://plnkr.co/edit/tpl:sKWy62) ,and get the only url .

**Comment by laborchu** [comment]
当radio的数据源需要异步加载获取的时候(比如数据通过服务器获取)，默认值设置失效，因为nz-radio-group在生命周期钩子中只会在ngAfterContentInit这个方法里面去设置默认值，当前我是通过执行updateValue方法来手动设置，希望能支持异步加载设置默认值

**Comment by ZeyZhang** [comment]
能否看一下你的代码

**Comment by laborchu** [comment]
- 模板代码

```
    <nz-radio-group #group ([ngModel])="option.value">
          <label nz-radio [nzValue]="item.value" *ngFor="let item of data">
            <span>{{item.label}}</span>
          </label>
    </nz-radio-group>
```
- 组件代码

```
data: Array<any>;
@ViewChild('group') group:NzRadioGroupComponent;
//发起异步请求获取数据
this.option.dataSource.getData({}).then((data: Array<any>) => {
      this.data = data;
      setTimeout(()=>{
        this.group._value = null;
        this.group.updateValue(this.option.value);        
      },10)
    });
```
