### ISSUE TITLE
骨架屏内部如果嵌套tab的话，tab默认第一个标签页不会被选中

### ISSUE THREAD

**Issue by michael2043** [NG-ZORRO/ng-zorro-antd#4802]
如题

![image](https://user-images.githubusercontent.com/4134458/74890705-ceb44100-53bf-11ea-8c9e-645b79f35aaa.png)
![image](https://user-images.githubusercontent.com/4134458/74890719-d8d63f80-53bf-11ea-9c4f-4a42e12982ea.png)
正常应该是
![image](https://user-images.githubusercontent.com/4134458/74913168-14dac600-53fb-11ea-8349-0c6d5c351579.png)

再现url
https://stackblitz.com/edit/ng-zorro-antd-start-vb7skq

**Comment by michael2043** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-vb7skq

**Comment by spt110** [comment]
我也遇到这个问题了

**Comment by wendellhu95** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/pull/4511 cc @NearZXH

**Comment by wenqi73** [comment]
Because the tabset does not display, so we can't get its width, a workaround is:
```html
<nz-tabset *ngIf="!loading">
...
```
