### ISSUE TITLE
Can not work correctly when add ng-zorro-antd to my project.

### ISSUE THREAD

**Issue by Fover23** [NG-ZORRO/ng-zorro-antd#4804]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-this-is-useless-url](https://stackblitz.com/edit/ng-zorro-antd-start-this-is-useless-url)

### Steps to reproduce
I use @angular/cli to create the new project and add antd to the project , when it try to install packages the script raise the error.

install commad :

```
ng add ng-zorro-antd
```

the error is :

```
Installing packages...× Install fail! Error: [ng-zorro-antd@^0.0.0-NOT-USED] Can't find package ng-zorro-antd@^0.0.0-NOT-USED
Error: [ng-zorro-antd@^0.0.0-NOT-USED] Can't find package ng-zorro-antd@^0.0.0-NOT-USED
    at resolve (C:\Users\xxx\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:79:11)
    at resolve.next (<anonymous>)
    at onFulfilled (C:\Users\xxx\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
npminstall version: 3.23.0
```

angular/cli version ：9.0.3

os system ：Windows 10

package manager :cnpm 6.1.0

node version: 12.7.0

### What is expected?
Add antd to my project correctly

### What is actually happening?
Install failure

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | firefox |

---
The stackblitz url is uesless...

**Comment by wendellhu95** [comment]
Please describe the commands you used and the npm registry you're using.

**Comment by Fover23** [comment]
Before I execute the commands I set the default package manager to cnpm

```
ng config -g cli.packageManager cnpm
```

```
ng new myProject
cd myProject
ng add ng-zorro-antd
```

The angular/cli info in my computer.
```
Angular CLI: 9.0.2
Node: 12.7.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.2
@angular-devkit/core         9.0.2
@angular-devkit/schematics   9.0.2
@schematics/angular          9.0.2
@schematics/update           0.900.2
rxjs                         6.5.3
```

**Comment by vthinkxie** [comment]
cnpm won't work with @angular/cli, plz use npm or yarn
