### ISSUE TITLE
bug(dropdown-menu): Can't bind to 'nzDisabled' since it isn't a known property of 'nz-dropdown-menu'

### ISSUE THREAD

**Issue by dylanvdmerwe** [NG-ZORRO/ng-zorro-antd#4808]
### Reproduction link
[https://stackblitz.com/edit/angular-mccuuw](https://stackblitz.com/edit/angular-mccuuw)

### Steps to reproduce
Add `nzDisabled` to an `<nz-dropdown-menu>` item and Angular will not compile.

### What is expected?
The ability to disable the dropdown-menu.

### What is actually happening?
According to the [API ](https://ng.ant.design/components/dropdown/en#api)you should be able to disable the `nz-dropdown-menu` component.

The control should be able to enter a disabled state.

```
ERROR in Can't bind to 'nzDisabled' since it isn't a known property of 'nz-dropdown-menu'.
1. If 'nz-dropdown-menu' is an Angular component and it has 'nzDisabled' input, then verify that it is part of this module.
2. If 'nz-dropdown-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("mName}}
              </button>
              <nz-dropdown-menu #paymentTermMenu="nzDropdownMenu" [ERROR ->][nzDisabled]='loading'>
                <ul nz-menu nzSelectable clas")
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
nzDisabled is a property of nz-menu or nz-dropdown not the nz-dropdown-menu
