### ISSUE TITLE
nz-select没有嵌套在form中时宽度错误

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#481]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>
nz-select没有放在form中时宽度不是100%

http://plnkr.co/edit/4s6u5C8Z19fNfCUcg6lA?p=preview

顺带问一下，最近几周都没什么给力更新是什么情况呢 (｡◕ˇ∀ˇ◕)

**Comment by vthinkxie** [comment]
you can add style to nz-select
