### ISSUE TITLE
Transfer穿梭框

### ISSUE THREAD

**Issue by koryoII** [NG-ZORRO/ng-zorro-antd#4811]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start111111111111111111111](https://stackblitz.com/edit/ng-zorro-antd-start111111111111111111111)

### Steps to reproduce
ng.ant.design/components/transfer/zh使用 Table 组件作为自定义渲染列表。穿梭框倒数第二个案例，自定义表格，打开showsearch开关会持续吃内存，直到内存耗尽引起网页奔溃，原因是因为控件会不断的调用component.ts的convertItems方法。

### What is expected?
期望结果是有变更才调用convertItems方法

### What is actually happening?
实际结果是控件不断调用convertItems导致硬件内存耗尽。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome 版本 79.0.3945.130（正式版本） （64 位） |

---
在业务中使用是碰到，如果可以请尽快完善，如果已完善请邮件：356081822@qq.com,重现链接官方文档就可以看传来，shift esc调出chrome任务管理器，肉眼可以看到它不断在涨。

**Comment by koryoII** [comment]
可以处理吗？

**Comment by xuewlw** [comment]
请问 这个问题解决了吗

**Comment by vthinkxie** [comment]
cc @Ricbet

**Comment by hsuanxyz** [comment]
close via #4670
