### ISSUE TITLE
nz-select without clear the Input

### ISSUE THREAD

**Issue by dertuerke** [NG-ZORRO/ng-zorro-antd#4818]
## What problem does this feature solve?
Hi, is there a setting for nz-select, that if no result is found, the input is still retained?

Some kind of "select" and "input" combination.
## What does the proposed API look like?
not specified :S

**Comment by vthinkxie** [comment]
any reason not using the auto-complete component?

**Comment by dertuerke** [comment]
@vthinkxie haha dont see it. Thx for the help 💋
