### ISSUE TITLE
nz-submenu incomplete display

### ISSUE THREAD

**Issue by MarcusMjk** [NG-ZORRO/ng-zorro-antd#4821]
### Reproduction link
[https://stackblitz.com/edit/angular-rxxezh](https://stackblitz.com/edit/angular-rxxezh)

### Steps to reproduce
Move your mouse to the 'there' menu

### What is expected?
The first option of the sub-menu is completely displayed

### What is actually happening?
Incomplete display of the first option in the sub-menu

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Google   Version 80.0.3987.116 (Official Build) (64-bit) |

**Comment by MarcusMjk** [comment]
Hi Vthinkxie, could you help me?

**Comment by micrologic** [comment]
when nzMode='horizontal' is displayed vertical，why?

**Comment by vthinkxie** [comment]
duplicated #4743
