### ISSUE TITLE
Angular 9 compatibility

### ISSUE THREAD

**Issue by taksumaki** [NG-ZORRO/ng-zorro-antd#4822]
## What problem does this feature solve?
Just installed and I want to use Ant Design, I have not expired yet but I came up with many warnings that the necessary dependency has not been found, this because Angular was updated to its version 9 and I see that the current version of Ant Design has not It is compatible so I ask if one day it will be compatible.
## What does the proposed API look like?
Nothing I can add.

**Comment by vthinkxie** [comment]
plz track https://github.com/NG-ZORRO/ng-zorro-antd/issues/4634
