### ISSUE TITLE
Modal showing position is not correct 

### ISSUE THREAD

**Issue by dothnguyen** [NG-ZORRO/ng-zorro-antd#4827]
### Reproduction link
[https://angular-cvxego.stackblitz.io/](https://angular-cvxego.stackblitz.io/)

### Steps to reproduce
Click on the edit icon on the row.

### What is expected?
Modal should be animated from the right side to its expected position

### What is actually happening?
Modal is animated from the left, to the right side then move back a little bit to the left. This makes the showing animation not smooth.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

**Comment by orzyyyy** [comment]
I'm not sure whether it is a bug, but this [basic demo](https://ng.ant.design/components/modal/en#components-modal-demo-basic), just change <button> to <a>, and then Modal will animate from the center, not from the <a>.

![深度录屏_选择区域_20200331093526](https://user-images.githubusercontent.com/24520193/77977756-1faa4400-7333-11ea-852f-e3115e43c9e1.gif)

![深度录屏_选择区域_20200331093600](https://user-images.githubusercontent.com/24520193/77977789-2afd6f80-7333-11ea-9cdf-58b0979a20f0.gif)

**Comment by hsuanxyz** [comment]
@dothnguyen The issue has fixed in `v9.x`.
@orzyyyy `<a>` tag must have `href` or `tabindex` attribute can get the position because the `Modal` need gets the position of the last `document.activeElement`.
