### ISSUE TITLE
suggestion： About the  tinymce（editor）

### ISSUE THREAD

**Issue by yunClouds** [NG-ZORRO/ng-zorro-antd#483]
首先感谢NG-ZORRO：
提个需求/建议：相信大家在实际应用中很多场景需要用到 富文本编辑器 ，所以建议增加此相关功能。
谢谢

**Comment by vthinkxie** [comment]
this library will only support components designed by ant design
you can find all components supported here https://ant.design/docs/react/introduce-cn

**Comment by HuiHenry** [comment]
请问解决了吗？用的哪个富文本编辑器

**Comment by 232650413** [comment]
我最后使用了TINYMCE富文本编辑器，还好，就是那个缓存快照存不了好像，反正我没弄对
http://www.deathghost.cn/article/angular/31
