### ISSUE TITLE
textarea display validation error in IE11

### ISSUE THREAD

**Issue by ClouderBai** [NG-ZORRO/ng-zorro-antd#4831]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-start?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
 stackblitz cannot work in IE11.  textarea of no-touched display validation error first load in IE11.

### What is expected?
An no-touched textarea doesn't display validation error first load in IE11.

### What is actually happening?
An no-touched textarea display validation error first load in IE11.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | IE11 |

**Comment by vthinkxie** [comment]
plz track https://github.com/angular/angular/issues/14440
