### ISSUE TITLE
Ng-zorro-select error when using with Angular Dynamic Form 

### ISSUE THREAD

**Issue by yv88john** [NG-ZORRO/ng-zorro-antd#4832]
### Reproduction link
[https://github.com/yv88john/ngzorro_select.git](https://github.com/yv88john/ngzorro_select.git)

### Steps to reproduce
1. git clone https://github.com/yv88john/ngzorro_select.git
2. npm install
3. ng serve --port=4200 --open
4. Since the multiple-select is dynamically generated by using another multiple-select, choose country on attribute criteria ( https://imgur.com/AOelzdm )
5. Select option from country ( https://imgur.com/1x1K5qT )

### What is expected?
After selecting country, the selectionbox can immediately reflect the selected country on the input box. 
On the first time opening the country selectionbox, only single selection is allow. 
On deleting country, the selectionbox cannot immediately reflect the deleted country on input box.

### What is actually happening?
After selecting country, the selectionbox doesn't change. Only when we focus-out and focus-in again, the box would change.
On the first time opening the country selectionbox, Multiple-select is allow.
On deleting country, the selectionbox can immediately reflect the deleted country on input box.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Version 80.0.3987.122 (Official Build) (64-bit) |

---
https://imgur.com/sLwuJrL
Please find the error message. I guess it just need a try-catch block in the red highlighted area as the cdr.markForCheck() is not trigger due to exception. So changes are not reflected.

**Comment by vthinkxie** [comment]
Hi @yv88john 
could you provde a more clear repro repo, stackblitz is the best, there are too many other third libs in your repro repo now.
https://github.com/yv88john/ngzorro_select/blob/c00f739289e609b46bce0d0d069ad77af8a56d26/ui-framework/package.json#L26
