### ISSUE TITLE
关于 sharepoint framework 的支持

### ISSUE THREAD

**Issue by YijieWang-22** [NG-ZORRO/ng-zorro-antd#4836]
### Reproduction link
[https://stackblitz.com/edit/typescript-2lazs6](https://stackblitz.com/edit/typescript-2lazs6)

### Steps to reproduce
1. 安装 NodeJS LTS 版本 10（未安装最新版本）
https://nodejs.org/en/
2. 运行以下命令
   npm install -g gulp
3. 将上载到 https://stackblitz.com/edit/typescript-2lazs6 的项目下载到电脑
4. 在 sck-sundoc-document, sck-sundoc-document-spfx, sck-sundoc-document-svc的各目录中运行以下命令
   npm install
5. 在 sck-sundoc-document-svc目录中运行以下命令
   npm run build
6. 在 sck-sundoc-document目录中运行以下命令
   npm run bundle
7. 在 sck-sundoc-document-spfx目录中运行以下命令
   gulp trust-dev-cert
8. 在 sck-sundoc-document-spfx目录中运行以下命令
   gulp bundle
   gulp serve --nobrowse
9. 启动 Internet Explorer 11 浏览器 （ie11）
   在 10.ie11 上，访问以下 URL。
   https://gotodev.sharepoint.com/sites/devgoto/_layouts/15/workbench.aspx
   输入以下用户帐户/密码
   yunhe.zhao@gotodev.onmicrosoft.com
   Avanade2@
11.访问以下 URL
   执行【「To use SharePoint Workbench to preview and test your web part」】的 1
   要放置的 Web 部件名称为 SckSundocCommon
11. 单击显示的切换选项
　※可以确认，这不是正常的动作。

### What is expected?
安装的Web部件正常运行

### What is actually happening?
单击显示的切换选项后没有正常的运行
 Off不变On
 Tab1,2,3也不变

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Internet Explorer 11  |

**Comment by vthinkxie** [comment]
Hi @YijieWang-22 请不要在公共信息中暴露密码，尽快修改
组件库获取不到当前的运行容器，与浏览器之外的运行容器不存在联系
