### ISSUE TITLE
Make the menu scrollable

### ISSUE THREAD

**Issue by SebastianStehle** [NG-ZORRO/ng-zorro-antd#4837]
## What problem does this feature solve?
Hi, I am evaluating ng-zorro and it looks awesome,  but i have a few menus with a lot of items. Is there a way to make them scrollable?
## What does the proposed API look like?
There is no need a for an API change

Example screen with shows the issue:

![image](https://user-images.githubusercontent.com/1236435/75884629-7cded280-5e25-11ea-85d8-4bfccbdbbc42.png)

**Comment by vthinkxie** [comment]
add class to the ul, it should work

**Comment by SebastianStehle** [comment]
What do you mean with classname? Any classname?

**Comment by SebastianStehle** [comment]
I have already tried this:

```


.submenu {
    overflow-y: auto;
    background: red;
}
```

(therefore the red color)

**Comment by vthinkxie** [comment]
overflow needs to work with at least a height value
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

**Comment by SebastianStehle** [comment]
I know, but I do not want to give the menu a fixed height, because I do not know the offset from the top nor the height the of the window.

Therefore the feature request to solve it with inside the component. The component should calculate if it overflows the window and then set the height accordingly and add overflow-y: auto or so.

**Comment by ahmdelgmil** [comment]
Remove/Comment `height` in this classes  `.inner-content` , `.app-layout` inside `\src\app\app.component.css`

.app-layout {
  /* height: 100vh; */
}

.inner-content {
  padding: 24px;
  background: #fff;
  /* height: 100%; */
}
