### ISSUE TITLE
Making the search bar in the Ant js website available throughout all the page

### ISSUE THREAD

**Issue by SidaouiBilel** [NG-ZORRO/ng-zorro-antd#4838]
## What problem does this feature solve?
Having to manually scroll up and search for the search box, type the new search and click enter.
## What does the proposed API look like?
This is not an API, this is just a change request in the website where you can make the header sticky in the top, or like when I scroll the mouse to the top of the screen, the header shows up and I can search easily.

**Comment by vthinkxie** [comment]
type 's' will auto scroll to the top and focus on the search box
