### ISSUE TITLE
这是一个KPI项目吗

### ISSUE THREAD

**Issue by ridecrafty** [NG-ZORRO/ng-zorro-antd#484]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

为什么每次版本变化更新这么少. 阿里团队有在用这个项目吗.
为什么没有感受到社区的氛围

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ridecrafty** [comment]
向我展示有力的证据, 我让我的团队信服能使用这些组件.

**Comment by vthinkxie** [comment]
it is an open source project, not an outsourcing project, you can use it or not as you wish.
