### ISSUE TITLE
[nz-switch] The default false value will cause flash

### ISSUE THREAD

**Issue by bbbbx** [NG-ZORRO/ng-zorro-antd#4840]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-2i21wg](https://stackblitz.com/edit/ng-zorro-antd-start-2i21wg)

### Steps to reproduce
click the second switch component

### What is expected?
the first switch won't flash

### What is actually happening?
the first switch flashes

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 80.0.3987.122 （64 位） |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-bnupxd?file=src/app/app.component.ts
you need to use trackBy to avoid re-render
