### ISSUE TITLE
Long text extends beyond the NzSelectComponent width on search

### ISSUE THREAD

**Issue by Xambey** [NG-ZORRO/ng-zorro-antd#4842]
### Reproduction link
[https://stackblitz.com/edit/angular-c1ku4m](https://stackblitz.com/edit/angular-c1ku4m)

### Steps to reproduce
1) write in search box text longer than the width of the select component

### What is expected?
The text on the left is hidden, the last entered characters are displayed on the right

### What is actually happening?
Long text extends beyond the component's width

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Version 80.0.3987.87 (Official Build) (64-bit) |

**Comment by vthinkxie** [comment]
Hi @Xambey 
this bug has been fixed in 9.0.0-beta.3 now
https://stackblitz.com/edit/angular-c1ku4m-gcov4a?file=src/app/app.component.ts
will release 9.0.0 version soon.
