### ISSUE TITLE
date-fns and tinycolor not treeshaken

### ISSUE THREAD

**Issue by banjankri** [NG-ZORRO/ng-zorro-antd#4844]
I wouldn't expect those 3rd party libraries to be present in my final bundle. I am using ng-zorro-antd@8.5.2 and the `--prod` flag. Please see the used ng-zorro modules and produced result bundle.

Angular CLI: 8.3.25
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cdk                      8.2.3
@angular/cli                      8.3.25
@angular/pwa                      0.900.3
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

![image](https://user-images.githubusercontent.com/2622286/76068747-0a3f3580-5f92-11ea-8503-ada57eb372a6.png)

**Comment by vthinkxie** [comment]
this is our doc site's sourcemap, which built with ng-zorro-antd@8.5.2
![](https://user-images.githubusercontent.com/1506722/69319188-aeb69980-0c79-11ea-962f-052c07b0adcc.png)
we can not help you without repro link.
