### ISSUE TITLE
date-fns and tinycolor not treeshaken

### ISSUE THREAD

**Issue by banjankri** [NG-ZORRO/ng-zorro-antd#4845]
### Reproduction link
[https://stackblitz.com/ng-zorro-antd-start](https://stackblitz.com/ng-zorro-antd-start)

### Steps to reproduce
1) Create empty app with ng new
2) add NgZorroAntModule
3) Build the app with --prod switch

### What is expected?
The unused code is treeshaken propertly

### What is actually happening?
date-fns and tinycolor present in the final bundle

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | all |

---
I wouldn't expect those 3rd party libraries to be present in my final bundle. I am using ng-zorro-antd@8.5.2 and the --prod flag. Please see the used ng-zorro modules and produced result bundle.

Angular CLI: 8.3.25
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package Version
@angular-devkit/architect 0.803.25
@angular-devkit/build-angular 0.803.25
@angular-devkit/build-optimizer 0.803.25
@angular-devkit/build-webpack 0.803.25
@angular-devkit/core 8.3.25
@angular-devkit/schematics 8.3.25
@angular/cdk 8.2.3
@angular/cli 8.3.25
@angular/pwa 0.900.3
@ngtools/webpack 8.3.25
@schematics/angular 8.3.25
@schematics/update 0.803.25
rxjs 6.4.0
typescript 3.5.3
webpack 4.39.2

![image](https://user-images.githubusercontent.com/2622286/76070239-791d8e00-5f94-11ea-9ad8-85978799656f.png)

**Comment by banjankri** [comment]
Reproduction stackblitz repo: https://stackblitz.com/edit/ng-zorro-antd-start-zp5xmr . Just build with the `--prod` flag a basic app like that and you'll see the 3rd parties included in the bundles.

**Comment by wenqi73** [comment]
`date-fns` has treeShaked; `tinycolor` is required by `@ant-design/colors-angular` which contains inner icons.
Here is the analysis of 9.3.0 which only import `NzButtonModule`:
![image](https://user-images.githubusercontent.com/23337087/93857055-93c71280-fcec-11ea-9e55-d9eb101b1155.png)
