### ISSUE TITLE
nzMaxTagPlaceholder is missing a class and has too much whitespace on the right side

### ISSUE THREAD

**Issue by oestrogen** [NG-ZORRO/ng-zorro-antd#4848]
### Reproduction link
[https://stackblitz.com/edit/angular-9xbvbe](https://stackblitz.com/edit/angular-9xbvbe)

### Steps to reproduce
Select more than nzMaxTagCount items in a nz-select with nzMode="multiple".

### What is expected?
The overflow/max tag (populated by nzMaxTagPlaceholder) should have the same amount of padding on both sides.

### What is actually happening?
The overflow/max tag (populated by nzMaxTagPlaceholder) should have more padding on the right side.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Any |

---
This is a discrepancy from upstream Ant and is caused by not setting the class `ant-select-selection__choice__disabled` on the max tag, thus leaving room for the non-existing close X.

![image](https://user-images.githubusercontent.com/351057/76097230-a33c7380-5fc7-11ea-8911-06f8eed01317.png)

**Comment by oestrogen** [comment]
To clarify, manually adding `ant-select-selection__choice__disabled` to the tag list element fixes the problem:
![image](https://user-images.githubusercontent.com/351057/76098933-a127e400-5fca-11ea-8a60-fefee5511ba2.png)

**Comment by oestrogen** [comment]
I took a quick look, but I think the solution is a bit outside of what I can handle with my skill level. @krokofant? 😅

**Comment by krokofant** [comment]
@oestrogen I'll take a look

**Comment by krokofant** [comment]
@oestrogen This issue does not seem to exist in Ng Zorro 9 / master

**Comment by oestrogen** [comment]
In NG-Zorro 9 the missing class is applied, but now there is to much whitespace on the left side instead. 😅

![image](https://user-images.githubusercontent.com/351057/76354840-81b6f100-6313-11ea-8d42-e6874b50da1e.png)

I will look at upstream and update this issue tomorrow.

**Comment by hsuanxyz** [comment]
@vthinkxie We lost the `ant-select-selection-item-content` classname when customize `contentTemplateOutlet` for `<nz-select-item>`

```diff
<span class="ant-select-selection-item">
+  <span class="ant-select-selection-item-content"> + 1 </span>
-    + 1   
</span>
```

**Comment by vthinkxie** [comment]
@hsuanxyz it works as expected, the classname would keep if user won't pass nzMaxTagPlaceholder

**Comment by vthinkxie** [comment]
@oestrogen @hsuanxyz 
it works as expected in v9, since you have already provided 'nzMaxTagPlaceholder' template, it would overwrite the ant-select-selection-item-content
