### ISSUE TITLE
table组件动态加载下一页数据问题

### ISSUE THREAD

**Issue by okuc** [NG-ZORRO/ng-zorro-antd#485]
在html中，使用 (nzPageIndexChange)="queryData()"来获取下一页数据，[(nzPageIndex)]="_pageIndex"绑定页数。
但是当程序运行后，默认显示第一页。点击第二页按扭时，在queryData()方法中发现_pageIndex仍然为1，再继续点击第三页按扭，发现_pageIndex成了2，想问下这个问题 怎么解决？
是不是我的使用方式不对？
谢谢。

**Comment by vthinkxie** [comment]
[(nzPageIndex)]="_pageIndex" (nzPageIndexChange)="queryData()" place in right order.

**Comment by okuc** [comment]
完整的代码如下：

`  <nz-table #nzTable [nzAjaxData]="_dataSet" [nzTotal]="_recordsTotal"  (nzPageIndexChange)="queryData()" (nzPageSizeChange)="queryData()" [nzShowTotal]=true [(nzPageSize)]="_pageSize" [(nzPageIndex)]="_pageIndex" [nzShowSizeChanger]="true">
    <thead nz-thead>
      <tr>
        <th nz-th><span>编号</span></th>
        <th nz-th><span>姓名</span></th>
        <th nz-th><span>电话</span></th>
        <th nz-th><span>地址</span></th>
        <th nz-th><span>创建时间</span></th>
      </tr>
    </thead>
    <tbody nz-tbody>
      <tr nz-tbody-tr *ngFor="let data of nzTable.data">
        <td nz-td>
          <a>{{data.id}}</a>
        </td>
        <td nz-td>{{data.name}}</td>
        <td nz-td>{{data.telephone}}</td>
        <td nz-td>{{data.address}}</td>
        <td nz-td>{{data.createTime}}</td>
      </tr>
    </tbody>
  </nz-table>`

**Comment by vthinkxie** [comment]
try this
```
<nz-table #nzTable [nzAjaxData]="_dataSet" [nzTotal]="_recordsTotal" (nzPageIndexChange)="queryData()" [(nzPageIndex)]="_pageIndex"  (nzPageSizeChange)="queryData()" [nzShowTotal]=true [(nzPageSize)]="_pageSize" [nzShowSizeChanger]="true"> <thead nz-thead> <tr> <th nz-th><span>编号</span></th> <th nz-th><span>姓名</span></th> <th nz-th><span>电话</span></th> <th nz-th><span>地址</span></th> <th nz-th><span>创建时间</span></th> </tr> </thead> <tbody nz-tbody> <tr nz-tbody-tr *ngFor="let data of nzTable.data"> <td nz-td> <a>{{data.id}}</a> </td> <td nz-td>{{data.name}}</td> <td nz-td>{{data.telephone}}</td> <td nz-td>{{data.address}}</td> <td nz-td>{{data.createTime}}</td> </tr> </tbody> </nz-table>
```

**Comment by vthinkxie** [comment]
try this
```html
<nz-table #nzTable
  [nzAjaxData]="_dataSet" 
  [nzTotal]="_recordsTotal"
  [nzShowTotal]="true"
  [(nzPageSize)]="_pageSize"
  [(nzPageIndex)]="_pageIndex"
  (nzPageIndexChange)="queryData()"
  (nzPageSizeChange)="queryData()"
  [nzShowSizeChanger]="true">
  <thead nz-thead>
    <tr>
      <th nz-th><span>编号</span></th>
      <th nz-th><span>姓名</span></th>
      <th nz-th><span>电话</span></th>
      <th nz-th><span>地址</span></th>
      <th nz-th><span>创建时间</span></th>
    </tr>
  </thead>
  <tbody nz-tbody>
    <tr nz-tbody-tr *ngFor="let data of nzTable.data">
      <td nz-td>
        <a>{{data.id}}</a>
      </td>
      <td nz-td>{{data.name}}</td>
      <td nz-td>{{data.telephone}}</td>
      <td nz-td>{{data.address}}</td>
      <td nz-td>{{data.createTime}}</td>
    </tr>
  </tbody>
</nz-table>
```

**Comment by okuc** [comment]
可以了，能正常工作了，谢谢。能说一下为什么么？这几个参数是有顺序的？

**Comment by vthinkxie** [comment]
@okuc angular design, you can find the reason in angular repo.

**Comment by LinBoLen** [comment]
in my short-sighted opinion:
pageIndex and pageSize should be set as a tuple. the `@input` should be like `@Input forPage: {pageIndex: number, pageSize: number} | [pageIndex: number, pageSize: number].

and the primary @input should be pageOffset, pageLimit.

**Comment by xpioneer** [comment]
在官方例子中：
`
table:
      [nzAjaxData]="_dataSet"
      [nzShowSizeChanger]="true"
      [nzLoading]="_loading"
      [nzTotal]="_total"
      [(nzPageIndex)]="_current"
      (nzPageIndexChange)="refreshData()"
      [(nzPageSize)]="_pageSize"
      (nzPageSizeChange)="refreshData(true)"
// some code....
refreshData(reset = false) {
    if (reset) {
      this._current = 1; //这一句
    }
    this._loading = true;
    const selectedGender = this._filterGender.filter(item => item.value).map(item => item.name);
    this._randomUser.getUsers(this._current, this._pageSize, 'name', this._sortValue, selectedGender).subscribe((data: any) => {
      this._loading = false;
      this._total = 200;
      this._dataSet = data.results;
    })
  };
`
[(nzPageIndex)]双向绑定，在改变"this._current = 1;"的时候，不会触发refreshData方法再次执行吗？？
我的代码中有连续发送了两次请求。
如图，
ts代码：
![image](https://user-images.githubusercontent.com/30486161/33028429-e83c457e-ce50-11e7-946c-a41cc5db20e0.png)
html代码：
![image](https://user-images.githubusercontent.com/30486161/33028347-ad0c271c-ce50-11e7-85e8-0fb755da8833.png)
网络请求：
![image](https://user-images.githubusercontent.com/30486161/33028380-cb21a8da-ce50-11e7-92c1-27c7390df97c.png)

**Comment by sunscheung** [comment]
```
<nz-table #nzTable [nzAjaxData]="taskFlowList" 
        [nzTotal]="total" [nzShowTotal]="true" 
        [nzPageSize]="pageSize" 
        [nzPageIndex]="pageNum" 
        (nzPageIndexChange)="search()">
```
after the event of nzPageIndexChange ，   the pageNum is still  1
