### ISSUE TITLE
Please give more space to code

### ISSUE THREAD

**Issue by XuanBeng** [NG-ZORRO/ng-zorro-antd#4851]
## What problem does this feature solve?
More convenient when watching code

## What does the proposed API look like?
I hope there is a larger space to display the code, which can display the code completely without sliding up, down, left and right. It can learn the ng-zorro-mobile

**Comment by Mr-Eve** [comment]
Actually, I prefer the doc style of zorro-pc. Maybe develop team can provider 2  doc styles.

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
