### ISSUE TITLE
Clearing <nz-input-number> value sets FormControl value to empty string

### ISSUE THREAD

**Issue by aloene** [NG-ZORRO/ng-zorro-antd#4862]
### Reproduction link
[https://ng-zorro-antd-start-cpfpdy.stackblitz.io](https://ng-zorro-antd-start-cpfpdy.stackblitz.io)

### Steps to reproduce
1. Enter value into nz-input-number control (either by hand or using  /- buttons)
2. Clear value (using backspace)
3. The related FormControl value is automatically set to empty string (instead of null).

### What is expected?
The nz-input-number related FormControl value should be set to null after erasing input.
Please note that same steps on native input (input type="number") lead to null. (It seems correct to me)

### What is actually happening?
The nz-input-number related FormControl value is incorrectly set to empty string when erasing input content.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 80 |

---
If this behavior is expected, could you explain why or how to workaround it ?

**Comment by aloene** [comment]
For nos, I have worked around the issue using a custom directive setting formcontrol value to null when set to empty string.

**Comment by sebcam** [comment]
+1

**Comment by sasyesp03** [comment]
still present

**Comment by HyperLife1119** [comment]
Please use the newly designed input-number component in v19 :)
