### ISSUE TITLE
As for the menu component of NG Zorro, I have a problem in order to implement the dynamic menu

### ISSUE THREAD

**Issue by z1429170900** [NG-ZORRO/ng-zorro-antd#4866]
### Reproduction link
[https://stackblitz.com/edit/angular-4tlu6n](https://stackblitz.com/edit/angular-4tlu6n)

### Steps to reproduce
<ul nz-menu nzMode="inline" nzTheme="dark" [nzInlineCollapsed]="isCollapsed">
        <div class="logo flex">
            <img src="assets/image/logo.png" alt="">
        </div>

        <ng-template #nzMenuItem let-name="name" let-icon="icon" let-url="url" let-selected="selected">
            <li nz-menu-item nz-tooltip nzPlacement="right" [nzSelected]="selected">
                <a [routerLink]="[url]">
                    <i nz-icon [nzType]="icon"></i>
                    <span>{{ name }}</span>
                </a>
            </li>
        </ng-template>

        <ng-template #nzSubmenu let-name="name" let-icon="icon" let-url="url" let-children="children" let-open="isOpen">
            <li nz-submenu [nzTitle]="name" [nzIcon]="icon" [nzOpen]="open">
                <ul>
                    <ng-container *ngFor="let item of children">
                        <ng-container *ngTemplateOutlet="item.hasNext ? nzSubmenu : nzMenuItem; context: item"></ng-container>
                    </ng-container>
                </ul>
            </li>
        </ng-template>
        
        <ng-container *ngFor="let item of sideMenuData">
            <ng-container *ngTemplateOutlet="item.hasNext ? nzSubmenu : nzMenuItem; context: item"></ng-container>
        </ng-container>

        
        
    </ul>

### What is expected?
What I want to achieve is dynamic menu, because this menu is affected by data, different data shows different menus

### What is actually happening?
My dynamic menu has been implemented. There is no problem with the function, but there is a little reverie in the style. Through my implementation method, the submenu is no longer adapted to padding left, and the submenu is the same 24px, which makes the menu look stiff

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Google Chrome版本 80.0.3987.132 |

---
It's a wrong address, you can read http://www.faker.site/basiclevel/admin. My implementation method: recursively concatenate components through ng template and * ngtemplateoutlet. I predict that the margin adaptation method of components will be loaded before I have finished rendering, but I don't know if there is a solution.

**Comment by vthinkxie** [comment]
it won't work because of https://github.com/angular/angular/issues/14842
how many levels are there in your menu? I don't think recursively is necessary since the menu's style will be broken if there are too many levels
