### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by LinBoLen** [NG-ZORRO/ng-zorro-antd#487]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

lots of extra detect change.

## Expected behavior

some of event should runoutsideofangular

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
I think `runOutsideAngular` it's not the best choice for detect change, maybe you can consider using `ChangeDetectorRef` that friendly to Angular5.

**reference:**

+ [feat(core): support for bootstrap with custom zone](https://github.com/angular/angular/commit/344a5ca5452bc01a1e5ff8f04aa7a283ce4134cf)
+ [【SNF-A】Angular 增加不使用 Zone.js 的支持](https://zhuanlan.zhihu.com/p/29577461)

**Comment by LinBoLen** [comment]
if not use runOutsideAngular, then should use dectectchange.onpush in component and detectchangeRef.markForcheck.

my optinion is that
zone.js is an async hook. if without zone.js, then must manual detectchange in some way.
