### ISSUE TITLE
main-es2015.acca8c05bb7aa8144e3f.js:1 ERROR TypeError: this._value.setHours is not a function

### ISSUE THREAD

**Issue by BrsJsk** [NG-ZORRO/ng-zorro-antd#4871]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-78vvuu](https://stackblitz.com/edit/ng-zorro-antd-start-78vvuu)

### Steps to reproduce
- Add a time picker
- Model for time picker is set
- Value is date but type is string

### What is expected?
Its expected to still work even date is passed as a string. This can create issues when dates are returned from API call as strings and not formatted to date beforehand, currently we need to format it always as date and then pass it to the component.

Time picker should IMO check if it is a string, and convert it to a date so it can use setHours methods etc

### What is actually happening?
Time picker component is not converting it to a Date object and therefore throwing an error. 

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | 80.0.3987.132 Chrome |

---
Ran into this bag when I was passing date value to the time picker. 
After a API call, I passed date to time picker but it threw an error as API returned it as a string.

**Comment by BrsJsk** [comment]
Will open a pull request for this.

**Comment by BrsJsk** [comment]
Created: https://github.com/NG-ZORRO/ng-zorro-antd/pull/4872

**Comment by dylanvdmerwe** [comment]
Is this similar? https://github.com/NG-ZORRO/ng-zorro-antd/issues/4777

**Comment by BrsJsk** [comment]
Identical issue.
Did not see that issue.
