### ISSUE TITLE
angular cli 打包后无法访问

### ISSUE THREAD

**Issue by zy8008** [NG-ZORRO/ng-zorro-antd#4874]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
1，使用angular cli 命令：ng build --prod --build 进行打包
2，打包后部署到IIS
3，使用浏览器访问

### What is expected?
能正常访问

### What is actually happening?
显示空白页，并报以下错误：
main-es2015.8868430a87af9b5f17d1.js:1 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(h)[e -> e]: 
  StaticInjectorError(Platform: core)[e -> e]: 
    NullInjectorError: No provider for e!
NullInjectorError: StaticInjectorError(h)[e -> e]: 
  StaticInjectorError(Platform: core)[e -> e]: 
    NullInjectorError: No provider for e!

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome 79.0.3945.130 |

**Comment by BrsJsk** [comment]
Run in local production but with debugging mode. That way you will see correct error message.
Most likely it will be a 'missing provider' error and you will need to update certain packages.

**Comment by zy8008** [comment]
thanks @BrsJsk ！
I have found the reason，It is caused by a low version service

**Comment by fonshin** [comment]
> thanks @BrsJsk ！
> I have found the reason，It is caused by a low version service
what's the "a low version service"? thx
