### ISSUE TITLE
头像组件在下拉菜单中和弹出框中会出现文字无法居中的问题

### ISSUE THREAD

**Issue by misteraries** [NG-ZORRO/ng-zorro-antd#4879]
### Reproduction link
[https://stackblitz.com/edit/angular-x2j4m9?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-x2j4m9?file=src/app/app.component.ts)

### Steps to reproduce
在下拉菜单中的下拉项加入头像组件，头像组件显示内容为文字

### What is expected?
文字居中

### What is actually happening?
文字没有居中，向右偏移

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | 谷歌 |

**Comment by hsuanxyz** [comment]
@misteraries avatar 需要动态计算缩放值，在 dropdown 实例化时还无法获取正确的计算值，暂时加上 `*ngIf` 使其实例化时机与 dropdown 打开一致。

```ts
@Component({
  template: `
    <a nz-dropdown [nzDropdownMenu]="menu" (nzVisibleChange)="visible = $event">
      Hover me
      <i nz-icon nzType="down"></i>
    </a>
    <nz-dropdown-menu #menu="nzDropdownMenu">
      <ul nz-menu nzSelectable *ngIf="visible">
        <li nz-menu-item>
          <nz-avatar nzText="张三" ></nz-avatar>
        </li>
      </ul>
    </nz-dropdown-menu>
  `
})
export class Component {
  visible = false;
}

```

**Comment by wendellhu95** [comment]
Ref #4451

**Comment by hsuanxyz** [comment]
duplicate #4660

**Comment by FuckDoctors** [comment]
> @misteraries avatar 需要动态计算缩放值，在 dropdown 实例化时还无法获取正确的计算值，暂时加上 `*ngIf` 使其实例化时机与 dropdown 打开一致。
> 
> ```ts
> @Component({
>   template: `
>     <a nz-dropdown [nzDropdownMenu]="menu" (nzVisibleChange)="visible = $event">
>       Hover me
>       <i nz-icon nzType="down"></i>
>     </a>
>     <nz-dropdown-menu #menu="nzDropdownMenu">
>       <ul nz-menu nzSelectable *ngIf="visible">
>         <li nz-menu-item>
>           <nz-avatar nzText="张三" ></nz-avatar>
>         </li>
>       </ul>
>     </nz-dropdown-menu>
>   `
> })
> export class Component {
>   visible = false;
> }
> ```

感谢，解决了~
