### ISSUE TITLE
layout  侧边布局 white space on the top

### ISSUE THREAD

**Issue by tigercosmos** [NG-ZORRO/ng-zorro-antd#488]
There is a white space on the top. I think it is a bug.
![image](https://user-images.githubusercontent.com/18013815/32095738-be47d486-bb36-11e7-847f-dee141ffa1be.png)

**Comment by cipchk** [comment]
just `nz-header` setting a white background.

**Comment by tigercosmos** [comment]
OK, I see there is a header.
Shall we change its colour to let it clearer?

**Comment by vthinkxie** [comment]
it is just a demo, don't care about it too much.
