### ISSUE TITLE
nz-checkbox-wrapper 不支持  [formControlName] 这种响应表单的使用规范

### ISSUE THREAD

**Issue by shenjunjian** [NG-ZORRO/ng-zorro-antd#4883]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-mcpm7y](https://stackblitz.com/edit/ng-zorro-antd-start-mcpm7y)

### Steps to reproduce
<nz-checkbox-wrapper style="width: 100%;" [formControlName]="'sex'">  控制台提示： 
no value accessor for form control

### What is expected?
能像其它组件一样，用在响应表单里。

### What is actually happening?
报错。文档要求用nzOnChange事件，但它破坏响应表单的行为，以及无法让nz-form-control 支持  [nzErrorTip] 标签功能！

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome |

---
nz-checkbox-wrapper  能继承ControlValueAccessor   ，支持 [formControlName]的用法

**Comment by pek77** [comment]
@shenjunjian 
`			<nz-checkbox-wrapper style="width: 100%;">
				<div nz-row>
					<div nz-col nzSpan="4" >
						<label nz-checkbox [formControlName]="'sex1'" [nzValue]="1">球</label>
            <label nz-checkbox [formControlName]="'sex2'" [nzValue]="2">跑步</label>
            <label nz-checkbox [formControlName]="'sex3'" [nzValue]="3">游泳</label>
					</div>
				</div>
			</nz-checkbox-wrapper>`

在nz-checkbox标签里加

**Comment by xingqiwu55555** [comment]
遇到了相同的问题，有解决这个问题的吗？

**Comment by wangxw1995** [comment]
同一个世界，同一个问题

**Comment by wangxw1995** [comment]
> @shenjunjian
> ` <nz-checkbox-wrapper style="width: 100%;"> <div nz-row> <div nz-col nzSpan="4" > <label nz-checkbox [formControlName]="'sex1'" [nzValue]="1">球</label> <label nz-checkbox [formControlName]="'sex2'" [nzValue]="2">跑步</label> <label nz-checkbox [formControlName]="'sex3'" [nzValue]="3">游泳</label> </div> </div> </nz-checkbox-wrapper>`
> 
> 在nz-checkbox标签里加

这种好麻烦，想得到个已勾选的数组，还得遍历

**Comment by eileen823** [comment]
我也遇到同样的问题了，求问有没有好的解决方案

**Comment by xuhen** [comment]
please response to this issue
