### ISSUE TITLE
icon user exp improve

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#4886]
- [ ] use forChild to register icons to ng-zorro-antd submodules
- [ ] change NZ_CONFIG to the params of the forRoot(icons, config)

**Comment by wendellhu95** [comment]
I don't think it's a good idea to make properties of `NZ_CONFIG.icon` to be a parameter or `NzIconModule.forRoot`. Anyway, if users want to change the config at runtime, they still need to call `NzConfigService` or `NzIconService`. I am afraid we are introducing unnecessary complexity.

**Comment by vthinkxie** [comment]
forRoot is just a syntactic sugar IMO, since we have already provided the forChild function, it makes sense for the users to use the forRoot
https://angular.io/guide/singleton-services#the-forroot-pattern
if the user need to change the config, they still can use the NzConfigService or NzIconService.
but I believe most users won't need to change it at the runtime.

**Comment by wendellhu95** [comment]
Already implemented in #4711. I am closing this.
