### ISSUE TITLE
disabled attribute not working initially on dropdown button

### ISSUE THREAD

**Issue by patricknazar** [NG-ZORRO/ng-zorro-antd#4894]
### Reproduction link
[https://stackblitz.com/edit/angular-bwb1lc?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-bwb1lc?file=src/app/app.component.ts)

### Steps to reproduce
The example has two buttons, one normal, and one dropdown. The normal button is disabled initially which is correct, but the dropdown one isn't. An interval observable will change this value after 2 seconds to `disabled=false` then after another 2 seconds to `disabled=true`. The dropdown then is disabled correctly. One the process is done, clicking 'start again' will show the correct behaviour from the start.

### What is expected?
Both buttons are disable initially, then both enabled, then both disabled.

### What is actually happening?
Only the normal button is disabled initially. It fixes itself after.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 80.0.3987.132 |

---
Clearly there is some problem initing the component. I tried using `[nzDisabled]` and it actually fixed the problem, BUT It gives me compilation error `Can't bind to 'nzDisabled' since it isn't a known property of 'button'.`

**Comment by vthinkxie** [comment]
nzDisable is not the nz-button's input but the nz-dropdown's input
https://stackblitz.com/edit/angular-bwb1lc-uwhva7?file=src/app/app.component.ts

**Comment by patricknazar** [comment]
Ok thanks, that works for me :)
