### ISSUE TITLE
Function to change theme white to black dynamically

### ISSUE THREAD

**Issue by taksumaki** [NG-ZORRO/ng-zorro-antd#4914]
## What problem does this feature solve?
It would be great if you could dynamically change the theme from white to black from a button, something like you can in Angular Material. I haven't found a documentation that explains how to do it with Ant Design (or maybe I haven't looked hard enough) but if that feature isn't there, it would be great to implement it in the new version of Ant Design.

In summary, I would like if you could add a method class to be able to implement it in Angular applications and control that the client user of the app chooses between a black or white theme easily.
## What does the proposed API look like?
URL of how to explain how to do it in Angular Material, something like that would be great for Ant Design.
https://material.angular.io/guide/theming

**Comment by krokofant** [comment]
Take a look at this old issue. It could be done with with fairly small changes to the current ng-zorro.
https://github.com/NG-ZORRO/ng-zorro-antd/issues/3110

**Comment by wendellhu95** [comment]
Hey guys. You may want to check this #4789

**Comment by wendellhu95** [comment]
Closed by #4896. Please let us know if you have problems after adopting 9.x. Thanks!
