### ISSUE TITLE
Add function to scroll selected node into view

### ISSUE THREAD

**Issue by nhanth191** [NG-ZORRO/ng-zorro-antd#4915]
## What problem does this feature solve?
In case of the node list of NzTreeComponent is very long when set a node as selected by code if that node is not visible scroll it into view automtically.
## What does the proposed API look like?
let node = nzTree.getTreeNodeByKey('100');
node.setSelectedAndVisible();

**Comment by simplejason** [comment]
You can use [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) to do that.
