### ISSUE TITLE
nzFrontPagination set to false doesn't works in beta.2

### ISSUE THREAD

**Issue by Innomalist** [NG-ZORRO/ng-zorro-antd#4919]
### Reproduction link
[https://stackblitz.com/edit/angular-5woub3](https://stackblitz.com/edit/angular-5woub3)

### Steps to reproduce
Change the for loops amount to see pagination respects nzData count not nzTotal.

### What is expected?
Because nzTotal is set to 25 the pagination should show 3 pages.

### What is actually happening?
Pagination shows 1 page. Based on nzData count.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0-beta.2 |
| Browser | Chrome, Safari |

---
In beta.0 it is working correct. I looked into documentation throughly and somewhere it was written there is a nzServerRender option. Enabling that didn't helped either. nzFrontPagination was set to false in all tests.

**Comment by doukun** [comment]
angular version is 9.0.7?

**Comment by Innomalist** [comment]
@doukun Yes, Switching between beta.0 and beta.2 fixes this issue. didn't tried with different angular versions.
