### ISSUE TITLE
Tab should simple support route link

### ISSUE THREAD

**Issue by LinBoLen** [NG-ZORRO/ng-zorro-antd#492]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

tab support route link must be wrapped in the template.

## Expected behavior

support `[tab]` attribute selector. because `<a>` is used for router link

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
not in plan, routerLink is quite easy to implements.
