### ISSUE TITLE
[nz-tree]树节点拖拽后，数据没有更新

### ISSUE THREAD

**Issue by kerwin-ly** [NG-ZORRO/ng-zorro-antd#4920]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-m9dy4w](https://stackblitz.com/edit/ng-zorro-antd-start-m9dy4w)

### Steps to reproduce
拖拽任意树节点（如：拖拽，将`交通工具`和`日常用品`两个树节点交换顺序），然后点击`getData`按钮。在控制台中查看`nodes`数据变更情况。

### What is expected?
拖拽后，从原始树节点数据被删除，在新节点位置添加数据。

### What is actually happening?
拖拽后，原始树节点数据未被移出

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome 80.0.3987.149 |

**Comment by simplejason** [comment]
nzTree 目前不会修改用户传递的原始数据（这部分重构工作还在设计中），目前是只能获取组件内部nzTreeNodes数组

**Comment by kerwin-ly** [comment]
@simplejason ok, 希望能添加上这个功能。对于业务开发来说，对原始数据的获取非常重要。

**Comment by SealinGp** [comment]
+1
