### ISSUE TITLE
Default nz-empty image does not support dark mode (well it looks bad)

### ISSUE THREAD

**Issue by whittssg** [NG-ZORRO/ng-zorro-antd#4921]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start = > https://ng.ant.design/version/next/components/empty/en](https://stackblitz.com/edit/ng-zorro-antd-start = > https://ng.ant.design/version/next/components/empty/en)

### Steps to reproduce
Go to  https://ng.ant.design/version/next/components/empty/en and see how the default images look bad in dark mode.

### What is expected?
They dont look bad

### What is actually happening?
They look bad

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0-beta.2 |
| Browser | Latest Chrome |

**Comment by wendellhu95** [comment]
@whittssg Thanks for opening this! This will be fixed in beta.3 or something.
