### ISSUE TITLE
The tabs do not adapt to the mobile version using NZ-LAYOUT

### ISSUE THREAD

**Issue by taksumaki** [NG-ZORRO/ng-zorro-antd#4923]
### Reproduction link
[https://ng-zorro-antd-start-5fcwep.stackblitz.io/](https://ng-zorro-antd-start-5fcwep.stackblitz.io/)

### Steps to reproduce
Use the TABS component in an NZ-LAYOUT

### What is expected?
That the tabs are responsive as in the documentation and that the scroll arrows appear to me.

### What is actually happening?
I try to use the Tabs component and it works well for me but when I put it in mobile version it doesn't adapt to the screen as seen in the doc and the scroll controls of the tabs don't appear so it shows not in a responsive way.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Firefox 74.0 |

**Comment by taksumaki** [comment]
I just found out what happens **if you put it in any div**, even without having any class, so the adaptive view of the Tabs is impossible to use.

I tried the Tabs without a div to encapsulate it and it adapted well, but when I put it inside a div the adaptive view did not appear and the Tab scroll controls did not appear.

**Comment by taksumaki** [comment]
**I recently discovered that it is not only with NZ-Layout, but with any Div.** _If I encapsulate the "Tabs" component in any Div, even though it is the only one in HTML, the "Tabs" component does not adapt to the version of small screens showing the scroll Tabs horizontal_, but _if I only enter the "Tabs" plugin without any parent div that will please it if it reacts to the small screen and adapts showing the horizontal scroll controls_.

Taking this error into account makes **the "Tabs" component unusable by having a lot of Tabs since it does not adapt to the content because it is inside a Div**. I have reviewed the _original Ant Design and this problem does not exist_, so I can determine that It is a problem with this extension that I hope you can repair as I need it a lot. I look forward to the **new version of Ant Design.**

**Comment by vthinkxie** [comment]
Hi @taksumaki 
I didn't get your point, the tabs work fine in the doc site https://ng.ant.design/components/tabs/en#components-tabs-demo-slide

It does not work in your repro because there is enough width in your link which make the browser **scroll**, the tabs will responsive according to the parent div, if the parent div has enough width, it would not be collapsed.

**Comment by taksumaki** [comment]
I understand, but in case you wanted to use it with a 100% wide div, how could you do it? Since you're telling me I have to specify a width for the Div for the buttons to be activated.

**Comment by vthinkxie** [comment]
you don’t have to, it is a css question, you can get the answer from any css lessons
