### ISSUE TITLE
TimePicker panel auto close

### ISSUE THREAD

**Issue by The-io-dev** [NG-ZORRO/ng-zorro-antd#4934]
## What problem does this feature solve?
The panel of a timepicker covers elements of the page and having to interact with a click to close them  form fill feel tidious in our application.
## What does the proposed API look like?
Could it be considerer an option to close the panel when every select has been clicked ? 

for every clickable select in the panel (hour, minutes, seconds) if present, when it get's selected, you consider that the user made the concious choice of every part of the time definition, therefore close the panel.

**Comment by wenqi73** [comment]
This should be enhanced after #5770 merges, then you can change the input value and press `enter` to close panel.
