### ISSUE TITLE
Autcomplete Documentation Basic Usage, set nzDataSource of nz-autocomplete with dataSource property.

### ISSUE THREAD

**Issue by sgentile** [NG-ZORRO/ng-zorro-antd#4935]
## What problem does this feature solve?
Basic Usage, set nzDataSource of nz-autocomplete with dataSource property.  The example does not show uses nzDataSource - the description says it does but it doesn't not

<nz-autocomplete nzBackfill #auto>
        <nz-auto-option *ngFor="let option of options" [nzValue]="option">
          {{ option }}
        </nz-auto-option>
      </nz-autocomplete>
    </div>
## What does the proposed API look like?
The documentation should show how to use nzDataSource

**Comment by sgentile** [comment]
I do see an example, however, there is no option to force only a selection from the autocomplete - someone can type anything into the text box.

**Comment by hsuanxyz** [comment]
close via #4589, If you need the specific options, use `nz-select[nzShowSearch]` is better.
