### ISSUE TITLE
Directive: nzModalFooter does not work

### ISSUE THREAD

**Issue by stochmalm** [NG-ZORRO/ng-zorro-antd#4948]
### Reproduction link
[https://ng-zorro-antd-ivy-6law1v.stackblitz.io](https://ng-zorro-antd-ivy-6law1v.stackblitz.io)

### Steps to reproduce
Add <nz-modal> component with content inside  <div *nzModalFooter>:
```html
<nz-modal nzVisible="true" nzTitle="Custom Modal Title" >
    <div>
      <p>Modal Content</p>
    </div>
    <div *nzModalFooter>
      This content should be visible.
    </div>
</nz-modal>
```

### What is expected?
Content inside nzModalFooter should be visible.

### What is actually happening?
Content inside nzModalFooter is not visible.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0-beta.3 |
| Browser | Chrome/80.0.3987.132 |

**Comment by VibhavRaj** [comment]
how to hide nzModalFooter
