### ISSUE TITLE
Checkable nz-tag is not really checkable when nzColor is defined

### ISSUE THREAD

**Issue by zour228** [NG-ZORRO/ng-zorro-antd#4950]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-3kwoez](https://stackblitz.com/edit/ng-zorro-antd-start-3kwoez)

### Steps to reproduce
Just click tags above the separated line.
Then do the same to the list of tags below the line

### What is expected?
I was expecting tags to become checked

### What is actually happening?
The tags above the separated horizontal line work properly.
But the tags below the line - don't become checked as I was expected

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0-beta.3 |
| Browser | Chromium Version 80.0.3987.149 (Official Build) snap (64-bit); Firefox74.0 |

---
The two lists of tags (separated by line) based on the same source.

I was also trying Angular 9 with ngZorro versions 8.5.2 - 9.0.0-beta.3. The bug also reproduces.

**Comment by hsuanxyz** [comment]
Ref https://github.com/ant-design/ant-design/issues/11889

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
