### ISSUE TITLE
Icon button style is broken in version 9

### ISSUE THREAD

**Issue by sasensi** [NG-ZORRO/ng-zorro-antd#4955]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-button-v9-0-0-beta-3](https://stackblitz.com/edit/ng-zorro-antd-button-v9-0-0-beta-3)

### Steps to reproduce
Create button with an icon but no text.

### What is expected?
The button should be a square.

### What is actually happening?
The button is a rectangle.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0-beta.3 |
| Browser | Chrome 80 |

---
The bug occurs with the new beta version and Angular 9.
This worked as expected with latest stable version (8.5.1) and Angular 8: https://stackblitz.com/edit/ng-zorro-antd-button-v8-5-1

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-button-v9-0-0-beta-3-uhmta9?file=src/app/app.component.html

**Comment by sasensi** [comment]
@vthinkxie, your project shows a circular icon button, what I am talking about is the square icon button.

**Comment by vthinkxie** [comment]
ng-zorro-antd v9 follow the antd v4 design spec, you can modify the less to customize the theme if you want.

**Comment by sasensi** [comment]
Oh, ok, I don't really know how this spec works.  
What I did is pick the example from the documentation:

![screenshot-ng ant design-2020 03 30-14_54_56](https://user-images.githubusercontent.com/11247504/77914639-80377380-7296-11ea-91f6-a1249fceea29.png)

So does this mean that this type of button won't no longer be available in v9 ?

**Comment by vthinkxie** [comment]
sorry for misunderstanding your repo
we will add this type back soon.
