### ISSUE TITLE
The carousel can not show properly while in a modal

### ISSUE THREAD

**Issue by ngstyle** [NG-ZORRO/ng-zorro-antd#4962]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-ss5b1a?file=src%2Fapp%2Fnz.modal.custom.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-ss5b1a?file=src%2Fapp%2Fnz.modal.custom.component.ts)

### Steps to reproduce
1. Add a carousel in a modal
2. The carousel does not display according to the set width and height

### What is expected?
The carousel width and height showed as set.

### What is actually happening?
The carousel does not display according to the set width and height while in a modal.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome  80.0.3987.149 |

**Comment by wendellhu95** [comment]
(Do) Please search issues before opening a new one.

https://github.com/NG-ZORRO/ng-zorro-antd/issues?q=is%3Aissue+modal+carousel+is%3Aclosed

**Comment by ngstyle** [comment]
> (Do) Please search issues before opening a new one.
> 
> https://github.com/NG-ZORRO/ng-zorro-antd/issues?q=is%3Aissue+modal+carousel+is%3Aclosed
> 
> Actually it's a known issue and we're working on a solution called unstable container.

Sorry for the duplicate issue.

**Comment by hsuanxyz** [comment]
fixed via #4702
