### ISSUE TITLE
menu菜单，子菜单较多，内嵌菜单被缩起，鼠标移到一级菜单的图标时，子菜单显示不全

### ISSUE THREAD

**Issue by 007GitHu** [NG-ZORRO/ng-zorro-antd#4968]
### Reproduction link
[https://stackblitz.com/edit/angular-anuxrh?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-anuxrh?file=src/app/app.component.ts)

### Steps to reproduce
点击收缩图标，缩起后，鼠标移到第一个用户图标上面即可重现

### What is expected?
被缩起时，子菜单太多，能出现滚动条，和菜单列展开效果一样

### What is actually happening?
被缩起时，子菜单太多，看不全

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.5.1 |
| Browser | 谷歌 |

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
