### ISSUE TITLE
[bug] can't be automatically installe `@angular/cdk` dependencie

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#497]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

version: `^0.6.0-rc.2`

get the following error if `ng build --prod`: 

```
ERROR in C:/Users/asdf/Desktop/work/ng-alain/src/$$_gendir/app/routes/charts/charts.module.ngfactory.ts (24,22): Cannot
find module '@angular/cdk/observers'.
ERROR in C:/Users/asdf/Desktop/work/ng-alain/src/$$_gendir/node_modules/ng-zorro-antd/node_modules/@angular/cdk/portal/t
ypings/index.ngfactory.ts (10,21): Cannot find module '@angular/cdk/portal'.

......more error..........
```

but,it works installed `@angular/cdk` via `npm install --save @angular/cdk`.  i don't think it's a proper way.

**Comment by wilsoncook** [comment]
Hi, 0.6.0-rc.2 introduced some breaking changes such as: peer dependencies to @angular/cdk 2.0.0-beta.1, @angular to ^4.4.4 .
