### ISSUE TITLE
menu组件使用nzMatchRouter,根据路由自动激活菜单项有问题

### ISSUE THREAD

**Issue by webxmsj** [NG-ZORRO/ng-zorro-antd#4974]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
先切换到page2 页面 再点击menu菜单项page1 弹窗是否确认退出 此时选择取消 ， 页面没有跳转到page1, menu还是把page1 高亮了

### What is expected?
路由没有跳转到对应页面,menu 对应项不要高亮

### What is actually happening?
路由没有跳转到对应页面,menu 对应项高亮了

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.1 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
已经在9.0.0-beta.3修复
