### ISSUE TITLE
nz-table中文字过长会导致thead和tbody不对齐

### ISSUE THREAD

**Issue by DaoShu** [NG-ZORRO/ng-zorro-antd#4976]
### Reproduction link
[https://stackblitz.com/edit/angular-36q8xc](https://stackblitz.com/edit/angular-36q8xc)

### Steps to reproduce
数据加载完成后，当td的内容过多时，会导致样式错位。

### What is expected?
当表格文字过多时，应该换行，或者使用nz-paragraph nzEllipsis能使其溢出省略是最好的。

### What is actually happening?
在分组表头使用nzWidthConfig设置每列的宽度后，无法固定col的宽度，导致thead和tbody不对齐。

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | chrome 版本 83.0.4100.3（正式版本）dev （64 位） |

---
这是我从官网的nz-table的分组表头里，直接拷贝的代码，只修改了第一列的数据，其他地方都没动过。

**Comment by vthinkxie** [comment]
8.5.2 中有 nzBreakWord
9.0.0-beta.3 中有 nzEllipsis
