### ISSUE TITLE
Regressions in NzDropDownMenu. Can't close it with another click and the opening/closing animation is slow even if nzNoAnimation is present.

### ISSUE THREAD

**Issue by MJomaa** [NG-ZORRO/ng-zorro-antd#4982]
### Reproduction link
[https://stackblitz.com/edit/angular-w1upj9](https://stackblitz.com/edit/angular-w1upj9)

### Steps to reproduce
1. Click on the dropdown menu button.
2. Compare it to the old behavior: 
[https://stackblitz.com/edit/ng-zorro-antd-start-bkzycd](https://stackblitz.com/edit/ng-zorro-antd-start-bkzycd)

### What is expected?
1. That I can close the dropdown menu with another click.
2. That when nzNoAnimation is present, it is not so slow opening/closing. 

### What is actually happening?
1. Can only open the menu but not close it. A bug in the dropdown menu logic.
2. It seems like [@slideMotion] is slowing the animation even if [@disabled] is true.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0-beta.3 |
| Browser | Chrome 80 |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-hsuj1w?file=src/app/app.module.ts

<img width="445" alt="截屏2020-04-04下午5 08 57" src="https://user-images.githubusercontent.com/1506722/78423148-fe30bb80-7696-11ea-847b-218f99986fbe.png">

**Comment by MJomaa** [comment]
Oh whopsie it seems related to (1). However the slide motion thing is still an issue.
