### ISSUE TITLE
Angular patchValue() does not update Ant Design custom form control

### ISSUE THREAD

**Issue by wollerman** [NG-ZORRO/ng-zorro-antd#4988]
### Reproduction link
[https://stackblitz.com/edit/angular-zdcj2a?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-zdcj2a?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. create custom form control using nz-select inside
2. use custom form control in an angular reactive form
3. when component mounts use "patchValue()" to set some value in the form

Then value is set in the model but not in the UI.

### What is expected?
The value in the model is displayed in the UI.

### What is actually happening?
The value is not displayed in the UI.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
the value will only show when there are matched nz-option, if you have some default value and don't want to display the nz-option at the same time, you can try https://ng.ant.design/components/select/en#components-select-demo-default-value
