### ISSUE TITLE
https://ng.ant.design/#/components/table

### ISSUE THREAD

**Issue by leixus** [NG-ZORRO/ng-zorro-antd#499]
这个是官网上的案例效果：
![image](https://user-images.githubusercontent.com/24884532/32151021-67bf99c6-bd54-11e7-8e13-6b2dca9fc05a.png)

按照上面的代码写表格，结果成了这样
![image](https://user-images.githubusercontent.com/24884532/32151035-8075ff00-bd54-11e7-8dfc-a11f0e320a59.png)
请帮忙解决。谢谢

**Comment by wilsoncook** [comment]
Make sure you have correct typed, you may provide a reproduction by: http://plnkr.co/edit/tpl:sKWy62

**Comment by leixus** [comment]
很抱歉，是我没有更新ng-zorro，谢谢你的帮助。
