### ISSUE TITLE
tree 组件的图标加事件

### ISSUE THREAD

**Issue by hukaixuan2017** [NG-ZORRO/ng-zorro-antd#4991]
## What problem does this feature solve?
目前业务需要，会编辑一个 tree，在编辑的时候存在添加和删除节点的问题，目前 tree 组件自带的右键事件可以变相满足需求，但是根据客户的实际使用反馈，右键事件不易使用户察觉，需要培训。

所以看能不能在树节点的 icon 上增加一个 click（tree 自带的 nzclick 事件是作用于整个节点包括节点前面的 icon） 事件，作为删除节点的一个操作？或者有其他解决方案？

## What does the proposed API look like?
在 tree 的组件中增加事件 [nzIconClick]="trigger($event)"

**Comment by vthinkxie** [comment]
nzTreeTemplate 一样可以实现，在自定义图标上增加 (click) 事件即可

**Comment by vthinkxie** [comment]
nzTreeTemplate 一样可以实现，在自定义图标上增加 (click) 事件即可

**Comment by hukaixuan2017** [comment]
我的 html 代码是这样：
<nz-tree
    [nzData]="nodes"
    (nzClick)="activeNode($event, 'click')"
    (nzDblClick)="openFolder($event)"
    [nzTreeTemplate]="nzTreeTemplate"
></nz-tree>
<ng-template #nzTreeTemplate let-node>
    <i nz-icon (click)="deletenode($event)" nzType="file"></i>
    <fa-icon (click)="deletenode($event)" [icon]="['far', 'trash-alt']"></fa-icon>
</ng-template>
</nz-dropdown-menu>

ts: 

  activeNode(data: NzFormatEmitEvent, action): void {
   console.log('click ', data, ' action ', action);
    this.activedNode = data.node!;
  }

  /**
   * 删除节点
   */
  deletenode(event: NzFormatEmitEvent): void{
    console.log('Event :', event);

  }

deletenode 这个函数一直不会被触发，是我那里写错了吗？

**Comment by vthinkxie** [comment]
所有的操作官网都有例子
https://stackblitz.com/edit/angular-gcpc3p?file=src/app/app.component.ts

**Comment by hukaixuan2017** [comment]
看到了，多谢多谢，之前对于 tree nzTreeTemplate 的理解不深，当 tree 加上 nzTreeTemplate，nzTreeTemplate 里面又对节点进行了二次处理，我之前把 icon click 事件写在对节点处理之前，所以对节点进行渲染时将之前绑定的 icon  事件取消掉，如下写法：

 <ng-template #nzTreeTemplate let-node>
      icon 的 click 事件在这里
      <i nz-icon nzType="file" (click)="clickFile($event)"></i>
      <span class="custom-node" [class.active]="activedNode?.key === node.key">
        <span *ngIf="!node.isLeaf" (contextmenu)="contextMenu($event, menu)">
          <span class="folder-name">{{ node.title }}</span>
          <span class="folder-desc">created by {{ node?.origin?.author | lowercase }}</span>
        </span>
       这里是对节点的处理，会将 icon 绑定的事件 off 掉，
        <span *ngIf="node.isLeaf" (contextmenu)="contextMenu($event, menu)">
          <span class="file-name">{{ node.title }}</span>
          <span class="file-desc" >modified by {{ node?.origin?.author | lowercase }}</span>
        </span>
      </span>
    </ng-template>

不知道这样理解对不对，

多谢指导。
