### ISSUE TITLE
 upload-list component support manual sort the FileList

### ISSUE THREAD

**Issue by jerrytang67** [NG-ZORRO/ng-zorro-antd#4992]
## What problem does this feature solve?
 upload-list component support manual sort the FileList
## What does the proposed API look like?
```
[nzSort]="handleRemove"
```

**Comment by cipchk** [comment]
@jerrytang67 You can sort by `nzFileList`.

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
