### ISSUE TITLE
nzMode="tags" in FormGroup adding items to FormArray

### ISSUE THREAD

**Issue by PavolVasko12** [NG-ZORRO/ng-zorro-antd#4995]
### Reproduction link
[https://ng-zorro-antd-start-kbyxfz.stackblitz.io](https://ng-zorro-antd-start-kbyxfz.stackblitz.io)

### Steps to reproduce
Everything is in the template. Basically I have issues to figure out how you would use the nzMode="tags" with formArray. It works perfectly fine on standard nz-select.

### What is expected?
I would expect to be able add items to the formArray.

### What is actually happening?
Cannot add any items to the array.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Google Chrome (Version 80.0.3987.163) on MacOS |

---
I am not really sure if that's a bug or just my lack of knowledge so I apologise in advance if that's the case.

**Comment by danranVm** [comment]
I don't quite understand why you need to use FormArray.
Maybe what you want is this ?
https://stackblitz.com/edit/ng-zorro-antd-start-rjd9bc?file=src/app/app.component.html

**Comment by PavolVasko12** [comment]
Hi,

Sorry I am not too sure why this did not work for me but I did try different approaches.

You solution works exactly as intended.

Thank you.

Pavol Vasko
------------------------------------------------
m: +44(0)7766665955
e: pavol.vasko.sk@gmail.com
w: https://pavolvasko.co.uk
