### ISSUE TITLE
ng build --prod --build-optimizer 出错

### ISSUE THREAD

**Issue by liuliangjia** [NG-ZORRO/ng-zorro-antd#50]
使用这个选项需要什么前提，只是基本工程，啥也没加。

ERROR in ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined

**Comment by trotyl** [comment]
Known issue (for me only?), being fixed by https://github.com/NG-ZORRO/ng-zorro-antd/pull/29.

**Comment by trotyl** [comment]
Can also be fixed by https://github.com/NG-ZORRO/ng-zorro-antd/pull/51.
