### ISSUE TITLE
table -> https://ng.ant.design/#/components/table

### ISSUE THREAD

**Issue by leixus** [NG-ZORRO/ng-zorro-antd#500]
![image](https://user-images.githubusercontent.com/24884532/32160020-de9e117c-bd8a-11e7-9673-592b8ffa7db8.png)
![image](https://user-images.githubusercontent.com/24884532/32160062-0f41d638-bd8b-11e7-902f-1a0fbd8b78bd.png)
![image](https://user-images.githubusercontent.com/24884532/32160102-37eb1130-bd8b-11e7-80a6-a7fa4f01518f.png)
表格没有展开

**Comment by vthinkxie** [comment]
nzExpand only defined the style, you have to manage your expand and collapse with your strategy.
