### ISSUE TITLE
angular9   ng-zorro-antd start error

### ISSUE THREAD

**Issue by ZhouXu-cc** [NG-ZORRO/ng-zorro-antd#5016]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
ng new demo
ng add ng-zorro-antd
ng serve --open

### What is expected?
the project start successfully

### What is actually happening?
rror: Tried to write /Users/daniellu/Desktop/antd/node_modules/ng-zorro-antd/core/addon/classlist_add.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /Users/daniellu/Desktop/antd/node_modules/ng-zorro-antd/core/addon/classlist_add.d.ts.
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.
Error: Tried to write /Users/daniellu/Desktop/antd/node_modules/ng-zorro-antd/core/addon/string_template_outlet.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /Users/daniellu/Desktop/antd/node_modules/ng-zorro-antd/core/addon/string_template_outlet.d.ts.
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.
Error: Tried to write /Users/daniellu/Desktop/antd/node_modules/ng-zorro-antd/core/addon/addon.module.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /Users/daniellu/Desktop/antd/node_modules/ng-zorro-antd/core/addon/addon.module.d.ts.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0-beta.3 |
| Browser | Chrome |

**Comment by ZhouXu-cc** [comment]
here is package.json
===================
{
  "name": "antd",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.1",
    "@angular/common": "~9.1.1",
    "@angular/compiler": "~9.1.1",
    "@angular/core": "~9.1.1",
    "@angular/forms": "~9.1.1",
    "@angular/platform-browser": "~9.1.1",
    "@angular/platform-browser-dynamic": "~9.1.1",
    "@angular/router": "~9.1.1",
    "ng-zorro-antd": "^8.5.2",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}

**Comment by hsuanxyz** [comment]
Try

```
$ ng add ng-zorro-antd@next
```

**Comment by ZhouXu-cc** [comment]
I will try it .
Thanks.
