### ISSUE TITLE
nz-tree can customize icon when nzShowLine is true

### ISSUE THREAD

**Issue by hellojayjay** [NG-ZORRO/ng-zorro-antd#5017]
## What problem does this feature solve?
can customize icon when nzShowLine is true.
## What does the proposed API look like?
nzIconTemplate

**Comment by hellojayjay** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/tree/tree-node-switcher.component.ts#L36

when nzShowLine is true, icon type is 'file' by default.

expect can customize the icon

**Comment by hsuanxyz** [comment]
Fixed in newer versions.

https://stackblitz.com/edit/angular-zg9avc?file=src/app/app.component.ts
