### ISSUE TITLE
ie下体验极差！！

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#502]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by liganggang** [comment]
ie 体验极差

**Comment by liepeng328** [comment]
ie10以上都还好，我用的很好。我整理了一个开源项目，你可以参考下，在我的首页
