### ISSUE TITLE
bug(module:button): class `ant-btn-icon-only` is not applied to the `icon-only-button`

### ISSUE THREAD

**Issue by LouisSung** [NG-ZORRO/ng-zorro-antd#5023]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-uaapgo](https://stackblitz.com/edit/ng-zorro-antd-start-uaapgo)

### Steps to reproduce
* I've tried to use the stackblitz to reproduce this bug, but seems like it's not yet supported `ng-zorro-antd@9.0.0-beta.4` (with `Angular 9.1.1` & `Ivy`)

* However, this bug is easy to reproduce as the [sample code](https://stackblitz.com/edit/ng-zorro-antd-start-uaapgo?file=src%2Fapp%2Fapp.component.html)
  + ```html
    <button nz-button nzType="danger"><i nz-icon nzType="caret-up"></i></button>
    <button nz-button nzType="primary" class="ant-btn-icon-only"><i nz-icon nzType="caret-up"></i></button>
    
    ```
  + <img src="https://user-images.githubusercontent.com/37973545/79225898-0b685a00-7e90-11ea-8098-3dbc26f58be3.png" width="500px">

### What is expected?
Buttons containing icon only should apply class `ant-btn-icon-only` as the **blue button**

### What is actually happening?
Buttons containing icon only do NOT apply class `ant-btn-icon-only` as the **red button**

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0-beta.4 |
| Browser | chrome:80 |<!-- generated by ng-zorro-issue-helper. DO NOT REMOVE -->

**Comment by vthinkxie** [comment]
duplicated #4955
