### ISSUE TITLE
NG-ZORRO v9 升级指南 / v9 upgrade guide

### ISSUE THREAD

**Issue by hsuanxyz** [NG-ZORRO/ng-zorro-antd#5035]
# 中文版
> 本指南适用于当前版本 ng-zorro-antd >= 8 ;
> 如果在升级过程中遇到问题，欢迎提出。提问前请阅读 [如何向开源社区提问题](https://github.com/seajs/seajs/issues/545)
> 如果发现本指南存在遗漏/错误，请指出!
> 或者你遇到了新的问题并解决了，欢迎补充!
>
### 开始之前

1. 首先确保你 `Node.js` >= `10.13`
2. 创建新的分支，或者使用其他方式备份当前项目
3. 删除项目下 package-lock.json 文件

#### 第一步 - 升级相关依赖

- 前往 https://update.angular.io/ 将项目升级到 Angular9。
- 如果你有单独使用 `@angular/cdk` 请执行 `ng update @angular/cdk`
- 如果你有单独使用 `date-fns` 请先升级到 `2.x`
- 如果你有使用 `monaco-editor` 请先升级到 `0.20.x`, 使用 `monaco-editor-webpack-plugin` 时请将其升级到 `1.9.x`

#### 第二步 - 升级 NG-ZORRO

- 运行 `ng update ng-zorro-antd`
- 如果控制台出现警告消息请按提示修改对应代码

### 常见问题

-  Class extends value undefined is not a constructor or null #5197
```bash
[error] TypeError: Class extends value undefined is not a constructor or null
```
在 `ng-zorro-antd@9.1.1` 发布以前将 `@angular/cdk` 降级到 ` 9.2.1`.  

---------------------
# English Version

> This guide applies to the current version ng-zorro-antd> = 8;
> If you encounter problems during the upgrade process, feel free to comment here.
> If you find any errors in this guide, please point out
> Or you have encountered a new problem and solved it, welcome to comment here.

### Before upgrade

1. Make sure `Node.js` >= `10.13`.
2. Create a new branch, or use other methods to back up the current project.
3. Delete the package-lock.json file.

### Upgrade dependencies

- Upgrade Angular to 9.x version, ref https://update.angular.io/ .
- Run `ng update @angular/cdk`, if you have used `@angular/cdk`.
- If you have used `date-fns` in your project, upgrade it to `2.x` version, ref https://github.com/date-fns/date-fns-upgrade.
- If you have used `monaco-editor` please upgrade it to `0.20.x`, don't forget to upgrade `monaco-editor-webpack-plugin` to `1.9.x` if you have used it.

### Upgrade NG-ZORRO

- Run `ng update ng-zorro-antd`.
- If a warning message appears in the console, follow the prompts to modify the corresponding code.

### Common Problem

-  Class extends value undefined is not a constructor or null #5197
```bash
[error] TypeError: Class extends value undefined is not a constructor or null
```
Try downgrade `@angular/cdk`  to 9.2.1 until `ng-zorro-antd@9.1.1`  released.

---

- [update.angular.io](https://update.angular.io)
- [date-fns upgrade guide](https://date-fns.org/v2.0.0/docs/Upgrade-Guide)
- [date-fns 2.x breaking change](https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#changed-3)

**Comment by BrsJsk** [comment]
English version?

**Comment by vthinkxie** [comment]
> English version?

updated

**Comment by BrsJsk** [comment]
Anyone knows why ng update @angular/cdk updates @angular/common, @angular/compiler, @angular/core and @angular/forms to version ~10.0.0-next.2 ?

**Comment by WuMianRen** [comment]
× Migration failed: Cannot read property 'attrs' of undefined
  See "C:\Users\12858\AppData\Local\Temp\ng-SUpNfq\angular-errors.log" for further details 报这个错误 并且编译时报
```
ERROR in src/app/menu-common/map-menu/map/map.component.ts:11:42 - error TS2307: Cannot find module 'ng-zorro-antd/date-picker/date-range-picker.component'.

11 import { DateRangePickerComponent } from 'ng-zorro-antd/date-picker/date-range-picker.component';

```

**Comment by zhang0101** [comment]
Ng-Zorro安装后运行发生record.factory is not a function是什么原因

**Comment by hsuanxyz** [comment]
@zhang0101 hope it helps you, https://github.com/angular/angular/issues/35282

**Comment by nishizhen** [comment]
ng update ng-zorro-antd               
Using package manager: 'npm'
Collecting installed dependencies...
Found 37 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency ng-zorro-antd @ "9.2.1" (was "8.3.1")...
UPDATE package.json (1898 bytes)
✔ Packages installed successfully.
** Executing migrations of package 'ng-zorro-antd' **

❯ Updates NG-ZORRO to v9 [https://github.com/NG-ZORRO/ng-zorro-antd/issues/5035]
✖ Migration failed: Cannot read property 'startTag' of undefined
  See "/private/var/folders/w0/r_snx5vx6y1c9vfwx1vzfbwh0000gn/T/ng-wNDsTu/angular-errors.log" for further details.

**Comment by hsuanxyz** [comment]
@nishizhen  we cannot reproduce this error, could you provide a repo for us to checks?
Maybe the problem is in the `nz-dropdown`, `nz-dropdown-button`, `nz-form-extra` and `nz-tooltip`, `nz-popover`, `nz-popconfirm` tags.

**Comment by nishizhen** [comment]
> @nishizhen we cannot reproduce this error, could you provide a repo for us to checks?
> Maybe the problem is in the `nz-dropdown`, `nz-dropdown-button`, `nz-form-extra` and `nz-tooltip`, `nz-popover`, `nz-popconfirm` tags.

Thx, we have resolved~

**Comment by yourival** [comment]
I got those issues when I was trying to upgrade to v9. All date-related components are not working. I did upgrade the date-fns to 2.x before the upgrade. Please Help! 

![02](https://user-images.githubusercontent.com/23730152/85821312-b748f280-b7bb-11ea-8010-24e5c4f884aa.png)
![01](https://user-images.githubusercontent.com/23730152/85821315-b87a1f80-b7bb-11ea-9c63-3042e481ba6b.png)
![03](https://user-images.githubusercontent.com/23730152/85821317-b87a1f80-b7bb-11ea-9494-34f878ed74a2.png)

**Comment by hsuanxyz** [comment]
@yourival 

> `error TypeError: Cannot read property 'slice' of undefined at generateTheme ...`

reinstall `antd-theme-generator@1.2.2`

---

> `ERROR TypeError: date_fns_addMonths_WEBPACK_IMPORTED_MODULE_0__default(...) is not a function ...`

@wenqi73 can you check it?

**Comment by wenqi73** [comment]
@yourival Could you provide a mini reproduction?

**Comment by Endran** [comment]
> > @nishizhen we cannot reproduce this error, could you provide a repo for us to checks?
> > Maybe the problem is in the `nz-dropdown`, `nz-dropdown-button`, `nz-form-extra` and `nz-tooltip`, `nz-popover`, `nz-popconfirm` tags.
> 
> Thx, we have resolved~

I also run into `Cannot read property 'startTag' of undefined`, could you explain how you resolved it?

**Comment by Endran** [comment]
Found it, in our case we still had `nz-form-explain` somewhere. I found it by replacing line 23 of `node_modules/ng-zorro-antd/schematics/utils/ng-update/elements.js` with the snippet below, whilst running `ng update ng-zorro-antd`.

```
  return elements.map((element) => {
    console.log(`element.nodeName ` + element.nodeName);
    return element.sourceCodeLocation.startTag.startOffset;
  });
```

**Comment by crossan007** [comment]
> I also run into Cannot read property 'startTag' of undefined, could you explain how you resolved it?

I downgraded my local install of NodeJS from 16 to 12, and I was able to run the ng-zorro-antd upgrade with:
```
cmd /C "set 'NG_DISABLE_VERSION_CHECK=1' && npx @angular/cli@9 update ng-zorro-antd@9.0.0 --force"
```

**Comment by FrogitH5** [comment]
升级angular7-9遇到报错请问如何解决
ERROR in Error: Internal Error: The name total is already defined in scope to be [object Object]
