### ISSUE TITLE
[bug] use laster version has getting error "Attempting to attach an unknown Portal type." via ng build --prod

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#504]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

you can visit [ng-alain](https://cipchk.github.io/ng-alain/#/) site getting error tip, i think `@angular/cdk` version is unreliable.

> i'll roll back `0.5.x` tonight.

**Comment by vthinkxie** [comment]
@cipchk have you specific @angualr/cdk version?

**Comment by cipchk** [comment]
@vthinkxie 

    "ng-zorro-antd": "^0.6.0-rc.2",
    "@angular/cdk": "^2.0.0-beta.12",

**Comment by cipchk** [comment]
@vthinkxie 以下代码就会产生错误：

```typescript
import { Component, OnInit } from '@angular/core';
import { NzNotificationService } from 'ng-zorro-antd';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app';

  constructor(private msg: NzNotificationService ) {}

  ngOnInit() {
    this.msg.error('error', 'asdf');
  }
}
```

**Comment by cipchk** [comment]
@vthinkxie hi, is there any news about?

**Comment by vthinkxie** [comment]
@cipchk it seems a bug of angular/cdk, @wilsoncook please check it.

**Comment by wilsoncook** [comment]
@cipchk It turns out that the incomplete rollup configurations for cdk due to cdk have been separated into multi importing entries, it could occur during `prod`. 
I'm going to fix tonight, thanks for your attention!
