### ISSUE TITLE
9.0版本的穿梭框设置direction无效

### ISSUE THREAD

**Issue by ShenJi7** [NG-ZORRO/ng-zorro-antd#5041]
### Reproduction link
[https://ng-zorro-antd-start-wfbaxn.stackblitz.io](https://ng-zorro-antd-start-wfbaxn.stackblitz.io)

### Steps to reproduce
在谷歌上使用9.0版本的穿梭框组件，使用table里面的穿梭框，设置direction并无效果

### What is expected?
期望设置了direction===left或者direction===right的数据得到展示

### What is actually happening?
并无效果

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | 谷歌 |

**Comment by vthinkxie** [comment]
@ShenJi7 
提供的repro link里面所有的功能都是正常工作的
