### ISSUE TITLE
V9 Popover controlling the close of the dialog only works for the first time

### ISSUE THREAD

**Issue by rppig42** [NG-ZORRO/ng-zorro-antd#5043]
### Reproduction link
[https://stackblitz.com/edit/angular-njvz5v?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-njvz5v?file=src/app/app.component.ts)

### Steps to reproduce
Close the popover within itself for multiple times

StackBlitz demo is not working for V9's popover but you can reproduce this bug on https://ng.ant.design/components/popover/en 

### What is expected?
You can always close the popover

### What is actually happening?
You can only close it for the first time

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | Chrome latest |

**Comment by hsuanxyz** [comment]
fixed via #5053
