### ISSUE TITLE
nz-sider component (nzCollapsedChange) event not work

### ISSUE THREAD

**Issue by itning** [NG-ZORRO/ng-zorro-antd#5044]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-9k6rja?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-start-9k6rja?file=src/app/app.component.ts)

### Steps to reproduce
nz-sider组件展开-收起时的回调函数 不回调

### What is expected?
回调

### What is actually happening?
不回调

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | 81.0.4044.113 |

**Comment by micobarac** [comment]
It still doesn't work...
