### ISSUE TITLE
9.0.1 中 Select 选择器中过长的 option 选项会显示横向滚动条造成遮挡

### ISSUE THREAD

**Issue by xinhaoxx** [NG-ZORRO/ng-zorro-antd#5047]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-uyzgww](https://stackblitz.com/edit/ng-zorro-antd-start-uyzgww)

### Steps to reproduce
**ng-zorro-antd 9.0.1** ↓
https://stackblitz.com/edit/ng-zorro-antd-start-uyzgww

**ng-zorro-antd 8.5.1** ↓
https://stackblitz.com/edit/ng-zorro-antd-start-yaulau

### What is expected?
与 ng-zorro-antd 8.5.1 或 ant design 一致

### What is actually happening?
Select 选择器中过长的 option 选项会显示横向滚动条造成遮挡

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | Chrome 80.0.3987.163 |

**Comment by rppig42** [comment]
In addition, property **nzDropdownMatchSelectWidth** doesn't work anymore

**Comment by hsuanxyz** [comment]
> In addition, property **nzDropdownMatchSelectWidth** doesn't work anymore

could you open an issue for this?

**Comment by rppig42** [comment]
> > In addition, property **nzDropdownMatchSelectWidth** doesn't work anymore
> 
> could you open an issue for this?

https://github.com/NG-ZORRO/ng-zorro-antd/issues/5058 here's the issue
