### ISSUE TITLE
popovercomponent 没有添加entrycomponent

### ISSUE THREAD

**Issue by webxmsj** [NG-ZORRO/ng-zorro-antd#5049]
### Reproduction link
[https://hvyrec.run.stackblitz.io](https://hvyrec.run.stackblitz.io)

### Steps to reproduce
https://hvyrec.run.stackblitz.io

### What is expected?
不要报错

### What is actually happening?
No component factory found for NzPopoverComponent. Did you add it to @NgModule.entryComponents?

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
the enable ivy is not enabled by default in stackblitz now, you can enable it by yourself.
