### ISSUE TITLE
upload组件的nzFileList无法显示bas64类型的svg图片 

### ISSUE THREAD

**Issue by cadleo** [NG-ZORRO/ng-zorro-antd#5052]
### Reproduction link
[https://stackblitz.com/edit/angular-ww2hpa?file=src%2Fapp%2Fapp.component.ts ](https://stackblitz.com/edit/angular-ww2hpa?file=src%2Fapp%2Fapp.component.ts )

### Steps to reproduce
在upload组件的nzFileList里的项里，如果它的url字段或thumbUrl为base64类型的svg图片的字符串，则会自动在该字段的值前添加了"unsafe:"字符串，导致无法正常显示

打开如上链接，再打开控制台，会看到unsafe的的报错字样 

### What is expected?
期望nzFileList配置能正常显示base64类型的svg图片 

### What is actually happening?
不能正常显示base64类型的svg图片 

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome80  |

**Comment by hsuanxyz** [comment]
@cadleo 感谢你的反馈，但是对于 unsafe 的处理的确应该由用户自己决定，而不是组件库。
