### ISSUE TITLE
The `NgZorroAntdModule` has been deprecated and will be removed in 10.0.0. Please use secondary entry instead.

### ISSUE THREAD

**Issue by lohmew** [NG-ZORRO/ng-zorro-antd#5054]
注意：不是用 https://ng.ant.design/issue-helper/#/zh 创建的 issue 会被立即关闭。

**Comment by lohmew** [comment]
The `NgZorroAntdModule` has been deprecated and will be removed in 10.0.0. Please use secondary entry instead.
用9.0会提示这个问题。请问怎么解决。

**Comment by hsuanxyz** [comment]
```
The `NgZorroAntdModule` has been deprecated and will be removed in 10.0.0. Please use secondary entry instead.
e.g. `import { NzButtonModule } from 'ng-zorro-antd/button';`
```

请在项目中使用次级入口引入模块，`NgZorroAntdModule` 10.0.0 将会移除。

**Comment by Siwar-Lazrak** [comment]
The `NgZorroAntdModule` has been deprecated and will be removed in 10.0.0. Please use secondary entry instead.!!!!!!!!!!!!!!!
