### ISSUE TITLE
Allow drawer to open inside any container not just htmlBody

### ISSUE THREAD

**Issue by whittssg** [NG-ZORRO/ng-zorro-antd#5060]
## What problem does this feature solve?
Allows the drawer to be opened inside other containers (for instance card) instead of just inside htmlBody

See similar request in ant design git: https://github.com/ant-design/ant-design/issues/11671
## What does the proposed API look like?
[drawerOrigin]="elemetRef"

**Comment by hsuanxyz** [comment]
Duplicate #4223

**Comment by whittssg** [comment]
@hsuanxyz man i really searched as well for that and only found the one from ant g.. :)

**Comment by hsuanxyz** [comment]
Don't worry, we will support it

**Comment by neesonqk** [comment]
When will this feature be available?
