### ISSUE TITLE
9.x-nz-date-picker: 当日期弹出时，文字框有内容的部分无法被正常选取

### ISSUE THREAD

**Issue by taipeiwu** [NG-ZORRO/ng-zorro-antd#5061]
### Reproduction link
[https://ng.ant.design/components/date-picker/zh](https://ng.ant.design/components/date-picker/zh)

### Steps to reproduce
官方文档就有这个问题。

### What is expected?
当日期弹出时，选择一个日期后，再次重复此步骤后，文字框无法被正常选取，若选取则会将弹出视窗关闭，而这只发生在Angular版本，React版本则可正常选取且动作流畅。

### What is actually happening?
参考 https://ant.design/components/date-picker-cn/。

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | Chrome 81.0.4044.92 |

**Comment by Mr-Eve** [comment]
这个是CDK的遮罩层问题吧, 这个有修复的可能吗? 有什么思路吗?

**Comment by taipeiwu** [comment]
原生HTML的SELECT菜单再同一页若有多个，当点击跳出一个后，现在要点击另外一个放置原本那一个关闭，而另一个跳出，却这边的流程，因为采用CDK遮罩的关系，需要点击先将遮罩消除，才能再次点选另一个，我认为这不符合用户操作的习惯，或是否能仅遮罩局部显示的范围呢？

**Comment by ricardo0624** [comment]
替代的方案,用ctrl+a,ctrl+c,就可以复制,但是的确react没这个问题,angular有

**Comment by vthinkxie** [comment]
cdk 弹窗采用的是通过backdrop来判断是否clickoutside的策略

优点
1. 没有全局click的点击监听，性能更好
2. 不受 stopPropagation 的限制

缺点
1. 每次 clickoutside 需要二次点击才能选择别的数据

请跟踪 https://github.com/NG-ZORRO/ng-zorro-antd/issues/4933

**Comment by taipeiwu** [comment]
请参考MDN的Input Date功能，也没有这个问题，所以我不认为完全是CDK的问题，而是思路的问题。

[https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input/date](MDN Input Date)
[https://stackblitz.com/edit/ng-zorro-antd-start-tg2une?file=src/app/app.component.html](复制了三个同样Input Date，请尝试点击一个菜单后，再选取另一个菜单，也不会有需要点击两次的问题。)

**Comment by vthinkxie** [comment]
1. MDN 的 Input Date 的遮罩是 浏览器原生实现的，与组件库没有关系
2. 不同的操作平台的体验也是不一致的，比如在 mac osx 上，所有的 MDN 的遮罩都需要点击两次才能选择
3. CDK 与 MDN Input Date 没有任何关系，是 Angular Component Developer Kit，是 ng-zorro-antd 的底层依赖

**Comment by taipeiwu** [comment]
@vthinkxie 
应该这样说，是否设计遮罩的方式设法与原生浏览器的实现方式相同会更好呢？

这已经跳脱出是否必须采用CDK的问题，原生浏览器也有针对各平台进行优化，用户已经熟悉原生 操作在使用上的经验，就算MAC要点击两次，那WINDOWS也不应该如此，因有所差异，所以我不认为因Angular或CDK等套件因素而能影响这些长久以来用户的操作习惯。

结论：CDK遮罩是全局遮罩，但用在 date-picker 和 time-picker 这里不合适，更适合的是局部或什至不需要使用遮罩，要能监听其他的物件， 一有其他物件的响应则会将当前的物件关闭。

**Comment by vthinkxie** [comment]
@taipeiwu 
1.  在这里讨论的更多是技术实现方式，而不是是否要去实现
2. 所有内容都是在我们的改进计划内，并且有milestone在记录，所以建议你先看下 #4933 的部分，所有的讨论中间并没有人与你有不同的意见。

**Comment by taipeiwu** [comment]
@vthinkxie 
1. 我不认为我是提出创新功能，期待能符合原始浏览器或能完整同步 Ant Design 的样式（包含操作方式）。
2. 我本身也是 Angular 开发者，能理解 CDK 遮罩原理。
3. 我们现在也是在技术上做讨论，我不明白这里为什么必须要采用 CDK 遮罩达到此目的，是否能将遮罩移除即可达到与 Ant Design 同步的效果。

**Comment by vthinkxie** [comment]
如果你有能够
1. 移除 CDK 遮罩
2. 并且能够避免用户 stopPropagation 导致 clickoutside click监听失败
满足以上两点的方案，欢迎提出一个新的 issue proposal 或者 pr

**Comment by huangyuanzhen** [comment]
我最近参照 ng-zorro 的 popover， 封装了一个相似的组件， 也碰到了这个问题，所以我顺手解决了这个问题，我这里
1. 移除了遮罩层，全局监听了 click 事件;
2. 可以顺畅切换不同的 popover，可以正常关闭；
3. 不会影响 popover 内的事件；

我需要在这里贴一下解决的代码还是去提一个 PR 呢？@vthinkxie ， @taipeiwu

**Comment by vthinkxie** [comment]
@huangyuanzhen 欢迎提PR，非常感谢
