### ISSUE TITLE
tab>nz-tabset>nzLinkRouter

### ISSUE THREAD

**Issue by wh77572** [NG-ZORRO/ng-zorro-antd#5067]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-habdfm](https://stackblitz.com/edit/ng-zorro-antd-start-habdfm)

### Steps to reproduce
when use nz-tabset && use property nzLinkRouter,and nzDisabled, the disabled tab is still can be clicked. 

### What is expected?
when use property disabled,tabItem can not be clicked. 

### What is actually happening?
the disabled tab can be clicked. 

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | chrome |

**Comment by wendellhu95** [comment]
Currently, tabs component only subscribe router change event. It does not interfere the default link behavior. Are you interested in a pull request?

**Comment by wh77572** [comment]
> Currently, tabs component only subscribe router change event. It does not interfere the default link behavior. You just disable `<a>` tags by yourself.

it works when push disabled into ‘<a>’, but the tab behavior is still works, and in angular template,'<a>' is  not allowed bind disabled, so it is not flexible to use  `<a>`'s property disable.

**Comment by hsuanxyz** [comment]
close via #5759
