### ISSUE TITLE
9.x Can not set/update column width by nzWidth or nzWidthConfig

### ISSUE THREAD

**Issue by mbrainiac** [NG-ZORRO/ng-zorro-antd#5069]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-eoetda?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-eoetda?file=src/app/app.component.ts)

### Steps to reproduce
Resizing the browser larger than 200px then see the width of each columns

### What is expected?
The last column should always be 80px, other should match with nzWidthConfig

### What is actually happening?
Column width not match with nzWidthConfig

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | all |

---
This work fine with ng-zorro-antd 8.x

**Comment by JoniVR** [comment]
Same issue here, a temporary workaround (if you only need to set the first column fixed) is setting `[nzWidthConfig]="['65px']"`

But I actually need both the first and last column fixed in size.

**Comment by vthinkxie** [comment]
Hi @mbrainiac @JoniVR 
this issue should be fixed in the latest version, please check https://stackblitz.com/edit/ng-zorro-antd-ivy-lvzwtc?file=src/app/app.component.ts
feel free to open a new issue if I miss anything, thanks for reporting this.
