### ISSUE TITLE
Animations inside the table row cells

### ISSUE THREAD

**Issue by desprit** [NG-ZORRO/ng-zorro-antd#5071]
### Reproduction link
[https://stackblitz.com/edit/angular-9-0-0-rc-1-aolgca](https://stackblitz.com/edit/angular-9-0-0-rc-1-aolgca)

### Steps to reproduce
Switch between "Body" and "Test" links.

### What is expected?
Rows get rendered without animation.

### What is actually happening?
ng-switch goes from disabled state to enabled, select boxes do some weird movements

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | Chrome, Firefox |

---
There are two key steps to reproduce the bug:
1. Table data has to be initialized with delay (even 0 second timeout works)
2. One of the table cells must contains a select box
In the body.component.ts try changing the logic inside ngOnInit. Uncomment commented block and comment uncommented. If setTimeout is not used, table renders correctly.
Or try to remove select box from table template. In that case table renders fine as well.
I couldn't fully re-produce behavior that I get when running it locally but for me it also happens when instead of a select box I add a button with dropdown-menu to the table. The whole row wiggles during initial rendering.

**Comment by vthinkxie** [comment]
don't forget to use trackBy: trackByFn when using ngFor

**Comment by desprit** [comment]
@vthinkxie 

What did you close it? `trackBy` is a good advice in general but first of all this is a "minimal" example to reproduce the issue. And secondly `trackBy` doesn't fix this issue.

**Comment by vthinkxie** [comment]
hey @desprit 
you can track this https://github.com/angular/angular/issues/34718
the router animation bug is caused by angular animations

**Comment by desprit** [comment]
@vthinkxie thank you! I may be wrong but when I updated all my ngzorro and angular related modules to the latest versions some of the transitions bugs gone. Anyways, thanks for the link, hope they'll release the fix soon.
