### ISSUE TITLE
nz-tree nzExpandAll属性无效

### ISSUE THREAD

**Issue by amoycode** [NG-ZORRO/ng-zorro-antd#5075]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-bvb6hr](https://stackblitz.com/edit/ng-zorro-antd-start-bvb6hr)

### Steps to reproduce
设置nzExpandAll

### What is expected?
节点全部展开

### What is actually happening?
1 节点没有展开
2 左侧箭头显示错误
3 node的缩进似乎不正常

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | chrome 80.0.3987.163 |

**Comment by simplejason** [comment]
Do not set `nzExpandAll` multiple times:
```html
<nz-tree
    [nzData]="nodes" 
    nzCheckable
    nzMultiple
    [nzExpandAll]="false" // Remove this line
    [nzCheckedKeys]="defaultCheckedKeys"
    [nzExpandAll]="true"
    [nzSelectedKeys]="defaultSelectedKeys"
    (nzClick)="nzEvent($event)"
    (nzExpandChange)="nzEvent($event)"
    (nzCheckBoxChange)="nzEvent($event)">
</nz-tree>
```

**Comment by 232650413** [comment]
> Do not set `nzExpandAll` multiple times:
> 
> ```
> <nz-tree
>     [nzData]="nodes" 
>     nzCheckable
>     nzMultiple
>     [nzExpandAll]="false" // Remove this line
>     [nzCheckedKeys]="defaultCheckedKeys"
>     [nzExpandAll]="true"
>     [nzSelectedKeys]="defaultSelectedKeys"
>     (nzClick)="nzEvent($event)"
>     (nzExpandChange)="nzEvent($event)"
>     (nzCheckBoxChange)="nzEvent($event)">
> </nz-tree>
> ```
不重复，好像也没有展开。我在数据里加了`expanded=“true”`

**Comment by simplejason** [comment]
I will close this issue due to inactivity and I didn't find error mentioned above.
Please file a new issue if you are encountering a similar or related problem.
