### ISSUE TITLE
ant-table-tbody>tr:nth-child(even) 对 sticky td 不起作用

### ISSUE THREAD

**Issue by billpeace** [NG-ZORRO/ng-zorro-antd#5078]
### Reproduction link
[https://stackblitz.com/edit/angular-4c7vh3-qlxidh?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-4c7vh3-qlxidh?file=src/app/app.component.ts)

### Steps to reproduce
看链接，

### What is expected?
和8.X版本一样，sticky td 也有能不同的background-color

### What is actually happening?
sticky td 不起作用

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.0 |
| Browser | chrome  81.0.4044.113 |

**Comment by vthinkxie** [comment]
css 权重问题，与框架无关，请参照任意 css 教程
