### ISSUE TITLE
Not able to dynamically hide the tooltip based on the condition

### ISSUE THREAD

**Issue by sivaecekrr** [NG-ZORRO/ng-zorro-antd#5087]
### Reproduction link
[https://stackblitz.com/edit/angular-mjbd3a?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-mjbd3a?file=src/app/app.component.ts)

### Steps to reproduce
In the example click on the VISIBLE button, when the visible is false then it should not show the tooltip and if visible is true, then it show the tooltip.

### What is expected?
should show/hide the tooltip dynamically. In previous version, it was working.

### What is actually happening?
Current version its not working as expected.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | Chrome 81 |

**Comment by wendellhu95** [comment]
This [PR](https://github.com/NG-ZORRO/ng-zorro-antd/pull/4653) also helps to solve the problem.

**Comment by sivaecekrr** [comment]
Thank you for fixing this. 👍
