### ISSUE TITLE
页码组件是否考虑增加首页显示

### ISSUE THREAD

**Issue by genhaodegenhao** [NG-ZORRO/ng-zorro-antd#5089]
注意：不是用 https://ng.ant.design/issue-helper/#/zh 创建的 issue 会被立即关闭。

页码组件是否考虑增加首页显示，例如：首页 1 2 3 下一页

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/pagination/zh#components-pagination-demo-total

**Comment by genhaodegenhao** [comment]
我看这个api了，知道可以设置上一页，我的意思是设置首页，不仅仅改变文字，比如我在第6页，点击首页到第一页，我看源码；里好像没有这个

**Comment by vthinkxie** [comment]
ng-template里面可以设定任意的模板和逻辑，实现你想要的功能多加一个(click)就可以实现

官网展示的永远都是demo，给用户展示的都是拓展的方法，而不是把用户业务中所有可能碰到的场景的代码都写好，这是不可能是实现的

**Comment by genhaodegenhao** [comment]
多谢
