### ISSUE TITLE
Problem with z-index in nz-modal.

### ISSUE THREAD

**Issue by masatada-kurihara** [NG-ZORRO/ng-zorro-antd#5091]
### Reproduction link
[https://stackblitz.com/edit/angular-5q7vdk](https://stackblitz.com/edit/angular-5q7vdk)

### Steps to reproduce
Implement nz-modal as guided.
Show modal.

### What is expected?
The modal is displayed in the forefront.

### What is actually happening?
The backdrop is shown in front of the modal.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | Chrome81 |

**Comment by hsuanxyz** [comment]
The class name is not bound on non-ivy mode, it will be fixed via #5090

**Comment by BrsJsk** [comment]
I have the same issue.

**Comment by vthinkxie** [comment]
close via #5090
