### ISSUE TITLE
nz-date-picker/Not able to enter date (with keyboard) with custom format

### ISSUE THREAD

**Issue by rockcoolt** [NG-ZORRO/ng-zorro-antd#5094]
### **Reproduction link**
https://stackblitz.com/edit/angular-2s3jch

### **Steps to reproduce**
Try to enter a date with keyboard (date format: 21/04/2020)

### **What is expected?**
The date you entered should be selected

### **What is actually happening?**
Date is no selected

**Comment by wenqi73** [comment]
@rockcool This feature is supported when you provide `NZ_DATE_LOCALE`. https://ng.ant.design/docs/i18n/en#how-to-format-a-date-using-date-fns

**Comment by rockcoolt** [comment]
Thank you !
