### ISSUE TITLE
Edge浏览器中，table的固定列（如nzLeft）边框消失

### ISSUE THREAD

**Issue by ai977313677** [NG-ZORRO/ng-zorro-antd#5099]
### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
使用edge打开官方文档，查看虚拟滚动demo，可以看到边框消失的现象，https://ng.ant.design/#components-table-demo-virtual

### What is expected?
边框与chrome和Firefox中的表现一致，可以正常显示

### What is actually happening?
边框消失

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362" |

---
原本是在7.5版本上发现的，但是在9.0的文档中依旧存在该情况
经查，是position:sticky导致的这个问题。

**Comment by vthinkxie** [comment]
注意：固定列通过 sticky 实现，不支持 sticky 的浏览器会自动降级成横向滚动

**Comment by ai977313677** [comment]
> 固定列通过 sticky 实现，不支持 sticky 的浏览器会自动降级成横向滚动

但问题是edge现在支持sticky，只是在edge中边框显示的有问题

![Edge浏览器表现](https://user-images.githubusercontent.com/15992800/80090375-fd9e8d00-8591-11ea-89c1-3401b922acb6.png)

![Edge浏览器支持标签](https://user-images.githubusercontent.com/15992800/80090454-1e66e280-8592-11ea-8054-0480f96b8682.png)

![Chrome浏览器表现](https://user-images.githubusercontent.com/15992800/80090173-aef0f300-8591-11ea-843e-e648500c5bfc.png)

**Comment by vthinkxie** [comment]
react 版本也有这个问题吗？
https://ant.design

**Comment by ai977313677** [comment]
> react 版本也有这个问题吗？
> https://ant.design

angular和react都存在这个问题，但是Vue就没有这个问题。

**Comment by vthinkxie** [comment]
> > react 版本也有这个问题吗？
> > https://ant.design
> 
> angular和react都存在这个问题，但是Vue就没有这个问题。

vue 应该还没有同步到 4.0 规范，能帮忙直接到 react 那边提一个issue吗，样式修复我们有机器人会直接同步过来

**Comment by ai977313677** [comment]
> 
> 
> > > react 版本也有这个问题吗？
> > > https://ant.design
> > 
> > 
> > angular和react都存在这个问题，但是Vue就没有这个问题。
> 
> vue 应该还没有同步到 4.0 规范，能帮忙直接到 react 那边提一个issue吗，样式修复我们有机器人会直接同步过来

在react那边提issue了
