### ISSUE TITLE
nz-time-picker组件中 ngModel 类型明明是Date却出现警告信息

### ISSUE THREAD

**Issue by itning** [NG-ZORRO/ng-zorro-antd#5100]
### Reproduction link
[https://stackblitz.com/edit/angular-x1ty2w-qecpnp?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-x1ty2w-qecpnp?file=src/app/app.component.ts)

### Steps to reproduce
控制台警告
`[NG-ZORRO]:
Non-Date type is not recommended for time-picker, use "Date" type`

### What is expected?
无警告

### What is actually happening?
有警告

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | Chrome(x64) 81.0.4044.113 |

---
`checkTimeUpdate:Date;`的类型明明是`Date`，但是还是显示警告信息

**Comment by hsuanxyz** [comment]
@wenqi73 `undefined | null` 应该是被允许的默认值
