### ISSUE TITLE
NzQueryParams of NzTable is called with delay (~300ms)

### ISSUE THREAD

**Issue by Chaniro** [NG-ZORRO/ng-zorro-antd#5113]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-bdsixw](https://stackblitz.com/edit/ng-zorro-antd-start-bdsixw)

### Steps to reproduce
In the linked StackBlitz, switch to another page of the table and look at "Last delay : X" at the top of the page.

### What is expected?
Almost no delay between the user's click and the call to nzQueryParams.

### What is actually happening?
There is a delay between the user's click and the call to nzQueryParams (nzQueryParams_call_time - last_click_time_on_document ~= 300)

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | Chrome 81 |

**Comment by vthinkxie** [comment]
this works as intend? is there any reason you want to remove the denounce?

**Comment by Chaniro** [comment]
There is no such delay in the [component's documentation](https://ng.ant.design/components/table/en) in the client side sorting/paging (nzCurrentPageDataChange for example, it's intended I guess).
I think this debounce should be configurable.
