### ISSUE TITLE
[9.x:nz-table] throw `StaticInjectorError`

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#5122]
## 重现

https://stackblitz.com/edit/angular-eh14r2?file=src/app/app.component.ts

若将 `<tbody></tobdy>` 放在某个 `<ng-template>` 下，且打开 `nzExpand` 时会抛出

```
StaticInjectorError(AppModule)[NzTableFixedRowComponent -> NzTableStyleService]:
```

>> PS: 急！

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-eh14r2-zedyzt?file=src/app/app.component.ts
必须放到tbody 内部，因为所有的expand需要获得table的实际宽度

**Comment by cipchk** [comment]
@vthinkxie 我建议可以考虑
