### ISSUE TITLE
异步获取tree数据，tree显示异常

### ISSUE THREAD

**Issue by BetterThanU1207** [NG-ZORRO/ng-zorro-antd#5124]
### Reproduction link
[https://stackblitz.com/edit/angular-7sa87q-fiyw3q](https://stackblitz.com/edit/angular-7sa87q-fiyw3q)

### Steps to reproduce
重现链接已暴露问题

### What is expected?
正常显示tree所有节点并且全部展开，每个节点前的复选框按照[nzCheckedKeys]的变量被选中。

### What is actually happening?
不能显示tree

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | Google Chrome版本 81.0.4044.92 |

---
实际使用是subscribe订阅后台tree数据，此处使用setTimeout复现，不知是否妥当

**Comment by simplejason** [comment]
目前tree数据更新存在顺序（在重构中），建议先赋值nzData后赋值其他属性

**Comment by BetterThanU1207** [comment]
已按照建议进行修改，没有得到解决

**Comment by simplejason** [comment]
> 已按照建议进行修改，没有得到解决

你 setTimeout 和赋值都不在一个周期内，注意一下数据设置顺序，或者提供最新的复现链接

**Comment by BetterThanU1207** [comment]
非常感谢，问题已得到解决
