### ISSUE TITLE
nz-button-group has visual issue if one of buttons are wrapped into span

### ISSUE THREAD

**Issue by mind-blowing** [NG-ZORRO/ng-zorro-antd#5125]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-vzjpfc](https://stackblitz.com/edit/ng-zorro-antd-start-vzjpfc)

### Steps to reproduce
Create nz-button-group and wrap one of buttons into span.

### What is expected?
No visual issues.

### What is actually happening?
First button is moved on 1-2px bellow expected row.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | Chromium 81.0.4044.113 |

---
There were no such issues at least in version 8.2.1.

**Comment by vthinkxie** [comment]
the extra DOM is supported insert inside the ng-zorro-antd nested component, it will cause the style broken.

**Comment by mind-blowing** [comment]
I'm sorry, but I didn't understood you, can you please provide example of how to fix this issue?

All that I want to do is to be able disable button inside button group and add tooltip with explanation of why it is disabled, to do this I'm using suggested by you approach with wrapping disabled button into a span and in version 8.2.1 such approach was without any issues, but now when I'm migrating to version 9.0.2 I have the issue.

```
<nz-button-group>
  <button nzTooltipTitle="Edit"
          nz-tooltip
          nz-button nzType="default">
    <i nz-icon nzType="file-text" nzTheme="outline"></i>
    Details
  </button>
  <span nzTooltipTitle="Edit is disabled because ..."
        nz-tooltip>
    <button [disabled]="true"
            nz-button nzType="default">
      <i nz-icon nzType="edit" nzTheme="outline"></i>
    </button>
  </span>
</nz-button-group>
```

**Comment by mind-blowing** [comment]
Here is example with usage of version  `"ng-zorro-antd": "9.0.2"` and there are no issues https://stackblitz.com/edit/ng-zorro-antd-start-nycwt2.

**Comment by vthinkxie** [comment]
I think it is a basic CSS issue, when you want to insert any inline-block element besides a block element, you need to make it vertical-align: bottom

https://stackblitz.com/edit/ng-zorro-antd-start-g9wgsl?file=src/styles.css

**Comment by mind-blowing** [comment]
@vthinkxie , thank you for the help with suggestion of how to fix this issue.

From my point of view solution looks more like workaround, and issue looks more like regression bug, since in version `8.2.1` there were no such issues, but it is of course up to you to decide is this a bug or not.

**Comment by vthinkxie** [comment]
Hi @mind-blowing 
thanks for reporting this, I think it is not a bug since the nested DOM style is not stable and safe between different version when the style update, users may need to adjust these minor changes of styles in this situation.

**Comment by mind-blowing** [comment]
Thanks, it's good to know and I'm agree with you that such small issues is not a big deal and they can be fixed on our side, anyway thanks for the great product.
