### ISSUE TITLE
nz-descriptions-item nzTitle的模板功能无效

### ISSUE THREAD

**Issue by amoycode** [NG-ZORRO/ng-zorro-antd#5127]
### Reproduction link
[https://stackblitz.com/edit/angular-sa2qyz](https://stackblitz.com/edit/angular-sa2qyz)

### Steps to reproduce
<nz-descriptions-item [nzTitle]="tpl">

### What is expected?
nzTitle由指定的模板进行渲染

### What is actually happening?
[object Object]

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | 81.0.4044.122 |

**Comment by edxxu** [comment]
same issue

**Comment by wendellhu95** [comment]
@edxxu Sorry, we do not have resources to maintain deprecated major versions. Please upgrade to 9.x.
