### ISSUE TITLE
Ivy Disabled Production build results in: Directive NzAvatarComponent, The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.

### ISSUE THREAD

**Issue by Endran** [NG-ZORRO/ng-zorro-antd#5138]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-adrd51](https://stackblitz.com/edit/ng-zorro-antd-start-adrd51)

### Steps to reproduce
```
yarn install 
ng build --prod
```

### What is expected?
A successful build

### What is actually happening?
A failing build, with error:
```
ERROR in (1,1): Directive NzAvatarComponent, The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
node_modules/ng-zorro-antd/list/ng-zorro-antd-list.d.ts.NzListItemMetaAvatarComponent.html(3,7): Directive NzAvatarComponent, The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | Chrome |

---
The repo provided for the stackblitz is freshly created Angular 9 project, with all defaults.

Then nz was added using `ng add ng-zorro-antd`, and we added a table so that we have some components going on.

Next we disable ivy in `tsconfig.json`, by means of `"angularCompilerOptions": { ..."enableIvy": false  }`

**Comment by vthinkxie** [comment]
Hi @Endran 
you need to disable strictTemplates in the current version.
plz track https://github.com/NG-ZORRO/ng-zorro-antd/pull/4994

**Comment by ismezy** [comment]
我也碰到同样的问题，添加strictTemplates: false时还是一样的错误，要禁用fullTemplateTypeCheck才行。
