### ISSUE TITLE
angular 5.0.0 waring

### ISSUE THREAD

**Issue by lizhihui0215** [NG-ZORRO/ng-zorro-antd#514]
I have upgrade my angualr version up to 5.0.0, that given me the waring below.

```
npm WARN ng-zorro-antd@0.5.5 requires a peer of @angular/animations@^4.0.0 but none was installed.
npm WARN ng-zorro-antd@0.5.5 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN ng-zorro-antd@0.5.5 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN ng-zorro-antd@0.5.5 requires a peer of @angular/forms@^4.0.0 but none was installed.
```
somebody tell is that ok?

**Comment by cipchk** [comment]
**SUGGEST:** there is no need to `peerDependencies` add Angular related package. By default, it has been installed via Angular Cli.

**Comment by cipchk** [comment]
hope ASAP release compatible Angular5 version.

i can hardly wait!!!

**Comment by vthinkxie** [comment]
not compatible with v5 yet, will upgrade after cdk release.

**Comment by liepeng328** [comment]
我升级到angular5也发现这个了，但是不影响项目使用。不报错。只是警告
