### ISSUE TITLE
nz-tree do not expand correctly in nz-dropdown

### ISSUE THREAD

**Issue by KellenHe** [NG-ZORRO/ng-zorro-antd#5143]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-wtxi8h](https://stackblitz.com/edit/ng-zorro-antd-start-wtxi8h)

### Steps to reproduce
set nz-tree nzExpandAll=true in nz-dropdown，normal for the first time, the second time nz-tree is not expand.
1. 在nz-dropdown中使用nz-tree，并设置tree的属性nzExpandAll=true
2.第一次打开nz-dropdown，tree正常展开，第二次打开nz-dropdown，tree没有正常展开。

### What is expected?
期望nz-tree可以正常展开

### What is actually happening?
nz-tree在第二次打开nz-dropdown后无法正常展开

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome 78.0.3904.97 |

**Comment by vthinkxie** [comment]
ref https://github.com/angular/angular/issues/24041

duplicated https://github.com/NG-ZORRO/ng-zorro-antd/issues/4576
