### ISSUE TITLE
nz-tree needs to be refactored to solve the problem of asynchronous operation for data synchronization

### ISSUE THREAD

**Issue by simplejason** [NG-ZORRO/ng-zorro-antd#5152]
## What problem does this feature solve?
Display data correctly whenever any property is set. For now, we must set `nzData` first, if `nzExpandedKeys` or any other property is set before `nzData`, it will not work as expected.

## What does the proposed API look like?
none

**Comment by AffanAzeem7** [comment]
can we remove children word from our nznode data and used  another word for that having array like that
  nodes = [
    {
      
      title: 'xyz',
      key: '0-0',
      Resellers: [
        {
          title: 'Inhouse',
          key: '0-0-0',
          
          Merchants: [
            { title: 'abc', 

            key: '0-0-0-0' ,
          }


            
          ]
          
        }
  ]
},

];
and the data is coming from an backend
kindly help
