### ISSUE TITLE
NzModalService 中使用talble

### ISSUE THREAD

**Issue by feijiing** [NG-ZORRO/ng-zorro-antd#516]
使用 NzModalService 打开一个页面，页面里面使用了nz-table，我再open函数的参数李加了，  footer: false,
但是还是会有foot儿显示

**Comment by feijiing** [comment]
代码如下：

  _updateProject(project: Project) {
    console.log('修改对象信息：' + project.name);
    this.modalService.open({
      title: '项目修改',
      content: ProjectUpdateComponent,
      onOk: () => {
        this._refreshData();
      },
      onCancel: () => {
        console.log('Click update');
      },
      maskClosable: false,
      width: '100%',
      footer: false,
      componentParams: {_updateProject: project}
    });
  }

**Comment by feijiing** [comment]
表格代码如下：
 <nz-table #nzTable [nzDataSource]="_selectedMember" nzShowFooter="false">
    <thead nz-thead>
    <tr>
      <th nz-th><span>姓名</span></th>
      <th nz-th><span>手机</span></th>
      <th nz-th><span>邮箱</span></th>
      <th nz-th><span>删除</span></th>
    </tr>
    </thead>
    <tbody nz-tbody>
    <tr nz-tbody-tr *ngFor="let data of nzTable.data">
      <td nz-td>
        <a>{{data.name}}</a>
      </td>
      <td nz-td>{{data.mobile}}</td>
      <td nz-td>{{data.email}}</td>
      <td nz-td>
        <a (click)="_delMem(_id,data.id)">删除</a>
      </td>
    </tr>
    </tbody>
  </nz-table>

**Comment by vthinkxie** [comment]
footer:false work well in my project, can you reproduce your error here http://plnkr.co/edit/tpl:sKWy62

**Comment by feijiing** [comment]
我是再打开的页面使用了 nz-table 组件，就会出现footer，使用其他组件没事。

**Comment by vthinkxie** [comment]
@feijiing please check if there is any error message in your dev tools.

**Comment by vthinkxie** [comment]
fixed in version 0.7.0
