### ISSUE TITLE
Show table again after hiding table lose column width

### ISSUE THREAD

**Issue by xxx0305102120** [NG-ZORRO/ng-zorro-antd#5160]
### Reproduction link
[https://stackblitz.com/edit/angular-hgjmxe](https://stackblitz.com/edit/angular-hgjmxe)

### Steps to reproduce
click show/hidden button, Table column width is not the initial width

### What is expected?
Table column width maintain initial width

### What is actually happening?
Table columns are not the width initially set

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36 |

**Comment by 232650413** [comment]
昨天我也发现有这个bug ，以为下次修复，今天看更新了，没修复到这个问题。哈哈

**Comment by CristoAtlas** [comment]
I have the same problem, do not you think to solve it?

**Comment by 232650413** [comment]
我也没有解决，待更新却未更新。主要我里面许多路由缓存下来了，所以那个问题很严重。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CristoAtlas"<notifications@github.com&gt;; 
发送时间: 2020年6月2日(星期二) 下午5:56
收件人: "NG-ZORRO/ng-zorro-antd"<ng-zorro-antd@noreply.github.com&gt;; 
抄送: "DeathGhost"<232650413@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [NG-ZORRO/ng-zorro-antd] Show table again after hiding table lose column width (#5160)





 
I have the same problem, do not you think to solve it?
