### ISSUE TITLE
Modal not closing properly if used with ngIf

### ISSUE THREAD

**Issue by BrsJsk** [NG-ZORRO/ng-zorro-antd#5162]
### Reproduction link
[https://stackblitz.com/edit/angular-5q7vdk-qgyff1](https://stackblitz.com/edit/angular-5q7vdk-qgyff1)

### Steps to reproduce
- Create modal
- Add ngIf to it

### What is expected?
Modal is closed properly

### What is actually happening?
Modal is not closed fully

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Chrome 81.0.4044.122 |

---
This is usefull if we need to re-render the component when opening the modal and to use ngOnInit lifecycle method instead of ngOnChanges

**Comment by hsuanxyz** [comment]
Will be fixed via #5161
