### ISSUE TITLE
docs: support upload image to search icon

### ISSUE THREAD

**Issue by danranVm** [NG-ZORRO/ng-zorro-antd#5170]
## What problem does this feature solve?
easier to find icons.

## What does the proposed API look like?
https://ant.design/components/icon-cn/

**Comment by wendellhu95** [comment]
hhh. I will do that.

**Comment by ywager** [comment]
HI @wendellhu95. Is this feature in your plan? If not, can I implement this feature? :)

**Comment by wendellhu95** [comment]
> HI @wendellhu95. Is this feature in your plan? If not, can I implement this feature? :)

Appreciate it! Looking forward to you contribution. :heart:
