### ISSUE TITLE
Cannot use custom component with ModalService warning/info/error/success methods

### ISSUE THREAD

**Issue by majakovacevic** [NG-ZORRO/ng-zorro-antd#5172]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-modal-componet](https://stackblitz.com/edit/ng-zorro-antd-modal-componet)

### Steps to reproduce
Follow the guide to create warning modal with Modal's service and pass Component as nzContent.

### What is expected?
Modal should be opened with provided content component or breaking change should be added to release notes for version where it was introduced.

### What is actually happening?
Modal is opened without content resolved from component and console error is present:

```Error: The confirm mode does not support using component as content```

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | All |

---
This was noticed while performing migration to 9.1.0. It was working in version 8.5.2.

**Comment by hsuanxyz** [comment]
Version 8.x  it shouldn't be supported, but it can work unexpectedly because of an error of judgment.

Should we officially support it on version 9.x ? @vthinkxie
