### ISSUE TITLE
Circle button icon alignment

### ISSUE THREAD

**Issue by levitatejay** [NG-ZORRO/ng-zorro-antd#5173]
### Reproduction link
[https://stackblitz.com/edit/angular-uf8sqb?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-uf8sqb?file=src/app/app.component.ts)

### Steps to reproduce
It is easier to see the problem on Firefox or if you increase browser zoom more than 100%

### What is expected?
Icons inside Button with nzShape="circle" should be aligned in the center of the button

### What is actually happening?
Icons are not aligned in the center

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Chrome & Firefox |

**Comment by levitatejay** [comment]
Here are some screenshots:

![image](https://user-images.githubusercontent.com/13340760/80550260-a0805c80-8a13-11ea-9e02-70110152ec08.png)

![image](https://user-images.githubusercontent.com/13340760/80550281-b130d280-8a13-11ea-9f70-bbbeea227be0.png)

![image](https://user-images.githubusercontent.com/13340760/80550310-d32a5500-8a13-11ea-9627-0a32bfa6838c.png)

**Comment by whittssg** [comment]
Is it me or is the square button with just an icon not centered as well? (the icon appears to be too low):
![image](https://user-images.githubusercontent.com/6453857/84026084-a8101b00-a95a-11ea-8c50-9c51c113f9d8.png)

**Comment by karocksjoelee** [comment]
any update on this ?

**Comment by hsuanxyz** [comment]
Should have been fixed in the latest version.

**Comment by ronny1020** [comment]
same here, I think it's  not fixed on version 11.2.0 .

**Comment by RaphiStein** [comment]
The problem for me was a conflict with Bootstrap CSS
(I don't know what exactly though, I didn't need Bootstrap at all so I just removed it)

**Comment by chrised123** [comment]
@RaphiStein this seem to fix the issue. Thanks for the help. I accidentally import bootstrap in every fresh project. Bootstrap became a muscle memory.
