### ISSUE TITLE
Using nzLeft/nzRight in ng-template not working when used in ngTemplateOutlet

### ISSUE THREAD

**Issue by renzabergos** [NG-ZORRO/ng-zorro-antd#5179]
### Reproduction link
[https://stackblitz.com/edit/angular-cdyoxq?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-cdyoxq?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
* move horizontal scroll from left to right

### What is expected?
`nzLeft`/`nzRight` directives that are added in `<td>` inside an `ng-template` must also reflect when used in the `ng-container`'s *`ngTemplateOutlet`

### What is actually happening?
nzLeft and nzRight are ignored.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Chrome 81.0.4044.122 - Mac OS |

---
I am using actually using the `ng-template` from another component, but the issue can be replicated as seen in the link.

**Comment by vthinkxie** [comment]
there is no way to get component inside the ng-template with ContentChildren with current design of angular now

blocked by https://github.com/angular/angular/issues/8563
