### ISSUE TITLE
Variable color support for nzRate

### ISSUE THREAD

**Issue by thinkdj** [NG-ZORRO/ng-zorro-antd#5181]
## What problem does this feature solve?
Currently, the rating colors are in the CSS and cannot be changed dynamically per-component. It would be great to have a per-component Input() for making color a variable
## What does the proposed API look like?
` <nz-rate nzColor="#8EB309"></nz-rate>`

**Comment by wendellhu95** [comment]
IMHO it's not necessary to add an API like that. See the [demo](https://codesandbox.io/s/crimson-glitter-ctlho?file=/src/app/app.component.ts).

**Comment by thinkdj** [comment]
Hi @wendellhu95, I see you have added 
```
.red-rate .ant-rate {
  color: red;
}
```

I am presently following a similar approach. Actually, there are three places you need to change (you missed half-star and active cases)

```
.rate-color-good .ant-rate-star-half {
    background: linear-gradient(to right, #abe200 50%, #f0f0f0 50%) !important;
}
.rate-color-good .ant-rate-star.ant-rate-star-full {
    background: #abe200;
}
.rate-color-good .ant-rate-star.ant-rate-star-active {
    background: #abe200;
}
```

I am favoring a variable against this hand-coded approach, as we need to create the above lines of code _per-color_ choice. By using a variable, we are not bound to limited colors and css changes too.

**Comment by wendellhu95** [comment]
Glad to help. 😄
