### ISSUE TITLE
Datepicker ignores NZ_DATE_LOCALE date format 

### ISSUE THREAD

**Issue by daxilshah** [NG-ZORRO/ng-zorro-antd#5182]
### Reproduction link
[https://stackblitz.com/edit/angular-2s3jch-t1clnb](https://stackblitz.com/edit/angular-2s3jch-t1clnb)

### Steps to reproduce
1. Set `NZ_DATE_LOCALE` to use `enUS` locale
2. Do not pass any custom formats via `nzFormat` for `nz-date-picker`

### What is expected?
1. Datepicker should get `nzFormat` based on locale provided.
2. While output, DatePipe should also consider the same format fetched from locale provided.

### What is actually happening?
Datepicker fallbacks to default `nzFormat` which is `yyyy-MM-dd` and ignores the date format provided via global configuration of provider using `NZ_DATE_LOCALE`. While output, DatePipe also ignores the format fetched from system locale.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Version 81.0.4044.122 (Official Build) (64-bit) |

**Comment by wenqi73** [comment]
Same with #3491.

**Comment by pafflu** [comment]
Still an issue with 9.3 for me, any updates?
Does NZ_DATE_LOCALE do anything for date-pickers at the moment?

**Comment by hsuanxyz** [comment]
duplicate of #3491
