### ISSUE TITLE
NzCarousel is taking too much height eventhough the content inside that is less

### ISSUE THREAD

**Issue by haribaskarvr** [NG-ZORRO/ng-zorro-antd#5183]
The issue which is not created via https://ng.ant.design/issue-helper/#/en will be closed immediately.
Create a 

**Reproduction link:** 
https://stackblitz.com/edit/angular-85716b
**Steps to Reproduce:**
Give some big content inside a nzrow and view the change.
**Expectation:**
Eventhough the text is 2 lines it is taking very high height px.

![image](https://user-images.githubusercontent.com/50363011/80636417-0f44d080-8a7b-11ea-930f-186fd88b6af4.png)

**Comment by wendellhu95** [comment]
Don't know what exactly you were referring to... Care for any more specific explanations?
