### ISSUE TITLE
nz-modal vertical layout

### ISSUE THREAD

**Issue by egalley** [NG-ZORRO/ng-zorro-antd#5187]
### Reproduction link
[https://stackblitz.com/edit/angular-jkfbas](https://stackblitz.com/edit/angular-jkfbas)

### Steps to reproduce
Use the modal sample and add form vertical layout. Put one component with label and see the result.

### What is expected?
Same as form in non modal.

### What is actually happening?
Does not work

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Chrome Version 81.0.4044.129 |

---
Is there a way to make modal draggable only by title with cdkDrag ?
Thank you.

**Comment by vthinkxie** [comment]
nz-form could only work with form
https://stackblitz.com/edit/angular-yu3u6u?file=src/app/app.component.ts

**Comment by egalley** [comment]
Bad new it was working like a charm in release 8.5.
There are too many break and isssues with this release. I'm going to try to downgrad or to find an other library. I can not spend many days trying to fix issues.
