### ISSUE TITLE
nzFormat in DatePicker doesn't parse manual value in input

### ISSUE THREAD

**Issue by nitrexx** [NG-ZORRO/ng-zorro-antd#5188]
### Reproduction link
[https://stackblitz.com/edit/angular-qetubt](https://stackblitz.com/edit/angular-qetubt)

### Steps to reproduce
Set custom nzFormat to "dd.MM.yyyy" and try to manually fill up to the DatePicker input.

### What is expected?
Parse this date after press Enter a set value to the DatePicker .

### What is actually happening?
Nothing, no parse, no event, exactly nothing.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome Version 81.0.4044.122 (Official Build) (64-bit) |

---
The same problems from 2018:
* https://github.com/NG-ZORRO/ng-zorro-antd/issues/3976
* https://github.com/NG-ZORRO/ng-zorro-antd/issues/3491
* https://github.com/NG-ZORRO/ng-zorro-antd/issues/2492

**Comment by daxilshah** [comment]
@nitrexx  Did you check this? [#5094](https://github.com/NG-ZORRO/ng-zorro-antd/issues/5094)

**Comment by nitrexx** [comment]
Yes, I did, but it still doesn't work.

https://stackblitz.com/edit/angular-qetubt-6cskmr

**Comment by wenqi73** [comment]
@nitrexx 9.0.0 has supported this, plz update.

**Comment by grapecitySagar** [comment]
Still, there is an issue with typing date manually into a date-picker. When the date-picker is getting focussed, the calendar would open, and then it works fine whether you type a date or select one from the picker. But when you re-click the input so the picker gets away and then when you type a date in but it won't be changed.

I also recorded a video on the following link that can help to reproduce the issue.
https://1drv.ms/v/s!AsAm4FCl_e_nmgQx3Evxa1O1AZ8z

**Comment by sainisagar310** [comment]
Still, there is an issue with typing date manually into a date-picker. When the date-picker is getting focused, the calendar would open, and then it works fine whether you type a date or select one from the picker. But when you re-click the input so the picker gets away and then when you type a date in but it won't be changed.

I also recorded a video on the following link that can help to reproduce the issue.
https://1drv.ms/v/s!AsAm4FCl_e_nmgQx3Evxa1O1AZ8z

**Comment by wenqi73** [comment]
@sainisagar310 Thanks for reporting this, please track #5284.
