### ISSUE TITLE
Content projection into In-Component modal

### ISSUE THREAD

**Issue by sainisagar310** [NG-ZORRO/ng-zorro-antd#5193]
I want to ask whether it is possible to inject the `ng-content` and a component together into a modal via `NzModalService.create` function.

Actually inside a modal component, I want to use `<ng-content select="[anElement]"></ng-content>`. I'm curious, whether it is possible or not.

**Comment by vthinkxie** [comment]
you can pass a TemplateRef as the component Input to the modalService.create(Component)
