### ISSUE TITLE
select在Table下显示异常

### ISSUE THREAD

**Issue by liweitao92** [NG-ZORRO/ng-zorro-antd#5198]
### Reproduction link
[https://ng-zorro-antd-start-nt9tza.stackblitz.io](https://ng-zorro-antd-start-nt9tza.stackblitz.io)

### Steps to reproduce
点击Edit, select宽度太小
![image](https://user-images.githubusercontent.com/30191996/81029710-8f729800-8eb8-11ea-93b6-0f2a83da45d9.png)

### What is expected?
正常显示

### What is actually happening?
宽度显示调小

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Edge |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-2jmbyy?file=src/app/app.component.css
修改一下css
