### ISSUE TITLE
nz-resizable 和table column sort功能，会存在同时触发，希望单独影响

### ISSUE THREAD

**Issue by billpeace** [NG-ZORRO/ng-zorro-antd#5199]
### Reproduction link
[https://stackblitz.com/edit/angular-rncvrd?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-rncvrd?file=src/app/app.component.ts)

### Steps to reproduce
table column，拖动resize-handle，使列宽度减少，就会同时触发列排序功能

### What is expected?
希望改变列宽度，不影响列排序功能

### What is actually happening?
减小列宽度，同时影响列排序功能

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | chrome 81.0.4044.129 |

**Comment by exenestecnico** [comment]
Im having this same issue. Any fix I can do on my end in the meantime?

**Comment by exenestecnico** [comment]
@billpeace found a simple solution. Posted it on [StackOverflow](https://stackoverflow.com/a/62121686/8714275)

**Comment by vthinkxie** [comment]
thanks for the link @exenestecnico 
closing
