### ISSUE TITLE
nz-menu-item支持根据路由自动高亮

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#52]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

在zn-menu-item中添加了路由后没法根据当前的默认路径自动高亮

## Expected behavior

在默认跳转到指定路径时routerLinkActive匹配的路由能够自动高亮

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shaodahong** [comment]
大兄弟，`routerLinkActive="ant-menu-item-selected"`就OK了呀

**Comment by shaodahong** [comment]
a标签的写法有问题，换个写法试试

**Comment by wanghaolu** [comment]
一样的，没起作用
![tim 20170817092500](https://user-images.githubusercontent.com/9586655/29392033-e02d1804-832d-11e7-981c-d1b8316556ed.png)

**Comment by vthinkxie** [comment]
@wanghaolu please check your code and https://angular.cn/guide/router for more detail. The method that @shaodahong provide is right.

**Comment by wanghaolu** [comment]
@shaodahong @vthinkxie 
我重现了这个问题，这个模块是通过lazy load加载的，在加载后就没法通过routerLinkActive="ant-menu-item-selected"来设置路由激活后的css，我发现仅限于这个名字的css class，随便改个名字都能应用成功。
![tim 20170818080621](https://user-images.githubusercontent.com/9586655/29438850-02651a84-83ec-11e7-88fa-3e68005717d8.png)
我尝试将nz-menu-item指令从<li>标签中移除后这个css class应用成功。我怀疑是nz-menu-item导致ant-menu-item-selected这个css应用失败。
![tim 20170818081108](https://user-images.githubusercontent.com/9586655/29438930-a523bec4-83ec-11e7-8dc6-08cec89dc78e.png)

**Comment by vthinkxie** [comment]
@wanghaolu please check the doc site's(https://ng.ant.design) source code:
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/showcase/app.component.html#L29
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/showcase/app.routing.module.ts

The doc site  also uses lazy load mode, and `routerLinkActive="ant-menu-item-selected"` works fine.

**Comment by wanghaolu** [comment]
但是你这个app.component并不是通过延迟加载的，我的意思是延迟加载的子模块中的menu上使用routerLinkActive设置为ant-menu-item-selected会无效。

**Comment by wanghaolu** [comment]
@vthinkxie 我已经新建了一个项目并复现了该问题，确认了在通过lazy load加载的模块中的menu上使用routerLinkActive="ant-menu-item-selected"无效。

**Comment by vthinkxie** [comment]
@wanghaolu bug confirm, thanks
We will try to fix it next version.

**Comment by zhhb** [comment]
another way to bind nzSelected or nzOpen is use the readonly prop isActive

angular doc below

```
<a routerLink="/user/bob" routerLinkActive #rla="routerLinkActive">
  Bob {{ rla.isActive ? '(already open)' : ''}}
</a>
```

and you can do like below (which could affect menu parent's selected)

```
<li nz-menu-item   routerLinkActive #rla="routerLinkActive" [nzSelected]="rla.isActive">
 // your links here 
</li>
<li  nz-submenu routerLinkActive #rla="routerLinkActive" [nzOpen]="rla.isActive">
 // your submenus here
</li>
```

**Comment by mbenedettini** [comment]
I'm going with @zhhb approach since it's more solid than relying on a class name

**Comment by therepo90** [comment]
@zhhb great solution, works with forloop also thanks
