### ISSUE TITLE
nz-table with fixed columns and *ngIf

### ISSUE THREAD

**Issue by alexbonair** [NG-ZORRO/ng-zorro-antd#5206]
### Reproduction link
[https://codesandbox.io/s/agitated-elbakyan-b3ylx?file=/src/app/app.component.ts](https://codesandbox.io/s/agitated-elbakyan-b3ylx?file=/src/app/app.component.ts)

As the stackblitz to fork from is v8.5.x. I forked your latest codesandbox for fixed columns example

### Steps to reproduce
It's reproducible by simply adding a *ngIf to a fixed column which is not the last/first in the table

### What is expected?
That it renders the table as before, as the *ngIf condition is true

### What is actually happening?
The browser almost freezes and this error appears:
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ant-table-cell-fix-right-first: false'. Current value: 'ant-table-cell-fix-right-first: true'.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | latest Chrome, FF, Safari |

**Comment by vthinkxie** [comment]
fixed by https://github.com/NG-ZORRO/ng-zorro-antd/commit/dc8c7e70c869b415cb55a072a77c1cfb704b7cb1
