### ISSUE TITLE
nz-select keyboard controls - focus the search/input field when the component is focused

### ISSUE THREAD

**Issue by asineath-dbhglobal** [NG-ZORRO/ng-zorro-antd#5208]
## What problem does this feature solve?
We would like the nz-select component to have keyboard functionality similar to a native HTML select. Currently, when the nz-select component (with nzShowSearch enabled) is focused by hitting Tab, the component is outlined in blue, but the text input is not focused. The user has to hit the Down button to focus the text/search field and begin typing, which they do not know to do because that is not the same as a native select element. The component is also not selecting the option they navigate to using the arrow buttons before hitting Tab; the user does not know they have to hit Enter to make a selection. As a result, users are only using the mouse to interact with our nz-select components, which is causing frustration.
## What does the proposed API look like?
 When the nz-select component is focused, open the dropdown list and focus the search/textbox if nzShowSearch is true. Also update the value of the nz-select when the user uses the up/down arrow buttons to navigate the options list.

**Comment by vthinkxie** [comment]
Hi we have updated some of the behavior of nz-select in next version, but we the keeps sync with ant design, the dropdown won't open automatically when focused, thanks for understanding.
> When the nz-select component is focused, open the dropdown list and focus the search/textbox if nzShowSearch is true.
