### ISSUE TITLE
NzMessageService doesn't work in angular 5 production mode 

### ISSUE THREAD

**Issue by jimmycarry** [NG-ZORRO/ng-zorro-antd#521]
In development mode NzMessageService can work; but when I make production for my production env, I found an some error so that my application don't work in my website; so I make production with sourcemap mode,I found NzMessageService caused this Error!  When I remove NzMessageService to my project  and my website work! please fix this problem in next version

**Comment by vthinkxie** [comment]
will be fixed in 0.6.0-rc.3
