### ISSUE TITLE
Fail to build library with fullTemplateTypeCheck on, when NzDatePickerComponent is used

### ISSUE THREAD

**Issue by highestop** [NG-ZORRO/ng-zorro-antd#5215]
### Reproduction link
[https://github.com/highestop/NzDemo](https://github.com/highestop/NzDemo)

### Steps to reproduce
Run `ng build` to build this Angular library and there will be a compiling error

### What is expected?
Build successfully

### What is actually happening?
Error in Directive NzDatePickerComponent: Property `picker` is protected and only accessible within class `NzDatePickerComponent` and its subclass

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Chrome Version 81.0.4044.129 |

---
- With a component simply using `nz-date-picker` in template
- With Ivy disabled (Cannot build a library in Ivy mode)
- With `fullTemplateTypeCheck` is ON. Turning it off will be an easy work-around, but not a perfect way :)
- With `strictTemplate` is already OFF

**Comment by wendellhu95** [comment]
Track #4994.
