### ISSUE TITLE
nz-badge: can't show nzCount in onpush mode

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#5216]
## 重现

https://codesandbox.io/s/nice-dirac-mrr7s?file=/src/app/app.component.ts:215-222

**Comment by nuonuoge** [comment]
because you use ```*ngIf="total != null"```

**Comment by cipchk** [comment]
@nuonuoge Yeah, i just mock data from http request, i have changed demo.

**Comment by hsuanxyz** [comment]
fixed via #5275
