### ISSUE TITLE
NzQueryParams of NzTable not called

### ISSUE THREAD

**Issue by zaideygrek** [NG-ZORRO/ng-zorro-antd#5219]
### **Reproduction link**
https://stackblitz.com/edit/ng-zorro-antd-start-kqwhjo

### **Steps to reproduce**
I encapsulate in a component nz-table and display the content (thead and tbody) by ng-content.
In the linked StackBlitz, click on the sort and look last NzQueryParams

### **What is expected?**
Call nzQueryParams

### **What is actually happening?**
There is no call to nzQueryParams

Environment | Info
-- | --
ng-zorro-antd | 9.0.2
Browser | Chrome 81

**Comment by vthinkxie** [comment]
the thead is queried by ContentChildren in the source code, which does not support nested `ng-content`.
if we add a `descendants: true`, it will cause a bug in nested table scenario.

**Comment by zaideygrek** [comment]
Ok, thanks for your reply
