### ISSUE TITLE
zorro打包后的js最大的2.6m，太大了，怎么处理？？？

### ISSUE THREAD

**Issue by liepeng328** [NG-ZORRO/ng-zorro-antd#522]
zorro打包后的js最大的2.6m，太大了，怎么处理？？？

![image](https://user-images.githubusercontent.com/19989280/32361590-d57b7b2e-c09c-11e7-9d0b-8753d01a5222.png)

**Comment by vthinkxie** [comment]
please read angular.cn and the doc https://github.com/angular/angular-cli/wiki/build carefully

**Comment by liepeng328** [comment]
首先感谢大佬的回复。刚入门，确实不太懂。
我的脚本是这样写的 

> First of all, thanks for the big brother's response. Just started, really do not understand.
My script is written like this

` "build-prod": "ng build -prod -base-href ./ --extract-css --build-optimizer"`
也就是

> that is

`ng build -prod -base-href ./ --extract-css --build-optimizer`
但是最大的还是1m多，如果服务端gizp之后还有500k，能不能再小一点？？
> But the biggest is 1m, if the server after gizp, there is 500K, can you be a little smaller?


![image](https://user-images.githubusercontent.com/19989280/32366371-cce4ac62-c0b8-11e7-8062-5086939953a1.png)
