### ISSUE TITLE
win10 自定义缩放导致的问题

### ISSUE THREAD

**Issue by yor1g** [NG-ZORRO/ng-zorro-antd#5222]
### Reproduction link
[https://stackblitz.com/none](https://stackblitz.com/none)

### Steps to reproduce
win10 自定义缩放 124%

1.Chrome 缩放会导致 Table 固定列头会不断计算并且变形 最后挤压在一起 Edge 没有
官网例子复现 https://ng.ant.design/components/table/zh#components-table-demo-fixed-columns-header

2.Chrome  Select 滚动到底部没有触发加载 Edge 没有
官网例子复现 https://ng.ant.design/components/select/zh#components-select-demo-scroll-load

之前 8.5的版本没有这样的问题

### What is expected?
Table 列不积压
Select 滚动到底部触发加载

### What is actually happening?
缩放会导致 Table 固定列头会不断计算并且变形 最后挤压在一起
Select 滚动到底部没有触发加载

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Chrome  81.0.4044.113 |

**Comment by yor1g** [comment]
补充截图
![20200507154222](https://user-images.githubusercontent.com/1337490/81267657-677e6280-9079-11ea-9006-b88cf58856ff.png)

**Comment by vthinkxie** [comment]
@yor1g 9.2.0 下还会有问题吗？帮忙确认一下

**Comment by yor1g** [comment]
@vthinkxie   问题依然存在

**Comment by hsuanxyz** [comment]
duplicate #4396

**Comment by yor1g** [comment]
> duplicate #4396

不对齐8就有的bug....   缩放变形是9才有的bug

**Comment by Renhj90520** [comment]
nzScroll只设置y, [nzScroll]="{ y: tableH + 'px' }", 如果浏览器窗口宽度小于每列nzWidth之和，则每行的高度不正常，和该问题的最终表现一致。 @vthinkxie 
![image](https://user-images.githubusercontent.com/7686919/90754066-028b0780-e30c-11ea-93f3-4c383ba290f5.png)
