### ISSUE TITLE
[nz-button]button 重构导致通过 nzType 自定义的按钮类型失效

### ISSUE THREAD

**Issue by renxia** [NG-ZORRO/ng-zorro-antd#5225]
## What problem does this feature solve?
如题，在 https://github.com/NG-ZORRO/ng-zorro-antd/commit/7d841a428a9e54ab220b14a26dbe1eab79267eb3 
这个提交中对按钮进行了重构。
以前对于 `nzType` 的样式绑定是这样的：`[`${prefixCls}-${this.nzType}`]: this.nzType,`，如今变成了这样的：`[`${prefixCls}-primary`]: this.nzType === 'primary'`

基于以前的实现方式，我们通过扩展 nzType 定义了一些自定义按钮样式，如今因为这个变更全部失效了。这对于我们来说是非常大的变动，开发了N年的项目中有大量相关应用。

## What does the proposed API look like?
对于新的实现方式来说，改变这种写法除了严格限定了按钮类型，并没有什么其它的好处。
故希望能够进行能够改回原来的样式绑定方式，或者给可行一个拓展接口方式。感谢！

**Comment by vthinkxie** [comment]
@renxia 可以通过自定义 nz-button directive 自行实现相关功能
