### ISSUE TITLE
Nz -table USES nzScroll. When the window shrinks, a horizontal scroll bar will appear

### ISSUE THREAD

**Issue by llkui** [NG-ZORRO/ng-zorro-antd#5227]
### Reproduction link
[https://stackblitz.com/edit/angular-hquq8a](https://stackblitz.com/edit/angular-hquq8a)

### Steps to reproduce
1、nz-table use [nzScroll]="{ y: '240px' }".

2、When the window shrinks, a horizontal scroll bar will appear

### What is expected?
When the window shrinks, the horizontal scroll bar should not appear, should adapt the width

### What is actually happening?
When the window shrinks, a horizontal scroll bar will appear

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Google Chrome 80.0.3987.132 |

**Comment by kunning** [comment]
I have the same issue, the column widths are not responsive when table width decrease (but the columen widths are responsive when table width increase).

**Comment by vthinkxie** [comment]
Hi @llkui @kunning 
try to update to 9.2.2 and give nzWidth to every column
https://stackblitz.com/edit/angular-hquq8a-gdl43y
without nzWidth, ng-zorro-antd will auto calc the nzWidth every time.

feel free to open a new issue if I miss anything, thanks for reporting this!
