### ISSUE TITLE
Steps 步骤条 中的nzDescription 不能进行换行

### ISSUE THREAD

**Issue by TyroneLao** [NG-ZORRO/ng-zorro-antd#523]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
Steps 步骤条 中的nzDescription 不能进行换行

## Expected behavior

我希望nzDescription 的内容可以按照其html内容展示

**Comment by cipchk** [comment]
screenshot:

![1](https://user-images.githubusercontent.com/2987467/32371180-e1dbb824-c0ca-11e7-8659-e24d057ebf51.png)

![2](https://user-images.githubusercontent.com/2987467/32371183-e3524a10-c0ca-11e7-8ab4-867048d132d0.png)
