### ISSUE TITLE
搭建开发环境，运行npm run start出现错误

### ISSUE THREAD

**Issue by xaclincoln** [NG-ZORRO/ng-zorro-antd#5231]
### Reproduction link
[https://ng-zorro-antd-start.stackblitz.io](https://ng-zorro-antd-start.stackblitz.io)

### Steps to reproduce
git clone https://github.com/NG-ZORRO/ng-zorro-antd
cd ng-zorro-antd
npm install
npm run start

### What is expected?
不出现错误，网站能正确显示

### What is actually happening?
运行npm run start之后，日志如下
 gulp start:dev
[16:24:32] Using gulpfile E:\angular\ng-zorro-antd\gulpfile.js
[16:24:32] Starting 'start:dev'...
[16:24:32] Starting 'clean'...
[16:24:32] Finished 'clean' after 15 ms
[16:24:32] Starting 'start:site'...
[16:24:32] Starting 'init:site'...
🌈 Theme generated successfully. OutputFile: E:\angular\ng-zorro-antd\site\doc\assets\color.less
[16:25:04] Finished 'init:site' after 32 s
[16:25:04] Starting 'watch:site'...
[16:25:04] Starting 'serve:site'...

chunk {main} main.js, main.js.map (main) 2.03 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 715 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.29 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2020-05-08T08:25:35.355Z - Hash: 0efa04a99ae919c436b0 - Time: 22818ms

ERROR in **Unable to write a reference to NzAffixComponent in E:/angular/ng-zorro-antd/components/affix/affix.component.ts from E:/angular/ng-zorro-antd/components/affix/affix.module.ts**

| Environment | Info |
|---|---|
|operating system| windows 10|
|node-js|v12.14.1|
| ng-zorro-antd | master |
| Browser | chrome |

---
上面的 stackblitz 链接没有什么作用，只是Issue的表单强制不能为空。尝试切换到9.1.0也出现同样的错误信息。

**Comment by hsuanxyz** [comment]
@wendellhu95 能用 Windows 试试吗？

**Comment by iconfontmee** [comment]
你们是在Linux 还是macOS

**Comment by Mr-Eve** [comment]
我这边win10 chrome, 刚刚重新clone, install, start, 没出现问题.

![image](https://user-images.githubusercontent.com/30228406/81497994-d0bdda00-92f4-11ea-97bb-e4156060c653.png)

**Comment by hsuanxyz** [comment]
> 我这边win10 chrome, 刚刚重新clone, install, start, 没出现问题.
> 
> ![image](https://user-images.githubusercontent.com/30228406/81497994-d0bdda00-92f4-11ea-97bb-e4156060c653.png)

不用 git 的 shell 也可以吗？

**Comment by xaclincoln** [comment]
我重新使用git的shell尝试了下，也报同样的错误。

**Comment by Mr-Eve** [comment]
直接用cmd吗? 也可以跑的. 能够正常打开4200端口的zorro @hsuanxyz

**Comment by xaclincoln** [comment]
我在Ubuntu 18.04 LTS上试了下，可以正常运行。

**Comment by wendellhu95** [comment]
> 
> 
> @wendellhu95 能用 Windows 试试吗？

可以运行。

@xaclincoln 是不是安装了什么软件监视了文件操作？

**Comment by wenqi73** [comment]
@xaclincoln 由于我们没有复现且该 issue 长期没有更新，这个 issue 将关闭。
