### ISSUE TITLE
9.1.0 版本的 Anchor 锚点 组件不能使用

### ISSUE THREAD

**Issue by webliuxiang** [NG-ZORRO/ng-zorro-antd#5235]
### Steps to reproduce
Code:
![image](https://user-images.githubusercontent.com/25944130/81408456-dc33c880-916f-11ea-81dd-fbad3b8809f5.png)

Browser performance: (chrome latest version)
![image](https://user-images.githubusercontent.com/25944130/81408502-ece43e80-916f-11ea-8ee5-a108be18ae48.png)

Developer Tools:
![image](https://user-images.githubusercontent.com/25944130/81408533-fbcaf100-916f-11ea-98aa-ed7cc15cc523.png)

### What is expected?
 Anchor 组件正常使用

### What is actually happening?
 Anchor 组件不能正常使用，而 card 组件可以正常使用

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | chrome |

**Comment by cipchk** [comment]
缺少 `nz-anchor` 模块导入，ng-alain 需要自行导入类库次级类库，见：https://github.com/ng-alain/ng-alain/blob/master/src/app/shared/shared-zorro.module.ts
