### ISSUE TITLE
Unit test failed in typography

### ISSUE THREAD

**Issue by Mr-Eve** [NG-ZORRO/ng-zorro-antd#5242]
### Steps to reproduce
最近跑zorro的单测  `npm run test:watch`  发现总会抱一个typography模块的错误, 具体见下图. 
![image](https://user-images.githubusercontent.com/30228406/81490932-6ab46100-92ba-11ea-9085-afc808ede3fd.png)

这个单测用例是在文本较多的情况下, 未显示多行省略的样式. 实际上, 本身官网的demo在火狐和谷歌中的表现就是不一样的. (同样的文本, 在火狐下会显示多行省略, 谷歌下不会显示多行省略)
![image](https://user-images.githubusercontent.com/30228406/81490962-de566e00-92ba-11ea-88a8-2b2cca5f8312.png)
![image](https://user-images.githubusercontent.com/30228406/81490965-e57d7c00-92ba-11ea-957f-6a23d0c5bb2b.png)

我简单调试了一下, 你可以搜索代码 `return ellipsisContainer.offsetHeight < maxHeight`, 这里的offsetHeight在火狐和谷歌两款浏览器中的值是不一样的. 具体如何修复我也不是很确定, 还是由这个模块的作者来修复比较合适.

### What is expected?
单测能够全部通过

### What is actually happening?
typography模块有一个单测用例没能通过

| Environment | Info |
|---|---|
| ng-zorro-antd | master |

**Comment by hsuanxyz** [comment]
@Mr-Eve Hi，能够分享一下 Firefox 版本吗？我在 Windows - Firefox 76.0.1 (64 位) 上没有复现上述问题。

**Comment by Mr-Eve** [comment]
跑测试可以指定平台吗? 我这边就是直接运行了 `npm test:watch`, 弹出的页面应该是谷歌内核的一个小浏览器.

**Comment by hsuanxyz** [comment]
@Mr-Eve 不行，测试优先使用 Headless Chrome，其次是本机 Chrome

**Comment by Mr-Eve** [comment]
噢懂了. 你是让我说下Firefox版本...哈哈, 我以为你让我用他跑下测试来着...
76.0.1 (64-bit) 和你一样吧
为什么说在火狐没有复现这个问题? 这个不是要跑测试吗?

**Comment by hsuanxyz** [comment]
> 同样的文本, 在火狐下会显示多行省略, 谷歌下不会显示多行省略

@Mr-Eve 主要是这个

**Comment by Mr-Eve** [comment]
你的火狐和谷歌表现一致吗?

**Comment by hsuanxyz** [comment]
@Mr-Eve 试试这个呢？ https://preview-5175-ng-zorro-antd.surge.sh/components/typography/zh

我忘了这个 #5175 还没发布，官网是有问题的

**Comment by Mr-Eve** [comment]
这个链接的确在火狐和谷歌上是正常的. 但是单测我是在最新的master跑的
我看了你的文件变更, 我当时有调试过这边, 我本地是包含你这个变更的, 但是单测依然还是报错了

**Comment by Mr-Eve** [comment]
这个问题在最新版没再出现
