### ISSUE TITLE
There is no select all function in the nz-select component

### ISSUE THREAD

**Issue by dansinian** [NG-ZORRO/ng-zorro-antd#5249]
## What problem does this feature solve?
When the nz-select component has many drop-down options that need to be selected, all the values need to be selected one by one manually. If there is a select all button, this will be much more convenient.

## What does the proposed API look like?
 <nz-select nzMode="multiple" nzPlaceHolder="Inserted are removed" [(ngModel)]="listOfSelectedValue">
      <nz-option *ngFor="let option of listOfOption" [nzLabel]="option" [nzValue]="option" [nzHide]="!isNotSelected(option)"></nz-option>
    </nz-select>

eg： Add an attribute to control whether to show select all

**Comment by vthinkxie** [comment]
you can add your own select all easily by this demo
https://ng.ant.design/components/select/en#components-select-demo-custom-dropdown-menu

**Comment by dansinian** [comment]
I hope there is such an effect in the picture.

![image](https://user-images.githubusercontent.com/29474503/81541834-52217500-93a6-11ea-8a3a-50a477b56ba3.png)

**Comment by dansinian** [comment]
I hope to have the select all and reverse select functions in the link below.

[https://www.cnblogs.com/landeanfen/p/7457283.html](url)

**Comment by dansinian** [comment]
I hope to have the select all and reverse select functions in the link below.

https://www.cnblogs.com/landeanfen/p/7457283.html

**Comment by vthinkxie** [comment]
`select all` equals
ngModel = all opitons value
`clear all` equals
ngModel = null
