### ISSUE TITLE
There is no open/close method for NzDatePickerComponent

### ISSUE THREAD

**Issue by chandrakantnaik789** [NG-ZORRO/ng-zorro-antd#5251]
## What problem does this feature solve?
I want an open/close method for opening or closing of DatePicker
There is open/close method for NzTimePickerComponent which is really handy to open close time picker dynamically from component
## What does the proposed API look like?
open(): open date picker
close(): close date picker

**Comment by wenqi73** [comment]
Duplicate of #3352
