### ISSUE TITLE
nz-option-item colorized bg

### ISSUE THREAD

**Issue by WeslleyDeSouza** [NG-ZORRO/ng-zorro-antd#5256]
## What problem does this feature solve?
Colorize bg of nz-option. 
## What does the proposed API look like?
<nz-option [style.background]="bgColor"></nz-option>
or
<nz-option [backgroundColor]="bgColor"></nz-option>

**Comment by vthinkxie** [comment]
you can use [nzDropdownClassName] to specifiy the className of dropdown and define your css
