### ISSUE TITLE
context-menu under tree does not show up at the node selected

### ISSUE THREAD

**Issue by zyzhu** [NG-ZORRO/ng-zorro-antd#5257]
### Reproduction link
[https://stackblitz.com/edit/angular-jxq5xm?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-jxq5xm?file=src/app/app.component.ts)

### Steps to reproduce
I've used the code from drop-down menu demo and put it into tree component. See stackblitz link

### What is expected?
I expect context menu shall show up at the node selected

### What is actually happening?
The context menu always shows up at the top left of the screen

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.1 |
| Browser | Chrome 81.0.4044.138 |

**Comment by zyzhu** [comment]
Bump. Any suggestion about how to get context menu working on tree? Thanks.

**Comment by vthinkxie** [comment]
ref https://ng.ant.design/components/tree/en#components-tree-demo-directory
