### ISSUE TITLE
Disabled on an NZ button with a dropdown doesn't work.

### ISSUE THREAD

**Issue by AprilHickson** [NG-ZORRO/ng-zorro-antd#5258]
### Reproduction link
[https://stackblitz.com/edit/angular-nc551o?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-nc551o?file=src/app/app.component.ts)

### Steps to reproduce
Create a button with attributes nz-button, nz-dropdown, nzDropdownMenu, and Disabled

### What is expected?
The button is disabled

### What is actually happening?
The button is not disabled

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.1 |
| Browser | Firefox 76.0.1 and Chrome Version 81.0.4044.138  |

---
It is visible on the dropdown menu page here: https://ng.ant.design/components/dropdown/en#components-dropdown-demo-dropdown-button

The section labeled "Button with dropdown menu"

**Comment by nuonuoge** [comment]
you can use nzDisabled
