### ISSUE TITLE
modal closing times error after the host view destroyed

### ISSUE THREAD

**Issue by llkui** [NG-ZORRO/ng-zorro-antd#5259]
### Reproduction link
[https://stackblitz.com/edit/angular-wgbxwe](https://stackblitz.com/edit/angular-wgbxwe)

### Steps to reproduce
1、open modal
2、click go to page2
3、console error: Uncaught (in promise): TypeError: Cannot read property 'nativeNode' of null
TypeError: Cannot read property 'nativeNode' of null

### What is expected?
1、modal close
2、page jump correctly

### What is actually happening?
1、page is not jump properly

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.1 |
| Browser | Google Chrome 80.0.3987.132 |

**Comment by wangxg6** [comment]
+1 遇到同样的问题，我这边直接关闭 modal 就会有这样的问题
