### ISSUE TITLE
nz-list-empty is always shown at the bottom of a nz-list

### ISSUE THREAD

**Issue by JoniVR** [NG-ZORRO/ng-zorro-antd#5260]
### Reproduction link
[https://stackblitz.com/edit/angular-vrt1mc](https://stackblitz.com/edit/angular-vrt1mc)

### Steps to reproduce
1. Create a `nz-list` with items and `nz-list-empty`
2. Scroll to the bottom of the list
3. See the `nz-list-empty` displayed even when items are present.

You can also just look at the `v9.1.1` `nz-list` documentation as the bug is present in those examples as well, I actually forked my stackblitz minimal reproduction from the documentation.

### What is expected?
The `nz-list-empty` only displays when no data is present.

### What is actually happening?
The `nz-list-empty` always displays at the bottom of the list, even when data is present.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.1 |
| Browser | Chrome Version 81.0.4044.138 (Official Build) (64-bit) |

---
As I mentioned earlier, you can see it happening in the v9.1.1 documentation.
https://ng.ant.design/components/list/en

**Comment by duongle26** [comment]
I got the same problem

**Comment by whittssg** [comment]
I was going crazy trying to fix this, glad to know its a bug in the new verison ;)
