### ISSUE TITLE
table组件将我的数据顺序打乱了

### ISSUE THREAD

**Issue by candy4290** [NG-ZORRO/ng-zorro-antd#5262]
### Reproduction link
[https://stackblitz.com/edit/angular-jze8hj-71zwif?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-jze8hj-71zwif?file=src/app/app.component.ts)

### Steps to reproduce
https://stackblitz.com/edit/angular-jze8hj-71zwif?file=src/app/app.component.ts
经过测试，chrome  63.0.3239.108 及其以下版本 配合 组件库8. 版本没有问题；
chrome最新版及组件库9. 版本没有问题；
chrome  63.0.3239.108 及其以下版本 配合 组件库 9. 版本出现该问题

### What is expected?
期望数据顺序不会被打乱

### What is actually happening?
chrome  63.0.3239.108 及 9. 版本出现该问题
![image](https://user-images.githubusercontent.com/19907991/82165566-19265a80-98e8-11ea-95f4-95552304c905.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.1 |
| Browser | chrome  63.0.3239.108 |

---
什么原因导致的？是ng9导致的，还是？

**Comment by candy4290** [comment]
please help!!!

**Comment by PelnHigh** [comment]
给table th加上nzWidth

**Comment by candy4290** [comment]
> 给table th加上nzWidth

没有任何作用

**Comment by candy4290** [comment]
help?!!!
