### ISSUE TITLE
nzSize not working in nz-input-group

### ISSUE THREAD

**Issue by mdragossh** [NG-ZORRO/ng-zorro-antd#5270]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-4kv9kn?embed=1&file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-4kv9kn?embed=1&file=src/app/app.component.html)

### Steps to reproduce
Create input with nzSize large with input group and without
Input is large
```html
<input nzSize="large" formControlName="username" nz-input placeholder="Username"/>
```
Input is not large
```html
 <nz-input-group nzPrefixIcon="user">
     <input nzSize="large" formControlName="username" nz-input placeholder="Username"/>
 </nz-input-group>
```
### What is expected?
Input size is not large

### What is actually happening?
Input size remain default

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.1 |
| Browser | Chrome 81.0.4044.138 |

**Comment by hsuanxyz** [comment]
move the `nzSize` input from `input[ nz-input]` to `nz-input-group`.

```diff
- <nz-input-group nzPrefixIcon="user">
+ <nz-input-group nzSize="large" nzPrefixIcon="user">
-  <input  nzSize="large" nz-input placeholder="Username"/>
+  <input  nz-input placeholder="Username"/>
 </nz-input-group>
```
