### ISSUE TITLE
穿梭框BUG,  无法更新数据

### ISSUE THREAD

**Issue by victory-wu** [NG-ZORRO/ng-zorro-antd#5278]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-yhfj99?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-yhfj99?file=src/app/app.component.html)

### Steps to reproduce
动态无法更新值

### What is expected?
正常显示

### What is actually happening?
没有触发渲染

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | chrome 版本 81.0.4044.113（正式版本） （64 位） |

**Comment by vthinkxie** [comment]
https://ng.ant.design/docs/faq/zh#%E6%95%B0%E6%8D%AE%E4%BF%AE%E6%94%B9%E5%90%8E%E9%A1%B5%E9%9D%A2%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%9B%B4%E6%96%B0
