### ISSUE TITLE
nz-select: 当遇到选中超长文本时鼠标悬停无法显示 title

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#5281]
## 重现

https://stackblitz.com/edit/angular-kxqpas?file=src/app/app.component.ts

**步骤**

- 已完成选中，列表不可见时：
  - 鼠标悬停时无法利用 `title` 呈现完成的文本内容
  - **问题根源：** `nz-select-search` 挡住导致其层高于 `nz-select-item` 且 `nz-select-item` 设置了 `pointer-events: none` 从而使 `title` 失效，（关于CSS样式问题，见[ant design #24157](https://github.com/ant-design/ant-design/issues/24157)）
- 打开列表时：
  - 列表项缺少 `title` 值（是否需要增加，鼠标悬停时无法利用 `title` 呈现完成的文本内容）

**Comment by PelnHigh** [comment]
Please help~
