### ISSUE TITLE
Cascader 级联选择组件nzShowSearch使用NzShowSearchOptions，能否增加个 query 方法

### ISSUE THREAD

**Issue by BigDamingming** [NG-ZORRO/ng-zorro-antd#5282]
## What problem does this feature solve?
能够自定义查询数据，而不是只能实现filter和sorter

## What does the proposed API look like?
nzShowSearch 为对象时需遵守 NzShowSearchOptions 接口，在 NzShowSearchOptions  下扩展个 query，(inputValue: string) => PromiseLike<any>

**Comment by wendellhu95** [comment]
没懂，请描述一下细节，什么叫做自定义查询数据。

有可能的话，请提供一个使用场景。
