### ISSUE TITLE
nz_upload 移动端android上传图片

### ISSUE THREAD

**Issue by dangzhenghui1985** [NG-ZORRO/ng-zorro-antd#5286]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-4l4uta?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-start-4l4uta?file=src/app/app.component.html)

### Steps to reproduce
使用android手机的时候 不像ios那样有拍照上传的功能 只有文件上传

### What is expected?
'capture','camera' 添加这个属性能够在android上面可以看到拍照上传的功能

### What is actually happening?
'capture','camera' 添加这个属性能够在android上面可以看到拍照上传的功能

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | android 内置浏览器 |

**Comment by cipchk** [comment]
Hi, antd is not totally compatible with mobile device. If Upload not work as expect, please try to use input instead.

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
