### ISSUE TITLE
confirm无法正常弹出

### ISSUE THREAD

**Issue by smile2014** [NG-ZORRO/ng-zorro-antd#5287]
### Reproduction link
[https://stackblitz.com/edit/angular-ag-grid-zorro](https://stackblitz.com/edit/angular-ag-grid-zorro)

### Steps to reproduce
鼠标移到表格数字上面点击按钮，confirm不弹出要再点击一下才触发

### What is expected?
点击就弹出

### What is actually happening?
点击就弹出

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | chrome |

**Comment by Zwei-J** [comment]
我也遇到同样的问题了

**Comment by hsuanxyz** [comment]
@smile2014 你可以暂时在 `NgZone.run` 中执行打开操作，直到我们找到真正的原因。

@Zwei-J 能提供以下你的复现吗？以便我们获得很多的信息，谢谢。

```ts
this.ngZone.run(() => {
  this.modalService.confirm({
    nzTitle:'<li>是否删除？</li>'  ,
    nzOnOk: () =>  console.log('add'),
  });
}) 
```

**Comment by smile2014** [comment]
谢谢，先用这个顶着
