### ISSUE TITLE
I need nzTag to have closable and checkable at same time.

### ISSUE THREAD

**Issue by kavinwang** [NG-ZORRO/ng-zorro-antd#5294]
## What problem does this feature solve?
I don't think  closable and checkable will clash in use. sometimes, I want the tag closable and checkable at same time. when I check it, something will be shown or excute under hood and when I close it, It will be disapeared。thanks!

## What does the proposed API look like?
<nz-tag *ngFor="let item of items" nzColor="blue" nzMode="closeable" nzCheckable (nzOnClose)="closeIt($event)"   (nzCheckedChange)="itemChecked($event)"></nz-tag> 
this will make the nzTag closable and checkable.

**Comment by hsuanxyz** [comment]
Hi, @kavinwang 

You can submit a feature request to [ant-design/ant-design](https://github.com/ant-design/ant-design) and we will follow the spec to implementation.
