### ISSUE TITLE
官网文档展开全部代码没效果   chrome 60

### ISSUE THREAD

**Issue by hsian** [NG-ZORRO/ng-zorro-antd#53]
官网文档展开全部代码没效果   chrome 60

**Comment by shaodahong** [comment]
看看控制台报错了没，是不是插件啥的影响到了

**Comment by hsian** [comment]
@shaodahong  控制台没报错， IE11下也没效果，不知道其他人有没遇到同样的问题？

**Comment by shaodahong** [comment]
你用隐身模式打开看一看是不是OK的

**Comment by hsian** [comment]
隐身模式还是没效果，同样情况下antd react的展开代码可以使用，但ng的就不行

**Comment by Tony-Lee** [comment]
没效果 +1 
Chrome 60.0.3112.90（正式版本） （64 位）

**Comment by shaodahong** [comment]
@Tony-Lee 我用这个版本测了下是没问题的，应该是其他原因，你剩下下chrome到最新的版本看看

**Comment by thegatheringstorm** [comment]
确实没有效果 Version 60.0.3112.78 (Official Build) (64-bit)

**Comment by vthinkxie** [comment]
@hsian @Tony-Lee @thegatheringstorm is there any error message in Chrome dev tools?

**Comment by Tony-Lee** [comment]
No error message in the console and network tab.
Tested in 
1. Windows + Chrome 60.0.3112.90 (64bit), Mac + Chrome 60.0.3112.101(64bit), both normal mode and private mode.
2. 360 Browser (V9.1.0.364, Kernel version: 55.0.2883.87).

**Comment by thegatheringstorm** [comment]
No error message in the console and network tab.
Tested in
    Ubuntu 16.04.01 + Chrome 60.0.3112.78 (Official Build) (64-bit) normal mode.

**Comment by hsian** [comment]
me too

**Comment by vthinkxie** [comment]
It is strange that all our members can not reproduce this problem at same version of chrome.
Can anyone help us to check the dom and style to figure out this problem.

**Comment by thegatheringstorm** [comment]
![1](https://user-images.githubusercontent.com/20680370/29802199-6cfab86e-8ca6-11e7-83b4-4f65997db111.jpg)
Do we press the same button?
:joy:

**Comment by Tony-Lee** [comment]
QQ469856
let me do the dirty job

**Comment by vthinkxie** [comment]
@Tony-Lee @hsian @thegatheringstorm please press the right bottom icon

**Comment by hsian** [comment]
@thegatheringstorm  en

**Comment by thegatheringstorm** [comment]
。。。。
the right bottom icon inside each demo works well
