### ISSUE TITLE
Style bug of slider

### ISSUE THREAD

**Issue by chensimeng** [NG-ZORRO/ng-zorro-antd#5302]
### Reproduction link
[https://stackblitz.com/edit/angular-j3dhts?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-j3dhts?file=src/app/app.component.ts)

### Steps to reproduce
marks: NzMarks = {
    10: '10 Cu',
    50: '50 Cu'
  };

### What is expected?
Style bug what Cu does not wrap

### What is actually happening?
Cu line breaks

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

**Comment by wendellhu95** [comment]
Add css property `white-space: nowrap` to `.ant-slider-mark-text` to solve it.

It happens to the React version as well.

![image](https://user-images.githubusercontent.com/12122021/82225514-e451ec00-9957-11ea-8a4b-bd9e87b9690e.png)
