### ISSUE TITLE
nz-table set sorting/filtering programmatically

### ISSUE THREAD

**Issue by snebjorn** [NG-ZORRO/ng-zorro-antd#5304]
## What problem does this feature solve?
This is a continuation of #4460

`nzQueryParams` made other aspects easier, but didn't address the core issue.

Given this
```html
<th
            nzColumnKey="foo" 
            [nzSortFn]="true"
>
```
The new `nzSort` is called `nzSortOrder` and is somewhat odd to work as it's not directly related to `nzQueryParams`. To set a default sort order we'd have to add a new public property to the component (for each relevant column) and use that in `[nzSortOrder]="fooSort"`

```html
<th
            nzColumnKey="foo" 
            [nzSortFn]="true"
            [nzSortOrder]="fooSort"
>
```

Simply writing `nzSortOrder="ascend"` won't do as the default value might be overwritten by URL params.

I'd prefer to work with the `NzTableQueryParams` object

## What does the proposed API look like?
Either make `nzQueryParams` double binding so we can set default values on the table. `(nzQueryParams)="onTableChange($event)" [nzQueryParams]="defaultValues"`. 
However this kind of conflicts with `[nzPageSize]` and `[nzPageIndex]`. 

So perhaps `[nzSort]: Array<{ key: string; value: NzTableSortOrder; }>` and `[nzFilter]: filter: Array<{ key: string; value: NzTableFilterValue; }>` on `nzTable` is better.

```html
<nz-table
            [nzPageIndex]="pageIndex" // NzTableQueryParams.pageIndex
            [nzPageSize]="pageSize" // NzTableQueryParams.pageSize
            [nzSort]="sort" // NzTableQueryParams.sort
            [nzFilter]="filter" // NzTableQueryParams.filter
>
```
Now there is no need to have extra properties or html attributes. It's all nicely wrapped up in a typesafe object.

**Comment by vthinkxie** [comment]
Hi @snebjorn 
does it work when you binding an `*ngFor` with the th params?
we have a demo here
https://ng.ant.design/components/table/en#components-table-demo-multiple-sorter

**Comment by snebjorn** [comment]
> does it work when you binding an `*ngFor` with the th params?

Using `*ngFor` or my example

```html
<th
            nzColumnKey="foo" 
            [nzSortFn]="true"
            [nzSortOrder]="fooSort"
>
```
Both do the same thing and work.

My point was to make `nzQueryParams` two way binding to simplify the API and table usage.

**Comment by vthinkxie** [comment]
> So perhaps [nzSort]: Array<{ key: string; value: NzTableSortOrder; }> and [nzFilter]: filter: Array<{ key: string; value: NzTableFilterValue; }> on nzTable is better.
it is the same as *ngFor and pass everything inside the `th` IMO, the worse thing is that you have to declare the `key` in different viewModel and make it more complex

> nzQueryParams double binding 

the `nz-table` is a template-driven table, which bring the benefit that the user can define everything inside the template, and if you want to use a reactive one, it would have a conflict with the template-driven (like the reactive form and template-driven form).
which means that it is impossible to use both reactive and template-driven in the same component.
