### ISSUE TITLE
Input sizes changed after updating to 9.1.2.

### ISSUE THREAD

**Issue by MehmetSert** [NG-ZORRO/ng-zorro-antd#5305]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy ](https://stackblitz.com/edit/ng-zorro-antd-ivy )
Before updating, the inputs were set to @input-height-base: 46px; https://prnt.sc/sja3li
It happened this way immediately after the update: http://prntscr.com/sizi8p

### Steps to reproduce
I first updated angular / cli (9.1.6) and angular / core (9.1.7).
Then I updated ng-zorro-antd to 9.1.2 version.

### What is expected?
Giving the height value to the input, not the div value of the height in the theme.less file.

### What is actually happening?
Input heights changed after the update. It takes the value in theme.less but gives it to the div, not the input. So all my inputs in the project have changed.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Opera |

---
I can't add a demo because there is no theme.less file in live demos.

**Comment by hsuanxyz** [comment]
This is a problem with [ant-design/ant-design](https://github.com/ant-design/ant-design) and cannot be resolved with NG-ZORRO.

But usually we change the variables related to the component at the same time instead of a single variable. Hope this helps.
