### ISSUE TITLE
Bug with disable on inputGroup when reactiveForm is used

### ISSUE THREAD

**Issue by JeremyValetteYmag** [NG-ZORRO/ng-zorro-antd#5307]
### Reproduction link
[https://stackblitz.com/edit/angular-aveg5n-m7xjmv?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-aveg5n-m7xjmv?file=src/app/app.component.ts)

### Steps to reproduce
* An nz-input-group with a suffix (or preffix)
   * an input used with ReactiveForm
you disable your form (reactiveForm) 

### What is expected?
The background-color of the whole nz-input-group has to be grey (input disable's color)

### What is actually happening?
only the input's background-color is grey (input disable's color) not the whole backgroud-color of the nz-input-group

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Google chrome |

**Comment by vthinkxie** [comment]
duplicated #5137
