### ISSUE TITLE
nz-table in a nz-modal cannot align properly and behaves differently after first time opening the modal

### ISSUE THREAD

**Issue by stevienie** [NG-ZORRO/ng-zorro-antd#5309]
### Reproduction link
https://codesandbox.io/s/ng-zorro-antd-ivy-yyu5m

### Steps to reproduce
1. click open button to open the modal
2. click close button to close the modal(I tried to bind onCancel() method to nzOnCancel but not working)
3. click open button to reopen the modal and you will find style in table is not the same with that of first time

### What is expected?
Style remains the same between first time opening the modal and those times after

### What is actually happening?
Style is messy when opening the modal for the first time and also different with styles when opening after the first time

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

---
In the modal may be the reason of causing this problem. The table behaves properly without that modal.

**Comment by msyesyan** [comment]
@vthinkxie can you help to take a look, I run into this problem too

**Comment by wenqi73** [comment]
@vthinkxie I met a similar problem, `nz-empty` is not aligned center。https://stackblitz.com/edit/nz9-table-in-modal?file=src/app/app.component.ts

**Comment by liuchintao** [comment]
@vthinkxie I met the similar problem +10086
