### ISSUE TITLE
Demand for advice：The new page custom sign trigger（ 需求建议：自定义新增页签触发器）

### ISSUE THREAD

**Issue by cyongk** [NG-ZORRO/ng-zorro-antd#531]
Demand for advice（需求建议）：新增《自定义新增页签触发器》
可以自定义的新增页，可关闭，可以包含其他组件容器

example（案例）1：
![1](https://user-images.githubusercontent.com/16489791/32411311-7792a1fa-c212-11e7-8069-5ec7d1b39326.PNG)
link （链接）：[https://ant.design/components/tabs-cn/]

example（案例）2：
![2](https://user-images.githubusercontent.com/16489791/32411313-7b0f8870-c212-11e7-9a24-9581e21462c5.PNG)
![3](https://user-images.githubusercontent.com/16489791/32411369-b5237566-c213-11e7-913c-5e10811f0324.PNG)
link （链接）：[http://bfunjmain.wsgjp.com.cn/Main.gspx]

**Comment by wanghaolu** [comment]
这个自己可以实现的啊
![default](https://user-images.githubusercontent.com/9586655/32411387-3c04e1b4-c214-11e7-8410-c94bbcb65760.PNG)

**Comment by cyongk** [comment]
你是怎么实现的，有代码吗？

**Comment by wanghaolu** [comment]
```html
<nz-tabset>
	<nz-tab *ngFor="let tab of tabs; let i = index">
		<ng-template #nzTabHeading>
			{{tab.name}}
      <i class="anticon anticon-close" (click)="closeTab(i)"></i>
		</ng-template>
		<span>{{tab.content}}</span>
	</nz-tab>
</nz-tabset>
```

``` javascript
import { Component, ChangeDetectorRef } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {

tabs = [
    {
      name   : 'Tab 1',
      content: 'Content of Tab Pane 1'
    },
    {
      name   : 'Tab 2',
      content: 'Content of Tab Pane 2'
    },
    {
      name   : 'Tab 3',
      content: 'Content of Tab Pane 3'
    }
  ];

  closeTab(index: number) {
     this.tabs.splice(index,1);
  }

}
```
