### ISSUE TITLE
nz-tab嵌套使用里面的tab默认底部蓝条样式不显示

### ISSUE THREAD

**Issue by Bigredorange** [NG-ZORRO/ng-zorro-antd#5310]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-dvkvk](https://codesandbox.io/s/ng-zorro-antd-ivy-dvkvk)

### Steps to reproduce
tab嵌套，里面tab放在外层tab容器的第二个标签页，里面tab默认底部蓝条样式不显示

### What is expected?
里面tab默认样式显示

### What is actually happening?
里面tab默认底部蓝条样式不显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | chrome |

**Comment by Bigredorange** [comment]
第一次加载页面有这个问题，点击里面的tab之后没有。

**Comment by hsuanxyz** [comment]
@Bigredorange https://codesandbox.io/s/ng-zorro-antd-ivy-e3jeb

```diff
- <nz-tab nzTitle="Tab 2">
+ <nz-tab nzForceRender nzTitle="Tab 2">
```

**Comment by Bigredorange** [comment]
试了下，可以的，谢谢了！👍
