### ISSUE TITLE
Unable to config autofocus of Nz-Modal

### ISSUE THREAD

**Issue by Lebronbingcheng** [NG-ZORRO/ng-zorro-antd#5319]
### Reproduction link
[https://ng-zorro-antd-ivy-oyx6o4.stackblitz.io](https://ng-zorro-antd-ivy-oyx6o4.stackblitz.io)

### Steps to reproduce
There is an auto focus when modal is opened. I do not want to enable auto focus. However, I do not find how to close it.

### What is expected?
Close auto focus when I open a modal.

### What is actually happening?
There is an auto focus when modal is opened

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

---
modal框打开的时候有一个auto focus。但是我没找到地方关掉这个auto focus。像是一个bug

**Comment by hsuanxyz** [comment]
close via #5313. `[nzAutofocus]="null"`
