### ISSUE TITLE
需求：Modal后弹出的窗口始终在最前面

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#532]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Expected behavior

在使用NzModalService显示对话框时如没有明确指定zIndex的值时，NzModalService自动对zIndex进行递增，而不是现在的始终为1000，这样保证后弹出的窗口始终在最前面

有时候出现嵌套弹窗的时候被嵌套的组件在多个地方使用的情况下，不方便进行手工确认zIndex顺序

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
duplicated #317

**Comment by vthinkxie** [comment]
close now, please track #317
