### ISSUE TITLE
Search box (nz-selector component) cannot input data on IE11

### ISSUE THREAD

**Issue by YuchenWell** [NG-ZORRO/ng-zorro-antd#5322]
### Reproduction link
[https://codesandbox.io/s/hi0qy](https://codesandbox.io/s/hi0qy)

### Steps to reproduce
The following demo in official document can not filter options by user input data on IE11, but available on Edge / Chrome / Firefox.
- Search Box 
- Custom Dropdown 
- Default Value (2nd selector)

### What is expected?
Available on IE11.

### What is actually happening?
User cannot enter on IE11

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | IE11 |

**Comment by wenqi73** [comment]
Please track #5645
