### ISSUE TITLE
No Internet Connection Results page

### ISSUE THREAD

**Issue by Infinical** [NG-ZORRO/ng-zorro-antd#5325]
## What problem does this feature solve?
if a user doesnt have network connection have a result page to show lack of connectivity

## What does the proposed API look like?
 `<nz-result nzStatus="Network" nzTitle="No Internet" nzSubTitle="Please check your network connectivity">
      <div nz-result-extra>
        <button nz-button nzType="primary">Retry</button>
      </div>
    </nz-result>`

**Comment by wendellhu95** [comment]
Hi. The requested feature needs to be designed by our friends from [antd](https://github.com/ant-design/ant-design). Would you please open an issue there?

**Comment by wendellhu95** [comment]
Closed due to inactivity. Please open an issue on antd first since this feature requires a new illustration.
