### ISSUE TITLE
broken style when using input group with range picker

### ISSUE THREAD

**Issue by scott-ho** [NG-ZORRO/ng-zorro-antd#5326]
### Reproduction link
[https://stackblitz.com/edit/angular-ffjwtj?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ffjwtj?file=src/app/app.component.ts)

### Steps to reproduce
see the link above

### What is expected?
no broken style/  range picker displays inline

### What is actually happening?
 range picker displays multiple lines

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome 81 |

---
sibling issue: https://github.com/NG-ZORRO/ng-zorro-antd/issues/2084

**Comment by scott-ho** [comment]
@vthinkxie are you going to fixed this or open for PR?

**Comment by vthinkxie** [comment]
Hi @scott-ho 
nzCompact mode won't support button inside
https://stackblitz.com/edit/angular-ffjwtj-wrg7ib?file=src/app/app.component.ts
