### ISSUE TITLE
Table Responsive

### ISSUE THREAD

**Issue by kelumpriya** [NG-ZORRO/ng-zorro-antd#5330]
## What problem does this feature solve?
Do the table responsive as of datatable.

## What does the proposed API look like?
not responsive like jquary datatable

**Comment by DevHabib** [comment]
They hasn't solved the responsive issue yet so I'm using css to make table responsive
**Here**
`.ant-table-content{
    overflow: auto;
  }`

**Comment by ryeborja** [comment]
I am facing the same issue. Adding `.ant-table-content{ overflow: auto; }` into the component style does not fix the issue. Any workaround?

**Comment by RohitGCoder** [comment]
Yes , For table there is no responsiveness, I need to create PWA app. But facing the issue because of this. `.ant-table-content{ overflow: auto; }` didn't worked for me as well. @devhabib can you post your code ?

**Comment by devhabib** [comment]
you 

> Yes , For table there is no responsiveness, I need to create PWA app. But facing the issue because of this. `.ant-table-content{ overflow: auto; }` didn't worked for me as well. @devhabib can you post your code ?

You can't override their css on your components css file.. add `.ant-table-content{overflow: auto;}` to your style.css/style.scss (which is your main style file) there you can override the design of ng zorro

**Comment by RohitGCoder** [comment]
> You can't override their css on your components css file.. add `.ant-table-content{overflow: auto;}` to your style.css/style.scss (which is your main style file) there you can override the design of ng zorro

I tried that, even it is not working in style.css
`html, body { height: 100%; overflow-x: hidden; }
body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif;}
.ant-table-content{overflow: auto;}
/* .ant-table-wrapper{overflow: auto;} */
}`

**Comment by tisufa** [comment]
> They hasn't solved the responsive issue yet so I'm using css to make table responsive **Here** `.ant-table-content{ overflow: auto; }`

This is the great solusion. But it's not work if you're not using view encaptulations or you can youse `::ng-deep`.

For an example:

`
.[your-table-wrapper] {
  ::ng-deep {
    .ant-table-content {
      overflow: auto;
    }
  }
}
`

Hope it can help you all.
