### ISSUE TITLE
expandable table with nested static table will show nest table header in top table header

### ISSUE THREAD

**Issue by scott-ho** [NG-ZORRO/ng-zorro-antd#5333]
### Reproduction link
[https://stackblitz.com/edit/angular-eaqiwo?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-eaqiwo?file=src/app/app.component.ts)

### Steps to reproduce
see the reproduction link

### What is expected?
expandable table supports nested static table

### What is actually happening?
not supported

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome 81 |

---
Obviously, the thead directive selector needs to be changed

**Comment by scott-ho** [comment]
@vthinkxie are you going to fixed this or open for PR?

**Comment by vthinkxie** [comment]
Hi @scott-ho 
https://stackblitz.com/edit/angular-eaqiwo-naxysx?file=src/app/app.component.ts
the nested table could only support `nz-table`
