### ISSUE TITLE
nz-table树形数据展示异常

### ISSUE THREAD

**Issue by BetterThanU1207** [NG-ZORRO/ng-zorro-antd#5334]
### Reproduction link
[https://stackblitz.com/edit/angular-nz-table-tree-data](https://stackblitz.com/edit/angular-nz-table-tree-data)

### Steps to reproduce
根据官方示例修改数据类型，数据已初始化，但是页面无任何展示，也无报错。

### What is expected?
页面正常显示数据

### What is actually happening?
页面无任何数据

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Google Chrome版本 81.0.4044.138（正式版本） （64 位） |

**Comment by BetterThanU1207** [comment]
没人啊

**Comment by qiurenbo** [comment]
I suggest you build your own tree data table based on this demo [https://stackblitz.com/edit/angular-nz-table-tree-data](https://stackblitz.com/edit/angular-nz-table-tree-data). The code you provide has many usage errors.

**Comment by BetterThanU1207** [comment]
> I suggest you build your own tree data table based on this demo https://stackblitz.com/edit/angular-nz-table-tree-data. The code you provide has many usage errors.

Thanks for your comment. Too many usage errors? Such as...? Also, I don't find any difference about  two link。

**Comment by vthinkxie** [comment]
menus 是数据入口，实际你的代码逻辑中menus没有进行任何赋值，建议先整理数据逻辑，再使用组件。
组件是视图数据ViewModel到视图View的体现，如果ViewModel本身的计算就是错的，和组件就不存在任何关系了
