### ISSUE TITLE
DatePicker: Problem with hours display on Iphone7

### ISSUE THREAD

**Issue by rockcoolt** [NG-ZORRO/ng-zorro-antd#5337]
### Reproduction link
https://ibb.co/7Jr88sC

### Steps to reproduce
Use datepicker on mobile resolution 375px with time display

### What is expected?
Time is cut

### What is actually happening?
Time should be responsive

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | chrome/safarie |

**Comment by wenqi73** [comment]
Currently there is no plan to support responsive. As another solution is allowing screen scrolling horizontally here. 🤔

**Comment by rockcoolt** [comment]
Ok Thank you !
