### ISSUE TITLE
table does not apply custom spin indicator in global nz config

### ISSUE THREAD

**Issue by kiyonlin** [NG-ZORRO/ng-zorro-antd#5339]
### Reproduction link
[https://stackblitz.com/edit/angular-nyjzgr](https://stackblitz.com/edit/angular-nyjzgr)

### Steps to reproduce
see the link

### What is expected?
table should use custom spin indicator in global nz config by default

### What is actually happening?
table uses default spin indicator

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | chrome Version 81.0.4044.138 |

**Comment by vthinkxie** [comment]
the table's spin indicator follows `nzLoadingIndicator`, is not support global config yet, which is not the same with spin indicator.

**Comment by kiyonlin** [comment]
It is more reasonable that all tables will use the global spin indicator if it is set while tables don't set a specific spin indicator, right?

**Comment by vthinkxie** [comment]
we will support nzLoadingIndicator global config soon

**Comment by kiyonlin** [comment]
good job, thanks :smile:

**Comment by nitin-rachabathuni** [comment]
Is it supported as of today?

**Comment by wendellhu95** [comment]
![image](https://user-images.githubusercontent.com/12122021/123565703-55690180-d7f0-11eb-9605-1146262ecf33.png)

@nitin-rachabathuni It's already supported.
