### ISSUE TITLE
inputmode for InputNumber component

### ISSUE THREAD

**Issue by junekpavel** [NG-ZORRO/ng-zorro-antd#5341]
## What problem does this feature solve?
Improve UX of InputNumber component, especially on mobiles. When user focus on InputNumber, the numeric keyboard should be opened instead of default (alphanumeric) one.

## What does the proposed API look like?
Native HTML input inside InputNumber component should have set [inputmode attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) to `numeric` or `decimal`. This value could be automatically determined by `nzStep`. Or at least there should be possibility to set `inputmode` manually.

**Comment by vthinkxie** [comment]
hi @junekpavel 
ng-zorro-antd is designed for desktop browser
if you need a mobile version, you can try ng-zorro-antd-mobile

**Comment by junekpavel** [comment]
Hello,
thanks for your answer.
I don't need a mobile version - we have responsive web application that is using only `nz-zorro-antd` ... people are using it on both desktop and mobiles.
