### ISSUE TITLE
nz-select - set initial values through ngModel not working under nzServerSearch mode

### ISSUE THREAD

**Issue by weihe8892** [NG-ZORRO/ng-zorro-antd#5345]
### Reproduction link
[https://codesandbox.io/s/keen-architecture-h7ixo?file=/src/app/app.component.ts](https://codesandbox.io/s/keen-architecture-h7ixo?file=/src/app/app.component.ts)

### Steps to reproduce
In nz-select set ngModel to  [(ngModel)]="selectedUser",  then in the code, initial selectedUser to ['David '] 

### What is expected?
Expect initial array of selectedUser (e.g. "David ") are displayed after page loading

### What is actually happening?
ng-select display blank at first. Add (ngModelChange) event listener to log $event to console, then start a search and select a new item, e.g "Victor", console display both initial value and new value, e.g. ['David ', 'Victor'], however screen still show 'Victor' only

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | all |

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/select/zh#components-select-demo-default-value
