### ISSUE TITLE
nz-select自定义下拉内容option内容多行时样式错误

### ISSUE THREAD

**Issue by amoycode** [NG-ZORRO/ng-zorro-antd#5346]
### Reproduction link
[https://stackblitz.com/edit/angular-e97kbb](https://stackblitz.com/edit/angular-e97kbb)

### Steps to reproduce
当option只有一个条目且该条目内容是多行: 
```
<nz-option nzCustomContent nzValue="1" nzLabel="o.label">
  <div >first</div>
  <div >first2</div>
</nz-option>
```

### What is expected?
下拉面板展开时option能够显示完整

### What is actually happening?
显示不完整, 只有一行的高度显示出来
![image](https://user-images.githubusercontent.com/18238708/83087493-0e2bb100-a0c4-11ea-9996-568705cd1fa0.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
nzOptionHeightPx
