### ISSUE TITLE
Reduce vendor.bundle size,too large in develop.

### ISSUE THREAD

**Issue by eminoda** [NG-ZORRO/ng-zorro-antd#535]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

vendor.bundle.js | 200 | script | detail:15 | 15.8 MB
it is too large when developping.
it still has 1M size when 'ng build --prod'.
How can i do if u have a solution?thank you...
开发的时候，合并zorro后vendor.bundle太大了，每次刷新页面等待时间有些久。觉得不太友好。
--prod --aot 后，该文件还有有1M的大小
## Expected behavior

希望后续在开发，和产线投入使用能再小一些。比如像：bootstrap-xng 我要用那个component就import

## Environment

<pre><code>
Angular version: 4.4.6

ng-zorro-antd version: 0.6.0-rc.2

**Comment by liepeng328** [comment]
这个问题，我处理过了，angular升级到5.0，然后`ng build -prod -base-href ./ -aot --extract-css --build-optimizer`,最大的js大概1m，配合后端gizp大概300-500k

**Comment by eminoda** [comment]
@liepeng328  
生产模式下，都觉的1M过大。开发10多M更接受不了。

**Comment by vthinkxie** [comment]
please upgrade to `angular 5.x` and use build-optimizer
