### ISSUE TITLE
[nzTabPosition]="'bottom'" does not work

### ISSUE THREAD

**Issue by altso** [NG-ZORRO/ng-zorro-antd#5352]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-geu9q](https://codesandbox.io/s/ng-zorro-antd-ivy-geu9q?file=/src/app/app.component.ts)

### Steps to reproduce
Use reproduction link and look at app.component.ts:

```html
  <nz-tabset [nzTabPosition]="'bottom'" [nzType]="'line'">
    <nz-tab [nzTitle]="'Tab 1'"> Content of tab1 1</nz-tab>
    <nz-tab [nzTitle]="'Tab 2'"> Content of tab 2</nz-tab>
    <nz-tab [nzTitle]="'Tab 3'"> Content of tab 3</nz-tab>
    <nz-tab [nzTitle]="'Tab 4'"> Content of tab 4</nz-tab>
  </nz-tabset>
```

### What is expected?
Tabs are shown on the bottom (below the content)

### What is actually happening?
Tabs are shown on the top (above the content).

![image](https://user-images.githubusercontent.com/1263018/83288433-5543a000-a1b1-11ea-81fd-72bd04edc7c1.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

---
The tab headers look like the bottom ones, but are shown at the top.

**Comment by hsuanxyz** [comment]
close via #5590
