### ISSUE TITLE
Recruitment Notice: 招聘Angular前端开发

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#536]
工作地点：	杭州
所属部门：	计算平台事业部

### 岗位描述：
1.  支持阿里巴巴流计算产品等多元业务发展，进行平台前端开发
2.  负责流计算WEB前端架构设计和核心模块编写
3.  参与团队技术规范制定，推动技术规范切实执行
4.  与开源社区对接，促进前端开源项目发展

### 岗位要求：
1.  精通Web编程，2年及以上web开发的经验，熟悉html、javascript、css
2.  熟练使用TypeScript的优先考虑
3.  实际使用过Angular(2+)/AngularJs/Vue/React中的一种或多种，熟练使用Angular(2+)的优先考虑
4.  对用户体验方面有经验优先
5.  对技术有强烈的兴趣，喜欢钻研，具有良好的学习能力，沟通技能，团队合作能力
6.  乐观、开朗、善于沟通，具有产品Ownership，热衷技术，乐于接受挑战

请投递简历至
![image](https://user-images.githubusercontent.com/1506722/32430047-6441b2e8-c308-11e7-83a7-85b9387e61f4.png)

**Comment by eminoda** [comment]
road over -。-

**Comment by liepeng328** [comment]
我要去阿里了，都别拉着我

**Comment by tigercosmos** [comment]
能著重在開源專案感覺挺不錯的
不知道薪水範圍是多少？

**Comment by liuya891012** [comment]
证明我来过

**Comment by wawsc5354524** [comment]
帮顶,哈哈

**Comment by wanghaolu** [comment]
我说zorro开发进度有点慢，原来是人手不够( • ̀ω•́ )✧

**Comment by franknew** [comment]
要不我来应个聘？

**Comment by tigercosmos** [comment]
> @wanghaolu  我说zorro开发进度有点慢，原来是人手不够( • ̀ω•́ )✧
靠你了  哈哈哈

**Comment by LinBoLen** [comment]
...

**Comment by Eusen** [comment]
我也想来！！

**Comment by njdmznkj** [comment]
read over,but still don't understand.

**Comment by jianqiao0313** [comment]
顶个~祝NG-ZORRO框架越来越好用，功能越来越强大~

**Comment by lc01010** [comment]
顶大angular框架

**Comment by ShaofeiZi** [comment]
233杭州，为啥不是北京

**Comment by franknew** [comment]
招聘有什么要求吗？

**Comment by Y2zz** [comment]
没有学历限制？
