### ISSUE TITLE
nz-select 启用 nzAllowClear 后，通过 clear 清除已选中值的情况下，再次触发下拉，发现刚才被清除的项依然处于选中状态

### ISSUE THREAD

**Issue by wxpxzdj** [NG-ZORRO/ng-zorro-antd#5360]
### Reproduction link
[https://stackblitz.com/edit/angular-gpjzzm](https://stackblitz.com/edit/angular-gpjzzm)

### Steps to reproduce
1、通过"X"按钮清空选中的值
2、触发下拉，但先不要将鼠标移动到下拉列表内部
3、这个时候就可以看到，滚动条依然在最下面，并且 “15”这个项依然处于选中状态
（不知道这算是一个BUG 还是一个 features，因为这可以理解为提示用户最后选的那个值，但这个行为确实与8.X不一致）

### What is expected?
下拉列表从第一个项目开始展示（就是滚动条回到最上面）

### What is actually happening?
下拉列表默认不是从第一个项目开始展示

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome 83.0.4103.61 |

**Comment by 232650413** [comment]
nz-cascader 组件貌似也是这个问题，我以为就是那样

**Comment by vthinkxie** [comment]
在 ant design 4.0 中 active 与 selected 是两种不同的状态，active 代表上次选中的位置，selected 代表是否选中

**Comment by awtkeithlin** [comment]
juset set new object to [(ngModel)]="data.myob"
data.myob = new Myob
