### ISSUE TITLE
popover和tooltip 一起使用时事件异常

### ISSUE THREAD

**Issue by nitmali** [NG-ZORRO/ng-zorro-antd#5365]
### Reproduction link
[https://stackblitz.com/edit/angular-9dxhuv?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-9dxhuv?file=src/app/app.component.ts)

### Steps to reproduce
 popover和tooltip 一起使用，PopoverTrigger click模式 会导致光标hover时间时直接就弹出了popover（有时候会不停闪烁）；

### What is expected?
hover事件时显示tooltip 文字提示，光标click事件时显示popover 气泡框

### What is actually happening?
click事件失效，hover事件弹出了tooltip和popover（有时候会不停闪烁）；

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Google Chrome 版本 83.0.4103.61（正式版本） （64 位） |

**Comment by qiurenbo** [comment]
Please remove ``` [(nzVisible)]="visible" ``` and try again. nzVisible is a shared API between popover and tooltip. If you set visible to true which is triggered by click or hover, both components will show together.

**Comment by nitmali** [comment]
> Please remove `[(nzVisible)]="visible"` and try again. nzVisible is a shared API between popover and tooltip. If you set visible to true which is triggered by click or hover, both components will show together.

未来版本能提供每个组件对应的visible属性分别控制吗，就像title一样。

**Comment by wendellhu95** [comment]
@nitmali 欢迎提交 PR

**Comment by qiurenbo** [comment]
I will fix this.

**Comment by wendellhu95** [comment]
Closed by #5449.
