### ISSUE TITLE
Select 多选时希望能不撑开布局

### ISSUE THREAD

**Issue by wxpxzdj** [NG-ZORRO/ng-zorro-antd#5367]
## What problem does this feature solve?
模拟效果如下：https://stackblitz.com/edit/angular-qyw4gx
当启用多选时，即使将 nzMaxTagCount 设为0时，Tag(或者应该说是search) 功能依然会导致 select 被撑大
为了不让 select 被撑大而破坏布局（一个常见的场景是列表页搜索功能），往往只能用 nzMaxTagPlaceholder 提示用户已经选择了多少个 item 以减少展示面积
但系统里面多选的情况下一般只会选中1 ~ 2 个item，但每个 item 的文字长度不固定，所以也好根据选中的数量来判断应该尽量展示 label 还是 count

所以，希望在多选的情况下支持关闭 tag 功能，且使 nzMaxTagPlaceholder 时的样式与 nzCustomTemplate 时的样式一样, 这样既可以利用有限的空间展示具体的 label，又不用担心撑开布局

一句话总结：希望提供一个功能，在多选的模式下，不管选中多少个，都希望能在一行内显示完(超出显示省略号)，不要撑开布局

## What does the proposed API look like?
[nzTag]="false"

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-qyw4gx-fascmn?file=src%2Fapp%2Fapp.component.ts
增加一句css就可以满足你的需要

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-qyw4gx-fascmn?file=src%2Fapp%2Fapp.component.ts
增加一句css就可以满足你的需要
