### ISSUE TITLE
DatePicker: when manual input date, the time info is changed

### ISSUE THREAD

**Issue by clannadxiaohei** [NG-ZORRO/ng-zorro-antd#5368]
### Reproduction link
[https://stackblitz.com/edit/angular-zcpef2?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-zcpef2?file=src/app/app.component.ts)

### Steps to reproduce
The origin date value is: Wed Jan 01 2020 00:00:00 GMT 0800 (中国标准时间), manual input date to 2019-01-01

### What is expected?
The modified date value is: Tue Jan 01 2019 00:00:00 GMT 0800 (中国标准时间)

### What is actually happening?
The modified date value is: Tue Jan 01 2019 08:00:00 GMT 0800 (中国标准时间)

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

**Comment by clannadxiaohei** [comment]
请问组件的这个行为是有意设计成这样还是bug？

**Comment by wenqi73** [comment]
@clannadxiaohei 默认解析输入值的时候用的 `new Date(inputValue)`，然而 `yyyy-MM-dd` 格式会返回 UTC 时间。可以通过引入 date-fns 来解决该问题。 https://github.com/NG-ZORRO/ng-zorro-antd/issues/4361#issuecomment-618959025
