### ISSUE TITLE
官方文件支援顯示歷史版本

### ISSUE THREAD

**Issue by tigercosmos** [NG-ZORRO/ng-zorro-antd#537]
讓使用者可以查閱舊版官方文件的內容
當前大版本可能以 xx.xx.xx 的中間號細分
歷史大版本則以頭號做區分

例如：
// 當前大版本
2.2.5
2.1.6
2.0.0
// 過去大版本 （最新的）
1.8.6
0.5.6

**Comment by vthinkxie** [comment]
https://ng.ant.design/version/0.5.x/

**Comment by tigercosmos** [comment]
@vthinkxie Shall we add note on README?

**Comment by vthinkxie** [comment]
https://ng.ant.design/#/docs/angular/introduce -> 历史版本入口

**Comment by tigercosmos** [comment]
It is still worth to let user know straightly while reading on Github, I thought.
