### ISSUE TITLE
Fixed nzWidth table broken after tab Select Change

### ISSUE THREAD

**Issue by Wsp0000** [NG-ZORRO/ng-zorro-antd#5370]
### Reproduction link
[https://stackblitz.com/edit/angular-ng-zorro-9-tabs-table-nzwidth?file=src%2Fapp%2Ffixed-header.component.ts](https://stackblitz.com/edit/angular-ng-zorro-9-tabs-table-nzwidth?file=src%2Fapp%2Ffixed-header.component.ts)

### Steps to reproduce
1. use nzWidth fixed Table column width in Tab1
2. click Tab2
3. click Tab1

please see gif:
![ng-zorro-9-tabs-table-width-issu](https://user-images.githubusercontent.com/30068092/83631262-ce872c80-a5cf-11ea-9a44-c8f30fe8e600.gif)

### What is expected?
After click Tab1 come back should still Fixed Table column width

### What is actually happening?
Table column width changed

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser |  Chrome 83.0.4103.61 |

---
same code in angular8/ng-zorro-antd@8.5.2 work as expected

https://stackblitz.com/edit/angular-ng-zorro-8-tabs-table-nzwidth?file=src%2Fapp%2Ffixed-header.component.ts

the same issue in angular9/ng-zorro-antd@9.1, seem like width become average width 

Is that possible to workaround by downgrade ng-zorro-antd@9 to angular9/ng-zorro-antd@8.5.2 or overwrite by css?

**Comment by styick** [comment]
我也遇到这个问题，并且如果把浏览器横向缩小会出现横向滚动条。
