### ISSUE TITLE
Button with only icon. Incorrect padding

### ISSUE THREAD

**Issue by neeeekto** [NG-ZORRO/ng-zorro-antd#5372]
### Reproduction link
[https://stackblitz.com/edit/angular-2trgr7](https://stackblitz.com/edit/angular-2trgr7)

### Steps to reproduce
Create button with loading state

### What is expected?
Button has no padding

### What is actually happening?
Button has padding

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

---
I think the reason is that the loading icon is rendered

**Comment by vthinkxie** [comment]
fixed by #5404
