### ISSUE TITLE
NzDescription with fixed columns width

### ISSUE THREAD

**Issue by dkorber** [NG-ZORRO/ng-zorro-antd#5373]
## What problem does this feature solve?
Depending on text size in description fields, the width of the columns changes. Would be nice to have the option to fix the width of the column with respective action in case of overflow.

## What does the proposed API look like?
two new properties: `fixedWidth: boolean` and `fixedWidthOverflow: string` (`hidden`, `ellipsis`, `wrap`, etc)

**Comment by wendellhu95** [comment]
IMHO, the API you proposed (such as `fixedWidthOverflow: 'hidden' | 'ellipsis' | 'wrap'`) suggests that the feature could be implemented by custom CSS.
