### ISSUE TITLE
Add embedded mode for select component/New embedded select component

### ISSUE THREAD

**Issue by mateusz-se** [NG-ZORRO/ng-zorro-antd#5374]
## What problem does this feature solve?
It solves a problem when available options are always visible for a user.
It could be similar to TreeSelect and Tree components. TreeSelect's data shows up only when user clicks on input box and the data in Tree component is always visible for a user.
This new mode could work in similar way that the data would be embedded to a page and always visible to a user. 

## What does the proposed API look like?
New boolean flag 'embedded' for SelectComponent, that would embed the data in the page and would be always visible.

**Comment by vthinkxie** [comment]
if you need an aways visible dropdown or option list, why do you still need the select component
input + list or input + table will meet your requirement
