### ISSUE TITLE
Can't bind to 'nzAutofocus' since it isn't a known property of 'nz-modal'

### ISSUE THREAD

**Issue by desprit** [NG-ZORRO/ng-zorro-antd#5378]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-ii0en?file=/src/app/app.component.ts](https://codesandbox.io/s/ng-zorro-antd-ivy-ii0en?file=/src/app/app.component.ts)

### Steps to reproduce
Error message is printed into the console.

### What is expected?
Property `nzAutofocus` to be available on the `nz-modal` component.

### What is actually happening?
It is not

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Chrome |

---
I tried to use both `nzAutoFocus` and `nzAutofocus`. According to this commit: https://github.com/hsuanxyz/ng-zorro-antd/commit/fc469012bde18ba50d4256d2240f86abc4b0fa16 property name is `nzAutofocus` but vscode suggests `nzAutoFocus`.

**Comment by hsuanxyz** [comment]
fixed via #5313, will be next release

**Comment by qiurenbo** [comment]
nzAutofocus of nz-modal should be 'ok' | 'cancel' | 'auto' | null.  It is used to make the focus on ok or cancel button.
