### ISSUE TITLE
【奇怪】Table 固定列 nzLeft 或 nzRight 缩放页面时 360浏览器一直向右滚动

### ISSUE THREAD

**Issue by 232650413** [NG-ZORRO/ng-zorro-antd#5383]
### Reproduction link
[https://codesandbox.io/s/beautiful-shtern-4lexo](https://codesandbox.io/s/beautiful-shtern-4lexo)

### Steps to reproduce
表格固定首尾列情况下，在360浏览器上缩放页面，达到145%情况下，滚动条一直朝右挤，即使恢复页面比列，也无法恢复。

### What is expected?
缩放时正常缩放就可以。

### What is actually happening?
在360浏览器上缩放页面，达到145%情况下，滚动条一直朝右挤

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | 360安全浏览器12 版本：12.1.2768.0 |

**Comment by vthinkxie** [comment]
duplicated of #5222
