### ISSUE TITLE
Tree组件的nzSelectedKeys值改变后没有取消上一次的选中状态

### ISSUE THREAD

**Issue by gaomengyong** [NG-ZORRO/ng-zorro-antd#5385]
### Reproduction link
[https://stackblitz.com/edit/angular-hfslgp](https://stackblitz.com/edit/angular-hfslgp)

### Steps to reproduce
先给nzSelectedKeys一个初始值
![image](https://user-images.githubusercontent.com/15724135/83874058-7daa3c00-a767-11ea-9a8a-335f29bc6e5d.png)
在setTimeout中给nzSelectedKeys设置一个新值
![image](https://user-images.githubusercontent.com/15724135/83874100-8733a400-a767-11ea-9a92-183a2f661618.png)

### What is expected?
之前的选中状态取消

### What is actually happening?
之前的还是选中状态
![image](https://user-images.githubusercontent.com/15724135/83874132-9155a280-a767-11ea-9f73-29949ee07a2d.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

**Comment by taojian-byte** [comment]
10.0.2 also has this problem
