### ISSUE TITLE
nz-list-item-actions not display when not append the nz-list-item-meta-avatar

### ISSUE THREAD

**Issue by Cozies** [NG-ZORRO/ng-zorro-antd#5393]
### Reproduction link
[https://stackblitz.com/edit/angular-vrt1mc-a2npgz](https://stackblitz.com/edit/angular-vrt1mc-a2npgz)

### Steps to reproduce
```
<nz-list class="demo-loadmore-list" [nzLoading]="initLoading">
  <nz-list-item *ngFor="let item of list">
    <ng-container *ngIf="!item.loading">
      <nz-list-item-meta>
        <nz-list-item-meta-title>
          <a href="https://ng.ant.design">{{ item.name }}</a>
        </nz-list-item-meta-title>
        <nz-list-item-meta-description>
          Ant Design, a design language for background applications, is refined by Ant UED Team
        </nz-list-item-meta-description>
      </nz-list-item-meta>
      content
      <ul nz-list-item-actions>
        <nz-list-item-action><a (click)="edit(item)">edit</a></nz-list-item-action>
        <nz-list-item-action><a (click)="edit(item)">more</a></nz-list-item-action>
      </ul>
    </ng-container>
    <nz-skeleton *ngIf="item.loading" [nzAvatar]="true" [nzActive]="true" [nzTitle]="false" [nzLoading]="true"> </nz-skeleton>
  </nz-list-item>
  <div class="loadmore" nz-list-load-more>
    <button nz-button *ngIf="!loadingMore" (click)="onLoadMore()">loading more</button>
  </div>
</nz-list>
```

### What is expected?
display actions when not append `<nz-list-item-meta-avatar [nzSrc]="'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png'"></nz-list-item-meta-avatar>` before the `nz-list-item-meta-title`

### What is actually happening?
`nz-list-item-actions` not display when not append `nz-list-item-meta-avatar `

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome 83.0.4103.61（正式版本）（64 位） |

**Comment by Yukimir** [comment]
The same problem.
Due to `ChangeDetectionStrategy.OnPush`?

**Comment by danielharven** [comment]
Having a simillar problem, won't update the list automatically
