### ISSUE TITLE
Select单选模式下，在IE中搜索无法输入

### ISSUE THREAD

**Issue by ClouderBai** [NG-ZORRO/ng-zorro-antd#5395]
### Reproduction link
[https://codesandbox.io/s/gw47q](https://codesandbox.io/s/gw47q)

### Steps to reproduce
点击后无法输入

### What is expected?
点击后可以输入

### What is actually happening?
点击后无法输入

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | IE11 |

---
https://ng.ant.design/components/select/zh#components-select-demo-search 可查看，stackblitz 和 codesandbox 不支持IE

**Comment by vthinkxie** [comment]
duplicated #4296
