### ISSUE TITLE
nz-select 'active' item highlighting does not change when value changes

### ISSUE THREAD

**Issue by altso** [NG-ZORRO/ng-zorro-antd#5399]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-9o16x?file=/src/app/app.component.ts](https://codesandbox.io/s/ng-zorro-antd-ivy-9o16x?file=/src/app/app.component.ts)

### Steps to reproduce
1. Open reproduction link
2. Click on 'update' button
3. Open dropdown to reveal the list of options

### What is expected?
Only selected item is highlighted

### What is actually happening?
Selected value and previous selected value are both highlighted. Previous value is highlighted as 'active'.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
在 ant design 4.0 中 active 与 selected 是两种不同的状态，active 代表上次选中的位置，selected 代表是否选中，如果需要高亮选中状态可以参考
https://codesandbox.io/s/ng-zorro-antd-ivy-d69o2?file=/src/app/app.component.ts

**Comment by altso** [comment]
I still think it's a weird behavior that needs to be fixed, but thanks for reviewing anyways.
