### ISSUE TITLE
Add animations switch for ng-zorro components only

### ISSUE THREAD

**Issue by alanyinjs** [NG-ZORRO/ng-zorro-antd#5400]
## What problem does this feature solve?
Ng-zorro allows developers to turn off animations globally, in templates and in services (https://ng.ant.design/docs/animations/en). However this feature heavily relies on `NoopAnimationsModule` which means there is no option to turn animations off globally only for ng-zorro components.

In our particular use case, we have recently upgraded from `v8` to `v9` and we would like to turn off animations for `ng-zorro` components only, while leaving animations on for the components we wrote ourselves. Considering that our existing code base is fairly large, it is not viable to turn it off template by template. Turning animations off globally using `NoopAnimationsModule` means we will have to lose all the animations we wrote for our platform.

## What does the proposed API look like?
Provide an option to turn off ng-zorro animations only at root level (or module level) of an app.

**Comment by HyperLife1119** [comment]
Please use `NzNoAnimationModule`.
