### ISSUE TITLE
nz-menu: cursor on top option

### ISSUE THREAD

**Issue by Cairon** [NG-ZORRO/ng-zorro-antd#5401]
## What problem does this feature solve?
Add an option to display the menu cursor on top of the menu in horizontal mode, like the top menu of https://ng.ant.design/. There's actually no way to do that without style customization.

## What does the proposed API look like?
<nz-menu nzCursorPosition="top" .../>

**Comment by vthinkxie** [comment]
this is not supported by ant design spec yet, you can submit an issue to https://github.com/ant-design/ant-design/stargazers/
