### ISSUE TITLE
表单control作为子组件时验证时，原本红色的提示现在是灰色的

### ISSUE THREAD

**Issue by peacejj** [NG-ZORRO/ng-zorro-antd#5402]
### Reproduction link
[https://stackblitz.com/edit/angular-zhapqa-89xqxk?file=src%2Fapp%2Fmobile.component.ts](https://stackblitz.com/edit/angular-zhapqa-89xqxk?file=src%2Fapp%2Fmobile.component.ts)

### Steps to reproduce
当formctrol为子组件时，在输入框内输入内容再删除，会发现提示以及输入框边框颜色是灰色，观察是父组件nz-form-item标签并没有class变化，如何触发？

### What is expected?
期望提示为红色，也就是nz-form-item的class随之变化

### What is actually happening?
当formctrol为子组件时，在输入框内输入内容再删除，会发现提示以及输入框边框颜色是灰色，观察是父组件nz-form-item标签并没有class变化，如何触发？

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | chorme Version 83.0.4103.97 (Official Build) (64-bit) |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-zhapqa-dcinql?file=src/app/app.component.ts

**Comment by peacejj** [comment]
@vthinkxie 非手动点击按钮验证，而是在输入的时候实时验证。我试了你发的stack，实时输入再删除并不可以置为红色

**Comment by vthinkxie** [comment]
那是因为你的内部form没有设定成dirty状态，如果你要手动定制 form 的话，至少要让 ControlValueAccessor 所有的功能都能正常工作，你所有的内部函数都是implements一个空函数，angular 是不会自动帮你写完剩下的代码的
