### ISSUE TITLE
AutoComplete关闭默认选中，但是输入关键字后，回车后搜索变量又还是看不见的默认选中项

### ISSUE THREAD

**Issue by git-xyx** [NG-ZORRO/ng-zorro-antd#5403]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/issues?q=autocomplete](https://github.com/NG-ZORRO/ng-zorro-antd/issues?q=autocomplete)

### Steps to reproduce
AutoComplete 查询模式 - 确定类目 ,关闭了弹框默认选中后，没法实际取消默认选中，在输入关键字后还会自动选上了某个值

### What is expected?
AutoComplete 查询模式 - 确定类目 ,关闭了弹框默认选中后，能自定义输入关键字后，回车搜索，能按照关键字搜索，而不是变成了默认选中的关键字

### What is actually happening?
AutoComplete 查询模式 - 确定类目 ,关闭了弹框默认选中后，没法实际取消默认选中，在输入关键字后还会自动选上了某个值

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome 81 |

**Comment by hsuanxyz** [comment]
**查询模式 - 确定类目** 中并为对搜索行为做过任何处理，AutoComplete 组件也没有。你需要自己定义搜索行为，请查参照其它 DEMO 的代码，比如 **不区分大小写**
