### ISSUE TITLE
能不能支持ng zorro按需加载

### ISSUE THREAD

**Issue by ydostyle** [NG-ZORRO/ng-zorro-antd#5406]
## What problem does this feature solve?
'ng-zorro-antd/alert' 这种要自己去写，太麻烦了，能不能有个插件能自动遍历项目使用的组件，生成对应模块

## What does the proposed API look like?
希望一个命令行执行完，能自动生成项目使用的组件

**Comment by hsuanxyz** [comment]
**为什么没有工具？**

目前开发工具需要的的主要依赖 ngast 还不支持 ng9 的懒加载模块 https://github.com/mgechev/ngast/issues/18

**那我现在怎么办？**

目前推荐 https://github.com/NG-ZORRO/nz-tslint-rules + Webstorm 重构引入路径

1. 首先删除顶级入口（import { NgZorroAntdModule } from 'ng-zorro-antd'）

2. 在 Webstorm 中排除顶级入口
```
ng-zorro-antd
ng-zorro-antd/ng-zorro-antd.module*
ng-zorro-antd/core
ng-zorro-antd/core/*.*
```
![image](https://user-images.githubusercontent.com/22736418/84475230-c2c9f300-acbe-11ea-919d-61acfc3b26fe.png)
3. 在模版中按下 <kbd>⌥</kbd> + <kbd>Enter</kbd> 自动在当前模块中引入对应模块

![image](https://user-images.githubusercontent.com/22736418/84475577-62878100-acbf-11ea-98c2-cf27b9f5ebca.png)

**Comment by wendellhu95** [comment]
这个问题应该在我们移除掉顶层入口之后就能解决了。个人看法，自动引入应该是编辑器做的事情。

**Comment by ydostyle** [comment]
问题是老项目，升级之后，项目里不知道用了多少模块

**Comment by ydostyle** [comment]
@hsuanxyz

**Comment by hsuanxyz** [comment]
@ydostyle 根据你的情况选择上面的方法就行了，如果有更多问题便不适合在 Github issue 中讨论，你可以使用钉钉扫描下方二维码在服务群中讨论。
![image](https://user-images.githubusercontent.com/22736418/84845211-a5aa7100-b07e-11ea-9f6c-c1f17d0e0139.png)
