### ISSUE TITLE
IE11下使用NzModalService以及自定义component时，无法获取返回值

### ISSUE THREAD

**Issue by FuckDoctors** [NG-ZORRO/ng-zorro-antd#5408]
### Reproduction link
[https://stackblitz.com/edit/angular-dslbvw](https://stackblitz.com/edit/angular-dslbvw)

### Steps to reproduce
再现链接是官网例子：https://ng.ant.design/components/modal/zh#components-modal-demo-service
由于stackblitz中有错误，稍微改了一下结构。
1. 点击`Use Component`按钮
2. 点击`destroy modal in the component`按钮

### What is expected?
跟Chrome一致，能得到返回值：
[afterOpen] emitted!
[afterClose] The result is: {data: "this the result data"}

### What is actually happening?
IE11的开发者工具中，无法打印返回值。
而且，点击`Use Component`按钮没有打印`afterOpen`，关闭时没有打印`afterClose`，而是打印了`afterOpen`

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | IE11 |

**Comment by hsuanxyz** [comment]
#5312
