### ISSUE TITLE
table动态加载表头的时候，如果表头分组，那么空状态时空状态不能撑满表格

### ISSUE THREAD

**Issue by youngsherlee** [NG-ZORRO/ng-zorro-antd#5410]
### Reproduction link
[https://stackblitz.com/edit/angular-lft43d](https://stackblitz.com/edit/angular-lft43d)

### Steps to reproduce
直接运行

### What is expected?
空状态应该填满table

### What is actually happening?
空状态填充的列数和第一行的列数一样

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Google Chrome 已是最新版本 版本 83.0.4103.97（正式版本） （64 位） |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-lft43d-g2bzmr?file=src/app/app.component.ts
可以暂时这样跳过，我们会在下个版本修复
