### ISSUE TITLE
Visually clearable datepicker when the nzAllowClear option is false

### ISSUE THREAD

**Issue by DRYmag** [NG-ZORRO/ng-zorro-antd#5411]
### Reproduction link
[https://codesandbox.io/s/dreamy-diffie-uslt0?file=/src/app/app.component.ts](https://codesandbox.io/s/dreamy-diffie-uslt0?file=/src/app/app.component.ts)

### Steps to reproduce
First, we need a `nz-datepicker` with the option `nzAllowClear` to `false`. The datepicker starts with a value (in the example set via the reactive form).

These next interactions will demonstrate the bug:
- click on the datepicker's input
- the datepicker will appear
- click a second time on the datepicker's input
- the datepicker will close
- but the datepicker's input still has the focus, so we can clean up the input with the keyboard (backspace or delete keys)
- exit the input

### What is expected?
On the blur, the display of the actual value will be restored.

### What is actually happening?
The input is still blank, no date is displayed.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome Version 85.0.4170.0 (Build officiel) canary (64 bits) |

**Comment by wenqi73** [comment]
I think your question will be resolved by this feature https://github.com/NG-ZORRO/ng-zorro-antd/issues/5284 🤔 .
