### ISSUE TITLE
nz-time-picker nzDisabledHours & nzDisabledMinutes Issue

### ISSUE THREAD

**Issue by stay3hungry** [NG-ZORRO/ng-zorro-antd#5413]
### Reproduction link
[https://ju97xh.run.stackblitz.io/](https://ju97xh.run.stackblitz.io/)

### Steps to reproduce
1、click the nz-time-picker input
2、select minute: 22
2、select hour: 4
3、click the blanks to blur
4、time is 4:22

### What is expected?
when the hour is 4, minute 22 should be disabled, 4:22 shouldnt be selected

### What is actually happening?
result is 4:22 

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | chrome |

**Comment by wenqi73** [comment]
@stay3hungry The reproduction URL should be with source code.
