### ISSUE TITLE
Get custom value from nz-tree

### ISSUE THREAD

**Issue by 1295** [NG-ZORRO/ng-zorro-antd#5418]
## What problem does this feature solve?
Can we add a value field for each NzTreeNode<T>, So we can get our value directly from the event instead of iterating the tree every time.

## What does the proposed API look like?
```ts
class NzTreeNode<T> {
    key: string;
    level: number;
    origin: NzTreeNodeOptions;
    parentNode: NzTreeNode | null;
    value?: T;
    // ...
}

interface NzFormatEmitEvent<T> {
    eventName: string;
    node?: NzTreeNode<T> | null;
    event?: MouseEvent | DragEvent | null;
    dragNode?: NzTreeNode<T>;
    selectedKeys?: NzTreeNode<T>[];
    checkedKeys?: NzTreeNode<T>[];
    matchedKeys?: NzTreeNode<T>[];
    nodes?: NzTreeNode<T>[];
    keys?: string[];
}
```<!-- generated by ng-zorro-issue-helper. DO NOT REMOVE -->

**Comment by simplejason** [comment]
Thanks for your suggestion, you can use `origin` to get the custom data for now. If it still can not solve your problem, you can provide a minimal reproduction by stackblitz or codesandbox :)

**Comment by 1295** [comment]
> Thanks for your suggestion, you can use `origin` to get the custom data for now. If it still can not solve your problem, you can provide a minimal reproduction by stackblitz or codesandbox :)

Think you so much, It solve my problem.
