### ISSUE TITLE
请问 ANT DESIGN PRO 有没有 zorro 版的？

### ISSUE THREAD

**Issue by zhangzheyuan** [NG-ZORRO/ng-zorro-antd#542]

**Comment by mizne** [comment]
不知道这个适不适合你 @zhangzheyuan 
https://github.com/cipchk/ng-alain

**Comment by tigercosmos** [comment]
我也蠻期待`ng-zorro-antd` 推出 `ANT DESIGN PRO`

**Comment by vthinkxie** [comment]
Hi all, please use https://github.com/cipchk/ng-alain now, it is a great admin start up for ng-zorro-antd
