### ISSUE TITLE
嵌套多级菜单样式混乱问题(BUG:Nested multilevel menu style confusion)

### ISSUE THREAD

**Issue by ZhangZheng-GIS** [NG-ZORRO/ng-zorro-antd#544]
通过子组件嵌套实现多级菜单，nz-menu中的nz-submenu项图标显示在下一行并且子级菜单padding-left值不对。恳请开发者解答，谢谢！
相关代码见下面连接：
https://plnkr.co/edit/8XcS2O?p=preview
![n0xm0vysnhcfrm n4 lxu 6](https://user-images.githubusercontent.com/14178404/32483325-7ad30060-c3d6-11e7-84ed-751d961d8a94.png)
@vthinkxie  @trotyl @cipchk @dyh333

**Comment by vthinkxie** [comment]
releated #364

**Comment by vthinkxie** [comment]
try to fixed in version 0.7.0 but failed
https://github.com/NG-ZORRO/ng-zorro-antd/blob/5c0716107e0955b034a2d9ce75463ff3b0e9fdb6/components/menu/style/index.less#L372
the design of ant design can not insert any self define component into menu, it will break the style define.

**Comment by liuyibing123456** [comment]
@vthinkxie 是否可以在subMenu的level属性增加@Input()，以便外层组件自己控制
