### ISSUE TITLE
Hide text of <a> tag for nz-sider on collapse

### ISSUE THREAD

**Issue by hoppler** [NG-ZORRO/ng-zorro-antd#5443]
### Reproduction link
[https://stackblitz.com/edit/angular-qabqom](https://stackblitz.com/edit/angular-qabqom)

### Steps to reproduce
Collapse sidebar

### What is expected?
Text "Team" should be hidden on collapse

### What is actually happening?
Text "Team" is still visible

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.0 |
| Browser | Edge / Chromium |

---
In CSS you only handle span, but not the a tag for collapsing
https://github.com/NG-ZORRO/ng-zorro-antd/blob/15b7cc21504a5735165e85bc0f6db3ab059dbb6b/components/menu/style/index.less#L185-L188
https://github.com/NG-ZORRO/ng-zorro-antd/blob/15b7cc21504a5735165e85bc0f6db3ab059dbb6b/components/menu/style/index.less#L470-L474

**Comment by ToledoNicola** [comment]
the solution is to wrap the <a> inside the span?
