### ISSUE TITLE
i18n for other locales than en_US does not compile

### ISSUE THREAD

**Issue by bossqone** [NG-ZORRO/ng-zorro-antd#5444]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-e2eb5m](https://stackblitz.com/edit/ng-zorro-antd-ivy-e2eb5m)

### Steps to reproduce
- create variable with type `NzI18nInterface`
- assign de_DE from `ng-zorro-antd/i18n` to that variable

### What is expected?
compilation works

### What is actually happening?
compilations error:
```
Property 'Form' is missing in type '{ locale: string; Pagination: { items_per_page: string; jump_to: string; jump_to_confirm: string; page: string; prev_page: string; next_page: string; prev_5: string; next_5: string; prev_3: string; next_3: string; }; ... 11 more ...; PageHeader: { ...; }; }' but required in type 'NzI18nInterface'.
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.0 |
| Browser | any |

---
I've looked at implementation of locale files and it would be great to use interface there to force compilation check.

**Comment by bossqone** [comment]
probably related to https://github.com/NG-ZORRO/ng-zorro-antd/issues/5441

**Comment by vthinkxie** [comment]
cc @wenqi73
