### ISSUE TITLE
nz-tree中首次设置[nzExpandAll]="true"展开，但nzData变动后不展开

### ISSUE THREAD

**Issue by peacejj** [NG-ZORRO/ng-zorro-antd#5446]
### Reproduction link
[https://stackblitz.com/edit/angular-q7lmud?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-q7lmud?file=src/app/app.component.ts)

### Steps to reproduce
我设置了一个定时器，5s后更新nzData值，树形结构收缩，没有展开

### What is expected?
希望一直是展开状态

### What is actually happening?
现在是收缩了

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.0 |
| Browser | Version 83.0.4103.97 (Official Build) (64-bit) |

**Comment by peacejj** [comment]
@simplejason  您好，这个问题定为bug了，现在没有解决的方法是嘛？

**Comment by yzhe554** [comment]
似乎问题是每次input改变expandAll都会被设置成false.
https://github.com/NG-ZORRO/ng-zorro-antd/blob/dfc443d16baa34eee4095a642c49408d3798ddec/components/tree/tree.component.ts#L257

**Comment by peacejj** [comment]
@yzhe554 您好 expandAll 设置为本地变量，在nzData变更时，还是会收缩。您提到的ngOnChanges我并没有使用，而是直接重置了nzData，和这个有关联嘛？

**Comment by w6942** [comment]
nzCollapsed也有类似的问题
