### ISSUE TITLE
nz-table There is a default td under expanded row

### ISSUE THREAD

**Issue by erdongerzhong** [NG-ZORRO/ng-zorro-antd#5448]
### Reproduction link
[https://stackblitz.com/edit/angular-xsdpnt-1f6zcy](https://stackblitz.com/edit/angular-xsdpnt-1f6zcy)

### Steps to reproduce
展开的行下存在默认的td标签，导致展开行中的元素都包含在这个td中
<br>在开发者工具定位到展开的tr，会发现tr下面的td都被包含在了一个默认的td中

### What is expected?
展开的tr保持开发者写的内容，不在其中增加任何元素

### What is actually happening?
展开的tr下被增加td标签，并且原tr下的td都又被包含在了这个td下

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

---
8.5.2升级9.1.2遇到的问题

**Comment by vthinkxie** [comment]
9.x 之后展开 td 的colspan 由 组件自动计算，不再需要在 tr 内手动声明 td

**Comment by erdongerzhong** [comment]
> 9.x之后展开td的colspan由组件自动计算，不再需要在tr内手动声明td

多谢
