### ISSUE TITLE
drawer nzZIndex not work with static cdk-overlay-container z-index setting

### ISSUE THREAD

**Issue by sddrwsm** [NG-ZORRO/ng-zorro-antd#5450]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-t3prdh](https://stackblitz.com/edit/ng-zorro-antd-ivy-t3prdh)

### Steps to reproduce
配置组件 drawer 的 nzZIndex 参数小于1000时，实际表现不会生效。

### What is expected?
点击 drawer-2 时，显示的 drawer 应该从 sider 的后方右移出现。因为 drawer 配置的 nzZIndex  属性小于 sider 的 z-index 属性。

### What is actually happening?
点击 drawer-2 时，显示的 drawer 应该从 sider 的前方右移出现。

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.1 |
| Browser | Microsoft Edge 83.0.478.50 |

---
经过排查，发现 zorro 为 cdk-overlay-container 添加了默认的 z-index 参数，导致该问题。
解决该问题只需要覆盖 zorro 的全局样式：
``` css
.cdk-overlay-container {
  position: absolute;
}
```
即可。

**Comment by hsuanxyz** [comment]
感谢你的反馈，但是 `position: fixed` 是 `cdk-overlay-container` 的默认行为，目的是为了创建**独立的叠加层**，以保证 `cdk-overlay-container` 中其它组件的叠层按我们预期的层级呈现。
