### ISSUE TITLE
Confirm modal always throws error in console

### ISSUE THREAD

**Issue by rppig42** [NG-ZORRO/ng-zorro-antd#5454]
### Reproduction link
[https://stackblitz.com/edit/angular-aaqib1?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-aaqib1?file=src/app/app.component.ts)

### Steps to reproduce
1. open Chrome dev console
2. click confirm button

### What is expected?
console is empty

### What is actually happening?
console prints: ERROR TypeError: Cannot read property 'focusInitialElementWhenReady' of undefined

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.1 |
| Browser | Chrome latest |

---
it can be reproduced on https://ng.ant.design. The bug might be introduced by 9.2.1

**Comment by 232650413** [comment]
core.js:6210 ERROR TypeError: Cannot read property 'focusInitialElementWhenReady' of undefined
