### ISSUE TITLE
Select 控件在nzOpenChange方法异步更新数据源  列表滚动会出现渲染问题

### ISSUE THREAD

**Issue by yor1g** [NG-ZORRO/ng-zorro-antd#5456]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-ltc0m](https://codesandbox.io/s/ng-zorro-antd-ivy-ltc0m)

### Steps to reproduce
滚动列表

### What is expected?
正常渲染

### What is actually happening?
列表项出现空白

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.1 |
| Browser | Chrome |

![20200619144538](https://user-images.githubusercontent.com/1337490/85104677-96bced80-b23b-11ea-8f41-a228617885bb.png)

**Comment by llkui** [comment]
+1 遇到同样的问题

**Comment by superjulius** [comment]
We are also facing the same issue after upgrading to 9.2.x. Looks like the issue is not reproducible with 9.1.2

**Comment by whb1993** [comment]
+1

**Comment by vthinkxie** [comment]
Hi @superjulius 
you are right, there is an error in #5425, I will fix it soon.
