### ISSUE TITLE
NzSortFn not work when set nzFrontPagination to false on nzTable component

### ISSUE THREAD

**Issue by Celles** [NG-ZORRO/ng-zorro-antd#5457]
### Reproduction link
[https://stackblitz.com/edit/angular-xsdpnt-8q2ppd](https://stackblitz.com/edit/angular-xsdpnt-8q2ppd)

### Steps to reproduce
The top table is without pagination and click the th which has sort button, nothing happend.
The bottom table's sort works fine with pagination

### What is expected?
I want to use sort function on table component without pagination

### What is actually happening?
Can't use nzSortFn without front pagination

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.1 |
| Browser | Google Chrome 85.0.4175.0 |

**Comment by abhinav82ify** [comment]
I was facing the same problem. This is an issue but there is a workaround to it. The workaround is to only use `[nzShowPagination]="false"` and skip `nzFrontPagination`.

https://stackblitz.com/edit/angular-xsdpnt-yavavr

**Comment by Celles** [comment]
> I was facing the same problem. This is an issue but there is a workaround to it. The workaround is to only use `[nzShowPagination]="false"` and skip `nzFrontPagination`.
> 
> https://stackblitz.com/edit/angular-xsdpnt-yavavr

Yeah，but your workaround still have a serious problem，your data is still paginated，the table only shows the first 10 data, and  i think it is not a good idea to change the pagesize every time you get the data. But it's still a workaround, thanks for your reply

**Comment by abhinav82ify** [comment]
> > I was facing the same problem. This is an issue but there is a workaround to it. The workaround is to only use `[nzShowPagination]="false"` and skip `nzFrontPagination`.
> > https://stackblitz.com/edit/angular-xsdpnt-yavavr
> 
> Yeah，but your workaround still have a serious problem，your data is still paginated，the table only shows the first 10 data, and i think it is not a good idea to change the pagesize every time you get the data. But it's still a workaround, thanks for your reply

Yes, I missed that. There is still a workaround in which you can set the default page size using `nzPageSize`. You could set the default page size to a very high value. `[nzPageSize]="10000"`

**Comment by Celles** [comment]
> > > I was facing the same problem. This is an issue but there is a workaround to it. The workaround is to only use `[nzShowPagination]="false"` and skip `nzFrontPagination`.
> > > https://stackblitz.com/edit/angular-xsdpnt-yavavr
> > 
> > 
> > Yeah，but your workaround still have a serious problem，your data is still paginated，the table only shows the first 10 data, and i think it is not a good idea to change the pagesize every time you get the data. But it's still a workaround, thanks for your reply
> 
> Yes, I missed that. There is still a workaround in which you can set the default page size using `nzPageSize`. You could set the default page size to a very high value. `[nzPageSize]="10000"`
> https://stackblitz.com/edit/angular-xsdpnt-yavavr

Yep，but like i said before， i don't think it's not a good way to solve this problem。Hope someone can fix this problem，and again，thanks for your reply

**Comment by RuudH** [comment]
Hi, we are also seeing this issue. Is there any progress on fixing this?

**Comment by saurabh47** [comment]
> > > I was facing the same problem. This is an issue but there is a workaround to it. The workaround is to only use `[nzShowPagination]="false"` and skip `nzFrontPagination`.
> > > https://stackblitz.com/edit/angular-xsdpnt-yavavr
> > 
> > 
> > Yeah，but your workaround still have a serious problem，your data is still paginated，the table only shows the first 10 data, and i think it is not a good idea to change the pagesize every time you get the data. But it's still a workaround, thanks for your reply
> 
> Yes, I missed that. There is still a workaround in which you can set the default page size using `nzPageSize`. You could set the default page size to a very high value. `[nzPageSize]="10000"`
> https://stackblitz.com/edit/angular-xsdpnt-yavavr


In case of ```[nzShowPagination] = false``` it only shows 10 rows & [nzScroll] = { y : '200px' } also doesn't works.
It does not shows the scrollbar for more than 10 rows.

@Celles , in case of large number of page size scroll works `[nzPageSize]="10000"`
Thanks for the workaround

Please fix this issue.

| Library | Version |
|--- | --- |
| ng-zorro-antd | ^9.3.0 |

Thank you so much to all the contributors for such a awesome design system/component library.

**Comment by cromat** [comment]
Are there any improvements regarding this issue? It is still there.

**Comment by liwei511** [comment]
Is it hard to fix

**Comment by Eve-Sama** [comment]
This bug has been fixed in V11 of Zorro. If you are using V10, you can set `nzPageSize` to `Infinity` to skip this problem.
