### ISSUE TITLE
nz-spin中可不可以添加一个延迟取消加载效果的时间？

### ISSUE THREAD

**Issue by qq253498229** [NG-ZORRO/ng-zorro-antd#5458]
## What problem does this feature solve?
和nzDelay类似的，也是为了防止闪烁，提高用户体验

## What does the proposed API look like?
nzDelayHide

**Comment by hsuanxyz** [comment]
`[nzDelay]`

**Comment by qq253498229** [comment]
> `[nzDelay]`

。。。。。我的意思是ngDelay是加载延迟，能不能出一个消失的延迟

**Comment by hsuanxyz** [comment]
@qq253498229 🤔 Ant Design 规范还没有包含此行为，从效果上来看都是防止闪烁，如果能在预留时间内准备好资源而不显示 spin 用户体验也应该会更好。如果你的场景的确需要每次都出现 spin 你可以使用 RxJS 的 `delay` 操作符轻松实现。
