### ISSUE TITLE
nz-badge nzShowDot 无效

### ISSUE THREAD

**Issue by cinling** [NG-ZORRO/ng-zorro-antd#5461]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-pljqm](https://codesandbox.io/s/ng-zorro-antd-ivy-pljqm)

### Steps to reproduce
nzShowDot 无效。

### What is expected?
nzShowDot为 false 时，不显示 徽标

### What is actually happening?
nzShowDot为 true 或 false，徽标都显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | chrome |

**Comment by hsuanxyz** [comment]
@cinling 感谢你的反馈，经过检查我们发现 `[nzShowDot]` 是重构是意外引入的属性，它与 `[nzCount]="0"` 时的行为重复了，我们将在 v10 版本中弃用它。
