### ISSUE TITLE
 i cant't get  value from <nz-input/> when i click enter.

### ISSUE THREAD

**Issue by jiangjianyu** [NG-ZORRO/ng-zorro-antd#547]
<nz-input **#box** [nzType]="'search'" [nzPlaceHolder]="'search'" **(keyup.enter)="onEnter(box.value)"**></nz-input>

In the ts:
onEnter(value: string){
    console.log(value);  **//it's  undefined**
  }
**but when i use **<input **#box** (keyup.enter)="onEnter(box.value)"**><input>****
In the ts:
onEnter(value: string){
    console.log(value);  **//i can get value**
  }
what should i do??

**Comment by Feng-JY** [comment]
try <input #box (keyup.enter)="onEnter(box.nzValue)">
