### ISSUE TITLE
nz-upload 存在filelist内容时触发异常

### ISSUE THREAD

**Issue by ManonLoki** [NG-ZORRO/ng-zorro-antd#5484]
### Reproduction link
[https://stackblitz.com/edit/angular-ivy-rock8s](https://stackblitz.com/edit/angular-ivy-rock8s)

### Steps to reproduce
官网picture-card示例

### What is expected?
显示图片，无异常

### What is actually happening?
显示图片 并触发异常

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | chrome |

---
Debug追踪原因得知
NzUploadList组件 OnChange钩子调用了 this.fixedData()
fixedData()函数调用了this.locale 
由于this.local 是由 NzUpload组件传入的参数
而NzUpload获取locale是在 OnInit钩子中进行订阅的
因此此时的 NzUploadList 中的locale默认值会被覆盖为undefined 从而引起此bug

**Comment by cipchk** [comment]
duplcated of #5472
