### ISSUE TITLE
Icon 404 (Not Found) after update from 9.1.2 to 9.2.2

### ISSUE THREAD

**Issue by rockcoolt** [NG-ZORRO/ng-zorro-antd#5485]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-j4xycw](https://stackblitz.com/edit/ng-zorro-antd-ivy-j4xycw)

### Steps to reproduce
Configure your application for dynamic icon importing.
In angular.json put this:

"assets": [
    {
      "glob": "**/*",
      "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
      "output": "/assets/"
    }
  ] 

### What is expected?
Http request found icon

### What is actually happening?
Some icons are not found 
ex: http://localhost:4200/assets/outline/dashboard.svg 404 (Not Found)
Before version 9.2.2 i did not have this issue.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | Chrome |

**Comment by wendellhu95** [comment]
Please provide a valid reproduction. You can create a repo on GitHub and share it with us.

**Comment by rockcoolt** [comment]
I found this: 
When i use **yarn install** i have the issue
with **npm install** not

Thank you
