### ISSUE TITLE
How to implement light/dark theme toggle?

### ISSUE THREAD

**Issue by IsaacHub** [NG-ZORRO/ng-zorro-antd#5491]
## What problem does this feature solve?
The instruction in this page [https://ng.ant.design/docs/customize-theme/en#switch-theming](https://ng.ant.design/docs/customize-theme/en#switch-theming) is not clear, it would be great if you provide a "stackblitz" example.

## What does the proposed API look like?
There are 2 separate pieces of code provided in [https://ng.ant.design/docs/customize-theme/en#switch-theming](https://ng.ant.design/docs/customize-theme/en#switch-theming) , but I have no idea what should be the file name, where should it be placed? How and when should it be called? It will be great if you update that page with an example of doing that on **stackblitz**

**Comment by vthinkxie** [comment]
https://stackoverflow.com/questions/61901234/how-to-change-the-ng-zorro-theme-at-runtime

**Comment by IsaacHub** [comment]
That was terrible and childish solution, because it's not intuitive and caused **Flash Of Unstyled Content(FOUC)**

Here is the enterprise-grade professional way of doing it using css variables 
https://stackblitz.com/edit/dark-mode-with-angular-and-css-variables-4bjhu3

**Comment by BeginsDuang** [comment]
```
# yarn
yarn add less -D less-plugin-clean-css -D less-plugin-npm-import -D
# npm
# npm i less -D less-plugin-clean-css -D less-plugin-npm-import -D
```

> project root: create `theme.js`

``` typescript
const less = require("less");
const LessPluginCleanCSS = require("less-plugin-clean-css");
const LessPluginNpmImport = require("less-plugin-npm-import");
const fs = require("fs");
const darkThemeVars = require("ng-zorro-antd/compact-theme");
const compactThemeVars = require("ng-zorro-antd/dark-theme");
const appStyles = "src/assets/styles/zorro.less"; // 应用的样式入口文件 style entry path for the application
const themeContent = `@import '${appStyles}';`;

function gen(type) {
  return less
    .render(themeContent, {
      javascriptEnabled: true,
      plugins: [
        new LessPluginNpmImport({ prefix: "~" }),
        new LessPluginCleanCSS({ advanced: true }),
      ],
      modifyVars: {
        ...(type === "dark" ? darkThemeVars : compactThemeVars),
      },
    })
    .then((data) => {
      fs.writeFileSync(
        // 主题样式的输出文件 output path for the theme style
        `src/assets/themes/style.${type}.css`,
        data.css
      );
    })
    .catch((e) => {
      // 记录渲染错误 log the render error
      console.error(type, e);
    });
}

Promise.all([gen("dark"), gen("compact")]).then(() => {
  console.log("Success!");
});

```

> terminal run：

```
node ./theme.js
```
