### ISSUE TITLE
nz-table 在电脑分辨率布局大小为125%的状态下，设置x,y固定滚动，会出现明显的错位（Chrome浏览器）

### ISSUE THREAD

**Issue by zmzimpl** [NG-ZORRO/ng-zorro-antd#5496]
### Reproduction link
[https://stackblitz.com/edit/angular-rve5mb](https://stackblitz.com/edit/angular-rve5mb)

### Steps to reproduce
将电脑分辨率布局大小设置为125%，固定列会出现明显错位
![image](https://user-images.githubusercontent.com/27490895/86227939-54db6200-bbc0-11ea-967b-51dac73e16c8.png)

### What is expected?
固定列不错位

### What is actually happening?
固定列出现错位

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | Chrome |

---
不是调整浏览器大小比例，是更改电脑的布局文本大小比例，我用的是Window系统

**Comment by hsuanxyz** [comment]
duplicate #4396
