### ISSUE TITLE
nz-upload 组件设置nzFileType属性后，选择文件时能否过滤为可选的文件，如果选择文件与限制文件类型不一致时， 请弹出提醒信息

### ISSUE THREAD

**Issue by zst20160902** [NG-ZORRO/ng-zorro-antd#5500]
## What problem does this feature solve?
设置nzFileType属性后， 用户选错文件类型时，没有信息提示，体验不友好！ 如果过滤为用户可选择的文件类型， 可避免用户选错文件！

## What does the proposed API look like?
不改变API

**Comment by cipchk** [comment]
你可以使用 `nzFilter` 来定制这类需求。

**Comment by zst20160902** [comment]
nzFilter在选择文件时可以进行判断达到过滤效果， 能否直接在弹出选择文件窗口加上过滤条件，类似于下图
![S{U% 96LNF67 U~PL FJLD6](https://user-images.githubusercontent.com/40650757/86322305-4eef8a80-bc6d-11ea-9292-60fbac1284d7.png)

**Comment by cipchk** [comment]
使用 `nzAccept`

**Comment by zst20160902** [comment]
那么 nzFileType 与 nzAccept 属性用途是否类似？能否用 nzFileType 代替 nzAccept  ？

**Comment by cipchk** [comment]
`nzFileType`、`nzSize`、`nzLimit` 实际内部都是转化成 `nzFilter`，它们只是简化了运用而已，这是属于编码形式；`nzAccept` 是面向浏览器自带的形式。

**Comment by zst20160902** [comment]
谢谢！明白了

**Comment by xingkoo** [comment]
那么我这么理解正确吗？

```
<input
  type="file"
  #file
  (change)="onChange($event)"
  [attr.accept]="options.accept" 
  [attr.directory]="options.directory ? 'directory' : null"
  [attr.webkitdirectory]="options.directory ? 'webkitdirectory' : null"
  [multiple]="options.multiple"
  style="display: none"
/>
<ng-content></ng-content>
```
所以，nzAccept最终对应到html的Input的，作用于弹出的文件选择框过滤。

`nzFileType`是应用在程序中的软性过滤。如果这个条件不满足，则文件不会被上传。

**Comment by zst20160902** [comment]
可以这么理解

> 那么我这么理解正确吗？
> 
> ```
> <input
>   type="file"
>   #file
>   (change)="onChange($event)"
>   [attr.accept]="options.accept" 
>   [attr.directory]="options.directory ? 'directory' : null"
>   [attr.webkitdirectory]="options.directory ? 'webkitdirectory' : null"
>   [multiple]="options.multiple"
>   style="display: none"
> />
> <ng-content></ng-content>
> ```
> 
> 所以，nzAccept最终对应到html的Input的，作用于弹出的文件选择框过滤。
> 
> `nzFileType`是应用在程序中的软性过滤。如果这个条件不满足，则文件不会被上传。
