### ISSUE TITLE
表格筛选单选时给NzTableFilterList中的value传0或false会抛出null

### ISSUE THREAD

**Issue by cjzzzz** [NG-ZORRO/ng-zorro-antd#5505]
### Reproduction link
[https://stackblitz.com/edit/antd9-single-filter](https://stackblitz.com/edit/antd9-single-filter)

### Steps to reproduce
筛选 0 无效
【源码：filter.component.ts第134行代码：this.filterChange.emit(listOfChecked[0] || null)有问题】

### What is expected?
筛选单选时给value传什么就抛出什么

### What is actually happening?
筛选单选时给value传0或false会抛出null

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | Chrome |

**Comment by maojj** [comment]
+1 , same problem
source code:
https://github.com/NG-ZORRO/ng-zorro-antd/blob/4dcc428fc68913abb36e81f1009d5e86c3887b16/components/table/src/addon/filter.component.ts#L134
