### ISSUE TITLE
zorro从7升级到9后，栅格布局nz-row与nz-col之间多了一层自定义的标签，栅格布局不生效

### ISSUE THREAD

**Issue by 007GitHu** [NG-ZORRO/ng-zorro-antd#5508]
### Reproduction link
[https://stackblitz.com/edit/angular-nmgbo1?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-nmgbo1?file=src/app/app.component.ts)

### Steps to reproduce
<form nz-form [formGroup]="validateForm" class="ant-advanced-search-form">  
   <div nz-row >
        <app-test>
         <div nz-col [nzSpan]="8" >
          <nz-form-item>
            <nz-form-label >FieldFieldFieldField </nz-form-label>
            <nz-form-control>
              <input nz-input placeholder="placeholder" />
            </nz-form-control>
          </nz-form-item>
        </div> 
       </app-test>
      </div>
</form>

### What is expected?
栅格布局nz-row与nz-col之间能加上自定义的标签，封装各个组件后，使用时会有一层标签，而9版本栅格布局中，多了一层自定义的标签，栅格布局失效

### What is actually happening?
可自定义标签

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | 谷歌浏览器 |

**Comment by vthinkxie** [comment]
在 9 的时候样式同步了 ant design 4.0 的设计方案，在4.0 的设计方案中，所有的样式均采用 flex 布局，对于中间增加嵌套标签的情况不再支持

**Comment by 007GitHu** [comment]
不支持中间嵌套标签，那封装组件怎么办

**Comment by vthinkxie** [comment]
nz-row 与 nz-col 都是 directive， 可以直接和你的组件混用，nz-col 是可以直接写在你的组件上的

**Comment by 007GitHu** [comment]
没有其他办法了吗，这样对已有的系统改造非常大

**Comment by vthinkxie** [comment]
也可以给已有的组件上增加css样式，或者不引入 nz-col 和 nz-row 的 module，自己实现 nz-col 和 nz-row
