### ISSUE TITLE
nz-table 表头分组下 nzNoResult 会错位

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#5509]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-nyczup?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-alain-setup-nyczup?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce

这种情况只会在使用 `*ngFor` 渲染表头时才会发生。

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | All |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-alain-setup-hxst1l?file=src%2Fapp%2Fapp.component.html
可以先这么解决，后面也支持了[colSpan]和[rowSpan]的写法
