### ISSUE TITLE
about show Modal For Component

### ISSUE THREAD

**Issue by PollionChang** [NG-ZORRO/ng-zorro-antd#551]
使用 modal for component时候如果在modal显示的时候手动从地址栏切换路由，modal不会消失，但是 <router-outlet></router-outlet>内页面已经切换到相应的模块(组件）下。
查看原因后发现是因为所创建的<nz-modal>属于<body>的子节点与rootComponent 的selector（<app-root>）属于同级，所以在切换路由的时候属于<router-outlet></router-outlet>外内容，因此没有变化。希望有相应办法解决。或者提供一些思路。

**Comment by vthinkxie** [comment]
duplicated #447
