### ISSUE TITLE
Upload component how to set upload parameters

### ISSUE THREAD

**Issue by fengzhihenxs** [NG-ZORRO/ng-zorro-antd#5513]
## What problem does this feature solve?
When uploading, you need to pass some parameter settings

## What does the proposed API look like?
Zorro Upload required parameters

**Comment by cipchk** [comment]
You can use the following parameters:

- `nzData` Uploading params or function which can return uploading params
- `nzHeaders` Set request headers

If none of the above meets the parameters, you can customize the request via `nzCustomRequest`.

**Comment by fengzhihenxs** [comment]
@cipchk Thanks, according to the documentation I have achieved
