### ISSUE TITLE
选择器用户搜索滚动条没有正确显示数据

### ISSUE THREAD

**Issue by Yenaele** [NG-ZORRO/ng-zorro-antd#5514]
### Reproduction link
[https://codesandbox.io/s/happy-morning-p5x2j?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/happy-morning-p5x2j?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
点击输入框，出现下拉列表选项时往下滚动，出现部分数据不显示的情况

### What is expected?
数据完整显示，可以滚动向下查找

### What is actually happening?
部分数据在滚动中不显示，必须一直往下滚才显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
duplicated #5514

**Comment by Yenaele** [comment]
> duplicated #5514

#5514 is this issue
can you tell me this bugs process

**Comment by vthinkxie** [comment]
@Yenaele sorry it is #5456
