### ISSUE TITLE
getCheckedNodeList() from Tree doesn't return the checked nodes when using the `checked` property from NzTreeNodeOptions

### ISSUE THREAD

**Issue by IonelLupu** [NG-ZORRO/ng-zorro-antd#5519]
### Reproduction link
[https://stackblitz.com/edit/angular-5f15lf?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-5f15lf?file=src/app/app.component.ts)

### Steps to reproduce
Create a nz-tree with these nodes:
```
  nodes: NzTreeNodeOptions[] = [
    { title: 'leaf 1-0-0', key: '10010', isLeaf: true, checked: true },
    { title: 'leaf 1-0-1', key: '10011', isLeaf: true }
  ];
```
Then, call `getCheckedNodeList()` on the `nzTreeComponent` template reference to try getting the checked nodes. You will see the method will return an empty array instead of one NzTreeNode item in the array.

### What is expected?
To return all the check nodes from the tree when using `checked: true` inside `NzTreeNodeOptions`.

### What is actually happening?
We get and empty array

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | * |

---
I want to mention that the method `getCheckedNodeList` returns correctly when we are using `nzCheckedKeys` instead of the `checked` key from `NzTreeNodeOptions`

**Comment by kalista124** [comment]
How can I get all the checked keys to push them into an array?

**Comment by IonelLupu** [comment]
@kalista124 in my case, I had to pass the checked keys inside the `[nzCheckedKeys]` attribute and not use the `checked` property from `NzTreeNodeOptions` at all.

Then, to get the nodes, I just used `getCheckedNodeList()` as usual.
