### ISSUE TITLE
nz-upload can't read cloudimage convert url, this url work with html img tag

### ISSUE THREAD

**Issue by rockcoolt** [NG-ZORRO/ng-zorro-antd#5520]
### Reproduction link
https://stackblitz.com/edit/angular-24aycx-jltcez

### Steps to reproduce
Use nz-upload with cloudimage convert url

### What is expected?
 nz-upload read cloudimage url

### What is actually happening?
 nz-upload can't read cloudimage url (html img tag can so, i think it's a bug)

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | Chrome |

**Comment by cipchk** [comment]
Do you mean that `fileList[1].url` cna't be displayed? But what I see can be displayed:

png:

![image](https://user-images.githubusercontent.com/2987467/86745781-2bfa1780-c06d-11ea-8e4f-d2aec2a9626f.png)

**Comment by rockcoolt** [comment]
The 1st image can't be displayed 
This: 
  {
      uid: '-1',
      name: 'image.png',
      status: 'done',
      url: 'http://demo.cloudimg.io/v7/sample.li/satie2.pdf?w=800&force_format=png'
    },

**Comment by cipchk** [comment]
Yes, can't parse whether the image is valid for this type of address. but you can via `nzPreviewFile ` 
 to fixed, pls refer to [Customize preview file](https://ng.ant.design/components/upload/en#components-upload-demo-preview-file) demo.

**Comment by rockcoolt** [comment]
I have already try nzPreviewFile but, nzPreviewFile is called when the user add new image.
In my case is when i initialize nz-upload with nzFileList.
It don't work here :(
