### ISSUE TITLE
nz-table without nzData , but with static table rows displays "no data"

### ISSUE THREAD

**Issue by IsaacHub** [NG-ZORRO/ng-zorro-antd#5522]
### Reproduction link
[https://stackblitz.com/edit/angular-y3fp41](https://stackblitz.com/edit/angular-y3fp41)

### Steps to reproduce
create `nz-table` without nzData, but with static values of <tbody>

### What is expected?
Label "No data" should not be visible.

### What is actually happening?
Label "No data" is getting displayed below the static rows.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | All |

**Comment by vthinkxie** [comment]
nzTemplateMode
