### ISSUE TITLE
Translation for nz-breadcrumb with autoGenerate enabled

### ISSUE THREAD

**Issue by deedarb** [NG-ZORRO/ng-zorro-antd#5523]
## What problem does this feature solve?
In routes there is option to add to data "breadcrumb" property, which will be used in breadcrumb autogeneration. If app have multiple translation languages then there is no option to translate "breadcrumb".

## What does the proposed API look like?
```html
<nz-breadcrumb [nzAutoGenerate]="true">
  <nz-breadcrumb-template>{{breadcrumb | customTranslatePipe}}</nz-breadcrumb-template>
</nz-breadcrumb>
```
or pass function
```html
<nz-breadcrumb [nzAutoGenerate]="true" [labelFn]="customTranslationFn"></nz-breadcrumb>
```

**Comment by wendellhu95** [comment]
That's a good idea! @deedarb Welcome to submit a PR. We will review it ASAP.

**Comment by deedarb** [comment]
Hi, thanks for response, i'll try to implement it, which API is OK? 
Passing function or template or both? Names of attributes/tags is OK?
Maybe change labelFn to nzLabelFn?

**Comment by deedarb** [comment]
sorry for commenting in closed issue, implemented function should handle promises and have type:

`(label: string) => string | Promise<string>`

this is required if you use **ngx-translate** or **transloco** services, they provide async and sync methods to translate, but if you use sync translate and provider didn't finished downloading translation it will not provide translation

should i open new issue?
