### ISSUE TITLE
Add the slick-carousel component

### ISSUE THREAD

**Issue by taksumaki** [NG-ZORRO/ng-zorro-antd#5534]
## What problem does this feature solve?
This component may solve the problem that some users want to add more than just one item to a carousel, since the carousel component only allows one item per page. With this you could add more than one item per page of the carousel and make it more dynamic to display content on cards, such as products, etc.

## What does the proposed API look like?
In order to solve this problem, I propose to add the slick-carousel component so that users can have a new feature that could be very useful.

This is an example:
https://codepen.io/Raddy/full/NojQmd

If this can be accomplished with the current carousel component, I would be very grateful if you could give me examples on how to implement it and be able to use it, thank you very much in advance for the attention.

**Comment by wendellhu95** [comment]
![image](https://user-images.githubusercontent.com/12122021/87002311-e57ef700-c1eb-11ea-98fd-dd76145e803b.png)

Hi @taksumaki. If you inspect the DOM structure of the demo, you can see that each section is actually an carousel item. IMHO, it could be implemented with the current Carousel component.

**Comment by wendellhu95** [comment]
sa
