### ISSUE TITLE
date-picker 在ie下默认出现focus状态

### ISSUE THREAD

**Issue by lihuabest** [NG-ZORRO/ng-zorro-antd#5538]
### Reproduction link
[https://codesandbox.io/s/68i4v](https://codesandbox.io/s/68i4v)

### Steps to reproduce
https://ng.ant.design/components/date-picker/zh 在ie下打开你们的官网就可以看到

### What is expected?
不要默认focus

### What is actually happening?
默认focus，直接就显示了选择面板

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | ie浏览器 |

**Comment by Smilewangjing** [comment]
这个问题能优先解决下吗？

**Comment by wenqi73** [comment]
Please track #5562
