### ISSUE TITLE
bordered table use virtual scroll style incorrect

### ISSUE THREAD

**Issue by wenqi73** [NG-ZORRO/ng-zorro-antd#5555]
### Reproduction link
[https://stackblitz.com/edit/nz-table-vs-border?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/nz-table-vs-border?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
见链接

### What is expected?
border will not exceed

### What is actually happening?
border exceed

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome |

**Comment by CK110** [comment]
https://stackblitz.com/edit/angular-jpea87?file=src/app/app.component.ts
