### ISSUE TITLE
refactor tabs component

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#5557]
## What problem does this feature solve?
refactor tabs component with latest antd

## What does the proposed API look like?
latest antd

**Comment by alvarolb** [comment]
Really like to see Draggable Tabs like on React:
https://ant.design/components/tabs#tabs-demo-custom-tab-bar-node

And extra content on the left:
https://ant.design/components/tabs#tabs-demo-extra

Related issue:
https://github.com/NG-ZORRO/ng-zorro-antd/issues/3461
