### ISSUE TITLE
After inputting Chinese characters in the multiple select, the cursor will move before the entered text

### ISSUE THREAD

**Issue by ousc** [NG-ZORRO/ng-zorro-antd#5560]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-glhm9k?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-glhm9k?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Enter Chinese characters in the check box

### What is expected?
Cursor behind text

### What is actually happening?
Cursor in front of text

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Google Chrome 83.0.4103.116（64 bit） |

**Comment by wenqi73** [comment]
Same problem with #5704
