### ISSUE TITLE
IE11DatePicker 加载后就是打开状态

### ISSUE THREAD

**Issue by Caozc** [NG-ZORRO/ng-zorro-antd#5562]
### Reproduction link
[https://codesandbox.io/s/t2t7z](https://codesandbox.io/s/t2t7z)

### Steps to reproduce
使用IE11浏览器打开https://ng.ant.design/components/date-picker/zh 所有选择框均是打开状态

### What is expected?
页面打开时DatePicker选择框 不打开

### What is actually happening?
页面打开时DatePicker选择框全部打开

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | IE11 |

**Comment by Caozc** [comment]
When can this problem be fixed

**Comment by wenqi73** [comment]
@Caozc 可以切回到 9.2.1 版本

**Comment by akaztp** [comment]
I also need this solved, please! And only a reviewer is needed!

**Comment by wenqi73** [comment]
@akaztp Roll back to 9.2.1 if you are anxious

**Comment by yangyachao** [comment]
NG-ZORRO v10正式版中 DatePicker和TimePicker在IE11下都出现这个问题
