### ISSUE TITLE
Keyboard not showing for search in nz-select

### ISSUE THREAD

**Issue by nestoralonsovina** [NG-ZORRO/ng-zorro-antd#5563]
### Reproduction link
[https://stackblitz.com/edit/angular-ovs1tk](https://stackblitz.com/edit/angular-ovs1tk)

### Steps to reproduce
1. Opening [Ng-zorro demo](https://ng.ant.design/components/select/en#components-select-demo-search) using safari in an iOS simulator
2.In the example with the name "Select with search field" 
3. Click on the select, you will see that it doesn't trigger the keyboard but it works on other examples where nzMode is not "default", with "multiple" or "tags" it works correctly

### What is expected?
iOS keyboard should open on click

### What is actually happening?
The keyboard is not showing up

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Safari 13 |

**Comment by WeslleyDeSouza** [comment]
any infos ?

**Comment by KwFung7** [comment]
Any update on this defect ?

**Comment by KwFung7** [comment]
I figure out a workaround, I simply remove "readonly" attribute in nz-select input element to fix this issue. 

`const inputEle = this.renderer.selectRootElement('nz-select nz-select-search input');`
`this.renderer.removeAttribute(inputEle , 'readonly');`

**Comment by wenqi73** [comment]
Closed via #5953.
