### ISSUE TITLE
关于nz-range-picker 使用体验改进的建议~

### ISSUE THREAD

**Issue by bianyuanfei** [NG-ZORRO/ng-zorro-antd#5572]
## What problem does this feature solve?
前景提要：在使用nz-range-picker（nzShowTime）组件时，在已设置好初始日期和时分秒的情况下。若我去修改起始日期
时，选的日子是在结束日期之后的，react版本和angular在此刻会有如下不同的事件发生：<br />
&#8195;&#8195;react版本中，假设此时起始结束日期都已设好，当前我去修改起始时间，若起始时间超过已选好的结束时间（点确定按钮后），会在设置好当前起始日期后清空结束时间，并且光标跳转到结束日期，这时会有一个disable，不让选起始日期之前的日子（十分合理）。
地址： <https://ant.design/components/date-picker-cn/><br />
&#8195;&#8195;然而angular版本中，没有等我点确定按钮，只修改了日期，年月日时和分就立马全都进行了互换，并且光标也没有跳转仍在起始日期位置，也就是说我曾经设好的初始的时分秒被转移到了结束日期的位置，此时再点击时分秒修改的不是我刚刚选的日子的时分秒。如果我不停的点击起始日期，不断把日子延后，就会出现时分秒不断互换的情况。十分容易混淆让人迷糊。
地址：<https://ng.ant.design/components/date-picker/zh>

## What does the proposed API look like?
建议：
  &#8195;选项1.像react版本一样点击确认按钮后（即选完时分秒）再执行，或者改变光标位置（即移到结束日期，因为还有修改时分秒的需求），否则我明明选的日子是结束日期，却还是停留在当前的初始日期位置，修改的就是初始日期的时分秒。
  &#8195;&#8195;选项2. 参考react版本，点击确认按钮后（即选完时分秒）再执行，不互换日期及时分秒，直接将后面的结束日期清空，并跳转光标去选新的结束日期。
建议：react版本有对日期的disable功能，建议加入，最好也加入对时分秒disable的功能（前不能选后，后不能选前），就没有上面那么多困扰啦。

**Comment by vthinkxie** [comment]
感谢建议，cc @wenqi73 看一下这个
