### ISSUE TITLE
select component exception

### ISSUE THREAD

**Issue by fengzhihenxs** [NG-ZORRO/ng-zorro-antd#5573]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-y4skye?file=package.json](https://stackblitz.com/edit/ng-zorro-antd-ivy-y4skye?file=package.json)

### Steps to reproduce
Open Modal, select select, close the modal after the selection is completed, open Modal again to delete the previously selected item, then ERROR Error: Cannot read property'zoomMotion' of undefined will be reported, and the selected item will not be deleted

### What is expected?
Normally open Modal again to delete the previously selected items

### What is actually happening?
Open Modal again to delete the selected item, it will report ERROR Error: Cannot read property'zoomMotion' of undefined, and the selected item cannot be deleted

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | Chrome |

**Comment by fengzhihenxs** [comment]
This is  error message
![image](https://user-images.githubusercontent.com/37610470/87739289-17a6df00-c812-11ea-8030-628585927251.png)

**Comment by fengzhihenxs** [comment]
@vthinkxie   Hi ,has this problem been resolved soon? This is the case. If the project needs to be resolved in the near future, I need to consider other methods to replace it.

**Comment by vthinkxie** [comment]
this is a duplicated of https://github.com/NG-ZORRO/ng-zorro-antd/issues/5290
and blocked by https://github.com/angular/angular/issues/24041

**Comment by fengzhihenxs** [comment]
@vthinkxie Don't worry, I don't understand how to solve it?

**Comment by fengzhihenxs** [comment]
@vthinkxie  Sorry, I didn't understand how to solve it?

**Comment by vthinkxie** [comment]
> @vthinkxie Sorry, I didn't understand how to solve it?

we can do nothing until angular fix it

**Comment by fengzhihenxs** [comment]
@vthinkxie   Ok， thank you very much

**Comment by LEXXEI** [comment]
> 
> 
> @vthinkxie Sorry, I didn't understand how to solve it?

@fengzhihenxs try use visible of nz-modal in *ngIf inside nz-select. I solved a similar problem in #5290

**Comment by fengzhihenxs** [comment]
@LEXXEI Ok, thank you. I will try when I have time

**Comment by huangchaofei** [comment]
@fengzhihenxs  thanks a lot,this solved my problem
