### ISSUE TITLE
Why is show arrrow not avaible on multi or tag select

### ISSUE THREAD

**Issue by DepickereSven** [NG-ZORRO/ng-zorro-antd#5575]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-ppxcmt](https://stackblitz.com/edit/ng-zorro-antd-ivy-ppxcmt)

### Steps to reproduce
Open the link.
The first select has an arrow icon and a search icon when you open the select.

The second select is a multi-select and doesn't have an arrow icon.
While I added the `[nzShowArrow]` and set it on `true`. 
In the documentation, there is no mention that the arrow icon doesn't work in multi-select mode.

### What is expected?
That I see the arrow icon in multi-select

### What is actually happening?
No arrow icon in multi-select

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Firefox Developer version 79.0b8 (64-bits), Firefox version 79.0b8 (64-bits), Google Chrome Version 84.0.4147.89 (64-bit)  |

---
`[nzShowSearch]` isn't also working in multi-select but that's mentioned in the documentation, but would it be possible to make it aviable in multi-select? If no, can you explain what the reason behind this choice is?

**Comment by DepickereSven** [comment]
@hsuanxyz I made a PR #5650 to fix this issue

**Comment by DepickereSven** [comment]
@vthinkxie 

By ant-design are you referring to this library https://github.com/ant-design/ant-design/? 

Because when I look in their docs I find the following:

<img width="905" alt="Schermafbeelding 2020-09-15 om 11 51 16" src="https://user-images.githubusercontent.com/26543813/93195660-c8195c80-f749-11ea-8dd5-6a915532a3db.png">

So for multi-select and tags is by default on false. But it's possible to set the showArrow on true so you can see it.

Like you can see in the following example the icons work in multi and tag mode.

https://stackblitz.com/edit/react-vrppip?file=index.js

**Comment by vthinkxie** [comment]
Hi @DepickereSven 
you are right, can you submit a new PR to make showArrow work and keep it false when in multiple select?
thanks

**Comment by DepickereSven** [comment]
@vthinkxie here is the PR #5785
