### ISSUE TITLE
nz-steps: incorrect mouse pointer and click behavior for enabled and disabled steps

### ISSUE THREAD

**Issue by ccppprogrammer** [NG-ZORRO/ng-zorro-antd#5579]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-disabled-steps](https://stackblitz.com/edit/ng-zorro-antd-ivy-disabled-steps)

### Steps to reproduce
1. Click on the Enable button.
2. Click on the Disable button.

### What is expected?
1. Cursor should be pointer.
2. Cursor shouldn't be pointer and shouldn't let click on any steps.

### What is actually happening?
1. Click on the Enable button. The cursor pointer is invalid. Cursor should be pointer. After clicking on any step, cursor becomes a pointer.
2. Click on the Disable button. The cursor pointer is invalid. Cursor should be default and shouldn't let click on any steps. After clicking on any step, cursor becomes default.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Google Chrome 84.0.4147.89 (Official Build) (64-bit) |

**Comment by hsuanxyz** [comment]
component is OnPush, you can't set the state by modifying the `nzDisabled` value, the only thing we need to add 'enable / disable' methods for the component.
