### ISSUE TITLE
Progress bar with step not working dynamically

### ISSUE THREAD

**Issue by filippocazzarolli** [NG-ZORRO/ng-zorro-antd#5585]
### Reproduction link
[https://2vqekl.run.stackblitz.io](https://2vqekl.run.stackblitz.io)

### Steps to reproduce
Progress bar with step not working dynamically

### What is expected?
bar not change

### What is actually happening?
bar change color

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome 84 |

**Comment by wendellhu95** [comment]
@filippocazzarolli Thanks for your feedback. Unfortunately we cannot open the reproduction link you provided. Could you please provide another one?

**Comment by filippocazzarolli** [comment]
The progress bar with [nzStep] don't update state after change it.

Sorry i have trouble with stakblitz....  I followed you I pasted the code

```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <nz-progress [nzPercent]="percent"></nz-progress>
    <nz-progress [nzPercent]="percent" [nzSteps]="5"></nz-progress>
    <nz-button-group>
      <button nz-button (click)="decline()"><i nz-icon nzType="minus"></i></button>
      <button nz-button (click)="increase()"><i nz-icon nzType="plus"></i></button>
    </nz-button-group>
  `
})
export class AppComponent  {
  percent = 0;

  increase(): void {
    this.percent = this.percent + 10;
    if (this.percent > 100) {
      this.percent = 100;
    }
  }


  decline(): void {
    this.percent = this.percent - 10;
    if (this.percent < 0) {
      this.percent = 0;
    }
  }
}
```
