### ISSUE TITLE
How to use Popover to load different content？

### ISSUE THREAD

**Issue by yuxl01** [NG-ZORRO/ng-zorro-antd#5586]
## What problem does this feature solve?
I encountered a problem in the implementation of requirements. Click the tree node to pop up the Popover component. The content of the component is determined according to different titles. The official website [nz-content] receives a TemplateRef<void> parameter. Can I declare a function in typescript? How about creating a different TemplateRef<void>? I don't know how to implement it here, so I'm here to ask, the existing DingTalk group is invalid

## What does the proposed API look like?
api can be more detailed

**Comment by yuxl01** [comment]
如果能中文就中文回答吧，我提问都是google翻译的，问题描述是：在tree节点上点击弹出popover,但是弹出的内容要根据据title渲染不同的，我看api[nz-content]能接收一个TemplateRef<void>参数，所以想请问下是否可以在typescript里定义一个函数作为创建popover里的内容的，函数返回值就是TemplateRef<void> 然后把这个函数给[nz-content]，现在问题不知道如何动态创建组件，所以在这里问一下，钉钉群加不了，社区没人回答，所以只能来这里了

**Comment by vthinkxie** [comment]
TemplateRef里面的数据本身就可以是一个动态的，Template 本身就是视图，是数据的映射
数据如果能动态改变，视图自然是动态改变的，不需要创建函数或者动态创建组件

**Comment by yuxl01** [comment]
是这样的，我在一个名为#contentTemplateForTable的 ng-template中放入了一个table ，现在点击某一个节点弹出这个popover并且显示table，我要实现的是点击另外一个不同的节点，依然弹出这个popover只不过里面的内容换成了table以外的其他组件，请问这个怎么实现

**Comment by yuxl01** [comment]
> TemplateRef里面的数据本身就可以是一个动态的，Template 本身就是视图，是数据的映射
> 数据如果能动态改变，视图自然是动态改变的，不需要创建函数或者动态创建组件

是这样的，我在一个名为#contentTemplateForTable的 ng-template中放入了一个table ，现在点击某一个节点弹出这个popover并且显示table，我要实现的是点击另外一个不同的节点，依然弹出这个popover只不过里面的内容换成了table以外的其他组件，请问这个怎么实现

**Comment by vthinkxie** [comment]
如果你需要帮助，请提供你目前的项目的完整stackbliz复现，仅靠描述没有人能知道你代码的逻辑和你想要实现的效果

**Comment by yuxl01** [comment]
> 如果你需要帮助，请提供你目前的项目的完整stackbliz复现，仅靠描述没有人能知道你代码的逻辑和你想要实现的效果

功能实现图片：
![image](https://user-images.githubusercontent.com/44578000/88008722-7f776580-cb43-11ea-84f8-f8b5299664c9.png)
html绑定代码：
![image](https://user-images.githubusercontent.com/44578000/88009085-3ffd4900-cb44-11ea-9ceb-40fc2a7eb832.png)
