### ISSUE TITLE
Zorro build 报错

### ISSUE THREAD

**Issue by rppig42** [NG-ZORRO/ng-zorro-antd#5587]
### Reproduction link
[https://stackblitz.com/edit/1234](https://stackblitz.com/edit/1234)

### Steps to reproduce
请无视上述Sackblitz 链接

我现在使用的版本是9.1.1，在升级zorro后发现跟第三方库有冲突，定位到最近的冲突版本是9.1.2。

我试图编译一个特定commit的的zorro来进一步定位问题，但9.1.2 `npm run build` 报错，9.3.0 `npm run build` 没有问题

### What is expected?
成功build

### What is actually happening?
运行到clean:schematics这一步时出错， 提示 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

**Comment by rppig42** [comment]
尝试过增加 --max_old_space_size 依然无效

**Comment by vthinkxie** [comment]
参照打包源码，目前打包是正常运行的
