### ISSUE TITLE
使用select 选择器时，快捷键复制文本直接到文本框中后宽度没有自动更新

### ISSUE THREAD

**Issue by ferqx** [NG-ZORRO/ng-zorro-antd#560]
使用select 选择器时 快捷键复制文本后宽度没有触发更新(开启拼音输入法下也会),会产生以下样式问题
![default](https://user-images.githubusercontent.com/23183225/32717438-995710d6-c894-11e7-86eb-c476931c0b4b.png)

在本地测试中,使用了(input)方法来解决了这个问题,(nz-select.component.ts)
![qq20171113-171847](https://user-images.githubusercontent.com/23183225/32718083-e458e4ea-c896-11e7-93bb-76db9d57f4d1.png)

**Comment by vthinkxie** [comment]
will be fixed in next version, thanks.
