### ISSUE TITLE
Tables recursive auto-resizing on Zoom

### ISSUE THREAD

**Issue by Adam-Pond** [NG-ZORRO/ng-zorro-antd#5600]
### Reproduction link
[https://z9imki.run.stackblitz.io](https://z9imki.run.stackblitz.io)

### Steps to reproduce
Using the mouse wheel to zoom in chrome, zoom out to 67%. Watch the resizing go into a crazy loop

### What is expected?
It does not go into a crazy loop, resizing each column progressively bigger and bigger

### What is actually happening?
The entire table starts resizing continuously. I believe it has something to do with the appearance of a horizontal scrollbar.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome |

---
This is reproducible on the ngZorro example page.
On firefox, it doesn't enter the loop, but it doesn't handle the horizontal scrollbar correctly.

**Comment by wenqi73** [comment]
This link is expired, could you provide another one with source codes?

**Comment by Adam-Pond** [comment]
I did mention that it was also happening on the example page for the table control.
Having said that, the issue seems to have been resolved and is no longer reproducible.

**Comment by wenqi73** [comment]
@Adam-Pond OK, please contact us if you have a stable reproduction.
