### ISSUE TITLE
cursor blink Inactive nz-select on nzMode multiple or tag

### ISSUE THREAD

**Issue by vietcnttk9a** [NG-ZORRO/ng-zorro-antd#5601]
### Reproduction link
[https://stackblitz.com/edit/angular-2kwhm7](https://stackblitz.com/edit/angular-2kwhm7)

### Steps to reproduce
click into  nz-select

### What is expected?
had  Cursor blink in text-box

### What is actually happening?
don't have Cursor blink when click into nz-select (nzMode="tab" or nzMode="multiple")

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chorm |

**Comment by wenqi73** [comment]
Please track #5704
