### ISSUE TITLE
nz-table causes application to freeze

### ISSUE THREAD

**Issue by WeslleyDeSouza** [NG-ZORRO/ng-zorro-antd#5602]
### Steps to reproduce
standart nz-table api

### What is expected?
Application should run normaly
it worked in version 8.*

### What is actually happening?
Application freezes when nz-table gets loaded

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | IPad - Safari &  IONIC Cordova IPad |

---
Im Using:
"@angular/core": "^9.1.12",
...

This happens only on the IOS Devices..

**Comment by WeslleyDeSouza** [comment]
Has anyone run into the same problem?

**Comment by hsuanxyz** [comment]
This issue has been closed. With only the information that is currently in the issue, we don't have enough information to take action. If you can provide more information, feel free to ping anyone of our maintainers to reopen this issue. Thank you for your contributions
