### ISSUE TITLE
teatArea nzAutosize may get scroll bar

### ISSUE THREAD

**Issue by sunyanan891114** [NG-ZORRO/ng-zorro-antd#5610]
### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
1. set a textarea with nzAutosize which does't have maxRows
2. insert 10  new lines

### What is expected?
The height should change automatically without scrollbar

### What is actually happening?
The scrollbar appears sometime

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | All |

---
I did some search on autosize directive. I think this is caused by the height calculate logic: 
```
let height = Math.round((textarea.scrollHeight - this.inputGap) / this.cachedLineHeight) * this.cachedLineHeight   this.inputGap;
```

**Comment by hsuanxyz** [comment]
https://stackblitz.com/edit/angular-9y7rqz?file=src/app/app.component.ts

Please provide a valid reproduction
