### ISSUE TITLE
nz-upload能否提供一个nzFileListRender示例

### ISSUE THREAD

**Issue by laoyingmo** [NG-ZORRO/ng-zorro-antd#5611]
## What problem does this feature solve?
我的需求要自定义显示整个列表，看文档没有看明白该如何使用，Google了个遍，也没找到相关例子。

## What does the proposed API look like?
最好有示例。

**Comment by cipchk** [comment]
A full demo: https://stackblitz.com/edit/ng-zorro-antd-upload-nzfilelistrender?file=src/app/app.component.ts
