### ISSUE TITLE
Select组件在移动端不能弹出输入法

### ISSUE THREAD

**Issue by BennyCxb** [NG-ZORRO/ng-zorro-antd#5616]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-hudmmr?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-hudmmr?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
在iphone的Safari浏览器中打开，点击select组件

### What is expected?
移动端中点击select组件，弹出输入法，可手动输入数据

### What is actually happening?
点击select组件，不能弹出输入法，导致无法手动输入，只能选择

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Safari |

**Comment by wenqi73** [comment]
Close it via https://github.com/NG-ZORRO/ng-zorro-antd/pull/5953.
