### ISSUE TITLE
After inputting Chinese characters in the tree-select with multiple and showsearch, the cursor will move before the entered text

### ISSUE THREAD

**Issue by ousc** [NG-ZORRO/ng-zorro-antd#5617]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-pgakyt](https://stackblitz.com/edit/ng-zorro-antd-ivy-pgakyt)

### Steps to reproduce
Enter Chinese characters in the check box，in above stackblitz example，input "叶子" or "双亲"

### What is expected?
Cursor behind text

### What is actually happening?
Cursor in front of text

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Google Chrome  84.0.4147.89 |

**Comment by hsuanxyz** [comment]
Fixed in the latest version https://stackblitz.com/edit/angular-zg9avc-3nku5b?file=src/app/app.component.ts
