### ISSUE TITLE
Select组件指定值时不能切换

### ISSUE THREAD

**Issue by Acessss** [NG-ZORRO/ng-zorro-antd#5618]
### Reproduction link
[https://stackblitz.com/edit/angular-pea3sc](https://stackblitz.com/edit/angular-pea3sc)

### Steps to reproduce
nz-select组件在ngModelChange时，手动指定model值

### What is expected?
nz-select组件在ngModelChange时，可以手动指定model的值

### What is actually happening?
model值不能在change时手动指定，值只能是被选中的项目

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

---
@Component({
  selector: 'nz-demo-select-basic',
  template: `
    <nz-select [(ngModel)]="selected" (ngModelChange)="valueChange($event)">
      <nz-option nzValue="jack" nzLabel="Jack"></nz-option>
      <nz-option nzValue="lucy" nzLabel="Lucy"></nz-option>
      <nz-option nzValue="zoe" nzLabel="zoe"></nz-option>
    </nz-select>
    <button (click)="setValue()">test</button>
  `,
  styles: [
    `
      nz-select {
        margin: 0 8px 10px 0;
        width: 120px;
      }
    `
  ]
})
export class NzDemoSelectBasicComponent {
  selected = 'zoe'

  valueChange(value) {
    console.log(value)
    this.selected = 'lucy';
  }

  setValue() {
    this.selected = 'lucy';
  }
}

**Comment by Acessss** [comment]
请问这个问题什么时候能解决呢

**Comment by vthinkxie** [comment]
这个和组件没有任何关系
https://stackblitz.com/edit/angular-pea3sc-1sqnhu

**Comment by Acessss** [comment]
https://stackblitz.com/edit/angular-hlwdfz?file=src/app/app.component.ts
