### ISSUE TITLE
表格头部分组样式不对齐

### ISSUE THREAD

**Issue by Bigredorange** [NG-ZORRO/ng-zorro-antd#5619]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-pecqqt?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-pecqqt?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
表格样式错乱

### What is expected?
表格单元格与表头单元格对齐

### What is actually happening?
表格样式错乱

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-alain-setup-nvc2xh?file=src%2Fapp%2Fapp.component.ts
