### ISSUE TITLE
support custom class for cdk overlay

### ISSUE THREAD

**Issue by PollionChang** [NG-ZORRO/ng-zorro-antd#562]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
When I use the select component  in my project,I found that I can't add classes to passed to the select panel.And then ,I carefully looking at the source，it doesn't have @input panelClass
like Material's select component,Can you add this feature, even if I do it

**Comment by PollionChang** [comment]
oh..I mean I can  do this for you

**Comment by vthinkxie** [comment]
it is easy to add class to `nz-collapse`, I think there is no need to add api to support this.

**Comment by PollionChang** [comment]
@vthinkxie I'm sorry ,maybe  I did not express it clearly,I mean the select component ..
like this <ng-template
      cdkConnectedOverlay
      cdkConnectedOverlayHasBackdrop
      [cdkConnectedOverlayOrigin]="origin"
      (backdropClick)="closeDropDown()"
      (detach)="closeDropDown();"
      (positionChange)="onPositionChange($event)"
      [cdkConnectedOverlayWidth]="_triggerWidth"
      [cdkConnectedOverlayOpen]="_isOpen"
    >

**Comment by vthinkxie** [comment]
@PollionChang it will be great if you want to handle this job.
