### ISSUE TITLE
select 组件多选模式下搜索选项，光标定位不正确

### ISSUE THREAD

**Issue by tirelyl** [NG-ZORRO/ng-zorro-antd#5621]
### Reproduction link
[https://fpzmv8.run.stackblitz.io](https://fpzmv8.run.stackblitz.io)

### Steps to reproduce
将 select 组件设置为多选模式 `nzMode="multiple"` , 切换为中文输入法，输入第一个文字后，光标会跳到文字前面。(官网没有这个问题，StackBlitz 和本地代码均会有这个问题)
![select](https://user-images.githubusercontent.com/20921324/88614068-87925080-d0c1-11ea-9fac-eda722e7cd78.gif)

### What is expected?
用中文输入法输入文字时，光标正确显示在文字末尾

### What is actually happening?
用中文输入法输入文字时，光标会跳到文字最前面

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome |

---
官网没有这个问题，StackBlitz 和本地代码均会有这个问题，复现链接里面可以看到这个问题

**Comment by cyhjojo** [comment]
I have same problem when I use 9.x

**Comment by ousc** [comment]
I have asked this question not long ago, not only the select component, but also the tree-select component with multi-select and searching.

**Comment by charisna** [comment]
+1 I have same problem when I use 9.3.0

**Comment by wenqi73** [comment]
It's the style problem, will be fixed in the next version. Please track #5704
