### ISSUE TITLE
有的icon能正常显示，但有的icon如<i nz-icon nzType="plus-circle" nzTheme="outline"></i>不能显示！

### ISSUE THREAD

**Issue by yurokn** [NG-ZORRO/ng-zorro-antd#5623]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy?file=src%2Fapp%2Fng-zorro-antd.module.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy?file=src%2Fapp%2Fng-zorro-antd.module.ts)

### Steps to reproduce
在stackblitz.com中能显示，但在本地引入NzIconModule后，将<i nz-icon nzType="plus-circle" nzTheme="outline"></i>放入项目无法显示，但是另外一些icon,比如<i nz-icon nzType="question-circle" nzTheme="outline" size="24"></i>就能够正常显示。

### What is expected?
希望所有的icon都能正常显示

### What is actually happening?
部分icon无法在本地显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
stackblitz 与 本地环境是一致的，并且可以直接下载至本地运行

**Comment by yurokn** [comment]
我这是一个已经成型的项目，不是刚新建的项目，无法直接用stackblitz。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Yadong Xie<mailto:notifications@github.com>
发送时间: 2020年7月29日 10:02
收件人: NG-ZORRO/ng-zorro-antd<mailto:ng-zorro-antd@noreply.github.com>
抄送: yurokn<mailto:easygate@live.cn>; Author<mailto:author@noreply.github.com>
主题: Re: [NG-ZORRO/ng-zorro-antd] 有的icon能正常显示，但有的icon如<i nz-icon nzType="plus-circle" nzTheme="outline"></i>不能显示！ (#5623)


stackblitz 与 本地环境是一致的，并且可以直接下载至本地运行

―

**Comment by vthinkxie** [comment]
我的建议是 不存在一个问题在本地会出现，在stackbliz上又会消失的情况
如果这是一个组件的bug的话，一定是可以在stackbliz上复现的，否则就100%不是组件库的问题
如果不是一个组件的bug，你提供的信息没有任何有效的部分能让我们给你提供帮助
