### ISSUE TITLE
网站打不开

### ISSUE THREAD

**Issue by sht819175141** [NG-ZORRO/ng-zorro-antd#5626]
## What problem does this feature solve?
因为 你们让填重现链接，我不会弄那个，所以，提了这个功能 ，我有截图，但是，没找到你们的邮箱，错误报告里没有重现链接，又不能提交，很麻烦，简要说一下，就是，我经常打不开  你们的网站 https://ng.ant.design/docs/introduce/zh  偶尔 可以打开，偶尔打不开，谷歌  火狐  IE edge 我都试了，都有这个问题

## What does the proposed API look like?
正常链接就可以，我的邮箱  sht819175141@163.com 如果需要联系，可以联系我

**Comment by rppig42** [comment]
建议科学上网访问，有困难的话可以访问国内镜像 ng-zorro.gitee.io
