### ISSUE TITLE
date-range-picker 没有自动调整，出现开始时间晚于结束时间的情况

### ISSUE THREAD

**Issue by tirelyl** [NG-ZORRO/ng-zorro-antd#5631]
### Reproduction link
[https://jyfkau.run.stackblitz.io](https://jyfkau.run.stackblitz.io)

### Steps to reproduce
给 `nz-range-picker` 组件添加 `nzShowTime` 属性，开始时间和结束时间都选择同一天，但是开始时间的时分秒比结束时间的时分秒要晚，组件不会自动调整开始时间和结束时间

![date-range-picker](https://user-images.githubusercontent.com/20921324/88906850-819b9b80-d28a-11ea-9308-3a3e0bb862a6.gif)

### What is expected?
`nz-range-picker` 组件能够正确调整开始时间和结束时间的位置

### What is actually happening?
`nz-range-picker` 组件不能正确调整开始时间和结束时间的位置

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

---
只在选择时分秒后，组件不能正确调整位置，只选择 '年/月/日' 可以正确调整时间位置

**Comment by serapme** [comment]
still exist
