### ISSUE TITLE
树形控件虚拟滚动在tabs组件下，虚拟滚动高度有问题

### ISSUE THREAD

**Issue by DawnSouther** [NG-ZORRO/ng-zorro-antd#5632]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-tzv3g?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/ng-zorro-antd-ivy-tzv3g?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1.页面加载完毕后点击tab1
2.滚动tree组件

### What is expected?
虚拟滚动正常渲染

### What is actually happening?
在滚动时先有部分空白，提升到一个高度后才渲染出内容，高度预估是200px左右。
会发现设置的虚拟滚动高度与实际高度不符合，div.cdk-virtual-scroll-content-wrapper渲染高度不正确

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome 84.0.4147.105 |

**Comment by vthinkxie** [comment]
使用lazyload tab

**Comment by DawnSouther** [comment]
> 使用lazyload tab

ok可以了

**Comment by DawnSouther** [comment]
出现了新的问题。
虚拟滚动高度在搜索前后应该是不变的。
在懒加载的情况下，使用[nzSearchValue]="searchValue"和[nzHideUnMatched]="true"属性。
虚拟滚动高度被重置。
情况已在
[https://codesandbox.io/s/ng-zorro-antd-ivy-tzv3g?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/ng-zorro-antd-ivy-tzv3g?fontsize=14&hidenavigation=1&theme=dark)重现

**Comment by hsuanxyz** [comment]
> 出现了新的问题。
> 虚拟滚动高度在搜索前后应该是不变的。
> 在懒加载的情况下，使用[nzSearchValue]="searchValue"和[nzHideUnMatched]="true"属性。
> 虚拟滚动高度被重置。
> 情况已在
> https://codesandbox.io/s/ng-zorro-antd-ivy-tzv3g?fontsize=14&hidenavigation=1&theme=dark重现。
> 在输入框任意输入1-9，向下滚动即可复现

复现链接无效，请新建一个有关 tree 的 issue 以便追踪。

**Comment by TonyJ616** [comment]
@DawnSouther 请问 ‘ 在懒加载的情况下，使用[nzSearchValue]="searchValue"和[nzHideUnMatched]="true"属性。 ’ 这个情况你后来有找到解决方法么

**Comment by DawnSouther** [comment]
> @DawnSouther 请问 ‘ 在懒加载的情况下，使用[nzSearchValue]="searchValue"和[nzHideUnMatched]="true"属性。 ’ 这个情况你后来有找到解决方法么

没有，后来我拿material的cdk重新做了
