### ISSUE TITLE
date-picker: years that contain disabled dates cannot be selected

### ISSUE THREAD

**Issue by QichenZhu** [NG-ZORRO/ng-zorro-antd#5633]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-0kxwq?file=/src/app/app.component.ts](https://codesandbox.io/s/ng-zorro-antd-ivy-0kxwq?file=/src/app/app.component.ts)

### Steps to reproduce
1. Open the demo link
2. Click the date picker
3. Click '2020'

### What is expected?
The Year 2019 should be enabled.

### What is actually happening?
The Year 2019 is disabled.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Google Chrome 83.0.4103.116 |

**Comment by QichenZhu** [comment]
Related to #2194.
I don't think it's necessary to disable years since users may just want to browse the calendar.
BTW, the React version of Ant Design does not disable years.

**Comment by wenqi73** [comment]
@QichenZhu Yeah, year disabled should only work when it's a year picker.
