### ISSUE TITLE
表格穿梭框，无法使用搜索功能

### ISSUE THREAD

**Issue by 007GitHu** [NG-ZORRO/ng-zorro-antd#5641]
### Reproduction link
[https://stackblitz.com/edit/angular-1vgrcr?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-1vgrcr?file=src/app/app.component.ts)

### Steps to reproduce
使用搜索功能无法正确过滤出值

### What is expected?
和8版本一样可以过滤出正确的值

### What is actually happening?
实际效果是过滤效果失效

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | 谷歌 |

**Comment by carolinetanxin** [comment]
> ### Reproduction link
> https://stackblitz.com/edit/angular-1vgrcr?file=src/app/app.component.ts
> 
> ### Steps to reproduce
> 使用搜索功能无法正确过滤出值
> 
> ### What is expected?
> 和8版本一样可以过滤出正确的值
> 
> ### What is actually happening?
> 实际效果是过滤效果失效
> 
> Environment	Info
> ng-zorro-antd	9.3.0
> Browser	谷歌

现在遇到了同样的问题，请问有任何进展吗？👀  @hsuanxyz @wenqi73 @cipchk @007GitHu

**Comment by cipchk** [comment]
@carolinetanxin 列表是根据 `hide` 来控制显示的，需要在加一层判断，例如：

```html
            <ng-container *ngFor="let data of t.data">
              <tr *ngIf="!data.hide" (click)="onItemSelect(data)">
                <td [nzChecked]="data.checked" [nzDisabled]="disabled || data.disabled" (nzCheckedChange)="onItemSelect(data)"></td>
                <td>{{ data.title }}</td>
                <td *ngIf="direction === 'left'">
                  <nz-tag>{{ data.tag }}</nz-tag>
                </td>
                <td>{{ data.description }}</td>
              </tr>
            </ng-container>
```

**Comment by carolinetanxin** [comment]
> @carolinetanxin 列表是根据 `hide` 来控制显示的，需要在加一层判断，例如：
> 
> ```
>             <ng-container *ngFor="let data of t.data">
>               <tr *ngIf="!data.hide" (click)="onItemSelect(data)">
>                 <td [nzChecked]="data.checked" [nzDisabled]="disabled || data.disabled" (nzCheckedChange)="onItemSelect(data)"></td>
>                 <td>{{ data.title }}</td>
>                 <td *ngIf="direction === 'left'">
>                   <nz-tag>{{ data.tag }}</nz-tag>
>                 </td>
>                 <td>{{ data.description }}</td>
>               </tr>
>             </ng-container>
> ```

@cipchk 感谢，但是另外一个问题是，table里关于搜索结果的显示，不在当前页的数据显示不出来。尝试使用table的虚拟滚动，并没有办法解决该问题。

**Comment by cipchk** [comment]
这个问题是传递过来的数据包含着所有数据不管是不是已经符合检索前后，应该是只返回检索过的数据。

**Comment by carolinetanxin** [comment]
> 这个问题是传递过来的数据包含着所有数据不管是不是已经符合检索前后，应该是只返回检索过的数据。

@cipchk 是的，没有只返回检索过的数据。谢谢你的解答，期待修复❤️。我也考虑下有没有什么别的设计方案先避开使用该组件。

**Comment by cipchk** [comment]
临时解决方案，就是做一个 Pipe 然后过滤掉这部分数据。
