### ISSUE TITLE
nz-select component input search is not working under ie 11

### ISSUE THREAD

**Issue by Alea81** [NG-ZORRO/ng-zorro-antd#5645]
### Reproduction link
[https://ng-zorro-antd-ivy-rzy4ku.stackblitz.io/](https://ng-zorro-antd-ivy-rzy4ku.stackblitz.io/)

### Steps to reproduce
Simply type something into the control, the search is not working under internet explorer 11.
Is also reproducible here: https://ng.ant.design/components/select/en

### What is expected?
The search is working

### What is actually happening?
Nothing is happening under ie 11.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | ie 11 |

**Comment by h4rm** [comment]
I can confirm that this issue exists, e.g., with the search box on https://ng.ant.design/components/select/en under IE11

**Comment by adiherzog** [comment]
This is a big issue for us as we need to support IE 11

**Comment by h4rm** [comment]
I could narrow it down to a problem with this template:

```HTML
        <nz-select-search
          [disabled]="disabled"
          [value]="inputValue!"
          [showInput]="open && showSearch"
          [mirrorSync]="false"
          [autofocus]="autofocus"
          [focusTrigger]="open"
          (isComposingChange)="isComposingChange($event)"
          (valueChange)="onInputValueChange($event)"
        ></nz-select-search>
```

When I change `[showInput]="open && showSearch"` to `[showInput]="showSearch"` it seems to work. Maybe the

```js
  host: {
	'(click)': 'onHostClick()',
  }
```

that controls the open state:

```js
  onHostClick(): void {
	if (!this.disabled) {
		this.openChange.next(!this.open);
	}
  }
```

is not working as intended.

**Comment by wenqi73** [comment]
I found the input cannot work if focused before removing "readonly", and I change the calling sort, but it seems not work 😕.

**Comment by Alea81** [comment]
@wenqi73 The problem has something to do with the opening/focusing sequence though. The input gets the focus, but this `cdk-overlay-backdrop` does not get removed. I also don't know what is addding this and what for. If I remove it manually, the control is working fine.
![image](https://user-images.githubusercontent.com/44226291/89555211-0a2cb580-d810-11ea-9927-ffd15197a935.png)
Would love to open a PR, but it would cost way more time to set up an env, and understand the logic behind this.
I can test and help, if you want.
Could this somehow narrow down the problem?

**Comment by wenqi73** [comment]
It's nothing to do with cdk, the `tag` mode select works fine.

**Comment by Alea81** [comment]
Yes, thanks, were also testing further. Something is broken with the focusing there. (We found another bug with the placeholder component too under IE11, might be related.)
