### ISSUE TITLE
Option to make the modal stay opened if the promise from `nzOnOk` fails

### ISSUE THREAD

**Issue by IonelLupu** [NG-ZORRO/ng-zorro-antd#5646]
## What problem does this feature solve?
Let's say I have a form inside the modal:

```ts
        this.modalService.confirm({
            nzTitle: 'Save user',
            nzContent: MyModalComponent,  // the form is inside this component
            nzOnOk: async (form) => {
                this.myService.saveUser(modal.form);
                console.log('User saved');
            }
        });
```

Upon clicking save, the server might reject the promise and the modal closes. In this case the user lost all the form information it had written and it has to reopen the modal and fill in the form again.

To fix this in the current version of ng-zorro, I have to use a try-catch block to catch the error and return false from it so the modal doesn't close(which is a bit ugly):

```ts
        this.modalService.confirm({
            nzTitle: 'Save user',
            nzContent: MyModalComponent,  // the form is inside this component
            nzOnOk: async (form) => {
                try{
                     this.myService.saveUser(modal.form);
                     console.log('User saved');
                }carch(e) {
                     // I am not handling the error here since it is handled by a HTTP interceptor
                     return false;
                }
            }
        });
```
I think the modal service, by default, should not close the modal if the promise returns a rejection. But if this cannot be done, I am thinking we can add a new option when creating a modal.

## What does the proposed API look like?
We can call the option: `nzCloseOnRejection`.

```ts
        this.modalService.confirm({
            nzTitle: 'Save user',
            nzContent: MyModalComponent,
           nzCloseOnRejection: true,
            nzOnOk: async (form) => {
                this.myService.saveUser(modal.form);
                console.log('User saved');
            }
        });
```
This will allow to remove a ton of try catches from the nzOnOk methods.

**Comment by IonelLupu** [comment]
What do you think about this feature, @hsuanxyz ?

**Comment by hsuanxyz** [comment]
For now, this is default behavior.

https://stackblitz.com/edit/angular-sjmdrt?file=src/app/app.component.ts

**Comment by zackshine** [comment]
> For now, this is default behavior.
> 
> https://stackblitz.com/edit/angular-sjmdrt?file=src/app/app.component.ts

It seems not work for modal created by `this.modalService.create()`, how to set delay time for this kind of modal?
