### ISSUE TITLE
input 输入框事件冒泡，使其他第三方库的 input focur 事件不能获取焦点，怎么阻止input事件冒泡。8版本没有这个问题。

### ISSUE THREAD

**Issue by qyjs** [NG-ZORRO/ng-zorro-antd#5649]
## What problem does this feature solve?
取消 input 输入框的事件冒泡

## What does the proposed API look like?
阻止input 事件冒泡

**Comment by qyjs** [comment]
![image](https://user-images.githubusercontent.com/22796811/89368950-580dc480-d70f-11ea-80be-e176d20f53ec.png)

请看截图，这是9版本出现的问题

**Comment by qyjs** [comment]
![image](https://user-images.githubusercontent.com/22796811/89369048-9d31f680-d70f-11ea-953f-5ff786b800fb.png)

在8的版本，focus 没有出现document，一切正常，使用9的时候focus 出现document，导致使用其他库input 无法focur

**Comment by qyjs** [comment]
@vthinkxie

**Comment by vthinkxie** [comment]
截图的部分指向都是polyfill部分，与ng-zorro-antd代码无关

**Comment by qyjs** [comment]
@vthinkxie ng-zorro-antd 8 的版本没这个问题啊，升级到ng-zorro-antd 9 就出现这个问题了。

**Comment by vthinkxie** [comment]
一同升级的肯定还有angular 版本，zone.js 版本，各种polyfill的版本，rxjs的版本，等等各种三方包
而不是只有ng-zorro-antd

**Comment by hsuanxyz** [comment]
This issue has been closed due to inactivity.
Please file a new issue or [discussion](https://github.com/NG-ZORRO/ng-zorro-antd/discussions/category_choices) if you are encountering a similar or related problem.
