### ISSUE TITLE
Datepickers disable entire months/years when disabling weekends

### ISSUE THREAD

**Issue by valerio-lucantonio** [NG-ZORRO/ng-zorro-antd#5655]
### Reproduction link
[https://stackblitz.com/edit/angular-85ayk8](https://stackblitz.com/edit/angular-85ayk8)

### Steps to reproduce
1) create a function to disable weekends
2) pass it to the nzDisableDate
3) open the datepicker
4) click on the year/month list on top of the calendar
5) some years/months are disabled and they should not

### What is expected?
the months/years to be enabled

### What is actually happening?
the months/years to be disabled

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

---
I noticed in console that not all the dates of a month/year are passed to the functions

**Comment by wenqi73** [comment]
Related to #5633.

**Comment by valerio-lucantonio** [comment]
Hello, with which version will be this bug delivered?

**Comment by wenqi73** [comment]
@valerio-lucantonio Next version, it will be released a few hours later.
