### ISSUE TITLE
运行 cnpm start 报错

### ISSUE THREAD

**Issue by chenling1983** [NG-ZORRO/ng-zorro-antd#566]
ERROR in /app/open-src/ui/ng-zorro-antd/src/components/dropdown/nz-dropdown.component.ts (196,26): Argument of type 'Observable<boolean | {}>' is not assignable to parameter of type 'Observable<boolean>'.
  Type 'boolean | {}' is not assignable to type 'boolean'.
    Type '{}' is not assignable to type 'boolean'.
ERROR in /app/open-src/ui/ng-zorro-antd/src/components/dropdown/nz-dropdown-button.component.ts (95,26): Argument of type 'Subject<{}>' is not assignable to parameter of type 'Observable<boolean>'.
  Types of property 'subscribe' are incompatible.
    Type '{ (): Subscription; (observer: PartialObserver<{}>): Subscription; (next?: (value: {}) => void, e...' is not assignable to type '{ (): Subscription; (observer: PartialObserver<boolean>): Subscription; (next?: (value: boolean) ...'.
      Types of parameters 'next' and 'next' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type '{}' is not assignable to type 'boolean'.

webpack: Failed to compile.

**Comment by vthinkxie** [comment]
it is not recommend to start source code by your self, you can use compiled file through https://www.npmjs.com/package/ng-zorro-antd
