### ISSUE TITLE
Close Tabs with TabsRouter

### ISSUE THREAD

**Issue by juniorpaiva95** [NG-ZORRO/ng-zorro-antd#5666]
### Reproduction link
[https://stackblitz.com/edit/angular-ilfpjx?file=src%2Fapp%2Fapp.html](https://stackblitz.com/edit/angular-ilfpjx?file=src%2Fapp%2Fapp.html)

### Steps to reproduce
first: Click on the "x" icon to try to remove a tab.

### What is expected?
Run the icon's click event and remove the tab.

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome |

---

Another question of mine is how to set the default for a tab router. I tried to redirect to a route and hoped that the tab containing the same link would be active.

**Comment by guobin211** [comment]
1. don't  use `nz-tab-link`, it's `DIRECTIVE`.

```
 <div>
     <a [routerLink]="[tab.url]">{{ tab.name }}</a>
     <i nz-icon nzType="close" (click)="closeTab(tab)" class="ant-tabs-close-x"></i>
 </div>
```

**Comment by hsuanxyz** [comment]
use `<nz-tabset nzLinkRouter>`, and manually handle the fallback behavior on closing(like routing to the closest tab's routerUrl)
