### ISSUE TITLE
Tree select: Ability to disable parent node selection, and just open it's child nodes on selection like the expand arrow next to it

### ISSUE THREAD

**Issue by Yorer** [NG-ZORRO/ng-zorro-antd#5674]
## What problem does this feature solve?
I think if you can add a flag like [nzDenyParentSelection] (boolean) will resolve this request.Basically currently parent node also selectable. Always. What I would like to be resolved if I have a list, and one node contains a sublist, then when I click it's parent node, do not select, just open it's sub node like the arrow next to parent node it it has subnodes.

## What does the proposed API look like?
API doesn't need here it's a simple task.

**Comment by whittssg** [comment]
Has anyone got a temp workaround for this? My users are all going to be clicking the parent thinking it will expand the children but it just selects it and the parent doesnt refer to anything. Thanks

**Comment by whittssg** [comment]
This seems to work for me:

```
  <nz-tree-select [nzDropdownMatchSelectWidth]="'false'" [nzVirtualHeight]="'50vh'" style="margin-right:2px;margin-left:2px" 
                    [nzNodes]="nzOptions"
                    nzShowSearch
                    nzPlaceHolder="Please select"
                    [(ngModel)]="rule.field"
                    (ngModelChange)="onChange($event, rule)">
      <ng-template #nzTreeTemplate let-node>
        <span class="ant-tree-node-content-wrapper" (click)="nodeClicked(node)" [class.ant-tree-node-selected]="node.isSelected">
          <span fxFlex>  {{ node.title }} </span>
        </span>
      </ng-template>
    </nz-tree-select>
```

```
  nodeClicked(node: any) {
    if (!node.isLeaf) {
      node.isSelectable = false;
      node.isExpanded = !node.isExpanded;
    }
  }
```

**Comment by Yorer** [comment]
Whittssg, you are amazing! This works for me as well, thanks! I close this request.
