### ISSUE TITLE
自动生成面包屑，用nzRouteLabelFn 进行中译文翻译，没有生效

### ISSUE THREAD

**Issue by Varsha-xiu** [NG-ZORRO/ng-zorro-antd#5675]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/5cdb3226cc0976dde1343326df1a760b2f93d9d4/components/breadcrumb/doc/index.zh-CN.md](https://github.com/NG-ZORRO/ng-zorro-antd/blob/5cdb3226cc0976dde1343326df1a760b2f93d9d4/components/breadcrumb/doc/index.zh-CN.md)

### Steps to reproduce
直接添加这个属性，会报错

### What is expected?
可以进行中译文翻译，这个nzRouteLabelFn 生效

### What is actually happening?
nzRouteLabelFn 没有生效，还是nzRouteLabel的内容

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

---
重现链接是一个假的， 你可以自己试试，刚刚私信了cipchk@qq.com，他说要提一个 issues

**Comment by YuchenWell** [comment]
你好，这个feature是在v9.3.0之后添加的，还没有被发布到npm呢~
![image](https://user-images.githubusercontent.com/25000956/90475202-9bc5ec80-e159-11ea-9499-630ec34d1a61.png)

**Comment by Varsha-xiu** [comment]
那大概什么时候可以使用呢

**Comment by wendellhu95** [comment]
@Varsha-xiu Ref #5471.

**Comment by wendellhu95** [comment]
I am closing this issue 'cause the requested feature is going to be shipped in v10.

**Comment by hoangns832** [comment]
[wzhudev](https://github.com/wzhudev) I'm still find this error on version 16.2.0
