### ISSUE TITLE
nz-time-picker，手动输入，没动变化

### ISSUE THREAD

**Issue by fupobaobaowoya** [NG-ZORRO/ng-zorro-antd#5678]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/time-picker/doc/index.zh-CN.md](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/time-picker/doc/index.zh-CN.md)

### Steps to reproduce
nz-time-picker，只能选择，手动输入没变化

### What is expected?
手动输入能改变 或者干脆禁止手动输入

### What is actually happening?
手动输入没变化

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | 谷歌 |

**Comment by fupobaobaowoya** [comment]
而且 手动输入错误格式也不能效验

**Comment by Wsp0000** [comment]
same issue,
and I found workaround like @wenqi73  did before they update ng-zorro-antd version

in component template
```html
    <nz-time-picker 
      #timePicker
      ...
    >
```

in component ts
```ts
  @ViewChild('timePicker') timePicker: NzTimePickerComponent;

  ngAfterViewInit(): void {
    this.timePicker.inputRef.nativeElement.setAttribute('readonly', 'true');
  }
```

Link to minimal reproduction:
https://stackblitz.com/edit/angular-ng-zorro-antd-9-3-timepicker-readonly?file=src/app/app.component.ts
