### ISSUE TITLE
nz-button memory leak

### ISSUE THREAD

**Issue by scorzy** [NG-ZORRO/ng-zorro-antd#5685]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-facszb](https://stackblitz.com/edit/ng-zorro-antd-ivy-facszb)

### Steps to reproduce
Press "toggle 1" multiple times. Collect garbage and take an Heap snapshot, NzButtonComponent instances are not collected.

Refresh the page.

Press "toggle 2" multiple times. Collect garbage and take an Heap snapshot, NzButtonComponent instances are collected.

### What is expected?
NzButtonComponent instance should be collected despite their contents.

### What is actually happening?
When you use nz-button containing plain text, NzButtonComponent instances are not collected by gc, causing memory leaks. 
Components containing "leaky buttons" are not collected too.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chromium |

**Comment by vthinkxie** [comment]
Hi @scorzy 
thanks for reporting this
I have tested the case and found the memory leaks only happened when disabled ivy, you can enable ivy to fix this bug(caused by angular view engine)
