### ISSUE TITLE
How to customize the Ant Design theme with CSS?

### ISSUE THREAD

**Issue by taksumaki** [NG-ZORRO/ng-zorro-antd#5686]
I don't see a guide on how to customize colors like, primary, secondary, etc. without the need to use Less. If you could guide me please would be very helpful.

**Comment by vthinkxie** [comment]
there is no method to customize the colors without using less in the current version, but you still can css to overwrite any style if you want.

**Comment by lperezp1** [comment]
And when is it at runtime? In the footer of NgZorro there is a ColorPicker that does it? Is there any documentation?
