### ISSUE TITLE
Prefix and suffix not working with NzInputNumber component

### ISSUE THREAD

**Issue by konossow** [NG-ZORRO/ng-zorro-antd#5690]
### Reproduction link
[https://stackblitz.com/edit/angular-cjhjvd?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-cjhjvd?file=src/app/app.component.ts)

### Steps to reproduce
1. Run example
2. See look of components

### What is expected?
Prefix and suffix should be inside input.
Suffix should be aligned to right side.

### What is actually happening?
Prefix and suffix is not inside input.
Suffix is put after input.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome |

**Comment by HyperLife1119** [comment]
v19 redesigned input-number, close this.
