### ISSUE TITLE
nz-slider nzDots/nzStep Function failure

### ISSUE THREAD

**Issue by ccScavengers** [NG-ZORRO/ng-zorro-antd#5699]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-mcwbqg?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-mcwbqg?file=src/app/app.component.ts)

### Steps to reproduce
The first is the example of setting step and the other is setting nzdots. Drag to find that the node cannot be selected

### What is expected?
[nzStep]="null"/[nzDots]="true" can work  ,In the examples,I can choose nodes.

### What is actually happening?
Both nzstep and nzdots do not work, and the component uses the default parameter of 1

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.2.2 |
| Browser | chorme |

**Comment by wendellhu95** [comment]
The Slider component doesn't support decimals currently. I will fix this.
