### ISSUE TITLE
路由联运的Tabs，点击菜单时，相同路由的tab经常不会显示为选中状态。

### ISSUE THREAD

**Issue by ghoolooloo** [NG-ZORRO/ng-zorro-antd#5702]
### Reproduction link
[https://stackblitz.com/edit/angular-ilfpjx-o22kzr?file=src%2Fapp%2Fapp.html](https://stackblitz.com/edit/angular-ilfpjx-o22kzr?file=src%2Fapp%2Fapp.html)

### Steps to reproduce
1、点击“页1”链接；
2、点击“页2”链接。

### What is expected?
1、出现“Page1” tab，并且“Page1” tab呈选中状态；
2、出现“Page2" tab，并且“Page2” tab呈选中状态。

### What is actually happening?
1、出现“Page1” tab，但是“Page1” tab没有呈选中状态；
2、出现“Page2" tab，但是“Page2” tab没有呈选中状态。

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chromium 84.0.4147.125 |

---
要第二次再点击“页1”或“页2”时才会呈现选中状态。

**Comment by hsuanxyz** [comment]
close via #5590

![屏幕录制2020-09-14 下午6 20 09 mov](https://user-images.githubusercontent.com/22736418/93074672-48db4880-f6b7-11ea-94ea-a7fc0990db0f.gif)
