### ISSUE TITLE
Cursor not showing in nz-select when nzMode is "multiple" or "tags"

### ISSUE THREAD

**Issue by IonelLupu** [NG-ZORRO/ng-zorro-antd#5704]
### Reproduction link
[https://stackblitz.com/edit/angular-urq8bv?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-urq8bv?file=src/app/app.component.ts)

### Steps to reproduce
Create a nz-select and set nzMode to "multiple"

```html
    <nz-select nzShowSearch nzAllowClear nzPlaceHolder="nzMode: multiple" nzMode="default" nzMode="multiple">
      <nz-option nzLabel="Jack" nzValue="jack"></nz-option>
      <nz-option nzLabel="Lucy" nzValue="lucy"></nz-option>
      <nz-option nzLabel="Tom" nzValue="tom"></nz-option>
    </nz-select>
```

### What is expected?
When focusing on the select box, it is expected to see a blinking cursor showing that you can type to search something

### What is actually happening?
No cursor is showing at all in Chrome

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome 84.0.4147.125, Opera 70.0.3728.119 |

---
It works on Firefox and Edge

**Comment by canmustu** [comment]
Same here. Following...

**Comment by wenqi73** [comment]
https://github.com/ant-design/ant-design/issues/24505. Styles have been synced, this will be fixed in the next version.

**Comment by Super-Mumoo** [comment]
> 10.0.0 已发布。只需要`padding: 0`样式：
> 
> ![图片](https://user-images.githubusercontent.com/23337087/94447628-8aeaab00-01dc-11eb-9bd2-ceb8c8043b4c.png)

为把padding设置成0就解决了
