### ISSUE TITLE
nz-input-group with textarea contain nzPrefix in version 9 the style is changed compared with version 8

### ISSUE THREAD

**Issue by tmirun** [NG-ZORRO/ng-zorro-antd#5705]
### Reproduction link
[https://stackblitz.com/edit/angular-hnhafj?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-hnhafj?file=src/app/app.component.ts)

![image](https://user-images.githubusercontent.com/8052536/90966696-b8558200-e4d5-11ea-9e5b-cfbe9cfc6a37.png)

### Steps to reproduce
implement nz-input-group with textarea and nzPrefix

### What is expected?
i don't know if this change of style in version 9 of ng-zorro is decision of antdesign team
but the style of version 8 of ng-zorro looks good, example: 
![image](https://user-images.githubusercontent.com/8052536/90966679-8b08d400-e4d5-11ea-9668-de621c538c33.png)

### What is actually happening?
style is changed

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

**Comment by wenqi73** [comment]
@tmirun Styles of v9 has been changed, you need to set `textarea` style manually. https://github.com/ant-design/ant-design/issues/10249#issuecomment-385434437
