### ISSUE TITLE
在tabs组件内嵌套g2图表会报错

### ISSUE THREAD

**Issue by 18469645** [NG-ZORRO/ng-zorro-antd#571]
在tabs组件内嵌套g2图表，第一次进入页面时正常，退出后，再去进入含有g2图表的页面就会报错

**Comment by cipchk** [comment]
这个问题我也发现了，原因是 g2 本身是依赖于 dom 容器，因此在编码时要很清除 angular 组件渲染生命周期。我建议你尽可能在 `ngAfterViewInit` 时初始化 g2，可以参考：ng-alain 的 [bar.component.ts](https://github.com/cipchk/ng-alain/blob/master/src/app/shared/components/charts/bar/bar.component.ts) 编码风格。
