### ISSUE TITLE
Table pagination is not compatible with template mode

### ISSUE THREAD

**Issue by sasensi** [NG-ZORRO/ng-zorro-antd#5721]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-aqcgyc?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-aqcgyc?file=src/app/app.component.ts)

### Steps to reproduce
- create a table using template mode
- enable pagination
- see that pagination is not displayed

### What is expected?
Pagination should be displayed

### What is actually happening?
Pagination is not displayed

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Google Chrome |

**Comment by Mr-Eve** [comment]
<nz-pagination
        *ngIf="nzShowPagination && data.length"
源码里是有对`nzData`的长度做判断的, 没有传递的话是不会出现分页器的, 不知道这是不是在官方的考虑范围内

**Comment by sasensi** [comment]
Thanks for the precision, I guess that if it is done on purpose, then the documentation of the template mode should mention its limitations.

**Comment by vthinkxie** [comment]
template mode can not work with pagination, it only adds the styles of ant design to the table.
