### ISSUE TITLE
Mention提及中nzSuggestions无法做到动态更新

### ISSUE THREAD

**Issue by changshuxiaohuge** [NG-ZORRO/ng-zorro-antd#5722]
## What problem does this feature solve?
在使用Mention组件时，一开始没有对nzSuggestions进行赋值，因为需要在用户选择某一个字段后才能根据这个字段获取nzSuggestions对应的值，现在选择字段之后nzSuggestions还是一个空的数组，只有在输入框内输入@并在@后再输入一些值，才能将nzSuggestions的值更新

## What does the proposed API look like?
nzSuggestions双向数据绑定，动态刷新nzSuggestions的值

**Comment by hsuanxyz** [comment]
@changshuxiaohuge 为什么不用 `(nzOnSearchChange)` ?

**Comment by changshuxiaohuge** [comment]
(nzOnSearchChange)在第一次输入@时会触发，但是第二次继续输入@时就不会再触发了

**Comment by hsuanxyz** [comment]
@changshuxiaohuge 麻烦写个你的复现，这里是可以触发的 https://codesandbox.io/s/unruffled-jones-hyzt5?file=/src/app/app.component.ts

**Comment by changshuxiaohuge** [comment]
@hsuanxyz https://codesandbox.io/s/zen-glitter-lhb7m?file=/src/app/app.component.ts ，同时用到@和#时，如果我输入@，第一次是会触发(nzOnSearchChange)，但是第二次输入@并且后面不继续输入任何值的时候，(nzOnSearchChange)就不会被触发了

**Comment by hsuanxyz** [comment]
@changshuxiaohuge got，这是一个 BUG

**Comment by changshuxiaohuge** [comment]
@hsuanxyz 这个问题是否会兼容ng-zorro7.5版本
