### ISSUE TITLE
select选择器

### ISSUE THREAD

**Issue by zjy18393346393** [NG-ZORRO/ng-zorro-antd#5723]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/issues/5360](https://github.com/NG-ZORRO/ng-zorro-antd/issues/5360)

### Steps to reproduce
选项中的某个值清空后，页面上还在显示.

### What is expected?
清空选项值后，页面对应的不应该显示该值

### What is actually happening?
还有值显示。
![image](https://user-images.githubusercontent.com/44798329/91394315-20f18580-e86d-11ea-82ba-e0bead420e30.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | 谷歌 |

---
也不是啥大问题，但是不方便。请尽快解决

**Comment by Mr-Eve** [comment]
可以做个gif吗, 没懂啥意思

**Comment by ousc** [comment]
我觉得是这个意思
![0z9a8-178s5](https://user-images.githubusercontent.com/31619017/91675614-901df100-eb6f-11ea-8625-746f151ab397.gif)
clear清空之后，去掉展开后选项的选中效果

**Comment by Mr-Eve** [comment]
react社区也是这样的.  https://ant.design/components/select-cn/#header

我猜测这个是最初没有考虑到的情况.

**Comment by vthinkxie** [comment]
在 https://github.com/NG-ZORRO/ng-zorro-antd/issues/5360 已经有完整回复，目前设计规范如此
