### ISSUE TITLE
popover's placement need a priority 

### ISSUE THREAD

**Issue by sonlichao** [NG-ZORRO/ng-zorro-antd#5733]
## What problem does this feature solve?
The popover automatically change the placement when not enough space for showing default placement. We need a priority order to do it.

## What does the proposed API look like?
[nzPopoverPlacement]="['top', 'topRight']"

**Comment by wendellhu95** [comment]
AFAIK this is already supported. Could you provide a reproduction link that shows the undesired behavior?

**Comment by linwrui** [comment]
> AFAIK this is already supported. Could you provide a reproduction link that shows the undesired behavior?

![image](https://user-images.githubusercontent.com/22316156/94225285-20f5ab80-ff27-11ea-9af9-7a8693eb3420.png)
How can i set placement with priority?

**Comment by wendellhu95** [comment]
We will support assigning an array of placements in the next minor version ;)
