### ISSUE TITLE
在nz-table没有数据时添加一个新的数据还是会显示“no data”

### ISSUE THREAD

**Issue by liyunfei0302** [NG-ZORRO/ng-zorro-antd#5735]
### Reproduction link
[https://stackblitz.com/edit/angular-y3fp41-zuvsp1?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-y3fp41-zuvsp1?file=src/app/app.component.ts)

### Steps to reproduce
1.创建一个nz-table，添加属性：[nzFrontPagination]="false"、[nzShowPagination]="false"
```html
<nz-table #myTable [nzData]="data" 
            [nzFrontPagination]="false"
            [nzShowPagination]="false">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let item of myTable.data">
      <td>{{item.name}}</td>
      <td>{{item.age}}</td>
      <td>
        <a>Delete</a>
      </td>
    </tr>
  </tbody>
</nz-table>
<button nz-button nzType="primary" (click)="add()">添加</button>
```
```typescript
data = [];
add() {
  this.data.push({
    name: 'name',
    age: 22,
  });
 }
```
2.使data的初始值为“[]”
3.data中添加一个对象

### What is expected?
当添加一个新的对象后，“no data”消失

### What is actually happening?
“no data”没有消失

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | all |

**Comment by Feng-JY** [comment]
需要改变data的引用，试下
`this.data = [...this.data,{
      name: 'name',
      age: 22,
    }]`

**Comment by liyunfei0302** [comment]
ok,多谢
