### ISSUE TITLE
关于NzCellEllipsisDirective中省略td文本的问题

### ISSUE THREAD

**Issue by yuxl01** [NG-ZORRO/ng-zorro-antd#5738]
## What problem does this feature solve?
解决表格数据太多可以自动折叠

## What does the proposed API look like?
我想请教一个代码上的问题，我在阅读NzCellEllipsisDirective源码时，发现Directive装饰器里面使用到host属性，里面的代码是：'[class.ant-table-cell-ellipsis]': 'nzEllipsis'，我去看了angular api指令文档解释“当 key 是宿主元素的 Property 时，这个 Property 值就会传播到指定的 DOM 属性”，在这里这段代码的意思是代表如果宿主上属性class等于ant-table-cell-ellipsis 时将 nzEllipsis传播到这个宿主的dom对象上作为属性吗

**Comment by vthinkxie** [comment]
具体的使用方式见 angular 文档，本项目不提供 angular 使用方式的答疑，感谢理解

**Comment by yuxl01** [comment]
那大佬能解释下这个代码这样写的思想吗？

**Comment by yuxl01** [comment]
> 那大佬能解释下这个代码这样写的思想吗？



> 具体的使用方式见 angular 文档，本项目不提供 angular 使用方式的答疑，感谢理解

那大佬能解释下这个代码这样写的思想吗？实在找不到资料
