### ISSUE TITLE
table能否支持横向滚动条呢，就像ant design一样

### ISSUE THREAD

**Issue by jerrypotti** [NG-ZORRO/ng-zorro-antd#574]
table能否支持横向滚动条呢，就像ant design一样，就是固定列，其他列表横向固定，这个功能特性很重要，很多地方要用的，谢谢！

**Comment by HsuanXyz** [comment]
duplicated #463

**Comment by jerrypotti** [comment]
那未来什么时候可以提供支持呢？
这个功能特性对我们系统来说很重要
