### ISSUE TITLE
Switching the theme dynamically .

### ISSUE THREAD

**Issue by Ananta580** [NG-ZORRO/ng-zorro-antd#5744]
### Steps to reproduce
In the documentation , for switching theme dynamically , there is a function for switching the theme , but i am confused where this function is to be called in order to make it work.
I would request for a clear documentation .

### What is expected?
changeTheme(theme: 'default' | 'dark'): void {
  if (theme === 'dark') {
    const style = document.createElement('link');
    style.type = 'text/css';
    style.rel = 'stylesheet';
    style.id = 'dark-theme';
    style.href = 'assets/themes/style.dark.css';
  } else {
    const dom = document.getElementById('dark-theme');
    if (dom) {
      dom.remove();
    }
  }
}

### What is actually happening?
I am not able to switching theme in dynamically.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | all browsers |

**Comment by hsuanxyz** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/pull/5715

```ts
changeTheme(theme: 'default' | 'dark'): void {
  if (theme === 'dark') {
    const style = document.createElement('link');
    style.type = 'text/css';
    style.rel = 'stylesheet';
    style.id = 'dark-theme';
    style.href = 'assets/themes/style.dark.css';
    document.body.appendChild(style);
  } else {
    const dom = document.getElementById('dark-theme');
    if (dom) {
      dom.remove();
    }
  }
}
```

**Comment by hsuanxyz** [comment]
Thanks for your feedback, if have any questions, welcome to open a new issue.
