### ISSUE TITLE
ivy

### ISSUE THREAD

**Issue by CreasyWorld** [NG-ZORRO/ng-zorro-antd#5754]
This likely means that the library (ng-zorro-antd) which declares NzInputModule has not been processed correctly by ngcc, or i
s not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking
with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by wendellhu95** [comment]
Could you provide a valid reproduction?

**Comment by asincole** [comment]
For anyone that has this issue, I have had it too and I see that restarting angular server resolves it.
```
ng serve 
```

**Comment by lperezp** [comment]
> Para cualquiera que tenga este problema, yo también lo he tenido y veo que reiniciar el servidor angular lo resuelve.
> 
> ```
> ng serve 
> ```

Also works for version 11.0.0
