### ISSUE TITLE
Weird nz-select search behaviour as a prefix of nz-input-group

### ISSUE THREAD

**Issue by ifree92** [NG-ZORRO/ng-zorro-antd#5757]
### Reproduction link
[https://stackblitz.com/edit/angular-witztb?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-witztb?file=src/app/app.component.ts)

### Steps to reproduce
Just open the select drop down menu and try to "search" for something

### What is expected?
I'm expecting to see the search icon on right place and have at least some min-width of the select container

### What is actually happening?
The width of nz-select container is collapsing so I cannot see the search input and the search icon has bad position

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | All |

**Comment by wenqi73** [comment]
select's width is not limited, you should manually set `width` style.

**Comment by vthinkxie** [comment]
plz follow @wenqi73 's advice
