### ISSUE TITLE
Modal对话框里的内容为空数据的虚拟滚动列表时，空状态的图标不能居中对齐

### ISSUE THREAD

**Issue by 007GitHu** [NG-ZORRO/ng-zorro-antd#5762]
### Reproduction link
[https://angular-vrcmyu.stackblitz.io](https://angular-vrcmyu.stackblitz.io)

### Steps to reproduce
1、modle对话框用模板方式弹出内容时，内容为空数据的虚拟滚动列表，指定[nzScroll]的x轴和y轴即可重现
点击重现链接中的弹框按钮，即可看到效果

### What is expected?
空状态的图标能居中对齐

### What is actually happening?
空状态的图标是左对齐的

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | 谷歌80 |

**Comment by wenqi73** [comment]
Duplicate of #5526
