### ISSUE TITLE
nz-form-label中文字过长会被遮挡且没有省略号

### ISSUE THREAD

**Issue by manman0310** [NG-ZORRO/ng-zorro-antd#5767]
## What problem does this feature solve?
当nz-form-label文字为动态内容时不确定内部文字会多长，看到nz-form-label使用nz-col的属性是生效的，nz-form-label宽度是正常的宽度，但是nz-form-label内部的label标签宽度没有继承，超出的宽度部分未处理。  
我也试过使用typography中的nzEllipsis但是好像不可以使用在nz-form-label这种非原生标签上？

最后使用强行写样式覆盖解决，请问是我使用不当还是ant没有处理？

## What does the proposed API look like?
希望可以处理labal继承nz-form-label的宽度属性，以及提供label处理方式的api，比如换行或者省略号等。谢谢

**Comment by danranVm** [comment]
麻烦写一个复现链接？在链接：https://stackblitz.com/edit/ng-zorro-antd-ivy 中重现出想要问的问题后点  fork

**Comment by hsuanxyz** [comment]
@manman0310 Ant Design 还没有定义这种行为，你可通过 css 实现，或者向 [ant-design/ant-design](https://github.com/ant-design/ant-design/issues) 提交一个功能请求，感谢你的贡献。
