### ISSUE TITLE
DatePicker组件的nzOpen属性有问题

### ISSUE THREAD

**Issue by lcq9732** [NG-ZORRO/ng-zorro-antd#5771]
### Reproduction link
[https://codesandbox.io/s/amazing-bush-dtijh?file=/src/app/app.component.ts](https://codesandbox.io/s/amazing-bush-dtijh?file=/src/app/app.component.ts)

### Steps to reproduce
1。打开后就可以看到第一个日期选择，不能打开选择器
2。第二个日期选择，日期选择器一直开着，关闭不了，且没有Mask层

### What is expected?
设置nzOpen=true后打开选择器,用户选择后要后可以关闭，在打开选择器时，要有Mask
即与select组件中的nzOpen属性行为一致

### What is actually happening?
DatePicker中的nzOpen与Select中的nzOpen行为不一致。且不能正常工作

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome Lastest |

---
select组件中有一个属性nzOpen，通过这个属性可以控制下拉框的显示与隐藏，但在DatePicker组件中也nzOpen属性，却是用来控制日期选择一直显示或不可显示；是否可以提供一个与select类似的功能来代码打开或关闭日期选择框？

**Comment by wenqi73** [comment]
`nzOpen` 保留，但文档不再提及。推荐使用 `open()` `close()`。
