### ISSUE TITLE
nz-popover如何给TemplateRef传值

### ISSUE THREAD

**Issue by Yaroglek** [NG-ZORRO/ng-zorro-antd#5773]
## What problem does this feature solve?
如果可以传值，我就可以在template处用let-data接到值，例如我需要做一个点击小图放大查看的功能。

## What does the proposed API look like?
新增一个nz属性，类似于[ngTemplateOutletContext]，可以传值给template

**Comment by wendellhu95** [comment]
template 可以访问业务组件的数据，请描述一下你想要实现的模板语法，什么场景需要用到 context

**Comment by calibura** [comment]
> ## What problem does this feature solve?
> 如果可以传值，我就可以在template处用let-data接到值，例如我需要做一个点击小图放大查看的功能。
> 
> ## What does the proposed API look like?
> 新增一个nz属性，类似于[ngTemplateOutletContext]，可以传值给template


> template 可以访问业务组件的数据，请描述一下你想要实现的模板语法，什么场景需要用到 context，最好用代码描述一下


 你好，请问如何实现 将 `[ngTemplateOutlet]="item"` 传给 `contentTemplate`，使用场景是期望 popover 可以显示复杂一些的数据
~~~HTML
<button nz-button nz-popover nzType="primary" [nzPopoverContent]="contentTemplate" [ngTemplateOutlet]="item">&nbsp;</button>
...
<ng-template #contentTemplate let-item>
        start: {{ item?.start }}
        <br />
        ...
        <br />
        end: {{ item?.end }}
 </ng-template>
~~~
