### ISSUE TITLE
nz-table 中nzFrontPagination属性为false时，排序功能不生效

### ISSUE THREAD

**Issue by zjxcv7** [NG-ZORRO/ng-zorro-antd#5780]
### Reproduction link
[https://stackblitz.com/edit/angular-z95use](https://stackblitz.com/edit/angular-z95use)

### Steps to reproduce
1.在最小化重现中将nz-table的nzFrontPagination属性设置为false，点击排序功能；
2.在最小化重现中将nz-table的nzFrontPagination属性设置为true，点击排序功能；

### What is expected?
不使用前端分页功能时能正常使用排序功能

### What is actually happening?
不使用前端分页功能时能不能正常使用排序功能

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome 85 |

**Comment by hsuanxyz** [comment]
Duplicate of #5457
