### ISSUE TITLE
use only one component, without the whole core

### ISSUE THREAD

**Issue by GlauberF** [NG-ZORRO/ng-zorro-antd#5783]
I want to use the component https://ng.ant.design/components/popover/en, but I don't need to be importing the whole core and making all the configurations, is there a way to use the component directly?

**Comment by vthinkxie** [comment]
`import { NzPopoverModule } from 'ng-zorro-antd/popover';`

**Comment by renilbabu03** [comment]
@vthinkxie : Will it affect the build size? Will the core be added to the build?

**Comment by Faris-AH** [comment]
Only the modules that you import will be included in the application build. The other modules will not be used in the build or removed by tree shaking.
We have other examples as well https://ng-bootstrap.github.io/#/getting-started#imports

**Comment by matijarmk** [comment]
You can use [nzShowSort] to show or hide sort
