### ISSUE TITLE
Tabs 标签页: Tab 很多时支持触摸板/鼠标滚轮

### ISSUE THREAD

**Issue by Xcorpio** [NG-ZORRO/ng-zorro-antd#579]
特性请求
 
404 啦
 http://ng.ant.design/issue-helper/#/new-issue
<img width="837" alt="2017-11-17 5 34 57" src="https://user-images.githubusercontent.com/4575409/32940760-89a311ee-cbbe-11e7-86f0-bca74b5ab9f9.png">

触摸滑动 方便些。

**Comment by vthinkxie** [comment]
Will not support in the near future, you can reopen it after 0.7.0 released.
