### ISSUE TITLE
[建议] Breadcrumb 最后一项加粗问题

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#58]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## What is the motivation ?

虽说【面包屑】绝大多数运用在导航，但有时需要做一些底部导航时，如果默认最后一项强制加粗会显得非常奇怪。

![tim 20170817122115](https://user-images.githubusercontent.com/2987467/29395861-985d4f8a-8346-11e7-857e-32c2581c060a.png)

**Comment by vthinkxie** [comment]
as design in react antd https://ant.design/components/breadcrumb-cn/
