### ISSUE TITLE
Dropdown 下拉菜单 与 Modal 对话框 层级问题，下拉菜单遮住了弹窗

### ISSUE THREAD

**Issue by kl2426** [NG-ZORRO/ng-zorro-antd#580]
问题：当点击Dropdown菜单项，弹出弹窗时。菜单项会在弹窗的上层（隐藏时的动画0.5秒的样子）。

尝试：
尝试修改 菜单 body下的容器层级（弹窗的为1000，菜单也为1000，修改菜单为999）
此时弹窗可以遮住菜单项。但如果弹窗 窗口中再添加菜单项时就无法显示了（因为菜单容器在弹窗的下层）。

请问：
1、怎么去掉动画效果？点击菜单项直接隐藏。
2、或者其他为法

**Comment by kl2426** [comment]
![tim 20171118085220](https://user-images.githubusercontent.com/12854042/32975008-fc19c676-cc3d-11e7-87a3-5c7590d5a3c5.png)

**Comment by vthinkxie** [comment]
you can add a 500ms delay before open the modal

**Comment by kl2426** [comment]
Thank you. 这样最简单的方法实现了需要的效果。
