### ISSUE TITLE
"nz-select" widget - there is a gap shows up  at the bottom of a dropdown if one tries to decrease the height of  "nz-option-item"

### ISSUE THREAD

**Issue by duxard** [NG-ZORRO/ng-zorro-antd#5802]
hi Team,

we've been been trying to customize the height of items in "nz-select" dropdown menu (we need it to be ~20-22px) but we haven't been able to do it. When we're decreasing the height of "nz-option item" (overriding it to be 22 px instead of the default one 32px):

```
.ant-select-item{
  height: 22px;
}

```

there shows up a gap at the bottom of a dropdown menu. The gap is coming from automatic calculations of height of "cdk-virtual-scroll-viewport"  & "cdk-virtual-scroll-spacer". Both have inline style "height: 96px" (though it should've been recalculated taking into account the new height (22px instead of default 32px) of nz-select items).

Is there a way to customize the height of nz-select dropdown items (so that there wouldn't be any gaps/paddings at the bottom?

p.s. It would be great if i could attach screenshots for better understanding of what I'm talking about, but it looks like there is no such a possibility here...

Thanks,
Aleksamdr

**Comment by vthinkxie** [comment]
nzOptionHeightPx

**Comment by duxard** [comment]
@vthinkxie, 

thank you!
