### ISSUE TITLE
nz-date-picker: calendar doesnt parse the written date if it has a value and the nzFormat is changed

### ISSUE THREAD

**Issue by fbcarpinato** [NG-ZORRO/ng-zorro-antd#5803]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-rmubwc?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-rmubwc?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. Enter a calendar which has a nzFormat like dd/MM/yyyy
2. Select a date with mouse
3. Try to change the date with keyboard

### What is expected?
I expect the date to change and get parsed by the calendar

### What is actually happening?
It is not parsing the date

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome |

**Comment by wenqi73** [comment]
See https://github.com/NG-ZORRO/ng-zorro-antd/issues/5654.

**Comment by fbcarpinato** [comment]
thanks
