### ISSUE TITLE
upload拖拽上传文件夹需要获取完整路径

### ISSUE THREAD

**Issue by Iwzw** [NG-ZORRO/ng-zorro-antd#5808]
## What problem does this feature solve?
upload拖拽上传 支持批量上传文件夹及文件，但是无法获取批量拖拽进去的文件的完整路径，例如：我需要一个组织架构及人员资料，是一个树形结构，选中树形节点拖拽上传整理好的文件夹及文件后生成对应的结构树完整目录，需要把文件的完整路径获取后提交给后台处理建立对应的文件夹及文件及相互之间的关系。

## What does the proposed API look like?
可以拦截到drag的相关事件

**Comment by ousc** [comment]
It seems that this may only be implemented on lower versions of ie, because it is considered unsafe to get the real path of the file.

**Comment by cipchk** [comment]
浏览器出于安全考虑，是无法在 `input="file"` 内获取到真实路径的，只有一个 `name` 文件名，关于路径你可以试着使用 swf 的上传方式，这是一种老式的做法。或者使用 zip 的方式打包上传。
