### ISSUE TITLE
nz-select tags - Do not take tags from the model (re-open)

### ISSUE THREAD

**Issue by andchir** [NG-ZORRO/ng-zorro-antd#581]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior
If I set `[nzMode]="'tags'"` for `nz-select` it ignore tags from ngModel, if it is updated after ajax request. But if Iset `[nzMode]="'multiple'"` - it takes the data from the model.

## Expected behavior
Need take tags from model if it not empty.

## Minimal reproduction of the problem with instructions

On the demo there is no problem, but it arises in this case:

~~~
<nz-select
      style="width: 400px;"
      [nzTags]="true"
      [nzPlaceHolder]="'请选择人员'"
      [(ngModel)]="selectedMultipleOption"
      [nzNotFoundContent]="'无法找到'"
      [nzShowSearch]="true">
      <nz-option
        *ngFor="let option of searchOptions"
        [nzLabel]="option.label"
        [nzValue]="option">
      </nz-option>
    </nz-select>
~~~

~~~
searchOptions = [
    { value: 'jack', label: '杰克' },
    { value: 'lucy', label: '露西' },
    { value: 'tom', label: '汤姆' }
];
selectedMultipleOption = [];

ngOnInit(): void {
    // After ajax request - tags is empty
    setTimeout(() => {
        this.selectedMultipleOption.push(this.searchOptions[0]);
    }, 2000);
}
~~~

`this.changeDetectionRef.detectChanges()` does not help.

## What is the motivation / use case for changing the behavior?
I think that this is a bug.

## Environment

<pre><code>
Angular version: 4.2.4 

ng-zorro-antd: 0.5 - 0.6.0-rc.3

Browser:
- [x ] Chrome (desktop) version 61.0.3163.100
- [?] Firefox version XX
- [?] Safari (desktop) version XX
- [?] IE version XX
 
For Tooling issues:
- Node version: 6.11.4
- Platform:  Linux

**Comment by HsuanXyz** [comment]
try this.

```diff
- this.selectedMultipleOption.push(this.searchOptions[0]);
+ this.selectedMultipleOption = [...this.selectedMultipleOption, this.searchOptions[0]];
```

**Comment by andchir** [comment]
**HsuanXyz**, this is works, thank you.
But my example is not supposed to work? I do not override a variable, I just add a value. I think need to fix, or add example to documentation.

**Comment by vthinkxie** [comment]
@andchir  only can work when the data is immutable
you can check this https://angular.cn/guide/lifecycle-hooks#docheck-钩子
