### ISSUE TITLE
nz-select

### ISSUE THREAD

**Issue by fashiontai** [NG-ZORRO/ng-zorro-antd#5811]
## What problem does this feature solve?
能不能想tabs组件一样加一个守卫 nzCanDeactivate

## What does the proposed API look like?
加个守卫，当选中时如果用户可以在改变值之前做某些操作

**Comment by unnhao** [comment]
@fashiontai  `<nz-tabset>`不是本来就有`nzCanDeactivate`？

**Comment by hsuanxyz** [comment]
请用 Dropdown 代替
