### ISSUE TITLE
table表格 - 树形数据展示，文档代码bug

### ISSUE THREAD

**Issue by Minitiai** [NG-ZORRO/ng-zorro-antd#5813]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/issues/new/choose](https://github.com/NG-ZORRO/ng-zorro-antd/issues/new/choose)

### Steps to reproduce
[nzShowExpand]="!!item.children"
改为
[nzShowExpand]="!!item.children || !!item.children.length"

### What is expected?
[nzShowExpand]="!!item.children"
改为
[nzShowExpand]="!!item.children || !!item.children.length"

### What is actually happening?
代码不严谨

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Google Chrome |

---
实际上children.length = 0时，!!item.children = true

**Comment by Xiaolei1200** [comment]
<nz-tree>  nzExpandAll 不生效

**Comment by Xiaolei1200** [comment]
nzTreeTemplate和nzSearchValue  一起使用时  搜索结果不会标红了
