### ISSUE TITLE
关于全局样式的一个设计想法

### ISSUE THREAD

**Issue by litice-wen** [NG-ZORRO/ng-zorro-antd#5815]
## What problem does this feature solve?
目前我们改变组件主题是使用程序生成样式文件进行实现的。那么我们有了一个想法，能否通过全局的单例样式配置对象来实现呢？如果是这样，我们就不用程序来生成样式文件才能进行修改主题了。

## What does the proposed API look like?
###1.利用ng全局单例服务的特性，创建一个全局的主题配置对象（如：GlobalThemeConfig等等），这对象里有很多配置项，如：组件颜色、组件圆角等等（即：官方less文件里的全局变量都抽离到这个配置对象里）
###2.然后各个组件根据这个全局对象实现自己的逻辑
###3.这样，我们就可以通过修改GlobalThemeConfig对象的属性来修改全局样式了

**Comment by wendellhu95** [comment]
应该不会做这样的功能：

1. 工作量太大了
2. 所有的 style 都是 inline 的，丧失了 CSS cascading 的能力，会导致所有用户的 breaking change
