### ISSUE TITLE
在form表单中使用nz-upload，异步加载图片，图片无法显示。

### ISSUE THREAD

**Issue by water-zzh** [NG-ZORRO/ng-zorro-antd#5819]
<nz-upload
        #logo
        [nzAction]="uploadUrl"
        nzListType="picture-card"
        [(nzFileList)]="fileList"
        [nzShowButton]="fileList.length < 8"
        [nzPreview]="handlePreview"
      >
        <i nz-icon nzType="plus"></i>
        <div class="ant-upload-text">上传</div>
      </nz-upload>
      <nz-modal [nzVisible]="previewVisible" [nzContent]="modalContent" [nzFooter]="null" (nzOnCancel)="previewVisible = false">
        <ng-template #modalContent>
          <img [src]="previewImage" [ngStyle]="{ width: '100%' }" />
        </ng-template>
      </nz-modal>

post回调后，赋值给fileList,界面没有变化

**Comment by water-zzh** [comment]
在使用FormGroup的情况下，下面这段代码加载图片，不能显示
this.activeRoute.queryParams.subscribe((p) => {
 this.http.post('/post‘, null).subscribe((v)=>{
     this.fileList = v;
});
})

**Comment by cipchk** [comment]
@water-zzh 麻烦针对这个情况提供一个重现示例。

**Comment by water-zzh** [comment]
this.logo.ngOnInit();我在异步加载后，再调用这个方法，图片显示出来了。
