### ISSUE TITLE
Table组件问题

### ISSUE THREAD

**Issue by 81519434** [NG-ZORRO/ng-zorro-antd#582]
如果table组件使用#nzFixedHeader来固定表头，就一定得设置nzWidth，否则表格的表头和表内容的单元格无法对齐。
这样的话，如果要固定表格，那么宽度就不好自适应了。
版本：0.6.0-rc.3

**Comment by vthinkxie** [comment]
there is no other ways to fix header, if you have other methods to do it, please tell us.

**Comment by 81519434** [comment]
nzWidth做成可以按照百分比设置，可以吗

**Comment by 81519434** [comment]
@vthinkxie

**Comment by vthinkxie** [comment]
@81519434 you can set `[nzWidth]="'20%'"`

**Comment by 81519434** [comment]
thank you
