### ISSUE TITLE
[nzExtra]无法向<ng-template>中传context

### ISSUE THREAD

**Issue by CN-Tower** [NG-ZORRO/ng-zorro-antd#5820]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
对于ngFor出来的<nz-card>, [nzExtra]不可以向<ng-template>中传context

### What is expected?
[nzExtra]可以向<ng-template>中传context

### What is actually happening?
[nzExtra]无法向<ng-template>中传context

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome |

---
对于ngFor出来的<nz-card>, [nzExtra]不可以向<ng-template>中传context

**Comment by liwei511** [comment]
麻烦讲详细些？贴出部分代码

**Comment by vthinkxie** [comment]
ng-template 直接放在 ngFor 内部，angular 标准用法

**Comment by CN-Tower** [comment]
> ng-template 直接放在 ngFor 内部，angular 标准用法

问题是这个ng-template在其它地方也被用到了。nzExtra的templateRef不能传context影响通用性

**Comment by z976807015** [comment]
<nz-collapse>
  <nz-collapse-panel
    *ngFor="let panel of panels"
    [nzHeader]="panel.name"
    [nzActive]="panel.active"
    [nzExtra]="extraTpl"
  >
    <p>
      A dog is a type of domesticated animal. Known for its loyalty and faithfulness, it can be found as a
      welcome guest in many households across the world.
    </p>
  </nz-collapse-panel>
</nz-collapse>
<ng-template #extraTpl let-name>
  {{name}}
</ng-template>

如何传panel属性给template?
