### ISSUE TITLE
nz-tree-select 设置隐藏未匹配节点时,搜索只匹配到父节点,其节树被自动打开

### ISSUE THREAD

**Issue by zhenni-is-me** [NG-ZORRO/ng-zorro-antd#5821]
### Reproduction link
https://stackblitz.com/edit/angular-nxusgz?embed=1&file=src/app/app.component.ts

### Steps to reproduce
1. 搜索框输入 parent 1
2. 继续在输入框输入1

### What is expected?
最终匹配到一个父节点,其展开树节点图标应该是关闭状态

### What is actually happening?
最终匹配到一个父节点,其展开树节点图标是打开状态

Environment | Info
-- | --
ng-zorro-antd | 9.3.0
Browser | chrome

--- 
组件同时匹配到父节点和其内部的子节点,自动切换其展开状态,没有什么问题,但如果最终只匹配到了父节点,组件应该要把其树节点的展开状态恢复回去吧

**Comment by hsuanxyz** [comment]
Duplicate of #5736
