### ISSUE TITLE
Modal doesn't show or show delayed when open modal in Baidu map

### ISSUE THREAD

**Issue by alex644715** [NG-ZORRO/ng-zorro-antd#5822]
### Steps to reproduce
The modal doesn't show or show delayed when I click the marker in Baidu map. 
I have a marker in Baidu map, it contains a function that to switch variable 'isVisible' from false to true to open a modal. I checked the inspector that isVisible of Modal is already became true, but modal doesn't show or show delayed.
The modal shows only if I resize the window of browser.

```
HTML codes: 
<baidu-map [options]="opts" >
  <marker *ngFor="let marker of markers" (clicked)="showModal(marker)" [point]="marker.point" [options]="marker.options"></marker>
</baidu-map>

<nz-modal [(nzVisible)]="isVisible" nzTitle="The first Modal" (nzOnCancel)="handleCancel()" (nzOnOk)="handleOk()">
  <p>{{text}}</p>
</nz-modal>


TS codes:
  public showModal(marker) {
    console.log(marker);
    this.text = marker['point']['lng'];
    this.isVisible = true;
    console.log('modal open: ', this.isVisible);
  }
```

### What is expected?
Modal shows when I click marker.

### What is actually happening?
Modal doesn't show or show delayed.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome85.0.4183 and Safari |

**Comment by liwei511** [comment]
打开调试模式：Elements 里是否有遮罩和modal，看一下是否 z-index 设置的问题。

**Comment by alex644715** [comment]
> 打开调试模式：Elements 里是否有遮罩和modal，看一下是否 z-index 设置的问题。
并不是z-index问题，只有在resize窗口大小的时候，elements才能出现遮罩和modal

**Comment by alex644715** [comment]
并不是z-index问题，只有在resize窗口大小的时候，elements才能出现遮罩和modal

**Comment by vthinkxie** [comment]
使用 component 方式打开 modal，否则nz-modal组件内部的component的ngOnInit会先于打开执行

**Comment by alex644715** [comment]
@vthinkxie 我已经改成component方式打开modal了，还是出现一样的问题。这个问题只会出现点击在百度地图里的元素才会出现，我在百度地图之外的地方设置一个button，打开modal就完全没有问题，而且我试了Drawer也会出现同样的问题，但是Message就可以正常打开

**Comment by sz274071580** [comment]
import {...**NgZone**...} from '@angular/core';


constructor(
>...  
>**private ngZone: NgZone**
>...
) {}


public showModal(marker) {

> **this.ngZone.run(() => {**

>> console.log(marker);
>> this.text = marker['point']['lng'];
>> this.isVisible = true;
>> console.log('modal open: ', this.isVisible);

> **});**

}
