### ISSUE TITLE
Modal and Drawer doesn't show or show delayed when open modal in Baidu map

### ISSUE THREAD

**Issue by alex644715** [NG-ZORRO/ng-zorro-antd#5825]
### Steps to reproduce
The modal doesn't show or show delayed when I click the marker in Baidu map.
I have a marker in Baidu map, it contains a function that to switch variable 'isVisible' from false to true to open a modal. I checked the inspector that isVisible of Modal is already became true, but modal doesn't show or show delayed.
I tried nz-modal and modal component both, but both not work.
The modal shows only if I resize the window of browser.

 ```
HTML:
<button nz-button [nzType]="'primary'" (click)="showModal(markers[1])">My OK</button>

<baidu-map [options]="opts" >
  <marker *ngFor="let marker of markers"
          (clicked)="showModal(marker)"
          (loaded)="setAnimation($event)"
          [point]="marker.point" [options]="marker.options"></marker>
  <!--导航控件-->
  <control type="navigation" [options]="controlOpts"></control>
  <!--比例尺-->
  <control type="scale" [options]="scaleOpts"></control>
  <!--地图类型-->
  <control type="maptype" [options]="mapTypeOpts"></control>
  <control type="geolocation" [options]="geolocationOpts"></control>
</baidu-map>


TS:
  public showModal(marker) {
    console.log(marker);
    this.text = marker['point']['lng'];
    // const theDiv = document.querySelector('.ant-layout-content') as HTMLElement;
    const modal = this.modal.create({
      nzTitle: 'Modal Title',
      nzContent: ModalComponent,
      nzWidth:300,
      nzZIndex:1200,
      nzAutofocus: 'ok',
      // nzGetContainer: () => theDiv,
      nzComponentParams: {
        modalSelector: 'map',
        marker: marker
      },
      nzFooter: null
    });

    modal.afterOpen.subscribe(() => console.log('[afterOpen] emitted!'));
    // Return a result when closed
    modal.afterClose.subscribe(result => console.log('[afterClose] The result is:', result));
  }


```
new:
我已经改成component方式打开modal了，还是出现一样的问题, 不过它会出现遮罩，然后在页面的最左边出现一个白色的大约50*50的正方形,如下图所示。这个问题只会出现点击在百度地图里的元素才会出现，我在百度地图之外的地方设置一个button，打开modal就完全没有问题，而且我试了Drawer也会出现同样的问题，但是Message就可以正常打开
<img width="632" alt="截屏2020-09-24上午9 32 10" src="https://user-images.githubusercontent.com/61206468/94091747-99873a00-fe4b-11ea-93d1-a63501d02ce7.png">

### What is expected?
Modal shows when I click marker.

### What is actually happening?
Modal doesn't show or show delayed.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome85.0.4183 and Safari |

**Comment by hsuanxyz** [comment]
`marker(clicked)` 没被 zone 处理到，手动在 `ngZone.run` 里面调用.

https://stackblitz.com/edit/angular-ivy-aycda1
