### ISSUE TITLE
nz-icon与preserveWhitespaces不兼容

### ISSUE THREAD

**Issue by xiaody** [NG-ZORRO/ng-zorro-antd#5826]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-s1wxlk?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-s1wxlk?file=src/app/app.component.ts)

### Steps to reproduce
对于 preserveWhitespaces 为 true 的组件，如果 `<i nz-icon></i>` 开闭合标签之间有空白符，这个 icon 将无法渲染。

### What is expected?
`<i></i>` 内的空白符不影响渲染。

### What is actually happening?
`<i></i>` 内的空白符导致 JS 异常，无法渲染。

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome 85 |

**Comment by wendellhu95** [comment]
为什么要往里面放空格呢？icon 需要操作 DOM，实际上会替换掉 i 标签内的所有内容

**Comment by xiaody** [comment]
> 为什么要往里面放空格呢？icon 需要操作 DOM，实际上会替换掉 i 标签内的所有内容

同事遇到的问题，我想应该是无意的。也不排除有代码格式化工具把 

```html
<span><i></i></span>
```

格式化成多行这样子。

```html
<span>
  <i>
  </i>
</span>
```

**Comment by wendellhu95** [comment]
Fixed by https://github.com/ant-design/ant-design-icons/pull/380.
