### ISSUE TITLE
[Drawer] getContentComponent方法无法获取到instance

### ISSUE THREAD

**Issue by wangyun122** [NG-ZORRO/ng-zorro-antd#5833]
### Reproduction link
[https://stackblitz.com/edit/angular-4ntu3g-zxbtou?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-4ntu3g-zxbtou?file=src/app/app.component.ts)

### Steps to reproduce
```javascript
 openComponent(): void {
    const drawerRef = this.drawerService.create({
      nzContent: NzDrawerCustomComponent,
      nzContentParams: {
        value: this.value
      }
    });
    const instance = drawerRef.getContentComponent(); // instance is null
```

### What is expected?
获取 drawerRef instance

### What is actually happening?
null

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

---
是我使用的方法不对吗？

**Comment by hsuanxyz** [comment]
Get it in `afterOpen`

```ts
    drawerRef.afterOpen.subscribe(() => {
       const instance = drawerRef.getContentComponent();
       console.log("instance", instance);
    })
```
