### ISSUE TITLE
table虚拟滚动设置tr样式问题

### ISSUE THREAD

**Issue by qinzheng2019** [NG-ZORRO/ng-zorro-antd#5839]
### Reproduction link
[https://stackblitz.com/edit/angular-ygfa7r?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-ygfa7r?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
click tr to set style, pull down the scroll bar

### What is expected?
only set the style where I click tr

### What is actually happening?
when I pull down thie scroll bar,  other tr has no style

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | chrome   85.0.4183.121（正式版本） （64 位） |

**Comment by qinzheng2019** [comment]
What is actually happening?
when I pull down thie scroll bar, other tr has the same style

**Comment by vthinkxie** [comment]
the virtual scroll reuse the DOM
you should not manipulate DOM in angular applications
