### ISSUE TITLE
where is 'ant-form-item-with-help' from?

### ISSUE THREAD

**Issue by capdiem** [NG-ZORRO/ng-zorro-antd#584]
# code 1
`  <div nz-form-item>`
`  <div nz-form-control nzHasFeedback [nzValidateStatus]="getRegisterFormControl('username')">`
`  <nz-input formControlName="username" [nzPlaceHolder]="'username'" [nzSize]="'large'">`
`  </nz-input>`
`  <div nz-form-explain               *ngIf="getRegisterFormControl('username').invalid">`
`  {{getUsernameErrorMessageForRegister()}}`
` </div>`
` </div>`
` </div>`
# code 2
`  <div nz-form-item>`
`  <div nz-form-control nzHasFeedback [nzValidateStatus]="getRegisterFormControl('username')">`
`  <nz-input formControlName="username" [nzPlaceHolder]="'username'" [nzSize]="'large'">`
`  </nz-input>`
`  <div nz-form-explain  *ngIf="getloginFormControl('username').dirty&&getloginFormControl('username').hasError('required')"">`
`  please enter your username`
` </div>`
` </div>`
` </div>`

when i use code 2, there is a extra classname `ant-form-item-with-help` at the top element.
![default](https://user-images.githubusercontent.com/16507773/32987239-c372d59a-cd20-11e7-8441-54b013de0e66.png)

**Comment by vthinkxie** [comment]
nz-form-explain will add ant-form-item-with-help to the form.
