### ISSUE TITLE
 `nz-table` did not release memory in time

### ISSUE THREAD

**Issue by zmzimpl** [NG-ZORRO/ng-zorro-antd#5843]
### Reproduction link
[https://stackblitz.com/edit/angular-wi1esc?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-wi1esc?file=src/app/app.component.ts)

### Steps to reproduce
You can open this demo and record the memory usage of it at this time. Look at it again after ten minutes, you can find that its memory usage soars.
[Demo](https://angular-wi1esc.stackblitz.io/)

This is a test example of mine.
![image](https://user-images.githubusercontent.com/27490895/94528322-ccc23280-026a-11eb-871e-59e61f76b252.png)
![image](https://user-images.githubusercontent.com/27490895/94528330-cf248c80-026a-11eb-8fdc-4e295e04edb2.png)

### What is expected?
Release memory in time.

### What is actually happening?
Something not released in time

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome Edge |

**Comment by charisna** [comment]
+1 same problem in 9.3.0

**Comment by zmzimpl** [comment]
> +1 same problem in 9.3.0

Hi, I find a solution that you can destroy the `nz-table` instance and it will release memory. Just like clear data before request and then add `*ngIf="data?.length"` to `nz-table`. Although the user experience is poor.

**Comment by charisna** [comment]
> > +1 same problem in 9.3.0
> 
> Hi, I find a solution that you can destroy the `nz-table` instance and it will release memory. Just like clear data before request and then add `*ngIf="data?.length"` to `nz-table`. Although the user experience is poor.

Thanks I'll try

**Comment by vthinkxie** [comment]
Hi, this bug should have been fixed via https://github.com/NG-ZORRO/ng-zorro-antd/commit/94607a0afacafdeccd942a525b3c5fce6491df7a
