### ISSUE TITLE
Datepicker do not close on tab out

### ISSUE THREAD

**Issue by valerio-lucantonio** [NG-ZORRO/ng-zorro-antd#5844]
### Reproduction link
[https://stackblitz.com/edit/waxmwq--run?file=src/app/app.component.ts](https://stackblitz.com/edit/waxmwq--run?file=src/app/app.component.ts)

### Steps to reproduce
1) enter a date in the picker typing it with the keyboard
2) tab out

### What is expected?
the datepicker close after tab out

### What is actually happening?
datepicker keeps open while the focus moves to the next field in the form

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.0 |
| Browser | Chrome (but i suppose is the same on every browser) |

**Comment by valerio-lucantonio** [comment]
Hello, any news/acknowledge on this issue?

**Comment by arneysebaert** [comment]
This bug can still be reproduced, any progress/news on it?
