### ISSUE TITLE
nz-menu-item nzDisabled doesnt work

### ISSUE THREAD

**Issue by NanFengCheong** [NG-ZORRO/ng-zorro-antd#5854]
### Reproduction link
[https://stackblitz.com/edit/angular-htjltx?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-htjltx?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Hover dropdown and select 1st menu item

### What is expected?
click shouldn't be triggered

### What is actually happening?
click is triggered

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.0 |
| Browser | chrome |

**Comment by hsuanxyz** [comment]
`nz-menu-item` and `(click)` are the same host and cannot be intercepted, please use `(nzClick)`
