### ISSUE TITLE
nz-code-editor's ControlValueAccessor triggers superfluous view→model updates

### ISSUE THREAD

**Issue by Airblader** [NG-ZORRO/ng-zorro-antd#5869]
### Steps to reproduce
The ControlValueAccessor for nz-code-editor seems to have an issue where a model->view update will also trigger a view->model update, which can cause all kinds of issues like infinite loops when subscribing to form changes and then writing back into the control.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

**Comment by Airblader** [comment]
FYI I couldn't provide a Stackblitz because I can't get nz-code-editor to work in there.

**Comment by wendellhu95** [comment]
Fixed by #5872. Thanks for your issue and PR! 🥂

**Comment by Airblader** [comment]
@wendellhu95 My PR was a different issue, this issue is not fixed by that PR.

**Comment by Airblader** [comment]
I can't open a PR at the moment, but if someone wants to send the fix for this, I believe all that has to be done is change `emitValue` in `code-editor.component.ts` to this:

```
  private emitValue(value: string): void {
    if (this.value === value) {
      // If the value didn't change there's no reason to send an update.
      // Specifically this may happen during an update from the model (writeValue) where sending an update to the model would actually be incorrect.
      return;
    }

    this.value = value;
    this.onChange(value);
  }
```
