### ISSUE TITLE
nz-table 只使用nzScroll中x,y的一个属性时会导致nzBordered边框无效

### ISSUE THREAD

**Issue by mostermsater** [NG-ZORRO/ng-zorro-antd#5876]
### Reproduction link
[https://stackblitz.com/edit/angular-rdx2vk?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-rdx2vk?file=src/app/app.component.ts)

### Steps to reproduce
当使用nzScroll时只使用xy中的一个表单边框就会失效，两个都使用才会有效

### What is expected?
任意使用xy中的一个属性都不影响表单边框

### What is actually happening?
只使用任意一个会导致边框无效，两个都使用边框正常

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.0 |
| Browser | Chrome |

---
NzTableStyleService的setScroll方法需要分开判断x,y

**Comment by hsuanxyz** [comment]
Duplicate of #5858
