### ISSUE TITLE
在zorro9.3的版本上，nz-select在nzMode="multiple"时，输入中文后光标会定位在中文前

### ISSUE THREAD

**Issue by Acessss** [NG-ZORRO/ng-zorro-antd#5877]
### Reproduction link
[https://stackblitz.com/edit/angular-1vcw9w?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-1vcw9w?file=src/app/app.component.ts)

### Steps to reproduce
见重现链接

### What is expected?
输入中文后光标定位正常

### What is actually happening?
光标定位在中文之前

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

**Comment by vthinkxie** [comment]
在最新版本上已经修复完毕了，麻烦检查一下

**Comment by wenqi73** [comment]
Ref #5704.
