### ISSUE TITLE
下拉菜单多，导致页面渲染变慢

### ISSUE THREAD

**Issue by qwz873112851** [NG-ZORRO/ng-zorro-antd#5878]
## What problem does this feature solve?
当我需要做一个长列表时，每条数据都需要有几个下拉菜单，例如收藏夹菜单。50条数据，每条数据六个下拉菜单，页面会渲染很慢，浏览器警告[Violation] 'load' handler took 2092ms

## What does the proposed API look like?
希望针对下拉菜单的渲染进行优化

**Comment by vthinkxie** [comment]
提bug至少要给出版本和使用场景，现在 ng-zorro-antd 有 126 个 历史版本
