### ISSUE TITLE
nz-anchor不支持Modal 对话框

### ISSUE THREAD

**Issue by hdhxby** [NG-ZORRO/ng-zorro-antd#588]
nz-anchor不支持Modal 对话框吗,position的问题吗?,怎么处理.

**Comment by yangpengfei369** [comment]
@hdhxby 今天我也遇到了相同的问题,发现nz-anchor在Model中并不起作用,阅读源码发现,框架已经提供了该功能的实现, 只是并没有在官方文档进行说明. 在此备注下,希望对你有所帮助.
查看[此处](https://github.com/NG-ZORRO/ng-zorro-antd/blob/b5e9aeebbe5ee9a4b2a12fb13c707eab83b9b53b/src/components/anchor/nz-anchor.component.ts),  这里提供一个输入参数, 代表需要滚动的容器, 默认的话是window,即全局滚动,我们如果采用对话框的形式的话,需要手动指定滚动的容器.我传过去一个`target`参数, 可以使nz-anchor在对话框中正常使用.
`this.target = this.doc.querySelector('.ant-modal-wrap');`
`<nz-anchor [nzTarget]="target">`

Today I also encountered the same problem and found that nz-anchor in the Model does not work, read the source code found that the framework has provided the realization of this function, but did not explain in the official document. In this note, I hope for your help.
View here, [here](https://github.com/NG-ZORRO/ng-zorro-antd/blob/b5e9aeebbe5ee9a4b2a12fb13c707eab83b9b53b/src/components/anchor/nz-anchor.component.ts)is an input parameter, on behalf of the need to scroll the container, the default is window, the global scroll, if we use the form of a dialog box, you need to manually specify the scroll container. I pass a past `target`parameter, you can make nz-anchor in the dialog box normal use.
`this.target = this.doc.querySelector('.ant-modal-wrap');`
`<nz-anchor [nzTarget]="target">`

谷歌翻译是个好东西..
