### ISSUE TITLE
Select 选择器 多选搜索框（使用nzKeepUnListOptions属性的情况下）数据重复BUG

### ISSUE THREAD

**Issue by ferqx** [NG-ZORRO/ng-zorro-antd#590]
1.  版本：自0.5.0-rc.0以来就一直存在，在此十分抱歉没有及时的反馈

2. 代码地址：[https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/select/nz-select.component.ts](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/select/nz-select.component.ts)

3. 重现步骤：

使用nz-select组件添加nzKeepUnListOptions属性时，并存在默认数据的情况下，如以下情况：
 ![1b5b557c-20ea-4b4e-a7be-c122ce73c7bd](https://user-images.githubusercontent.com/23183225/33011523-300fb17a-ce19-11e7-9894-c8151294c0da.png)

 这时我再次输入与默认数据相关的文字时
 ![qq20171120-173657](https://user-images.githubusercontent.com/23183225/33011967-80413c94-ce1a-11e7-8d21-9f257a12d64c.png)

 并回车
 ![Uploading QQ20171120-173722.png…]()
 这时搜索相关的数据时数据再次出现，并增加相同数据

4. 原因：

 ![qq20171120-174910](https://user-images.githubusercontent.com/23183225/33012201-2f396938-ce1b-11e7-90d4-a7976767e9f5.png)
 在执行 `updateSelectedOption` 方法时，该红框内的 Set 对象 has 方法无法正确的过滤对象进行判断

5. 个人解决方案:

 ![qq20171120-180339](https://user-images.githubusercontent.com/23183225/33012921-3e9d15ee-ce1d-11e7-817d-8f1409f18088.png)

**Comment by vthinkxie** [comment]
thanks for your feedback, will be fixed in next version.
