### ISSUE TITLE
TreeSelect is not scrollable

### ISSUE THREAD

**Issue by duongle26** [NG-ZORRO/ng-zorro-antd#5901]
### Reproduction link
[https://stackblitz.com/edit/angular-ebfjxg?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ebfjxg?file=src/app/app.component.ts)

### Steps to reproduce
1. Click on the dropdown
2. Scroll to the bottom

### What is expected?
The overlay can be scroll and all the content of the dropdown can be seen.

### What is actually happening?
The overflow part of the content is hidden.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome 86 |

**Comment by hsuanxyz** [comment]
Hi, @duongle26 You can use `nzDropdownStyle`  to specify the height of the dropdown.

```html
<nz-tree-select
   ...
  [nzDropdownStyle]="{ 'max-height': '300px' }">
</nz-tree-select>
```
