### ISSUE TITLE
[nz-select]不能正常触发updateOn: 'blur' 验证

### ISSUE THREAD

**Issue by mostermsater** [NG-ZORRO/ng-zorro-antd#5902]
### Reproduction link
[https://stackblitz.com/edit/angular-ah1zza?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ah1zza?file=src/app/app.component.ts)
### Steps to reproduce
不填充任何数据 直接提交表单触发错误验证 这个时候再对select进行选择赋值

### What is expected?
select能正常触发blur验证

### What is actually happening?
表单updateOn为blur时不能进行触发 需要再次更改值才能触发验证。
表单updateOn为其它时能正常触发

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.0 |
| Browser | Chrome |

**Comment by hsuanxyz** [comment]
Duplicate of #5154
