### ISSUE TITLE
If the option 'maskClosable' of  modal component is set to false, the modal can't auto close  when the router changed.

### ISSUE THREAD

**Issue by bokire** [NG-ZORRO/ng-zorro-antd#591]
## Version

0.6.0

## Environment

https://ng.ant.design/

## Reproduction link

[https://ng.ant.design/#/components/modal](https://ng.ant.design/#/components/modal)

## Steps to reproduce

If the option 'maskClosable' of  modal component is set to false, the modal can't auto close  when the router changed

## What is expected?

if the router changed, auto close all modal

## What is actually happening?

can't auto close the modal which maskClosable is false

**Comment by vthinkxie** [comment]
duplicated #447
