### ISSUE TITLE
[Table] Default Pagination Styles With "small" Table

### ISSUE THREAD

**Issue by faisalmuhammad** [NG-ZORRO/ng-zorro-antd#5913]
## What problem does this feature solve?
At the moment, if we set `nzTableSize` as `small`, then the "mini" pagination is used. It would be great for user experience if we can have an option to set table pagination styles as well as an `@Input`

## What does the proposed API look like?
`nzPaginationType="paginationType"`

where "paginationType" is 'default' | 'mini' | 'normal'

**Comment by stygian-desolator** [comment]
If `nzPaginationType` is `default` and `nzTableSize` is `small`, will the final result be `small`?

**Comment by faisalmuhammad** [comment]
> If `nzPaginationType` is `default` and `nzTableSize` is `small`, will the final result be `small`?

`default` pagination type will result in the same behavior as of today. We will need a new pagination type e.g. `normal` which will keep the pagination buttons of the same size as with `default` table size.

**Comment by stygian-desolator** [comment]
Hello faisalmuhammad, I think your suggestion is very good, but I think it is more appropriate to only set `default` and `small` for `nzPaginationType`. If it is `default`, then it will be based on the `nzSize` of the table as before. If `small` is set, then `nzPagination` will become a `small` size.
