### ISSUE TITLE
nz-table 在nzModal中使用nzScroll属性时, 无数据样式错误

### ISSUE THREAD

**Issue by xuhailin** [NG-ZORRO/ng-zorro-antd#5923]
### Reproduction link
[https://angular-ae9afz.stackblitz.io/](https://angular-ae9afz.stackblitz.io/)

### Steps to reproduce
通过nzModalService创建组件，组件内使用了nz-table组件，nz-table设置了nzScroll属性

### What is expected?
nz-table的无数据图片样式能够正确显示

### What is actually happening?
无数据图片不居中

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.1 |
| Browser | chorme |

**Comment by hsuanxyz** [comment]
Duplicate of #5526
