### ISSUE TITLE
issue again: mask prevents user interaction when nzMask is set to false

### ISSUE THREAD

**Issue by hanaimin** [NG-ZORRO/ng-zorro-antd#5938]
### Steps to reproduce
 [nzMask]="false" 

### What is expected?
if set nzmask false, should not prevent user interaction.

### What is actually happening?
mask prevents user interaction when nzMask is set to false

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.1 |
| Browser | edge |

**Comment by VitalyLipko** [comment]
This is annoyed issue which appeared  in 10.0.0 also has in drawer component.  I wish they fix it finally.

**Comment by goodbeysr** [comment]
I'm wondering if this one is gonna be in the next release and when approximately?

**Comment by gdp81** [comment]
Hi guys, any news on this annoying issue?

**Comment by Laffery** [comment]
It's by designed that modal will interrupt interaction with other elements under the overlay. If you'd like to interact those elements anyway, it's recommended to use drawer instead.
