### ISSUE TITLE
Breadcrumb <a></a> tag's style is overiding breadcrumb last-child's style

### ISSUE THREAD

**Issue by duongle26** [NG-ZORRO/ng-zorro-antd#5942]
### Reproduction link
[https://stackblitz.com/edit/angular-yokrh1?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-yokrh1?file=src/app/app.component.ts)

### Steps to reproduce
Add ```<a></a>``` tag to the last breadcrumb-item.

### What is expected?
The last breadcrumb item's color should be different from the others.

### What is actually happening?
The last breadcrumb item's color is the same as the others.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome 86 |

**Comment by wenqi73** [comment]
As our DOM is not the same with ant-design, the less in https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/breadcrumb/style/index.less#L24-L29 is not work, need additional less in patch.less.

**Comment by stygian-desolator** [comment]
Hello @wenqi73 , I would like to fix this issue, but I have some doubts during the repair process, such as whether the `a` element needs to show the blue highlight effect when hovering, and the result of my test on `react-ant-design` is `a` The highlight effect of the element will also be erased, but I don’t know if this is a bug or a feature it should have
