### ISSUE TITLE
nz-tree单选模式，初始化设置节点selected为true，点击其他节点当前节点选中不消失(nz-tree radio mode, selected node initialization set to true, the current node click to select another node does not disappear)

### ISSUE THREAD

**Issue by taojian-byte** [NG-ZORRO/ng-zorro-antd#5949]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
1、初始化设置选中的节点状态selected为true
2、完成节点创建
3、用户点击其他节点选中

### What is expected?
当前只有一个节点被选中，背景为蓝色

### What is actually happening?
两个节点被选中，默认选中的节点可以通过再次点击取消

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.2 |
| Browser | chrome |

**Comment by wenqi73** [comment]
@taojian-byte Could you provide a reproduction by stackblitz?

**Comment by jaune162** [comment]
大概与 #6889 是同一个问题。该问题从2021年就有，目前还没有得到解决
