### ISSUE TITLE
[nz-tree-select] property to make only leaf items selectable

### ISSUE THREAD

**Issue by nicoayci** [NG-ZORRO/ng-zorro-antd#5956]
## What problem does this feature solve?
In some cases, only leaves should be selectable.

## What does the proposed API look like?
a new property called [nzOnlyLeafSelectable]

**Comment by hsuanxyz** [comment]
set the `selectable` property.

```diff
[
  {
    title: 'parent',
    key: '100',
+   selectable: false,
    children: [...]
  }
];

```

**Comment by nouram23** [comment]
tree data how it works?
