### ISSUE TITLE
nzTabLink: tab query sometimes not changed when click

### ISSUE THREAD

**Issue by lovepocky** [NG-ZORRO/ng-zorro-antd#5958]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
https://ng.ant.design/components/tabs/zh?tab=four
反复点击其中两个tab, 观察url的query部分

### What is expected?
query每次都都跟着变化

### What is actually happening?
有时候query没有跟着变化

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.2 |
| Browser | chrome |

**Comment by lovepocky** [comment]
![image](https://user-images.githubusercontent.com/10250869/96836597-c729c800-1477-11eb-94de-0105848349d5.png)

**Comment by Airblader** [comment]
#5857

**Comment by wenqi73** [comment]
The solution is in #5857.
