### ISSUE TITLE
nzQueryParams 方法首次加载或者切换页码操作都会被触发

### ISSUE THREAD

**Issue by C-racker** [NG-ZORRO/ng-zorro-antd#5960]
### Reproduction link
[https://stackblitz.com/edit/angular-dowtek?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-dowtek?file=src/app/app.component.ts)

### Steps to reproduce
添加nzQueryParams方法后会首次会被自动触发

### What is expected?
只有点击排序才触发，首次和切换页码、翻页无需触发

### What is actually happening?
首次加载和翻页都被触发

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.2 |
| Browser | Chrome 86 |

**Comment by vthinkxie** [comment]
切换页码触发是预期操作，服务器分页的时候需要页码传入服务器
如果需要过滤不需要的事件建议使用rxjs filter

**Comment by C-racker** [comment]
> 切换页码触发是预期操作，服务器分页的时候需要页码传入服务器
> 如果需要过滤不需要的事件建议使用rxjs filter

感谢回复，页码改变有单独的事件`nzPageIndexChange`这样不冲突了嘛 .. 而且首次加载也会请求服务器 这样很难控制什么时候发起请求。如果设计如此能否请教下具体如何使用rxjs过滤掉呢~

**Comment by vthinkxie** [comment]
如果使用服务器分页，不应当单独再使用 nzPageIndexChange 监听事件，rxjs 的  distinctUntilChanged 可以帮助你

**Comment by C-racker** [comment]
> 如果使用服务器分页，不应当单独再使用 nzPageIndexChange 监听事件，rxjs 的 distinctUntilChanged 可以帮助你，另外首次加载不请求服务器，数据从哪里获取

首次加载前会组装一些参数并手动请求，但是首次加载的时候表格`nzQueryParams`方法会主动响应，这样就导致我自己的请求跟表格的方法会冲突，先后顺序无法控制，并且会导致多次请求。

**Comment by vthinkxie** [comment]
nzQueryParams 只是一个 output，具体 output 之后做任何操作是由你的业务来决定的，并非由组件来决定

**Comment by C-racker** [comment]
> nzQueryParams 只是一个 output，具体 output 之后做任何操作是由你的业务代码来决定的，并非由组件来决定。

那可否首次加载的时候output不被响应呢，只有更改排序或筛选条件才响应？

**Comment by C-racker** [comment]
> nzQueryParams 只是一个 output，具体 output 之后做任何操作是由你的业务代码来决定的，并非由组件来决定。

antd react 示例首次加载并没有执行change方法：https://stackblitz.com/edit/react-5u44ai?file=index.js
antd angular 示例首次加载change方法被执行：https://stackblitz.com/edit/angular-dowtek?file=src/app/app

**Comment by vthinkxie** [comment]
> > nzQueryParams 只是一个 output，具体 output 之后做任何操作是由你的业务代码来决定的，并非由组件来决定。
> 
> 那可否首次加载的时候output不被响应呢，只有更改排序或筛选条件才响应？

rxjs 的 skip(1)就可以实现，你的所有需求都可以通过rxjs的操作符很容易满足

**Comment by vthinkxie** [comment]
> > nzQueryParams 只是一个 output，具体 output 之后做任何操作是由你的业务代码来决定的，并非由组件来决定。
> 
> antd react 示例首次加载并没有执行change方法：https://stackblitz.com/edit/react-5u44ai?file=index.js
> antd angular 示例首次加载change方法被执行：https://stackblitz.com/edit/angular-dowtek?file=src/app/app
> ![截图](https://user-images.githubusercontent.com/20217449/97690795-6c781800-1ad8-11eb-9eaa-a19ce0b80b80.png)

angular 与 react 的 table 设计思路从最开始就是完全不同的，提供的 api 也是完全不同的
