### ISSUE TITLE
Error while create login form using schematic

### ISSUE THREAD

**Issue by gks0089** [NG-ZORRO/ng-zorro-antd#5968]
ERROR in src/app/login/login.component.ts:7:41 - error NG8002: Can't bind to 'formGroup' since it isn't a known property of 'form'.

7     <form nz-form [nzLayout]="'inline'" [formGroup]="validateForm" (ngSubmit)="submitForm()">
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/login/login.component.ts:10:11 - error NG8001: 'nz-input-group' is not a known element:
1. If 'nz-input-group' is an Angular component, then verify that it is part of this module.
2. If 'nz-input-group' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

10           <nz-input-group nzPrefixIcon="user">
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/login/login.component.ts:17:11 - error NG8001: 'nz-input-group' is not a known element:
1. If 'nz-input-group' is an Angular component, then verify that it is part of this module.
2. If 'nz-input-group' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

17           <nz-input-group nzPrefixIcon="lock">
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.component.html:55:17 - error NG8001: 'nz-input-group' is not a known element:
1. If 'nz-input-group' is an Angular component, then verify that it is part of this module.
2. If 'nz-input-group' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

55                 <nz-input-group nzPrefixIcon="user">
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
src/app/app.component.html:62:17 - error NG8001: 'nz-input-group' is not a known element:
1. If 'nz-input-group' is an Angular component, then verify that it is part of this module.
2. If 'nz-input-group' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

62                 <nz-input-group nzPrefixIcon="lock">
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.

**Comment by vthinkxie** [comment]
hi, you have to import the module before using any component, read angular document first is a better option

**Comment by gks0089** [comment]
I already import into app.module.ts

**Comment by vthinkxie** [comment]
https://angular.io/guide/feature-modules

**Comment by gks0089** [comment]
![Module](https://user-images.githubusercontent.com/64023279/97175514-97a7f200-17ce-11eb-93cd-8f43840d0327.PNG)
![error](https://user-images.githubusercontent.com/64023279/97175577-aee6df80-17ce-11eb-909b-7da634b56e21.PNG)


I got no idea on this error

**Comment by vthinkxie** [comment]
the module in your app.module only works in your app.component, not in your login module

The prerequisite of Ant Design Angular is solid background knowledge of Angular and JavaScript ES2015.

**Comment by gks0089** [comment]
I dont create a separate module for login where I register my login component in the app module in order for me to use my login component inside my app component using the 
![project](https://user-images.githubusercontent.com/64023279/97186223-fc1d7e00-17db-11eb-9482-4dbe48431b5d.PNG)
routing module.

**Comment by vthinkxie** [comment]
have you import the NzInputModule?

**Comment by JackDan9** [comment]
I have a same question with it and I import all antd module in my project(app.module.ts), but cannot find it. 
It is so weird?
version: 'ng-antd-zorro': '^10.2.2'

**Comment by guilhermegps** [comment]
> the module in your app.module only works in your app.component, not in your login module and login component.
> 
> I believe you can find your error easily if you read the angular document before using ng-zorro-antd
> 
> > The prerequisite of Ant Design Angular is solid background knowledge of Angular and JavaScript ES2015.

If you don't know what's the problem, don't answer anything or just have him read the documentation.

**Comment by pavrda** [comment]
Add following into your `app.module.ts`
It will solve your problem:

```
import { NzInputModule } from 'ng-zorro-antd/input';

...
  imports: [
    ...
    NzInputModule
```

**Comment by sssunilshinde1** [comment]
you should have used ReactiveFormsModule.
