### ISSUE TITLE
z-tree数据较多的时候 在搜索框输入和删去检索内容比较慢

### ISSUE THREAD

**Issue by linacloud** [NG-ZORRO/ng-zorro-antd#5976]
### Reproduction link
[https://stackblitz.com/edit/angular-cxfqab?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-cxfqab?file=src/app/app.component.ts)

### Steps to reproduce
输入框输入检索内容 检索匹配树状数据  输入特别卡顿
删去检索内容 删去也特别卡顿

### What is expected?
希望输入框输入和删去都不要卡顿

### What is actually happening?
输入框输入和删去都比较卡段

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Google Chrome 已是最新版本 版本 86.0.4240.111（正式版本） (x86_64) |

---
不知道可否优化 难道这个nz-tree检索应该由后端实现？？
andesign 版本是（8.5.2） ps:版本可选项数据为空 所以写在这里

**Comment by vthinkxie** [comment]
可以使用最新版的虚拟滚动功能解决性能问题
https://ng.ant.design/components/tree/zh#components-tree-demo-virtual-scroll
