### ISSUE TITLE
English version for documentation

### ISSUE THREAD

**Issue by boubouhkarim** [NG-ZORRO/ng-zorro-antd#598]
## What problem does this feature solve?

i like to use ant design for my next angular project but it's fully written in Chinese. is there any plan to add an English version of docs.

## What does the proposed API look like?

Write an English version of docs

**Comment by vthinkxie** [comment]
Hi @boubouhkarim , it is in our plan, thanks for your advice

**Comment by nikolayr1** [comment]
i would love to see this happen.

**Comment by marco-nicolini** [comment]
Same here, i'm really contemplating this but the documentation not in english is a showstopper right now.

**Comment by vthinkxie** [comment]
Hi @boubouhkarim @nikolayr1 @marco-nicolini 
we switch our default branch to 0.7.0 and english doc has been provided
https://ng.ant.design/version/0.7.x/docs/introduce/en
please help us correct if some english sentence is wrong.
