### ISSUE TITLE
nzAllowEmpty icon can be clicked when TimePicker has been disabled

### ISSUE THREAD

**Issue by rencoo** [NG-ZORRO/ng-zorro-antd#5980]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-hgux55](https://stackblitz.com/edit/ng-zorro-antd-ivy-hgux55)

### Steps to reproduce
* select time when TimePicker  is active
* disable TimePicker  and watch if nzAllowEmpty icon can be clicked

### What is expected?
nzAllowEmpty icon can not be clicked when TimePicker has been disabled

### What is actually happening?
nzAllowEmpty icon can be clicked when TimePicker has been disabled

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.2 |
| Browser | chrome |

**Comment by wenqi73** [comment]
Should not display the clear icon when disabled.

**Comment by stygian-desolator** [comment]
Hello. I would like to fix this issue, if no one is already on it.

**Comment by wenqi73** [comment]
closed via #5990
