### ISSUE TITLE
Table summary

### ISSUE THREAD

**Issue by antsteyer** [NG-ZORRO/ng-zorro-antd#5984]
## What problem does this feature solve?
Implementation of the summary in table : https://ant.design/components/table/#components-table-demo-summary
I'm really interessed by this feature from Ant Design for React

## What does the proposed API look like?
Check :  https://ant.design/components/table/#components-table-demo-summary

**Comment by antsteyer** [comment]
Hi @vthinkxie ! Do you have any clue about the due date for this feature ?

**Comment by bcherkezovtf** [comment]
Hi @vthinkxie , is there any issue blocking this PR from merging?
This is really helpful feature for platform with alotof tables.

**Comment by GeryStoycheva** [comment]
Hello,
I am also interested in this feature. Will it be merged soon?

**Comment by L-Nonchev** [comment]
Hello @vthinkxie,
I am interested in this feature. I really hope it will be merged soon.
