### ISSUE TITLE
`ng add ng-zorro-antd` does not give options

### ISSUE THREAD

**Issue by nelnico** [NG-ZORRO/ng-zorro-antd#5985]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-mp18k ](https://codesandbox.io/s/ng-zorro-antd-ivy-mp18k )

### Steps to reproduce
ng new my-project -> cd my-project -> ng add ng-zorro-antd

### What is expected?
Options to configure to be presented as in https://ng.ant.design/docs/schematics/en

### What is actually happening?
ng ant get added to the project without any options presented.

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.2 |
| Browser | Chrome |

**Comment by hsuanxyz** [comment]
@nelnico Could you run `ng --version` to get more info? like `@angular/cli` version.
