### ISSUE TITLE
nz-select customContent option's height is not correct - a scroll bar displayed

### ISSUE THREAD

**Issue by daiyis** [NG-ZORRO/ng-zorro-antd#5987]
### Reproduction link
[https://ng-zorro-antd-ivy-aumjoy.stackblitz.io](https://ng-zorro-antd-ivy-aumjoy.stackblitz.io)

### Steps to reproduce
1. open the select
2. there is a scroll bar for even just one option

### What is expected?
there shouldn't be a scroll bar displayed for just one option with custom content.

please note that this is what happening on version 8.5, so it is a regression bug.

### What is actually happening?
A scroll bar displayed for only one option.

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.2 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
hi, plz try nzOptionHeightPx
https://ng.ant.design/components/select/en

**Comment by daiyis** [comment]
> hi, plz try nzOptionHeightPx
> https://ng.ant.design/components/select/en

oh nice one, great thanks!
