### ISSUE TITLE
`nzAllowClear` opens the select box instead of clearing it when `nz-select` is inside a `nz-input-group` with `nzCompact` 

### ISSUE THREAD

**Issue by IonelLupu** [NG-ZORRO/ng-zorro-antd#5989]
### Reproduction link
[https://stackblitz.com/edit/angular-bzybrd?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-bzybrd?file=src/app/app.component.ts)

### Steps to reproduce
Inside a `nz-input-group` with the ` nzCompact` attribute, add a `nz-select` with a few options and the `nzAllowClear` attribute.

### What is expected?
It is expected the select input to be cleared

### What is actually happening?
After selecting an option, clicking the clear icon in the select box opens the options dropdown instead of clearing the select input

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.2 |
| Browser | * |

**Comment by wenqi73** [comment]
![image](https://user-images.githubusercontent.com/23337087/98210290-47255700-1f7b-11eb-9215-fbb45e27087a.png)

Need to reverse the order of these two elements.

**Comment by IonelLupu** [comment]
@wenqi73 I see there is also the arrow present. I think the arrow should be removed all together when there is data in the selectbox, right?

**Comment by wenqi73** [comment]
@IonelLupu Not necessary, the clear icon will display above the arrow icon.

**Comment by IonelLupu** [comment]
@wenqi73  aah. I see now. This is the current behavior of the select box. 

So yeah. We need to swap them. You need help? Maybe I can do it 😄

**Comment by wenqi73** [comment]
@IonelLupu That's great!

**Comment by tangdiying** [comment]
How to solve it，

**Comment by tangdiying** [comment]
@wenqi73

**Comment by IonelLupu** [comment]
@tangdiying temporarily, I fixed this by adding a `nz-row` inside `nz-input-group`:
```html
<nz-input-group>
    <nz-row>
        <nz-col nzFlex="1" [nzSpan]="18">
            <nz-select nzAllowClear nzPlaceHolder="Choose">
                <nz-option  [nzLabel]="'test'" [nzValue]="'test'"></nz-option>
            </nz-select>
        </nz-col>
        <nz-col [nzSpan]="6">
            <input nz-input type="text">
        </nz-col>
    </nz-row>
</nz-input-group>

```

I still didn't find time to fix this 😢 Maybe you can find some time @tangdiying 😄 (and if you want)
