### ISSUE TITLE
select wrong items when Transfer module enable search function

### ISSUE THREAD

**Issue by NeverRen** [NG-ZORRO/ng-zorro-antd#599]
## Version

0.6.0

## Environment

any enviroment

## Reproduction link

[https://ng.ant.design/#/components/transfer](https://ng.ant.design/#/components/transfer)

## Steps to reproduce

create a transfer module and enable search box, type into a few words, then click select all button. it will select all items not only filtered ones, it's actually ALL items
On official website, this problem also exist.

## What is expected?

it should select items showed in the list, not all of items

## What is actually happening?

it actually selected ALL items

**Comment by vthinkxie** [comment]
@cipchk

**Comment by cipchk** [comment]
confirmed, thx.
