### ISSUE TITLE
TreeSelect组件应该增加可以禁止某项点击的设置

### ISSUE THREAD

**Issue by qq124719010** [NG-ZORRO/ng-zorro-antd#5997]
## What problem does this feature solve?
有时候TreeSelect的某一项不应该被用户点击选择，可是没法单独禁用那一项

## What does the proposed API look like?
可以有一个disabled设置禁用某一项

**Comment by hsuanxyz** [comment]
请查看 `NzTreeNodeOptions` 类型
![image](https://user-images.githubusercontent.com/22736418/97825570-05d24480-1cfa-11eb-99dd-0455de160540.png)

**Comment by qq124719010** [comment]
原来这样，TreeSelect的文档里没有提及这点，十分感谢！

**Comment by songxx1989** [comment]
我也遇到了相同的问题，`NzTreeNodeOptions`为什么不写在文档里，节约大家的时间。
