### ISSUE TITLE
nz-modal 设置 nzWidth 属性问题

### ISSUE THREAD

**Issue by wangxg6** [NG-ZORRO/ng-zorro-antd#6002]
### Steps to reproduce
nz-modal 中的 nzWidth 属性支持传入 string | number
但是在使用中
 `<nz-modal nzWidth="100"> ` 不能生效

### What is expected?
能不能让 
 `<nz-modal nzWidth="100"> `
等同于
 `<nz-modal [nzWidth]="100"> `

### What is actually happening?
 `<nz-modal nzWidth="100"> ` 不能生效

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.0 |
| Browser | Chrome |

**Comment by hsuanxyz** [comment]
`<nz-modal nzWidth="100px">` or `<nz-modal [nzWidth]="100">` 

![image](https://user-images.githubusercontent.com/22736418/97955527-57a1ca00-1de1-11eb-84f1-45c6dce05e5a.png)
