### ISSUE TITLE
UX Enhancement for nz-select multiple w/ search

### ISSUE THREAD

**Issue by thinkdj** [NG-ZORRO/ng-zorro-antd#6004]
## What problem does this feature solve?
nz-select-search block inside nz-select is taking up 4px width as the first element inside it. That is spoiling the perfect look of the component. How about changing the position of the search element to the end, making it more visually pleasing

## What does the proposed API look like?
Visually, it would look like - Before vs After: 
![proto](https://i.ibb.co/7Gw8NhX/SELECT-UX-ENHANCEMENT.png)

**Comment by vthinkxie** [comment]
https://stackoverflow.com/questions/42840136/disable-input-fields-in-reactive-form

**Comment by thinkdj** [comment]
> https://stackoverflow.com/questions/42840136/disable-input-fields-in-reactive-form

hi @vthinkxie, I think there is some misunderstanding. My suggestion was purely a visual one. Suggesting to put the input/searchable text in the end instead of the beginning.
