### ISSUE TITLE
nz-select disable allows editing

### ISSUE THREAD

**Issue by srinivas-tlt** [NG-ZORRO/ng-zorro-antd#6005]
### Reproduction link
[https://stackblitz.com/edit/angular-7bfft6?devtoolsheight=33&file=src/app/app.component.ts](https://stackblitz.com/edit/angular-7bfft6?devtoolsheight=33&file=src/app/app.component.ts)

### Steps to reproduce
The project is runnable as provided.

### What is expected?
nz-select component when disabled should not allow editing

### What is actually happening?
nz-select value is editable on clicking 'down' arrow at the right side of the nz-select field.

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.0 |
| Browser | Chrome |

**Comment by 232650413** [comment]
没法发问题，有没有遇到下面这种，打包时：
`Compiling ng-zorro-antd/typography : es2015 as esm2015
Compiling ng-zorro-antd/upload : es2015 as esm2015
Compiling ng-zorro-antd/version : es2015 as esm2015
92% chunk asset optimization optimize-css-webpack-pluginAn unhandled exception occurred: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: auto + 1
^..^
See "C:\Users\DEATHG~1\AppData\Local\Temp\ng-Hbupjp\angular-errors.log" for further details.`
