### ISSUE TITLE
Disabled attribute not working correctly

### ISSUE THREAD

**Issue by fbcarpinato** [NG-ZORRO/ng-zorro-antd#6010]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-p8vaqm?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-p8vaqm?file=src/app/app.component.ts)

### Steps to reproduce
Create a nz-button with [disabled]="0"

### What is expected?
The button should be enabled

### What is actually happening?
The disabled attribute is disabling even if a value of 0 is passed but if the value is false it works

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.0 |
| Browser | Chrome |

**Comment by wenqi73** [comment]
We use `coerceBooleanProperty` which is from cdk. https://github.com/angular/components/issues/20052#issuecomment-662093027
