### ISSUE TITLE
opened date-picker is floating when scrolling the container div

### ISSUE THREAD

**Issue by daiyis** [NG-ZORRO/ng-zorro-antd#6011]
### Reproduction link
[https://stackblitz.com/edit/angular-9vxeih?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-9vxeih?file=src/app/app.component.ts)

### Steps to reproduce
1. open the datepicker.
2. use the mouse to scroll down
3. the opened datepicker is floating there all the time

### What is expected?
the opened datepicker is scrolling the same as the textbox

### What is actually happening?
the opened datepicker not moving, still displayed misaligned.
- It is working fine with the scroll from the whole page as it shows on the document page
- same problem happens to the time-picker

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.0 |
| Browser | chrome |

**Comment by wenqi73** [comment]
Fixed by #6380.
