### ISSUE TITLE
nz-select nzDisabled Disabled select component opens dropdown menu when clicking on icon

### ISSUE THREAD

**Issue by sofiaps** [NG-ZORRO/ng-zorro-antd#6025]
### Reproduction link
[https://stackblitz.com/edit/new-project-gicmng?file=src/app/app.component.ts](https://stackblitz.com/edit/new-project-gicmng?file=src/app/app.component.ts)

### Steps to reproduce
Click on 'down' icon

### What is expected?
That the dropdown menu won't be opened

### What is actually happening?
The dropdown menu opens

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.0 |
| Browser | Chrome |

---
Clicking anywhere but the icon, works as expected. This behaviour occurs only when clicking on 'down' icon

**Comment by stygian-desolator** [comment]
I would like to fix this issue

**Comment by stygian-desolator** [comment]
It has been fixed(#6008), please wait patiently for the next version.

**Comment by vthinkxie** [comment]
closed via #6008 
thanks @stygian-desolator
