### ISSUE TITLE
form input 输入框回车事件导致页面上第一个button被点击

### ISSUE THREAD

**Issue by navisoftware** [NG-ZORRO/ng-zorro-antd#603]
## Version

0.6.0

## Environment

macos safari,chrome,ng-zorro(0.6)

## Reproduction link

[https://ng.ant.design/#/components/form](https://ng.ant.design/#/components/form)

## Steps to reproduce

https://ng.ant.design/#/components/form 
这个里面的[注册新用户],在任何input框内点击回车均会触发[Get Captcha]按钮被点击一下.
这样还会导致控件本身的enter事件监听被拦截,从而导致自定义业务不被执行.

The "registered new user" in this box, click enter in any input frame will trigger the [Get Captcha] button to be clicked
This will cause the enter event monitoring of the control itself to be intercepted, resulting in the custom business being not executed

## What is expected?

在input框内的任何键盘事件不被拦截和转发.

Any keyboard event in the input frame is not intercepted and forwarded

## What is actually happening?

现在回车事件是被拦截了,并默认点击了Form表单内的第一个按钮.

Now the return event is blocked and the default is clicked on the first button in the Form form

**Comment by ZuiSong** [comment]
You can add a attribute   `type = "button" `

**Comment by navisoftware** [comment]
@ZuiSong 非常感谢,解决方式很多.比如加一个隐藏按钮,什么都不做,放到form的第一个元素.但是我觉得这个应该算一个BUG,希望官方能修复.

**Comment by vthinkxie** [comment]
the default value for the type attribute of button elements is "submit", we can not fix it
https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type
