### ISSUE TITLE
Couldn't set default value in nz-select of tags mode using formGroup

### ISSUE THREAD

**Issue by LemniscateX** [NG-ZORRO/ng-zorro-antd#6033]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-select-report](https://stackblitz.com/edit/ng-zorro-select-report)

### Steps to reproduce
Just run that demo, compare the two input.

### What is expected?
In the first input field: 
- There should be a default value, which is set by the formGroup
- Options should show up

### What is actually happening?
In the first input field:
- An error occurs: listOfSelectedValue.filter is not a function.
- There isn't default value or option list

It should act like the second input field

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.0 |
| Browser | Version 86.0.4240.183 (Official Build) (64-bit) |

---
Compare the two, nz-select with default mode works just fine, but nz-select with tags mode triggers an error.

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-select-report-5vyoay-6tixj8

**Comment by LemniscateX** [comment]
> https://stackblitz.com/edit/ng-zorro-select-report-5vyoay-6tixj8

@vthinkxie hi, link above is unreachable. Could you offer some hints? Thanks.

**Comment by vthinkxie** [comment]
try this https://stackblitz.com/edit/ng-zorro-select-report-nhxdiq

**Comment by LemniscateX** [comment]
> try this https://stackblitz.com/edit/ng-zorro-select-report-nhxdiq

Got it! Thanks a lot.
