### ISSUE TITLE
Cascader should restore its value after cancel search

### ISSUE THREAD

**Issue by rppig42** [NG-ZORRO/ng-zorro-antd#6036]
### Reproduction link
[https://stackblitz.com/edit/angular-zz1hq5?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-zz1hq5?file=src/app/app.component.ts)

### Steps to reproduce
1. select something from the cascader
2. type random string into the search bar
3. click outside the menu to close the popover

### What is expected?
1. cascader reverted to original value

### What is actually happening?
1. cascader remains with the search string

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.1 |
| Browser | Chrome latest |

---
You can compare with react version https://vulov4--run.stackblitz.io

**Comment by stygian-desolator** [comment]
I would like to fix this issue
