### ISSUE TITLE
nz-alert - provide a way to pass in custom icons to the component

### ISSUE THREAD

**Issue by banjankri** [NG-ZORRO/ng-zorro-antd#6047]
## What problem does this feature solve?
At the moment we have a fixed set of icons available to be used in the component - we would like to be able to provide a custom icon to the alert box.

It would be benefitial to be able to provide a different icon to the alert box in case a distinct error/warning occurs without the need of re-working the entire box and keeping the UX consistent.

Happy to work on a PR for it.

## What does the proposed API look like?
content projection to allow user to specify exactly what icon is need in (e.g. filled/outlined etc)

**Comment by vthinkxie** [comment]
hi, have you try `[nzIconType]`

**Comment by banjankri** [comment]
hey, thanks for quick reply! I have tried it, but our UI designers are after a totally custom SVG icon for an alert box, so it cannot be done with `[nzIconType]` as it only pulls from ng-zorro icons set.

**Comment by wendellhu95** [comment]
You can use icon namespace for that: https://ng.ant.design/components/icon/en#components-icon-demo-namespace

**Comment by banjankri** [comment]
Nice! Thanks for the tip, closing the issue.

**Comment by banjankri** [comment]
Actually just seeing the codebase of the `nz-alert` I do not see it is passed into the icon: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/alert/alert.component.ts#L49. Did you mean using this for the implementation of this feature @wendellhu95 ?

**Comment by banjankri** [comment]
ah forget it, reopened prematurely - can see how it works now - neat!
