### ISSUE TITLE
如何限制nz-input框的输入长度，这个好像可以无限输入啊！

### ISSUE THREAD

**Issue by 15879476852** [NG-ZORRO/ng-zorro-antd#605]

**Comment by 15879476852** [comment]
如何限制nz-input框的输入长度，api里好像没有这个东西，也没有输入事件，只能超控dom来限制了

**Comment by simplejason** [comment]
you can set "width: 100px"(based on your layout) to limit it，ng-zorro‘s components can be used like html elements too. @15879476852
