### ISSUE TITLE
现在nz-table有纵向虚拟滚动，是否有横向虚拟滚动，或横向纵向一起虚拟滚动

### ISSUE THREAD

**Issue by peacejj** [NG-ZORRO/ng-zorro-antd#6050]
## What problem does this feature solve?
现在nz-table有纵向虚拟滚动，是否有横向虚拟滚动，或横向纵向一起虚拟滚动

## What does the proposed API look like?
想要：nz-table有横向虚拟滚动，或横向纵向一起虚拟滚动

**Comment by peacejj** [comment]
@vthinkxie help~

**Comment by vthinkxie** [comment]
duplicated of #6158
