### ISSUE TITLE
 Errors received in Datepicker dynamic nzMode selections.

### ISSUE THREAD

**Issue by C3maLi** [NG-ZORRO/ng-zorro-antd#6052]
### Reproduction link
https://stackblitz.com/edit/ng-zorro-datepicker-dynamic-nzmode?file=src/app/app.component.ts
![date](https://user-images.githubusercontent.com/3233264/99080159-f2648a80-25d1-11eb-81d3-312056e0eace.gif)

### Steps to reproduce
When I want to dynamically change nzMode;
No problem when I choose daily 
No problem when I choose weekly
No problem when I choose monthly
No problem when I choose yearly

Only when I choose daily and then weekly or weekly and then select daily,
visually an error occurs when I click somewhere in the popup popup, the problem is fixed. Do you think this is a bug?

As the second question, when I dynamically change nzMode in the visual, the input field with the date is not formatted according to nzMode, so when I select annual, the input field is not displayed as "yyyy". Is there a solution to this?

Thanks.

### What is expected?
Elimination of errors in visual and sample work in dynamic selection of nzMode.

### What is actually happening?
--

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.1 |
| Browser | Chrome |

**Comment by C3maLi** [comment]
Hello,
Thank you so much for solving this problem.
Formats change in dynamic change.

However, the following problem persists? Do you know about this?
or an ongoing process.

When we switch from the daily selection to the weekly selection, the popup of the daily show is also shown in the week. Likewise, the same problem occurs when switching from weekly to diary.
I tried to explain it visually.

Thanks to those who have already contributed.

![ng-zorro-nzmode](https://user-images.githubusercontent.com/3233264/100724057-85bffd00-33d3-11eb-9356-c1532a63d684.gif)

**Comment by wenqi73** [comment]
@C3maLi You did not switch mode in your gif, the official document works fine.

**Comment by C3maLi** [comment]
I'm so sorry for sharing the wrong gif.
I just added the gif again, can you see it again?

![ng-zorro](https://user-images.githubusercontent.com/3233264/100731526-9032c480-33dc-11eb-9e88-b4f3ffe511b0.gif)
