### ISSUE TITLE
Table Component RoadMap

### ISSUE THREAD

**Issue by icycore** [NG-ZORRO/ng-zorro-antd#606]
## What problem does this feature solve?

```Table feather``` same as ant design for ```React```

## What does the proposed API look like?

I need a ```more powerful table component``` in order to deal with some usage in "dashboard system"、"admin system".
I've check the table in ant design,those feather is what i need.
I want to ask how long will you guys take to implement all those feather in react version,do you have a road map?
thanks a lot,you guys are doing a great job!

**Comment by vthinkxie** [comment]
Hi, @icycore we can not promise accurate time at the moment, please follow the issue of #463 , Thank you for your concern.
