### ISSUE TITLE
nz-select used in multiple or tags mode will cause zoomMotion error

### ISSUE THREAD

**Issue by Chibubaodezhu** [NG-ZORRO/ng-zorro-antd#6065]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-sxy9vv?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-sxy9vv?file=src/app/app.component.ts)

### Steps to reproduce
When you use nz-select component in nz-modal, and the mode of nz-select is multiple or tags. First, you open the modal and choose some value from select, then you close the modal and open the modal again, now, when you click the close icon of select, the console of browser will prints 'Cannot read property 'zoomMotion' of undefined'

### What is expected?
remove the value we closed

### What is actually happening?
the option was not removed

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.2 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
duplicated https://github.com/NG-ZORRO/ng-zorro-antd/issues/5290
