### ISSUE TITLE
整个 ng-zorro-antd 可否使用 cdn 的方式加载?

### ISSUE THREAD

**Issue by wang777777** [NG-ZORRO/ng-zorro-antd#6067]
## What problem does this feature solve?
比如使用以下网址提供的 cdn，https://www.jsdelivr.com/package/npm/ng-zorro-antd?version=9.3.0 可否给个示例？谢谢

## What does the proposed API look like?
无

**Comment by vthinkxie** [comment]
angular 项目涉及到 compile 过程，不支持无编译导入
