### ISSUE TITLE
分页条数不能配置

### ISSUE THREAD

**Issue by vellengs** [NG-ZORRO/ng-zorro-antd#608]
![image](https://user-images.githubusercontent.com/5743338/33229718-3ae6943e-d20f-11e7-8a27-dae9ec012521.png)

**Comment by tigercosmos** [comment]
Use `nzPageSize`

**Comment by vellengs** [comment]
No, I mean the options can't config.

**Comment by vellengs** [comment]
I saw that's hard code.

**Comment by tigercosmos** [comment]
Ah! I see.
This should be improved!

**Comment by hllinc** [comment]
Omg!

**Comment by hllinc** [comment]
I had add this function in the source code, but I cannot submit.

**Comment by vthinkxie** [comment]
@hllinc please do not merge 0.5.x to master, you should rebase your code first.

**Comment by hllinc** [comment]
Sorry, I cannot commit code now.@vthinkxie

**Comment by hllinc** [comment]
how can i push my code to master?

**Comment by vthinkxie** [comment]
@hllinc just start a new pr

**Comment by hllinc** [comment]
a new pr is start, please check it and update the package as soon as possible. our projects is waiting for using, thank you very much.

**Comment by vthinkxie** [comment]
@hllinc we will review it soon

**Comment by hllinc** [comment]
@vthinkxie check failed?
