### ISSUE TITLE
dynamic listOfFilter

### ISSUE THREAD

**Issue by robertnicjoo** [NG-ZORRO/ng-zorro-antd#6091]
### Reproduction link
[https://codesandbox.io/s/beautiful-galileo-cml01?file=/src/app/app.component.ts](https://codesandbox.io/s/beautiful-galileo-cml01?file=/src/app/app.component.ts)

### Steps to reproduce
How can I get my dynamic data into `listOfFilter`?

by sample codes

```
listOfColumns: ColumnItem[] = [
    {
      name: 'Name',
      sortOrder: null,
      sortFn: (a: DataItem, b: DataItem) => a.name.localeCompare(b.name),
      sortDirections: ['ascend', 'descend', null],
      filterMultiple: true,
      listOfFilter: [
        { text: 'Joe', value: 'Joe' },
        { text: 'Jim', value: 'Jim', byDefault: true }
      ],
      filterFn: (list: string[], item: DataItem) => list.some(name => item.name.indexOf(name) !== -1)
    },
```

`listOfFilter` it is provided statically

```
 listOfFilter: [
        { text: 'Joe', value: 'Joe' },
        { text: 'Jim', value: 'Jim', byDefault: true }
      ],
```

and I can't figure how to get my dynamic data into `listOfFilter`?

### What is expected?
Getting my column data dynamically instead of providing statically.

### What is actually happening?
Can't get my column values in filter section

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.2 |
| Browser | Firefox |

**Comment by robertnicjoo** [comment]
# Solved

So I've created separate array of my columns data and assigned those arrays to `listOfFilter`, it's probably not the best solution but for now doing the job just fine

### Sample code

```javascript
// create empty array
titles: any[] = []


// push data to my array from my loop function
this.titles.push({
  text: data.data[i]['name'],
  value: data.data[i]['name'],
})

// use the array as of listOfFilter
{
        name: 'Title',
        sortOrder: null,
        sortDirections: ['ascend', 'descend', null],
        sortFn: (a: DataItem, b: DataItem) => a.name.length - b.name.length,
        filterMultiple: false,
        listOfFilter: this.titles,
        filterFn: (name: string, item: DataItem) => item.name.indexOf(name) !== -1
},
```

Hope it helps.

**Comment by asif986** [comment]
@robertnicjoo Hello i am try your solution in  , but getting blank.

**Comment by robertnicjoo** [comment]
@asif986 Hi, sorry man this was project for client of mine and currently have no memory of TBH  I prefer writing 60.000 lines of code rather than using this package one more time! it's just pain in the A...

Maybe others be able to help you with it.
- Best of luck.
