### ISSUE TITLE
nztable 固定表头滑动IE兼容问题

### ISSUE THREAD

**Issue by git-xyx** [NG-ZORRO/ng-zorro-antd#6094]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
重现链接因为要求就填了antd首页地址，IE11浏览器上，table的固定头，滑动方式有bug，并未固定住，chrome才可以

### What is expected?
ie尽可能也能支持table表头固定滑动效果，版本更新较慢，希望能提供回复下解决方案。

### What is actually happening?
IE不支持table表头固定滑动效果，表头也会跟着滑动,

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.2 |
| Browser | IE |

![image](https://user-images.githubusercontent.com/53975298/99955495-6a476780-2dbf-11eb-95c9-96f1f5f22957.png)

**Comment by stygian-desolator** [comment]
`sticky` doesn't work on IE11

**Comment by vthinkxie** [comment]
因为 ie 不支持 `position:sticky`，目前设计 ie 为降级处理是预期的行为，后续也没有支持的计划

解决方案建议切换为别的组件，比如 ag grid，zorro 所有的 module 都可以单独引入，可以将 nzTable 组件移除
