### ISSUE TITLE
文档是否有支持markdown的计划？

### ISSUE THREAD

**Issue by CK110** [NG-ZORRO/ng-zorro-antd#61]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

目前showcase的文档是直接写在html中的（类似primeng），不知是否有有计划直接写markdown（类似antd）的计划？

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
Markdown is supported through `nz-markdown` component, see https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/showcase/nz-intro-getting-started/nz-intro-get-started.component.ts#L8 and https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/showcase/nz-intro-getting-started/nz-intro-get-started.html#L1
The doc system is very simple now, we will try to make it more user friendly.
Thanks.
