### ISSUE TITLE
The nzFileType parameter configuration of nz-upload component application/x-rar-compressed is invalid

### ISSUE THREAD

**Issue by MaxCDon** [NG-ZORRO/ng-zorro-antd#6102]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-fege5a?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-fege5a?file=src/app/app.component.ts)

### Steps to reproduce
Open the stackblitz link click the upload component to select the .rar file

### What is expected?
Configuration takes effect, you can upload .rar files

### What is actually happening?
Unable to upload .rar file

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2, 10.1.2 |
| Browser | Chrome 87.0.4280.66 |

---
nzFileType is configured as 'application/x-rar' or 'application/octet-stream' is also invalid

**Comment by cipchk** [comment]
Try:

```diff
- <nz-upload nzAction="https://jsonplaceholder.typicode.com/posts/" [nzFileType]="'application/x-rar-compressed'">
+ <nz-upload nzAction="https://jsonplaceholder.typicode.com/posts/" [nzFileType]="'application/x-rar-compressed,application/x-rar'">
```

**Comment by MaxCDon** [comment]
> Try:
> 
> ```diff
> - <nz-upload nzAction="https://jsonplaceholder.typicode.com/posts/" [nzFileType]="'application/x-rar-compressed'">
> + <nz-upload nzAction="https://jsonplaceholder.typicode.com/posts/" [nzFileType]="'application/x-rar-compressed,application/x-rar'">
> ```

I try it, and also invalid

**Comment by cipchk** [comment]
I can work well with this demo.

gif:

![demo](https://user-images.githubusercontent.com/2987467/100252751-31ec8880-2f7b-11eb-88f8-411b889dc3c9.gif)

**Comment by MaxCDon** [comment]
@cipchk 
I test it can work well on mac chrome, but it invalid on windows chrome and firefox.

version: chrome 87.0.4280.66, firefox 79.0

gif: 
![nz-upload](https://user-images.githubusercontent.com/33407227/100303164-e4056e00-2fd6-11eb-899d-dcc4f24588ce.gif)

**Comment by cipchk** [comment]
Should real type of difference between different systems, You can get valid types via `nzFilter`, like this:

```ts
import { Component } from '@angular/core';
import { UploadFilter } from 'ng-zorro-antd/upload';

@Component({
  selector: 'my-app',
  template: `
    <nz-upload nzAction="https://jsonplaceholder.typicode.com/posts/" [nzFileType]="'application/x-rar-compressed,application/x-rar'" [nzFilter]="filters">
      <button nz-button><i nz-icon nzType="upload"></i><span>Click to Upload</span></button>
    </nz-upload>
  `
})
export class AppComponent {
  filters:  UploadFilter[] = [
    {
      name: 'get-type',
      fn: (fileList) => {
        console.log(fileList[0].type);
        return fileList;
      }
    }
  ];
}
```

**Comment by MaxCDon** [comment]
Can't get rar filetype

![image](https://user-images.githubusercontent.com/33407227/100306848-55491f00-2fdf-11eb-9ec1-6ad9d8c82f84.png)

**Comment by cipchk** [comment]
May be an invalid rar file. Another solution is to limit the file extension.

**Comment by MaxCDon** [comment]
[https://cowtransfer.com/s/0936994b2b4d47](url)
This is my test file, it can work well on macos.
Another solution are you referring to nzAccept?

**Comment by cipchk** [comment]
抱歉，我也无法解释为什么在 windows 下会空，我试着根据 cowtransfer.com/s/0936994b2b4d47 提供的尝试上传是可以获取到类型为 `application/x-rar`。

至于其他解决方法有许多种，比如 `nzAccept` 在现代浏览器都是有效的，或者也可以自己通过 `nzFilter` 参数再根据 `name` 来判断一个有效的 rar 文件后缀。

关闭此 issues，我认为这是文件或浏览器行为引起。
