### ISSUE TITLE
Scrollable tabs in angular

### ISSUE THREAD

**Issue by robertnicjoo** [NG-ZORRO/ng-zorro-antd#6105]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy12](https://stackblitz.com/edit/ng-zorro-antd-ivy12)

### Steps to reproduce
How can I have such scrollable tabs in angular version? (this screenshot and code below is react based)

![Screenshot(23)](https://user-images.githubusercontent.com/8672823/100401081-0c4ea480-308b-11eb-808e-3e4b5f09462f.png)

```react
<Tabs className={style['contain-tabs']}>
          <TabPane key="1" tab={<Button type="primary" size="large" icon={<PlusOutlined />}>Create New</Button>} />
          <TabPane key="2" tab={<Button size="large" icon={<DownloadOutlined />} className="ml-3">Download</Button>} />
          <TabPane key="3" tab={<Button size="large" icon={<DownloadOutlined />} className="ml-3">Download</Button>} />
          <TabPane key="4" tab={<Button size="large" icon={<DownloadOutlined />} className="ml-3">Download</Button>} />
          <TabPane key="5" tab={<Button size="large" icon={<DownloadOutlined />} className="ml-3">Download</Button>} />
          <TabPane key="6" tab={<Button size="large" icon={<DownloadOutlined />} className="ml-3">Download</Button>} />
          <TabPane key="7" tab={<Button size="large" icon={<DownloadOutlined />} className="ml-3">Download</Button>} />
</Tabs>
```

### What is expected?
1. Scroll tabs on mobile / small screens
2. use buttons as tab title with no body content

### What is actually happening?
it shows listed

### sample code refer to

```
src\app\components\kit\widgets\General\11\11.component.html
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.2 |
| Browser | Firefox |

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/tabs/en#components-tabs-demo-slide

**Comment by robertnicjoo** [comment]
@vthinkxie please don't close this begore receiving my response! 

That sample shows how to make slider yes, but it doesn't answer my second question 

```use buttons as tab title with no body content
```

**Comment by vthinkxie** [comment]
Hi
1. `[nzTitle]` accept `TemplateRef` as document describe
2. if you don't pass any body content, there won't be any body content.

**Comment by robertnicjoo** [comment]
@vthinkxie would you mind check this sample of my code please? sort of can't get it right

https://stackblitz.com/edit/ng-zorro-antd-ivy-9brfqg?file=src%2Findex.html

**Comment by robertnicjoo** [comment]
Or if I do this, it only prints HTML

https://stackblitz.com/edit/ng-zorro-antd-ivy-ibh9d5?file=src%2Findex.html

**Comment by robertnicjoo** [comment]
**Based on documents code:** https://stackblitz.com/edit/angular-aab4nz-jhwkuh?file=src/app/app.component.ts

**Comment by robertnicjoo** [comment]
@vthinkxie please if you can't or you don't have plan to help me open this issue let others at least help. 

Because titles just print html codes instead of showing buttons. 

Thanks.

**Comment by vthinkxie** [comment]
Hi
if you dont get what is TemplateRef, I believe reading angular.io is a better option. issue is only used for bug report here
