### ISSUE TITLE
Connector between start time and end time of date component, which does not conform to semantics

### ISSUE THREAD

**Issue by xiaoqiangvs** [NG-ZORRO/ng-zorro-antd#6106]
## What problem does this feature solve?
The connector between the start time and the end time of a date component does not conform to the semantics. It should be expressed as - and ~ as approximately

## What does the proposed API look like?
[nzCustomConnector]  string

**Comment by stygian-desolator** [comment]
`[nzSeparator]` support custom separator, it may help you

**Comment by xiaoqiangvs** [comment]
![image](https://user-images.githubusercontent.com/25839789/100564748-da447900-32fc-11eb-889a-c016222b0012.png),
i want to modify this ~ to - ,  datepicker cantnot  `nzSeparator` property

**Comment by stygian-desolator** [comment]
> ![image](https://user-images.githubusercontent.com/25839789/100564748-da447900-32fc-11eb-889a-c016222b0012.png),
> i want to modify this ~ to - , datepicker cantnot `nzSeparator` property

it seems like `nz-range-picker`, not `nz-date-picker` 🤔

**Comment by wenqi73** [comment]
@xiaoqiangvs Your screenshot is old, 8.x version did not support this.
