### ISSUE TITLE
Descriptions default layout style error, should align content horizontal

### ISSUE THREAD

**Issue by emondora** [NG-ZORRO/ng-zorro-antd#6109]
### Reproduction link
[https://ng-zorro-antd-ivy-fwxmey.stackblitz.io/](https://ng-zorro-antd-ivy-fwxmey.stackblitz.io/)

### Steps to reproduce
1. Add descriptions;
2. Set nzLayout default (default is horizontal align);
3. Get wrong content align as vertial not horizontal;

PS: The offical descriptions first default sample is wrong. 

### What is expected?
nzLayout default should align content horizontal

### What is actually happening?
nzLayout default align content vertical

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.2 |
| Browser | Chrome 87.0.4280.66 |

---
V10.0.1 everything goes fine

**Comment by wendellhu95** [comment]
It looks like that Ant Design renamed 'ant-descriptions-item' to 'ant-descriptions-item-container'.

Could you please submit a PR for this?
