### ISSUE TITLE
this.nzDropdownMenu.descendantMenuItemClick$ is undefined

### ISSUE THREAD

**Issue by robertnicjoo** [NG-ZORRO/ng-zorro-antd#6115]
### Reproduction link
[Demo](https://stackblitz.com/edit/angular-ecxh6j?file=src/app/app.component.ts)

### Steps to reproduce
I am trying to make custom filter in my table but i'm unable to open dropdown, it return error of

```
ERROR TypeError: this.nzDropdownMenu.descendantMenuItemClick$ is undefined
```

### What is expected?
Open each table heading dropfown

### What is actually happening?

get error

![01101](https://user-images.githubusercontent.com/8672823/100533658-61301d80-3239-11eb-8704-5a81c7f3fb3c.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.2 |
| Browser | Firefox |

---
# Code

```html
<th *ngFor="let column of listOfColumns; let i = index;">
                {{ column.name }}
                <nz-filter-trigger [(nzVisible)]="visible" [nzActive]="searchValue.length > 0" [nzDropdownMenu]="'menu' +  i">
                  <i nz-icon nzType="caret-down"></i>
                </nz-filter-trigger>
                <!-- filter fields -->
                <nz-dropdown-menu #menu{{i}}="nzDropdownMenu">
                    <div class="search-box p-2" *ngIf="visible">
                      <div class="mb-2">
                        <label for="">Search By {{ column.name }}</label> <br>
                        <input nz-input placeholder="Type here..." />
                      </div>

                      <div class="mb-2">
                        <label for="sort">Sort Order</label> <br>
                        <nz-select ngModel="none" class="text-left mr-2" style="width:100%;">
                            <nz-option nzValue="none" nzLabel="None"></nz-option>
                            <nz-option nzValue="asc" nzLabel="Ascending"></nz-option>
                            <nz-option nzValue="desc" nzLabel="Descending"></nz-option>
                        </nz-select>
                      </div>

                      <div class="mb-2">
                        <label for="op">Filter Column</label> <br>
                        <nz-select ngModel="contains" class="text-left mr-2" style="width:100%;">
                            <nz-option nzValue="contains" nzLabel="Contains"></nz-option>
                            <nz-option nzValue="like" nzLabel="Like"></nz-option>
                        </nz-select>
                      </div>
                      <button type="button" class="btn btn-warning w-100 mt-2" (click)="search()"><i class="fe fe-search"></i> Search</button>
                    </div>
                </nz-dropdown-menu>
                <!-- filter fields -->
</th>
```

**Note** If I use `[nzDropdownMenu]="menu"` and `#menu="nzDropdownMenu"` (as of documents) it will open all headers dropdown at the same time but since I've added index number to have unique ids it returns this error (mentioned above).

**any idea?**

**Comment by to0simple** [comment]
I think you're using the same variable（visible）

**Comment by robertnicjoo** [comment]
> I think you're using the same variable（visible）

Would you mind share with me what do you think i should do? I'm really stuck at this.

**Comment by to0simple** [comment]
> > I think you're using the same variable（visible）
> 
> Would you mind share with me what do you think i should do? I'm really stuck at this.
I think u can remove [(visible)] in the <nz-filter-trigger>

**Comment by to0simple** [comment]
> > I think you're using the same variable（visible）
> 
> Would you mind share with me what do you think i should do? I'm really stuck at this.

> I think u can remove [(nzVisible)] on the nz-filter-trigger

**Comment by robertnicjoo** [comment]
@to0simple I've already removed that it didn't work

**Comment by to0simple** [comment]
>> @to0simple I've already removed that it didn't work
>
>https://stackblitz.com/edit/angular-ecxh6j-wenfft?file=src%2Fapp%2Fapp.component.ts

**Comment by robertnicjoo** [comment]
@to0simple 

```javascript

<th *ngFor="let column of listOfColumns; let i = index;">
  {{ column.name }}
  <nz-filter-trigger [nzActive]="searchValue.length > 0" [nzDropdownMenu]="'menu' + i">
    <i nz-icon nzType="caret-down"></i>
  </nz-filter-trigger>
 
  <!-- filter fields -->
  <nz-dropdown-menu #menu{{i}}="nzDropdownMenu">
  ..... rest of it...
```

Also as your sample `<nz-dropdown-menu #menu{{i}}>` none of them work 😞  did I miss something from your sample?!

**Comment by to0simple** [comment]
> @to0simple
> 
> ```js
> <th *ngFor="let column of listOfColumns; let i = index;">
>   {{ column.name }}
>   <nz-filter-trigger [nzActive]="searchValue.length > 0" [nzDropdownMenu]="'menu' + i">
>     <i nz-icon nzType="caret-down"></i>
>   </nz-filter-trigger>
>  
>   
>   <nz-dropdown-menu #menu{{i}}="nzDropdownMenu">
>   ..... rest of it...
> ```
> 
> Also as your sample `<nz-dropdown-menu #menu{{i}}>` none of them work 😞 did I miss something from your sample?!

> ```js
> <th *ngFor="let column of listOfColumns; let i = index;">
>   {{ column.name }}
>   <nz-filter-trigger [nzActive]="searchValue.length > 0" [nzDropdownMenu]="menu">
>     <i nz-icon nzType="caret-down"></i>
>   </nz-filter-trigger>
>  
>   
>   <nz-dropdown-menu #menu="nzDropdownMenu">
>   ..... rest of it...
> ```
>  u can try this way . remove i

**Comment by robertnicjoo** [comment]
@to0simple Thanks man it worked eventually ❤️
