### ISSUE TITLE
How to change Top-Menu default class?

### ISSUE THREAD

**Issue by robertnicjoo** [NG-ZORRO/ng-zorro-antd#6116]
### Reproduction link
[Demo](https://stackblitz.com/edit/angular-jioek4?file=src/app/app.component.ts)

Demo screenshot

![234](https://user-images.githubusercontent.com/8672823/100576862-88f2b480-3311-11eb-9f28-60533a8efa0a.png)

### Steps to reproduce
I am trying to make mega menu after lots of debugging I ended up that changing default value of class `cdk-overlay-pane` will give me the result that I'm looking for, unfortunately for some reason that I'm not aware of changing that class default values from `menu-top-component.scss` will not take place and I had to place my code in `global.scss` in order to work.

![232](https://user-images.githubusercontent.com/8672823/100574624-ffd97e80-330c-11eb-8001-ac394f6e85c6.png)

### Issue
 
Changing `cdk-overlay-pane` values in `global.scss` will effect other parts such as dropdowns which is not in my interest.

### Question

1. How can I change that class values to only effect my `top-menu` style and not the rest of the app.
2. Alternatively is there any possible way to add extra class into my top menu div and place my style codes into `menu-top-component.scss`?

### What is expected?
Changing `cdk-overlay-pane` values without effecting rest of app.

### What is actually happening?
Either effect all component or not work at all!

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.2 |
| Browser | Firefox |

**Comment by stygian-desolator** [comment]
Hi~ 
Reproduction link is not accessible, could you pls update it?

**Comment by robertnicjoo** [comment]
@stygian-desolator Updated

**Comment by to0simple** [comment]
https://stackblitz.com/edit/angular-jioek4-m2ofz3?file=src%2Fapp%2Fapp.component.ts

u can try this way

**Comment by robertnicjoo** [comment]
@to0simple thanks man but the problem is with ficed pixels it won't be responsive in small screens. I need `rem` or `%` options

**Comment by robertnicjoo** [comment]
@to0simple  please check this:

My way:

![000100](https://user-images.githubusercontent.com/8672823/100586824-4eddde80-3322-11eb-97ef-aeeedac5a81f.png)

And your way:

![000200](https://user-images.githubusercontent.com/8672823/100586834-556c5600-3322-11eb-9945-3ae18321e178.png)

**Comment by stygian-desolator** [comment]
Maybe `nz-popover` is more suitable

**Comment by robertnicjoo** [comment]
> Maybe `nz-popover` is more suitable

What do you mean? For navbar using popover?!

**Comment by stygian-desolator** [comment]
> > Maybe `nz-popover` is more suitable
> 
> What do you mean? For navbar using popover?!

Since it is displaying complex content on `overlay`, `nz-popover` may be more suitable than `nz-sub-menu` in this scenario, or add a custom `class` by looking for ancestor elements.

**Comment by robertnicjoo** [comment]
@stygian-desolator Thanks man I've used popover its much more better than default classes, not what I was looking for exactly but good enough for now.
