### ISSUE TITLE
在nz-tag中，不能重复输入已删除的内容

### ISSUE THREAD

**Issue by Maple512** [NG-ZORRO/ng-zorro-antd#6117]
### Reproduction link
[https://codesandbox.io/s/lfroz?file=/src/main.ts](https://codesandbox.io/s/lfroz?file=/src/main.ts)

### Steps to reproduce
文档上的原例子，见https://ng.ant.design/components/tag/zh#components-tag-demo-control ，删除一个tag后，不能再次输入前面被删除tag的内容

### What is expected?
tag删除后，且其内容可以重复输入

### What is actually happening?
不能重复输入

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.2 |
| Browser | Google Chrome 版本 84.0.4147.89（正式版本） （64 位） |

---
或许时因为没有触发nzAfterClose导致，文档下方的api中，也没有这个事件了

**Comment by stygian-desolator** [comment]
use `nzOnClose ` instead, I would like to fix this doc error
