### ISSUE TITLE
表格穿梭框 tbody 中的 checkbox 没显示

### ISSUE THREAD

**Issue by xujz520** [NG-ZORRO/ng-zorro-antd#6130]
### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
https://ng.ant.design/components/transfer/zh#components-transfer-demo-table-transfer

### What is expected?
https://ng.ant.design/components/transfer/zh#components-transfer-demo-table-transfer

### What is actually happening?
https://ng.ant.design/components/transfer/zh#components-transfer-demo-table-transfer

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.0 |
| Browser | chrome 最新版 |

---
https://ng.ant.design/components/transfer/zh#components-transfer-demo-table-transfer

**Comment by yangjunhan** [comment]
Please double check your reproduction link. It is not a valid stackblitz demo link.

**Comment by xujz520** [comment]
> Please double check your reproduction link. It is not a valid stackblitz demo link.

https://ng.ant.design/components/transfer/zh#components-transfer-demo-table-transfer
---
看我
