### ISSUE TITLE
nz-date-picker and nz-range-picker updating disabled dates inconsistently

### ISSUE THREAD

**Issue by fbcarpinato** [NG-ZORRO/ng-zorro-antd#6131]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-hedkbm?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-hedkbm?file=src/app/app.component.ts)

### Steps to reproduce
Just open the date picker and see that the dates are not disabled until you change the month with the arrows

### What is expected?
I expect that the dates are disabled even when I open the date picker the first time

### What is actually happening?
the date picker is updating the disabled dates only once and then updating once again when you change months

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.0 |
| Browser | chrome |

**Comment by wenqi73** [comment]
```ts
ngOnInit() {
  setTimeout(() => {
    this.disabledDate = () => true;
  }, 3000);
}
```
Input is a function, so you need to change the function.
