### ISSUE TITLE
nz-menu使用递归的demo当[nzInlineCollapsed]="true"时，鼠标滑动至3级菜单后2级菜单消失

### ISSUE THREAD

**Issue by sfwjiao** [NG-ZORRO/ng-zorro-antd#6140]
### Reproduction link
[https://stackblitz.com/edit/angular-ok4uuv?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-ok4uuv?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
鼠标滑动至Mail Group -> Group 1 -> Option 1后，Group 1所在的二级菜单消失。

### What is expected?
期望与不使用递归时的效果相同，鼠标滑动至三级菜单上，二级菜单不消失。

### What is actually happening?
实际情况是使用了递归生成菜单后，鼠标滑动至三级菜单上，二级菜单消失。

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.0 |
| Browser | 谷歌 |

**Comment by vthinkxie** [comment]
递归生成菜单，需要手动指定 nzPaddingLeft，仅在 nzMode 为 inline 的模式，且 nzInlineCollapsed 为 false 的情况下有效。

https://ng.ant.design/components/menu/zh#components-menu-demo-recursive
