### ISSUE TITLE
时间选择器，时区问题

### ISSUE THREAD

**Issue by sht819175141** [NG-ZORRO/ng-zorro-antd#6147]
### Reproduction link
[https://stackblitz.com/angular/kgqqelvpmgx?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/angular/kgqqelvpmgx?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
写一个时间选择框，把电脑时间切换到非北京时区，最好时差大一点，我项目中遇到的问题是夏威夷时区，然后，数据库传过来一个时间

### What is expected?
期望就是数据库传什么，显示什么

### What is actually happening?
实际结果就是，数据库传了2020-11-03，选择器里显示了2020-11-02

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.0 |
| Browser | Edge |

---
没做过 stackblitz,不会弄，另外，我想了一下，我这个东西，轻易实现不了，我可以截图，但是，stackblitz我想不到怎么重现，所以，不用看stackblitz的链接，我随便粘贴的。版本是0.7版，我在下拉框里，没找到0.7，就随便选了一个

**Comment by wenqi73** [comment]
@sht819175141 new Date() 用 `yyyy-MM-dd` 有个时区问题：https://github.com/NG-ZORRO/ng-zorro-antd/issues/4361#issuecomment-551403003
