### ISSUE TITLE
table nzLeft style error

### ISSUE THREAD

**Issue by qf8505** [NG-ZORRO/ng-zorro-antd#6149]
### Reproduction link
[https://stackblitz.com/run?file=package.json](https://stackblitz.com/run?file=package.json)

### Steps to reproduce
nzLeft   样式被覆盖，，nzRight没有问题

### What is expected?
左右效果一样

### What is actually happening?
左侧效果错误

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.0 |
| Browser | chrome |

**Comment by yangjunhan** [comment]
Please double check your reproduction link, it does not seem to be a correct sharing url.
