### ISSUE TITLE
modal 对话框 if the user drags to nzMask and release the mouse the modal will close

### ISSUE THREAD

**Issue by tirelyl** [NG-ZORRO/ng-zorro-antd#615]
## What problem does this feature solve?

Our website often used modal to display form data. user want copy data from modal but often drag out of the viewport and release the mouse the modal  closes，caused information should be fill again.

## What does the proposed API look like?

I think modal components should be added a mouseup event, feel the mouse in the modal viewport, press the mouse out of the viewport release the mouse will shut down, in many scenes experience is not good enough.

**Comment by vthinkxie** [comment]
Will not support in the near future, you can reopen it after 0.7.0 released.
