### ISSUE TITLE
nz-Select开启搜索模式，(nzBlur)事件会在获取焦点时触发

### ISSUE THREAD

**Issue by cxyhgh999** [NG-ZORRO/ng-zorro-antd#6150]
### Reproduction link
[https://stackblitz.com/edit/angular-sfbggs?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-sfbggs?file=src/app/app.component.ts)

### Steps to reproduce
点击下拉框，会直接触发nzBlur事件的alert

### What is expected?
期望正常失去焦点时触发

### What is actually happening?
实际获取焦点时就已触发

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | 谷歌 |

**Comment by yangjunhan** [comment]
Your `ng-zorro-antd` version is `8.5.2`. Please upgrade to the latest version and this issue should be disappeared. For more information, you can check out this demo whose `ng-zorro-antd` version is `10.2.0`: https://stackblitz.com/edit/angular-wjpkag?file=package.json
