### ISSUE TITLE
穿梭框选择问题

### ISSUE THREAD

**Issue by wangyahua** [NG-ZORRO/ng-zorro-antd#6153]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-blod9y](https://stackblitz.com/edit/ng-zorro-antd-ivy-blod9y)

### Steps to reproduce
选择左边的复选框后不可以移动到右边，但是在此取消选择过的复选框后就可以移动到右边了。

### What is expected?
期望就是选择复选框后就能移动到右边。

### What is actually happening?
实际就是选择了不能移动到右边。

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.0 |
| Browser | Chrome |

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/transfer/zh#components-transfer-demo-tree-transfer
https://stackblitz.com/edit/angular-hkhzni?file=src/app/app.component.ts
官网有标准 demo 的，建议参考 demo
