### ISSUE TITLE
tabs show error when [nzSize]="'small'" [nzType]="'card'"

### ISSUE THREAD

**Issue by winds2016** [NG-ZORRO/ng-zorro-antd#616]
## Version

0.6.0

## Environment

firefox56 node7.7 win7

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.html)

## Steps to reproduce

set  [nzSize]="'small'" [nzType]="'card'"

## What is expected?

Selected tab header has no bottom line

## What is actually happening?

Selected tab header has bottom line

## Other?

 normal size has no error

**Comment by vthinkxie** [comment]
nzType = card does not support nzSize option by ant design

**Comment by winds2016** [comment]
can it support in future?

**Comment by vthinkxie** [comment]
@winds2016 you can check it after 0.7.0 released, if not supported then, please reopen this issue.

**Comment by winds2016** [comment]
ok thanks
