### ISSUE TITLE
tabs header can custom distance from tab context,if can ,how custom?

### ISSUE THREAD

**Issue by winds2016** [NG-ZORRO/ng-zorro-antd#617]
## What problem does this feature solve?

i want to custom distance from tab header to tab context,or add other three border line for tab context

## What does the proposed API look like?

add property to set other three border line ,and can custom padding(if can,add use method info to manual)

**Comment by vthinkxie** [comment]
you can custom all style with your class and css file

**Comment by winds2016** [comment]
`<nz-tabset [nzSize]="'small'" [nzType]="'card'" style="padding: 0.2em;">
  <nz-tab style="padding: 0.2em;">
    <ng-template #nzTabHeading>
      订单记录
    </ng-template>
    <div style="background-color: #eee;margin: 0;">订单信息</div>
  </nz-tab>
  <nz-tab style="padding: 0.2em;">
    <ng-template #nzTabHeading>
      工单记录
    </ng-template>
    工单信息
  </nz-tab>
</nz-tabset>`

it's not work?where is the error?

**Comment by vthinkxie** [comment]
@winds2016 please check the dom via devtools, there is no `nz-tab` in dom acutally

**Comment by winds2016** [comment]
done, thanks
