### ISSUE TITLE
Extra params in tooltipFormatter function

### ISSUE THREAD

**Issue by nicoayci** [NG-ZORRO/ng-zorro-antd#6188]
## What problem does this feature solve?
For now the tooltip formatter of the slider is basic. I would like to be able to pass extra params from my own component because the value of the generated tooltip string depends on those extra params.

## What does the proposed API look like?
The function passed could be (value: number, params?: {}) => string

**Comment by wendellhu95** [comment]
`nzTipFormatter` is called inside the slider handler component. I have no idea how we can pass `params` into that function. A more specfic example would be appreciated, code pieces even better.
