### ISSUE TITLE
文档中 Avatar 头像 的 何时使用 的描述有错误 , 与  Anchor 锚点 相同

### ISSUE THREAD

**Issue by wenner** [NG-ZORRO/ng-zorro-antd#619]
## Version

0.6.1

## Environment

任意

## Reproduction link

[https://ng.ant.design/#/components/avatar](https://ng.ant.design/#/components/avatar)

## Steps to reproduce

任意

## What is expected?

正确

## What is actually happening?

显示错误

**Comment by vthinkxie** [comment]
@cipchk

**Comment by cipchk** [comment]
confirmed
