### ISSUE TITLE
"deprecated: 'danger' value of 'nzType' in Button" after updating to v10.2.1

### ISSUE THREAD

**Issue by hedegitsinue** [NG-ZORRO/ng-zorro-antd#6191]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-pzsfrs?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-pzsfrs?file=src/app/app.component.ts)

### Steps to reproduce
* Install ng-zorro-antd@10.2.1
* Insert ```<button nz-button nzType="primary">...</button>``` in the template (Any value with `nzType` will give the same warning)

### What is expected?
It should not give any warnings

### What is actually happening?
It gives the warning in the console as

> [NG-ZORRO]: deprecated: 'danger' value of 'nzType' in Button is going to be removed in 12.0.0. Please use 'nzDanger' instead

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.1 |
| Browser | Chrome |

---
My guess is that it is caused by 
`type NzLegacyButtonType = 'primary' | 'default' | 'dashed' | 'danger' | 'link' | 'text' | null;` which contains `danger` value and triggers this warning.

I was not able to edit the file in `node_modules` after `npm` runs `postinstall` and therefore was not able to check if removing the `danger` value solves the issue.

**Comment by Airblader** [comment]
It seems that [this](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/button/button.component.ts#L138) should check the type being used rather than check for any nzType being set.
