### ISSUE TITLE
Nz-tree with CRUD of nodes

### ISSUE THREAD

**Issue by ibodzoda-001** [NG-ZORRO/ng-zorro-antd#6199]
## What problem does this feature solve?
Add possibility of adding new nodes and children nodes to nz-tree, so we can build an hierarchy of something. In m case i should create an hierarchy of country -> region -> city and etc., but i need to make custom adding with nz-tree, which takes a lot of time.

## What does the proposed API look like?
For adding main node you just add button "Add main node", by clicking this button you write a node title and add main node, when you add main node it will have plus, edit and delete buttons, so you can add, update and delete current node. When you click node plus button you can add children node to clicked node. So this way you can build any hierarchy.

**Comment by hsuanxyz** [comment]
will be included in the next release

![image](https://user-images.githubusercontent.com/22736418/102204996-8beec700-3f05-11eb-81d9-491e76f61a9e.png)

**Comment by ibodzoda-001** [comment]
What about deleting nodes?

**Comment by hsuanxyz** [comment]
https://preview-6161-ng-zorro-antd.surge.sh/components/tree-view/en#components-tree-view-demo-editable

You can customize the nodes

**Comment by ibodzoda-001** [comment]
Got it. Thanks!
