### ISSUE TITLE
nzAddOnBefore and nzAddOnAfter for InputNumber component

### ISSUE THREAD

**Issue by junekpavel** [NG-ZORRO/ng-zorro-antd#6215]
### Reproduction link
[https://codesandbox.io/s/intelligent-hill-q2y3n?file=/src/app/app.component.ts](https://codesandbox.io/s/intelligent-hill-q2y3n?file=/src/app/app.component.ts)

### Steps to reproduce
Use `nz-input-number` within `nz-input-group` with `nzAddOnBefore` or `nzAddOnAfter` set.

### What is expected?
The addons should be styled properly.

### What is actually happening?
Input border radius should be 0 and `nzAddOnAfter` is not connected to input at all.

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.2 |
| Browser | Chrome |

---
![issue demonstration](https://uc860201cd56a4a05adf1480933a.previews.dropboxusercontent.com/p/thumb/ABAJpZntiWrA8fcvC6x1YdNKx0A_LJ60mNUO3N5LGQjZHdFT3UBGZrQPghnmOPFhqzcqJqXg16Qf8qGIOMI5PGbqi5WSi060v_z_jmJyk0N9waRZxwtgCaPElgFNrgITDIJzIaclhN9hqKsSaMFD76ecUnWQ0NGsDtLs72ACqFFKLZ-VHsQazQbLg0a06GRb7d_4LssRutBrxmCRer258WLo0lozGe61ah5EWFKF1etc_wGQ5TeXHm2vE_7gbK-5umk4hIEgA3OOkAvuyxWv34-B4i5MUUtaLXxNMOste8243VPXQ2rJKSb56KeF3AKMFGaK_DF084uT3lz-yoNFK_auvmfKWeJZB6o9jQ3BjZ7i_-Nw67nD5V4e1BowejDvgtWQVs2_uaefzhUgRDUiU6LG/p.png?fv_content=true&size_mode=5)

**Comment by junekpavel** [comment]
Just found out that `NzSelect` component has exactly same issue.

**Comment by HyperLife1119** [comment]
Please use the newly designed input-number component in v19 :)
