### ISSUE TITLE
对nzTable封装后,排序和表格样式失效

### ISSUE THREAD

**Issue by LYSSION** [NG-ZORRO/ng-zorro-antd#6219]
### Reproduction link
[https://stackblitz.com/edit/angular-luhcme-fjjzjw?file=src/app/app.component.html](https://stackblitz.com/edit/angular-luhcme-fjjzjw?file=src/app/app.component.html)

### Steps to reproduce
点击下面表格排序无反应,点击上面表格的排序可正常响应

### What is expected?
下面表格正常显示样式,点击排序可正常排序

### What is actually happening?
下方表格的排序和表格样式失效

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.2 |
| Browser | Chrome  87.0.4280.88 |

**Comment by vthinkxie** [comment]
table 不支持封装后再暴露 td 与 th
可以参考 https://github.com/ng-alain/ng-alain 的封装方式
