### ISSUE TITLE
select组件，当设置选中的值为options中不存在的值时，组件仍显示之前选中的值

### ISSUE THREAD

**Issue by feixia5320** [NG-ZORRO/ng-zorro-antd#6248]
### Reproduction link
[https://stackblitz.com/edit/angular-bmegup?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-bmegup?file=src/app/app.component.ts)

### Steps to reproduce
监听click方法，改变ngmodel绑定的值，如果该值不在options中，则仍然显示选中之前值的状态，

### What is expected?
如果该值不在options中，应该显示为空

### What is actually happening?
仍然显示选中之前值的状态，

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.0 |
| Browser | 谷歌浏览器 87. |

**Comment by vthinkxie** [comment]
需要移除选中值请直接传入null，不在option的值不会做出响应
