### ISSUE TITLE
nz-image用不了,你们官网的demo也跑不起来

### ISSUE THREAD

**Issue by wude583380410** [NG-ZORRO/ng-zorro-antd#6259]
### Reproduction link
[https://1hoe5g--run.stackblitz.io](https://1hoe5g--run.stackblitz.io)

### Steps to reproduce
没有这个标签， nz-image没有起作用

### What is expected?
正常使用

### What is actually happening?
打不开，找不到标签

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.0 |
| Browser | Google Chrome |

**Comment by wude583380410** [comment]
https://1hoe5g--run.stackblitz.io

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/angular-ztkocn?file=src/app/ng-zorro-antd.module.ts

**Comment by vthinkxie** [comment]
@hsuanxyz stackbliz fork 的模板需要更新一下

**Comment by wude583380410** [comment]
import { NzImageModule } from 'ng-zorro-antd/image';
这个在文档中并未说明，https://ng.ant.design/components/image/zh
谢谢

**Comment by hsuanxyz** [comment]
@stygian-desolator
