### ISSUE TITLE
tabs路由联动打不开沙盒环境（tabs routerlink can't open in codesandbox or StackBlitz)

### ISSUE THREAD

**Issue by DBSDs** [NG-ZORRO/ng-zorro-antd#6267]
### Reproduction link
[https://szaz3x--run.stackblitz.io](https://szaz3x--run.stackblitz.io)

### Steps to reproduce
点击tabs组件进入沙盒环境

### What is expected?
正常运行

### What is actually happening?
加载失败Error in /turbo_modules/@angular/compiler@11.0.5/bundles/compiler.umd.js (2983:21)

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.0 |
| Browser | chrome |

---
路由联动可能还有问题，我在自己环境下循环渲染出来的组件，点击a才会跳转，点击a下方只改变样式并没有跳转路由

**Comment by hsuanxyz** [comment]
谢谢你的反馈，stackblitz / sandbox 的问题我们无法负责修复，a 标签点击区域的问题已被 https://github.com/NG-ZORRO/ng-zorro-antd/pull/6278 修复。
