### ISSUE TITLE
NzTable Data List Pagination Seriously Bug

### ISSUE THREAD

**Issue by emondora** [NG-ZORRO/ng-zorro-antd#6272]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-barbkh?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-barbkh?file=src/app/app.component.ts)

### Steps to reproduce
1. Set default pageSize 10 items;
2. Set data list more than 10 items(eg: 15 items);
3. Set default pageIndex = 2;
4. Change data list, set list empty = [] (0 items);
5. NzTable appears "empty" notice, and the old data list shows before "empty" notice.

### What is expected?
When set data list empty (0 items), NzTalbe should appears "empty" notice , do not show "old data list".

### What is actually happening?
NzTable appears "empty" notice, also the "old data list" shows before "empty" notice.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.0 |
| Browser | Chrome 87.0.4280.88 |

**Comment by ywager** [comment]
HI @vthinkxie , Since this error has a wide range of effects, can this patch be cherry picked to v10.2.2, or is there any way to solve it without relying on the component library workaround in v10.2.2?
