### ISSUE TITLE
PageHeader组件文档，表格内容错误

### ISSUE THREAD

**Issue by Hgwxxdd** [NG-ZORRO/ng-zorro-antd#6276]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/edit/master/components/page-header/doc/index.zh-CN.md](https://github.com/NG-ZORRO/ng-zorro-antd/edit/master/components/page-header/doc/index.zh-CN.md)

### Steps to reproduce
1. 访问链接 https://github.com/NG-ZORRO/ng-zorro-antd/edit/master/components/page-header/doc/index.zh-CN.md
2. 查看「 nz-page-header 」小节

### What is expected?
表格显示正常

### What is actually happening?
「 nz-page-header 」小节中的「 nzBack 」参数的文字说明多了一个括号

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.0 |
| Browser | chrome 88.0.4324.50 |

**Comment by lsbbd** [comment]
@Hgwxxdd fix in #6275
