### ISSUE TITLE
in nz-select component,   if the config `nzOptions`  label  set type `TemplateRef<any> ` , but it dose'nt work！

### ISSUE THREAD

**Issue by denggy** [NG-ZORRO/ng-zorro-antd#6282]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-tyjnjc](https://stackblitz.com/edit/ng-zorro-antd-ivy-tyjnjc)

### Steps to reproduce
https://stackblitz.com/edit/ng-zorro-antd-ivy-tyjnjc

### What is expected?
show label content

### What is actually happening?
nothing I can see

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.2 |
| Browser | chrome |

**Comment by stygian-desolator** [comment]
Hi~, set `{ static: true }` in `@ViewChild`, it may help you
demo: https://stackblitz.com/edit/ng-zorro-antd-ivy-9ssrtd

**Comment by vthinkxie** [comment]
@stygian-desolator is correct
