### ISSUE TITLE
In nz-date-picker, even after using nzFormat="dd-MMM-yyy" as given in the docs, the date-picker still sends the time.

### ISSUE THREAD

**Issue by dineshgupta630** [NG-ZORRO/ng-zorro-antd#6285]
### Reproduction link
[https://stackblitz.com/edit/angular-nbne35?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-nbne35?file=src/app/app.component.ts)

### Steps to reproduce
Use the latest version of nz-date-picker, in that, trying using the nzFormat="dd-MMM-yyy" as given in the documentation. 

While doing console.log(date), I get the datetime instead of just the date.

Let me know if I am doing something wrong, or this could be say a new feature if not supported? Thank you in advance.

### What is expected?
Just the date.

### What is actually happening?
Getting datetime instead of just date.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.0 |
| Browser | Chrome |

**Comment by C3maLi** [comment]
Hi, I don't think it's a mistake. 
Here's how I solve your question.

[https://stackblitz.com/edit/ng-zorro-datepicker-get-only-date?file=src/app/app.component.ts](url)

**Comment by wenqi73** [comment]
The datepicker always emits `Date` type to the user, you need to format it by yourself.
