### ISSUE TITLE
消息弹框消失时突然闪动一下

### ISSUE THREAD

**Issue by wangyanci** [NG-ZORRO/ng-zorro-antd#6296]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
点击任意弹出message的按钮

### What is expected?
消息弹框平滑消失

### What is actually happening?
偶现消息弹框消失瞬间回到原位闪动一下

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.0 |
| Browser | chrome |

---
偶现，概率还是较大的

**Comment by hsuanxyz** [comment]
@wangyanci 请提供有效的复现连接

**Comment by XuZhaoTong** [comment]
> @wangyanci 请提供有效的复现连接

https://stackblitz.com/edit/ng-zorro-antd-start-bbsrjf?file=src/app/app.component.ts
刷新3次差不多就会出现一次这种情况
