### ISSUE TITLE
递归生成的menu处于收起状态时，鼠标移动到多级菜单的最外级时，中间级消失

### ISSUE THREAD

**Issue by Ravenyjh** [NG-ZORRO/ng-zorro-antd#6306]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-3jqodk?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-3jqodk?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. 点击顶部按钮收起侧边栏
2. 鼠标悬浮Mail Group的icon
3. 此时出现第二级菜单，鼠标悬浮Group1
4. 此时出现第三级菜单，鼠标悬浮Option1

### What is expected?
第二级菜单依然存在

### What is actually happening?
第二级菜单消失

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.1 |
| Browser | chrome 81.0.4044.129 |

**Comment by Ravenyjh** [comment]
![image](https://user-images.githubusercontent.com/30866879/103458061-70761f80-4d3f-11eb-8ac2-112fe5ae2463.png)

**Comment by vthinkxie** [comment]
递归生成菜单，需要手动指定 nzPaddingLeft，仅在 nzMode 为 inline 的模式，且 nzInlineCollapsed 为 false 的情况下有效。
https://ng.ant.design/components/menu/zh#components-menu-demo-recursive
追踪 Issue：https://github.com/angular/angular/issues/14842

**Comment by DaoShu** [comment]
我也遇到这个问题了，和你描述的情况一模一样，但是官方给出的解释完全没用，就官网目前的递归写法，加一个收缩后，这个问题就出现了，为什么官方没解决还把问题关闭了。

**Comment by evilbdef** [comment]
> 我也遇到这个问题了，和你描述的情况一模一样，但是官方给出的解释完全没用，就官网目前的递归写法，加一个收缩后，这个问题就出现了，为什么官方没解决还把问题关闭了。

意思应该是说,  暂时只支持  inline  且 nzInlineCollapsed 为 false  的模式下使用,  不支持 vertical  模式递归菜单
