### ISSUE TITLE
table设置nzBordered当nzScroll属性未设置y值则单元格边框不显示问题

### ISSUE THREAD

**Issue by 232650413** [NG-ZORRO/ng-zorro-antd#6311]
### Reproduction link
[https://stackblitz.com/edit/angular-75fslh?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-75fslh?file=src/app/app.component.ts)

### Steps to reproduce
设置nzBordered与nzScroll{ x: "*px" }未设置y值时，单元格边框不显示问题；若设置y值，方才显示。

### What is expected?
仅nzScroll{ x: "*px" }时显示单元格边框

### What is actually happening?
仅nzScroll{ x: "*px" }时不显示单元格边框

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.1 |
| Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 |

---
问题由v10.x版本至今

**Comment by 232650413** [comment]
@vthinkxie

**Comment by vthinkxie** [comment]
this has been fixed in the latest version
https://stackblitz.com/edit/angular-75fslh-p42q7s?file=src/app/app.component.ts
