### ISSUE TITLE
table中的nzAlign在控制nzExpand列中无法使内容居中

### ISSUE THREAD

**Issue by DBSDs** [NG-ZORRO/ng-zorro-antd#6314]
### Reproduction link
[https://stackblitz.com/edit/angular-bzqx5o](https://stackblitz.com/edit/angular-bzqx5o)

### Steps to reproduce
在table中加入nzAlign='center'属性
nzExpand列内容没有居中

### What is expected?
nzExpand列内容居中

### What is actually happening?
nzExpand列内容没有居中

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.1 |
| Browser | chorme |

---
老项目用的版本，在8.5版本可以

**Comment by vthinkxie** [comment]
nzExpand 内容居左是预期行为，如果想改变样式可以通过修改css来实现
