### ISSUE TITLE
form表单中属性设置为disabled之后，value中没有这个值

### ISSUE THREAD

**Issue by douxingli** [NG-ZORRO/ng-zorro-antd#6315]
## What problem does this feature solve?
1、在接口传递数据时，不需要另外拼凑数据。
2、方便了新增和编辑时使用数据

## What does the proposed API look like?
form表单中属性设置为disabled之后，value中有这个值

**Comment by vthinkxie** [comment]
https://blog.kevinyang.net/2020/05/06/angular-formgroup-value/
