### ISSUE TITLE
可编辑表格Bug

### ISSUE THREAD

**Issue by qq67999427** [NG-ZORRO/ng-zorro-antd#632]
## What problem does this feature solve?

1.当表格里面的行是可编辑情况，即行里面的单元格为nz-input框，用代码增加一行并插入到首行。原来第一行的内容会被置为空。

## What does the proposed API look like?

1.当表格里面的行是可编辑情况，即行里面的单元格为nz-input框，用代码增加一行并插入到首行。原来第一行的内容会被置为空。

**Comment by vthinkxie** [comment]
it is just a demo, if you want to keep the state, just write your own strategy.
