### ISSUE TITLE
官网文档中 modal 自定义位置/垂直居中 demo 存在问题

### ISSUE THREAD

**Issue by lsbbd** [NG-ZORRO/ng-zorro-antd#6327]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/65944147b22767bfb3c3c7aec71c16d8ffaf6e76/components/modal/demo/position.ts#L41](https://github.com/NG-ZORRO/ng-zorro-antd/blob/65944147b22767bfb3c3c7aec71c16d8ffaf6e76/components/modal/demo/position.ts#L41)

### Steps to reproduce
1. 打开链接 http://localhost:62754/components/modal/zh#components-modal-demo-position
2. 点击 `Vertically centered modal dialog` 按钮
3. 缩小窗口宽度至 modal 溢出
4. 尝试滚动到 modal 顶部

### What is expected?
正常显示完整的 modal

### What is actually happening?
modal 顶部溢出部分被裁切，无法显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.1 |
| Browser | chrome 87.0.4280.141 |

---
可参考 (https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container)

**Comment by hsuanxyz** [comment]
@lsbbd Hi, I see that the React version added a `centered` property for Modal, and the implementation uses an other solution, would you like to submit this contribution for us? This means that instead of accepting #6328, we will be adding a new feature(`nzCentered`)

**Comment by lsbbd** [comment]
> @lsbbd Hi, I see that the React version added a `centered` property for Modal, and the implementation uses an other solution, would you like to submit this contribution for us? This means that instead of accepting #6328, we will be adding a new feature(`nzCentered`)

Okay, I will implement `nzCentered`
