### ISSUE TITLE
In nzpaginationmodule, if I set both [nzsimple] and [nzshowsizechanger], then [nzshowsizechanger] is invalid

### ISSUE THREAD

**Issue by MatchaCutie** [NG-ZORRO/ng-zorro-antd#6332]
### Reproduction link
[https://s6mn55--run.stackblitz.io](https://s6mn55--run.stackblitz.io)

### Steps to reproduce
In nzpaginationmodule, set both [nzsimple] and [nzshowsizechanger]

### What is expected?
In nzpaginationmodule, if I set [nzsimple] and [nzshowsizechanger] at the same time, [nzshowsizechanger] is still valid

### What is actually happening?
[nzshowsizechanger] is invalid

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.1 |
| Browser | google |

**Comment by vthinkxie** [comment]
Hi, it works as intended, thanks for your issue anyway
