### ISSUE TITLE
[招聘] 快来加入我们吧，推荐成功有大礼！🔥🔥🔥🔥🔥🔥

### ISSUE THREAD

**Issue by simplejason** [NG-ZORRO/ng-zorro-antd#6343]
> 推荐简历成功入职的同学也有 AirPods Pro 相送 ~

阿里云实时计算部是阿里巴巴大数据技术体系的核心团队，包括所有 Apache Flink 创始成员。以 Apache Flink 为核心打造的大数据实时计算平台，一方面在阿里集团内部提供全公司范围的实时数据服务，淘宝、天猫、高德、优酷、饿了么、钉钉等所有子公司的数据和算法业务都运行在该平台上；另一方面通过阿里云向外界提供实时计算云服务，服务全球中小企业。

**高级前端工程师/专家（P6-P7）**
与 NG-ZORRO 团队一起工作

岗位职责：

支持阿里巴巴实时计算产品多个业务线的前端开发，负责模块编写及相关架构设计
岗位要求：

熟练掌握前端技术（HTML+CSS+JS）
- 了解 Angular / React / Vue 中一种或多种，对其中一种或多种有较为深入的学习和项目经验
- 乐观、开朗、善于沟通，具有良好的学习能力、团队协作能力和产品 ownership，热衷技术，乐于接受挑战
- (优先项) 参与或创建开源项目或在开源社区活跃成员，对某个领域有较深的钻研
- (优先项) 有用户体验方面经验及大型项目经验

面向人群：3 - 5年工作经验同学

工作地址：杭州市余杭区向往街1122号欧美金融城(EFC)英国中心西楼T6-阿里巴巴

简历发送至：simplejason.coder@gmail.com

**Comment by ferqx** [comment]
能在线解决个BUG么，通过umd的形式导入ng-ant组件库，挂在icon这了，
![image](https://user-images.githubusercontent.com/23183225/109269665-c8b13580-7847-11eb-8de7-a81c5e16e061.png)
