### ISSUE TITLE
Can't bind to 'nzOptions' since it isn't a known property of 'nz-select'

### ISSUE THREAD

**Issue by f1nch** [NG-ZORRO/ng-zorro-antd#6345]
### Reproduction link
[https://stackblitz.com](https://stackblitz.com)

### Steps to reproduce
include nz-select with nzOptions attribute

### What is expected?
nz-select should work with nzOptions

### What is actually happening?
console error is thrown: Can't bind to 'nzOptions' since it isn't a known property of 'nz-select'.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | Chrome |

---
What version was the the nz-select Large amounts of data added?

**Comment by Martin367** [comment]
maybe you just need to import the module in a proper place like this:
`import { NzSelectModule } from 'ng-zorro-antd/select';`
