### ISSUE TITLE
nz-tree中nzData在8.x中将不再支持传递 NzTreeNode，改用NzTreeNodeOptions，请问isHalfChecked状态如果设置

### ISSUE THREAD

**Issue by mrlionline** [NG-ZORRO/ng-zorro-antd#6347]
## What problem does this feature solve?
节点是否半选中状态

## What does the proposed API look like?
像NzTreeNode一样支持isHalfChecked状态

**Comment by simplejason** [comment]
isHalfChecked由组件判断（子节点由部分选中），如果实在需要，在非受控模式下，可通过 `getTreeNodeByKey` 等方法操作
