### ISSUE TITLE
nz-tree组件设置了nzDraggable并且使用nzTreeTemplate时拖动的占位标志不显示

### ISSUE THREAD

**Issue by zhangjian4** [NG-ZORRO/ng-zorro-antd#6352]
### Reproduction link
[https://stackblitz.com/edit/angular-4hsavx?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-4hsavx?file=src/app/app.component.ts)

### Steps to reproduce
拖动任意一个节点

### What is expected?
显示拖动的占位标志，也就是nz-tree-drop-indicator
![image](https://user-images.githubusercontent.com/23302214/104983887-a3f7c000-5a48-11eb-9ac5-d37f3f2e74b0.png)

### What is actually happening?
没有显示占位标志
![image](https://user-images.githubusercontent.com/23302214/104983911-b2de7280-5a48-11eb-8c97-5addecd39e2a.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.0.2 |
| Browser | Chrome 87.0.4280.141 |

**Comment by simplejason** [comment]
`nz-tree-drop-indicator` was lost when customizing the node

**Comment by sun293529884** [comment]
@simplejason Is there any temporary solution  for us?

**Comment by zhangjian4** [comment]
@simplejason 大哥这东西有计划要改吗

**Comment by mehmet-erim** [comment]
@simplejason is there any progress?

**Comment by crystalYY** [comment]
https://stackblitz.com/edit/angular-32h29m   用的7的版本，在最外层的span标签加draggable后可以，我试了下必须是span标签

**Comment by churjan** [comment]
> https://stackblitz.com/edit/angular-32h29m 用的7的版本，在最外层的span标签加draggable后可以，我试了下必须是span标签
> 
> Https://stackblitz.com/edit/angular-32h29m’s version 7 works by adding a drawable span tag to the outermost span tag, and I tried that it had to be a span tag

现在新版有解决办法吗

**Comment by shaharkazaz** [comment]
@simplejason any workaround here?

**Comment by shaharkazaz** [comment]
@simplejason I am willing to open a PR that does the following:
1. The indicator will always show by default
2. Add a new input to hide the indicator

WDYT?

**Comment by Heymancn** [comment]
这个问题有解决吗

**Comment by shaharkazaz** [comment]
@Heymancn no

**Comment by buqiyuan** [comment]
一个最简单的做法是：
```angular
 <ng-template #nzTreeTemplate let-node let-origin="origin">
     <nz-tree-drop-indicator 
       *ngIf="node.component.showIndicator" 
       class="ant-tree-drop-indicator ng-star-inserted"
       style="bottom: -3px; left: 4px; right: 0px;"
     >
     </nz-tree-drop-indicator>
 </ng-template>
```

**Comment by crystalYY** [comment]
您好，您的邮件我已收到，会尽快回复！樊

**Comment by HyperLife1119** [comment]
Close via #7579.

**Comment by crystalYY** [comment]
您好，您的邮件我已收到，会尽快回复！樊
