### ISSUE TITLE
Custom request parameters in nzUpload

### ISSUE THREAD

**Issue by dbvcode** [NG-ZORRO/ng-zorro-antd#6375]
## What problem does this feature solve?
I try to upload to an unsigned preset in Cloudinary with nzUpload.
The problem is I need to send the `upload_preset` as the request payload and I cannot send it as a header.
Seems it's impossible to do it directly and I require a `nzCustomRequest` which is overkill and also have no example code for it.

## What does the proposed API look like?
Please show some example code for `nzCustomRequest` or please allow a way to pass request payload.

**Comment by wxpxzdj** [comment]
![image](https://user-images.githubusercontent.com/7706151/105793164-99e33d80-5fc3-11eb-8786-4ea2c2e936fc.png)
https://stackblitz.com/edit/angular-xdqdlw-rpbw87?file=src/app/app.component.ts

**Comment by dbvcode** [comment]
Thanks. For some reason it was confusing for me in the docs, [https://ng.ant.design/components/upload/en#nz-upload](https://ng.ant.design/components/upload/en#nz-upload) as I expected to create a function to do this and had no idea how.
