### ISSUE TITLE
希望能够添加upload组件

### ISSUE THREAD

**Issue by m17319325007** [NG-ZORRO/ng-zorro-antd#638]
## What problem does this feature solve?

文件上传和照片上传File upload and photo upload

## What does the proposed API look like?

To select photos / documents immediately upload and select photos / documents click upload and select callback, select Delete after the callback, the callback, upload success callback, upload failed callback, if upload pictures can limit the upload, upload files in the upload size limit, if you upload photos can preview function, can display the default upload photos. Can limit the maximum number of upload, cancel the upload, upload files can be set.

**Comment by dusdong** [comment]
我看[pull](https://github.com/NG-ZORRO/ng-zorro-antd/pull/370)快完成了，近期能发版吗？着急用，非常感谢！

**Comment by vthinkxie** [comment]
@dusdong there are still many bugs in the pull, I am afraid it will not be released before version 0.7.0

**Comment by dusdong** [comment]
ok, think you!

**Comment by vthinkxie** [comment]
is released in version 0.6.11 closed now
