### ISSUE TITLE
Drawer抽屉嵌套组件（内含抽屉）多重打开第一层会遮挡最后打开的抽屉弹层

### ISSUE THREAD

**Issue by 232650413** [NG-ZORRO/ng-zorro-antd#6381]
### Reproduction link
[https://stackblitz.com/edit/angular-giqmv2?file=src/app/child/child.html](https://stackblitz.com/edit/angular-giqmv2?file=src/app/child/child.html)

### Steps to reproduce
当前模块组件中打开抽屉（Drawer），其内容调用另一个模块组件，此模块组件也含有抽屉Drawer，打开这个抽屉会被第一次打开的抽屉所遮挡。需要在“第一模块”中设置抽屉nzZIndex ，如：999，方可。

### What is expected?
默认无需设置nzZIndex。

### What is actually happening?
当前层级问题，只能设置nzZIndex处理。

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.1.0 |
| Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 |

---
原9.3版本是不用设置（升级后出现这个问题）。

**Comment by chongqiangchen** [comment]
此BUG我理解应该是因为使用`<ng-container  *nzDrawerContent></ng-container>`插入内容的方案造成的问题，如果直接使用`<ng-content></ng-content>`[方案](https://stackblitz.com/edit/angular-giqmv2-mrc5qf?file=src/app/app.component.ts)不会出现层级问题。

有个额外的问题：[6085](https://github.com/NG-ZORRO/ng-zorro-antd/pull/6085) 中提到：
> Usage <ng-content></ng-content> is deprecated, use <ng-template nzDrawerContent></ng-template> to declare the contents of the drawer.

为何这么说?

**Comment by 232650413** [comment]
11.2版本还没修复...多drawer需定义层级。

**Comment by 232650413** [comment]
@hsuanxyz

**Comment by 232650413** [comment]
还有，若路由变更，跳转别的页面，上个页面的抽屉无法自动关闭，再点击也无法关闭。
下拉select菜单的悬浮菜单之类也一样

**Comment by Xie-Jay** [comment]
> 还有，若路由变更，跳转别的页面，上个页面的抽屉无法自动关闭，再点击也无法关闭。
> 下拉select菜单的悬浮菜单之类也一样，不太好demo，不知道大家又遇到没？咋处理的

可以试试创建一个服务存储抽屉这种组件的实例，监听相应路由事件调用实例的close方法

**Comment by 232650413** [comment]
> 抽屉

那样貌似麻烦了
