### ISSUE TITLE
Conflicts with other components, causing the page to jam

### ISSUE THREAD

**Issue by huanghuadong527** [NG-ZORRO/ng-zorro-antd#6389]
ng-zorro-antd     10.1.2
angular-gridster2     11.0.0
When a page uses a table or tab component, it conflicts with angular-gridster2, causing the page to get stuck

**Comment by huanghuadong527** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-bcyffn
I did an example that didn't cause the page to jam, but when I imported ng-zorro-antd and angular-gridster2 locally with the newly created ng11.0.0 project, it still stuck
![image](https://user-images.githubusercontent.com/22953694/106093561-73f89d00-616b-11eb-942e-ed74c248883f.png)

**Comment by vthinkxie** [comment]
Hi @huanghuadong527 
the stackblitz is the same as your local env
you can also download the stackblitz project and run on your local side.

**Comment by huanghuadong527** [comment]
Thank you @vthinkxie 
This is a strange phenomenon. Could you tell me how to check this overflow problem
