### ISSUE TITLE
希望添加 Input和Button的组合组件

### ISSUE THREAD

**Issue by canaanjin** [NG-ZORRO/ng-zorro-antd#639]
## What problem does this feature solve?

我试了在nz-input中添加button组件 出现了样式的错误

感觉这种功能还是有需求的吧

就像bootstrap中的一样
http://v3.bootcss.com/components/#input-groups-buttons-multiple

## What does the proposed API look like?

        <nz-input>
            <ng-template #addOnAfter>
                <button nz-button [nzType]="'primary'">
                    <span>Primary</span>
                  </button>
            </ng-template>
        </nz-input>

**Comment by vthinkxie** [comment]
this feat will be added when sync with ant design 3.0

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed
