### ISSUE TITLE
nz-table 子表格内容不能随父级表格的横向滚动条一起移动！

### ISSUE THREAD

**Issue by ycpaladin** [NG-ZORRO/ng-zorro-antd#6390]
### Reproduction link
[https://angular-fhldun.stackblitz.io](https://angular-fhldun.stackblitz.io)

### Steps to reproduce
1. 将浏览器窗口适当调小，直到表格出现横向滚动条；
2.展开第一条数据；
3.向右拖动横向滚动条；

### What is expected?
子表格中的内容能够跟随滚动条一起移动

### What is actually happening?
实际上并没有，子表格似乎被固定在当前的位置。

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.1.0 |
| Browser | Microsoft Edge v88 |

---
ng-zorro-antd v8.5.2 没有这个问题！  查看地址： https://angular-zfl5b1.stackblitz.io

**Comment by vthinkxie** [comment]
按照 ant design 4.0 设计规范，子表格内容不跟随横向滚动条滚动
