### ISSUE TITLE
nz-carousel没法默认初始index展示

### ISSUE THREAD

**Issue by AlicePrincess** [NG-ZORRO/ng-zorro-antd#6398]
## What problem does this feature solve?
比如我现在有一个轮播空间，旁边有一排缩略图，我需要点击缩略图打来轮播图并且定位到缩略图当前的位置

## What does the proposed API look like?
增加轮播图index的双向绑定

**Comment by ElderJames** [comment]
有 `goTo(index: number)` 方法。

**Comment by wendellhu95** [comment]
建议使用 goTo 方法，设置初始 index 这个 API 会导致 carousel 组件模糊了受控组件和非受控组件的边界，造成用户理解的困难。我们可能暂时不会考虑添加这样的 API。
