### ISSUE TITLE
When nz-input componet is [nzAutosize]="true", It is not working!

### ISSUE THREAD

**Issue by K1IRVING** [NG-ZORRO/ng-zorro-antd#6403]
### Reproduction link
[https://stackblitz.com/edit/angular-dftbsv-pmve3a?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-dftbsv-pmve3a?file=src/app/app.component.ts)

### Steps to reproduce
https://stackblitz.com/edit/angular-dftbsv-pmve3a?file=src/app/app.component.ts

### What is expected?
Textarea height autosize

### What is actually happening?
Textarea height autosize is not work

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Google Chrome 88.0.4324.96 |

**Comment by YuriyLitvin** [comment]
I also want to add that the Undo command (Ctrl + Z) does not work when [nzAutosize] is used.
