### ISSUE TITLE
HttpClientModule 替换 HttpModule

### ISSUE THREAD

**Issue by zimv** [NG-ZORRO/ng-zorro-antd#641]
官方文档上快速上手 替换app.module的文档上使用的还是HttpModule。我看官方已经希望用@angular/common/http 包替代原有http包了，这个也不算bug，但又不知道用什么方式联系你们更好。就这里说下吧，你们立刻关掉就行了。

**Comment by vthinkxie** [comment]
@zimv will be fixed in next version, thanks for your feedback.

**Comment by zimv** [comment]
@vthinkxie you are welcome
