### ISSUE TITLE
服务端渲染报错

### ISSUE THREAD

**Issue by UvDream** [NG-ZORRO/ng-zorro-antd#6411]
### Steps to reproduce
服务端渲染会报错,项目里面没有使用ng-zorro的icon

### What is expected?
希望服务端渲染不报错

### What is actually happening?
ERROR Error: [@ant-design/icons-angular]:the icon user-o does not exist or is not registered.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.1.0 |
| Browser | 谷歌最新版 |

---
ERROR Error: [@ant-design/icons-angular]:the icon user-o does not exist or is not registered.

**Comment by vthinkxie** [comment]
项目里面没有使用ng-zorro的icon
程序是不会骗人的，建议仔细检查代码

**Comment by UvDream** [comment]
呵呵，程序的确不会骗人，其中有个作者告诉我是内部依赖，那你告诉我是我用了还是框架用了呢，还要我把所有代码给你这位作者看看不
