### ISSUE TITLE
[NzTag] The main class .ant-tag is not added

### ISSUE THREAD

**Issue by fabiodursoexin** [NG-ZORRO/ng-zorro-antd#6420]
### Reproduction link
[https://stackblitz.com/edit/angular-znvpnn?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-znvpnn?file=src/app/app.component.ts)

### Steps to reproduce
When using <nz-tag> the .ant-tag class is not dynamically added.

### What is expected?
Move the addition of the .ant-tag class to the component host. For example:
```
host: {
   '[class.ant-tag]': 'true'
   .....
}
```

### What is actually happening?
The .ant-tag class is currently being added in the component constructor and is not being added correctly.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.1.0 |
| Browser | Chrome |

**Comment by edgarelc** [comment]
Same issue here. The HTML classes are basically stripped out when building using the flag --prod or even using --aot --build-optimizer
