### ISSUE TITLE
groupLabel in nz-select

### ISSUE THREAD

**Issue by egalley** [NG-ZORRO/ng-zorro-antd#6432]
### Reproduction link
[https://stackblitz.com/edit/angular-3ea78b?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-3ea78b?file=src/app/app.component.ts)

### Steps to reproduce
Add a new item in listOfGroupOption with a same groupLabel than the first group label

### What is expected?
Display the value under the same groupLabel or show the groupLabel

### What is actually happening?
groupLabel is missing

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.1.0 |
| Browser | Edge 88.0.705.68 |

**Comment by rodro75** [comment]
Hello guys.

It looks like you need to order the options by groupLabel or they would show up under the wrong group.
Here is a fork of the original repro that clarifies the issue.

https://stackblitz.com/edit/angular-3ea78b-pljmqf?file=src/app/app.component.ts

I hope this helps.

-Rodro-

**Comment by egalley** [comment]
Sorting data like mentioned by Rodro is the solution.
