### ISSUE TITLE
nz-form-item 标签中有两个nz-form-control时，当其中一个校验发生会同时触发另一个nzValidateStatus

### ISSUE THREAD

**Issue by W-Abel-jia** [NG-ZORRO/ng-zorro-antd#6439]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-8hacfn?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-8hacfn?file=src/app/app.component.ts)

### Steps to reproduce
在一个 nz-form-item  标签中有两个  nz-form-control  时,即如下：

模版文件：
```html
<form nz-form [formGroup]="validateForm" (ngSubmit)="submitForm(validateForm.value)">
  <nz-form-item>
    <nz-form-label [nzSpan]="7" nzRequired>Username</nz-form-label>
    <nz-form-control [nzSpan]="12" nzHasFeedback [nzErrorTip]="userErrorTpl">
      <input nz-input formControlName="userName" placeholder="please placeholder" />
      <ng-template #userErrorTpl let-control>
        <ng-container *ngIf="control.hasError('required')">
          Please input your username!
        </ng-container>
      </ng-template>
    </nz-form-control>
    <nz-form-label [nzSpan]="7" nzRequired>E-mail</nz-form-label>
    <nz-form-control [nzSpan]="12" nzHasFeedback [nzErrorTip]="emailErrorTpl">
      <input nz-input formControlName="email" placeholder="email" type="email" />
      <ng-template #emailErrorTpl let-control>
        <ng-container *ngIf="control.hasError('email')">
          The input is not valid E-mail!
        </ng-container>
        <ng-container *ngIf="control.hasError('required')">
          Please input your E-mail!
        </ng-container>
      </ng-template>
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-control [nzOffset]="7" [nzSpan]="12">
      <button nz-button nzType="primary" [disabled]="!validateForm.valid">Submit</button>
    </nz-form-control>
  </nz-form-item>
</form>

```

类文件：
```ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.less']
})
export class WelcomeComponent implements OnInit {
  validateForm: FormGroup;

  constructor(private fb: FormBuilder) {
    this.validateForm = this.fb.group({
      userName: ['', [Validators.required]],
      email: ['', [Validators.email, Validators.required]],
    });
  }

  ngOnInit() {
  }

  submitForm(value: { userName: string; email: string; }): void {
    console.log(value);
  }

}

```

在页面上, userName 触发了required 错误的时候，email也会触发 nzValidateStatus 为 error;
当 userName 控件输入了正确的值以后，在email 输入不正确的值时，userName 也会触发 nzValidateStatus为 error;

这里必须要将这两个控件分别单独放在一个nz-form-item中就不会出现此问题。

### What is expected?
userName 和 email  分别触发对应的```nzValidateStatus```

### What is actually happening?
userName 和 email  相会触发对方的```nzValidateStatus```

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.1.0 |
| Browser | 87.0.4280.88 |

**Comment by myopenresources** [comment]
https://github.com/myopenresources/cc-project 这个是用zorro开发的项目，需要的自己下

**Comment by danranVm** [comment]
`nz-form-item` 的 `status` 是由它的子组件 `nz-form-control` 控制的，因此一个 `nz-form-item ` 中确实只应该有一个 `nz-form-control` 组件.

如果你需要一行内多个表单元素：
- 可以考虑使用 `inline` 布局，参考：https://ng.ant.design/components/form/zh#components-form-demo-horizontal-login
- 或者也可以如果栅格组件，参考：https://ng.ant.design/components/form/zh#components-form-demo-advanced-search

**Comment by W-Abel-jia** [comment]
> `nz-form-item`的`status`是由它的子组件`nz-form-control`控制的，因此一个`nz-form-item `中确实只应该有一个`nz-form-control`组件。
> 
> 如果你需要一行内多个表单元素：
> 
> * 可以考虑使用`inline`布局，参考：[https](https://ng.ant.design/components/form/zh#components-form-demo-horizontal-login) ://ng.ant.design/components/form/zh#components-form-demo-horizo​​ntal-login[](https://ng.ant.design/components/form/zh#components-form-demo-horizontal-login)
> * 或者也可以如果上方组件，参考：[https](https://ng.ant.design/components/form/zh#components-form-demo-advanced-search) ://ng.ant.design/components/form/zh#components-form-demo-advanced-search[](https://ng.ant.design/components/form/zh#components-form-demo-advanced-search)

明白了，谢谢～
