### ISSUE TITLE
NzDrawerService does't close drawer when changing navigation

### ISSUE THREAD

**Issue by IonelLupu** [NG-ZORRO/ng-zorro-antd#6451]
### Reproduction link
[https://stackblitz.com/edit/angular-bagdwn](https://stackblitz.com/edit/angular-bagdwn)

### Steps to reproduce
Use the NzDrawerService to create a new drawer with a link inside the drawer. Click that link and observe that the drawer won't close. As per docs, the `nzCloseOnNavigation` property is set to `true`. Even setting it manually doesn't work.
  
This does not happen when you open a drawer using the `<nz-drawer>` component in HTML.

```ts
@Component({
  selector: "nz-demo-drawer-service",
  template: `
    <ng-template #drawerTemplate>
      <a [routerLink]="['test']">Go to Test</a>
    </ng-template>
    <button nz-button nzType="primary" (click)="isVisible = true">
      Use Drawer HTML component
    </button>
    <p></p>

    <button nz-button nzType="primary" nzDanger (click)="openTemplate()">
      Use Drawer service
    </button>

    <nz-drawer [nzVisible]="isVisible">
      <ng-container *nzDrawerContent>
        <a [routerLink]="['test']">Go to Test</a>
      </ng-container>
    </nz-drawer>
  `
})
export class NzDemoDrawerServiceComponent {
  @ViewChild("drawerTemplate") drawerTemplate?: TemplateRef<any>;

  isVisible = false;

  constructor(private drawerService: NzDrawerService) {}

  openTemplate(): void {
    this.drawerService.create({
      nzContent: this.drawerTemplate
    });
  }
}
```

### What is expected?
It is expected the drawer to close on navigation change, just like when the `<nz-drawer>` component is used

### What is actually happening?
The drawer does not close

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.1.0 |
| Browser | * |

**Comment by hsuanxyz** [comment]
@IonelLupu  We used CDK Overlay to implement the feature, which only works when history is forward or backward, and is not based on the ng router, we will improve its document. For now, the best way is to manually listen for ng router and call the close.

**Comment by IonelLupu** [comment]
thank you @hsuanxyz for the info. 

I've checked the commit you've made for the docs. I guess we can add more details to it:

---

| `[nzCloseOnNavigation]` | Whether to close the drawer when the user goes backwards/forwards in history. This works only for the `<nz-drawer>` component.  When creating a drawer using the NzDrawerService, setting `nzCloseOnNavigation` to true won't close the navigation due to how the CDK Overlay package works (unless the user is using the HashLocationStrategy). | `boolean` | `true` | ✅ |

---

PS. By the way, is there a way to create the drawer in the current component and not on the body of the page? Like, setting the parent(which is defaulted to <`body>` or something I guess) to a custom element?

Maybe we can do something like:
```ts
    constructor(private hostElement: ElementRef) {
      console.log(this.elRef.nativeElement);
    }
    this.drawerService.create({
      nzContent: this.drawerTemplate,
      parent: this.hostElement
    });
```

But I guess we need to talk with the CDK Overlay team to be able to do this :(
