### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts #6455

### ISSUE THREAD

**Issue by wojtek1150** [NG-ZORRO/ng-zorro-antd#6456]
### Steps to reproduce
When starting application or build with for production there are few warnings that appears after update from v10 to v11

### What is expected?
No warnings of course :P

### What is actually happening?
```
Warning: /node_modules/ng-zorro-antd/__ivy_ngcc__/fesm2015/ng-zorro-antd-i18n.js depends on 'date-fns/getISOWeek'.
Warning: /node_modules/ng-zorro-antd/__ivy_ngcc__/fesm2015/ng-zorro-antd-i18n.js depends on 'date-fns/format'. 
Warning: /node_modules/ng-zorro-antd/__ivy_ngcc__/fesm2015/ng-zorro-antd-i18n.js depends on 'date-fns/parse'. 
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.1.0 |
| angular | 11.2.3 |
| Browser | Chrome (but not important) |

---
I know that I can use **allowedCommonJsDependencies** but it's workaround not resolver ;) Also it doesn't exists in v10

**Comment by wenqi73** [comment]
Fixed by #6524.
