### ISSUE TITLE
support date range picker

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#646]
## What problem does this feature solve?

support date range picker in date-picker component

## What does the proposed API look like?

https://ant.design/components/date-picker-cn/

**Comment by dusdong** [comment]
问下，这个组件什么时候能够完成？捉急用啊，呵呵

**Comment by vthinkxie** [comment]
@HsuanXyz

**Comment by HsuanXyz** [comment]
@dusdong 功能已经全部完成了，在斟酌一下命名就能进行 code review， 顺利的话下版本就能发布。
