### ISSUE TITLE
nz-select: Custom Title for Option Items

### ISSUE THREAD

**Issue by sofiaps** [NG-ZORRO/ng-zorro-antd#6462]
Is there a way to set a custom title for the options of nz-select, or to hide the title alltogether?

**Comment by faizanu94** [comment]
Have you tried the `[nzPlaceHolder]` attribute on nz-select? Read out [here](https://ng.ant.design/components/select/en#nz-select) for its documentation

**Comment by sofiaps** [comment]
Hello @faizanu94 and thanks for your answer! The nzPlaceholder is not what we need unfortunately. I've used one of the given examples of nz-select to depict with a screenshot the title attribute we'd need to customize:
![image](https://user-images.githubusercontent.com/31549943/109472911-02b24f80-7a73-11eb-8009-d79d4adfec22.png)

**Comment by ousc** [comment]
https://stackblitz.com/edit/angular-ztk7dh?file=src/app/app.component.ts

**Comment by sofiaps** [comment]
Hi @ousc and thanks for the suggestion! I have already used this work-around, but the thing with it is that we need to add several css rules, since the title in the padding left and right of the options still remains the initial one. At any case, I have worked with what I have for the time, but I still think that the options' title should be customizable.

**Comment by zhengsansan** [comment]
would you share with me how do you resolve this problem what about modify the default title.
