### ISSUE TITLE
用nz-input会与表单状态touched等字段冲突，这些字段无效果

### ISSUE THREAD

**Issue by yuelinghunyu** [NG-ZORRO/ng-zorro-antd#65]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
please provide steps to reproduce, thanks

**Comment by vthinkxie** [comment]
duplicated #117
