### ISSUE TITLE
Calendar can touch off onClickDay event when click day panel(only when click day number can touch off the event now)

### ISSUE THREAD

**Issue by winds2016** [NG-ZORRO/ng-zorro-antd#650]
## What problem does this feature solve?

Calendar can touch off onClickDay event when click day panel,customer is used to click whole day panel,not the day number only

## What does the proposed API look like?

Calendar can touch off onClickDay event when click whole day panel

**Comment by vthinkxie** [comment]
it is easy to achieve the goal with dateCell template
