### ISSUE TITLE
datapicker nzDisabledDate需要点击后才更新限制，在测试看来是个错误

### ISSUE THREAD

**Issue by jinxiangqiang** [NG-ZORRO/ng-zorro-antd#6500]
### Reproduction link
[https://stackblitz.com/edit/angular-wufagu?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-wufagu?file=src/app/app.component.ts)

### Steps to reproduce
nzDisabledDate示例点击开始时间后，展开结束不更新，点击后才禁用了日期

### What is expected?
展开即禁用日期

### What is actually happening?
展开未禁用日期，点击后才更新禁用日期

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.2.0 |
| Browser | Chrome |

**Comment by wrivas96** [comment]
hello!, is there any updates regarding to this bug?

**Comment by syn6UK** [comment]
Not sure if this is the same error I'm having, but the nzDisabledDate function only runs on component load/mount and once you have selected a date in that datepicker. It should be running on click to expand the calendar.

I'm trying to prevent users from selecting a date that is earlier than a previous date, i don't want to use range as I want separate fields as rangepicker isn't mobile friendly. (I am not using ng-zorro mobile alongside ng-zorro desktop).

If this is the same issue, when will it be fixed please?

**Comment by syn6UK** [comment]
Hello is there any update to this? It seems everyone ignore any issues on here I post. Issues that are fundamental issues with components that make them unusable on production projects. Please can someone just advise when it will be fixed. I will pay for a fix just please fix it!

**Comment by wenqi73** [comment]
@syn6UK We will fix it soon, the temporary solution is to reassign the `nzDisabledate` when you changed the date.

**Comment by wenqi73** [comment]
Fixed in 11.4.2

**Comment by Tina-Li121220** [comment]
I have the same issue. I am using angular V9 and zorro ant V8, any way to fix  the nzDisableDate issue?
