### ISSUE TITLE
[nz-code-editor] Configure MonacoEnvironment before (first) load

### ISSUE THREAD

**Issue by Airblader** [NG-ZORRO/ng-zorro-antd#6502]
## What problem does this feature solve?
Since monaco-editor 0.22.0¹, the global `monaco` object is only defined if you add

```
window.MonacoEnvironment = { globalAPI: true };
```

It would be nice if ng-zorro had some hook to configure `MonacoEnvironment` (also for potential other use-cases) before monaco-editor is actually loaded. Also, the documentation for `onLoad` is now slightly incorrect/incomplete:

> The hook invoked when the resource of monaco editor is loaded. At this moment and afterwards the global variable monaco is usable

¹ https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md

## What does the proposed API look like?
Extend `NzConfig#codeEditor` with either an object or a function to modify `MonacoEnvironment`.

**Comment by thekhegay** [comment]
@hullis @simplejason 

`"ng-zorro-antd": "^13.2.0",`

```
Error: node_modules/ng-zorro-antd/core/config/config.d.ts:9:29 - error TS2307: Cannot find module 'monaco-editor' or its corresponding type declarations.

import { Environment } from 'monaco-editor';

**Comment by anthoniriv** [comment]
> @hullis @simplejason 
> 
> 
> 
> `"ng-zorro-antd": "^13.2.0",`
> 
> 
> 
> ```
> 
> Error: node_modules/ng-zorro-antd/core/config/config.d.ts:9:29 - error TS2307: Cannot find module 'monaco-editor' or its corresponding type declarations.
> 
> 
> 
> import { Environment } from 'monaco-editor';
> 
> 

Did you fix it? Same problem here

**Comment by hullis** [comment]
> 

Hi @thekhegay. Have you installed the monaco-editor package? ng-zorro-antd does not list monaco-editor as a dependency for a reason.

**Comment by anthoniriv** [comment]
I had to install monaco-editor to solve the problem idk why. I don't use it

**Comment by hullis** [comment]
> I had to install monaco-editor to solve the problem idk why. I don't use it

For sorry that. The problem is on out side. We will fix it soon.

**Comment by hullis** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/99f4141826489f81e78d27e1bcb754726dee29d5/components/core/config/config.ts#L11 

@yangjunhan Should not import type declaration here. Forcing all users to install monaco editor.

**Comment by thekhegay** [comment]
@hullis any updates?

**Comment by hullis** [comment]
> @hullis any updates?

This problem should have been fixed in our recent release.
