### ISSUE TITLE
ERROR Error: listOfSelectedValue.filter is not a function - nz-select

### ISSUE THREAD

**Issue by kaname-png** [NG-ZORRO/ng-zorro-antd#6516]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-kd3h3h](https://stackblitz.com/edit/ng-zorro-antd-ivy-kd3h3h)

### Steps to reproduce
I am trying to do a for loop of the elements of the channel array (I put one as an example because the array is very long) in the select options, but I get this error and I don't know what to do.

### What is expected?
View the elements of the for cycle to select options

### What is actually happening?
I get an error in the console and it does not show any element.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.1.0 |
| Browser | Microsoft Edge Chromium Version 89.0.774.50 |

Note: I do not need to select any default items as I want the user to select the channels optionally.

**Comment by Airblader** [comment]
This is a problem with how you're using FormBuilder.

Change

```
channels: [""]
```

to either

```
channels: [[]]
```

or

```
channels: this.formBuilder.control([])
```

**Comment by kaname-png** [comment]
works properly, thanks.

**Comment by sjregistered** [comment]
Thank You so much brother.

**Comment by dearmarko** [comment]
> 

god job ! thank you bro

**Comment by Pursuemc** [comment]
thank you bro

**Comment by bsayat** [comment]
@Airblader it works! thx
