### ISSUE TITLE
datepicker : can't manually write date when setting format 'dd/MM/yyyy'

### ISSUE THREAD

**Issue by wiwilol** [NG-ZORRO/ng-zorro-antd#6518]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-jb4sww?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-jb4sww?file=src/app/app.component.ts)

### Steps to reproduce
Just click on date picker input, type "15/03/2021" and press enter

### What is expected?
It should recognise and use given date

### What is actually happening?
nothing happens when press enter button

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.2.0 |
| Browser | Chrome |

---
it work when using default format, but not with this format 'dd/MM/yyyy'

**Comment by wenqi73** [comment]
Please import `date-fns`, see https://ng.ant.design/docs/i18n/en#how-to-format-a-date-using-date-fns

**Comment by wiwilol** [comment]
I dont understand, i did import date-fns, but that does not change anything.
When i type 15/03/2021 in the datepicker's input, it still does not recognise it.
