### ISSUE TITLE
walkthrough / tour

### ISSUE THREAD

**Issue by serdartaylan** [NG-ZORRO/ng-zorro-antd#6532]
## What problem does this feature solve?
It would be nice to add a walkthrough / tour.

## What does the proposed API look like?
example
https://isaacplmann.github.io/ngx-tour/ngx-bootstrap
http://benmarch.github.io/angular-ui-tour/#/docs
https://nmilicic.github.io/ngx-bootstrap-product-tour/

**Comment by ousc** [comment]
recommend @delon/abc/onboarding.

https://ng-alain.com/components/onboarding/zh

**Comment by saeidi-dev** [comment]
The tour component is very useful. This is implemented in the React version.
https://ant.design/components/tour

**Comment by Laffery** [comment]
duplicated #8112
