### ISSUE TITLE
tree异步渲染: 获取数据才渲染所有属性

### ISSUE THREAD

**Issue by xiejay97** [NG-ZORRO/ng-zorro-antd#6539]
## What problem does this feature solve?
实际应用场景,当 `nzData` 为空 (即值非数组或 `[]`), 渲染`nzExpandedKeys`这种属性是无意义的.

多数情况下, 当 `nzData` 由空变为非空, 即 `length > 0`, 这时候应当初始化渲染一次所有属性.

这将很好解决目前异步获取数据渲染繁琐的情况.

## What does the proposed API look like?
无

**Comment by Xie-Jay** [comment]
@simplejason Can it applied to production? 🤔
