### ISSUE TITLE
表格-新增功能-支持分组查看

### ISSUE THREAD

**Issue by a532533603** [NG-ZORRO/ng-zorro-antd#654]
## What problem does this feature solve?

企业项目中，很多都需要进行数据的同类比较，有了分组查看，就可以尽可能已一种优良的体现方式进行查看

## What does the proposed API look like?

https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/index.htm#demos/jqxgrid/grouping.htm
类是 jqwidgets 分组表格

**Comment by vthinkxie** [comment]
will not supported recently, you can reopen this after 0.7.0 released.
