### ISSUE TITLE
*nzSpaceItem causes undefined in variable when subscribing to nzQueryParams of a table.

### ISSUE THREAD

**Issue by ragnar-pals** [NG-ZORRO/ng-zorro-antd#6558]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-4prl23?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-4prl23?file=src/app/app.component.ts)

### Steps to reproduce
In the example on Stackblitz I've two tables that are separated using NzSpace. One table uses the deprecated nz-space-item and the other uses the new *nzSpaceItem. Then I need to subscribe to its nzQueryParams in ngOnInit. Using the new directive the listTable1 is undefined when running in ngOnInit.

### What is expected?
The same behavior should be for both the nz-space-item and *nzSpaceItem so using nzQueryParams in ngOnInit should work without causing error

### What is actually happening?
When using *nzSpaceItem the listTable1 variable is undefined when subscribing to nzQueryParams in ngOnInit which is not the same behavior as before when using nz-space-item.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.3.0 |
| Browser | Chrome 89.0.4389.90 64bit |

**Comment by hsuanxyz** [comment]
The new API does not create view that can be queried statically (like `*ngIf *ngFor`), so you can't use the `{ static: true }` parameter to get its content.

You can learn more in [Angular - Dynamic queries flag migration](https://angular.io/guide/migration-dynamic-flag) .
