### ISSUE TITLE
[ nz-table] when nz-table using nzScroll , <td class="nz-disbale-td ..."> will appears.

### ISSUE THREAD

**Issue by xiaojia117** [NG-ZORRO/ng-zorro-antd#6565]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-sp2mwq?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-sp2mwq?file=src/app/app.component.ts)

### Steps to reproduce
1、Look at the table, there are  "td class="nz-disbale-td ..."  between  "th"  and "td"
2、If we delete the [nzScroll], the table show normally.

### What is expected?
1、Do not show  "td class="nz-disbale-td ..."

### What is actually happening?
 there are  "td class="nz-disbale-td ..." between "th" and "td"

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.2.0 |
| Browser | Google Chrome : version  89.0.4389.90（正式版本） （64 位） |

---
1、My conmany use style in the styles.css, I try to put them in style.css but this phenomenon will not apprear any more, so I put them in .less . If possible, retain this style.

**Comment by vthinkxie** [comment]
these elements are used to measure the width of `td`
you should not overwrite all `td` styles in your `index.less` file
