### ISSUE TITLE
When nzSize both set in parent node and child node, it won't allways affect by last

### ISSUE THREAD

**Issue by linjianhong** [NG-ZORRO/ng-zorro-antd#657]
## What problem does this feature solve?

Such as nz-table, when parent node use nzSize="small", and then other size lose effectiveness

## What does the proposed API look like?

Let the last nzSize usefull

**Comment by vthinkxie** [comment]
parent node? can you give an reproduction link for this?

**Comment by linjianhong** [comment]
import { Component } from '@angular/core';

@Component({
  selector: 'action-list',
  template: `
    
    <nz-table #nzTable [nzDataSource]="data" [nzIsPagination]="false" nzSize="small">
      <thead nz-thead>
        <tr>
          <th nz-th><span>A</span></th>
          <th nz-th><span>SubTable</span></th>
        </tr>
      </thead>
      <tbody nz-tbody>
        <tr nz-tbody-tr >
          <td nz-td>
            <a>name1</a>
          </td>
          <td nz-td>
            
            <nz-table #nzSubTable [nzDataSource]="dataSub" [nzIsPagination]="false" nzSize="middle">
              <thead nz-thead>
                <tr>
                  <th nz-th><span>SubA</span></th>
                  <th nz-th><span>SubB</span></th>
                </tr>
              </thead>
              <tbody nz-tbody>
                <tr nz-tbody-tr >
                  <td nz-td>
                    SubnameA
                  </td>
                  <td nz-td>
                    SubnameB
                  </td>
                </tr>
              </tbody>
            </nz-table>
          </td>
        </tr>
      </tbody>
    </nz-table>`,
  styleUrls: []
})
export class ActionListComponent {
  data=[{}]
  dataSub=[{}]
}

**Comment by vthinkxie** [comment]
@afc163 https://stackblitz.com/edit/ng-zorro-antd-setup-8n2uvt?file=app/app.component.html
please check the style and dom, the bug still exist in ant design 3.0

**Comment by vthinkxie** [comment]
related https://github.com/ant-design/ant-design/issues/8525

**Comment by vthinkxie** [comment]
this will be solved when sync with ant design 3.0

**Comment by vthinkxie** [comment]
hi @linjianhong ,please do not close this issue before fixed.

**Comment by linjianhong** [comment]
So sorry!

**Comment by vthinkxie** [comment]
fixed in version 0.7.0
