### ISSUE TITLE
nz-form-control validation status lose effectiveness while FormGroup instance changed

### ISSUE THREAD

**Issue by zhhb** [NG-ZORRO/ng-zorro-antd#6570]
### Reproduction link
[https://angular-2aeljz.stackblitz.io](https://angular-2aeljz.stackblitz.io)

### Steps to reproduce
1.create form instance from the FormBuider; this.form = this.fb.group({name:[...], ...others form items})
2.use FormBuilder create new instance; this.form = this.fb.group({name:[...],...others form items which have diff with before})
3.the validation status lose effictiveness on nz-form-control

### What is expected?
expect the part of form which not changed can still correctly trigger validation

### What is actually happening?
not trigger validation

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.3.0 |
| Browser | 5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 |

---
temporary，it can be force trigger while make [nzValidateStatus]="form.get('name')!" binding to nz-form-control, but it's just a temporary solution

**Comment by danranVm** [comment]
What is the need for you to create a new instance? 
Maybe you can try using `this.form.reset()`

**Comment by danranVm** [comment]
I’ll close this issue first, if you have other questions, you can reopen it, or create a new issue.
