### ISSUE TITLE
Different colour for each option in the nz-select>nz-option

### ISSUE THREAD

**Issue by sagar52270** [NG-ZORRO/ng-zorro-antd#6576]
## What problem does this feature solve?
allow developer to modify and add styling to nz-option

## What does the proposed API look like?
<nz-option [nzValue]="1" [style]="{'background-color': 'red'}" nzLabel="1"></nz-option>

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/select/en#components-select-demo-custom-content
