### ISSUE TITLE
nz-form-item-required don't recieve data

### ISSUE THREAD

**Issue by linjianhong** [NG-ZORRO/ng-zorro-antd#658]
## What problem does this feature solve?

When I want to hide/show the red * in FormItem label, I can't  do it by this directive, for, the source code `function NzFormItemRequiredDirective` : `this.nzRequired = true;`

## What does the proposed API look like?

[nzFormItemRequired]="required"

**Comment by vthinkxie** [comment]
just set `[nzRequired]="false"`

**Comment by lanmolsz** [comment]
You can do this using `[ngClass]="{'ant-form-item-required':required}"`
