### ISSUE TITLE
nz-space 和*nzSpaceItem 回到导致内容消失

### ISSUE THREAD

**Issue by John0King** [NG-ZORRO/ng-zorro-antd#6584]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-v18a7m?file=src/app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-ivy-v18a7m?file=src/app/app.component.html)

### Steps to reproduce
see link

### What is expected?
显示内容并添加 外边距

### What is actually happening?
元素消失了

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.2.0 |
| Browser | edge |

**Comment by vthinkxie** [comment]
https://stackblitz.com/edit/ng-zorro-antd-ivy-ytrs7j?file=src/app/app.component.html
在 11.3.0 支持 *nzSpaceItem， 请升级版本
