### ISSUE TITLE
date picker not picking value entered manually when used with nzFormat="dd/MM/yyyy"

### ISSUE THREAD

**Issue by eliashourany** [NG-ZORRO/ng-zorro-antd#6587]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-xuxsha?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-xuxsha?file=src/app/app.component.ts)

### Steps to reproduce
use the datepicker with nzFormat="dd/MM/yyyy" or any format where the day starts at first, and try to enter the date manually in the input without selecting it from the datepicker, the datepicker does not take the date.

### What is expected?
the datepicker should automatically select a date when it's entered manually in the input

### What is actually happening?
the datepicker is disregarding the value entered

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.0 |
| Browser | all browsers |

**Comment by tongtanhieu** [comment]
hello, you can try to replace it to nzFormat="'dd/MM/yyyy'" (whith two \' \' inside). Hope this help.

**Comment by eliashourany** [comment]
@tongtanhieu did not work.

**Comment by wenqi73** [comment]
@eliashourany Should use `date-fns`. I have added it into documents as many people are confused abort this. https://github.com/NG-ZORRO/ng-zorro-antd/pull/6627/files
