### ISSUE TITLE
animation of tab tilte in y is excessive,

### ISSUE THREAD

**Issue by HorbieHuo** [NG-ZORRO/ng-zorro-antd#659]
## Version

0.6.2

## Environment

ubuntu 17.10 chrome 62.0.3202.94    angular5

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-cf1fjq?file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-cf1fjq?file=app/app.component.html)

## Steps to reproduce

change tabs to show error scene

```html
<nz-tabset [nzType]="card" [nzSize]="small"
     [nzTabPosition]="top" (nzSelectChange)="_tabChange($event)">
    <nz-tab *ngFor="let tab of AppListData">
        <ng-template #nzTabHeading>
            {{tab.name}}
        </ng-template>
        <!-- {{tab.content}} -->
        <p>{{tab.name}}</p>
    </nz-tab>
    <!-- <ng-template #nzTabBarExtraContent>
        <i class="ant-tabs-new-tab anticon anticon-plus" (click)="newTab()"></i>
    </ng-template> -->
</nz-tabset>
```
![err_p](http://oh14x29vm.bkt.clouddn.com/2017-12-02%2013-11-19%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

## What is expected?

![suc_p](http://oh14x29vm.bkt.clouddn.com/2017-12-02%2013-13-59%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

## What is actually happening?

![err_p](http://oh14x29vm.bkt.clouddn.com/2017-12-02%2013-11-19%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

## Other?

change tabs to show error scene

**Comment by vthinkxie** [comment]
use
```
[nzType]="'card'" [nzSize]="'small'"
```
or
```
nzType="card" [nzSize]="small"
```

your code is wrong for angular
