### ISSUE TITLE
11.4下的nz-drawer使用*nzDrawerContent后子组件无法正常使用

### ISSUE THREAD

**Issue by Credo-Zhao** [NG-ZORRO/ng-zorro-antd#6592]
### Reproduction link
[https://stackblitz.com/edit/drawer-sub-rror?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/drawer-sub-rror?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
去掉<ng-container *nzDrawerContent>或者降级到11.3 可以正常使用。

### What is expected?
可以和11.3以及以前版本一样使用

### What is actually happening?
子组件无法正常使用
@ViewChild 引入子组件，无法正常使用。

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.0 |
| Browser | EDGE,FIREFOX |

**Comment by hsuanxyz** [comment]
@Credo-Zhao 11.4 修复了在未打开时就挂载 `nzDrawerContent` 的问题，现在 Drawer 打开后才会挂载。你可以订阅 `afterOpen` 获取 content 中的引用。

https://stackblitz.com/edit/drawer-sub-rror-su7mec?file=src/app/app.component.ts
