### ISSUE TITLE
use nzBackdrop to fix the selection dropdown menu, but it leads to hover effect of elements don't work

### ISSUE THREAD

**Issue by z-kidy** [NG-ZORRO/ng-zorro-antd#6593]
### Reproduction link
[https://stackblitz.com/edit/angular-8pfzib?file=src/app/app.component.ts ](https://stackblitz.com/edit/angular-8pfzib?file=src/app/app.component.ts )

### Steps to reproduce
1. multiple selection with nzBackdrop=true
2. open dropdown menu 
3. select one of options
4. hover the selected item on input field

### What is expected?
Hover effect of elements should always work, whether the menu is open or not.

Can remove the selected item by click remove icon.

Selection menu position should fixed when scrolling.

### What is actually happening?
Hover effect of elements doesn't work.

Can't remove the selected item with menu open, that is, I have to close the menu first.

Hover effect of elements works if set nzBackdrop=false, but menu position is not fixed. 

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.0 |
| Browser | chrome |

**Comment by z-kidy** [comment]
related issue 
[Select/Datepicker/Cascader menu position not fixed when scrolling in some layout](https://github.com/NG-ZORRO/ng-zorro-antd/issues/6029)

**Comment by wenqi73** [comment]
Currently the solution is add `cdkScrollable` to your container.

**Comment by lelequinter** [comment]
what if, cdkScrollable does not work and the cdk dropdown is still floating?
