### ISSUE TITLE
nzSortDirections global config

### ISSUE THREAD

**Issue by serdartaylan** [NG-ZORRO/ng-zorro-antd#6613]
## What problem does this feature solve?
I am using a table in the application. I use sorting in almost all columns. and just ascend, descend. Typing [nzSortDirections] = "['ascend', 'descend']" in all tables and columns is quite tedious and tiring.

I request the nzSortDirections value to be defined as global settings.

## What does the proposed API look like?
*

**Comment by rxxy** [comment]
+1
I need use 'asc' instead of 'ascend' in almost all columns.

**Comment by rxxy** [comment]
Expect to be able to configure this property globally

**Comment by tmpi-fr** [comment]
Any update on this ? I would love to have this feature implemented

**Comment by Laffery** [comment]
close via #8721
