### ISSUE TITLE
Can't use nzMaxStack option

### ISSUE THREAD

**Issue by Jbz797** [NG-ZORRO/ng-zorro-antd#6617]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-ztft3p?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-ztft3p?file=src/app/app.component.ts)

### Steps to reproduce
Use nzMaxStack option in NzNotificationDataOptions

### What is expected?
No error and 15 notifications that can be displayed at the same time

### What is actually happening?
Type error : "Object literal may only specify known properties, and 'nzMaxStack' does not exist in type 'NzNotificationDataOptions<{}>'.(2345)"

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.0 |
| Browser | Firefox |

**Comment by stygian-desolator** [comment]
you can set `nzMaxStack` in global config
doc: https://ng.ant.design/docs/global-config/en
demo: https://stackblitz.com/edit/ng-zorro-antd-ivy-z5tvop?file=src%2Fapp%2Fapp.module.ts
