### ISSUE TITLE
Progress进度条组件 通过performance monitor观察 CPU 非常高，通过 一直降不下了，导致页面卡顿

### ISSUE THREAD

**Issue by jys2013** [NG-ZORRO/ng-zorro-antd#6624]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
1.https://ng.ant.design/components/progress/zh 进入进度条组件
2.打开chrome的performance monitor
3.观察CPU占用率

### What is expected?
1.CPU占用率下降https://guides.github.com/features/mastering-markdown/

### What is actually happening?
1.CPU占用率居高不下

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.0 |
| Browser | chrome 89.0.4389.128 |

**Comment by jys2013** [comment]
![CPU很高](http://wx3.sinaimg.cn/mw1024/6dad45afgy1gpr4l0p9k9j21hc0op42g.jpg)

**Comment by hsuanxyz** [comment]
ref https://github.com/ant-design/ant-design/issues/31124
