### ISSUE TITLE
Missing Locale Data for Datepicker

### ISSUE THREAD

**Issue by ridyio** [NG-ZORRO/ng-zorro-antd#6629]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-tbavyg?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-tbavyg?file=src/app/app.component.ts)

### Steps to reproduce
Set the locale to es_ES and datepicker won't work anymore

### What is expected?
Datepicker would work

### What is actually happening?
Datepicker doesn't appears correct

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.0 |
| Browser | Safari |

**Comment by wenqi73** [comment]
Need to `registerLocaleData(es);`, NG-ZORRO depends on Angular date default.
