### ISSUE TITLE
模态框中的选择器，滚动时，下拉框会浮动错位

### ISSUE THREAD

**Issue by jaydonyin** [NG-ZORRO/ng-zorro-antd#6646]
### Reproduction link
[https://stackblitz.com/edit/angular-afxmes-sj91yn?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-afxmes-sj91yn?file=src/app/app.component.ts)

### Steps to reproduce
打开选择器列表，上下滚动，选择器的下拉列表与选择器分离，下拉框悬浮不动。

### What is expected?
选择器和下拉列表位置保持同步

### What is actually happening?
垂直滚动时，选择器上下滚动，选择器的下拉列表没有跟随滚动

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | Chrome |

---
希望能给予解决方案或指导意见，非常感谢

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/tooltip/zh#%E9%9D%9E-body-%E6%BB%9A%E8%BD%B4%E4%BA%8B%E4%BB%B6%E9%9C%80%E8%A6%81%E6%9B%B4%E6%96%B0-cdk-%E7%9A%84%E4%BD%8D%E7%BD%AE
https://stackblitz.com/edit/angular-afxmes-xr3brn?file=src/app/app.component.ts

**Comment by jaydonyin** [comment]
非常感谢，还有一小点缺陷是select的下拉框 z-index比模态框的大，通过穿透样式已解决。

**Comment by Tommy0604** [comment]
> 非常感谢，还有一小点缺陷是select的下拉框 z-index比模态框的大，通过穿透样式已解决。

我也遇到同样的问题，当我把tooltips滚动到 滚动区域之外的地方，它依然显示。样式穿透如何修改 z-index，能不能帮我下，帖一个已经修复的 stackblitz link 多谢。

**Comment by jaydonyin** [comment]
实际上，样式穿透的方法是错误的，可能仍然需要监听滚动条去动态设置。我现在的一个方案是监听滚动条，超过距离后隐藏弹出框

**Comment by jaydonyin** [comment]
cdkScrollable在样式冲突上会出现一些问题，希望ngZorro可以提供 类似于ant-Design中的getPopupContainer={triggerNode => triggerNode.parentNode}， 类似的API  将浮动框中的选择器弹框锁定。当然这从技术角度可能很难实现。

**Comment by jaydonyin** [comment]
**更新** 我最新的解决方案是：监听模态框页面的非**body**轴滚动事件（当模态框打开时），发生滚动时，关闭弹出层。
```
import { fromEvent } from 'rxjs';
import { debounce } from 'lodash';

... ...

 constructor(
    private fb: FormBuilder,
    private notifyApi: NotifyApi,
    private message: NzMessageService,
    private cdr: ChangeDetectorRef,
  ) {
    this.onWindowScroll = debounce(this.onWindowScroll, 300);  // 防抖
  }

......

  ngOnInit(): void {
    this.initForm();
    const scrollDom = document.querySelector('.ant-modal-wrap');
    this.subscribeScroll = fromEvent(scrollDom, 'scroll')
      .subscribe((event) => {
        this.onWindowScroll();
  });
  }
  onWindowScroll() {
    console.log('滚动了');
  // 在这里关掉选择器的弹出框
  }
```

发生滚动直接关闭，比较粗暴的解决方案，希望能够给阅读者提供帮助。

**Comment by xianshenglu** [comment]
https://github.com/angular/components/issues/1628#issuecomment-384091352

**Comment by findxc** [comment]
补充分享一下怎么在滚动时关掉 Select 的弹出层给后来的有缘人：

```js
onScroll() {
  // 先删掉，因为关闭有动画效果，就有延迟
  document.querySelectorAll('.ant-select-dropdown').forEach((item: any) => {
    item.remove();
  });
  // 手动点击下，这样 Select 右侧箭头图标显示就对了
  document.querySelectorAll('.ant-select-open').forEach((item: any) => {
    item.click();
  });
}
```
