### ISSUE TITLE
使用Modal的组件形式创建模态框时，调用closeAll或使用浏览器历史的前进/后退进行关闭后，不能重新打开

### ISSUE THREAD

**Issue by tyzh** [NG-ZORRO/ng-zorro-antd#6647]
### Reproduction link
[https://stackblitz.com/edit/angular-xiopcq](https://stackblitz.com/edit/angular-xiopcq)

### Steps to reproduce
1.使用组件形式创建模态框
2.调用closeAll或使用浏览器的前进/后退关闭模态框
3.重新打开模态框

### What is expected?
成功重新打开模态框

### What is actually happening?
打不开模态框

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | chrome |

---
closeAll循环关闭modalRef时，未置为null，导致modalcomponent.open打不开模态框；浏览器的前进后退关闭模态框时，仅从openModals删除了ref。

**Comment by hsuanxyz** [comment]
Duplicate of #6320
