### ISSUE TITLE
IE11下，Menu组件dark主题，nz-submenu的背景色变为白色

### ISSUE THREAD

**Issue by tyzh** [NG-ZORRO/ng-zorro-antd#6651]
### Reproduction link
[https://stackblitz.com/edit/angular-5uyh5a](https://stackblitz.com/edit/angular-5uyh5a)

### Steps to reproduce
Menu组件使用dark主题，并设置submenu

### What is expected?
背景色正常为黑色

### What is actually happening?
背景色为白色

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | IE11 |

---
stackblitz地址IE11可能打不开，可以使用官方文档的例子查看 https://ng.ant.design/components/menu/zh#components-menu-demo-theme
好像是div nz-submenu-inline-child 中缺失了部分class导致的

**Comment by wenqi73** [comment]
IE11 support will be deprecated in Angular 12, so we will not solve the IE11 issues. https://github.com/angular/angular/issues/41840#issuecomment-836836247
