### ISSUE TITLE
one form item multiple controls bug

### ISSUE THREAD

**Issue by vatsake** [NG-ZORRO/ng-zorro-antd#6668]
### Reproduction link
[https://stackblitz.com/](https://stackblitz.com/)

### Steps to reproduce
I couldn't reproduce it in stackblitz (version diff?).

in html:

```
<form nz-form [formGroup]="Form">
      <nz-form-item>
        <nz-form-label nzSpan="6" nzFor="Name" nzRequired>Name</nz-form-label>
        <nz-form-control nzErrorTip="Name is mandatory!" nzSpan="7">
          <input nz-input id="Name" formControlName="Name"/>
        </nz-form-control>
        <nz-form-label nzSpan="4" nzFor="Family" nzRequired>Family</nz-form-label>
        <nz-form-control nzErrorTip="Family is mandatory" nzSpan="7">
          <input  nz-input id="Family" formControlName="Family"/>
        </nz-form-control>
      </nz-form-item>
</form>
```

in .ts:
```
Form:FormGroup = this.fb.group({
    Name: [null, Validators.required],
    Family: [null, Validators.required]
  })
```

### What is expected?
Each control validates its own input.

### What is actually happening?
If one control (input) has an error. Both are 'invalid'.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | Chrome, any |

**Comment by danranVm** [comment]
The status of `nz-form-item` is controlled by its subcomponent `nz-form-control`, so there should be only one `nz-form-control` component in an `nz-form-item`.

If you need multiple form elements in a row:

- You can consider using inline layout, refer to: https://ng.ant.design/components/form/zh#components-form-demo-horizontal-login
- Or you can use grid components, refer to: https://ng.ant.design/components/form/zh#components-form-demo-advanced-search

re #6439
