### ISSUE TITLE
How to change the size of nz cascader menu?

### ISSUE THREAD

**Issue by liujiayi13** [NG-ZORRO/ng-zorro-antd#6678]
## What problem does this feature solve?
I want to change the size to fit for mobile phone's display

## What does the proposed API look like?
An api to change the min-width for nz cascader menu

**Comment by stygian-desolator** [comment]
You can override the default style like this:
![image](https://user-images.githubusercontent.com/73412177/117565678-10282d80-b0e5-11eb-99ef-4f3b1724a15f.png)
