### ISSUE TITLE
how to set the style of single DateCell of Calendar

### ISSUE THREAD

**Issue by Ximena-con** [NG-ZORRO/ng-zorro-antd#6679]
## What problem does this feature solve?
I want to set the background-color for some datecells 

## What does the proposed API look like?
<nz-calendar [nzFullscreen]="false" (nzSelectChange)="onValueChange($event)">
          <ng-container *nzDateCell="let date" [ngStyle]="{ backgroundColor: 'red' }">
     
          </ng-container>
        </nz-calendar>

**Comment by stygian-desolator** [comment]
use [nzDateRender] customize the rendering of date cells
https://ng.ant.design/components/date-picker/en#components-date-picker-demo-date-render
demo: https://stackblitz.com/edit/angular-p5grec?file=src/app/app.component.ts

or customize basic theme
https://ng.ant.design/docs/customize-theme/en
