### ISSUE TITLE
nz-radio-group can not check default value

### ISSUE THREAD

**Issue by vellengs** [NG-ZORRO/ng-zorro-antd#668]
## Version

0.5.3

## Environment

0.6.0

## Reproduction link

[https://ng-zorro-antd-setup-gn1kkp.stackblitz.io](https://ng-zorro-antd-setup-gn1kkp.stackblitz.io)

## Steps to reproduce

https://ng-zorro-antd-setup-gn1kkp.stackblitz.io

## What is expected?

option can be checked.

## What is actually happening?

nothing checked.

**Comment by vthinkxie** [comment]
bug confirm, will be fixed in next version.
