### ISSUE TITLE
How to disable the calendar default highlight dateCell? 

### ISSUE THREAD

**Issue by Ximena-con** [NG-ZORRO/ng-zorro-antd#6680]
## What problem does this feature solve?
I need one calendar without default selected date, I want to highlight some dates which decided by my code.

## What does the proposed API look like?
may be some API like [nzDisabledDefaultDate]?

![image](https://user-images.githubusercontent.com/81148098/117559922-f7efe880-b0bb-11eb-9d23-528ccdcb4b57.png)

**Comment by Ximena-con** [comment]
Please can anyone provide us with a solution ?

**Comment by stygian-desolator** [comment]
use [nzDateRender]  customize the rendering of date cells 
https://ng.ant.design/components/date-picker/en#components-date-picker-demo-date-render
demo: https://stackblitz.com/edit/angular-p5grec?file=src/app/app.component.ts

or customize basic theme
https://ng.ant.design/docs/customize-theme/en

**Comment by Ximena-con** [comment]
Thanks for the response, and add one point : if want to customize the **nz-calendar**, you need to use **[nzDateCell]** , [nzDateRender] only support nz-date-picker.
![image](https://user-images.githubusercontent.com/81148098/117648145-733ac280-b1c0-11eb-8505-4e71fdb099f5.png)
