### ISSUE TITLE
why the calendar [(ngModel)] can't support ngfor value?

### ISSUE THREAD

**Issue by Ximena-con** [NG-ZORRO/ng-zorro-antd#6681]
## What problem does this feature solve?
why the calendar [(ngModel)] can't support ngfor value?

## What does the proposed API look like?
why the calendar [(ngModel)] can't support ngfor value?

As this screenshot, "months" is the date array, and "item" is date type, I want to show 12 calendars in web, 
![image](https://user-images.githubusercontent.com/81148098/117562788-3d201480-b0d4-11eb-8c1b-1b11993d59fb.png)

 and I get this error" Cannot use variable 'item' as the left-hand side of an assignment expression. Template variables are read-only."
![image](https://user-images.githubusercontent.com/81148098/117562883-ccc5c300-b0d4-11eb-815b-35c211c410cd.png)

**Comment by stygian-desolator** [comment]
try using like this 
https://stackblitz.com/edit/angular-kvcmyg?file=src/app/app.component.ts

**Comment by Ximena-con** [comment]
@stygian-desolator thanlks for the quick response !  it works !
