### ISSUE TITLE
two nz-form-control in one nz-form-item will cause validatition error

### ISSUE THREAD

**Issue by hizikata** [NG-ZORRO/ng-zorro-antd#6688]
### Reproduction link
[https://stackblitz.com/edit/angular-ryucds-gn3jeq](https://stackblitz.com/edit/angular-ryucds-gn3jeq)

### Steps to reproduce
1. type in something in **Username** form control;
2. delete what you type in on step one;
3. you'll see the input box of **E-mail** form control turning red which has no validator actually.

### What is expected?
input box in the second form-control won't turn red;

### What is actually happening?
input box in the second form-control has turned red;

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | google chrome; ege |

**Comment by danranVm** [comment]
dup #6668
