### ISSUE TITLE
DatePicker 组件 当nzMode="week"时 选择2021年1月2日 文本框显示2021-53

### ISSUE THREAD

**Issue by a249474283** [NG-ZORRO/ng-zorro-antd#6689]
### Reproduction link
[https://stackblitz.com/edit/h8cbjg--run?file=src/app/app.module.ts](https://stackblitz.com/edit/h8cbjg--run?file=src/app/app.module.ts)

### Steps to reproduce
<nz-date-picker nzMode="week" [nzSize]="size"></nz-date-picker> 
选择2021年1月2日

### What is expected?
文本框显示 2021-01或2020-53 

### What is actually happening?
显示 2021-53

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.1 |
| Browser | google chrome |

---
在示例代码即可复现此问题 重现链接我就用了咱们的示例代码

**Comment by wenqi73** [comment]
Duplicate of https://github.com/NG-ZORRO/ng-zorro-antd/issues/5751.
