### ISSUE TITLE
如何设置cascader的元素当没有children时自动isLeaf=false

### ISSUE THREAD

**Issue by liujiayi13** [NG-ZORRO/ng-zorro-antd#6693]
## What problem does this feature solve?
如何设置cascader的元素当没有children时自动isLeaf=false

## What does the proposed API look like?
设置cascader的元素当没有children时自动isLeaf=false

**Comment by stygian-desolator** [comment]
https://github.com/ant-design/ant-design/issues/30659

**Comment by wendellhu95** [comment]
> [ant-design/ant-design#30659](https://github.com/ant-design/ant-design/issues/30659)

It seems to that we're in a totally different situation here. Currently we don't show an extra layer when an item has no children. But there's a small arrow indicating that it is not a leaf item. While the issue requires a new feature that treats this kind of item as leaf item.

![image](https://user-images.githubusercontent.com/12122021/121772429-e5c80500-cba7-11eb-9766-ecad70f38d2a.png)

**Comment by wendellhu95** [comment]
This will introduce a breaking change. Considering https://ng.ant.design/components/cascader/en#components-cascader-demo-lazy this as an example. If we want to load child options of an option, we will force users to declare that it is not a leaf option.

```diff
const provinces = [
  {
    value: 'zhejiang',
    label: 'Zhejiang'
+  isLeaf: false
  },
  {
    value: 'jiangsu',
    label: 'Jiangsu'
+  isLeaf: false
  }
];
```

Hence, I am afraid we will not implement this. At least not soon.

**Comment by wendellhu95** [comment]
I am going to close this issue since a fix would introduce breaking change. 

Please traverse options to make them as leaves.
