### ISSUE TITLE
nz-tabset nzCentered not working

### ISSUE THREAD

**Issue by renmengting** [NG-ZORRO/ng-zorro-antd#6703]
### Reproduction link
[https://stackblitz.com/edit/angular-cspyyo?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-cspyyo?file=src/app/app.component.ts)

### Steps to reproduce
1.set [nzCentered]="true"
2.tabs not display center

### What is expected?
tabs display center

### What is actually happening?
tabs not display center

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | chrome |

---
in version 10 nzCentered is working
version 11.4.1 not working

**Comment by stygian-desolator** [comment]
@hsuanxyz we need to sync styles 😃 
https://github.com/ant-design/ant-design/pull/30106/files

**Comment by hsuanxyz** [comment]
@stygian-desolator Can you submit a PR for this? Because [components/style/themes/default.less:L242](https://github.com/NG-ZORRO/ng-zorro-antd/pull/6670/files#diff-078bc4e1aa99f846fbca53047d876b80353e8d2d730b9a45fd3a9a9ba361b593L242) has not been fully tested
