### ISSUE TITLE
使用nz-datepicker 组合成 range，使用nzDisabledDate，显示可以点击，但点击无效

### ISSUE THREAD

**Issue by yy7054wyq5** [NG-ZORRO/ng-zorro-antd#6709]
### Reproduction link
[https://stackblitz.com/edit/angular-jqekil?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-jqekil?file=src/app/app.component.ts)

### Steps to reproduce
1.  点击链接里的选择"按周"，
2. 选中一个开始日期
3. 在结束日期的datepicker中，无法选中未禁用的最后一天。
[
![截屏2021-05-21 上午10 28 13](https://user-images.githubusercontent.com/11879742/119073392-d37eff00-ba1f-11eb-8b0c-1cdd4d1084c2.png)
](url)

### What is expected?
选中未禁用的最后一天。

### What is actually happening?
无法选中未禁用的最后一天。

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | 版本 90.0.4430.212（正式版本） (x86_64)，mac |

**Comment by wenqi73** [comment]
- 升到 11.4.2
- 在日期面板中用来判断是否可点击的时间是当天的`00:00:00`点；而点击后时间则变为当前时间，如`16:10:00`，这时候用 `getTime()` 会不准。你的例子中应该剔除掉 time 仅用 date 来判断

**Comment by yy7054wyq5** [comment]
> * 升到 11.4.2
> * 在日期面板中用来判断是否可点击的时间是当天的`00:00:00`点；而点击后时间则变为当前时间，如`16:10:00`，这时候用 `getTime()` 会不准。你的例子中应该剔除掉 time 仅用 date 来判断

```js
 disabledEndDate = (endValue: Date): boolean => {
    if (!endValue || !this.startValue) {
      return false;
    }
    let range = Infinity;
    switch (this.range) {
      case 'week':
        const ymd = format(addWeeks(this.startValue, 1), 'yyyy-MM-dd');
        range = new Date(ymd + ' 23:59:59').getTime();
        break;
      default:
        break;
    }
    return (
      endValue.getTime() <= this.startValue.getTime() ||
      endValue.getTime() > range
    );
  };
```
我采用的是这种方式，也是可行的。感谢。

**Comment by galaxynova1999** [comment]
要进行比较的两个时间使用moment(date).endOf('days')处理一下也是可以的
