### ISSUE TITLE
日期选择器和时间选择器的控件要有只返回日期和时间的功能

### ISSUE THREAD

**Issue by Newxml** [NG-ZORRO/ng-zorro-antd#6726]
## What problem does this feature solve?
获取日期部分的信息，或者只获取时间部分的信息

## What does the proposed API look like?
我使用nz-time-picker 的时候 。假设选中的是“11:46:32”, 但是实际上控件绑定的值为“2021/04/29 11:46:32”，但此时我只需要控件返回“11:46:32”这部分的信息就行了。
日期控件同理，只需要返回“2021/04/29” 不需要后面的时间

**Comment by wenqi73** [comment]
统一返回 `Date` 类型，其他的转化需要自行处理。
