### ISSUE TITLE
Layout组件中如何使[nzIcon]有更多来源的图，而不是只能来源于自带的icon库里的图

### ISSUE THREAD

**Issue by Rdandelion** [NG-ZORRO/ng-zorro-antd#6728]
## What problem does this feature solve?
在使用layout时，icon图标库里的图不能满足需求

## What does the proposed API look like?
希望有api的选择，是选择现有的icon，还是iconfont中项目的icon，还是自己设计的图如svg、png等

**Comment by wendellhu95** [comment]
https://ng.ant.design/components/icon/zh#components-icon-demo-namespace 请仔细阅读有关 icon 的文档
