### ISSUE TITLE
nz-cascader nzClear not working or implemented

### ISSUE THREAD

**Issue by chriso86** [NG-ZORRO/ng-zorro-antd#6751]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/ab63d7e25aabab8c2fbb2c63294b6b7c08c30480/components/cascader/cascader.component.ts#L252](https://github.com/NG-ZORRO/ng-zorro-antd/blob/ab63d7e25aabab8c2fbb2c63294b6b7c08c30480/components/cascader/cascader.component.ts#L252)

### Steps to reproduce
Try to consume the EventEmitter for nz-cascader called nzClear.

### What is expected?
It should emit to the consumer of the component using the nzClear event emitter somewhere, probably in the clearSelection method:
[cascader.component.ts line 466](https://github.com/NG-ZORRO/ng-zorro-antd/blob/ab63d7e25aabab8c2fbb2c63294b6b7c08c30480/components/cascader/cascader.component.ts#L466)

### What is actually happening?
It doesn't emit anything.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.2 |
| Browser | Chrome (Doesn't matter) |

---
I searched through the cascader service and found a method called prepareEmitValue, but nzClear is never emitted anywhere as far as I'm able to see.

**Comment by wendellhu95** [comment]
PR is welcomed!

**Comment by chriso86** [comment]
@wendellhu95 Okay cool, I'll make the change now and create the PR. Do I create the PR to "master" branch? What is your ALM model for a fix like this? Do you have a QAS channel?

**Comment by chriso86** [comment]
Nevermind, it seems like you're using trunking with rebase. I'll create a branch and PR for the fix now.

**Comment by chriso86** [comment]
The "npm run test" command is failing from the root package.json file.
I'll try again later when I have more time.
