### ISSUE TITLE
dropdownmenu中设置menu mode 为inline submenu右侧箭头不是向下，且当鼠标离开dropdown时，菜单会自动展开，nzOpen状态错乱(需点击多次)

### ISSUE THREAD

**Issue by sbyps** [NG-ZORRO/ng-zorro-antd#6756]
### Reproduction link
[https://stackblitz.com/edit/angular-srharw](https://stackblitz.com/edit/angular-srharw)

### Steps to reproduce
dropdownmenu中设置menu mode 为inline 
1. submenu右侧箭头不是向下
2. 当鼠标离开dropdown时，菜单会自动展开，
3. 再次进入dropdown menu，nzOpen状态错乱(需点击多次)
```javascript
<a nz-dropdown [nzDropdownMenu]="menu">
      Hover me
      <i nz-icon nzType="down"></i>
    </a>
    <nz-dropdown-menu #menu="nzDropdownMenu">
      <ul nz-menu nzMode="inline">
        <li nz-menu-item>1st menu item</li>
        <li nz-menu-item>2nd menu item</li>
        <li nz-menu-divider></li>
        <li nz-submenu nzTitle="sub menu">
          <ul>
            <li nz-menu-item>3rd menu item</li>
            <li nz-menu-item>4th menu item</li>
          </ul>
        </li>
        <li nz-submenu nzTitle="sub menu">
          <ul>
            <li nz-menu-item>3rd menu item</li>
            <li nz-menu-item>4th menu item</li>
          </ul>
        </li>
      </ul>
    </nz-dropdown-menu>
```

### What is expected?
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/menu/submenu-title.component.ts
inline模式修复title arrow icon为向下，且submenu多次展开收起顺畅

### What is actually happening?
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/menu/submenu-title.component.ts
inline模式title arrow icon为向右，且离开dropdown后再进入submenu多次展开收起后open状态错误，需点击两次

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.2 |
| Browser | Chrome 81 |

**Comment by stygian-desolator** [comment]
Hi, thank you very much for your suggestion, but we don't recommend using `inline` mode in `nz-dropdown-menu`, you can check this [issue](https://github.com/ant-design/ant-design/issues/6101#issuecomment-300700950) for more details.

**Comment by sbyps** [comment]
@stygian-desolator using collapse in dropdown also has the same behavior, the collapse will open when mouse leave the dropdown
