### ISSUE TITLE
Affix固钉在滚动条消失时，固定状态没有改变

### ISSUE THREAD

**Issue by AdvanceOrange** [NG-ZORRO/ng-zorro-antd#6764]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-forked-hmeb3](https://codesandbox.io/s/ng-zorro-antd-ivy-forked-hmeb3)

### Steps to reproduce
1. 点击remove
2. 弹出modal，点击确认，移除组件
3. 页面已经无法滚动，但affix固定状态没有改变

### What is expected?
修复，affix应该取消固定

### What is actually happening?
Affix固钉在window高度发生改变，滚动条消失时，固定状态没有改变

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.2.0 |
| Browser | chrome |

**Comment by wendellhu95** [comment]
@AdvanceOrange Hi there. I didn't see that the Affix component is used in your reproduction. Could you please check that?

**Comment by AdvanceOrange** [comment]
> @AdvanceOrange你好。我没有看到您的复制中使用了 Affix 组件。你能检查一下吗？
好的，这是新的链接
https://codesandbox.io/s/ng-zorro-antd-ivy-forked-0sqox

**Comment by xaclincoln** [comment]
看了源码的实现方式，原因在于nzTarget内容的变化无法触发位置更新，是否可以考虑使用ResizeObserver(不支持IE11)监控document.body或nzTarget的高度变化，示例如下
`const observer = new ResizeObserver(()=>{ this.updatePosition() }; //可以结合RXJS减少更新频率
observer.observe(document.body);
`

**Comment by wendellhu95** [comment]
> 看了源码的实现方式，原因在于nzTarget内容的变化无法触发位置更新，是否可以考虑使用ResizeObserver(不支持IE11)监控document.body或nzTarget的高度变化，示例如下
> `const observer = new ResizeObserver(()=>{ this.updatePosition() }; //可以结合RXJS减少更新频率 observer.observe(document.body); `

是的，欢迎提交 PR
