### ISSUE TITLE
support single select in checkbox-group

### ISSUE THREAD

**Issue by xiejay97** [NG-ZORRO/ng-zorro-antd#6792]
## What problem does this feature solve?
in some scenes, checkbox-group need not only multiple select, but also  single select 

## What does the proposed API look like?
nzSingle: boolean

**Comment by konossow** [comment]
Why not use radio-group?

**Comment by xiejay97** [comment]
> Why not use radio-group?

radio-group not support multichoice, I need a component that can apply to both single and multiple choice.
