### ISSUE TITLE
栅格布局中使用nz-affix时，布局错位

### ISSUE THREAD

**Issue by yedajiang44** [NG-ZORRO/ng-zorro-antd#6798]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-rortcl?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-rortcl?file=src/app/app.component.ts)

### Steps to reproduce
1. 打开页面后注意下按钮与左边div的间隔距离
2. 向下滚动页面直至按钮被固定，并记录按钮与左边div间隔距离
3. 向上滚动页面直至按钮取消固定，观察按钮与左边div间隔距离

### What is expected?
按钮与左边的div间隔距离不受页面滚动影响

### What is actually happening?
滚动后按钮错位

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.2 |
| Browser | chrome 91.0.44 |

**Comment by robertkemp** [comment]
Perhaps it is should work as you coded it (the devs would be able to comment on this).  In my testing it maintains the margin when putting the nz-affix in its own div -> https://stackblitz.com/edit/ng-zorro-antd-ivy-vsq2by?file=src%2Fapp%2Fapp.component.ts

**Comment by yedajiang44** [comment]
> Perhaps it is should work as you coded it (the devs would be able to comment on this). In my testing it maintains the margin when putting the nz-affix in its own div -> https://stackblitz.com/edit/ng-zorro-antd-ivy-vsq2by?file=src%2Fapp%2Fapp.component.ts

thanks for your reply~it's work！
