### ISSUE TITLE
I get an error when importing  NzCascaderModule  

### ISSUE THREAD

**Issue by oscarigarcia** [NG-ZORRO/ng-zorro-antd#6824]
## What problem does this feature solve?
an error is being presented when importing the waterfall component

## What does the proposed API look like?
core.js:4127 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Event binding overlayOutsideClick not emitted by any directive on an embedded template. Make sure that the event name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("erlayTransformOriginOn]="'.ant-cascader-menus'"
      [cdkConnectedOverlayOpen]="menuVisible"
      [ERROR ->](overlayOutsideClick)="onClickOutside($event)"
      (detach)="closeMenu()"
    >
"): ng:///NzCascaderModule/NzCascaderComponent.html@60:6
Error: Template parse errors:
Event binding overlayOutsideClick not emitted by any directive on an embedded template. Make sure that the event name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("erlayTransformOriginOn]="'.ant-cascader-menus'"
      [cdkConnectedOverlayOpen]="menuVisible"
      [ERROR ->](overlayOutsideClick)="onClickOutside($event)"
      (detach)="closeMenu()"
-----------------------------------------------------------------------
Package.json

"@agm/core": "^1.1.0",
    "@angular/animations": "^9.1.4",
    "@angular/cdk": "^9.2.2",
    "@angular/common": "^9.0.0",
    "@angular/compiler": "^9.0.0",
    "@angular/core": "^9.1.12",
    "@angular/forms": "^9.0.0",
    "@angular/localize": "^9.1.13",
    "@angular/material": "^9.2.2",
    "@angular/platform-browser": "^9.0.0",
    "@angular/platform-browser-dynamic": "^9.0.0",
    "@angular/router": "^9.0.0",
    "@ckeditor/ckeditor5-angular": "^1.2.3",
    "@ckeditor/ckeditor5-build-classic": "^19.0.2",
    "@coreui/angular": "^2.9.0",
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.3.1",
    "@coreui/coreui-pro": "^2.1.16",
    "@coreui/icons": "0.3.0",
    "@ng-bootstrap/ng-bootstrap": "^6.0.0",
    "@ng-select/ng-select": "^3.7.3",
    "@ngrx/store": "^10.0.0",
    "@rxweb/reactive-form-validators": "^2.1.2",
    "@sweetalert2/ngx-sweetalert2": "^7.0.0",
    "@types/jest": "^26.0.10",
    "@types/karma": "^5.0.1",
    "@types/mocha": "^8.0.2",
    "@types/mongodb": "^3.5.14",
    "@types/papaparse": "^5.0.4",
    "angular-calendar": "^0.27.11",
    "angular-mydatepicker": "^0.11.2",
    "angular-oauth2-oidc": "^10.0.3",
    "angular-oauth2-oidc-jwks": "^9.0.0",
    "angular2-datatable": "^0.6.0",
    "angular2-text-mask": "^9.0.0",
    "angular2-toaster": "^8.0.0",
    "axios": "^0.21.1",
    "bootstrap": "^4.4.1",
    "bs-stepper": "^1.7.0",
    "chart.js": "^2.9.2",
    "core-js": "^2.5.7",
    "csv-parser": "^3.0.0",
    "date-fns": "2.22.1",
    "dateformat": "^4.5.1",
    "file-saver": "^2.0.5",
    "flag-icon-css": "^3.4.6",
    "font-awesome": "^4.7.0",
    "html-to-text": "^7.0.0",
    "html2canvas": "^1.0.0-rc.7",
    "joi": "^14.3.1",
    "jspdf": "^2.3.1",
    "jwt-decode": "^2.2.0",
    "lodash.clonedeep": "^4.5.0",
    "lodash.isequal": "^4.5.0",
    "md-steppers": "^0.4.1",
    "moment": "^2.25.1",
    "mutationobserver-shim": "^0.3.3",
    "ng-select": "^1.0.2",
    "ng-zorro-antd": "^11.4.2",
    "ng2-ace-editor": "^0.3.9",
    "ng2-charts": "2.4.0",
    "ng2-dragula": "^2.1.1",
    "ng2-search-filter": "^0.5.1",
    "ng2-select2": "^1.0.0-beta.16",
    "ngx-bootstrap": "^5.5.0",
    "ngx-editor": "^5.0.0-alpha.9",
    "ngx-filter-pipe": "^2.1.2",
    "ngx-forms-builder": "^0.5.3",
    "ngx-mask": "^9.1.2",
    "ngx-pagination": "^5.1.0",
    "ngx-perfect-scrollbar": "^8.0.0",
    "ngx-print": "^1.2.0-beta.6",
    "ngx-quill": "^5.2.0",
    "ngx-spinner": "^9.0.2",
    "node-fetch": "^2.6.1",
    "papaparse": "^5.2.0",
    "quill": "^1.3.7",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.6.6",
    "select2": "^4.1.0-rc.0",
    "simple-line-icons": "^2.5.2",
    "socket.io-client": "^4.1.2",
    "spinkit": "^1.2.5",
    "stepper": "0.0.4",
    "sweetalert2": "^9.0.0",
    "ts-helpers": "^1.1.2",
    "tslib": "^1.14.1",
    "tweetnacl": "^1.0.3",
    "tweetnacl-util": "^0.15.1",
    "uuid": "^8.3.2",
    "web-animations-js": "^2.3.2",
    "xlsx": "^0.16.9",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.4",
    "@angular/cli": "^9.1.4",
    "@angular/compiler-cli": "^9.0.0",
    "@angular/language-service": "^9.0.0",
    "@types/jasmine": "^3.6.0",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^12.12.47",
    "codelyzer": "^5.2.1",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^5.1.0",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.5.2",
    "prettier": "2.0.5",
    "protractor": "^7.0.0",
    "ts-node": "^8.4.1",
    "tslint": "^5.20.0",
    "typescript": "~3.7.5"

**Comment by wendellhu95** [comment]
Could you please make a mini-reproduction?

**Comment by oscarigarcia** [comment]
Of course, Here I import the button component is imported well
 
![InkedCapture_LI](https://user-images.githubusercontent.com/53156103/124763872-6c9ba380-df02-11eb-8b5c-e52044ec1470.jpg)

Here I import the waterfall component and it gives me the following error

![InkedCapture2_LI](https://user-images.githubusercontent.com/53156103/124763976-7fae7380-df02-11eb-9d22-12aa03cdf6bb.jpg)

**Comment by oscarigarcia** [comment]
> Could you please make a mini-reproduction?

Of course, Here I import the button component is imported well
 
![InkedCapture_LI](https://user-images.githubusercontent.com/53156103/124763872-6c9ba380-df02-11eb-8b5c-e52044ec1470.jpg)

Here I import the waterfall component and it gives me the following error

![InkedCapture2_LI](https://user-images.githubusercontent.com/53156103/124763976-7fae7380-df02-11eb-9d22-12aa03cdf6bb.jpg)

**Comment by wendellhu95** [comment]
Please provide a reproduction (a stackblitz link or a demo repo) so we can investigate this. Thanks.
