### ISSUE TITLE
Cannot tranfer items with javascript

### ISSUE THREAD

**Issue by MarkoPomerants** [NG-ZORRO/ng-zorro-antd#6829]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-bwx7wo?embed=1&file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-bwx7wo?embed=1&file=src/app/app.component.ts)

### Steps to reproduce
Add a function that changes a TransferItem direction property to a button. (try it with stackblitz link - press button)

### What is expected?
It changes property and displays it.

### What is actually happening?
It changes property but it doesn't show it.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.2 |
| Browser | Chrome |

**Comment by MarkoPomerants** [comment]
The property 'direction' changes, but how to refresh/update nz-transfer componenet?

**Comment by cipchk** [comment]
Please use immutable way to update array or object. like this:

```diff
addToRight() {
   this.groups.find((x: TransferItem) => x.title == 'Group 4').direction = 'right';
+  this.groups = [...this.groups]
}
```
