### ISSUE TITLE
模板驱动表单中使用nz-cascader时设置ngModel默认值无法正确回显选中

### ISSUE THREAD

**Issue by mrlionline** [NG-ZORRO/ng-zorro-antd#6855]
### Reproduction link
[https://stackblitz.com/edit/angular-w6gvrh?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-w6gvrh?file=src/app/app.component.ts)

### Steps to reproduce
1. 新建模板驱动表单
2. 在nz-form-control增加nz-cascader，并设置ngModel
3. 查看选中状态（未选中ngModel设置的value）
4. 在form外写同样的nz-cascader可以选中

### What is expected?
模板驱动表单中正确回显级联字段

### What is actually happening?
模板驱动表单中未正确回显级联字段

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | chrome 版本 91.0.4472.124（正式版本） （64 位） |

**Comment by Feng-JY** [comment]
控制台有报错，在元素上使用 [(ngModel)] 时，必须为该元素定义一个 name 属性
https://angular.cn/guide/forms#naming-control-elements

**Comment by vthinkxie** [comment]
请按照 @Feng-JY 建议进行修改

**Comment by mrlionline** [comment]
> 有错误，在元素上使用 [(ngModel)] 时，必须为该元素定义一个名称属性
> https://angular.cn/guide/forms#naming-control-elements

感谢，加上name的确可以了，但我本地不是name的问题
我给form加了个#baseInfoForm="ngForm"，去掉后可正确回显默认值
但我需要在在ts里获取到baseInfoForm进行手动验证，
请问模板驱动表单如果手动验证
