### ISSUE TITLE
nz-popconfirm nzOkType="danger" is not working after the nz-button danger breaking change

### ISSUE THREAD

**Issue by Greegko** [NG-ZORRO/ng-zorro-antd#6864]
### Reproduction link
[https://stackblitz.com/edit/angular-ak4al8](https://stackblitz.com/edit/angular-ak4al8)

### Steps to reproduce
use nzOkType="danger" for nz-popconfirm

### What is expected?
Being red

### What is actually happening?
Not being red

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | Any |

---
It is a breaking change that `nz-button nzType="danger"` has been removed, I think that's the root issue of it.

**Comment by wendellhu95** [comment]
@Greegko You're absolutely right. Interested in a PR? Thanks!

**Comment by wendellhu95** [comment]
This bug is [also reported](https://github.com/ant-design/ant-design/issues/28654) in the React version.
