### ISSUE TITLE
对话框（Modal）可拖动

### ISSUE THREAD

**Issue by Mike-Jia** [NG-ZORRO/ng-zorro-antd#6867]
## What problem does this feature solve?
在有的场景下对话框内容是一个表单，需要输入内容比较多，而部分信息可能需要参考之前界面展示的信息来输入。在弹出对话框后不能拖动则导致对话框将原有展示信息挡住，无法参考，不利于用户使用，被用户抱怨。

## What does the proposed API look like?
期望提供两种方式API：
* HTML模板：
```
<nz-modal [movable]="true" [(nzVisible)]="isVisible" nzTitle="The first Modal">  
```

* 服务接口：
```
export class NzDemoModalServiceComponent {
  constructor(private modal: NzModalService) {}

  createModal(): void {
    this.modal.create({
      movable: true,
      nzTitle: 'Modal Title',
      nzContent: 'string, will close after 1 sec',
    });
  }
}
```
两种场景的movable都应该提供默认值false保持兼容升级。

**Comment by huajian123** [comment]
@Mike-Jia 可以参考http://124.71.128.53:8081/#/default/feat/ex-modal在线预揽地址
源码地址https://github.com/huajian123/ng-ant-admin

**Comment by HyperLife1119** [comment]
Close via #8419.
