### ISSUE TITLE
Angular 12.1 LESS problem

### ISSUE THREAD

**Issue by rockletz** [NG-ZORRO/ng-zorro-antd#6869]
### Reproduction link
[https://stackblitz.com/edit/angular-ivy-jfxzab?file=package.json](https://stackblitz.com/edit/angular-ivy-jfxzab?file=package.json)

### Steps to reproduce
Upgrade to Angular 12.1

### What is expected?
The project should compile correctly.

### What is actually happening?
```
./src/theme.less - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// ================================================================
.table-size(~'middle', @table-padding-vertical-md, @table-padding-horizontal-md, @table-font-size-md);
^
Operation on an invalid type
      Error in /home/samuel/VBWeb2/vbweb_frontend/node_modules/ng-zorro-antd/table/style/size.less (line 39, column 0)
    at processResult (/home/samuel/VBWeb2/vbweb_frontend/node_modules/webpack/lib/NormalModule.js:701:19)
    at /home/samuel/VBWeb2/vbweb_frontend/node_modules/webpack/lib/NormalModule.js:807:5
    at /home/samuel/VBWeb2/vbweb_frontend/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/samuel/VBWeb2/vbweb_frontend/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/samuel/VBWeb2/vbweb_frontend/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.lessLoader (/home/samuel/VBWeb2/vbweb_frontend/node_modules/less-loader/dist/index.js:54:5)
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | Chrome |

**Comment by sainisagar310** [comment]
+1

**Comment by llkui** [comment]
+1

**Comment by hoondeveloper** [comment]
+1
(https://github.com/NG-ZORRO/ng-zorro-antd/issues/6760 I opened this issue before, but i still have same problem..)

**Comment by wendellhu95** [comment]
Hey guys. Could you please create a minimal reproduction? We will look into this. Thanks!

**Comment by wendellhu95** [comment]
Stackblitz may be not helpful here. You could upload a repo.

**Comment by llkui** [comment]
I found the reason for the bug.

When the project is updated to angular12 and ng-zorro-antd12.
If the content of theme.less file is not updated, such a bug will appear.

So, update the content of theme.less file, it's no problem.
[theme.less](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/default.less)

**Comment by zapatel** [comment]
+1

**Comment by billpeace** [comment]
上次我测试出来了 

不重新引入 https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/default.less
不会报错

假如引入 https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/default.less 最新的 也不会报错

假如引入 https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/default.less 以前zorro版本，就会报错

**Comment by zhenzhenChange** [comment]
[Less v4.0](https://github.com/less/less.js/releases/tag/v4.0.0)

是因为 Less 在 v4 中将除法`/`的解析规则变了：除法周围需要加上括号包裹。

v4 以前：

```less
@var: xxx / xxx;
```

现在：

```less
@var: (xxx / xxx);
```

---

![image](https://user-images.githubusercontent.com/51586637/208837080-990f5e43-fb23-49a1-b372-4593867d35bd.png)


![image](https://user-images.githubusercontent.com/51586637/208837040-ddbcbb38-1d94-4736-923b-2ece0d55b5ac.png)
