### ISSUE TITLE
Can't use dropdown into a popover

### ISSUE THREAD

**Issue by AymericSauty** [NG-ZORRO/ng-zorro-antd#6894]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-hd7qrr](https://stackblitz.com/edit/ng-zorro-antd-ivy-hd7qrr)

### Steps to reproduce
Use the popover component to display a card containing a button wich open a dropdown

### What is expected?
The dropdown should be opened

### What is actually happening?
ERROR TypeError: Cannot read property 'pipe' of undefined at NzDropDownDirective.ngAfterViewInit (dropdown.directive.ts:118)

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | Opera |

**Comment by Feng-JY** [comment]
https://stackblitz.com/edit/ng-zorro-antd-ivy-7qwgj3?file=src/app/app.component.ts

**Comment by AymericSauty** [comment]
Great, thx a lot !
