### ISSUE TITLE
模块引入报错

### ISSUE THREAD

**Issue by oukingtim** [NG-ZORRO/ng-zorro-antd#69]
WARNING in ./~/ng-zorro-antd/src/components/root/nz-root.component.ts
43:22-30 "export 'DOCUMENT' was not found in '@angular/common'

WARNING in ./~/ng-zorro-antd/src/components/core/floater/floater.service.ts
56:22-30 "export 'DOCUMENT' was not found in '@angular/common'

WARNING in ./~/ng-zorro-antd/src/components/core/floater/floater.service.ts
66:20-28 "export 'DOCUMENT' was not found in '@angular/common'

**Comment by vthinkxie** [comment]
please provide more info

**Comment by 392475992** [comment]
I have this problem, too，i'll Introduce “NgZorroAntdModule.forRoot()” into the rootModule  and introduce <nz-root> in rootComponent.html

**Comment by trotyl** [comment]
Make sure you're using Angular version higher than 4.3.0.

**Comment by LinBoLen** [comment]
aha, forRoot(). deprecated
