### ISSUE TITLE
When the select selector is placed in a container with a scrollbar, the dropdown box float does not follow the container scroll

### ISSUE THREAD

**Issue by maizsss** [NG-ZORRO/ng-zorro-antd#6900]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-soaryj?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-soaryj?file=src/app/app.component.ts)

### Steps to reproduce
1. outer div：height: 100%;overflow: auto;
2. inner div： height: 2000px;
3. Click on the select component and the drop-down box appears；
4. Trigger container scrolling；

### What is expected?
The drop-down box position will follow the scrolling

### What is actually happening?
The position of the dropdown box remains the same and deviates from the position of the select component.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.1 |
| Browser | chrome version 91 |

---
In addition to the select component, others include: DatePicker, Popover and other components with floating layers all have the same problem.
Is there a good solution for a compatible solution?

**Comment by maizsss** [comment]
hello~
The problem has been solved. The scrollbar container is solved by using cdkScrollable.

**Comment by maizsss** [comment]
> > hello~ The problem has been solved. The scrollbar container is solved by using cdkScrollable.
> 
> Could you tell me how to resolve it? I need help

I've updated the solution to the link in stackblitz
https://stackblitz.com/edit/ng-zorro-antd-ivy-8bjm8d?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/13618912/136522919-fa1568b0-791f-4ed8-8930-87d00434ca30.png)

Also, the ScrollingModule needs to be imported.
import {ScrollingModule} from '@angular/cdk/scrolling';

**Comment by zhengsansan** [comment]
> > > hello~ The problem has been solved. The scrollbar container is solved by using cdkScrollable.
> > 
> > 
> > Could you tell me how to resolve it? I need help
> 
> I've updated the solution to the link in stackblitz https://stackblitz.com/edit/ng-zorro-antd-ivy-8bjm8d?file=src/app/app.component.ts
> 
> ![image](https://user-images.githubusercontent.com/13618912/136522919-fa1568b0-791f-4ed8-8930-87d00434ca30.png)
> 
> Also, the ScrollingModule needs to be imported. import {ScrollingModule} from '@angular/cdk/scrolling';

it works，Thank you very much.比心

**Comment by pgarzina** [comment]
anyone found a solution for this inside a zorro table? the cdkScrollable should be added to an element that is the scroll container but in a zorro table the scroll container is not directly accessible in the html file.

**Comment by liyf0520** [comment]
我目前也遇到了相同问题,我没有什么好的方案。使用场景是在一个可编辑的滚动表格中,当某个select在打开的情况下去滚动表格就会出现这个问题了,这个有什么要的处理方法吗
I'm currently having the same problem and I don't have a good solution. The usage scenario is in an editable scrolling table. This problem will occur when a certain select is opened to scroll the table. Is there any way to deal with this?
