### ISSUE TITLE
关于 nz-form-control 组件 nzValidateStatus 属性问题

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#693]
## What problem does this feature solve?

我们会用到 `nzValidateStatus` 几乎是在响应式表单中应用，然后其中 `isError` （[code](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/form/nz-form-control.component.ts#L43)）明显受限于所列的错误状态才会有生效，这导致自定义验证器亦或部分angular内置（例如：`min` 等）会出现无效CSS渲染的问题。

就这一问题的根源来看，我认为是否有错误的判断标准只需要检验 `name.errors` 是否为 `null` 亦可，这种规则不光是 [angular validators](https://github.com/angular/angular/blob/master/packages/forms/src/validators.ts#L110) 在匹配正确的情况下都返回 `null`；当然这一点在自定义检验当中也形成一种默契规则。

## What does the proposed API look like?

nothing

**Comment by vthinkxie** [comment]
There is another `nzValidateStatus` called warning must be taken into consideration.

```typescript
isError = this.nzValidateStatus && this.nzValidateStatus.dirty && this.nzValidateStatus.errors && this.nzValidateStatus.hasError && this.nzValidateStatus.hasError('warning')
```
