### ISSUE TITLE
bug migration 12

### ISSUE THREAD

**Issue by jongomes** [NG-ZORRO/ng-zorro-antd#6940]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
ng-zorro-antd\table\style\index.less (line 11, column 0)

### What is expected?
./src/theme.less - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

@table-header-icon-color-hover: darken(@table-header-icon-color, 10%);
--->  @table-sticky-zindex:  1;

Compiled successfully.

### What is actually happening?
./src/theme.less - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

@table-header-icon-color-hover: darken(@table-header-icon-color, 10%);
---> @table-sticky-zindex: (@zindex-table-fixed + 1);

Not Compiled

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | Edge |

**Comment by acsabi310** [comment]
same here. any update in this?

**Comment by MichaellAlavedraMunayco** [comment]
I need help to solve this

**Comment by joaomvfsantos** [comment]
In our case we have a file that overrides the variables in default.less and `@zindex-table-fixed` changed it's value from `auto` to `2`. When we changed this value to `2` in our custom less file this error was solved.

**Comment by acsabi310** [comment]
thanks, yepp, we had a copy-pasted less file from some earlier version for that "override purpose", and when we deleted the unneccessary rows from there the problem solved. So in our cases it is not an issue any more.

**Comment by jhimelymendoza** [comment]
same here. any update in this?
