### ISSUE TITLE
希望nz-table组件[nzShowPagination]值设置为false时，将[nzFrontPagination]的默认值设置为false

### ISSUE THREAD

**Issue by cnnicknick** [NG-ZORRO/ng-zorro-antd#6947]
## What problem does this feature solve?
新手很容易误以为[nzShowPagination]值为false时前端就不会分页了，导致数据多余10条时前端无法展示所有数据。

## What does the proposed API look like?
无。

**Comment by vthinkxie** [comment]
nzShowPagination 控制展示，nzFrontPagination 控制数据分页，两个职责不同
