### ISSUE TITLE
支持 InputNumber 组件 nzPrecision 能保留输入的精度

### ISSUE THREAD

**Issue by RedzRedz** [NG-ZORRO/ng-zorro-antd#6953]
## What problem does this feature solve?
在一些工业应用中 1.0与1表达了不同的业务意义
如果不设置nzPrecision 在输入1.0时 会被自动转为1
如果设置nzPrecision=2 在输入1.0时 会被自动转为1.00
希望有一种灵活的精度处理方式 可以保留输入的精度
虽然当前nzPrecisionMode提供了回调函数 但是依旧在输入1.0时会自动转为1

## What does the proposed API look like?
1. 增加配置项，允许保留输入的精度

**Comment by C-racker** [comment]
有进展吗，比如输入1.20，保留0而不是自动变成1.2
