### ISSUE TITLE
nz-select 在固定表头的表格中使用，表格滚动时，nz-select 的下拉框和输入框分离

### ISSUE THREAD

**Issue by castelain** [NG-ZORRO/ng-zorro-antd#6956]
### Reproduction link
[https://stackblitz.com/edit/angular-uf44ee?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular-uf44ee?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
1. 创建表格
2. 固定表格的表头
3. 把表格的行改为可编辑的行
4. 可编辑的行中使用 nz-select 组件
5. 触发行编辑状态，打开 select 下拉框，滚动表格
6. 能看到 select 框和 下拉选项框分离了（下拉选项框的 top 样式属性值没有更新）

### What is expected?
下拉选项框和 select 框不分离，可以一起随表格滚动；或者，在有未关闭的 select 下拉选项弹框时，能禁止滚动

### What is actually happening?
nz-select 在固定表头的表格中使用，表格滚动时，nz-select 的下拉选项框和 select 框分离

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.2 |
| Browser | chrome V92 |

**Comment by CharmingGeeker** [comment]
This is my solution:  

add `[nzBackdrop]="true" ` to `nz-select` component. when you open select option list, it will block outside scroll control.

**Comment by castelain** [comment]
Thank you for your reply. This plan can meet my needs.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NG-ZORRO/ng-zorro-antd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 下午2:45
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [NG-ZORRO/ng-zorro-antd] nz-select 在固定表头的表格中使用，表格滚动时，nz-select 的下拉框和输入框分离 (#6956)





 
This is my solution:
 
add [nzBackdrop]="true"  to nz-select component. when you open select option list, it will block outside scroll control.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
