### ISSUE TITLE
Can I use Calendar with External Event Dragging

### ISSUE THREAD

**Issue by zackshine** [NG-ZORRO/ng-zorro-antd#6957]
## What problem does this feature solve?
I just could not find any way to use External Event Dragging on calendar

## What does the proposed API look like?
It can be used in full-calendar like https://fullcalendar.io/docs/external-dragging, so I want to know whether the ant calendar could make it.

**Comment by zackshine** [comment]
Can any developer answer whether it can be done in nz-calendar?I just want to know.

**Comment by zackshine** [comment]
@wenqi73 Or it is not supported in angular ant-design?

**Comment by wenqi73** [comment]
@zackshine Not supported for this.
