### ISSUE TITLE
Nz-Select - Make it look like the fly-down menu is "connected" to the select field

### ISSUE THREAD

**Issue by duxard** [NG-ZORRO/ng-zorro-antd#6960]
## What problem does this feature solve?
Nz-Select - Make it look like the fly-down menu is "connected" to the select field, where there is gap between the bottom of the Select field and the menu (please provide a property to do so if one does not already exist).

Please let us know if there is a way to make it look like the fly-down menu is "connected" to the select field (without any gap between them when the fly-down menu is triggered to appear, so that the top of the menu shares the same bottom border of the select field's rectangle).

If there is no way to close the distance between these two parts today, then please add a property (perhaps calling it "[nzDropdownMenuGap]") where we can just enter in the # of pixels the gap should be (and setting the gap to zero pixels will make it look like the fly down is "connected" to the select field's rectangle).

## What does the proposed API look like?
[nzDropdownMenuGap]

**Comment by simplejason** [comment]
You can use `padding: 0` to overwrite the styles of `.ant-select-dropdown`.

**Comment by duxard** [comment]
Thank you simplejason!
