### ISSUE TITLE
nz-table nzExpand doesn't work without table header

### ISSUE THREAD

**Issue by krokofant** [NG-ZORRO/ng-zorro-antd#6961]
### Reproduction link
[https://stackblitz.com/edit/angular-pty3yf](https://stackblitz.com/edit/angular-pty3yf)

### Steps to reproduce
Remove table header and use nzExpand.
Notice that the expand content doesn't fill the entire row.

### What is expected?
The entire row should be filled. colspan should be set properly.

### What is actually happening?
It breaks. nzExpand doens't fill the row.

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | Chrome/Firefox |

**Comment by simplejason** [comment]
`nz-table` needs `thead` to calculate the table header widtd, you can use `display: none` to hide it, check this demo: https://stackblitz.com/edit/angular-pty3yf-qtnun8
