### ISSUE TITLE
Nz-Select - add an ability to change down arrow icon

### ISSUE THREAD

**Issue by duxard** [NG-ZORRO/ng-zorro-antd#6962]
## What problem does this feature solve?
Hi Team,

May I know if there is a possibility to change/replace the default down arrow with a custom one? (e.g. like the one from Fontawesome https://fontawesome.com/v5.15/icons/caret-down)

![select](https://user-images.githubusercontent.com/18247015/131480405-8dc296cf-ee40-41a1-804c-1ef14c21f278.JPG)

## What does the proposed API look like?
N/A

**Comment by wendellhu95** [comment]
Try `nzSuffixIcon` with a custom template. https://codesandbox.io/s/intelligent-blackwell-k8sxn?file=/src/app/app.component.ts

**Comment by duxard** [comment]
Thanks a lot!
