### ISSUE TITLE
Pattern validation in nz-select for tags mode

### ISSUE THREAD

**Issue by SharmaAayush** [NG-ZORRO/ng-zorro-antd#6963]
## What problem does this feature solve?
I am trying to create an input where the user can either select from pre-defined options or create their own entry as long as the new entry matches a certain pattern (i.e, the entry only contains alpha-numeric characters)

`nz-select` with `nzMode="tags"` seemed like a good solution for my use-case but we can not limit the user provided entries in it based on a pattern (i.e alpha-numeric inputs in my case)

## What does the proposed API look like?
```
<nz-select [(ngModel)]="selectedValue" nzMode="tags" nzPlaceHolder="Select a Value"
  [nzNotFoundContent]="'Type to add a new Value'" [pattern]="'^([0-9a-zA-Z] )$'">
  <nz-option *ngFor="let option of availableValues" [nzValue]="option.value" [nzLabel]="option.label">
  </nz-option>
</nz-select>
```

`pattern` input or a new input can be used to get the regEx and match the user input with provided regex before adding the user provided tag. The user provided tag will only be added if it passes the pattern validation.

**Comment by simplejason** [comment]
you can use `ngModelChange` to validate the input value, we have no plans to support this feature for now, unless antd-design supports it :)
