### ISSUE TITLE
穿梭框能够支持自定义左右两部分的宽度

### ISSUE THREAD

**Issue by MaZhi-A** [NG-ZORRO/ng-zorro-antd#6968]
## What problem does this feature solve?
穿梭框左侧渲染列表自定义为Tree组件，右侧渲染列表为默认列表。<br>
Tree组件层级不超过3级，宽度可以设置小一些；右侧每行数据会拼接多个字段，宽度期望能设置大一些。

## What does the proposed API look like?
<nz-transfer [nzListStyle]="[leftStyleObject, rightStyleObject]"></nz-transfer>

**Comment by simplejason** [comment]
You can modify the styles of the left or right `nz-transfer-list` according to the custom width, for now we have no plans to add this feature if antd doesn't support.
