### ISSUE TITLE
Change checkbox indeterminate check color

### ISSUE THREAD

**Issue by duxard** [NG-ZORRO/ng-zorro-antd#6969]
## What problem does this feature solve?
Hi Team,

I've been wondering is there a way to change checkbox indeterminate check color? E.g. I'd like it to be blue:
![image](https://user-images.githubusercontent.com/18247015/132040714-65e58f1b-9d6e-48ab-8b2a-95bdf22e1775.png)

I didn't find a corresponding Ng-Zorro variable to override.
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/default.less

Thank you

## What does the proposed API look like?
N/A

**Comment by simplejason** [comment]
It is same with `primary-color`, if you want to change the style of `indeterminate` state, you can overwrite `.ant-checkbox-indeterminate .ant-checkbox-inner::after` with any color.

**Comment by duxard** [comment]
Hi, simplejason
thanks a lot for clarification!

**Comment by duxard** [comment]
Thank you simplejason!
