### ISSUE TITLE
Is ng-zorro's webStorm snippet provided?

### ISSUE THREAD

**Issue by asweetonion** [NG-ZORRO/ng-zorro-antd#697]
## What problem does this feature solve?

Entering nz- in webStorm will automatically appear in the smart reminder list

## What does the proposed API look like?

Entering nz- in webStorm will automatically appear in the smart reminder list

**Comment by vthinkxie** [comment]
there is no snippet provided for webstorm yet, you can use https://marketplace.visualstudio.com/items?itemName=cipchk.ng-zorro-vscode with vscode.
pr is welcome

**Comment by asweetonion** [comment]
thank you~

**Comment by HsuanXyz** [comment]
work in progress https://github.com/HsuanXyz/ng-zorro-live-templates/issues/1
