### ISSUE TITLE
The examples in the docs do not work on stackblitz

### ISSUE THREAD

**Issue by rdvitka** [NG-ZORRO/ng-zorro-antd#6976]
### Reproduction link
[https://vtqmqy--run.stackblitz.io](https://vtqmqy--run.stackblitz.io)

### Steps to reproduce
Open the stackblitz page of any example from the documentation

### What is expected?
work examples

### What is actually happening?
None of the examples in the documentation work on stackblitz

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | chrome 93 |

**Comment by hsuanxyz** [comment]
close via #6861
