### ISSUE TITLE
Missing translations for "DatePicker.lang.*" in language "en-gb".

### ISSUE THREAD

**Issue by Bullsized** [NG-ZORRO/ng-zorro-antd#6979]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-tutleq?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-tutleq?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Open console and you will see numerous warnings about missing translations.

### What is expected?
To have the proper translations (which there are for 'en_US').

### What is actually happening?
It is reverting to the 'en_US' translations, instead using the 'en_GB' translations.

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | Chrome, Edge, Firefox |

**Comment by Bullsized** [comment]
Open console and you will see numerous warnings about missing translations.
Image to issue: https://i.imgur.com/19Mn2ju.png
Just add the translation files from 'en_US' to the 'en_GB' files for:
"DatePicker.lang.yearPlaceholder"
"DatePicker.lang.monthPlaceholder"
"DatePicker.lang.weekPlaceholder"
"DatePicker.lang.rangeYearPlaceholder"
"DatePicker.lang.rangeMonthPlaceholder"
"DatePicker.lang.rangeWeekPlaceholder"
It's annoying to receive numerous warnings when testing stuff.

**Comment by wenqi73** [comment]
It's in https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/i18n/languages/en_GB.ts, can you help us to add the translation?

**Comment by Bullsized** [comment]
@wenqi73 https://github.com/NG-ZORRO/ng-zorro-antd/pull/6982
I added all of the missing en_US translations to the en_GB file and submitted a PR. Hope that helped.

**Comment by saeidi-dev** [comment]
The same problem exists in the Persian language.
