### ISSUE TITLE
nzPageIndexChangeClick 

### ISSUE THREAD

**Issue by zhangkang1521** [NG-ZORRO/ng-zorro-antd#698]
## What problem does this feature solve?

I use nzPageIndexChangeClick like this,(nzPageIndexChangeClick)="pageChange(event)", but the event is undefined, what number of page dose the user click ? who know?

## What does the proposed API look like?

(nzPageIndexChangeClick)="pageChange(event)" , event contains pageNo,pageSize and so on

**Comment by trotyl** [comment]
https://stackblitz.com/edit/ng-zorro-antd-setup-hhjsrc?file=app/app.component.html

Working fine here, please provide a reproduction.

**Comment by zhangkang1521** [comment]
thank you, it's work! but I do't know the difference of `event `and `$event`?

**Comment by trotyl** [comment]
`$event` is the keyword indicate the emitted payload, `event` is just a normal property on your component.

https://angular.io/guide/template-syntax#event-and-event-handling-statements

**Comment by soulxy** [comment]
@trotyl
hi, I found it doesnot work, because pf  a spelling error with the function `nzPageIndexChangeClick`  in the [document ](https://ng.ant.design/#/components/table)
