### ISSUE TITLE
Link button is disabled but click event still triggered

### ISSUE THREAD

**Issue by hanjeahwan** [NG-ZORRO/ng-zorro-antd#6983]
### Reproduction link
https://stackblitz.com/edit/ng-zorro-antd-ivy-b6erc9?file=src/app/app.component.ts

### Steps to reproduce
click the disabled link button and check console the click handler is get triggered

### What is expected?
disabled link button should not trigger click handler

### What is actually happening?
click handler get triggered when link button is disabled

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | Microsoft Edge Version 93.0.961.52 (Official build) (64-bit) |

I am upgrade from ng-zorro-antd v10 to v12
this is v10 example https://stackblitz.com/edit/angular-rqnjiy?file=src/app/app.component.ts

**Comment by simplejason** [comment]
Use `button` instead of `a` tag
