### ISSUE TITLE
nz-upload上传成功后支持设置uid

### ISSUE THREAD

**Issue by snowchenlei** [NG-ZORRO/ng-zorro-antd#6984]
## What problem does this feature solve?
文件上传成功后后台会动态生成id，这个id会用于删除和下载。
希望可以将这个id替换nz-upload默认生成的uid

## What does the proposed API look like?
提供一个响应拦截，在这个回调里面可以设置uid、name等参数

**Comment by cipchk** [comment]
删除、预览、下载操作都有对应的事件可以处理，若需要对数据的额外维护，也可以自行 `(nzChange)` 的变更单独处理。
