### ISSUE TITLE
期望增加一个可以被拖动的容器

### ISSUE THREAD

**Issue by songcheng-laosong** [NG-ZORRO/ng-zorro-antd#6987]
## What problem does this feature solve?
可以解决小容器内容溢出，同时不希望出现滚动条，我们可以用鼠标拖动查看溢出的内容。

## What does the proposed API look like?
希望增加两个容器溢出组件，或者作为一个angular的directive实现

**Comment by vthinkxie** [comment]
可以参照 https://material.angular.io/cdk/scrolling/overview 实现你的功能

**Comment by songcheng-laosong** [comment]
> 可以参照 https://material.angular.io/cdk/scrolling/overview 实现你的功能

这个容器是可以进行滚动，但是只能拖动滚动条，或者鼠标滚轮进行操作。如果想要去掉滚动条的，操作方式比较单一。能不能新增鼠标可以拖动的滚动容器？
