### ISSUE TITLE
feat: better integration with Angular i18n

### ISSUE THREAD

**Issue by trotyl** [NG-ZORRO/ng-zorro-antd#699]
## What problem does this feature solve?

Angular is going to use a "one bundle for all locales" strategy in v5 (not 5.0 as we already know), namely all locales with be bundled to app and the locate-to-use is also determined at runtime.

The current design makes it hard to switch locale in runtime, or cause duplication logic on choosing locale data (against Angular i18n itself).

### Using `NgZorroAntdModule`

```typescript
import { NgModule } from '@angular/core'
import { NgZorroAntdModule } from 'ng-zorro-antd'
// for tree-shaking purpose
import { enUS } from 'ng-zorro-antd/locales/en_US'
import { zhCN } from 'ng-zorro-antd/locales/zn_CN'

// convention: the first one is going to be the fallback locale when no match found
const nzLocales = [ enUS, zhCN ] 

@NgModule({
  imports: [
    NgZorroAntdModule.forRoot({ locales: nzLocales })
  ],
})
export class AppModule { }
// Will use the locale according to `LOCALE_ID`.
```

### Using standalone modules by providing manually

<sub>Not available yet, for design purpose.</sub>

```typescript
import { NgModule } from '@angular/core'
// to distinguish with 'locales' for data
import { NZ_LOCALES } from 'ng-zorro-antd/i18n'
// for tree-shaking purpose
import { enUS } from 'ng-zorro-antd/locales/en_US'
import { zhCN } from 'ng-zorro-antd/locales/zn_CN'

// convention: the first one is going to be the fallback locale when no match found
const nzLocales = [ enUS, zhCN ] 

@NgModule({
  providers: [
    { provide: NZ_LOCALES, useValue: nzLocales }
  ]
})
export class AppModule { }
// Will use the locale according to `LOCALE_ID`.
```

### Dynamically changing locale

```typescript
import { Component } from '@angular/core'
import { NzLocaleService } from 'ng-zorro-antd'
// for tree-shaking purpose
import { enUS } from 'ng-zorro-antd/locales/en_US'
import { zhCN } from 'ng-zorro-antd/locales/zn_CN'

// convention: the first one is going to be the fallback locale when no match found
const nzLocales = [ enUS, zhCN ] 

@Component({})
export class AppComponent {
  constructor(private localeService: NzLocaleService) { }

  onLocaleChange(localeId: string): void {
    // passing string is much simpler than handling cached data
    this.localeService.setLocaleId('en-US')
  }
}
// Will use the locale according to `en-US`.
```

### Locale resolution

Consider we have providing several locales like:

```typescript
const nzLocales = [ enUS, zhCN, zhTW ]
```

Then it comes:

LOCALE_ID     | Matched Locale | Note
---------------|-----------------| -------------
`en-US`          | `enUS`               | ideal, exact match
`zh-CN`          | `zhCN`              | ideal, exact match
`zh-TW`         | `zhTW`              | ideal, exact match
`zh-US`          | `zhCN`              | good, language default
`zh-Hans`       | `zhCN`              | ideal, exact match
`zh-Hant`        | `zhTW`              | ideal, exact match
`zh-Hans-CN` | `zhCN`              | ideal, exact match
`zh-Hant-TW` | `zhTW`              | ideal, exact match
`zh-Hans-US` | `zhCN`              | good, language default
`so-ET`            | `enUS`              | OK, application default

<sub>Alias definition required on locale data.</sub>

If user wants to have control over which locale to use based on `LOCALE_ID`, some advanced usage:

```typescript
import { NgModule } from '@angular/core'
import { NgZorroAntdModule, NzLocaleStrategy } from 'ng-zorro-antd'
// for tree-shaking purpose
import { enUS } from 'ng-zorro-antd/locales/en_US'
import { zhCN } from 'ng-zorro-antd/locales/zn_CN'

// convention: the first one is going to be the fallback locale when no match found
const nzLocales = [ enUS, zhCN ]

export class CheatingUserStrategy implements NzLocaleStrategy {
  resolve(localeId: string): string {
    return localeId.startsWith('en') ? 'zh-CN' : 'en-US'
  }

  // or
  resolve(localeId: string): NzLocale {
    return localeId.startsWith('en') ? zhCN : enUS
  }
}

@NgModule({
  imports: [
    NgZorroAntdModule.forRoot({
      locales: nzLocales,
      // or just providing as NzLocaleStrategy
      localeStrategy: CheatingUserStrategy,
    })
  ],
})
export class AppModule { }
// Will use the locale according to `LOCALE_ID`.
```

### Using static locale data

Just look at current documentation.

**Comment by vthinkxie** [comment]
close as implements already.
