### ISSUE TITLE
Select options don't follow select field

### ISSUE THREAD

**Issue by projer** [NG-ZORRO/ng-zorro-antd#7003]
### Reproduction link
[https://angular-tw2hmj.stackblitz.io](https://angular-tw2hmj.stackblitz.io)

### Steps to reproduce
1- Click on the select field
2- Scroll inside the content

### What is expected?
3 things could be expected:
- options are following the select field (unrealistic to me seeing how you're doing it)
- scroll is deactivated as long as an option is not selected
- scrolling closes the options

### What is actually happening?
select field is moving but the options are not following and are staying at the same place.

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.2 |
| Browser | Chrome |

**Comment by abumuawiyah** [comment]
I have this issue too in <nz-select> component. The top, left value is provided by CDK, did we need specified version of CDK for specific version of ngzorro?

**Comment by ParsaArvanehPA** [comment]
This PR will fix the issue mentioned above for all components created with the CDK Overlay that are inside modals or drawers: #8804.


As a temporary fix, you can follow these steps:
- Create a wrapper inside your modal or drawer
- Add the cdkScrollable directive to the wrapper
- Set overflow: auto on the wrapper

This way, the wrapper will handle the scrolling.
You can refer to this [link](https://stackblitz.com/edit/angular-sg8j5f?file=src%2Fapp%2Fapp.component.ts) for a sample.
