### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'nzValue') when pressed arrows on an empty NzSelect

### ISSUE THREAD

**Issue by Bonelol** [NG-ZORRO/ng-zorro-antd#7018]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-kapl5j](https://stackblitz.com/edit/ng-zorro-antd-ivy-kapl5j)

### Steps to reproduce
Click select to open drop down, then press any arrow key. Open DevTools, check error messages

### What is expected?
No error pops up, this should be handled by NgZorro itself

### What is actually happening?
Cannot read properties of undefined (reading 'nzValue')
    at NzSelectComponent.onKeyDown

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | Chrome, Edge |

**Comment by SalehPayandeh** [comment]
65
