### ISSUE TITLE
中文文档错误 全局配置项-如何使用  useValue: { ngZorroConfig }

### ISSUE THREAD

**Issue by magicbing** [NG-ZORRO/ng-zorro-antd#7019]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
https://ng.ant.design/docs/global-config/zh
全局配置项
如何使用
  providers: [
    { provide: NZ_CONFIG, useValue: { ngZorroConfig } }
  ],

### What is expected?
多了个括号

providers: [
    { provide: NZ_CONFIG, useValue: ngZorroConfig }
  ],

### What is actually happening?
不起作用

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | chrome94 |

**Comment by simplejason** [comment]
Thank you for your feedback, feel free to submit a PR fix it if you wish :)

**Comment by simplejason** [comment]
Sorry for this,  I forgot that there is a commit that has fixed this issue. And thanks your feedback again :)
