### ISSUE TITLE
建议 Switch开关可以自定义设置开关值

### ISSUE THREAD

**Issue by luoxiao-xy** [NG-ZORRO/ng-zorro-antd#7025]
## What problem does this feature solve?
建议 Switch开关可以自定义设置开关值。现在Switch开关只支持默认的ture和false的布尔类型，但是如果我先1表示开，0表示关，或者其他的值，却无法实现。

## What does the proposed API look like?
API 参数增加：[nzCheckedValue]  [nzUnCheckedValue] 值可以是string number boolean

**Comment by simplejason** [comment]
暂不支持，按照 switch 设计，是两个互斥条件来开关（on/off），可以自行对其进行二次封装或单独维护一个字段表示状态达到期望的效果
