### ISSUE TITLE
nz-tree-virtual-scroll-view not updates when data inside datasource changes

### ISSUE THREAD

**Issue by oleksandr-codefresh** [NG-ZORRO/ng-zorro-antd#7040]
### Reproduction link
[https://codesandbox.io/s/gifted-pine-ndby2?file=/src/app/app.component.ts](https://codesandbox.io/s/gifted-pine-ndby2?file=/src/app/app.component.ts)

### Steps to reproduce
1. set initial data ( dataSource.setData([]) )
2. set new data (dataSource.setData(yourArrayOfValues) )

### What is expected?
nz-tree-virtual-scroll-view should call `changeDetectionRef.detectChanges()` and re-render list

### What is actually happening?
it updates data array inside of component, but doesn't call `changeDetectionRef.detectChanges()`

| Environment | Info |
|---|---|
| ng-zorro-antd | 11.4.2 |
| Browser | Chrome |

**Comment by simplejason** [comment]
Close this issue  due to #7083 has been merged.

**Comment by genru** [comment]
here is a simlar #7383, please help
