### ISSUE TITLE
V13 update

### ISSUE THREAD

**Issue by simplejason** [NG-ZORRO/ng-zorro-antd#7044]
- [x] Upgrade to angular v13
- [x] Using Ivy to build
- [x] Remove deprecated APIs and add migration schematics
- [ ] #7009 @wendellhu95 

Note:
This should be merged after styles ant-design synced #7099.

**Comment by altso** [comment]
Did you consider starting Angular upgrades _before_ the stable release using Angular vNext beta or even alpha builds? We heavily rely on ng-zorro and it would be nice to have the next version of Angular supported as soon as possible.

**Comment by simplejason** [comment]
> Did you consider starting Angular upgrades _before_ the stable release using Angular vNext beta or even alpha builds? We heavily rely on ng-zorro and it would be nice to have the next version of Angular supported as soon as possible.

Generally, ng-zorro will only follow the stable version of angular. However, some compatibility and upgrade work may also be done in the alpha stage, but it is not recommended for prod env.

**Comment by junchaohu** [comment]
Angular/core V13 is already stable, wish to update ng-zorro-antd to support it, thanks.

**Comment by maratkalibek** [comment]
I suppose that @altso asked to start work on the next release version when RC for Angular is released.

For example, Angular 13 RC was available on Oct 14.

ng-zorro-antd v12 was released two months after Angular 12 release. You can reduce this next version release approx by 1 month when you will start to upgrade with Angular RC version.

**Comment by simplejason** [comment]
> I suppose that @altso asked to start work on the next release version when RC for Angular is released.
> 
> For example, Angular 13 RC was available on Oct 14.
> 
> ng-zorro-antd v12 was released two months after Angular 12 release. You can reduce this next version release approx by 1 month when you will start to upgrade with Angular RC version.

Good advice , no doubt! We will consider it if there is enough time and energy to promote :) also we hope that more people participate in the development of ng-zorro-antd :eyes:

**Comment by RoboZoom** [comment]
> Good advice , no doubt! We will consider it if there is enough time and energy to promote :) also we hope that more people participate in the development of ng-zorro-antd 👀

@simplejason I have no place to complain, and maybe someday I can become a contributor.  But I did want to point out that this is a question more of organization than effort/energy.  This library pledges to upgrade with angular every release- it's a fixed amount of work.  If you start the work 2-4 weeks earlier, it's still the same work, requiring the same time and energy.  You just have a better product sooner.

**Comment by klerick** [comment]
@simplejason Do you have news? When can we see a new version of ng-zorro)

**Comment by cjdxhjj** [comment]
@simplejason is there any progress?

**Comment by simplejason** [comment]
> @simplejason is there any progress?

V13 will be released after we have synchronized the latest styles of ant-design, we will finish processing ASAP :)

**Comment by smile2014** [comment]
Angular 13 has been released for so long, zorro has not synchronized yet

**Comment by dertuerke** [comment]
@simplejason where can you look at the new design?

**Comment by superjulius** [comment]
@dertuerke you can find all the Ant Design sync work [here](https://github.com/NG-ZORRO/ng-zorro-antd/pulls?q=is%3Apr+sync+ant-design)

Ant Design change log can be found [there](https://ant.design/changelog)

**Comment by klerick** [comment]
@superjulius 
Could you please release a new version without sync style (as beta or alpha version)?   
I’m using ng-zooro as a project which is the part of mono repo(nx.dev). And I cannot update nx.dev for 13 version.

**Comment by hsuanxyz** [comment]
@klerick The [style sync action](https://github.com/NG-ZORRO/ng-zorro-antd/actions/workflows/sync-styles.yml) is now working correctly, but the latest styles are blocking our bundling process. @simplejason is actively fixing it, you can track the latest progress through the CI/CD status of #7099.

**Comment by klerick** [comment]
@hsuanxyz Could you please give an approximate estimate? We are waiting for the new version for more than one month. And it is blocking our work:(

**Comment by luoxiao-xy** [comment]
Me too. I hope to release the V13 adapter as soon as possible

**Comment by smile2014** [comment]
Me too. I hope to release the V13 adapter as soon as possible

**Comment by boralbgra** [comment]
I get this error with Angular 13.

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^12.1.0" from ng-zorro-antd@12.1.0
npm ERR! node_modules/ng-zorro-antd
npm ERR!   ng-zorro-antd@"12.1.0" from the root project
npm ERR!

**Comment by heuristicAL** [comment]
@boralbgra If it helps, I'm currently running with the latest version and installed packages using `npm i --legacy-peer-deps` and it works as expected (at least for out use case), even if it's not Angular 13-based.

**Comment by FOWind** [comment]
Can't wait to upgrade to V13.  It's time to try the strictly typed reactive forms experimental features.

**Comment by maratkalibek** [comment]
@simplejason what is the expected release date of ng-zorro-antd@13?

**Comment by smile2014** [comment]
难产了

**Comment by bwinchester** [comment]
> @simplejason what is the expected release date of ng-zorro-antd@13?

Released today
