### ISSUE TITLE
[nzModal] Style cannot apply to modal content

### ISSUE THREAD

**Issue by ambersun1234** [NG-ZORRO/ng-zorro-antd#7061]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-xmiw8l](https://stackblitz.com/edit/ng-zorro-antd-ivy-xmiw8l)

### Steps to reproduce
+ open stackblitz provided above
+ click the *delete button*

### What is expected?
+ The text *Some descriptions* color should be red

### What is actually happening?
+ The text *Some descriptions* color is black

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.2 |
| Browser | Google Chrome Version 95.0.4638.69 (Official Build) (64-bit) |

---
Angular will automatically run sanitize to the content causing the *style* being removed from the content, although we can use [bypassSecurityTrustHtml](https://angular.io/api/platform-browser/DomSanitizer#bypasssecuritytrusthtml) to make it work, but it will cause the security issue.\
I wonder if there's a better way to achieve this

**Comment by souhailharrati** [comment]
Simple solution:

1.  add class in content:
      nzContent: '<b class="content">Some descriptions</b>',
2. add scss script: 
    ::ng-deep .content {
      color: red;
    }

Thanks 👍

**Comment by simplejason** [comment]
The problem is that you are passing html in a string to the nzContent, and angular doesn't trust it. You can pass `template` to `nzContent`.
https://angular.io/api/platform-browser/DomSanitizer
