### ISSUE TITLE
can add a dateRange component  like this 

### ISSUE THREAD

**Issue by WallenHan** [NG-ZORRO/ng-zorro-antd#707]
## What problem does this feature solve?

case: when you need a  date range  in current version  antD,  you should  use two datePicker component  and click  twice for select the date you want.
 maybe  we can make real dateRange  component, just one component and one click ,  **less operation more  efficiency**。

## What does the proposed API look like?

```
[type] = " 'dateRange' "
[format] = " 'YYYY-MM-DD|YYYY-MM-DD' "
```
may like this:
![66667](https://user-images.githubusercontent.com/5639544/33761946-c53ac9ee-dc45-11e7-80ff-36b45c1b6d3a.gif)

**Comment by vthinkxie** [comment]
related #656
