### ISSUE TITLE
modalService.create 创造出来的弹窗设置了nzzindex之后显示异常

### ISSUE THREAD

**Issue by shetz163** [NG-ZORRO/ng-zorro-antd#7072]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-qn2ncx](https://stackblitz.com/edit/ng-zorro-antd-ivy-qn2ncx)

### Steps to reproduce
点击click me 按钮显示效果

### What is expected?
弹窗的正常显示

### What is actually happening?
弹窗在遮罩层下方

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.2 |
| Browser | chrome |

---
cdk-global-overlay-wrapper的z-index的数值依旧为1000, 而非传递的1001,
在stackblitz里的 ng-zorro 11 我无法重现这个情况, 12上面现在是这样的

**Comment by simplejason** [comment]
```typescript
...
constructor(public modal: NzModalService) {}
  // Duplicate identifier 'modal', please rename `modal()` to be `createModal()`
  modal() {
    this.modal.create({
      nzContent: '在ng-zorro 11上无法复现这个情况,但12上可以',
      nzZIndex: 1001,
    });
}
```

**Comment by shetz163** [comment]
> ```ts
> ...
> constructor(public modal: NzModalService) {}
>   // Duplicate identifier 'modal', please rename `modal()` to be `createModal()`
>   modal() {
>     this.modal.create({
>       nzContent: '在ng-zorro 11上无法复现这个情况,但12上可以',
>       nzZIndex: 1001,
>     });
> }
> ```

rename completed

**Comment by shetz163** [comment]
@simplejason how can I REOPEN it?
