### ISSUE TITLE
Need Explicit icon

### ISSUE THREAD

**Issue by rishabh-sonal** [NG-ZORRO/ng-zorro-antd#7090]
## What problem does this feature solve?
It provides Explicit icon for users who want to use it in their application.

## What does the proposed API look like?
`<i nz-icon nzType="explicit"></i>`

**Comment by hullis** [comment]
Could you please describe the API you would like?

**Comment by rishabh-sonal** [comment]
importing NzIconModule from ng-zorro-antd/icon  provides various icons. It would be useful for applications like a music app if it can provide an `Explicit Icon`.

**Comment by hullis** [comment]
Please submit new icon requirement here https://github.com/ant-design/ant-design-icons/issues/71. Thanks!

**Comment by hullis** [comment]
This would be closed. Icon will be added to ng-zorro once after it is added in ant-design-icons. Before that, you could use custom icon instead.
