### ISSUE TITLE
How to change less variable @primary-color online

### ISSUE THREAD

**Issue by huajian123** [NG-ZORRO/ng-zorro-antd#7092]
## What problem does this feature solve?
change customize theme color online

## What does the proposed API look like?
output a function to change the variable

**Comment by DouglasOGarrido** [comment]
Hi @huajian123. I don't know if your question is "how to" or a suggestion for improvement. But if that's how to do it, follow the examples below:

The docs has a nice example how to dynamic change the theme [Ng Zorro - Theme Dynamic Swithing](https://ng.ant.design/docs/customize-theme/en#theme-dynamic-switching). 

There is also another example at [StackOverflow](https://stackoverflow.com/a/61901235/4640746).

Having a function in Zorro's own ecosystem would be very interesting, it would facilitate development.

**Comment by huajian123** [comment]
@DouglasOGarrido Hi,I want to change the primary-color online,not change the dark theme online.There is my demo[http://124.71.128.53:8081/](url)  and you can login it.On the theme setting button on the right, clicking the switch theme color does not take effect, I don’t know how to implement it，There is source code [https://github.com/huajian123/ng-ant-admin](url) .Thank you very much

**Comment by DouglasOGarrido** [comment]
Hi @huajian123. The name "dark" doesn't mean anything. Could be also "primary-color-theme", "primary-color-2-theme", etc. The point is, you have to create another theme file, but change only the "@primary-color" variable. You don't have to change all others variables, just one. But to change that, you have to change the theme.

**Comment by huajian123** [comment]
@DouglasOGarrido Thank you, I understand what you mean, I have two themes, one is dark and the other is bright. There are a total of 8 primary-color colors. If I follow your idea, there must be 2*8 theme files, which is too big. I don’t know if my meaning is clear. Thank you very much

**Comment by DouglasOGarrido** [comment]
@huajian123 that's a lot hahaha. Now I understand. I don't know any other method to do that, how I said, would be very insterestin if Zorro's own ecosystem have this embedded.

If I discover other way to do that, I will post here. Meanwhile, post that question on StackOverflow, there's so much more people to help with that.

**Comment by huajian123** [comment]
@DouglasOGarrido Thank you for your reply.

**Comment by huajian123** [comment]
@DouglasOGarrido  Thank you for your help
