### ISSUE TITLE
can not install with nodejs 16.13.1

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [NG-ZORRO/ng-zorro-antd#7106]
### Reproduction link
stackblitz can not reproduce
~~[https://stackblitz.com/](https://stackblitz.com/)~~

### Steps to reproduce
```sh
npm install -g @angular/cli
ng new demo
cd demo
ng add ng-zorro-antd
```

### What is expected?
成功安装

### What is actually happening?
```sh
$ ng add ng-zorro-antd
ℹ Using package manager: npm
⚠ Unable to find compatible package.  Using 'latest' tag.
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

The package ng-zorro-antd@12.1.0 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: demo@0.0.0
npm ERR! Found: @angular/animations@13.0.3
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^12.1.0" from ng-zorro-antd@12.1.0
npm ERR! node_modules/ng-zorro-antd
npm ERR!   ng-zorro-antd@"12.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mmc/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mmc/.npm/_logs/2021-12-06T03_07_36_607Z-debug.log
✖ Package install failed, see above
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.1.0 |
| Browser | not necessary |

```sh
$ nvm list
->     v16.13.1
default -> stable (-> v16.13.1)

node --version
v16.13.1
```

---
yarn add ng-zorro-antd 能成功安装，安装以后，再执行 ng add ng-zorro-antd， 会让你选择语言，是不是创建side menu等等，但是最后还是一样的错误

**Comment by chenc041** [comment]
看着像是 你本地安装的 @angular/cli 和 ng-zorro-antd 依赖的 @angular/cli 的版本不一致导致的
建议你把本地安装的 @angular/cli 的版本改成和ng-zorro-antd 一致试试

**Comment by ziyouchutuwenwu** [comment]
全局安装 cli
```sh
npm install -g @angular/cli
```

项目里面的 package.json

```json
{
  "name": "demo",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.4",
    "@angular/cli": "~13.0.4",
    "@angular/compiler-cli": "~13.0.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.4.3"
  }
}
```

重新安装 angular cli

```sh
npm uninstall -g @angular/cli
npm install -g @angular/cli@13.0.0
```

```sh
$ ng version                        

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.0
Node: 16.13.1
Package Manager: npm 8.1.2
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.0 (cli-only)
@angular-devkit/core         13.0.0 (cli-only)
@angular-devkit/schematics   13.0.0 (cli-only)
@schematics/angular          13.0.0 (cli-only)
```

重新创建项目

```sh
ng new demo
cd demo
ng add ng-zorro-antd
```

还是不行

```sh
$ ng add ng-zorro-antd
ℹ Using package manager: npm
⚠ Unable to find compatible package.  Using 'latest' tag.
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

The package ng-zorro-antd@12.1.0 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: demo@0.0.0
npm ERR! Found: @angular/animations@13.0.3
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.0.0-next.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^12.1.0" from ng-zorro-antd@12.1.0
npm ERR! node_modules/ng-zorro-antd
npm ERR!   ng-zorro-antd@"12.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mmc/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mmc/.npm/_logs/2021-12-06T13_41_04_021Z-debug.log
✖ Package install failed, see above.
```

package.json

```json
{
  "name": "demo",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.0.0-next.0",
    "@angular/common": "~13.0.0-next.0",
    "@angular/compiler": "~13.0.0-next.0",
    "@angular/core": "~13.0.0-next.0",
    "@angular/forms": "~13.0.0-next.0",
    "@angular/platform-browser": "~13.0.0-next.0",
    "@angular/platform-browser-dynamic": "~13.0.0-next.0",
    "@angular/router": "~13.0.0-next.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.0",
    "@angular/cli": "~13.0.0",
    "@angular/compiler-cli": "~13.0.0-next.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.4.3"
  }
}
```

**Comment by chenc041** [comment]
> 全局安装 cli
> 
> ```shell
> npm install -g @angular/cli
> ```
> 
> 项目里面的 package.json
> 
> ```json
> {
>   "name": "demo",
>   "version": "0.0.0",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "watch": "ng build --watch --configuration development",
>     "test": "ng test"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "~13.0.0",
>     "@angular/common": "~13.0.0",
>     "@angular/compiler": "~13.0.0",
>     "@angular/core": "~13.0.0",
>     "@angular/forms": "~13.0.0",
>     "@angular/platform-browser": "~13.0.0",
>     "@angular/platform-browser-dynamic": "~13.0.0",
>     "@angular/router": "~13.0.0",
>     "rxjs": "~7.4.0",
>     "tslib": "^2.3.0",
>     "zone.js": "~0.11.4"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~13.0.4",
>     "@angular/cli": "~13.0.4",
>     "@angular/compiler-cli": "~13.0.0",
>     "@types/jasmine": "~3.10.0",
>     "@types/node": "^12.11.1",
>     "jasmine-core": "~3.10.0",
>     "karma": "~6.3.0",
>     "karma-chrome-launcher": "~3.1.0",
>     "karma-coverage": "~2.0.3",
>     "karma-jasmine": "~4.0.0",
>     "karma-jasmine-html-reporter": "~1.7.0",
>     "typescript": "~4.4.3"
>   }
> }
> ```
> 
> 重新安装 angular cli
> 
> ```shell
> npm uninstall -g @angular/cli
> npm install -g @angular/cli@13.0.0
> ```
> 
> ```shell
> $ ng version                        
> 
>      _                      _                 ____ _     ___
>     / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
>    / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
>   / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
>  /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
>                 |___/
>     
> 
> Angular CLI: 13.0.0
> Node: 16.13.1
> Package Manager: npm 8.1.2
> OS: linux x64
> 
> Angular: 
> ... 
> 
> Package                      Version
> ------------------------------------------------------
> @angular-devkit/architect    0.1300.0 (cli-only)
> @angular-devkit/core         13.0.0 (cli-only)
> @angular-devkit/schematics   13.0.0 (cli-only)
> @schematics/angular          13.0.0 (cli-only)
> ```
> 
> 重新创建项目
> 
> ```shell
> ng new demo
> cd demo
> ng add ng-zorro-antd
> ```
> 
> 还是不行
> 
> ```shell
> $ ng add ng-zorro-antd
> ℹ Using package manager: npm
> ⚠ Unable to find compatible package.  Using 'latest' tag.
> ⚠ Package has unmet peer dependencies. Adding the package may not succeed.
> 
> The package ng-zorro-antd@12.1.0 will be installed and executed.
> Would you like to proceed? Yes
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: demo@0.0.0
> npm ERR! Found: @angular/animations@13.0.3
> npm ERR! node_modules/@angular/animations
> npm ERR!   @angular/animations@"~13.0.0-next.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/animations@"^12.1.0" from ng-zorro-antd@12.1.0
> npm ERR! node_modules/ng-zorro-antd
> npm ERR!   ng-zorro-antd@"12.1.0" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /home/mmc/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/mmc/.npm/_logs/2021-12-06T13_41_04_021Z-debug.log
> ✖ Package install failed, see above.
> ```
> 
> package.json
> 
> ```json
> {
>   "name": "demo",
>   "version": "0.0.0",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "watch": "ng build --watch --configuration development",
>     "test": "ng test"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "~13.0.0-next.0",
>     "@angular/common": "~13.0.0-next.0",
>     "@angular/compiler": "~13.0.0-next.0",
>     "@angular/core": "~13.0.0-next.0",
>     "@angular/forms": "~13.0.0-next.0",
>     "@angular/platform-browser": "~13.0.0-next.0",
>     "@angular/platform-browser-dynamic": "~13.0.0-next.0",
>     "@angular/router": "~13.0.0-next.0",
>     "rxjs": "~7.4.0",
>     "tslib": "^2.3.0",
>     "zone.js": "~0.11.4"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~13.0.0",
>     "@angular/cli": "~13.0.0",
>     "@angular/compiler-cli": "~13.0.0-next.0",
>     "@types/jasmine": "~3.10.0",
>     "@types/node": "^12.11.1",
>     "jasmine-core": "~3.10.0",
>     "karma": "~6.3.0",
>     "karma-chrome-launcher": "~3.1.0",
>     "karma-coverage": "~2.0.3",
>     "karma-jasmine": "~4.0.0",
>     "karma-jasmine-html-reporter": "~1.7.0",
>     "typescript": "~4.4.3"
>   }
> }
> ```

你把全局安装的 @angular/cli 改成 12.1.0 的版本 node 版本改成 14.18.2 再试试

**Comment by ziyouchutuwenwu** [comment]
node换成 14.18.2 解决，非常感谢
