### ISSUE TITLE
请问12版本less编译报错问题如何解决？

### ISSUE THREAD

**Issue by 13776668267** [NG-ZORRO/ng-zorro-antd#7117]
### Reproduction link
[]

### Steps to reproduce
angular9升级到12，然后升级ng-zorro-antd到12，ng build编译APP
./themes/default/index.less - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/less-loader/dist/cjs.js):

// ================================================================
.table-size(~'middle', @table-padding-vertical-md, @table-padding-horizontal-md, @table-font-size-md);
^
Operation on an invalid type
      Error in D:\idesign\angular12-dev\idesign-app-platform\node_modules\ng-zorro-antd\table\style\size.less (line 39, column 0)
    at processResult (D:\idesign\angular12-dev\idesign-app-platform\node_modules\webpack\lib\NormalModule.js:713:19)
    at D:\idesign\angular12-dev\idesign-app-platform\node_modules\webpack\lib\NormalModule.js:819:5
    at D:\idesign\angular12-dev\idesign-app-platform\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\idesign\angular12-dev\idesign-app-platform\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (D:\idesign\angular12-dev\idesign-app-platform\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.lessLoader (D:\idesign\angular12-dev\idesign-app-platform\node_modules\@angular-devkit\build-angular\node_modules\less-loader\dist\index.js:54:5)

### What is expected?
解决方法

### What is actually happening?
编译失败

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.2 |
| Browser | chrome |

**Comment by simplejason** [comment]
建议逐版本升级，并参考 angular 与 ng-zorro-antd 升级文档
