### ISSUE TITLE
About the usage of tree-view trackBy attribute

### ISSUE THREAD

**Issue by lycHub** [NG-ZORRO/ng-zorro-antd#7118]
### Reproduction link
[https://stackblitz.com/edit/angular-xdjeqe?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-xdjeqe?file=src/app/app.component.ts)

### Steps to reproduce
Click the remove button at the top to delete the last node

### What is expected?
Delete the last node, the arrow of its parent node disappears

### What is actually happening?
The arrow of its parent node will not disappear

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.1.0 |
| Browser | edge |

---
In order to prevent washing the entire tree every time, I used the trackBy attribute

**Comment by plakyda-codefresh** [comment]
@lycHub, @hsuanxyz  prepared PR for this issue
[PR](https://github.com/NG-ZORRO/ng-zorro-antd/pull/7150)
