### ISSUE TITLE
建议：add Tags Input

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd#715]
## What problem does this feature solve?

for managing tags

## What does the proposed API look like?

example：
[https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/](https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)

**Comment by vthinkxie** [comment]
please check https://ng.ant.design/#/components/select

**Comment by dusdong** [comment]
select 控件是选择录入的；我的建议是 input 框，直接录入，输入“,” 可形成 tag

**Comment by dusdong** [comment]
不好意思，select 的确有录入tag的功能，要是能够隐藏后面的下拉按钮就好了，呵呵
