### ISSUE TITLE
nz-input textarea 在 formControlName 下， disabled 属性不生效

### ISSUE THREAD

**Issue by msyesyan** [NG-ZORRO/ng-zorro-antd#7167]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-uda7th](https://stackblitz.com/edit/ng-zorro-antd-ivy-uda7th)

### Steps to reproduce
直接打开重现链接，点击按钮，应该可以切换 disabled 状态，但是并没有

### What is expected?
点击按钮，可以 toggle disabled  状态

### What is actually happening?
没反映

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.1 |
| Browser | Chrome |

---
我们实际代码是 12.0.1, 但是 stackblitz 里是 11 版本，但其实都一样，12 也有同样问题，只不过那个 stackblitz 链接给的是 v11 的代码，自己换 12 又太麻烦了。我们代码中需要如下策略：
1. OnPush 策略
2. formControlName

**Comment by yangjunhan** [comment]
Hi, @msyesyan. There are some mistakes made in your reproduction. A better way to manipulate formControl's disabled:
``` typescript
@Component({
  selector: 'nz-demo',
  template: `
    <form [formGroup]="formGroup">
      <button nz-button nzType="primary" (click)="toggle()"> Enable </button>
      <textarea nz-input formControlName="text"></textarea>
    </form>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class NzDemoInputBasicComponent {
  formGroup: FormGroup;
  private _disable = false;

  constructor(private cdr: ChangeDetectorRef) {
    this.formGroup = new FormGroup({
      text: new FormControl({ value: '', disabled: false })
    });
  }

  toggle(): void {
    if (this._disable) {
      this.formGroup.get('text')?.enable();
    } else {
      this.formGroup.get('text')?.disable();
    }
    this._disable = !this._disable;
    this.cdr.markForCheck();
  }
}

```

**Comment by msyesyan** [comment]
thanks,
