### ISSUE TITLE
V13 Icon broken due to rxjs dependency conflict

### ISSUE THREAD

**Issue by umaim** [NG-ZORRO/ng-zorro-antd#7168]
### Reproduction link
[https://github.com/ant-design/ant-design-icons/blob/af69440ddb02b1a417716d26a40904eebee6d70e/packages/icons-angular/src/package.json#L17](https://github.com/ant-design/ant-design-icons/blob/af69440ddb02b1a417716d26a40904eebee6d70e/packages/icons-angular/src/package.json#L17)

### Steps to reproduce
Environment:
```
Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.5.1
typescript                      4.5.4
```

- Upgrade Angular v12 to v13 (also upgrade rxjs to v7)
- Upgrade ng-zorro-antd to v13.0.0
- Remove `package-lock.json`
- Remove `node_modules`
- Remove `.angular/cache`
- Re-`npm install` the project with some WARNINGs below
```
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> xxxxxxx@xxx prepare
> husky install

husky - Git hooks installed

added 1313 packages, and audited 1314 packages in 2m

135 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

- Then modules not found
```
import { IconDefinition } from '@ant-design/icons-angular';
import { DeleteOutline } from '@ant-design/icons-angular/icons';
```

- Dive into dependencies, can not found `@ant-design/icons-angular` under `node_modules`

- Install `@ant-design/icons-angular` manually: `npm install @ant-design/icons-angular`, with error below
```
npm ERR! Found: rxjs@7.5.1
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"^7.5.1" from the root project
npm ERR!   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/common@13.1.1
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"~13.1.1" from the root project
npm ERR!     peer @angular/common@"^13.0.1" from @ant-design/icons-angular@13.0.1
npm ERR!     node_modules/@ant-design/icons-angular
npm ERR!       @ant-design/icons-angular@"*" from the root project
npm ERR!     1 more (@angular/platform-browser)
npm ERR!   1 more (@angular/core)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.4.0" from @ant-design/icons-angular@13.0.1
npm ERR! node_modules/@ant-design/icons-angular
npm ERR!   @ant-design/icons-angular@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
```

Dive into `@ant-design/icons-angular` source code, found a outdated rxjs dependency [here](https://github.com/ant-design/ant-design-icons/blob/af69440ddb02b1a417716d26a40904eebee6d70e/packages/icons-angular/src/package.json#L17)

### What is expected?
Bump rxjs dependency in `@ant-design/icons-angular` to v7

### What is actually happening?
Wrong rxjs peer dependency. Icon not work.

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.0.0 |
| Browser | Edge 96 |

---
Bump rxjs dependency in `@ant-design/icons-angular` package.
https://github.com/ant-design/ant-design-icons/tree/master/packages/icons-angular

**Comment by qyjs** [comment]
> rxjs                            7.5.1

Rxjs uses 7.4 0 version

**Comment by Diluka** [comment]
@umaim fixed by https://github.com/ant-design/ant-design-icons/pull/514 version >= `13.0.2`
