### ISSUE TITLE
Less resolver error for NgZorro Themes (NgZorro v13 upgrade)

### ISSUE THREAD

**Issue by merih-bb** [NG-ZORRO/ng-zorro-antd#7171]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-hxizgr](https://stackblitz.com/edit/ng-zorro-antd-ivy-hxizgr)

### Steps to reproduce
**Code:**
// Import the official default less style file
@import "~ng-zorro-antd/ng-zorro-antd.less";

**Error:**
Less resolver error: '~ng-zorro-antd/ng-zorro-antd.less' wasn't found. 

### What is expected?
I expect to import NgZorro Themes correctly

### What is actually happening?
After I upgraded NgZorro version to 13, I started getting "Less resolver error" for NgZorro Themes. 

**Code:**
// Import the official default less style file
@import "~ng-zorro-antd/ng-zorro-antd.less";

**Error:**
Less resolver error:
'~ng-zorro-antd/ng-zorro-antd.less' wasn't found. Tried - /Users/XXXX/Development/workspaces/Testinium/Xxxx/frontend/xxx-web/src/~ng-zorro-antd/ng-zorro-antd.less,npm://~ng-zorro-antd/ng-zorro-antd.less,~ng-zorro-antd/ng-zorro-antd.less

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.0.0 |
| Browser | Chrome |

**Comment by merih-bb** [comment]
Problem solved. I imported it wrong. Indeed, this is how it should be.
@import "../node_modules/ng-zorro-antd/ng-zorro-antd.less";

**Comment by saeidi-dev** [comment]
I have this problem

**Comment by fsbflavio** [comment]
using "~" at the beginning doesn't work for me, I simply removed it and it works:
`@import ng-zorro-antd/ng-zorro-antd.less`
