### ISSUE TITLE
api中代码示例看不到，点击没有效果

### ISSUE THREAD

**Issue by google88888888** [NG-ZORRO/ng-zorro-antd#718]
## Version

0.6.4

## Environment

api中代码示例看不到，点击没有效果

## Reproduction link

[https://ng.ant.design/issue-helper/#/new-issue](https://ng.ant.design/issue-helper/#/new-issue)

## Steps to reproduce

api中代码示例看不到，点击没有效果

## What is expected?

api中代码示例看不到，点击没有效果

## What is actually happening?

api中代码示例看不到，点击没有效果

**Comment by vthinkxie** [comment]
![default](https://user-images.githubusercontent.com/1506722/33803606-c8ccf2be-ddce-11e7-9dd6-467159e643ff.png)
