### ISSUE TITLE
Sidebar collapse icon issue

### ISSUE THREAD

**Issue by Vikramalakshman** [NG-ZORRO/ng-zorro-antd#7186]
![SidebarICollapseIcon](https://user-images.githubusercontent.com/73377984/148087435-d0817875-f5db-492a-bf28-55356275ffeb.PNG)
### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
```

1. Go to the official website: https://ng.ant.design/components/me![SidebarICollapseIcon](https://user-images.githubusercontent.com/73377984/148087472-1cd9103d-7d79-4b6e-8858-988049f89a91.PNG)
2. then just click once on the collapse icon and do not move the cursor and now the double icon issue could be noticable

```

### What is expected?
Collapse icon should appear only once when it is clicked even after page reload

### What is actually happening?
Sidebar collapse icon is appearing twice when it is clicked first time after reload

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.0.0 |
| Browser | Chrome |

---
this double icon issue comes only once per page successful loading
but this issue is not happening in stackblitz
this bug is presented in (ng.ant.design) official page

**Comment by yangjunhan** [comment]
@wendellhu95 I think this is related to the **Icon Module** and caused by the perf PR #7071 , which `setSVGData` method is running outside the Angular zone. Could you help take a look at it?
