### ISSUE TITLE
弹出层NzModalSubject的泛型类型有问题，导致代码大量报错“export declare class NzModalSubject extends Subject<any>”

### ISSUE THREAD

**Issue by fuybooo** [NG-ZORRO/ng-zorro-antd#719]
## Version

0.6.4

## Environment

0.6.4

## Reproduction link

[http://www.a.com](http://www.a.com)

## Steps to reproduce

1.升级到0.6.4
2.运行项目npm start
3.编译不通过：Argument of type '{ type: string; data: any[]; }' is not assignable to parameter of type 'string'
    1.注入NzModalSubject：constructor(
    private subject: NzModalSubject,
    ) { }，
    2.使用subject发送自定义事件：this.subject.next({type: 'save'});
    3.此时会报错：subject的泛型不支持any，只支持string。
    4.问题根源：nz-modal-subject.service.d.ts文件的第二行：
```
export declare class NzModalSubject extends Subject<string> {应该改为export declare class NzModalSubject extends Subject<any> {

```
## What is expected?

nz-modal-subject.service.d.ts文件的第二行：export declare class NzModalSubject extends Subject<string> {应该改为export declare class NzModalSubject extends Subject<any> {
这样能够支持更多的自定义事件。

## What is actually happening?

NzModalSubject：subject的泛型不支持any，只支持string。

## Other?

弹出框发送自定义事件时传递的类型可以是any，这样支持的事件更多。之前的版本是any类型的，代码能够正常启动，但是更新之后，报错，导致项目出现较大的问题。

**Comment by vthinkxie** [comment]
@trotyl

**Comment by vthinkxie** [comment]
@fuybooo , you can use 0.6.3 now, we will fix it soon.

**Comment by vthinkxie** [comment]
@fuybooo please try it again in 0.6.5 version.

**Comment by fuybooo** [comment]
OK,Thank you!
