### ISSUE TITLE
After updating to V13 icons are missing | node-module @ant-design/icons-angular/icons missing

### ISSUE THREAD

**Issue by Neru87** [NG-ZORRO/ng-zorro-antd#7198]
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-forked-xl483?file=/src/app/app.module.ts](https://codesandbox.io/s/ng-zorro-antd-ivy-forked-xl483?file=/src/app/app.module.ts)

### Steps to reproduce
1. Create a new Angular Projekt. 
2. Install NgZorro. Optional: Choose Dynamic Icon loading.
3. The Node-Module @ant-design/icons-angular/icons is missing

### What is expected?
node-module @ant-design/icons-angular/icons in place

### What is actually happening?
It was deleted after Updating. Still not there after fresh install.

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.0.0 |
| Browser | Chrome |

---
This is not happening in the Sanbox example

**Comment by Neru87** [comment]
I testet it again with 13.0.1

1. Created a new Angular Application
2. ng add ng-zorro-antd
        Dynamic Icon loading = Y
3. ng serve
4. Error
![error](https://user-images.githubusercontent.com/97506275/151781618-84408bf4-8313-41b3-a8ea-9254a16d7c59.png)

**Comment by wendellhu95** [comment]
Hi. I tried to reproduce the error but everything looks good. Could you please upload a repo or something so I can investigate into this? Thanks! <img width="1290" alt="截屏2022-02-06 22 35 08" src="https://user-images.githubusercontent.com/12122021/152685884-02dba474-e291-492a-9dc9-7bf671659351.png">

**Comment by Neru87** [comment]
Hi @wendellhu95 , here is the repository.
https://github.com/Neru87/Icon-Test

Steps to reproduce:
1. npm install
2. ng serve
3. Error (@ant-design/icons-angular/icons missing)

**Comment by Neru87** [comment]
Issue can be closed. After updating node.js (version 16.13.0 => 16.13.2) and npm (version 8.1.0 -> 8.4.1) everything is working as expected.
