### ISSUE TITLE
Engineering: re-implement Cascader on the top of Select

### ISSUE THREAD

**Issue by wzhudev** [NG-ZORRO/ng-zorro-antd#7207]
- [ ] Support borderless mode #7114
- [x] Support multi-select #6981

**Comment by FOWind** [comment]
Any update here?

**Comment by simplejason** [comment]
@hullis Do you want to refactor this component?

**Comment by FOWind** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/pull/7115
@simplejason I have been doing some work on it. May be you can continue on it.

**Comment by hullis** [comment]
> @hullis Do you want to refactor this component?

Yes but I am lack of time to do it. Anyone interested in this could take it over.

**Comment by Laffery** [comment]
all subtask closed
