### ISSUE TITLE
树形组件（nz-tree）添加nzTreeTemplate属性（自定义属性），拖拽的时候目标对象拖拽线不会出现

### ISSUE THREAD

**Issue by churjan** [NG-ZORRO/ng-zorro-antd#7209]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-vurf2u?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-vurf2u?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
拖拽树形组件

### What is expected?
加了自定义字节 nzTreeTemplate 这个属性，拖拽的时候，目标节点也要出现放置位置的拖拽线

NzFormatBeforeDropEvent props
pos 放置位置(-1:目标节点前面, 0: 目标节点内部, 1: 目标节点后面)

### What is actually happening?
加了自定义字节 nzTreeTemplate 这个属性,不出现拖拽线。
除非我把[nzTreeTemplate]="treeTemplateTpl" 这个属性删除

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.1.1 |
| Browser | chrome |

**Comment by HyperLife1119** [comment]
Close via #7579.
