### ISSUE TITLE
Ant Design Pro with Angular13

### ISSUE THREAD

**Issue by huajian123** [NG-ZORRO/ng-zorro-antd#7213]
## What problem does this feature solve?
online demo http://124.71.128.53:8080/
source code https://github.com/huajian123/ng-ant-admin
I hope to be recommended on the official website

## What does the proposed API look like?
I hope to be recommended on the official website

**Comment by simplejason** [comment]
感谢社区同学的努力，针对项目的几个建议：
1、使用者调研页面（https://github.com/NG-ZORRO/ng-zorro-antd/issues/1142）添加部分展示图，让更多的人了解此项目，吸引更多的人参与，具备一定降低二次开发难度的脚手架最好
2、关于开发，可参考一定的 commit 规范，最好是语义化的 commit message，如 ng-zorro 参考的规范（https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#rules ） 
来源于google angular 规范：https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#

**Comment by palmtreefrb** [comment]
Some issues on mobile...
![Screenshot from 2022-01-22 08-13-05](https://user-images.githubusercontent.com/7799495/150646635-5742f97c-535a-44be-8437-073a66972c21.png)

**Comment by huajian123** [comment]
@palmtreefrb thank you very much

**Comment by huajian123** [comment]
@palmtreefrb I fixed it，Thank you
