### ISSUE TITLE
should support node v16 as part of engines field in package.json

### ISSUE THREAD

**Issue by yangjunhan** [NG-ZORRO/ng-zorro-antd#7225]
## What problem does this feature solve?
For users who are globally installed node v16.X, `npm install ng-zorro-antd` does not install its dependencies automatically.

## What does the proposed API look like?
For `package.json`:
```json
"engines": {
    "node": "^12.20.0 || ^14.0.0 || ^16.0.0"
  }
```

**Comment by hsuanxyz** [comment]
Duplicate #7177
