### ISSUE TITLE
inputNumber supports new apis

### ISSUE THREAD

**Issue by yangjunhan** [NG-ZORRO/ng-zorro-antd#7228]
## What problem does this feature solve?
Reference PRs from Ant Design:
https://github.com/ant-design/ant-design/pull/31432
https://github.com/ant-design/ant-design/pull/31548

## What does the proposed API look like?
- `[nzAddonBefore]`
- `[nzAddonAfter]`
- `[nzPrefix]`
- `[nzControls]`
- `[nzBorderless]`

**Comment by Laffery** [comment]
outdated
