### ISSUE TITLE
add kk_KZ to i18n

### ISSUE THREAD

**Issue by YenbakhtovMaxim** [NG-ZORRO/ng-zorro-antd#7237]
## What problem does this feature solve?
adds kk_KZ translation

## What does the proposed API look like?
import { kk_KZ } from 'ng-zorro-antd/i18n';

**Comment by chenc041** [comment]
> how can I push my feature?

check this
[CONTRIBUTING](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md)

**Comment by wenqi73** [comment]
Ref https://github.com/NG-ZORRO/ng-zorro-antd/pull/7220

**Comment by YenbakhtovMaxim** [comment]
![image](https://user-images.githubusercontent.com/13758747/154078169-e559cc9b-99e5-4f87-baf6-e16d9cb584b2.png)
I can not push - Permission to NG-ZORRO/ng-zorro-antd.git denied to deploy key

**Comment by YenbakhtovMaxim** [comment]
![image](https://user-images.githubusercontent.com/13758747/154078572-8a1aa979-6be4-49cb-84bf-7412446cb8ed.png)

**Comment by chenc041** [comment]
1. fork ng-zorro
2. check a new branch from your forked repo
3. push feature to your forked repo
4. submit pr to ng-zorro from your forked repo

**Comment by YenbakhtovMaxim** [comment]
Thank you. It works.

**Comment by chenc041** [comment]
nice
