### ISSUE TITLE
nz-upload when use nzCustomRequest can't access class variable

### ISSUE THREAD

**Issue by tangjwtj** [NG-ZORRO/ng-zorro-antd#7238]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-lh9ihe?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-lh9ihe?file=src/app/app.component.ts)

### Steps to reproduce
1. Define custom upload function
2. Access class variable in custom function
3. Use console.log print class variable 

### What is expected?
In nzCustomRequest function can access class variable

### What is actually happening?
In nzCustomRequest function, all class variable can't access,  the console.log result show undefined

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.0.1 |
| Browser | chrome |

**Comment by cipchk** [comment]
Must use `=>` to define the method:

```diff
- upload(item: NzUploadXHRArgs) {
+ upload = (item: NzUploadXHRArgs): Subscription => {
```
