### ISSUE TITLE
bug: date-picker [nzShowTime] do not work

### ISSUE THREAD

**Issue by HsuanXyz** [NG-ZORRO/ng-zorro-antd#724]
## Version

0.6.5

## Reproduction link

[https://ng.ant.design/#/components/date-picker](https://ng.ant.design/#/components/date-picker)

## Steps to reproduce

https://ng.ant.design/#/components/date-picker

## What is expected?

show time-picker

## What is actually happening?

not show

**Comment by trotyl** [comment]
Confirmed, didn't consider mixed type (boolean & non-boolean) when simplify showcase usage.
