### ISSUE TITLE
IconNotFoundError when using dynamically loaded icons with Angular Universal

### ISSUE THREAD

**Issue by nicholasgerard** [NG-ZORRO/ng-zorro-antd#7240]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/f40aad9393930e7ff595cdf4679beb374414a572/components/icon/icon.directive.ts#L139](https://github.com/NG-ZORRO/ng-zorro-antd/blob/f40aad9393930e7ff595cdf4679beb374414a572/components/icon/icon.directive.ts#L139)

### Steps to reproduce
1. Create a project with Angular Universal
2. Attempt to use dynamically loaded SVG icons as described in docs with `nz-icon`
3. Build for SSR and run locally
4. App crashes

### What is expected?
Icons are loaded

### What is actually happening?
```
Angular is running on http://localhost:4000
Angular is running in development mode. Call enableProdMode() to enable production mode.
/Users/xxx/Documents/yyy/dist/zzz/server/main.js:309464
              throw error;
              ^

Error: [@ant-design/icons-angular]:the icon delete-o does not exist or is not registered.
    at IconNotFoundError (/Users/xxx/Documents/yyy/dist/zzz/server/main.js:477160:10)
    at /Users/xxx/Documents/yyy/dist/zzz/server/main.js:477315:15
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.0.1 |
| Browser | Any |

---
See refactor of `changeIcon2`  in `NzIconDirective` 12.1.1:

https://github.com/NG-ZORRO/ng-zorro-antd/blob/f40aad9393930e7ff595cdf4679beb374414a572/components/icon/icon.directive.ts#L139

It appears this throws the above error when running in a Node environment (e.g. Angular Universal).

**Comment by arturovt** [comment]
Hey @nicholasgerard . I've just tried the older version of the `nz-icon` in the simple skeleton app and I got the same error, because it can't load the SVG on the server-side (the `xhr2.XMLHttpRequest` throws an error that protocol is unsupported).

**Comment by nicholasgerard** [comment]
Makes sense, thanks!

**Comment by nicholasgerard** [comment]
This still seems to be an issue in 13.1.0.

**Comment by arturovt** [comment]
Hey @simplejason . I could guess this commit https://github.com/NG-ZORRO/ng-zorro-antd/pull/7242/commits/84b00c703311a8636bff48c743a8e525d84de45d was cherry-picked into this https://github.com/NG-ZORRO/ng-zorro-antd/commit/4bd86ca0a72baf653fdb93d311159d97f3d36b84, so the changes were just lost?

**Comment by simplejason** [comment]
> Hey @simplejason . I could guess this commit [84b00c7](https://github.com/NG-ZORRO/ng-zorro-antd/commit/84b00c703311a8636bff48c743a8e525d84de45d) was cherry-picked into this [4bd86ca](https://github.com/NG-ZORRO/ng-zorro-antd/commit/4bd86ca0a72baf653fdb93d311159d97f3d36b84), so the changes were just lost?

Cool, I will review and merge it :) We will release ng-zorro-antd to v13.1.1 this week!
