### ISSUE TITLE
In the input box with buttons in the form, such as nzSearch after adding the [nzSuffix] attribute, the background color is inconsistent after disabling the input box

### ISSUE THREAD

**Issue by wangz-code** [NG-ZORRO/ng-zorro-antd#7247]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-enjurx?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-enjurx?file=src/app/app.component.ts)

### Steps to reproduce
look this  https://stackblitz.com/edit/ng-zorro-antd-ivy-enjurx?file=src/app/app.component.ts

### What is expected?
be consistent

### What is actually happening?
inconsistent

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.0.1 |
| Browser | 版本 98.0.4758.80（正式版本） (arm64) |

---
在表单中带按钮的输入框, 比如 nzSearch 添加 [nzSuffix] 属性后 禁用输入框后背景色不一致 , 我不太理解为什么要这样设计

**Comment by chenc041** [comment]
这是个 bug

**Comment by wangz-code** [comment]
拉取 pr 后测试没问题了 , 我将关闭此issue, 非常感谢!

**Comment by chenc041** [comment]
> 拉取 pr 后测试没问题了 , 我将关闭此issue, 非常感谢!

铁子 你要不要等他们把 pr 合了 再关 issue ?

**Comment by wangz-code** [comment]
> > 拉取公关后测试没问题了，我将关闭这个问题，非常感谢！
> 
> 铁子 你要不要等他们把公关合了 再关问题？

好的
