### ISSUE TITLE
 Not able to manually(not from calendar) edit dates when  nzFormat set to "dd/MM/yyyy HH:mm:ss"

### ISSUE THREAD

**Issue by sameerkattel** [NG-ZORRO/ng-zorro-antd#7258]
### Reproduction link
[https://stackblitz.com/edit/angular-4p5rjp](https://stackblitz.com/edit/angular-4p5rjp)

### Steps to reproduce
set nzformat to "dd/MM/yyyy HH:mm:ss" 
set startdate and enddate from calendar
edit startdate manaully(not from calendar) to a valid date and press enter

### What is expected?
Should be able to edit date range manually when date format is  "dd/MM/yyyy HH:mm:ss"

### What is actually happening?
Not able to edit startdate and enddate manually

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.0.1 |
| Browser | chrome |

**Comment by whittssg** [comment]
Maybe its this? 
![image](https://user-images.githubusercontent.com/6453857/153948649-0402cfbb-7794-4983-b30f-5d9b5b87f493.png)
