### ISSUE TITLE
How to use focus event on `nz-input` ?

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#73]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Support request => Please do not submit support request here
</code></pre>

## Current behavior

I try to set focus on a `nz-input` component using `(focus)="onFocus()"` but anything happens!

```html
<nz-input [nzPlaceHolder]="'input search text'" [(ngModel)]="q" (focus)="onFocus()" (blur)="onBlur()">
    <ng-template #prefix>
        <i class="anticon anticon-search"></i>
    </ng-template>
</nz-input>
```

but……

Do you believe in magic?

Yes!!

so, i found a solution: 

```typescript
-- in typescript
ngOnInit() {
    setTimeout(() => {
        this.qIpt._renderer.listen(this.qIpt._el.querySelector('input'), 'focus', () => {
            this.focus = true;
        });
        this.qIpt._renderer.listen(this.qIpt._el.querySelector('input'), 'blur', () => {
            this.focus = false;
        });
    }, 500);
}
```

```html
-- in html
<nz-input #qIpt [nzPlaceHolder]="'input search text'" [(ngModel)]="q"></nz-input>
```

although resolved!!!

do you have anything simpler solution?

**Comment by vthinkxie** [comment]
todo: provide nzFocus event next version
