### ISSUE TITLE
select: mode tags, server search, unexpected options

### ISSUE THREAD

**Issue by zmpo** [NG-ZORRO/ng-zorro-antd#7303]
### Reproduction link
[https://stackblitz.com/edit/angular-f8zv9z?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-f8zv9z?file=src/app/app.component.ts)

### Steps to reproduce
search 'a',select 'a' option, but 'a' is unexpected. the others options are what i want.
检索框输入 a, 下拉中出现了a的选项，但是实际上我不想让'a'的选项被选中，而是想要后端数据中和a 相关的数据

![select](https://user-images.githubusercontent.com/53931565/157362615-5ec292cc-0e75-4b49-8c2e-3a029290f2a2.gif)

### What is expected?
Search value can not be selected。
检索值不能备选或者检索项不出现在下拉中

### What is actually happening?
检索值能选,

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.1.1 |
| Browser | Chrome 89 |

**Comment by chenc041** [comment]
把 `nzMode="tags"` 改成 `nzMode="multiple"` 应该可以解决你的问题

**Comment by zmpo** [comment]
非常感谢， 用'multiple'模式可以解决我个人的问题。

我很好奇，'multiple' 和 'tags'两种模式除了检索时的下拉项不同，他们在组件设计或者应用场景上有什么区别呢？

**Comment by chenc041** [comment]
`tags` 在没有匹配的情况下 应该会自动创建一个新的选项
组件设计上啥考虑 我还真不太清楚...
应该不是 bug

**Comment by zmpo** [comment]
好的，谢谢
