### ISSUE TITLE
nz-submenu cause memory leak. page instance can't be release when page life end.

### ISSUE THREAD

**Issue by suzhengda** [NG-ZORRO/ng-zorro-antd#7316]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-1njjuq](https://stackblitz.com/edit/ng-zorro-antd-ivy-1njjuq)

### Steps to reproduce
1.点击测试
2.点击返回
3.点击按钮“please after "Collect garbage" then click this button to console”
4.F12查看控制台
5.查看weakmap对象，会看到里边“SubPageComponent => 1”
6.右键Clear console
7.切换到控制台Memory面板，点击左上角“Collect garbage”
8.点击按钮“please after "Collect garbage" then click this button to console”
9.查看weakmap对象，SubPageComponent没有被释放

### What is expected?
在页面销毁之后，SubPageComponent实例随着垃圾回收而被释放

### What is actually happening?
只要引用了这个nz-menu的页面实例，其内存占用通通不能被回收，造成内存泄露。阿里作为大公司模块质量测试不足，请引起重视。

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.1.1 |
| Browser | chrome |

**Comment by suzhengda** [comment]
请参考takeUntil导致的泄露：https://zhuanlan.zhihu.com/p/100450150

**Comment by arturovt** [comment]
P.S. I'm not Chinese.

1. the reproduction is not runnable, it shows `Error in turbo_modules/@ant-design/icons-angular@13.0.2/fesm2015/ant-design-icons-angular-icons.mjs
Maximum call stack size exceeded`
2. I've just checked the code locally with `@angular/core@14.0.0-next.5` which shipped this fix https://github.com/angular/angular/commit/88f1168506befd0665125da1fca2a719cb27dbb5. The Angular itself had been having a memory leak for a long time. There's no memory leak in the `nz-menu` itself.

Running `delete this.mode$` only hides the issue, but doesn't solve it. The `map` callback captures `this`, `this` doesn't exist as a standalone object, I mean it's created only when the `new NzSubmenuService()` is run. Until there's a reference to `NzSubmenuService` instance, `this` will not be garbage collected. Angular had kept references to instances within its internal data structures in `__ngContext__` property on elements which prevented components (directives, services, etc.) to be garbage collected.

**Comment by suzhengda** [comment]
> P.S. I'm not Chinese.
> 
> 1. the reproduction is not runnable, it shows `Error in turbo_modules/@ant-design/icons-angular@13.0.2/fesm2015/ant-design-icons-angular-icons.mjs Maximum call stack size exceeded`
> 2. I've just checked the code locally with `@angular/core@14.0.0-next.5` which shipped this fix [angular/angular@88f1168](https://github.com/angular/angular/commit/88f1168506befd0665125da1fca2a719cb27dbb5). The Angular itself had been having a memory leak for a long time. There's no memory leak in the `nz-menu` itself.
> 
> Running `delete this.mode$` only hides the issue, but doesn't solve it. The `map` callback captures `this`, `this` doesn't exist as a standalone object, I mean it's created only when the `new NzSubmenuService()` is run. Until there's a reference to `NzSubmenuService` instance, `this` will not be garbage collected. Angular had kept references to instances within its internal data structures in `__ngContext__` property on elements which prevented components (directives, services, etc.) to be garbage collected.

**Comment by suzhengda** [comment]
@arturovt 
brother you are right. i had been verified that it reference by angular internal data structures  "directiveRegistry in TView". I don't know much about angular rendering. thank your
![A06FE1D7-3868-4b06-A91D-9B80BF2B49AE](https://user-images.githubusercontent.com/10463826/158054127-88671d88-8f6b-40ae-9646-eb3e0b7b9d59.png)

**Comment by arturovt** [comment]
Can I close the issue as “solved”?

**Comment by suzhengda** [comment]
@arturovt Yes, you can. i just need waiting angular solve this problem. right?

**Comment by arturovt** [comment]
Yeah, angular 14 will definitely solve it.
