### ISSUE TITLE
nzSelect with nzMode="multiple" error listOfSelectedValue.filter is not a function

### ISSUE THREAD

**Issue by rdvitka** [NG-ZORRO/ng-zorro-antd#7322]
### Reproduction link
[https://stackblitz.com/edit/angular-1kn6s7-zxkgcv](https://stackblitz.com/edit/angular-1kn6s7-zxkgcv)

### Steps to reproduce
Run the link and open the console

### What is expected?
Possibility to use multiple mode with reactive form

### What is actually happening?
multiple mode does not work with reactive form

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.1.1 |
| Browser | chrome 99.0.4844.51 |

**Comment by chenc041** [comment]
You're writing it wrong and check out the link below

https://stackblitz.com/edit/angular-1kn6s7-qynjsv

**Comment by rdvitka** [comment]
@chenc041 thank you!

**Comment by chenc041** [comment]
> @chenc041 thank you!

You're welcome. You can close this issue if you're okay

**Comment by guillermosaez** [comment]
> You're writing it wrong and check out the link below
> 
> https://stackblitz.com/edit/angular-1kn6s7-qynjsv

Hi, the stackblitz sample provided does not open. Could you please check it?

**Comment by hariton-andrei-marius** [comment]
> > You're writing it wrong and check out the link below
> > https://stackblitz.com/edit/angular-1kn6s7-qynjsv
> 
> Hi, the stackblitz sample provided does not open. Could you please check it?

I have the same problem, the page at this link doen't exist

**Comment by chenc041** [comment]
> > You're writing it wrong and check out the link below
> > https://stackblitz.com/edit/angular-1kn6s7-qynjsv
> 
> Hi, the stackblitz sample provided does not open. Could you please check it?

Sorry, the sample has been deleted when finishing stackbiz

Please check the new sample https://stackblitz.com/edit/angular-1kn6s7-zvmhjq?file=src%2Fapp%2Fapp.component.ts

**Comment by chenc041** [comment]
> > > You're writing it wrong and check out the link below
> > > https://stackblitz.com/edit/angular-1kn6s7-qynjsv
> > 
> > 
> > Hi, the stackblitz sample provided does not open. Could you please check it?
> 
> I have the same problem, the page at this link doen't exist

Sorry, the sample has been deleted when finishing stackbiz

Please check the new sample https://stackblitz.com/edit/angular-1kn6s7-zvmhjq?file=src%2Fapp%2Fapp.component.ts

**Comment by NachiketaDhal** [comment]
Thanks a lot @chenc041

**Comment by chenc041** [comment]
> Thanks a lot @chenc041

You're welcome
