### ISSUE TITLE
抽屉封装在组件中出现层次问题

### ISSUE THREAD

**Issue by Cyclone77** [NG-ZORRO/ng-zorro-antd#7328]
### Reproduction link
[https://stackblitz.com/edit/angular-xabzfw?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-xabzfw?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
抽屉封装在组件中，组件的抽屉最后加载，组件的抽屉在最上层，页面的抽屉在最下层

### What is expected?
组件的抽屉在在页面的抽屉下面

### What is actually happening?
层次出现问题

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.1.1 |
| Browser | google |

**Comment by chenc041** [comment]
如果着急的, 可以先将封装的 drawer 组件的 nzZIndex 改小点来解决这个问题

**Comment by Cyclone77** [comment]
> 如果着急的, 可以先将封装的 drawer 组件的 nzZIndex 改小点来解决这个问题

改了没用 可能是我的cdk的样式影响到了

**Comment by chenc041** [comment]
> https://stackblitz.com/edit/angular-xabzfw?file=src%2Fapp%2Fapp.component.ts

看下这个
https://stackblitz.com/edit/angular-xabzfw-gppqyr?file=src%2Fapp%2Fedit.component.ts

**Comment by chenc041** [comment]
> > 如果着急的, 可以先将封装的 drawer 组件的 nzZIndex 改小点来解决这个问题
> 
> 改了没用 可能是我的cdk的样式影响到了

看下这个
https://stackblitz.com/edit/angular-xabzfw-gppqyr?file=src%2Fapp%2Fedit.component.ts

**Comment by Cyclone77** [comment]
> > > 如果着急的, 可以先将封装的 drawer 组件的 nzZIndex 改小点来解决这个问题
> > 
> > 
> > 改了没用 可能是我的cdk的样式影响到了
> 
> 看下这个 https://stackblitz.com/edit/angular-xabzfw-gppqyr?file=src%2Fapp%2Fedit.component.ts

嗯嗯 谢谢 费心了，只有暂时这样了，我这zindex没生效是因为引用了angular/cdk/overlay的样式

**Comment by chenc041** [comment]
不客气












chenc
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月22日(周二) 下午4:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NG-ZORRO/ng-zorro-antd] 抽屉封装在组件中出现层次问题 (Issue #7328)




    
如果着急的, 可以先将封装的 drawer 组件的 nzZIndex 改小点来解决这个问题
  
改了没用 可能是我的cdk的样式影响到了
  
看下这个 https://stackblitz.com/edit/angular-xabzfw-gppqyr?file=src%2Fapp%2Fedit.component.ts
  
嗯嗯 谢谢 费心了，只有暂时这样了，我这zindex没生效是因为引用了angular/cdk/overlay的样式
