### ISSUE TITLE
input组件，type为password时，第一次点击小眼睛，会出现两个眼睛图标

### ISSUE THREAD

**Issue by genhaodegenhao** [NG-ZORRO/ng-zorro-antd#7334]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/issues/new/choose](https://github.com/NG-ZORRO/ng-zorro-antd/issues/new/choose)

### Steps to reproduce
第一次点击小眼睛，会出现两个眼睛图标

### What is expected?
交替出现

### What is actually happening?
第一次点击小眼睛，同时出现两个眼睛图标

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.1.1 |
| Browser | all |

**Comment by cipchk** [comment]
看起来都是正常的，参考：https://ng.ant.design/components/input/en#components-input-demo-password-input

**Comment by genhaodegenhao** [comment]
https://ng-zorro.gitee.io/components/input/zh
这个网站上有问题

**Comment by genhaodegenhao** [comment]
https://ng-zorro.gitee.io/components/input/zh
https://ng.ant.design/components/input/zh
这两个网站是什么区别，组件代码都是一样的吧

**Comment by genhaodegenhao** [comment]
Hi：
&nbsp;&nbsp;https://ng-zorro.gitee.io/components/input/zh#components-input-demo-password-input&nbsp; &nbsp; 这个是有问题的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NG-ZORRO/ng-zorro-antd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月1日(星期五) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NG-ZORRO/ng-zorro-antd] input组件，type为password时，第一次点击小眼睛，会出现两个眼睛图标 (Issue #7334)





 
看起来都是正常的，参考：https://ng.ant.design/components/input/en#components-input-demo-password-input

**Comment by cipchk** [comment]
应该是版本问题，gitee 是镜像但是好像此时版本是滞后了 https://ng.ant.design/ 。你看是否可以通过 Stackblitz 重现出来。
