### ISSUE TITLE
The icon "icon" does not exist or is not registered | Angular universal

### ISSUE THREAD

**Issue by kaname-png** [NG-ZORRO/ng-zorro-antd#7351]
### Example code
```typescript
// icons.module.ts
@NgModule({
  imports: [
    CommonModule,
    NzIconModule.forRoot([
      HomeOutline,
      MacCommandOutline,
      AppstoreAddOutline,
      MenuOutline,
      AppstoreOutline,
      UserOutline,
      PullRequestOutline,
      RollbackOutline,
      DownOutline,
    ]),
  ],
  exports: [NzIconModule],
})
export class IconsModule {}

// app.module.ts
@NgModule({
  declarations: [AppComponent],
  imports: [
    // ... more imports
    IconsModule,
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

### Steps to reproduce
Upgrade from version 13.0.0 to version 13.1.1 with ng update ng-zorro-antd.

### What is expected?
A correct universal angular application compilation and usage.

### What is actually happening?
Error that X icon has not been registered, it is strange because without changing absolutely nothing of code using version 13.0.0.0 I don't get any error, but when I update to the latest version I get this error.

I am using the latest version of angular (13.3.2).

```
Error: [@ant-design/icons-angular]:the icon menu-o does not exist or is not registered.
    at IconNotFoundError (..\dist\naeko-dashboard\server\main.js:1:3066144)
    at ..\dist\naeko-dashboard\server\main.js:1:3069234
    at ..\dist\naeko-dashboard\server\main.js:1:1436878
    at OperatorSubscriber2._this._next (..\dist\naeko-dashboard\server\main.js:1:1395143)
    at OperatorSubscriber2.Subscriber2.next (..\dist\naeko-dashboard\server\main.js:1:1347277)
    at ..\dist\naeko-dashboard\server\main.js:1:1341997
    at Object.errorContext (..\dist\naeko-dashboard\server\main.js:1:1540750)
    at Subject3.next (..\dist\naeko-dashboard\server\main.js:1:1341774)
    at Object.next (..\dist\naeko-dashboard\server\main.js:1:1467113)
    at Object.next (..\dist\naeko-dashboard\server\main.js:1:1349251)

Node.js v17.5.0
error Command failed with exit code 1.
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.1.1 |
| Browser | Microsoft Edge Versión 100.0.1185.29 |

---
I have a module called IconsModule where I register the icons that I am using, it is imported to AppModule, and as I said, without changing absolutely nothing of code, I get these errors that the icon has not been found or registered.

**Comment by kaname-png** [comment]
fixed when nuke node_modules folder and again yarn install.

**Comment by tegola** [comment]
I'm having the same issue after upgrading from 13.0.1 to 13.1.1, and it's not even an SSR issue. It happens on the client.
I've removed the `node_modules` dir and reinstalled the packages, but it didn't change anything.

```
Uncaught Error: [@ant-design/icons-angular]:the icon user-o does not exist or is not registered.
    at IconNotFoundError (ant-design-icons-angular.mjs:93:12)
    at ant-design-icons-angular.mjs:235:23
    at map.js:7:1
    at OperatorSubscriber._next (OperatorSubscriber.js:13:1)
    at OperatorSubscriber.next (Subscriber.js:31:1)
    at Subject.js:34:1
    at errorContext (errorContext.js:19:1)
    at Subject.next (Subject.js:27:21)
    at Object.next (share.js:44:1)
    at ConsumerObserver.next (Subscriber.js:91:1)
```

**Comment by KaiSoellch** [comment]
Same Problem here 😢

**Comment by dertuerke** [comment]
do this in you `angular.json`

```
{
  "assets": [
    {
      "glob": "**/*",
      "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
      "output": "/assets/"
    }
  ]
}
```

**Comment by tegola** [comment]
> Do this in you `angular.json` [https://ng.ant.design/components/icon/en#svg-icons](url)
> 
> ```
> {
>   "assets": [
>     {
>       "glob": "**/*",
>       "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
>       "output": "/assets/"
>     }
>   ]
> }
> ```

This is not a solution, we're using static loading, while this is needed to support dynamic loading.

**Comment by alexdsantos** [comment]
```
{
  "assets": [
    {
      "glob": "**/*",
      "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
      "output": "/assets/"
    }
  ]
}
```

Copy that to the angular.json and in my case I had to remove and reinstall node_modules
