### ISSUE TITLE
ng-zorro Cascader级联选择多选

### ISSUE THREAD

**Issue by gdhlaosan** [NG-ZORRO/ng-zorro-antd#7360]
## What problem does this feature solve?
ng-zorro Cascader级联选择怎样才能实现多选？

## What does the proposed API look like?
none

**Comment by 232650413** [comment]
这不适合多选吧，可以换种方式。

**Comment by gdhlaosan** [comment]
> 这不适合多选吧，可以换种方式。

基于react和vue的antd级联选择组件都支持多选

**Comment by ymind** [comment]
> > 这不适合多选吧，可以换种方式。
> 
> 基于react和vue的antd级联选择组件都支持多选

顶！这个很有用啊！

**Comment by ymind** [comment]
一个月过去啦，没动静啊，很想在项目中用这个功能。

**Comment by jinxiangqiang** [comment]
现在也需要这个功能，什么时候加上

**Comment by ymind** [comment]
考古催更

**Comment by MunMunMiao** [comment]
很需要。

**Comment by luver225** [comment]
angular很多功能都比react和vue少，希望能同步啊

**Comment by zhaozhang-xi** [comment]
我现在的项目也很需要这个功能，感觉可能是angular用的人少，需求量小就没有做，我是真的希望添加这个功能，希望能和react和vue同步

**Comment by ymind** [comment]
以前有人实现过，但PR没被合并，可能底层改造成本太大吧！

不过话说回来，若不是因为ng-alain太过顺手，早就弃库了。。。

**Comment by ThenMorning** [comment]
求

**Comment by HyperLife1119** [comment]
Close via #8903.
