### ISSUE TITLE
The button cannot be used normally in the form

### ISSUE THREAD

**Issue by tianguangcn** [NG-ZORRO/ng-zorro-antd#7374]
### Reproduction link
[https://ng-zorro-antd-ivy-vdhbar.stackblitz.io](https://ng-zorro-antd-ivy-vdhbar.stackblitz.io)

### Steps to reproduce
Using the button in the form and entering the Enter key in other input components will trigger the click event of the button.

### What is expected?
解决问题

### What is actually happening?
Using the button in the form and entering the Enter key in other input components will trigger the click event of the button.

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.1.1 |
| Browser | Chrome |

**Comment by volvachev** [comment]
Hi, this is not a problem of `ng-zorro`. The html form works in such way: the button has type `submit` by default inside `<form>` tag and triggers `click` event for button when you press `enter` key.

You can set `type="button"` attribute to avoid this

```html
<button type="button" nz-button (click)="onButtonClick()">
 Text
</button>
```

**Comment by tianguangcn** [comment]
ok , thanks. It really works normally.
