### ISSUE TITLE
 nz-space cannot use input and its validation properly in form.

### ISSUE THREAD

**Issue by tianguangcn** [NG-ZORRO/ng-zorro-antd#7386]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-rkdlez](https://stackblitz.com/edit/ng-zorro-antd-ivy-rkdlez)

### Steps to reproduce
 nz-space cannot use input and its validation properly in form.

### What is expected?
Fix it ,or show me how to correctly use nz-space in form control.

### What is actually happening?
not work

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.1.1 |
| Browser | Chrome |

**Comment by volvachev** [comment]
Hi, By default `nz-form-control` gets control by `ContentChild` and in your case it doesn't find when you pass `nz-space` as content.
You can set  `nzValidateStatus` property to`nz-form-control` and it should work.

```html
<nz-form-control [nzSpan]="12" [nzErrorTip]="userErrorTpl" [nzValidateStatus]="validateForm.get('userName1')!">
   <nz-space>
    <input *nzSpaceItem nz-input formControlName="userName1"/>
    <p *nzSpaceItem>123</p>
  </nz-space>
  <ng-template #userErrorTpl let-control>
    <ng-container *ngIf="control.hasError('required')">Please input your username!</ng-container>
  </ng-template>
</nz-form-control>
```

**Comment by tianguangcn** [comment]
Hi, thank you. It is finally working properly now, but why can't we find such instructions in the official documentation and update notes. I didn't have this problem until I updated version 13.
