### ISSUE TITLE
Layout->Menu显示不正确

### ISSUE THREAD

**Issue by Feng-JY** [NG-ZORRO/ng-zorro-antd#74]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/13466494/29440491-f38b931a-83f7-11e7-8ea4-65e84f6cb0b5.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/13466494/29440476-c8b3a808-83f7-11e7-8e63-7f9d46f41e68.png)

## What is the motivation / use case for changing the behavior?

[nzMode]  初始化为 'vertical' 展开后出现该bug。

## Environment

<pre><code>
@angular/cli: 1.3.0
node: 6.10.2
os: darwin x64
@angular/cdk: 2.0.0-beta.8
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/platform-browser: 4.3.4
@angular/cli: 1.3.0
@angular/compiler: 4.3.4
@angular/compiler-cli: 4.3.4
@angular/http: 4.3.4
@angular/language-service: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4

ng-zorro-antd version: 0.5.0-rc.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: 6.10.2  
- Platform: Mac 

Others:

</code></pre>

**Comment by vthinkxie** [comment]
@Feng-JY 
OnPush ChangeDetection is not supported yet.

**Comment by Feng-JY** [comment]
@vthinkxie  
Demo中修改此处
![image](https://user-images.githubusercontent.com/13466494/29441404-a81d9cba-83fd-11e7-88ad-1d416b9502ce.png)
结果 Menu 的 padding-left 为 0，也是上面那种效果

**Comment by vthinkxie** [comment]
bug confirm, thanks
