### ISSUE TITLE
需求：提供一个单独调用 DatePicker 日期选择框的方式，比如单击按钮调用

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd#741]
## What problem does this feature solve?

在没有 input 输入框的情况下调用日期选择框

## What does the proposed API look like?

无

**Comment by HsuanXyz** [comment]
follows this.
https://stackblitz.com/edit/ng-zorro-antd-setup-oujsto

**Comment by Cyclone77** [comment]
看来也就只能这样了 ，然后把input的隐藏了
