### ISSUE TITLE
angular4下出现版本兼容问题，报错为“Metadata version mismatch for module D:/gitProject/toh-pt6/node_modules/ng-zorro-antd/antd.d.ts, found version 4, expected 3, ”

### ISSUE THREAD

**Issue by google88888888** [NG-ZORRO/ng-zorro-antd#742]
## Version

0.6.6

## Environment

angular4下出现版本兼容问题，报错为“Metadata version mismatch for module D:/gitProject/toh-pt6/node_modules/ng-zorro-antd/antd.d.ts, found version 4, expected 3, ”

## Reproduction link

[https://ng.ant.design/issue-helper/#/new-issue](https://ng.ant.design/issue-helper/#/new-issue)

## Steps to reproduce

angular4下出现版本兼容问题，报错为“Metadata version mismatch for module D:/gitProject/toh-pt6/node_modules/ng-zorro-antd/antd.d.ts, found version 4, expected 3, ”

## What is expected?

angular4下出现版本兼容问题，报错为“Metadata version mismatch for module D:/gitProject/toh-pt6/node_modules/ng-zorro-antd/antd.d.ts, found version 4, expected 3, ”

## What is actually happening?

angular4下出现版本兼容问题，报错为“Metadata version mismatch for module D:/gitProject/toh-pt6/node_modules/ng-zorro-antd/antd.d.ts, found version 4, expected 3, ”

**Comment by vthinkxie** [comment]
if you want to use angular4, please use 0.5.x version.

read the first line of the doc https://ng.ant.design/#/docs/angular/introduce
