### ISSUE TITLE
Adjusting Tab Width (Module : Tabs) #2242

### ISSUE THREAD

**Issue by smile2014** [NG-ZORRO/ng-zorro-antd#7422]
## What problem does this feature solve?
tab fullwidth

## What does the proposed API look like?
tab fullwidth

**Comment by simplejason** [comment]
Try to overwrite `css` to make it work, you can follow [the demo](https://stackblitz.com/edit/angular-edsr4g?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts) to change your css file :)

**Comment by smile2014** [comment]
谢谢，已经解决
