### ISSUE TITLE
range-picker控件 ngModel属性，当初始值不为null时，点击清空按钮，ngModel值被清空，但控件不刷新，依然显示原有日期

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd#7433]
### Reproduction link
[https://stackblitz.com/edit/angular-xpdyc9-yme7u2?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-xpdyc9-yme7u2?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
range-picker控件 ngModel属性，当初始值不为null时，点击清空按钮

### What is expected?
ngModel值被清空，控件刷新为空白

### What is actually happening?
ngModel值被清空，但控件不刷新，依然显示日期

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.2.2 |
| Browser | edge 101.0 |

**Comment by 232650413** [comment]
好像依然存在这个问题
