### ISSUE TITLE
input

### ISSUE THREAD

**Issue by google88888888** [NG-ZORRO/ng-zorro-antd#744]
## Version

0.6.6

## Environment

input type="file'  的上传组件没找到

## Reproduction link

[https://ng.ant.design/issue-helper/#/new-issue](https://ng.ant.design/issue-helper/#/new-issue)

## Steps to reproduce

input type="file'  的上传组件没找到

## What is expected?

input type="file'  的上传组件没找到

## What is actually happening?

input type="file'  的上传组件没找到

**Comment by vthinkxie** [comment]
duplicated #638
