### ISSUE TITLE
dataPicker disabled style bug

### ISSUE THREAD

**Issue by lyc152** [NG-ZORRO/ng-zorro-antd#746]
<img width="224" alt="datepicker 2x" src="https://user-images.githubusercontent.com/4793878/33929120-49736744-e023-11e7-96ce-3c8ef75aa6cb.png">

## Version

0.6.6

## Environment

所有浏览器

## Reproduction link

[https://ng.ant.design/#/components/date-picker](https://ng.ant.design/#/components/date-picker)

## Steps to reproduce

When I choose today and the future date not to be selected, The picture above style problem arises, how to solve

## What is expected?

remove Today's highlights

## What is actually happening?

Today's highlights are also mixed with diabled style, which is ugly

**Comment by vthinkxie** [comment]
it seems the problem of your css file, please check it again.
