### ISSUE TITLE
support remote multiple search box

### ISSUE THREAD

**Issue by lyc152** [NG-ZORRO/ng-zorro-antd#747]
<img width="369" alt="select 2x" src="https://user-images.githubusercontent.com/4793878/33929449-84cbceb6-e024-11e7-96c6-70249ca8962b.png">
## What problem does this feature solve?

Search the user
A remote search, throttling control, request timing control, similar the picture above

## What does the proposed API look like?

React version: https://ant.design/components/select-cn/

**Comment by vthinkxie** [comment]
just dynamic change nz-option, all the feature you requested can be fulfilled.
