### ISSUE TITLE
增加 AutoComplete 组件请求

### ISSUE THREAD

**Issue by colee1985** [NG-ZORRO/ng-zorro-antd#749]
## What problem does this feature solve?

自动完成是一个使用频率很高的组件，在大量的搜索框上使用；提供实时输入建议，使用者可以从建议的下拉列表中选择文本，也可以任意输入；目前的select组件的搜索框强制选择，而不能任意输入，无法满足要求。

## What does the proposed API look like?

1、组件内支持自定义的列表模版
2、使用promise方式接收列表数据
其它的API能参考这个即可： https://ant.design/components/auto-complete-cn/

**Comment by xingkoo** [comment]
这个功能增加了吗？急需使用

**Comment by alexspring123** [comment]
如果急用，可以参考：https://github.com/NG-ZORRO/ng-zorro-antd/issues/557

**Comment by xingkoo** [comment]
非常感谢！

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed
