### ISSUE TITLE
<ul> tag is missing in the pagination component

### ISSUE THREAD

**Issue by danilmoro3** [NG-ZORRO/ng-zorro-antd#7493]
### Reproduction link
[https://stackblitz.com/edit/angular-cfkohx?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-cfkohx?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Inspect the pagination component via devTool 
https://ng.ant.design/components/pagination/en

### What is expected?
The ul tag is present

### What is actually happening?
The ul tag is missing

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.2.2 |
| Browser | All |

**Comment by danilmoro3** [comment]
Any updates?

**Comment by danilmoro3** [comment]
@chenc041 @hsuanxyz

**Comment by chenc041** [comment]
> @chenc041 @hsuanxyz 
> 

Sorry, I don't know why they does not review it

**Comment by chenc041** [comment]
Sorry, I don't know why they does not review it
