### ISSUE TITLE
nz-table满足特定情况会使cpu狂飙至100%，直到浏览器标签崩溃

### ISSUE THREAD

**Issue by buyuanne** [NG-ZORRO/ng-zorro-antd#7507]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-in6h1p?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-in6h1p?file=src/app/app.component.ts)

### Steps to reproduce
1、nzPageSize为0，
2、nzPageIndex为0,
3、nzTotal条数大于0

### What is expected?
na-table无展示数据或者给nzPageIndex和nzPageSize默认值，使程序能够正常运行

### What is actually happening?
浏览器cpu占用100%，且程序崩溃

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.2.2 |
| Browser | chrome |

**Comment by simplejason** [comment]
避免将 nzPageSize 设置为 0，因为这是业务场景中使用 table 基本不可能出现的情况，如果仍然出现问题请重新打开这个 issue 或者创建新的 issue 追踪 :)
