### ISSUE TITLE
Input输入框 带移除图标 无法触发

### ISSUE THREAD

**Issue by 232650413** [NG-ZORRO/ng-zorro-antd#7514]
### Reproduction link
[https://angular-1hxuae.stackblitz.io](https://angular-1hxuae.stackblitz.io)

### Steps to reproduce
Input输入框 输入内容，右边清除按钮无效，无法点击。

### What is expected?
正常清除。

### What is actually happening?
Input输入框 输入内容，右边清除按钮无效，无法点击。

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.3.0 |
| Browser | chrome |

**Comment by simplejason** [comment]
We will fix it today, thanks for your feedback

**Comment by caoxicheng** [comment]
@simplejason 

I have created a [PR](https://github.com/NG-ZORRO/ng-zorro-antd/pull/7518l) to fix it.


----
我创建了一个修复性[PR](https://github.com/NG-ZORRO/ng-zorro-antd/pull/7518l)
