### ISSUE TITLE
请问NG-ZORRO的组件是按需加载的吗，ng build --prod 会去掉没有使用过的组件吗？

### ISSUE THREAD

**Issue by PedroGao** [NG-ZORRO/ng-zorro-antd#752]
请问NG-ZORRO的组件是按需加载的吗，ng build --prod 会去掉没有使用过的组件吗？
希望回答一下

**Comment by PollionChang** [comment]
不会

**Comment by vthinkxie** [comment]
@PedroGao @PollionChang 
`ng build --prod` will tree-shaking the unused part of ng-zorro.
you can try yourself too.
You can see the different between the images below.
<img width="1372" alt="2017-12-15 11 24 58" src="https://user-images.githubusercontent.com/1506722/34025617-ba28d8fc-e18b-11e7-85d6-a641af2a3469.png">
<img width="1385" alt="2017-12-15 11 24 51" src="https://user-images.githubusercontent.com/1506722/34025618-ba5eb404-e18b-11e7-874f-b60b730d8fa3.png">

**Comment by y8n** [comment]
@vthinkxie  Tree-shaking unused module is ok,but how can i  tree-shaking unused module's style? 
since import style file link in `angular.json` as below, it will import all style even some modules are unused. 
```
{
  "styles": [
    "node_modules/ng-zorro-antd/ng-zorro-antd.min.css"
  ]
}
```
Thanks ~
