### ISSUE TITLE
在容器内使用select，弹出框在滚动时显示异常。

### ISSUE THREAD

**Issue by my5201314zwl** [NG-ZORRO/ng-zorro-antd#7528]
### Reproduction link
[https://ng-zorro-antd-ivy-bzjjdp.stackblitz.io  ](https://ng-zorro-antd-ivy-bzjjdp.stackblitz.io  )

### Steps to reproduce
1、点击select弹出菜单框。
2、滚动滚轮，select滚出容器范围，菜单框显示异常。

### What is expected?
select的菜单栏随select一起滚动，消失在容器内。

### What is actually happening?
select的菜单栏随select一起滚动，select滚出可视范围，菜单栏位置异常。

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.3.1 |
| Browser | chrome |

**Comment by ParsaArvanehPA** [comment]
This PR will fix the issue mentioned above for all components created with the CDK Overlay that are inside modals or drawers: #8804.


As a temporary fix, you can follow these steps:
- Create a wrapper inside your modal or drawer
- Add the cdkScrollable directive to the wrapper
- Set overflow: auto on the wrapper

This way, the wrapper will handle the scrolling.
You can refer to this [link](https://stackblitz.com/edit/angular-sg8j5f?file=src%2Fapp%2Fapp.component.ts) for a sample.
