### ISSUE TITLE
DatePicker日期选择框 初始化赋值 清空依然存在问题

### ISSUE THREAD

**Issue by 232650413** [NG-ZORRO/ng-zorro-antd#7534]
### Reproduction link
[https://angular-aev8a1.stackblitz.io](https://angular-aev8a1.stackblitz.io)

### Steps to reproduce
DatePicker日期选择框 初始化赋值，点击右边清空按钮依然无法清空。有时好像延时好几秒后清除掉，有时点击清除无效；
除非点开面板重新赋值 ，方可实时清空。
nz-range-picker 好像点击后5-10秒自动清空
nz-date-picker 纯粹点击无法清空

### What is expected?
DatePicker日期选择框 初始化赋值 实时清空。

### What is actually happening?
DatePicker日期选择框 初始化赋值，点击右边清空按钮依然无法清空。

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.3.2 |
| Browser | chrome |

---
这个问题好像几个版本都存在...

**Comment by luckyship** [comment]
手动触发angular变更检测可以解决
```
import { ChangeDetectorRef } from '@angular/core';

constructor(private _cdr: ChangeDetectorRef)

onModelChange() {
  this._cdr.detectChanges();
}

```
