### ISSUE TITLE
the problem about Support for older versions of Internet Explorer,and some suggestions.

### ISSUE THREAD

**Issue by PollionChang** [NG-ZORRO/ng-zorro-antd#756]
## Version

0.5.5

## Environment

Internet Explorer 9

## Reproduction link

[https://about;blank](https://about;blank)

## Steps to reproduce

just import NgZorroAntdModule

## What is expected?

All component styles can take effect in 

## What is actually happening?

First, let's look at some rules for IE9
A sheet may contain up to 4095 selectors (Demo)
A sheet may @import up to 31 sheets
@import nesting supports up to 4 levels deep

In fact, if we import all the modules to Project, it is easy to break this rule and it will lead to the loss of styles

## Other?

I think it's very painful to support for older versions of Internet Explorer. but  other  Angular UI components  like primeng has some solutions about this problem. Contains all the component styles in a single file ? 
Or statement does not support  ie9.

**Comment by vthinkxie** [comment]
@PollionChang the style will only effect your page when you use the specific component, all the components not used will not append the style in your page.

**Comment by PollionChang** [comment]
@vthinkxie  yes,but when you use more than a large number of components , the problem always to be happens, such as a medium-sized project~

**Comment by vthinkxie** [comment]
we will separate the style file from the components in version 0.7.0.

**Comment by PollionChang** [comment]
@vthinkxie  ok thanks for your help
