### ISSUE TITLE
<nz-autocomplete> dropdown disappeared abnormally in <nz-form-control>

### ISSUE THREAD

**Issue by yunyuyuan** [NG-ZORRO/ng-zorro-antd#7572]
### Reproduction link
[https://stackblitz.com/edit/angular-stxgla?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-stxgla?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
focus at input, dropdown will show, then input a single character, dropdown disappeared.
Note: It occurs after the page first loaded,or after hot update,or validateStatus changed .

### What is expected?
auto-complete dropdown does not disappear.

### What is actually happening?
auto-complete dropdown disappeared after input a character.

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.3.2 |
| Browser | Edge 103.0.1264.62 |

**Comment by yunyuyuan** [comment]
Closed because there is no response

**Comment by yunyuyuan** [comment]
@LucianaMq What did you mean? If there is no <input>, nz-autocomplete makes no sense.
https://github.com/NG-ZORRO/ng-zorro-antd/pull/7618/files#diff-e581b7fccfce41aa71bddda98f463eb741a10afee0cb9a521e3df720baa2fd59L144
By the way, I found that the problem is with the nz-input, which use `hsotView.clear()` to remove all its host view just for hidden feedback icon,without checking.To fix that,we only need to use `indexOf` to remove the specific `feedbackRef`.

**Comment by jdonzallaz** [comment]
@yunyuyuan Did you find a workaround ? I have the same problem.

**Comment by yunyuyuan** [comment]
> @yunyuyuan Did you find a workaround ? I have the same problem.

Unfortunately no.

**Comment by swseverance** [comment]
@yunyuyuan thank you for figuring out this happens when the autocomplete is placed inside an nz-form-control! i am experiencing the same issue and it saved me a lot of time. for now i am simply avoiding the usage of the nz-form-control when working with the autocomplete
