### ISSUE TITLE
NullInjectorError: No provider for Overlay!

### ISSUE THREAD

**Issue by xiongyayun428** [NG-ZORRO/ng-zorro-antd#759]
## Version

0.6.6

## Environment

windows7、Google Chrome版本 63.0.3239.84、

## Reproduction link

[https://ng.ant.design/issue-helper/#/new-issue](https://ng.ant.design/issue-helper/#/new-issue)

## Steps to reproduce

启动报错

## What is expected?

不报错

## What is actually happening?

报错

## Other?

![image](https://user-images.githubusercontent.com/11458959/34021757-75a985d8-e176-11e7-957f-6eb5f3254e04.png)

![image](https://user-images.githubusercontent.com/11458959/34021770-88f136d6-e176-11e7-8cda-04a05050e9ae.png)

**Comment by vthinkxie** [comment]
just try removing all the `node_modules` and reinstall, if you are using cnpm or tnpm, please use `--by=npm` option.

**Comment by xiongyayun428** [comment]
@vthinkxie Still the same

**Comment by vthinkxie** [comment]
@xiongyayun428 
everything works fine in our integration test here https://travis-ci.org/NG-ZORRO/ng-zorro-antd/jobs/316302861,
if there is anything wrong in your project, please reproduce it or check your environment, we can not help you only with your one screenshot.

**Comment by vthinkxie** [comment]
@xiongyayun428 check your cdk again, you should have install wrong cdk version.

**Comment by xiongyayun428** [comment]
@vthinkxie 
```
Angular CLI: 1.6.1
Node: 9.3.0
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.0
@angular/cli: 1.6.1
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.6.2
webpack: 3.10.0
```

**Comment by vthinkxie** [comment]
@xiongyayun428 cdk version is the same as material design, it has conflict with ng-zorro-antd version 0.6.6, since 0.6.6 only support the cdk 5.0.0. there must be a warning when you install your node_modules.

**Comment by xwHoward** [comment]
Solved this problem by removing node_modules/ under ng-zorro-antd/.

**Comment by imAcityman** [comment]
> Solved this problem by removing node_modules/ under ng-zorro-antd/.

although i solved too by ur way，i still don`t know why. this node_modules effect the global?

**Comment by wgjtyu** [comment]
> Solved this problem by removing node_modules/ under ng-zorro-antd/.

works for me too.
ng-zorro-antd@8.0.2
angular@8.1.0

**Comment by wgjtyu** [comment]
run this command can also solve this:
rm -rf node_modules && rm package-lock.json && npm install

**Comment by kerwin-ly** [comment]
It works for me.Thx @wgjtyu

**Comment by jacobswain** [comment]
> Solved this problem by removing node_modules/ under ng-zorro-antd/.

Worked for me.  Thanks, @xwHoward.

**Comment by Svetomechc** [comment]
Same problem here :(

My versions:

![image](https://user-images.githubusercontent.com/36156020/61967358-c76db600-afdd-11e9-887e-27ba1035e5ae.png)

**Comment by davidmarquis** [comment]
Quick note that I just had a similar issue on my project and it turns out the `@angular/cdk` dependency I had in my project was old than the one `ng-zorro-antd` declares as a dependency and it seemed to create an issue with the injector for `Overlay`.

If anyone gets a similar issue, my first advice would be to ensure the `@angular/cdk` version you use in your project (if you do declare one explicitly) matches the version `ng-zorro-antd` uses. In my particular case, for `ng-zorro-antd@10.1.1`, I needed `@angular/cdk@10.2.7`.
