### ISSUE TITLE
tabset style error

### ISSUE THREAD

**Issue by wanghaolu** [NG-ZORRO/ng-zorro-antd#76]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

在只有1个tab时也会出现分页，并且点击左箭头tab样式会出现错误
![2017-08-18_10-46-17](https://user-images.githubusercontent.com/9586655/29442184-8eca72ec-8402-11e7-8c9e-74083f14cbca.gif)

## Environment

<pre><code>
Angular version: 4.3.4

ng-zorro-antd version: 0.5.0 rc.0

Browser:
- [ x] Chrome (desktop) version 60
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: 8.1.2  
- Platform: Windows 

Others:

</code></pre>

**Comment by vthinkxie** [comment]
please provide code to reproduce this error.

**Comment by wanghaolu** [comment]
@vthinkxie you can try it

```xml
<nz-root>
  <nz-layout class="layout">
    <nz-header>
      <div class="logo"></div>
      <ul nz-menu [nzTheme]="'dark'" [nzMode]="'horizontal'" style="line-height: 64px;">
        <li nz-submenu style="float:right">
          <span title>个人信息</span>
          <ul>
            <li nz-menu-divider></li>
            <li nz-menu-item><a routerLink="/personal">个人信息</a></li>
          </ul>
        </li>
      </ul>
    </nz-header>
    <nz-layout style="padding:24px">
      <nz-content style="background:#fff; padding: 24px; height: 100%;">
        <nz-tabset [nzType]="'card'" [nzSize]="default" [nzTabPosition]="top" [nzSelectedIndex]="activeIndex">
          <nz-tab>
            <ng-template #nzTabHeading>
              列表
            </ng-template>
          </nz-tab>
        </nz-tabset>
      </nz-content>
    </nz-layout>
  </nz-layout>
</nz-root>

**Comment by vthinkxie** [comment]
@wanghaolu 
Please CHECK your code for ` [nzSize]="default"` and ` [nzTabPosition]="top"`
This code should be, you should use string other than variable.
 ` [nzSize]="'default'"` and ` [nzTabPosition]="'top'"` 
OR
 `nzSize="default"` and ` nzTabPosition="top"`
