### ISSUE TITLE
dropdown-animations cubic-bezier can more faster?

### ISSUE THREAD

**Issue by Elliottssu** [NG-ZORRO/ng-zorro-antd#760]
As you can see, dropdown menu visiables animations is to slowly.
The user experience is very bad, so i wonder if it have some custom configs to fix.

like: 
form `animate('150ms cubic-bezier(0.25, 0.8, 0.25, 1)')` to `animate('150ms ease-out')`

otherwise, the dropdown with pagination is so nice, smooth and clean.

**Comment by vthinkxie** [comment]
@Elliottssu this is because there is an debounceTime delay when you hover or click the dropdown, we will try to fix it later, thanks for your advice.

**Comment by Elliottssu** [comment]
@vthinkxie I see, looking forward to your improvement
