### ISSUE TITLE
reflector(moment): remove the dependency of moment

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#761]
## What problem does this feature solve?

reduce the package size since angular has provided all the locales we need

## What does the proposed API look like?

may bring some break changes.

**Comment by trotyl** [comment]
## Draft design doc for anyone works on this

#### Background

Angular has dropped dependency of [Intl API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) and uses [self-provided locale data](https://unpkg.com/@angular/common/locales/) extracted from [CLDR](https://github.com/unicode-cldr) starts from v5.

#### Usage

An Angular application needs to define which locale to support by registering the locale data, like:

```typescript
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
import localeZh from '@angular/common/locales/zh';

// the second parameter 'fr', 'zh' are optional
registerLocaleData(localeFr, 'fr');
registerLocaleData(localeFr, 'zh');
```

More details can be found in [Angular i18n doc](https://angular.io/guide/i18n).

All registered locale data would be available in runtime. Then the application needs to provide the `LOCALE_ID` somehow, for example by CLI option at build time or using `navigator.language` at runtime. <sub>(Or whatever methods like url path, that's not decided by library)</sub>

But the library should provide an option to override `LOCALE_ID` as the DI result cannot be changed after setup. <sub>(Which can be a separate work)</sub>

#### Implementation

For template formatting, just use the [DatePipe](https://angular.io/api/common/DatePipe), it will automatically use the locale provided by `LOCALE_ID` token, also there is a `locale` parameter to override it.

For logic formatting, Angular would provide something like `LocaleService` in 5.2 or 5.3, but before that (being our minimal requirement), we need to make it work for current infrastructure. The easiest way to do is the **pipe as a service** pattern (should use pipe directly when possible), like:

```typescript
@NgModule({
  providers: [ DatePipe ]
})
class LocaleModule { }

@Injectable()
class LocaleService {
  constructor(private datePipe: DatePipe) { }

  formatDate(date: Date, format: string, locale: string): string {
    return this.datePipe.transform(date, format, /* timezone */ undefined, locale);
  }
}
```

For other utilities like plus one day, can be achieved by some **tiny** 3rd-party libraries like [date-fns](https://date-fns.org/v1.29.0/docs/addDays). But could still have some problem for typing in CommonJS module integration. <sub>(Should only import the exact helpers for size consideration)</sub>
