### ISSUE TITLE
Content Security Policy (CSP) Support

### ISSUE THREAD

**Issue by FRdanielsuszczyk** [NG-ZORRO/ng-zorro-antd#7644]
## Content Security Policy

When I was implementing Content Security Policy I ran into a problem related to `ng-zorro`.

There is no way to configure CSP handling (by nonce/hash) like it is possible in ant-design using ConfigProvider like [here](https://ant.design/components/config-provider/#Content-Security-Policy).

`ng-zorro` in its components uses inline `style="..."` attributes which are not allowed in CSP Level 3 (some examples and explanation can be found [here](https://content-security-policy.com/examples/allow-inline-style/).

```
Refused to apply inline style because it violates the following Content Security Policy directive:
"style-src 'self''sha256-nMxMqdZhkHxz5vAuW/PAoLvECzzsmeAxD/BNwG15HuA='".
Either the 'unsafe-inline' keyword, a hash ('sha256-nMxMqdZhkHxz5vAuW/PAoLvECzzsmeAxD/BNwG15HuA='),
or a nonce ('nonce-...') is required to enable inline execution.
```

Additionaly Wave Effect somehow affects components styles and there are more `style` attributes produced.

I believe there are at least two possible solutions.

#### Solution 1

Implement something similat to [ConfigProvider](https://ant.design/components/config-provider/#Content-Security-Policy), but I'm not sure how complex that could be.

#### Solution 2

Remove all inline `style` attributes (probably something around 215 results) and replace them with css classes.

## Profit

Stricter CSP policy

**Comment by vanswang** [comment]
I had the same problem, waitting for the solution.
