### ISSUE TITLE
[nz-carousel] should support loop flag

### ISSUE THREAD

**Issue by nikolatasikj** [NG-ZORRO/ng-zorro-antd#7652]
## What problem does this feature solve?
It should prevent the carousel to go in a loop, for example when we are on the last item and swipe it right it should stay there, not going on the first item.

## What does the proposed API look like?
It should have *[nzLoop]* input that will be boolean and will decide if the carousel will go in a loop or not, by default it should be *true*

**Comment by hullis** [comment]
This could be implemented as a custom strategy. Please refer to this [demo](https://ng.ant.design/components/carousel/en#components-carousel-demo-custom).
