### ISSUE TITLE
how to use formsArray for multi-select using nz-select 

### ISSUE THREAD

**Issue by shahin4u000** [NG-ZORRO/ng-zorro-antd#7674]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-nz-select-formcontrolname-41qcxk?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-nz-select-formcontrolname-41qcxk?file=app%2Fapp.component.html)

### Steps to reproduce
I have an angular app and in my form, I have a multi-select. Multiselect value will be stored in an array, therefore I am using angular formsArray. 

in my app.component.ts: 

    {{testForm.value|json}}
    
    <form nz-form [formGroup]="testForm">
    
      <div>
        <p>Title</p>
        <nz-input formControlName="title"></nz-input>
      </div>
    
      <div>
        <p>Items</p>
        <nz-select
          [nzMode]="'multiple'"
          [nzPlaceHolder]="'Choose items'"
          formArrayName="items"
          [nzNotFoundContent]="'Item not found'">
          <nz-option
            *ngFor="let item of items"
            [nzLabel]="item.title"
            [nzValue]="item.id">
          </nz-option>
        </nz-select>
      </div>
    
    </form>

and inside the .ts file: 

    export class AppComponent  {
      testForm: FormGroup;
      items = [
        {
          title: 'Item 1',
          id: 1
        },
        {
          title: 'Item 2',
          id: 2
        }
      ]
    
      constructor(private fb: FormBuilder) {
        this.testForm = this.fb.group({
          title: '',
          items: this.fb.array([]),
        });
      }
    
    }
However, the problem is that, even though I selected the multiple items, but I am getting an empty array like that: 

    { "title": "test", "items": [] }

items, attribute is not filling up with the value from nz-select. I have created an app with this example. Here is the link. 

[stackblitz app sample][1]

  [1]: https://stackblitz.com/edit/ng-zorro-antd-nz-select-formcontrolname-41qcxk?file=app/app.component.html

### What is expected?
items should be filled with selected value from multiselect

### What is actually happening?
instead of binding the value inside the array getting empty array

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.1.0 |
| Browser | chrome |

**Comment by Nicoss54** [comment]
hey shahin4u000, NzSelectComponent extends the ControlValueAccessor. As explain in the Angular documentation, to bind correctly with the control of NzSelectComponent, the control must be a type of FormControl.

In your exemple the correct solution is

app.component.ts

```
export class AppComponent  {
  testForm: FormGroup;
  items = [
    {
      title: 'Item 1',
      id: 1
    },
    {
      title: 'Item 2',
      id: 2
    }
  ]

  constructor(private fb: FormBuilder) {
    this.testForm = this.fb.group({
      title: '',
      items: []
    });
  }
}
```

app.component.html

```
{{testForm.value|json}}

<form nz-form [formGroup]="testForm">

  <div>
    <p>Title</p>
    <nz-input formControlName="title"></nz-input>
  </div>

  <div>
    <p>Items</p>
    <nz-select
      [nzMode]="'multiple'"
      [nzPlaceHolder]="'Choose items'"
      formControlName="items"
      [nzNotFoundContent]="'Item not found'">
      <nz-option
        *ngFor="let item of items"
        [nzLabel]="item.title"
        [nzValue]="item.id">
      </nz-option>
    </nz-select>
  </div>

</form>
```

Hope it help
