### ISSUE TITLE
Warning: The animation trigger "collapseMotion" is attempting to animate the following not animatable properties: overflow

### ISSUE THREAD

**Issue by kurimuson** [NG-ZORRO/ng-zorro-antd#7692]
### Reproduction link
[https://stackblitz.com/edit/angular-tudsnl?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-tudsnl?file=src/app/app.component.ts)

### Steps to reproduce
When nz-menu open or close, console will print this waring.

### What is expected?
no warning at animate.

### What is actually happening?
animate with warning.

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.1.1 |
| Browser | chrome 103 |

---
browser.mjs:2541 Warning: The animation trigger "collapseMotion" is attempting to animate the following not animatable properties: overflow
(to check the list of all animatable properties visit https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties)

**Comment by wangz-code** [comment]
我也遇到了 盯一下

**Comment by string-lzc** [comment]
Any updates?

**Comment by chenweihan** [comment]
me too

**Comment by CamiloB664** [comment]
...

**Comment by akib1997** [comment]
Waiting for updates!

**Comment by vanswang** [comment]
同样遇到了，mark 一下

**Comment by shalltears** [comment]
me too

**Comment by mjunlee** [comment]
16.1.0  有同样的告警

**Comment by bloom8848** [comment]
mark,same warning

**Comment by qq253498229** [comment]
ng17+zorro17也有这个问题

**Comment by linlin991229** [comment]
有解决吗

**Comment by mvcheeyong** [comment]
用Github build, 会产生	
Error: NG05105: Unexpected synthetic property @.disabled found. Please make sure that:
	  - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application.
	  - There is corresponding configuration for the animation named `@.disabled` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations).
package.json :	  
"ng-zorro-antd": "16.2.2"
...

**Comment by codypotter** [comment]
bump

**Comment by ParsaArvanehPA** [comment]
> 用Github build, 会产生 Error: NG05105: Unexpected synthetic property @.disabled found. Please make sure that: - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application. - There is corresponding configuration for the animation named `@.disabled` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations). package.json : "ng-zorro-antd": "16.2.2" ...

If you are getting this error, it is because you haven't imported [provideAnimations ](https://angular.io/api/platform-browser/animations/provideAnimations)in your application.
Try this in your app.config.ts:

```ts
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideAnimations()
  ]
};
```

**Comment by ParsaArvanehPA** [comment]
Could someone who is using Angular version 16 or 17 verify if this warning persists?
I have tested the op's stackblitz in my local project with version 17 and I do not see this warning.

**Comment by autogumcom** [comment]
> Czy ktoś, kto używa Angulara w wersji 16 lub 17, mógłby sprawdzić, czy to ostrzeżenie nadal występuje? Przetestowałem stackblitz operacji w moim lokalnym projekcie w wersji 17 i nie widzę tego ostrzeżenia.

After adding provideAnimations() everything is ok!

**Comment by autogumcom** [comment]
> Could someone who is using Angular version 16 or 17 verify if this warning persists? I have tested the op's stackblitz in my local project with version 17 and I do not see this warning.

After adding provideAnimations() everything is ok!

**Comment by mvcheeyong** [comment]
> ```ts
> export const appConfig: ApplicationConfig = {
>   providers: [
>     provideRouter(routes),
>     provideAnimations()
>   ]
> };
> ```

Thanks, it doesn't work if i imported provideAnimations() into my app.module.ts, but it works when i imported into my sider.module.ts.

**Comment by All-The-Best-for** [comment]
> > 用Github build, 会产生 Error: NG05105: Unexpected synthetic property @.disabled found. Please make sure that: - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application. - There is corresponding configuration for the animation named `@.disabled` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations). package.json : "ng-zorro-antd": "16.2.2" ...
> 
> If you are getting this error, it is because you haven't imported [provideAnimations ](https://angular.io/api/platform-browser/animations/provideAnimations)in your application. Try this in your app.config.ts:
> 
> ```ts
> export const appConfig: ApplicationConfig = {
>   providers: [
>     provideRouter(routes),
>     provideAnimations()
>   ]
> };
> ```

Thank you very much, this question has been bothering me all day！

**Comment by micobarac** [comment]
This is still an issue in version `19.2.1`. 

The problem is that `overflow` property cannot be animated as the warning says:

```
hook.js:608 Warning: The animation trigger "collapseMotion" is attempting to animate the following not animatable properties: overflow
(to check the list of all animatable properties visit https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties)
```

**Comment by micobarac** [comment]
```ts
/**
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/LICENSE
 */

import {
  animate,
  AnimationTriggerMetadata,
  query,
  stagger,
  state,
  style,
  transition,
  trigger
} from '@angular/animations';

import { AnimationCurves } from './animation-consts';

export const collapseMotion: AnimationTriggerMetadata = trigger('collapseMotion', [
  state('expanded', style({ height: '*' })),
  state('collapsed', style({ height: 0, overflow: 'hidden' })),
  state('hidden', style({ height: 0, overflow: 'hidden', borderTopWidth: '0' })),
  transition('expanded => collapsed', animate(`150ms ${AnimationCurves.EASE_IN_OUT}`)),
  transition('expanded => hidden', animate(`150ms ${AnimationCurves.EASE_IN_OUT}`)),
  transition('collapsed => expanded', animate(`150ms ${AnimationCurves.EASE_IN_OUT}`)),
  transition('hidden => expanded', animate(`150ms ${AnimationCurves.EASE_IN_OUT}`))
]);

export const treeCollapseMotion: AnimationTriggerMetadata = trigger('treeCollapseMotion', [
  transition('* => *', [
    query(
      'nz-tree-node:leave,nz-tree-builtin-node:leave',
      [
        style({ overflow: 'hidden' }),
        stagger(0, [
          animate(`150ms ${AnimationCurves.EASE_IN_OUT}`, style({ height: 0, opacity: 0, 'padding-bottom': 0 }))
        ])
      ],
      {
        optional: true
      }
    ),
    query(
      'nz-tree-node:enter,nz-tree-builtin-node:enter',
      [
        style({ overflow: 'hidden', height: 0, opacity: 0, 'padding-bottom': 0 }),
        stagger(0, [
          animate(
            `150ms ${AnimationCurves.EASE_IN_OUT}`,
            style({ overflow: 'hidden', height: '*', opacity: '*', 'padding-bottom': '*' })
          )
        ])
      ],
      {
        optional: true
      }
    )
  ])
]);
```

Looking at the official code, the logical conclusion is that `overflow: 'hidden'` cannot be animated and should be removed from the flow.
