### ISSUE TITLE
Select Dropdown behave differently on scroll in drawer or modal

### ISSUE THREAD

**Issue by The-io-dev** [NG-ZORRO/ng-zorro-antd#7695]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-ivpnnn?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fng-zorro-antd.module.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-ivpnnn?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fng-zorro-antd.module.ts)

### Steps to reproduce
1 - focus in select and scroll over the background (or use scrollbar), the options stick to the select
2 - click the drawer or modal button
3 - do the same as step 1, but this time the options stays in place

### What is expected?
the options should to stick to the select

### What is actually happening?
the options stays in place when select is in drawer or modal

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.1.1 |
| Browser | chrome |

**Comment by chenyueyuan** [comment]
I have the same problem

**Comment by ParsaArvanehPA** [comment]
This PR will fix the issue mentioned above for all components created with the CDK Overlay that are inside modals or drawers: #8804.


As a temporary fix, you can follow these steps:
- Create a wrapper inside your modal or drawer
- Add the cdkScrollable directive to the wrapper
- Set overflow: auto on the wrapper

This way, the wrapper will handle the scrolling.
You can refer to this [link](https://stackblitz.com/edit/angular-sg8j5f?file=src%2Fapp%2Fapp.component.ts) for a sample.
