### ISSUE TITLE
Styles are not exported in package causing issues with `@import 'ng-zorro-antd/ng-zorro-antd.less'`

### ISSUE THREAD

**Issue by snebjorn** [NG-ZORRO/ng-zorro-antd#7696]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-c33sdw](https://stackblitz.com/edit/ng-zorro-antd-ivy-c33sdw)

### Steps to reproduce
Open stackbliz and observe error:
> The entrypoint for 'ng-zorro-antd' could not successfully be resolved. The file '/turbo_modules/ng-zorro-antd@14.1.1/ng-zorro-antd.less' does not exist. Please log an issue with the package author or check for an updated version of the package.

### What is expected?
`@import 'ng-zorro-antd/ng-zorro-antd.less'` should work.

Styles (css and less) must be included in package exports for the above to work.

See how Angular Material does it: https://github.com/angular/components/blob/75df8fe520818f1762df1988b1706c4af6cc1330/src/material/package-base.json#L15-L55

<details><summary>Angular Material's package.json</summary>

```jsonc
// package.json
{
  // rest omitted...
  "exports": {
    ".": {
      "sass": "./_index.scss"
    },
    "./theming": {
      "sass": "./_theming.scss"
    },
    "./_theming": {
      "sass": "./_theming.scss"
    },
    "./prebuilt-themes/indigo-pink.css": {
      "style": "./prebuilt-themes/indigo-pink.css"
    },
    "./prebuilt-themes/deeppurple-amber.css": {
      "style": "./prebuilt-themes/deeppurple-amber.css"
    },
    "./prebuilt-themes/pink-bluegrey.css": {
      "style": "./prebuilt-themes/pink-bluegrey.css"
    },
    "./prebuilt-themes/purple-green.css": {
      "style": "./prebuilt-themes/purple-green.css"
    },
    "./prebuilt-themes/*": {
      "style": "./prebuilt-themes/*.css"
    },
    "./legacy-prebuilt-themes/indigo-pink.css": {
      "style": "./legacy-prebuilt-themes/legacy-indigo-pink.css"
    },
    "./legacy-prebuilt-themes/deeppurple-amber.css": {
      "style": "./legacy-prebuilt-themes/legacy-deeppurple-amber.css"
    },
    "./legacy-prebuilt-themes/pink-bluegrey.css": {
      "style": "./legacy-prebuilt-themes/legacy-pink-bluegrey.css"
    },
    "./legacy-prebuilt-themes/purple-green.css": {
      "style": "./legacy-prebuilt-themes/legacy-purple-green.css"
    },
    "./legacy-prebuilt-themes/*": {
      "style": "./legacy-prebuilt-themes/*.css"
    }
  }
}
```
</details>

### What is actually happening?
Angular cannot find and import the styles.

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.1.1 |
| Browser | No relevant |

---
Workaround: use path instead of package reference  `@import '../node_modules/ng-zorro-antd/ng-zorro-antd.less'`

This is not an angular issue: https://github.com/angular/angular-cli/issues/24093

package exports:
- https://angular.io/guide/angular-package-format#exports
- https://webpack.js.org/guides/package-exports/

**Comment by caoxicheng** [comment]
use `node_modules/ng-zorro-antd/ng-zorro-antd.less`

**Comment by snebjorn** [comment]
> use `node_modules/ng-zorro-antd/ng-zorro-antd.less`

Doing what you suggest

```less
// styles.less
@import 'node_modules/ng-zorro-antd/ng-zorro-antd.less';
```

Results in this error

> ./src/styles.less.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].rules[0].oneOf[0].use[2]!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[7].rules[1].use[0]!./src/styles.less - Warning: Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
> his.addContextDependency (directories).
> Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
> Globs: They are not supported. Pass absolute path to the directory as context dependencies.The following invalid values have been reported:
>  * "node_modules\\ng-zorro-antd\\affix\\style\\entry.less" * "node_modules\\ng-zorro-antd\\affix\\style\\index.less"
>  * "node_modules\\ng-zorro-antd\\affix\\style\\patch.less"
>  * and more ...

As I mentioned in the workaround the full path must be used so it's

```less
// styles.less
@import '../node_modules/ng-zorro-antd/ng-zorro-antd.less';
```

But that is just that - a workaround.

**Comment by DepickereSven** [comment]
@snebjorn the PR #7928 should fix that issue that you have mentioned.

**Comment by gkorakas-eli** [comment]
It seems the fix [here](https://github.com/NG-ZORRO/ng-zorro-antd/pull/7928) is not enough as the following files are not exported. 

```
ng-zorro-antd/style/variable.less
ng-zorro-antd/style/patch.less
```

If the following is used instead all the components' styling is going to be imported.

```
ng-zorro-antd/ng-zorro-antd.variable.less
```

This way you cannot import only the components styling that you need for those that are used in the app.

Please let me know what you think.
