### ISSUE TITLE
Descriptions描述列表 当title为嵌入内容TemplateRef 横向模式样式异常

### ISSUE THREAD

**Issue by 232650413** [NG-ZORRO/ng-zorro-antd#7698]
### Reproduction link
[https://stackblitz.com/edit/angular-5etyb8?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-5etyb8?file=src/app/app.component.ts)

### Steps to reproduce
nzLayout 当默认状态下Horizontal 自定义title 样式异常

### What is expected?
正常显示

### What is actually happening?
nzLayout 当默认状态下Horizontal 自定义title 样式异常

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.1.1 |
| Browser | chrome |

**Comment by Laffery** [comment]
the reproduction link seems to be error: `A network error (such as timeout, interrupted connection or unreachable host) has occurred.`

you'd better provide a demo project link with [template](https://stackblitz.com/edit/ng-zorro-antd-ivy).

**Comment by 232650413** [comment]
> the reproduction link seems to be error: `A network error (such as timeout, interrupted connection or unreachable host) has occurred.`
> 
> you'd better provide a demo project link with [template](https://stackblitz.com/edit/ng-zorro-antd-ivy).

我这可以打开么
