### ISSUE TITLE
建议：nz-table 更友好的数据源选择

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#772]
## What problem does this feature solve?

当下 `nzAjaxData` 与 `nzDataSource` 二者用于区分两种不同的数据源加载方式，有时候我非常难于确认我应该采用哪种形式，特别是在一些小数据量会优先读取本地缓存（例如：localStorage）的数据（一般会是一些单位数据，例如：个、袋等），若缓存没有情况下才发起后端请求。

```html
<nz-table [nzAjaxData]="_data" [nzDataSource]="_cachedData"></nz-table>
```

## What does the proposed API look like?

我想统一一种数据源名（例如：`nzData`） 意思会非常明确，假使需要由 `nz-table` 帮忙处理数据分页，`nzIsPagination` & `nzPageSize` 已经非常明确给出答案。

**Comment by bokire** [comment]
表格在展示树形结构数据的时候不支持按节点异步加载数据

**Comment by vthinkxie** [comment]
@bokire 树形结构的所有逻辑都是自己控制的，页面上是demo不是它全部的用法

**Comment by bokire** [comment]
@vthinkxie [惊呆]刚看了下树形结构demo中的示例代码跟nz-row-expand-icon组件的源码，原来nz-row-expand-icon组件已经提供了nzExpandChange的回调方法，只是API中缺少了这项内容
