### ISSUE TITLE
nz-modal with nz-table nzLeft has some error

### ISSUE THREAD

**Issue by cai1035752265** [NG-ZORRO/ng-zorro-antd#7724]
### Reproduction link
[https://stackblitz.com/edit/angular-qkqw7n-1wp6v5?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-qkqw7n-1wp6v5?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
使用表格nz-table设置固定列，并将这个nz-table放到nz-modal上

### What is expected?
弹框中的表格固定列正常显示

### What is actually happening?
实际上弹框中的表格固定列从第二列起，left和right就出现了异常
![image](https://user-images.githubusercontent.com/33340516/202142634-216ee51f-e97f-4112-a0c7-4218cf3c929f.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.1.1 |
| Browser | Chrome107.0.5304.107（正式版本） （64 位），Chrome版本 86.0.4240.198（正式版本） （32 位）火狐107.0（64 位）。 |

**Comment by simplejason** [comment]
https://stackblitz.com/edit/angular-qkqw7n-amn8mb?file=src%2Fapp%2Fapp.component.ts
复现地址看着好像没什么问题？看下原因？

**Comment by cai1035752265** [comment]
非常抱歉，光抄官方文档例子了，没注意到还有 `列头与内容不对齐或出现列重复，请指定固定列的宽度 [nzWidth]。如果指定 width 不生效或出现白色垂直空隙，请尝试建议留一列不设宽度以适应弹性布局` 这段提示。加上[nzWidth]复现地址就正常了，自己的项目里留了一列不设宽度的表格也正常了

**Comment by simplejason** [comment]
> 非常抱歉，光抄官方文档例子了，没注意到还有 `列头与内容不对齐或出现列重复，请指定固定列的宽度 [nzWidth]。如果指定 width 不生效或出现白色垂直空隙，请尝试建议留一列不设宽度以适应弹性布局` 这段提示。加上[nzWidth]复现地址就正常了，自己的项目里留了一列不设宽度的表格也正常了

ok 如果后面还有其他问题可以提 issue，这个先关闭了
