### ISSUE TITLE
Carousel content slide down when the content is too high and vertical scroll bar shows

### ISSUE THREAD

**Issue by Aralhi** [NG-ZORRO/ng-zorro-antd#774]
# Version
0.6.7
# Reproduction link
http://plnkr.co/edit/hd5AxL117oQquGgt4pv0?p=catalogue
# Steps to reproduce
1. add four slideContents for Carousel
2. set the height of slideContent 500px
3. set the width of slideContent to 100%, same with the screen。

I found something after debugged the source code. 

1. renderContent  run twice
2. After `this._renderer.removeStyle(this.slickTrack.nativeElement, 'width');`
the content will slide down when the width is removed, and vertical scroll bar shows. On this moment, `this.hostElement.nativeElement.offsetWidth` is not equal to the real width of content(either to the screen). It cannot reset by``this._renderer.setStyle(this.slickTrack.nativeElement, 'width', `${this.slideContents.length * this.hostElement.nativeElement.offsetWidth}px`);``. The width of slickTrack smaller then the width of slideContents, and content slide down.
3. And I found it works well when `this._renderer.removeStyle(this.slickTrack.nativeElement, 'width');` is removed. I wonder it will case other bugs or not when this line is removed.
4. I found it on my windows, and it works well on my Mac(Both chrome 63). Maybe there is no scroll bar on chrome of mac.

**Comment by vthinkxie** [comment]
ref #1072

**Comment by vthinkxie** [comment]
fixed in version 0.7.0, please check it , thanks
