### ISSUE TITLE
cron组件的样式定义影响了折叠面板

### ISSUE THREAD

**Issue by ymind** [NG-ZORRO/ng-zorro-antd#7745]
### Reproduction link
[https://ng.ant.design/components/collapse/zh](https://ng.ant.design/components/collapse/zh)

### Steps to reproduce
查看官网文档即可：https://ng.ant.design/components/collapse/zh

### What is expected?
上下左右留白统一为16px

### What is actually happening?
现在的情况是左右留白变成了36px

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.2.1 |
| Browser | all |

---
造成该问题的代码位置（不知是否只此一处）：

https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/cron-expression/style/index.less#L120-L126

**Comment by simplejason** [comment]
Please overwrite the css to avoid it for now, we will fix it in this week with `v14.2.2` :)
