### ISSUE TITLE
Modal Footer Directive Not work

### ISSUE THREAD

**Issue by jhmagicloud** [NG-ZORRO/ng-zorro-antd#7746]
### Reproduction link
[https://stackblitz.com/edit/angular-rsj1kv?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts](https://stackblitz.com/edit/angular-rsj1kv?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts)

### Steps to reproduce
点击In Component 按钮

### What is expected?
Footer 展示Custom Callback 和 Custom Submit 两个按钮

### What is actually happening?
展示了Cancel和Ok

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.4.0 |
| Browser | chrome |

**Comment by simplejason** [comment]
Add `NzModalCustomFooterComponent` to `declarations`:
https://stackblitz.com/edit/angular-cxfjyy?file=src%2Fapp%2Fapp.module.ts%3AL44,src%2Fapp%2Fapp.component.ts
