### ISSUE TITLE
Ngzorro graph is not working

### ISSUE THREAD

**Issue by gan0928** [NG-ZORRO/ng-zorro-antd#7748]
### Reproduction link
[https://stackblitz.com/edit/angular-vnp6c2?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-vnp6c2?file=src/app/app.component.ts)

### Steps to reproduce
Just click above Stackblitz will see the error

### What is expected?
Working fine with the latest angular 14

### What is actually happening?
Error in src/app/app.component.ts (104:9)
Type '{ id: string; label: string; }' is not assignable to type 'NzGraphNodeDef'.
Object literal may only specify known properties, and 'id' does not exist in type 'NzGraphNodeDef'.

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.2.1 |
| Browser | Chrome, Edge |

![image](https://user-images.githubusercontent.com/19318827/204412920-a5e61da3-b72f-417d-8602-9674d793968c.png)

**Comment by simplejason** [comment]
The demo missed some dependencies, please check [this example](https://stackblitz.com/edit/angular-vnp6c2-mdgyg6?file=package.json,angular.json,src%2Fstyles.css) :)

**Comment by gan0928** [comment]
Noice~~~

Thanks for the example.
