### ISSUE TITLE
ngModelChange not firing with nz-switch

### ISSUE THREAD

**Issue by ludovicoq** [NG-ZORRO/ng-zorro-antd#7754]
### Reproduction link
[https://stackblitz.com/edit/angular-frfzcy?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-frfzcy?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Simply call ngModelChange inside nz-switch and then log the event... the function is not even called

### What is expected?
When using ngModelChange will emit an event of type boolean on switch change

### What is actually happening?
The boolean event is not being fired using ngModelChange

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.2.1 |
| Browser | Chrome |

**Comment by lmioco** [comment]
The event `(ngModelChange)` will work only if `[ngModel]` is passed to the nz-switch.

**Comment by ludovicoq** [comment]
> The event `(ngModelChange)` will be emitted only if `[ngModel]` is passed to the nz-switch.

Yes that works indeed. I really appreciate your answer dear Mr. Ludovico. From this answer it is clear that you are a senior developer with a lot of experience. Again thanks for the beaufiful reply, very appreciated! Cheers!

**Comment by amomesso** [comment]
The NgModel class has the update property with an EventEmitter instance bound to it. This means you can’t use (ngModelChange) without ngModel.
![image](https://user-images.githubusercontent.com/92845421/206149849-4f62f0f4-7c7b-4152-942a-43159ff0d666.png)
