### ISSUE TITLE
customize popover inner content style ?

### ISSUE THREAD

**Issue by SealinGp** [NG-ZORRO/ng-zorro-antd#7763]
## What problem does this feature solve?
just like this issue(antd in react) https://github.com/ant-design/ant-design/issues/32275

need to override the styles for the `ant-popover-inner-content` through the existing Popover API.

## What does the proposed API look like?
just like this issue https://github.com/ant-design/ant-design/issues/32275
![image](https://user-images.githubusercontent.com/32982627/206618269-6ae54787-f97e-4d26-8421-6ab9216a39ae.png)

i follow the instrution but it didn't work in angular
![image](https://user-images.githubusercontent.com/32982627/206618413-19ca153f-08e3-46f5-9d15-ade3d43087cd.png)
![image](https://user-images.githubusercontent.com/32982627/206618736-16907e0b-ceab-40bd-942a-05598dcdeeb2.png)

**Comment by OriginRing** [comment]
@SealinGp ::ng-deep{.ant-popover-inner-content { padding: 0;}}

**Comment by sazedur-strativ** [comment]
```
  useEffect(() => {
    const style = document.createElement('style');
    style.innerHTML = `
      .ant-popover-inner-content {
        padding:0;
      }
    `;
    document.head.appendChild(style);
    return () => document.head.removeChild(style);
  }, []);
```
