### ISSUE TITLE
官网的钉钉群怎么是个防疫的网页

### ISSUE THREAD

**Issue by xiaoke-1** [NG-ZORRO/ng-zorro-antd#7771]
## What problem does this feature solve?
https://ng.ant.design/docs/introduce/zh#%E7%A4%BE%E5%8C%BA%E4%BA%92%E5%8A%A9
钉钉群二维码

## What does the proposed API look like?
钉钉群二维码

**Comment by simplejason** [comment]
可能是转发问题，我们今天会更新，感谢反馈
