### ISSUE TITLE
Bold font in nz-select

### ISSUE THREAD

**Issue by GustavoEduardo** [NG-ZORRO/ng-zorro-antd#7795]
## What problem does this feature solve?
Hello how are you?
A user of the system reported a detail that intrigued me. the nx-option of nz-select when clicking on the scroll bar for the first time and dragging it holding it, after some options (usually the last ones), are in bold.

This behavior can be observed on the page of this component in the first two selects of the Sizes example

https://ng.ant.design/components/select/en#ng-content

I believe that it is not necessary to report a bug because it is a detail that does not interfere with the usability of the system, but if there is a way that I have not found so that this does not happen anymore, please let me know.

Thanks

## What does the proposed API look like?
this can prevent the user from thinking that he is selecting several options at once.

**Comment by Laffery** [comment]
Could you please provide a reproduction screenshot or video?
