### ISSUE TITLE
ng-zorro slider bullet point

### ISSUE THREAD

**Issue by butilka123** [NG-ZORRO/ng-zorro-antd#7817]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-2sk5wq?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-2sk5wq?file=src/app/app.component.ts)

### Steps to reproduce
Use Version 13.4.0 or higher

### What is expected?
I expect that I can click the bullet point directly at 100C°

### What is actually happening?
I can't click the bullet point at 100C°

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.4.0 |
| Browser | Edge |

---
In earlier Versions you can click the bullet point directly, see here: https://ng.ant.design/version/12.1.x/components/slider/en

[Not working:](https://ng.ant.design/version/13.4.x/components/slider/en)
![Not working image](https://i.imgur.com/mgGp0xO.png)

[Working:](https://ng.ant.design/version/12.1.x/components/slider/en)
![Working image](https://i.imgur.com/IUls5Bh.png)

**Comment by OriginRing** [comment]
The button is not on the slider
