### ISSUE TITLE
中文镜像网站版本更新落后

### ISSUE THREAD

**Issue by luckyship** [NG-ZORRO/ng-zorro-antd#7821]
## What problem does this feature solve?
中文镜像网站版本更新应和最新版本保持一致

## What does the proposed API look like?
中文镜像网站版本更新应和最新版本保持一致
![image](https://user-images.githubusercontent.com/22162049/215776367-b3227f42-1cdc-4a20-b955-0f077ef0c4a0.png)
![image](https://user-images.githubusercontent.com/22162049/215776514-83b64e36-59f5-43c5-8b3d-14d5b4b5fe12.png)

**Comment by Laffery** [comment]
duplicate #7912
