### ISSUE TITLE
Typography on link consist unrecognizable HTML <Link /> tag

### ISSUE THREAD

**Issue by Shahar-Galukman** [NG-ZORRO/ng-zorro-antd#7832]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/typography/demo/text.ts#L21](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/typography/demo/text.ts#L21)

### Steps to reproduce
Copy paste provided example from ant-zorro example documentation to any IDE (e.g JetBrains WebStorm)

### What is expected?
Example code recognized properly by IDE

### What is actually happening?
<Link /> HTML tag falsely recognized as <link> HTML tag used to load stylesheets.

| Environment | Info |
|---|---|
| ng-zorro-antd | 15.0.2 |
| Browser | Chrome |

---
Would appreciate clarification for this odd tag, as it doesn't seem to even follow HTML RDFa (https://www.w3.org/TR/html-rdfa/)

**Comment by Shahar-Galukman** [comment]
Adding screenshot for better clarification of false recognition by IDE
<img width="649" alt="image" src="https://user-images.githubusercontent.com/4593289/218962765-d1794343-ae87-406f-8cb4-e6432ef8a8dc.png">

**Comment by hsuanxyz** [comment]
@Shahar-Galukman Oh, this code shouldn't be here, would you like to submit a PR to fix it?

**Comment by Shahar-Galukman** [comment]
@hsuanxyz Sure, have a look when possible  https://github.com/NG-ZORRO/ng-zorro-antd/pull/7834

**Comment by hsuanxyz** [comment]
@Shahar-Galukman Thanks, I have done that, it will be correct in the next release.
