### ISSUE TITLE
nz-input-number does not show trailing zero

### ISSUE THREAD

**Issue by skwny** [NG-ZORRO/ng-zorro-antd#7845]
### Reproduction link
[https://stackblitz.com/edit/angular-j3gtkx?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-j3gtkx?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. Add a 0 to the end of the input in the component HTML (3.5 -> 3.50).
2. Click out of the input box.
3. Notice the number changes from 3.50 back to 3.5.

### What is expected?
Expect trailing zeros to conform to the specified nzPrecision value.

### What is actually happening?
Trailing zeros are not displaying to meet nzPrecision requirement.

| Environment | Info |
|---|---|
| ng-zorro-antd | 15.0.2 |
| Browser | Version 108.0.5359.124 (Official Build) (x86_64) |

---
The use case for this is when dealing with a number that typically uses a trailing zero, such as a currency. $3.50 is normally displayed (not $3.5).

**Comment by OriginRing** [comment]
@skwny 
```
[nzFormatter]="formatterDollar"

formatterDollar = (value: number): string => {
    if (String(value).split('.').pop().length !== 2) {
      return `${value}0`;
    } else {
      return `${value}`;
    }
};
```

**Comment by skwny** [comment]
@OriginRing has the right solution. Thank you 🙏
