### ISSUE TITLE
nz-select dropdown content does not scroll with the modal parent

### ISSUE THREAD

**Issue by maidmehic** [NG-ZORRO/ng-zorro-antd#7865]
### Reproduction link
[https://stackblitz.com/edit/angular-a5kqqf?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-a5kqqf?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Open the modal.
Click the nz-select control.
Scroll the modal content.

### What is expected?
`nz-select` dropdown content should scroll together with the rest of the page and follow the control.

There are many tickets regarding this on `ant-design` repo. Please take a look: https://github.com/ant-design/ant-design/issues/8268

### What is actually happening?
`nz-select` dropdown content does not move with the rest of the page and is fixed in one position.

![Screenshot 2023-03-08 at 11 51 07](https://user-images.githubusercontent.com/45770647/223693997-04592119-b00a-482a-bcf5-c764e77151a3.png)

| Environment | Info |
|---|---|
| ng-zorro-antd | 15.0.2 |
| Browser | Chrome |

**Comment by Galiza** [comment]
This currently happens on the newer version as well.

ng-zorro-antd | 15.0.3
-- | --

**Comment by felipesantos1504** [comment]
this happens to me aswell but with the nz-mention, but in the demo docs it does work

**Comment by vhphuc** [comment]
this issue only occur when use in nz-modal.

**Comment by danilmoro3** [comment]
The same for DatePicker, TreeSelect, etc. Reproduces in Drawer component as well.

**Comment by ttakennn** [comment]
hi @vthinkxie 
I got the same issue. Please help to fix this issue.

**Comment by DownAndDoerrty** [comment]
@vthinkxie, I'm also having the same issue

**Comment by alexmao1024** [comment]
I also have the same issue, and there are many dropdown menus in my project that exist on a scrollable page. This is a significant issue for me. Has anyone fixed it yet?

**Comment by majid-seifi** [comment]
I also have the same issue! Has anyone any solution?

**Comment by saikrishnasandiri** [comment]
Iam also having same issue

**Comment by is-tongben** [comment]
Listen for box scrolling events, trigger the 'updateCdkConnectedOverlayPositions' method of the' NzSelectComponent ' instance element
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/22648810/19e9fcd5-846d-4309-a2ce-a64055947401)

**Comment by Guruprasanth98** [comment]
Iam also having same issue. please help me someone

**Comment by mehdiboutoumit** [comment]
Same issue.

**Comment by andressalhenriques** [comment]
trans

**Comment by andressalhenriques** [comment]
Hi. Someone find a solution ?

**Comment by nainiteknol123** [comment]
Is there any solution for this ?

**Comment by Lukinoh** [comment]
As a workaround, you can write a custom [ScrollDispatcher](https://github.com/angular/components/blob/main/src/cdk/scrolling/scroll-dispatcher.ts).
The `ScrollDispatcher` is used to emit an event when any one of the Scrollable references emit a scrolled event.
It is used to update the position of an overlay when a scroll occurs, and by default, it listens only to the `document.defaultView.window`.

So I wrote the following `CustomScrollDispatcher` that will listen to all scroll events in your page, and register the `HTMLElement` who was scrolled in the `ScrollDispatcher`.
Hence, when you scroll it, the dropdown position will be updated.

Code is provided as is, I didn't notice yet any side effects.

```typescript
import {
  ClassProvider,
  ElementRef,
  Inject,
  Injectable,
  NgZone,
  Optional,
} from "@angular/core";
import {CdkScrollable, ScrollDispatcher} from "@angular/cdk/overlay";
import {Platform} from '@angular/cdk/platform';
import {DOCUMENT} from "@angular/common";

@Injectable({providedIn: 'root'})
class CustomScrollDispatcher extends ScrollDispatcher {

  private scrollables: Map<HTMLElement, CdkScrollable> = new Map();

  constructor(_ngZone: NgZone,
              _platform: Platform,
              @Optional() @Inject(DOCUMENT) document: any) {
    super(_ngZone, _platform, document);
    this.registerAllScrollsAsScrollables(document, _ngZone);
  }

  registerAllScrollsAsScrollables(document: Document, ngZone: NgZone) {
    document.addEventListener('scroll', (event) => {
      if (event.target instanceof HTMLElement) {
        if (!this.scrollables.has(event.target)) {
          // Avoid memory leaks
          this.cleanScrollables();

          const scrollable = new CdkScrollable(new ElementRef(event.target), this, ngZone);
          this.scrollables.set(event.target, scrollable);
          this.register(scrollable)
        }
      }
    }, true)
  }

  cleanScrollables(): void {
    for (const [element, scrollable] of this.scrollables) {
      if (!element.isConnected) {
        this.scrollables.delete(element);
        this.deregister(scrollable);
      }
    }
  }

  override ngOnDestroy() {
    super.ngOnDestroy();
    this.scrollables.clear();
  }
}

export const CustomScrollDispatcherProvider: ClassProvider = {
  provide: ScrollDispatcher,
  useClass: CustomScrollDispatcher,
};

// export const appConfig: ApplicationConfig = {
//   providers: [CustomScrollDispatcherProvider, ...]
// };

```

**Comment by StefaniOSApps** [comment]
same

**Comment by ParsaArvanehPA** [comment]
This PR will fix the issue mentioned above for all components created with the CDK Overlay that are inside modals or drawers: #8804.


As a temporary fix, you can follow these steps:
- Create a wrapper inside your modal or drawer
- Add the cdkScrollable directive to the wrapper
- Set overflow: auto on the wrapper

This way, the wrapper will handle the scrolling.
You can refer to this [link](https://stackblitz.com/edit/angular-sg8j5f?file=src%2Fapp%2Fapp.component.ts) for a sample.

**Comment by ZeevKatz** [comment]
After 20v installation this issue is reproduced even when wrapping the select with cdk scrollable.
Suggest reopening this thread.

Here is a temporary workaround:
```ts
@Directive({ selector: 'nz-select[updatePositionOnScroll]' })
export class NzSelectUpdatePositionOnScrollDirective {
  private readonly scrollDispatcher = inject(ScrollDispatcher);
  private readonly elementRef = inject(ElementRef);
  private readonly nzSelect = inject(NzSelectComponent);

  constructor() {
    this.scrollDispatcher
      .ancestorScrolled(this.elementRef, 0)
      .pipe(
        throttleTime(0, animationFrameScheduler),
        filter(() => !!this.nzSelect.nzOpen),
        takeUntilDestroyed()
      )
      .subscribe(() => this.nzSelect.cdkConnectedOverlay?.overlayRef?.updatePosition());
  }
}
```
