### ISSUE TITLE
WIP NG-ZORRO TODOS

### ISSUE THREAD

**Issue by simplejason** [NG-ZORRO/ng-zorro-antd#7887]
> NG-ZORRO-ANTD 目前升级至 V15 后，还有许多特性需要支持和完善，这里将列出组件库需要支持的功能内容和用户关心的需求列表，将在后续版本中尽快支持，今年也会努力扩大社区同学的参与度

- [x] [typed form](https://angular.io/guide/typed-forms)
- [ ] ant-design 样式同步问题（less vs Css-in-js）
- [ ] ant-design 未支持组件的开发
- [ ] 常用的业务组件，逐步在实验性功能支持
- [ ] 与 antv 集成使用
- [ ] 发版周期：minor version（1-2 周内），major version（1 月内）
- [ ] 社区活跃用户参与，提供技术支持和小礼品
- [ ] 更多...

---
> Currently, after upgrading to V15, there are still many features that NG-ZORRO-ANTD needs to support and improve. Here is a list of the functional content and user requirements that we need to support, which will be supported as soon as possible in future versions. We will also strive to expand the participation of the community students this year.

- [x] [typed form](https://angular.io/guide/typed-forms)
- [ ] Synchronization with antd styles（less vs Css-in-js）
- [ ] Implementing the unsupported antd components
- [ ] More experimental features supported
- [ ] ANTV in NG-ZORRO
- [ ] More community users to participate in development
- [ ] More...

**Comment by HyperLife1119** [comment]
And [`space-compact`](https://4x.ant.design/components/space-cn/#components-space-demo-compact) component.

**Comment by HyperLife1119** [comment]
我想我们应该先完成 antd-v4 的样式同步，已经有一段时间没进行同步了：
https://github.com/NG-ZORRO/ng-zorro-antd/commits?author=ng-zorro-bot

**Comment by santoshyadavdev** [comment]
I see no tasks to improve code samples to support the Standalone component approach. I tried to use the menu component in my last stream, and I have some ideas about updating the docs. Should I create a new issue? Or can we add more in this issue for docs and code samples?

**Comment by HarryPitsillides** [comment]
Do we have any update in regards to  Synchronization with antd styles（less vs Css-in-js）?

**Comment by HyperLife1119** [comment]
我想我们应该尽快完成 antd **v4** 的样式同步，已经有很长一段时间没进行同步了：
https://github.com/NG-ZORRO/ng-zorro-antd/commits?author=ng-zorro-bot
目前已同步到 v4.20.6，最新的是 v4.24.14

@OriginRing @simplejason
