### ISSUE TITLE
The fast-way of nz-tooltip should support all original configurations

### ISSUE THREAD

**Issue by qq67999427** [NG-ZORRO/ng-zorro-antd#791]
## What problem does this feature solve?

<a nz-tooltip="Most simple prompt text" href="#">Most simple way to trigger a tooltip!</a>
Position to be able to specify

## What does the proposed API look like?

<a nz-tooltip="Most simple prompt text" href="#">Most simple way to trigger a tooltip!</a>
Position to be able to specify
<a nz-tooltip="Most simple prompt text" nz-Placement="bottom" href="#">Most simple way to trigger a tooltip!</a>

**Comment by vthinkxie** [comment]
@wilsoncook

**Comment by wilsoncook** [comment]
Not only `nzPlacement `, the other configs will be supported
