### ISSUE TITLE
日期选择框，在选择跨年份的周日期时，文本框中年份信息显示不正确

### ISSUE THREAD

**Issue by tzyuan** [NG-ZORRO/ng-zorro-antd#7916]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-jwyulb?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-jwyulb?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
2021年第52周范围是（2021-12-26 ~ 2022-01-01），当鼠标点击2021年12月26~31日时，文本框中的格式为2021-52。而当鼠标点击2022-01-01时，文本框中的格式为2022-52。

### What is expected?
期望文本框中可是显示正确的年份信息，而不是根据鼠标点击的日期显示年份
即：在周选择模式下，点击2021-12-26 ~ 2022-01-01当中任何一天文本框中显示的都是2021-52

### What is actually happening?
在周选择模式下，点击2021年12月26~31日时，文本框中的格式为2021-52。而当鼠标点击2022-01-01时，文本框中的格式为2022-52。

| Environment | Info |
|---|---|
| ng-zorro-antd | 15.1.0 |
| Browser | chrome 112.0.5615.49 |

**Comment by Laffery** [comment]
感谢您的反馈，我们会在后续版本修复这个问题。如果你有好的实现思路，欢迎提交 PR！
