### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by jornare** [NG-ZORRO/ng-zorro-antd#7929]
## What problem does this feature solve?
Angular 16 just got released. Ng-zorro-antd should be compatible with the newest Angular release.

## What does the proposed API look like?
ng-zorro-antd supports Angular 16

**Comment by jornare** [comment]
Just made a PR to update the ant-design-icons package to v16 also. https://github.com/ant-design/ant-design-icons/pull/564

**Comment by Nicoss54** [comment]
Hey currently some depencies of ng-zorro make the migration complicated:
- ant-design-icons-angular (PR: already done)
- angular-builder-custom-webpack

**Comment by simplejason** [comment]
> Hey currently some depencies of ng-zorro make the migration complicated:

added:
- [ ]  `ngx-color`: not compatible with Angular Ivy

**Comment by Nicoss54** [comment]
> > Hey currently some depencies of ng-zorro make the migration complicated:
> 
> added:
> 
> * [ ]   `ngx-color`: not compatible with Angular Ivy

it seems that the last version of this package is compatible with Angular Ivy

**Comment by simplejason** [comment]
> > > Hey currently some depencies of ng-zorro make the migration complicated:
> > 
> > 
> > added:
> > 
> > * [ ]    `ngx-color`: not compatible with Angular Ivy
> 
> it seems that the last version of this package is compatible with Angular Ivy

Cool, I'll try the latest version. It works fine(`ng serve`) on my computer after I removed `ngx-color` and upgraded to angular v16, I think we can release `ng-zorro-antd@16.0.0-beta.0` after everything is ready.(`migrations` / `tests` .etc.)

**Comment by Nicoss54** [comment]
> > > > Hey currently some depencies of ng-zorro make the migration complicated:
> > > 
> > > 
> > > added:
> > > 
> > > * [ ]     `ngx-color`: not compatible with Angular Ivy
> > 
> > 
> > it seems that the last version of this package is compatible with Angular Ivy
> 
> Cool, I'll try the latest version. It works fine(`ng serve`) on my computer after I removed `ngx-color` and upgraded to angular v16, I think we can release `ng-zorro-antd@16.0.0-beta.0` after everything is ready.(`migrations` / `tests` .etc.)

I checked where ngx-color is used :) it seens it's used for the doc site applicationa and the demo water-mark

**Comment by simplejason** [comment]
> I checked where ngx-color is used :) it seens it's used for the doc site applicationa and the demo water-mark

@Nicoss54 Right, it's used in demos of `water-mark`(we can remove it to avoid third-party dependency). Most of our dependencies do not change :) The only thing that needs attention right now is the upgrade tool(`@schematics`)

**Comment by simplejason** [comment]
Also, before we upgrade to v16, we need to sync themes from `ant-design@5.x`, @hsuanxyz is working on this :)

**Comment by MunMunMiao** [comment]
> Also, before we upgrade to v16, we need to sync themes from `ant-design@5.x`, @hsuanxyz is working on this :)

so. in v16 we can use ant-design 5 style ?

**Comment by zhenzhenChange** [comment]
I would like to know how `Angular` supports `JSS`.

**Comment by Nicoss54** [comment]
> any update?

there is already a PR: https://github.com/NG-ZORRO/ng-zorro-antd/pull/7934 for this. This PR is still in draft mode

Waiting an update of two package that depends NG-Zorro

**Comment by conioX** [comment]
can we release beta version 16?

**Comment by junshengL** [comment]
in v16 we can use ant-design 5 style ?

**Comment by simplejason** [comment]
> in v16 we can use ant-design 5 style ?

Not in `16.0.0` , maybe in the future version `16.x`, we need to sync styles(`css-in-js`) from antv-v5 and make sure it can work.

**Comment by qyjs** [comment]
> Where are we with support for v16?

already ng16

**Comment by alexgit2k** [comment]
> > Where are we with support for v16?
> 
> already ng16

But this issue is still open and the [Readme](https://github.com/NG-ZORRO/ng-zorro-antd/blob/6d31bde3ef1f43cc145d2009afcf90931e96a731/README.md#-environment-support) still says Angular 15:

https://github.com/NG-ZORRO/ng-zorro-antd/blob/6d31bde3ef1f43cc145d2009afcf90931e96a731/README.md?plain=1#L53

**Comment by dylanvdmerwe** [comment]
Does the 16.1.0 release mean that Angular 16 support is _finally_ ready? The delays in updating to the latest Angular versions is pretty dismal.

**Comment by Nicoss54** [comment]
> Does the 16.1.0 release mean that Angular 16 support is _finally_ ready? The delays in updating to the latest Angular versions is pretty dismal.

Yes, since the version 16, angular v16 is supported

**Comment by alexgit2k** [comment]
> > Does the 16.1.0 release mean that Angular 16 support is _finally_ ready? The delays in updating to the latest Angular versions is pretty dismal.
> 
> Yes, since the version 16, angular v16 is supported

So why is this issue still open and the Readme still says Angular 15?

**Comment by Nicoss54** [comment]
> > > Does the 16.1.0 release mean that Angular 16 support is _finally_ ready? The delays in updating to the latest Angular versions is pretty dismal.
> > 
> > 
> > Yes, since the version 16, angular v16 is supported
> 
> So why is this issue still open and the Readme still says Angular 15?

It’s an issue. Just look the package.json https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/package.json here. 

The dependencies are for angular 16. You can use angular 16 with ng-zorro v16 without problems. 

It seems that the readme is not up to date. It will be fix soon

**Comment by Nicoss54** [comment]
Ng Zorro support Angular 16 since the version 16

**Comment by tomcek112** [comment]
> Also, before we upgrade to v16, we need to sync themes from `ant-design@5.x`, @hsuanxyz is working on this :)

Sorry to dig this issue back up but it's the only place I see `ant-design@5.x` mentioned.

@simplejason do you have an update on this? We're currently evaluating adopting `ng-zorro` internally so I'd just like to know if the version drift is still considered only temporary or if this will be a more permanent thing. Thanks a lot!
