### ISSUE TITLE
建议：Transfer组件数据在左右穿梭时能否增加一个校验方法

### ISSUE THREAD

**Issue by bokire** [NG-ZORRO/ng-zorro-antd#793]
## What problem does this feature solve?

某些情况需要后台远程校验或者同步数据，当远程校验方法返回true是才能进行左右穿梭

## What does the proposed API look like?

`
canMove(param:any):boolean | Observable<boolean> | Promise<boolean> {
   ...
}
`

**Comment by vthinkxie** [comment]
@cipchk

**Comment by cipchk** [comment]
真有这种必要吗？对于可被穿梭不应该在一开始加载过程中就可以确认了吗？我不清楚这个需求在实际中是怎么样的一种场景。

**Comment by bokire** [comment]
@cipchk 
原先我的需求是，在点击“穿梭”按钮的时候，将数据提交到后台进行处理。若处理成功了，页面再进行穿梭。
按照目前的提供的API，只能数据全部穿梭完成后，再通过“保存”按钮一起提交到后台进行处理。
虽然也能完成功能，但中间需要多点击一次“保存”按钮。

**Comment by bokire** [comment]
也想过用nzChange方法进行自动提交，但执行nzChange方法时页面上已经完成穿梭。。这时候如果后台处理失败，页面上又需要将数据恢复提交前的样子，此时页面上的数据会出现来回穿梭闪现的情况。
