### ISSUE TITLE
建议：关于时间轴幽灵节点的建议

### ISSUE THREAD

**Issue by bokire** [NG-ZORRO/ng-zorro-antd#794]
## What problem does this feature solve?

当我在页面中添加幽灵节点后  
 
`<ng-template #pending>
        <a>See more</a>
</ng-template> `
无法在对应的component.ts中通过变量灵活的隐藏、显示这个幽灵节点

## What does the proposed API look like?

方案1、在nz-timeline中增加一个属性，用来控制是否显示幽灵节点
方案2、可以动态的指定幽灵节点的对应的ng-template，而不是固定的#pending。。

**Comment by leoshuaige** [comment]
fuck you

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed
