### ISSUE TITLE
Modal  设置 [nzMask]="false" 不生效

### ISSUE THREAD

**Issue by jhsonlee** [NG-ZORRO/ng-zorro-antd#7942]
### Reproduction link
[https://stackblitz.com/edit/angular-aug4hy?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts](https://stackblitz.com/edit/angular-aug4hy?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts)

### Steps to reproduce
就直接用不行,但是官方的例子可以,不知道原因

### What is expected?
能实现

### What is actually happening?
不能实现

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.3.0 |
| Browser | Google Chrome |

---
就直接用不行,但是官方的例子可以,不知道原因

**Comment by lifo-linxuanli** [comment]
你设置的 [nzMask]="false"已经生效了，你设成true再对比一下

**Comment by jhsonlee** [comment]
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/95340822/61f2c37a-a3f0-4bdb-9c0a-c28db1287423)
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/95340822/336ce78f-7621-4bcf-ba62-3f80454243cb)

**Comment by lifo-linxuanli** [comment]
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/69353714/65521c98-ef28-4770-ad8d-4ba953cebe95)
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/69353714/14053211-4bce-458f-b867-24bf4e1c3af3)

**Comment by jhsonlee** [comment]
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/95340822/fca9e0ca-3929-4594-b73c-6b77c278798d)

所以在标题里说明了,例子是生效的,但是开发的时候不生效,我都是完全copy了例子,package 也是是一致的,这才是我提出问题的原因

**Comment by lifo-linxuanli** [comment]
那建议不要把正常的例子放到 reproduction link里面。
还有，你没有可复现的例子，这大概率是你个人项目的配置问题。 
你可以尝试新建一个项目，使用跟你自己项目相同的packge.json，看是否能复现。

如果仍然不能复现，那一定是你个人项目的某些配置出问题了。
如果可以复现，可以更新复现的demo link在 reproduction link里面。

**Comment by jhsonlee** [comment]
谢谢你的解答~我尽量试试能否重新重现~再次感谢
