### ISSUE TITLE
How to set the horizontal scroller for table

### ISSUE THREAD

**Issue by leoshuaige** [NG-ZORRO/ng-zorro-antd#795]
Why does the table have no lateral scrollbar? Vertically setting y is the scroll bar that can be set up and down. However, when there are dozens of tables in my form, a page is incomplete. At this time, I want to slide the table horizontally, just like setting up {y:240px}.

**Comment by vthinkxie** [comment]
not supported now, you can add some style to achieve the goal
https://stackblitz.com/edit/ng-zorro-antd-setup-mqorph?file=app%2Fapp.component.css
