### ISSUE TITLE
Make step-counter optional in nz-input [type=number]

### ISSUE THREAD

**Issue by syamsmenon1** [NG-ZORRO/ng-zorro-antd#7956]
## What problem does this feature solve?
I hope this message finds you well.Currently, there is a step counter implemented in the input field [when we allow " type=number" ], allowing users to increment or decrement the number. However, we would like to make this step counter optional, giving developers the flexibility to choose whether to use it or not.

## What does the proposed API look like?
<nz-input-group>
  <input
    type="number"
    min="0"
   stepCounterEnabled="false"
  />
</nz-input-group>
I have introduced the "stepCounterEnabled" variable, which can be set to true or false based on your requirements or any user-defined conditions. When stepCounterEnabled is true, the step counter will be enabled, allowing users to increment or decrement the number. On the other hand, when stepCounterEnabled is false, the step counter will be disabled.

**Comment by Nicoss54** [comment]
@syamsmenon1  ?

**Comment by syamsmenon1** [comment]
Thank You For Reply.
yeah , i have used html input classic with the directive nz-input and the type number

**Comment by Nicoss54** [comment]
> Thank You For Reply. yeah , i have used html input classic with the directive nz-input and the type number.

Hey @syamsmenon1 this PR: #8003 normally implement your request. 

Happy coding, and thanks for reporting

**Comment by syamsmenon1** [comment]
Thank you so much for letting me know about PR: #8003.
Happy coding to you too, and thanks again for your swift action on this.
