### ISSUE TITLE
v16 date-picker component use nzShowTime, ngModel is not update.

### ISSUE THREAD

**Issue by NickBoomBoom** [NG-ZORRO/ng-zorro-antd#7976]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-qjpih3?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-qjpih3?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
   If you increase the current time by 1 minute, there is no change in the data.

   But when you add two minutes, the data changes.

   ex:

      2023-06-05 17:22  add  1 minute  =>  2023-06-05 17:23; no changes

      2023-06-05 17:22 add 2 minute => 2023-06-05 17:24; changes 

### What is expected?
Data synchronization update

### What is actually happening?
https://github.com/NG-ZORRO/ng-zorro-antd/pull/7948
The v16 version does not fully fix the issue

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.0.0 |
| Browser | chrome |

**Comment by NickBoomBoom** [comment]
Will it be repaired online these days?

**Comment by NickBoomBoom** [comment]
Will it be fixed in the next version?

**Comment by Nicoss54** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/pull/7998

**Comment by Nicoss54** [comment]
@NickBoomBoom this is fix in the PR: #7998 

@simplejason, if pipeline pass are you agree that I merge this PR ?

**Comment by NickBoomBoom** [comment]
Although the pr merged is in master, no new version has been released.
I don't think it's a proper way to close the problem like this. At least you need to close it after releasing a new version.
