### ISSUE TITLE
nz-menu-item 中，无论 nzSelected是什么值，所有的菜单都是选中状态

### ISSUE THREAD

**Issue by goinni** [NG-ZORRO/ng-zorro-antd#798]
## Version

0.6.7

## Environment

chrome,"ng-zorro-antd": "^0.6.1"

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd/issues/new](https://github.com/NG-ZORRO/ng-zorro-antd/issues/new)

## Steps to reproduce

<li nz-submenu *ngFor="let item of menus.hasChildren">
        <span title><i class="anticon {{item.icon}}"></i><span class="nav-text" >{{item.title}}</span></span>
        <ul>
          <li nz-menu-item nzSelected="false" (click)="goto(child.link, child.event)" *ngFor="let child of item.children">{{child.title}}</li>
        </ul>
      </li>

## What is expected?

我想通过 nzSelected 动态计算的值 控制 菜单是否选中 （页面有两个导航部分：面包屑导航 和左侧菜单导航 ，希望这两个导航样式能同步，比如面包屑导航当前是 
 "订单列表"，那么左侧导航应该也选中订单列表 ）

## What is actually happening?

无论 nzSelected是什么值，我的所有的菜单都是选中状态

## Other?

<ul nz-menu [nzTheme]="'dark'" [nzMode]="isCollapsed?'vertical':'inline'">
      
      <li nz-menu-item [routerLink]="[item.link]" *ngFor="let item of menus.noChildren">
        <span><i class="anticon {{item.icon}}"></i><span class="nav-text" >{{item.title}}</span></span>
      </li>
      
      <li nz-submenu *ngFor="let item of menus.hasChildren">
        <span title><i class="anticon {{item.icon}}"></i><span class="nav-text" >{{item.title}}</span></span>
        <ul>
          <li nz-menu-item nzSelected="false" (click)="goto(child.link, child.event)" *ngFor="let child of item.children">{{child.title}}</li>
        </ul>
      </li>
    </ul>

**Comment by goinni** [comment]
<ul nz-menu [nzTheme]="'dark'" [nzMode]="isCollapsed?'vertical':'inline'">
      
      <li nz-menu-item [routerLink]="[item.link]" *ngFor="let item of menus.noChildren">
        <span><i class="anticon {{item.icon}}"></i><span class="nav-text" >{{item.title}}</span></span>
      </li>
      
      <li nz-submenu *ngFor="let item of menus.hasChildren">
        <span title><i class="anticon {{item.icon}}"></i><span class="nav-text" >{{item.title}}</span></span>
        <ul>
          <li nz-menu-item nzSelected="false" (click)="goto(child.link, child.event)" *ngFor="let child of item.children">{{child.title}}</li>
        </ul>
      </li>
    </ul>

**Comment by goinni** [comment]
`<ul nz-menu [nzTheme]="'dark'" [nzMode]="isCollapsed?'vertical':'inline'">
      
      <li nz-menu-item [routerLink]="[item.link]" *ngFor="let item of menus.noChildren">
        <span><i class="anticon {{item.icon}}"></i><span class="nav-text" >{{item.title}}</span></span>
      </li>
      
      <li nz-submenu *ngFor="let item of menus.hasChildren">
        <span title><i class="anticon {{item.icon}}"></i><span class="nav-text" >{{item.title}}</span></span>
        <ul>
          <li nz-menu-item nzSelected="false" (click)="goto(child.link, child.event)" *ngFor="let child of item.children">{{child.title}}</li>
        </ul>
      </li>
    </ul>`

**Comment by goinni** [comment]
![image](https://user-images.githubusercontent.com/10232688/34239972-f8917a9a-e645-11e7-99a5-de41395a29db.png)

**Comment by vthinkxie** [comment]
please provide the online reproduce link, we can not help you without your code.

**Comment by luodongseu** [comment]
I have the same trouble, I want to dynamic change menu-items' selected state when changed route，but I cannot get the right result every time. 

Code like that:
```
<li nz-menu-item [nzSelected]="item.selected"></li>
```
 And when I change the value of item.selected in ts code, but menu always not show what I want to see.

Can anyone help me ? Thanks!

**Comment by sandogeek** [comment]
> I have the same trouble, I want to dynamic change menu-items' selected state when changed route，but I cannot get the right result every time.
> 
> Code like that:
> 
> ```
> <li nz-menu-item [nzSelected]="item.selected"></li>
> ```
> And when I change the value of item.selected in ts code, but menu always not show what I want to see.
> 
> Can anyone help me ? Thanks!

Same with you.Did you work it out now? I try `[class.ant-menu-item-selected]` did not help anyway.
