### ISSUE TITLE
nz-date-picker not emitting change event when only time is changed.

### ISSUE THREAD

**Issue by rohit267** [NG-ZORRO/ng-zorro-antd#7994]
### Reproduction link
[https://github.com/rohit267/angular-ng-zorro-antd-bug](https://github.com/rohit267/angular-ng-zorro-antd-bug)

### Steps to reproduce
1. Click on the date picker
2. Select a date, press ok.
3. Click outside the date picker.
4. Again click inside the date picker and only change time.

### What is expected?
The time should change without changing date.

### What is actually happening?
Time is not changing without changing the date.

| Environment | Info |
|---|---|
| ng-zorro-antd | 15.1.0 |
| Browser | Chrome |

---
Also it's not emitting any change events.
https://t9rqnf-4200.csb.app
https://codesandbox.io/p/github/rohit267/angular-ng-zorro-antd-bug/

**Comment by rohit267** [comment]
is this related to #7968 ?

**Comment by Nicoss54** [comment]
@rohit267 it's not related to this issus, your issue is already fixed in the last release of Ng-Zorro, you issue is related to this one https://github.com/NG-ZORRO/ng-zorro-antd/issues/7946 which is already closed since the fix is merged

**Comment by rohit267** [comment]
> #7946

Can we have a patch in v15? It's no feasible to update whole `ng-zorro-antd`.

**Comment by pricopz** [comment]
Hi, I have the same issue on v15.1.0 with reactive forms :( . Is there any chance to have a patch for this version also ?

**Comment by vanswang** [comment]
> Hi, I have the same issue on v15.1.0 with reactive forms :( . Is there any chance to have a patch for this version also ?

me too.

**Comment by is-tongben** [comment]
两种方法可以暂时解决，遇到了相同痛点亲测可以使用，遇到的同学可以先尝试一下，下面提供下关键思路和代码
- `@ViewChild` 获取`nz-date-picker`子节点元素（下面简称A元素）
- 通过`nzOnOpenChange`函数（弹出日历和关闭日历的回调）每次关闭面板触发时，获取`A`元素内部`datePickerService.value.nativeDate`，如果不是anyScript 可以手动断言下类型
- 🤔或者，使用内部订阅`A.datePickerService.valueChange$.subscribe...`会实时拿到，订阅的触发频率较高，需要自己防抖处理下
```html
<nz-date-picker #ATarget nzShowTime [nzAllowClear]="false"
    nzFormat="yyyy-MM-dd HH:mm:ss"
    (nzOnOpenChange)="manualUpdatePicker()" formControlName="toTriggerAt" >
```
```js
// 1
public manualUpdatePicker(panelState: boolean): void {
  const a = (this.ATarget.datePickerService.value as SingleValue)?.nativeDate;
}
// 2
 this.ATarget.datePickerService.valueChange$.subscribe({
      next: val => {
        console.log('-----', val)
      }
    })
```
