### ISSUE TITLE
Steps步骤条nzProgressDot点状步骤条CSS响应异常

### ISSUE THREAD

**Issue by 232650413** [NG-ZORRO/ng-zorro-antd#7995]
### Reproduction link
[https://angular-qjrvfp.stackblitz.io](https://angular-qjrvfp.stackblitz.io)

### Steps to reproduce
同样数据，缩放浏览器时，点状步骤条不响应，溢出问题。

### What is expected?
同样数据，缩放浏览器时，CSS响应

### What is actually happening?
同样数据，缩放浏览器时，点状步骤条不响应，溢出问题。

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.0.0 |
| Browser | chrome |

**Comment by OriginRing** [comment]
description 区域的宽度写死了，导致 steps 最小展示宽度为 (140 x  stepNum) px
添加 .ant-steps-item-content{ width: auto }; 可正常展示
