### ISSUE TITLE
QRCode另存为图片的时候能不能增加padding

### ISSUE THREAD

**Issue by wikylyu** [NG-ZORRO/ng-zorro-antd#7999]
## What problem does this feature solve?
当前右键打开QRCode的图片的时候，二维码图片是没有任何padding的，看上去不是很舒服。
建议增加padding设置的选项。

```
blob:null/6f390630-3032-4ce6-91a5-be214464486f
```

## What does the proposed API look like?
QRCode增加 nzPadding 参数，可以为number也可以为 []number，当类型是number的时候表示所有方向的padding，否则按照上右下左的方式处理。

**Comment by Nicoss54** [comment]
Hi, is it possible to a stackblitz to reproduce what you want please ?

**Comment by xItsSky** [comment]
I'll be happy to take care of it

**Comment by Nicoss54** [comment]
> I'll be happy to take care of it

With pleasure, @wikylyu could you give more information please :) ?

**Comment by wikylyu** [comment]
[link](https://ng.ant.design/components/qr-code/en)

Right click the QRCode element, and in the context menu,  choose "Save Image As ...". 

The image saved has a transparent background without any padding. 

I think white background with some padding is better.

**Comment by xItsSky** [comment]
Ok , thanks for the information. I'll take care of it and come back to you once the PR is oppened.

**Comment by xItsSky** [comment]
@wikylyu this issue is fixed in the PR #8001

**Comment by OriginRing** [comment]
下载的 demo 中取的是 canvas 元素，你可以向外再取一层(nz-qrcode)，同时可以添加需要的样式
