### ISSUE TITLE
按钮样式

### ISSUE THREAD

**Issue by lovexurongquan** [NG-ZORRO/ng-zorro-antd#800]
## What problem does this feature solve?

按钮样式不够用，不同场景用的按钮不一样。

## What does the proposed API look like?

希望加点success  warning  info 这类的按钮。

**Comment by vthinkxie** [comment]
@lovexurongquan ng-zorro-antd follow the design rules of ant design.
you can submit your request to https://github.com/ant-design/ant-design

**Comment by lanmingle** [comment]
@vthinkxie 

发现一个问题，最新版本谷歌浏览器，默认：按钮进行加载状态时，边框没有给全覆盖，发现解决方法有两个，一是把边框变为 none，二是把边框颜色同步为加载时的颜色。

https://ng.ant.design/version/0.7.x/components/button/zh

就在这里可以看到。
