### ISSUE TITLE
Sidebar to top navigation for mobile

### ISSUE THREAD

**Issue by vatsake** [NG-ZORRO/ng-zorro-antd#8002]
## What problem does this feature solve?
On smaller screens the sidebar gets in the way, would be better if it was on top.
Like this: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_sidebar_responsive

## What does the proposed API look like?
¯\_(ツ)_/¯

**Comment by Laffery** [comment]
This should be something the developer does at the application level and not at the component library level, try following the example you gave using the media query to implemente, enjoy codeing :)
