### ISSUE TITLE
nzModal的打开时的焦点可以被指定

### ISSUE THREAD

**Issue by rockclock** [NG-ZORRO/ng-zorro-antd#8005]
## What problem does this feature solve?
savePreviouslyFocusedElement被赋值为document.avtiveElement，但是现在的浏览器无法通过divElement.foucs()来改变document.avtiveElement，这迫使我将div改成input来达成目标，如果可以直接在options中设置，那就太好了

## What does the proposed API look like?
`this._nzModalService.create({
      nzFooter: null,
      nzFocusElement: focusDom,
      nzContent: AiVideoComponent,
      nzClosable: false,
      nzCentered: true,
      nzWidth: 'auto',
      nzBodyStyle: {
        padding: '0'
      },
      nzStyle: {
        backgroundColor: 'transparent'
      }
    })`

**Comment by Laffery** [comment]
Feature 描述不是很清晰，根据您给出的 API 示例，似乎您希望指定一个 DOM 元素 focusDom，在 Modal 打开时 focus 到该元素。
这个 focusDom 是 nzConent 组件中的一个元素，显然是不能在 Modal 创建前获取它的，因此这种 API 是不合理的。
您可以尝试在 nzContent 组件中，通过 ngAfterViewInit 钩子获取要聚焦的元素。
