### ISSUE TITLE
级联选择组件自定义已选项后会出现 title="undefined"

### ISSUE THREAD

**Issue by ymind** [NG-ZORRO/ng-zorro-antd#8006]
### Reproduction link
不需要，见下图

![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/315716/e93962b1-252a-4f5b-9831-384b37401322)

### Steps to reproduce
官网文档

### What is expected?
期望无title=“undefined”

### What is actually happening?
有title=“undefined”

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.0.0 |
| Browser | all |

**Comment by OriginRing** [comment]
此 [pr](https://github.com/NG-ZORRO/ng-zorro-antd/pull/8011) 合并后，title将正常展示 选取信息
