### ISSUE TITLE
Unexpected Flickering Behavior in NgZorro Dropdown when Multiple Menu Items are Clicked Subsequently

### ISSUE THREAD

**Issue by KShewengger** [NG-ZORRO/ng-zorro-antd#8009]
### Reproduction link
[https://stackblitz.com/edit/angular-2ftor9?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-2ftor9?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1.) Include multiple nz-menu-item elements within a NgZorro Dropdown component.
2.) Click on one menu item, then the other, and observe the flickering behavior.
3.) Repeat the above step for different menu items, noticing the same flickering behavior.

### What is expected?
- When opening a menu item by clicking on it, the item should remain open until explicitly closed by the user.
- Clicking on a subsequent menu item should not result in a quick open and close action, but rather keep the previously opened item open and smoothly transition to the newly clicked item.
- The opened menu item should not flicker or close abruptly after being clicked.

### What is actually happening?
- When clicking on a menu item, after the prior one, it briefly opens and then immediately closes, resulting in a flickering effect.
- The flickering behavior occurs when clicking on 2 or more items subsequently.

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.0.0 |
| Browser | Chrome |

**Comment by OriginRing** [comment]
Make dropdown a component
```
<ng-container *ngFor="let item of list">
    <nz-demo-dropdown-trigger></nz-demo-dropdown-trigger>
</ng-container>
```

**Comment by pomelo-ccc** [comment]
你好，这个闪烁问题我也遇到了，但我这边是先出现在左上角，然后再出现在正确的位置，排查发现是宿主dom移除但没有销毁导致的（内存泄漏），这甚至还导致了打开弹窗也没有打开，会出现在左上角然后整个页面都是蒙版，window resize后弹窗正常展示，版本是16.2

**Comment by yanyoo2000** [comment]
@pomelo-ccc 您好，我最近也遇到了相同的问题。使用*ngFor="let item of list"嵌套生成的dropdown，当list更新后，下拉菜单先出现在左上角再闪烁到鼠标点击的位置，window resize后正常。请问您有什么思路吗
