### ISSUE TITLE
nz-date-picker component, the date that is not disabled cannot be selected

### ISSUE THREAD

**Issue by ousc** [NG-ZORRO/ng-zorro-antd#8028]
### Reproduction link
[https://stackblitz.com/edit/angular-tqk9ij-hzyapk](https://stackblitz.com/edit/angular-tqk9ij-hzyapk)

### Steps to reproduce
![屏幕录制2023-07-21 16 34 57](https://github.com/NG-ZORRO/ng-zorro-antd/assets/31619017/938e837c-346b-45eb-bb59-9b2dc2067971)
2023-07-30 is not disabled, but cannot be selected

### What is expected?
2023-07-30 can be normally selected

### What is actually happening?
cannot be selected

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.1.0 |
| Browser | Chrome/FireFox/Safari |

**Comment by ousc** [comment]
Hello, I found the reason for this problem. 

When [nzShowTime]="false", the time (hour, minute and second) of selectedDate uses the current time, which makes the date comparison of the same day wrong, such as:

`July 30th` is selected, but the picker returns `July 30th at 3:50 PM`, new Date("2023-07-30") < selectedDate, but we actually want them to be the same day.

I don't know if it's a feature or a bug, if it's a bug I can submit a PR to fix it.

**Comment by Laffery** [comment]
Hi @ousc, I got `July 30th` selected normally in your reproduction link, please check again whether the problem is still existing and re-provide a new link.

![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/49607541/fc6a54dc-302d-449e-adac-58ae8b76112e)
