### ISSUE TITLE
Dropdown nzDisable is doesn't work

### ISSUE THREAD

**Issue by Elliottssu** [NG-ZORRO/ng-zorro-antd#803]
## Version

0.6.8

## Environment

angular 5.1.1

## Reproduction link

[http://plnkr.co/edit/YLQBy21c3IXOaxFEa4EZ?p=preview](http://plnkr.co/edit/YLQBy21c3IXOaxFEa4EZ?p=preview)

## Steps to reproduce

I put zorro dropdown in my angular project, and it doesn't work when i try to use `nzDisable` disable the drop-down list.

angular: V5.1.1
code:
```
<nz-dropdown [nzTrigger]="'click'">
  <a class="ant-dropdown-link" nz-dropdown>
    click me
    <i class="anticon anticon-down"></i>
  </a>
  <ul nz-menu>
    <li nz-menu-item>
      <a target="_blank" rel="noopener noreferrer" href="http://www.alipay.com/">1st menu item</a>
    </li>
    <li nz-menu-item>
      <a target="_blank" rel="noopener noreferrer" href="http://www.alipay.com/">2nd menu item</a>
    </li>
    <li nz-menu-divider></li>
    <li nz-menu-item nzDisable>3rd menu item（disabled）</li>
  </ul>
</nz-dropdown>
```

## What is expected?

![image.png](http://upload-images.jianshu.io/upload_images/3502567-72854da8cfba2933.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## What is actually happening?

![image.png](http://upload-images.jianshu.io/upload_images/3502567-a8d62bd3e98330b6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## Other?

I can't find information about `nzDisable` in the console, I'm not sure whether it's a  angular version problem.

**Comment by vthinkxie** [comment]
work fine in your reproduction link, and it works well in my computer too, please check your local version
