### ISSUE TITLE
NzDisabled attribute in select component and switch component doesn't change control status to disabled

### ISSUE THREAD

**Issue by mikaelboff** [NG-ZORRO/ng-zorro-antd#8041]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-ffet1c?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-ffet1c?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Click on the button that has the label "TOGGLE". 

### What is expected?
The form control status of select and switch should change to "DISABLED"

### What is actually happening?
The form control status of select and switch still remain "VALID" instead of changing to "DISABLED"

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.0.0 |
| Browser | Google Chrome |

---
I was using a custom directive to disable select and switch, then I realized I could use the attribute nzDisabled. I change my code to use it, but I've faced this problem where my forms got broken.

Custom directive code (that disables the form control when I change its value)
```
@Directive({ selector: '([formControlName], [formControl])[disableControl]' })
export class DisableControlDirective implements OnChanges {
  @Input() disableControl = false;

  ngOnChanges(changes: SimpleChanges) {
    if (changes.disableControl.currentValue) {
      this.ngControl.control?.disable();
    } else {
      this.ngControl.control?.enable();
    }
  }

  constructor(private ngControl: NgControl) {}
}
``` 

Example of usage:

```
<nz-select [formControl]="control" [disableControl]="condition">
...
</nz-select>
```
<br>

**Comment by Laffery** [comment]
Hello @mikaelboff.

In your reproduction code, you'd tried to use `nzDisabled`  to disable the form control. However,  this attribute is designed to disable the **data entry component** (nz-select, nz-switch, etc.),  **not the form control**. A truly effective way to disable the form control is use **FormControl#disable()** method, such as your custom directive `disableControl`.

I'd like to close this issue, feel free to reopen it if you hava any further questions. Enjoy coding :)
