### ISSUE TITLE
After using NzCustomColumn and fixed column configuration, nz-table style crashed

### ISSUE THREAD

**Issue by michael2043** [NG-ZORRO/ng-zorro-antd#8043]
### Reproduction link
[https://stackblitz.com/edit/angular-li5yrg-9obcpu?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-li5yrg-9obcpu?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
[nzScroll]="{ x: '2000px' }"
set name column to nzLeft
set all the column to fix width

### What is expected?
Fixed column displayed normally as not using NzCustomColumn

### What is actually happening?
nz-table scroll style crashed, if we nzscroll.x too large(2000px), lot of white space appeared, if we nzscroll.x too small(500px), column cannot be fixed displayed

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.1.0 |
| Browser | Chrome |

**Comment by jugrc** [comment]
Having the same at [](https://stackblitz.com/edit/angular-gw6ynf-dnd8tn?file=src%2Fapp%2Fapp.component.ts)

**nzScroll.x** is not working even without column fixed width (**y** is fine).

It was working well before version 16.0.

Hope that can help!

**Comment by OriginRing** [comment]
Please give tr supplemental styles for now to fix the style crash, we will fix it in the next version!
```
tr {
  width: 100%;
  display: flex;
  justify-content: space-between;
}
```
