### ISSUE TITLE
[nz-menu] 文本内容溢出的时候没有变成省略号

### ISSUE THREAD

**Issue by liulovegame** [NG-ZORRO/ng-zorro-antd#8051]
在使用导航菜单[nz-menu]的时候内容溢出了，看着像是设置了flex的盒模型顶掉了block。
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/11360743/d3b9e72b-789f-4dba-af88-d80f7386b3e1)

**Comment by Laffery** [comment]
I'd like to close this issue because the [v16.2.1](https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/16.2.1) which contains this bugfix had been released.
