### ISSUE TITLE
表单中tooltip在导入NzInputModule后报错

### ISSUE THREAD

**Issue by Liumangxing** [NG-ZORRO/ng-zorro-antd#8057]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-yt74xi?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-yt74xi?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
如链接中所示，导入NzInputModule后，鼠标移入input框不显示tooltip，鼠标移出input框时，控制台报错： ERROR TypeError: Cannot read properties of undefined (reading 'overlayRef')，不导入NzInputModule时是正常的

### What is expected?
鼠标移入input框显示tooltip，鼠标移出input框时，tooltip消失

### What is actually happening?
鼠标移入input框不显示tooltip，鼠标移出input框时，控制台报错： ERROR TypeError: Cannot read properties of undefined (reading 'overlayRef')

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.1.0 |
| Browser | Google Chrome版本 115.0.5790.110（正式版本） （64 位） |

**Comment by OriginRing** [comment]
```
<span nz-tooltip nzTooltipTitle="名字是张三">
        <input nz-input formControlName="name"/>
</span>
```
请更改为该写法
