### ISSUE TITLE
自定义主题颜色 Custom theme color

### ISSUE THREAD

**Issue by weimingxuan** [NG-ZORRO/ng-zorro-antd#806]
## What problem does this feature solve?
我们项目中的主题色和ngzorro的不一致，但是很喜欢这些精巧的组件库，很苦恼，如果可以自定义主题色可以解决我们项目中很多问题，感谢，希望采纳
（The theme color of our project is not the same as that of ngzorro, but we like these smart component libraries very much. It's very annoying. If we can customize the theme color, we can solve many problems in our project. Thanks, we hope to adopt it.）

## What does the proposed API look like?
希望可以在一个配置文件中添加一个主题颜色的字段
（You want to add a field with a topic color field in a configuration file）

**Comment by vthinkxie** [comment]
Hi @weimingxuan , we will support this feature in version 0.7.0, it will come few month later

**Comment by YoungWinter** [comment]
Does it use the same way as material?

**Comment by vthinkxie** [comment]
@YoungWinter will be same way as antd react version.

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed
