### ISSUE TITLE
Pagination Error: "Cannot read property 'nodeName' of null at HTMLDocument.onMouseClick"

### ISSUE THREAD

**Issue by jakechan2012** [NG-ZORRO/ng-zorro-antd#807]
## Version

0.6.8

## Steps to reproduce

click any page number  
reproduce on [https://ng.ant.design/#/components/pagination](https://ng.ant.design/#/components/pagination)

## What is expected?

no error

## What is actually happening?

**throw an error**  
content.js:140 Uncaught TypeError: Cannot read property 'nodeName' of null at HTMLDocument.onMouseClick

## Other?

```
<li class="ant-pagination-item ng-star-inserted" title="3">
  <a>3</a>
</li>
```

for example, the elements above, the `<a>` do not full fill the `<li>` (css).

when I click the edge of the `li` (do not click on the `<a>`), console thow the error, but page number changed correctly

**Comment by vthinkxie** [comment]
work fine, and there is not content.js in zorro's website. please check the extension of your browser.

**Comment by jakechan2012** [comment]
@vthinkxie thx, and sorry for this issue, the error was from thunder extension
