### ISSUE TITLE
Hide tooltip default when hover in nz-option

### ISSUE THREAD

**Issue by HuynhVuInnomize** [NG-ZORRO/ng-zorro-antd#8080]
## What problem does this feature solve?
Hide tooltip default when hover in nz-option

## What does the proposed API look like?
No

**Comment by HuynhVuInnomize** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/assets/140676148/55f4e67f-cc97-4111-9d4b-0097df3cb47e

**Comment by Laffery** [comment]
I had committed a pr #8097 that supports to customize by `nzTitle` property of nz-option-item

```html
<!-- hide tooltip -->
<nz-option-item nzLabel="Jack" [nzTitle]="null"></option-item>
<!-- or -->
<nz-option-item nzLabel="Jack" nzTitle=""></option-item>
<!-- or show specific content -->
<nz-option-item nzLabel="Jack" nzTitle="this is a title"></option-item>
```

**Comment by HuynhVuInnomize** [comment]
Thank you.

**Comment by Laffery** [comment]
I'd like close this issue because [v16.2.1](https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/16.2.1) which contains this feature had been released.

**Comment by HuynhVuInnomize** [comment]
ok. Thank you very much.
