### ISSUE TITLE
Scroll to bottom on "Load Data on Scroll" stops working if zoomed out

### ISSUE THREAD

**Issue by MatejZgela** [NG-ZORRO/ng-zorro-antd#8086]
### Reproduction link
[https://stackblitz.com/edit/angular-7uqnys?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-7uqnys?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. Open dropdown select 
2. Zoom out
3. Scroll to bottom

### What is expected?
Expected to load more items until all are loaded irrespective of zoom state

### What is actually happening?
Nothing is happening until zoomed in to the original state

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.2.0 |
| Browser | Chrome, Brave, Edge |

**Comment by pgarzina** [comment]
any update on this one?
