### ISSUE TITLE
弹窗中的表格无数据时，empty未居中显示

### ISSUE THREAD

**Issue by ifuyun** [NG-ZORRO/ng-zorro-antd#8089]
### Reproduction link
[https://stackblitz.com/edit/angular-acoktj](https://stackblitz.com/edit/angular-acoktj)

### Steps to reproduce
1. 定义一个modal；
2. 在modal中定义一个table，data为空；
3. 设置table的nzScroll属性为[nzScroll]="{ y: '400px' }"，即固定表头。

### What is expected?
empty居中显示

### What is actually happening?
empty居左显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.2.0 |
| Browser | Chrome |

---
另外，empty的宽度应该为行的宽度，而不是行宽度+2px。

**Comment by Laffery** [comment]
这是由于弹窗打开时存在动画（弹窗从小变大），empty 组件初始化的宽度比实际小，因此未居中显示。可在 nz-modal 上加上 `nzNoAnimation`，使 empty 组件宽度占满整个 table 组件，即居中显示。

**Comment by ifuyun** [comment]
> 这是由于弹窗打开时存在动画（弹窗从小变大），empty 组件初始化的宽度比实际小，因此未居中显示。可在 nz-modal 上加上 `nzNoAnimation`，使 empty 组件宽度占满整个 table 组件，即居中显示。

这种解决方式就会导致交互上的不统一，合适的解决方法是对modal增加动画完成的回调事件，在动画完成后更新视图。
