### ISSUE TITLE
NzDrawerService not working anymore with components whose inject not root services

### ISSUE THREAD

**Issue by sebcam** [NG-ZORRO/ng-zorro-antd#8100]
### Reproduction link
[https://stackblitz.com/edit/angular-qbjtey-8jnym6](https://stackblitz.com/edit/angular-qbjtey-8jnym6)

### Steps to reproduce
- Register a service In lazy loaded module
- Create a drawer with a component injecting the service

### What is expected?
Drawer should open, and child service should be injected

### What is actually happening?
Drawer is not opening with error :
NullInjectorError: No provider for ChildService!

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.2.0 |
| Browser | All |

---
This worked in v15
In v16, the `NzDrawerService` changed to be `'providedIn: 'root'`

**Comment by sebcam** [comment]
[Here ](https://github.com/NG-ZORRO/ng-zorro-antd/pull/8079) is the PR which introduces this issue

**Comment by Nicoss54** [comment]
> [Here ](https://github.com/NG-ZORRO/ng-zorro-antd/pull/8079) is the PR which introduces this issue

Hi as a workaroud you can inject your provider this way

`
{ path: '', providers: [ChildService], component: EditComponent }
`

and it will work as expected

**Comment by sebcam** [comment]
@Nicoss54 You talk about routing but the issue talk about drawer.
This wont fix the issue.

**Comment by Nicoss54** [comment]
> @Nicoss54 You talk about routing but the issue talk about drawer. This wont fix the issue.

Ohh sorry sorry, I was too fast in reproducing this issue! My bad !

**Comment by danvy** [comment]
Idem

**Comment by Nicoss54** [comment]
@hsuanxyz i will take this one ;). I will do a fix for today

**Comment by Nicoss54** [comment]
@sebcam @danvy the PR fixing this issue is done, happy coding :)
