### ISSUE TITLE
Deprecated tilde (~) import in css, breaks with esbuild

### ISSUE THREAD

**Issue by jornare** [NG-ZORRO/ng-zorro-antd#8106]
### Reproduction link
[https://ng-zorro-antd-ivy-yrpgmk.stackblitz.io](https://ng-zorro-antd-ivy-yrpgmk.stackblitz.io)

### Steps to reproduce
(This does not replicate in stackblitz as it is using a different builder)

Add "node_modules/ng-zorro-antd/ng-zorro-antd.min.css" to styles in angular.json, change to "builder": "@angular-devkit/build-angular:browser-esbuild".
Run build.

### What is expected?
A successful build

### What is actually happening?
Vite is throwing an error due to a deprecated import syntax

    X [ERROR] Could not resolve "~@angular/cdk/overlay-prebuilt.css"

    node_modules/ng-zorro-antd/ng-zorro-antd.min.css:1:8:
      1 │ @import '~@angular/cdk/overlay-prebuilt.css';.ant-carousel .slick-s...
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    You can mark the path "~@angular/cdk/overlay-prebuilt.css" as external to exclude it from the bundle, which will remove this error.

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.2.0 |
| Browser | NA |

---
Remove the tilde, and it is working perfectly. "~@angular/cdk/overlay-prebuilt.css" => "@angular/cdk/overlay-prebuilt.css"
This fix should be backwards compatible as it has been deprecated since Angular 13.

**Comment by lexeek** [comment]
I faced the same problem
