### ISSUE TITLE
编译到生产环境下拉框、日期选择等控件都不能下拉或选择了

### ISSUE THREAD

**Issue by hllinc** [NG-ZORRO/ng-zorro-antd#811]
编译到生产环境下拉框、日期选择等控件都不能下拉或选择了。
使用的angular版本为5.0.3，ng-zorro的版本为0.6.8

**Comment by vthinkxie** [comment]
please try to upgrade to latest version.

**Comment by hllinc** [comment]
Already upgrade to the latest version 0.6.8, but it still can't work.

**Comment by hllinc** [comment]
Already upgrade to the latest version 0.6.8, but it still can't work. @vthinkxie

**Comment by vthinkxie** [comment]
@hllinc please check your node_modules and dependencies,remove all node_modules and reinstall it.
it work fine in all our project.

**Comment by hllinc** [comment]
do like your said, but still not work.

**Comment by hllinc** [comment]
I did it like your words, but still not work. @vthinkxie

**Comment by vthinkxie** [comment]
try start a new project with angular cli with ng-zorro-antd?

**Comment by hllinc** [comment]
Now we have 4 project, all use the ng-zorro-antd, the other three is ok, only this project has that problem, all prop files are the same... I had delete all of the custom components to find out where the problem is, but still now, there is no a piece of light.

**Comment by vthinkxie** [comment]
@hllinc this problem has been confirmed, it seems some dependency have break changes, we are trying to figure it out.

**Comment by hllinc** [comment]
@vthinkxie Thank you very much! Please notice me when it works. Our projects are waiting for it.

**Comment by wilsoncook** [comment]
It seems due to `webpack` with `uglifyjs`, for resolve production building emergency, try use: 
```
ng build --aot=true --environment=prod --output-hashing=all --sourcemaps=false --extract-css=true --named-chunks=false --build-optimizer=true
```
instead of
```
ng build --prod
```
please!

**Comment by vthinkxie** [comment]
@hllinc you can make it work with @wilsoncook 's temp solution.

**Comment by hllinc** [comment]
yes, it works! thank you! @vthinkxie @wilsoncook 
and what only we can do is waiting for angular cli team fix it?

**Comment by vthinkxie** [comment]
you can also use your own build tools, we can do nothing about it

**Comment by hllinc** [comment]
My build tools is the ng commands as follows:
```javascript
ng build --prod --named-chunks --env=prod --base-href /cms-frontend/
```
I mean when can I use the original commands.

**Comment by vthinkxie** [comment]
@hllinc you can track the issue of angular-cli, they will fix the bug later.

**Comment by hllinc** [comment]
@vthinkxie Thank you!
