### ISSUE TITLE
ColorPicker引入项目后，不能正常启动

### ISSUE THREAD

**Issue by Seraphims** [NG-ZORRO/ng-zorro-antd#8115]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
- 引入插件，import { NzColorPickerModule } from 'ng-zorro-antd/color-picker';
- 启动项目
```sh
./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.NgAntdColorPickerModule to symbol
                                              ~~~~~~~~~~~~~~~~~~~~~~
Error: node_modules/ng-zorro-antd/color-picker/color-picker.module.d.ts:6:21 - error TS2307: Cannot find module 'ng-antd-color-picker' or its corresponding type declarations.
6 import * as i5 from "ng-antd-color-picker";
                      ~~~~~~~~~~~~~~~~~~~~~~
Error: node_modules/ng-zorro-antd/color-picker/typings.d.ts:5:23 - error TS2307: Cannot find module 'ng-antd-color-picker' or its corresponding type declarations.
5 import { Color } from 'ng-antd-color-picker';
                        ~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/routes/dashboard/customLayout/components/properties-panel/properties-panel.module.ts:5:35 - error TS2307: Cannot find module 'ngx-color-picker' or its corresponding type declarations.
5 import { ColorPickerModule } from 'ngx-color-picker';
                                    ~~~~~~~~~~~~~~~~~~
```

### What is expected?
引入依赖，项目正常启动

### What is actually happening?
引入依赖，项目启动失败

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.2.0 |
| Browser | chrome |

**Comment by OriginRing** [comment]
复现链接无效，麻烦重新发下，另外color-picker需要安装ng-antd-color-picker

**Comment by igorbremec** [comment]
I'm getting the same error when trying to import the ColorPicker into my app:

```
./projects/showcase/src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.NgAntdColorPickerModule to symbol

./projects/showcase/src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i5.NgAntdColorPickerModule to symbol

Error: node_modules/ng-zorro-antd/color-picker/color-picker.module.d.ts:6:21 - error TS2307: Cannot find module 'ng-antd-color-picker' or its corresponding type declarations.

6 import * as i5 from "ng-antd-color-picker";
                      ~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ng-zorro-antd/color-picker/typings.d.ts:5:23 - error TS2307: Cannot find module 'ng-antd-color-picker' or its corresponding type declarations.

5 import { Color } from 'ng-antd-color-picker';
```

**Comment by igorbremec** [comment]
I just realized that the build error above is the result of user error. After reading the color picker documentation a bit more carefully, I noticed this in the API section:

```
Install ng-antd-color-picker in your project first:

npm install ng-antd-color-picker
```

After installing the specified package, the app compiles. However, I feel this bit of information should be featured more prominently at the top of the page.

**Comment by Laffery** [comment]
> After installing the specified package, the app compiles. However, I feel this bit of information should be featured more prominently at the top of the page.

@OriginRing 对于这类需要额外安装包的组件，我们可以看下是否可以在官网组件文档最上方透出，目前是放在 API 这一 part 的

**Comment by sangnguyendev** [comment]
> I just realized that the build error above is the result of user error. After reading the color picker documentation a bit more carefully, I noticed this in the API section:
> 
> ```
> Install ng-antd-color-picker in your project first:
> 
> npm install ng-antd-color-picker
> ```
> 
> After installing the specified package, the app compiles. However, I feel this bit of information should be featured more prominently at the top of the page.

Help full
