### ISSUE TITLE
Make Compatible NG-Zorro with the new angular builder: build-angular:browser-esbuild

### ISSUE THREAD

**Issue by Nicoss54** [NG-ZORRO/ng-zorro-antd#8119]
## What problem does this feature solve?
This feature solve an issue when we try to use ng-zorro in a project that use the new angular builder: browser-esbuild

## What does the proposed API look like?
Support the new angular builder

**Comment by jornare** [comment]
Related: https://github.com/NG-ZORRO/ng-zorro-antd/issues/8106
