### ISSUE TITLE
编译到生产环境下拉框、日期选择等控件都不能下拉或选择了

### ISSUE THREAD

**Issue by hllinc** [NG-ZORRO/ng-zorro-antd#812]
## Version

0.6.6

## Environment

angular5

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd/issues/811](https://github.com/NG-ZORRO/ng-zorro-antd/issues/811)

## Steps to reproduce

编译到生产环境下拉框、日期选择等控件都不能下拉或选择了。
使用的angular版本为5.0.3，ng-zorro的版本为0.6.6

## What is expected?

功能正常，或报错。

## What is actually happening?

功能不正常，并且不报错。

**Comment by vthinkxie** [comment]
it is a bug of `angular-cli` caused by `uglify-es`
you can use https://github.com/NG-ZORRO/ng-zorro-antd/issues/816#issuecomment-353961173 as a temp solution.
more info here.
https://github.com/NG-ZORRO/ng-zorro-antd/issues/817#issuecomment-353962561
