### ISSUE TITLE
穿梭框不支持异步数据

### ISSUE THREAD

**Issue by Tommytwy** [NG-ZORRO/ng-zorro-antd#814]
## What problem does this feature solve?

穿梭框只支持同步数据不满足项目要求

## What does the proposed API look like?

穿梭框可以像表格一样支持异步数据

**Comment by cipchk** [comment]
请问具体的场景是怎么样的？

**Comment by cipchk** [comment]
[Demo](https://stackblitz.com/edit/ng-zorro-antd-issue-910?file=app/app.component.ts)，并无问题。

**Comment by cipchk** [comment]
长时间未处理，关闭此问题；若有更多细节请重新提交issues。
