### ISSUE TITLE
nz-table使用自定义列的时候，同时指定 nzScroll 

### ISSUE THREAD

**Issue by cl1998-cl** [NG-ZORRO/ng-zorro-antd#8148]
### Reproduction link
[https://stackblitz.com/edit/angular-m6szev?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-m6szev?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
nz-table使用自定义列的时候，同时指定 nzScroll  会导致body宽度不对

### What is expected?
自定义列和nzScroll，nzLeft  可以同时正常使用

### What is actually happening?
body不会正常展示

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.2.2 |
| Browser | chrome |

**Comment by OriginRing** [comment]
请参考 #8043 暂时解决该现象，我们会在后续修复它
