### ISSUE TITLE
Add support for application generated by @angular/cli.

### ISSUE THREAD

**Issue by qq253498229** [NG-ZORRO/ng-zorro-antd#8156]
## What problem does this feature solve?
I use the `@angular/cli` tool to execute `ng g application` to generate an application. After that, when I run `ng add ng-zorro-antd@17.0.0-beta.0`, the console throws an error:

Bootstrap call not found

It seems that applications without a `'src'` directory are currently not supported.

## What does the proposed API look like?
Select the project to be executed in the command-line interface prompts.

**Comment by Nicoss54** [comment]
This will be fix with the release of 17.0.0 of the library!

**Comment by Laffery** [comment]
This issues had been fixed in v17.0.1. Have a try with the latest version :)
