### ISSUE TITLE
Angular V 17 (angular.dev) Support

### ISSUE THREAD

**Issue by nashwit** [NG-ZORRO/ng-zorro-antd#8158]
## What problem does this feature solve?
Hi there, 

I appreciate the work you are doing with this library. 
At the moment upgrading to angular V17 will break NG-Zorro library

## What does the proposed API look like?
build angular application would successfully build

**Comment by JoaoPauloLousada** [comment]
There is an issue related to v17. The upgrade is in progress.
https://github.com/NG-ZORRO/ng-zorro-antd/issues/8142

**Comment by Nicoss54** [comment]
Closed because duplicated of https://github.com/NG-ZORRO/ng-zorro-antd/issues/8142
