### ISSUE TITLE
readme文件中最新支持的Angular版本与实际不符

### ISSUE THREAD

**Issue by caoxicheng** [NG-ZORRO/ng-zorro-antd#8164]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
github readme page

### What is expected?
截至11.17应该支持17

### What is actually happening?
^15.0.0

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.2.2 |
| Browser | any |

**Comment by kwongtn** [comment]
并不支持，支持工作在以下链接
https://github.com/NG-ZORRO/ng-zorro-antd/issues/8142

不过话说回来， ng-zorro-antd 16.2.2 应该写支持 angular 16 😅
