### ISSUE TITLE
TreeSelect 搜索框内输入中文会出现重叠现象，且无法高亮选中

### ISSUE THREAD

**Issue by Icedb** [NG-ZORRO/ng-zorro-antd#8165]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-nnbpkf?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-nnbpkf?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
在TreeSelect 搜索框内输入中文会出现重叠现象，且无法将符合的内容高亮选中，需要在中文后加个空格再删除空格才可以实现相应功能

### What is expected?
没有重叠现象，可以正常搜索

### What is actually happening?
文字重叠，无法正常搜索

| Environment | Info |
|---|---|
| ng-zorro-antd | 16.2.2 |
| Browser | Chrome 119.0.6045.124 |

---
只有chrome有此问题，只有中文有此问题，官方的16.2.2版本演示也有此问题

**Comment by EnochGao** [comment]
抱歉之前处理禁用节点能删除问题的时候，顺便优化了处于输入组合状态下搜索问题导致的，#8139 修了。这边如果你着急的话建议使用 v16.2.0。😖

**Comment by Icedb** [comment]
> 抱歉之前处理删除节点建议删除问题的时候，顺便优化了一个输入组合状态下搜索问题导致的，#8139修改了。草莓如果你着急的话使用v16.2.0。😖

好的好的，感谢

**Comment by EnochGao** [comment]
@xiaoke-1 这个已经修复了，只不过是在17.2.0+，如果你是在用17，那就安装17.2.0+，如果还要往前，需要16.x了

**Comment by xiaoke-1** [comment]
> [@xiaoke-1](https://github.com/xiaoke-1) 这个已经修复了，只不过是在17.2.0+，如果你是在用17，那就安装17.2.0+，如果还要往前，需要16.x了

16的最新版16.2.2还有这个问题

**Comment by EnochGao** [comment]
@xiaoke-1 使用16.2.0具体版本吧，当时合并的时候管理给合到17分支上去了

**Comment by xiaoke-1** [comment]
> [@xiaoke-1](https://github.com/xiaoke-1) 使用16.2.0具体版本吧，当时合并的时候管理给合到17分支上去了

好的,谢谢
