### ISSUE TITLE
表单什么的都不能用了（prod模式下）

### ISSUE THREAD

**Issue by kouzigege** [NG-ZORRO/ng-zorro-antd#817]
看了前几个人提问的问题，我大概明白了什么情况，也知道需要等待一下此问题的解决，但是我在此建议：

1、请在一个版本固定时，固定你们package.json中的版本号
2、请在一个版本固定时，固定你们package.json中的版本号
3、请在一个版本固定时，固定你们package.json中的版本号

**Comment by trotyl** [comment]
@kouzigege It's **NOT** related to any of our dependencies, not even peerDependencies. It's the problem of your own build tools.

Please make sure what the problem is before making comments.

**Comment by wilsoncook** [comment]
It confirmed due to `webpack` with `uglifyjs` with latest breaking changes, for resolve production building emergency, try use: 
```
ng build --aot=true --environment=prod --output-hashing=all --sourcemaps=false --extract-css=true --named-chunks=false --build-optimizer=true
```
instead of
```
ng build --prod
```
please!

**Comment by trotyl** [comment]
```javascript
new UglifyJSPlugin({
    sourceMap: buildOptions.sourcemaps,
    uglifyOptions: {
        ecma: wco.supportES2015 ? 6 : 5,
        warnings: buildOptions.verbose,
        ie8: false,
        // mangle: {
        //     safari10: true,
        // },
        mangle: false,
        compress: uglifyCompressOptions,
        output: {
            ascii_only: true,
            comments: false,
            webkit: true,
        },
    }
}),
```

Caused by `mangle` option of UglifyJS plugin, please wait for fix from 1) UglifyJS 2) Angular CLI. Or eject the config then disable it by yourself.

**Comment by vthinkxie** [comment]
related https://github.com/angular/angular-cli/issues/8997

**Comment by kouzigege** [comment]
能不能先解决问题，再说其他的.....  说了半天，答非所问，找不到焦点在哪？焦点都放到，我问题问的不ok上面了，行，在此深感抱歉.......  最后，请解决问题，多说无益，谢谢。

**Comment by trotyl** [comment]
你电脑死机我们怎么解决？已经说地清楚了和我们的内容以及我们的依赖都没有关系。

**Comment by kouzigege** [comment]
.....  谢谢您，总之解决了，免回，多说无益

**Comment by kouzigege** [comment]
对了，我上面说的问题，确实是我想表达的，也并非说明此问题是导致本次异常的....  我是在项目上线前，固定自己版本时，看到你们未固定版本，我这边每次是固定版本的，所有对于不固定版本的好处，了解并不深入，其实也是请教一下，如此做的好处是什么（真心请教），由此我也许会改变自己的方式

**Comment by vthinkxie** [comment]
@kouzigege the project is NOT a scaffold for angular, but a lib for angular, there is no reason for a lib to lock it's dependency, it will bring hundreds of conflict with other angular lib such as material design or ngx-bootstrap when you use them all in one project.

**Comment by kouzigege** [comment]
批评.....  我只是想尽快解决问题，在用你们的产品，何来批评，能出一个优秀的框架并被认可，获取到的更多的是赞赏和期待，我也希望你们能做的更好，更全面。然而用户遇到了问题，第一时间想到的是上来询问，这不是最好的赞赏吗.....   我觉得你们言辞挺犀利的，而且你们想走国际化路线，要承受的更多，不是吗？如果您认为这段还是在和您较真，那么我再次道歉：是我言辞不温柔了，抱歉。说了这么多，其实我最终问题还是得到解决了，也学习到了一些，thinks
