### ISSUE TITLE
ng-select nz-submenu 

### ISSUE THREAD

**Issue by huanz** [NG-ZORRO/ng-zorro-antd#818]
## Version

0.6.8

## Environment

node9.3.0 chrome63.0.3239.84 ng-zorro0.6.8

## Steps to reproduce

link：http://bukas.coding.me/zorro/dist/
code：https://coding.net/u/bukas/p/zorro/git

```bash
ng build --prod
```
select and submenu are not normal

## What is expected?

ng-select nz-submenu

## What is actually happening?

ng-select nz-submenu

**Comment by vthinkxie** [comment]
related #816 ,please wait for a moment.

**Comment by vthinkxie** [comment]
it is a bug of `angular-cli` caused by `uglify-es`
you can use https://github.com/NG-ZORRO/ng-zorro-antd/issues/816#issuecomment-353961173 as a temp solution.
more info here.
https://github.com/NG-ZORRO/ng-zorro-antd/issues/817#issuecomment-353962561

**Comment by vthinkxie** [comment]
related https://github.com/angular/angular-cli/issues/8997
