### ISSUE TITLE
WaterMark 水印组件在Safari上无法显示

### ISSUE THREAD

**Issue by ZENETOM** [NG-ZORRO/ng-zorro-antd#8187]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
无

### What is expected?
在Chrome上可以正常显示，在Safari上不行

### What is actually happening?
期望显示水印

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.0.1 |
| Browser | Safari 版本17.0 (19616.1.27.211.1) |

**Comment by ZENETOM** [comment]
<img width="1582" alt="截屏2023-11-27 10 18 08" src="https://github.com/NG-ZORRO/ng-zorro-antd/assets/57745254/ad9d0089-7122-4e2d-8352-217c17c5ad83">

**Comment by OriginRing** [comment]
请给 nz-water-mark 添加 diaplay: block 解决问题，我会在下个版本修复他
