### ISSUE TITLE
[公告 Announcement]: temp solution of `ng build --prod` 报错的临时解决方案

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#819]
Hi all 

The upgrade of `uglify-es` caused some bugs in `angular-cli` when using `ng build --prod` commond.

You can solve it using the following methods before `angular-cli` fix it.

### recommended
use 
```bash
ng build --aot=true --environment=prod --output-hashing=all --sourcemaps=false --extract-css=true --named-chunks=false --build-optimizer=true
```
instead of `ng build --prod`

### hack way

find `\node_modules\@angular\cli\models\webpack-configs\production.js` and comments the following lines, and set `mangle` to `false`

```js
// mangle: {
//     safari10: true,
// },
mange:false
```

You can track this issue https://github.com/angular/angular-cli/issues/8997 to get more infomation.

**Comment by icepoint0** [comment]
do not add <pre> --aot</pre> will fix this bug; i don't  know why,but it really worked

**Comment by cipchk** [comment]
[1.6.3](https://github.com/angular/angular-cli/releases/tag/v1.6.3) has fixed!
