### ISSUE TITLE
Custom tooltip color doesn't affect arrow color

### ISSUE THREAD

**Issue by alexmao1024** [NG-ZORRO/ng-zorro-antd#8190]
### Reproduction link
[https://stackblitz.com/edit/angular-71ldqp?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-71ldqp?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
The "minimal reproduction" link refers to the examples on your official website. The four buttons below allow for customizing the tooltip colors. When you hover over them, you can see the tooltip display, along with the black arrow beneath the tooltip.

### What is expected?
Expect the arrow color to be consistent with other customized colors, changing accordingly with the customized color.

### What is actually happening?
The arrow color seems to remain the default black and does not respond to the customization of colors.

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.0.1 |
| Browser | Chrome |

---

I attempted to use CSS to modify the arrow style, but the tooltip is created in the outermost div, making it impossible for me to change the arrow color within a single component. The changes I make seem to affect the entire global scope. Additionally, I examined ant-design 5.0, and it has successfully implemented the customization of tooltip colors, which leaves me puzzled as to why this functionality is not implemented in ng-zero.
I've checked the "chenc041:fix-issue-7639" branch, which indicates that the issue has been fixed. However, I am currently using the latest version of ng-zero, and the problem still persists. Moreover, the example is present in the official documentation, and the issue continues to exist.

**Comment by ParsaArvanehPA** [comment]
I would like to work on this issue, if you agree, please assign it to me.

**Comment by alexmao1024** [comment]
> I would like to work on this issue, if you agree, please assign it to me.

Thank you for offering to help! I don't have the ability to assign issues. Hopefully, someone with the necessary permissions can assign this issue to you.

**Comment by ParsaArvanehPA** [comment]
I hope this message finds you well. 
Changes have been merged.
You should be able to see the requested change in the next release.
@alexmao1024
