### ISSUE TITLE
Angular 17 import error

### ISSUE THREAD

**Issue by MarcosPaulo775** [NG-ZORRO/ng-zorro-antd#8199]
### Reproduction link
[https://github.com/MarcosPaulo775/ng-zorro-angular-17-error](https://github.com/MarcosPaulo775/ng-zorro-angular-17-error)

### Steps to reproduce
ng new name-project

ng add ng-zorro-antd

ng serve

### What is expected?
No errors occur during the execution of the project as nothing was changed after installation

### What is actually happening?
An import error is occurring within the package

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.0.1 |
| Browser | Chrome |

---
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/32870576/0150c540-8869-4002-a2fe-05cc22fcc9cb)

**Comment by Laffery** [comment]
These are just warnings, not errors, and do not affect normal usage.
This is a known issue, we'll fix this issue later.

**Comment by qyjs** [comment]
> These are just warnings, not errors, and do not affect normal usage. This is a known issue, we'll fix this issue later.

Has this been repaired。 @Laffery

**Comment by MarcosPaulo775** [comment]
What version will it come in?

@Laffery

**Comment by Laffery** [comment]
> What version will it come in?
> 
> 
> 
> @Laffery 

v18, is coming next week:)
