### ISSUE TITLE
能尽快将angular的功能与react的同步一下么，比如uploader的功能都没有呢

### ISSUE THREAD

**Issue by aresa7796** [NG-ZORRO/ng-zorro-antd#820]
## What problem does this feature solve?

可以更全面的使用NG ZORRO

## What does the proposed API look like?

angular的版本相比react的版本要少了很多功能，能同步一下么

**Comment by HsuanXyz** [comment]
Hi, this work in progress, you can follow [this](https://github.com/NG-ZORRO/ng-zorro-antd/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22ant+design+3.0%22+label%3Atype%3Afeature+).
