### ISSUE TITLE
ng-tag ie浏览器不点击X会出现抖动情况

### ISSUE THREAD

**Issue by liganggang** [NG-ZORRO/ng-zorro-antd#821]

**Comment by liganggang** [comment]
bug！

**Comment by liganggang** [comment]
点击nz-tag 除x外

**Comment by vthinkxie** [comment]
Hello @liganggang , your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper]( http://ng.ant.design/issue-helper/#/new-issue ) to create an issue, thank you!
