### ISSUE TITLE
dropdown 下拉组件在angular-5.1.2 版本中异常

### ISSUE THREAD

**Issue by icepoint0** [NG-ZORRO/ng-zorro-antd#822]
## Version

0.6.8

## Environment

angular ^5.1.2, ng-zorro 0.6.x

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

## Steps to reproduce

下载官方源码
安装库
将npm start 加入 --prod
启动doc 文档发现dropdown出现该问题

## What is expected?

dropdown中overlay的内容不消失

## What is actually happening?

dropdown中overlay的内容消失

**Comment by icepoint0** [comment]
请问下是什么问题

**Comment by icepoint0** [comment]
Your global Angular CLI version (1.6.2) is greater than your local
version (1.6.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.1
Node: 7.7.3
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

**Comment by icepoint0** [comment]
`Your global Angular CLI version (1.6.2) is greater than your local
version (1.6.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.1
Node: 7.7.3
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0`

**Comment by icepoint0** [comment]
> Your global Angular CLI version (1.6.2) is greater than your local
version (1.6.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.1
Node: 7.7.3
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

**Comment by icepoint0** [comment]
<pre>Your global Angular CLI version (1.6.2) is greater than your local
version (1.6.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.1
Node: 7.7.3
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0</pre>

**Comment by icepoint0** [comment]
我刚才解决了。用npm clean 掉淘宝registry安装的缓存之后。重新使用npm 安装。然后就可以了。不知道taobao的源啥时候才能稳定。

**Comment by icepoint0** [comment]
还是不对。也不是taobao源的问题

**Comment by HsuanXyz** [comment]
@icepoint0 Hi，请尽可能的按照 [《如何向开源社区提问题》](https://github.com/seajs/seajs/issues/545) 提交您的问题，这里的每一条评论都会有 138 人收到邮件提醒！谢谢 : )

**Comment by icepoint0** [comment]
需要用npm的源 ，并且 cli不能 加上--aot 打包，官方文档说的是--prod 已经有aot选项 我理解是加不加都不会影响最终打包的，但是实际情况是加上了--aot 确实还是有bug

**Comment by icepoint0** [comment]
@HsuanXyz 好的 我是按照表单提交的。但是问题比较难以描述清楚。也无法在其他环境复现。所以没有提供Reproduction link。目前我已经解决了

**Comment by vthinkxie** [comment]
@icepoint0 read the announcement please https://github.com/NG-ZORRO/ng-zorro-antd/issues/819

**Comment by LinBoLen** [comment]
138+me
