### ISSUE TITLE
with pnpm & angular v17, the @ant-design/icons-angular/icons cannot be found

### ISSUE THREAD

**Issue by Alfxjx** [NG-ZORRO/ng-zorro-antd#8238]
### Reproduction link
[https://github.com/Alfxjx/ng-17-zorro-icon-test-pnpm](https://github.com/Alfxjx/ng-17-zorro-icon-test-pnpm)

### Steps to reproduce
1.  ng new ng-17-zorro-icon-test-pnpm --package-manager=pnpm
2.  ng add ng-zorro-antd

and ng serve to start, which shows error: 

### What is expected?
a module not found error

### What is actually happening?

[ERROR] TS2307: Cannot find module '@ant-design/icons-angular/icons' or its corresponding type declarations. [plugin angular-compiler]

    src/app/icons-provider.ts:7:7:
      7 │ } from '@ant-design/icons-angular/icons';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.0.1 |
| Browser | MSEdge |

---
maybe it's the pnpm's strategy for node_modules. install the @ant-design/icons-angular package and the icon can be seen properly

**Comment by Alfxjx** [comment]
maybe in the ng add schematics, we need install @ant-design/icons-angular and other related packages explicitly

**Comment by Alfxjx** [comment]
Thank you for your reply!
IMO, the package is the dependency of ng-zorro-antd,     

```
"@ant-design/icons-angular": "^17.0.0",
```
adding `shamefully-hoist=true` in `.npmrc` works which is not elegant.

I think it's a shadow dependency issue, since now angular can use pnpm as package manager, ng-zorro should make pnpm compatible.

**Comment by OriginRing** [comment]
> Not everyone wants to use @ant-design/icons-angular; some people prefer custom icons. Therefore, it is not advisable to explicitly install related packages. How about providing an option in `ng add` to choose whether to use @ant-design/icons-angular? If selected, we will install the package. But what about code-editor, cron-expression....? Should we provide options for all of these modules? What do you think? @Nicoss54 @OriginRing

I agree with adding the option to install @ant-design/icons-angula to ng add, but I don’t agree with adding libraries that components depend on. They are not universal components and have not many users.

**Comment by Alfxjx** [comment]
seems no more problems
