### ISSUE TITLE
Update snippet code documentation with the new code flow

### ISSUE THREAD

**Issue by Nicoss54** [NG-ZORRO/ng-zorro-antd#8261]
## What problem does this feature solve?
Currently all the snippet code use the older code flow of Angular using ngIf ngFor and ngSwitchDirective

It will be great if the snippet use the new code flow of Angular

## What does the proposed API look like?
Replace ngIf ngFor and ngSwitch by the respect @-syntax code flow

**Comment by Nicoss54** [comment]
@OriginRing @HyperLife1119 @simplejason are you agree with that ? It it's ok i will begin the work :)

**Comment by HyperLife1119** [comment]
I agree with this suggestion!

**Comment by Nicoss54** [comment]
> I agree with this suggestion!

I take the point so :)

**Comment by Nicoss54** [comment]
> I agree with this suggestion!

I take the point

**Comment by Nicoss54** [comment]
> > > Just out of curiosity, won't it have any effect on maintaining older version? Does ng-zorro even continue to support it's older versions?
> > 
> > 
> > I don’t totally understand, with this issue I will update the documentation snippet with the new code flow, also i will migrate components on the new code flow.
> > This will impact the version 17 of ng-zorro. Previous version will not be impacted.
> > I don’t know If I answer to your curiosity correctly :)
> 
> Sorry I was a bit vague, let me explain what I meant in my previous message: Imagine this scenario that ng-zorro supports it's 3 latest versions, that means that currently version number 17 and 16 and 15 needs to be maintained. Normally when a bug is fixed in version 17, it is cherry-picked via git to branches /16.x and /15.x.
> 
> Now my question is that whatever ng zorro supports several versions or just it's latest version. Because if it supports several versions, maybe it's not a good idea to move to new code flow now, because it will make automatic cherry-pick not possible, and whenever a bug is fixed it should be manually cherry-picked which can be very time consuming.

Normally we support only the current version, if @OriginRing can confirm this it will be great. But This issue is just an update doc issue, I will just ypdate the snippet code of component documentation not the component business logic

**Comment by Nicoss54** [comment]
> More about the ng-zorro support, as mentioned [here](https://github.com/NG-ZORRO/ng-zorro-antd/pull/8279#issuecomment-1840196555) a lot of future changes may depend on knowing the answer to as how many prior released versions should be maintained.
> 
> If we want to follow Angular on LTS support, we should support the releases made in the last 18 months: [Angular LTS support](https://angular.io/guide/releases#actively-supported-versions) For [environment support](https://github.com/NG-ZORRO/ng-zorro-antd#-environment-support) we currently follow [their policy](https://angular.io/guide/browser-support)

If i'm not wrong we don't support the previous version of Ng-Zorro but i'm not sure about that. If @OriginRing or @simplejason can confirm or not this supposition it will be great.

**Comment by ParsaArvanehPA** [comment]
Would you mind if I join you on these tasks? @Nicoss54

**Comment by Nicoss54** [comment]
> Would you mind if I join you on these tasks? @Nicoss54

@ParsaArvanehPA its should be nice to work together on this, unfortunately it will be complicated, and it will be a high risk of doing the same work or have conflicts :/

**Comment by Laffery** [comment]
As I can see, this work had been done, and I'd like to close this issue. Thank you everyone for this fantacy work!
