### ISSUE TITLE
The 0.6.8 version of nz-select will appear the default placeholder, and the nz-select is not available after the ng build --prod

### ISSUE THREAD

**Issue by quanjialiang** [NG-ZORRO/ng-zorro-antd#828]
The 0.6.8 version of nz-select will appear the default placeholder, and the nz-select is not available after the ng build --prod

**Comment by vthinkxie** [comment]
@quanjialiang please read the announcement in the issue https://github.com/NG-ZORRO/ng-zorro-antd/issues/819
it is a bug caused by the latest version of uglify-es
