### ISSUE TITLE
你好，请问一下我想要在carousel里面显示 prev和next 按钮，在我的代码里要怎么写？谢谢！

### ISSUE THREAD

**Issue by EmmanuelAgui** [NG-ZORRO/ng-zorro-antd#829]

**Comment by vthinkxie** [comment]
Hello @EmmanuelAgui , your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper]( http://ng.ant.design/issue-helper/#/new-issue ) to create an issue, thank you!
