### ISSUE TITLE
Tabs标签页显示问题

### ISSUE THREAD

**Issue by kurimuson** [NG-ZORRO/ng-zorro-antd#8351]
### Reproduction link
[https://angular-agvz7u.stackblitz.io](https://angular-agvz7u.stackblitz.io)

### Steps to reproduce
页面宽度偏小，同时tab标签数量很多的时候，tab标签右侧用来表示更多标签的的“三个点按钮”不显示（即nz-tab-nav-operation不显示，在控制台中可以看到该按钮会随着组件宽度减小而逐渐跑至dom外）

### What is expected?
nz-tab-nav-operation该按钮固定在右侧正常显示

### What is actually happening?
nz-tab-nav-operation该按钮在某些情况下不显示

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.1.0 |
| Browser | 最新版本的chrome与edge |

---
在官方文档中就可以复现：在Tabs标签页这块，“可以左右、上下滑动，容纳更多标签”这个示例，将页面宽度缩小，可以看到该示例中，tab标签右侧的“三个点按钮”会逐渐消失

**Comment by ParsaArvanehPA** [comment]
Hi @kurimuson 
Thank you for reporting this issue;
If it's alright by everyone, I can start working on this issue.
