### ISSUE TITLE
nz-table missing `tbody` in virtual scroll mode

### ISSUE THREAD

**Issue by tigrisg** [NG-ZORRO/ng-zorro-antd#8352]
### Reproduction link
[https://stackblitz.com/edit/angular-hjnvxw](https://stackblitz.com/edit/angular-hjnvxw)

### Steps to reproduce
Go to the stackblitz demo and the style is missing for `tbody`

### What is expected?
The table is supposed to have `<tbody class="ant-table-tbdoy">`

### What is actually happening?
The table is missing `class="ant-table-tbody"` in the `tbody` in HTML and is missing `tbody` altogether in angular

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.1.0 |
| Browser | Chrome 120.0.6099.199 |

---
The problem does not exist in version 17.0.0

**Comment by ParsaArvanehPA** [comment]
Hi @tigrisg 
Thank you for submitting this issue;
If it's ok by everyone, i will start working on a solution for this bug.

**Comment by ParsaArvanehPA** [comment]
Hello again @tigrisg @jimmytheneutrino 
With PR #8328 by @behdi this bug is fixed.
