### ISSUE TITLE
angular13构建的项目在谷歌低版本目前测试78和81的版本 运行时候nz-select组件 获取焦点的时候 光标在输入框中间没有考最左边

### ISSUE THREAD

**Issue by DavisGYF** [NG-ZORRO/ng-zorro-antd#8354]
### Reproduction link
[https://github.com/DavisGYF/main-angular13](https://github.com/DavisGYF/main-angular13)

### Steps to reproduce
是nz-select下拉选项获取焦点
angular13构建的项目在谷歌低版本目前测试78和81的版本 运行时候nz-select组件 获取焦点的时候 光标在输入框中间没有考最左边

### What is expected?
光标能够靠最左边儿

### What is actually happening?
光标居中

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.3.0 |
| Browser | 谷歌低版本78和81 |

**Comment by ParsaArvanehPA** [comment]
Hi @DavisGYF,
Thank you for reporting this issue;
The thing is Ng-zorro has a policy that only the last version of ng-zorro will be maintained.
I have not been able to reproduce this bug in the latest version of ng-zorro with the supported version of browsers, If I have done this wrong and the problem still exists, please notify me and I will start working on it.
