### ISSUE TITLE
The pagination of the table is fixed at the bottom

### ISSUE THREAD

**Issue by willowlau** [NG-ZORRO/ng-zorro-antd#8375]
## What problem does this feature solve?
It is hoped that the pagination of the table can be fixed at the bottom and the height of the ant-table can occupy the space of the page.
希望表格的分页可以固定在底部，ant-table的高度可以占满页面的空间。

You can refer to EasyUI's Table to automatically calculate the height.
可以参考EasyUI的Table自动计算高度。

Reference address: https://demo.topjui.com/html/grid/datagrid.html
参考地址: https://demo.topjui.com/html/grid/datagrid.html

## What does the proposed API look like?
<nz-table [nzPaginationFixedToFooter]="true" >

**Comment by ParsaArvanehPA** [comment]
Hi @willowlau 
We appreciate your interest in this behavior for the table component. However, this behavior is not available in Ant Design's table, so we are not able to add it to Ng-zorro's table, as we are an implementation that follows the original design. You can still achieve this behavior with css styling, without using the referenced api. If you want to use this behavior consistently in your project, you may consider creating a wrapper component for it.
