### ISSUE TITLE
v17.2.0 官方文档错误

### ISSUE THREAD

**Issue by Laffery** [NG-ZORRO/ng-zorro-antd#8381]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
打开官网 https://ng.ant.design/

1. https://ng.ant.design/components/form/zh#api
<img width="1183" alt="image" src="https://github.com/NG-ZORRO/ng-zorro-antd/assets/49607541/9ec10fda-acc2-4759-ae97-1534ab80a55d">

2. https://ng.ant.design/components/progress/zh#api
<img width="1157" alt="image" src="https://github.com/NG-ZORRO/ng-zorro-antd/assets/49607541/2cb5fd60-70b7-40c3-983e-cf628cd1c010">

3. https://ng.ant.design/experimental/code-editor/zh#api
<img width="1109" alt="image" src="https://github.com/NG-ZORRO/ng-zorro-antd/assets/49607541/84169e53-021f-4a80-ab7b-a013c9a6771e">

### What is expected?
文档正确

### What is actually happening?
文档错误

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.2.0 |
| Browser | Chrome |

**Comment by EnochGao** [comment]
稍等我都排查下文档
