### ISSUE TITLE
Issue with nz-tab not having default pointer to cursor 

### ISSUE THREAD

**Issue by amassoudi-wiremind** [NG-ZORRO/ng-zorro-antd#8385]
### Reproduction link
[https://stackblitz.com/edit/angular-xzinrf-bdhkxp?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-xzinrf-bdhkxp?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Just create an angular page with a template containing <nz-tabset> with a list of <nz-tab...> items

Example

```
import { Component } from '@angular/core';

@Component({
  selector: 'nz-demo-tabs-basic',
  template: `
    <nz-tabset>
      <nz-tab nzTitle="Tab 1">Content of Tab Pane 1</nz-tab>
      <nz-tab nzTitle="Tab 2">Content of Tab Pane 2</nz-tab>
      <nz-tab nzTitle="Tab 3">Content of Tab Pane 3</nz-tab>
    </nz-tabset>
  `
})
export class NzDemoTabsBasicComponent {}
```

You can notice that when hoovering the tabs, the cursor is not a pointer

### What is expected?
The expected behavious is to have a pointer style cursor when hovering the tabs

### What is actually happening?
The cursor takes pointer shape only at the broder of the tabs

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.2.0 |
| Browser | chrome |

**Comment by ParsaArvanehPA** [comment]
I Hope this message finds you well @amassoudi-wiremind 

Thank you for reporting this issue; this PR #8386 will address it.

**Comment by F-JJTH** [comment]
Hi, looks like it's fixed, can we close this issue ?

**Comment by Laffery** [comment]
close via #8386
