### ISSUE TITLE
 DatePicker will throw an error  when used with nzFormat="b"

### ISSUE THREAD

**Issue by Sophia-yolo** [NG-ZORRO/ng-zorro-antd#8387]
### Reproduction link
[https://stackblitz.com/edit/angular-gphznd?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-gphznd?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. Setting nzFormat to "b".
2. Select a date.

### What is expected?
Can correctly convert the date format.

### What is actually happening?
ERROR
Error: Missing extra locale data for the locale "en". Use "registerLocaleData" to load new data. See the "I18n guide" on angular.io to know more.

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.2.0 |
| Browser | Chrome 120.0.6099.216 |

**Comment by ParsaArvanehPA** [comment]
Greeting @Sophia-yolo 

What is the expected outcome when you assign the value 'b' to the `nzFormat` property?

**Comment by Sophia-yolo** [comment]
@ParsaArvanehPA 
Hello, what I want to achieve is that the date picker outputs properly for any character format, but when I format the input b, I find that the date picker does not output properly, it should output "mid." according to the DatePipe syntax or output the character b.

**Comment by ParsaArvanehPA** [comment]
@Sophia-yolo 
Did get a workaround for your problem? 
I am asking because you closed it; i was just checking the code...
