### ISSUE TITLE
tree组件应该加一个可选属性，让树节点的点击事件与checkbox的change事件关联起来

### ISSUE THREAD

**Issue by Easyzhou** [NG-ZORRO/ng-zorro-antd#8391]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
点击树组件的节点，无法同步选中该节点的checkbox组件

### What is expected?
点击树节点的同时选中该组件的checkbox控件，应该加一个可选的属性用来关联此操作，不然无法满足用户，便捷操作checkbox选中的需求

### What is actually happening?
点击树组件的节点，无法同步选中该节点的checkbox组件

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.2.2 |
| Browser | 所有浏览器 |

**Comment by EnochGao** [comment]
你这复现链接有问题

**Comment by ParsaArvanehPA** [comment]
I hope this message finds you well @vthinkxie 

A node can have two different states: `selected` and `checked`. However, not every selected node should be checked, so the checkbox should remain unchecked. This is consistent with the behavior of [Ant design's Tree component](https://ant.design/components/tree?), which we are using as a reference. I agree that it would be convenient to have the option to check the node's checkbox by clicking on the node, but unfortunately, we cannot implement a feature that is not supported by the original source.
