### ISSUE TITLE
ng-select when [compareWidth]='compareFn' err

### ISSUE THREAD

**Issue by adongroom** [NG-ZORRO/ng-zorro-antd#840]
## Version

0.6.8

## Environment

mac pro . chrome . 0.6.8

## Reproduction link

[https://github.com/adongroom/antselect](https://github.com/adongroom/antselect)

## Steps to reproduce

<nz-select [compareWidth]="compareFn" style="width: 140px" [(ngModel)]="item.Sex" name="Sex" required> <nz-option *ngFor="let opt of Sexs" [nzLabel]="opt.ItemName" [nzValue]="opt"> </nz-option> </nz-select>

compareFn(val1,val2){
    if(val1.ItemCode==val2.ItemCode){
      return true
    }else{
      return false;
    }

  }

## What is expected?

compareWidth 可以使用

## What is actually happening?

Error: Template parse errors:
Can't bind to 'compareWidth' since it isn't a known property of 'nz-select'.

If 'nz-select' is an Angular component and it has 'compareWidth' input, then verify that it is part of this module.
If 'nz-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

<div nz-form-control nz-col [nzSpan]="8">
<nz-select [ERROR ->][compareWidth]="compareFn" style="width: 140px" [(ngModel)]="item.Sex" name="Sex" required>
"): ng:///StaffModule/StaffEditComponent.html@38:21
Error: Template parse errors:
Can't bind to 'compareWidth' since it isn't a known property of 'nz-select'.
If 'nz-select' is an Angular component and it has 'compareWidth' input, then verify that it is part of this module.
If 'nz-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

<div nz-form-control nz-col [nzSpan]="8">
<nz-select [ERROR ->][compareWidth]="compareFn" style="width: 140px" [(ngModel)]="item.Sex" name="Sex" required>
"): ng:///StaffModule/StaffEditComponent.html@38:21
at syntaxError (webpack-internal:///../../../compiler/esm5/compiler.js:706)
at TemplateParser.parse (webpack-internal:///../../../compiler/esm``

**Comment by vthinkxie** [comment]
ref https://github.com/angular/material2/commit/054ea4d1ef63b9a3dd370ba019b1498d4aa0082c

**Comment by vthinkxie** [comment]
fixed in version 0.7.0
