### ISSUE TITLE
创建空白项目报错，未创建theme.less文件

### ISSUE THREAD

**Issue by HCenggel** [NG-ZORRO/ng-zorro-antd#8409]
### Steps to reproduce
ng new ngTest01 --routing --style=scss
Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? No

ng add ng-zorro-antd
? Enable icon dynamic loading [ Detail: https://ng.ant.design/components/icon/en ] Yes
? Set up custom theme file [ Detail: https://ng.ant.design/docs/customize-theme/en ] Yes
? Choose your locale code: zh_CN
? Choose template to create project: sidemenu

报错信息：Cannot find module 'E:\ngTest01\node_modules\@schematics\angular\private\components.js'

### What is expected?
创建theme.less文件，并在里面引入相应的less文件
app.config.ts文件缺少provideAnimations()

### What is actually happening?
theme.less缺少
app.config.ts文件缺少provideAnimations()

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.2.0 |
| Browser | Chrome  |

---
无

**Comment by HyperLife1119** [comment]
Fixed via #8410

**Comment by HCenggel** [comment]
> Fixed via #8410 通过 #8410 修复

LGTM
