### ISSUE TITLE
No pipe found with name 'nzHighlight' 

### ISSUE THREAD

**Issue by ccc920** [NG-ZORRO/ng-zorro-antd#8421]
### Reproduction link
[https://stackblitz.com/edit/angular-p9bsci?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-p9bsci?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Tree View  Searchable Tree, official example

### What is expected?
Successfully executed

### What is actually happening?
Bugs appear: No pipe found with name 'nzHighlight' 

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.2.0 |
| Browser | Chrome |

**Comment by ParsaArvanehPA** [comment]
Hi @ccc920,
Have you tried importing `NzHighlightModule`?
```ts
import { NzHighlightModule } from 'ng-zorro-antd/core/highlight';
```

**Comment by ccc920** [comment]
> 你好@ccc920， 你尝试过导入吗`NzHighlightModule`？
> 
> ```ts
> import { NzHighlightModule } from 'ng-zorro-antd/core/highlight';
> ```
Thank you, I am looking for this import path.
