### ISSUE TITLE
CSP not supported with nz-range-picker - it still has a div that has inline styles 

### ISSUE THREAD

**Issue by sarudiana18** [NG-ZORRO/ng-zorro-antd#8425]
## What problem does this feature solve?
<nz-range-picker nzFormat="MM/dd/yyyy" nz-row [(ngModel)]="dateRange" [nzFormat]="dateFormat"
      (ngModelChange)="dateData(dateRange)" class="flex-no-wrap"></nz-range-picker>

when I am looking with inspect on the app, i can see that nz-range-picker has this div: div class="ng-tns-c802749266-2 ant-picker-active-bar ng-star-inserted" ng-reflect-ng-style="[object Object]" style="position: absolute; width: 96px; left: 0px;"

which is causing the following error 

platform-browser.mjs:590 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'nonce-NONCE_PLACEHOLDER'". Either the 'unsafe-inline' keyword, a hash ('sha256-T6AAKdWxO6p6GZVyzGAJDSLhOoPuuoZ6LlqMX153CvM='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

## What does the proposed API look like?
remove inline styles

**Comment by ParsaArvanehPA** [comment]
Greetings @sarudiana18 ,
Could you please provide a testable sample for your problem?
I can not generate the same error when using `nz-range-picker`.

**Comment by sarudiana18** [comment]
@ParsaArvanehPA please see the code below https://github.com/sarudiana18/sample-csp-handling. Also here you can see the inline style from nz-range-picker
<img width="1114" alt="Screenshot 2024-04-07 at 20 10 33" src="https://github.com/NG-ZORRO/ng-zorro-antd/assets/105063916/e7d1fe3a-5c69-489e-a111-0393f5538048">

**Comment by sarudiana18** [comment]
@ParsaArvanehPA any updates on this?

**Comment by sarudiana18** [comment]
@ParsaArvanehPA i think the issue comes from this part of the code: 
https://github.com/ParsaArvanehPA/ng-zorro-antd/blob/7235666c86fdc37c86e09ae2de9bff53bab17c52/components/date-picker/date-picker.component.ts#L415C4-L429C1

**Comment by arturovt** [comment]
@sarudiana18 the provided fix works. I checked it in your repo. There are still inline styles, but they're set through the `ngStyle` directive, which applies styles securely using `element.style[property] = ...`, rather than `element.setAttribute('style', ...)`.
