### ISSUE TITLE
Suggestion: nz-select&nz-option add output when click one option.

### ISSUE THREAD

**Issue by Aralhi** [NG-ZORRO/ng-zorro-antd#844]
# What problem does this feature solve?
I think it's very necessary to solve this three or more condition such as.

1. I wish doSomething about business after click one option.
2. I wish update another select option which is associated with the option i click.
3. I wish set option.a, option.b, option.c to other variates after click one option.

# What does the proposed API look like?
`output: any | optional parameters, emit when click one option  | function | none
`

I wish add an output for nz-option, and the param is the option object i click.
```
<nz-select style="width: 120px;" [(ngModel)]="selectedOption" [nzPlaceHolder]="'choose option'" nzAllowClear>
      <nz-option
        *ngFor="let option of options"
        [nzLabel]="option.label"
        [nzValue]="option"
        (output)="doSomething(option)">
      </nz-option>
    </nz-select>
```

**Comment by yy7054wyq5** [comment]
@Aralhi 
可以用自定义content。在上面使用click事件，间接的搞事情。不过可能会出现冒泡的问题（导致多触发一次的ngModelChange），但若是阻止了冒泡，点击了option，则不会自动关闭option的下拉框了。
其实还是蛮希望官方如你所提支持类似的功能。
