### ISSUE TITLE
Borderless tag with status(eg: warning)

### ISSUE THREAD

**Issue by dibfibo** [NG-ZORRO/ng-zorro-antd#8492]
### Reproduction link
[https://stackblitz.com/edit/angular-irj1ov?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-irj1ov?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Run example.

### What is expected?
A borderless status.

### What is actually happening?
A status tag with border.

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.3.0 |
| Browser | Chrome |

**Comment by OriginRing** [comment]
That's a great proposal, I will implement it soon.

**Comment by HyperLife1119** [comment]
Fixed via #8495.
