### ISSUE TITLE
Not support for Rollup in AOT mode

### ISSUE THREAD

**Issue by miao17game** [NG-ZORRO/ng-zorro-antd#85]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

When i try to rollup for the AOT mode, i find that it's impossible to build with ng-zorro.

the error message is below here:

<pre><code>
> ngc -p tsconfig-aot.json && rollup -c rollup-config.js

⚠️   'default' is imported from external module 'rollup' but never used

'default' is not exported by 'node_modules\@angular\common\@angular\common.es5.js'
'default' is not exported by 'node_modules\@angular\core\@angular\core.es5.js'
�   Error: Cannot call a namespace ('moment')
node_modules\ng-zorro-antd\src\release\datepicker\nz-datepicker.component.js (17:26)
15:     this._value = null;
16:     this._today = new Date();
17:     this._selectedMonth = moment(this.nzValue).month();
                              ^
18:     this._selectedYear = moment(this.nzValue).year();
19:     this._selectedDate = moment(this.n
</code></pre>

## What is the motivation / use case for changing the behavior?

the problem is the 'moment', it's imported in time-picker component in this format:
<pre><code>
import * as moment from 'moment'
</code></pre>
but it's not support in AOT mode.
if i change the format into 
<pre><code>
import moment from 'moment'
</code></pre>
,no errors will be called up, but still some other errors in moment.
if i remove the NG-ZORRO from my angular4 project, there is nothing wrong.
And there is no problems in JIT mode.

I don't think change the source by myself is a good way to resolve this problem.
I need help.

## Environment

<pre><code>
Angular version: 4.2.4

ng-zorro-antd version: 0.5.0

Browser:
- [x] Chrome (desktop) version 59
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform: Windows7 

Others:

</code></pre>

**Comment by miao17game** [comment]
well, i have gotten a new way to resolve this problem, the is the plugins section in my rollup-config:
<pre><code>
plugins: [
        nodeResolve({ jsnext: true, module: true }),
        commonjs({
            namedExports: {
                'node_modules/cerialize/index.js': ['deserialize', 'serializeAs', 'deserializeAs', 'serialize', 'inheritSerialization'],
                'node_modules/angular2-cookie/core.js': ['CookieOptions', 'CookieService'],
            },
            include: [
                'node_modules/rxjs/**',
                'node_modules/angular2-cookie/**',
                'node_modules/cerialize/**',
                'node_modules/ng-zorro-antd/**',
                'node_modules/moment/**',
            ]
        }),
        {
            name: 'replace moment imports',
            transform: code =>
                ({
                    code: code.replace(/import\s*\*\s*as\s*moment/g, 'import moment'),
                    map: { mappings: '' }
                })
        },
        uglify()
    ]
</code></pre>

if not add in commonjs, there will be a new undefined-error throwed in runtime.

**Comment by vthinkxie** [comment]
angular cli is officially supported, rollup has not been tested yet.
thanks for feedback, we will discuss it latter.

**Comment by trotyl** [comment]
Sounds valid, the current usage is not valid JavaScript code and has been banned in TypeScript (https://github.com/Microsoft/TypeScript/issues/2242#issuecomment-92230695) for a long time, I'm not sure why it could still compile.

**Comment by LinBoLen** [comment]
- don't import default in angular, the tslint have hinted it with error.

`import moment from 'moment` this is import default which corresponding to `export default xxx`

![image](https://user-images.githubusercontent.com/5467712/29453939-08f13f6a-83d1-11e7-9b3f-309359b2cb97.png)

- `import moment` sames that it's a hack style

**Comment by trotyl** [comment]
@LinBoLen There is no definition of how ES module interacts with CommonJS, for native Node.js and earlier version of Babel (by default), the `module.exports` would be retrieved from `import foo from '...'`, but for TypeScript (by default) and latest version of Babel (by default), the `module.exports` would be retrieved from `import * as foo from '...'`.

Moreover, TypeScript has provided `allowSyntheticDefaultImports` option for language service to allow default import for namespace implicitly, but must be combined with other bundle tools (like webpack).

Frankly, there is no valid way to import something like `moment` or `express`, all of them would be wrong, just some may work and some may not.

**Comment by LinBoLen** [comment]
long time i have not tracking ecmascript import feature. 

onething i can confirm. should only use `import {foo} from "bar"`, other like `import foo from "bar"` `import * as foo from "bar"` is not recommend

**Comment by miao17game** [comment]
the problem is there are functions and namespace in this library with the same declare name 'moment', and the rollup can not the difference.
<pre><code>
�   Error: Cannot call a namespace ('moment')
</code></pre>
in fact, the 'moment' to be used is a function ,not a namespace... but it seems that rollup don't know it

**Comment by trotyl** [comment]
Whatever import by as must be a namespace, that's the semantics of JavaScript language, and CommonJS `module.exports` has no equivalence in ES module. Rollup did nothing towrong for following the standard as an ES module bundler.

**Comment by miao17game** [comment]
but we need a solution here, or the experience in AOT and rollup won't be improved.

**Comment by miao17game** [comment]
my opinion is whether a hack or reconstruction in source code of ng-zorro isfeasible, but not the most important. 
the first work to do is make the ng-zorro usable in AOT/rollup mode cause this mode is better than any other ways for the production.

thst's my hack way ,though it' not elegant, and i prefer an official solution if possible.

**Comment by trotyl** [comment]
The best way to do it to make `moment` a global requirement like a polyfill instead of a module dependency, as it's not tree-shakable at all.

**Comment by wilsoncook** [comment]
Even i tried pass through the rollup compiling with success, the generated build.js file executed with errors that can't resolve. We are recommended to use angular-cli's tree-shaking functionality.

**Comment by trotyl** [comment]
Will be solved by #240.
