### ISSUE TITLE
nz-table 纵向支持滚动的问题

### ISSUE THREAD

**Issue by Charles953** [NG-ZORRO/ng-zorro-antd#850]
nzScroll目前只支持固定数值，不能自适应或设置百分比
是否应该支持自适应高度呢？

**Comment by cuicuicuinice** [comment]
可以自适应的；
只不过需要自己手动设置监测机制容器变化机制，
nzScroll的绑定对象在ts文件中设置，每次容器宽高改变时，
都重新给nzScroll所绑定的对象重新赋值；

切记不能这样，这样是无效的：
假设：
public height:number;
//下面是nzScroll绑定的对象
public scroll={
}

**Comment by vthinkxie** [comment]
通过修改css就可以直接获得自适应高度的table了
例子可见
https://stackblitz.com/edit/ng-zorro-antd-start-4w8y3b?file=src%2Fapp%2Fapp.component.css

**Comment by cuicuicuinice** [comment]
vthinkxie是对的！我那个方式是错误的

**Comment by 1-2-3** [comment]
自适应高度的表格：
https://1-2-3.github.io/zorro-sharper/directives/auto-height-table-demo
