### ISSUE TITLE
<nz-list-item-action> not visible

### ISSUE THREAD

**Issue by pdahlenburg** [NG-ZORRO/ng-zorro-antd#8517]
### Reproduction link
[https://angular-z3fmxr.stackblitz.io](https://angular-z3fmxr.stackblitz.io)

### Steps to reproduce
- Create a `<nz-list>`
- Create a `<nz-list-item>` inside the `<nz-list>`
- Create `<nz-list-item-action><a (click)="example()">test</a></nz-list-item-action>` inside the `<nz-list-item>`

### What is expected?
The List Item Actions should be visible and clickable

### What is actually happening?
They're somehow not visible and it's not possible to interact with them

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.4.0 |
| Browser | Firefox & Chrome latest stable |

---
Bug is since 17.4.0. In 17.3.0 there's no problem.
Bug is also active in the latest docs: https://ng.ant.design/components/list/en#components-list-demo-loadmore

**Comment by mrdear** [comment]
Also ran into this problem
