### ISSUE TITLE
nzLoading is not working with nz-card on v17.4.0

### ISSUE THREAD

**Issue by sebastian-ionita** [NG-ZORRO/ng-zorro-antd#8518]
### Reproduction link
[[[https://angular-6uqkrj.stackblitz.io/)](https://github.com/NG-ZORRO/ng-zorro-antd/issues/8518#issue-2256149997)](https://angular-6uqkrj.stackblitz.io/)

### Steps to reproduce
Go to https://ng.ant.design/components/card/en and observe Loading card example. The first card is empty when it should show loading animation.

### What is expected?
Loading animation to be displayed.

### What is actually happening?
Loading animation is not displayed.

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.4.0 |
| Browser | Chrome |

**Comment by pdahlenburg** [comment]
@vthinkxie The reproduction link is invalid

**Comment by pdahlenburg** [comment]
@sebastian-ionita The reproduction link is invalid

**Comment by sebastian-ionita** [comment]
@pdahlenburg https://angular-6uqkrj.stackblitz.io. Initally I pasted stackblitz url from here: https://ng.ant.design/components/card/en
