### ISSUE TITLE
datepicker

### ISSUE THREAD

**Issue by asweetonion** [NG-ZORRO/ng-zorro-antd#852]
## Version

0.6.9

## Environment

Google Chrome 63.0.3239.84（正式版本） （64 位）;

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-91sjw7?file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-91sjw7?file=app/app.component.html)

## Steps to reproduce

I want the start date and end date to display the current date by default, but after using the [nzDisabledDate] option, the date will not appear in the selection box

## What is expected?

The time selector defaults to show time while disabling some unwanted dates

## What is actually happening?

after using the [nzDisabledDate] option, the date will not appear in the selection box

**Comment by vthinkxie** [comment]
where is your `nzShowTime`

**Comment by asweetonion** [comment]
Thanks for the attention！ I just want to show the date, do not show the time, there is no nzShowTime seems to have no effect

**Comment by vthinkxie** [comment]
Your start date and end date should not be the same. it will trigger endValueChange and startValueChange which setting all of them to null
``` 
   _startDate = new Date();
    _endDate = new Date(new Date().getTime()+6000);
```
