### ISSUE TITLE
Angular 18 support

### ISSUE THREAD

**Issue by jornare** [NG-ZORRO/ng-zorro-antd#8546]
## What problem does this feature solve?
I'm expecting ng-zorro to be up to date with the latest Angular 18 release.

## What does the proposed API look like?
Update necessary dependencies and make a release that runs fine on Angular 18.

**Comment by Laffery** [comment]
@jornare ng-zorro 18 will come soon：)

**Comment by jornare** [comment]
> @jornare ng-zorro 18 will come soon：)

Looking forward to it :)

**Comment by wikylyu** [comment]
什么时候发布

**Comment by relliv** [comment]
+1

**Comment by MurhafSousli** [comment]
The problem that it throws an error when trying to install it on Angular 18 project, please consider using 

```
@angular/cdk": ">=17.3.0"
```

to allow installing Angular 18 without errors

https://github.com/NG-ZORRO/ng-zorro-antd/blob/843b7035225df3d3a635a5ef8926d1e80f10ae18/package.json#L31-L36

**Comment by ducminhquan** [comment]
+1

**Comment by jornare** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/pull/8564

**Comment by Laffery** [comment]
> #8564

We'll release a v18 beta version this week

**Comment by Laffery** [comment]
Hey Everyone 👋 
I'm glad to announce that [18.0.0-beta.0](https://www.npmjs.com/package/ng-zorro-antd/v/18.0.0-beta.0) is released ! 🎉
Welcom to upgrade and have a try.  We are looking forward to your feedback and  make it stable soon :)

**Comment by MurhafSousli** [comment]
@Laffery works fine with Angular 18!

**Comment by relliv** [comment]
It's working fine on my projects. Also, I'm using PNPM. Many many thanks!

**Comment by jornare** [comment]
I'm having trouble with using modals/popups that has a custom component using signal inputs. Just tested with 17, but I assume this also goes for the 18 release as I can't find any fixes in that regard.

**Comment by Laffery** [comment]
> I'm having trouble with using modals/popups that has a custom component using signal inputs. Just tested with 17, but I assume this also goes for the 18 release as I can't find any fixes in that regard.

hi @jornare, would you like provide a reproduction link to help us troubleshoot the problem?

**Comment by jornare** [comment]
> > I'm having trouble with using modals/popups that has a custom component using signal inputs. Just tested with 17, but I assume this also goes for the 18 release as I can't find any fixes in that regard.
> 
> hi @jornare, would you like provide a reproduction link to help us troubleshoot the problem?

https://stackblitz.com/edit/angular-kjryqu?file=src%2Fapp%2Fapp.component.ts

**Comment by sdbrother0** [comment]
Hello! I have different style in angular 17:
<img width="625" alt="Screenshot 2024-06-14 at 18 02 38" src="https://github.com/NG-ZORRO/ng-zorro-antd/assets/111975981/75387249-4e6a-49ac-98ae-a5fdad69eb3e">

and angular 18:
<img width="1180" alt="Screenshot 2024-06-14 at 18 03 38" src="https://github.com/NG-ZORRO/ng-zorro-antd/assets/111975981/d57e5798-606e-4870-83bd-1aea52a26308">

for NzTabsModule (nz-table) component. It's ok?

**Comment by graphicsxp** [comment]
> @jornare ng-zorro 18 will come soon：)

could you provide an estimated delivery date please ?   "soon" is a bit vague and we are blocked from upgrading to angular 18 at the moment.

**Comment by mrbusche** [comment]
> > @jornare ng-zorro 18 will come soon：)
> 
> could you provide an estimated delivery date please ? "soon" is a bit vague and we are blocked from upgrading to angular 18 at the moment.

I recommend updating to the beta and posting any issues you have here

**Comment by sdbrother0** [comment]
> > Hello! I have different style in angular 18: <img alt="Screenshot 2024-06-14 at 18 02 38" width="625" src="https://private-user-images.githubusercontent.com/111975981/339812458-75387249-4e6a-49ac-98ae-a5fdad69eb3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTE3OTksIm5iZiI6MTcxODU5MTQ5OSwicGF0aCI6Ii8xMTE5NzU5ODEvMzM5ODEyNDU4LTc1Mzg3MjQ5LTRlNmEtNDlhYy05OGFlLWE1ZmRhZDY5ZWIzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwMjMxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDczYmYzNTZmYjEyNzVkNWMxMjNkNWRkNjczMzg5OTM0ZTBkZjc0YjUwNmRiMjgwZDE0ODdmZTg5OTdhOWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8347nNJkzffTK4vQIqgJYTzQPN7M3isU3vym1LUiMcI">
> > and angular 17: <img alt="Screenshot 2024-06-14 at 18 03 38" width="1180" src="https://private-user-images.githubusercontent.com/111975981/339812661-d57e5798-606e-4870-83bd-1aea52a26308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTE3OTksIm5iZiI6MTcxODU5MTQ5OSwicGF0aCI6Ii8xMTE5NzU5ODEvMzM5ODEyNjYxLWQ1N2U1Nzk4LTYwNmUtNDg3MC04M2JkLTFhZWE1MmEyNjMwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwMjMxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTVhZTA2ZjZiMjc4MTI3MTM3NzAxNGI5OGQ0ODdjMTZiMGU5ZWZmMzcyMTYzY2IwNTI3NDQ4YzAzNDU5MmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tx5ZGtutSdso7jY6dn2NNys5mIbpGZpz3Rhtfr1wdk8">
> > for NzTableComponent (nz-table) component. It's ok?
> 
> **The same problem with Angular 17**

Exactly, thanks. How to fix, who knows?

**Comment by HyperLife1119** [comment]
Close via #8568.

**Comment by xixixixixiao** [comment]
> > Hello! I have different style in angular 18: <img alt="Screenshot 2024-06-14 at 18 02 38" width="625" src="https://private-user-images.githubusercontent.com/111975981/339812458-75387249-4e6a-49ac-98ae-a5fdad69eb3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTE3OTksIm5iZiI6MTcxODU5MTQ5OSwicGF0aCI6Ii8xMTE5NzU5ODEvMzM5ODEyNDU4LTc1Mzg3MjQ5LTRlNmEtNDlhYy05OGFlLWE1ZmRhZDY5ZWIzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwMjMxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDczYmYzNTZmYjEyNzVkNWMxMjNkNWRkNjczMzg5OTM0ZTBkZjc0YjUwNmRiMjgwZDE0ODdmZTg5OTdhOWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8347nNJkzffTK4vQIqgJYTzQPN7M3isU3vym1LUiMcI">
> > and angular 17: <img alt="Screenshot 2024-06-14 at 18 03 38" width="1180" src="https://private-user-images.githubusercontent.com/111975981/339812661-d57e5798-606e-4870-83bd-1aea52a26308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTE3OTksIm5iZiI6MTcxODU5MTQ5OSwicGF0aCI6Ii8xMTE5NzU5ODEvMzM5ODEyNjYxLWQ1N2U1Nzk4LTYwNmUtNDg3MC04M2JkLTFhZWE1MmEyNjMwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwMjMxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTVhZTA2ZjZiMjc4MTI3MTM3NzAxNGI5OGQ0ODdjMTZiMGU5ZWZmMzcyMTYzY2IwNTI3NDQ4YzAzNDU5MmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tx5ZGtutSdso7jY6dn2NNys5mIbpGZpz3Rhtfr1wdk8">
> > for NzTableComponent (nz-table) component. It's ok?
> 
> **The same problem with Angular 17**

Add `NzTableModule` to `imports`:
```ts
@Component({
  imports: [ NzTableModule ],
  selector: 'app-demo',
  standalone: true,
  styles: ``,
  template: ``
})
export class DemoComponent {}
```

**Comment by s-triar** [comment]
Is v18 support zoneless?
