### ISSUE TITLE
nz-button style collapse without element button

### ISSUE THREAD

**Issue by tinshee** [NG-ZORRO/ng-zorro-antd#858]
## Version

0.6.9

## Environment

chrome windows7 0.6.*

## Reproduction link

[https://plnkr.co/edit/Do60xQwuNqvthsRC6Hut](https://plnkr.co/edit/Do60xQwuNqvthsRC6Hut)

## Steps to reproduce

`<a nz-button nzType='default'>link</a>`
line-heigth not work

## What is expected?

self-align : middle

## What is actually happening?

self-align : top

**Comment by vthinkxie** [comment]
nz-button can not work with `a`, please use it with `button`
