### ISSUE TITLE
[Angular 17]when I use the command 'ng g ng-zorro-antd:button-size thebutton' to generate a Component I met So many Errors in the generated html files

### ISSUE THREAD

**Issue by JavaProgrammerLB** [NG-ZORRO/ng-zorro-antd#8584]
## What problem does this feature solve?
- My NG-ZORRO project based Angular 17 without app.module.ts file（standalone=true）
-  When I use the command `ng g ng-zorro-antd:button-size thebutton` to generate a Component, I hope the command will generate `imports` code for me
- Without the `imports` code, the html file reports so many errors
![Snip20240620_4](https://github.com/NG-ZORRO/ng-zorro-antd/assets/3973419/10b18b07-2d12-4d4a-8c4c-b379cf594185)

## What does the proposed API look like?
```
import { NzButtonModule, NzButtonSize } from 'ng-zorro-antd/button';
import { NzRadioModule } from 'ng-zorro-antd/radio';

  standalone: true,
  imports: [NzButtonModule, NzRadioModule, FormsModule]
```
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/3973419/16c65534-c774-471d-a573-9286ae34dc1e)

**Comment by Laffery** [comment]
already supported since 18.2.x that we migrated all the showcase into standalone mode
