### ISSUE TITLE
messageModule nzMaxStack is doesn't work

### ISSUE THREAD

**Issue by Elliottssu** [NG-ZORRO/ng-zorro-antd#859]
## Version

0.5.0

## Environment

ng-zorro 0.5.x , angular 4.4.6

## Reproduction link

[http://plnkr.co/edit/YLQBy21c3IXOaxFEa4EZ?p=preview](http://plnkr.co/edit/YLQBy21c3IXOaxFEa4EZ?p=preview)

## Steps to reproduce

`this._message.success('**', {nzDuration: 3000,nzMaxStack:1});`

## What is expected?

nzMaxStack can work

## What is actually happening?

nzMaxStack is doesn't work

**Comment by vthinkxie** [comment]
try upgrade to zorro 0.5.5 version

**Comment by Elliottssu** [comment]
@vthinkxie It's really a question of the version, thanks
