### ISSUE TITLE
Destroy inactive lazy loaded nz-tab

### ISSUE THREAD

**Issue by vypsim** [NG-ZORRO/ng-zorro-antd#8591]
## What problem does this feature solve?
The behavior of nz-tab has changed in [sync ant-design v4.23.6 PR](https://github.com/NG-ZORRO/ng-zorro-antd/pull/8482/files#diff-beb23e4688da2850dbffb292a84b509eaa9aafc7c25c8eab18e1405306f4c97aR26)

Previously, when a lazy-loaded tab is inactive, then its content is destroyed. This has been changed as shown in the link above to keep the content rendered even if the tab is inactive.

This has been a breaking change for some components in our app that were relying on ngOnInit logic executed when the tab is activated for example.

But more importantly, we have some tabs that have active websocket subscriptions that can be resource intensive and ideally they shouldn't be polling data or keeping that subscription to the backend active when their content is not visible.

Can you please provide a suitable replacement for the old behavior.

## What does the proposed API look like?
```html
<nz-tabset>
  <nz-tab nzTitle="Lazy loaded persistent tab">
    <ng-template nz-tab>
      <app-child-component></app-child-component>
    </ng-template>
  </nz-tab>
  <nz-tab nzTitle="Lazy loaded ephemeral tab">
    <ng-template nz-tab let-active>
    @if (active) {
      <app-data-polling-component></app-data-polling-component>
    }
    </ng-template>
  </nz-tab>
</nz-tabset>
```

OR 

```html
<nz-tabset>
  <nz-tab nzTitle="Lazy loaded persistent tab">
    <ng-template nz-tab>
      <app-child-component></app-child-component>
    </ng-template>
  </nz-tab>
  <nz-tab nzTitle="Lazy loaded ephemeral tab">
    <ng-template nz-tab [nzDestroyOnClose]="true">
      <app-data-polling-component></app-data-polling-component>
    </ng-template>
  </nz-tab>
</nz-tabset>
```

**Comment by rasiaq** [comment]
Same here – we also have components relying on ngOnInit logic which is broken right now. \

In addition, the components that are in the tabs are tables with many records and we introduced lazy loading for performance reasons, precisely so that the content of all the tabs is not in the DOM at the same time

**Comment by larscom** [comment]
same here, any updates on this?

**Comment by HyperLife1119** [comment]
In the upcoming v18.2 release, we've added support for the `nzDestroyInactiveTabPane` property to nz-tabset, which fixes this issue.

**Comment by bite-john-jiang** [comment]
There is the same issue in ng-zorror-antd@17, can u fix the problem in 17? because we still use the angular@17. @HyperLife1119

**Comment by HyperLife1119** [comment]
We usually do not add new features to older major versions, we recommend you upgrade to v18 as soon as possible, or you can take the temporary workaround provided by the community: https://github.com/NG-ZORRO/ng-zorro-antd/issues/8732#issuecomment-2358572543

@bite-john-jiang

**Comment by bite-john-jiang** [comment]
> We usually do not add new features to older major versions, we recommend you upgrade to v18 as soon as possible, or you can take the temporary workaround provided by the community: [#8732 (comment)](https://github.com/NG-ZORRO/ng-zorro-antd/issues/8732#issuecomment-2358572543)
> 
> @bite-john-jiang

all right, thanks
