### ISSUE TITLE
Nz-table does not show nested table when nzScroll is set

### ISSUE THREAD

**Issue by dev-anton-ko** [NG-ZORRO/ng-zorro-antd#8599]
### Reproduction link
[https://stackblitz.com/edit/angular-xpxnrx](https://stackblitz.com/edit/angular-xpxnrx)

### Steps to reproduce
* Use sample of Nested Table
* Add [nzScroll]="{y: '300px'}" to the root table

### What is expected?
Displaying of nested table

### What is actually happening?
Nested table is not displaying

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.0.0 |
| Browser | Any |

**Comment by RuneTreeStar** [comment]
I'm also having this issue.

**Comment by Laffery** [comment]
close via #8610
