### ISSUE TITLE
表格组件，有没有固定表头，这种设置？

### ISSUE THREAD

**Issue by liuliangjia** [NG-ZORRO/ng-zorro-antd#86]
表格组件，有没有固定表头，这种设置？

**Comment by SangKa** [comment]
目前还没有实现 后续会完善各种组件及功能

**Comment by vthinkxie** [comment]
not supported yet, discuss later.
thanks for feedback.

**Comment by liuliangjia** [comment]
您好，rc.4已经有这个选项了吗？是设置的 nzScroll ?

**Comment by SangKa** [comment]
@liuliangjia The PR for this feature is ready, not merged yet.
