### ISSUE TITLE
how to change all font size and font color?

### ISSUE THREAD

**Issue by zhangkang1521** [NG-ZORRO/ng-zorro-antd#860]
## What problem does this feature solve?

i want to change all font's size and color, but I just found this  NgZorroAntdModule.forRoot({ extraFontName: 'anticon', extraFontUrl: './assets/fonts/iconfont' })

## What does the proposed API look like?

NgZorroAntdModule.forRoot({ font-size: '14px', color: 'black' })

**Comment by vthinkxie** [comment]
supported in version 0.7.0 closed
