### ISSUE TITLE
NG0955

### ISSUE THREAD

**Issue by egalley** [NG-ZORRO/ng-zorro-antd#8608]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Just set [nzData]="listOfRandomUser"

### What is expected?
No warning NG0955 trackByPageItem, same warning with measure_key

### What is actually happening?
Multiple warnings that kill the browser debug.

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.0.0 |
| Browser | Chrome |

---
Please check @for track loop.

**Comment by HyperLife1119** [comment]
Close via #8593.
