### ISSUE TITLE
nz-input-number component can not set an empty value,if delete value,it will be min value or undefined

### ISSUE THREAD

**Issue by fuybooo** [NG-ZORRO/ng-zorro-antd#861]
## Version

0.6.9

## Environment

chrome

## Reproduction link

[https://ng.ant.design/#/components/input-number/github.](https://ng.ant.design/#/components/input-number/github.)

## Steps to reproduce

1.open https://ng.ant.design/#/components/input-number
2.delete number input by order
3.watch the input values

## What is expected?

when input value has been deleted, it should be an empty value,like ant-design

## What is actually happening?

when input value has been deleted, it was it's min value or undefined

## Other?

In my project,the input's default value should be an empty value.But use this version,it is unable.

**Comment by fuybooo** [comment]
Why this phenomenon is not a bug? If you leave the number input without any value, the value often goes to be undefined.

**Comment by vthinkxie** [comment]
@fuybooo how can you leave the input number without any value? it can not be set to empty with user.
