### ISSUE TITLE
Tabs: the component ngOnInit is executed only once when tab switched. 

### ISSUE THREAD

**Issue by binfuli** [NG-ZORRO/ng-zorro-antd#8629]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.module.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.module.ts)

### Steps to reproduce
I just use the lazy load demo to reproduce the issue, when switch the tab, check the console log, only the first time to the tab, the component ngOnInit is executed

### What is expected?
The component ngOnInit will be executed every time when tab switched

### What is actually happening?
ngOnInit is executed only the first time when tab switched, if switch to other tab and back, ngOnInit isn't executed

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.0.1 |
| Browser | Chrome |

**Comment by swseverance** [comment]
@binfuli the approach outlined [here](https://stackblitz.com/edit/angular-rwtvxr?file=src%2Fapp%2Fapp.component.ts) seems to work.

```ts
import { Component, OnInit, Input } from "@angular/core";

@Component({
  selector: "test",
  template: "{{ value }}",
})
export class TestComponent implements OnInit {
  @Input() value: string;

  ngOnInit(): void {
    console.log("ngOnInit() " + this.value);
  }
}

@Component({
  selector: "nz-demo-tabs-basic",
  template: `
    <nz-tabset (nzSelectChange)="index = $event.index">
      <nz-tab nzTitle="Tab 1">
        <ng-template nz-tab>
          <test *ngIf="index === 0" value="1"></test>
        </ng-template>
      </nz-tab>

      <nz-tab nzTitle="Tab 2">
        <ng-template nz-tab>
          <test *ngIf="index === 1" value="2"></test>
        </ng-template>
      </nz-tab>

      <nz-tab nzTitle="Tab 3">
        <ng-template nz-tab>
          <test *ngIf="index === 2" value="3"></test>
        </ng-template>
      </nz-tab>
    </nz-tabset>
  `,
})
export class NzDemoTabsBasicComponent {
  index = 0;
}

```

**Comment by binfuli** [comment]
@swseverance, the code you posted work well, better than my workaround by ngOnChanges, seem like have to add ngIf to let the component init when tab changed, not sure what happened comparing previous version.

Anyway, highly appreciate your help.

**Comment by bite-john-jiang** [comment]
There is the same issue in ng-zorror-antd@17, can u fix the problem in 17? because we still use the angular@17. @binfuli
