### ISSUE TITLE
dev正常，prod下tooltip以及confirm都会一闪而过

### ISSUE THREAD

**Issue by yoyohoo** [NG-ZORRO/ng-zorro-antd#863]
## Version

0.6.8

## Environment

win7  ng5  chrome  

## Reproduction link

[https://do-it-yourself.github.com](https://do-it-yourself.github.com)

## Steps to reproduce

    <nz-tooltip [nzTitle]="'提示信息'">
      <span nz-tooltip>基本提示：</span>
    </nz-tooltip>

ng build --prod 

## What is expected?

prod和dev一致

## What is actually happening?

prod有BUG

**Comment by vthinkxie** [comment]
please update your angular cli version, there is an bug in pre version.

**Comment by yoyohoo** [comment]
thanks.

**Comment by yoyohoo** [comment]
it looks the same as before, yet i've updated to "@angular/cli@1.6.3"
