### ISSUE TITLE
Variable @input-border-color: @border-color-base; not working

### ISSUE THREAD

**Issue by kid1110nd** [NG-ZORRO/ng-zorro-antd#8634]
### Reproduction link
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/default.less](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/default.less)

### Steps to reproduce
@input-border-color: red;

### What is expected?
Change variable working

### What is actually happening?
Change variable not working

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.0.1 |
| Browser | Chrome |

**Comment by Laffery** [comment]
Could you please provide a reproduction link?
