### ISSUE TITLE
DatePicker Add API for month and year change events

### ISSUE THREAD

**Issue by azimtechie** [NG-ZORRO/ng-zorro-antd#8648]
## What problem does this feature solve?
The DatePicker component should provide event emitters or callback methods to handle month and year changes when the navigation arrows are used.

## Currently, without this feature, developers are unable to:

1. Trigger Custom Actions: Perform specific actions when users navigate to a different month or year, such as loading data or updating UI elements.

2. Improve User Experience: Enhance user experience by dynamically updating the application state based on the month and year changes without requiring the user to select a date.

3. Data Loading and Caching: Implement efficient data loading and caching strategies based on the visible month and year, improving application performance.

4. Analytics and Tracking: Track user interactions with the date picker for analytics purposes, providing insights into user behavior and preferences.

By adding onMonthChange and onYearChange event emitters, developers can gain finer control over the date picker interactions, leading to more dynamic and responsive applications.

## What does the proposed API look like?
To solve the problem of detecting month and year changes in the ng-zorro-antd DatePicker, the proposed solution involves adding two new event emitters: nzOnMonthChange and nzOnYearChange. These emitters will trigger events whenever the month or year is changed using the navigation arrows.

# Proposed API

### Description: Emits an event when the month is changed.
Type: (newMonth: number) => void

### Description: Emits an event when the year is changed.
Type: (newYear: number) => void

**Comment by azimtechie** [comment]
Hello @Nicoss54 , Thank you for your suggestion! We can indeed return the whole date instead of just the year or month.

For the nzOnMonthChange and nzOnYearChange event emitters, we will return the full date corresponding to the first day of the month or year, respectively. This will provide a comprehensive view of the date context when changes occur via the navigation arrows at the top of the picker.

On Month Change: The emitter will return the date set to the 1st of the new month.
On Year Change: The emitter will return the date set to the 1st of January of the new year.
This approach ensures that developers receive a complete date object, allowing them to handle any necessary updates or actions more effectively.

Looking forward to your feedback and any further suggestions!

**Comment by Nicoss54** [comment]
Hello @azimtechie , i'm not sure that reinit to the first of month or first date of year when month or year change suit the best with user experience

Let's imagine a user select a date, and then change the month, changing the entire date doest not respect the initial choice of the user.

Maybe it could be a better id to send in the event the date without any kind of transformation

what do you think ?

**Comment by HyperLife1119** [comment]
I think we should implement onPanelChange event, reference:
https://4x.ant.design/components/date-picker/#API:~:text=%2D-,onPanelChange,-Callback%20when%20picker

demo: https://stackblitz.com/edit/react-stvs1n?file=demo.tsx

**Comment by Nicoss54** [comment]
@HyperLife1119 i'm ok with this idea, let's create a new event emitter which emit the full date :), if you are agree with that i will take the developement on my side and do as soos as possible

**Comment by HyperLife1119** [comment]
@Nicoss54 Yes, just make the zorro API as consistent with the ant design as possible :)

**Comment by Nicoss54** [comment]
@HyperLife1119 of course, i will do my best

**Comment by azimtechie** [comment]
> I think we should implement onPanelChange event, reference: https://4x.ant.design/components/date-picker/#API:~:text=%2D-,onPanelChange,-Callback%20when%20picker
> 
> demo: https://stackblitz.com/edit/react-stvs1n?file=demo.tsx

yes this is exactly what needs to be done as we have the same in Ant design. @HyperLife1119 Thanks for your suggestion
