### ISSUE TITLE
use the latest version has getting error "Attempting to attach an unknown Portal type." again

### ISSUE THREAD

**Issue by PatricioPeng** [NG-ZORRO/ng-zorro-antd#865]
## Version

0.6.9

## Environment

`ng-zorro-antd@0.6.9`  
`@angular/cdk@5.0.3`

## Reproduction link

[github.com/NG-ZORRO/ng-zorro-antd/issues/504](https://github.com/NG-ZORRO/ng-zorro-antd/issues/504)

## Steps to reproduce

 just like the [issue#504](https://github.com/NG-ZORRO/ng-zorro-antd/issues/504)    
 I got error "Attempting to attach an unknown Portal type." via ng build --prod while using `ng-zorro-antd@0.6.9` and `@angular/cdk@5.0.3`

## What is expected?

no error

## What is actually happening?

`ERROR Error: Attempting to attach an unknown Portal type. BasePortalOutlet accepts either a ComponentPortal or a TemplatePortal.`

## Other?

The [issue#504](https://github.com/NG-ZORRO/ng-zorro-antd/issues/504) had been closed in [#509 "build(packaging): fix cdk 2.0.0-beta.12 configurations of rollup "](https://github.com/NG-ZORRO/ng-zorro-antd/pull/509).    
And it works while using `ng-zorro-antd@0.6.2` and `@angular/cdk@5.0.0-rc0`.    
But it gets error while useing the lastest version `ng-zorro-antd@0.6.9` and `@angular/cdk@5.0.3`

**Comment by vthinkxie** [comment]
make sure you have installed the correct version, if you have to reinstall all the node_modules when you upgrade your package.json
