### ISSUE TITLE
nzQueryParams not called

### ISSUE THREAD

**Issue by BenediktKarl** [NG-ZORRO/ng-zorro-antd#8659]
### Reproduction link
[https://stackblitz.com/edit/angular-qwhhql?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-qwhhql?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Use nz-table as standalone component. Try to use the AJAX features as in the documentation: https://ng.ant.design/components/table/en#components-table-demo-ajax

### What is expected?
The expected behaviour is that the function specified in nzQueryParams will be called when sorting changes. Paginiation should show up with the code from the documentation.

### What is actually happening?
The function specified in nzQueryParams is not called when sorting changes. Pagination is missing, even though it shows in the documentation.

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.1.0 |
| Browser | Chrome |

**Comment by hanjeahwan** [comment]
```
@Component({
  selector: 'app-order-table',
  standalone: true,
  imports: [
    NzTableModule, <---
    NzEmptyComponent,
    NzFlexDirective,
  ],
  templateUrl: './order-table.component.html',
})
```
