### ISSUE TITLE
输入型(text)nz-input 不支持自动获取用户输入焦点的事件onfocus 

### ISSUE THREAD

**Issue by oyboyb** [NG-ZORRO/ng-zorro-antd#866]

**Comment by oyboyb** [comment]
项目表格nz-table中动态生成一行数据让用户输入数据,可是nz-input不支持onfocus事件

**Comment by vthinkxie** [comment]
read the doc again https://ng.ant.design/#/components/input

**Comment by oyboyb** [comment]
大佬 ，这里只有事件获取焦点事件回调机制并不是我想要的，那个 nzFocus 并不是我想要的功能。我们是想要的，当input 生成的时候立马获取用户焦点就行了，提示用户新增的item里的input在这儿。[http://www.w3school.com.cn/tags/att_input_autofocus.asp](url)

github玩得少，不太习惯英文，大佬见谅。

**Comment by oyboyb** [comment]
上面那个链接功能就是我想要的。

**Comment by vthinkxie** [comment]
https://stackoverflow.com/questions/43689532/is-there-an-angular2-way-to-focus-on-an-input-field
