### ISSUE TITLE
isolatedModules support

### ISSUE THREAD

**Issue by strigefleur** [NG-ZORRO/ng-zorro-antd#8703]
## What problem does this feature solve?
Typescript 5.5 (since Angular 18.1) allows using [isolatedModules](https://www.typescriptlang.org/tsconfig/#isolatedModules) supposedly giving some build performance.

Enabling `isolatedModules` in project with `ng-zorro-antd` atm results in errors.

```
X [ERROR] TS6053: File '.../node_modules/ng-zorro-antd/icon/public-api.ngtypecheck.d.ts' not found. [plugin angular-compiler]

    node_modules/ng-zorro-antd/icon/public-api.d.ts:5:21:
      5 │ /// <reference path="public-api.ngtypecheck.d.ts" />
```

Actually it's enabled by default with ts > 5.5

## What does the proposed API look like?
-

**Comment by Laffery** [comment]
due to #8697, fixed in v18.1.1
