### ISSUE TITLE
Drawer抽屉nzCloseOnNavigation前进/后退nzVisible值未变更

### ISSUE THREAD

**Issue by 232650413** [NG-ZORRO/ng-zorro-antd#8719]
### Reproduction link
[https://angular-undw7j.stackblitz.io](https://angular-undw7j.stackblitz.io)

### Steps to reproduce
打开抽屉，浏览器后退/前进，抽屉关闭了nzVisible值却未变更。二次打开抽屉无响应。

### What is expected?
打开抽屉，浏览器后退/前进，抽屉关闭了nzVisible值变更。

### What is actually happening?
打开抽屉，浏览器后退/前进，抽屉关闭了nzVisible值却未变更。二次打开抽屉无响应。

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.1.1 |
| Browser | chrome |

---
modal同样有，是正常的。笔记本手触还是比较影响的。

**Comment by ParsaArvanehPA** [comment]
Hi @232650413 ,
Thank you for reporting this issue. 
The link you have provided only has the application view, please share the `Editor URL` so we can see your code.

**Comment by 232650413** [comment]
> L
https://stackblitz.com/edit/angular-undw7j?file=src%2Fapp%2Fapp.component.ts 这个是编辑模式
