### ISSUE TITLE
Icons rendered incorrectly

### ISSUE THREAD

**Issue by vatsake** [NG-ZORRO/ng-zorro-antd#8723]
### Reproduction link
--

### Steps to reproduce
--

### What is expected?
Icon rendered correctly

### What is actually happening?
Icon is wrong or incorrectly rendered

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.1.1 |
| Browser | Chrome |

Look at the medicinebox icon. Taken from ng-zorro docs.
![image](https://github.com/user-attachments/assets/45eed6a4-0f38-4a54-80b1-a1311922f437)
If hovering icon, then it renders correctly.
![image](https://github.com/user-attachments/assets/360465c7-94da-4359-b0e6-0015f753fcbf)

**Comment by Laffery** [comment]
Failed to reproduce
