### ISSUE TITLE
nz-tab懒加载失效

### ISSUE THREAD

**Issue by 694551594** [NG-ZORRO/ng-zorro-antd#8732]
### Reproduction link
[https://stackblitz.com/edit/angular-56busz?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-56busz?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1、使用官网自带的示例即可重现。
2、在多次切换懒加载的nz-tab时，ngOnInit方法只触发一次，之前是每次切换都会触发。

### What is expected?
希望在懒加载模式下ngOnInit每次切换都会触发。

### What is actually happening?
在多次切换懒加载的nz-tab时，ngOnInit方法只触发一次

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.1.1 |
| Browser | Microsoft Edge 版本 128.0.2739.63 (正式版本) (64 位) |

**Comment by ParsaArvanehPA** [comment]
Hi @694551594 
Well I guess this behavior is expected. A lazy-loaded tab just lazy loads it; it is right there in the title, there is not indication that a lazy-loaded tab should be destroyed when moved to another tab. Although the main reason to use a lazy-loaded tab is memory optimization, so I agree with you that this is a useful feature. 

For now you can simple use a `@if` in in lazy-loaded tab to get the result you're after. You can see the workaound [here](https://stackblitz.com/edit/angular-56busz-dt5vea?file=src%2Fapp%2Fapp.component.ts).

What do you guys think?
Should this feature be implemented as a default behavior for the tab component?
@HyperLife1119 
@Laffery 
@Nicoss54

**Comment by HyperLife1119** [comment]
Repeat for #8591. Close this.
