### ISSUE TITLE
 nz-form 错误

### ISSUE THREAD

**Issue by toplinuxsir** [NG-ZORRO/ng-zorro-antd#874]
## Version

0.6.10

## Environment

chrome 63

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-hzfnv6](https://stackblitz.com/edit/ng-zorro-antd-setup-hzfnv6)

## Steps to reproduce

Please visit : 
https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.ts

## What is expected?

nz-form work correctly

## What is actually happening?

nz-form does not work

**Comment by vthinkxie** [comment]
you need to import `ReactiveFormsModule` when you want to use reactive form

**Comment by toplinuxsir** [comment]
Thanks ! , It works !
