### ISSUE TITLE
开发完成后，使用Ng-build命令打包后，ng-zorro按钮绑定的一些方法失效。

### ISSUE THREAD

**Issue by Hubmeat** [NG-ZORRO/ng-zorro-antd#880]
## Version

0.6.10

## Environment

浏览器版本 63.0.3239.84（正式版本） （32 位）

## Reproduction link

[https://github.com/Hubmeat/RealMadrid.git](https://github.com/Hubmeat/RealMadrid.git)

## Steps to reproduce

ng build --prod出错，ng build正常。

## What is expected?

期望正常使用

## What is actually happening?

使用ng-build --prod打包后部门ui组件方法失效，ng-zorro按钮绑定的一些方法失效  
menu组件点击展开，打包后运行变成了hover的时候展开。

使用ng-build页面正常

## Other?

可能是我的问题，希望大神们能给我一个回应

**Comment by vthinkxie** [comment]
@Hubmeat please upgrade to the latest version of `angular-cli` and reinstall the node_modules, there is a serious bug in pre version.

**Comment by Hubmeat** [comment]
@vthinkxie thank you, i have deal with this problems。
Are you a foreign friend?

**Comment by qq894617385** [comment]
@Hubmeat 请问你是如何解决的,是按照Hubmeat 的方法吗
