### ISSUE TITLE
nz-input-number can not change the value by inputting a number after setting nzFormatter/nzParser

### ISSUE THREAD

**Issue by KunerRick** [NG-ZORRO/ng-zorro-antd#883]
## Version

0.6.10

## Environment

Windows 7

## Reproduction link

[https://ng-zorro-antd-setup-5ubjsg.stackblitz.io](https://ng-zorro-antd-setup-5ubjsg.stackblitz.io)

## Steps to reproduce

html :
```

<nz-input-number
 style="width: 200px;"
 [(ngModel)]="MaxAngle" 
[nzFormatter]="formatterAngle" 
[nzParser]="parserAngle"
  [nzMin]="0"
 [nzMax]="360"
 [nzStep]="10" ></nz-input-number>

```
<br/>
ts:

```

 MaxAngle = 360;
 formatterAngle  = value => `${value} °`;
 parserAngle = value=>`value.replace(' °', '')`;

```

## What is expected?

input 20 ,value of nz-input-number will be 20

## What is actually happening?

input 20 ,value of nz-input-number is 360 (initial value is 360)

**Comment by vthinkxie** [comment]
```typescript 
parserAngle = value=>value.replace(' °', '');
```
not 
```typescript
parserAngle = value=>`value.replace(' °', '')`;
```

**Comment by KunerRick** [comment]
Thanks
