### ISSUE TITLE
Remove nz-drawer focus

### ISSUE THREAD

**Issue by vatsake** [NG-ZORRO/ng-zorro-antd#8839]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-eqsoqx?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-eqsoqx?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1. Click the first button
2. Close the drawer
3. Click the second button
3. Close the drawer

The first button will be focused

### What is expected?
The previous button is focused or nothing is focused at all.

### What is actually happening?
nz-drawer components saves the first focused element.
So it will focus that one after drawer close.

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.1.1 |
| Browser | Chrome |

---
It might not look like a big issue, but in my form, the buttons are far apart.
After closing the drawer, the element will be focused and the window will be scrolled to that element.

Maybe add option to focus or not?

**Comment by ParsaArvanehPA** [comment]
Hi @vatsake ,
Thank you for reporting this issue,
a fix is on it's way 👍

**Comment by ParsaArvanehPA** [comment]
@vatsake 
My bad, i had forgotten to make the pr for this change back then 😅😅
This should fix this issue #8893

**Comment by Laffery** [comment]
> Is there any way to fix this problem at that exact version because my app could not just upgrade to the latest ng-zorro version

We only support the latest major version.

**Comment by oktesting** [comment]
Thanks for the information, my workaround this behavior is just use the *ngIf on the drawer itself, then `previouslyFocusedElement` will not have a chance to focus itself anymore
