### ISSUE TITLE
能不能把 那些直接引用 cdn 上的资料直接打包在 npm 引用里面?比如 https://at.alicdn.com/t/font_zck90zmlh7hf47vi.ttf 这些东西。

### ISSUE THREAD

**Issue by lsczyzkb** [NG-ZORRO/ng-zorro-antd#884]
## What problem does this feature solve?

能不能把 那些直接引用 cdn 上的资料直接打包在 npm 引用里面?比如 https://at.alicdn.com/t/font_zck90zmlh7hf47vi.ttf 这些东西。
既然是做企业后台管理系统，这些企业的管理系统，好多地方是没有外网权限的。也就是没法访问那些信息。最后出现图标显示不出来

## What does the proposed API look like?

直接引用在 npm 里面

**Comment by vthinkxie** [comment]
https://ng.ant.design/#/components/icon -> 本地部署
