### ISSUE TITLE
导航菜单menu显示异常,复制官网上的代码后测试显示异常

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [NG-ZORRO/ng-zorro-antd#8869]
### Reproduction link
[https://github.com/LetAmericaGreatAgain/Demo2/tree/master](https://github.com/LetAmericaGreatAgain/Demo2/tree/master)

### Steps to reproduce
下载master分支代码后，npm install然后ng serve运行就行

### What is expected?
解决一下这个异常问题

### What is actually happening?
导航菜单menu显示异常,复制官网上的代码后测试显示异常，还卡的一匹

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.2.0 |
| Browser | chrome |

**Comment by Laffery** [comment]
检查控制台报错，你需要在 AppModule 中 provide 一下 BrowserAnimationModule 或者 NoopAnimationModule

<img width="494" alt="image" src="https://github.com/user-attachments/assets/2c8f64f8-02d3-4b4b-aa9b-f67177b0d388">
