### ISSUE TITLE
Incorrect parameter explanation of Tooltip document (zh) in ng zorro website

### ISSUE THREAD

**Issue by WwwHhhYran** [NG-ZORRO/ng-zorro-antd#8871]
### Reproduction link
https://ng.ant.design/components/tooltip/zh

### Steps to reproduce
Document (zh) error of [Tooltip](https://ng.ant.design/components/tooltip/zh)

### What is expected?
| 参数 | 说明 | 类型 | 默认值 |
|---|---|---|---|
| `[nzTooltipTrigger]`            | 触发行为，可选 `hover` \| `focus` \| `click`，为 `null` 时不响应光标事件 | `'click' \| 'focus' \| 'hover' \| null`                                                                                                                                           | `'hover'` |

### What is actually happening?
| 参数 | 说明 | 类型 | 默认值 |
|---|---|---|---|
| `[nzTooltipTrigger]`            | 触发行为，可选 `hover` | `focus` |  `click`，为 `null` 时不响应光标事件 | 

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.2.0 |
| Browser | Chrome |

**Comment by Laffery** [comment]
@WwwHhhYran Feel free to draft a pr to fix it;
