### ISSUE TITLE
NzNotificationService.error(title, content, option) 

### ISSUE THREAD

**Issue by tankgod** [NG-ZORRO/ng-zorro-antd#888]
NzNotificationService.error(title, content, option)  当 title 有值 content 没有值且 title  为单行显示的时，样式并不是很nice 如图 
![image](https://user-images.githubusercontent.com/11535593/34760138-8671a906-f619-11e7-9d21-b55f4e22db96.png)

**Comment by vthinkxie** [comment]
@tankgod the style is synced with ant design version 2.x, you can try it after 0.7.0 released
