### ISSUE TITLE
nz-select title error

### ISSUE THREAD

**Issue by dubbowang** [NG-ZORRO/ng-zorro-antd#889]
## Version

0.5.4

## Environment

Windows10   Google Chrome 61.0.3163.100

## Reproduction link

[https://ng-zorro-antd-setup-ypredw.stackblitz.io](https://ng-zorro-antd-setup-ypredw.stackblitz.io)

## Steps to reproduce

The first step : nz-select  [nzMode]="'multiple'"

Second steps : select multiple values

Third steps: The mouse stays on a value , show the value of the item

## What is expected?

Third steps: The mouse stays on a value , show the label of the item

## What is actually happening?

Third steps: The mouse stays on a value , show the value of the item

## Other?

英语不好，中文表达一遍，在使用select 多选模式 的时候  当鼠标停留在已经选择的选项上面，会显示该选项的value，这是不应该的，应该显示该选项的label,请修正，谢谢

**Comment by vthinkxie** [comment]
Hi @dubbowang , version 0.5.x is not under maintain now, the bug will be fixed in next 0.6.x version, thanks for your feedback.

**Comment by dubbowang** [comment]
Your reply is very quick, expect the product to do better.
