### ISSUE TITLE
Angular 19 Support

### ISSUE THREAD

**Issue by markpritchett** [NG-ZORRO/ng-zorro-antd#8890]
## What problem does this feature solve?
Allows users to migrate to Angular 19

## What does the proposed API look like?
Upgrade dependencies to enable users to migrate to Angular 19.

PR merged for **@ant-design/icons-angular** package [chore: bump icons-angular to v19](https://github.com/ant-design/ant-design-icons/pull/677) but it seems we waiting for NPM package to be published

**Comment by Laffery** [comment]
npm package for @ant-design/icons-angular v19 is published.

ng-zorro-antd@19 is on the way, we are planning to publish a beta version this week.

**Comment by azimtechie** [comment]
> npm package for @ant-design/icons-angular v19 has been published today.
> 
> ng-zorro-antd@19 is on the way, we are planning to publish a beta version this week.

Any update on this ? because we are starting new project with angular 19 and we really need to ng-zorro in our project

**Comment by Laffery** [comment]
There is an important feature PR still in progress #8903

**Comment by dylanvdmerwe** [comment]
These two PRs have nothing to do with Angular 19 though? Why would these block the support of 19?

**Comment by markpritchett** [comment]
> These two PRs have nothing to do with Angular 19 though? Why would these block the support of 19

@dylanvdmerwe  It's likely to be because those 2 PRs are part of [v19 Milestone](https://github.com/NG-ZORRO/ng-zorro-antd/milestone/19) and since at least one of these PRs contains breaking changes, it will be better to include it with Angular upgrade otherwise the team wouldn't have the opportunity to introduce breaking changes until v20, most likely due out after Angular v20.

**Comment by ext-dflopes** [comment]
![image](https://github.com/user-attachments/assets/944768c7-fb14-4a31-98bf-6f27c737e619)
Yeah! We're almost there! My frontend team is joining me next week, and I’m pumped to have Angular 19 ready in the architecture for their arrival. Let’s keep up the amazing work!

**Comment by Laffery** [comment]
👋 Hey everyone!

`ng-zorro-antd@19.0.0-beta.0` is available, welcome to upgrade to the beta version and have a try by executing

```sh
ng update ng-zorro-antd@19.0.0-beta.0
```

We've brought in a lot of new features in v19, please refer to [release note](https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/19.0.0-beta.0) to learn more! Thanks to all the developers in the community who have contributed so much to it!

Looking forward to your kindly feedback, which is really **important** to us. 

Best,
NG ZORRO team

**Comment by Laffery** [comment]
> ```shell
> ng update ng-zorro-antd@19.0.0-beta.0
> ```

For people who use ng update to upgrade, you may encounter the following errors

```log
An unhandled exception occurred: Cannot find module '@angular-devkit/core'
Require stack:
- /Users/laffery/playground/ng-version/ng18/node_modules/@angular/cdk/schematics/utils/build-component.js
- /Users/laffery/playground/ng-version/ng18/node_modules/@angular/cdk/schematics/utils/index.js
- /Users/laffery/playground/ng-version/ng18/node_modules/@angular/cdk/schematics/index.js
- /Users/laffery/playground/ng-version/ng18/node_modules/ng-zorro-antd/schematics/ng-update/index.js
- /private/var/folders/wy/hks67dyn2t3856tggqh4zkkw0000gp/T/angular-cli-packages-o3eQSL/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /private/var/folders/wy/hks67dyn2t3856tggqh4zkkw0000gp/T/angular-cli-packages-o3eQSL/node_modules/@angular-devkit/schematics/tools/index.js
- /private/var/folders/wy/hks67dyn2t3856tggqh4zkkw0000gp/T/angular-cli-packages-o3eQSL/node_modules/@angular/cli/src/commands/update/cli.js
- /private/var/folders/wy/hks67dyn2t3856tggqh4zkkw0000gp/T/angular-cli-packages-o3eQSL/node_modules/@angular/cli/src/commands/command-config.js
- /private/var/folders/wy/hks67dyn2t3856tggqh4zkkw0000gp/T/angular-cli-packages-o3eQSL/node_modules/@angular/cli/src/command-builder/command-runner.js
- /private/var/folders/wy/hks67dyn2t3856tggqh4zkkw0000gp/T/angular-cli-packages-o3eQSL/node_modules/@angular/cli/lib/cli/index.js
- /private/var/folders/wy/hks67dyn2t3856tggqh4zkkw0000gp/T/angular-cli-packages-o3eQSL/node_modules/@angular/cli/lib/init.js
See "/private/var/folders/wy/hks67dyn2t3856tggqh4zkkw0000gp/T/ng-eUtPGl/angular-errors.log" for further details.
```

Consider to add `@angular-devkit/core` to devDependencies explicitly.

**Comment by lppedd** [comment]
@Laffery hey! The `19.0.0-beta.0` changelog says `NzInputGroupComponent` is deprecated, yet it's not marked as such in the code and I can't find the proposed alternative. Are you sure it's correct?

**Comment by Laffery** [comment]
> @Laffery hey! The `19.0.0-beta.0` changelog says `NzInputGroupComponent` is deprecated, yet it's not marked as such in the code and I can't find the proposed alternative. Are you sure it's correct?

@lppedd hi! It's a mistake, what's really deprecated is its `nzCompact` input property, which can be replaced with new `nz-space-compact` component.

The [release note](https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/19.0.0-beta.0) is updated, thank you very much!
