### ISSUE TITLE
Component for File Uploading like Ant Design of React

### ISSUE THREAD

**Issue by OnlyBelter** [NG-ZORRO/ng-zorro-antd#89]
后续会开发上传文件或图片的组件吗，就像Ant Design of React中实现的[Upload组件](https://ant.design/components/upload-cn/)那样。

**Comment by vthinkxie** [comment]
we will sync with ant design react, upload component is in our plan.

**Comment by thegatheringstorm** [comment]
Can I claim this task?

**Comment by vthinkxie** [comment]
@thegatheringstorm 
of course, thanks.

**Comment by vthinkxie** [comment]
duplicated #132
