### ISSUE TITLE
19.0.0-beta.0版本下，刷新页面布局会闪烁

### ISSUE THREAD

**Issue by huajian123** [NG-ZORRO/ng-zorro-antd#8918]
### Reproduction link
[https://stackblitz.com/~/github.com/huajian123/ng19](https://stackblitz.com/~/github.com/huajian123/ng19)

### Steps to reproduce
可以通过stackblitz链接复现（stackblitz 刷新难复现页面闪烁），也可以通过https://github.com/huajian123/ng19这个源码地址，本地安装启动复现(本地启动时，打开浏览器控制台，容易复现页面闪烁)
1. 创建ng18的纯净应用
2. ng add ng-antd-zorro 安装18的zorro版本，选择side模式的布局
3. ng update @angular/cli @angular/core --force --allow-dirty 升级ng
4. npm uninstall ng-zorro-antd    移除18的zorro
5. 安装  "ng-zorro-antd": "^19.0.0-beta.0"的zorro

本地启动后，按f12打开控制台，疯狂刷新页面，会发现menu刷新后有缩放动画，偶尔会出现页面闪烁的问题。
然而在ng18版本下，是没有此情况

### What is expected?
多次刷新页面，页面不会闪烁

### What is actually happening?
多次刷新页面，页面会闪烁

| Environment | Info |
|---|---|
| ng-zorro-antd | 19.0.0-beta.0 |
| Browser | chrome |

---
stackblitz 刷新难复现页面闪烁，可以通过https://github.com/huajian123/ng19这个源码地址，本地安装启动复现，本地启动时，打开浏览器控制台，多次刷新页面，容易复现页面闪烁

**Comment by HyperLife1119** [comment]
https://github.com/angular/angular/issues/59058
