### ISSUE TITLE
how to get img dom in modal by this.elementRef.nativeElement.querySelector

### ISSUE THREAD

**Issue by lishaoh** [NG-ZORRO/ng-zorro-antd#892]
## What problem does this feature solve?

```
<ng-template #content><img src=''></ng-template>
```
## What does the proposed API look like?

this.elementRef.nativeElement.querySelector('img')   is  null, why?

**Comment by lishaoh** [comment]
now need tu upload img and get img dom

**Comment by vthinkxie** [comment]
the dom is moved from the element to the root body, you can get it from this.document.querySelector

**Comment by lishaoh** [comment]
but this.document.querySelector, document is undefined?? @vthinkxie

**Comment by vthinkxie** [comment]
https://angular.cn/api/common/DOCUMENT

**Comment by lishaoh** [comment]
TypeError: Cannot read property 'querySelector' of undefined by DOCUMENT , but use document is ok
