### ISSUE TITLE
NzModalService.confirm添加属性content无效，content内容不显示

### ISSUE THREAD

**Issue by x3852** [NG-ZORRO/ng-zorro-antd#893]
## What problem does this feature solve?

NzModalService.info、NzModalService.success、NzModalService.error、NzModalService.warning、NzModalService.confirm里的content设置无效，弹框内容显示空白，控制台没报异常。
iconType这个属性设置了也不显示icon。
当前ng-zorro-antd版本0.6.10

## What does the proposed API look like?

正常情况下应该能像API示例中弹框能显示出来内容。
我的Code:
this.modalService.confirm({
      iconType: 'warning',
      title: '系统提示',
      content: '确定要提交数据吗?',
      onOk: () => {}
});

**Comment by vthinkxie** [comment]
please produce the mini reproduction link, everything work fine in the doc website, we can not help you without your code.

**Comment by x3852** [comment]
![image](https://user-images.githubusercontent.com/26081477/34816100-d28ad652-f6ee-11e7-9fde-99403a19e1d7.png)
![image](https://user-images.githubusercontent.com/26081477/34816217-3d715f36-f6ef-11e7-92f5-d1e56f6af18d.png)

**Comment by vthinkxie** [comment]
reproduce it with plunker or https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.ts we can not reproduce it with your screenshot

**Comment by x3852** [comment]
在plunker上并没有出现问题，只是在我的项目中出现了这样的问题。

**Comment by vthinkxie** [comment]
@x3852 please check your code or your local environment.
