### ISSUE TITLE
The nz-collapse's [nzTitle] can not be added html label

### ISSUE THREAD

**Issue by dzh145** [NG-ZORRO/ng-zorro-antd#895]
<nz-collapseset id="miao" style="background: lightskyblue" [nzBordered]="false" >
                    <nz-collapse *ngFor="let panel of planNum"
                                 [nzTitle]="'方案'+panel.PROC_PLAN+':'+panel.allProgamName"
                                 [ngStyle]="panel.customStyle"
                                 [nzActive]="panel.active">
[nzTitle]  can not add html label ,  please

**Comment by vthinkxie** [comment]
[collapse-title]	与nzTitle二选一，定义面板头内容	ng-content	无 
https://ng.ant.design/#/components/collapse
please read the doc before asking
