### ISSUE TITLE
nz-collapse ' error 

### ISSUE THREAD

**Issue by dzh145** [NG-ZORRO/ng-zorro-antd#898]
message: Can't bind to 'collapse-title' since it isn't a known property of 'nz-collapse'.

my code :
<nz-collapse *ngFor="let panel of panels"
[collapse-title]="'11111'"
[ngStyle]="panel.customStyle"
[nzActive]="panel.active">

**Comment by vthinkxie** [comment]
collapse-title is a `ng-content` selector

```html
<nz-collapse *ngFor="let panel of panels"
[ngStyle]="panel.customStyle"
[nzActive]="panel.active">
<div collapse-title>11111</div>
</nz-collapse>

```
