### ISSUE TITLE
staticinjectorerror occurred when use nz-popover in PROD environment 

### ISSUE THREAD

**Issue by wunaidage** [NG-ZORRO/ng-zorro-antd#899]
## Version

0.6.10

## Environment

windows 7; latest chrome; latest ng-zorro; backend: spring boot. use maven build to run angular building process

## Reproduction link

[https://ng-zorro-antd-setup.stackblitz.io](https://ng-zorro-antd-setup.stackblitz.io)

## Steps to reproduce

1. apply nz-popover in a component's template
2. run ng build or yarn build
3. start backend, go to the page that have the component 

## What is expected?

see page rendered correctly and I can use popover without issue.

## What is actually happening?

page render failed. the component applied nz-popover only runs the constructor(), it can not even run onInit(). 
Developer console shows error: 
```
staticinjectorerror[n]: nullinjectorerror: no provider for n!
```
there is no further valuable error information since in prod environment it's all minified. 
if I remove nz-popover in the component, there will be no error and page rendered as expected.

## Other?

THIS ONLY HAPPENS IN PROD ENVIRONMENT. IN DEV ENVIRONMENT, EVERYTHING WORKS PERFECTLY. HELP!
重现链接 is fake, no way to reproduce it.

**Comment by vthinkxie** [comment]
please update your angular-cli version, if the bug only arise with prod mode, it is not the bug of ng-zorro, you can get more information from here https://github.com/angular/angular-cli/issues/8997

**Comment by wunaidage** [comment]
thanks @vthinkxie ! I'll check it
