### ISSUE TITLE
组件的ngOnInit方法中调用NzModalService的open方法出错

### ISSUE THREAD

**Issue by hdhxby** [NG-ZORRO/ng-zorro-antd#90]
Angular版本信息:
4.2.6.
使用组件库替换ng-bootstrap的过程中,弹出主键的初始化方法中调用了NzModalService的open方法.
方法信息.
export class MainRegionComponent implements OnInit {

    constructor(private modalService: NzModalService) {
    }

    /**
     * 初始化.
     */
    ngOnInit(){
        const subscription = this.modalService.open({
            title: '对话框标题',
            content: OtherRegionDeleteComponent,
            onOk() {
            },
            onCancel() {
                console.log('Click cancel');
            },
            footer: false,
            componentParams: {
                name: '测试渲染Component'
            }
        });
        subscription.subscribe(result => {
            console.log(result);
        })
    }
}
异常信息
ERROR Error: ApplicationRef.tick is called recursively
    at ApplicationRef_.tick (core.es5.js:5004)
    at ApplicationRef_._loadComponent (core.es5.js:4985)
    at ApplicationRef_.bootstrap (core.es5.js:4973)
    at NzModalService._open (nz-modal.service.js:87)
    at NzModalService.open (nz-modal.service.js:121)
    at MainRegionComponent.ngOnInit (main.component.ts:26)
    at checkAndUpdateDirectiveInline (core.es5.js:11038)
    at checkAndUpdateNodeInline (core.es5.js:12534)
    at checkAndUpdateNode (core.es5.js:12473)
    at debugCheckAndUpdateNode (core.es5.js:13334)

**Comment by vthinkxie** [comment]
modal can not open directly in ngOnInit hook, you can wrap it with setTimeout() like below

```typescript
ngOnInit(){
    setTimeout(()=>{
        const subscription = this.modalService.open({
            title: '对话框标题',
            content: OtherRegionDeleteComponent,
            onOk() {
            },
            onCancel() {
                console.log('Click cancel');
            },
            footer: false,
            componentParams: {
                name: '测试渲染Component'
            }
        });
        subscription.subscribe(result => {
            console.log(result);
        })
    })
}
```
