### ISSUE TITLE
when I click on the <nz-switch>, the <nz-collapse> will unfold at the same time, and I don't want to do this

### ISSUE THREAD

**Issue by dzh145** [NG-ZORRO/ng-zorro-antd#901]
## What problem does this feature solve?

Ok,I've got your hint，And it's been successful, but there's a little problem.

<div  collapse-title > 
                             '方案'{{panel.PROC_PLAN}}':'{{panel.allProgamName}} 
                            <nz-switch style="float: right; margin-right: 10px;" (ngModelChange)="switchCase($evnet,panel)" [ngModel]="panel.oncheck">
                                <i class=" anticon anticon-check" checked></i>
                                <i class=" anticon anticon-cross" unchecked></i>
                            </nz-switch>
                        </div>

I used the <nz-switch> ,  problem is that when I click on the <nz-switch>, the <nz-collapse> will unfold at the same time, and I don't want to do this

## What does the proposed API look like?

Ok,I've got your hint，And it's been successful, but there's a little problem.

<div  collapse-title > 
                             '方案'{{panel.PROC_PLAN}}':'{{panel.allProgamName}} 
                            <nz-switch style="float: right; margin-right: 10px;" (ngModelChange)="switchCase($evnet,panel)" [ngModel]="panel.oncheck">
                                <i class=" anticon anticon-check" checked></i>
                                <i class=" anticon anticon-cross" unchecked></i>
                            </nz-switch>
                        </div>

I used the <nz-switch> ,  problem is that when I click on the <nz-switch>, the <nz-collapse> will unfold at the same time, and I don't want to do this

**Comment by vthinkxie** [comment]
If you do not want to collapse, what you need is not the `collapse` component.

**Comment by dzh145** [comment]
No, I want to use collapse, but at the same time, I want to use <nz-switch> on the collapse's title propertie,When I click on <nz-switch>, I don't  let collpse expand，Can you understand what I mean

**Comment by dzh145** [comment]
No, I want to use collapse, but at the same time, I want to use <nz-switch> on the collapse's title propertie,When I click <nz-switch> , I don't let collpse expand，Can you understand what I mean

**Comment by dzh145** [comment]
No, I want to use collapse, but at the same time, I want to use nz-switch on the collapse's title propertie,When I click on , I don't let collpse expand，Can you understand what I mean

**Comment by dzh145** [comment]
No, I want to use collapse, but at the same time, I want to use nz-switch on the collapse's title propertie,When I click on nz-switch , I don't let collpse expand，Can you understand what I mean
