### ISSUE TITLE
优化：开启 fullTemplateTypeCheck 后无法编译

### ISSUE THREAD

**Issue by cipchk** [NG-ZORRO/ng-zorro-antd#909]
## 示例

像 [nz-menu-item.component.ts](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/menu/nz-menu-item.component.ts#L58)：

```ts
  @HostListener('click', [ '$event' ])
  _onClickItem(): void {
  }
```

 指定参数 `$event` 必须在方法体内也指定，一个正确的写法：

```ts
  @HostListener('click', [ '$event' ])
  _onClickItem(event: KeyboardEvent): void {
  }
```

或

```ts
  @HostListener('click')
  _onClickItem(): void {
  }
```

**Comment by vthinkxie** [comment]
close
ref https://github.com/NG-ZORRO/ng-zorro-antd/pull/2134
