### ISSUE TITLE
transfer控件，目前只能在 OnInit() 时设置数据源，无法通过 Http 获取

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd#910]
## What problem does this feature solve?

可以通过 http 获取 transfer 数据源的值

## What does the proposed API look like?

模板：
`<nz-transfer [nzDataSource]="list">`

获取数据源：
`this.http.get().subscribe(res=>this.list = res);`

**Comment by cipchk** [comment]
[Demo](https://stackblitz.com/edit/ng-zorro-antd-issue-910?file=app/app.component.ts)，并无问题。

**Comment by niunai007** [comment]
不要用foreach来做循环。。得用for。。。明显的BUG

**Comment by dusdong** [comment]
@cipchk 
我原先无效的代码是这样写的：
```
this.http.get(...).subscribe(res=>{
    res.data.forEach(item=>{
        this.list.push({...});
    });
});
```
然后按照示例改成这样的就好使了：
```
this.http.get(...).subscribe(res=>{
    const ls: any[] = [];
    res.data.forEach(item=>{
        ls.push({...});
    });
    this.list = [...ls];
});
```
为什么不能直接操作 this.list 呢？而是需要通过   this.list = [...ls];  的方式？

**Comment by dusdong** [comment]
好的，非常感谢！
