### ISSUE TITLE
 , i hope to clear nz-select 's content  and nzPlacehOlder 

### ISSUE THREAD

**Issue by dzh145** [NG-ZORRO/ng-zorro-antd#912]
## What problem does this feature solve?

this is my code , i hope to clear nz-select 's content  and nzPlacehOlder by clicking the button,  Now I've done it through an empty array, but no way
```html
<nz-select  [(ngModel)]="varStartFacilities" id="txtStartFacilities"
                              [nzSize]="'large'" (nzSearchChange)="startStationClick($event)"
                              [nzPlaceHolder]="'请输入名称'"
                              [nzFilter]="false"
                              nzShowSearch
                              style="max-width: 287px; width: 100%;"  >
                    <nz-option   *ngFor="let cc of startStationData" (click)="clickMustStation(ss)"  [nzLabel]="cc.FULL_NAME" [nzValue]="cc.ID" >
                      <ng-template #nzOptionTemplate>
                        <i class="anticon anticon-flag" (click)="clickStartStation(cc)"></i>&nbsp;
                        <a  (click)="clickStartStation(cc)" >
                          {{cc.FULL_NAME}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br/>
                          <p style="color: darkgrey" (click)="clickStartStation(cc)">
                            <i class="anticon anticon-tool" (click)="clickStartStation(cc)"></i>&nbsp;
                            {{cc.STATION_TYPE}}
                          </p>
                        </a>
                      </ng-template>
                    </nz-option>
                  </nz-select>
```
## What does the proposed API look like?

this is my code , i hope to clear nz-select 's content  and nzPlacehOlder by clicking the button,  Now I've done it through an empty array, but no way

<nz-select  [(ngModel)]="varStartFacilities" id="txtStartFacilities"
                              [nzSize]="'large'" (nzSearchChange)="startStationClick($event)"
                              [nzPlaceHolder]="'请输入名称'"
                              [nzFilter]="false"
                              nzShowSearch
                              style="max-width: 287px; width: 100%;"  >
                    <nz-option   *ngFor="let cc of startStationData" (click)="clickMustStation(ss)"  [nzLabel]="cc.FULL_NAME" [nzValue]="cc.ID" >
                      <ng-template #nzOptionTemplate>
                        <i class="anticon anticon-flag" (click)="clickStartStation(cc)"></i>&nbsp;
                        <a  (click)="clickStartStation(cc)" >
                          {{cc.FULL_NAME}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br/>
                          <p style="color: darkgrey" (click)="clickStartStation(cc)">
                            <i class="anticon anticon-tool" (click)="clickStartStation(cc)"></i>&nbsp;
                            {{cc.STATION_TYPE}}
                          </p>
                        </a>
                      </ng-template>
                    </nz-option>
                  </nz-select>

**Comment by vthinkxie** [comment]
Hi @dzh145 please read the doc and angular doc carefully, we do not accept the usage questions of angular here.
