### ISSUE TITLE
关于ng-zorro打包后会导致文件很大的问题

### ISSUE THREAD

**Issue by Charles953** [NG-ZORRO/ng-zorro-antd#916]
比如nz-datepicker组件依赖了第三方包moment，打包时moment的语言包也压缩进去了，导致压缩完后文件过大
就是能否做成需要依赖该包时再去npm install

**Comment by vthinkxie** [comment]
@Charles953 the datepicker and timepicker and calendar all based on moment, they can not work without it.

**Comment by Charles953** [comment]
understood.
thanks

**Comment by gItSpLasHeR** [comment]
@vthinkxie  is the dependency of moment removed in the latest release? referring the issue #761

**Comment by vthinkxie** [comment]
@gItSpLasHeR 0.7.0 in in progress, and it won't be released very soon.
