### ISSUE TITLE
How to Fix column of nz-table?

### ISSUE THREAD

**Issue by KunerRick** [NG-ZORRO/ng-zorro-antd#922]
## What problem does this feature solve?

I have 10~20 columns to show，when the total width of table is fixed, these columns are all packed together.  I found  "nzScroll ", but It seems to fix the header only。

## What does the proposed API look like?

NOW : nzScroll : {y:300}
I wish that when set  just like "nzScroll : {x:900,y:240}" ,scrolls in both x and y directions of table  are supported. " ant design of react " seems to have this feature.

**Comment by vthinkxie** [comment]
it will be released in 0.7.0 version
