### ISSUE TITLE
how to close this log ,like G6

### ISSUE THREAD

**Issue by xingkoo** [NG-ZORRO/ng-zorro-antd#923]
hi,
website send https://kcart.alipay.com/web/bi.do a message.but it very slow.
i want to close it.
use G6.track(false) in G6, how to close in ng-zorro?

**Comment by vthinkxie** [comment]
@xingkoo our lib won't track user info, you can check the web inspector when you visit https://ng.ant.design/#/docs/angular/introduce

**Comment by xingkoo** [comment]
have a request.
Request URL:https://kcart.alipay.com/web/bi.do?BIProfile=merge&d=%5B%7B%22pg%22%3A%22http%3A%2F%2Flocalhost%3A4200%2F%23%2Fworkplace%22%2C%22r%22%3A1516442751603%2C%22g2%22%3Atrue%2C%22version%22%3A%223.0.2-beta.1%22%2C%22page_type%22%3A%22syslog%22%7D%5D

**Comment by vthinkxie** [comment]
@xingkoo you can look deep into the source code, there is no tracking code at all.
