### ISSUE TITLE
nz-upload default upload request can not be intercepted by the HttpInterceptor

### ISSUE THREAD

**Issue by jaydonshi** [NG-ZORRO/ng-zorro-antd#926]
## Version

0.6.11

## Environment

Windows 10, Google Chrome 63, ng-zorro 0.6.11

## Reproduction link

[https://ng-zorro.github.io/#/components/upload](https://ng-zorro.github.io/#/components/upload)

## Steps to reproduce

1. import HttpClientModule in the AppModule
2. provide a HttpInterceptor in the AppModule so it can be injected anywhere
3. use nz-upload in sub modules
4. upload a file

## What is expected?

upload request  should be intercepted by the HttpInterceptor

## What is actually happening?

upload request was not intercepted by the HttpInterceptor

## Other?

我的项目中使用HttpInterceptor来统一为请求加authorithation header，但是子模块使用nz-upload后发现上传的请求并没有被拦截器拦截到。查了一些资料并且看了下nz-upload的源码，原因可能是多次import HttpClientModule引起的。我的项目根模块中会import HttpClientModule和注册拦截器。而nz-upload的模块中也import 了HttpClientModule。虽然可以在使用nz-upload中重新提供拦截器，也能达到目的。但我的想法是这种项目中公用的功能最好还是能保持单例。不知道有没有更好的解决办法和建议？

**Comment by vthinkxie** [comment]
@cipchk

**Comment by cipchk** [comment]
的确如此，我会将 `HttpClientModule` 从 `NzUploadModel` 移除。
