### ISSUE TITLE
bug: nz-select [nzMode='tabs'] enter a duplicates, the before option will be removed

### ISSUE THREAD

**Issue by HsuanXyz** [NG-ZORRO/ng-zorro-antd#929]
## Version

0.6.11

## Environment

*

## Reproduction link

[http://plnkr.co/edit/Db2qq1O2NjyrS35i5gsO?p=preview](http://plnkr.co/edit/Db2qq1O2NjyrS35i5gsO?p=preview)

## Steps to reproduce

1. input `'A'`  <kbd>enter</kbd>
2. input `'A'`  again  <kbd>enter</kbd>

## What is expected?

keep a 'A'

## What is actually happening?

they are all removed

**Comment by gin-lsl** [comment]
enter 'A' then 'a' too

**Comment by vthinkxie** [comment]
resolved in 0.7.0
