### ISSUE TITLE
I using the nz-table,when I click the column, i want to change the current column's color

### ISSUE THREAD

**Issue by dzh145** [NG-ZORRO/ng-zorro-antd#930]
## What problem does this feature solve?

I using the nz-table,when I click the column, i want to change the current column's color

## What does the proposed API look like?

I using the nz-table,when I click the column, i want to change the current column's color

**Comment by vthinkxie** [comment]
use (click) they are all provided by default angular

**Comment by dzh145** [comment]
How do i to use,?

**Comment by vthinkxie** [comment]
how can you highlight an div in angular? it is the same in the table
