### ISSUE TITLE
升级到0.6.11后 设置的HttpInterceptor跨module会失效

### ISSUE THREAD

**Issue by xioxin** [NG-ZORRO/ng-zorro-antd#934]
## Version

0.6.11

## Environment

macos 10.13.3 chrome 65.0.3322.3 ng-zorro 0.6.11

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-w9xtqj](https://stackblitz.com/edit/ng-zorro-antd-setup-w9xtqj)

## Steps to reproduce

ng-zorro-antd: 0.6.11 https://stackblitz.com/edit/ng-zorro-antd-setup-w9xtqj

ng-zorro-antd: 0.6.10 https://stackblitz.com/edit/ng-zorro-antd-setup-g9hh9v

分别访问两个页面 点击"button2"

在**0.6.11**下 "button2" 触发的http请求**不经过**HttpInterceptor

在**0.6.10**下 "button2" 触发的http请求**经过**HttpInterceptor

两个代码一样 仅 ng-zorro-antd 版本不同

## What is expected?

 均触发HttpInterceptor中的方法

## What is actually happening?

未触发

**Comment by vthinkxie** [comment]
will hot fix today
