### ISSUE TITLE
nz-Cascader的nzShowSearch参数无效

### ISSUE THREAD

**Issue by mianxiaoqian** [NG-ZORRO/ng-zorro-antd#940]
## Version

0.6.9

## Environment

最新

## Reproduction link

[https://ng-zorro-antd-setup-44qmr3.stackblitz.io](https://ng-zorro-antd-setup-44qmr3.stackblitz.io)

## Steps to reproduce

设置nz-cascader组件的nzShowSearch为true

## What is expected?

组件的输入框可以进行输入搜索

## What is actually happening?

组件无法进行输入只能进行选择

**Comment by vthinkxie** [comment]
nz-cascader will be totally rewrite in version 0.7.0

**Comment by lycHub** [comment]
hi! I have the same problem.  When will the 0.7 version be released

**Comment by vthinkxie** [comment]
you can track https://github.com/NG-ZORRO/ng-zorro-antd/tree/0.7.0 for more detail
