### ISSUE TITLE
want to control disabled or not for button by true or false

### ISSUE THREAD

**Issue by lishaoh** [NG-ZORRO/ng-zorro-antd#943]
## What problem does this feature solve?

想通过true 或 false控制button是否能点击

## What does the proposed API look like?

<button [nzDisabled]="!isEdit"> </button>

**Comment by vthinkxie** [comment]
`<button [attr.disabled]="!isEdit">`

**Comment by lishaoh** [comment]
it doesn't work

**Comment by vthinkxie** [comment]
try again, it is a basic angular knowledge, please do not ask these questions here, you can get answers in stackoverflow or segmentfault.
