### ISSUE TITLE
I hope the nz-table component supports the column's resize feature 

### ISSUE THREAD

**Issue by lanmolsz** [NG-ZORRO/ng-zorro-antd#946]
## What problem does this feature solve?

This feature is very useful and difficult to achieve！

## What does the proposed API look like?

<nz-table #contentTable  [nzResize]="true"></nz-table>

**Comment by vellengs** [comment]
https://github.com/ant-design/ant-design/issues/4207
ant no plan for this, so no plan for this right?

**Comment by vthinkxie** [comment]
yes, no plan for this, we will sync with antd react.
