### ISSUE TITLE
Menu inline collapsed init error

### ISSUE THREAD

**Issue by xunjianxiang** [NG-ZORRO/ng-zorro-antd#949]
## Version

0.6.12

## Environment

ng-zorro: 0.6.12

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-udqw9g?file=app%2Fapp.component.html](https://stackblitz.com/edit/ng-zorro-antd-setup-udqw9g?file=app%2Fapp.component.html)

## Steps to reproduce

点击菜单第二项

## What is expected?

Menu inline 模式收起的正常展现

## What is actually happening?

展现异常

**Comment by vthinkxie** [comment]
will be fixed in next version.
