### ISSUE TITLE
There is a serious bug in the style

### ISSUE THREAD

**Issue by smile2014** [NG-ZORRO/ng-zorro-antd#953]
## Version

0.6.12

## Environment

WIN10、Chrome、0.6.11

## Reproduction link

[https://stackblitz.com/edit/angular-oprfhy](https://stackblitz.com/edit/angular-oprfhy)

## Steps to reproduce

There is a serious bug in the style. If you put multiple Inputs in a row and use data validation, all the input values in the first row will be emptied one by one, and the entire page layout will be in disorder

## What is expected?

The effect of the interface is opened

## What is actually happening?

The effect of the interface is opened

**Comment by vthinkxie** [comment]
all `nz-col`'s `nzSpan` in a `nz-row` can not more than 24, please check your code.

**Comment by smile2014** [comment]
If all nz-col's nzSpan in a nz-row more than 24, I opened the interface when dislocation
我检查过了，没有，如果有我界面打开的时候就错位了。

**Comment by vthinkxie** [comment]
![image](https://user-images.githubusercontent.com/1506722/35311384-3527ed3e-00f1-11e8-84c9-8554c2d60ca5.png)
check it again.

**Comment by smile2014** [comment]
谢谢了。懂你说的了，只是这种如果动态表单就很有局限性了。

**Comment by smile2014** [comment]
@vthinkxie  你的做的searchForm也是这样的

**Comment by vthinkxie** [comment]
@smile2014 `ng-alain` is not an official project, you can submit an issue at https://github.com/cipchk/ng-alain

**Comment by smile2014** [comment]
@vthinkxie   样式上的bug ，加上这个就OK了margin-bottom:6px; height: 40px; 
<div nz-form-item nz-col [nzSpan]="to.divCol" style="margin-bottom:6px; height: 40px;">

**Comment by vthinkxie** [comment]
it is not a bug, we do not support the usage like that, there will be more so called bugs if you do not follow the doc
