### ISSUE TITLE
nzShowQuickJumper

### ISSUE THREAD

**Issue by cicilalala** [NG-ZORRO/ng-zorro-antd#954]
## What problem does this feature solve?

when i changed the pageindex in quickjumper box, nzPageIndexChange function triggered too frequent,for example,if i want to jump to 23,but when i input the number,it will trigger the  nzPageIndexChange funtion  twice,2 and 23

## What does the proposed API look like?

Can i add a debounceTime when i change the pageindex in quickjumper box?

**Comment by vthinkxie** [comment]
fixed in version 0.7.0
