### ISSUE TITLE
nz-rangepicker控件是否提供了回调方法

### ISSUE THREAD

**Issue by YouToBeYourself** [NG-ZORRO/ng-zorro-antd#956]
问题：在使用nz-rangepicker控件后，我想在选完时间范围后执行某个方法（携带最新选中的值），这里是否有提供回调方法，在查阅官方文档没有找到相应的回调方法。

**Comment by YouToBeYourself** [comment]
Problem: when using the nz-rangepicker component, I want to execute a callback method after selected. (bring the latest selected value). Is there a callback method provided here? There is no callback method found in the official documents.

**Comment by vthinkxie** [comment]
do you kown ngModelChange?

**Comment by YouToBeYourself** [comment]
I know it, but it's not working!

**Comment by soulxy** [comment]
@YouToBeYourself 
Force update the range array in `ngModelChange` function ，it worked.
