### ISSUE TITLE
NzModal :  click 'Mask' quickly , the callback 'onCancel 'is triggered twice, should only once

### ISSUE THREAD

**Issue by dknfeiov** [NG-ZORRO/ng-zorro-antd#958]
## Version

0.5.5

## Environment

windows7 chrome: 61.0.3163.79

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-giu6if?embed=1&file=app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-setup-giu6if?embed=1&file=app/app.component.ts)

## Steps to reproduce

1. click the button , the modal  is opened
2. quickly click the Mask , see the console , the onCancel is triggered twice, maybe more 

## What is expected?

the callback 'OnCancel' only be trigger once;

## What is actually happening?

the callback 'OnCancel' be triggered twice ;

**Comment by vthinkxie** [comment]
the modal will be rewrite totally in version 0.7.0 ref #920
