### ISSUE TITLE
nz-alert 的 [alert-description] 项定义后不显示

### ISSUE THREAD

**Issue by dusdong** [NG-ZORRO/ng-zorro-antd#960]
## Version

0.6.12

## Environment

chrome 63

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-alter-description?file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-alter-description?file=app/app.component.html)

## Steps to reproduce

```
<nz-alert [nzType]="'success'" [nzShowIcon]="true">
	<div alert-body>i am body</div>
	<div alert-description>i as description</div>
</nz-alert>
```
## What is expected?

显示 `<div alert-description>` 中的内容

## What is actually happening?

`<div alert-description>` 中的内容不显示

## Other?

`<div alert-body>` 可用

**Comment by vthinkxie** [comment]
will be fixed in next version, thanks for your feedback.
