### ISSUE TITLE
How to use Zorro's folding panels to make multilayer panels

### ISSUE THREAD

**Issue by mjn1154477982** [NG-ZORRO/ng-zorro-antd#961]
## What problem does this feature solve?

I want to make a multi-layer folding panel, but Zorro looks like only two layers, how do I do

## What does the proposed API look like?

panels = [
    {
      active: true,
      name: 'This is panel header 1',
      childPanel: [
        {
          active: false,
          name: 'This is panel header 1-1'，
          childPanel:[{name:'heloo'}]
        }
      ]
    },
    {
      active: false,
      name: 'This is panel header 2'
    },
    {
      active: false,
      name: 'This is panel header 3'
    }
  ];

**Comment by vthinkxie** [comment]
it has already support it. please read the doc carefully.
