### ISSUE TITLE
Can NzTable be generated by config like Antd for react ?

### ISSUE THREAD

**Issue by fuybooo** [NG-ZORRO/ng-zorro-antd#967]
## What problem does this feature solve?

When use nzTable, we needn't write more code to configure the repetition.

## What does the proposed API look like?

Use NzTable's API,just use table like &lt;nz-table [columns]="columns" ...otherConfig&gt;&lt;/nz-table&gt;

**Comment by vthinkxie** [comment]
http://ng-alain.com/components/simple-table you can use this
