### ISSUE TITLE
bug 无法结合Angular Universal使用

### ISSUE THREAD

**Issue by kywlw** [NG-ZORRO/ng-zorro-antd#975]
## Version

0.6.12

## Environment

0.6.12

## Reproduction link

[https://github.com/angular/universal/blob/master/README.md#universal-gotchas](https://github.com/angular/universal/blob/master/README.md#universal-gotchas)

## Steps to reproduce

NzGlobalMonitorService 里使用了原生的document对象。

## What is expected?

NzGlobalMonitorService 里使用了原生的document对象。

## What is actually happening?

NzGlobalMonitorService 里使用了原生的document对象。

## Other?

NzGlobalMonitorService 里使用了原生的document对象。

**Comment by vthinkxie** [comment]
duplicated #43
