### ISSUE TITLE
I want use nz-popconfirm on the input

### ISSUE THREAD

**Issue by dzh145** [NG-ZORRO/ng-zorro-antd#976]
## What problem does this feature solve?

I want use nz-popconfirm on the input,  but my input is dom created, this my code :
let input  = document.createElement("input");

so , i hope use nz-popconfirm on this input's onblur.  what should i do ??

## What does the proposed API look like?

I want use nz-popconfirm on the input,  but my input is dom created, this my code :
let input  = document.createElement("input");

so , i hope use nz-popconfirm on this input's onblur.  what should i do ??

**Comment by vthinkxie** [comment]
please read angular doc about how to create dynamic component carefully
