### ISSUE TITLE
Oh.i update my code

### ISSUE THREAD

**Issue by dzh145** [NG-ZORRO/ng-zorro-antd#977]
## What problem does this feature solve?

import {Component, ViewChild, OnInit, Input, Inject} from '@angular/core';
import {_HttpClient, SettingsService} from '@delon/theme';
import {DA_SERVICE_TOKEN, ITokenService} from '@delon/auth';
import {NzMessageService} from 'ng-zorro-antd';

@Component({
    selector: 'input-comfrimInput',
    template: `
        <nz-popconfirm [nzTitle]="'确定要删除这个任务吗？'"  (nzOnConfirm)="confirm()" (nzOnCancel)="cancel()" [nzPlacement]="'top'">
            <input nz-popconfirm type="text" />
        </nz-popconfirm>
    `
})

export class ComfrimInputComponent implements OnInit {
    ngOnInit() {
    }
    constructor(private http: _HttpClient,
                private settingService: SettingsService, private message: NzMessageService,
    @Inject(DA_SERVICE_TOKEN) private tokenService: ITokenService) {

    }

    confirm = () => {
        this.message.info('click confirm');
    };

    cancel = function () {
        this.message.info('click cancel');
    };
}
     
now.i want popup the nz-popconfirm on input's onblur
  
 

## What does the proposed API look like?

import {Component, ViewChild, OnInit, Input, Inject} from '@angular/core';
import {_HttpClient, SettingsService} from '@delon/theme';
import {DA_SERVICE_TOKEN, ITokenService} from '@delon/auth';
import {NzMessageService} from 'ng-zorro-antd';

@Component({
    selector: 'input-comfrimInput',
    template: `
        <nz-popconfirm [nzTitle]="'确定要删除这个任务吗？'"  (nzOnConfirm)="confirm()" (nzOnCancel)="cancel()" [nzPlacement]="'top'">
            <input nz-popconfirm type="text" />
        </nz-popconfirm>
    `
})

export class ComfrimInputComponent implements OnInit {
    ngOnInit() {
    }
    constructor(private http: _HttpClient,
                private settingService: SettingsService, private message: NzMessageService,
    @Inject(DA_SERVICE_TOKEN) private tokenService: ITokenService) {

    }

    confirm = () => {
        this.message.info('click confirm');
    };

    cancel = function () {
        this.message.info('click cancel');
    };
}
     
now.i want popup the nz-popconfirm on input's onblur

**Comment by vthinkxie** [comment]
<img width="910" alt="2018-01-27 10 14 03" src="https://user-images.githubusercontent.com/1506722/35472722-6c2ba648-03af-11e8-88ad-aa86747383ec.png">

**Comment by vthinkxie** [comment]
@dzh145 I hope you can understand, the issue function in github only used for tracking bugs and features, but not for helping people learn angular, the developers used issue list to keep the track bugs and mark the features to be developed in the future, 151 people will receive the notification when a new issue are submitted.
