### ISSUE TITLE
Provide an entry for the unified font-size to be set to 14px

### ISSUE THREAD

**Issue by fuybooo** [NG-ZORRO/ng-zorro-antd#984]
## What problem does this feature solve?

The default font size is 12px,I think it is too small,how to change it to 14px?

## What does the proposed API look like?

{provide: FONT_SIZE, useValue: MIDDLE_SIZE}

**Comment by fuybooo** [comment]
我下载下来最新的代码,将@font-size-base改为14px,然后执行npm run release 然后将生成的publish替换到项目中去.不知道这种做法对不对,期望得到答复! @afc163 @pjurczynski @hllinc @vthinkxie @etuncay

**Comment by vthinkxie** [comment]
@fuybooo this could work for current version, we will provide define theme less file in version 0.7.0.
duplicated #806
