### ISSUE TITLE
Can't bind to 'compareWith' since it isn't a known property of 'nz-select'.

### ISSUE THREAD

**Issue by patricknazar** [NG-ZORRO/ng-zorro-antd#985]
## Version

0.6.12

## Environment

Ubuntu, Chrome, ng-zorro 0.6.12, angular 5.2.1

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-nz-select-comparewith?file=app/app.component.html](https://stackblitz.com/edit/ng-zorro-antd-nz-select-comparewith?file=app/app.component.html)

## Steps to reproduce

This shouldn't have trouble compiling. Comment out the nz-select bit in the component template to see what it should do with the normal select.

## What is expected?

[compareWith] works

## What is actually happening?

Can't bind to 'compareWith' since it isn't a known property of 'nz-select'.

**Comment by vthinkxie** [comment]
will support in version 0.7.0
