### ISSUE TITLE
垂直菜单，子菜单内嵌在菜单区域

### ISSUE THREAD

**Issue by CoSaoyears** [NG-ZORRO/ng-zorro-antd#987]
## What problem does this feature solve?

如果里面有一个展开的 子菜单，直接关闭父菜单，在打开父菜单，此时子菜单 箭头不对，  需要点击二次才会展开子菜单内容

## What does the proposed API look like?

正常情况下不管点击那个节点， 都应该检查一下有没有子菜单  是打开的 ，如果是打开的应该关闭,
<li nz-submenu>
            <span title><i class="anticon anticon-appstore"></i> Navigation Two</span>
            <ul>
              <li nz-menu-item>Option 5</li>
              <li nz-submenu>
                <span title>Submenu</span>
                <ul>
                  <li nz-menu-item>Option</li>
                </ul>
              </li>
            </ul>
          </li>

**Comment by vthinkxie** [comment]
duplicated #607
