### ISSUE TITLE
Upload nzHeaders怎么用？

### ISSUE THREAD

**Issue by jiankian** [NG-ZORRO/ng-zorro-antd#991]
## What problem does this feature solve?

我用 new HttpHeaders().set('ann_token','token_string')和new Headers({ 'ann_token': 'token_string' });和直接用{'ann_token':'token_string'}都是报错

## What does the proposed API look like?

怎么才能在上传请求加入我要的headers呢，我看了源码找不到方法

**Comment by jiankian** [comment]
解决了 是(nzHeaders)="数据变量名称"而不是nzHeaders="{{数据变量}}"

**Comment by yonghp** [comment]
How did you solve it?
my code is it, please help me.

`(nzHeaders)="application/json"`

**Comment by zhouxy0809** [comment]
it works as follow: @yonghp 
[nzHeaders]="{'Content-Type': 'application/json'}"

**Comment by freezyh** [comment]
@zhouxy0809 请教下nzCustomRequest怎么使用的，还有就是文件上传成功后的回调函数如何使用，谢谢
