### ISSUE TITLE
nz-input-number did't show zero value

### ISSUE THREAD

**Issue by alexspring123** [NG-ZORRO/ng-zorro-antd#992]
## Version

0.6.12

## Environment

chrome

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-b38plx](https://stackblitz.com/edit/ng-zorro-antd-setup-b38plx)

## Steps to reproduce

did't show zero value

## What is expected?

show zero value

## What is actually happening?

did't show zero value

**Comment by vthinkxie** [comment]
will be fixed in next version.
