### ISSUE TITLE
transfer控件不使用nzSelectChange的时候checkbox没有正常联动

### ISSUE THREAD

**Issue by deart1mer** [NG-ZORRO/ng-zorro-antd#996]
## Version

0.6.13

## Environment

Mac / Chrome 63

## Reproduction link

[https://stackblitz.com/edit/angular-xhkjof?file=app%2Fnz-demo-transfer-basic.component.ts](https://stackblitz.com/edit/angular-xhkjof?file=app%2Fnz-demo-transfer-basic.component.ts)

## Steps to reproduce

选择所有 target 列表的 checkbox，target 的全选没有选中，取消掉一个之后，全选选中了
![transfer-bug](https://user-images.githubusercontent.com/10653243/35555257-8910bcfe-05d9-11e8-8bd3-278c8b6bf67c.gif)

## What is expected?

checkbox 正常联动

## What is actually happening?

选择所有 target 列表的 checkbox，target 的全选没有选中，取消掉一个之后，全选选中了

## Other?

这像是 Angular Form 模块 的一个 bug，在父组件使用 onPush 策略之后，自定义表单控件的子组件 writeValue 已经获取到最新的值，但是没有进行脏检查。
https://github.com/angular/angular/issues/21780

**Comment by cipchk** [comment]
可能是逻辑上处理有问题，我不太确定，我会核实一下，可能不是 Angular 的问题。

**Comment by cipchk** [comment]
的确非常奇怪，我可以排除逻辑上的问题；暂时先跟踪 Angular #21780。

**Comment by deart1mer** [comment]
可以考虑 nz-transfer 暂时先不使用 OnPush 做兼容处理

**Comment by cipchk** [comment]
其实好奇的是若指定 `nzSelectChange` 就正常；一头雾水。

**Comment by deart1mer** [comment]
我猜是因为 `nz-transfer` 的 `nzSelectChange`事件是从在 `nz-transfer-list` 里面，`<li *ngIf="!item._hiden" (click)="_handleSelect(item)" class="ant-transfer-list-content-item">` ， 中的 click 事件一路过来的，所以指定 `nzSelectChange ` 的话使得 markForCheck 发生在 `nz-transfer-list` 组件而不是 `nz-transfer` 组件？

**Comment by vthinkxie** [comment]
@deart1mer is right

**Comment by vthinkxie** [comment]
@cipchk please check if this bug was fixed in version 0.7.0
