### ISSUE TITLE
menu添加路由链接会加一个蓝色的边（浅色主题较明显）

### ISSUE THREAD

**Issue by MrLiSong** [NG-ZORRO/ng-zorro-antd#998]
## Version

0.6.10

## Environment

ng-zorro 0.6.10

## Reproduction link

[https://ng-zorro-antd-setup.stackblitz.io/data](https://ng-zorro-antd-setup.stackblitz.io/data)

## Steps to reproduce

没有添加路由链接时，正常
加上后，点击后会有一个边，和input聚焦时类似

## What is expected?

点击后不要边

## What is actually happening?

点击后存在边

**Comment by vthinkxie** [comment]
please provide an valid reproduce link, or we can not help you

**Comment by mashuai333** [comment]
0.6.15 has same question ,if we have added 'routerLink', this 'li' will has a blue border

**Comment by deepthan** [comment]
in chrome, this element will has a blue border when it focus, so add this to your css will resolve it.
```
ul li,
div,
ol li {
  &:focus {
    outline: 0;
  }
}
```
